{
  "hash": "d65c9745653a38d6c994129b5b6a9e42",
  "result": {
    "markdown": "---\ntitle: \"Final Project - Check point 1\"\nauthor: \"Felix Betanourt\"\ndesription: \"DACSS 603 Final Project\"\ndate: \"03/18/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - finalpart1\n  - final project\n  - burnout\n  - employee burnout\n  - descriptives\n  - Research question\n  - hyphoteses\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning = FALSE)\n```\n:::\n\n\n\n### **Burnout in the workplace**.\n\nDACSS 603, Spring 2023\n\nBurnout is a pervasive issue in many professions, and its consequences can be significant for individuals and organizations alike. According to Maslach and Leiter (2016), burnout is characterized by emotional exhaustion, despersonalization, and reduced personal accomplishment. It is prevalent in a variety of fields, including healthcare (West et al., 2016), among other professions. Burnout can have serious consequences, including decreased job satisfaction, increased absenteeism, and turnover (West et al., 2016).\n\nThere is a growing body of research exploring the causes and consequences of burnout, as well as potential solutions. Some scholars have identified factors such as job demands, lack of control, and social support as contributing to burnout (Bakker & Demerouti, 2017).\n\nLee & Eissenstat (2017), for instance, affirm that psychological job demands and work-to-family conflict, as well as control over working hours/schedule, decision-making authority, and role clarity, have significant effects on burnout.\n\nThe aim of this research paper is to provide a comprehensive understanding of how type of business, and seniority level explain the level of burnout.\n\n**Null hypothesis**: The type of business, and seniority does not affect the burnout rate.\n\n**Alternative hypotheses**:\n\n1.  Working in Services (vs product type of business) predict significantly higher burnout rate, especially in Female workers.\n\n2.  Less years of experience (lower seniority) is significantly related to higher burnout rate.\n\n3.  The numbers of work hours allocated affect the burnout rate significantly in WFH setup (vs on site).\n\n\n### **About the Data**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Loading packages\n\nsuppressPackageStartupMessages(library(dplyr))\nsuppressPackageStartupMessages(library(tidyverse))\n\n# Reading the data.\n\nburn <- read.csv(\"_data/burnout.csv\")\n```\n:::\n\n\nThe dataset was obtained from:\n\nhttps://www.kaggle.com/datasets/blurredmachine/are-your-employees-burning-out\n\nLet's check the strucutre of the dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Structure\nstr(burn)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t22750 obs. of  9 variables:\n $ Employee.ID         : chr  \"fffe32003000360033003200\" \"fffe3700360033003500\" \"fffe31003300320037003900\" \"fffe32003400380032003900\" ...\n $ Date.of.Joining     : chr  \"2008-09-30\" \"2008-11-30\" \"2008-03-10\" \"2008-11-03\" ...\n $ Gender              : chr  \"Female\" \"Male\" \"Female\" \"Male\" ...\n $ Company.Type        : chr  \"Service\" \"Service\" \"Product\" \"Service\" ...\n $ WFH.Setup.Available : chr  \"No\" \"Yes\" \"Yes\" \"Yes\" ...\n $ Designation         : num  2 1 2 1 3 2 3 2 3 3 ...\n $ Resource.Allocation : num  3 2 NA 1 7 4 6 4 6 6 ...\n $ Mental.Fatigue.Score: num  3.8 5 5.8 2.6 6.9 3.6 7.9 4.4 NA NA ...\n $ Burn.Rate           : num  0.16 0.36 0.49 0.2 0.52 0.29 0.62 0.33 0.56 0.67 ...\n```\n:::\n:::\n\nThe dataset contain 9 variables and 22750 observations.\n\nFour of the variables are categorical and five are numeric (including one as date)\n\nLet's see a Summary for each variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(burn)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Employee.ID        Date.of.Joining       Gender          Company.Type      \n Length:22750       Length:22750       Length:22750       Length:22750      \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n WFH.Setup.Available  Designation    Resource.Allocation Mental.Fatigue.Score\n Length:22750        Min.   :0.000   Min.   : 1.000      Min.   : 0.000      \n Class :character    1st Qu.:1.000   1st Qu.: 3.000      1st Qu.: 4.600      \n Mode  :character    Median :2.000   Median : 4.000      Median : 5.900      \n                     Mean   :2.179   Mean   : 4.481      Mean   : 5.728      \n                     3rd Qu.:3.000   3rd Qu.: 6.000      3rd Qu.: 7.100      \n                     Max.   :5.000   Max.   :10.000      Max.   :10.000      \n                                     NA's   :1381        NA's   :2117        \n   Burn.Rate    \n Min.   :0.000  \n 1st Qu.:0.310  \n Median :0.450  \n Mean   :0.452  \n 3rd Qu.:0.590  \n Max.   :1.000  \n NA's   :1124   \n```\n:::\n:::\n\n\nAccording to the source of the data, here is an explanation of each variable:\n\nEmployee ID: The unique ID allocated for each employee.\n\nDate of Joining: The date-time when the employee has joined the organization.\n\nGender: The gender of the employee\n\nCompany Type: The type of company where the employee is working\n\nWFH Setup Available: Is the work from home facility available for the employee\n\nDesignation: The designation of the employee of work in the organization. In the range of \\[0.0, 5.0\\] bigger is higher designation.\n\nResource Allocation: The amount of resource allocated to the employee to work, ie. number of working hours.In the range of \\[1.0, 10.0\\] (higher means more resource)\n\nMental Fatigue Score: The level of fatigue mentally the employee is facing.In the range of \\[0.0, 10.0\\] where 0.0 means no fatigue and 10.0 means completely fatigue.\n\nBurn Rate: The value we need to predict for each employee telling the rate of Bur out while working.In the range of \\[0.0, 1.0\\] where the higher the value is more is the burn out.\n\n\n### **References**:\n\nBakker, A. B., & Demerouti, E. (2017). Job demands-resources theory: Taking stock and looking forward. Journal of Occupational Health Psychology, 22(3), 273--285.\n\nLee, Y., Eissenstat, S. (2017). A longitudinal examination of the causes and effects of burnout based on the job demands-resources model. International Journal for Educational and Vocational Guidance, 18(3), 337--354.\n\nMaslach, C., & Leiter, M. P. (2016). Understanding the burnout experience: Recent research and its implications for psychiatry. World Psychiatry, 15(2), 103--111.\n\nWest, C. P., Dyrbye, L. N., Erwin, P., Shanafelt, T. D., (2016). Interventions to promote physician well-being and mitigate burnout: A systematic review and meta-analysis. The Lancet, 388(10057), 2272--228\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}