{
  "hash": "1825e2622b48fe69ca3ecf002b27489d",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Guanhua Tan\"\ndescription: \"Homework 1\"\ndate: \"02/05/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n\n# Question 1\n\n## a)\n\nFirst, let's read in the data from the Excel file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\ndf <- read_excel(\"_data/LungCapData.xls\")\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n  LungCap   Age Height Smoke Gender Caesarean\n    <dbl> <dbl>  <dbl> <chr> <chr>  <chr>    \n1    6.48     6   62.1 no    male   no       \n2   10.1     18   74.7 yes   female no       \n3    9.55    16   69.7 no    female yes      \n4   11.1     14   71   no    male   no       \n5    4.8      5   56.9 no    male   no       \n6    6.22    11   58.7 no    female no       \n```\n:::\n:::\n\n\nThe distribution of LungCap looks as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df$LungCap)\n```\n\n::: {.cell-output-display}\n![](HW1_Guanhua_Tan_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe histogram suggests that the distribution is close to a normal distribution. Most of the observations are close to the mean. Very few observations are close to the margins (0 and 15).\n\n## b)  Compare the probability distribution of the LungCap with respect to Males and Females?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  ggplot(aes(x=Gender,y=LungCap))%+%\n  stat_boxplot(geom = \"errorbar\", # Error bars\n               width = 0.2)+\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](HW1_Guanhua_Tan_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe box graphic suggests that the median of male lung capacities are slightly larger than the one of female ones.\n\n## c)  Compare the mean lung capacities for smokers and non-smokers. Does it make sense?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_c <- df %>%\n  group_by(Smoke) %>%\n  mutate(mean_lungcap=mean(LungCap))%>%\n  distinct(mean_lungcap)\ndf_c \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n# Groups:   Smoke [2]\n  Smoke mean_lungcap\n  <chr>        <dbl>\n1 no            7.77\n2 yes           8.65\n```\n:::\n:::\n\n\nThe data indicates smokers' lung capacities are larger than no-smokers' ones. It runs counter to the intuition.\n\n## d)  Examine the relationship between Smoking and Lung Capacity within age groups: \"less than or equal to 13\", \"14 to 15\", \"16 to 17\", and \"greater than or equal to 18\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# less than or equal to 13\ndf_d_13<-df %>%\n  filter(Smoke == \"yes\" & Age <= 13) %>%\n  mutate(mean_lungcap=mean(LungCap)) %>%\n  distinct(mean_lungcap)\n\n\ndf_d_14_15 <-df %>%\n   filter(Smoke == \"yes\" & Age <= 15 | Age >= 14) %>%\n  mutate(mean_lungcap=mean(LungCap)) %>%\n  distinct(mean_lungcap)\n\n\ndf_d_16_17 <-df %>%\n   filter(Smoke == \"yes\" & Age <= 17 | Age >= 16) %>%\n  mutate(mean_lungcap=mean(LungCap)) %>%\n  distinct(mean_lungcap)\n\n\ndf_d_18 <-df %>%\n   filter(Smoke == \"yes\" & Age >= 18) %>%\n  mutate(mean_lungcap=mean(LungCap)) %>%\n  distinct(mean_lungcap)\nresult <-c(df_d_13, df_d_14_15, df_d_16_17, df_d_18)\nprint(result)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$mean_lungcap\n[1] 7.201852\n\n$mean_lungcap\n[1] 9.725077\n\n$mean_lungcap\n[1] 10.00616\n\n$mean_lungcap\n[1] 10.51333\n```\n:::\n:::\n\n\nThe data indicates that with the increase of the age, the lung capacities grows larger.\n\n## e)  Compare the lung capacities for smokers and non-smokers within each age group. Is your answer different from the one in part c. What could possibly be going on here?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_e_13<-df %>%\n  filter(Age <= 13) %>%\n  group_by(Smoke) %>%\n  mutate(mean_lungcap=mean(LungCap)) %>%\n  distinct(mean_lungcap)\n\ndf_e_14<-df %>%\n  filter(Age == 15 | Age == 14) %>%\n  group_by(Smoke) %>%\n  mutate(mean_lungcap=mean(LungCap)) %>%\n  distinct(mean_lungcap)\n\n\ndf_e_16<-df %>%\n  filter(Age == 17 | Age == 16) %>%\n  group_by(Smoke) %>%\n  mutate(mean_lungcap=mean(LungCap)) %>%\n  distinct(mean_lungcap)\n\n\ndf_e_18<-df %>%\n  filter( Age >= 18) %>%\n  group_by(Smoke) %>%\n  mutate(mean_lungcap=mean(LungCap)) %>%\n  distinct(mean_lungcap)\n\ndf_e_13\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n# Groups:   Smoke [2]\n  Smoke mean_lungcap\n  <chr>        <dbl>\n1 no            6.36\n2 yes           7.20\n```\n:::\n\n```{.r .cell-code}\ndf_e_14\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n# Groups:   Smoke [2]\n  Smoke mean_lungcap\n  <chr>        <dbl>\n1 no            9.14\n2 yes           8.39\n```\n:::\n\n```{.r .cell-code}\ndf_e_16\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n# Groups:   Smoke [2]\n  Smoke mean_lungcap\n  <chr>        <dbl>\n1 no           10.5 \n2 yes           9.38\n```\n:::\n\n```{.r .cell-code}\ndf_e_18\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n# Groups:   Smoke [2]\n  Smoke mean_lungcap\n  <chr>        <dbl>\n1 yes           10.5\n2 no            11.1\n```\n:::\n:::\n\n\nThe shows a big difference from the part C. Only in age group under 13, smokers have larger lung capacities than non-smokers. In other age groups, unlike what the part C suggests, non-smokers have large lung capacities that smokers.\n\n# Question2\n2.  Let X = number of prior convictions for prisoners at a state prison at which there are 810 prisoners.\n\n<!-- -->\n\n## a)  What is the probability that a randomly selected inmate has exactly 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc <- 160/810\nc\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1975309\n```\n:::\n:::\n\n\nThe probability is 19.8%.\n\n## b)  What is the probability that a randomly selected inmate has fewer than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc<-(128+434)/810\nc\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\n\nThe probability is 69.4%.\n\n## c)  What is the probability that a randomly selected inmate has 2 or fewer prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc <- (434+160+128)/810\nc\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\n\nThe probability is 89.1%.\n\n## d)  What is the probability that a randomly selected inmate has more than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc<-(64+24)/810\nc\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\n\nThe probability is 10.9%.\n\n## e)  What is the expected value1 for the number of prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvals<-c(0,1,2,3,4)\nprobs<-c(128/810, 434/810, 160/810, 64/801, 24/810)\nexv<-weighted.mean(vals, probs)\nexv\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28794\n```\n:::\n:::\n\n\nThe expected value is 1.29.\n\nf)  Calculate the variance and the standard deviation for the Prior Convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar <- sum((vals-exv)^2*probs)\nvar\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8588399\n```\n:::\n\n```{.r .cell-code}\nsd <- sqrt(var)\nsd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9267361\n```\n:::\n:::\n\n\nThe variance is 0.8588. The standard deviation is 0.9267.\n",
    "supporting": [
      "HW1_Guanhua_Tan_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}