{
  "hash": "379645c6d8579cd515aec7d51c247f6b",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Justine Shakespeare\"\ndescription: \"Homework 1 for DACSS 603\"\ndate: \"02/26/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - Justine Shakespeare\n  - descriptive statistics \n  - probability\n---\n\n\n# Question 1\n\nWe start by loading the appropriate packages and reading in the data from the Excel file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   1.0.1 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.3.0      ✔ stringr 1.5.0 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\ndf <- read_excel(\"_data/LungCapData.xls\")\n```\n:::\n\n\nWe can use the glimpse() function to take a look at the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 725\nColumns: 6\n$ LungCap   <dbl> 6.475, 10.125, 9.550, 11.125, 4.800, 6.225, 4.950, 7.325, 8.…\n$ Age       <dbl> 6, 18, 16, 14, 5, 11, 8, 11, 15, 11, 19, 17, 12, 10, 10, 13,…\n$ Height    <dbl> 62.1, 74.7, 69.7, 71.0, 56.9, 58.7, 63.3, 70.4, 70.5, 59.2, …\n$ Smoke     <chr> \"no\", \"yes\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\",…\n$ Gender    <chr> \"male\", \"female\", \"female\", \"male\", \"male\", \"female\", \"male\"…\n$ Caesarean <chr> \"no\", \"no\", \"yes\", \"no\", \"no\", \"no\", \"yes\", \"no\", \"no\", \"no\"…\n```\n:::\n:::\n\n\nThis shows that this dataset has 725 observations (rows) and 6 variables (columns). The first three columns are labeled: LungCap, Age, and Height and they are all classified as double, which is a type of numeric variable. The last three columns are Smoke, Gender, and Caesarean, which are all classified as character variables. LungCap refers to the lung capacity of the person, Age, Height, and Gender all describe the relevant characteristics of that person. Smoke is a dichotomous variable which records whether a person smokes or not. Caesarean is also a dichotomous variable that reflects whether a person was born by a caesaren or not. \n\n\n## 1a. \nThe distribution of the LungCap variable looks as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df$LungCap)\n```\n\n::: {.cell-output-display}\n![](HW1_JustineShakespeare_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe histogram suggests that the distribution is close to a normal distribution. Most of the observations are close to the mean.\n\n## 1b.\nWe can use the boxplot function to compare the distribution of the LungCap variable with respect to males and females. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(LungCap ~ Gender, data=df)\n```\n\n::: {.cell-output-display}\n![](HW1_JustineShakespeare_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## 1c.\nBy using pipes, the group_by() and the summarize() functions we can take a look at the mean lung capacity of smokers and non-smokers. The results are counter-intuitive: it looks as though the mean lung capacity for those who smoke is larger than those who do not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% \n  group_by(Smoke) %>% \n  summarize(\"Mean_LungCap\"=mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke Mean_LungCap\n  <chr>        <dbl>\n1 no            7.77\n2 yes           8.65\n```\n:::\n:::\n\n\n## 1d. & 1e\nTo examine the relationship between smoking and lung capacity within age groups we can use the mutate() and case_when() functions and piping to create an ordinal variable that captures different age groups:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>% \n  mutate(AgeGroups = case_when(\n    Age<=13 ~ \"a. Less than or equal to 13\",\n    Age==14 | Age==15 ~ \"b. 14 or 15\", \n    Age==16 | Age==17 ~ \"c. 16 or 17\",\n    Age>=18 ~ \"d. Greater than or equal to 18\"))\n```\n:::\n\n\nWith this new variable we can more easily compare the lung capacities for smokers and non-smokers within each age group. The following tables show the mean lung capacity for study subjects arranged by age group, first for those who reported not smoking and second for those who did report smoking:\n\n#### Lung capacity by age for NON-SMOKERS:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(df, Smoke==\"no\") %>% \n  group_by(AgeGroups) %>% \n  summarize(\"Mean_LungCap\"=mean(LungCap)) %>% \n  arrange(AgeGroups)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n  AgeGroups                      Mean_LungCap\n  <chr>                                 <dbl>\n1 a. Less than or equal to 13            6.36\n2 b. 14 or 15                            9.14\n3 c. 16 or 17                           10.5 \n4 d. Greater than or equal to 18        11.1 \n```\n:::\n:::\n\n\n#### Lung capacity by age for SMOKERS:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(df, Smoke==\"yes\") %>% \n  group_by(AgeGroups) %>% \n  summarize(\"Mean_LungCap\"=mean(LungCap)) %>% \n  arrange(AgeGroups)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n  AgeGroups                      Mean_LungCap\n  <chr>                                 <dbl>\n1 a. Less than or equal to 13            7.20\n2 b. 14 or 15                            8.39\n3 c. 16 or 17                            9.38\n4 d. Greater than or equal to 18        10.5 \n```\n:::\n:::\n\n\nThis data shows that lung capacity generally increases with age. \n\nIt is interesting to note that on average all age groups that did not smoke had a higher lung capacity *except* for those who were 13 or under. The group found to have the lowest lung capacity in the whole dataset were children 13 or under who did *not* smoke. \n\nSince the finding related to this age group (study subjects aged 13 or under) was unexpected, I used the filter() and table() functions to examine the sample size of this group. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nThirteen_and_under <- filter(df, AgeGroups == \"a. Less than or equal to 13\")\ntable(Thirteen_and_under$Smoke)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n no yes \n401  27 \n```\n:::\n:::\n\n\nAccording to this data, there were only 27 children in this study 13 years old or under who reported smoking. In order to better understand the relationship between age, smoking status and lung capacity we could run another study with a larger sample size. \n\n\n# Question 2\n\nPart 2 of the homework provided a table and stated, \"Let X = number of prior convictions for prisoners at a state prison at which there are 810  prisoners.\" I have recreated the table as a dataframe here and added an additional column that gives the probability for each prior conviction by dividing frequency values by the total number of prisoners:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq_num_prisoners <- c(128, 434, 160, 64, 24)\nX_prior_convictions <- c(0,1,2,3,4)\nprobability <- freq_num_prisoners/810\ndf <- data.frame(X_prior_convictions,freq_num_prisoners,probability)\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  X_prior_convictions freq_num_prisoners probability\n1                   0                128  0.15802469\n2                   1                434  0.53580247\n3                   2                160  0.19753086\n4                   3                 64  0.07901235\n5                   4                 24  0.02962963\n```\n:::\n:::\n\n\nWith this table we can answer several of the questions for HW1, part 2:\n\n## 2a. \n*What is the probability that a randomly selected inmate has exactly 2 prior convictions?* \n\nIn the table above we can see that the probability that a randomly selected inmate has 2 prior convictions is .1975, or .2 rounded.\n  \n## 2b. \n*What is the probability that a randomly selected inmate has fewer than 2 prior convictions?* \n\nThis question is looking for the cumulative probability that an inmate has less than 2 prior convictions. We can find cumulative probability by adding the relevant probabilities: The probability that an inmate has 0 convictions is .16 and the probability that an inmate has 1 conviction is .54.\n  \n\n::: {.cell}\n\n```{.r .cell-code}\n# We can see these numbers in the table above, but as a reminder and a way to \n# double check, we can calculate those probabilities again before adding them:\nzero_convictions <- 128/810\none_conviction <- 434/810\nProb_fewer_than_2 <- zero_convictions + one_conviction\nProb_fewer_than_2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\n  \n## 2c. \n*What is the probability that a randomly selected inmate has 2 or fewer prior convictions?*\n\nTo find the probability that a randomly selected inmate has 2 or fewer prior convictions we use the same method as the in the previous question: add together the probabilities for X = 0, X = 1, and X = 2:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We can see these numbers in the table above, but as a reminder and a way to \n# double check, we can calculate those probabilities again before adding them:\ntwo_convictions <- 160/810\nProb_2_or_fewer <- zero_convictions + one_conviction + two_convictions\nProb_2_or_fewer \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\n  \n  \n## 2d. \n*What is the probability that a randomly selected inmate has more than 2 prior convictions?* \n\nTo find the probability that a randomly selected inmate has more than 2 prior convictions we use the same method as in the previous questions, except that we add the probabilities of X = 3 and X = 4:\n  \n\n::: {.cell}\n\n```{.r .cell-code}\n# We can see these numbers in the table above, but as a reminder and a way to \n# double check, we can calculate those probabilities again before adding them:\nthree_convictions <- 64/810\nfour_convictions <- 24/810\nProb_2_or_more <- three_convictions + four_convictions\nProb_2_or_more \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\n\n\n## 2e. \n*What is the expected value for the number of prior convictions?* \n\nTo find the expected value for the number of prior convictions we multiply each possible value of X by its probability of occurring and add that up over all X. To do this in R I used some of the same variables I created above to calculate the expected value:\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nExpVal <- sum(probability*X_prior_convictions)\nExpVal\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\n## 2f. \n*Calculate the variance and the standard deviation for the Prior Convictions.* \n\nTo calculate the variance I used the expected value we just calculated and the following equation for variance: E[(X-u)^2]. Once I found the variance, I was able to find the standard deviation, since it is the square root of the variance:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVarX <- sum((X_prior_convictions-ExpVal)^2*probability)\nVarX\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8562353\n```\n:::\n\n```{.r .cell-code}\nsdX <- sqrt(VarX)\nsdX\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9253298\n```\n:::\n:::\n",
    "supporting": [
      "HW1_JustineShakespeare_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}