{
  "hash": "931c42f9b6a7267f7b599036c4122a4d",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Asch Harwood\"\ndescription: \"hw2\"\ndate: \"3/28/23\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - hypothesis_testing\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\n```\n:::\n\n\n# Q1\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create data frame\ndf <- data.frame(\n  \"Surgical Procedure\" = c(\"Bypass\", \"Angiography\"),\n  \"Sample Size\" = c(539, 847),\n  \"Mean Wait Time\" = c(19, 18),\n  \"Standard Deviation\" = c(10, 9)\n)\n\n# bypass confidence interval\nmean <- 19\nn <- 539\nsd <- 10\nci_level <- .9\ntail_area <- (1 - ci_level)/2\nt_score <- qt(p=1-tail_area, df = n - 1)\nb_ci <- c(mean - t_score * sd/sqrt(n), mean + t_score * sd/sqrt(n))\n\n# angiography\nmean <- 18\nn <- 847\nsd <- 9\nci_level <- .9\ntail_area <- (1 - ci_level)/2\nt_score <- qt(p=1-tail_area, df = n - 1)\na_ci <- c(mean - t_score * sd/sqrt(n), mean + t_score * sd/sqrt(n))\n\n\ncat(\"Bypass 90% Confidence Interval: (\", b_ci[1], \", \", b_ci[2], \")\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBypass 90% Confidence Interval: (18.29029, 19.70971)\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"Angiography 90% Confidence Interval: (\", a_ci[1], \", \", a_ci[2], \")\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAngiography 90% Confidence Interval: (17.49078, 18.50922)\n```\n:::\n:::\n\n\n\n### Interpretation\n\nBypass confidence interval: 18.29029, 19.70971\nAngiography confidence interval: 17.49078 18.50922\n\nThe angiography confidence level is smaller.\n\n# Q2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 1031 # num of americans survey\ncollege_essential <- 567 # num americans believe college is essential\npoint_estimate <- college_essential/n\nprop_results <- prop.test(college_essential, n)\n\ncat(\"College is essential point estimate:\", point_estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCollege is essential point estimate: 0.5499515\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"College is essential 95% Confidence Interval: (\", prop_results$conf.int[1], \", \", prop_results$conf.int[2], \")\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCollege is essential 95% Confidence Interval: (0.5189682, 0.580558)\n```\n:::\n:::\n\n\n# Q3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# solve for n:  CI = x + (t * (sd / sqrt(n)))\n# plug in value in this equation: n = (sd * t / (CI - x))^2\n#calculate mean\nhigh_price <- 200\nlow_price <- 30\n\nsd <- (high_price - low_price) * .25\nmean <- (high_price + low_price)/2\nci_lower <- mean - 5\nci_upper <- mean + 5\nci_level <- .95\nestimated_sample_size <- (sd * ci_level / (ci_upper - mean))^2\n\ncat(\"The estimated sample size is: \", round(estimated_sample_size))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe estimated sample size is:  65\n```\n:::\n:::\n\n\n\n\n# Q4\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# goal: test whether mean female incole is inline with union agreement\nmean_weekly_income_predicted <- 500\nn = 9\nmean_sampled = 410\nsd_sample = 90\n```\n:::\n\n\n### Q4_A\n\n#### Approach and Assumptions\n\n- Approach 1: Construct confidence interval\n- Approach 2: One-sample, two-tailed T-test\n\n- Assumptions: \n1. Sample is random and representative of underlying population\n2. Data is normally distributed\n3. Sample observations are independent\n4. Population standard deviation is not known\n\n- Hypothesis\n1. h0: female weekly salary is the same as union weekly ($410 == $500)\n2. h1: female weekly salary is different from the union weekly (higher/lower) ($410 != $500)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#confidence interval calculation\nmean <- 410\nunion_mean <- 500\nn <- 9\nsd <- 90\nalpha <- 0.05\nci_level <- .95\ntail_area <- (1 - ci_level)/2\nt_score <- qt(p=1-tail_area, df = n - 1)\na_ci <- c(mean - t_score * sd/sqrt(n), mean + t_score * sd/sqrt(n))\n\n#p-value calculation\n\n#compute t_staistics\nt_stat <- (mean - union_mean)/(sd/sqrt(n))\n\n#computer degrees of freedom\ndf <- n - 1\n\n#calculate lower/left tail because t statistics is negative\n#multipy by two for two-tailed test\np_val <- 2*pt(t_stat, df)\n\ncat(\"Approach 1: Confidence Interval\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nApproach 1: Confidence Interval\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"Female Salary 95% Confidence Interval: (\", a_ci[1], \", \", a_ci[2], \")\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFemale Salary 95% Confidence Interval: (340.8199, 479.1801)\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"T score:\", t_score)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nT score: 2.306004\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"Interpretation\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nInterpretation\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"The 95% confidence interval for the weekly female salary of $410 does not include $500, so we can reject the null hypothesis in favor of the alternative hypthosis that weekly female salary differs from $500 a week\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe 95% confidence interval for the weekly female salary of $410 does not include $500, so we can reject the null hypothesis in favor of the alternative hypthosis that weekly female salary differs from $500 a week\n```\n:::\n\n```{.r .cell-code}\ncat(\"Approach 2: Calculat P Value\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nApproach 2: Calculat P Value\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"T statistic:\", t_stat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nT statistic: -3\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"Two-tailed P Value\", p_val)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTwo-tailed P Value 0.01707168\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"Is P value less than alpha?:\", p_val < alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIs P value less than alpha?: TRUE\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"Interpretation\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nInterpretation\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"We can reject the null hypothesis in favor of the alternative hypothosis that weekly female salary differs from $500 a week because the observed p value of\", p_val, \"is less than our designated signifiance level of\", alpha, \".\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWe can reject the null hypothesis in favor of the alternative hypothosis that weekly female salary differs from $500 a week because the observed p value of 0.01707168 is less than our designated signifiance level of 0.05 .\n```\n:::\n:::\n\n\n\n### Q4_B\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#p-value calculation\n\nmean <- 410\nunion_mean <- 500\nn <- 9\nsd <- 90\nalpha <- 0.05\n\n#compute t_staistics\nt_stat <- (mean - union_mean)/(sd/sqrt(n))\n\n#computer degrees of freedom\ndf <- n - 1\n\np_val <- pt(t_stat, df, lower.tail = TRUE)\n\n#calculate lower/left tail because t statistics is negative\n#multipy by two for two-tailed test\ncat(\"Lower Tail P Value:\", p_val)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLower Tail P Value: 0.008535841\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"This lower tail p value can be used to test whether the observed weekly female salary is less than the union wage. In this case, if we were doing a one-tailed t-test with an alpha significance level of 0.05, we could reject the null hypothesis in favor of the altnernative that weekly female salary is less than the union wage with a p value of\", p_val,\".\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThis lower tail p value can be used to test whether the observed weekly female salary is less than the union wage. In this case, if we were doing a one-tailed t-test with an alpha significance level of 0.05, we could reject the null hypothesis in favor of the altnernative that weekly female salary is less than the union wage with a p value of 0.008535841 .\n```\n:::\n:::\n\n\n\n### Q4_C\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean <- 410\nunion_mean <- 500\nn <- 9\nsd <- 90\nalpha <- 0.05\n\n#compute t_staistics\nt_stat <- (mean - union_mean)/(sd/sqrt(n))\n\n#computer degrees of freedom\ndf <- n - 1\n\np_val <- pt(t_stat, df, lower.tail = FALSE)\n\n#calculate lower/left tail because t statistics is negative\n#multipy by two for two-tailed test\ncat(\"Upper Tail P Value:\", p_val)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nUpper Tail P Value: 0.9914642\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"This upper tail p value can be used to test whether the observed weekly female salary is more than the union wage. In this case, if we were doing a one-tailed t-test with an alpha significance level of 0.05, we cannot reject the null hypothesis in favor of the altnernative that weekly female salary is less than the union wage with a p value of\", p_val,\".\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThis upper tail p value can be used to test whether the observed weekly female salary is more than the union wage. In this case, if we were doing a one-tailed t-test with an alpha significance level of 0.05, we cannot reject the null hypothesis in favor of the altnernative that weekly female salary is less than the union wage with a p value of 0.9914642 .\n```\n:::\n:::\n\n# Q5\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 1000 #sample size\ndf <- n - 1 #degrees of freedom\nse <- 10.0 #standard error\npop_mean <- 500 #assumed pop mean\ny_jones <- 519.5\ny_smith <- 519.7\nt_jones <- 1.95\nt_smith <- 1.97\np_jones <- 0.051\np_smith <- 0.049\n\n# helper functions - computes t-stat\nt_stat_func <- function(mean_1, test_mean, standard_error){\n  t_stat <- (mean_1 - test_mean)/(standard_error)\n  return(t_stat)\n}\n\n#helper function - computers p-value\np_val_func <- function(t_stat, df, tail_type){\n  if (t_stat < 0){\n    p_val <- pt(t_stat, df, lower.tail = TRUE)\n  } else{\n    p_val <- pt(t_stat, df, lower.tail = FALSE)\n  }\n  if (tail_type==2){\n    p_val <- p_val*2\n  }else{p_val}\n  \n  return(p_val)\n}\n```\n:::\n\n\n### Q5_A\n\n::: {.cell}\n\n```{.r .cell-code}\n#compute t_staistics for jones\n\nt_stat_jones <- t_stat_func(y_jones, pop_mean, se)\n\np_val_jones <- p_val_func(t_stat_jones, df, 2)\n\nt_stat_smith <- t_stat_func(y_smith, pop_mean, se)\n\np_val_smith <- p_val_func(t_stat_smith, df, 2)\n\ncat(\"Jones\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nJones\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"T statistic:\", t_stat_jones,\",\", \"P value:\", p_val_jones)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nT statistic: 1.95 , P value: 0.05145555\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"Smith\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSmith\n```\n:::\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"T statistic:\", t_stat_smith,\",\", \"P value:\", p_val_smith)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nT statistic: 1.97 , P value: 0.04911426\n```\n:::\n:::\n\n### Q5_B\n\nWith an alpha of 0.05, Smith's result is statistically significant, while Jones's result is not.\n\n### Q5_C\n\nThe chosen significant level (alpha = 0.05, for example) is typically a rule of thumb in the social sciences. In this case, a decision to round a value to decimal places would put both of these p-values at 0.05. Context matters as well. Depending on what is being measured in this example, the difference between 519.5 versus 519.7 might not be meaningful, or it could represent a huge real world difference. The implications/consequences of committing type 1 or type 2 error could be pertinent in the interpretation of these p_values as well. By reporting the actual p-values, readers are empowered to better evaluate the decisions of the researchers.\n\n# Q6\n\n#### Null Hypothesis\nH0: There is no association between snack choice and grade level\n\n6th_grade_healthy_snack_31 = 7th_grade_healthy_snack_43 = 8th_grade_healthy_snack_51\n\n6th_grade_unhealthy_snack_69 = 7th_grade_healthy_snack_57 = 8th_grade_healthy_snack_49\n\n#### Chi Squared Test\n\n- We will use a chi-squared test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnack_counts <- matrix(\n  c(31, 43, 51, 69, 57, 49),\n  nrow = 2,\n  byrow = TRUE\n)\nrownames(snack_counts) <- c(\"Healthy_Snack\", \"Unhealthy_Snack\")\ncolnames(snack_counts) <- c(\"6th grade\", \"7th grade\", \"8th grade\")\nsnack_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                6th grade 7th grade 8th grade\nHealthy_Snack          31        43        51\nUnhealthy_Snack        69        57        49\n```\n:::\n\n```{.r .cell-code}\n# Perform the Chi-square test\nchi_square_test <- chisq.test(snack_counts)\n\n# Print the test results\nprint(chi_square_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  snack_counts\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\n#### Interpretation\n\nWe can reject the null hypothesis that there is no association between snack choice and grade in favor of the alternative hypothesis that there is an association between snack choice and grade\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a dataframe\nsnack_data <- data.frame(\n  Grade_Level = c(\"6th grade\", \"7th grade\", \"8th grade\"),\n  Healthy_Snack = c(31, 43, 51),\n  Unhealthy_Snack = c(69, 57, 49)\n)\n\n# Calculate the proportions\nsnack_data$Total <- snack_data$Healthy_Snack + snack_data$Unhealthy_Snack\nsnack_data$Healthy_Prop <- snack_data$Healthy_Snack / snack_data$Total\nsnack_data$Unhealthy_Prop <- snack_data$Unhealthy_Snack / snack_data$Total\n\n# Reshape the data to a long format\nsnack_data_long <- tidyr::gather(snack_data, key = \"Snack_Type\", value = \"Proportion\", Healthy_Prop, Unhealthy_Prop)\n\n# Create a bar plot using ggplot2\nggplot(snack_data_long, aes(x = Grade_Level, y = Proportion, fill = Snack_Type)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Proportion of Healthy and Unhealthy Snacks by Grade Level\",\n       x = \"Grade Level\",\n       y = \"Proportion\",\n       fill = \"Snack Type\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](asch_harwood_hw2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\n# Q7\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data from the table\ndata_matrix <- matrix(\n  c(\n    6.2, 9.3, 6.8, 6.1, 6.7, 7.5,\n    7.5, 8.2, 8.5, 8.2, 7.0, 9.3,\n    5.8, 6.4, 5.6, 7.1, 3.0, 3.5\n  ),\n  nrow = 3,\n  byrow = TRUE\n)\n# Create a dataframe with Area and Value columns\ndata_df <- data.frame(\n  Area = factor(rep(c(\"Area 1\", \"Area 2\", \"Area 3\"), each = 6)),\n  Value = as.vector(t(data_matrix))\n)\n\nmean_df <- data_df %>%\n  group_by(Area) %>%\n  summarise(mean_val = mean(Value))\n```\n:::\n\n\n\n### Answer\n\n#### Null Hypothesis\n\nH0: All groups have the same population mean\n\narea_1 = area_2 = area_3 is TRUE\n\nH1: At least one group has a different population mean\n\narea_1 = area_2 = area_3 is FALSE\n\n#### ANOVA\n\n- Since we are trying to determine if the observed differences in area means are statistically significant, we will use a one-way analysis of variance test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_results <- aov(Value ~ Area, data_df)\nsummary(anova_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \nArea         2  25.66  12.832   8.176 0.00397 **\nResiduals   15  23.54   1.569                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n#### Interpretation\n\nWith a P value of 0.00397 we can reject the null hypothesis that there is no difference between the three group means in favor of the alternative hypothesis that there is indeed a difference.\n\n\n\n",
    "supporting": [
      "asch_harwood_hw2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}