{
  "hash": "be03e56890e2481281c43b3ed0103acf",
  "result": {
    "markdown": "---\ntitle: \"HW2\"\nauthor: \"Liam Tucksmith\"\ndesription: \"HW2\"\ndate: \"03/12/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - Liam Tucksmith\n  - tidyverse\n  - readxl\n  - ggplot2\n  - dplyr\n  - tidyr\neditor_options: \n  markdown: \n    wrap: 72\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n1.  The time between the date a patient was recommended for heart\n    surgery and the surgery date for cardiac patients in Ontario was\n    collected by the Cardiac Care Network (\"Wait Times Data Guide,\"\n    Ministry of Health and Long-Term Care, Ontario, Canada, 2006). The\n    sample mean and sample standard deviation for wait times (in days)\n    of patients for two cardiac procedures are given in the accompanying\n    table. Assume that the sample is representative of the Ontario\n    population\n\nConstruct the 90% confidence interval to estimate the actual mean wait\ntime for each of the two procedures. Is the confidence interval narrower\nfor angiography or bypass surgery?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbp_num <- 539\nbp_mean <- 19\nbp_sd <- 10\nbp_se <- sqrt(bp_sd)\nag_num <- 847\nag_mean <- 18\nag_sd <- 9\nag_se <- sqrt(ag_sd)\n\nalpha = 0.1\ndegrees.freedom = bp_num - 1\nt.score = qt(p=alpha/2, df=degrees.freedom,lower.tail=F)\n\nmargin.error <- t.score * bp_se\n\nlower.bound <- bp_mean - margin.error\nupper.bound <- bp_mean + margin.error\nbypass_confidenceInterval <- print(c(lower.bound,upper.bound))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 13.78954 24.21046\n```\n:::\n\n```{.r .cell-code}\ndegrees.freedom = ag_num - 1\nt.score = qt(p=alpha/2, df=degrees.freedom,lower.tail=F)\n\nmargin.error <- t.score * ag_se\n\nlower.bound <- ag_mean - margin.error\nupper.bound <- ag_mean + margin.error\nangiography_confidenceInterval <- print(c(lower.bound,upper.bound))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 13.06003 22.93997\n```\n:::\n:::\n\n\nThe confidence interval is narrower for angiography surgery than it is\nfor bypass surgery. The bypass surgery confidence interval spans from\n13.78954 to 24.21046 days while the angiography surgery spans from\n13.06003 to 22.93997 days. Since the bypass surgery confidence interval\nspans 10.42 days and the angiography surgery spans 9.88 days, the\nangiography surgery has a narrower confidence interval than the bypass\nsurgery.\n\n2.  A survey of 1031 adult Americans was carried out by the National\n    Center for Public Policy. Assume that the sample is representative\n    of adult Americans. Among those surveyed, 567 believed that college\n    education is essential for success. Find the point estimate, p, of\n    the proportion of all adult Americans who believe that a college\n    education is essential for success. Construct and interpret a 95%\n    confidence interval for p.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = 1031 \ncollege_y = 567\np = college_y/n\nprint(p)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n\n```{.r .cell-code}\nmargin_error <- qnorm(0.95)*sqrt(p*(1-p)/n)\nlowerbound <- p - margin_error\nupperbound <- p + margin_error\n\np_confidenceInterval <- print(c(lowerbound,upperbound))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5244662 0.5754368\n```\n:::\n:::\n\n\n3.  Suppose that the financial aid office of UMass Amherst seeks to\n    estimate the mean cost of textbooks per semester for students. The\n    estimate will be useful if it is within \\$5 of the true population\n    mean (i.e. they want the confidence interval to have a length of\n    \\$10 or less). The financial aid office is pretty sure that the\n    amount spent on books varies widely, with most values between \\$30\n    and \\$200. They think that the population standard deviation is\n    about a quarter of this range (in other words, you can assume they\n    know the population standard deviation). Assuming the significance\n    level to be 5%, what should be the size of the sample\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmargin_error_max = 5\nconfidence_interval_length = 10\nlower_bound_avg = 30\nupper_bound_avg = 200\nrange = upper_bound_avg - lower_bound_avg\n\nz = .95 +(1-.95)/2\nn = ((z - (range/4))/confidence_interval_length)^2\n\nprint(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.24326\n```\n:::\n:::\n\n\n4.  According to a union agreement, the mean income for all senior-level\n    workers in a large service company equals \\$500 per week. A\n    representative of a women's group decides to analyze whether the\n    mean income μ for female employees matches this norm. For a random\n    sample of nine female employees, ȳ = \\$410 and s = 90\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome_n <- c(rnorm(9, mean = 410, sd = 90))\n```\n:::\n\n\nA. Test whether the mean income of female employees differs from \\$500\nper week. Include assumptions, hypotheses, test statistic, and P-value.\nInterpret the result.\n\nassumption: The mean income of female employees is \\$500 per week. \nnull hypothesis: The mean income of female employees is \\$500 per week. alternative hypothesis: The mean income of female employees differs from \\$500 per week.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome_female <- t.test(income_n, mu=500)\nprint(income_female)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  income_n\nt = -4.0036, df = 8, p-value = 0.00393\nalternative hypothesis: true mean is not equal to 500\n95 percent confidence interval:\n 303.2482 447.0648\nsample estimates:\nmean of x \n 375.1565 \n```\n:::\n:::\n\n\nThe result is that with 95% certainty the mean female income falls\nbetween \\$322.6557 and \\$441.1327. Since the range falls below \\$500, we reject the null hypothesis that the mean female income is \\$500, and accept the alternative hypothesis that the true mean female income is not equal to \\$500.\n\nB. Report the P-value for Ha: μ \\< 500. Interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome_female <- t.test(income_n, mu=500, alternative = 'less')\nprint(income_female)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  income_n\nt = -4.0036, df = 8, p-value = 0.001965\nalternative hypothesis: true mean is less than 500\n95 percent confidence interval:\n     -Inf 433.1429\nsample estimates:\nmean of x \n 375.1565 \n```\n:::\n:::\n\n\nThe p_value is 0.0081. It is less than the 0.5 alpha so we reject the null hypothesis that that the mean female income is \\$500, and accept the alternative hypothesis that the true mean female income is less than $500.\n\nC. Report and interpret the P-value for Ha: μ \\> 500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome_female <- t.test(income_n, mu=500, alternative = 'greater')\nprint(income_female)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  income_n\nt = -4.0036, df = 8, p-value = 0.998\nalternative hypothesis: true mean is greater than 500\n95 percent confidence interval:\n 317.1701      Inf\nsample estimates:\nmean of x \n 375.1565 \n```\n:::\n:::\n\n\nThe p_value is 0.9919. It is not less than the 0.5 alpha so we fail to reject the null hypothesis that that the mean female income is $500.\n\n5.  Jones and Smith separately conduct studies to test H0: μ = 500 against Ha: μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7, with se = 10.0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd.js = 10*(sqrt(1000))\n\nincome_jones <- c(rnorm(1000, mean = 519.5, sd = sd.js))\nincomes_smith <- c(rnorm(1000, mean = 519.7, sd = sd.js))\n```\n:::\n\n\nA. Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njones_t <- (519.5 - 500)/(sd.js/sqrt(1000))\njones_p <- 2*(pt(-jones_t, 999))\n\nprint(jones_t)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\nprint(jones_p)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\nsmith_t <- (519.7 - 500)/(sd.js/sqrt(1000))\nsmith_p <- 2*(pt(-smith_t, 999))\n\nprint(smith_t)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\nprint(smith_p)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\nB. Using α = 0.05, for each study indicate whether the result is \"statistically significant.\"\n\nThe Jones study result is not statistically significant because their p-value is above the alpha. The Smith study result is statistically significant because the p-value is below the alpha.\n\nC. Using this example, explain the misleading aspects of reporting the result of a test as \"P ≤ 0.05\" versus \"P \\> 0.05,\" or as \"reject H0\" versus \"Do not reject H0,\" without reporting the actual P-value.\n\nBecause in this case the p-value is so close to the alpha, it's misleading to not report the actual p-value. If someone only read that a null hypothesis was not rejected and not that statistical significance criteria was almost met, they may falsely attribute the strength of confidence of which the null hypothesis was not rejected with. It's important to report the p-value so that the strength of confidence is\nknown.\n\n6.  A school nurse wants to determine whether age is a factor in whether children choose a healthy snack after school. She conducts a survey of 300 middle school students, with the results below. Test at α = 0.05 the claim that the proportion who choose a healthy snack differs by grade level. What is the null hypothesis? Which test should we use? What is the conclusion?\n\nx = proportion of students who choose a healthy snack\nnull hypothesis: X is not affected by grade level. \nalternative hypothesis: X is affected by grade level. \n\n::: {.cell}\n\n```{.r .cell-code}\ngrade <- c(6, 7, 8) \nhealthy_prop <- c(31, 43, 51)\nunhealthy_prop <- c(69, 57, 49)\nstudent_n <- c(100, 100, 100)\n\nstudent_data <- data.frame(grade, healthy_prop, unhealthy_prop)\n\nstudent_t <- prop.test(student_data$healthy_prop, n=student_n)\nprint(student_t)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t3-sample test for equality of proportions without continuity\n\tcorrection\n\ndata:  student_data$healthy_prop out of student_n\nX-squared = 8.3383, df = 2, p-value = 0.01547\nalternative hypothesis: two.sided\nsample estimates:\nprop 1 prop 2 prop 3 \n  0.31   0.43   0.51 \n```\n:::\n:::\n\nThe conclusion is that since the p-value of 0.01547 is below our 0.05 value we reject the null hypothesis that the proportion of students who choose a healthy snack is not affected by grade level in favor of the alternative hypothesis that the proportion of students who choose a healthy snack is affected by grade level. \n\n7. Per-pupil costs (in thousands of dollars) for cyber charter school tuition for school districts in three areas are shown. Test the claim that there is a difference in means for the three areas, using an appropriate test. What is the null hypothesis? Which test should we use? What is the conclusion?\n\nnull hypothesis: There is not a difference in mean per-pupil cost (in thousands of dollars) for cyber charter school tuition for school districts for the three areas.\nalternative hypothesis: There is a difference in mean per-pupil cost (in thousands of dollars) for cyber charter school tuition for school districts for the three areas. \n\n::: {.cell}\n\n```{.r .cell-code}\nvalues <- c(6.2,9.3,6.8,6.1,6.7,7.5,\n           7.5,8.2,8.5,8.2,7.0,9.3,\n           5.8,6.4,5.6,7.1,3.0,3.5)\narea <- c(1,1,1,1,1,1,\n          2,2,2,2,2,2,\n          3,3,3,3,3,3)\n\ncost_data <- data.frame(values, area)\n\nanova <- aov(values~area, data = cost_data)\nsummary(anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \narea         1  10.45  10.453   4.316 0.0542 .\nResiduals   16  38.75   2.422                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\nThe conclusion is that since the p-value of 0.0542 is above our 0.05 value we fail reject the null hypothesis that there is not a difference in mean per-pupil cost (in thousands of dollars) for cyber charter school tuition for school districts for the three areas in favor of the alternative hypothesis that there is a difference in mean per-pupil cost (in thousands of dollars) for cyber charter school tuition for school districts for the three areas. ",
    "supporting": [
      "HW2_LTucksmith_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}