{
  "hash": "f8ee62975c42080eaf6740be811d0341",
  "result": {
    "markdown": "---\ntitle: \"Homework 5\"\nauthor: \"Darron Bunt\"\ndescription: \"Homework Assignment 5 - Darron Bunt\"\ndate: \"05/07/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw5\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.2     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n\nLoading required package: effects\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\nlibrary(ggplot2)\nlibrary(broom)\n```\n:::\n\n\n# Question 1 \n\n(Data file: house.selling.price.2 from smss R package)\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data file\ndata(house.selling.price.2)\n```\n:::\n\n\n**For the house.selling.price.2 data the tables below show a correlation matrix and a model fit using four predictors of selling price.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHousePriceVars <- lm(P ~ S + Be + Ba + New, data = house.selling.price.2)\nsummary(HousePriceVars)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = P ~ S + Be + Ba + New, data = house.selling.price.2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-36.212  -9.546   1.277   9.406  71.953 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -41.795     12.104  -3.453 0.000855 ***\nS             64.761      5.630  11.504  < 2e-16 ***\nBe            -2.766      3.960  -0.698 0.486763    \nBa            19.203      5.650   3.399 0.001019 ** \nNew           18.984      3.873   4.902  4.3e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.36 on 88 degrees of freedom\nMultiple R-squared:  0.8689,\tAdjusted R-squared:  0.8629 \nF-statistic: 145.8 on 4 and 88 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n#### A \n\n**With these four predictors: For backward elimination, which variable would be deleted first? Why?**\n\nIn backward elimination, we start by including all variables in the model, pre-determine a significance level, and then at each stage delete the variable with the largest p-value and continue on until all variables are significant.\n\nLooking at the regression output, Beds has the largest p-value (0.487) and would be deleted first.\n\n#### B\n\n**With these four predictors: For forward selection, which variable would be added first? Why?**\n\nIn forward selection, we start with no explanatory variable and a pre-determined significance level. At each step we add the variable that is the most significant (ie. the one with the smallest p-value) and then stop when there are no remaining variables that can make a significant partial contribution.\n\nLooking at the regression output, Size has the smallest p-value (< 2e-16) and would be added first. \n\n#### C\n\n**Why do you think that BEDS has such a large P-value in the multiple regression model, even though it has a substantial correlation with PRICE?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCorHousePriceVars <- cor(house.selling.price.2)\nCorHousePriceVars\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            P         S        Be        Ba       New\nP   1.0000000 0.8988136 0.5902675 0.7136960 0.3565540\nS   0.8988136 1.0000000 0.6691137 0.6624828 0.1762879\nBe  0.5902675 0.6691137 1.0000000 0.3337966 0.2672091\nBa  0.7136960 0.6624828 0.3337966 1.0000000 0.1820651\nNew 0.3565540 0.1762879 0.2672091 0.1820651 1.0000000\n```\n:::\n:::\n\nI would suspect multicollinearity. Multicollinarity refers to a situation where 2+ variables in a regression model are highly correlated with each other - that is, they are measuring either the same or similar things. \n\nLarger houses typically have more bedrooms and bathrooms (you can only fill so much space with giant living rooms!) and the number of bathrooms is also frequently correlated with the number of bedrooms (houses with 2-4 bedrooms commonly have 2 bathrooms, etc.). If size, bedrooms, and bathrooms are all measuring similar things, multicollinearity is likely a factor. \n\n#### D\n\n**Using software with these four predictors, find the model that would be selected using each criterion:**\n\nI'll create the models using backwards elimination:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# All four predictors: P ~ S + Be + Ba + New\nsummary(HousePriceVars)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = P ~ S + Be + Ba + New, data = house.selling.price.2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-36.212  -9.546   1.277   9.406  71.953 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -41.795     12.104  -3.453 0.000855 ***\nS             64.761      5.630  11.504  < 2e-16 ***\nBe            -2.766      3.960  -0.698 0.486763    \nBa            19.203      5.650   3.399 0.001019 ** \nNew           18.984      3.873   4.902  4.3e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.36 on 88 degrees of freedom\nMultiple R-squared:  0.8689,\tAdjusted R-squared:  0.8629 \nF-statistic: 145.8 on 4 and 88 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# eliminate BEDS due to highest p-value - now have three predictors\nHousePriceNoBeds <- lm(P ~ S + Ba + New, data = house.selling.price.2)\nsummary(HousePriceNoBeds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = P ~ S + Ba + New, data = house.selling.price.2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-34.804  -9.496   0.917   7.931  73.338 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -47.992      8.209  -5.847 8.15e-08 ***\nS             62.263      4.335  14.363  < 2e-16 ***\nBa            20.072      5.495   3.653 0.000438 ***\nNew           18.371      3.761   4.885 4.54e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.31 on 89 degrees of freedom\nMultiple R-squared:  0.8681,\tAdjusted R-squared:  0.8637 \nF-statistic: 195.3 on 3 and 89 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nAll variables are now significant. For the sake of having another model to compare to, I'll continue the backwards elimination and remove Baths, which is the next largest p-value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# eliminate BATHS, now have two predictors \nHousePriceNoBedsBath <- lm(P ~ S + New, data = house.selling.price.2)\nsummary(HousePriceNoBedsBath)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = P ~ S + New, data = house.selling.price.2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-47.207  -9.763  -0.091   9.984  76.405 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -26.089      5.977  -4.365 3.39e-05 ***\nS             72.575      3.508  20.690  < 2e-16 ***\nNew           19.587      3.995   4.903 4.16e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 17.4 on 90 degrees of freedom\nMultiple R-squared:  0.8484,\tAdjusted R-squared:  0.845 \nF-statistic: 251.8 on 2 and 90 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert the model results to a data frame\nHousePrice_results <- bind_rows(\n  data.frame(model_name = \"HousePriceVars\", glance(HousePriceVars)),\n  data.frame(model_name = \"HousePriceNoBeds\", glance(HousePriceNoBeds)),\n  data.frame(model_name = \"HousePriceNoBedsBath\", glance(HousePriceNoBedsBath)))\nHousePrice_results\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            model_name r.squared adj.r.squared    sigma statistic      p.value\n1       HousePriceVars 0.8688630     0.8629022 16.35994  145.7634 5.936558e-38\n2     HousePriceNoBeds 0.8681361     0.8636912 16.31279  195.3127 4.964676e-39\n3 HousePriceNoBedsBath 0.8483699     0.8450003 17.39529  251.7748 1.365665e-37\n  df    logLik      AIC      BIC deviance df.residual nobs\n1  4 -389.3113 790.6225 805.8181 23552.98          88   93\n2  3 -389.5683 789.1366 801.7996 23683.53          89   93\n3  2 -396.0631 800.1262 810.2566 27233.66          90   93\n```\n:::\n:::\n\n**Find the model that would be selected using each criterion:**\n\n**1. R2**\n\nHousePriceVars - the model with all four predictors (Size, Beds, Baths, New).\n\n**2. Adjusted R2**\n\nHousePriceNoBeds - the model with three predictors (Size, Baths, New)\n\n**3. PRESS**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# PRESS of HousePriceVars\nPRHousePriceVars <- resid(HousePriceVars)/(1 - lm.influence(HousePriceVars)$hat)\nsum(PRHousePriceVars^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 28390.22\n```\n:::\n\n```{.r .cell-code}\n# PRESS of HousePriceNoBeds\nPRHousePriceNoBeds <- resid(HousePriceNoBeds)/(1 - lm.influence(HousePriceNoBeds)$hat)\nsum(PRHousePriceNoBeds^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 27860.05\n```\n:::\n\n```{.r .cell-code}\n# PRESS of HousePriceNoBedsBath\nPRHousePriceNoBedsBath <- resid(HousePriceNoBedsBath)/(1 - lm.influence(HousePriceNoBedsBath)$hat)\nsum(PRHousePriceNoBedsBath^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 31066\n```\n:::\n:::\n\nHousePriceNoBeds - the model with three predictors (Size, Baths, New) - has the smallest PRESS statistic.\n\n**4. AIC**\n\nHousePriceNoBeds - the model with three predictors (Size, Baths, New) - has the smallest AIC statistic.\n\n**5. BIC**\n\nHousePriceNoBeds - the model with three predictors (Size, Baths, New) - has the smallest BIC statistic.\n\n#### E\n\n**Explain which model you prefer and why.**\n\nThe model with Size, Baths, and New as the predictors of Price is the model that I prefer. It had the highest adjusted r squared, lowest PRESS, lowest AIC, and lowest BIC. It also had the lowest p-value. \n\nIt appears to be the best fitting model, and accordingly, the one that I prefer.\n\n# Question 2\n\n(Data file: trees from base R)\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data file\ndata(trees)\n```\n:::\n\nFrom the documentation:\n“This data set provides measurements of the diameter, height and volume of timber in 31 felled black cherry trees. Note that the diameter (in inches) is erroneously labeled Girth in the data. It is measured at 4 ft 6 in above the ground.”\n\n*Tree volume estimation is a big deal, especially in the lumber industry. Use the trees data to build a basic model of tree volume prediction. In particular,*\n\n#### A\n\n**Fit a multiple regression model with the Volume as the outcome and Girth and Height as the explanatory variables**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Multiple regression model with Volume as the outcome and Girth and Height as the explanatory variables\nTreeVolume <- lm(Volume ~ Girth + Height, data = trees)\nsummary(TreeVolume)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Volume ~ Girth + Height, data = trees)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.4065 -2.6493 -0.2876  2.2003  8.4847 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -57.9877     8.6382  -6.713 2.75e-07 ***\nGirth         4.7082     0.2643  17.816  < 2e-16 ***\nHeight        0.3393     0.1302   2.607   0.0145 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.882 on 28 degrees of freedom\nMultiple R-squared:  0.948,\tAdjusted R-squared:  0.9442 \nF-statistic:   255 on 2 and 28 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n#### B\n\n**Run regression diagnostic plots on the model. Based on the plots, do you think any of the regression assumptions is violated?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the diagnostic plots\npar(mfrow = c(2, 2))\nplot(TreeVolume)\n```\n\n::: {.cell-output-display}\n![](HW5_DarronBunt_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n**Based on the plots, do you think any of the regression assumptions is violated?**\n\nI think that three of the four plots violate regression assumptions. \n\nOn the Residuals vs. Fitted Values plot we want to see linearity and constant variance. The residuals should \"bounce randomly\" around the zero line, suggesting a linear and reasonable relationship. The residuals here do not. The residuals also do not roughly form a horizonal band around the zero line, suggesting that the variances of the error terms are not equal. This plot shows neither; there are patterns, and a funnel shape. \n\nThe Normal Q-Q plot looks as it should - the points on the plot follow a straight line and the points do not deviate significantly from the line. \n\nThe Scale-Location plot does not show constant variance. The line is not approximately horizontal.\n\nFinally, the Resisuals vs. Leverage plot shows an outlier outside of Cook's distance. This point with larger leverage indicates a larger potential influence on the regression model. \n\n# Question 3\n\n(Data file: florida in alr R package)\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load florida data set\ndata(florida)\n```\n:::\n\nIn the 2000 election for U.S. president, the counting of votes in Florida was controversial. In Palm Beach County in south Florida, for example, voters used a so-called butterfly ballot. Some believe that the layout of the ballot caused some voters to cast votes for Buchanan when their intended choice was Gore.\n\n*The data has variables for the number of votes for each candidate — Gore, Bush, and Buchanan.*\n\n#### A\n\n**Run a simple linear regression model where the Buchanan vote is the outcome and the Bush vote is the explanatory variable. Produce the regression diagnostic plots. Is Palm Beach County an outlier based on the diagnostic plots? Why or why not?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# linear regression model where Buchanan vote is outcome and Bush vote is explanatory \nBuchanan <- lm(Buchanan ~ Bush, data = florida)\nsummary(Buchanan)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Buchanan ~ Bush, data = florida)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-907.50  -46.10  -29.19   12.26 2610.19 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 4.529e+01  5.448e+01   0.831    0.409    \nBush        4.917e-03  7.644e-04   6.432 1.73e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 353.9 on 65 degrees of freedom\nMultiple R-squared:  0.3889,\tAdjusted R-squared:  0.3795 \nF-statistic: 41.37 on 1 and 65 DF,  p-value: 1.727e-08\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Produce the regression diagnostic plots\npar(mfrow = c(2, 2))\nplot(Buchanan)\n```\n\n::: {.cell-output-display}\n![](HW5_DarronBunt_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n**Is Palm Beach County an outlier based on the diagnostic plots? Why or why not?**\n\nYes, based on the diagnostic plots, Palm Beach County is an outlier. \n\nOn the Residuals vs. Fitted Values plot, the residuals largely \"bounce randomly\" around the zero line and form a roughly horizontal band around the zero line - with Dade and Palm Beach as significant outliers. \n\nThe Normal Q-Q plot follows a straight line and the points do not deviate significantly from the line - again, with two major exceptions: Dade, and Palm Beach. \nThe Scale-Location plot is roughly horizonal, but again has a major exception: Palm Beach. \n\nFinally, the Resisuals vs. Leverage plot shows outliers outside of Cook's distance - Dade, and once again, Palm Beach. \n\n#### B\n\n**Take the log of both variables (Bush vote and Buchanan Vote) and repeat the analysis in (A.) Does your findings change?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# linear regression model where log(Buchanan) is outcome and log(Bush) is explanatory \nLogBuchanan <- lm(log(Buchanan) ~ log(Bush), data = florida)\nsummary(LogBuchanan)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Buchanan) ~ log(Bush), data = florida)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.96075 -0.25949  0.01282  0.23826  1.66564 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2.57712    0.38919  -6.622 8.04e-09 ***\nlog(Bush)    0.75772    0.03936  19.251  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4673 on 65 degrees of freedom\nMultiple R-squared:  0.8508,\tAdjusted R-squared:  0.8485 \nF-statistic: 370.6 on 1 and 65 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Produce the regression diagnostic plots\npar(mfrow = c(2, 2))\nplot(LogBuchanan)\n```\n\n::: {.cell-output-display}\n![](HW5_DarronBunt_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n**Do your findings change?**\n\nThe p-value has gotten smaller and the adjusted r squared has gone from 0.3795 to 0.8485, suggesting that the log-log model is a better-fitting model. When it comes to the diagnostic plots, however, Palm Beach is still a notable outlier on the Residuals vs. Fitted, Normal Q-Q, and Scale-Location plots. It is now within Cook's distance on the Residuals vs. Leverage plot. \n",
    "supporting": [
      "HW5_DarronBunt_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}