{
  "hash": "66afc1e3964436965a0431b26ce0da91",
  "result": {
    "markdown": "---\ntitle: \"Homework_5\"\nauthor: \"Paritosh G\"\ndesription: \"HW_5\"\ndate: \"05/28/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - challenge1\n  - my name\n  - dataset\n  - ggplot2\n---\n\n\nLoding the libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.1     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the \u001b]8;;http://conflicted.r-lib.org/\u0007conflicted package\u001b]8;;\u0007 to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(smss)\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n\nLoading required package: effects\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(magrittr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'magrittr'\n\nThe following object is masked from 'package:purrr':\n\n    set_names\n\nThe following object is masked from 'package:tidyr':\n\n    extract\n```\n:::\n\n```{.r .cell-code}\nlibrary(broom)\n```\n:::\n\n\n## Question 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"house.selling.price.2\")\n\ndf <- house.selling.price.2\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhouse_price <- lm(P ~ S + Be + Ba + New, data = df)\nsummary(house_price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = P ~ S + Be + Ba + New, data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-36.212  -9.546   1.277   9.406  71.953 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -41.795     12.104  -3.453 0.000855 ***\nS             64.761      5.630  11.504  < 2e-16 ***\nBe            -2.766      3.960  -0.698 0.486763    \nBa            19.203      5.650   3.399 0.001019 ** \nNew           18.984      3.873   4.902  4.3e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.36 on 88 degrees of freedom\nMultiple R-squared:  0.8689,\tAdjusted R-squared:  0.8629 \nF-statistic: 145.8 on 4 and 88 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n## a)\n\n-   Beds would be deleted first as its p value of 0.4867 not statistically significant\n\n## b)\n\n-   Size(s) has the smallest p value and hence in forward method when we start with no explanatory variable Size(s) should be added first.\n\n## c)\n\nHouse with more bedrooms have most likely more number of bathrooms hence larger in size. If size, bedrooms, and bathrooms all are measuring price the high p value of bed is due to multi-collinearity.\n\n## d)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_No_Bed <- lm(P ~ S + Ba + New, data = df)\nfit_No_Bed_and_Bath <- lm(P ~ S + New, data = df)\nfit_new <- lm(P ~ New, data = df)\n```\n:::\n\n\n***R2***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_No_Bed)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8681361\n```\n:::\n\n```{.r .cell-code}\nsummary(fit_No_Bed_and_Bath)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8483699\n```\n:::\n\n```{.r .cell-code}\nsummary(fit_new)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1271307\n```\n:::\n:::\n\n\n-   fit_No_Bed model is the best with highest R2 and our best model.\n\n***Adjusted R2***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_No_Bed)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8636912\n```\n:::\n\n```{.r .cell-code}\nsummary(fit_No_Bed_and_Bath)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8450003\n```\n:::\n\n```{.r .cell-code}\nsummary(fit_new)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1175388\n```\n:::\n:::\n\n\n-   fit_No_Bed model has the highest adjusted R squared and our best model.\n\n***Press***\n\n**function for calculating press stat.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npress_stat <- function(model) {\n  # Calculate PRESS residuals\n  pr <- resid(model) / (1 - lm.influence(model)$hat)\n  \n  # Compute the PRESS statistic\n  press <- sum(pr^2)\n  \n  return(press)\n}\n```\n:::\n\n\ncalculating Press statistic for all models\n\n\n::: {.cell}\n\n```{.r .cell-code}\npress_stat(fit_No_Bed)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 27860.05\n```\n:::\n\n```{.r .cell-code}\npress_stat(fit_No_Bed_and_Bath)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 31066\n```\n:::\n\n```{.r .cell-code}\npress_stat(fit_new)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 164039.3\n```\n:::\n:::\n\n\n-   fit_no_Bed_and_Bath has the lowest Press of 31066 and it is our best model.\n\n***AIC***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(fit_No_Bed)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 789.1366\n```\n:::\n\n```{.r .cell-code}\nAIC(fit_No_Bed_and_Bath)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 800.1262\n```\n:::\n\n```{.r .cell-code}\nAIC(fit_new)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 960.908\n```\n:::\n:::\n\n\n-   fit_No_bed has the lowest AIC score and is our best model.\n\n***BIC***\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBIC(fit_No_Bed)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 801.7996\n```\n:::\n\n```{.r .cell-code}\nBIC(fit_No_Bed_and_Bath)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 810.2566\n```\n:::\n\n```{.r .cell-code}\nBIC(fit_new)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 968.5058\n```\n:::\n:::\n\n\n-   fit_No_Bed has the lowest BIC score and is our best model\n\n## e)\n\nhence model fit_no_Bed with variables size,bathroom and new is our best model.\n\n## Q.2)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(trees)\n```\n:::\n\n\n## a)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(Volume ~ Girth + Height, data = trees)\nsummary(tree_model)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in summary(tree_model): object 'tree_model' not found\n```\n:::\n:::\n\n\n## b)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2,3))\nplot(model, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](Homework_5_Paritosh_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n**Residuals vs Fitted**\n\nThe curved shape of the line suggests this model violates our assumption of linearity that the relationship between the independent and dependent variables is linear.\n\n**Scale-Location**\n\nThe curved shape of the line suggests this model violates our assumption of constant variance, or homoscedasticity, which affects the statistical significance of the model.\n\n**Cooks Distance, Residuals vs Leverage, Cooks dist vs Leverage**\n\nAll three charts show there is single, potentially influence point, which can impact whether our model meets the assumptions of linear regression and can disproportionately affect our regression coefficients.\n\n## Q.3)\n\n## a)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"florida\")\nmodel_2 <- lm(Buchanan ~ Bush, data = florida)\npar(mfrow = c(2,3))\nplot(model_2, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](Homework_5_Paritosh_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nYes, based on the diagnostic plots, Palm Beach County is an outlier.\n\nOn the Residuals vs. Fitted Values plot, the residuals largely \"bounce randomly\" around the zero line and form a roughly horizontal band around the zero line - with Dade and Palm Beach as significant outliers.\n\nThe Normal Q-Q plot follows a straight line and the points do not deviate significantly from the line - again, with two major exceptions: Dade, and Palm Beach. The Scale-Location plot is roughly horizonal, but again has a major exception: Palm Beach.\n\nFinally, the Resisuals vs. Leverage plot shows outliers outside of Cook's distance - Dade, and once again, Palm Beach.\n\n## b)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLogBuchanan <- lm(log(Buchanan) ~ log(Bush), data = florida)\nsummary(LogBuchanan)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Buchanan) ~ log(Bush), data = florida)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.96075 -0.25949  0.01282  0.23826  1.66564 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2.57712    0.38919  -6.622 8.04e-09 ***\nlog(Bush)    0.75772    0.03936  19.251  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4673 on 65 degrees of freedom\nMultiple R-squared:  0.8508,\tAdjusted R-squared:  0.8485 \nF-statistic: 370.6 on 1 and 65 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Produce the regression diagnostic plots\npar(mfrow = c(2, 2))\nplot(LogBuchanan)\n```\n\n::: {.cell-output-display}\n![](Homework_5_Paritosh_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe p-value has gotten smaller and the adjusted r squared has gone from 0.3795 to 0.8485, suggesting that the log-log model is a better-fitting model. When it comes to the diagnostic plots, however, Palm Beach is still a notable outlier on the Residuals vs. Fitted, Normal Q-Q, and Scale-Location plots. It is now within Cook's distance on the Residuals vs. Leverage plot.\n",
    "supporting": [
      "Homework_5_Paritosh_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}