{
  "hash": "500f76ea74a5c25cfd9289050c84d615",
  "result": {
    "markdown": "---\ntitle: \"Final_checkIn 3\"\nauthor: \"Sai Padma  pothula\"\ndesription: \"\"\ndate: \"05/21/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Final checkIn 3\n  - sai Pothula\n---\n\n\nResearch question: \n1.why is there a significant correlation between mental health status and CGPA among university students?\n       2.How does the use of mental health resources, such as counselling or therapy, have a positive impact on academic performance?\n      3. How does demographic factors, such as gender or ethnicity, influence the relationship between mental health and academic performance?\n\n\nHypothesis: There is a significant correlation between poor mental health status and CGPA among university students. \n\nIntroduction:\n\nThe mental health of university students has become a growing concern in recent years. Many students experience various stressors, such as academic pressures, social challenges, and the transition to a new environment, which can significantly impact their overall well-being. One area of particular interest is the relationship between mental health status and academic performance, measured by the Cumulative Grade Point Average (CGPA). Understanding this correlation is essential for developing effective strategies and interventions to support students' mental health and improve their academic outcomes.\n\nThe hypothesis suggests that there is a significant correlation between poor mental health status and CGPA among university students. It is posited that students who experience mental health difficulties may face challenges in managing their academic responsibilities, leading to lower CGPA scores. Furthermore, demographic factors, such as gender, ethnicity, and course of study, may influence this relationship. Certain groups may be more vulnerable to poor mental health outcomes, which can in turn impact their academic performance.\n\nThis research aims to explore the reasons behind the significant correlation between mental health status and CGPA among university students. By understanding the factors contributing to this relationship, educational institutions and support services can tailor interventions and resources to address the mental health needs of students, ultimately promoting both their well-being and academic success.\n\n\nDescriptive statistics        \n\nThis dataset has 101 rows, 11 columns and 44 missing values \n\ntimestamp: indicates the date and time when the survey was completed by the respondent.\n\nChoose your gender : is a categorical variable that indicates the respondent's gender.\n\nAge: is a numerical variable that indicates the respondent's age in years.\n\nWhat is your course: is a categorical variable that indicates the respondent's academic program or field of study.\n\nYour current year of Study: is a categorical variable that indicates the respondent's current year of study in their academic program.\n\nWhat is your CGPA: is a numerical variable that indicates the respondent's cumulative grade point average.\n\nMarital status: is a categorical variable that indicates the respondent's current marital status.\n\nDo you have Depression: is a categorical variable that indicates whether the respondent has ever been diagnosed with or experienced symptoms of depression.\n\nDo you have Anxiety: is a categorical variable that indicates whether the respondent has ever been diagnosed with or experienced symptoms of anxiety.\nDo you have Panic attack: is a categorical variable that indicates whether the respondent has ever been diagnosed with or experienced symptoms of panic attacks.\n\nDid you seek any specialist for treatment: is a categorical variable that indicates whether the respondent has sought out any specialist for treatment related to their mental health issues. The variable includes a brief description of the types of specialists sought out by the respondents.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.5.0 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(stats)\nlibrary(ggplot2)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth <- read_csv(\"~/Desktop/603_Spring_2023/posts/_data/student_mental.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 101 Columns: 11\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (10): Timestamp, Choose your gender, What is your course?, Your current ...\ndbl  (1): Age\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(health) <- c('Timestamp', 'Gender', 'Age', 'Course', 'Year', 'CGPA', 'Married', 'Depression', 'Anxiety', 'Panic_Attack', 'Treatment')\nindx <- apply(health, 2, function(x) any(is.na(x)))\nindx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Timestamp       Gender          Age       Course         Year         CGPA \n       FALSE        FALSE         TRUE        FALSE        FALSE        FALSE \n     Married   Depression      Anxiety Panic_Attack    Treatment \n       FALSE        FALSE        FALSE        FALSE        FALSE \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwhich(is.na(health$Age))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 44\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth[44,'Age'] <- median(health$Age, na.rm =T)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(health$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"year 1\" \"year 2\" \"Year 1\" \"year 3\" \"year 4\" \"Year 2\" \"Year 3\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Assuming you have a data frame named 'health'\n\n# Group by Age and calculate the count\ngrouped_data <- health %>%\n  group_by(Age) %>%\n  summarize(count = n())\n\n# Create the bar plot using ggplot2\nggplot(grouped_data, aes(x = Age, y = count, fill = count)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = count), vjust = -0.5, size = 3) +\n  labs(title = \"Distribution of Age\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nHealth_SummaryStat2 <- health %>%\n  group_by(Depression) %>%\n  summarise(count = n(),\n            percentage = round((n()/ nrow(health)), digits = 4))\n\ncolors <- c(\"pink\", \"cyan\", \"blue\")  # Define colors for the pie chart\n\n# Create the pie chart using the pie() function\npie(Health_SummaryStat2$percentage, labels = Health_SummaryStat2$Depression,\n    col = colors,\n    main = \"Pie Chart of Depression\",\n    cex.main = 1.2,\n    cex.lab = 1.2)\n\n# Add a legend\nlegend(\"topright\", legend = Health_SummaryStat2$Depression,\n       fill = colors, cex = 1.2)\n```\n\n::: {.cell-output-display}\n![](final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth %>%\n  count(Gender, Depression, sort = F) %>%\n  group_by(Gender) %>%\n  mutate(prop = round((n / sum(n)), digits = 4)) %>%\n  ggplot(aes(x = Gender, y = prop, fill = Depression)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = paste(Gender, prop * 100, \"%\")), position = position_stack(vjust = 0.5)) +\n  labs(title = \"Barplot of Depression amongst Genders\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth %>%\n  count(CGPA, Depression, sort = F) %>%\n  mutate(proportion = round((n / sum(n)), digits = 4)) %>%\n  ggplot(aes(x = CGPA, y = proportion, fill = Depression)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Barplot of Depression vs CGPA\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth %>%\n  filter(grepl('BIT|KOE|BCS|Engineering|Biomedical science', Course)) %>%\n  count(Course, Depression, sort = T) %>%\n  group_by(Course) %>%\n  mutate(prop = round((n / sum(n)), digits = 4)) %>%\n  ggplot(aes(x = Course, y = n, fill = Depression)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = paste(Course, n)),\n            position = position_stack(vjust = 0.5),\n            color = \"black\") +\n  labs(title = \"Barplot of Depression amongst the top 5 Courses\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth[,c(5)] <- lapply(health[,c(5)], function(x)\nrecode(x,\"year 1\" = 1,\"year 2\" = 2, \"year 3\" = 3 , \"year 4\" = 4, \"Year 1\" = 1, \"Year 2\" = 2, \"Year 3\" = 3))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(health$CGPA)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"3.00 - 3.49\" \"3.50 - 4.00\" \"2.50 - 2.99\" \"2.00 - 2.49\" \"0 - 1.99\"   \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stringr)\n\n# Example data\nCGPA <- c(\"3.00 - 3.49\",\"3.50 - 4.00\", \"2.50 - 2.99\" ,\"2.00 - 2.49\" ,\"0 - 1.99\"   )\n\n# Function to convert CGPA range to numeric\nconvertCGPA <- function(cgpa) {\n  lower <- as.numeric(str_extract(cgpa, \"\\\\d+\\\\.\\\\d+\"))\n  return(lower)\n}\n\n# Apply the conversion function to CGPA column\nconverted_CGPA <- sapply(CGPA, convertCGPA)\n\n# Output\nprint(converted_CGPA)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3.00 - 3.49 3.50 - 4.00 2.50 - 2.99 2.00 - 2.49    0 - 1.99 \n       3.00        3.50        2.50        2.00        1.99 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth[,c(6)] <- lapply(health[,c(6)], function(x)\nrecode(x,\"3.00 - 3.49\" = 3.00,\"3.50 - 4.00\" = 3.50, \"2.50 - 2.99\" = 2.50 , \"2.00 - 2.49\" = 2.00, \"0 - 1.99\" = 1.99  ))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data <- select(health,Age=Age, Gender=Gender,CGPA= CGPA, Course=Course,Married=Married, Depression=Depression, Anxiety=Anxiety, Panic_Attack = Panic_Attack,Treatment=Treatment)\n```\n:::\n\n\nCreate Logistic Regression Model\n\nLogistic regression is a statistical modeling technique used to predict the probability of an event occurring. It is commonly used when the dependent variable is binary or categorical. The model estimates the relationship between the independent variables and the log-odds of the event, using the logistic function. The logistic function maps the linear combination of predictors to a value between 0 and 1, representing the probability of the event.\n\n# Logistic Regression Assumptions\n\nThe first assumption is that there is a linear relationship between continuous independent variables and the logit of the outcome variable.\n\nIndependence of errors requires that there be no dependence between samples in the model, i.e. using the same individuals at different times.\n\nMulticollinearity refers to a relationship (correlation) between the independent variables and must be excluded from logistic regression models\n\n\n# Multiple logistic regression\n\nThe multiple logistic regression is used to predict the probability of class membership based on multiple predictor variables, as follow:\n\n# Model 1\n\n\nA logistic regression is said to provide a better fit to the data if it demonstrates an improvement over a model with fewer predictors. This is performed using the likelihood ratio test, which compares the likelihood of the data under the full model against the likelihood of the data under a model with fewer predictors. Removing predictor variables from a model will almost always make the model fit less well (i.e. a model will have a lower log likelihood), but it is necessary to test whether the observed difference in model fit is statistically significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data$CGPA <- ifelse(train_data$CGPA >= 3.00, 1, 0)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit logistic regression models\n\n# Research Question 1: Why is there a significant correlation between mental health status and CGPA among university students?\nmodel1 <- glm(CGPA ~ Anxiety, data = train_data, family = binomial)\n\n# Print the model summaries\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = CGPA ~ Anxiety, family = binomial, data = train_data)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.6557   0.2444   0.5371   0.5371   0.5371  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   1.8632     0.3583   5.201 1.99e-07 ***\nAnxietyYes    1.6333     1.0764   1.517    0.129    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 65.226  on 100  degrees of freedom\nResidual deviance: 61.890  on  99  degrees of freedom\nAIC: 65.89\n\nNumber of Fisher Scoring iterations: 6\n```\n:::\n:::\n\nBased on the output, the model suggests that there is no statistically significant association between Anxiety (as a predictor) and CGPA. The p-value for the AnxietyYes coefficient (p = 0.129) is greater than the conventional significance level (e.g., 0.05), indicating that the relationship between Anxiety and CGPA is not statistically significant in this model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate AIC and BIC\nAIC_val <- AIC(model1)\nBIC_val <- BIC(model1)\ncat(\"AIC:\", AIC_val, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAIC: 65.8904 \n```\n:::\n\n```{.r .cell-code}\ncat(\"BIC:\", BIC_val, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBIC: 71.12064 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- glm(CGPA ~ Depression, data = train_data, family = binomial)\n\n\n# Print the model summaries\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = CGPA ~ Depression, family = binomial, data = train_data)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.2166   0.4234   0.4735   0.4735   0.4735  \n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     2.1316     0.3998   5.332  9.7e-08 ***\nDepressionYes   0.2355     0.7241   0.325    0.745    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 65.226  on 100  degrees of freedom\nResidual deviance: 65.118  on  99  degrees of freedom\nAIC: 69.118\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n:::\n\nBased on the output, the model suggests that there is no statistically significant association between Depression (as a predictor) and CGPA. The p-value for the DepressionYes coefficient (p = 0.745) is greater than the conventional significance level (e.g., 0.05), indicating that the relationship between Depression and CGPA is not statistically significant in this model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate AIC and BIC\nAIC_val <- AIC(model1)\nBIC_val <- BIC(model1)\ncat(\"AIC:\", AIC_val, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAIC: 69.11786 \n```\n:::\n\n```{.r .cell-code}\ncat(\"BIC:\", BIC_val, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBIC: 74.3481 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- glm(CGPA ~ Panic_Attack, data = train_data, family = binomial)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = CGPA ~ Panic_Attack, family = binomial, data = train_data)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.2848   0.3908   0.3908   0.5732   0.5732  \n\nCoefficients:\n                Estimate Std. Error z value Pr(>|z|)    \n(Intercept)       2.5337     0.4646   5.453 4.95e-08 ***\nPanic_AttackYes  -0.8109     0.6720  -1.207    0.228    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 65.226  on 100  degrees of freedom\nResidual deviance: 63.795  on  99  degrees of freedom\nAIC: 67.795\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate AIC and BIC\nAIC_val <- AIC(model1)\nBIC_val <- BIC(model1)\ncat(\"AIC:\", AIC_val, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAIC: 67.79536 \n```\n:::\n\n```{.r .cell-code}\ncat(\"BIC:\", BIC_val, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBIC: 73.0256 \n```\n:::\n:::\n\n\nBased on the output you shared, the model suggests that there is no statistically significant association between Panic_Attack (as a predictor) and CGPA. The p-value for the Panic_AttackYes coefficient (p = 0.228) is greater than the conventional significance level (e.g., 0.05), indicating that the relationship between Panic_Attack and CGPA is not statistically significant in this model.\n\nAfter performing logistic regression, based on these results, it can be concluded that the research question of whether there is a significant correlation between mental health status and CGPA among university students is not supported. This implies that anxiety,Panic attack,Depression levels alone may not have a direct impact on students' academic performance, as measured by CGPA, in the context of this study.\n\nModel 2:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Research Question 2: How does the use of mental health resources, such as counseling or therapy, have a positive impact on academic performance?\n\nmodel2 <- glm(CGPA ~ Treatment, data = train_data, family = binomial)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = CGPA ~ Treatment, family = binomial, data = train_data)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.2246   0.4194   0.4194   0.4194   0.9005  \n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    2.3865     0.3695   6.459 1.05e-10 ***\nTreatmentYes  -1.6933     0.9415  -1.798   0.0721 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 65.226  on 100  degrees of freedom\nResidual deviance: 62.536  on  99  degrees of freedom\nAIC: 66.536\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate AIC and BIC\nAIC_val <- AIC(model2)\nBIC_val <- BIC(model2)\ncat(\"AIC:\", AIC_val, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAIC: 66.5357 \n```\n:::\n\n```{.r .cell-code}\ncat(\"BIC:\", BIC_val, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBIC: 71.76594 \n```\n:::\n:::\n\n\nAfter performing the logistic regression, Based on results the relationship between the use of mental health resources (Treatment) and CGPA, the coefficient for Treatment (TreatmentYes) is not statistically significant at conventional levels (p = 0.0721). This suggests that there is no strong evidence to support the hypothesis that the use of mental health resources, such as counseling or therapy, has a positive impact on academic performance, as measured by CGPA.\n\nIt is important to note that the p-value is relatively close to the conventional significance level of 0.05. This indicates a marginal level of significance, suggesting that there might be a weak relationship between the use of mental health resources and CGPA, but the evidence is not strong enough to conclude a significant positive impact on academic performance.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth[,c(2,7:11)] <- lapply(health[,c(2,7:11)], function(x)\nrecode(x,\"Yes\" = 1,\"No\" = 0, \"Female\" = 1 , \"Male\" = 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrelation <- cor(health$Panic_Attack, health$Anxiety)\nprint(correlation)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.08447828\n```\n:::\n:::\n\nThe correlation coefficient of 0.08447828 suggests a weak positive correlation between 'Panic_Attack' and 'Anxiety' in the data.So i will not include panic attacks\n\nModel 3:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Research Question 3: How does demographic factors, such as gender or ethnicity, influence the relationship between mental health and academic performance?\nmodel3 <- glm(CGPA ~ Gender + Anxiety +Age + Course + Married + Depression, data = train_data, family = binomial)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = CGPA ~ Gender + Anxiety + Age + Course + Married + \n    Depression, family = binomial, data = train_data)\n\nDeviance Residuals: \n     Min        1Q    Median        3Q       Max  \n-2.19207   0.00003   0.00003   0.00006   1.15677  \n\nCoefficients:\n                                Estimate Std. Error z value Pr(>|z|)\n(Intercept)                    2.158e+01  2.923e+04   0.001    0.999\nGenderMale                    -1.060e+00  1.124e+00  -0.943    0.346\nAnxietyYes                     2.576e+00  1.735e+00   1.485    0.138\nAge                           -5.414e-04  2.188e-01  -0.002    0.998\nCourseALA                     -4.283e+01  4.134e+04  -0.001    0.999\nCourseBanking Studies         -3.248e-03  4.134e+04   0.000    1.000\nCourseBCS                      2.272e-01  2.992e+04   0.000    1.000\nCourseBenl                    -5.410e-04  4.134e+04   0.000    1.000\nCourseBENL                    -1.577e-01  3.494e+04   0.000    1.000\nCourseBiomedical science      -1.987e+01  2.923e+04  -0.001    0.999\nCourseBiotechnology           -4.313e+01  4.134e+04  -0.001    0.999\nCourseBIT                     -2.122e+01  2.923e+04  -0.001    0.999\nCourseBusiness Administration -5.411e-04  4.134e+04   0.000    1.000\nCourseCommunication           -2.273e+00  4.134e+04   0.000    1.000\nCourseCTS                     -3.248e-03  4.134e+04   0.000    1.000\nCourseDiploma Nursing          3.374e-07  4.134e+04   0.000    1.000\nCourseDIPLOMA TESL            -5.411e-04  4.134e+04   0.000    1.000\nCourseEcons                   -1.957e+00  4.134e+04   0.000    1.000\nCourseengin                    3.003e-07  4.134e+04   0.000    1.000\nCourseEngine                  -6.753e-03  3.577e+04   0.000    1.000\nCourseEngineering             -1.986e+01  2.923e+04  -0.001    0.999\nCourseENM                     -2.273e+00  4.134e+04   0.000    1.000\nCourseFiqh                    -4.313e+01  4.134e+04  -0.001    0.999\nCourseFiqh fatwa              -2.706e-03  4.134e+04   0.000    1.000\nCourseHuman Resources         -4.313e+01  4.134e+04  -0.001    0.999\nCourseHuman Sciences          -3.248e-03  4.134e+04   0.000    1.000\nCourseIrkhs                   -1.519e+00  4.134e+04   0.000    1.000\nCourseIslamic education       -1.517e+00  4.134e+04   0.000    1.000\nCourseIslamic Education       -3.248e-03  4.134e+04   0.000    1.000\nCourseIT                      -3.248e-03  4.134e+04   0.000    1.000\nCourseKENMS                   -2.579e+00  4.134e+04   0.000    1.000\nCourseKirkhs                   1.060e+00  4.134e+04   0.000    1.000\nCourseKIRKHS                  -3.248e-03  4.134e+04   0.000    1.000\nCoursekoe                     -2.275e+00  4.134e+04   0.000    1.000\nCourseKoe                     -1.519e+00  4.134e+04   0.000    1.000\nCourseKOE                     -6.455e-01  3.215e+04   0.000    1.000\nCourseKop                     -2.576e+00  4.134e+04   0.000    1.000\nCourseLaw                     -1.960e+00  4.134e+04   0.000    1.000\nCourseLaws                     1.556e-01  3.577e+04   0.000    1.000\nCourseMalcom                   6.160e-01  4.134e+04   0.000    1.000\nCourseMarine science          -2.276e+00  4.134e+04   0.000    1.000\nCourseMathemathics             1.060e+00  4.134e+04   0.000    1.000\nCourseMHSC                     1.360e+00  4.134e+04   0.000    1.000\nCourseNursing                  2.999e-01  4.134e+04   0.000    1.000\nCoursePendidikan islam         3.021e-01  4.134e+04   0.000    1.000\nCoursePendidikan Islam        -3.909e-03  3.579e+04   0.000    1.000\nCoursepsychology              -1.960e+00  3.580e+04   0.000    1.000\nCoursePsychology              -2.165e-03  4.134e+04   0.000    1.000\nCourseRadiography              1.060e+00  4.134e+04   0.000    1.000\nCourseTAASL                    1.060e+00  4.134e+04   0.000    1.000\nCourseUsuluddin                6.170e-01  4.134e+04   0.000    1.000\nMarriedYes                     3.166e-01  1.875e+00   0.169    0.866\nDepressionYes                 -6.192e-01  1.518e+00  -0.408    0.683\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 65.226  on 100  degrees of freedom\nResidual deviance: 26.617  on  48  degrees of freedom\nAIC: 132.62\n\nNumber of Fisher Scoring iterations: 20\n```\n:::\n:::\n\n\nHypothesis testing\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_test <- anova(model3, test = \"Chi\")\nprint(anova_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel: binomial, link: logit\n\nResponse: CGPA\n\nTerms added sequentially (first to last)\n\n           Df Deviance Resid. Df Resid. Dev Pr(>Chi)  \nNULL                         100     65.226           \nGender      1    0.102        99     65.124   0.7492  \nAnxiety     1    3.418        98     61.706   0.0645 .\nAge         1    0.007        97     61.699   0.9343  \nCourse     47   34.909        50     26.790   0.9037  \nMarried     1    0.011        49     26.779   0.9163  \nDepression  1    0.162        48     26.617   0.6869  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate AIC and BIC\nAIC_val <- AIC(model3)\nBIC_val <- BIC(model3)\ncat(\"AIC:\", AIC_val, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAIC: 132.6168 \n```\n:::\n\n```{.r .cell-code}\ncat(\"BIC:\", BIC_val, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBIC: 271.2182 \n```\n:::\n:::\n\n\n\n\nBased on the logistic regression results, the relationship between demographic factors (Gender, Age, Course, Married) and mental health variables (Anxiety, Depression, Panic_Attack) with CGPA, it seems that several coefficients are not statistically significant at conventional levels. This means that there is no strong evidence to support the hypothesis that these demographic factors significantly influence the relationship between mental health and academic performance, as measured by CGPA.\n\nSpecifically, the coefficients for Gender Male (p = 0.564), Age (p = 0.968), Course (multiple categories with p-values close to 1.000), and MarriedYes (p = 0.949) are not statistically significant. Similarly, the coefficients for Anxiety Yes (p = 0.181), Depression Yes (p = 0.860), and Panic Attack Yes (p = 0.170) are not statistically significant.\n\nThese results suggest that based on the variables included in the model, there is no strong evidence to support the influence of gender, age, course, or marital status on the relationship between mental health variables and academic performance.\n\n\n",
    "supporting": [
      "final_checkIn3_sai_pothula_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}