{
  "hash": "5b88e1ec1ad774435c3079b6082bad66",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Justine Shakespeare\"\ndescription: \"Homework 2 for DACSS 603\"\ndate: \"03/27/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - hypothesis testing\n  - confidence intervals\n  - Justine Shakespeare\n---\n\n\n## Question 1\n\n*The time between the date a patient was recommended for heart surgery\nand the surgery date for cardiac patients in Ontario was collected by\nthe Cardiac Care Network (\"Wait Times Data Guide,\" Ministry of Health\nand Long-Term Care, Ontario, Canada, 2006). The sample mean and sample\nstandard deviation for wait times (in days) of patients for two cardiac\nprocedures are given in the accompanying table. Assume that the sample\nis representative of the Ontario population.*\n\n*Construct the 90% confidence interval to estimate the actual mean wait\ntime for each of the two procedures. Is the confidence interval narrower\nfor angiography or bypass surgery?*\n\nFirst we'll calculate the confidence interval manually with the formula:\nCI = (X bar) ± (t × s/sqrt(n))\n\nWe'll create objects in R to plug into this formula. We'll start with\nthe Bypass data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   1.0.1 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.3.0      ✔ stringr 1.5.0 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\n# Bypass data\nBypassSample <- 539\nBypassMean <- 19\nBypassSD <- 10\n\n# standard error\nBypassSEM <- BypassSD/sqrt(BypassSample)\n\n# t-value\nConfidenceLevel <- .90\nBYPtail <- (1-ConfidenceLevel)/2\nBypass_t_score <- qt(1-BYPtail, df=BypassSample-1)\n\n# plug everything back into the CI formula:\nCIBypass <- c(BypassMean-Bypass_t_score*BypassSEM, \n              BypassMean+Bypass_t_score*BypassSEM)\n\nprint(CIBypass)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n:::\n\n\nNow let's do the same for the Angiography data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAngioSample <- 847\nAngioMean <- 18\nAngioSD <- 9\n\n# standard error\nAngioSEM <- AngioSD/sqrt(AngioSample)\n\n# t-value\nConfidenceLevel <- .90\nAngtail <- (1-ConfidenceLevel)/2\nAngio_t_score <- qt(1-Angtail, df=AngioSample-1)\n\n# plug everything back in\n\nCIAngio <- c(AngioMean-Angio_t_score*AngioSEM, \n             AngioMean+Angio_t_score*AngioSEM)\n\nprint(CIAngio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n:::\n\n\nNow we can compare the confidence intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabs(diff(CIAngio)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.018436\n```\n:::\n\n```{.r .cell-code}\nabs(diff(CIBypass))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.419421\n```\n:::\n:::\n\n\nThe confidence interval for Angiography is narrower than for Bypass.\n\n## Question 2\n\n*A survey of 1031 adult Americans was carried out by the National Center\nfor Public Policy. Assume that the sample is representative of adult\nAmericans. Among those surveyed, 567 believed that college education is\nessential for success. Find the point estimate, p, of the proportion of\nall adult Americans who believe that a college education is essential\nfor success. Construct and interpret a 95% confidence interval for p.*\n\nWe can use the prop.test() function to find the point estimate and the\nconfidence interval:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x=567, n=1031, conf.level = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  567 out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\n## Question 3\n\n*Suppose that the financial aid office of UMass Amherst seeks to\nestimate the mean cost of textbooks per semester for students. The\nestimate will be useful if it is within \\$5 of the true population mean\n(i.e. they want the confidence interval to have a length of \\$10 or\nless). The financial aid office is pretty sure that the amount spent on\nbooks varies widely, with most values between \\$30 and \\$200. They think\nthat the population standard deviation is about a quarter of this range\n(in other words, you can assume they know the population standard\ndeviation). Assuming the significance level to be 5%, what should be the\nsize of the sample.*\n\nWe have to solve for n here. Because we have the standard deviation,\nwe'll use the CI formula that uses the z-score: CI = (X bar) ± (z ×\ns/sqrt(n))\n\nThis can be rewritten: n=((s\\*z)/5)\\^2\n\nUsing the data we have:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ3_s = (200-30)/4\nQ3_z = qnorm(.975)\n\n((Q3_s*Q3_z)/5)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5454\n```\n:::\n:::\n\n\n## Question 4\n\n*According to a union agreement, the mean income for all senior-level\nworkers in a large service company equals 500 per week. A representative\nof a women's group decides to analyze whether the mean income μ for\nfemale employees matches this norm. For a random sample of nine female\nemployees, ȳ = \\$410 and s = 90*\n\n### 4.A\n\n*Test whether the mean income of female employees differs from \\$500 per\nweek. Include assumptions, hypotheses, test statistic, and P-value.\nInterpret the result.*\n\nTo solve this problem I followed the steps of hypothesis testing:\n\n1\\. Specify the null hypothesis and alternative hypothesis\n\n2\\. Set the significance level (alpha)\n\n3\\. Calculate the test statistic\n\n4\\. Compare test statistics to the critical value determined by alpha,\nor check if p-value is smaller than alpha\n\n5\\. Draw a conclusion\n\n1.  Our null hypothesis is that the population mean is 500 dollars, our\n    alternative hypothesis is that the population mean is NOT \\$500\n\n2.  The significance level (alpha) is .05, or 5%\n\n3.  Calculate the test statistic:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ4_SD <- 90\nQ4_ymean <- 410\nQ4_umean <- 500\nQ4_s_size <- 9\nQ4_SEM <- Q4_SD/sqrt(Q4_s_size)\n\nQ4_T_Statistic <- (Q4_ymean - Q4_umean)/(Q4_SEM)\nQ4_T_Statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\n\n4.  Calculate the critical value so that we can compare it with the test\n    statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ4_Crit_Value <- qt(0.025, df=(Q4_s_size-1))\nQ4_Crit_Value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -2.306004\n```\n:::\n:::\n\n\nThe critical value (on the lower tail end) is -2.3060. Because the test\nstatistic is smaller than the critical value (and larger in absolute\nterms), we can conclude that we should reject the null hypothesis.\n\n4.  (continued) calculate the p-value to check to see if it is smaller\n    than alpha.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ4_p_value <- pt(Q4_T_Statistic, df = (Q4_s_size-1), lower.tail = TRUE)*2\nQ4_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nThe p-value is 0.01707, which is smaller than our alpha (.05). 0.01707\n\\< 0.05 This again means that we can reject the null hypothesis.\n\n5.  Draw a conclusion\n\nBecause the test statistic (-3) is in absolute terms larger than the\ncritical values (2.30) AND because the p-value (0.01707) is less than\nthe alpha levelof .05, we can reject the null hypothesis\n\nNote that when we calculate the confidence interval of these values we\ncan also see that the estimated population mean here is outside of a 95%\nCI.\n\nTo calculate the confidence level we'll first create some objects we'll\nneed in our formulas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nConfLevel <- 0.95\nQ4_tail_area <- (1-ConfLevel)/2\nQ4_tscore <- qt(p=1-Q4_tail_area, df = Q4_s_size-1)\n\n# Then, using this and some of the objects we created earlier we'll plug everything in: \nQ4_CI <- c(Q4_ymean - (Q4_tscore * Q4_SEM), Q4_ymean + (Q4_tscore * Q4_SEM))\n\nprint(Q4_CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 340.8199 479.1801\n```\n:::\n:::\n\n\nWe can see here that \\$500 is not within the 95% confidence interval,\nwhich is another reason we can reject the null hypothesis.\n\n### 4.B\n\n*Report the P-value for Ha: μ \\< 500. Interpret.*\n\nTo calculate a one sided P-value you do not need to multiply the formula\nby 2 and you need to specify that we're only looking at one side. An\nalternative hypothesis of μ \\< 500 means the null hypothesis is μ \\>=\n500. We need to specify that we are looking at the lower tail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ4_p_value1 <- pt(Q4_T_Statistic, df = (Q4_s_size-1), lower.tail = TRUE)\nQ4_p_value1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nThe p-value here is even lower than it was for the two sided test, it is\n0.0085. We can definitely reject the null hypothesis that the true\npopulation mean is over \\$500.\n\n### 4.C\n\n*Report and interpret the P-value for Ha: μ \\> 500.*\n\nTo calculate the P-value for Ha: μ \\> 500 we run the same formula as\nbefore but we specify that we're *not* interested in the lower tail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ4_p_value2 <- pt(Q4_T_Statistic, df = (Q4_s_size-1), lower.tail = FALSE)\nQ4_p_value2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nThe p-value for this one sided test is quite large. It means that we\nshould not reject the null hypothesis that the true population mean is\nless than \\$500.\n\nTo test these p-values we can add them up.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ4_p_value1 + Q4_p_value2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\nWe find that they add up to 1.\n\n## Question 5\n\n*Jones and Smith separately conduct studies to test H0: μ = 500 against\nHa: μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0.\nSmith gets ȳ = 519.7, with se = 10.0.*\n\n### 5.A\n\n*Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97\nand P-value = 0.049 for Smith.*\n\nFirst we can create some objects to represent the values for this\nquestion. Then we can use those to get the test statistic and the\np-value for Jones and Smith.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ5_SEM <- 10 # they have the same standard error\nJones_ymean <- 519.5\nSmith_ymean <- 519.7\nQ5_s_size <- 1000 # they have the same sample size\n\nQ5_umean <- 500\n\n# calculate the test statistic and p-value for Jones:\nJones_T_Statistic <- (Jones_ymean - Q5_umean)/(Q5_SEM)\nJones_T_Statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\n# we find that Jones' test statistic is 1.95. We can use that to find the p-value:\nJones_p_value <- pt(Jones_T_Statistic, df = (Q5_s_size-1), lower.tail = FALSE)*2\nJones_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\n# Calculate test statistic and p-value for Smith:\nSmith_T_Statistic <- (Smith_ymean - Q5_umean)/(Q5_SEM)\nSmith_T_Statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n# we find that Smith's test statistic is 1.97. We can use that to find the p-value:\nSmith_p_value <- pt(Smith_T_Statistic, df = (Q5_s_size-1), lower.tail = FALSE)*2\nSmith_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n### 5.B\n\n*Using α = 0.05, for each study indicate whether the result is\n\"statistically significant.\"*\n\nAbove we found the p-value for both Jones and Smith, we can use that to\nshow how those values compare to alpha set at 0.05.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\n\nJones_p_value < alpha\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n\n```{.r .cell-code}\nSmith_p_value < alpha\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\n\nThis shows that technically Jones' p-value is not statistically\nsignificant because it is more than the alpha of 0.05, but Smith's\np-value is technically statistically significant because it is less than\nthe alpha.\n\n### 5.C\n\n*Using this example, explain the misleading aspects of reporting the\nresult of a test as \"P ≤ 0.05\" versus \"P \\> 0.05,\" or as \"reject H0\"\nversus \"Do not reject H0,\" without reporting the actual P-value.*\n\nThis question demonstrates how close two results can be and still\ntechnically not have the same significance level. In these cases it is\nimportant to include the p-value so that readers can put the results\ninto context.\n\n## Question 6\n\n*A school nurse wants to determine whether age is a factor in whether\nchildren choose a healthy snack after school. She conducts a survey of\n300 middle school students, with the results below. Test at α = 0.05 the\nclaim that the proportion who choose a healthy snack differs by grade\nlevel. What is the null hypothesis? Which test should we use? What is\nthe conclusion?*\n\nSince we're dealing with categorical variables (grade and the choice of\na healthy or unhealthy snack) we should use a chi-square test. First\nwe'll create the dataframe we'll need to run the test in r.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs <- matrix(c(31, 69, 43, 57, 51, 49), nrow=3, byrow = TRUE)\ndimnames(obs) <- list(Grade = c(\"Grade_6\", \"Grade_7\", \"Grade_8\"),\n                      Snack = c(\"healthy\", \"unhealthy\"))\n\nobs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         Snack\nGrade     healthy unhealthy\n  Grade_6      31        69\n  Grade_7      43        57\n  Grade_8      51        49\n```\n:::\n:::\n\n\nThen we can run the chi-square test and print the result:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nChiResult <- chisq.test(obs)\n\nprint(ChiResult)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  obs\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\n\nGiven the p-value \\< 0.05, we can reject the null hypothesis that grade\nlevel does not have an effect on the choice of healthy snack. The\nrelatively high X-squared value also indicates that there is a\nmeaningful difference in the choices made by kids in different grade\nlevels.\n\n## Question 7\n\n*Per-pupil costs (in thousands of dollars) for cyber charter school\ntuition for school districts in three areas are shown. Test the claim\nthat there is a difference in means for the three areas, using an\nappropriate test. What is the null hypothesis? Which test should we use?\nWhat is the conclusion?*\n\nThe null hypothesis is that all three districts have equal average\ntuition. We can use the ANOVA test since we are comparing three means.\n\nFirst we'll create the dataframe in r:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nArea1 <- c(6.2, 9.3, 6.8, 6.1, 6.7, 7.5)  \nArea2 <- c(7.5, 8.2, 8.5, 8.2, 7.0, 9.3)\nArea3 <- c(5.8, 6.4, 5.6, 7.1, 3.0, 3.5)\n\nQ7df <- data.frame(Area1, Area2, Area3)\n\nQ7df_PL <- pivot_longer(Q7df, cols = c(Area1, Area2, Area3), names_to = \"district\", values_to = \"tuition\")\nQ7df_PL\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 18 × 2\n   district tuition\n   <chr>      <dbl>\n 1 Area1        6.2\n 2 Area2        7.5\n 3 Area3        5.8\n 4 Area1        9.3\n 5 Area2        8.2\n 6 Area3        6.4\n 7 Area1        6.8\n 8 Area2        8.5\n 9 Area3        5.6\n10 Area1        6.1\n11 Area2        8.2\n12 Area3        7.1\n13 Area1        6.7\n14 Area2        7  \n15 Area3        3  \n16 Area1        7.5\n17 Area2        9.3\n18 Area3        3.5\n```\n:::\n:::\n\n\nNow that we have a dataframe with one continuous variable and one\ncategorical variable, we can use the anova test function in r `aov()` to\ntest our hypothesis. This type of hypothesis test is appropriate for\nthis scenario because we want to compare the mean of three groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ7o <- aov(tuition ~ district, data = Q7df_PL)\nsummary(Q7o)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \ndistrict     2  25.66  12.832   8.176 0.00397 **\nResiduals   15  23.54   1.569                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nGiven that the p value here is less than 0.01, we can reject the null\nhypothesis that the mean tuition is the same at all three schools.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}