{
  "hash": "2e53c67fd48476896fb420d3fa746be3",
  "result": {
    "markdown": "---\ntitle: \"Final Project \"\nauthor: \"Xiaoyan\"\ndescription: \"Template of course blog qmd file\"\ndate: \"05/17/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - finalpart1\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(ggplot2)\nlibrary(MASS)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'MASS'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:dplyr':\n\n    select\n```\n:::\n\n```{.r .cell-code}\nlibrary(reshape2)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'reshape2'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:tidyr':\n\n    smiths\n```\n:::\n:::\n\n# {.tabset}\n\n## Introduction and background\n\n The implementation of the one-child policy by the Chinese government in 1979 led to an increase in the number of families with only one child and a unique family structure known as the \"four-two-one\" model, consisting of four grandparents, two parents, and one child. While being part of such a family structure provides certain advantages in terms of family and social resources, children without siblings, commonly referred to as \"only children,\" may experience various physical and socio-psychological challenges during their development.\nOne notable concern is the increased risk of overweight and obesity among only children. These children are more likely to struggle with weight-related issues compared to their counterparts who have one or more siblings. Additionally, the psychosocial consequences associated with being an only child are also worth investigating.\nIn this context, it is important to explore not only the relationship between overweight/obesity and mental health in young adolescents but also how the presence or absence of siblings and other factors into this relationship.\nOverall, investigating the link between overweight/obesity, mental health, and sib-size in young adolescents within the context of the one-child policy can shed light on the potential challenges faced by only children and contribute to a better understanding of their overall well-being.\n\n \n\n## research questions\n1. Does obesity positively related to depression rate?\n2. What are factors that affects obesity?\n3. Does sibling or obesity directly related to depression?\n\n## key predictors\n1. depression rate\n2. sibling number\n3. obesity rate\n4. Family location, finance and education\n\n\n## hypothesis\n1. Higher obesity rate increase the risk of depression\n2. higher family income increase the rate of obesity\n3. More sibling reduce the risk of depression \n\n\n## data description\n### overlook of data\n\n::: {.cell}\n\n```{.r .cell-code}\ndata<-read_excel(\"/Users/cassie199/Desktop/23spring/603_Spring_2023-1/posts/_data/mentalhealth_data.xlsx\")\nhead(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 29\n  T0depres…¹ T0anx…² T1dep…³ T1anx…⁴ Height Weight    WC    HC   SBP   DBP   FBG\n       <dbl>   <dbl>   <dbl>   <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1         31      35      41      35   153.   34.6    58  67      98    60   4.4\n2         35      24      35      25   172.   46.1    63  78     110    70   3.9\n3         31      34      37      26   146.   38.9    72  77.7   102    62   4.6\n4         27      31      42      35   162.   46.8    62  80     116    80   4.5\n5         31      26      49      33   154.   36.4    56  72      90    60   4.2\n6         30      28      47      32   164.   40.6    55  73     102    70   3.7\n# … with 18 more variables: TC <dbl>, TG <dbl>, `HDL-C` <dbl>, `LDL-C` <dbl>,\n#   BMI <dbl>, WHR <dbl>, WtHR <dbl>, `Family location` <dbl>,\n#   `Number of siblings` <dbl>,\n#   `How much time do you spend with your father in elementary school?` <dbl>,\n#   `How much time do you spend with your mother in elementary school?` <dbl>,\n#   `Father’s education level` <dbl>, `Mother’s education level` <dbl>,\n#   `Family financial situation` <dbl>, `Sleeping hours` <dbl>, …\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 728\n```\n:::\n\n```{.r .cell-code}\nplot(data$T0depression~data$BMI)\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\nThis dataset including 1348 variables and 29 columns. there are 728 NA in this data set. all variables was presented as numberic data. descriptive data was also presented as degrees such as education level, family financial situation and depression rate. By pre-plotting depression rate vs BMI, we can see that some ouliers may need to deal with and there is no siginifcant disrtibution on graph. More data processing is needed in future process.\n\n\nModified column name \n\n::: {.cell}\n\n```{.r .cell-code}\nvariables <- c(\"Family location\", \"Number of siblings\", \" time  spend with father in elementary school?\", \n          \" time spend with mother in elementary school?\", \"Father’s education level\", \n          \"Mother’s education level\", \"Family financial situation\", \"Sleeping hours\", \"Skipping breakfast\", \n          \"Vigorous\", \"Moderate\")\nabreviations <- c(\"FL\", \"NS\", \"TFE\", \"TME\", \"FEL\", \"MEL\", \"FS\", \"SL\", \"SB\", \"VG\", \"MD\")\n\n\ncat(\"varible table\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nvarible table\n```\n:::\n\n```{.r .cell-code}\nvariable_table <- data.frame(variables, abreviations)\nvariable_table\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                        variables abreviations\n1                                 Family location           FL\n2                              Number of siblings           NS\n3   time  spend with father in elementary school?          TFE\n4    time spend with mother in elementary school?          TME\n5                        Father’s education level          FEL\n6                        Mother’s education level          MEL\n7                      Family financial situation           FS\n8                                  Sleeping hours           SL\n9                              Skipping breakfast           SB\n10                                       Vigorous           VG\n11                                       Moderate           MD\n```\n:::\n\n```{.r .cell-code}\ncolnames(data)<-c(\"T0depression\",\"T0anxiety\",\"T1depression\",\"T1anxiety\",\"Height\",\"Weight\",\"WC\",\"HC\",\"SBP\",\"DBP\",\"FBG\",\"TC\",\"TG\",\"HDL-C\",\"LDL-C\",\"BMI\",\"WHR\",\"WtHR\",\"FL\", \"NS\", \"TFE\", \"TME\", \"FEL\", \"MEL\", \"FS\", \"SL\", \"SB\",\"Vigorous\",\"Moderate\")\n```\n:::\n\n### parameter explaination\nBMI (body mass index) in this study is used as indicator of obisity. NIH divided BMI value into three levels as table below.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the data frame for BMI categories\nbmi_levels <- c(\"Underweight\", \"Normal Weight\", \"Overweight\")\nbmi_values <- c(\"<18.5\", \"18.5-24.9\", \">=25\")\nbmi_table <- data.frame(Category = bmi_levels, BMI = bmi_values)\n\n\n# Print the BMI category table\ncat(\"\\nBMI Categories\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBMI Categories\n```\n:::\n\n```{.r .cell-code}\nprint(bmi_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       Category       BMI\n1   Underweight     <18.5\n2 Normal Weight 18.5-24.9\n3    Overweight      >=25\n```\n:::\n:::\n\n### data explanatory\nSome key predictors were plotted. The distribution of family location was plotted in the first chart and the distribution of family financial situation were plotted in the second chart.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$proportion <- data$FL / sum(data$FL)\ndata$category <- factor(data$FS, levels = c(\"1\", \"2\", \"3\",\"4\"))\nggplot(data, aes(x = \"\", y = proportion, fill = category)) +\n  geom_bar(stat = \"identity\", width = 1) +\n  coord_polar(theta = \"y\") +\n  labs(fill = \"Category\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndata$proportion1 <- data$FS / sum(data$FS)\nggplot(data, aes(x = \"\", y = proportion1, fill = category)) +\n  geom_bar(stat = \"identity\", width = 1) +\n  coord_polar(theta = \"y\") +\n  labs(fill = \"Category\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\nA scatter plot was used to visualize the relationship between skipping breakfast and BMI rate. Only by scatter plot it is difficult to observe the relationship between two varibales. Therefore, further analysis is needed \n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = SB, y = BMI)) +\ngeom_jitter(width = 0.2, height = 0, color = \"indianred\", alpha = 0.5) +\n  xlab(\"skipping breakfast\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 36 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n## hypothesis test\n\n### 1. Higher obesity rate increase the risk of depression\nH0=no relationship between obesity rate and the risk of depression\n\nHa=higher obesity rate increases the risk of depression\n\nIn order to prove this hypothesis, linear model was used to calculate relationship between depression rate and BMI.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#linear regression of depresison and BMI\nlm0<-lm(T1depression ~ BMI, data = data)\nsummary(lm0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = T1depression ~ BMI, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-19.2371  -6.2000   0.1719   6.2964  21.9845 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 40.75036    1.50580  27.062   <2e-16 ***\nBMI         -0.09528    0.07803  -1.221    0.222    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.093 on 1308 degrees of freedom\n  (38 observations deleted due to missingness)\nMultiple R-squared:  0.001139,\tAdjusted R-squared:  0.0003749 \nF-statistic: 1.491 on 1 and 1308 DF,  p-value: 0.2223\n```\n:::\n:::\n\nThe BMI coefficient (-0.09528) represents the estimated change in the depression score for a one-unit increase in BMI. For each unit increase in BMI, the depression score decreases by 0.09528. With p-value of 0.222, the coefficient is not significant. Therefore, there is no strong evidence of a linear relationship between BMI and depression. the residuals range from -19.2371 to 21.9845. The residual standard error is relatively high also indicates the model is not fit to the data. F-staistic gives an overall sinificance of the model and with a high p-value, this model is also not statically significant as a whole. The multiple R-squared value (0.001139) represents the proportion of variance in the depression score explained by the model and only 0.1139% of the variability in depression can be attributed to the linear relationship with BMI.\nThe adjusted R-squared value (0.0003749) adjusts the multiple R-squared value for the number of predictors in the model. It penalizes the inclusion of unnecessary predictors. A lower adjusted  R-squared suggests that the model does not provide a good fit to the data. \n\nIn summary, based on the provided output, there is no strong evidence to support a linear relationship between BMI and depression. The coefficient for BMI is not statistically significant, and the model's overall fit is weak (low R-squared values and non-significant F-statistic). \n\n::: {.cell}\n\n```{.r .cell-code}\n#diagnostic\npar(mfrow = c(2,2))\nplot(lm0)\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nLinear regression diagnostic plot was used to  evaluate the performance.In residual vs fitted plot, the a horizontal red line represent the mean or expected value of the residuals. and the residuals are evenly distributes above and below the horizontal line. This indicates the linear model was fitted to our data. In normal Q_Q plot, the straight pattern suggests that the residuals of a linear regression model follow a normal distribution,supporting the assumption of normality. In a scale-location plot , a straight red line typically indicates homoscedasticity, which means that the residuals have a constant variance across different levels of the predictor variable(s). The scale-location plot detects any systematic patterns in the spread (variance) of the residuals.Here, the plot suggested that the assumption of homoscedasticity is met.\nAccording to these diagnostics，the linear model is reliable and presenting the relationship properly.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#visualization\nggplot(data, aes(x = BMI, y = T1depression)) +\n  geom_point(color = \"indianred\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkred\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 38 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 38 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplott1depression<-data$T1depression[1:length(predict(lm0))]\nplot_data <- data.frame(Predicted_value = predict(lm0),  \n                       Observed_value = plott1depression)\nggplot(plot_data, aes(x = Predicted_value, y = Observed_value)) +\n                  geom_point() +\n                 geom_abline(intercept = 0, slope = 1, color = \"green\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n:::\n\nIn addition to BMI, several other variables were included in the analysis to examine their relationship with depression rate in children. Two variables, namely time spent with father in elementary school and frequency of skipping breakfast, emerged as significant factors influencing children's depression rate.\n\nThe findings revealed that less time spent with father in elementary school was associated with a higher likelihood of experiencing an increase in depression rate among children. This suggests the importance of positive father-child interactions and involvement during this critical period of development.The analysis showed that skipping breakfast more frequently was also linked to a higher depression rate in children. With diagnostic, there was not a substantial deviation from the assumptions of the model. This suggests that the linear regression analysis provided a reasonable fit to the data and supported the interpretation of the results.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#linear regression model 2\nlm1<-lm(T1depression ~ BMI+NS+TFE+TME+FEL+MEL+FL+SL+SB, data = data)\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = T1depression ~ BMI + NS + TFE + TME + FEL + MEL + \n    FL + SL + SB, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-22.3852  -5.9985   0.1987   6.4197  21.1941 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 42.55778    2.88686  14.742  < 2e-16 ***\nBMI         -0.10358    0.07798  -1.328   0.1843    \nNS           0.72821    0.51703   1.408   0.1592    \nTFE         -0.57069    0.24271  -2.351   0.0189 *  \nTME         -0.18783    0.30401  -0.618   0.5368    \nFEL         -0.28747    0.24332  -1.181   0.2376    \nMEL         -0.22372    0.26894  -0.832   0.4056    \nFL           0.09777    0.18801   0.520   0.6031    \nSL           0.10706    0.38873   0.275   0.7831    \nSB           1.47402    0.31288   4.711 2.73e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.967 on 1300 degrees of freedom\n  (38 observations deleted due to missingness)\nMultiple R-squared:  0.0379,\tAdjusted R-squared:  0.03124 \nF-statistic: 5.691 on 9 and 1300 DF,  p-value: 9.18e-08\n```\n:::\n\n```{.r .cell-code}\n#diagnostic\npar(mfrow = c(2,2))\nplot(lm1)\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\nTo verify if the model is correct, some of varibles with large p value are deleted for backward elimination. \"Time spend with mother in elementary school\", \"Father's educaion level\", \"sleeping time\" are deleted comparing to the model before. In this case, \"Time spend with father in elementary school\" and \"skipping breakfast\" still above the significant level. By comparing the adjusted R square of two models(0.03124 and 0.03321). There was no not two big difference in these two models. \n\n::: {.cell}\n\n```{.r .cell-code}\n#linear regression model 3\nlm2<-lm(T1depression ~ BMI+NS+TFE+FEL+SB, data = data)\nsummary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = T1depression ~ BMI + NS + TFE + FEL + SB, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-22.9398  -6.0354   0.2289   6.3596  20.8288 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 41.91051    2.17737  19.248  < 2e-16 ***\nBMI         -0.10798    0.07716  -1.399  0.16193    \nNS           0.73126    0.45738   1.599  0.11011    \nTFE         -0.64654    0.20647  -3.131  0.00178 ** \nFEL         -0.33519    0.23154  -1.448  0.14795    \nSB           1.51314    0.31049   4.873 1.23e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.959 on 1304 degrees of freedom\n  (38 observations deleted due to missingness)\nMultiple R-squared:  0.03681,\tAdjusted R-squared:  0.03312 \nF-statistic: 9.967 on 5 and 1304 DF,  p-value: 2.26e-09\n```\n:::\n\n```{.r .cell-code}\n#diagnostic \npar(mfrow = c(2,3))\nplot(lm2)\n#compare predicted value with observe value\nlm3<-lm(T1depression ~ TFE, data = data)\n\nplot_data <- data.frame(Predicted_value = predict(lm3),  \n                       Observed_value = data$T1depression[1:length(predict(lm3))])\nggplot(plot_data, aes(x = Predicted_value, y = Observed_value)) +\n                  geom_point() +\n                 geom_abline(intercept = 0, slope = 1, color = \"green\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nPredicted value was plotted between first linear model and actual value.The regression line was slightly decreasing. This also implies the linear model is not statistic significant. \nIn summary, based on the provided output, there is no strong evidence to support a linear relationship between BMI and depression. The coefficient for BMI is not statistically significant, and the model's overall fit is weak (low R-squared values and non-significant F-statistic). Therefore, we fail to reject the null hypothesis.  \n\n\n### 2. higher family income increase the rate of obesity\nH0=no relationship between family income and rate of obesity \n\nHa=higher family income increase the rate of obesity\n\nBased on this data, we may also explore what factors may affect the obesity rate. Here we made a hypothsis as higher family income increase the rate of obesity. Due to most of the variables are ordinal variables, ordinal logistic regression is applied in this slot to verify the hypothesis. \n\n::: {.cell}\n\n```{.r .cell-code}\n#convert BMI to ordinal varible\ndata$BMI_category <- cut(data$BMI, \n                       breaks = c(-Inf, 18.5, 24.9, Inf),\n                       labels = c(\"Underweight\", \"Normal weight\", \"Overweight\"))\ndata$BMI_rank <- as.factor(unclass(data$BMI_category))\n\n# Visualizing data\n# Filter out rows with NA values in BMI_rank or FS\nfiltered_data <- data[complete.cases(data$BMI_rank, data$FS), ]\n\n# Create the plot with filtered data\nggplot(filtered_data, aes(x = BMI_category, y = FS)) +\n  geom_boxplot(size = 0.75, color = \"indianred\") +\n  geom_jitter(alpha = 0.5, color = \"red\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))+\n  ylab(\"Financial Situation\")\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# #Fit BMI rank and family finanacial situation into ordinal logit model\nmodel <- polr(BMI_rank ~ FS, data = data, Hess=TRUE)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\npolr(formula = BMI_rank ~ FS, data = data, Hess = TRUE)\n\nCoefficients:\n     Value Std. Error t value\nFS -0.1883    0.07865  -2.394\n\nIntercepts:\n    Value   Std. Error t value\n1|2 -0.7067  0.2554    -2.7672\n2|3  2.6195  0.2828     9.2639\n\nResidual Deviance: 2173.226 \nAIC: 2179.226 \n(36 observations deleted due to missingness)\n```\n:::\n\n```{.r .cell-code}\n#p value\nctable <- coef(summary(model))\np <- pnorm(abs(ctable[, \"t value\"]), lower.tail = FALSE) * 2\nctable <- cbind(ctable, \"p value\" = p)\nctable\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         Value Std. Error   t value      p value\nFS  -0.1883107  0.0786533 -2.394187 1.665724e-02\n1|2 -0.7067002  0.2553870 -2.767174 5.654453e-03\n2|3  2.6194751  0.2827624  9.263873 1.971474e-20\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Getting odds-ratio\nexp(coef(model))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       FS \n0.8283573 \n```\n:::\n:::\n\nThe findings of the study indicate that financial situation (FS) is significantly associated with BMI ranks. The coefficient of -0.1883 suggests that higher financial situation is linked to a decreased likelihood of being in a higher BMI rank. Specifically, individuals with higher financial situation are less likely to fall into the normal weight category compared to the underweight category (1|2) with a coefficient of -0.7067. Conversely, they are more likely to be in the overweight category compared to the normal weight category (2|3) with a coefficient of 2.6195. These relationships were found to be statistically significant, indicating that the observed associations are unlikely to occur by chance. Furthermore, the inclusion of additional variables in the model improved its predictive ability, as indicated by the slightly lower AIC value. These findings highlight the importance of considering financial situation as a factor influencing BMI ranks and provide insights into the complex relationship between socioeconomic factors and weight status.\nThe null hypothsis is therefore rejected\n\n::: {.cell}\n\n```{.r .cell-code}\n#introduce more variables to compare\n\nLR1<-polr(formula = BMI_rank~SL+SB+FS, data = data, Hess = TRUE, method = \"logistic\")\nSUM1<-summary(LR1)\nSUM1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\npolr(formula = BMI_rank ~ SL + SB + FS, data = data, Hess = TRUE, \n    method = \"logistic\")\n\nCoefficients:\n     Value Std. Error t value\nSL -0.5179    0.09863  -5.250\nSB  0.2064    0.07715   2.676\nFS -0.1336    0.08003  -1.669\n\nIntercepts:\n    Value   Std. Error t value\n1|2 -1.3558  0.3381    -4.0102\n2|3  2.0251  0.3551     5.7024\n\nResidual Deviance: 2136.853 \nAIC: 2146.853 \n(36 observations deleted due to missingness)\n```\n:::\n\n```{.r .cell-code}\n#p value\nctable2 <- coef(summary(LR1))\np <- pnorm(abs(ctable2[, \"t value\"]), lower.tail = FALSE) * 2\nctable2 <- cbind(ctable2, \"p value\" = p)\nctable2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         Value Std. Error   t value      p value\nSL  -0.5178720 0.09863452 -5.250414 1.517580e-07\nSB   0.2064347 0.07715030  2.675748 7.456279e-03\nFS  -0.1336130 0.08003340 -1.669465 9.502524e-02\n1|2 -1.3557600 0.33807702 -4.010210 6.066466e-05\n2|3  2.0251068 0.35513075  5.702426 1.181141e-08\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(SUM1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         Value Std. Error   t value\nSL  -0.5178720 0.09863452 -5.250414\nSB   0.2064347 0.07715030  2.675748\nFS  -0.1336130 0.08003340 -1.669465\n1|2 -1.3557600 0.33807702 -4.010210\n2|3  2.0251068 0.35513075  5.702426\n```\n:::\n\n```{.r .cell-code}\nexp(coef(SUM1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        Value Std. Error      t value\nSL  0.5957870   1.103663 5.245348e-03\nSB  1.2292875   1.080204 1.452320e+01\nFS  0.8749286   1.083323 1.883478e-01\n1|2 0.2577513   1.402249 1.812958e-02\n2|3 7.5769204   1.426367 2.995934e+02\n```\n:::\n\n```{.r .cell-code}\n### Predict probability\n# Create a data frame with possible IV values\nnewdat <- data.frame(\n  FS = rep(1:5, each = 272),\n  SL = rep(1:4, each = 340),\n  SB = rep(1:4, each = 340),\n  BMI = rep(seq(from = 12.8, to = 39, length.out = 340), 4))\n  \n\n\n# Get the predicted probability \n\nnewdat <- cbind(newdat, predict(LR1, newdat, type = \"probs\"))\n\n# Keeping the category with the highest probability\nlnewdat <- melt(newdat, id.vars = c(\"FS\", \"SL\", \"SB\",\"BMI\"),\n                variable.name = \"Level\", value.name=\"Probability\")\n\n\n# Visualizing probability\nggplot(lnewdat, aes(x = BMI, y = Probability, colour = Level)) +\n  geom_line() + facet_grid(FS ~ SL, labeller=\"label_both\")\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#plot\nggplot(data, aes(x = SL, y = BMI)) +\n  geom_point(color = \"red4\") +\n  geom_smooth(method = \"lm\", se = FALSE,color=\"indianred\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 36 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 36 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-15-2.png){width=672}\n:::\n:::\n\n \n\n### 3. More sibling reduce the risk of both depression and anxiety. \nH0=no relationship between sibling numbers and depression rate\n\nHa=more siblings reduce the risk of depression\n\nThe sibling numbers here indicates as 1: only child and 2: have siblings. Therefore, a welch two sample t-test and corelation test were performed to explore the relationship. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=subset(data,!is.na(NS)), aes(x = factor(NS), y = T1depression)) +\n  geom_boxplot(color = \"red4\")+\n  geom_jitter(color = \"tomato1\")+\n  xlab(\"Number of sibling\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing non-finite values (`stat_boxplot()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\nvar1<-as.numeric(data$T1depression)\nvar2<-as.numeric(data$NS)\n```\n:::\n\n\n\nThe analysis revealed a positive correlation between the number of siblings and depression score, with a sample estimate of the correlation coefficient (rho) of 0.0716. This suggests that as the number of siblings increases, the depression score tends to be higher. The statistical significance of this correlation was confirmed by a p-value of 0.0085, indicating that the observed relationship is unlikely to occur by chance. Furthermore, a Welch t-test was conducted, which demonstrated that the group with more siblings had a significantly higher depression index. Based on these findings, we can conclude that there is a positive relationship between the number of siblings and depression score, suggesting that having more siblings may contribute to increased levels of depression.\nTherefore, we conclude that number of siblings has a postive relationship with depression score.\n\n## Conclusion\n\n\n  In this study, we investigated the relationship between depression, obesity, family financial situation, and sibling numbers among young adolescents.      \nFirstly, we examined the association between depression and obesity using various linear regression models. The results indicated that there was no significant relationship between depression and obesity in this population.\nNext, we focused on the impact of family financial situation on obesity using ordinal logistic regression. Our findings revealed that higher family financial situation was associated with a higher likelihood of having abnormal weight, including being underweight or overweight, rather than having a normal weight.\nFurthermore, we tested the hypothesis regarding the association between depression and sibling numbers using a Welch t-test. Interestingly, the results showed that adolescents with siblings had significantly lower depression scores compared to those without siblings.\n      Overall, this study contributes to our understanding of the factors influencing the mental and physical well-being of young adolescents. The findings suggest that family financial situation plays a role in the occurrence of abnormal weight, while the presence of siblings appears to have a protective effect against depression. These results emphasize the importance of considering familial and social factors in addressing the mental and physical health of young individuals. Further research and interventions can build upon these findings to develop strategies for promoting healthier outcomes in this population.\n\n\n\n\n",
    "supporting": [
      "XiaoyanHu_Finalproject3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}