{
  "hash": "3b31f06571359ec84b9117fd2dd2841d",
  "result": {
    "markdown": "---\ntitle: \"Homework 3\"\nauthor: \"Caitlin Rowley\"\ndescription: \"Homework 3\"\ndate: \"04/11/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw3\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n# load libraries\nlibrary(tidyr)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(magrittr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'magrittr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:tidyr':\n\n    extract\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(markdown)\nlibrary(ggtext)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggtext' was built under R version 4.2.2\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readxl' was built under R version 4.2.2\n```\n:::\n:::\n\n\n### Question 1\n\n| United Nations (Data file: UN11in alr4) The data in the file UN11 contains several variables,\n| including ppgdp, the gross national product per person in U.S. dollars, and fertility, the birth\n| rate per 1000 females, both from the year 2009. The data are for 199 localities, mostly UN\n| member countries, but also other areas such as Hong Kong that are not independent countries.\n| The data were collected from the United Nations (2011). We will study the dependence of\n| fertility on ppgdp.\n| (a) Identify the predictor and the response.\n| (b) Draw the scatterplot of fertility on the vertical axis versus ppgdp on the horizontal axis\n| and summarize the information in this graph. Does a straight-line mean function seem to\n| be plausible for a summary of this graph?\n| (c) Draw the scatterplot of log(fertility) versus log(ppgdp) using natural logarithms. Does\n| the simple linear regression model seem plausible for a summary of this graph? If you use\n| a different base of logarithms, the shape of the graph won't change, but the values on the\n| axes will change.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in data:\n\nUN11 <- readRDS(url('https://github.com/omerfyalcin/colab-data/blob/main/UN.rds?raw=true'))\nhead(UN11)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  region  group fertility   ppgdp lifeExpF pctUrban\nAfghanistan         Asia  other     5.968   499.0    49.49       23\nAlbania           Europe  other     1.525  3677.2    80.40       53\nAlgeria           Africa africa     2.142  4473.0    75.00       67\nAmerican Samoa      <NA>   <NA>        NA      NA       NA       NA\nAngola            Africa africa     5.135  4321.9    53.17       59\nAnguilla       Caribbean  other     2.000 13750.1    81.10      100\n               infantMortality\nAfghanistan          124.53500\nAlbania               16.56100\nAlgeria               21.45800\nAmerican Samoa        11.29389\nAngola                96.19100\nAnguilla                    NA\n```\n:::\n:::\n\n\n#### A)\n\nIn studying the dependence of fertility on GDP, fertility is the predictor and GDP is the response.\n\n#### B)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate scatterplot:\n\nscatter_1 <- ggplot(UN11, aes(x=ppgdp, y=fertility)) + \n  geom_point( color=\"black\")\nscatter_1\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 14 rows containing missing values (geom_point).\n```\n:::\n\n::: {.cell-output-display}\n![](Rowley_Homework_3_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# with linear trend\nscatter_2 <- ggplot(UN11, aes(x=ppgdp, y=fertility)) +\n  geom_point() +\n  geom_smooth(method=lm, se=TRUE)\nscatter_2\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 14 rows containing non-finite values (stat_smooth).\nRemoved 14 rows containing missing values (geom_point).\n```\n:::\n\n::: {.cell-output-display}\n![](Rowley_Homework_3_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n:::\n\n\nIn viewing this scatterplot, we can see that higher rates of birth correlates with lower per-person GPD. A straight-line mean function does not seem plausible for this graph, as the line extends far beyond the range of data points.\n\n#### C)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate scatterplot using natural logarithms:\n\nscatter_3 <- ggplot(UN11, aes(x=log(ppgdp), y=log(fertility))) +\n  geom_point() +\n  geom_smooth(method=lm, se=TRUE)\nscatter_3\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 14 rows containing non-finite values (stat_smooth).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 14 rows containing missing values (geom_point).\n```\n:::\n\n::: {.cell-output-display}\n![](Rowley_Homework_3_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nUsing natural logarithms, we see a much more plausible summary for this graph.\n\n### Question 2\n\n| Annual income, in dollars, is an explanatory variable in a regression analysis. For a British\n| version of the report on the analysis, all responses are converted to British pounds sterling (1 pound\n| equals about 1.33 dollars, as of 2016).\n| (a) How, if at all, does the slope of the prediction equation change?\n| (b) How, if at all, does the correlation change?\n\n#### A)\n\nThe slope of the prediction will need to be divided by 1.33 to account for the conversion to British pounds.\n\n#### B)\n\nThe correlation will not change.\n\n### Question 3\n\n| Water runoff in the Sierras (Data file: water in alr4) Can Southern California's water\n| supply in future years be predicted from past data? One factor affecting water availability is stream\n| runoff. If runoff could be predicted, engineers, planners, and policy makers could do their jobs\n| more efficiently. The data file contains 43 years' worth of precipitation measurements taken at six\n| sites in the Sierra Nevada mountains (labeled APMAM, APSAB, APSLAKE, OPBPC, OPRC, and\n| OPSLAKE) and stream runoff volume at a site near Bishop, California, labeled BSAAM. Draw\n| the scatterplot matrix for these data and summarize the information available from these\n| plots. (Hint: Use the pairs() function.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'alr4' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'car' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'carData' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'car'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: effects\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'effects' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'alr4'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked _by_ '.GlobalEnv':\n\n    UN11\n```\n:::\n\n```{.r .cell-code}\nhead(water)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Year APMAM APSAB APSLAKE OPBPC  OPRC OPSLAKE  BSAAM\n1 1948  9.13  3.58    3.91  4.10  7.43    6.47  54235\n2 1949  5.28  4.82    5.20  7.55 11.11   10.26  67567\n3 1950  4.20  3.77    3.67  9.52 12.20   11.35  66161\n4 1951  4.60  4.46    3.93 11.14 15.15   11.13  68094\n5 1952  7.15  4.99    4.88 16.34 20.05   22.81 107080\n6 1953  9.70  5.65    4.91  8.88  8.15    7.41  67594\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(water)\n```\n\n::: {.cell-output-display}\n![](Rowley_Homework_3_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nBased on the scatterplot matrix, stream runoff near Bishop, California appears to be correlated with precipitation at \"O\" sites, but not with \"A\" sites or year.\n\n### Question 4\n\n| Professor ratings (Data file: Rateprof in alr4) In the website and online forum\n| RateMyProfessors.com, students rate and comment on their instructors. Launched in 1999, the site\n| includes millions of ratings on thousands of instructors. The data file includes the summaries of\n| the ratings of 364 instructors at a large campus in the Midwest (Bleske-Rechek and Fritsch, 2011).\n| Each instructor included in the data had at least 10 ratings over a several year period. Students\n| provided ratings of 1--5 on quality, helpfulness, clarity, easiness of instructor's courses, and\n| raterInterest in the subject matter covered in the instructor's courses. The data file provides the\n| averages of these five ratings. Create a scatterplot matrix of these five variables. Provide a\n| brief description of the relationships between the five ratings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(Rateprof)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  gender numYears numRaters numCourses pepper discipline              dept\n1   male        7        11          5     no        Hum           English\n2   male        6        11          5     no        Hum Religious Studies\n3   male       10        43          2     no        Hum               Art\n4   male       11        24          5     no        Hum           English\n5   male       11        19          7     no        Hum           Spanish\n6   male       10        15          9     no        Hum           Spanish\n   quality helpfulness  clarity easiness raterInterest sdQuality sdHelpfulness\n1 4.636364    4.636364 4.636364 4.818182      3.545455 0.5518564     0.6741999\n2 4.318182    4.545455 4.090909 4.363636      4.000000 0.9020179     0.9341987\n3 4.790698    4.720930 4.860465 4.604651      3.432432 0.4529343     0.6663898\n4 4.250000    4.458333 4.041667 2.791667      3.181818 0.9325048     0.9315329\n5 4.684211    4.684211 4.684211 4.473684      4.214286 0.6500112     0.8200699\n6 4.233333    4.266667 4.200000 4.533333      3.916667 0.8632717     1.0327956\n  sdClarity sdEasiness sdRaterInterest\n1 0.5045250  0.4045199       1.1281521\n2 0.9438798  0.5045250       1.0744356\n3 0.4129681  0.5407021       1.2369438\n4 0.9990938  0.5882300       1.3322506\n5 0.5823927  0.6117753       0.9749613\n6 0.7745967  0.6399405       0.6685579\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(Rateprof[,8:12])\n```\n\n::: {.cell-output-display}\n![](Rowley_Homework_3_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Quality**: Based on the scatterplot matrix, we can see that there is a positive correlation between quality and helpfulness, as well as between quality and clarity (though we see one outlier in this data set that represents a comparitively higher rate of clarity linked with a lower rate of quality). There is a slightly positive correlation between quality and easiness, but no definitive correlation between quality and rater interest.\n\n**Helpfulness**: Based on the scatterplot matrix, we see (as mentioned) a positive correlation between helpfulness and quality, as well as between helpfulness and clarity (though the spread of data points is slightly larger). Similar to quality, there is a slightly positive correlation between helpfulness and easiness, but no definitive correlation between helpfulness and rater interest.\n\n**Clarity**: Based on the scatterplot, we see (as mentioned) a positive correlation between clarity and quality, as well as between clarity and helpfulness (though the spread of data points is slightly larger). Similarly to quality and helpfulness, there is no definitive correlation between clarity and easiness or clarity and rater interest.\n\n**Easiness**: There are slightly positive correlations between easiness and quality, easiness and helpfulness, and easiness and clarity. There is no definitive correlation between easiness and rater interest.\n\n**Rater Interest**: There are no definitive correlations between rater interest and any of the remaining four variables.\n\nOverall, quality, helpfulness, and clarity provide more insight related to professor rating than easiness and rater interest.\n\n### Question 5\n\n| For the student.survey data file in the smss package, conduct regression analyses relating\n| (by convention, y denotes the outcome variable, x denotes the explanatory variable)\n| (i) y = political ideology and x = religiosity,\n| (ii) y = high school GPA and x = hours of TV watching.\n| (You can use ?student.survey in the R console, after loading the package, to see what each variable\n| means.)\n| (a) Graphically portray how the explanatory variable relates to the outcome variable in\n| each of the two cases\n| (b) Summarize and interpret results of inferential analyses.\n\n#### A)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(smss)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'smss' was built under R version 4.2.3\n```\n:::\n\n```{.r .cell-code}\ndata(student.survey)\nhead(student.survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  subj ge ag  hi  co   dh   dr tv sp ne ah    ve pa           pi           re\n1    1  m 32 2.2 3.5    0  5.0  3  5  0  0 FALSE  r conservative   most weeks\n2    2  f 23 2.1 3.5 1200  0.3 15  7  5  6 FALSE  d      liberal occasionally\n3    3  f 27 3.3 3.0 1300  1.5  0  4  3  0 FALSE  d      liberal   most weeks\n4    4  f 35 3.5 3.2 1500  8.0  5  5  6  3 FALSE  i     moderate occasionally\n5    5  m 23 3.1 3.5 1600 10.0  6  6  3  0 FALSE  i very liberal        never\n6    6  m 39 3.5 3.5  350  3.0  4  5  7  0 FALSE  d      liberal occasionally\n     ab    aa    ld\n1 FALSE FALSE FALSE\n2 FALSE FALSE    NA\n3 FALSE FALSE    NA\n4 FALSE FALSE FALSE\n5 FALSE FALSE FALSE\n6 FALSE FALSE    NA\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nsurvey <- student.survey %>%\n  rename(\"poli_ideo\"=\"pi\", \"relig\"=\"re\", \"TV\"=\"tv\", \"gpa_hs\"=\"hi\")\n\nlm(poli_ideo ~ relig, data=survey)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in model.response(mf, \"numeric\"): using type = \"numeric\" with a factor\nresponse will be ignored\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in Ops.ordered(y, z$residuals): '-' is not meaningful for ordered\nfactors\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = poli_ideo ~ relig, data = survey)\n\nCoefficients:\n(Intercept)      relig.L      relig.Q      relig.C  \n     3.5253       2.1864       0.1049      -0.6958  \n```\n:::\n\n```{.r .cell-code}\nggplot(data = survey, aes(x = relig, fill = poli_ideo)) +\n    geom_bar(position = \"fill\") + scale_fill_brewer(palette=\"PiYG\")\n```\n\n::: {.cell-output-display}\n![](Rowley_Homework_3_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(gpa_hs ~ TV, data=survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = gpa_hs ~ TV, data = survey)\n\nCoefficients:\n(Intercept)           TV  \n    3.44135     -0.01831  \n```\n:::\n\n```{.r .cell-code}\nggplot(data = survey, aes(x=TV, y=gpa_hs)) +\n    geom_point() + geom_smooth(method=lm, se=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](Rowley_Homework_3_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n#### B)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"stargazer\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nInstalling package into 'C:/Users/caitr/AppData/Local/R/win-library/4.2'\n(as 'lib' is unspecified)\n```\n:::\n\n::: {.cell-output .cell-output-error}\n```\nError in contrib.url(repos, \"source\"): trying to use CRAN without setting a mirror\n```\n:::\n\n```{.r .cell-code}\nlibrary(stargazer)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nPlease cite as: \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n R package version 5.2.3. https://CRAN.R-project.org/package=stargazer \n```\n:::\n\n```{.r .cell-code}\npoli_relig <- lm(as.numeric(poli_ideo) ~ as.numeric(relig), \n         data = survey)\n\ngpa_tv <- lm(gpa_hs ~ TV, data = survey)\n\nstargazer(poli_relig, gpa_tv, type = 'text', dep.var.labels = c('Political Ideology', 'High School GPA'), covariate.labels = c('Religiosity', 'Hours of TV'))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n================================================================\n                                     Dependent variable:        \n                              ----------------------------------\n                              Political Ideology High School GPA\n                                     (1)               (2)      \n----------------------------------------------------------------\nReligiosity                        0.970***                     \n                                   (0.179)                      \n                                                                \nHours of TV                                         -0.018**    \n                                                     (0.009)    \n                                                                \nConstant                           0.931**          3.441***    \n                                   (0.425)           (0.085)    \n                                                                \n----------------------------------------------------------------\nObservations                          60               60       \nR2                                  0.336             0.072     \nAdjusted R2                         0.324             0.056     \nResidual Std. Error (df = 58)       1.345             0.447     \nF Statistic (df = 1; 58)          29.336***          4.471**    \n================================================================\nNote:                                *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n\nBased on this inferential analysis, we can see that there is a statistically significant and positive correlation between religiosity and political ideology (p-value\\<0.01). Specifically, there is for every \"one unit of increase\" in religiosity, there is a \"0.970-unit increase\" in political ideology. However, the adjusted R-squared value is 0.324, which suggests that a linear regression is not a very good fit for this model.\n\nHowever, we also see that there is a statistically significant negative correlation between hours of TV watch and high school GPA (p-value\\<0.05). Specifically, for every one hour of TV watched, there is a 0.018-unit decline in GPA. However, the adjusted R-squared value is 0.056, which suggests that a linear regression is a very unreliable fit for this model.\n",
    "supporting": [
      "Rowley_Homework_3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}