{
  "hash": "8b012dc9e7ec4ab46675ed0be29f5397",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Meredith Derian-Toth\"\ndescription: \"DACSS603_Homework 2\"\ndate: \"04/02/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - confidence intervals \n---\n\n\n### Question 1: Construct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?\n\n|                    |             |                |                    |\n|--------------------|-------------|----------------|--------------------|\n| Surgical Procedure | Sample Size | Mean Wait Time | Standard Deviation |\n| Bypass             | 539         | 19             | 10                 |\n| Angiography        | 847         | 18             | 9                  |\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#90% CI for Bypass\n\nBy_mean<-19\nBy_sd<-10\nBy_size<-539\n\nBySE<-By_sd/sqrt(By_size)\n\nConfidence_level1<-0.90\n\ntail_area<-(1-Confidence_level1)/2\n\nBy_t_score<-qt(p = 1 - tail_area, df = By_size - 1)\n\nBy_CI <- c(By_mean - By_t_score * BySE, By_mean + By_t_score * BySE)\nBy_CI\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n\n```{.r .cell-code}\n#Difference between the range average wait time for Bypass\n19.70971-18.29029\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.41942\n```\n:::\n:::\n\n\nThe average wait time for a Bypass ranges from 18.29 minutes to 19.71 minutes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#CI Angiography\n\nAng_mean<-18\nAng_sd<-9\nAng_size<-847\n\nAng_SE<- Ang_sd/sqrt(Ang_size)\n\n#Condifence level and tail area calculated in the code chunk above\n\nAng_t_score <- qt(p = 1 - tail_area, df = Ang_size)\n\nAng_CI <- c(Ang_mean - Ang_t_score * Ang_SE, Ang_mean + Ang_t_score * Ang_SE)\nAng_CI\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n\n```{.r .cell-code}\n#Difference between the range average wait time for Angiography\n18.50922-17.49078\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.01844\n```\n:::\n:::\n\n\nThe average wait time for an Angiography ranges from 17.5 minutes to 18.51 minutes.\n\nThe difference in wait time for Bypass is 1.42 minutes, whereas the difference in wait time for Angiography is 1.02 minutes. Therefor the confidence interval is narrower for the Angiography wait time.\n\n### Question 2: Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success. Construct and interpret a 95% confidence interval for p.\n\n*A survey of 1031 adult Americans was carried out by the National Center for Public Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 believed that college education is essential for success.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNCPP_size<-1031\nCollegeSuc<-567\n#Calculating those who do not necessarily believe you need a college degree to be successful (1031-567)\nNotCollegeSuc<-464\n\n#Creating a dataframe to run a t-test to find the P value and confidence interval\nNCPP_DF<-data.frame(CollegeSuc, NotCollegeSuc)\n\nprop.test(NCPP_DF$CollegeSuc,1031)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  NCPP_DF$CollegeSuc out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nThe point of estimate (p value) for adult Americans who believe that you need a college degree to be successful is 0.5499515, meaning about 55% of adult Americans believe you need a college degree to be successful. The confidence interval (95%) shows a range of 0.5189682 to 0.5805580, meaning this belief could range from about 52% of adult Americans to 58% of adult Americans.\n\n### Question 3: Assuming the significance level to be 5%, what should be the size of the sample?\n\n*Suppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within \\$5 of the true population mean (i.e. they want the confidence interval to have a length of \\$10 or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between \\$30 and \\$200. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation).*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Brainstorming:\n#.25*30\n#Pop_sd_Low<-7.5\n#.25*200\n#Pop_sd_High<-50\n#Confidence_level2<-0.95\n\nPop_sd<-.25*(200-30)\nPop_sd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.5\n```\n:::\n\n```{.r .cell-code}\n#Based on the formula for a 95% confidence interval:\n\nz <- qnorm(.95)\ns <- Pop_sd\nn <- ((z*s)/5)^2\nprint(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 195.4755\n```\n:::\n\n```{.r .cell-code}\n#Question - this drops the sample mean, how can we use this formula without the sample mean?\n```\n:::\n\n\nDue to the fact that the financial aid office believes that the amount spent on books varies widely, we can assume that the estimator value is not efficient. This means our sample mean should have a smaller variance than our sample median. Therefore, we need a higher sample size in order to reduce the variance.\n\n### **Question 4A - 4C:**\n\n*According to a union agreement, the mean income for all senior-level workers in a large service company equals \\$500 per week. A representative of a women's group decides to analyze whether the mean income μ for female employees matches this norm. For a random sample of nine female employees, ȳ = \\$410 and s = 90*\n\n**Hint:** *The P-values for the two possible one-sided tests must sum to 1.*\n\n#### A. Test whether the mean income of female employees differs from \\$500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#pop mean = 500\n#sample mean = 410\n#sample standard deviation = 90\n#sample size = 9\n\nSEM<- 90/sqrt(9)\nSEM\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30\n```\n:::\n\n```{.r .cell-code}\n#SEM = 30\n\nqnorm(0.025, mean = 500, sd = SEM)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 441.2011\n```\n:::\n\n```{.r .cell-code}\n#qnorm(0.025)=$441.2011\nqnorm(0.975, mean = 500, sd = SEM)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 558.7989\n```\n:::\n\n```{.r .cell-code}\n#qnorm(0.975)=$558.7989\n\n#Also\n500-1.96*SEM\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 441.2\n```\n:::\n\n```{.r .cell-code}\n500+1.96*SEM\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 558.8\n```\n:::\n\n```{.r .cell-code}\ns_mean<- 410\ns_sd<- 90\ns_size<-9\nconfidence_level3<-0.975\ntail_area2<-(1-confidence_level3)/2\nt_score<-qt(p = 1-tail_area2, df = s_size-1)\nCI<- c(s_mean-t_score*s_sd/sqrt(s_size),\ns_mean+t_score*s_sd/sqrt(s_size))\nprint(CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 327.4543 492.5457\n```\n:::\n\n```{.r .cell-code}\nt_statistic<-410-500/(30/sqrt(9))\nt_statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 360\n```\n:::\n\n```{.r .cell-code}\np_value<- (1 - pt(t_statistic, df=8))*2\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nHere we are working with a two-tailed test, because we want to know if female employees are making more or less than and average of \\$500/ week. A normal distribution tells us that only 5% of the observations would be less than \\$441.20 and more than \\$558.80, 95% of the observations are expected to to be between this range (about \\$441 - \\$559).\n\n*Significance Testing*\n\nIn this test, the null hypothesis is that female employees make on average \\$500/ week.\n\nThe p value is: 0\n\nThe t value is: 360\n\nWith a t value of 360, greater than the critical value of 5, we reject the null hypothesis that the population mean is 500.\n\n#### B. Report the P-value for Ha: μ \\< 500. Interpret\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#pop mean = 500\n#sample mean = 410\n#sample standard deviation = 90\n#sample size = 9\n\nqnorm(0.05, mean = 500, sd = SEM)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 450.6544\n```\n:::\n\n```{.r .cell-code}\n#qnorm(0.05)=$450.6544\n\ns_mean<- 410\ns_sd<- 90\ns_size<-9\nconfidence_level4<-0.05\ntail_area3<-(1-confidence_level4)/1\nt_score<-qt(p = 1-tail_area3, df = s_size-1)\nCI<- c(s_mean-t_score*s_sd/sqrt(s_size),\ns_mean+t_score*s_sd/sqrt(s_size))\nprint(CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 465.7864 354.2136\n```\n:::\n\n```{.r .cell-code}\nt_statistic2<-410-500/(30/sqrt(9))\nt_statistic2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 360\n```\n:::\n\n```{.r .cell-code}\np_value2<- (1 - pt(t_statistic, df=8))*1\np_value2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nHere we are working with a one-tailed test, because we are asking whether female employees make an average of less than \\$500/ week. A normal distribution tells us that 5% of the observations would be less than \\$450.6544 and 95% of the observations would be more than that.\n\n*Significance Testing*\n\np value = 0\n\nt value = 360\n\nWith a critical value of 0, and a t value of 360 (larger than the critical value) we reject the null hypothesis that the population mean is less than 500.\n\n#### C. Report and interpret the P-value for Ha: μ \\> 500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#pop mean = 500\n#sample mean = 410\n#sample standard deviation = 90\n#sample size = 9\n\nqnorm(0.95, mean = 500, sd = SEM)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 549.3456\n```\n:::\n\n```{.r .cell-code}\n#qnorm(0.025)=$549.3456\n\ns_mean<- 410\ns_sd<- 90\ns_size<-9\nconfidence_level5<-0.95\ntail_area4<-(1-confidence_level5)/1\nt_score<-qt(p = 1-tail_area4, df = s_size-1)\nCI<- c(s_mean-t_score*s_sd/sqrt(s_size),\ns_mean+t_score*s_sd/sqrt(s_size))\nprint(CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 354.2136 465.7864\n```\n:::\n\n```{.r .cell-code}\nt_statistic3<-410+500/(30/sqrt(9))\nt_statistic3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 460\n```\n:::\n\n```{.r .cell-code}\np_value3<- (1 - pt(t_statistic, df=8))*1\np_value3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nHere we are working with a one-tailed test, because we are asking whether female employees make an average of more than \\$500/ week. A normal distribution tells us that 5% of the observations would be more than \\$549.34 and 95% of the observations would be less than that.\n\n*Significance Testing*\n\np value = 0\n\nt value = 460\n\nWith a critical value of 0, and a t value of 460 (larger than the critical value) we reject the null hypothesis that the population mean is greater than 500.\n\n### Question 5A - 5C:\n\n*Jones and Smith separately conduct studies to test H0: μ = 500 against Ha: μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7, with se = 10.0.*\n\n#### A. Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#H0: μ = 500\n#Ha: μ ≠ 500\n\n#Jones: \n#n = 1000; y = 519.5; se = 10\n#t = 1.95 and P-value = 0.051\n#t_value = x1-x2/se\nJones_t_value<-(519.5-500)/10\nJones_t_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\nJones_p_value<-(2*pt(Jones_t_value, df = 999, lower.tail=FALSE))\nJones_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\n#Smith: \n#n = 1000; y = 519.7; se = 10\n#t = 1.97 and P-value = 0.049\nSmith_t_value<-(519.7-500)/10\nSmith_t_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\nSmith_p_value<-(2*pt(Smith_t_value, df=999, lower.tail = FALSE))\nSmith_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n#### B. Using α = 0.05, for each study indicate whether the result is \"statistically significant.\"\n\nSmith's results are statistically significant, as the p value is less than .05. However, Jone's results are not statistically significant since they are greater than .05.\n\n#### C. Using this example, explain the misleading aspects of reporting the result of a test as \"P ≤ 0.05\" versus \"P \\> 0.05,\" or as \"reject H0\" versus \"Do not reject H0,\" without reporting the actual P-value.\n\nReporting the actual p value provides context for how strong the results of the statistical analysis are. Without the context of the actual p value, it hides this context, and does not provide enough information to understand the validity of the results.\n\n### Question 6: Test at α = 0.05 the claim that the proportion who choose a healthy snack differs by grade level. What is the null hypothesis? Which test should we use? What is the conclusion?\n\n*A school nurse wants to determine whether age is a factor in whether children choose a healthy snack after school. She conducts a survey of 300 middle school students, with the results below.*\n\n|                 |           |           |           |\n|-----------------|-----------|-----------|-----------|\n| Grade level     | 6th grade | 7th grade | 8th grade |\n| Healthy snack   | 31        | 43        | 51        |\n| Unhealthy snack | 69        | 57        | 49        |\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#n = 300\n\ngrade_level<-(c(rep(\"6th Grade\", 100), \n                rep(\"7th Grade\", 100), \n                rep(\"8th Grade\", 100)))\nsnack_choice<-(c(rep(\"healthy snack\", 31), \n                 rep(\"unhealthy snack\", 69), \n                 rep(\"healthy snack\", 43), \n                 rep(\"unhealthy snack\", 57), \n                 rep(\"healthy snack\", 51), \n                 rep(\"unhealthy snack\", 49)))\nMS_snack_choice<-data.frame(grade_level, snack_choice)\n\nchisq.test(MS_snack_choice$snack_choice, MS_snack_choice$grade_level, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  MS_snack_choice$snack_choice and MS_snack_choice$grade_level\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\n\nI chose to use a chi-square test because we are comparing a categorical IV with a categorical DV. The results show a significant relationship between grade level and snack choice. We know it is significant because the p-value is less than .05 (p = 0.015).\n\n### Question 7: Test the claim that there is a difference in means for the three areas, using an appropriate test. What is the null hypothesis? Which test should we use? What is the conclusion?\n\n*Per-pupil costs (in thousands of dollars) for cyber charter school tuition for school districts in three areas are shown.*\n\n|        |     |     |     |     |     |     |\n|--------|-----|-----|-----|-----|-----|-----|\n| Area 1 | 6.2 | 9.3 | 6.8 | 6.1 | 6.7 | 7.5 |\n| Area 2 | 7.5 | 8.2 | 8.5 | 8.2 | 7.0 | 9.3 |\n| Area 3 | 5.8 | 6.4 | 5.6 | 7.1 | 3.0 | 3.5 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nArea<-c(rep(\"Area1\", 6), \n        rep(\"Area2\", 6), \n        rep(\"Area3\", 6))\n\nCost<-c(6.2, 9.3, 6.8, 6.1, 6.7, 7.5, 7.5, 8.2, 8.5, 8.2, 7.0, 9.3,\n          5.8, 6.4, 5.6, 7.1, 3.0, 3.5)\nArea_cost<-data.frame(Area, Cost)\n\nmy.anova <- aov(Cost ~ Area, data = Area_cost)\nsummary(my.anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \nArea         2  25.66  12.832   8.176 0.00397 **\nResiduals   15  23.54   1.569                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nI chose to run an ANOVA because we have a continuous DV and more than one categorical IV. According to the results, there is a significant relationship between area and cost because the p value is less than .05 (p = 0.00397). The null hypothesis for this test is that the means for each Area are equal. We reject the null hypothesis with a clear difference between the means.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}