{
  "hash": "1e054e545505aa948bab87916d303473",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Caitlin Rowley\"\ndescription: \"Homework 2\"\ndate: \"03/28/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n# load libraries\n\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(magrittr)\nlibrary(ggplot2)\nlibrary(markdown)\nlibrary(ggtext)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggtext' was built under R version 4.2.2\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readxl' was built under R version 4.2.2\n```\n:::\n:::\n\n\n### Question 1\n\n| The time between the date a patient was recommended for heart surgery and the surgery date\n| for cardiac patients in Ontario was collected by the Cardiac Care Network (\"Wait Times Data\n| Guide,\" Ministry of Health and Long-Term Care, Ontario, Canada, 2006). The sample mean\n| and sample standard deviation for wait times (in days) of patients for two cardiac procedures\n| are given in the accompanying table. Assume that the sample is representative of the Ontario\n| population. Construct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# bypass: sample size = 539, mean wait time = 19, SD = 10\n\nb_size=539\nb_mean=19\nb_sd=10\nb_ci=0.9\n\n# calculate standard error:\nbypass_se = b_sd/sqrt(b_size)\n\n# specify confidence interval:\nbypass_tail <- (1-b_ci)/2\nprint(bypass_tail)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\n# calculate t-value:\nb_t_value <-  qt(p=1-bypass_tail, df=b_size-1)\nprint(b_t_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691\n```\n:::\n\n```{.r .cell-code}\n# calculate confidence intervals:\nb_conf_int <- c(b_mean-b_t_value*bypass_se, b_mean+b_t_value*bypass_se)\nprint(b_conf_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n:::\n\n\nThe 90% confidence interval for wait-time for bypass surgery is 18.3--19.7 days.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# angiography: sample size = 847, mean wait time = 18, SD = 9\n\na_size=847\na_mean=18\na_sd=9\na_ci=0.9\n\n# calculate standard error:\nangio_se = a_sd/sqrt(a_size)\n\n# specify confidence interval:\nangio_tail <- (1-a_ci)/2\nprint(angio_tail)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\n# calculate t-value:\na_t_value <-  qt(p=1-angio_tail, df=a_size-1)\nprint(a_t_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.646657\n```\n:::\n\n```{.r .cell-code}\n# calculate confidence intervals:\na_conf_int <- c(a_mean-a_t_value*angio_se, a_mean+a_t_value*angio_se)\nprint(a_conf_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n:::\n\n\nThe 90% confidence interval for wait-time for angiography surgery is 17.5--18.5 days.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate size of confidence interval for bypass:\n\nbypass_ci_size=19.70971-18.29029\nprint(bypass_ci_size)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.41942\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate size of confidence interval for angiography:\n\nangio_ci_size=18.50922-17.49078\nprint(angio_ci_size)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.01844\n```\n:::\n:::\n\n\nThe confidence level is narrower for angiography surgery (1.01844) than it is for bypass surgery (1.41942).\n\n### Question 2\n\n| A survey of 1031 adult Americans was carried out by the National Center for Public\n| Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567\n| believed that college education is essential for success. Find the point estimate, p, of the\n| proportion of all adult Americans who believe that a college education is essential for success.\n| Construct and interpret a 95% confidence interval for p.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# binomial test - compares a sample proportion to a hypothesized proportion\n\ntotal_pop = 1031\nsurvey_pop = 567\n\nbinom.test(survey_pop, total_pop)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tExact binomial test\n\ndata:  survey_pop and total_pop\nnumber of successes = 567, number of trials = 1031, p-value = 0.001478\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.5189927 0.5806243\nsample estimates:\nprobability of success \n             0.5499515 \n```\n:::\n:::\n\n\nThe proportion of American adults who believe that a college education is essential for success, or p, is 0.55%, which falls between the 95% confidence interval of 52%-58%.\n\n### Question 3\n\n| Suppose that the financial aid office of UMass Amherst seeks to estimate the mean cost\n| of textbooks per semester for students. The estimate will be useful if it is within \\$5 of the true\n| population mean (i.e. they want the confidence interval to have a length of \\$10 or less). The\n| financial aid office is pretty sure that the amount spent on books varies widely, with most values\n| between \\$30 and \\$200. They think that the population standard deviation is about a quarter of\n| this range (in other words, you can assume they know the population standard deviation). Assuming the significance level to be 5%, what should be the size of the sample?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find sample size using [error=z*SD/sqrt of n]\n\n# range in cost of books:\nrange=200-30\n\n# population SD is 1/4 of range:\npopulation_sd = range/4\nprint(population_sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.5\n```\n:::\n\n```{.r .cell-code}\n# If 95% of the area lies between −z and z, then 5% of the area must lie outside of this range. Since normal curves are symmetric, half of this amount (2.5%) must lie before −z. Then the area under the curve before z must be: 0.025+0.95=0.975. The number z is the 97.5th percentile of the standard normal distribution:\nz=qnorm(.975)\n\n# estimate is within $5 of true population mean:\nn=((z*population_sd)/5)^2\nprint(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5454\n```\n:::\n:::\n\n\nThe sample size should be 278.\n\n### Question 4\n\n| According to a union agreement, the mean income for all senior-level workers in a large service company equals \\$500 per week. A representative of a women's group decides to analyze whether the mean income 'u' for female employees matches this norm. For a random sample of nine female employees, y=\\$410 and s=90.\n| A. Test whether the mean income of female employees differs from \\$500 per week. Include assumptions, hypotheses, test statistics, and P-value. Interpret the result.\n| B. Report the P-value for Ha: u\\<500. Interpret.\n| C. Report and interpret the P-value for Ha: u\\>500. (Hint: the P-values for the two possible one-sided tests must sum to 1).\n\n#### A)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# mean income = $500/week\n# mean income female: y=$410, s=90\n\n# A)\n# test statistics: describes how far your observed data is from the null hypothesis of no relationship between variables or no difference among sample groups (support or reject null)\n# formula: x_bar is sample mean, mu is hypothesized population mean, sd is sample standard deviation, and n is sample size.\n# formula: (sample mean-population mean)/(standard deviation/sqrt(sample size))\n\ntest_stat <- function(x_bar, mu, sd, n){return((x_bar-mu)/(sd/sqrt(n)))}\n\nsample_mean=410\npop_mean=500\nsd=90\nsample_size=9\n\n# find t-value:\nt_stat <- test_stat(sample_mean, pop_mean, sd, sample_size)\nprint(t_stat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# t-value is negative, so find lower tail\n# degree of freedom = n-1\n# find p-value:\nlow_p_value <- pt(q=t_stat, df=8, lower.tail=TRUE)\nprint(low_p_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n\n```{.r .cell-code}\n# find p-value for two-tailed t-test:\nlow_p_value <- 2*pt(t_stat, 8)\nprint(low_p_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nMy assumption is that the mean income of female employees will differ from the mean of all senior-level workers (\\$500/week). After running test statistics, we see that the t-stat is -3, meaning that females' average pay is 3 standard deviations from the population mean. We also see that the p-value is 0.02, which means that we can reject the null hypothesis, which assumes that there is no significant difference in pay across genders (i.e., females make \\$500/week on average).\n\n#### B)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# B\n# calculate p-value for LT alternative hypothesis (Ha: u<500):\n\np_Ha = pt(q=t_stat, df=8, lower.tail=TRUE)\np_Ha\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nThe p-value for the lower-tail alternative hypothesis is 0.009, which supports our previous assertion that we can reject the null hypothesis and accept the alternative. This indicates that u≠500. In other words, females do not make \\$500/week.\n\n#### C)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# C\n# calculate p-value for UT alternative hypothesis 2 (Ha: u>500):\n\np_Ha = pt(q=t_stat, df=8, lower.tail=FALSE)\np_Ha\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nThe p-value for the upper-tail alternative hypothesis is 0.991, which indicates that 'u' is not greater than 500. In other words, we now know that, on average, females make less than \\$500/week.\n\n### Question 5\n\n| Jones and Smith separately conduct studies to test H0: μ = 500 against Ha: μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7, with se = 10.0.\n| A. Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.\n| B. Using α = 0.05, for each study indicate whether the result is \"statistically significant.\"\n| C. Using this example, explain the misleading aspects of reporting the result of a test as \"P ≤0.05\" versus \"P \\> 0.05,\" or as \"reject H0\" versus \"Do not reject H0,\" without reporting the actual P-value.\n\n#### A)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# H0: u=500\n# Ha: u≠500\n# n=1000\n# Jones: y=519.5, se=10.0\n# Smith : y=519.7, se=10.0\n\n# Jones: t=1.95\n\nt_jones = ((519.5 - 500)/ 10)\ncat(\"t value for Jones:\", t_jones, '\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt value for Jones: 1.95 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Jones: p-value=0.0515\n\ncat('p value for Jones:', round(2*pt(t_jones, df = 999, lower.tail=FALSE), 4), '\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\np value for Jones: 0.0515 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Smith: t=1.97\n\nt_smith = ((519.7 - 500)/ 10)\ncat(\"t value for Smith:\", t_smith, '\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt value for Smith: 1.97 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Smith: p-value=0.049\n\ncat('p value for Smith:', round(2*pt(t_smith, df = 999, lower.tail=FALSE), 4), '\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\np value for Smith: 0.0491 \n```\n:::\n:::\n\n\n#### B)\n\nAssuming that 0.05 indicates statistical significance, we can see that while Smith's study shows statistical significance with a p-value of 0.0491 (\\<0.05), Jones's does not (p-value=0.0515, p-value\\>0.05).\n\n#### C)\n\nBased on this example, we can see why it is misleading to report a p-value as significant solely using \"p ≤0.05,\" \"reject H0,\" or \"cannot reject H0\" as indicators. After calculating each study's respective p-value, we can see that the two values are very close, and, if we were to round each to the nearest hundredth, both would be equal to 0.05. So, it is important to provide the p-values themselves so as to make the distinction between degrees of significance. In other words, although Jones's study showed statistical significance and Smith's did not, the differences in the two p-values was marginal, so it is important to indicate by how slim a margin both were greater/less than the significance level (0.05) so as to not overestimate statistical significance.\n\n### Question 6\n\n| A school nurse wants to determine whether age is a factor in whether children choose a\n| healthy snack after school. She conducts a survey of 300 middle school students, with the results\n| below. Test at α = 0.05 the claim that the proportion who choose a healthy snack differs by grade\n| level. What is the null hypothesis? Which test should we use? What is the conclusion?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 6th: healthy = 31, unhealthy = 69\n# 7th: healthy = 43, unhealthy = 57\n# 8th: healthy = 51, unhealthy = 49\n# n=300, each grade has 100 survey participants\n\n# create dataframe:\ngrade <- c(rep(\"6th\", 100), rep(\"7th\", 100), rep(\"8th\", 100))\nsnack <- c(rep(\"healthy\", 31), rep(\"unhealthy\", 69), rep(\"healthy\", 43),\n           rep(\"unhealthy\", 57), rep(\"healthy\", 51), rep(\"unhealthy\", 49))\n\nsurvey_data <- data.frame(grade, snack)\nhead(survey_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  grade   snack\n1   6th healthy\n2   6th healthy\n3   6th healthy\n4   6th healthy\n5   6th healthy\n6   6th healthy\n```\n:::\n\n```{.r .cell-code}\n# transform dataframe into table:\ntable(survey_data$snack,survey_data$grade)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           \n            6th 7th 8th\n  healthy    31  43  51\n  unhealthy  69  57  49\n```\n:::\n\n```{.r .cell-code}\n# conduct chi-squared test:\nchisq.test(survey_data$snack,survey_data$grade,correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  survey_data$snack and survey_data$grade\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\n\nThe null hypothesis is that age is not a factor in whether children choose a healthy snack after school. To test this hypothesis (two categorical variables), we should use Pearson's Chi-squared test. After running this test, we can see that the p-value is 0.015, which indicates statistical significance. Thus, we can reject the null hypothesis and conclude that age is a factor in whether children choose a healthy snack after school.\n\n### Question 7\n\n| Per-pupil costs (in thousands of dollars) for cyber charter school tuition for school\n| districts in three areas are shown. Test the claim that there is a difference in means for the three\n| areas, using an appropriate test. What is the null hypothesis? Which test should we use? What is\n| the conclusion?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# area 1: 6.2, 9.3, 6.8, 6.1, 6.7, 7.5\n# area 2: 7.5, 8.2, 8.5, 8.2, 7.0, 9.3\n# area 3: 5.8, 6.4, 5.6, 7.1, 3.0, 3.5\n\n# create dataframe:\narea <- c(rep(\"area_1\", 6), rep(\"area_2\", 6), rep(\"area_3\", 6))\ncost <- c(6.2, 9.3, 6.8, 6.1, 6.7, 7.5, 7.5, 8.2, 8.5, 8.2, 7.0, 9.3,\n          5.8, 6.4, 5.6, 7.1, 3.0, 3.5)\narea_cost <- data.frame(area,cost)\nhead(area_cost)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    area cost\n1 area_1  6.2\n2 area_1  9.3\n3 area_1  6.8\n4 area_1  6.1\n5 area_1  6.7\n6 area_1  7.5\n```\n:::\n\n```{.r .cell-code}\n# one-way ANOVA test:\none.way <- aov(cost ~ area, data = area_cost)\nsummary(one.way)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \narea         2  25.66  12.832   8.176 0.00397 **\nResiduals   15  23.54   1.569                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThe null hypothesis is that area has an effect on cost per pupil. Because we are testing the means of more than one group with one independent variable, we should use the one-way ANOVA test. After running the ANOVA test, we can see that the p-value (0.00397) is statistically significant. Thus, we can reject the null hypothesis and conclude that area does have an effect on cost per pupil.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}