{
  "hash": "125be804fe6bd23f94d914a448282e04",
  "result": {
    "markdown": "---\ntitle: \"Final Project Checkin-1\"\nauthor: \"Xiaoyan\"\ndescription: \"Template of course blog qmd file\"\ndate: \"03/17/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - finalpart1\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(ggplot2)\n```\n:::\n\n# {.tabset}\n\n## Introduction and background\n\n The Chinese government implemented the one-child policy in 1979, which resulted in the increasing proportion of one-child families and the \"four-two-one\" family structure consisting of four grandparents, two parents, and one child. Despite being blessed with relatively more family and social resources, only children may face physical and socio-psychological problems during development, including an elevated risk for overweight and obesity and negative psychosocial consequences. Previous studies have shown that only children had a higher likelihood of overweight or obesity, compared with children who had one or more siblings. Over obesity, mental healthy is also interesting to explore that how it is related to overweight/obesity, as well as sib-size, in young adolescents affects mental health.\n \n\n## research questions\n1. Does obesity positively related to mental health?\n2. what are factors that affects mental healthy?\n3. does sibling or obeisty directily related to mental health?\n\n## key predictors\n1. mental health\n2. sibling number\n3. obisity rate\n4. gender\n\n## hypothesis\n1. Higher obesity rate increase the risk of depression\n2. higher family income increase the rate of obesity\n3. More sibling reduce the risk of both depression and anxiety. \n\n## data description\n\n::: {.cell}\n\n```{.r .cell-code}\ndata<-read_excel(\"/Users/cassie199/Desktop/23spring/603_Spring_2023-1/posts/_data/Finaldata.xlsx\")\nhead(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 29\n  T0depres…¹ T0anx…² T1dep…³ T1anx…⁴ Height Weight    WC    HC   SBP   DBP   FBG\n       <dbl>   <dbl>   <dbl>   <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1         31      35      41      35   153.   34.6    58  67      98    60   4.4\n2         35      24      35      25   172.   46.1    63  78     110    70   3.9\n3         31      34      37      26   146.   38.9    72  77.7   102    62   4.6\n4         27      31      42      35   162.   46.8    62  80     116    80   4.5\n5         31      26      49      33   154.   36.4    56  72      90    60   4.2\n6         30      28      47      32   164.   40.6    55  73     102    70   3.7\n# … with 18 more variables: TC <dbl>, TG <dbl>, `HDL-C` <dbl>, `LDL-C` <dbl>,\n#   BMI <dbl>, WHR <dbl>, WtHR <dbl>, `Family location` <dbl>,\n#   `Number of siblings` <dbl>,\n#   `How much time do you spend with your father in elementary school?` <dbl>,\n#   `How much time do you spend with your mother in elementary school?` <dbl>,\n#   `Father’s education level` <dbl>, `Mother’s education level` <dbl>,\n#   `Family financial situation` <dbl>, `Sleeping hours` <dbl>, …\n```\n:::\n\n```{.r .cell-code}\nglimpse(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 1,348\nColumns: 29\n$ T0depression                                                        <dbl> 31…\n$ T0anxiety                                                           <dbl> 35…\n$ T1depression                                                        <dbl> 41…\n$ T1anxiety                                                           <dbl> 35…\n$ Height                                                              <dbl> 15…\n$ Weight                                                              <dbl> 34…\n$ WC                                                                  <dbl> 58…\n$ HC                                                                  <dbl> 67…\n$ SBP                                                                 <dbl> 98…\n$ DBP                                                                 <dbl> 60…\n$ FBG                                                                 <dbl> 4.…\n$ TC                                                                  <dbl> 3.…\n$ TG                                                                  <dbl> 0.…\n$ `HDL-C`                                                             <dbl> 0.…\n$ `LDL-C`                                                             <dbl> 2.…\n$ BMI                                                                 <dbl> 14…\n$ WHR                                                                 <dbl> 0.…\n$ WtHR                                                                <dbl> 0.…\n$ `Family location`                                                   <dbl> 2,…\n$ `Number of siblings`                                                <dbl> 2,…\n$ `How much time do you spend with your father in elementary school?` <dbl> 5,…\n$ `How much time do you spend with your mother in elementary school?` <dbl> 5,…\n$ `Father’s education level`                                          <dbl> 4,…\n$ `Mother’s education level`                                          <dbl> 3,…\n$ `Family financial situation`                                        <dbl> 3,…\n$ `Sleeping hours`                                                    <dbl> 3,…\n$ `Skipping breakfast`                                                <dbl> 1,…\n$ Vigorous                                                            <dbl> 1,…\n$ Moderate                                                            <dbl> 2,…\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 728\n```\n:::\n\n```{.r .cell-code}\nplot(data$T0depression~data$BMI)\n```\n\n::: {.cell-output-display}\n![](FinalProjXH_1_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\nThis dataset including 1348 variables and 29 columns. there are 728 NA in this data set. all variables was presented as numberic data. descriptive data was also presented as degrees such as education level, family financial situation and depression rate. By pre-plotting depression rate vs BMI, we can see that some ouliers may need to deal with and there is no siginifcant disrtibution on graph. More data processing is needed in future process.",
    "supporting": [
      "FinalProjXH_1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}