{
  "hash": "8850da3ab11c99d461ca77604b0916c7",
  "result": {
    "markdown": "---\ntitle: \"603_Project_Check_In_Saisrinivas_Ambatipudi\"\nauthor: \"Akhilesh Kumar & Saisrinivas Ambatipudi\"\ndate: \"2023-03-22\"\nproject title: \"Investigating Factors Affecting Blood Donation Frequency and Building a Donor Retention Strategy\"\noutput: html_document\n---\n\n\n\n\n## Data Description:\n\nThe blood transfusion dataset contain 748 samples with 5 input features:\nInput Features:\n•\tRecency (number of months since the last donation)\n•\tFrequency (total number of donations)\n•\tMonetary (total blood donated in c.c.)\n•\tTime (number of months since the first donation)\n•\tAge (age of the donor)\n\nSource: https://www.kaggle.com/datasets/ninalabiba/blood-transfusion-dataset \n\n\n::: {.cell}\n\n```{.r .cell-code}\nBD <- read_csv(\"C:/UMass/DACSS_603/603_Spring_2023/posts/_data/transfusion_saisrinivas.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 748 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (5): Recency (months), Frequency (times), Monetary (c.c. blood), Time (m...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nBD\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 748 × 5\n   `Recency (months)` `Frequency (times)` Monetary (c.c. blood…¹ Time …² wheth…³\n                <dbl>               <dbl>                  <dbl>   <dbl>   <dbl>\n 1                  2                  50                  12500      98       1\n 2                  0                  13                   3250      28       1\n 3                  1                  16                   4000      35       1\n 4                  2                  20                   5000      45       1\n 5                  1                  24                   6000      77       0\n 6                  4                   4                   1000       4       0\n 7                  2                   7                   1750      14       1\n 8                  1                  12                   3000      35       0\n 9                  2                   9                   2250      22       1\n10                  5                  46                  11500      98       1\n# … with 738 more rows, and abbreviated variable names\n#   ¹​`Monetary (c.c. blood)`, ²​`Time (months)`,\n#   ³​`whether he/she donated blood in March 2007`\n```\n:::\n:::\n\n\n## Research Questions:\n\n*Blood Donation Prediction Frequency:*\n\nThe aim of this study is to develop linear regression, logistic regression machine learning model, to accurately predict whether a blood donor is likely to donate in the future. \nThe results of this study could be useful in developing targeted strategies for donor recruitment and retention, ultimately improving the availability and accessibility of blood donations.\n\n*Identify Factors that Affect Blood Donation:*\n\nHow do donation behaviors vary across different regions, and what factors may contribute to these variations? Using hypothesis testing, this research project aims to compare the donation patterns of donors from different regions based on demographic and donation-related variables, such as age, gender, donation frequency, and time since last donation. The findings can provide insights into the regional variations in blood donation behaviors and inform targeted strategies to address these differences, potentially leading to increased donation rates and more efficient allocation of resources for blood donation organizations.\nThe study will visualize the results using plots and charts to identify any significant patterns or trends that could help healthcare and blood donation organizations to develop effective strategies to increase blood donation rates.\n\n*Segmentation of Blood Donors:*\n\nUse clustering techniques to segment blood donors based on their demographic and donation history characteristics. Explore methods such as K-means clustering or hierarchical clustering to identify groups of donors with similar characteristics. Examine the differences between these groups and explore their donation patterns over time.\n\n*Building a Donor Retention Strategy:*\n\nUse the insights gained from the previous projects to develop a donor retention strategy for the blood donation center. Identify factors that are associated with donor churn (i.e., donors who stop donating blood), and develop a plan to mitigate these factors. This can help healthcare and blood donation organizations to develop strategies to retain donors over the long term.\n\n## Summary of the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(BD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Recency (months) Frequency (times) Monetary (c.c. blood) Time (months)  \n Min.   : 0.000   Min.   : 1.000    Min.   :  250         Min.   : 2.00  \n 1st Qu.: 2.750   1st Qu.: 2.000    1st Qu.:  500         1st Qu.:16.00  \n Median : 7.000   Median : 4.000    Median : 1000         Median :28.00  \n Mean   : 9.507   Mean   : 5.515    Mean   : 1379         Mean   :34.28  \n 3rd Qu.:14.000   3rd Qu.: 7.000    3rd Qu.: 1750         3rd Qu.:50.00  \n Max.   :74.000   Max.   :50.000    Max.   :12500         Max.   :98.00  \n whether he/she donated blood in March 2007\n Min.   :0.000                             \n 1st Qu.:0.000                             \n Median :0.000                             \n Mean   :0.238                             \n 3rd Qu.:0.000                             \n Max.   :1.000                             \n```\n:::\n:::\n\n\n## Descrpition of the Variables:\n\nThis summary function presents a statistical description of a dataset related to blood donation, with five variables: Recency, Frequency, Monetary, Time, and whether the individual donated blood in March 2007. Here's a breakdown of each variable:\n\nRecency (months): This variable represents the number of months since the last blood donation. The minimum value is 0 months, indicating that some individuals donated blood very recently. The mean is 9.507 months, suggesting that, on average, people donated blood around 9.5 months ago. The maximum value is 74 months, which means the longest gap between donations is 74 months.\n\nFrequency (times): This variable shows the total number of times an individual has donated blood. The minimum value is 1, meaning that at least one person has only donated blood once. The mean is 5.515 times, indicating that people, on average, have donated blood about 5.5 times. The maximum value is 50 times, showing that some individuals have donated blood quite frequently.\n\nMonetary (c.c. blood): This variable represents the total volume of blood donated by an individual, measured in cubic centimeters (c.c.). The minimum value is 250 c.c., which corresponds to the minimum single donation volume. The mean is 1379 c.c., suggesting that, on average, individuals have donated around 1.379 liters of blood. The maximum value is 12,500 c.c., indicating that the highest total volume donated by a person is 12.5 liters.\n\nTime (months): This variable measures the length of time an individual has been donating blood. The minimum value is 2 months, suggesting that some individuals are relatively new to blood donation. The mean is 34.28 months, indicating that, on average, people have been donating blood for about 34.3 months. The maximum value is 98 months, showing that some individuals have been donating blood for a long time.\n\nWhether he/she donated blood in March 2007: This is a binary variable that indicates if an individual donated blood in March 2007. The mean is 0.238, which means that about 23.8% of the individuals in the dataset donated blood in that specific month.\n\nThe summary function provides an overview of the dataset's key statistics, such as minimum, 1st quartile, median, mean, 3rd quartile, and maximum values for each variable. This information helps to understand the distribution, central tendency, and spread of the data.\n\n## Expected Contribution:\n\n- Akhilesh Kumar: Will work on the Segmentation of Blood Donors and Building a Donor Retention Strategy\n\n- Sai Srinivas: Will work on the Blood Donation Prediction Frequency and Identify Factors that Affect Blood Donation \n\n## References:\n\nKaggle: https://www.kaggle.com/datasets/ninalabiba/blood-transfusion-dataset \n\nOriginal Owner and Donor: Prof. I-Cheng Yeh, Department of Information Management, Chung-Hua University,\nHsin Chu, Taiwan 30067, R.O.C., e-mail:icyeh '@' chu.edu.tw, TEL:886-3-5186511, Date Donated: October 3, 2008\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}