{
  "hash": "c106f338131fc4ac33103a1b49789884",
  "result": {
    "markdown": "---\ntitle: \"Homework 3\"\nauthor: \"Akhilesh Kumar Meghwal\"\ndescription: \"The third homework\"\ndate: \"04/11/2023\"\nformat:\n  html:\n    df-print: paged\n    css: styles.css\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Homework3\n  - Akhilesh\n---\n\n\n\n\n## Question 1\n\n**United Nations** (Data file: UN 1 lin alr4) The data in the file UN 11 contains several variables, including ppgdp, the gross national product per person in U.S. dollars, and fertility, the birth rate per 1000 females, both from the year 2009. The data are for 199 localities, mostly UN member countries, but also other areas such as Hong Kong that are not independent countries.The data were collected from the United Nations (2011). We will study the dependence of fertility on ppgdp.\n\n### (a) \n\nIdentify the predictor and the response?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(UN11)\nhead(UN11)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"region\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"group\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"fertility\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"ppgdp\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"lifeExpF\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"pctUrban\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Asia\",\"2\":\"other\",\"3\":\"5.968\",\"4\":\"499.0\",\"5\":\"49.49\",\"6\":\"23\",\"_rn_\":\"Afghanistan\"},{\"1\":\"Europe\",\"2\":\"other\",\"3\":\"1.525\",\"4\":\"3677.2\",\"5\":\"80.40\",\"6\":\"53\",\"_rn_\":\"Albania\"},{\"1\":\"Africa\",\"2\":\"africa\",\"3\":\"2.142\",\"4\":\"4473.0\",\"5\":\"75.00\",\"6\":\"67\",\"_rn_\":\"Algeria\"},{\"1\":\"Africa\",\"2\":\"africa\",\"3\":\"5.135\",\"4\":\"4321.9\",\"5\":\"53.17\",\"6\":\"59\",\"_rn_\":\"Angola\"},{\"1\":\"Caribbean\",\"2\":\"other\",\"3\":\"2.000\",\"4\":\"13750.1\",\"5\":\"81.10\",\"6\":\"100\",\"_rn_\":\"Anguilla\"},{\"1\":\"Latin Amer\",\"2\":\"other\",\"3\":\"2.172\",\"4\":\"9162.1\",\"5\":\"79.89\",\"6\":\"93\",\"_rn_\":\"Argentina\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe predictor variable is ppgdp and the response variable is fertility. 'ppgdp' represents the gross national product per person, while 'fertility' refers to the birth rate per 1000 females. The objective of the study is to understand how changes in 'ppgdp' can influence the value of 'fertility'. Positive or negative correlations between the two variables can lead to conclusions about how one variable impacts the other. The analysis of this relationship can provide insights into socio-economic factors that influence birth rates, which can then inform policies on population growth, family planning, and economic development.\n\n\n### (b): \n\nDraw the scatterplot of fertility on the vertical axis versus ppgdp on the horizontal axis and summarize the information in this graph. Does a straight-line mean function seem to be plausible for a summary of this graph?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUN11 %>%\n  select(c(ppgdp, fertility)) %>%\n  ggplot(aes(x = ppgdp, y = fertility)) + \n  geom_point(color = \"#001F3F\", alpha = 0.8, size = 3) +\n  geom_smooth(method = lm, se = FALSE, color = \"#E41A1C\", size = 1) +\n  theme_minimal() +\n  labs(x = \"Gross National Product per Person (US$)\",\n       y = \"Birth Rate per 1000 Females\",\n       title = element_text(color = \"#006600\", \"Scatterplot of Fertility vs. PPGDP with Regression Line\")) +\n  theme(plot.title = element_text(size = 12, face = \"bold\", hjust = 0.5, color = \"#006600\"),\n        axis.title = element_text(size = 10, color = \"#001F3F\"),\n        axis.text = element_text(size = 8, color = \"#001F3F\"),\n        panel.grid.major = element_blank(),\n        panel.grid.minor = element_blank(),\n        panel.border = element_blank(),\n        axis.line = element_line(color = \"#333333\", size = 0.5),\n        plot.background = element_blank(),\n        panel.background = element_blank(),\n        legend.position = \"none\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.\nℹ Please use the `linewidth` argument instead.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\nThe scatterplot shows the relationship between two variables, fertility (number of live births per 1000 females) and ppgdp (gross national product per person in US dollars). Each point on the plot represents a country, with its fertility rate on the vertical axis and its ppgdp on the horizontal axis.\n\nFrom the scatterplot, we can see that there is a general negative relationship between fertility and ppgdp. This means that as a country's income increases, its fertility rate tends to decrease. However, the relationship is not perfectly linear, and there is a lot of variation in fertility rates at each level of ppgdp.\n\nTo summarize the trend in the data, A straight-line mean function does seem to be plausible for summarizing the data, as the plotted regression line suggests a linear negative trend in the data. However, it is important to note that the relationship between ppgdp and fertility may not be entirely linear, and other factors may also contribute to the observed patterns in the data. Therefore, it may be appropriate to explore more complex statistical models to better understand the relationship between these variables.\n\nOverall, this scatterplot provides a visual representation of the relationship between fertility and ppgdp. It allows us to quickly identify trends and patterns in the data and can be used to inform further analysis and modeling.\n\n### (c):\n\nDraw the scatterplot of log(fertility) versus log(ppgdp) using natural logarithms. Does the simple linear regression model seem plausible for a summary of this graph? If you use a different base of logarithms, the shape of the graph won’t change, but the values on the axes will change.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUN11 %>%\n  select(c(ppgdp, fertility)) %>%\n  ggplot(aes(x = log(ppgdp), y = log(fertility))) + \n  geom_point(color = \"#001F3F\", alpha = 0.8, size = 3) +\n  geom_smooth(method = lm, se = TRUE, color = \"#E41A1C\", size = 1) +\n  theme_minimal() +\n  labs(x = \"Log(Gross National Product per Person (US$))\",\n       y = \"Log(Birth Rate per 1000 Females)\",\n       title = element_text(color = \"#006600\", \"Scatterplot of Log(Fertility) vs. Log(PPGDP) with Regression Line\")) +\n  theme(plot.title = element_text(size = 12, face = \"bold\", hjust = 0.5, color = \"#006600\"),\n        axis.title = element_text(size = 10, color = \"#001F3F\"),\n        axis.text = element_text(size = 8, color = \"#001F3F\"),\n        panel.grid.major = element_blank(),\n        panel.grid.minor = element_blank(),\n        panel.border = element_blank(),\n        axis.line = element_line(color = \"#333333\", size = 0.5),\n        plot.background = element_blank(),\n        panel.background = element_blank(),\n        legend.position = \"none\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\nThe scatterplot of Log(Fertility) versus Log(PPGDP) using data from the UN11 dataset shows the relationship between birth rates per 1000 females and gross national product per person in U.S. dollars. The graph displays the logarithmic transformation of the variables to better visualize the relationship between them.\n\nThe graph shows a negative linear relationship between log(fertility) and log(ppgdp), indicating that as gross national product per person increases, birth rates per 1000 females decrease. The linear regression line, which is plotted using the method of least squares, indicates that the relationship is statistically significant.\n\nThe scatterplot also shows some degree of variability around the regression line, which is captured by the shaded area around the line. This variability could be due to other factors that are not accounted for in the linear regression model.\n\nOverall, the scatterplot suggests that there is a general negative relationship between fertility and gross national product per person, with higher levels of economic development associated with lower birth rates. However, the relationship does not appear to be strictly linear, as the points are not forming a tight linear pattern around the regression line. There is also significant scatter in the data, which suggests that there may be other factors that influence fertility rates besides gross national product per person.\n\nTherefore, while a simple linear regression model could provide a summary of the relationship between fertility and gross national product per person, it may not capture the full complexity of the relationship. A more sophisticated model that takes into account additional factors may be necessary to accurately model the relationship between these two variables.\n\n#### Changing the base of the logs \n\n**Log10**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUN11 %>%\n  select(c(ppgdp, fertility)) %>%\n  ggplot(aes(x = log10(ppgdp), y = log10(fertility))) + \n  geom_point(color = \"#001F3F\", alpha = 0.8, size = 3) +\n  geom_smooth(method = lm, se = TRUE, color = \"#E41A1C\", size = 1) +\n  theme_minimal() +\n  labs(x = \"Log10(Gross National Product per Person (US$))\",\n       y = \"Log10(Birth Rate per 1000 Females)\",\n       title = element_text(color = \"#006600\", \"Scatterplot of Log10(Fertility) vs. Log10(PPGDP) with Regression Line\")) +\n  theme(plot.title = element_text(size = 12, face = \"bold\", hjust = 0.5, color = \"#006600\"),\n        axis.title = element_text(size = 10, color = \"#001F3F\"),\n        axis.text = element_text(size = 8, color = \"#001F3F\"),\n        panel.grid.major = element_blank(),\n        panel.grid.minor = element_blank(),\n        panel.border = element_blank(),\n        axis.line = element_line(color = \"#333333\", size = 0.5),\n        plot.background = element_blank(),\n        panel.background = element_blank(),\n        legend.position = \"none\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n**Log 2**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUN11 %>%\n  select(c(ppgdp, fertility)) %>%\n  ggplot(aes(x = log2(ppgdp), y = log2(fertility))) + \n  geom_point(color = \"#001F3F\", alpha = 0.8, size = 3) +\n  geom_smooth(method = lm, se = TRUE, color = \"#E41A1C\", size = 1) +\n  theme_minimal() +\n  labs(x = \"Log2(Gross National Product per Person (US$))\",\n       y = \"Log2(Birth Rate per 1000 Females)\",\n       title = element_text(color = \"#006600\", \"Scatterplot of Log2(Fertility) vs. Log2(PPGDP) with Regression Line\")) +\n  theme(plot.title = element_text(size = 12, face = \"bold\", hjust = 0.5, color = \"#006600\"),\n        axis.title = element_text(size = 10, color = \"#001F3F\"),\n        axis.text = element_text(size = 8, color = \"#001F3F\"),\n        panel.grid.major = element_blank(),\n        panel.grid.minor = element_blank(),\n        panel.border = element_blank(),\n        axis.line = element_line(color = \"#333333\", size = 0.5),\n        plot.background = element_blank(),\n        panel.background = element_blank(),\n        legend.position = \"none\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nChanging the base of logarithms will only change the values on the axes and not the shape of the graph.\n\nIn the case of the fertility vs. PPGDP graph, changing the base of logarithms will not change the overall pattern observed in the data, but it will change the values on the x and y axes. For example, using the natural logarithm (base e) instead of base 10 will result in different numerical values on the axes but the same underlying relationship between the two variables.\n\n## Question 2 \n\nAnnual income, in dollars, is an explanatory variable in a regression analysis. For a British version of the report on the analysis, all responses are converted to British pounds sterling (1 pound equals about 1.33 dollars, as of 2016).\n\n### (a) \n\nHow, if at all, does the slope of the prediction equation change?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUN11$ppgdp_pound <- 1.33 * UN11$ppgdp\nsummary(lm(fertility ~ ppgdp_pound, UN11))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = fertility ~ ppgdp_pound, data = UN11)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.9006 -0.8801 -0.3547  0.6749  3.7585 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.178e+00  1.048e-01  30.331  < 2e-16 ***\nppgdp_pound -2.407e-05  3.500e-06  -6.877  7.9e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.206 on 197 degrees of freedom\nMultiple R-squared:  0.1936,\tAdjusted R-squared:  0.1895 \nF-statistic: 47.29 on 1 and 197 DF,  p-value: 7.903e-11\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(fertility ~ ppgdp, UN11))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = fertility ~ ppgdp, data = UN11)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.9006 -0.8801 -0.3547  0.6749  3.7585 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.178e+00  1.048e-01  30.331  < 2e-16 ***\nppgdp       -3.201e-05  4.655e-06  -6.877  7.9e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.206 on 197 degrees of freedom\nMultiple R-squared:  0.1936,\tAdjusted R-squared:  0.1895 \nF-statistic: 47.29 on 1 and 197 DF,  p-value: 7.903e-11\n```\n:::\n:::\n\nThe analysis shows the results of fitting two linear regression models to the UN11 dataset. The first model predicts fertility rate based on the variable \"ppgdp_pound,\" which is the gross domestic product (GDP) per capita in British pounds. The second model predicts fertility rate based on the variable \"ppgdp,\" which is the GDP per capita in US dollars.\n\nBoth models show a statistically significant negative relationship between GDP per capita and fertility rate, with a p-value of 7.903e-11 for both. The coefficient estimates for ppgdp and ppgdp_pound are different, which is expected since the units are different. The coefficient for ppgdp_pound is -2.407e-05, which means that for every one pound increase in GDP per capita, the fertility rate decreases by 0.00002407. The coefficient for ppgdp is -3.201e-05, which means that for every one dollar increase in GDP per capita, the fertility rate decreases by 0.00003201.\n\nOverall, the results suggest that increasing economic development, as measured by GDP per capita, is associated with a decrease in fertility rate. However, the impact of the pound conversion on the slope of the regression line is negligible, with a difference of only 0.0000086 in the coefficient estimates.\n\n### (b)\n\nHow, if at all, does the correlation change?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(UN11$ppgdp, UN11$fertility)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.4399891\n```\n:::\n\n```{.r .cell-code}\ncor(UN11$ppgdp_pound, UN11$fertility)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.4399891\n```\n:::\n:::\n\n\nThe correlation coefficient between fertility and ppgdp (in US dollars) is the same as the correlation coefficient between fertility and ppgdp_pound (in British pounds). This suggests that the choice of currency used to measure gross domestic product per capita does not have a significant impact on the relationship between fertility and economic development.\n\nThe correlation coefficient of -0.4399891 indicates a moderate negative correlation between fertility and gross domestic product per capita. This suggests that as the gross domestic product per capita increases, the fertility rate tends to decrease, and vice versa.\n\nOverall, the analysis suggests that the choice of currency used to measure gross domestic product per capita does not have a significant impact on the relationship between fertility and economic development.\n\n## Question 3 \n\nWater runoff in the Sierras (Data file: water in alr4) Can Southern California’s water supply in future years be predicted from past data? One factor affecting water availability is stream runoff. If runoff could be predicted, engineers, planners, and policy makers could do their jobs more efficiently. The data file contains 43 years’ worth of precipitation measurements taken at six sites in the Sierra Nevada mountains (labeled APMAM, APSAB, APSLAKE, OPBPC, OPRC, and OPSLAKE) and stream runoff volume at a site near Bishop, California, labeled BSAAM. Draw the scatterplot matrix for these data and summarize the information available from these plots.\n\n(Hint: Use the pairsQ function.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(water)\npairs(~APMAM + APSAB + APSLAKE + OPBPC + OPRC + OPSLAKE, data=water, main = \"Sierra Southern California Water Supply Runoff\",\n      pch = 21, bg = \"red\")\n```\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Set colors for variables\ncolorA <- \"blue\"\ncolorB <- \"red\"\npar(cex.axis = 0.8, cex.lab=0.8)\n\n# Create the plots with colored points and title\nplot(y=water$BSAAM,x=water$APMAM, col=ifelse(substr(names(water)[2],1,1) == \"A\", colorA, colorB),\n     main=\"Scatter plot of BSAAM and APMAM\", xlab=\"APMAM\", ylab=\"BSAAM\")\n```\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=water$BSAAM,x=water$APSAB, col=ifelse(substr(names(water)[3],1,1) == \"A\", colorA, colorB),\n     main=\"Scatter plot of BSAAM and APSAB\", xlab=\"APSAB\", ylab=\"BSAAM\")\n```\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-8-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=water$BSAAM,x=water$APSLAKE, col=ifelse(substr(names(water)[4],1,1) == \"A\", colorA, colorB),\n     main=\"Scatter plot of BSAAM and APSLAKE\", xlab=\"APSLAKE\", ylab=\"BSAAM\")\n```\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-8-4.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=water$BSAAM,x=water$OPBPC, col=ifelse(substr(names(water)[5],1,1) == \"A\", colorA, colorB),\n     main=\"Scatter plot of BSAAM and OPBPC\", xlab=\"OPBPC\", ylab=\"BSAAM\")\n```\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-8-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=water$BSAAM,x=water$OPRC, col=ifelse(substr(names(water)[6],1,1) == \"A\", colorA, colorB),\n     main=\"Scatter plot of BSAAM and OPRC\", xlab=\"OPRC\", ylab=\"BSAAM\")\n```\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-8-6.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=water$BSAAM,x=water$OPSLAKE, col=ifelse(substr(names(water)[7],1,1) == \"A\", colorA, colorB),\n     main=\"Scatter plot of BSAAM and OPSLAKE\", xlab=\"OPSLAKE\", ylab=\"BSAAM\")\n```\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-8-7.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n:::\n\nI created output graph using 'pairs' to establish and read correlation between different variables given in the dataset, but I had trouble reading the correlation output; so I also ran each of the scatter-plots separately\n\nThe graph provided in the analysis shows the correlations between six variables: OPBPC, OPRC, OPSLAKE, APMAM, APSAB, and APSLAKE. The graph indicates that there are two groups of variables that are more closely related to each other than to the other variables in the set.\n\nThe first group consists of OPBPC, OPRC, and OPSLAKE, which are strongly correlated with each other. The correlation between these three variables and APMAM, APSAB, and APSLAKE is much weaker. This suggests that the first group of variables is related to each other in a way that is different from their relationship with the second group of variables.\n\nThe second group consists of APMAM, APSAB, and APSLAKE, which are also correlated with each other, although to a lesser extent than OPBPC, OPRC, and OPSLAKE. This suggests that there is indeed a correlation among these three variables, but it is not as strong as the correlation between the first group of variables.\n\nThe analysis also indicates that BSAAM is more closely related to OPBPC, OPRC, and OPSLAKE than to APMAM, APSAB, and APSLAKE. The results show that BSAAM has a stronger positive correlation with OPBPC, OPRC, and OPSLAKE. On the other hand, the correlation between BSAAM and APMAM, APSAB, and APSLAKE are weaker. This suggests that BSAAM is indeed more closely related to the first group of variables than to the second group of variables.\n\nIn summary, the analysis reveals that there are two groups of variables in the set, and they are more closely related to each other within their group. OPBPC, OPRC, and OPSLAKE are strongly correlated with each other, but not with APMAM, APSAB, and APSLAKE. APMAM, APSAB, and APSLAKE are also correlated with each other, but to a lesser extent than OPBPC, OPRC, and OPSLAKE. BSAAM is more closely related to the first group of variables than to the second group of variables. This information can be useful in identifying important variables for analysis or modeling.\n\n## Question 4 \n\nProfessor ratings (Data fde: Rateprof in alr4) In the website and online forum RateMyProfessors.com, students rate and comment on their instructors. Launched in 1999, the site includes millions of ratings on thousands of instructors. The data file includes the summaries of the ratings of 364 instructors at a large campus in the Midwest (Bleske-Rechek and Fritsch, 2011). Each instructor included in the data had at least 10 ratings over a several year period. Students provided ratings of 1-5 on quality, helpfulness, clarity, easiness of instructor’s courses, and raterinterest in the subject matter covered in the instructor’s courses. The data file provides the averages of these five ratings. Create a scatterplot matrix of these five variables. Provide a brief description of the relationships between the five ratings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Rateprof)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    gender       numYears        numRaters       numCourses     pepper   \n female:159   Min.   : 1.000   Min.   :10.00   Min.   : 1.000   no :320  \n male  :207   1st Qu.: 6.000   1st Qu.:15.00   1st Qu.: 3.000   yes: 46  \n              Median :10.000   Median :24.00   Median : 4.000            \n              Mean   : 8.347   Mean   :28.58   Mean   : 4.251            \n              3rd Qu.:11.000   3rd Qu.:37.00   3rd Qu.: 5.000            \n              Max.   :11.000   Max.   :86.00   Max.   :12.000            \n                                                                         \n    discipline          dept        quality       helpfulness   \n Hum     :134   English   : 49   Min.   :1.409   Min.   :1.364  \n SocSci  : 66   Math      : 34   1st Qu.:2.936   1st Qu.:3.069  \n STEM    :103   Biology   : 20   Median :3.612   Median :3.662  \n Pre-prof: 63   Chemistry : 20   Mean   :3.575   Mean   :3.631  \n                Psychology: 20   3rd Qu.:4.250   3rd Qu.:4.351  \n                Spanish   : 20   Max.   :4.981   Max.   :5.000  \n                (Other)   :203                                  \n    clarity         easiness     raterInterest     sdQuality      \n Min.   :1.333   Min.   :1.391   Min.   :1.098   Min.   :0.09623  \n 1st Qu.:2.871   1st Qu.:2.548   1st Qu.:2.934   1st Qu.:0.87508  \n Median :3.600   Median :3.148   Median :3.305   Median :1.15037  \n Mean   :3.525   Mean   :3.135   Mean   :3.310   Mean   :1.05610  \n 3rd Qu.:4.214   3rd Qu.:3.692   3rd Qu.:3.692   3rd Qu.:1.28730  \n Max.   :5.000   Max.   :4.900   Max.   :4.909   Max.   :1.67739  \n                                                                  \n sdHelpfulness      sdClarity        sdEasiness     sdRaterInterest \n Min.   :0.0000   Min.   :0.0000   Min.   :0.3162   Min.   :0.3015  \n 1st Qu.:0.9902   1st Qu.:0.9085   1st Qu.:0.9045   1st Qu.:1.0848  \n Median :1.2860   Median :1.1712   Median :1.0247   Median :1.2167  \n Mean   :1.1719   Mean   :1.0970   Mean   :1.0196   Mean   :1.1965  \n 3rd Qu.:1.4365   3rd Qu.:1.3328   3rd Qu.:1.1485   3rd Qu.:1.3326  \n Max.   :1.8091   Max.   :1.8091   Max.   :1.6293   Max.   :1.7246  \n                                                                    \n```\n:::\n\n```{.r .cell-code}\nhead(Rateprof)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"gender\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"numYears\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"numRaters\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"numCourses\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"pepper\"],\"name\":[5],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"discipline\"],\"name\":[6],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"dept\"],\"name\":[7],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"quality\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"helpfulness\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"clarity\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"easiness\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"raterInterest\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sdQuality\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sdHelpfulness\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sdClarity\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sdEasiness\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sdRaterInterest\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"male\",\"2\":\"7\",\"3\":\"11\",\"4\":\"5\",\"5\":\"no\",\"6\":\"Hum\",\"7\":\"English\",\"8\":\"4.636364\",\"9\":\"4.636364\",\"10\":\"4.636364\",\"11\":\"4.818182\",\"12\":\"3.545455\",\"13\":\"0.5518564\",\"14\":\"0.6741999\",\"15\":\"0.5045250\",\"16\":\"0.4045199\",\"17\":\"1.1281521\",\"_rn_\":\"1\"},{\"1\":\"male\",\"2\":\"6\",\"3\":\"11\",\"4\":\"5\",\"5\":\"no\",\"6\":\"Hum\",\"7\":\"Religious Studies\",\"8\":\"4.318182\",\"9\":\"4.545455\",\"10\":\"4.090909\",\"11\":\"4.363636\",\"12\":\"4.000000\",\"13\":\"0.9020179\",\"14\":\"0.9341987\",\"15\":\"0.9438798\",\"16\":\"0.5045250\",\"17\":\"1.0744356\",\"_rn_\":\"2\"},{\"1\":\"male\",\"2\":\"10\",\"3\":\"43\",\"4\":\"2\",\"5\":\"no\",\"6\":\"Hum\",\"7\":\"Art\",\"8\":\"4.790698\",\"9\":\"4.720930\",\"10\":\"4.860465\",\"11\":\"4.604651\",\"12\":\"3.432432\",\"13\":\"0.4529343\",\"14\":\"0.6663898\",\"15\":\"0.4129681\",\"16\":\"0.5407021\",\"17\":\"1.2369438\",\"_rn_\":\"3\"},{\"1\":\"male\",\"2\":\"11\",\"3\":\"24\",\"4\":\"5\",\"5\":\"no\",\"6\":\"Hum\",\"7\":\"English\",\"8\":\"4.250000\",\"9\":\"4.458333\",\"10\":\"4.041667\",\"11\":\"2.791667\",\"12\":\"3.181818\",\"13\":\"0.9325048\",\"14\":\"0.9315329\",\"15\":\"0.9990938\",\"16\":\"0.5882300\",\"17\":\"1.3322506\",\"_rn_\":\"4\"},{\"1\":\"male\",\"2\":\"11\",\"3\":\"19\",\"4\":\"7\",\"5\":\"no\",\"6\":\"Hum\",\"7\":\"Spanish\",\"8\":\"4.684211\",\"9\":\"4.684211\",\"10\":\"4.684211\",\"11\":\"4.473684\",\"12\":\"4.214286\",\"13\":\"0.6500112\",\"14\":\"0.8200699\",\"15\":\"0.5823927\",\"16\":\"0.6117753\",\"17\":\"0.9749613\",\"_rn_\":\"5\"},{\"1\":\"male\",\"2\":\"10\",\"3\":\"15\",\"4\":\"9\",\"5\":\"no\",\"6\":\"Hum\",\"7\":\"Spanish\",\"8\":\"4.233333\",\"9\":\"4.266667\",\"10\":\"4.200000\",\"11\":\"4.533333\",\"12\":\"3.916667\",\"13\":\"0.8632717\",\"14\":\"1.0327956\",\"15\":\"0.7745967\",\"16\":\"0.6399405\",\"17\":\"0.6685579\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n#subset of RateProf data\n\nrate_my_prof<-select(Rateprof,c('quality','helpfulness','clarity','easiness','raterInterest'))\n\nhead(rate_my_prof)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"quality\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"helpfulness\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"clarity\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"easiness\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"raterInterest\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"4.636364\",\"2\":\"4.636364\",\"3\":\"4.636364\",\"4\":\"4.818182\",\"5\":\"3.545455\",\"_rn_\":\"1\"},{\"1\":\"4.318182\",\"2\":\"4.545455\",\"3\":\"4.090909\",\"4\":\"4.363636\",\"5\":\"4.000000\",\"_rn_\":\"2\"},{\"1\":\"4.790698\",\"2\":\"4.720930\",\"3\":\"4.860465\",\"4\":\"4.604651\",\"5\":\"3.432432\",\"_rn_\":\"3\"},{\"1\":\"4.250000\",\"2\":\"4.458333\",\"3\":\"4.041667\",\"4\":\"2.791667\",\"5\":\"3.181818\",\"_rn_\":\"4\"},{\"1\":\"4.684211\",\"2\":\"4.684211\",\"3\":\"4.684211\",\"4\":\"4.473684\",\"5\":\"4.214286\",\"_rn_\":\"5\"},{\"1\":\"4.233333\",\"2\":\"4.266667\",\"3\":\"4.200000\",\"4\":\"4.533333\",\"5\":\"3.916667\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n#Scatterplot Matrix of five RateProf variables\n\npairs(rate_my_prof,\n      col = \"red3\",\n      pch = 20,\n      main = \"Rate my Professor Matrix ScatterPlot \")\n```\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nInterpreting  the scatter plot output generated through 'pairs' for the average professor ratings on the topics of quality, clarity, helpfulness, easiness, and rater interest, the variables quality, clarity, and helpfulness appear to each have strong positive correlations with each other. \n\nThe relationship between some pairs of variables indicates better positive linear correlations than others.\n\n- Quality-Clarity and Quality-Helpfulness indicate very strong positive linear correlations.\n- Quality-Easiness and Quality-RaterInterest indicate weak positive linear correlations.\n- Helpfulness-Easiness and Helpfulness-RaterInterest indicate weak linear correlations.\n- Clarity-Helpfulness indicates a positive correlation\n- Clarity-RaterInterest and Clarity-Easiness indicate weak positive correlations.\n- Easiness and RaterInterest indicate a very weak positive correlation.\n\n## Question 5 \n\nFor  the  student.survey  data  file  in  the  smss  package,  conduct  regression  analysesrelating (by convention, y denotes the outcome variable, x denotes the explanatory variable)\n\t(i) y = political ideology and x = religiosity,\n\t(ii) y = high school GPA and x = hours of TV watching.\n(You can use ?student. survey in the R console, after loading the package, to see what each variable means.)\n\n### (a)\n\nGraphically  portray  how  the  explanatory  variable  relates  to  the  outcome  variable  in each of the two cases\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(student.survey)\nsummary(student.survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      subj       ge           ag              hi              co       \n Min.   : 1.00   f:31   Min.   :22.00   Min.   :2.000   Min.   :2.600  \n 1st Qu.:15.75   m:29   1st Qu.:24.00   1st Qu.:3.000   1st Qu.:3.175  \n Median :30.50          Median :26.50   Median :3.350   Median :3.500  \n Mean   :30.50          Mean   :29.17   Mean   :3.308   Mean   :3.453  \n 3rd Qu.:45.25          3rd Qu.:31.00   3rd Qu.:3.625   3rd Qu.:3.725  \n Max.   :60.00          Max.   :71.00   Max.   :4.000   Max.   :4.000  \n                                                                       \n       dh             dr               tv               sp        \n Min.   :   0   Min.   : 0.200   Min.   : 0.000   Min.   : 0.000  \n 1st Qu.: 205   1st Qu.: 1.450   1st Qu.: 3.000   1st Qu.: 3.000  \n Median : 640   Median : 2.000   Median : 6.000   Median : 5.000  \n Mean   :1232   Mean   : 3.818   Mean   : 7.267   Mean   : 5.483  \n 3rd Qu.:1350   3rd Qu.: 5.000   3rd Qu.:10.000   3rd Qu.: 7.000  \n Max.   :8000   Max.   :20.000   Max.   :37.000   Max.   :16.000  \n                                                                  \n       ne               ah             ve          pa    \n Min.   : 0.000   Min.   : 0.000   Mode :logical   d:21  \n 1st Qu.: 2.000   1st Qu.: 0.000   FALSE:60        i:24  \n Median : 3.000   Median : 0.500                   r:15  \n Mean   : 4.083   Mean   : 1.433                         \n 3rd Qu.: 5.250   3rd Qu.: 2.000                         \n Max.   :14.000   Max.   :11.000                         \n                                                         \n                     pi                re         ab              aa         \n very liberal         : 8   never       :15   Mode :logical   Mode :logical  \n liberal              :24   occasionally:29   FALSE:60        FALSE:59       \n slightly liberal     : 6   most weeks  : 7                   NA's :1        \n moderate             :10   every week  : 9                                  \n slightly conservative: 6                                                    \n conservative         : 4                                                    \n very conservative    : 2                                                    \n     ld         \n Mode :logical  \n FALSE:44       \n NA's :16       \n                \n                \n                \n                \n```\n:::\n\n```{.r .cell-code}\nhead(student.survey)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"subj\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"ge\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"ag\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"hi\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"co\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"dh\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"dr\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"tv\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sp\"],\"name\":[9],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"ne\"],\"name\":[10],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"ah\"],\"name\":[11],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"ve\"],\"name\":[12],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"pa\"],\"name\":[13],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"pi\"],\"name\":[14],\"type\":[\"ord\"],\"align\":[\"right\"]},{\"label\":[\"re\"],\"name\":[15],\"type\":[\"ord\"],\"align\":[\"right\"]},{\"label\":[\"ab\"],\"name\":[16],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"aa\"],\"name\":[17],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"ld\"],\"name\":[18],\"type\":[\"lgl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"m\",\"3\":\"32\",\"4\":\"2.2\",\"5\":\"3.5\",\"6\":\"0\",\"7\":\"5.0\",\"8\":\"3\",\"9\":\"5\",\"10\":\"0\",\"11\":\"0\",\"12\":\"FALSE\",\"13\":\"r\",\"14\":\"conservative\",\"15\":\"most weeks\",\"16\":\"FALSE\",\"17\":\"FALSE\",\"18\":\"FALSE\",\"_rn_\":\"1\"},{\"1\":\"2\",\"2\":\"f\",\"3\":\"23\",\"4\":\"2.1\",\"5\":\"3.5\",\"6\":\"1200\",\"7\":\"0.3\",\"8\":\"15\",\"9\":\"7\",\"10\":\"5\",\"11\":\"6\",\"12\":\"FALSE\",\"13\":\"d\",\"14\":\"liberal\",\"15\":\"occasionally\",\"16\":\"FALSE\",\"17\":\"FALSE\",\"18\":\"NA\",\"_rn_\":\"2\"},{\"1\":\"3\",\"2\":\"f\",\"3\":\"27\",\"4\":\"3.3\",\"5\":\"3.0\",\"6\":\"1300\",\"7\":\"1.5\",\"8\":\"0\",\"9\":\"4\",\"10\":\"3\",\"11\":\"0\",\"12\":\"FALSE\",\"13\":\"d\",\"14\":\"liberal\",\"15\":\"most weeks\",\"16\":\"FALSE\",\"17\":\"FALSE\",\"18\":\"NA\",\"_rn_\":\"3\"},{\"1\":\"4\",\"2\":\"f\",\"3\":\"35\",\"4\":\"3.5\",\"5\":\"3.2\",\"6\":\"1500\",\"7\":\"8.0\",\"8\":\"5\",\"9\":\"5\",\"10\":\"6\",\"11\":\"3\",\"12\":\"FALSE\",\"13\":\"i\",\"14\":\"moderate\",\"15\":\"occasionally\",\"16\":\"FALSE\",\"17\":\"FALSE\",\"18\":\"FALSE\",\"_rn_\":\"4\"},{\"1\":\"5\",\"2\":\"m\",\"3\":\"23\",\"4\":\"3.1\",\"5\":\"3.5\",\"6\":\"1600\",\"7\":\"10.0\",\"8\":\"6\",\"9\":\"6\",\"10\":\"3\",\"11\":\"0\",\"12\":\"FALSE\",\"13\":\"i\",\"14\":\"very liberal\",\"15\":\"never\",\"16\":\"FALSE\",\"17\":\"FALSE\",\"18\":\"FALSE\",\"_rn_\":\"5\"},{\"1\":\"6\",\"2\":\"m\",\"3\":\"39\",\"4\":\"3.5\",\"5\":\"3.5\",\"6\":\"350\",\"7\":\"3.0\",\"8\":\"4\",\"9\":\"5\",\"10\":\"7\",\"11\":\"0\",\"12\":\"FALSE\",\"13\":\"d\",\"14\":\"liberal\",\"15\":\"occasionally\",\"16\":\"FALSE\",\"17\":\"FALSE\",\"18\":\"NA\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstudent.survey %>%\n  \n  # Group by religiosity and political ideology and count the number of observations\n  group_by(re, pi) %>%\n  summarize(count = n(), .groups = \"drop\") %>%\n  # Create a stacked bar chart\n  ggplot() + \n  geom_col(aes(x = re, y = count, fill = pi), position = \"stack\") +\n  # Add labels to x and y axis\n  xlab(\"Religiosity\") +\n  ylab(\"Count\") +\n  # Add a legend to show the relationship between fill colors and political ideology\n  scale_fill_discrete(name = \"Political ideology\")\n```\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\nConservatism and religiosity appear to be positively correlated, meaning that individuals who are more religious tend to be more conservative in their political beliefs.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=student.survey, aes(x=tv, y=hi))+\ngeom_point()+\ngeom_smooth(method=\"lm\", se=FALSE)+\nxlab(\"Average Number of Hours of TV watched per Week\") +\nylab(\"High School GPA\") \n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](HW3_AkhileshKumarMeghwal_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\nHigh school GPA and TV-watching seem to have a negative relationship.\n\n### (b)\n\nSummarize and interpret results of inferential analyses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(data = student.survey, formula = as.numeric(pi) ~ as.numeric(re)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = as.numeric(pi) ~ as.numeric(re), data = student.survey)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.81243 -0.87160  0.09882  1.12840  3.09882 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      0.9308     0.4252   2.189   0.0327 *  \nas.numeric(re)   0.9704     0.1792   5.416 1.22e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.345 on 58 degrees of freedom\nMultiple R-squared:  0.3359,\tAdjusted R-squared:  0.3244 \nF-statistic: 29.34 on 1 and 58 DF,  p-value: 1.221e-06\n```\n:::\n:::\n\nThis output is from a linear regression model that examines the relationship between religiousness (re) and political ideology (pi) in a sample of students. The model shows that there is a statistically significant positive relationship between religiousness and political ideology. \n\nThe intercept coefficient is 0.9308, which means that when religiousness is zero, the expected value of political ideology is 0.9308. The slope coefficient for religiousness is 0.9704, which means that for a one-unit increase in religiousness, the expected value of political ideology increases by 0.9704 units. The R-squared value is 0.3359, which indicates that the model explains 33.59% of the variation in political ideology. \n\nThe p-value for the slope coefficient is 1.221e-06, which is less than 0.05, indicating that the relationship between religiousness and political ideology is statistically significant. Therefore, we can conclude that there is a positive relationship between religiousness and political ideology in the sample of students.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(data = student.survey, formula = hi ~ tv))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = hi ~ tv, data = student.survey)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.2583 -0.2456  0.0417  0.3368  0.7051 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.441353   0.085345  40.323   <2e-16 ***\ntv          -0.018305   0.008658  -2.114   0.0388 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4467 on 58 degrees of freedom\nMultiple R-squared:  0.07156,\tAdjusted R-squared:  0.05555 \nF-statistic: 4.471 on 1 and 58 DF,  p-value: 0.03879\n```\n:::\n:::\n\nThis analysis reports the results of a linear regression model to investigate the relationship between average hours of TV watched per week (TV) and high school GPA (hi) using data from student survey.\n\nThe model shows that the intercept is statistically significant at a p-value < 2e-16, indicating that the predicted value of the high school GPA when the average number of hours of TV watched per week is zero is 3.44. This value can be interpreted as the expected high school GPA for students who do not watch any TV.\n\nFurthermore, the coefficient for TV is -0.018 with a p-value of 0.0388, which indicates that there is a statistically significant negative association between TV watching and high school GPA at the 0.05 level of significance. The negative coefficient suggests that as the average number of hours of TV watched per week increases by 1 hour, high school GPA decreases by 0.018.\n\nThe model's R-squared value is 0.07156, indicating that only about 7% of the variance in high school GPA is explained by the variance in the average number of hours of TV watched per week. The adjusted R-squared value is 0.05555, which means that the model has a weak predictive power for high school GPA based on the average number of hours of TV watched per week.\n\nIn summary, the results suggest that there is a negative association between TV watching and high school GPA. However, the model's low R-squared value suggests that other factors not included in the model might be more important in predicting high school GPA.\n\n",
    "supporting": [
      "HW3_AkhileshKumarMeghwal_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}