{
  "hash": "1b319bbdc74d98995a798e994abf7afb",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Abigail Balint\"\ndesription: \"HW2 Responses\"\ndate: \"04/03/23\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - homework2\n  - abigailbalint\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(readxl)\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Question 1\n\nGenerating a table here to calculate standard deviation\n\n::: {.cell}\n\n```{.r .cell-code}\nheart <- matrix(c(539, 19, 10, 847, 18, 9), ncol=3, byrow=TRUE)\ncolnames(heart) <- c('Sample Size','Mean Wait Time','Standard Deviation')\nrownames(heart) <- c('Bypass','Angiography')\nheart <- as.table(heart)\nhead(heart)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Sample Size Mean Wait Time Standard Deviation\nBypass              539             19                 10\nAngiography         847             18                  9\n```\n:::\n:::\n\n\nCalculating confidence interval for Bypass:\n\n::: {.cell}\n\n```{.r .cell-code}\nstander1 <- 10/sqrt(539)\nconfidence_level <- 0.90 \ntail_area <- (1-confidence_level)/2\nt_score <- qt(p = 1-tail_area, df = 539-1)\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691\n```\n:::\n\n```{.r .cell-code}\nCI <- c(19 - t_score * stander1,\n        19 + t_score * stander1)\nprint(CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n:::\n\n\nCalculating confidence interval for Angiography:\n\n::: {.cell}\n\n```{.r .cell-code}\nstander2 <- 9/sqrt(847)\nconfidence_level <- 0.90 \ntail_area <- (1-confidence_level)/2\nt_score <- qt(p = 1-tail_area, df = 847-1)\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.646657\n```\n:::\n\n```{.r .cell-code}\nCI <- c(18 - t_score * stander2,\n        18 + t_score * stander2)\nprint(CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nBypassInt <- 19.70971 - 18.29029\nAngiographyInt <- 18.50922-17.49078 \nprint(BypassInt)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.41942\n```\n:::\n\n```{.r .cell-code}\nprint(AngiographyInt) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.01844\n```\n:::\n:::\n\nQuestion: Is the confidence interval narrower for angiography or bypass surgery?\nAnswer: The interval for angiography surgery is shorter at an interval of 1.01.\n\n## Question 2\n\nHere I am using a prop test function to find the p value - \n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(567, 1031, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  567 out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\nAnswer: To interpret this, I am looking at my confidence interval and seeing that the true population mean of those who believe college is needed for success is somewhere between 52-58% which makes sense because the reported percentage from this random sample who believe college is needed for success is 54%, inside of that range.\n\n## Question 3\n\nMy calculations to find the sample size are step by step in the below code block:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Starting by trying to find margin of error:\n#Formula is error= z * SD/sqrt of n\n#By squaring the whole thing, can transform this formular to to n=z^2*SD^2/error^2\n# Z score for 95% confidence is 1.96\n1.96^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.8416\n```\n:::\n\n```{.r .cell-code}\n#n=3.8416*SD^2/error^2\n#Finding the range and dividing it by 4 since we know SD is quarter of the range\n(200-30)/4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.5\n```\n:::\n\n```{.r .cell-code}\n42.5^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1806.25\n```\n:::\n\n```{.r .cell-code}\n#Now formula looks like this and just need to find standard error n=3.8416*1806.25/error^2\n#We know that margin of error is 5 (within $5)\n5^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 25\n```\n:::\n\n```{.r .cell-code}\n#Now we can fill in the final formula n=3.8416*1806.25/25\n(3.8416*1806.25)/25\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n\n```{.r .cell-code}\n#n=277.56\n```\n:::\n\nAnswer: The sample size should be about 278 (rounded)\n\n## Question 4\n\nA. Test whether the mean income of female employees differs from $500 per week. Include\nassumptions, hypotheses, test statistic, and P-value. Interpret the result.\n\nAssumptions - \n-Randomly generated sample\n-From the same general population\n-Distribution is normal\n\nNull hypothesis - females earn  $500 a week\nAlternative hypothesis - females earn more or less than $500 a week\n\nCalculating the t value below using standard formula -\n\nt= (sample mean-population mean)/(standard deviation/sample size^2)\n\n::: {.cell}\n\n```{.r .cell-code}\ntvalue =  (410 - 500) / (90/sqrt(9))\ntvalue\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\nAnswer: t=-3\n\nThis tells us that the mean of the female group is three standard deviations away from the mean of the overall group's pay.\n\nB. Report the P-value for alternative hypothesis: μ < 500. Interpret.\n\nCalculating p-value -\n\nFormula pt(q = t, df =standardeviation-1, lower.tail = TRUE)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt(q = tvalue, df =8, lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nAnswer: .01 (rounded)\n\nA p-value of .01 means we can reject the alternative hypothesis (mean for females < 500 a week)\n\nC. Report and interpret the P-value for alternative hypothesis: μ > 500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt(q = tvalue, df =8, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n \n Answer: .99 (rounded)\nThis is the same but flipped, can reject the alternative hypothesis (mean for females > 500 a week)\n\n\n## Question 5\n\n\nUsing formula t= sample mean-population mean/standard error\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt=(519.5-500)/10\nprint(t)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\npt(q = t, df = 999, lower.tail = FALSE)*2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\nAnswer: Jones t=1.95, p=.051\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt=(519.7-500)/10\nprint(t)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\npt(q = t, df = 999, lower.tail = FALSE)*2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\nAnswer: Smith t=1.97, p=.049\n\nB. This makes Smith statistically significant because .049 falls below .05 but .051 does not.\n\nC. This shows that results presented this way can be misleading because even though the p-values are extremely close here, one would report rejecting the null hypothesis and one wouldn't even though the differences in results are marginal.\n\n## Question 6\n\n\nNull hypothesis: Proportion of those who choose healthy snacks is not equal by grade level.\n\nGenerating table -\n\n::: {.cell}\n\n```{.r .cell-code}\nsnack <- matrix(c(31, 43, 51, 69, 57, 49), ncol=3, byrow=TRUE)\ncolnames(snack) <- c('6th','7th','8th')\nrownames(snack) <- c('healthy','unhealthy')\nsnack <- as.table(snack)\nhead(snack)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          6th 7th 8th\nhealthy    31  43  51\nunhealthy  69  57  49\n```\n:::\n:::\n\n\nPerforming chi squared test - \n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(snack, .05, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  snack\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\nSince the p value is .01 we can assume that there is a difference by grade level in those who choose unhealthy vs healthy snacks, rejecting null hypothesis.\n\n## Question 7\n\n\nNull hypothesis: There is no difference in per-pupil costs between areas.\n\nGenerating data frame -\n\n\n::: {.cell}\n\n```{.r .cell-code}\narea <- c(rep(\"Area1\", 6), rep(\"Area2\", 6), rep(\"Area3\", 6))\ncost <- c(6.2, 9.3, 6.8, 6.1, 6.7, 7.5, 7.5, 8.2, 8.5, 8.2, 7.0, 9.3,\n          5.8, 6.4, 5.6, 7.1, 3.0, 3.5)\ntuition <- data.frame(area,cost)\nhead(tuition)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   area cost\n1 Area1  6.2\n2 Area1  9.3\n3 Area1  6.8\n4 Area1  6.1\n5 Area1  6.7\n6 Area1  7.5\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nanova <- aov(cost ~ area, data = tuition)\nsummary(anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \narea         2  25.66  12.832   8.176 0.00397 **\nResiduals   15  23.54   1.569                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\nInterpretation: The p value is very low indicating there is a difference and we can reject the null hypothesis.\n:",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}