{
  "hash": "2eedaa61d21afc51f2e9da9fd5ef6fad",
  "result": {
    "markdown": "---\ntitle: \"Homework 4\"\nauthor: \"Abigail Balint\"\ndesription: \"HW4 Responses\"\ndate: \"04/24/23\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw4\n  - homework4\n  - abigailbalint\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(readxl)\nlibrary(alr4)\nlibrary(smss)\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n# Question 1\n\n\na) Equation: ŷ = −10,536 + 53.8x1 + 2.84x2\nSubbing the size of home and lot size out for the variables in the equation:\nŷ = −10,536 + 53.8(1240) + 2.84(18000)\nsolving for y:\n\n::: {.cell}\n\n```{.r .cell-code}\na = -10536 + (53.8*1240) + (2.84*18000)\nprint(a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n\n```{.r .cell-code}\na2=145000-a\nprint(a2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37704\n```\n:::\n:::\n\n\nThe predicted selling price is 107296. To find the residual, I am subtracting what it sold for from the predicted price. This means our prediction was low and the house sold for 37704 more than was predicted.\n\nb) It is predicted to increase 53.8 dollars per square foot as this is the coefficient in the equation for home size square footage.\n\nc) I think because the coefficient for home size is so much bigger than lot size, if we divide the coefficients by each other that would give the amount of home square feet we would need to have the same impact of one square foot in lot size, so 18.94 sq feet.\n\n::: {.cell}\n\n```{.r .cell-code}\nc=53.8/2.84\nprint(c)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\n# Question 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     degree      rank        sex          year            ysdeg      \n Masters:34   Asst :18   Male  :38   Min.   : 0.000   Min.   : 1.00  \n PhD    :18   Assoc:14   Female:14   1st Qu.: 3.000   1st Qu.: 6.75  \n              Prof :20               Median : 7.000   Median :15.50  \n                                     Mean   : 7.481   Mean   :16.12  \n                                     3rd Qu.:11.000   3rd Qu.:23.25  \n                                     Max.   :25.000   Max.   :35.00  \n     salary     \n Min.   :15000  \n 1st Qu.:18247  \n Median :23719  \n Mean   :23798  \n 3rd Qu.:27258  \n Max.   :38045  \n```\n:::\n:::\n\n\n\na) The p value is .07 so we fail to reject the null hypothesis and are not able to say there is a significant difference in male vs female salaries.\n\n::: {.cell}\n\n```{.r .cell-code}\nmale <- salary %>%\n  filter(sex == \"Male\")\nfemale <- salary %>%\n  filter(sex == \"Female\")\nt.test(male$salary, female$salary, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  male$salary and female$salary\nt = 1.8474, df = 50, p-value = 0.0706\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -291.257 6970.550\nsample estimates:\nmean of x mean of y \n 24696.79  21357.14 \n```\n:::\n:::\n\nb) Fitting model and summary below:\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(salary ~ degree + rank + sex + year + ysdeg, data = salary)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nc:\ndegree: Degree has a positive coefficient but not a significant p-value, indicating as degree increases salary does as well but not at a statistically significant level.\nrank: Rank has a very high positive coefficient as well as being very statistically significant, indicating a strong relationship between this variable and salary.\nsex: Similarly to degree, sex has a positive coefficient but not a significant p-value, indicating a positive slope here but not a statistically significant level.\nyear: This variable is statistically significant with a positive slope indicating more years in a current rank may increase salary.\nysdeg: This variable is not significant and actually has a negative slope/coefficient.\n\nd: When I relevel rank I can see that it flips rank to have a negative slope/coefficient now instead of a positive one.\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(salary$rank)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Asst\"  \"Assoc\" \"Prof\" \n```\n:::\n\n```{.r .cell-code}\nrankrl <- relevel(salary$rank, ref=\"Prof\")\nmodel2 <- lm(salary ~ degree + rankrl + sex + year + ysdeg, data = salary)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rankrl + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankrlAsst  -11118.76    1351.77  -8.225 1.62e-10 ***\nrankrlAssoc  -5826.40    1012.93  -5.752 7.28e-07 ***\nsexFemale     1166.37     925.57   1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\ne.When I take rank out of the model, year and ysdeg now have a p-value that is statistically significant (a drastic change).\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- lm(salary ~ degree + sex + year + ysdeg, data = salary)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\nf. To avoid multicollinearity, I don't think we should use year and ysdeg both within the model since we now know there is an interaction due to the new dean 15 years ago that could cause these two variables to be related.\n\nBelow I am making a new variable that is if there is more than 15 years since highest degree they are assigned yes, otherwise no. I can see when fitting a model against salary this is very statistically significant, indicating the dean may have had an impact.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary2 <- salary  %>%\n  mutate(ysdeg15 = ifelse(ysdeg > 15, \"yes\", \"no\"))\nmodel4 <- lm(salary ~ ysdeg15, data = salary2)\nsummary(model4)    \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ysdeg15, data = salary2)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -8294  -3486  -1772   3829  10576 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  20125.9      913.4  22.033  < 2e-16 ***\nysdeg15yes    7343.5     1291.8   5.685 6.73e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4658 on 50 degrees of freedom\nMultiple R-squared:  0.3926,\tAdjusted R-squared:  0.3804 \nF-statistic: 32.32 on 1 and 50 DF,  p-value: 6.734e-07\n```\n:::\n:::\n\n\n# Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(smss)\ndata(\"house.selling.price\")\nhouse <- house.selling.price\nsummary(house)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      case            Taxes           Beds       Baths           New      \n Min.   :  1.00   Min.   :  20   Min.   :2   Min.   :1.00   Min.   :0.00  \n 1st Qu.: 25.75   1st Qu.:1178   1st Qu.:3   1st Qu.:2.00   1st Qu.:0.00  \n Median : 50.50   Median :1614   Median :3   Median :2.00   Median :0.00  \n Mean   : 50.50   Mean   :1908   Mean   :3   Mean   :1.96   Mean   :0.11  \n 3rd Qu.: 75.25   3rd Qu.:2238   3rd Qu.:3   3rd Qu.:2.00   3rd Qu.:0.00  \n Max.   :100.00   Max.   :6627   Max.   :5   Max.   :4.00   Max.   :1.00  \n     Price             Size     \n Min.   : 21000   Min.   : 580  \n 1st Qu.: 93225   1st Qu.:1215  \n Median :132600   Median :1474  \n Mean   :155331   Mean   :1629  \n 3rd Qu.:169625   3rd Qu.:1865  \n Max.   :587000   Max.   :4050  \n```\n:::\n:::\n\na) Based on this model, both whether it is new or not and the size are statistically significant variables in predicting price, although size is much more significant with a much smaller p value, the positive coefficient for whether the home is new or not is much higher.\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel5 <- lm(Price ~ New + Size, data = house)\nsummary(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ New + Size, data = house)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nNew          57736.283  18653.041   3.095  0.00257 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\nb) Prediction equation for new:\ny=-40230.867 + 57736.283*new + 116.132*size\n\nc) 3000 square feet for new vs not:\n\n::: {.cell}\n\n```{.r .cell-code}\nnew <- -40230.867 + 57736.283*1 + 116.132*3000\nprint (new)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 365901.4\n```\n:::\n\n```{.r .cell-code}\nnotnew <- -40230.867 + 57736.283*0 + 116.132*3000\nprint(notnew)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 308165.1\n```\n:::\n:::\n\nSelling price of new: 365901.4\nSelling price of not new: 308165.1\n\nd) Fitting model with interaction: \n\n::: {.cell}\n\n```{.r .cell-code}\nmodel6 <- lm(Price ~ New*Size, data = house)\nsummary(model6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ New * Size, data = house)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nNew         -78527.502  51007.642  -1.540  0.12697    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew:Size        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\ne) Plot for new:\n\n::: {.cell}\n\n```{.r .cell-code}\nhousenew <- house %>%\n  filter(New==1)\nggplot(data = housenew, aes(x = Size, y = Price)) +\n  geom_point() +\n  labs(x = \"Home size\", y = \"Selling price\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](abigailbalint_hw4_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nPlot for not new:\n\n::: {.cell}\n\n```{.r .cell-code}\nhousenotnew <- house %>%\n  filter(New==0)\nggplot(data = housenotnew, aes(x = Size, y = Price)) +\n  geom_point() +\n  labs(x = \"Home size\", y = \"Selling price\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](abigailbalint_hw4_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nf) Same answer as C I think.\n\ng) c) 300 square feet for new vs not was:\nSelling price of new: 365901.4\nSelling price of not new: 308165.1\n\nNow doing this for 1500 sf I got the same result. Is thi s because the new vs not new coefficient holds so much weight here?\n\n::: {.cell}\n\n```{.r .cell-code}\nnew2 <- -40230.867 + 57736.283*1 + 116.132*1500\nprint (new)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 365901.4\n```\n:::\n\n```{.r .cell-code}\nnotnew2 <- -40230.867 + 57736.283*0 + 116.132*1500\nprint(notnew)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 308165.1\n```\n:::\n:::\n\n\nh) I would use the model without interaction here because since the new vs not is so strong I feel like it overpowers the size variable and it makes more sense to look at them separately.",
    "supporting": [
      "abigailbalint_hw4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}