{
  "hash": "41bc527cc0e6b2daf3037484c1e4815f",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Caitlin Rowley\"\ndescription: \"Template of course blog qmd file\"\ndate: \"02/26/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n\n### Question 1a: What does the distribution of LungCap look like?\n\nFirst, let's read in the data from the Excel file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readxl' was built under R version 4.2.2\n```\n:::\n\n```{.r .cell-code}\ndf <- read_excel(\"_data/LungCapData.xls\")\n```\n:::\n\n\nThe distribution of LungCap looks as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df$LungCap)\n```\n\n::: {.cell-output-display}\n![](Rowley_Homework_1_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe histogram suggests that the distribution is close to a normal distribution. Most of the observations are close to the mean. Very few observations are close to the margins (0 and 15).\n\n### Question 1b: Compare the probability distribution of the LungCap with respect to Males and Females. (Hint:make boxplots separated by gender using the boxplot() function)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(magrittr)\nlibrary(ggplot2)\nlibrary(markdown)\nlibrary(ggtext)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggtext' was built under R version 4.2.2\n```\n:::\n\n```{.r .cell-code}\n# generate boxplot:\n\nLungCap_Gender <- LungCapData%>%\n  group_by(LungCapData$Gender)%>%\n  ggplot(aes(x=Gender, y=LungCap)) +\n  geom_point(alpha=.08, size=5) +\n  labs(x=\"Gender\", y=\"LungCap\", title=\"LungCap by Gender\") +\n  theme_light() +\n  geom_boxplot() +\n  theme(axis.text.x=element_markdown(hjust=1))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in group_by(., LungCapData$Gender): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nLungCap_Gender\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'LungCap_Gender' not found\n```\n:::\n\n```{.r .cell-code}\n# would next like to identify specific values for boxplots...\n```\n:::\n\n\nThe distribution of LungCap is higher for males than it is for females. For males, the Q1 value is approximately 6.5, the median value is approximately 8, and the Q3 value is approximately 10. For females, the Q1 value is approximately 5.5, the median value is approximately 7.5, and the Q3 value is approximately 9.\n\n### Question 1c: Compare the mean lung capacities for smokers and non-smokers. Does it make sense?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSmoker_Mean <- LungCapData %>%\n  filter(Smoke==\"yes\")%>%\n  select(Smoke, LungCap)%>%\n  summarize(mean(LungCap, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in filter(., Smoke == \"yes\"): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nSmoker_Mean\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'Smoker_Mean' not found\n```\n:::\n\n```{.r .cell-code}\nNonSmoker_Mean <- LungCapData %>%\n  filter(Smoke==\"no\")%>%\n  select(Smoke, LungCap)%>%\n  summarize(mean(LungCap, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in filter(., Smoke == \"no\"): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nNonSmoker_Mean\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'NonSmoker_Mean' not found\n```\n:::\n:::\n\n\nThe mean LungCap for smokers is 8.645, while the mean LungCap for non-smokers is 7.77. This doesn't seem to make sense!\n\n### Question 1d: Examine the relationship between Smoking and Lung Capacity within age groups: \"less than or equal to 13\", \"14 to 15\", \"16 to 17\", and \"greater than or equal to 18\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSmoker_Age_1 <- LungCapData %>%\n  filter(Smoke==\"yes\")%>%\n  filter(Age<=13)%>%\n  select(Smoke, Age, LungCap)%>%\n  summarize(mean(LungCap, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in filter(., Smoke == \"yes\"): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nSmoker_Age_1\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'Smoker_Age_1' not found\n```\n:::\n\n```{.r .cell-code}\nSmoker_Age_2 <- LungCapData %>%\n  filter(Smoke==\"yes\")%>%\n  filter(Age==14:15)%>%\n  select(Smoke, Age, LungCap)%>%\n  summarize(mean(LungCap, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in filter(., Smoke == \"yes\"): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nSmoker_Age_2\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'Smoker_Age_2' not found\n```\n:::\n\n```{.r .cell-code}\nSmoker_Age_3 <- LungCapData %>%\n  filter(Smoke==\"yes\")%>%\n  filter(Age==16:17)%>%\n  select(Smoke, Age, LungCap)%>%\n  summarize(mean(LungCap, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in filter(., Smoke == \"yes\"): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nSmoker_Age_3\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'Smoker_Age_3' not found\n```\n:::\n\n```{.r .cell-code}\nSmoker_Age_4 <- LungCapData %>%\n  filter(Smoke==\"yes\")%>%\n  filter(Age>=18)%>%\n  select(Smoke, Age, LungCap)%>%\n  summarize(mean(LungCap, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in filter(., Smoke == \"yes\"): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nSmoker_Age_4\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'Smoker_Age_4' not found\n```\n:::\n:::\n\n\nThe mean LungCap value for smokers 13 years or younger is 7.202, whereas it is 8.909 for those ages 14-15. For smokers 16-17, the mean LungCap value is 9.602, and for those 18 years and older, it is 10.513.\n\n### Question 1e: Compare the lung capacities for smokers and non-smokers within each age group. Is your answer different from the one in part c? What could possibly be going on here?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNonSmoker_Age_1 <- LungCapData %>%\n  filter(Smoke==\"no\")%>%\n  filter(Age<=13)%>%\n  select(Smoke, Age, LungCap)%>%\n  summarize(mean(LungCap, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in filter(., Smoke == \"no\"): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nNonSmoker_Age_1\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'NonSmoker_Age_1' not found\n```\n:::\n\n```{.r .cell-code}\nNonSmoker_Age_2 <- LungCapData %>%\n  filter(Smoke==\"no\")%>%\n  filter(Age==14:15)%>%\n  select(Smoke, Age, LungCap)%>%\n  summarize(mean(LungCap, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in filter(., Smoke == \"no\"): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nNonSmoker_Age_2\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'NonSmoker_Age_2' not found\n```\n:::\n\n```{.r .cell-code}\nNonSmoker_Age_3 <- LungCapData %>%\n  filter(Smoke==\"no\")%>%\n  filter(Age==16:17)%>%\n  select(Smoke, Age, LungCap)%>%\n  summarize(mean(LungCap, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in filter(., Smoke == \"no\"): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nNonSmoker_Age_3\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'NonSmoker_Age_3' not found\n```\n:::\n\n```{.r .cell-code}\nNonSmoker_Age_4 <- LungCapData %>%\n  filter(Smoke==\"no\")%>%\n  filter(Age>=18)%>%\n  select(Smoke, Age, LungCap)%>%\n  summarize(mean(LungCap, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in filter(., Smoke == \"no\"): object 'LungCapData' not found\n```\n:::\n\n```{.r .cell-code}\nNonSmoker_Age_4\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'NonSmoker_Age_4' not found\n```\n:::\n:::\n\n\nThe corresponding LungCap mean values for non-smokers are 6.359, 8.844, 10.394, and 11.069. All LungCaps are higher for non-smokers with the exception of those in the 13-and-under age bracket. It would make sense that non-smokers would have higher lung capacities, though it is interesting that the value is lower for the youngest age group. This does, however, correlate with the results to question 1c, which indicated that smokers have higher lung capacities than non-smokers; there could, perhaps, be other extenuating circumstances contributing to these lower rates of capacity, such as health issues, development, or exposure.\n\n### Question 2a: What is the probability that a randomly selected inmate has exactly 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninmate <- c(128, 434, 160, 64, 24)\nmean(inmate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 162\n```\n:::\n\n```{.r .cell-code}\nsd(inmate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 161.0838\n```\n:::\n\n```{.r .cell-code}\n# mean=162\n# sd=161.1\n\nconvictions <- c(0:4)\n\ndata <- tibble(inmate, convictions)\n\ntwo <- 160/summarise(data, sum(inmate))\n  two\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sum(inmate)\n1   0.1975309\n```\n:::\n:::\n\n\nHere, we can see that the probability of an inmate having exactly two prior convictions is 19.8%.\n\n### Question 2b: What is the probability that a randomly selected inmate has fewer than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfewer_than_two <- 128 + 434\nfewer_than_two/summarise(data, sum(inmate))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sum(inmate)\n1   0.6938272\n```\n:::\n:::\n\n\nHere, we can see that the probability of a randomly selected inmate having fewer than two prior convictions is 69.4%.\n\n### Question 2c: What is the probability that a randomly selected inmate has 2 or fewer prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_or_fewer <- 128 + 434 + 160\ntwo_or_fewer/summarise(data, sum(inmate))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sum(inmate)\n1    0.891358\n```\n:::\n:::\n\n\nHere, we can see that the probability of a randomly selected inmate having two or fewer prior convictions is 89.1%.\n\n### Question 2d: What is the probability that a randomly selected inmate has more than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmore_than_two <- 160 + 64 + 24\nmore_than_two/summarise(data, sum(inmate))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sum(inmate)\n1   0.3061728\n```\n:::\n:::\n\n\nHere, we can see that the probability of a randomly selected inmate having more than two prior convictions is 30.6%.\n\n### Question 2e: What is the expected value1 for the number of prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_prob <- transform(data, probability = (inmate/810))\ndata_ev <- transform(data_prob, x = convictions*probability)\n\nEV <- sum(data_ev$x)\nEV\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\nThe expected value1 for the number of prior convictions is 1.3.\n\n### Question 2f: Calculate the variance and the standard deviation for the Prior Convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninmate <- c(128, 434, 160, 64, 24)\nvar(inmate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 25948\n```\n:::\n\n```{.r .cell-code}\nsd(inmate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 161.0838\n```\n:::\n:::\n\n\nThe variance for the prior convictions is 25948, while the standard deviation is 161.\n",
    "supporting": [
      "Rowley_Homework_1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}