{
  "hash": "5c2e492a7fa5c9ed14eafafa9aa8678f",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Abigail Balint\"\ndesription: \"Distributions and probability\"\ndate: \"02/23/23\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - homework1\n  - abigailbalint\n  - lungcap\n  - prisoner\n  - ggplot2\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(readxl)\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Question 1 - Lung Capacity \n\nReading in LungCapData --\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlung <- read_excel(\"_data/LungCapData.xls\")\nhead(lung,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  LungCap   Age Height Smoke Gender Caesarean\n    <dbl> <dbl>  <dbl> <chr> <chr>  <chr>    \n1    6.48     6   62.1 no    male   no       \n2   10.1     18   74.7 yes   female no       \n```\n:::\n:::\n\nLooking at some basic descriptive stats --\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(lung)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 725\nColumns: 6\n$ LungCap   <dbl> 6.475, 10.125, 9.550, 11.125, 4.800, 6.225, 4.950, 7.325, 8.…\n$ Age       <dbl> 6, 18, 16, 14, 5, 11, 8, 11, 15, 11, 19, 17, 12, 10, 10, 13,…\n$ Height    <dbl> 62.1, 74.7, 69.7, 71.0, 56.9, 58.7, 63.3, 70.4, 70.5, 59.2, …\n$ Smoke     <chr> \"no\", \"yes\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\",…\n$ Gender    <chr> \"male\", \"female\", \"female\", \"male\", \"male\", \"female\", \"male\"…\n$ Caesarean <chr> \"no\", \"no\", \"yes\", \"no\", \"no\", \"no\", \"yes\", \"no\", \"no\", \"no\"…\n```\n:::\n\n```{.r .cell-code}\nmean(lung$LungCap, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.863148\n```\n:::\n\n```{.r .cell-code}\nvar(lung$LungCap, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.086288\n```\n:::\n\n```{.r .cell-code}\nsd(lung$LungCap, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.662008\n```\n:::\n\n```{.r .cell-code}\nrange(lung$LungCap, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  0.507 14.675\n```\n:::\n:::\n\n\na) What does the distribution of LungCap look like? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lung, aes(x = LungCap)) +\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](abigailbalint_hw1_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nThe distribution looks relatively normal. There is a clear concentration of the sample around 7-8 and the outliers are only a very small portion of the sample.\n\n\nb) Compare the probability distribution of the LungCap with respect to Males and Females\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lung, aes(x=LungCap)) + \n    geom_boxplot(fill=\"slateblue\", alpha=0.2) + \n    xlab(\"Lung Capacity\") +\n  facet_wrap(\"Gender\")\n```\n\n::: {.cell-output-display}\n![](abigailbalint_hw1_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nThe probability distribution is pretty similar between male and female, but males skew to a higher lung capacity overall and the median line is at around 8 whereas female is closer to 7.5. \n\nc) Compare the mean lung capacities for smokers and non-smokers. Does it make sense?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlung %>%\n  group_by(Smoke) %>%\n  summarise(mean = mean(LungCap), n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  Smoke  mean     n\n  <chr> <dbl> <int>\n1 no     7.77   648\n2 yes    8.65    77\n```\n:::\n:::\n\nWe would expect the lung capacities for non smokers to be higher but the mean for smokers is actually a little bit higher.\n\nd) Examine the relationship between Smoking and Lung Capacity within age groups: “less than or  equal to 13”, “14 to 15”, “16 to 17”, and “greater than or equal to 18”. \n\nRecoding the age groups --\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlunggroup <- lung %>%\n  mutate(`AgeGroup` = dplyr::case_when(\n    `Age` >= 0 & `Age` < 14 ~ \"0-13\",\n    `Age` >= 14 & `Age` < 16 ~ \"14-15\",\n    `Age` >= 16 & `Age` < 18 ~ \"16-17\",\n    `Age` >= 18 ~ \"18+\" ))\nhead(lunggroup)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 7\n  LungCap   Age Height Smoke Gender Caesarean AgeGroup\n    <dbl> <dbl>  <dbl> <chr> <chr>  <chr>     <chr>   \n1    6.48     6   62.1 no    male   no        0-13    \n2   10.1     18   74.7 yes   female no        18+     \n3    9.55    16   69.7 no    female yes       16-17   \n4   11.1     14   71   no    male   no        14-15   \n5    4.8      5   56.9 no    male   no        0-13    \n6    6.22    11   58.7 no    female no        0-13    \n```\n:::\n:::\n\nMean lung capacity by age group -- \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlunggroup %>%\ngroup_by(Smoke, AgeGroup) %>%\n  summarise(mean = mean(LungCap), n = n())\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'Smoke'. You can override using the\n`.groups` argument.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 4\n# Groups:   Smoke [2]\n  Smoke AgeGroup  mean     n\n  <chr> <chr>    <dbl> <int>\n1 no    0-13      6.36   401\n2 no    14-15     9.14   105\n3 no    16-17    10.5     77\n4 no    18+      11.1     65\n5 yes   0-13      7.20    27\n6 yes   14-15     8.39    15\n7 yes   16-17     9.38    20\n8 yes   18+      10.5     15\n```\n:::\n:::\n\nFor both smokers and non-smokers, the lung capacity goes up as the age increases with 18+ having the highest average capacity. In all age ranges besides 0-13 (the broadest range), the mean is higher for non-smokers than smokers.\n\ne. Compare the lung capacities for smokers and non-smokers within each age group. Is your answer  different from the one in part c. What could possibly be going on here? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lunggroup, aes(x=LungCap, fill=Smoke)) + \n    geom_boxplot() + \n    xlab(\"Lung Capacity\") +\n  facet_wrap(\"AgeGroup\")\n```\n\n::: {.cell-output-display}\n![](abigailbalint_hw1_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\nI'm seeing that the results by age group are slightly different than in part C. Above I can see that the average for all age ranges is higher for non-smokers, besides age group 0-13. I can see in my results in part D that the sample size for 0-13 non-smokers is extremely high, much higher than any other group of smokers or non-smokers, so with this higher sample size comes more variance. The median lines are actually pretty close but the outliers are probably affecting the mean.\n\n\n## Question 2 \n\nCreating a data frame -- \n\n\n::: {.cell}\n\n```{.r .cell-code}\npriorconviction <- c(0,1,2,3,4)\nprisoners <- c(128,434,160,64,24)\nq2 <- data.frame(priorconviction, prisoners)\nhead(q2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  priorconviction prisoners\n1               0       128\n2               1       434\n3               2       160\n4               3        64\n5               4        24\n```\n:::\n:::\n\n\n\na) What is the probability that a randomly selected inmate has exactly 2 prior convictions? \n\n::: {.cell}\n\n```{.r .cell-code}\n160/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1975309\n```\n:::\n:::\n\n I found it to be .1975 or 19.75%\n \nb) What is the probability that a randomly selected inmate has fewer than 2 prior convictions? \n\n::: {.cell}\n\n```{.r .cell-code}\n(434+128)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\nTo get this I added the sample of 0 or 1 prior conviction and it comes out to .69 or 69%.\n\nc) What is the probability that a randomly selected inmate has 2 or fewer prior convictions? \n\n::: {.cell}\n\n```{.r .cell-code}\n(128+434+160)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\nTo get this I added the sample of 0 or 1 or 2 prior convictions and it comes out to .89 or 89%.\n\nd) What is the probability that a randomly selected inmate has more than 2 prior convictions? \n\n::: {.cell}\n\n```{.r .cell-code}\n(64+24)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\nTo get this I added the sample of 3 or 4 prior convictions and it comes out to .108 or 11%.\n\ne) What is the expected value1 for the number of prior convictions? \n\n::: {.cell}\n\n```{.r .cell-code}\nsum(q2$priorconviction*prisoners)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1042\n```\n:::\n\n```{.r .cell-code}\n1042/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\nTo get this I summed all of the numbers of prior convictions by the amount of prisoners (1042) then divided this by total sample (810) to get a final expected value of 1.28 prior convictions.\n\nf) Calculate the variance and the standard deviation for the Prior Convictions. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(q2$priorconviction)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.5\n```\n:::\n\n```{.r .cell-code}\nvar(q2$priorconviction)*(5-1)/5\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2\n```\n:::\n:::\n\n\nI used the above code to find a sample variance of 2.5 and a population variance of 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(q2$priorconviction)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.581139\n```\n:::\n:::\n\n\nI used the standard deviation function to calculate the above.\n\n\n:::",
    "supporting": [
      "abigailbalint_hw1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}