{
  "hash": "6e6fa6fe663cd8a5ec7584e7a957b02d",
  "result": {
    "markdown": "---\ntitle: \"Final Project\"\nauthor: \"Thrishul Pola\"\ndescription: \"Final Project\"\ndate: \"5/2/2023\"\nformat:\n  html:\n    df-print: paged\n    css: styles.css\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Final_Project\n---\n\n\n# Research Question\n\nCan the reading and writing scores, along with gender, be used as predictors for students math exam scores?\n\n## Hypothesis\n\nThe math exam scores of students are positively associated with their reading and writing scores.\n\nThe math exam scores of male students are higher than those of female students.\n\n## Importing Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressWarnings(suppressPackageStartupMessages({\nlibrary(tidyverse) \nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(fBasics) \nlibrary(kableExtra)\nlibrary(funModeling)\nlibrary(plotly)\nlibrary(MASS)\nlibrary(corrplot)\n}))\n```\n:::\n\n\n## Reading and Analysing Dataset\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv(\"_data/S.csv\", show_col_types = FALSE)\nnames_columns <- c(\"gender\",\"race\",\"parent_education\",\"lunch\",\"test_prep\",\"math_score\",\"reading_score\",\"writing_score\")\ncolnames(data) <- names_columns\n```\n:::\n\n# Dataset Description\n\nThe \"Students Performance in Exams\" dataset contains information about the marks obtained by students in different subjects. The dataset consists of 1000 rows and 8 features.\n\nThe categorical features in the dataset include:\n\nGender: Indicates whether the student is female or male.\nRace/Ethnicity: Represents the group to which the student belongs, categorized as Group A, Group B, Group C, Group D, or Group E.\nParental Level of Education: Reflects the educational level of the student's parents, such as associate's degree, bachelor's degree, high school, etc.\nLunch: Specifies the type of lunch provided to the student, categorized as either free/reduced or standard.\nTest Preparation Course: Indicates whether the student completed a test preparation course or not.\n\nThe numerical features in the dataset are:\n\nMath Score: Represents the marks obtained by the student in the math subject.\nReading Score: Represents the marks obtained by the student in the reading subject.\nWriting Score: Represents the marks obtained by the student in the writing subject.\nAll the scores in the dataset are measured on a scale of 0 to 100.\n\nThe dataset provides valuable insights into the performance of students in exams across various subjects. By analyzing this data, we can explore the relationships between different features and understand the factors that influence students' academic achievements.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    gender              race           parent_education      lunch          \n Length:1000        Length:1000        Length:1000        Length:1000       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n  test_prep           math_score     reading_score    writing_score   \n Length:1000        Min.   :  0.00   Min.   : 17.00   Min.   : 10.00  \n Class :character   1st Qu.: 57.00   1st Qu.: 59.00   1st Qu.: 57.75  \n Mode  :character   Median : 66.00   Median : 70.00   Median : 69.00  \n                    Mean   : 66.09   Mean   : 69.17   Mean   : 68.05  \n                    3rd Qu.: 77.00   3rd Qu.: 79.00   3rd Qu.: 79.00  \n                    Max.   :100.00   Max.   :100.00   Max.   :100.00  \n```\n:::\n\n```{.r .cell-code}\nhead(data, 10)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"race\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"parent_education\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"lunch\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"test_prep\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"math_score\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"reading_score\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"writing_score\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"group B\",\"3\":\"bachelor's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"72\",\"7\":\"72\",\"8\":\"74\"},{\"1\":\"female\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"completed\",\"6\":\"69\",\"7\":\"90\",\"8\":\"88\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"master's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"90\",\"7\":\"95\",\"8\":\"93\"},{\"1\":\"male\",\"2\":\"group A\",\"3\":\"associate's degree\",\"4\":\"free/reduced\",\"5\":\"none\",\"6\":\"47\",\"7\":\"57\",\"8\":\"44\"},{\"1\":\"male\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"76\",\"7\":\"78\",\"8\":\"75\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"associate's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"71\",\"7\":\"83\",\"8\":\"78\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"completed\",\"6\":\"88\",\"7\":\"95\",\"8\":\"92\"},{\"1\":\"male\",\"2\":\"group B\",\"3\":\"some college\",\"4\":\"free/reduced\",\"5\":\"none\",\"6\":\"40\",\"7\":\"43\",\"8\":\"39\"},{\"1\":\"male\",\"2\":\"group D\",\"3\":\"high school\",\"4\":\"free/reduced\",\"5\":\"completed\",\"6\":\"64\",\"7\":\"64\",\"8\":\"67\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"high school\",\"4\":\"free/reduced\",\"5\":\"none\",\"6\":\"38\",\"7\":\"60\",\"8\":\"50\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [1,000 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ gender          : chr [1:1000] \"female\" \"female\" \"female\" \"male\" ...\n $ race            : chr [1:1000] \"group B\" \"group C\" \"group B\" \"group A\" ...\n $ parent_education: chr [1:1000] \"bachelor's degree\" \"some college\" \"master's degree\" \"associate's degree\" ...\n $ lunch           : chr [1:1000] \"standard\" \"standard\" \"standard\" \"free/reduced\" ...\n $ test_prep       : chr [1:1000] \"none\" \"completed\" \"none\" \"none\" ...\n $ math_score      : num [1:1000] 72 69 90 47 76 71 88 40 64 38 ...\n $ reading_score   : num [1:1000] 72 90 95 57 78 83 95 43 64 60 ...\n $ writing_score   : num [1:1000] 74 88 93 44 75 78 92 39 67 50 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   gender = col_character(),\n  ..   `race/ethnicity` = col_character(),\n  ..   `parental level of education` = col_character(),\n  ..   lunch = col_character(),\n  ..   `test preparation course` = col_character(),\n  ..   math = col_double(),\n  ..   reading = col_double(),\n  ..   writing = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\nanyNA(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(data$gender)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The `<scale>` argument of `guides()` cannot be `FALSE`. Use \"none\" instead as\nof ggplot2 3.3.4.\nℹ The deprecated feature was likely used in the funModeling package.\n  Please report the issue at <https://github.com/pablo14/funModeling/issues>.\n```\n:::\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"var\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"frequency\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"percentage\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cumulative_perc\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"518\",\"3\":\"51.8\",\"4\":\"51.8\"},{\"1\":\"male\",\"2\":\"482\",\"3\":\"48.2\",\"4\":\"100.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIt can be observed that among the students included, approximately 51.8% of them are female students. This indicates that the majority of the students in the dataset are female.\n\nOn the other hand, approximately 48.2% of the students in the dataset are male students. This suggests that male students make up a slightly smaller portion of the total student population compared to female students.\n\nOverall, the dataset represents a relatively balanced distribution in terms of gender, with a slightly higher proportion of female students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(data$race)\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"var\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"frequency\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"percentage\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cumulative_perc\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"group C\",\"2\":\"319\",\"3\":\"31.9\",\"4\":\"31.9\"},{\"1\":\"group D\",\"2\":\"262\",\"3\":\"26.2\",\"4\":\"58.1\"},{\"1\":\"group B\",\"2\":\"190\",\"3\":\"19.0\",\"4\":\"77.1\"},{\"1\":\"group E\",\"2\":\"140\",\"3\":\"14.0\",\"4\":\"91.1\"},{\"1\":\"group A\",\"2\":\"89\",\"3\":\"8.9\",\"4\":\"100.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIt can be observed that Group C is the most prevalent race/ethnicity among the students. This suggests that a larger number of students in the dataset belong to Group C compared to the other race/ethnicity categories while  Group A is the least represented race/ethnicity among the students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(data$parent_education)\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"var\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"frequency\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"percentage\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cumulative_perc\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"some college\",\"2\":\"226\",\"3\":\"22.6\",\"4\":\"22.6\"},{\"1\":\"associate's degree\",\"2\":\"222\",\"3\":\"22.2\",\"4\":\"44.8\"},{\"1\":\"high school\",\"2\":\"196\",\"3\":\"19.6\",\"4\":\"64.4\"},{\"1\":\"some high school\",\"2\":\"179\",\"3\":\"17.9\",\"4\":\"82.3\"},{\"1\":\"bachelor's degree\",\"2\":\"118\",\"3\":\"11.8\",\"4\":\"94.1\"},{\"1\":\"master's degree\",\"2\":\"59\",\"3\":\"5.9\",\"4\":\"100.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nAbove chart reveal the distribution of parent education levels among the students in the dataset. Out of the total number of students, 226 individuals (22.6%) reported having their parents pursued some college education\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(data$lunch)\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"var\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"frequency\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"percentage\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cumulative_perc\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"standard\",\"2\":\"645\",\"3\":\"64.5\",\"4\":\"64.5\"},{\"1\":\"free/reduced\",\"2\":\"355\",\"3\":\"35.5\",\"4\":\"100.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nStandard Price Lunch: 64.5%\nApproximately 64.5% of the students in the dataset eat lunch at the standard price. This indicates that the majority of the students opt for the standard-priced lunch option.\n\nFree/Reduced Lunch: 35.5%\nAbout 35.5% of the students in the dataset eat lunch at a free or reduced price. This suggests that a smaller portion of the students qualify for and choose the free or reduced lunch option.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data,aes(data$gender, fill=data$race))+\n  geom_bar(position=position_dodge())+\n  ggtitle(\"Ethnic Group distribution by Gender\")+\n  xlab(\"Gender\")+\n  ylab(\"Frequency\")\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\nI have compared the gender with their race type and its interesting to see that the majority of students in the dataset are from group C followed by group D race.\n\nSo, keeping all the analysed information in mind i want to conduct the correlation analysis for the variables Math, Reading and Writing scores and see if there is any correlation between the variables.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprofiling_num(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"variable\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"mean\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"std_dev\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"variation_coef\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_01\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_05\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_25\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_50\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_75\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_95\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_99\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"skewness\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"kurtosis\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"iqr\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"range_98\"],\"name\":[15],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"range_80\"],\"name\":[16],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"math_score\",\"2\":\"66.089\",\"3\":\"15.16308\",\"4\":\"0.2294342\",\"5\":\"27.99\",\"6\":\"40.95\",\"7\":\"57.00\",\"8\":\"66\",\"9\":\"77\",\"10\":\"90.05\",\"11\":\"98.01\",\"12\":\"-0.2785166\",\"13\":\"3.267597\",\"14\":\"20.00\",\"15\":\"[27.99, 98.01]\",\"16\":\"[47, 86]\"},{\"1\":\"reading_score\",\"2\":\"69.169\",\"3\":\"14.60019\",\"4\":\"0.2110800\",\"5\":\"31.99\",\"6\":\"44.00\",\"7\":\"59.00\",\"8\":\"70\",\"9\":\"79\",\"10\":\"92.00\",\"11\":\"100.00\",\"12\":\"-0.2587157\",\"13\":\"2.926081\",\"14\":\"20.00\",\"15\":\"[31.99, 100]\",\"16\":\"[51, 87.1]\"},{\"1\":\"writing_score\",\"2\":\"68.054\",\"3\":\"15.19566\",\"4\":\"0.2232882\",\"5\":\"31.98\",\"6\":\"42.95\",\"7\":\"57.75\",\"8\":\"69\",\"9\":\"79\",\"10\":\"92.00\",\"11\":\"100.00\",\"12\":\"-0.2890096\",\"13\":\"2.960808\",\"14\":\"21.25\",\"15\":\"[31.98, 100]\",\"16\":\"[48, 87]\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_num(data)\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nBased on our hypothesis that the math exam scores of students are positively associated with their reading and writing scores, the findings from the profiling analysis and also plot chart provide evidence supporting this hypothesis. The average scores for math, reading, and writing are relatively close, indicating a positive association between these subjects.\n\n## Math Scores based on Reading and Writing Scores\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# scatter plot\nggplot(data, aes(x = reading_score, y = writing_score, color = math_score)) +\n  geom_point() +\n  labs(x = \"Reading Score\", y = \"Writing Score\", \n       title = \"Math Scores based on Reading and Writing Scores\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n## Math Scores based on Gender\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean math score by gender\nmean_scores <- data %>%\n  group_by(gender) %>%\n  summarise(mean_math_score = mean(math_score))\n\n# bar chart\nggplot(mean_scores, aes(x = gender, y = mean_math_score)) +\n  geom_bar(stat = \"identity\", fill = \"steelblue\") +\n  labs(x = \"Gender\", y = \"Mean Math Score\", \n       title = \"Mean Math Scores by Gender\") +\n  theme_minimal() +\n  geom_text(aes(label = round(mean_math_score, 2)), vjust = -0.5, color = \"black\")\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\nThe chart reveals that the mean math score for males is approximately 68.73, indicating a relatively higher average performance in math compared to females . On the other hand,females have a mean math score of around 63.63, suggesting a slightly lower average performance in math compared to males . These findings highlight a gender-based difference in math scores, with males demonstrating a higher average math score compared to females.\n\n\n## Math Scores based on Race\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean math score by race\nmean_scores <- data %>%\n  group_by(race) %>%\n  summarise(mean_math_score = mean(math_score))\n\n# bar chart\nggplot(data, aes(x = race, y = math_score)) +\n  geom_bar(stat = \"summary\", fun = \"mean\", fill = \"steelblue\") +\n  labs(x = \"Race\", y = \"Math Score\", \n       title = \"Math Scores by Race\") +\n  theme_minimal() +\n  geom_text(data = mean_scores, aes(x = race, y = mean_math_score, \n                                   label = paste0(\"Mean: \", round(mean_math_score, 2))),\n            vjust = -0.5, color = \"black\")\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nThese findings highlight the variations in math scores across different race categories, with Group E demonstrating the highest average score and Group A showing the lowest average score performance.\n\n## Math Scores based on Parents Education Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# bar chart\nggplot(data, aes(x = parent_education, y = math_score)) +\n  geom_bar(stat = \"summary\", fun = \"mean\", fill = \"steelblue\") +\n  labs(x = \"Parental Education Level\", y = \"Math Score\", \n       title = \"Math Scores by Parental Education Level\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\nEven thought there is a little difference in the math scores there is not significant difference based on their parents education level\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n\n# Calculate mean math score by lunch type\nmean_scores <- data %>%\n  group_by(lunch) %>%\n  summarise(mean_math_score = mean(math_score))\n\n# bar chart\nggplot(data, aes(x = lunch, y = math_score)) +\n  geom_bar(stat = \"summary\", fun = \"mean\", fill = \"steelblue\") +\n  labs(x = \"Lunch Type\", y = \"Math Score\",\n       title = \"Math Scores by Lunch Type\") +\n  theme_minimal() +\n  geom_text(data = mean_scores, aes(x = lunch, y = mean_math_score,\n                                   label = paste0(\"Mean: \", round(mean_math_score, 2))),\n            vjust = -0.5, color = \"black\")\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\nIt is interesting to see the math score of students based on their lunch type. Students how are taking standard meal are performing better at math as compared to people taking free or reduced lunch option. \n\n\n## Correlation Matrix of Math, Reading, and Writing Scores\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_data <- data[, c( \"math_score\", \"reading_score\", \"writing_score\")]\nm<-cor(num_data)\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              math_score reading_score writing_score\nmath_score     1.0000000     0.8175797     0.8026420\nreading_score  0.8175797     1.0000000     0.9545981\nwriting_score  0.8026420     0.9545981     1.0000000\n```\n:::\n\n```{.r .cell-code}\ncorrplot(m, method=\"circle\", type='upper', tl.cex=0.8, tl.col = 'black')\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\nThe correlation analysis reveals interesting insights into the relationships between math scores, reading scores, and writing scores. The strong positive correlation coefficient of 0.8176 between math_score and reading_score suggests that students who excel in math also tend to perform well in reading. Similarly, the high correlation coefficient of 0.8026 between math_score and writing_score indicates a strong positive association, indicating that students who demonstrate proficiency in math often display strong writing skills as well. Furthermore, the very high correlation coefficient of 0.9546 between reading_score and writing_score highlights a robust positive relationship, indicating that students who excel in reading are highly likely to excel in writing.\n\nTaken together, these findings provide substantial evidence supporting our hypothesis that math exam scores are positively associated with both reading and writing scores. These results suggest that students who demonstrate proficiency in one subject area are more likely to excel in the other subjects as well, reinforcing the idea of a positive relationship between math scores and reading/writing scores.\n\n## Comparison of Math Scores between Male and Female Students\n\n### T-Test\n\n::: {.cell}\n\n```{.r .cell-code}\n# T-test for math scores\nttest_math <- t.test(math_score ~ gender, data = data)\nttest_math\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  math_score by gender\nt = -5.398, df = 997.98, p-value = 8.421e-08\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -6.947209 -3.242813\nsample estimates:\nmean in group female   mean in group male \n            63.63320             68.72822 \n```\n:::\n:::\n\n\n### One-way ANOVA Test\n\n::: {.cell}\n\n```{.r .cell-code}\n# One-way ANOVA for all three subjects\nanova_scores <- aov(math_score + reading_score + writing_score ~ gender, data = data)\nsummary(anova_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Df  Sum Sq Mean Sq F value   Pr(>F)    \ngender        1   31297   31297   17.39 3.31e-05 ***\nResiduals   998 1796315    1800                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nBased on the analysis conducted, we performed a Welch Two Sample t-test to examine the differences in math scores between male and female students. The results indicate that there is a statistically significant disparity in the mean math scores between the two groups (t = -5.398, df = 997.98, p-value = 8.421e-08). It was found that the mean math score for females (63.63) is significantly lower compared to males (68.73) with a 95% confidence interval ranging from -6.947209 to -3.242813.\n\nFurthermore, we conducted a one-way ANOVA to explore the impact of gender on math, reading, and writing scores. The ANOVA results demonstrate a significant effect of gender on math scores (F = 17.39, p < 0.001). However, this analysis does not provide information regarding the relationship between math scores and reading/writing scores.\n\nIn summary, our analysis reveals a significant difference in math scores between male and female students, with males demonstrating higher performance in this subject compared to females. These findings highlight the influence of gender on academic achievement, particularly in the context of math\n\n# Linear Regression Models for Predicting Math Scores\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ntrain_idx <- sample(nrow(data), nrow(data) * 0.7)\ntrain_data <- data[train_idx, ]\ntest_data <- data[-train_idx, ]\n```\n:::\n\n### Model 1\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(math_score ~ reading_score + writing_score, data = train_data)\npredictions1 <- predict(model1, newdata = test_data)\nrmse1 <- sqrt(mean((test_data$math_score - predictions1)^2))\nr_squared1 <- summary(model1)$r.squared\nrmse1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.753639\n```\n:::\n\n```{.r .cell-code}\nr_squared1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6630448\n```\n:::\n:::\n\nThis model includes reading score and writing score as predictors for math score. The root mean squared error (RMSE) for predicting math scores on the test data is approximately 8.75. The R-squared value, which represents the proportion of variance in math scores explained by the model, is approximately 0.663. This suggests that reading score and writing score collectively account for about 66.3% of the variation in math scores.\n\n### Model 2\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- lm(math_score ~ writing_score * reading_score + gender , data = train_data)\npredictions2 <- predict(model2, newdata = test_data)\nrmse2 <- sqrt(mean((test_data$math_score - predictions2)^2))\nr_squared2 <- summary(model2)$r.squared\nrmse2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.148844\n```\n:::\n\n```{.r .cell-code}\nr_squared2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8366321\n```\n:::\n:::\n\nThis model extends Model 1 by including an interaction term between writing score and reading score, as well as the gender variable. The RMSE for this model is approximately 6.15, indicating a slight improvement in prediction accuracy compared to Model 1. The R-squared value increases to approximately 0.837, suggesting that the addition of the interaction term and gender variable accounts for a higher proportion of the variation in math scores.\n### Model 3\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- lm(math_score ~  ., data = train_data)\npredictions3 <- predict(model3, newdata = test_data)\nrmse3 <- sqrt(mean((test_data$math_score - predictions3)^2))\nr_squared3 <- summary(model3)$r.squared\nrmse3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.697975\n```\n:::\n\n```{.r .cell-code}\nr_squared3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8774988\n```\n:::\n:::\n\nThis model includes all available variables as predictors for math score. The RMSE decreases further to approximately 5.70, indicating improved prediction accuracy compared to both Model 1 and Model 2. The R-squared value increases to approximately 0.877, indicating that this model explains approximately 87.7% of the variance in math scores when considering all available predictors.\n\n### Model Comparison using AIC and BIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [1,000 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ gender          : chr [1:1000] \"female\" \"female\" \"female\" \"male\" ...\n $ race            : chr [1:1000] \"group B\" \"group C\" \"group B\" \"group A\" ...\n $ parent_education: chr [1:1000] \"bachelor's degree\" \"some college\" \"master's degree\" \"associate's degree\" ...\n $ lunch           : chr [1:1000] \"standard\" \"standard\" \"standard\" \"free/reduced\" ...\n $ test_prep       : chr [1:1000] \"none\" \"completed\" \"none\" \"none\" ...\n $ math_score      : num [1:1000] 72 69 90 47 76 71 88 40 64 38 ...\n $ reading_score   : num [1:1000] 72 90 95 57 78 83 95 43 64 60 ...\n $ writing_score   : num [1:1000] 74 88 93 44 75 78 92 39 67 50 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   gender = col_character(),\n  ..   `race/ethnicity` = col_character(),\n  ..   `parental level of education` = col_character(),\n  ..   lunch = col_character(),\n  ..   `test preparation course` = col_character(),\n  ..   math = col_double(),\n  ..   reading = col_double(),\n  ..   writing = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\nAIC(model1,model2, model3)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"4\",\"2\":\"5009.934\",\"_rn_\":\"model1\"},{\"1\":\"6\",\"2\":\"4507.172\",\"_rn_\":\"model2\"},{\"1\":\"16\",\"2\":\"4325.654\",\"_rn_\":\"model3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nBIC(model1,model2, model3)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BIC\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"4\",\"2\":\"5028.138\",\"_rn_\":\"model1\"},{\"1\":\"6\",\"2\":\"4534.478\",\"_rn_\":\"model2\"},{\"1\":\"16\",\"2\":\"4398.471\",\"_rn_\":\"model3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nWhen comparing the models using the Akaike Information Criterion (AIC) and Bayesian Information Criterion (BIC), lower values indicate better model fit. \n\nModel 1: AIC = 5009.934, BIC = 5028.138\nModel 2: AIC = 4507.172, BIC = 4534.478\nModel 3: AIC = 4325.654, BIC = 4398.471\n\nThe AIC and BIC values for each model suggest that Model 3 has the best fit among the three models. However, adding gender to reading and writing score made the model better and fit. it is very near to the model3 which includes all the variables.\n\nAs the AIC and BIC scores are less compared to Model1 & Model2, Im choosing Model3 to perform Residual Diagnostics \n\n# Regression Diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model3)\n```\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-25-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-25-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](FinalProject_Thrishul_files/figure-html/unnamed-chunk-25-4.png){width=672}\n:::\n:::\n\n\nAs we can see the Residual Diagnosis plots above for Model3, in all the plots the red line fitted values are straight and linear accross all the plots indicating that the model is better fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stargazer)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nPlease cite as: \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n R package version 5.2.3. https://CRAN.R-project.org/package=stargazer \n```\n:::\n\n```{.r .cell-code}\nstargazer(model1, model2, model3, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=============================================================================================================\n                                                              Dependent variable:                            \n                                  ---------------------------------------------------------------------------\n                                                                  math_score                                 \n                                            (1)                      (2)                       (3)           \n-------------------------------------------------------------------------------------------------------------\nreading_score                             0.539***                 0.276***                 0.229***         \n                                          (0.077)                  (0.077)                   (0.050)         \n                                                                                                             \ngendermale                                                        13.197***                 13.392***        \n                                                                   (0.486)                   (0.435)         \n                                                                                                             \nwriting_score:reading_score                                         0.001                                    \n                                                                   (0.001)                                   \n                                                                                                             \nracegroup B                                                                                   0.247          \n                                                                                             (0.842)         \n                                                                                                             \nracegroup C                                                                                  -0.085          \n                                                                                             (0.779)         \n                                                                                                             \nracegroup D                                                                                   0.163          \n                                                                                             (0.798)         \n                                                                                                             \nracegroup E                                                                                 5.154***         \n                                                                                             (0.873)         \n                                                                                                             \nparent_educationbachelor's degree                                                            -0.534          \n                                                                                             (0.725)         \n                                                                                                             \nparent_educationhigh school                                                                  1.346**         \n                                                                                             (0.637)         \n                                                                                                             \nparent_educationmaster's degree                                                             -2.379***        \n                                                                                             (0.907)         \n                                                                                                             \nparent_educationsome college                                                                 -0.064          \n                                                                                             (0.591)         \n                                                                                                             \nparent_educationsome high school                                                             1.169*          \n                                                                                             (0.646)         \n                                                                                                             \nlunchstandard                                                                               3.029***         \n                                                                                             (0.439)         \n                                                                                                             \ntest_prepnone                                                                               3.775***         \n                                                                                             (0.460)         \n                                                                                                             \nwriting_score                             0.304***                 0.553***                 0.750***         \n                                          (0.073)                  (0.074)                   (0.051)         \n                                                                                                             \nConstant                                  8.214***                  -2.079                 -12.694***        \n                                          (1.631)                  (3.629)                   (1.504)         \n                                                                                                             \n-------------------------------------------------------------------------------------------------------------\nObservations                                700                      700                       700           \nR2                                         0.663                    0.837                     0.877          \nAdjusted R2                                0.662                    0.836                     0.875          \nResidual Std. Error                   8.637 (df = 697)         6.022 (df = 695)         5.253 (df = 685)     \nF Statistic                       685.762*** (df = 2; 697) 889.801*** (df = 4; 695) 350.484*** (df = 14; 685)\n=============================================================================================================\nNote:                                                                             *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n\n\nIn Model 1, we found that an increase in the reading score is linked to a higher math score. The coefficient for the reading score was statistically significant (p < 0.01) and had a positive value of 0.539. This suggests that students who perform better in reading tend to have higher math scores. Similarly, the coefficient for the writing score was also statistically significant (p < 0.01) with a positive value of 0.304. This implies that students who excel in writing also tend to have higher math scores.\n\nWhen we examined Model 2, which includes additional variables, we observed that the coefficients for reading_score and writing_score remained statistically significant and positive. This finding reaffirms the results from Model 1, indicating a consistent relationship between reading, writing, and math scores. It suggests that students who perform well in both reading and writing are likely to have higher math scores.\n\nIn Model 3, where we considered all available variables, we found that the coefficients for reading_score and writing_score continued to be statistically significant and positive. This further supports our hypothesis that math scores are positively associated with both reading and writing scores. It suggests that students who demonstrate strong abilities in reading and writing are more likely to achieve higher math scores.\n\nThese findings provide evidence supporting our hypothesis that math exam scores are positively associated with reading and writing scores and that there is a gender difference in math performance, with males outperforming females.\n\n# Conclusion\n\nIn conclusion, our research focused on examining the factors influencing math scores among students. We analyzed a dataset containing information on various variables such as gender, race/ethnicity, parental education, lunch type, test preparation, and scores in reading and writing.\n\nOur findings revealed several important insights. Firstly, gender played a significant role, with male students showing higher math scores compared to females. \n\nThe scores in reading and writing were strongly correlated with math scores. Higher scores in reading and writing were associated with higher math scores.\n\nAdditionally, the type of lunch and completion of a test preparation course were also found to have a positive impact on math scores. Students who had a standard lunch and completed a test preparation course tended to perform better in math.\n\nOverall, our research suggests that reading and writing, gender, and lunch type are important factors influencing math scores among students. \n\nIt is important to note that this research was based on a specific dataset and may not capture all possible factors influencing math scores. Further research and exploration are recommended to gain a comprehensive understanding of the complex dynamics affecting students' math performance.\n\n# Bibilography\n\nDataset : \"Students Performance in Exams\" Dataset. Retrieved from https://www.kaggle.com/datasets/spscientist/students-performance-in-exams\n\nJohnson, R. A. (2010). Applied Multivariate Statistical Analysis (6th ed.). Pearson Education.\n\nField, A. (2013). Discovering Statistics Using R. SAGE Publications Ltd.\n\nWickham, H. (2016). ggplot2: Elegant Graphics for Data Analysis. Springer.",
    "supporting": [
      "FinalProject_Thrishul_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}