{
  "hash": "c7af34896f755e88581af36afaead110",
  "result": {
    "markdown": "---\ntitle: \"Homework_One\"\nauthor: \"Meredith Derian-Toth\"\ndescription: \"Template of course blog qmd file\"\ndate: \"02/05/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n\n# Question 1\n\n#### (1a) What does the distribution of LungCap look like?\n\nFirst, let's read in the data from the Excel file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"quarto\")\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.0     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.1     ✔ tibble    3.1.8\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the \u001b]8;;http://conflicted.r-lib.org/\u0007conflicted package\u001b]8;;\u0007 to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(\"palmerpenguins\")\nlibrary(readxl)\nlibrary(dplyr)\nlibrary(ggplot2)\n#getwd()\ndf <- read_excel(\"_data/LungCapData.xls\")\n#View(df)\n```\n:::\n\n\nThe distribution of LungCap looks as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df$LungCap)\n```\n\n::: {.cell-output-display}\n![](DerianToth_M_HW1_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe histogram suggests that the distribution is close to a normal distribution. Most of the observations are close to the mean. Very few observations are close to the margins (0 and 15).\n\n#### (1b) The probability distribution of the LungCap with respect to gender is as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(df$LungCap ~ df$Gender)\n```\n\n::: {.cell-output-display}\n![](DerianToth_M_HW1_files/figure-html/BoxPlot-1.png){width=672}\n:::\n:::\n\n\n#### (1c) The mean lung capacities for smokers and non-smokers can be found in the table below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  group_by(Smoke) %>%\n  summarise_at(vars(LungCap), list(name = mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  name\n  <chr> <dbl>\n1 no     7.77\n2 yes    8.65\n```\n:::\n:::\n\nThese means are not what I would expect. It looks like those who smoke (\"yes\") have a higher long capacity (8.65) than those who do not smoke (7.77).\n\n\n#### (1d) The relationship between Smoking and Lung Capacity within age groups \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Age groups defined by:\n#“less than or\n#equal to 13”, \n#“14 to 15”, \n#“16 to 17”, \n#“greater than or equal to 18”.\n\n# Create variable\ndf <- df %>% \n  mutate(age_group = case_when(\n      Age <= 13 ~ \"0-13\",\n      Age > 13 & Age < 16 ~ \"14-15\",\n      Age > 15 & Age < 18 ~ \"16-18\",\n      Age >= 18 ~ \">= 18\"),\n    # Convert to factor\n    age_group = factor(\n      age_group,\n      level = c(\"0-13\", \"14-15\",\"16-18\", \">= 18\")))\n\nView(df)\n\ndf %>%\n  group_by(age_group,Smoke) %>%\n  summarise_at(vars(LungCap), list(name = mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 3\n# Groups:   age_group [4]\n  age_group Smoke  name\n  <fct>     <chr> <dbl>\n1 0-13      no     6.36\n2 0-13      yes    7.20\n3 14-15     no     9.14\n4 14-15     yes    8.39\n5 16-18     no    10.5 \n6 16-18     yes    9.38\n7 >= 18     no    11.1 \n8 >= 18     yes   10.5 \n```\n:::\n\n```{.r .cell-code}\ndbinom(x=8,size=8,prob=.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.00390625\n```\n:::\n\n```{.r .cell-code}\ndbinom(x=6,size=8,prob=.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.109375\n```\n:::\n:::\n\n\n#### (1e) Compare the lung capacities for smokers and non-smokers within each age group. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x=age_group, y=LungCap, color = Smoke)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](DerianToth_M_HW1_files/figure-html/relationship btw age_group & LungCap-1.png){width=672}\n:::\n:::\n\nThis data visualization makes more sense for what we expect from lung capacity when comparing smokers to non smokers. It looks like lunch capacity increases as the participants get older. The data could have more participants who are smokers and who are older. This unbalance in participants could be skewing the overall average lunch capacity. \n\n\n# Question 2:Setting up the Dataframe\n\n\n::: {.cell}\n\n```{.r .cell-code}\nStatePrison <- data.frame(number_convictions = 0:4, InMateCount = c(128, 434, 160, 64, 24)) %>%\n                            mutate(Probability = InMateCount/810)\n\nView(StatePrison)\n```\n:::\n\n\n#### (2a) What is the probability that a randomly selected inmate has exactly 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 1, size = 1, p = 160/810)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1975309\n```\n:::\n:::\n\n\n\n#### (2b) What is the probability that a randomly selected inmate has fewer than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 1, size = 1, p = sum(128+434)/810)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\n\n\n#### (2c) What is the probability that a randomly selected inmate has 2 or fewer prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 1, size = 1, p = sum(128+434+160)/810)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\n\n#### (2d) What is the probability that a randomly selected inmate has more than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 1, size = 1, p = sum(64+24)/810)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\n\n#### (2e) What is the expected value for the number of prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nEV <- sum(StatePrison$number_convictions *StatePrison$Probability)\nprint(EV)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\n\n#### (2f) Calculate the variance and the standard deviation for the Prior Convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVar <- sum((StatePrison$number_convictions - EV) ^ 2 * StatePrison$Probability)\n\nprint(Var)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8562353\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nSD <- sqrt(Var)\n\nprint(SD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9253298\n```\n:::\n:::\n\n---\n",
    "supporting": [
      "DerianToth_M_HW1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}