{
  "hash": "1274ad748833351c43ec9e0e2e5f5e90",
  "result": {
    "markdown": "---\ntitle: \"Hw 3 by Kristin Abijaoude\"\nauthor: \"Kristin Abijaoude\"\ndescription: \"HW3\"\ndate: \"04/02/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Hw3\n  - kristin abijaoude\n  - un \n  - ratemyprof\n  - water\n  - student survey\n  - smss\n---\n\n\n# Question 1: Fertility vs. GDP\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\npackages <- c(\"readr\", \"ggplot2\", \"caret\", \"summarytools\", \"smss\", \"alr4\", \"tidyverse\", \"dplyr\", \"stats\", \"pwr\")\nlapply(packages, require, character.only = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: readr\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: ggplot2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: caret\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: lattice\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: summarytools\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: smss\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: alr4\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: effects\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nUse the command\n    lattice::trellis.par.set(effectsTheme())\n  to customize lattice options for effects plots.\nSee ?effectsTheme for details.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: tidyverse\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ tibble  3.1.8     ✔ dplyr   1.1.0\n✔ tidyr   1.2.1     ✔ stringr 1.5.0\n✔ purrr   1.0.0     ✔ forcats 0.5.2\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n✖ purrr::lift()   masks caret::lift()\n✖ dplyr::recode() masks car::recode()\n✖ purrr::some()   masks car::some()\n✖ tibble::view()  masks summarytools::view()\nLoading required package: pwr\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\n[1] TRUE\n\n[[2]]\n[1] TRUE\n\n[[3]]\n[1] TRUE\n\n[[4]]\n[1] TRUE\n\n[[5]]\n[1] TRUE\n\n[[6]]\n[1] TRUE\n\n[[7]]\n[1] TRUE\n\n[[8]]\n[1] TRUE\n\n[[9]]\n[1] TRUE\n\n[[10]]\n[1] TRUE\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(UN11)\nsummary(UN11)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        region      group       fertility         ppgdp         \n Africa    :53   oecd  : 31   Min.   :1.134   Min.   :   114.8  \n Asia      :50   other :115   1st Qu.:1.754   1st Qu.:  1283.0  \n Europe    :39   africa: 53   Median :2.262   Median :  4684.5  \n Latin Amer:20                Mean   :2.761   Mean   : 13012.0  \n Caribbean :17                3rd Qu.:3.545   3rd Qu.: 15520.5  \n Oceania   :17                Max.   :6.925   Max.   :105095.4  \n (Other)   : 3                                                  \n    lifeExpF        pctUrban     \n Min.   :48.11   Min.   : 11.00  \n 1st Qu.:65.66   1st Qu.: 39.00  \n Median :75.89   Median : 59.00  \n Mean   :72.29   Mean   : 57.93  \n 3rd Qu.:79.58   3rd Qu.: 75.00  \n Max.   :87.12   Max.   :100.00  \n                                 \n```\n:::\n\n```{.r .cell-code}\nhead(UN11)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                region  group fertility   ppgdp lifeExpF pctUrban\nAfghanistan       Asia  other     5.968   499.0    49.49       23\nAlbania         Europe  other     1.525  3677.2    80.40       53\nAlgeria         Africa africa     2.142  4473.0    75.00       67\nAngola          Africa africa     5.135  4321.9    53.17       59\nAnguilla     Caribbean  other     2.000 13750.1    81.10      100\nArgentina   Latin Amer  other     2.172  9162.1    79.89       93\n```\n:::\n:::\n\n\n## A\n\n`fertility`: Predictor\n\n`ppgdp`: Response\n\n## B\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(x = UN11$fertility, y = UN11$ppgdp,\n     xlab = \"Fertility\",\n     ylab = \"GDP\")\n```\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nBased on this graph, a straight-line mean function does not seem to be plausible for a summary of this graph, due to the fact that the points are clustered in one area.\n\n## C\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(x = log(UN11$fertility), y = log(UN11$ppgdp),\n     xlab = \"Fertility\",\n     ylab = \"GDP\")\n```\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nOn the other hand, it's plausible to make a straight line mean function from the graph above. It paints a clearer picture of a trend. In other words, one can see from the graph that there is a correlation between fertility rates and GDP- richer countries tend to have fewer children per woman.\n\n# Question 2: in UK pounds\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUN11_uk <- UN11 %>% \n  select(ppgdp, fertility) %>%\n  mutate(gdp_uk = ppgdp / 1.33)\n\n\nplot(x = log(UN11_uk$fertility), y = log(UN11_uk$gdp_uk),\n     xlab = \"Fertility\",\n     ylab = \"GDP\")\n```\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThere seems to be no changes when I convert US dollars into UK pounds, and it's no surprise since both currencies are two of the strongest in the world. The trend is still the same.\n\n# Question 3: Water Runoff in the Sierras\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(water)\nhead(water)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Year APMAM APSAB APSLAKE OPBPC  OPRC OPSLAKE  BSAAM\n1 1948  9.13  3.58    3.91  4.10  7.43    6.47  54235\n2 1949  5.28  4.82    5.20  7.55 11.11   10.26  67567\n3 1950  4.20  3.77    3.67  9.52 12.20   11.35  66161\n4 1951  4.60  4.46    3.93 11.14 15.15   11.13  68094\n5 1952  7.15  4.99    4.88 16.34 20.05   22.81 107080\n6 1953  9.70  5.65    4.91  8.88  8.15    7.41  67594\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(water)\n```\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nFrom this graph, the data seems too cluttered to make a prediction out of; in other words, there is no correlation between the past years and percipitation measures in inches.\n\n# Question 4: Rate My Professors\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(Rateprof)\nsummary(Rateprof)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    gender       numYears        numRaters       numCourses     pepper   \n female:159   Min.   : 1.000   Min.   :10.00   Min.   : 1.000   no :320  \n male  :207   1st Qu.: 6.000   1st Qu.:15.00   1st Qu.: 3.000   yes: 46  \n              Median :10.000   Median :24.00   Median : 4.000            \n              Mean   : 8.347   Mean   :28.58   Mean   : 4.251            \n              3rd Qu.:11.000   3rd Qu.:37.00   3rd Qu.: 5.000            \n              Max.   :11.000   Max.   :86.00   Max.   :12.000            \n                                                                         \n    discipline          dept        quality       helpfulness   \n Hum     :134   English   : 49   Min.   :1.409   Min.   :1.364  \n SocSci  : 66   Math      : 34   1st Qu.:2.936   1st Qu.:3.069  \n STEM    :103   Biology   : 20   Median :3.612   Median :3.662  \n Pre-prof: 63   Chemistry : 20   Mean   :3.575   Mean   :3.631  \n                Psychology: 20   3rd Qu.:4.250   3rd Qu.:4.351  \n                Spanish   : 20   Max.   :4.981   Max.   :5.000  \n                (Other)   :203                                  \n    clarity         easiness     raterInterest     sdQuality      \n Min.   :1.333   Min.   :1.391   Min.   :1.098   Min.   :0.09623  \n 1st Qu.:2.871   1st Qu.:2.548   1st Qu.:2.934   1st Qu.:0.87508  \n Median :3.600   Median :3.148   Median :3.305   Median :1.15037  \n Mean   :3.525   Mean   :3.135   Mean   :3.310   Mean   :1.05610  \n 3rd Qu.:4.214   3rd Qu.:3.692   3rd Qu.:3.692   3rd Qu.:1.28730  \n Max.   :5.000   Max.   :4.900   Max.   :4.909   Max.   :1.67739  \n                                                                  \n sdHelpfulness      sdClarity        sdEasiness     sdRaterInterest \n Min.   :0.0000   Min.   :0.0000   Min.   :0.3162   Min.   :0.3015  \n 1st Qu.:0.9902   1st Qu.:0.9085   1st Qu.:0.9045   1st Qu.:1.0848  \n Median :1.2860   Median :1.1712   Median :1.0247   Median :1.2167  \n Mean   :1.1719   Mean   :1.0970   Mean   :1.0196   Mean   :1.1965  \n 3rd Qu.:1.4365   3rd Qu.:1.3328   3rd Qu.:1.1485   3rd Qu.:1.3326  \n Max.   :1.8091   Max.   :1.8091   Max.   :1.6293   Max.   :1.7246  \n                                                                    \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nRate_pairs <- Rateprof %>%\n  select(clarity, quality, helpfulness, easiness, raterInterest)\n\npairs(Rate_pairs)\n```\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n-   There seems to be a very clear positive correlation between `clarity`, `helpfulness`, and `quality`, given by the seemingly straight lines.\n-   While the trends are not as straight, `easiness` has a positive correlation between variables `clarity`, `helpfulness`, and `quality`.\n-   `raterInterest`, on the other hand, presents less of a correlation, for a lack of better words, when it's graphed with the rest of the variables, but you can see a general pattern of positive correlation with those variables.\n\n# Question 5: Student Surveys\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(student.survey)\nhead(student.survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  subj ge ag  hi  co   dh   dr tv sp ne ah    ve pa           pi           re\n1    1  m 32 2.2 3.5    0  5.0  3  5  0  0 FALSE  r conservative   most weeks\n2    2  f 23 2.1 3.5 1200  0.3 15  7  5  6 FALSE  d      liberal occasionally\n3    3  f 27 3.3 3.0 1300  1.5  0  4  3  0 FALSE  d      liberal   most weeks\n4    4  f 35 3.5 3.2 1500  8.0  5  5  6  3 FALSE  i     moderate occasionally\n5    5  m 23 3.1 3.5 1600 10.0  6  6  3  0 FALSE  i very liberal        never\n6    6  m 39 3.5 3.5  350  3.0  4  5  7  0 FALSE  d      liberal occasionally\n     ab    aa    ld\n1 FALSE FALSE FALSE\n2 FALSE FALSE    NA\n3 FALSE FALSE    NA\n4 FALSE FALSE FALSE\n5 FALSE FALSE FALSE\n6 FALSE FALSE    NA\n```\n:::\n\n```{.r .cell-code}\nhelp(\"student.survey\") # to find out what those columns stand for\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(student.survey$pi)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] conservative          liberal               moderate             \n[4] very liberal          slightly liberal      slightly conservative\n[7] very conservative    \n7 Levels: very liberal < liberal < slightly liberal < ... < very conservative\n```\n:::\n:::\n\n\n\n## Political Ideology vs Religiosity \n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudent.survey<- student.survey%>% \n       mutate(p_i = case_when(pi == \"very liberal\" ~ 1,\n                              pi == \"liberal\" ~ 2,\n                              pi == \"slightly liberal\" ~ 3,\n                              pi == \"moderate\" ~ 4,\n                              pi == \"slightly conservative\" ~ 5,\n                              pi == \"conservative\" ~ 6,\n                              pi == \"very conservative\" ~ 7,\n                              TRUE ~ 0)) \nstudent.survey<- student.survey%>% \n       mutate(r_e = case_when(re == \"never\" ~ 1,\n                              re == \"occasionally\" ~ 2,\n                              re == \"most weeks\" ~ 3,\n                              re == \"every week\" ~ 4,\n                              TRUE ~ 0))\n\nreligion <- lm(p_i ~ r_e, data = student.survey)\nreligion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = p_i ~ r_e, data = student.survey)\n\nCoefficients:\n(Intercept)          r_e  \n     0.9308       0.9704  \n```\n:::\n\n```{.r .cell-code}\nplot(religion)\n```\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-12-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-12-4.png){width=672}\n:::\n:::\n\n\n### Interpretion \n\nThe intercept coefficient is around 0.93, meaning that one's political ideology starts around the \"very liberal\" area, and the religiosity coefficient starts around 0.97, meaning that one basically never attends religious services. In other word, this model starts of with a very liberal person who never attends church. The more religious a person is (i.e. the more often they attend religious services at places such as church or synagogue etc.), the more ideologically conservative they tend to be. \n\n## High School GPA vs Hours of Watching TV\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTV <- lm(hi ~ tv, data = student.survey)\nTV\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = hi ~ tv, data = student.survey)\n\nCoefficients:\n(Intercept)           tv  \n    3.44135     -0.01831  \n```\n:::\n\n```{.r .cell-code}\nplot(TV)\n```\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-13-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW3_files/figure-html/unnamed-chunk-13-4.png){width=672}\n:::\n:::\n\n\n### Interpretation\n\nWhat we have here is the Intercept of around 3.44, which means that this is the student's expected high school GPA when they watch 0 hours of TV. The negative coefficient of -0.01831 means that the more hours one watches TV, the lower their GPA by this amount.\n",
    "supporting": [
      "Kristin_Abijaoude_HW3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}