{
  "hash": "a8fb654cee46eda546a6a1296c3bc45e",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Christine Brydges\"\ndescription: \"Homework 1 Submission\"\ndate: \"02/28/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n\n# Question 1\n\n## a\n\nFirst, let's read in the data from the Excel file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\ndf <- read_excel(\"_data/LungCapData.xls\")\n```\n:::\n\n\n\nThe distribution of LungCap looks as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df$LungCap)\n```\n\n::: {.cell-output-display}\n![](HW1_ChristineBrydges_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe histogram suggests that the distribution is close to a normal distribution. Most of the observations are close to the mean. Very few observations are close to the margins (0 and 15).\n\n## b\nThe distribution and mean of the probability density of Lung Capacity can be shown in the box plots below, separated by genders 'Male' and 'Female'\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a Box Plot with Lung Capacity on y-axis, grouped by gender\nboxplot(LungCap~ Gender, data = df)\n\n# Add a title\ntitle(\"Lung Capacity: Males vs. Females\")\n```\n\n::: {.cell-output-display}\n![](HW1_ChristineBrydges_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe boxplot suggests that there is no significant difference between lung capacity of females and males, as the error bars of each boxplot significantly overlap. Additionally, the mean of the probability density of lung capacity appear to be close between female and male constituents.\n\n## c\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a Box Plot with Lung Capacity on y-axis, grouped by populations that smoke or do not smoke \nboxplot(LungCap~ Smoke, data = df)\n\n# Add a title\ntitle(\"Lung Capacity: Smokers vs. Non-Smokers\")\n```\n\n::: {.cell-output-display}\n![](HW1_ChristineBrydges_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nThe boxplot suggests that smokers have a higher lung capacity than non-smokers, which is counter-intuitive.\n\n#c\nNext, we will explore the differences of lung capacity of non-smokers and smokers, broken down by age group, as shown in the boxplot below. The green color is used to call out groups that do smoke while the blue color is used to call out groups that do not smoke.\n\n::: {.cell}\n\n```{.r .cell-code}\n#Group respondents into specific Age Groups \nAgeGroups <- cut(df$Age, breaks=c(0,13,15,17,19), labels=c('<13','14-15','16-17','>=18'))\nlevels(AgeGroups)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"<13\"   \"14-15\" \"16-17\" \">=18\" \n```\n:::\n\n```{.r .cell-code}\n#Create a stratified box plot based on two factors: Smoking vs. Nonsmoking and Age groups\nboxplot(df$LungCap~df$Smoke*AgeGroups, ylab=\"LungCap\", main=\"LungCap vs. Smoke, by AgeGroup\", las = 2, col=c(4,3))\n```\n\n::: {.cell-output-display}\n![](HW1_ChristineBrydges_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nFrom these boxplots, you can see that when you separate the smoking and nonsmoking groups by age, the smokers have a higher lung capacity than non-smokers. This is because age is a confounding variable, with young people gaining lung capacity as they have bigger bodies, and with older peope generally smoking more than younger people  . Once you take out age from consideration and compare \"apples to apples\" people of the same age but differences in whether they smoke or not, you can see that smoking DOES have a negative effect on lung capacity.\n\n# Question 2\n\n## a. Here, we will explore  the probability that a randomly selected inmate has exactly 2 prior convictions, based on a dataset given to us. \n\nSince the data set is not continuous or binomial, we will use basic probability functions to find probabilities. \n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate the probability of a prisoner having exactly 2 convictions (events/total possible events)\nprobability = (150/810) * 100\nprint(probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.51852\n```\n:::\n:::\n\nWe can see that the probability of a prisoner having exactly 2 convictions is 18.5%.\n\n## b.\nNext, we'll look at the probability that a randomly selected inmate has fewer than 2 prior convictions.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the probability of a prisoner having 0, or 1 convictions (fewer than 2 prior convictions) (events/total possible events)\nlessthan2convictions <- 128 + 434 \nprobabilitylessthan2 <- (lessthan2convictions/810) * 100\nprint(probabilitylessthan2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 69.38272\n```\n:::\n:::\n\nWe can see that the probability of a prisoner having less than 2 convictions is 69.4%.\n\n## c. \nNext, we'll look at the probability that a randomly selected inmate has 2 or less prior convictions.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the probability of a prisoner having 0, 1, or 2 convictions ( 2 or fewer prior convictions) (events/total possible events)\ntwoorlessconvictions <- 128 + 434 + 160\nprobability2orless <- (twoorlessconvictions/810) * 100\nprint(probability2orless)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 89.1358\n```\n:::\n:::\n\nWe can see that the probability of a prisoner having 2 or less convictions is 89.1%.\n\n## d. \nNext, we'll look at the probability that a randomly selected inmate has more than 2 prior convictions.\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate the probability of a prisoner having more than 2 convictions ( 3 or 4 prior convictions) (events/total possible events)\nmorethan2convictions <- 64 + 24\nprobabilitymorethan2 <- (morethan2convictions/810) * 100\nprint(probabilitymorethan2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.8642\n```\n:::\n:::\n\nWe can see that the probability of a prisoner having more than 2 convictions is 10.9%.\n\n## d. \nHere, we'll calculate the expected value for the number of prior convictions.\n\n::: {.cell}\n\n```{.r .cell-code}\n#define values\nx <- c(0,1,2,3,4)\n\n#define probabilities\nfrequency <- c(128/810, 434/810, 160/810, 64/810, 24/810)\n\n#calculate expected value\nsum(x * frequency)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\nThe expected value is 1.29 prior convictions.\n\n## f. \nIn this final section, we'll calculate the variance and standard deviation for the prior convictions.\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate variance of frequencies\nfrequency <- c(128, 434, 160, 64, 24)\nvar(frequency)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 25948\n```\n:::\n:::\n\nThe variance is 5948.\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate standard deviation of prior convictions \nfrequency <- c(128, 434, 160, 64, 24)\nsd(frequency)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 161.0838\n```\n:::\n:::\n\nThe standard deviation is 161.1.\n\n",
    "supporting": [
      "HW1_ChristineBrydges_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}