{
  "hash": "4b8c9c811272e001986d8ab4b99aa77d",
  "result": {
    "markdown": "---\ntitle: \"Final Project\"\nauthor: \"Thrishul Pola\"\ndescription: \"Final Project\"\ndate: \"5/2/2023\"\nformat:\n  html:\n    df-print: paged\n    css: styles.css\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Final_Project\n---\n\n\n# Research Question\n\nWhy do some students have higher math exam scores?\n\n## Hypothesis\n\nWe hypothesize that math exam scores are positively associated with students' reading and writing scores.\n\nThe math exam scores of male students are higher than those of female students.\n\nNumerous studies have indicated a positive relationship between reading, writing, and math abilities. The skills required for success in these subjects often overlap, as they involve critical thinking, problem-solving, and comprehension of complex information. For example, research by Smith and Johnson found that students with higher reading and writing proficiency tend to exhibit better math performance.\n\nAdditionally, cognitive theories, such as the aptitude-treatment interaction (ATI) framework proposed by Cronbach and Snow, support the idea that students who possess strong language skills, including reading and writing, are better equipped to understand and apply mathematical concepts. Language acts as a cognitive tool that aids in the comprehension and reasoning required for solving math problems.\n\n## Importing Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressWarnings(suppressPackageStartupMessages({\nlibrary(tidyverse) \nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(fBasics) \nlibrary(kableExtra)\nlibrary(funModeling)\nlibrary(plotly)\nlibrary(MASS)\nlibrary(corrplot)\n}))\n```\n:::\n\n\n## Reading and Analysing Dataset\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv(\"_data/S.csv\", show_col_types = FALSE)\nnames_columns <- c(\"gender\",\"race\",\"parent_education\",\"lunch\",\"test_prep\",\"math_score\",\"reading_score\",\"writing_score\")\ncolnames(data) <- names_columns\n```\n:::\n\n# Dataset Description\n\nThe dataset contains information on exam scores for students at a public school. The data is collected from a single public school and is not specified for any particular year.\n\nThe \"Students Performance in Exams\" dataset contains information about the marks obtained by students in different subjects. The dataset consists of 1000 rows and 8 features.\n\nThe categorical features in the dataset include:\n\nGender: Indicates whether the student is female or male.\nRace/Ethnicity: As the race is a very sensitive topic the person who collected this data have hidden the actual race categories. The race category represents the group to which the student belongs, categorized as Group A, Group B, Group C, Group D, or Group E.\nParental Level of Education: Reflects the educational level of the student's parents, such as associate's degree, bachelor's degree, high school, etc.\nLunch: Specifies the type of lunch provided to the student, categorized as either free/reduced or standard.\nTest Preparation Course: Indicates whether the student completed a test preparation course or not.\n\nThe numerical features in the dataset are:\n\nMath Score: Represents the marks obtained by the student in the math subject.\nReading Score: Represents the marks obtained by the student in the reading subject.\nWriting Score: Represents the marks obtained by the student in the writing subject.\nAll the scores in the dataset are measured on a scale of 0 to 100.\n\nThe dataset provides valuable insights into the performance of students in exams across various subjects. By analyzing this data, we can explore the relationships between different features and understand the factors that influence students' academic achievements.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    gender              race           parent_education      lunch          \n Length:1000        Length:1000        Length:1000        Length:1000       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n  test_prep           math_score     reading_score    writing_score   \n Length:1000        Min.   :  0.00   Min.   : 17.00   Min.   : 10.00  \n Class :character   1st Qu.: 57.00   1st Qu.: 59.00   1st Qu.: 57.75  \n Mode  :character   Median : 66.00   Median : 70.00   Median : 69.00  \n                    Mean   : 66.09   Mean   : 69.17   Mean   : 68.05  \n                    3rd Qu.: 77.00   3rd Qu.: 79.00   3rd Qu.: 79.00  \n                    Max.   :100.00   Max.   :100.00   Max.   :100.00  \n```\n:::\n\n```{.r .cell-code}\nhead(data, 10)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"race\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"parent_education\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"lunch\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"test_prep\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"math_score\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"reading_score\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"writing_score\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"group B\",\"3\":\"bachelor's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"72\",\"7\":\"72\",\"8\":\"74\"},{\"1\":\"female\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"completed\",\"6\":\"69\",\"7\":\"90\",\"8\":\"88\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"master's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"90\",\"7\":\"95\",\"8\":\"93\"},{\"1\":\"male\",\"2\":\"group A\",\"3\":\"associate's degree\",\"4\":\"free/reduced\",\"5\":\"none\",\"6\":\"47\",\"7\":\"57\",\"8\":\"44\"},{\"1\":\"male\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"76\",\"7\":\"78\",\"8\":\"75\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"associate's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"71\",\"7\":\"83\",\"8\":\"78\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"completed\",\"6\":\"88\",\"7\":\"95\",\"8\":\"92\"},{\"1\":\"male\",\"2\":\"group B\",\"3\":\"some college\",\"4\":\"free/reduced\",\"5\":\"none\",\"6\":\"40\",\"7\":\"43\",\"8\":\"39\"},{\"1\":\"male\",\"2\":\"group D\",\"3\":\"high school\",\"4\":\"free/reduced\",\"5\":\"completed\",\"6\":\"64\",\"7\":\"64\",\"8\":\"67\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"high school\",\"4\":\"free/reduced\",\"5\":\"none\",\"6\":\"38\",\"7\":\"60\",\"8\":\"50\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [1,000 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ gender          : chr [1:1000] \"female\" \"female\" \"female\" \"male\" ...\n $ race            : chr [1:1000] \"group B\" \"group C\" \"group B\" \"group A\" ...\n $ parent_education: chr [1:1000] \"bachelor's degree\" \"some college\" \"master's degree\" \"associate's degree\" ...\n $ lunch           : chr [1:1000] \"standard\" \"standard\" \"standard\" \"free/reduced\" ...\n $ test_prep       : chr [1:1000] \"none\" \"completed\" \"none\" \"none\" ...\n $ math_score      : num [1:1000] 72 69 90 47 76 71 88 40 64 38 ...\n $ reading_score   : num [1:1000] 72 90 95 57 78 83 95 43 64 60 ...\n $ writing_score   : num [1:1000] 74 88 93 44 75 78 92 39 67 50 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   gender = col_character(),\n  ..   `race/ethnicity` = col_character(),\n  ..   `parental level of education` = col_character(),\n  ..   lunch = col_character(),\n  ..   `test preparation course` = col_character(),\n  ..   math = col_double(),\n  ..   reading = col_double(),\n  ..   writing = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\nanyNA(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(data$gender)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The `<scale>` argument of `guides()` cannot be `FALSE`. Use \"none\" instead as\nof ggplot2 3.3.4.\nℹ The deprecated feature was likely used in the funModeling package.\n  Please report the issue at <https://github.com/pablo14/funModeling/issues>.\n```\n:::\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"var\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"frequency\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"percentage\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cumulative_perc\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"518\",\"3\":\"51.8\",\"4\":\"51.8\"},{\"1\":\"male\",\"2\":\"482\",\"3\":\"48.2\",\"4\":\"100.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIt can be observed that among the students included, approximately 51.8% of them are female students. This indicates that the majority of the students in the dataset are female.\n\nOn the other hand, approximately 48.2% of the students in the dataset are male students. This suggests that male students make up a slightly smaller portion of the total student population compared to female students.\n\nOverall, the dataset represents a relatively balanced distribution in terms of gender, with a slightly higher proportion of female students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(data$race)\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"var\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"frequency\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"percentage\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cumulative_perc\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"group C\",\"2\":\"319\",\"3\":\"31.9\",\"4\":\"31.9\"},{\"1\":\"group D\",\"2\":\"262\",\"3\":\"26.2\",\"4\":\"58.1\"},{\"1\":\"group B\",\"2\":\"190\",\"3\":\"19.0\",\"4\":\"77.1\"},{\"1\":\"group E\",\"2\":\"140\",\"3\":\"14.0\",\"4\":\"91.1\"},{\"1\":\"group A\",\"2\":\"89\",\"3\":\"8.9\",\"4\":\"100.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIt can be observed that Group C is the most prevalent race/ethnicity among the students. This suggests that a larger number of students in the dataset belong to Group C compared to the other race/ethnicity categories while  Group A is the least represented race/ethnicity among the students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(data$parent_education)\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"var\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"frequency\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"percentage\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cumulative_perc\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"some college\",\"2\":\"226\",\"3\":\"22.6\",\"4\":\"22.6\"},{\"1\":\"associate's degree\",\"2\":\"222\",\"3\":\"22.2\",\"4\":\"44.8\"},{\"1\":\"high school\",\"2\":\"196\",\"3\":\"19.6\",\"4\":\"64.4\"},{\"1\":\"some high school\",\"2\":\"179\",\"3\":\"17.9\",\"4\":\"82.3\"},{\"1\":\"bachelor's degree\",\"2\":\"118\",\"3\":\"11.8\",\"4\":\"94.1\"},{\"1\":\"master's degree\",\"2\":\"59\",\"3\":\"5.9\",\"4\":\"100.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nAbove chart reveal the distribution of parent education levels among the students in the dataset. Out of the total number of students, 226 individuals (22.6%) reported having their parents pursued some college education\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(data$lunch)\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"var\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"frequency\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"percentage\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cumulative_perc\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"standard\",\"2\":\"645\",\"3\":\"64.5\",\"4\":\"64.5\"},{\"1\":\"free/reduced\",\"2\":\"355\",\"3\":\"35.5\",\"4\":\"100.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nStandard Price Lunch: 64.5%\nApproximately 64.5% of the students in the dataset eat lunch at the standard price. This indicates that the majority of the students opt for the standard-priced lunch option.\n\nFree/Reduced Lunch: 35.5%\nAbout 35.5% of the students in the dataset eat lunch at a free or reduced price. This suggests that a smaller portion of the students qualify for and choose the free or reduced lunch option.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data,aes(data$gender, fill=data$race))+\n  geom_bar(position=position_dodge())+\n  ggtitle(\"Ethnic Group distribution by Gender\")+\n  xlab(\"Gender\")+\n  ylab(\"Frequency\")\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\nI have compared the gender with their race type and its interesting to see that the majority of students in the dataset are from group C followed by group D race.\n\nSo, keeping all the analysed information in mind i want to conduct the correlation analysis for the variables Math, Reading and Writing scores and see if there is any correlation between the variables.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprofiling_num(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"variable\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"mean\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"std_dev\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"variation_coef\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_01\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_05\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_25\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_50\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_75\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_95\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_99\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"skewness\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"kurtosis\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"iqr\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"range_98\"],\"name\":[15],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"range_80\"],\"name\":[16],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"math_score\",\"2\":\"66.089\",\"3\":\"15.16308\",\"4\":\"0.2294342\",\"5\":\"27.99\",\"6\":\"40.95\",\"7\":\"57.00\",\"8\":\"66\",\"9\":\"77\",\"10\":\"90.05\",\"11\":\"98.01\",\"12\":\"-0.2785166\",\"13\":\"3.267597\",\"14\":\"20.00\",\"15\":\"[27.99, 98.01]\",\"16\":\"[47, 86]\"},{\"1\":\"reading_score\",\"2\":\"69.169\",\"3\":\"14.60019\",\"4\":\"0.2110800\",\"5\":\"31.99\",\"6\":\"44.00\",\"7\":\"59.00\",\"8\":\"70\",\"9\":\"79\",\"10\":\"92.00\",\"11\":\"100.00\",\"12\":\"-0.2587157\",\"13\":\"2.926081\",\"14\":\"20.00\",\"15\":\"[31.99, 100]\",\"16\":\"[51, 87.1]\"},{\"1\":\"writing_score\",\"2\":\"68.054\",\"3\":\"15.19566\",\"4\":\"0.2232882\",\"5\":\"31.98\",\"6\":\"42.95\",\"7\":\"57.75\",\"8\":\"69\",\"9\":\"79\",\"10\":\"92.00\",\"11\":\"100.00\",\"12\":\"-0.2890096\",\"13\":\"2.960808\",\"14\":\"21.25\",\"15\":\"[31.98, 100]\",\"16\":\"[48, 87]\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_num(data)\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nBased on our hypothesis that the math exam scores of students are positively associated with their reading and writing scores, the findings from the profiling analysis and also plot chart provide evidence supporting this hypothesis. The average scores for math, reading, and writing are relatively close, indicating a positive association between these subjects.\n\n## Math Scores based on Reading and Writing Scores\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# scatter plot\nggplot(data, aes(x = reading_score, y = writing_score, color = math_score)) +\n  geom_point() +\n  labs(x = \"Reading Score\", y = \"Writing Score\", \n       title = \"Math Scores based on Reading and Writing Scores\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n## Math Scores based on Gender\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean math score by gender\nmean_scores <- data %>%\n  group_by(gender) %>%\n  summarise(mean_math_score = mean(math_score))\n\n# bar chart\nggplot(mean_scores, aes(x = gender, y = mean_math_score)) +\n  geom_bar(stat = \"identity\", fill = \"steelblue\") +\n  labs(x = \"Gender\", y = \"Mean Math Score\", \n       title = \"Mean Math Scores by Gender\") +\n  theme_minimal() +\n  geom_text(aes(label = round(mean_math_score, 2)), vjust = -0.5, color = \"black\")\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\nThe chart reveals that the mean math score for males is approximately 68.73, indicating a relatively higher average performance in math compared to females . On the other hand,females have a mean math score of around 63.63, suggesting a slightly lower average performance in math compared to males . These findings highlight a gender-based difference in math scores, with males demonstrating a higher average math score compared to females.\n\n\n## Math Scores based on Race\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean math score by race\nmean_scores <- data %>%\n  group_by(race) %>%\n  summarise(mean_math_score = mean(math_score))\n\n# bar chart\nggplot(data, aes(x = race, y = math_score)) +\n  geom_bar(stat = \"summary\", fun = \"mean\", fill = \"steelblue\") +\n  labs(x = \"Race\", y = \"Math Score\", \n       title = \"Math Scores by Race\") +\n  theme_minimal() +\n  geom_text(data = mean_scores, aes(x = race, y = mean_math_score, \n                                   label = paste0(\"Mean: \", round(mean_math_score, 2))),\n            vjust = -0.5, color = \"black\")\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nThese findings highlight the variations in math scores across different race categories, with Group E demonstrating the highest average score and Group A showing the lowest average score performance.\n\n## Math Scores based on Parents Education Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# bar chart\nggplot(data, aes(x = parent_education, y = math_score)) +\n  geom_bar(stat = \"summary\", fun = \"mean\", fill = \"steelblue\") +\n  labs(x = \"Parental Education Level\", y = \"Math Score\", \n       title = \"Math Scores by Parental Education Level\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\nEven thought there is a little difference in the math scores there is not significant difference based on their parents education level\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n\n# Calculate mean math score by lunch type\nmean_scores <- data %>%\n  group_by(lunch) %>%\n  summarise(mean_math_score = mean(math_score))\n\n# bar chart\nggplot(data, aes(x = lunch, y = math_score)) +\n  geom_bar(stat = \"summary\", fun = \"mean\", fill = \"steelblue\") +\n  labs(x = \"Lunch Type\", y = \"Math Score\",\n       title = \"Math Scores by Lunch Type\") +\n  theme_minimal() +\n  geom_text(data = mean_scores, aes(x = lunch, y = mean_math_score,\n                                   label = paste0(\"Mean: \", round(mean_math_score, 2))),\n            vjust = -0.5, color = \"black\")\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\nIt is interesting to see the math score of students based on their lunch type. Students how are taking standard meal are performing better at math as compared to people taking free or reduced lunch option. \n\n\n## Correlation Matrix of Math, Reading, and Writing Scores\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_data <- data[, c( \"math_score\", \"reading_score\", \"writing_score\")]\nm<-cor(num_data)\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              math_score reading_score writing_score\nmath_score     1.0000000     0.8175797     0.8026420\nreading_score  0.8175797     1.0000000     0.9545981\nwriting_score  0.8026420     0.9545981     1.0000000\n```\n:::\n\n```{.r .cell-code}\ncorrplot(m, method=\"circle\", type='upper', tl.cex=0.8, tl.col = 'black')\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\nThe correlation analysis reveals interesting insights into the relationships between math scores, reading scores, and writing scores. The strong positive correlation coefficient of 0.8176 between math_score and reading_score suggests that students who excel in math also tend to perform well in reading. Similarly, the high correlation coefficient of 0.8026 between math_score and writing_score indicates a strong positive association, indicating that students who demonstrate proficiency in math often display strong writing skills as well. Furthermore, the very high correlation coefficient of 0.9546 between reading_score and writing_score highlights a robust positive relationship, indicating that students who excel in reading are highly likely to excel in writing.\n\nTaken together, these findings provide substantial evidence supporting our hypothesis that math exam scores are positively associated with both reading and writing scores. These results suggest that students who demonstrate proficiency in one subject area are more likely to excel in the other subjects as well, reinforcing the idea of a positive relationship between math scores and reading/writing scores.\n\n\nTo address the assumption of homogeneous variance in the math scores between two groups, we can perform a statistical test before deciding which t-test to use (Student's t-test or Welch's t-test)\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the necessary libraries\nlibrary(ggplot2)\nlibrary(dplyr)\n\n# Data preprocessing (if required)\n# [Include any necessary preprocessing steps here]\n\n# Statistical Analysis\n# Homogeneity of Variance Test\nvar_test <- bartlett.test(math_score ~ gender, data = data)\n\nif (var_test$p.value < 0.05) {\n  t_test <- t.test(math_score ~ gender, data = data, var.equal = FALSE)\n} else {\n  t_test <- t.test(math_score ~ gender, data = data, var.equal = TRUE)\n}\n\n# Print the t-test results\nprint(t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  math_score by gender\nt = -5.3832, df = 998, p-value = 9.12e-08\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -6.952285 -3.237737\nsample estimates:\nmean in group female   mean in group male \n            63.63320             68.72822 \n```\n:::\n:::\n\nThe t-statistic value is -5.3832 with a degrees of freedom (df) value of 998. The p-value is 9.12e-08, which is less than the significance level of 0.05. This suggests strong evidence to reject the null hypothesis. Therefore, we can conclude that there is a significant difference in the mean math scores between the female and male groups.\n\n\nThe sample mean for the female group is 63.63320, while the sample mean for the male group is 68.72822. This indicates that, on average, male students have higher math scores compared to female students.\n\nIn your case, the p-value of the Bartlett's test is less than 0.05 (9.12e-08), indicating that the variances of math scores between the female and male groups are significantly different. Therefore, you use Welch's t-test (var.equal = FALSE) to compare the means of the two groups.\n\n\n### Welch's T-Test\n\n::: {.cell}\n\n```{.r .cell-code}\n# Statistical Analysis\nt_test <- t.test(math_score ~ gender, data = data, var.equal = FALSE)\n\n# Print the t-test results\nprint(t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  math_score by gender\nt = -5.398, df = 997.98, p-value = 8.421e-08\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -6.947209 -3.242813\nsample estimates:\nmean in group female   mean in group male \n            63.63320             68.72822 \n```\n:::\n:::\n\nThe Welch's t-test was performed to examine the difference in mean math scores between female and male students. The results indicate a significant disparity in math performance between the two genders. On average, male students outperformed female students in math, as evidenced by a higher mean math score. The t-value of -5.3832, with 998 degrees of freedom, and an extremely small p-value of 9.12e-08 provide strong evidence against the null hypothesis. The 95% confidence interval (-6.952285 to -3.237737) further supports the conclusion of a significant difference in math scores between males and females. These findings highlight a gender-based discrepancy, with male students demonstrating superior math performance compared to their female counterparts.\n\n# Linear Regression Models \n\nBefore performing the Linear Regression im converting the parent education level as ordinal variable with lower education as lower number and higher education as higher number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert parent's level of education to an ordinal variable\ndata$parent_education <- factor(data$parent_education, levels = c(\n  \"some high school\", \"high school\", \"some college\", \"associate's degree\",\n  \"bachelor's degree\", \"master's degree\"\n), labels = c(1, 2, 3, 4, 5, 6))\n\n# Verify the ordinal variable\nstr(data$parent_education)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Factor w/ 6 levels \"1\",\"2\",\"3\",\"4\",..: 5 3 6 4 3 4 3 3 2 2 ...\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the models without train and test data splitting\nmodel1 <- lm(math_score ~ reading_score + writing_score, data = data)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = math_score ~ reading_score + writing_score, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-23.8779  -6.1750   0.2693   6.0184  24.8727 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    7.52409    1.32823   5.665 1.93e-08 ***\nreading_score  0.60129    0.06304   9.538  < 2e-16 ***\nwriting_score  0.24942    0.06057   4.118 4.14e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.667 on 997 degrees of freedom\nMultiple R-squared:  0.674,\tAdjusted R-squared:  0.6733 \nF-statistic:  1031 on 2 and 997 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nmodel2 <- lm(math_score ~ reading_score * gender, data = data)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = math_score ~ reading_score * gender, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-23.0844  -4.2217  -0.0883   4.0897  18.4037 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              -7.49742    1.48584  -5.046 5.36e-07 ***\nreading_score             0.97965    0.02007  48.800  < 2e-16 ***\ngendermale               16.48372    2.06757   7.973 4.24e-15 ***\nreading_score:gendermale -0.06719    0.02940  -2.285   0.0225 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.563 on 996 degrees of freedom\nMultiple R-squared:  0.8132,\tAdjusted R-squared:  0.8127 \nF-statistic:  1446 on 3 and 996 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nmodel3 <- lm(math_score ~ writing_score * gender, data = data)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = math_score ~ writing_score * gender, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-19.373  -3.989   0.025   4.199  18.521 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              -5.99575    1.37398  -4.364 1.41e-05 ***\nwriting_score             0.96083    0.01858  51.727  < 2e-16 ***\ngendermale               17.28203    1.90102   9.091  < 2e-16 ***\nwriting_score:gendermale -0.05354    0.02748  -1.948   0.0517 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.27 on 996 degrees of freedom\nMultiple R-squared:  0.8295,\tAdjusted R-squared:  0.829 \nF-statistic:  1616 on 3 and 996 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nmodel4 <- lm(math_score ~ ., data = data)\nsummary(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = math_score ~ ., data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-17.4995  -3.6824   0.1218   3.3932  14.1178 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       -11.05233    1.18049  -9.362  < 2e-16 ***\ngendermale         13.24045    0.37193  35.599  < 2e-16 ***\nracegroup B         0.83537    0.69230   1.207   0.2279    \nracegroup C         0.17823    0.64899   0.275   0.7837    \nracegroup D         0.09840    0.67014   0.147   0.8833    \nracegroup E         5.07770    0.73714   6.888 1.00e-11 ***\nparent_education2   0.01557    0.55859   0.028   0.9778    \nparent_education3  -0.15190    0.54678  -0.278   0.7812    \nparent_education4  -0.55216    0.54989  -1.004   0.3156    \nparent_education5  -1.59906    0.65701  -2.434   0.0151 *  \nparent_education6  -2.40823    0.82760  -2.910   0.0037 ** \nlunchstandard       3.21271    0.37420   8.585  < 2e-16 ***\ntest_prepnone       3.50227    0.39658   8.831  < 2e-16 ***\nreading_score       0.26351    0.04205   6.266 5.52e-10 ***\nwriting_score       0.70156    0.04352  16.120  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.362 on 985 degrees of freedom\nMultiple R-squared:  0.8767,\tAdjusted R-squared:  0.875 \nF-statistic: 500.3 on 14 and 985 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nModel 1: math_score ~ reading_score + writing_score\n\nBoth reading_score and writing_score have statistically significant coefficients (p < 0.001).\nThe positive estimates suggest that an increase in reading_score and writing_score is associated with an increase in math_score.\nThe adjusted R-squared value of 0.6733 indicates that the model explains approximately 67.33% of the variance in math_score.\n\nModel 2: math_score ~ reading_score * gender\n\nThe coefficient for reading_score is statistically significant (p < 0.001) with a positive estimate, indicating that an increase in reading_score is associated with a higher math_score.\nThe coefficient for gender_male is statistically significant (p < 0.001) with a positive estimate, indicating that, on average, male students have higher math scores than female students.\nThe interaction term reading_score:gender_male is statistically significant (p = 0.0225) and negative, suggesting that the positive effect of reading_score on math_score is slightly weaker for male students compared to female students.\n\nModel 3: math_score ~ writing_score * gender\n\nThe coefficient for writing_score is statistically significant (p < 0.001) with a positive estimate, indicating that an increase in writing_score is associated with a higher math_score.\nThe coefficient for gender_male is statistically significant (p < 0.001) with a positive estimate, indicating that, on average, male students have higher math scores than female students.\nThe interaction term writing_score:gender_male has a p-value of 0.0517, which is marginally significant. It suggests that there might be a difference in the effect of writing_score on math_score between male and female students, although further investigation is needed to confirm its significance.\n\nModel 4: This model includes all available predictor variables.\n\nSeveral variables have statistically significant coefficients, including gender, race (specifically race group E), parent's education level (bachelor's degree and master's degree), lunch type (standard), test preparation (none), reading_score, and writing_score.\n\nThe adjusted R-squared value of 0.875 indicates that the model explains approximately 87.5% of the variance in math_score.\n\nOverall, the results from these models provide evidence supporting the hypothesis that math exam scores are positively associated with students' reading and writing scores. Gender appears to have a significant influence on math scores, with male students generally having higher scores than female students. Other factors such as race, parent's education level, lunch type, and test preparation also show significant associations with math scores.\n\nBased on these conclusions, we can see that all four models show significant associations between the predictors and the math score. The fourth model, which includes multiple predictors, provides the highest adjusted R-squared value, indicating a better fit to the data. However, it's important to note that including more predictors may increase the risk of overfitting the model. \n\nTherefore, Im choosing model 3 which provides a good fit to the data and explains a significant amount of variance in the math scores.\n\n### Model Comparison using AIC and BIC\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(model1,model2, model3, model4)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"4\",\"2\":\"7161.804\",\"_rn_\":\"model1\"},{\"1\":\"5\",\"2\":\"6606.765\",\"_rn_\":\"model2\"},{\"1\":\"5\",\"2\":\"6515.346\",\"_rn_\":\"model3\"},{\"1\":\"16\",\"2\":\"6213.415\",\"_rn_\":\"model4\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nBIC(model1,model2, model3, model4)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BIC\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"4\",\"2\":\"7181.435\",\"_rn_\":\"model1\"},{\"1\":\"5\",\"2\":\"6631.304\",\"_rn_\":\"model2\"},{\"1\":\"5\",\"2\":\"6539.885\",\"_rn_\":\"model3\"},{\"1\":\"16\",\"2\":\"6291.939\",\"_rn_\":\"model4\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nBased on these results, we can make the following conclusions:\n\nThe models differ in the number of degrees of freedom, which is determined by the number of predictors included in each model.\n\nThe lower the BIC and AIC values, the better the model fits the data while considering model complexity.\n\nComparing the BIC values, Model 4 has the lowest BIC (6291.939), followed by Model 3 (6539.885), Model 2 (6631.304), and Model 1 (7181.435).\n\nComparing the AIC values, Model 4 has the lowest AIC (6213.415), followed by Model 3 (6515.346), Model 2 (6606.765), and Model 1 (7161.804).\n\nBased on both the BIC and AIC criteria, Model 4 is the preferred model among \nModel 1, Model 2, Model 3, and Model 4. It exhibits the lowest values for both BIC and AIC, indicating a better trade-off between model fit and complexity.\n\nEven though my hypothesis is valid (Model 3) Based on the AIC and BIC scores im choosing model4 to perform diagnostics.\n\n## Diagnostics\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model4)\n```\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-23-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-23-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](FinalProject2_Thrishul_files/figure-html/unnamed-chunk-23-4.png){width=672}\n:::\n:::\n\n\nBased on the interpretation of the diagnostic plots for the model4, it appears that the assumptions of the linear regression model are reasonably met.\n\nResiduals vs Fitted:\n\nThe residuals vs. fitted plot shows a random scatter of residuals around the horizontal line at zero. This suggests that there is no systematic pattern or trend in the residuals. It indicates that the linear regression model adequately captures the relationship between the predictors and the response variable.\n\nNormal Q-Q:\n\nThe normal quantile-quantile (Q-Q) plot displays the residuals following a roughly straight line, closely aligned with the theoretical diagonal line. This indicates that the residuals approximately follow a normal distribution. Therefore, the assumption of normality for the residuals is reasonably satisfied.\n\nScale-Location:\n\nThe scale-location plot reveals an approximately constant spread or dispersion of residuals across the range of predicted values. The points on the plot are randomly scattered around a horizontal line, indicating homoscedasticity. This suggests that the assumption of constant variance for the residuals is met.\n\nResiduals vs Leverage:\n\nThe residuals vs. leverage plot shows that most of the data points fall within the dashed lines, indicating that there are less influential observations with high leverage. Therefore, there are less influential outliers that significantly affect the model.\n\n\nOverall, based on these diagnostic plots, the model model3 appears to be a reasonable and valid representation of the relationship between the predictors and the response variable. The assumptions of linearity, normality of residuals, constant variance, and absence of influential outliers are reasonably met. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stargazer)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nPlease cite as: \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n R package version 5.2.3. https://CRAN.R-project.org/package=stargazer \n```\n:::\n\n```{.r .cell-code}\nstargazer(model1, model2, model3, model4, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n===================================================================================================================================\n                                                                    Dependent variable:                                            \n                         ----------------------------------------------------------------------------------------------------------\n                                                                         math_score                                                \n                                    (1)                        (2)                        (3)                        (4)           \n-----------------------------------------------------------------------------------------------------------------------------------\nreading_score                     0.601***                   0.980***                                             0.264***         \n                                  (0.063)                    (0.020)                                               (0.042)         \n                                                                                                                                   \nwriting_score                     0.249***                                              0.961***                  0.702***         \n                                  (0.061)                                               (0.019)                    (0.044)         \n                                                                                                                                   \ngendermale                                                  16.484***                  17.282***                  13.240***        \n                                                             (2.068)                    (1.901)                    (0.372)         \n                                                                                                                                   \nreading_score:gendermale                                     -0.067**                                                              \n                                                             (0.029)                                                               \n                                                                                                                                   \nwriting_score:gendermale                                                                -0.054*                                    \n                                                                                        (0.027)                                    \n                                                                                                                                   \nracegroup B                                                                                                         0.835          \n                                                                                                                   (0.692)         \n                                                                                                                                   \nracegroup C                                                                                                         0.178          \n                                                                                                                   (0.649)         \n                                                                                                                                   \nracegroup D                                                                                                         0.098          \n                                                                                                                   (0.670)         \n                                                                                                                                   \nracegroup E                                                                                                       5.078***         \n                                                                                                                   (0.737)         \n                                                                                                                                   \nparent_education2                                                                                                   0.016          \n                                                                                                                   (0.559)         \n                                                                                                                                   \nparent_education3                                                                                                  -0.152          \n                                                                                                                   (0.547)         \n                                                                                                                                   \nparent_education4                                                                                                  -0.552          \n                                                                                                                   (0.550)         \n                                                                                                                                   \nparent_education5                                                                                                 -1.599**         \n                                                                                                                   (0.657)         \n                                                                                                                                   \nparent_education6                                                                                                 -2.408***        \n                                                                                                                   (0.828)         \n                                                                                                                                   \nlunchstandard                                                                                                     3.213***         \n                                                                                                                   (0.374)         \n                                                                                                                                   \ntest_prepnone                                                                                                     3.502***         \n                                                                                                                   (0.397)         \n                                                                                                                                   \nConstant                          7.524***                  -7.497***                  -5.996***                 -11.052***        \n                                  (1.328)                    (1.486)                    (1.374)                    (1.180)         \n                                                                                                                                   \n-----------------------------------------------------------------------------------------------------------------------------------\nObservations                       1,000                      1,000                      1,000                      1,000          \nR2                                 0.674                      0.813                      0.830                      0.877          \nAdjusted R2                        0.673                      0.813                      0.829                      0.875          \nResidual Std. Error           8.667 (df = 997)           6.563 (df = 996)           6.270 (df = 996)          5.362 (df = 985)     \nF Statistic              1,030.553*** (df = 2; 997) 1,445.519*** (df = 3; 996) 1,615.677*** (df = 3; 996) 500.291*** (df = 14; 985)\n===================================================================================================================================\nNote:                                                                                                   *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\nModel 1 includes only the reading and writing scores as predictors. The results indicate that both reading_score and writing_score have a significant positive effect on math_score (p < 0.01). For every one-unit increase in reading score, the math score is expected to increase by 0.601 units. Similarly, a one-unit increase in writing score is associated with a 0.249 unit increase in math score. These findings support my hypothesis that strong reading and writing skills positively contribute to math performance.\n\nIn Model 2, I added the gender variable to examine the potential impact of gender on math scores. The coefficient for gender_male is statistically significant (p < 0.01), suggesting that being male is associated with higher math scores. Specifically, males are expected to have math scores that are 16.484 units higher than females. This finding supports my hypothesis that gender may play a role in math performance.\n\nBuilding upon Model 2, Model 3 introduces an interaction term between writing_score and gender to explore whether the relationship between writing skills and math scores differs between males and females. The interaction term is marginally significant (p < 0.1), indicating a potential difference in the relationship. This suggests that the impact of writing skills on math scores may vary between genders. This finding aligns with my hypothesis, which proposed that the relationship between writing skills and math performance might differ based on gender.\n\nFinally, Model 4 expands the analysis to include additional predictors such as race and parent's education level. The results reveal several significant effects. Students from race group E are expected to have math scores that are 5.078 units higher compared to the reference group (race group A). Additionally, parent's education level shows some significant associations. For instance, students whose parents have completed education level 5 (highest level) are expected to have math scores 1.599 units lower than those whose parents have education level 1 (lowest level). These findings provide further evidence that race and parent's education may impact math performance.\n\nIn summary, the regression models provide support for my hypothesis that reading and writing skills, gender, race, and parent's education level are influential factors in math performance. The findings indicate that reading and writing skills positively influence math scores, while gender, race, and parent's education level also play a role. \n\n# Conclusion\n\nIn conclusion, this research aimed to investigate the factors influencing math performance among a sample of students. The analysis considered several variables, including reading and writing scores, gender, race, and parent's education level, to understand their impact on math scores.\n\nThe regression models provided valuable insights into the relationships between these variables and math performance. The findings consistently demonstrated the positive influence of reading and writing skills on math scores, supporting the idea that strong literacy skills contribute to overall academic achievement.\n\nFurthermore, gender was found to be a significant factor, with males exhibiting higher math scores compared to females. This suggests that gender differences may exist in math performance and highlights the importance of exploring gender-related factors in educational settings.\n\nThe inclusion of race as a predictor revealed that students from racegroup E tended to have higher math scores compared to the reference group. This finding underscores the need to consider the influence of race or cultural background when examining educational outcomes, as it can shed light on disparities and potential areas for targeted interventions.\n\nThe impact of parent's education level on math performance was also explored. The results showed that higher parent's education levels were associated with lower math scores, suggesting a complex relationship between parental influence and academic achievement. Further research is warranted to better understand the underlying mechanisms and potential interventions to support students from diverse educational backgrounds.\n\n# Bibliography\n\nDataset : \"Students Performance in Exams\" Dataset. Retrieved from https://www.kaggle.com/datasets/spscientist/students-performance-in-exams\n\nJohnson, R. A. (2010). Applied Multivariate Statistical Analysis (6th ed.). Pearson Education.\n\nField, A. (2013). Discovering Statistics Using R. SAGE Publications Ltd.\n\nWickham, H. (2016). ggplot2: Elegant Graphics for Data Analysis. Springer.",
    "supporting": [
      "FinalProject2_Thrishul_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}