{
  "hash": "a2fb0ea58ad71c30f56358f2c2d03e62",
  "result": {
    "markdown": "---\ntitle: \"Final Project - Impact of Men's March Madness Tournament on a School's Online Conversation Volume\"\nauthor: \"Darron Bunt\"\ndescription: \"Final Project - Darron Bunt\"\ndate: \"05/25/2023\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - finalproject\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.2     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(lubridate)\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n```\n:::\n\n```{.r .cell-code}\nlibrary(forcats)\nlibrary(stargazer)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nPlease cite as: \n\n Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.\n R package version 5.2.3. https://CRAN.R-project.org/package=stargazer \n```\n:::\n:::\n\n# Introduction\n\nIn April 2013, Doug J. Chung published a research paper[^1] endeavoring to quantify and model the impact of the so-called \"Flutie Effect\" - the spillover impact that athletics has on the quantity and quality of applicants to US colleges (named after Boston College quarterback Doug Flutie, who in 1984 threw a Hail Mary touchdown pass to secure victory with six seconds in a game against the University of Miami, qualifying the team to compete in the Cotton Bowl[^2]). The legacy of Flutie's on-field success has been credited with catalyzing a 30% increase in undergraduate applications at Boston College, though institutional officials have argued that other, non-athletic factors were the \"true\" reason behind the increase. This trend of increased applications after prominent athletic successes, however, has been observed at other institutions including Georgetown, Northwestern, Boise State, and Texas Christian University.\n\n[^1]: <https://www.hbs.edu/faculty/Pages/item.aspx?num=44778>\n[^2]: <https://hbswk.hbs.edu/item/diagnosing-the-flutie-effect-on-college-marketing>\n\nChung was able to find a statistically significant relationship between athletic success and both the quantity (number of applications) and quality (SAT scores of those applicants) of applicants to a given institution; his findings included that when a school rises from being classified as a mediocre football program to great one, applications rise by 18.7%[^3]. \n\n[^3]: <https://www.forbes.com/sites/hbsworkingknowledge/2013/04/29/the-flutie-effect-how-athletic-success-boosts-college-applications/?sh=61f984206e96>\n\nWhile in my job I do not focus directly on applications to US colleges, I do work with on campus marketing and communications leaders, and generate insights from data derived from online conversation about their schools so that they can better understand that conversation in ways that can help them to develop, refine, and align their communications strategies with the goals of the institutions that they serve[^4]. A trend I frequently observe while analyzing this online conversation data is the impact that athletics has on the volume and reach of mentions related to schools. \n\n[^4]: <https://www.campussonar.com/campus-sonar-expertise>\n\nIn benchmarking work that we've undertaken in order to better understand online conversation trends in higher education, we've found that, on average, 63% of all online conversation related to schools is about their athletics - and for some schools, this proportion can be as high as 91%[^5]. And while the proportion of overall online conversation relating to different colleges is already quite high, there are certain significant events within the realm of college sports that send mention volume even higher. One such event is March Madness.\n\n[^5]: Publication of this data is forthcoming; it will be discussed during this webinar <https://t.co/MK2fARTWb5>\n\nRun by the NCAA every year during the month of March, the men's version of the March Madness tournament is widely regarded as one of biggest American sporting events. 68 teams participate in the three-week long single-elimination tournament, which produced $1.14 billion in annual revenue for the NCAA in 2022[^6]. One of the most exciting parts of the tournament are the \"Cinderella stories\"; teams with a low ranking that manage to eliminate higher ranked teams. \n\n[^6]: <https://wallethub.com/blog/march-madness-statistics/11016>\n\nIn 2022, I became interested in developing a greater understanding of the impact that March Madness could have on a school's online conversation volume and began tracking that year's Cinderella - the Saint Peter's College Peacocks, a #15 seed that made it all the way to the Elite 8. In their Sweet 16 game against Purdue, Saint Peter's had more mentions *per minute* than their average monthly volume for the prior five months. Their total mention volume during the month of March was *12,380 times* more than that same monthly average[^7].\n\n[^7]: <https://blog.campussonar.com/blog/leverage-the-everyday-impact-of-athletics>\n\nAfter completing that work, I became increasingly curious about how participation in the tournament affected conversation volume and reach for all teams, not just Cinderella stories. I wanted to investigate the factors that might influence more/less conversation volume for any given team, and indeed, whether conversation about the team was the only facet of conversation about a college that increased - or if the school as a whole received more conversation overall. I became very interested in learning more about the overall trends that relate to participation in events like March Madness and how we could use that information to provide strategic insights to colleges across the US.\n\nBringing it back to the Flutie Effect - if on-field athletic success can impact enrollment at US colleges, it stands to reason that online conversation about athletic success (or athletic events in general) could have a similar impact. Accordingly, it would be prudent to further explore the impact an event like the men's March Madness tournament has on online conversation volume for US colleges. \n\n# Research Question\n\nSpecifically, the research question that I want to explore is:\n\n**How does online conversation volume differ when schools are participating in the men's March Madness tournament?** \n\nTo examine this research question in greater detail, I will also consider what variables contribute to differences in mention volume during the tournament. These variables can be broken down into three types: game outcome related, tournament related, and school related. \n\nThe answer to this question and a better understanding of the variables that contribute to differences in mention volume will provide more robust insight into the overall impact that events such as the men's March Madness tournament have and the types of changes that can be expected based on the presence/absence of additional variables.  This information can subsequently serve to inform strategies and tactics that can be implemented by marketing and communications professionals who focus on digital media in higher education. That is, schools can use this information to develop further hypotheses to be tested that would facilitate a goal of leveraging and maximizing the impact of athletic participation and success on their online conversation. \n\n# Hypothesis\n\nMy overarching hypothesis is that **participation in the men's March Madness tournament increases online conversation about the schools that are involved.** I further hypothesize that the increase in conversation volume for each school will be further influenced by three types of additional mediating variables: game-outcome related variables, school-related variables, and tournament related variables.\n\n# Data Collection\n\nThe data used for this project was collected by me using the Brandwatch Consumer Research platform. I first wrote Boolean to search for mentions about all 68 schools with teams in the men's March Madness tournament, using the same parameters to construct each one (specifically, the school's full name, shortened name(s), acronym(s), mascot(s), website URL, athletics website URL, and Twitter usernames for the school's flagship, flagship athletics, and men's basketball team accounts). \n\nThe Boolean was then used to run a query within Brandwatch to pull all relevant, retrievable online mentions for the 68 schools made between January 1 and May 12 2023. This search returned 9,007,552 mentions. \n\nOne of the features included in Brandwatch is the ability to segment data into categories, and this can be done in a wide range of manners (using Boolean or a variety of pre-built parameters such as content sources and mention types). I used this feature to break the mention volume data down by school (the 68 schools participating in men's March Madness), and daily volume (for the 132 days) and exported this information to .csv. This mention volume data provides the foundation for this analysis. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nMMVolumeNew <- read_csv(\"_data/MMVolumeByDayFullNEW.csv\", show_col_types = FALSE)\n```\n:::\n\n\n# Variables of Interest \n\nI performed a variety of data manipulation in order to create my variables of interest.\n\n## Data Manipulation For Mention Volume (Dependent Variable)\n\nI calculated the average daily volume for the following time spans:\n\n* during the tournament (March 14 to day the after each team's elimination)\n* outside of the tournament (January 1 to March 13 and the day after each team's elimination to May 12 - ie. both before and after, but not during)\n* the week after the tournament for each team (the week after each team's elimination)\n* two weeks after the tournament for each team (the week two weeks after each team's elimination)\n* before the tournament (January 1 to March 11)\n* after the tournament (Two days after each team's elimination to May 12)\n\nI also added columns for the actual daily volume on the following days: \n\n* Day of elimination\n* Day after elimination\n* Two days after elimination\n* Three days after elimination\n* Four days after elimination\n* Five days after elimination\n* Six days after elimination\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read in data\nTournamentVariables <- read_csv(\"_data/MMVariables.csv\", show_col_types = FALSE)\n\n# Join data\nMMVolumeVar <- MMVolumeNew %>%\n  left_join(TournamentVariables, by = \"School\")\n\n# Calculate pre-tournament average daily volume \nMMVolumeVar$VolBefore <- (round(rowMeans(MMVolumeVar[, 2:73]), digits = 0))\n\n# Create a function to pull the rows needed to calculate \"during tournament\" for each of the schools\nfun1 <- function(row) {\n  start_col1 <- as.numeric(row[134])  # Convert the value to a numeric column index\n  end_col1 <- as.numeric(row[135])    # Convert the value to a numeric column index\n  values1 <- as.numeric(row[start_col1:end_col1]) # The rows to calculate the average\n  average1 <- (round(mean(values1, na.rm = TRUE), digits = 0))\n  return(average1)\n}\n\n# Return the average daily volume for \"during tournament\" for each school \nMMVolumeVar$VolDuring <- apply(MMVolumeVar, 1, fun1)\n\n# Create a function to pull the rows needed to calculate \"after tournament\" for each of the schools\nfun2 <- function(row) {\n  start_col2 <- as.numeric(row[136])  # Convert the value to a numeric column index\n  end_col2 <- as.numeric(row[137])    # Convert the value to a numeric column index\n  values2 <- as.numeric(row[start_col2:end_col2]) # The rows to calculate the average\n  average2 <- (round(mean(values2, na.rm = TRUE), digits = 0))\n  return(average2)\n}\n\n# Return the average daily volume for \"during tournament\" for each school \nMMVolumeVar$VolAfter <- apply(MMVolumeVar, 1, fun2)\n\n# Create a function to pull the rows needed for post-elimination volume \nfun3 <- function(row) {\n  column_index3 <- as.numeric(row[136])  # Convert the value to a numeric column index\n  value3 <- as.numeric(row[column_index3])  # Get the value from the specified column\n  return(value3)\n}\n\n# Return the post-elimination day volume for each school \nMMVolumeVar$VolPostElim <- apply(MMVolumeVar, 1, fun3)\n\n# Create a function to pull the rows needed for non-tournament volume\nfun14 <- function(row) {\n  start_col14 <- as.numeric(row[145])    # Start column index for range 1\n  end_col14 <- as.numeric(row[146])      # End column index for range 1\n  start_col14a <- as.numeric(row[147])    # Start column index for range 2\n  end_col14a <- as.numeric(row[148])      # End column index for range 2\n  \n  values14 <- as.numeric(row[start_col14:end_col14])    # Values for range 1\n  values14a <- as.numeric(row[start_col14a:end_col14a])    # Values for range 2\n  \n  values14b <- c(values14, values14a)    # Combine the values from both ranges\n  \n  average14 <- (round(mean(values14b, na.rm = TRUE), digits = 0))\n  return(average14)\n}\n\n# Return the average non-tournament daily volume for each school \nMMVolumeVar$VolNonTourn <- apply(MMVolumeVar, 1, fun14) \n\n# Create a function to pull the rows needed for post-elimination +1 volume \nfun4 <- function(row) {\n  column_index4 <- as.numeric(row[137])  # Convert the value to a numeric column index\n  value4 <- as.numeric(row[column_index4])  # Get the value from the specified column\n  return(value4)\n}\n\n# Return the post-elimination +1 volume for each school \nMMVolumeVar$VolPostElim1 <- apply(MMVolumeVar, 1, fun4)\n\n# Create a function to pull the rows needed for post-elimination +2 volume \nfun5 <- function(row) {\n  column_index5 <- as.numeric(row[138])  # Convert the value to a numeric column index\n  value5 <- as.numeric(row[column_index5])  # Get the value from the specified column\n  return(value5)\n}\n\n# Return the post-elimination +2 volume for each school \nMMVolumeVar$VolPostElim2 <- apply(MMVolumeVar, 1, fun5)\n\n# Create a function to pull the rows needed for post-elimination +3 volume \nfun6 <- function(row) {\n  column_index6 <- as.numeric(row[139])  # Convert the value to a numeric column index\n  value6 <- as.numeric(row[column_index6])  # Get the value from the specified column\n  return(value6)\n}\n\n# Return the post-elimination +3 volume for each school \nMMVolumeVar$VolPostElim3 <- apply(MMVolumeVar, 1, fun6)\n\n# Create a function to pull the rows needed for post-elimination +4 volume \nfun17 <- function(row) {\n  column_index17 <- as.numeric(row[140])  # Convert the value to a numeric column index\n  value17 <- as.numeric(row[column_index17])  # Get the value from the specified column\n  return(value17)\n}\n\n# Return the post-elimination +4 volume for each school \nMMVolumeVar$VolPostElim4 <- apply(MMVolumeVar, 1, fun17)\n\n# Create a function to pull the rows needed for post-elimination +5 volume \nfun18 <- function(row) {\n  column_index18 <- as.numeric(row[141])  # Convert the value to a numeric column index\n  value18 <- as.numeric(row[column_index18])  # Get the value from the specified column\n  return(value18)\n}\n\n# Return the post-elimination +5 volume for each school \nMMVolumeVar$VolPostElim5 <- apply(MMVolumeVar, 1, fun18)\n\n# Create a function to pull the rows needed for post-elimination +6 volume \nfun19 <- function(row) {\n  column_index19 <- as.numeric(row[142])  # Convert the value to a numeric column index\n  value19 <- as.numeric(row[column_index19])  # Get the value from the specified column\n  return(value19)\n}\n\n# Return the post-elimination +6 volume for each school \nMMVolumeVar$VolPostElim6 <- apply(MMVolumeVar, 1, fun19)\n\n# Create a function to pull the rows needed for day after elimination volume \nfun20 <- function(row) {\n  column_index20 <- as.numeric(row[135])  # Convert the value to a numeric column index\n  value20 <- as.numeric(row[column_index20])  # Get the value from the specified column\n  return(value20)\n}\n\n# Return the day after volume for each school \nMMVolumeVar$VolAfterElim <- apply(MMVolumeVar, 1, fun20)\n\n# Create a function to pull the rows needed for day of elimination volume \nfun21 <- function(row) {\n  column_index21 <- as.numeric(row[149])  # Convert the value to a numeric column index\n  value21 <- as.numeric(row[column_index21])  # Get the value from the specified column\n  return(value21)\n}\n\n# Return the day after volume for each school \nMMVolumeVar$VolElim_Day <- apply(MMVolumeVar, 1, fun21)\n\n# Create a function to pull the rows needed to calculate \"week after tournament\" for each of the schools\nfun15 <- function(row) {\n  start_col15 <- as.numeric(row[136])  # Convert the value to a numeric column index\n  end_col15 <- as.numeric(row[142])    # Convert the value to a numeric column index\n  values15 <- as.numeric(row[start_col15:end_col15]) # The rows to calculate the average\n  average15 <- (round(mean(values15, na.rm = TRUE), digits = 0))\n  return(average15)\n}\n\n# Return the average daily volume for \"week after tournament\" for each school \nMMVolumeVar$VolWeekAfter <- apply(MMVolumeVar, 1, fun15)\n\n# Create a function to pull the rows needed to calculate \"two weeks after tournament\" for each of the schools\nfun16 <- function(row) {\n  start_col16 <- as.numeric(row[143])  # Convert the value to a numeric column index\n  end_col16 <- as.numeric(row[144])    # Convert the value to a numeric column index\n  values16 <- as.numeric(row[start_col16:end_col16]) # The rows to calculate the average\n  average16 <- (round(mean(values16, na.rm = TRUE), digits = 0))\n  return(average16)\n}\n\n# Return the average daily volume for \"two weeks after tournament\" for each school \nMMVolumeVar$Vol2WeeksAfter <- apply(MMVolumeVar, 1, fun16)\n\n# Specify the starting date\nTournEndDate <- as.Date(\"2023-03-12\")\n\n# Convert the existing column \"Numbers\" to dates\nMMVolumeVar$EndDate <- TournEndDate + (MMVolumeVar$During_End - 72)\n\n# Create a data frame with the columns for the calculated means\nMMVolAvgs <- MMVolumeVar %>%\n  select(School, VolDuring, VolNonTourn, VolWeekAfter, Vol2WeeksAfter, VolElim_Day, VolAfterElim, VolPostElim,  VolPostElim1, VolPostElim2, VolPostElim3, VolPostElim4, VolPostElim5, VolPostElim6, VolBefore, VolAfter)\nMMVolAvgs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 68 × 16\n   School          VolDuring VolNonTourn VolWeekAfter Vol2WeeksAfter VolElim_Day\n   <chr>               <dbl>       <dbl>        <dbl>          <dbl>       <dbl>\n 1 University of …       796         260          151            132        1481\n 2 University of …      2903        1320         1037           1113        6441\n 3 Arizona State …      2476        1352         1121           1199        2458\n 4 Duke University      4567        2162         1242           1879        8261\n 5 Utah State Uni…       734         297          203            236        1796\n 6 University of …      3762        1453          824            983        6693\n 7 North Carolina…      1013         861          993            561        2255\n 8 University of …      5907        1487         1722           1239       11182\n 9 Providence Col…       721         363          997            489        1829\n10 Xavier Univers…      1238         354          228            170        2975\n# ℹ 58 more rows\n# ℹ 10 more variables: VolAfterElim <dbl>, VolPostElim <dbl>,\n#   VolPostElim1 <dbl>, VolPostElim2 <dbl>, VolPostElim3 <dbl>,\n#   VolPostElim4 <dbl>, VolPostElim5 <dbl>, VolPostElim6 <dbl>,\n#   VolBefore <dbl>, VolAfter <dbl>\n```\n:::\n:::\n\n## Data Manipulation for Independent Variables\n\nI also manipulated the data to create my tournament variables of interest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read in game scores, dates, etc.\nDateAndTeam <- read_csv(\"_data/MBBMMGameData.csv\", show_col_types = FALSE)\n\nDateAndTeam$GameDate <- as.Date(DateAndTeam$Date, format = \"%m/%d/%Y\")\nDateAndTeam$Time <- DateAndTeam$Time <- gsub(\" ET\", \"\", DateAndTeam$Time)\nDateAndTeam$Time <- strptime(DateAndTeam$Time, format=\"%I:%M%p\")\nDateAndTeam$Time <- format(DateAndTeam$Time, format = \"%H:%M:%S\")\n\n# Use GameDate to create a TournamentRound variable\nDateRoundTeam <- DateAndTeam %>%\n  mutate(TournamentRound = case_when(\n      GameDate >= \"2023-03-14\" & GameDate <= \"2023-03-15\" ~ \"First 4\", \n      GameDate >= \"2023-03-16\" & GameDate <= \"2023-03-17\" ~ \"Round of 64\",\n      GameDate >= \"2023-03-18\" & GameDate <= \"2023-03-19\" ~ \"Round of 32\",\n      GameDate >= \"2023-03-23\" & GameDate <= \"2023-03-24\" ~ \"Sweet 16\",\n      GameDate >= \"2023-03-25\" & GameDate <= \"2023-03-26\" ~ \"Elite 8\",\n      GameDate == \"2023-04-01\" ~ \"Final 4\",\n      GameDate == \"2023-04-03\" ~ \"Championship\")) %>%\n\n# Replace game start times with time categories\n  mutate(Time = case_when(\n    Time >= \"12:00:00\" & Time < \"14:14:59\" ~ \"Early Afternoon\",\n    Time >= \"14:15:00\" & Time < \"16:29:59\" ~ \"Mid Afternoon\",\n    Time >= \"16:30:00\" & Time < \"18:44:59\" ~ \"Late Afternoon\",\n    Time >= \"18:45:00\" & Time < \"20:59:59\" ~ \"Early Evening\",\n    Time >= \"21:00:00\" & Time < \"22:45:00\" ~ \"Late Evening\")) %>%\n\n# Import game day volume\n  mutate(GDayVolCol = case_when(\n      GameDate == \"2023-03-14\" ~ 74, \n      GameDate == \"2023-03-15\" ~ 75, \n      GameDate == \"2023-03-16\" ~ 76,\n      GameDate == \"2023-03-17\" ~ 77,\n      GameDate == \"2023-03-18\" ~ 78,\n      GameDate == \"2023-03-19\" ~ 79,\n      GameDate == \"2023-03-23\" ~ 83,\n      GameDate == \"2023-03-24\" ~ 84,\n      GameDate == \"2023-03-25\" ~ 85,\n      GameDate == \"2023-03-26\" ~ 86,\n      GameDate == \"2023-04-01\" ~ 92,\n      GameDate == \"2023-04-03\" ~ 94\n            )) %>%\n  rename(School = Team) %>%\n  select(School, Seed, GameDate, TournamentRound, Time, GDayVolCol, IsWinner, WinningSeed, LosingSeed)\n\n# Create a function to bring in Game Day Volume \nfun13 <- function(row) {\n  school <- row[\"School\"]  # Get the school name from the row\n  column_index <- as.numeric(row[\"GDayVolCol\"])  # Convert the value to a numeric column index\n  value <- MMVolumeVar[MMVolumeVar$School == school, column_index]\n  return(as.numeric(value))\n}\n\n# Return the flattened game day volume for each school\nDateRoundTeam$GameDayVolume <- unlist(apply(DateRoundTeam, 1, fun13))\n\n# Create data frame with School, GameDate, Time, TournamentRound, GameDayVolume, IsWinner, WinningSeed, LosingSeed\nTVariables <- DateRoundTeam %>%\n  left_join(TournamentVariables, by = \"School\") %>%\n  select(School, Seed, GameDate, Time, TournamentRound, GameDayVolume, IsWinner, WinningSeed, LosingSeed)\n\n# Mutate WinningSeed and LosingSeed to create SeedDifference column \nTVariables <- TVariables %>%\n  mutate(SeedDifference = ifelse(IsWinner == \"Yes\", WinningSeed - LosingSeed, LosingSeed - WinningSeed)) %>%\n# Mutate SeedDifference and Is Winner to create UpsetWin and UpsetLoss\n   mutate(UpsetWin = ifelse(IsWinner == \"Yes\" & SeedDifference >= 5, \"Yes\", \"No\")) %>%\n  mutate(UpsetLoss = ifelse(IsWinner == \"No\" & SeedDifference <= -5, \"Yes\", \"No\")) %>%\n# Mutate IsWinner and Winning Seed/Losing Seed to create FavoriteWin and FavoriteLoss\n  mutate(FavoriteWin = ifelse(IsWinner == \"Yes\" & WinningSeed > LosingSeed, \"Yes\", \"No\")) %>%\n  mutate(FavoriteLoss = ifelse(IsWinner == \"No\" & WinningSeed > LosingSeed, \"Yes\", \"No\")) %>%\n# Mutate IsWinner and Winning Seed/Losing Seed to create UnderdogWin and UnderdogLoss\n  mutate(UnderdogWin = ifelse(IsWinner == \"Yes\" & WinningSeed < LosingSeed, \"Yes\", \"No\")) %>%\n  mutate(UnderdogLoss = ifelse(IsWinner == \"No\" & WinningSeed < LosingSeed, \"Yes\", \"No\"))\nTVariables\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 134 × 16\n   School           Seed GameDate   Time  TournamentRound GameDayVolume IsWinner\n   <chr>           <dbl> <date>     <chr> <chr>                   <dbl> <chr>   \n 1 Pittsburgh Uni…    11 2023-03-14 Late… First 4                  4731 Yes     \n 2 Texas A&M Corp…    16 2023-03-14 Late… First 4                   521 Yes     \n 3 Arizona State …    11 2023-03-15 Late… First 4                  3967 Yes     \n 4 Fairleigh Dick…    16 2023-03-15 Late… First 4                  1669 Yes     \n 5 Princeton Univ…    15 2023-03-16 Mid … Round of 64              9532 Yes     \n 6 Furman Univers…    13 2023-03-16 Earl… Round of 64              8721 Yes     \n 7 Penn State Uni…    10 2023-03-16 Late… Round of 64              3692 Yes     \n 8 Auburn Univers…     9 2023-03-16 Earl… Round of 64              4477 Yes     \n 9 University of …     8 2023-03-16 Late… Round of 64              5918 Yes     \n10 University of …     8 2023-03-16 Earl… Round of 64             10336 Yes     \n# ℹ 124 more rows\n# ℹ 9 more variables: WinningSeed <dbl>, LosingSeed <dbl>,\n#   SeedDifference <dbl>, UpsetWin <chr>, UpsetLoss <chr>, FavoriteWin <chr>,\n#   FavoriteLoss <chr>, UnderdogWin <chr>, UnderdogLoss <chr>\n```\n:::\n:::\n\n\n# Does Participation Impact Average Mention Volume? \n\nIn order to answer the question of what impact participation in the men's March Madness tournament has on the volume of online conversation about the schools involved, it is important to first examine **if** March Madness does indeed have an impact on conversation volume. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Descriptive statistics for volume during the tournament and not during\nMMVolAvgs %>%\n  select(VolNonTourn, VolDuring) %>%\nsummary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  VolNonTourn     VolDuring     \n Min.   :  51   Min.   : 322.0  \n 1st Qu.: 269   1st Qu.: 731.5  \n Median : 682   Median :1802.0  \n Mean   : 908   Mean   :2389.1  \n 3rd Qu.:1312   3rd Qu.:3576.0  \n Max.   :5269   Max.   :7504.0  \n```\n:::\n:::\n\nThis seems to indicate a pretty clear difference between average volume during the tournament and average volume outside of the tournament; the mean for volume has increased from 908 mentions to 2,389 and the IQR has increased from 269-1,312 to 731-3,576\n\nWe can also display this difference visually:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Create bar chart showing difference between average mention volume during/not during March Madness\n\nMMVolAvgs_Long <- pivot_longer(MMVolAvgs, cols = c(VolDuring, VolNonTourn), names_to = \"Variable\", values_to = \"Volume\")\nMMVolAvgs_Long$School <- factor(MMVolAvgs_Long$School, levels = unique(MMVolAvgs_Long$School)) \nggplot(MMVolAvgs_Long, \n       aes(x = School, y=Volume, fill = Variable)) +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  labs(x = \"School\", y = \"Average Mention Volume\", fill = \"Time Frame\") +\n scale_fill_manual(values = c(\"VolDuring\" = \"blue\", \"VolNonTourn\" = \"red\"),\n                    labels = c(\"March Madness\", \"Not March Madness\")) +\n  ggtitle(\"Comparison of Mention Volume During and Outside March Madness\") +\n  theme(axis.text.x = element_blank())\n```\n\n::: {.cell-output-display}\n![](FPRedoneWithLog_DarronBunt_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nIt can also be helpful to visualize this difference in mention volume by highlighting just how large, proportionally, that difference was. Accordingly, I transformed these volume metrics into a percentage difference in in-tournament volume compared to outside-tournament volume. \n\nWe can then provide summary statistics on this proportional difference in volume during the tournament compared to not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate difference between average volume during tournament and non-tournament\nMMVolDiffs <- MMVolAvgs %>%\n  mutate(\n    InTournamentDifference = round((((VolDuring / VolNonTourn) * 100) -100), digits = 2),\n    WeekAfterDifference = round((((VolWeekAfter / VolNonTourn) * 100) -100), digits = 2),\n    V2WeeksAfterDifference = round((((Vol2WeeksAfter / VolNonTourn) * 100) -100), digits = 2),\n    ElimDayDifference = round(((VolElim_Day / VolNonTourn) * 100), digits = 2),\n    DayAfterElimDifference = round(((VolAfterElim / VolNonTourn) * 100), digits = 2),\n    DayPostElimDifference = round(((VolPostElim / VolNonTourn) * 100), digits = 2),\n    ElimPlus1Difference = round(((VolPostElim1 / VolNonTourn) * 100), digits = 2),\n    ElimPlus2Difference = round(((VolPostElim2 / VolNonTourn) * 100), digits = 2), \n    ElimPlus3Difference = round(((VolPostElim3 / VolNonTourn) * 100), digits = 2),\n    ElimPlus4Difference = round(((VolPostElim4 / VolNonTourn) * 100), digits = 2),\n    ElimPlus5Difference = round(((VolPostElim5 / VolNonTourn) * 100), digits = 2),\n    ElimPlus6Difference = round(((VolPostElim6 / VolNonTourn) * 100), digits = 2),\n  ) %>%\n  \n  select(School, InTournamentDifference, WeekAfterDifference, V2WeeksAfterDifference, ElimDayDifference, DayPostElimDifference, ElimPlus1Difference, ElimPlus2Difference, ElimPlus3Difference) %>%\n  arrange(desc(InTournamentDifference))\n\n# Descriptive statistics for the proportional difference in volume during the tournament and not \nsummary(MMVolDiffs$InTournamentDifference)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  -6.32   94.75  162.41  278.95  278.06 3800.00 \n```\n:::\n:::\n\nAmong the 68 schools, there was a mean proportional difference in average mention volume of 279% - again, this seems to indicate that participation in March Madness increases mention volume. \n\nOverall, mention volume increased by more than 100% for 50 of the 68 schools in the men's March Madness tournament. We can visualize the magnitude of the increase by creating groupings of schools according to how much their average volume changed during the tournament.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use InTournamentDifference to create a percentage difference\nMMVolDiffCat <- MMVolDiffs %>%\n  mutate(InTournamentDifference = case_when(\n      InTournamentDifference < 0 ~ \"Decreased Volume\",\n      InTournamentDifference > 0 & InTournamentDifference <= 100 ~ \"Up to 100% Increase\",\n      InTournamentDifference >= 101 & InTournamentDifference <= 200 ~ \"100%-200% Increase\",\n      InTournamentDifference >= 201 & InTournamentDifference <= 300 ~ \"201%-300% Increase\",\n      InTournamentDifference >= 301 & InTournamentDifference <= 600 ~ \"301%-600% Increase\",\n      InTournamentDifference >= 601 & InTournamentDifference <= 800 ~ \"601%-800% Increase\",\n      InTournamentDifference > 801 ~ \"1000%+ Increase\"))\n\nMMVolDiffCatBD <- MMVolDiffCat %>%\n        group_by(InTournamentDifference) %>%\n        tally() %>%\n  arrange(factor(InTournamentDifference, levels = c(\"Decreased Volume\", \"Up to 100% Increase\", \"100%-200% Increase\", \"201%-300% Increase\", \"301%-600% Increase\", \"601%-800% Increase\", \"1000%+ Increase\")))\n\nMMVolDiffCatBD$InTournamentDifference <- factor(MMVolDiffCatBD$InTournamentDifference, levels = c(\"Decreased Volume\", \"Up to 100% Increase\", \"100%-200% Increase\", \"201%-300% Increase\", \"301%-600% Increase\", \"601%-800% Increase\", \"1000%+ Increase\"))\nggplot(MMVolDiffCatBD, \n       aes(x = InTournamentDifference, y=n)) +\n  geom_bar(stat = \"identity\", fill = \"purple\") +\n  geom_text(aes(label = n), vjust = -0.1) +\n  labs(x = \"\", y = \"Number of Schools\") +\n  ggtitle(\"Number of Schools w/Each Grouping of % Increase/Decrease\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](FPRedoneWithLog_DarronBunt_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nOut of the 68 schools that participated in March Madness, only two experienced a decrease in their average mention volume - the University of Iowa (-6.08%) and Michigan State (-6.32%). These outliers have both experienced significant non-athletic events during 2023 that have also served to increase their mention volume outside of March Madness (a screening of the contentious film \"What is a Woman\" at the University of Iowa and a school shooting on campus at Michigan State). \n\n37 schools experienced an increase in their mention volume of 100-300% while 11 saw a 301-800% increase. Two schools - Furman University and Farleigh Dickinson University - experienced volume increases of over 1,000% (1,121% and 3,800% respectively.)\n\n#### Testing the Hypothesis\n\nMy original hypothesis was that **participation in the men's March Madness tournament increases online conversation about the schools that are involved.**\n\nTo test this hypothesis, I will perform a paired t.test on the average volume during the tournament and outside of the tournament for all of the teams involved.\n\n* Null hypothesis: Participation in the men's March Madness tournament **does not** increase average mention volume for the schools that are involved.\n\n* Alternative hypothesis: Participation in the men's March Madness tournament **does ** increase average mention volume for the schools that are involved.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(MMVolAvgs$VolDuring, MMVolAvgs$VolNonTourn, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  MMVolAvgs$VolDuring and MMVolAvgs$VolNonTourn\nt = 8.1765, df = 67, p-value = 1.157e-11\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 1119.565 1842.700\nsample estimates:\nmean difference \n       1481.132 \n```\n:::\n:::\n\nThe observed mean difference between the paired observations was 1,481 mentions and the 95% confidence interval is 1,120-1,843. We can be 95% certain that the true mean difference lies between this range. \n\nThe magnitude of the t-value (8.18) indicates there is strong evidence against the null hypothesis. Based on the p-value (1.157e-11) we reject the null hypothesis and support the alternative hypothesis that participation in the men's March Madness tournament **does ** increase average mention volume for the schools that are involved. \n\n#### How long does March Madness contribute to changes in online conversation volume?\n\nI was immediately curious how long changes in conversation volume due to March Madness would be considered statistically significant, so I performed t-tests for the average volume one week and two weeks after each team's elimination.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare non-tournament volume to week after and two weeks after tournament ended for each team\nt.test(MMVolAvgs$Vol2WeeksAfter, MMVolAvgs$VolNonTourn, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  MMVolAvgs$Vol2WeeksAfter and MMVolAvgs$VolNonTourn\nt = -2.6328, df = 67, p-value = 0.0105\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -302.18943  -41.57528\nsample estimates:\nmean difference \n      -171.8824 \n```\n:::\n\n```{.r .cell-code}\nt.test(MMVolAvgs$VolWeekAfter, MMVolAvgs$VolNonTourn, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  MMVolAvgs$VolWeekAfter and MMVolAvgs$VolNonTourn\nt = -1.2093, df = 67, p-value = 0.2308\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -225.99467   55.46526\nsample estimates:\nmean difference \n      -85.26471 \n```\n:::\n:::\n\nBased on the p-value for both two weeks after (0.0105) and one week after (0.2308) we fail to reject the null hypothesis - participation in the men's March Madness tournament **does not** increase mention volume for the schools that are involved at either one or two weeks post tournament.\n\nI was then curious whether changes in conversation volume due to March Madness would be considered statistically significant in the days immediately following the tournament, so I performed t-tests comparing those days' volume numbers to each school's average non-tournament volume. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(MMVolAvgs$VolElim_Day, MMVolAvgs$VolNonTourn, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  MMVolAvgs$VolElim_Day and MMVolAvgs$VolNonTourn\nt = 6.7004, df = 67, p-value = 5.187e-09\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 2723.919 5035.346\nsample estimates:\nmean difference \n       3879.632 \n```\n:::\n\n```{.r .cell-code}\nt.test(MMVolAvgs$VolAfterElim, MMVolAvgs$VolNonTourn, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  MMVolAvgs$VolAfterElim and MMVolAvgs$VolNonTourn\nt = 2.3848, df = 67, p-value = 0.01993\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n  230.9917 2602.8318\nsample estimates:\nmean difference \n       1416.912 \n```\n:::\n\n```{.r .cell-code}\nt.test(MMVolAvgs$VolPostElim, MMVolAvgs$VolNonTourn, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  MMVolAvgs$VolPostElim and MMVolAvgs$VolNonTourn\nt = -0.048907, df = 67, p-value = 0.9611\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -283.4630  269.9042\nsample estimates:\nmean difference \n      -6.779412 \n```\n:::\n\n```{.r .cell-code}\nt.test(MMVolAvgs$VolPostElim1, MMVolAvgs$VolNonTourn, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  MMVolAvgs$VolPostElim1 and MMVolAvgs$VolNonTourn\nt = -1.4567, df = 67, p-value = 0.1499\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -334.72775   52.28657\nsample estimates:\nmean difference \n      -141.2206 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data frame with results\nVolTTestResults <- data.frame(\n  \"Time Frame\" = c(\"Elimination Day\", \"Day After Elimination\", \"2 Days After Elimination\", \"3 Days After Elimination\"),\n  t_value = c(6.7004, 2.3848, -0.048907, -1.4567),\n  p_value = c(5.187e-09, 0.01993, 0.9611, 0.1499),\n  Mean_Difference = c(3880, 1417,  -6.8, -141))\nVolTTestResults$p_value <- format(VolTTestResults$p_value, scientific = FALSE)\nVolTTestResults\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                Time.Frame   t_value        p_value Mean_Difference\n1          Elimination Day  6.700400 0.000000005187          3880.0\n2    Day After Elimination  2.384800 0.019930000000          1417.0\n3 2 Days After Elimination -0.048907 0.961100000000            -6.8\n4 3 Days After Elimination -1.456700 0.149900000000          -141.0\n```\n:::\n:::\n\nBased on the p-values for Elimination Day and Day After Elimination, we can reject the null hypothesis - participation in the men's March Madness tournament **does** increase mention volume on those two days. \n\nFor two days and three days post-elimination, however, the p-values (0.96 and 0.15) are higher than 0.05. For these days we fail to reject the null hypothesis - participation in the men's March Madness tournament **does not** increase mention volume for the schools that are involved two and three days post-elimination.\n\nThe observed mean difference for the day of elimination and the day after elimination was 3,880 and 1,417 mentions respectively and the 95% confidence intervals were 2,724-5,035 and 231-2,603 respectively. We can be 95% certain that the true mean difference lies between this range. \n\nTo summarize: Participation in the men's March Madness tournament **does** increase mention volume for schools with teams participating and does so for **the days between the start of the tournament and the day after each team is eliminated**. \n\n# What variables contribute to changes in mention volume during the tournament?\n\nHaving confirmed that participation in the men's March Madness tournament does indeed increase mention volume for schools with teams participating, the next step is to determine what variables contribute to these changes in mention volume. \n\nFor the daily mention outcome variable, I created a data frame with the daily mention volume for each of the 68 schools in March Madness for the two days prior to the tournament beginning, all days in the tournament, and the day after the tournament, for a total time frame of March 12 to April 4, 2023. I then joined together the predictor variable data for each school's daily mention volume during the tournament/on tournament game days. \n\n## Data manipulation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read in data for enrollment \nSchoolNameToSchool <- read_csv(\"_data/SchoolNameToSchool.csv\", show_col_types = FALSE) \nEnrollmentData <- read_csv(\"_data/CCIHE2021PublicData.csv\", show_col_types = FALSE)\nSchoolEnrollmentData <- SchoolNameToSchool %>%\n  left_join(EnrollmentData, by = \"SchoolName\")\n\nVolumeByDay <- MMVolumeNew %>%\n  pivot_longer(cols = -School, names_to = \"Date\", values_to = \"Mention_Volume\") %>%\n  arrange(Date)\n\n# Convert the Date column to the \"YYYY-MM-DD\" format if needed\nVolumeByDay$Date <- as.Date(VolumeByDay$Date, format = \"%m/%d/%Y\")\n\n# Join volume by school and enrollment data for each school\nVolumeAndEnrollment <- VolumeByDay %>%\n  left_join(SchoolEnrollmentData, by = c(\"School\"))\n\n# Narrow down to all days between March 12 and April 4\nMMVolumeByDay <- VolumeByDay %>%\n  filter(Date >= as.Date(\"2023-03-12\") & Date <= as.Date(\"2023-04-04\"))\n\n# Remove unneeded variables from TVariables\nTVariables <- TVariables %>%\n  rename(\"Date\" = \"GameDate\") %>%\n  select(-GameDayVolume, -WinningSeed, -LosingSeed)\n\n# Join volume by school and game-day variables for each school\nTVariables$Date <- as.Date(TVariables$Date)\nMMVolumeByDay$Date <- as.Date(MMVolumeByDay$Date)\nVolumeAndVariables <- MMVolumeByDay %>%\n  left_join(TVariables, by = c(\"School\", \"Date\")) %>%\n  left_join(SchoolEnrollmentData, by = c(\"School\"))\n\nVolumeAndVariables <- VolumeAndVariables %>%\n  mutate(Seed = ifelse(School %in% TVariables$School, TVariables$Seed, NA))\n\n# Read in data\nAddMajor <- read_csv(\"_data/DateRoundTeamSeedMajor.csv\", show_col_types = FALSE) %>%\n  select(School, Major)\n# Find matching indices\nmatching_indices <- match(VolumeAndVariables$School, AddMajor$School)\nVolumeAndVariables$Major <- ifelse(!is.na(matching_indices), AddMajor$Major[matching_indices], NA)\n\n# Add EndDate column to VolumeAndVariables\nMMVolVarJustEndDate <- MMVolumeVar %>%\n  select(School, EndDate)\nVolumeAndVariables <- VolumeAndVariables %>%\n  left_join(MMVolVarJustEndDate, by = \"School\")\n\n# Create column for DayAfterGame\nDateRoundTeam2 <- DateRoundTeam %>%\n  rename(Date = GameDate) %>%\n  mutate(DayAfterGame = as.Date(Date + 1)) %>%\n  select(School, Date, DayAfterGame)\n\n# Join to dataset\nVolumeAndVariables <- VolumeAndVariables %>%\n  left_join(DateRoundTeam2, by = c(\"School\", \"Date\")) %>%\nmutate(\n    IsMarchMadness = ifelse(Date >= as.Date(\"2023-03-12\") & Date <= EndDate, 1, 0),\n    IsGameDay = ifelse(is.na(Time), 0, 1)) %>%\n  mutate(\n    NextRow = if_else(!is.na(DayAfterGame), row_number() + 1, NA_integer_),\n    IsDayAfterGame = if_else(row_number() %in% NextRow & !is.na(NextRow), 1, 0)) %>%\n  mutate(\n    IsDayAfterGame = replace(IsDayAfterGame, NextRow, 1),\n    GDayOrAfter = ifelse(IsGameDay == 1 | IsDayAfterGame == 1, 1, 0)) %>%\n    ungroup() %>%\n  mutate(\n    IsWinner = ifelse(is.na(IsWinner), \"No\", IsWinner),\n    UpsetWin = ifelse(is.na(UpsetWin), \"No\", UpsetWin), \n    UpsetLoss = ifelse(is.na(UpsetLoss), \"No\", UpsetLoss),\n    FavoriteWin = ifelse(is.na(FavoriteWin), \"No\", FavoriteWin),\n    FavoriteLoss = ifelse(is.na(FavoriteLoss),  \"No\", FavoriteLoss),\n    UnderdogWin = ifelse(is.na(UnderdogWin), \"No\", UnderdogWin),\n    UnderdogLoss = ifelse(is.na(UnderdogLoss), \"No\", UnderdogLoss),\n    SeedDifference = abs(SeedDifference),\n    SeedDifference = ifelse(is.na(SeedDifference), \"Not March Madness\", SeedDifference),\n   TournamentRound = fct_na_value_to_level(as.factor(TournamentRound), \"Not March Madness\"),\n    Time = fct_na_value_to_level(as.factor(Time), \"Not March Madness\"),\n    SizeSetting = as.factor(SizeSetting),\n    Control = as.factor(Control),\n    Seed = ifelse(is.na(Seed), \"Not March Madness\", Seed)) %>%\n  select(Date, School, Mention_Volume, Seed, Time, TournamentRound, IsWinner, SeedDifference, UpsetWin, UpsetLoss, FavoriteWin, FavoriteLoss, UnderdogWin, UnderdogLoss, SizeSetting, Control, F20Enrollment, Major, IsMarchMadness, IsGameDay, IsDayAfterGame, GDayOrAfter)\n\nVolumeAndVariables\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,632 × 22\n   Date       School         Mention_Volume  Seed Time  TournamentRound IsWinner\n   <date>     <chr>                   <dbl> <dbl> <fct> <fct>           <chr>   \n 1 2023-03-12 University of…            786    11 Not … Not March Madn… No      \n 2 2023-03-12 University of…           1532    16 Not … Not March Madn… No      \n 3 2023-03-12 Arizona State…           2664    11 Not … Not March Madn… No      \n 4 2023-03-12 Duke Universi…           8882    16 Not … Not March Madn… No      \n 5 2023-03-12 Utah State Un…            638    15 Not … Not March Madn… No      \n 6 2023-03-12 University of…           3980    13 Not … Not March Madn… No      \n 7 2023-03-12 North Carolin…           2181    10 Not … Not March Madn… No      \n 8 2023-03-12 University of…           1476     9 Not … Not March Madn… No      \n 9 2023-03-12 Providence Co…           1012     8 Not … Not March Madn… No      \n10 2023-03-12 Xavier Univer…            801     8 Not … Not March Madn… No      \n# ℹ 1,622 more rows\n# ℹ 15 more variables: SeedDifference <chr>, UpsetWin <chr>, UpsetLoss <chr>,\n#   FavoriteWin <chr>, FavoriteLoss <chr>, UnderdogWin <chr>,\n#   UnderdogLoss <chr>, SizeSetting <fct>, Control <fct>, F20Enrollment <dbl>,\n#   Major <chr>, IsMarchMadness <dbl>, IsGameDay <dbl>, IsDayAfterGame <dbl>,\n#   GDayOrAfter <dbl>\n```\n:::\n:::\n\n\n## Model 1 - Participation in March Madness \n\nThere is one independent variable to be considered in this section - whether the day's mention volume is from a day when the school was not yet eliminated from the tournament (1 - Yes, 2 - No).  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run linear regression with NonTournProp and IsMarchMadness\nIsMarchMadnessLR <- lm(Mention_Volume ~ IsMarchMadness, data = VolumeAndVariables)\nsummary(IsMarchMadnessLR)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness, data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -2787   -682   -428    339  37243 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      720.54      80.47   8.954   <2e-16 ***\nIsMarchMadness  2150.27     130.13  16.524   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2555 on 1630 degrees of freedom\nMultiple R-squared:  0.1435,\tAdjusted R-squared:  0.1429 \nF-statistic:   273 on 1 and 1630 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nWhile linear regression does indeed demonstrate a statistically significant relationship between IsMarchMadness and mention volume, a scatterplot comparing the two variables shows large cluster of values, followed by a long tail indicating outliers on the high end of mention volume.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scatterplot of IsMarchMadness vs. (Mention_Volume)\nplot(VolumeAndVariables$IsMarchMadness, VolumeAndVariables$Mention_Volume, \n     xlab = \"IsMarchMadness\", ylab = \"Mention Volume\", \n     main = \"Scatterplot of IsMarchMadness vs. Mention Volume\")\n```\n\n::: {.cell-output-display}\n![](FPRedoneWithLog_DarronBunt_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\nWhereas if I plot IsMarchMadness against the log of Mention_Volume, this reduces the skew and makes the data more symmetric.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scatterplot of IsMarchMadness vs. log(Mention_Volume)\nplot(VolumeAndVariables$IsMarchMadness, log(VolumeAndVariables$Mention_Volume), \n     xlab = \"IsMarchMadness\", ylab = \"log(Mention Volume)\", \n     main = \"Scatterplot of IsMarchMadness vs. log(Mention Volume)\") \n```\n\n::: {.cell-output-display}\n![](FPRedoneWithLog_DarronBunt_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run linear regression with MentionVolume and log(IsMarchMadness)\nIsMarchMadnessLRlog <- lm(log(Mention_Volume) ~ IsMarchMadness, data = VolumeAndVariables)\nsummary(IsMarchMadnesslog)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'IsMarchMadnesslog' not found\n```\n:::\n:::\n\nUsing the log transformed dependent variable has a much higher r squared (0.2491) vs. the model using the original dependent variable (0.1395). \n\nAccordingly, I am going to use test using the log transformed version of Mention_Volume and the original version in all of my other models. \n\n## Model 2 - Game Outcome Related Variables\n\n* Win/Loss (IsWinner - Yes, No, Not March Madness)\n* Did the favorite win? (FavoriteWin - Yes, No, Not March Madness)\n* Did the favorite lose? (FavoriteLoss - Yes, No, Not March Madness)\n* Did the underdog win? (UnderdogWin - Yes, No, Not March Madness)\n* Did underdog lose (UnderdogLose - Yes, No, Not March Madness)\n* Is this an upset win? (UpsetWin - Yes, No, Not March Madness)\n* Is this an upset loss? (UpsetLoss - Yes, No, Not March Madness)\n  \n### Win/Loss\n\nThis category is relatively self-explanatory - does the result of the game (win or loss) have an impact on mention volume.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression for IsWinner\nsummary(lm(Mention_Volume ~ IsMarchMadness + IsWinner, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + IsWinner, data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -7435   -669   -388    391  37855 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      720.54      72.78    9.90   <2e-16 ***\nIsMarchMadness  1538.60     121.99   12.61   <2e-16 ***\nIsWinnerYes     5696.69     298.79   19.07   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2311 on 1629 degrees of freedom\nMultiple R-squared:  0.2997,\tAdjusted R-squared:  0.2989 \nF-statistic: 348.6 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + IsWinner, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + IsWinner, \n    data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5531 -0.8947  0.0863  0.8877  3.3890 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     5.95095    0.03607 164.990   <2e-16 ***\nIsMarchMadness  1.25949    0.06046  20.832   <2e-16 ***\nIsWinnerYes     1.41941    0.14808   9.586   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.145 on 1629 degrees of freedom\nMultiple R-squared:  0.2938,\tAdjusted R-squared:  0.293 \nF-statistic: 338.9 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nWinning the game **is** a statistically significant predictor variable.\n\n### Favorite Win/Loss\n\nThe favorite in a game is the team that has a higher seed. Here we will consider whether the favorite in the game winning, the favorite in the game losing, and both variables together had a statistically significant impact on mention volume.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Mention_Volume ~ IsMarchMadness + FavoriteWin, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + FavoriteWin, data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -8848   -672   -410    356  37490 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      720.54      75.78   9.508   <2e-16 ***\nIsMarchMadness  1903.57     123.73  15.384   <2e-16 ***\nFavoriteWinYes  8102.16     560.55  14.454   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2406 on 1629 degrees of freedom\nMultiple R-squared:  0.2408,\tAdjusted R-squared:  0.2399 \nF-statistic: 258.4 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + FavoriteWin, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + FavoriteWin, \n    data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5531 -0.9075  0.0774  0.8943  3.2894 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     5.95095    0.03661 162.528  < 2e-16 ***\nIsMarchMadness  1.35915    0.05979  22.734  < 2e-16 ***\nFavoriteWinYes  1.73238    0.27085   6.396 2.08e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.162 on 1629 degrees of freedom\nMultiple R-squared:  0.2723,\tAdjusted R-squared:  0.2714 \nF-statistic: 304.7 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression for favorite win\nFaveWin <- (lm(Mention_Volume ~ IsMarchMadness + FavoriteWin, data = VolumeAndVariables))\nFaveWinlog <- (lm(log(Mention_Volume) ~ IsMarchMadness + FavoriteWin, data = VolumeAndVariables))\n\n# Linear regression for favorite loss\nFaveLoss <- (lm(Mention_Volume ~ IsMarchMadness + FavoriteLoss, data = VolumeAndVariables))\nFaveLosslog <- (lm(log(Mention_Volume) ~ IsMarchMadness + FavoriteLoss, data = VolumeAndVariables))\n\n# Linear regression for both favorite win and loss\nFaveWinOrLoss <- (lm(Mention_Volume ~ IsMarchMadness + FavoriteWin + FavoriteLoss, data = VolumeAndVariables))\nFaveWinOrLosslog <- (lm(log(Mention_Volume) ~ IsMarchMadness + FavoriteWin + FavoriteLoss, data = VolumeAndVariables))\n\nstargazer(FaveWin, FaveLoss, FaveWinOrLoss, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=================================================================================================\n                                                 Dependent variable:                             \n                    -----------------------------------------------------------------------------\n                                                   Mention_Volume                                \n                               (1)                       (2)                       (3)           \n-------------------------------------------------------------------------------------------------\nIsMarchMadness            1,903.568***              2,036.239***              1,777.843***       \n                            (123.734)                 (129.823)                 (123.048)        \n                                                                                                 \nFavoriteWinYes            8,102.157***                                        8,227.883***       \n                            (560.552)                                           (552.157)        \n                                                                                                 \nFavoriteLossYes                                     3,744.960***              4,003.356***       \n                                                      (588.138)                 (552.157)        \n                                                                                                 \nConstant                   720.538***                720.538***                720.538***        \n                            (75.779)                  (79.508)                  (74.607)         \n                                                                                                 \n-------------------------------------------------------------------------------------------------\nObservations                  1,632                     1,632                     1,632          \nR2                            0.241                     0.164                     0.265          \nAdjusted R2                   0.240                     0.163                     0.263          \nResidual Std. Error   2,405.903 (df = 1629)     2,524.305 (df = 1629)     2,368.703 (df = 1628)  \nF Statistic         258.388*** (df = 2; 1629) 160.101*** (df = 2; 1629) 195.234*** (df = 3; 1628)\n=================================================================================================\nNote:                                                                 *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n\n```{.r .cell-code}\nstargazer(FaveWinlog, FaveLosslog, FaveWinOrLosslog, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=================================================================================================\n                                                 Dependent variable:                             \n                    -----------------------------------------------------------------------------\n                                                 log(Mention_Volume)                             \n                               (1)                       (2)                       (3)           \n-------------------------------------------------------------------------------------------------\nIsMarchMadness              1.359***                  1.374***                  1.318***         \n                             (0.060)                   (0.060)                   (0.060)         \n                                                                                                 \nFavoriteWinYes              1.732***                                            1.773***         \n                             (0.271)                                             (0.269)         \n                                                                                                 \nFavoriteLossYes                                       1.252***                  1.307***         \n                                                       (0.272)                   (0.269)         \n                                                                                                 \nConstant                    5.951***                  5.951***                  5.951***         \n                             (0.037)                   (0.037)                   (0.036)         \n                                                                                                 \n-------------------------------------------------------------------------------------------------\nObservations                  1,632                     1,632                     1,632          \nR2                            0.272                     0.264                     0.283          \nAdjusted R2                   0.271                     0.263                     0.281          \nResidual Std. Error     1.162 (df = 1629)         1.169 (df = 1629)         1.155 (df = 1628)    \nF Statistic         304.721*** (df = 2; 1629) 291.442*** (df = 2; 1629) 213.829*** (df = 3; 1628)\n=================================================================================================\nNote:                                                                 *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\nBoth the favorite winning and the favorite losing **are** statistically significant predictor variables.\n\n### Underdog Win/Loss\n\nThe favorite in a game is the team that has a lower seed. Here we will consider whether the underdog in the game winning, the underdog in the game losing, and both variables had a statistically significant impact on mention volume.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression for underdog win\nUnderWin <- (lm(Mention_Volume ~ IsMarchMadness + UnderdogWin, data = VolumeAndVariables))\nUnderWinlog <- (lm(log(Mention_Volume) ~ IsMarchMadness + UnderdogWin, data = VolumeAndVariables))\n\n# Linear regression for underdog loss\nUnderLoss <- (lm(Mention_Volume ~ IsMarchMadness + UnderdogLoss, data = VolumeAndVariables))\nUnderLosslog <- (lm(log(Mention_Volume) ~ IsMarchMadness + UnderdogLoss, data = VolumeAndVariables))\n\n# Linear regression for both underdog win and loss\nUnderWinAndLoss <- (lm(Mention_Volume ~ IsMarchMadness + UnderdogWin + UnderdogLoss, data = VolumeAndVariables))\nUnderWinAndLosslog <- (lm(log(Mention_Volume) ~ IsMarchMadness + UnderdogWin + UnderdogLoss, data = VolumeAndVariables))\n\nstargazer(UnderWin, UnderLoss, UnderWinAndLoss, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=================================================================================================\n                                                 Dependent variable:                             \n                    -----------------------------------------------------------------------------\n                                                   Mention_Volume                                \n                               (1)                       (2)                       (3)           \n-------------------------------------------------------------------------------------------------\nIsMarchMadness            1,819.167***              2,083.666***              1,719.918***       \n                            (127.417)                 (132.958)                 (130.267)        \n                                                                                                 \nUnderdogWinYes            4,695.613***                                        4,794.863***       \n                            (382.296)                                           (382.145)        \n                                                                                                 \nUnderdogLossYes                                       944.547**               1,308.295***       \n                                                      (398.920)                 (382.145)        \n                                                                                                 \nConstant                   720.538***                720.538***                720.538***        \n                            (77.005)                  (80.353)                  (76.753)         \n                                                                                                 \n-------------------------------------------------------------------------------------------------\nObservations                  1,632                     1,632                     1,632          \nR2                            0.216                     0.146                     0.222          \nAdjusted R2                   0.215                     0.145                     0.220          \nResidual Std. Error   2,444.823 (df = 1629)     2,551.140 (df = 1629)     2,436.817 (df = 1628)  \nF Statistic         224.500*** (df = 2; 1629) 139.706*** (df = 2; 1629) 154.559*** (df = 3; 1628)\n=================================================================================================\nNote:                                                                 *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n\n```{.r .cell-code}\nstargazer(UnderWinlog, UnderLosslog, UnderWinAndLosslog, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=================================================================================================\n                                                 Dependent variable:                             \n                    -----------------------------------------------------------------------------\n                                                 log(Mention_Volume)                             \n                               (1)                       (2)                       (3)           \n-------------------------------------------------------------------------------------------------\nIsMarchMadness              1.322***                  1.375***                  1.275***         \n                             (0.060)                   (0.061)                   (0.062)         \n                                                                                                 \nUnderdogWinYes              1.272***                                            1.319***         \n                             (0.181)                                             (0.181)         \n                                                                                                 \nUnderdogLossYes                                       0.522***                  0.622***         \n                                                       (0.184)                   (0.181)         \n                                                                                                 \nConstant                    5.951***                  5.951***                  5.951***         \n                             (0.037)                   (0.037)                   (0.036)         \n                                                                                                 \n-------------------------------------------------------------------------------------------------\nObservations                  1,632                     1,632                     1,632          \nR2                            0.276                     0.258                     0.281          \nAdjusted R2                   0.275                     0.257                     0.280          \nResidual Std. Error     1.160 (df = 1629)         1.174 (df = 1629)         1.156 (df = 1628)    \nF Statistic         310.261*** (df = 2; 1629) 282.726*** (df = 2; 1629) 212.140*** (df = 3; 1628)\n=================================================================================================\nNote:                                                                 *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\nBoth the underdog winning and the underdog losing **are** statistically significant predictor variables. However, when I ran them together, the underdog losing had a significant impact on mention volume while the underdog winning did not.\n\n### Is Upset \n\nA game is considered an upset when a team ranked five or more seeds lower than the team they are playing wins the game. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add IsUpset column\nVolumeAndVariables <- VolumeAndVariables %>%\n  mutate(IsUpset = ifelse(UpsetWin == \"Yes\" | UpsetLoss == \"Yes\", \"Yes\", \"No\"))\n\n# Linear Regression for IsUpset\nIsUpset <- (lm(Mention_Volume ~ IsMarchMadness + IsUpset, data = VolumeAndVariables))\nIsUpsetlog <- (lm(log(Mention_Volume) ~ IsMarchMadness + IsUpset, data = VolumeAndVariables))\n\n# Linear Regression for UpsetWin\nUpsetWin <- (lm(Mention_Volume ~ IsMarchMadness + UpsetWin, data = VolumeAndVariables))\nUpsetWinlog <- (lm(log(Mention_Volume) ~ IsMarchMadness + UpsetWin, data = VolumeAndVariables))\n\n# Linear Regression for UpsetLoss\nUpsetLoss <- (lm(Mention_Volume ~ IsMarchMadness + UpsetLoss, data = VolumeAndVariables))\nUpsetLosslog <- (lm(log(Mention_Volume) ~ IsMarchMadness + UpsetLoss, data = VolumeAndVariables))\n\n# Linear Regression for UpsetWin and UpsetLoss\nUpsetWinAndLoss <- (lm(Mention_Volume ~ IsMarchMadness + UpsetWin + UpsetLoss, data = VolumeAndVariables))\nUpsetWinAndLosslog <- (lm(log(Mention_Volume) ~ IsMarchMadness + UpsetWin + UpsetLoss, data = VolumeAndVariables))\n\nstargazer(IsUpset, UpsetWin, UpsetLoss, UpsetWinAndLoss, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n===========================================================================================================================\n                                                              Dependent variable:                                          \n                    -------------------------------------------------------------------------------------------------------\n                                                                Mention_Volume                                             \n                               (1)                       (2)                       (3)                       (4)           \n---------------------------------------------------------------------------------------------------------------------------\nIsMarchMadness            1,934.834***              2,001.561***              2,086.693***              1,934.834***       \n                            (125.196)                 (124.830)                 (129.696)                 (124.244)        \n                                                                                                                           \nIsUpsetYes                7,468.406***                                                                                     \n                            (582.541)                                                                                      \n                                                                                                                           \nUpsetWinYes                                         10,310.340***                                       10,377.070***      \n                                                      (819.144)                                           (811.654)        \n                                                                                                                           \nUpsetLossYes                                                                  4,407.880***              4,559.740***       \n                                                                                (851.074)                 (811.654)        \n                                                                                                                           \nConstant                   720.538***                720.538***                720.538***                720.538***        \n                            (76.714)                  (76.842)                  (79.837)                  (76.131)         \n                                                                                                                           \n---------------------------------------------------------------------------------------------------------------------------\nObservations                  1,632                     1,632                     1,632                     1,632          \nR2                            0.222                     0.219                     0.157                     0.234          \nAdjusted R2                   0.221                     0.218                     0.156                     0.233          \nResidual Std. Error   2,435.604 (df = 1629)     2,439.646 (df = 1629)     2,534.742 (df = 1629)     2,417.079 (df = 1628)  \nF Statistic         232.380*** (df = 2; 1629) 228.915*** (df = 2; 1629) 152.092*** (df = 2; 1629) 165.993*** (df = 3; 1628)\n===========================================================================================================================\nNote:                                                                                           *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n\n```{.r .cell-code}\nstargazer(IsUpsetlog, UpsetWinlog, UpsetLosslog, UpsetWinAndLosslog, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n===========================================================================================================================\n                                                              Dependent variable:                                          \n                    -------------------------------------------------------------------------------------------------------\n                                                              log(Mention_Volume)                                          \n                               (1)                       (2)                       (3)                       (4)           \n---------------------------------------------------------------------------------------------------------------------------\nIsMarchMadness              1.362***                  1.383***                  1.392***                  1.362***         \n                             (0.060)                   (0.060)                   (0.060)                   (0.060)         \n                                                                                                                           \nIsUpsetYes                  1.736***                                                                                       \n                             (0.278)                                                                                       \n                                                                                                                           \nUpsetWinYes                                           2.018***                                            2.039***         \n                                                       (0.392)                                             (0.391)         \n                                                                                                                           \nUpsetLossYes                                                                    1.402***                  1.432***         \n                                                                                 (0.394)                   (0.391)         \n                                                                                                                           \nConstant                    5.951***                  5.951***                  5.951***                  5.951***         \n                             (0.037)                   (0.037)                   (0.037)                   (0.037)         \n                                                                                                                           \n---------------------------------------------------------------------------------------------------------------------------\nObservations                  1,632                     1,632                     1,632                     1,632          \nR2                            0.271                     0.266                     0.260                     0.272          \nAdjusted R2                   0.270                     0.265                     0.259                     0.271          \nResidual Std. Error     1.163 (df = 1629)         1.168 (df = 1629)         1.172 (df = 1629)         1.163 (df = 1628)    \nF Statistic         303.386*** (df = 2; 1629) 295.067*** (df = 2; 1629) 285.804*** (df = 2; 1629) 202.694*** (df = 3; 1628)\n===========================================================================================================================\nNote:                                                                                           *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\nBoth the an upset win and an upset loss **are** statistically significant predictor variables.\n\n### Testing All of the Game Outcome-Related Variables Together\n\nI will test the game outcome-related variables together using both the Mention_Volume predictor variable and the log transformed version. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Mention_Volume ~ IsMarchMadness + IsWinner + UpsetWin + UpsetLoss + FavoriteWin + FavoriteLoss + UnderdogWin + UnderdogLoss, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + IsWinner + UpsetWin + \n    UpsetLoss + FavoriteWin + FavoriteLoss + UnderdogWin + UnderdogLoss, \n    data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -7306   -661   -386    398  38151 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       720.54      69.21  10.411  < 2e-16 ***\nIsMarchMadness   1242.75     120.69  10.297  < 2e-16 ***\nIsWinnerYes       758.71    1103.15   0.688    0.492    \nUpsetWinYes      4381.74    1009.65   4.340 1.51e-05 ***\nUpsetLossYes     1355.41    1009.65   1.342    0.180    \nFavoriteWinYes   5928.70    1300.01   4.560 5.49e-06 ***\nFavoriteLossYes  3896.41     701.88   5.551 3.31e-08 ***\nUnderdogWinYes   4513.32    1147.57   3.933 8.74e-05 ***\nUnderdogLossYes  1785.46     345.71   5.165 2.71e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2197 on 1623 degrees of freedom\nMultiple R-squared:  0.369,\tAdjusted R-squared:  0.3659 \nF-statistic: 118.7 on 8 and 1623 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nWhen combining all the game-related variables together, IsWinnerYes and UpsetLossYes were no longer statistically significant. IsWinnerYes had the highest p-value, so I will remove it first and run the model again. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Mention_Volume ~ IsMarchMadness + UpsetWin + UpsetLoss + FavoriteWin + FavoriteLoss + UnderdogWin + UnderdogLoss, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + UpsetWin + UpsetLoss + \n    FavoriteWin + FavoriteLoss + UnderdogWin + UnderdogLoss, \n    data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -7306   -660   -384    397  38145 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        720.5       69.2  10.412  < 2e-16 ***\nIsMarchMadness    1248.8      120.3  10.378  < 2e-16 ***\nUpsetWinYes       4381.7     1009.5   4.341 1.51e-05 ***\nUpsetLossYes      1355.4     1009.5   1.343     0.18    \nFavoriteWinYes    6681.3      701.7   9.521  < 2e-16 ***\nFavoriteLossYes   3890.3      701.7   5.544 3.44e-08 ***\nUnderdogWinYes    5265.9      345.5  15.240  < 2e-16 ***\nUnderdogLossYes   1779.4      345.5   5.149 2.93e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2197 on 1624 degrees of freedom\nMultiple R-squared:  0.3689,\tAdjusted R-squared:  0.3661 \nF-statistic: 135.6 on 7 and 1624 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nUpsetLoss is still not statistically significant, so I will run the model again without it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGameOutcomeLR <- lm(Mention_Volume ~ IsMarchMadness + UpsetWin + FavoriteWin + FavoriteLoss + UnderdogWin + UnderdogLoss, data = VolumeAndVariables)\nsummary(GameOutcomeLR)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + UpsetWin + FavoriteWin + \n    FavoriteLoss + UnderdogWin + UnderdogLoss, data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -7306   -660   -383    398  38145 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       720.54      69.22  10.410  < 2e-16 ***\nIsMarchMadness   1248.84     120.37  10.375  < 2e-16 ***\nUpsetWinYes      4381.74    1009.73   4.340 1.52e-05 ***\nFavoriteWinYes   6681.32     701.89   9.519  < 2e-16 ***\nFavoriteLossYes  4532.36     513.69   8.823  < 2e-16 ***\nUnderdogWinYes   5265.94     345.63  15.236  < 2e-16 ***\nUnderdogLossYes  1779.37     345.63   5.148 2.95e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2198 on 1625 degrees of freedom\nMultiple R-squared:  0.3682,\tAdjusted R-squared:  0.3658 \nF-statistic: 157.8 on 6 and 1625 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nWhen it comes to game outcome-related variables and Mention_Volume, UpsetWin, FavoriteWin, FavoriteLoss, UnderdogWin, and UnderdogLoss all had a statistically significant impact on March Madness mention volume.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For log(Mention_Volume)\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + IsWinner + UpsetWin + UpsetLoss + FavoriteWin + FavoriteLoss + UnderdogWin + UnderdogLoss, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + IsWinner + \n    UpsetWin + UpsetLoss + FavoriteWin + FavoriteLoss + UnderdogWin + \n    UnderdogLoss, data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5531 -0.8526  0.0646  0.8850  3.4984 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      5.95095    0.03555 167.417  < 2e-16 ***\nIsMarchMadness   1.15015    0.06198  18.556  < 2e-16 ***\nIsWinnerYes      0.50475    0.56655   0.891 0.373110    \nUpsetWinYes      0.58808    0.51853   1.134 0.256910    \nUpsetLossYes     0.32011    0.51853   0.617 0.537101    \nFavoriteWinYes   1.15807    0.66765   1.735 0.083013 .  \nFavoriteLossYes  1.32353    0.36047   3.672 0.000249 ***\nUnderdogWinYes   0.93893    0.58936   1.593 0.111327    \nUnderdogLossYes  0.74721    0.17755   4.208 2.71e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.129 on 1623 degrees of freedom\nMultiple R-squared:  0.3167,\tAdjusted R-squared:  0.3133 \nF-statistic: 94.02 on 8 and 1623 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# For log(Mention_Volume)\nGameOutcomeLRlog <- lm(log(Mention_Volume) ~ IsMarchMadness + FavoriteWin + FavoriteLoss + UnderdogWin + UnderdogLoss, data = VolumeAndVariables)\nsummary(GameOutcomeLRlog)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + FavoriteWin + \n    FavoriteLoss + UnderdogWin + UnderdogLoss, data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5531 -0.8668  0.0745  0.8872  3.4943 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      5.95095    0.03554 167.445  < 2e-16 ***\nIsMarchMadness   1.15420    0.06180  18.675  < 2e-16 ***\nFavoriteWinYes   1.93732    0.26375   7.345 3.24e-13 ***\nFavoriteLossYes  1.47110    0.26375   5.578 2.85e-08 ***\nUnderdogWinYes   1.43962    0.17746   8.112 9.69e-16 ***\nUnderdogLossYes  0.74316    0.17746   4.188 2.97e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.128 on 1626 degrees of freedom\nMultiple R-squared:  0.3156,\tAdjusted R-squared:  0.3135 \nF-statistic:   150 on 5 and 1626 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nWhen it comes to modeling game-related outcomes, the statistically significant variables were slightly different when using Mention_Volume vs. log(Mention_Volume); namely, in the log(Mention_Volume) version, UpsetWin was no longer a statistically significant predictor variable. \n\nThe r squared for the non-transformed version of Mention_Volume was higher (0.3658) compared to the log (0.3135), suggesting that the non-transformed Mention_Volume is a better fit for modeling.\n\n## Model 3 - Tournament Related Variables\n\n* Round of the tournament (8 - First4, RoundOf64, RoundOf32, Sweet16, Elite8, Final4, Championship, Not in Tournament)\n* What Seed each team was (16 - 1 through 16)\n  + Absolute difference in seeding between teams in game (0-15)\n* Time slot the game was played during (5 - LateEve, EarlyEve, LateAft, MidAft, EarlyAft)\n* Is Game Day (Yes/No)\n\n### Tournament Round\n\nThere are seven rounds in March Madness - First Four (play-in to determine the final eight teams in the round of 64), Round of 64, Round of 32, Sweet 16, Elite 8, Final 4, and the Championship. I have an eighth category for \"Not in Tournament\" for teams that have been eliminated from competition. \n\nI will create dummy variables for each round as \"not in tournament\" will be multicollinear with IsMarchMadness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make new TournamentRound column\nVolumeAndVariables <- VolumeAndVariables %>%\n  mutate(\n    TournamentRoundNew = case_when(\n      IsMarchMadness == 1 & IsWinner == \"Yes\" & Date >= as.Date(\"2023-03-12\") & Date <= as.Date(\"2023-03-15\") ~ \"First 4\",\n      IsMarchMadness == 1 & IsWinner == \"No\" & Date >= as.Date(\"2023-03-12\") & Date <= as.Date(\"2023-03-16\") ~ \"First 4\",\n      IsMarchMadness == 1 & IsWinner == \"Yes\" & Date >= as.Date(\"2023-03-16\") & Date <= as.Date(\"2023-03-17\") ~ \"Round of 64\",\n      IsMarchMadness == 1 & IsWinner == \"No\" & Date >= as.Date(\"2023-03-16\") & Date <= as.Date(\"2023-03-18\") ~ \"Round of 64\",\n      IsMarchMadness == 1 & Date >= as.Date(\"2023-03-18\") & Date <= as.Date(\"2023-03-20\") ~ \"Round of 32\",\n      IsMarchMadness == 1 & IsWinner == \"Yes\" & Date >= as.Date(\"2023-03-23\") & Date <= as.Date(\"2023-03-24\") ~ \"Sweet 16\",\n      IsMarchMadness == 1 & IsWinner == \"No\" & Date >= as.Date(\"2023-03-23\") & Date <= as.Date(\"2023-03-25\") ~ \"Sweet 16\",\n      IsMarchMadness == 1 & Date >= as.Date(\"2023-03-25\") & Date <= as.Date(\"2023-03-27\") ~ \"Elite 8\",\n      IsMarchMadness == 1 & Date >= as.Date(\"2023-04-01\") & Date <= as.Date(\"2023-04-02\") ~ \"Final 4\",\n      IsMarchMadness == 1 & Date >= as.Date(\"2023-04-03\") & Date <= as.Date(\"2023-04-04\") ~ \"Championship\",\n      IsMarchMadness == 0 ~ \"Not In Tournament\"))\n\n# Create dummy variables for each round\nVolumeAndVariables <- VolumeAndVariables %>%\nmutate(\nIsFirst4 = ifelse(TournamentRoundNew ==\"First 4\", 1, 0),\nIsRd64 = ifelse(TournamentRoundNew == \"Round of 64\", 1, 0),\nIsRd32 = ifelse(TournamentRoundNew == \"Round of 32\", 1, 0),\nIsRd16 = ifelse(TournamentRoundNew == \"Sweet 16\", 1, 0),\nIsRd8 = ifelse(TournamentRoundNew == \"Elite 8\", 1, 0),\nIsRd4 = ifelse(TournamentRoundNew == \"Final 4\", 1, 0),\nIsChamp = ifelse(TournamentRoundNew == \"Championship\", 1, 0))\n\nMMDaysTournamentRound <- VolumeAndVariables %>%\n  select(Mention_Volume, IsMarchMadness, IsFirst4, IsRd64, IsRd32, IsRd16, IsRd8, IsRd4, IsChamp)\n\n# Linear regression for tournament round\nsummary(lm(Mention_Volume ~ ., data = MMDaysTournamentRound))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ ., data = MMDaysTournamentRound)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14604.5   -640.5   -368.0    402.0  20132.5 \n\nCoefficients: (1 not defined because of singularities)\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       720.5       62.5   11.53   <2e-16 ***\nIsMarchMadness  24136.0      994.1   24.28   <2e-16 ***\nIsFirst4       -23419.2      998.3  -23.46   <2e-16 ***\nIsRd64         -21908.0     1008.5  -21.72   <2e-16 ***\nIsRd32         -20473.0     1022.7  -20.02   <2e-16 ***\nIsRd16         -18959.4     1038.3  -18.26   <2e-16 ***\nIsRd8          -16179.4     1109.2  -14.59   <2e-16 ***\nIsRd4          -12657.6     1215.1  -10.42   <2e-16 ***\nIsChamp              NA         NA      NA       NA    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1984 on 1576 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.497,\tAdjusted R-squared:  0.4948 \nF-statistic: 222.4 on 7 and 1576 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThe IsChamp coefficient was not defined due to singularities; I will run linear regression again with this variable on its own, and for all of the rounds except the championship round. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Mention_Volume ~ IsChamp, data = MMDaysTournamentRound))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsChamp, data = MMDaysTournamentRound)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14604.5  -1212.7   -717.0    103.5  25757.5 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1460.49      63.73   22.92   <2e-16 ***\nIsChamp     23396.01    1268.24   18.45   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2533 on 1582 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.177,\tAdjusted R-squared:  0.1765 \nF-statistic: 340.3 on 1 and 1582 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsChamp, data = MMDaysTournamentRound))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsChamp, data = MMDaysTournamentRound)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.0504 -0.9348  0.1631  0.9045  3.7634 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  6.44828    0.03405 189.394  < 2e-16 ***\nIsChamp      3.54487    0.67752   5.232  1.9e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.353 on 1582 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.01701,\tAdjusted R-squared:  0.01639 \nF-statistic: 27.37 on 1 and 1582 DF,  p-value: 1.9e-07\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(Mention_Volume ~ .-IsChamp, data = MMDaysTournamentRound))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ . - IsChamp, data = MMDaysTournamentRound)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14604.5   -640.5   -368.0    402.0  20132.5 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       720.5       62.5   11.53   <2e-16 ***\nIsMarchMadness  24136.0      994.1   24.28   <2e-16 ***\nIsFirst4       -23419.2      998.3  -23.46   <2e-16 ***\nIsRd64         -21908.0     1008.5  -21.72   <2e-16 ***\nIsRd32         -20473.0     1022.7  -20.02   <2e-16 ***\nIsRd16         -18959.4     1038.3  -18.26   <2e-16 ***\nIsRd8          -16179.4     1109.2  -14.59   <2e-16 ***\nIsRd4          -12657.6     1215.1  -10.42   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1984 on 1576 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.497,\tAdjusted R-squared:  0.4948 \nF-statistic: 222.4 on 7 and 1576 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ .-IsChamp, data = MMDaysTournamentRound))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ . - IsChamp, data = MMDaysTournamentRound)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5531 -0.8450  0.0987  0.8922  2.9509 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     5.95095    0.03548 167.747  < 2e-16 ***\nIsMarchMadness  4.04219    0.56428   7.163 1.20e-12 ***\nIsFirst4       -3.12992    0.56665  -5.524 3.88e-08 ***\nIsRd64         -2.46016    0.57247  -4.297 1.83e-05 ***\nIsRd32         -2.03323    0.58049  -3.503 0.000474 ***\nIsRd16         -1.60848    0.58937  -2.729 0.006420 ** \nIsRd8          -1.22641    0.62963  -1.948 0.051615 .  \nIsRd4          -0.75028    0.68973  -1.088 0.276855    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.126 on 1576 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.3217,\tAdjusted R-squared:  0.3187 \nF-statistic: 106.8 on 7 and 1576 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nTournament round **is** a statistically significant predictor variable for the increase in March Madness tournament volume. \n\nWhen the championship round is run separately from the other rounds, its impact is statistically significant; however, when it is run with the other rounds, it produces singularities. \n\nLooking at the coefficients, I suspect there may be better variables to explain increases in mention volume during March Madness.\n\n### Seeding\n\nThe 68 teams in March Madness are divided into four regions, and each region's teams are ranked 1-16 (the other four teams participate in the First Four and are additional teams ranked at either 11 or 16). There are two questions I want to answer as it relates to seeding and whether it is a predictor for conversation volume:\n\n* Does the absolute difference in seeding between the two teams in the game impact mention volume?\n* Does each team's seeding impact mention volume?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression for seeding\nsummary(lm(Mention_Volume ~ IsMarchMadness + Seed, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + Seed, data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -2952   -766   -395    327  37209 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      959.00     132.86   7.218 8.05e-13 ***\nIsMarchMadness  2133.91     130.17  16.393  < 2e-16 ***\nSeed             -31.38      13.92  -2.254   0.0243 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2552 on 1629 degrees of freedom\nMultiple R-squared:  0.1461,\tAdjusted R-squared:  0.1451 \nF-statistic: 139.4 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + Seed, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + Seed, data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.4589 -0.9049  0.1126  0.9052  3.2083 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     6.15053    0.06097 100.877  < 2e-16 ***\nIsMarchMadness  1.39820    0.05974  23.406  < 2e-16 ***\nSeed           -0.02627    0.00639  -4.111 4.14e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.171 on 1629 degrees of freedom\nMultiple R-squared:  0.2616,\tAdjusted R-squared:  0.2607 \nF-statistic: 288.6 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nSimilar to tournament round, while Seed is statistically significant, I suspect there are likely other variables that are a better fit in terms of explaining this impact.\n\nTo measure the impact of seed difference without causing multicollinearity with IsMarchMadness, I will again create dummy variables for each possible difference in seeding. \n\nBecause no games had a seeding difference of 14, 12, 10, or 2, these will be excluded from my dummy variables. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create dummy variables for each possible difference in seeding\nVolumeAndVariables <- VolumeAndVariables %>%\nmutate(\nIs15 = ifelse(SeedDifference == 15, 1, 0),\nIs13 = ifelse(SeedDifference == 13, 1, 0),\nIs11 = ifelse(SeedDifference == 11, 1, 0),\nIs9 = ifelse(SeedDifference == 9, 1, 0),\nIs8 = ifelse(SeedDifference == 8, 1, 0),\nIs7 = ifelse(SeedDifference == 7, 1, 0),\nIs6 = ifelse(SeedDifference == 6, 1, 0),\nIs5 = ifelse(SeedDifference == 5, 1, 0),\nIs4 = ifelse(SeedDifference == 4, 1, 0),\nIs3 = ifelse(SeedDifference == 3, 1, 0),\nIs1 = ifelse(SeedDifference == 1, 1, 0),\nIs0 = ifelse(SeedDifference == 0, 1, 0))\nSeedDifference <- VolumeAndVariables %>%\n  select(Mention_Volume, IsMarchMadness, Is15, Is13, Is11, Is9, Is8, Is7, Is6, Is5, Is4, Is3, Is1, Is0)\n\n# Linear regression for difference in seeding\nsummary(lm(Mention_Volume ~ IsMarchMadness + ., data = SeedDifference))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + ., data = SeedDifference)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -7124   -658   -382    402  38147 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      720.54      68.44  10.529  < 2e-16 ***\nIsMarchMadness  1246.83     119.66  10.420  < 2e-16 ***\nIs15            5303.00     774.44   6.848 1.06e-11 ***\nIs13            1997.25     774.44   2.579  0.01000 ** \nIs11            -125.75     774.44  -0.162  0.87103    \nIs9             1877.23     694.07   2.705  0.00691 ** \nIs8             3231.93     694.07   4.656 3.48e-06 ***\nIs7             3417.27     588.94   5.802 7.85e-09 ***\nIs6            13337.13    1539.52   8.663  < 2e-16 ***\nIs5             2920.13     588.94   4.958 7.86e-07 ***\nIs4            10969.53     694.07  15.805  < 2e-16 ***\nIs3             4573.13     551.99   8.285 2.45e-16 ***\nIs1             5999.67     437.28  13.721  < 2e-16 ***\nIs0              125.13     774.44   0.162  0.87166    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2173 on 1618 degrees of freedom\nMultiple R-squared:  0.385,\tAdjusted R-squared:  0.3801 \nF-statistic: 77.92 on 13 and 1618 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + ., data = SeedDifference))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + ., data = SeedDifference)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5531 -0.8630  0.0490  0.8891  3.4991 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     5.95095    0.03558 167.239  < 2e-16 ***\nIsMarchMadness  1.14942    0.06222  18.474  < 2e-16 ***\nIs15            1.38431    0.40267   3.438 0.000601 ***\nIs13            0.76900    0.40267   1.910 0.056344 .  \nIs11            0.31545    0.40267   0.783 0.433515    \nIs9             0.92347    0.36088   2.559 0.010590 *  \nIs8             1.29187    0.36088   3.580 0.000354 ***\nIs7             1.12796    0.30622   3.684 0.000238 ***\nIs6             2.52050    0.80048   3.149 0.001670 ** \nIs5             1.08112    0.30622   3.531 0.000426 ***\nIs4             2.28742    0.36088   6.338 3.00e-10 ***\nIs3             1.24910    0.28701   4.352 1.43e-05 ***\nIs1             1.56438    0.22736   6.881 8.50e-12 ***\nIs0             0.29790    0.40267   0.740 0.459520    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.13 on 1618 degrees of freedom\nMultiple R-squared:  0.3173,\tAdjusted R-squared:  0.3118 \nF-statistic: 57.85 on 13 and 1618 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nNearly all differences in seeding (with the exception of Is11 and Is0) had a statistically significant impact on mention volume. There are, however, likely better explanatory variables than this. \n\nFor seeding, there are two final variables I want to create and examine: the impact of a seed difference of 15 (ie. a number 1 seed playing a number 16 seed), and the impact of a seed difference greater or equal to five (ie. the difference in seeding that creates the potential for a game to be an upset).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add new column for seed difference = 15 \nVolumeAndVariables <- VolumeAndVariables %>%\n  mutate(SeedDiff15 = ifelse(SeedDifference == 15, 1, 0))\n  \n# Add new column for seed difference >= 5 \nVolumeAndVariables <- VolumeAndVariables %>%\n  mutate(SeedDiffMoreThan5 = ifelse(SeedDifference >= 5, 1, 0))\n\n# Linear regression for seed difference = 15\nsummary(lm(Mention_Volume ~ IsMarchMadness + SeedDiff15, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + SeedDiff15, data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -6681   -676   -424    346  37300 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       720.5       79.9   9.018  < 2e-16 ***\nIsMarchMadness   2093.1      129.7  16.135  < 2e-16 ***\nSeedDiff15       4456.7      902.6   4.937 8.73e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2537 on 1629 degrees of freedom\nMultiple R-squared:  0.1561,\tAdjusted R-squared:  0.1551 \nF-statistic: 150.7 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + SeedDiff15, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + SeedDiff15, \n    data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5531 -0.9203  0.0809  0.9121  3.2512 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     5.95095    0.03699 160.889  < 2e-16 ***\nIsMarchMadness  1.39733    0.06006  23.267  < 2e-16 ***\nSeedDiff15      1.13640    0.41788   2.719  0.00661 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.174 on 1629 degrees of freedom\nMultiple R-squared:  0.2574,\tAdjusted R-squared:  0.2564 \nF-statistic: 282.3 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nGames where a number one seed was playing a number 15 seed did indeed have a statistically significant impact on mention volume. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Mention_Volume ~ IsMarchMadness + SeedDiffMoreThan5, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + SeedDiffMoreThan5, \n    data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -6176   -669   -383    402  37838 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         5141.4      288.9   17.80   <2e-16 ***\nIsMarchMadness      1555.1      126.9   12.26   <2e-16 ***\nSeedDiffMoreThan5  -4420.9      279.0  -15.85   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2379 on 1629 degrees of freedom\nMultiple R-squared:  0.2579,\tAdjusted R-squared:  0.2569 \nF-statistic:   283 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + SeedDiffMoreThan5, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + SeedDiffMoreThan5, \n    data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5531 -0.9075  0.0933  0.9068  3.3915 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        7.10126    0.13986  50.774   <2e-16 ***\nIsMarchMadness     1.25705    0.06141  20.468   <2e-16 ***\nSeedDiffMoreThan5 -1.15031    0.13507  -8.516   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.152 on 1629 degrees of freedom\nMultiple R-squared:  0.2858,\tAdjusted R-squared:  0.2849 \nF-statistic: 325.9 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nWhile a seed difference of more than five had a statistically significant result, there are likely better explanatory variables for the increase in mention volume during March Madness.\n\n#### Time Slot\n\nI have divided all the games played during the tournament into five categories based on the time that each game tipped off. start times for the March Madness games into five time slots - Early Afternoon (12:00-2:15pm), Mid Afternoon (2:15-4:30pm), Late Afternoon (4:30-6:45pm), Early Evening (6:45-9:00pm), and Late Evening (9:00-10:45pm).\n\nI included this variable because I suspect that playing earlier in the day may have an impact on overall conversation volume.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create dummy variables for each time slot\nVolumeAndVariables <- VolumeAndVariables %>%\nmutate(\nIsEarlyEvening = ifelse(Time == \"Early Evening\", 1, 0),\nIsLateAfternoon = ifelse(Time == \"Late Afternoon\", 1, 0),\nIsLateEvening = ifelse(Time == \"Late Evening\", 1, 0),\nIsMidAfternoon = ifelse(Time == \"Mid Afternoon\", 1, 0),\nIsEarlyAfternoon = ifelse(Time == \"Early Afternoon\", 1, 0))\nTimeVariables <- VolumeAndVariables %>%\n  select(Mention_Volume, IsMarchMadness, IsEarlyEvening, IsLateAfternoon, IsLateEvening, IsMidAfternoon, IsEarlyAfternoon)\n\n# Linear regression for time of day\nsummary(lm(Mention_Volume ~ IsMarchMadness + ., data = TimeVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + ., data = TimeVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -9146   -662   -384    409  38147 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        720.54      71.27  10.110  < 2e-16 ***\nIsMarchMadness    1246.83     124.61  10.006  < 2e-16 ***\nIsEarlyEvening    3743.33     401.30   9.328  < 2e-16 ***\nIsLateAfternoon   7699.94     455.38  16.909  < 2e-16 ***\nIsLateEvening     3007.43     390.73   7.697 2.40e-14 ***\nIsMidAfternoon    4613.46     543.04   8.496  < 2e-16 ***\nIsEarlyAfternoon  2248.08     516.19   4.355 1.41e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2263 on 1625 degrees of freedom\nMultiple R-squared:  0.3301,\tAdjusted R-squared:  0.3277 \nF-statistic: 133.5 on 6 and 1625 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + ., data = TimeVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + ., data = TimeVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5531 -0.8773  0.0790  0.8965  3.4991 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       5.95095    0.03575 166.455  < 2e-16 ***\nIsMarchMadness    1.14942    0.06251  18.388  < 2e-16 ***\nIsEarlyEvening    1.26754    0.20130   6.297 3.90e-10 ***\nIsLateAfternoon   1.56688    0.22843   6.859 9.81e-12 ***\nIsLateEvening     0.99169    0.19600   5.060 4.68e-07 ***\nIsMidAfternoon    1.30455    0.27241   4.789 1.83e-06 ***\nIsEarlyAfternoon  1.03853    0.25894   4.011 6.33e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.135 on 1625 degrees of freedom\nMultiple R-squared:  0.3079,\tAdjusted R-squared:  0.3053 \nF-statistic: 120.5 on 6 and 1625 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nTime slot had a statistically significant impact across all times. \n\n### Is Game Day\n\nWhile the entire tournament takes 20 days to play, games only occur on 12 of those days. Accordingly, I want to consider the impact of game day when modeling. \n\nIn my original hypothesis testing the day after each game also had a statistically significant impact on mention volume, so I want to use that in regression as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression game day\nIsOnGameDay <- lm(Mention_Volume ~ IsMarchMadness + IsGameDay, data = VolumeAndVariables)\nIsOnGameDaylog <- lm(log(Mention_Volume) ~ IsMarchMadness + IsGameDay, data = VolumeAndVariables)\n\n# Linear regression day after game \nIsOnDayAfterGame <- lm(Mention_Volume ~ IsMarchMadness + IsDayAfterGame, data = VolumeAndVariables)\nIsOnDayAfterGamelog <- lm(log(Mention_Volume) ~ IsMarchMadness + IsDayAfterGame, data = VolumeAndVariables)\n\n# Linear regression for day of and day after game \nIsOnBothDays <- lm(Mention_Volume ~ IsMarchMadness + GDayOrAfter, data = VolumeAndVariables)\nIsOnBothDayslog <- lm(log(Mention_Volume) ~ IsMarchMadness + GDayOrAfter, data = VolumeAndVariables)\n\nstargazer(IsOnGameDay, IsOnDayAfterGame, IsOnBothDays, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n======================================================================\n                                         Dependent variable:          \n                                --------------------------------------\n                                            Mention_Volume            \n                                    (1)          (2)          (3)     \n----------------------------------------------------------------------\nIsMarchMadness                  1,246.834*** 2,140.523*** 1,569.368***\n                                 (127.826)    (132.629)    (133.667)  \n                                                                      \nIsGameDay                       4,207.039***                          \n                                 (226.273)                            \n                                                                      \nIsDayAfterGame                                  89.928                \n                                              (234.776)               \n                                                                      \nGDayOrAfter                                               2,270.919***\n                                                           (188.061)  \n                                                                      \nConstant                         720.538***   716.880***   628.169*** \n                                  (73.107)     (81.052)     (77.493)  \n                                                                      \n----------------------------------------------------------------------\nObservations                       1,632        1,632        1,632    \nR2                                 0.293        0.144        0.214    \nAdjusted R2                        0.293        0.142        0.213    \nResidual Std. Error (df = 1629)  2,321.087    2,555.411    2,448.297  \nF Statistic (df = 2; 1629)       338.231***   136.519***   221.554*** \n======================================================================\nNote:                                      *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n\n```{.r .cell-code}\nstargazer(IsOnGameDaylog, IsOnDayAfterGamelog, IsOnBothDayslog, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n================================================================\n                                      Dependent variable:       \n                                --------------------------------\n                                      log(Mention_Volume)       \n                                   (1)        (2)        (3)    \n----------------------------------------------------------------\nIsMarchMadness                   1.149***   1.399***   1.240*** \n                                 (0.063)    (0.061)    (0.063)  \n                                                                \nIsGameDay                        1.222***                       \n                                 (0.111)                        \n                                                                \nIsDayAfterGame                               0.120              \n                                            (0.108)             \n                                                                \nGDayOrAfter                                            0.673*** \n                                                       (0.089)  \n                                                                \nConstant                         5.951***   5.946***   5.924*** \n                                 (0.036)    (0.037)    (0.037)  \n                                                                \n----------------------------------------------------------------\nObservations                      1,632      1,632      1,632   \nR2                                0.306      0.255      0.279   \nAdjusted R2                       0.305      0.254      0.278   \nResidual Std. Error (df = 1629)   1.135      1.177      1.157   \nF Statistic (df = 2; 1629)      359.055*** 278.132*** 315.725***\n================================================================\nNote:                                *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\nGame day had the most significant impact on mention volume. \n\n### Testing All of the Tournament-Related Variables Together\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Mention_Volume ~ IsMarchMadness + IsGameDay + IsDayAfterGame + IsFirst4 + IsRd64 + IsRd32 + IsRd16 + IsRd8 + IsRd4 + IsChamp + Is15 + Is13 + Is11 + Is9 + Is8 + Is7 + Is6 + Is5 + Is4 + Is3 + Is1 + Is0 + IsEarlyEvening + IsLateAfternoon + IsLateEvening + IsMidAfternoon + IsEarlyAfternoon, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + IsGameDay + IsDayAfterGame + \n    IsFirst4 + IsRd64 + IsRd32 + IsRd16 + IsRd8 + IsRd4 + IsChamp + \n    Is15 + Is13 + Is11 + Is9 + Is8 + Is7 + Is6 + Is5 + Is4 + \n    Is3 + Is1 + Is0 + IsEarlyEvening + IsLateAfternoon + IsLateEvening + \n    IsMidAfternoon + IsEarlyAfternoon, data = VolumeAndVariables)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13943.8   -640.4   -289.6    406.4  17009.8 \n\nCoefficients: (3 not defined because of singularities)\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         734.13      54.82  13.393  < 2e-16 ***\nIsMarchMadness    23461.67     893.45  26.260  < 2e-16 ***\nIsGameDay           -69.13     799.62  -0.086 0.931118    \nIsDayAfterGame     -334.18     167.80  -1.991 0.046601 *  \nIsFirst4         -22915.62     896.50 -25.561  < 2e-16 ***\nIsRd64           -22398.66     907.72 -24.676  < 2e-16 ***\nIsRd32           -21062.18     916.82 -22.973  < 2e-16 ***\nIsRd16           -20214.68     924.32 -21.870  < 2e-16 ***\nIsRd8            -17610.87     990.90 -17.773  < 2e-16 ***\nIsRd4            -14514.47    1073.34 -13.523  < 2e-16 ***\nIsChamp                 NA         NA      NA       NA    \nIs15               5758.96     917.35   6.278 4.44e-10 ***\nIs13               2041.10     930.93   2.193 0.028488 *  \nIs11                464.91     941.22   0.494 0.621418    \nIs9                2052.03     847.64   2.421 0.015597 *  \nIs8                2063.71     893.39   2.310 0.021020 *  \nIs7                2952.85     820.67   3.598 0.000331 ***\nIs6                7191.86    1419.27   5.067 4.52e-07 ***\nIs5                2101.36     816.62   2.573 0.010167 *  \nIs4                6086.26     912.41   6.671 3.53e-11 ***\nIs3                3613.55     798.24   4.527 6.44e-06 ***\nIs1                2526.37     743.58   3.398 0.000697 ***\nIs0                     NA         NA      NA       NA    \nIsEarlyEvening      231.95     520.08   0.446 0.655661    \nIsLateAfternoon    2898.75     593.53   4.884 1.15e-06 ***\nIsLateEvening     -1135.84     534.53  -2.125 0.033749 *  \nIsMidAfternoon     1481.34     630.17   2.351 0.018863 *  \nIsEarlyAfternoon        NA         NA      NA       NA    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1727 on 1559 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.6232,\tAdjusted R-squared:  0.6174 \nF-statistic: 107.4 on 24 and 1559 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nI'm going to use backward elimination to determine the final model. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nTournamentRelatedLR <- lm(Mention_Volume ~ IsMarchMadness + IsDayAfterGame + IsFirst4 + IsRd64 + IsRd32 + IsRd16 + IsRd8 + IsRd4 + Is15 + Is13 + Is9 + Is8 + Is7 + Is6 + Is5 + Is4 + Is3 + Is1 + IsLateAfternoon + IsLateEvening + IsMidAfternoon, data = VolumeAndVariables)\nsummary(TournamentRelatedLR)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + IsDayAfterGame + \n    IsFirst4 + IsRd64 + IsRd32 + IsRd16 + IsRd8 + IsRd4 + Is15 + \n    Is13 + Is9 + Is8 + Is7 + Is6 + Is5 + Is4 + Is3 + Is1 + IsLateAfternoon + \n    IsLateEvening + IsMidAfternoon, data = VolumeAndVariables)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13927.7   -640.4   -292.7    408.1  17008.2 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        734.18      54.77  13.404  < 2e-16 ***\nIsMarchMadness   23445.48     892.06  26.282  < 2e-16 ***\nIsDayAfterGame    -335.41     167.29  -2.005 0.045140 *  \nIsFirst4        -22897.87     894.47 -25.599  < 2e-16 ***\nIsRd64          -22341.78     903.97 -24.715  < 2e-16 ***\nIsRd32          -21030.36     914.91 -22.986  < 2e-16 ***\nIsRd16          -20197.16     923.07 -21.880  < 2e-16 ***\nIsRd8           -17579.51     989.14 -17.772  < 2e-16 ***\nIsRd4           -14517.70    1072.52 -13.536  < 2e-16 ***\nIs15              5777.35     647.24   8.926  < 2e-16 ***\nIs13              2093.96     686.04   3.052 0.002310 ** \nIs9               2032.30     616.83   3.295 0.001007 ** \nIs8               2086.84     575.70   3.625 0.000298 ***\nIs7               3004.99     498.30   6.031 2.04e-09 ***\nIs6               7239.14    1318.33   5.491 4.65e-08 ***\nIs5               2149.85     531.60   4.044 5.51e-05 ***\nIs4               6187.63     672.38   9.203  < 2e-16 ***\nIs3               3635.31     475.06   7.652 3.43e-14 ***\nIs1               2570.99     416.45   6.174 8.49e-10 ***\nIsLateAfternoon   2774.03     423.35   6.553 7.66e-11 ***\nIsLateEvening    -1217.31     376.70  -3.232 0.001257 ** \nIsMidAfternoon    1342.85     503.56   2.667 0.007739 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1726 on 1562 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.623,\tAdjusted R-squared:  0.6179 \nF-statistic: 122.9 on 21 and 1562 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThe remaining variables are all considered statistically significant in the model for tournament-related variables.\n\nTesting with log(Mention_Volume)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTournamentRelatedLRlog <- lm(log(Mention_Volume) ~ IsMarchMadness + IsGameDay + IsFirst4 + IsRd64 + IsRd32 + IsRd16, data = VolumeAndVariables)\nsummary(TournamentRelatedLRlog)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + IsGameDay + \n    IsFirst4 + IsRd64 + IsRd32 + IsRd16, data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5531 -0.8271  0.0958  0.8731  3.0197 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     5.95095    0.03487 170.671  < 2e-16 ***\nIsMarchMadness  2.73125    0.21830  12.511  < 2e-16 ***\nIsGameDay       0.92348    0.12063   7.656 3.33e-14 ***\nIsFirst4       -1.88781    0.22226  -8.494  < 2e-16 ***\nIsRd64         -1.58017    0.23238  -6.800 1.48e-11 ***\nIsRd32         -1.06859    0.25091  -4.259 2.18e-05 ***\nIsRd16         -0.69331    0.27009  -2.567   0.0103 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.107 on 1577 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.3443,\tAdjusted R-squared:  0.3419 \nF-statistic:   138 on 6 and 1577 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThere are far fewer variables that are considered statistically significant when using the log of Mention_Volume compared to the non-transformed version. In the log-transformed model, there are five significant variables other than IsMarchMadness; in the original model there are 20. \n\nIsGameDay was statistically significant in the log model; it was not in the non-transformed model.\n\nIsDayAfterGame, IsRd8, IsRd4, Is15, Is13, Is9, Is8, Is7, Is6, Is5, Is4, Is3, Is1, IsLateAfternoon, IsLateEvening, and IsMidAfternoon were statistically significant in the non-log transformed model but not the log model.\n\nThe non-log-transformed model has a much higher adjusted r squared (0.6179) than the log-transformed model (0.3419).\n\n## Model 4 - School-Related Variables\n\n* Size of school (6 variables - LargeHighRez, LargePriRez, LargePriNonRez, MedHighRez, MedPriRez, SmallHighRez\n* Major / mid-major (1 - Yes, 0 - No)\n\n### School Size\n\nSchool size is based on how school size is defined by [Carnegie Classification of Institutions of Higher Education](https://carnegieclassifications.acenet.edu/) and broken into six categories: Large (Highly Residential), Large (Primarily Residential), Large (Primarily Non-Residential), Medium (Highly Residential), Medium (Primarily Residential), Small (Highly Residential).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression for school size and setting\nsummary(lm(Mention_Volume ~ IsMarchMadness + SizeSetting, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + SizeSetting, data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -3128   -896   -255    293  36654 \n\nCoefficients:\n                                                      Estimate Std. Error\n(Intercept)                                             1354.8      202.1\nIsMarchMadness                                          2105.6      128.4\nSizeSettingFour-year, large, primarily nonresidential   -388.8      234.5\nSizeSettingFour-year, large, primarily residential      -392.2      216.1\nSizeSettingFour-year, medium, highly residential       -1420.4      265.1\nSizeSettingFour-year, medium, primarily residential    -1462.5      274.5\nSizeSettingFour-year, small, highly residential        -1579.0      411.2\n                                                      t value Pr(>|t|)    \n(Intercept)                                             6.702 2.82e-11 ***\nIsMarchMadness                                         16.394  < 2e-16 ***\nSizeSettingFour-year, large, primarily nonresidential  -1.658 0.097465 .  \nSizeSettingFour-year, large, primarily residential     -1.815 0.069633 .  \nSizeSettingFour-year, medium, highly residential       -5.357 9.67e-08 ***\nSizeSettingFour-year, medium, primarily residential    -5.328 1.13e-07 ***\nSizeSettingFour-year, small, highly residential        -3.840 0.000128 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2509 on 1625 degrees of freedom\nMultiple R-squared:  0.1761,\tAdjusted R-squared:  0.1731 \nF-statistic:  57.9 on 6 and 1625 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + SizeSetting, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + SizeSetting, \n    data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.0525 -0.7147  0.0280  0.7061  3.6527 \n\nCoefficients:\n                                                        Estimate Std. Error\n(Intercept)                                            6.4197206  0.0810504\nIsMarchMadness                                         1.3742651  0.0514978\nSizeSettingFour-year, large, primarily nonresidential -0.4102806  0.0940232\nSizeSettingFour-year, large, primarily residential     0.0001005  0.0866304\nSizeSettingFour-year, medium, highly residential      -1.2290024  0.1063152\nSizeSettingFour-year, medium, primarily residential   -1.5743925  0.1100526\nSizeSettingFour-year, small, highly residential       -1.9468254  0.1648861\n                                                      t value Pr(>|t|)    \n(Intercept)                                            79.207  < 2e-16 ***\nIsMarchMadness                                         26.686  < 2e-16 ***\nSizeSettingFour-year, large, primarily nonresidential  -4.364 1.36e-05 ***\nSizeSettingFour-year, large, primarily residential      0.001    0.999    \nSizeSettingFour-year, medium, highly residential      -11.560  < 2e-16 ***\nSizeSettingFour-year, medium, primarily residential   -14.306  < 2e-16 ***\nSizeSettingFour-year, small, highly residential       -11.807  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.006 on 1625 degrees of freedom\nMultiple R-squared:  0.4561,\tAdjusted R-squared:  0.4541 \nF-statistic: 227.1 on 6 and 1625 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nSizeSetting overall had a statistically significant impact, but being a large-sized school specifically did not. Schools being small or medium had a statistically significant impact.\n\nAccordingly, I'm curious what the impact would be with size broken down only as small, medium, and large, and with size as a binary variable for IsLarge (Yes = 1, No = 2).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reduce SizeSetting to just Size\nVolumeAndVariables <- VolumeAndVariables %>%\nmutate(\nSize = case_when(\nSizeSetting == \"Four-year, large, primarily residential\" ~ \"Large\",\nSizeSetting == \"Four-year, large, primarily nonresidential\" ~ \"Large\",\nSizeSetting == \"Four-year, large, highly residential\" ~ \"Large\",\nSizeSetting == \"Four-year, medium, primarily residential\" ~ \"Medium\",\nSizeSetting == \"Four-year, medium, highly residential\" ~ \"Medium\",\nSizeSetting == \"Four-year, small, highly residential\" ~ \"Small\"),\nIsLarge = ifelse(Size == \"Large\", 1, 0))\n\n# Linear regression for small, medium, large\nsummary(lm(Mention_Volume ~ IsMarchMadness + Size, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + Size, data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -2956   -911   -269    286  36984 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     1012.80      87.48  11.577  < 2e-16 ***\nIsMarchMadness  2117.25     127.95  16.548  < 2e-16 ***\nSizeMedium     -1102.32     150.52  -7.323 3.79e-13 ***\nSizeSmall      -1240.40     369.52  -3.357 0.000807 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2510 on 1628 degrees of freedom\nMultiple R-squared:  0.1743,\tAdjusted R-squared:  0.1728 \nF-statistic: 114.6 on 3 and 1628 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + Size, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + Size, data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.9337 -0.7169  0.0555  0.7192  3.4716 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     6.30102    0.03561  176.97   <2e-16 ***\nIsMarchMadness  1.36937    0.05207   26.30   <2e-16 ***\nSizeMedium     -1.26971    0.06126  -20.73   <2e-16 ***\nSizeSmall      -1.82670    0.15039  -12.15   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.021 on 1628 degrees of freedom\nMultiple R-squared:  0.4384,\tAdjusted R-squared:  0.4374 \nF-statistic: 423.7 on 3 and 1628 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThese results were statistically significant, but the r squared from the first models suggests a better fit. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression for IsLarge\nsummary(lm(Mention_Volume ~ IsMarchMadness + IsLarge, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + IsLarge, data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -2957   -910   -269    271  36983 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      -106.1      132.3  -0.802    0.422    \nIsMarchMadness   2118.3      127.9  16.566  < 2e-16 ***\nIsLarge          1118.5      143.5   7.794 1.15e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2509 on 1629 degrees of freedom\nMultiple R-squared:  0.1743,\tAdjusted R-squared:  0.1733 \nF-statistic: 171.9 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + IsLarge, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + IsLarge, \n    data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.9320 -0.7301  0.0622  0.7256  3.5342 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     4.96422    0.05404   91.86   <2e-16 ***\nIsMarchMadness  1.37379    0.05224   26.30   <2e-16 ***\nIsLarge         1.33507    0.05863   22.77   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.025 on 1629 degrees of freedom\nMultiple R-squared:  0.4341,\tAdjusted R-squared:  0.4334 \nF-statistic: 624.8 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nIsLarge was statistically significant; the adjusted r squared (for both log and non-log models) were effectively the same (0.1675 vs. 0.168 and 0.4006 vs. 0.3969) respectively. \n\n### Status as Major or Mid-Major\n\nWhile it is not an official designation by the NCAA, teams that play in particular NCAA Division 1 conferences (ACC, AAC, Big East, Big 10, Big 12, Pac-12, and SEC) are often referred to as \"high major\" programs, while teams that play in any other conference are referred to as \"mid-major\"[^8].\n\n[^8]: Some [split this designation down even further to high-, mid-, and low-major](https://torchcollegerecruiting.com/z_a3_high_mid_low_majors/1641907452726x394612841469246460), but I did not see merit in narrowing the sample down this far.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression for whether or not team is a high major\nsummary(lm(Mention_Volume ~ IsMarchMadness + Major, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + Major, data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -3018   -919   -124    129  36769 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       176.3      101.6   1.735   0.0829 .  \nIsMarchMadness   2115.7      127.5  16.600   <2e-16 ***\nMajorYes         1053.1      124.1   8.486   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2501 on 1629 degrees of freedom\nMultiple R-squared:  0.1797,\tAdjusted R-squared:  0.1787 \nF-statistic: 178.5 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Mention_Volume) ~ IsMarchMadness + Major, data = VolumeAndVariables))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + Major, data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.8262 -0.6724 -0.0451  0.5702  3.6218 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     5.22406    0.03837  136.17   <2e-16 ***\nIsMarchMadness  1.36575    0.04814   28.37   <2e-16 ***\nMajorYes        1.40635    0.04687   30.01   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9445 on 1629 degrees of freedom\nMultiple R-squared:  0.5196,\tAdjusted R-squared:  0.519 \nF-statistic: 880.8 on 2 and 1629 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nBeing considered a high major school had a statistically significant impact on mention volume.\n\n### Testing the School-Related Variables Together\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSchoolRelatedLR <- lm(Mention_Volume ~ IsMarchMadness + Size + Major, data = VolumeAndVariables)\nsummary(SchoolRelatedLR)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + Size + Major, \n    data = VolumeAndVariables)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -2936   -935   -293    289  36737 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       508.4      127.0   4.003 6.54e-05 ***\nIsMarchMadness   2104.9      126.9  16.593  < 2e-16 ***\nSizeMedium       -695.3      167.0  -4.165 3.28e-05 ***\nSizeSmall        -732.4      378.1  -1.937   0.0529 .  \nMajorYes          763.8      140.5   5.435 6.31e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2488 on 1627 degrees of freedom\nMultiple R-squared:  0.1891,\tAdjusted R-squared:  0.1871 \nF-statistic: 94.82 on 4 and 1627 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n### Testing log(Mention_Volume) for the school-related variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSchoolRelatedLRlog <- lm(log(Mention_Volume) ~ IsMarchMadness + Size + Major, data = VolumeAndVariables)\nsummary(SchoolRelatedLRlog)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + Size + Major, \n    data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.2523 -0.6714 -0.0486  0.5529  3.6293 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     5.57580    0.04599 121.237  < 2e-16 ***\nIsMarchMadness  1.35167    0.04593  29.426  < 2e-16 ***\nSizeMedium     -0.68447    0.06045 -11.322  < 2e-16 ***\nSizeSmall      -1.09632    0.13689  -8.009 2.19e-15 ***\nMajorYes        1.09822    0.05088  21.583  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9009 on 1627 degrees of freedom\nMultiple R-squared:  0.5634,\tAdjusted R-squared:  0.5624 \nF-statistic:   525 on 4 and 1627 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nBoth models had the same p-value, but the log-transformed model has an adjusted r squared of 0.5624 while the non-transformed model was 0.1871. \n\nWhen it comes to modeling school-related variables, the model with log-transformed mention volume was a better fit. \n\n## Model 5 - All Variables\n\nI will now run a model with every variable from all four previous models. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nAllVariablesLR <- lm(Mention_Volume ~ IsMarchMadness + IsWinner + UpsetWin + UpsetLoss + FavoriteWin + FavoriteLoss + UnderdogWin + UnderdogLoss + IsGameDay + IsDayAfterGame + IsFirst4 + IsRd64 + IsRd32 + IsRd16 + IsRd8 + IsRd4 + IsChamp + Is15 + Is13 + Is11 + Is9 + Is8 + Is7 + Is6 + Is5 + Is4 + Is3 + Is1 + Is0 + IsEarlyEvening + IsLateAfternoon + IsLateEvening + IsMidAfternoon + IsEarlyAfternoon + Size + Major, data = VolumeAndVariables)\nsummary(AllVariablesLR)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + IsWinner + UpsetWin + \n    UpsetLoss + FavoriteWin + FavoriteLoss + UnderdogWin + UnderdogLoss + \n    IsGameDay + IsDayAfterGame + IsFirst4 + IsRd64 + IsRd32 + \n    IsRd16 + IsRd8 + IsRd4 + IsChamp + Is15 + Is13 + Is11 + Is9 + \n    Is8 + Is7 + Is6 + Is5 + Is4 + Is3 + Is1 + Is0 + IsEarlyEvening + \n    IsLateAfternoon + IsLateEvening + IsMidAfternoon + IsEarlyAfternoon + \n    Size + Major, data = VolumeAndVariables)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13366.5   -538.1   -148.0    256.2  16412.3 \n\nCoefficients: (4 not defined because of singularities)\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         424.49      78.70   5.393 7.98e-08 ***\nIsMarchMadness    23193.97     786.22  29.501  < 2e-16 ***\nIsWinnerYes        1048.41    1065.28   0.984 0.325188    \nUpsetWinYes        7102.00     839.81   8.457  < 2e-16 ***\nUpsetLossYes       3839.19     838.70   4.578 5.08e-06 ***\nFavoriteWinYes     2504.38     950.12   2.636 0.008476 ** \nFavoriteLossYes     968.62     947.51   1.022 0.306805    \nUnderdogWinYes     3029.86     878.18   3.450 0.000575 ***\nUnderdogLossYes    1107.89     873.47   1.268 0.204854    \nIsGameDay          -100.41     880.61  -0.114 0.909234    \nIsDayAfterGame     -265.74     147.21  -1.805 0.071240 .  \nIsFirst4         -22583.09     788.85 -28.628  < 2e-16 ***\nIsRd64           -22352.73     799.16 -27.970  < 2e-16 ***\nIsRd32           -21261.16     806.37 -26.366  < 2e-16 ***\nIsRd16           -19989.55     815.03 -24.526  < 2e-16 ***\nIsRd8            -17565.23     876.73 -20.035  < 2e-16 ***\nIsRd4            -14329.90     936.47 -15.302  < 2e-16 ***\nIsChamp                 NA         NA      NA       NA    \nIs15               1942.69     668.07   2.908 0.003690 ** \nIs13              -1818.91     677.58  -2.684 0.007343 ** \nIs11              -1742.82     678.82  -2.567 0.010338 *  \nIs9               -1348.84     622.47  -2.167 0.030392 *  \nIs8               -1126.76     636.16  -1.771 0.076723 .  \nIs7                 -84.35     560.00  -0.151 0.880293    \nIs6                 832.81    1246.77   0.668 0.504248    \nIs5               -2904.69     588.19  -4.938 8.73e-07 ***\nIs4                3963.33     644.11   6.153 9.65e-10 ***\nIs3                1092.60     494.37   2.210 0.027245 *  \nIs1                     NA         NA      NA       NA    \nIs0                     NA         NA      NA       NA    \nIsEarlyEvening      646.44     470.42   1.374 0.169591    \nIsLateAfternoon    1999.72     530.69   3.768 0.000171 ***\nIsLateEvening      -858.93     472.92  -1.816 0.069529 .  \nIsMidAfternoon     1470.80     550.89   2.670 0.007668 ** \nIsEarlyAfternoon        NA         NA      NA       NA    \nSizeMedium         -505.87     103.73  -4.877 1.19e-06 ***\nSizeSmall          -402.88     230.77  -1.746 0.081044 .  \nMajorYes            842.34      87.83   9.590  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1506 on 1550 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.715,\tAdjusted R-squared:  0.7089 \nF-statistic: 117.8 on 33 and 1550 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nAllVariablesLRlog <- lm(log(Mention_Volume) ~ IsMarchMadness + IsWinner + UpsetWin + UpsetLoss + FavoriteWin + FavoriteLoss + UnderdogWin + UnderdogLoss + IsGameDay + IsDayAfterGame + IsFirst4 + IsRd64 + IsRd32 + IsRd16 + IsRd8 + IsRd4 + IsChamp + Is15 + Is13 + Is11 + Is9 + Is8 + Is7 + Is6 + Is5 + Is4 + Is3 + Is1 + Is0 + IsEarlyEvening + IsLateAfternoon + IsLateEvening + IsMidAfternoon + IsEarlyAfternoon + Size + Major, data = VolumeAndVariables)\nsummary(AllVariablesLRlog)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + IsWinner + \n    UpsetWin + UpsetLoss + FavoriteWin + FavoriteLoss + UnderdogWin + \n    UnderdogLoss + IsGameDay + IsDayAfterGame + IsFirst4 + IsRd64 + \n    IsRd32 + IsRd16 + IsRd8 + IsRd4 + IsChamp + Is15 + Is13 + \n    Is11 + Is9 + Is8 + Is7 + Is6 + Is5 + Is4 + Is3 + Is1 + Is0 + \n    IsEarlyEvening + IsLateAfternoon + IsLateEvening + IsMidAfternoon + \n    IsEarlyAfternoon + Size + Major, data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.2475 -0.5444 -0.0327  0.4991  3.1885 \n\nCoefficients: (4 not defined because of singularities)\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       5.548279   0.041446 133.867  < 2e-16 ***\nIsMarchMadness    3.667101   0.414029   8.857  < 2e-16 ***\nIsWinnerYes       0.128204   0.560985   0.229 0.819262    \nUpsetWinYes       1.437542   0.442252   3.251 0.001177 ** \nUpsetLossYes      0.489885   0.441667   1.109 0.267527    \nFavoriteWinYes   -0.267184   0.500339  -0.534 0.593414    \nFavoriteLossYes  -0.578416   0.498964  -1.159 0.246540    \nUnderdogWinYes   -0.289704   0.462454  -0.626 0.531112    \nUnderdogLossYes  -0.332252   0.459974  -0.722 0.470203    \nIsGameDay         1.239874   0.463736   2.674 0.007582 ** \nIsDayAfterGame   -0.132229   0.077523  -1.706 0.088269 .  \nIsFirst4         -2.826484   0.415412  -6.804 1.45e-11 ***\nIsRd64           -2.631728   0.420845  -6.253 5.18e-10 ***\nIsRd32           -2.232335   0.424641  -5.257 1.67e-07 ***\nIsRd16           -1.558388   0.429201  -3.631 0.000292 ***\nIsRd8            -1.404315   0.461691  -3.042 0.002392 ** \nIsRd4            -0.896345   0.493151  -1.818 0.069320 .  \nIsChamp                 NA         NA      NA       NA    \nIs15              0.749508   0.351812   2.130 0.033294 *  \nIs13              0.101789   0.356816   0.285 0.775475    \nIs11              0.092589   0.357469   0.259 0.795661    \nIs9               0.286940   0.327796   0.875 0.381512    \nIs8               0.191323   0.335005   0.571 0.568011    \nIs7               0.426904   0.294898   1.448 0.147923    \nIs6               0.244996   0.656558   0.373 0.709086    \nIs5              -0.688168   0.309745  -2.222 0.026446 *  \nIs4               0.268176   0.339194   0.791 0.429283    \nIs3               0.025999   0.260339   0.100 0.920462    \nIs1                     NA         NA      NA       NA    \nIs0                     NA         NA      NA       NA    \nIsEarlyEvening   -0.142239   0.247729  -0.574 0.565934    \nIsLateAfternoon  -0.203041   0.279464  -0.727 0.467620    \nIsLateEvening    -0.585250   0.249044  -2.350 0.018899 *  \nIsMidAfternoon    0.006344   0.290104   0.022 0.982556    \nIsEarlyAfternoon        NA         NA      NA       NA    \nSizeMedium       -0.661744   0.054622 -12.115  < 2e-16 ***\nSizeSmall        -1.033428   0.121527  -8.504  < 2e-16 ***\nMajorYes          1.147779   0.046254  24.815  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7932 on 1550 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.6692,\tAdjusted R-squared:  0.6621 \nF-statistic:    95 on 33 and 1550 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nIn this version of the model, the p-values are again the same for the original mention volume variable and the log-transformed one; however, the adjusted r squared for the original model is higher (0.7089 vs. 0.6621). \n\n## Model 6 - Only Significant Variables\n\nI now want to create a model with statistically significant variables from the four models that I created. I am going to use backward elimination to create this model. I am not going to include every step of me backwardly creating this model, but will include the final model with only significant variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use backward elimination to create model of significant variables\nSigVariablesLR <- lm(Mention_Volume ~ IsMarchMadness + UpsetWin + UpsetLoss + FavoriteWin + UnderdogWin + IsFirst4 + IsRd64 + IsRd32 + IsRd16 + IsRd8 + IsRd4 + Is15 + Is13 + Is9 + Is5 + Is4 + Is3 + IsEarlyEvening + IsLateAfternoon + IsMidAfternoon + Major, data = VolumeAndVariables)\nsummary(SigVariablesLR)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Mention_Volume ~ IsMarchMadness + UpsetWin + UpsetLoss + \n    FavoriteWin + UnderdogWin + IsFirst4 + IsRd64 + IsRd32 + \n    IsRd16 + IsRd8 + IsRd4 + Is15 + Is13 + Is9 + Is5 + Is4 + \n    Is3 + IsEarlyEvening + IsLateAfternoon + IsMidAfternoon + \n    Major, data = VolumeAndVariables)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13319.3   -526.5    -92.7    206.5  16456.0 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        174.71      62.27   2.806 0.005082 ** \nIsMarchMadness   23396.59     764.40  30.608  < 2e-16 ***\nUpsetWinYes       7154.29     768.31   9.312  < 2e-16 ***\nUpsetLossYes      3937.23     584.18   6.740 2.22e-11 ***\nFavoriteWinYes    2611.99     531.59   4.914 9.88e-07 ***\nUnderdogWinYes    3028.71     283.61  10.679  < 2e-16 ***\nIsFirst4        -22793.33     768.04 -29.677  < 2e-16 ***\nIsRd64          -22658.56     775.93 -29.202  < 2e-16 ***\nIsRd32          -21514.15     786.95 -27.339  < 2e-16 ***\nIsRd16          -20233.70     805.01 -25.135  < 2e-16 ***\nIsRd8           -17617.28     859.38 -20.500  < 2e-16 ***\nIsRd4           -14420.43     941.36 -15.319  < 2e-16 ***\nIs15              2351.40     575.09   4.089 4.56e-05 ***\nIs13             -1617.32     599.77  -2.697 0.007081 ** \nIs9              -1147.69     509.99  -2.250 0.024561 *  \nIs5              -2692.84     476.91  -5.646 1.94e-08 ***\nIs4               4492.86     608.05   7.389 2.40e-13 ***\nIs3               1499.10     411.92   3.639 0.000282 ***\nIsEarlyEvening    1124.35     312.27   3.601 0.000327 ***\nIsLateAfternoon   2558.36     377.14   6.784 1.66e-11 ***\nIsMidAfternoon    2123.85     426.94   4.975 7.26e-07 ***\nMajorYes          1056.04      77.09  13.699  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1519 on 1562 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.7078,\tAdjusted R-squared:  0.7038 \nF-statistic: 180.2 on 21 and 1562 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nAnd then for the log-transformed version of mention volume:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use backward elimination to create model of significant variables\nSigVariablesLRlog <- lm(log(Mention_Volume) ~ IsMarchMadness + IsWinner + UpsetWin + FavoriteLoss + UnderdogLoss + IsFirst4 + IsRd64 + IsRd32 + IsRd16 + IsRd8 + Is15 + Is5 + Size + Major, data = VolumeAndVariables)\nsummary(SigVariablesLRlog)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Mention_Volume) ~ IsMarchMadness + IsWinner + \n    UpsetWin + FavoriteLoss + UnderdogLoss + IsFirst4 + IsRd64 + \n    IsRd32 + IsRd16 + IsRd8 + Is15 + Is5 + Size + Major, data = VolumeAndVariables)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.2516 -0.5599 -0.0313  0.5010  3.1930 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      5.54377    0.04121 134.521  < 2e-16 ***\nIsMarchMadness   2.92884    0.23678  12.369  < 2e-16 ***\nIsWinnerYes      0.97977    0.12242   8.003 2.34e-15 ***\nUpsetWinYes      1.56557    0.29417   5.322 1.17e-07 ***\nFavoriteLossYes  0.75590    0.19610   3.855 0.000121 ***\nUnderdogLossYes  0.81726    0.13380   6.108 1.27e-09 ***\nIsFirst4        -2.08275    0.23861  -8.729  < 2e-16 ***\nIsRd64          -1.90091    0.24268  -7.833 8.71e-15 ***\nIsRd32          -1.49297    0.25236  -5.916 4.04e-09 ***\nIsRd16          -0.87063    0.26330  -3.307 0.000965 ***\nIsRd8           -0.66700    0.30565  -2.182 0.029239 *  \nIs15             0.62959    0.29513   2.133 0.033055 *  \nIs5             -0.81295    0.23441  -3.468 0.000539 ***\nSizeMedium      -0.65313    0.05435 -12.017  < 2e-16 ***\nSizeSmall       -1.03135    0.12132  -8.501  < 2e-16 ***\nMajorYes         1.14217    0.04608  24.784  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7954 on 1568 degrees of freedom\n  (48 observations deleted due to missingness)\nMultiple R-squared:  0.6635,\tAdjusted R-squared:  0.6602 \nF-statistic: 206.1 on 15 and 1568 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nExcluding IsMarchMadess, the non-log transformed model had 20 statistically significant variables, while the log-transformed model had 13. \n\nThe non-log transformed model differed from the log-transformed model with the inclusion of the UpsetLoss, FavoriteWin, UnderdogWin, IsRd4, Is13, Is9, Is4, Is3, IsEarlyEvening, IsLateAfternoon, and IsMidAfternoon variables. \n\nThe log transformed model differed from the non-log transformed model with the inclusion of the IsWinner, FavoriteLoss, UnderdogLoss, and Size variables. \n\nThe two models once again had the same p-value (< 2.2e-16) but the non-log transformed model once again had the larger adjusted r squared (0.7038 vs. 0.6602). \n\n# Comparing the Models Using Adjusted r-squared, AIC, and BIC\n\nI have compiled a final summary of all six non-log transformed models, and a summary for the six log-transformed models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels <- list(IsMarchMadnessLR, GameOutcomeLR, TournamentRelatedLR, SchoolRelatedLR, AllVariablesLR, SigVariablesLR)\nstargazer(models, \n          title = \"Linear Regression Models\", \n          align = TRUE, \n          single.row = TRUE,\n          type = \"text\", \n          font.size = \"small\",\n          add.lines = list(c(\"AIC\", \n                             round(AIC(IsMarchMadnessLR), 2), \n                             round(AIC(GameOutcomeLR), 2), \n                             round(AIC(TournamentRelatedLR), 2), \n                             round(AIC(SchoolRelatedLR), 2), \n                             round(AIC(AllVariablesLR), 2),\n                             round(AIC(SigVariablesLR), 2)), \n                           c(\"BIC\", \n                             round(BIC(IsMarchMadnessLR), 2), \n                             round(BIC(GameOutcomeLR), 2), \n                             round(BIC(TournamentRelatedLR), 2), \n                             round(BIC(SchoolRelatedLR), 2), \n                             round(BIC(AllVariablesLR), 2),\n                             round(BIC(SigVariablesLR), 2)))) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nLinear Regression Models\n=================================================================================================================================================================================\n                                                                                         Dependent variable:                                                                     \n                    -------------------------------------------------------------------------------------------------------------------------------------------------------------\n                                                                                           Mention_Volume                                                                        \n                               (1)                       (2)                       (3)                       (4)                       (5)                        (6)            \n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\nIsMarchMadness       2,150.268*** (130.132)    1,248.844*** (120.370)    23,445.480*** (892.060)    2,104.942*** (126.861)   23,193.970*** (786.221)    23,396.590*** (764.397)  \nIsWinnerYes                                                                                                                   1,048.415 (1,065.283)                              \nUpsetWinYes                                   4,381.744*** (1,009.731)                                                        7,102.001*** (839.815)     7,154.288*** (768.309)  \nUpsetLossYes                                                                                                                  3,839.192*** (838.703)     3,937.226*** (584.177)  \nFavoriteWinYes                                 6,681.318*** (701.888)                                                         2,504.379*** (950.118)     2,611.989*** (531.591)  \nFavoriteLossYes                                4,532.355*** (513.694)                                                           968.625 (947.508)                                \nUnderdogWinYes                                 5,265.937*** (345.628)                                                         3,029.861*** (878.177)     3,028.715*** (283.613)  \nUnderdogLossYes                                1,779.368*** (345.628)                                                          1,107.887 (873.468)                               \nIsGameDay                                                                                                                       -100.411 (880.612)                               \nIsDayAfterGame                                                             -335.408** (167.289)                                -265.745* (147.212)                               \nIsFirst4                                                                 -22,897.870*** (894.474)                            -22,583.090*** (788.846)   -22,793.330*** (768.044) \nIsRd64                                                                   -22,341.780*** (903.967)                            -22,352.730*** (799.164)   -22,658.560*** (775.934) \nIsRd32                                                                   -21,030.360*** (914.912)                            -21,261.160*** (806.371)   -21,514.150*** (786.946) \nIsRd16                                                                   -20,197.160*** (923.072)                            -19,989.550*** (815.030)   -20,233.700*** (805.009) \nIsRd8                                                                    -17,579.510*** (989.145)                            -17,565.230*** (876.728)   -17,617.280*** (859.384) \nIsRd4                                                                   -14,517.690*** (1,072.525)                           -14,329.900*** (936.470)   -14,420.430*** (941.364) \nIsChamp                                                                                                                                                                          \nIs15                                                                      5,777.345*** (647.241)                              1,942.691*** (668.073)     2,351.403*** (575.086)  \nIs13                                                                      2,093.956*** (686.043)                             -1,818.909*** (677.575)    -1,617.316*** (599.769)  \nIs11                                                                                                                          -1,742.822** (678.815)                             \nIs9                                                                       2,032.296*** (616.835)                              -1,348.843** (622.467)     -1,147.685** (509.988)  \nIs8                                                                       2,086.841*** (575.695)                              -1,126.764* (636.157)                              \nIs7                                                                       3,004.990*** (498.296)                                -84.348 (559.997)                                \nIs6                                                                      7,239.143*** (1,318.326)                              832.813 (1,246.771)                               \nIs5                                                                       2,149.854*** (531.601)                             -2,904.689*** (588.191)    -2,692.837*** (476.905)  \nIs4                                                                       6,187.630*** (672.376)                              3,963.332*** (644.113)     4,492.858*** (608.050)  \nIs3                                                                       3,635.314*** (475.062)                              1,092.598** (494.371)      1,499.101*** (411.917)  \nIs1                                                                       2,570.985*** (416.446)                                                                                 \nIs0                                                                                                                                                                              \nIsEarlyEvening                                                                                                                  646.438 (470.425)        1,124.348*** (312.271)  \nIsLateAfternoon                                                           2,774.030*** (423.352)                              1,999.720*** (530.688)     2,558.360*** (377.143)  \nIsLateEvening                                                            -1,217.310*** (376.697)                               -858.932* (472.921)                               \nIsMidAfternoon                                                            1,342.854*** (503.565)                              1,470.798*** (550.893)     2,123.854*** (426.935)  \nIsEarlyAfternoon                                                                                                                                                                 \nSizeMedium                                                                                          -695.316*** (166.956)     -505.874*** (103.725)                              \nSizeSmall                                                                                            -732.447* (378.056)       -402.884* (230.774)                               \nMajorYes                                                                                             763.765*** (140.525)      842.340*** (87.834)       1,056.045*** (77.088)   \nConstant               720.538*** (80.467)       720.538*** (69.218)       734.180*** (54.774)       508.443*** (127.016)      424.485*** (78.704)        174.705*** (62.267)    \n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\nAIC                          30243.8                  29757.29                   28131.13                  30160.56                  27712.21                   27727.59         \nBIC                         30259.99                  29800.47                   28254.59                  30192.94                  27900.08                   27851.04         \nObservations                  1,632                     1,632                     1,584                     1,632                     1,584                      1,584           \nR2                            0.143                     0.368                     0.623                     0.189                     0.715                      0.708           \nAdjusted R2                   0.143                     0.366                     0.618                     0.187                     0.709                      0.704           \nResidual Std. Error   2,554.742 (df = 1630)     2,197.609 (df = 1625)     1,725.566 (df = 1562)     2,488.128 (df = 1627)     1,506.217 (df = 1550)      1,519.184 (df = 1562)   \nF Statistic         273.034*** (df = 1; 1630) 157.803*** (df = 6; 1625) 122.909*** (df = 21; 1562) 94.824*** (df = 4; 1627) 117.808*** (df = 33; 1550) 180.154*** (df = 21; 1562)\n=================================================================================================================================================================================\nNote:                                                                                                                                                 *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n\n```{.r .cell-code}\nlogmodels <- list(IsMarchMadnessLRlog, GameOutcomeLRlog, TournamentRelatedLRlog, SchoolRelatedLRlog, AllVariablesLRlog, SigVariablesLRlog)\nstargazer(logmodels, \n          title = \"Linear Regression Models - log\", \n          align = TRUE, \n          single.row = TRUE,\n          type = \"text\", \n          font.size = \"small\",\n          add.lines = list(c(\"AIC\", \n                             round(AIC(IsMarchMadnessLRlog), 2), \n                             round(AIC(GameOutcomeLRlog), 2), \n                             round(AIC(TournamentRelatedLRlog), 2), \n                             round(AIC(SchoolRelatedLRlog), 2), \n                             round(AIC(AllVariablesLRlog), 2),\n                             round(AIC(SigVariablesLRlog), 2)), \n                           c(\"BIC\", \n                             round(BIC(IsMarchMadnessLRlog), 2), \n                             round(BIC(GameOutcomeLRlog), 2), \n                             round(BIC(TournamentRelatedLRlog), 2), \n                             round(BIC(SchoolRelatedLRlog), 2), \n                             round(BIC(AllVariablesLRlog), 2),\n                             round(BIC(SigVariablesLRlog), 2)))) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nLinear Regression Models - log\n================================================================================================================================================================================\n                                                                                        Dependent variable:                                                                     \n                    ------------------------------------------------------------------------------------------------------------------------------------------------------------\n                                                                                        log(Mention_Volume)                                                                     \n                               (1)                       (2)                       (3)                       (4)                       (5)                       (6)            \n--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\nIsMarchMadness          1.412*** (0.060)          1.154*** (0.062)          2.731*** (0.218)          1.352*** (0.046)          3.667*** (0.414)           2.929*** (0.237)     \nIsWinnerYes                                                                                                                       0.128 (0.561)            0.980*** (0.122)     \nUpsetWinYes                                                                                                                     1.438*** (0.442)           1.566*** (0.294)     \nUpsetLossYes                                                                                                                      0.490 (0.442)                                 \nFavoriteWinYes                                    1.937*** (0.264)                                                               -0.267 (0.500)                                 \nFavoriteLossYes                                   1.471*** (0.264)                                                               -0.578 (0.499)            0.756*** (0.196)     \nUnderdogWinYes                                    1.440*** (0.177)                                                               -0.290 (0.462)                                 \nUnderdogLossYes                                   0.743*** (0.177)                                                               -0.332 (0.460)            0.817*** (0.134)     \nIsGameDay                                                                   0.923*** (0.121)                                    1.240*** (0.464)                                \nIsDayAfterGame                                                                                                                   -0.132* (0.078)                                \nIsFirst4                                                                    -1.888*** (0.222)                                   -2.826*** (0.415)         -2.083*** (0.239)     \nIsRd64                                                                      -1.580*** (0.232)                                   -2.632*** (0.421)         -1.901*** (0.243)     \nIsRd32                                                                      -1.069*** (0.251)                                   -2.232*** (0.425)         -1.493*** (0.252)     \nIsRd16                                                                      -0.693** (0.270)                                    -1.558*** (0.429)         -0.871*** (0.263)     \nIsRd8                                                                                                                           -1.404*** (0.462)          -0.667** (0.306)     \nIsRd4                                                                                                                            -0.896* (0.493)                                \nIsChamp                                                                                                                                                                         \nIs15                                                                                                                             0.750** (0.352)           0.630** (0.295)      \nIs13                                                                                                                              0.102 (0.357)                                 \nIs11                                                                                                                              0.093 (0.357)                                 \nIs9                                                                                                                               0.287 (0.328)                                 \nIs8                                                                                                                               0.191 (0.335)                                 \nIs7                                                                                                                               0.427 (0.295)                                 \nIs6                                                                                                                               0.245 (0.657)                                 \nIs5                                                                                                                             -0.688** (0.310)          -0.813*** (0.234)     \nIs4                                                                                                                               0.268 (0.339)                                 \nIs3                                                                                                                               0.026 (0.260)                                 \nIs1                                                                                                                                                                             \nIs0                                                                                                                                                                             \nIsEarlyEvening                                                                                                                   -0.142 (0.248)                                 \nIsLateAfternoon                                                                                                                  -0.203 (0.279)                                 \nIsLateEvening                                                                                                                   -0.585** (0.249)                                \nIsMidAfternoon                                                                                                                    0.006 (0.290)                                 \nIsEarlyAfternoon                                                                                                                                                                \nSizeMedium                                                                                            -0.684*** (0.060)         -0.662*** (0.055)         -0.653*** (0.054)     \nSizeSmall                                                                                             -1.096*** (0.137)         -1.033*** (0.122)         -1.031*** (0.121)     \nMajorYes                                                                                              1.098*** (0.051)          1.148*** (0.046)           1.142*** (0.046)     \nConstant                5.951*** (0.037)          5.951*** (0.036)          5.951*** (0.035)          5.576*** (0.046)          5.548*** (0.041)           5.544*** (0.041)     \n--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\nAIC                          5166.33                   5033.57                   4826.28                   4297.86                   3796.8                    3787.85          \nBIC                          5182.52                   5071.35                   4869.22                   4330.24                   3984.67                    3879.1          \nObservations                  1,632                     1,632                     1,584                     1,632                     1,584                     1,584           \nR2                            0.254                     0.316                     0.344                     0.563                     0.669                     0.663           \nAdjusted R2                   0.254                     0.314                     0.342                     0.562                     0.662                     0.660           \nResidual Std. Error     1.177 (df = 1630)         1.128 (df = 1626)         1.107 (df = 1577)         0.901 (df = 1627)         0.793 (df = 1550)         0.795 (df = 1568)     \nF Statistic         554.943*** (df = 1; 1630) 149.983*** (df = 5; 1626) 138.039*** (df = 6; 1577) 524.973*** (df = 4; 1627) 95.004*** (df = 33; 1550) 206.086*** (df = 15; 1568)\n================================================================================================================================================================================\nNote:                                                                                                                                                *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\nAllVariablesLR had the highest adjusted r-squared (0.709) while SigVariablesLR had the next highest (0.704). When it came to AIC and BIC, however, the numbers for the log-adjusted models were substantially lower - AIC was 3,787.85 to 5,166.33 for the log-adjusted models and 27,727.59 to 30,243.8 for the non-adjusted ones; BIC was similar, varying from 3,879.1 to 5,182.52 for the log-adjusted models and 27,851.04 to 30,259.99 for the non-adjusted ones. \n\nHigh values of AIC and BIC suggest that the model may not be a good fit for the data and that it may be overfitting. Accordingly, while the adjusted r squared was highest for the non-log models, I believe a log-adjusted model is a better fit for the data overall. Specifically, SigVariablesLRlog - the model for all significant variables from the four categories of variables (is march madness, game outcome-related, tournament-related, and school-related) is the best fitting model, with the lowest AIC and BIC, and the highest adjusted r squared amongst the log-adjusted models.\n\n# Diagnostics \n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2,3))\nplot(SigVariablesLRlog, which = 1:5)\n```\n\n::: {.cell-output-display}\n![](FPRedoneWithLog_DarronBunt_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n### Residuals vs. Fitted\n\nThere is a slight curve to the residuals vs. fitted. While there are some outliers, this is mostly a well behaving residuals vs. fitted plot. This suggests the model is capturing most of the relationship. \n\n### Q-Q Residuals\n\nThere is greater variability/outliers at the lower end of this plot and then points fall nearly perfectly along the line until there is again slight variability at the top end. This suggests that the residuals are largely normally distributed. \n\n### Scale-Location\n\nIn the scale-location plot, the red line should be approximately horizontal, which this is. The points also appear to be randomly scattered around the line. These two observations suggest that the residuals have a largely consistent spread across the range of fitted values. \n\n### Cook's Distance\n\nIf I use 4/n as my threshold for Cook's distance, this plot surpasses that threshold; however, if I use 1, then this plot does not surpass that threshold. The presence of influential observations makes sense within the research context and arguably, the higher threshold is appropriate. \n\n### Residuals vs. Leverage\n\nThere are no points outside of the lines for Cook's distance. \n\n# Conclusion\n\nThe results for both hypotheses were statistically significant - \n\n1. **Participation in the men's March Madness tournament increases online conversation about the schools that are involved**\n2. This increase in conversation volume for each school is influenced by three types of additional mediating variables: **game-outcome related variables, school-related variables, and tournament related variables.**\n\nTesting of the different variables and models evidenced that there are a large number of variables and factors that can contribute to differences in conversation volume for the schools/teams involved in the tournament in a statistically significant fashion. While I believe I was able to determine many of the factors that can help to predict an increase in volume, I think this also presents a significant limitation when it comes to the utility of this research for the schools involved. When it comes to social media management strategies for the teams involved in March Madness, a model with tens of different variables is not going to be easy to use; in this sense I believe that quantitative analysis to determine the statistically significant factors followed by qualitative analysis and subsequent overarching recommendations leveraging both components would provide such groups with the best opportunities to leverage the information when moving forward. ",
    "supporting": [
      "FPRedoneWithLog_DarronBunt_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}