{
  "hash": "6ebfdc777e8c2bb103b511e0fd20bcd8",
  "result": {
    "markdown": "---\ntitle: \"603_Final_Project_Saisrinivas\"\nauthor: \"Saisrinivas Ambatipudi\"\ndate: \"2023-04-20\"\noutput:\n  word_document: default\n  html_document: default\nTeam Members: Akhilesh Kumar, Sai Srinivas\nProject Title: Investigating Factors Affecting Blood Donation Frequency and Building\n  a Donor Retention Strategy\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n\n## Data Read & Exploratory Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBD <- read_csv(\"C:/Back Up/UMass_Sem_2/DACSS_603/603_Spring_2023/posts/_data/transfusion_saisrinivas.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 748 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (5): Recency (months), Frequency (times), Monetary (c.c. blood), Time (m...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\ndata(BD)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in data(BD): data set 'BD' not found\n```\n:::\n\n```{.r .cell-code}\n# Convert \"whether he/she donated blood in March 2007\" to factor\nBD$`whether he/she donated blood in March 2007` <- factor(BD$`whether he/she donated blood in March 2007`,\n                                                         levels = c(0, 1),\n                                                         labels = c(\"No\", \"Yes\"))\n\n# summary of blood donation data\nsummary(BD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Recency (months) Frequency (times) Monetary (c.c. blood) Time (months)  \n Min.   : 0.000   Min.   : 1.000    Min.   :  250         Min.   : 2.00  \n 1st Qu.: 2.750   1st Qu.: 2.000    1st Qu.:  500         1st Qu.:16.00  \n Median : 7.000   Median : 4.000    Median : 1000         Median :28.00  \n Mean   : 9.507   Mean   : 5.515    Mean   : 1379         Mean   :34.28  \n 3rd Qu.:14.000   3rd Qu.: 7.000    3rd Qu.: 1750         3rd Qu.:50.00  \n Max.   :74.000   Max.   :50.000    Max.   :12500         Max.   :98.00  \n whether he/she donated blood in March 2007\n No :570                                   \n Yes:178                                   \n                                           \n                                           \n                                           \n                                           \n```\n:::\n\n```{.r .cell-code}\n# Check the dimensions of the data\ndim(BD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 748   5\n```\n:::\n\n```{.r .cell-code}\n# Check the column names\ncolnames(BD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Recency (months)\"                          \n[2] \"Frequency (times)\"                         \n[3] \"Monetary (c.c. blood)\"                     \n[4] \"Time (months)\"                             \n[5] \"whether he/she donated blood in March 2007\"\n```\n:::\n\n```{.r .cell-code}\n# Check the data types of each variable\nstr(BD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [748 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ Recency (months)                          : num [1:748] 2 0 1 2 1 4 2 1 2 5 ...\n $ Frequency (times)                         : num [1:748] 50 13 16 20 24 4 7 12 9 46 ...\n $ Monetary (c.c. blood)                     : num [1:748] 12500 3250 4000 5000 6000 1000 1750 3000 2250 11500 ...\n $ Time (months)                             : num [1:748] 98 28 35 45 77 4 14 35 22 98 ...\n $ whether he/she donated blood in March 2007: Factor w/ 2 levels \"No\",\"Yes\": 2 2 2 2 1 1 2 1 2 2 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   `Recency (months)` = col_double(),\n  ..   `Frequency (times)` = col_double(),\n  ..   `Monetary (c.c. blood)` = col_double(),\n  ..   `Time (months)` = col_double(),\n  ..   `whether he/she donated blood in March 2007` = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\n# Check for missing values\nsum(is.na(BD))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nThe blood transfusion dataset contain 748 samples with 5 input features:\nInput Features: • Recency (number of months since the last donation) •\nFrequency (total number of donations) • Monetary (total blood donated in\nc.c.) • Time (number of months since the first donation) • Age (age of\nthe donor)\n\nSource:\nhttps://www.kaggle.com/datasets/ninalabiba/blood-transfusion-dataset\n\nThis summary function presents a statistical description of a dataset\nrelated to blood donation, with 748 observations and five variables:\nRecency, Frequency, Monetary, Time, and whether the individual donated\nblood in March 2007. Here's a breakdown of each variable:\n\nRecency (months): This variable represents the number of months since\nthe last blood donation. The minimum value is 0 months, indicating that\nsome individuals donated blood very recently. The mean is 9.507 months,\nsuggesting that, on average, people donated blood around 9.5 months ago.\nThe maximum value is 74 months, which means the longest gap between\ndonations is 74 months.\n\nFrequency (times): This variable shows the total number of times an\nindividual has donated blood. The minimum value is 1, meaning that at\nleast one person has only donated blood once. The mean is 5.515 times,\nindicating that people, on average, have donated blood about 5.5 times.\nThe maximum value is 50 times, showing that some individuals have\ndonated blood quite frequently.\n\nMonetary (c.c. blood): This variable represents the total volume of\nblood donated by an individual, measured in cubic centimeters (c.c.).\nThe minimum value is 250 c.c., which corresponds to the minimum single\ndonation volume. The mean is 1379 c.c., suggesting that, on average,\nindividuals have donated around 1.379 liters of blood. The maximum value\nis 12,500 c.c., indicating that the highest total volume donated by a\nperson is 12.5 liters.\n\nTime (months): This variable measures the length of time an individual\nhas been donating blood. The minimum value is 2 months, suggesting that\nsome individuals are relatively new to blood donation. The mean is 34.28\nmonths, indicating that, on average, people have been donating blood for\nabout 34.3 months. The maximum value is 98 months, showing that some\nindividuals have been donating blood for a long time.\n\nWhether he/she donated blood in March 2007: This is a binary variable\nthat indicates if an individual donated blood in March 2007. The mean is\n0.238, which means that about 23.8% of the individuals in the dataset\ndonated blood in that specific month.\n\nThe summary function provides an overview of the dataset's key\nstatistics, such as minimum, 1st quartile, median, mean, 3rd quartile,\nand maximum values for each variable. This information helps to\nunderstand the distribution, central tendency, and spread of the data.\n\n### Distribution of variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of Recency\n\nggplot(BD, aes(x = as.numeric(`Recency (months)`))) +\n  geom_histogram(binwidth = 1, fill = \"blue\", color = \"black\") +\n  labs(title = \"Histogram of Recency\", x = \"Recency (months)\", y = \"Number of Donors\") +\n  theme(plot.title = element_text(hjust = 0.5), \n        panel.background = element_blank(), \n        axis.line = element_line(colour = \"black\"), \n        axis.title = element_text(size = 10), \n        axis.text = element_text(size = 8))+\n        geom_text(stat = \"count\", aes(label = ..count..), vjust = -0.5, size=3)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.\nℹ Please use `after_stat(count)` instead.\n```\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Create a box plot for the Recency (months) variable\n\nggplot(BD, aes(x = \"\", y = `Recency (months)`)) +\n  geom_boxplot(fill = \"#00B945\", color = \"black\") +\n  labs(x = \"\", y = \"Recency (months)\", title = \"Box Plot of Recency (months)\") +\n  theme_bw() +\n  theme(\n    axis.title = element_text(color = \"black\", size = 10, face = \"bold\"), \n    axis.text = element_text(color = \"black\", size = 8), \n    plot.title = element_text(color = \"black\", hjust = 0.5),\n    panel.border = element_rect(color = \"black\", fill = NA, size = 1)\n  ) +\n  geom_text(\n    aes(x = 1.5, y = quantile(`Recency (months)`, 0.25), label = paste(\"Q1 = \", round(quantile(`Recency (months)`, 0.25), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = median(`Recency (months)`), label = paste(\"Median = \", round(median(`Recency (months)`), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 1.5, y = quantile(`Recency (months)`, 0.75), label = paste(\"Q3 = \", round(quantile(`Recency (months)`, 0.75), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = max(`Recency (months)`), label = paste(\"Max = \", round(max(`Recency (months)`), 0))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = min(`Recency (months)`), label = paste(\"Min = \", round(min(`Recency (months)`), 0))),\n    color = \"black\", size = 3\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The `size` argument of `element_rect()` is deprecated as of ggplot2 3.4.0.\nℹ Please use the `linewidth` argument instead.\n```\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n:::\n\n\nThe Recency (months) histogram and box plot provide insights into the\ntime elapsed since the last blood donation. The histogram indicates that\nthe majority of donors have donated blood more recently, with 50% of\ndonors having a recency of 7 months or less. The distribution is\nright-skewed, indicating that there are fewer donors with a longer\nrecency period. The box plot shows that the median recency is 7 months,\nwith 25% of donors having a recency of 2.75 months or less and 75%\nhaving a recency of 14 months or less.\n\nThe Recency (months) bar chart provides a visual representation of the\nnumber of donors who donated blood at different recency periods. The\nhighest number of donors, 174, donated blood around the 2-month mark,\nand the number of donors gradually decreases with longer recency\nperiods. However, there are some outliers in the data, with the maximum\nrecency observed being 74 months.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of Frequency\nggplot(BD, aes(x = as.numeric(`Frequency (times)`))) +\n  geom_histogram(binwidth = 1, fill = \"red\", color = \"black\") +\n  labs(title = \"Histogram of Frequency\", x = \"Frequency (Times)\", y = \"Number of Donors\") +\n  theme(plot.title = element_text(hjust = 0.5), \n        panel.background = element_blank(), \n        axis.line = element_line(colour = \"black\"), \n        axis.title = element_text(size = 10), \n        axis.text = element_text(size = 8))+\n        geom_text(stat = \"count\", aes(label = ..count..), vjust = -0.5, size=3)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Create a box plot for the Frequency (times) variable\n\nggplot(BD, aes(x = \"\", y = `Frequency (times)`)) +\n  geom_boxplot(fill = \"#00B945\", color = \"black\") +\n  labs(x = \"\", y = \"Frequency (times)\", title = \"Box Plot of Frequency (times)\") +\n  theme_bw() +\n  theme(\n    axis.title = element_text(color = \"black\", size = 10, face = \"bold\"), \n    axis.text = element_text(color = \"black\", size = 8), \n    plot.title = element_text(color = \"black\", hjust = 0.5),\n    panel.border = element_rect(color = \"black\", fill = NA, size = 1)\n  ) +\n  geom_text(\n    aes(x = 1.5, y = quantile(`Frequency (times)`, 0.25), label = paste(\"Q1 = \", round(quantile(`Frequency (times)`, 0.25), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = median(`Frequency (times)`), label = paste(\"Median = \", round(median(`Frequency (times)`), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 1.5, y = quantile(`Frequency (times)`, 0.75), label = paste(\"Q3 = \", round(quantile(`Frequency (times)`, 0.75), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = max(`Frequency (times)`), label = paste(\"Max = \", round(max(`Frequency (times)`), 0))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = min(`Frequency (times)`), label = paste(\"Min = \", round(min(`Frequency (times)`), 0))),\n    color = \"black\", size = 3\n  )\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n:::\n\n\nThe histogram of Frequency (times) shows the distribution of the number\nof times each donor has donated blood. The x-axis represents the number\nof times donated, while the y-axis shows the number of donors falling\nwithin each bin. The plot indicates that the majority of donors have\ndonated blood 1-2 times, with the number of donors decreasing as the\nnumber of donations increases. The distribution is highly right-skewed,\nindicating that there are fewer donors who have donated blood many\ntimes.\n\nThe box plot of Frequency (times) shows that the median number of\ndonations made by each donor is 4, with 25% of donors having made 2 or\nfewer donations and 75% having made 7 or fewer donations. This indicates\nthat the majority of donors have made a relatively small number of\ndonations. The maximum number of donations observed in the data is 50,\nwhile the minimum number of donations is 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of Monetary (Total Blood Donated in c.c.)\nggplot(BD, aes(x = `Monetary (c.c. blood)`)) +\n  geom_histogram(binwidth = 250, fill = \"green\", color = \"black\") +\n  labs(title = \"Histogram of Monetary (Total Blood Donated in c.c.)\", x = \"Total Blood Donated in (c.c.)\", y = \"Number of Donors\") +\n  theme(plot.title = element_text(hjust = 0.5), \n        panel.background = element_blank(), \n        axis.line = element_line(colour = \"black\"), \n        axis.title = element_text(size = 10), \n        axis.text = element_text(size = 8)) +\n  geom_text(stat = \"count\", aes(label = ..count..), vjust = -0.5, size = 3)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Create a box plot for the Monetary (c.c. blood) variable\n\nggplot(BD, aes(x = \"\", y = `Monetary (c.c. blood)`)) +\n  geom_boxplot(fill = \"#00B945\", color = \"black\") +\n  labs(x = \"\", y = \"Monetary (c.c. blood)\", title = \"Box Plot of Monetary (c.c. blood)\") +\n  theme_bw() +\n  theme(\n    axis.title = element_text(color = \"black\", size = 10, face = \"bold\"), \n    axis.text = element_text(color = \"black\", size = 8), \n    plot.title = element_text(color = \"black\", hjust = 0.5),\n    panel.border = element_rect(color = \"black\", fill = NA, size = 1)\n  ) +\n  geom_text(\n    aes(x = 1.5, y = quantile(`Monetary (c.c. blood)`, 0.25), label = paste(\"Q1 = \", round(quantile(`Monetary (c.c. blood)`, 0.25), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = median(`Monetary (c.c. blood)`), label = paste(\"Median = \", round(median(`Monetary (c.c. blood)`), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 1.5, y = quantile(`Monetary (c.c. blood)`, 0.75), label = paste(\"Q3 = \", round(quantile(`Monetary (c.c. blood)`, 0.75), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = max(`Monetary (c.c. blood)`), label = paste(\"Max = \", round(max(`Monetary (c.c. blood)`), 0))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = min(`Monetary (c.c. blood)`), label = paste(\"Min = \", round(min(`Monetary (c.c. blood)`), 0))),\n    color = \"black\", size = 3\n  )\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n\nThe box plot for Monetary (c.c. blood) indicates that the median\ndonation amount is 1000 cubic centimeters, with 25% of donors having\ndonated 500 cubic centimeters or less and 75% having donated 1750 cubic\ncentimeters or less. The data also contains several outliers, with the\nmaximum donation amount being 12,500 cubic centimeters. This suggests\nthat while most donors donate smaller amounts, there are some donors who\ndonate significantly larger amounts.\n\nSimilarly, the histogram for Monetary (c.c. blood) reveals a\nright-skewed distribution, with the majority of donors donating smaller\namounts and fewer donors donating larger amounts. The peak of the\ndistribution is observed at the bin corresponding to 500 cubic\ncentimeters, with the number of donors decreasing as the donation amount\nincreases. The presence of outliers in the box plot indicates that there\nare some donors who have donated very large amounts of blood.\n\nIt's worth noting that there is a correlation between the Monetary (c.c.\nblood) variable and the Frequency (times) variable. Since each donation\ncorresponds to 250 cc, a frequency of 1 corresponds to 250 cc, a\nfrequency of 2 corresponds to 500 cc, and so on. This implies that\ndonors who donate more frequently are also likely to donate larger\namounts of blood overall.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of Time (months)\n\nggplot(BD, aes(x = `Time (months)`)) +\n  geom_histogram(binwidth = 1, fill = \"green\", color = \"black\") +\n  labs(title = \"Histogram of Time (months)\", x = \"Time (Months)\", y = \"Number of Donors\") +\n  theme(plot.title = element_text(hjust = 0.5), \n        panel.background = element_blank(), \n        axis.line = element_line(colour = \"black\"), \n        axis.title = element_text(size = 10), \n        axis.text = element_text(size = 8))\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Create a box plot for the Monetary (c.c. blood) variable\n\nggplot(BD, aes(x = \"\", y = `Time (months)`)) +\n  geom_boxplot(fill = \"#00B945\", color = \"black\") +\n  labs(x = \"\", y = \"Time (months)\", title = \"Box Plot of Time (months)\") +\n  theme_bw() +\n  theme(\n    axis.title = element_text(color = \"black\", size = 10, face = \"bold\"), \n    axis.text = element_text(color = \"black\", size = 8), \n    plot.title = element_text(color = \"black\", hjust = 0.5),\n    panel.border = element_rect(color = \"black\", fill = NA, size = 1)\n  ) +\n  geom_text(\n    aes(x = 1.5, y = quantile(`Time (months)`, 0.25), label = paste(\"Q1 = \", round(quantile(`Time (months)`, 0.25), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = median(`Time (months)`), label = paste(\"Median = \", round(median(`Time (months)`), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 1.5, y = quantile(`Time (months)`, 0.75), label = paste(\"Q3 = \", round(quantile(`Time (months)`, 0.75), 2))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = max(`Time (months)`), label = paste(\"Max = \", round(max(`Time (months)`), 0))),\n    color = \"black\", size = 3\n  ) +\n  geom_text(\n    aes(x = 0.5, y = min(`Time (months)`), label = paste(\"Min = \", round(min(`Time (months)`), 0))),\n    color = \"black\", size = 3\n  )\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\nThe histogram plot of Time (months) also shows that the distribution is\nright-skewed, with a peak at around 2-4 months, indicating that many\ndonors donate again within a few months of their previous donation. As\nthe time since the last donation increases, the number of donors\ndecreases, with a small peak observed around 20-25 months. There are\nalso a few donors who have a very long time since their last donation,\nas indicated by the outliers in the box plot.\n\nThe box plot of Time (months) shows that the median time between a\ndonor's first donation and their most recent donation is around 28\nmonths, with 25% of donors having a time period of 16 months or less and\n75% having a time period of 50 months or less. There are several\noutliers in the data, with the maximum time period being 98 months. This\nindicates that while the majority of donors have donated more recently,\nthere are a few donors who donated a long time ago but still continued\nto donate blood.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bar chart of Whether he/she donated blood in March 2007\n\nggplot(data = BD, aes(x = factor(`whether he/she donated blood in March 2007`))) +\n  geom_bar(fill = c(\"red\", \"green\"), color = \"black\") +\n  labs(title = \"Blood Donation in March 2007\", \n       x = \"Blood Donation in March 2007 \", \n       y = \"Number of Donors\", \n       title.position = \"plot\") +\n  scale_x_discrete(labels = c(\"No\", \"Yes\")) +\n  theme(plot.title = element_text(hjust = 0.5),\n        panel.background = element_blank(),\n        panel.grid.major = element_blank(),\n        panel.grid.minor = element_blank(),\n        axis.line = element_line(colour = \"black\"),\n        axis.text = element_text(colour = \"black\"),\n        axis.title = element_text(colour = \"black\"))\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Create a pie chart\nggplot(data = BD, aes(x = \"\", fill = `whether he/she donated blood in March 2007`, group = `whether he/she donated blood in March 2007`)) +\n  geom_bar(width = 1, color = \"black\") +\n  coord_polar(theta = \"y\") +\n  labs(title = \"Blood Donation in March 2007\",\n       fill = \"Blood Donation in March 2007\",\n       x = \"\", y = \"\") +\n  scale_fill_manual(values = c(\"#FF8C00\", \"#1F3552\")) +  # navy blue and dark orange color scheme\n  theme_void() +\n  theme(plot.title = element_text(hjust = 0.5, color = \"#FF8C00\", size = 18)) +  # center title and change color to dark orange\n  geom_text(aes(label = scales::percent(..count../sum(..count..)), y = ..count..), stat = \"count\", position = position_stack(vjust = 0.5), size = 5) +\n  labs(caption = \"Source: Blood Transfusion Service Center Data Set\")\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n:::\n\n\nThe bar chart displays the number of donors who donated blood in March\n2007 and those who did not. Majority of donors did not donate blood in\nMarch 2007, with 570 donors falling into this category, while 178 donors\ndid donate blood in March 2007. The pie chart shows that only about\n23.8% of donors donated blood in March 2007, while the remaining 76.2%\ndid not.\n\nOverall, both charts indicate that a relatively small proportion of\ndonors donated blood in March 2007, which may be important to consider\nwhen analyzing the other variables in the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(BD[, c(\"Recency (months)\", \"Frequency (times)\", \"Monetary (c.c. blood)\", \"Time (months)\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                      Recency (months) Frequency (times) Monetary (c.c. blood)\nRecency (months)             1.0000000        -0.1827455            -0.1827455\nFrequency (times)           -0.1827455         1.0000000             1.0000000\nMonetary (c.c. blood)       -0.1827455         1.0000000             1.0000000\nTime (months)                0.1606181         0.6349403             0.6349403\n                      Time (months)\nRecency (months)          0.1606181\nFrequency (times)         0.6349403\nMonetary (c.c. blood)     0.6349403\nTime (months)             1.0000000\n```\n:::\n\n```{.r .cell-code}\n# Compute the correlation matrix\ncorr_matrix <- cor(BD[, c(\"Recency (months)\", \"Frequency (times)\", \"Monetary (c.c. blood)\", \"Time (months)\")])\n\n# Create the correlation plot\ncorrplot(corr_matrix, method = \"circle\", type = \"upper\", tl.col = \"black\", tl.srt = 45)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nBased on the correlation table, there is a weak negative correlation\nbetween Recency (months) and Frequency (times) with a correlation\ncoefficient of -0.18. This means that as the number of months since the\nlast donation increases, the frequency of blood donations decreases\nslightly.\n\nThere is also a strong positive correlation between Frequency (times)\nand Monetary (c.c. blood) with a correlation coefficient of 1.0. This\nmeans that as the frequency of blood donations increases, the amount of\nblood donated also tends to increase.\n\nMoreover, there is a moderate positive correlation between Time (months)\nand Frequency (times) as well as Monetary (c.c. blood) with correlation\ncoefficients of 0.63 and 0.63 respectively. This means that donors who\ndonate more frequently tend to do so over a longer period of time, and\nthey also tend to donate more blood overall.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = BD, aes(x = `Recency (months)`, y = `whether he/she donated blood in March 2007`, color = `whether he/she donated blood in March 2007`)) +\n  geom_point() +\n  labs(title = \"Donation vs Recency\", x = \"Recency (months)\", y = \"Donation\", color = \"Donated\") +\n  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(size=1, color=\"black\")) +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = BD, aes(x = `Frequency (times)`, y = `whether he/she donated blood in March 2007`, color = `whether he/she donated blood in March 2007`)) +\n  geom_point() +\n  labs(title = \"Donation vs Frequency\", x = \"Frequency (times)\", y = \"Donation\", color = \"Donated\") +\n  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(size=1, color=\"black\")) +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = BD, aes(x = `Monetary (c.c. blood)`, y = `whether he/she donated blood in March 2007`, color = `whether he/she donated blood in March 2007`)) +\n  geom_point() +\n  labs(title = \"Donation vs Monetary\", x = \"Monetary (c.c. blood)\", y = \"Donation\", color = \"Donated\") +\n  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(size=1, color=\"black\")) +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-8-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = BD, aes(x = `Time (months)`, y = `whether he/she donated blood in March 2007`, color = `whether he/she donated blood in March 2007`)) +\n  geom_point() +\n  labs(title = \"Donation vs Time\", x = \"Time (months)\", y = \"Donation\", color = \"Donated\") +\n  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(size=1, color=\"black\")) +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-8-4.png){width=672}\n:::\n:::\n\n\nThe first scatterplot shows the relationship between recency of donation\nand the likelihood of donating blood in March 2007. The second\nscatterplot shows the relationship between frequency of donation and the\nlikelihood of donating blood in March 2007. The third scatterplot shows\nthe relationship between the amount of blood donated (measured in cubic\ncentimeters) and the likelihood of donating blood in March 2007.\nFinally, the fourth scatterplot shows the relationship between the\nlength of time since the donor's first donation and the likelihood of\ndonating blood in March 2007.\n\nIn general, it appears that more frequent, recent, and higher volume\ndonations are associated with a higher likelihood of donating blood in\nMarch 2007. The fourth scatterplot shows a slightly different trend,\nwith a higher likelihood of donation at around the 30-month mark since\nthe first donation. However, none of scatterplots show a strong\nrelationship between the predictor variable and the likelihood of\ndonating blood in March 2007, as indicated by the relatively flat\nregression lines.\n\n## Hypothesis\n\n1.  Hypothesis 1: There is a significant difference in the past\n    frequency of blood donations between donors who have donated in\n    March 2007 and those who have not.\n\nConfounding variables recency of blood donations, Monetary Value of\nblood donations, Time (months) of blood donations\n\n2.  Hypothesis 2: There is a significant difference in the Recency of\n    blood donations between donors who have donated in March 2007 and\n    those who have not.\n\nConfounding variables: Past frequency of blood donations, Monetary Value\nof blood donations, Time (months) of blood donations\n\n3.  Hypothesis 3: There is a significant difference in the Monetary\n    Value of blood donations between donors who have donated in March\n    2007 and those who have not.\n\nConfounding variables: Past frequency of blood donations, Recency of\nblood donations, Time (months) of blood donations\n\n4.  Hypothesis 4: There is a significant difference in the Time (months)\n    of blood donations between donors who have donated in March 2007 and\n    those who have not.\n\nConfounding variables: Past frequency of blood donations, Recency of\nblood donations, Monetary Value of blood donations\n\n5.  Hypothesis 5: Donors who have donated blood more frequently in the\n    past (i.e. a higher average number of donations per month) are more\n    likely to donate again in March 2007.\n\n6.  Hypothesis 6: Donors who have donated higher average Monetary (c.c.\n    blood) (per month) are more likely to donate again in March 2007.\n\n7.  Hypothesis 7: Donors who have donated blood more recently (Recency\n    (months)) and with higher frequency (Frequency (times)) are more\n    likely to donate again in March 2007.\n\n8.  Hypothesis 8: Donors who have donated blood more recently (Recency\n    (months)) and with higher blood donation in past (Monetary (c.c.\n    blood)) are more likely to donate again in March 2007.\n\n## Logistic regression Analysis:\n\n### Hypothesis 1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 11\nmodel11 <- glm(`whether he/she donated blood in March 2007` ~ `Frequency (times)` * (`Recency (months)` + `Monetary (c.c. blood)` + `Time (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model11)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Frequency (times)` * (`Recency (months)` + `Monetary (c.c. blood)` + \n        `Time (months)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.8337  -0.7340  -0.4852  -0.1756   2.5925  \n\nCoefficients: (1 not defined because of singularities)\n                                              Estimate Std. Error z value\n(Intercept)                                 -1.122e+00  2.671e-01  -4.199\n`Frequency (times)`                          3.104e-01  5.713e-02   5.433\n`Recency (months)`                          -6.617e-02  2.607e-02  -2.538\n`Monetary (c.c. blood)`                             NA         NA      NA\n`Time (months)`                             -1.702e-02  1.031e-02  -1.651\n`Frequency (times)`:`Recency (months)`      -5.439e-03  3.919e-03  -1.388\n`Frequency (times)`:`Monetary (c.c. blood)` -1.016e-06  9.250e-06  -0.110\n`Frequency (times)`:`Time (months)`         -1.990e-03  1.163e-03  -1.712\n                                            Pr(>|z|)    \n(Intercept)                                 2.68e-05 ***\n`Frequency (times)`                         5.54e-08 ***\n`Recency (months)`                            0.0111 *  \n`Monetary (c.c. blood)`                           NA    \n`Time (months)`                               0.0987 .  \n`Frequency (times)`:`Recency (months)`        0.1652    \n`Frequency (times)`:`Monetary (c.c. blood)`   0.9125    \n`Frequency (times)`:`Time (months)`           0.0869 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 692.89  on 741  degrees of freedom\nAIC: 706.89\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nPRESS(model11)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 707.8452\n```\n:::\n\n```{.r .cell-code}\nBIC(model11)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 739.2094\n```\n:::\n\n```{.r .cell-code}\nAIC(model11)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 706.8876\n```\n:::\n\n```{.r .cell-code}\n# Model 111\nmodel111 <- glm(`whether he/she donated blood in March 2007` ~ `Frequency (times)` * (`Recency (months)`  + `Time (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model111)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Frequency (times)` * (`Recency (months)` + `Time (months)`), \n    family = binomial(link = \"logit\"), data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.8359  -0.7328  -0.4841  -0.1775   2.5913  \n\nCoefficients:\n                                         Estimate Std. Error z value Pr(>|z|)\n(Intercept)                            -1.1235111  0.2667332  -4.212 2.53e-05\n`Frequency (times)`                     0.3086468  0.0549479   5.617 1.94e-08\n`Recency (months)`                     -0.0671781  0.0244043  -2.753  0.00591\n`Time (months)`                        -0.0161226  0.0062869  -2.564  0.01033\n`Frequency (times)`:`Recency (months)` -0.0053101  0.0037377  -1.421  0.15540\n`Frequency (times)`:`Time (months)`    -0.0021010  0.0005798  -3.624  0.00029\n                                          \n(Intercept)                            ***\n`Frequency (times)`                    ***\n`Recency (months)`                     ** \n`Time (months)`                        *  \n`Frequency (times)`:`Recency (months)`    \n`Frequency (times)`:`Time (months)`    ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 692.90  on 742  degrees of freedom\nAIC: 704.9\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nPRESS(model111)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 705.3619\n```\n:::\n\n```{.r .cell-code}\nBIC(model111)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 732.604\n```\n:::\n\n```{.r .cell-code}\nAIC(model111)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 704.8996\n```\n:::\n\n```{.r .cell-code}\n# Model 112\nmodel112 <- glm(`whether he/she donated blood in March 2007` ~ `Frequency (times)` * (`Time (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model112)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Frequency (times)` * (`Time (months)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.8658  -0.6898  -0.5688  -0.2717   2.5392  \n\nCoefficients:\n                                      Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                         -1.5986493  0.2069198  -7.726 1.11e-14 ***\n`Frequency (times)`                  0.3413174  0.0466596   7.315 2.57e-13 ***\n`Time (months)`                     -0.0278320  0.0062804  -4.432 9.36e-06 ***\n`Frequency (times)`:`Time (months)` -0.0023162  0.0005376  -4.308 1.64e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 728.64  on 744  degrees of freedom\nAIC: 736.64\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code}\nPRESS(model112)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 737.7991\n```\n:::\n\n```{.r .cell-code}\nBIC(model112)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 755.1073\n```\n:::\n\n```{.r .cell-code}\nAIC(model112)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 736.6377\n```\n:::\n\n```{.r .cell-code}\n# Model 113\nmodel113 <- glm(`whether he/she donated blood in March 2007` ~ `Frequency (times)` * (`Recency (months)`), data = BD, family = binomial(link = \"logit\"))\nsummary(model113)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Frequency (times)` * (`Recency (months)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.3019  -0.8079  -0.4994  -0.2725   2.6070  \n\nCoefficients:\n                                        Estimate Std. Error z value Pr(>|z|)\n(Intercept)                            -0.796449   0.204599  -3.893 9.91e-05\n`Frequency (times)`                     0.090311   0.025025   3.609 0.000307\n`Recency (months)`                     -0.092477   0.023485  -3.938 8.23e-05\n`Frequency (times)`:`Recency (months)` -0.004730   0.003521  -1.343 0.179151\n                                          \n(Intercept)                            ***\n`Frequency (times)`                    ***\n`Recency (months)`                     ***\n`Frequency (times)`:`Recency (months)`    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 722.55  on 744  degrees of freedom\nAIC: 730.55\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nPRESS(model113)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 730.0172\n```\n:::\n\n```{.r .cell-code}\nBIC(model113)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 749.0217\n```\n:::\n\n```{.r .cell-code}\nAIC(model113)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 730.552\n```\n:::\n\n```{.r .cell-code}\n# Model 12\nmodel12 <- glm(`whether he/she donated blood in March 2007` ~ `Frequency (times)` + (`Recency (months)` + `Monetary (c.c. blood)` + `Time (months)`), data = BD, family = binomial(link = \"logit\"))\nsummary(model12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Frequency (times)` + (`Recency (months)` + `Monetary (c.c. blood)` + \n        `Time (months)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.4875  -0.7933  -0.4997  -0.1701   2.6450  \n\nCoefficients: (1 not defined because of singularities)\n                         Estimate Std. Error z value Pr(>|z|)    \n(Intercept)             -0.449540   0.180349  -2.493 0.012681 *  \n`Frequency (times)`      0.135390   0.025672   5.274 1.34e-07 ***\n`Recency (months)`      -0.098584   0.017317  -5.693 1.25e-08 ***\n`Monetary (c.c. blood)`        NA         NA      NA       NA    \n`Time (months)`         -0.023092   0.005964  -3.872 0.000108 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 707.87  on 744  degrees of freedom\nAIC: 715.87\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nPRESS(model12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 716.0328\n```\n:::\n\n```{.r .cell-code}\nBIC(model12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 734.3364\n```\n:::\n\n```{.r .cell-code}\nAIC(model12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 715.8668\n```\n:::\n\n```{.r .cell-code}\n# Model 121\nmodel121 <- glm(`whether he/she donated blood in March 2007` ~ `Frequency (times)` + (`Recency (months)` + `Time (months)`), data = BD, family = binomial(link = \"logit\"))\nsummary(model121)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Frequency (times)` + (`Recency (months)` + `Time (months)`), \n    family = binomial(link = \"logit\"), data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.4875  -0.7933  -0.4997  -0.1701   2.6450  \n\nCoefficients:\n                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -0.449540   0.180349  -2.493 0.012681 *  \n`Frequency (times)`  0.135390   0.025672   5.274 1.34e-07 ***\n`Recency (months)`  -0.098584   0.017317  -5.693 1.25e-08 ***\n`Time (months)`     -0.023092   0.005964  -3.872 0.000108 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 707.87  on 744  degrees of freedom\nAIC: 715.87\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nPRESS(model121)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 716.0328\n```\n:::\n\n```{.r .cell-code}\nBIC(model121)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 734.3364\n```\n:::\n\n```{.r .cell-code}\nAIC(model121)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 715.8668\n```\n:::\n\n```{.r .cell-code}\nanova(model111,model112,model113, model121)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Frequency (times)` * \n    (`Recency (months)` + `Time (months)`)\nModel 2: `whether he/she donated blood in March 2007` ~ `Frequency (times)` * \n    (`Time (months)`)\nModel 3: `whether he/she donated blood in March 2007` ~ `Frequency (times)` * \n    (`Recency (months)`)\nModel 4: `whether he/she donated blood in March 2007` ~ `Frequency (times)` + \n    (`Recency (months)` + `Time (months)`)\n  Resid. Df Resid. Dev Df Deviance\n1       742     692.90            \n2       744     728.64 -2  -35.738\n3       744     722.55  0    6.086\n4       744     707.87  0   14.685\n```\n:::\n\n```{.r .cell-code}\nlrtest(model111, model112,model113,model121)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Frequency (times)` * \n    (`Recency (months)` + `Time (months)`)\nModel 2: `whether he/she donated blood in March 2007` ~ `Frequency (times)` * \n    (`Time (months)`)\nModel 3: `whether he/she donated blood in March 2007` ~ `Frequency (times)` * \n    (`Recency (months)`)\nModel 4: `whether he/she donated blood in March 2007` ~ `Frequency (times)` + \n    (`Recency (months)` + `Time (months)`)\n  #Df  LogLik Df   Chisq Pr(>Chisq)    \n1   6 -346.45                          \n2   4 -364.32 -2 35.7380  1.736e-08 ***\n3   4 -361.28  0  6.0856  < 2.2e-16 ***\n4   4 -353.93  0 14.6852  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_model <- tidy(model111)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntidy_model <- tidy(model12)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing missing values (`geom_errorbarh()`).\n```\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n:::\n\n\n## Model 11\n\n-   The intercept coefficient is estimated to be -1.122, indicating the\n    log-odds of donating blood in March 2007 when all predictor\n    variables are zero. The intercept is statistically significant (p \\<\n    0.001), suggesting that the probability of donating blood in March\n    2007 is significantly different from zero even without any predictor\n    variables.\n\n-   The coefficient for **`Frequency (times)`** is estimated to be\n    0.3104, indicating that for each unit increase in the frequency of\n    blood donation, the log-odds of donating blood in March 2007\n    increase by 0.3104. This coefficient is statistically significant (p\n    \\< 0.001), suggesting that higher frequencies of blood donation are\n    associated with a higher likelihood of donating blood in March 2007.\n\n-   The coefficient for **`Recency (months)`** is estimated to be\n    -0.0662, indicating that for each unit increase in the number of\n    months since the last donation, the log-odds of donating blood in\n    March 2007 decrease by 0.0662. This coefficient is statistically\n    significant (p = 0.0111), suggesting that a longer time since the\n    last donation is associated with a lower likelihood of donating\n    blood in March 2007.\n\n-   The coefficient for **`Time (months)`** is estimated to be -0.0170,\n    indicating that for each unit increase in the number of months since\n    the first donation, the log-odds of donating blood in March 2007\n    decrease by 0.0170. However, this coefficient is not statistically\n    significant at conventional levels (p = 0.0987), suggesting that the\n    relationship between the overall duration of blood donation\n    experience and the likelihood of donation in March 2007 may not be\n    significant.\n\n-   The coefficient for the interaction term\n    **`Frequency (times):Recency (months)`** is estimated to be -0.0054.\n    However, this coefficient is not statistically significant (p =\n    0.1652), indicating that the interaction between frequency and\n    recency does not have a significant effect on the log-odds of\n    donating blood in March 2007.\n\n-   interaction terms:\n\n    -   The coefficient for the interaction term\n        **`Frequency (times):Monetary (c.c. blood)`** has an NA value,\n        indicating that it could not be estimated due to collinearity or\n        singularity issues caused by the high correlation between\n        **`Frequency (times)`** and **`Monetary (c.c. blood)`**.\n\n    -   The coefficient for the interaction term\n        **`Frequency (times):Time (months)`** is estimated to be\n        -0.00199. Although marginally significant (p = 0.0869), this\n        suggests that the interaction between frequency and the duration\n        of blood donation experience may be associated with a decrease\n        in the log-odds of donating blood in March 2007.\n\n-   The model's deviance statistics show a residual deviance of 692.89\n    on 741 degrees of freedom, indicating a reasonably good fit of the\n    model to the data.\n\n-   The AIC value of 706.89 and the BIC value of 739.2094 indicate the\n    relative quality of the model fit, with lower values suggesting\n    better fit while considering the model's complexity.\n\nIn summary, considering the NA value for the **`Monetary (c.c. blood)`**\ncoefficient, the logistic regression model suggests that the frequency\nof blood donation, the recency of the last donation, and the overall\nduration of blood donation experience are important factors in\npredicting the likelihood of donating blood in March 2007. The\ninteraction between frequency and recency, as well as frequency and\ntime, does not appear to have significant effects on the likelihood of\ndonation. The model's deviance statistics and model selection criteria\nsupport the adequacy of the model fit.\n\n**Model111:**\n\n-   The intercept coefficient is estimated to be -1.1235, indicating the\n    log-odds of donating blood in March 2007 when all predictor\n    variables are zero. The intercept is statistically significant (p \\<\n    0.001), suggesting that the probability of donating blood in March\n    2007 is significantly different from zero even without any predictor\n    variables.\n\n-   The coefficient for **`Frequency (times)`** is estimated to be\n    0.3086, indicating that for each unit increase in the frequency of\n    blood donation, the log-odds of donating blood in March 2007\n    increase by 0.3086. This coefficient is statistically significant (p\n    \\< 0.001), suggesting that higher frequencies of blood donation are\n    associated with a higher likelihood of donating blood in March 2007.\n\n-   The coefficient for **`Recency (months)`** is estimated to be\n    -0.0672, indicating that for each unit increase in the number of\n    months since the last donation, the log-odds of donating blood in\n    March 2007 decrease by 0.0672. This coefficient is statistically\n    significant (p = 0.00591), suggesting that a longer time since the\n    last donation is associated with a lower likelihood of donating\n    blood in March 2007.\n\n-   The coefficient for **`Time (months)`** is estimated to be -0.0161,\n    indicating that for each unit increase in the number of months since\n    the first donation, the log-odds of donating blood in March 2007\n    decrease by 0.0161. This coefficient is statistically significant (p\n    = 0.01033), suggesting that a longer duration of blood donation\n    experience is associated with a lower likelihood of donating blood\n    in March 2007.\n\n-   interaction terms:\n\n    -   The coefficient for the interaction term\n        **`Frequency (times):Recency (months)`** is estimated to be\n        -0.0053. However, this coefficient is not statistically\n        significant (p = 0.15540), indicating that the interaction\n        between frequency and recency does not have a significant effect\n        on the log-odds of donating blood in March 2007.\n\n    -   The coefficient for the interaction term\n        **`Frequency (times):Time (months)`** is estimated to be\n        -0.0021, indicating that the interaction between frequency and\n        the duration of blood donation experience is associated with a\n        decrease in the log-odds of donating blood in March 2007. This\n        coefficient is statistically significant (p = 0.00029),\n        suggesting that the interaction has a significant effect.\n\n-   The model's deviance statistics show a residual deviance of 692.90\n    on 742 degrees of freedom, indicating a reasonably good fit of the\n    model to the data.\n\n-   The AIC value of 704.9 and the BIC value of 732.604 indicate the\n    relative quality of the model fit, with lower values suggesting\n    better fit while considering the model's complexity.\n\n    In summary, the logistic regression model (Model 111) suggests that\n    the frequency of blood donation, recency of the last donation, and\n    the overall duration of blood donation experience are important\n    factors in predicting the likelihood of donating blood in\n    March 2007. The interaction between frequency and time has a\n    significant effect on the likelihood of donation, while the\n    interaction between frequency and recency does not.\n\n**Model 112**\n\nIn Model 112, we examine the relationship between the likelihood of\ndonating blood in March 2007 and the predictors **`Frequency (times)`**\nand **`Time (months)`**. The model also includes an interaction term\nbetween these two predictors.\n\nThe model's summary output reveals the following:\n\nThe intercept coefficient is -1.5986, indicating the log-odds of\ndonating blood in March 2007 when both **`Frequency (times)`** and\n**`Time (months)`** are zero.\n\nThe coefficient for **`Frequency (times)`** is 0.3413, suggesting that\nfor each unit increase in **`Frequency (times)`**, the log-odds of\ndonating blood in March 2007 increase by 0.3413. Individuals who donate\nblood more frequently have higher odds of donating blood in March 2007\ncompared to those who donate less frequently.\n\nThe coefficient for **`Time (months)`** is -0.0278, indicating that for\neach unit increase in **`Time (months)`**, the log-odds of donating\nblood in March 2007 decrease by 0.0278. Individuals with a longer\noverall duration of blood donation experience are less likely to donate\nblood in March 2007.\n\nThe coefficient for the interaction term between **`Frequency (times)`**\nand **`Time (months)`** is -0.0023, suggesting that the relationship\nbetween **`Frequency (times)`** and the log-odds of donating blood in\nMarch 2007 depends on the value of **`Time (months)`**.\n\nThe model's deviance statistics indicate a residual deviance of 728.64\non 744 degrees of freedom, suggesting that the model provides a\nreasonable fit to the data.\n\nConsidering the model selection criteria, the AIC value of 736.64 and\nBIC value of 755.11 suggest that Model 112 provides a relatively good\nfit to the data while considering the model's complexity. Lower AIC and\nBIC values indicate better trade-offs between model fit and complexity.\n\nAdditionally, the PRESS value of 737.7991 indicates the predictive\nperformance of the model. Lower PRESS values suggest better predictive\naccuracy, indicating that Model 112 has relatively good predictive\nperformance.\n\nOverall, Model 112 suggests that both **`Frequency (times)`** and\n**`Time (months)`** are significant predictors of the likelihood of\ndonating blood in March 2007. Furthermore, there is evidence of an\ninteraction effect between these two predictors, indicating that the\nrelationship between frequency and the likelihood of donation depends on\nthe duration of blood donation experience.\\\n\n**Model 113**\n\nIn Model 113, we examine the relationship between the likelihood of\ndonating blood in March 2007 and the predictors **`Frequency (times)`**\nand **`Recency (months)`**. The model also includes an interaction term\nbetween these two predictors.\n\nThe model's summary output reveals the following:\n\nThe intercept coefficient is -0.7964, indicating the log-odds of\ndonating blood in March 2007 when both **`Frequency (times)`** and\n**`Recency (months)`** are zero.\n\nThe coefficient for **`Frequency (times)`** is 0.0903, suggesting that\nfor each unit increase in **`Frequency (times)`**, the log-odds of\ndonating blood in March 2007 increase by 0.0903. Individuals who donate\nblood more frequently have higher odds of donating blood in March 2007\ncompared to those who donate less frequently.\n\nThe coefficient for **`Recency (months)`** is -0.0925, indicating that\nfor each unit increase in **`Recency (months)`**, the log-odds of\ndonating blood in March 2007 decrease by 0.0925. Individuals with a\nlonger time interval since their last donation are less likely to donate\nblood in March 2007.\n\nThe coefficient for the interaction term between **`Frequency (times)`**\nand **`Recency (months)`** is -0.0047, suggesting that the relationship\nbetween **`Frequency (times)`** and the log-odds of donating blood in\nMarch 2007 depends on the value of **`Recency (months)`**.\n\nThe model's deviance statistics indicate a residual deviance of 722.55\non 744 degrees of freedom, suggesting that the model provides a\nreasonable fit to the data.\n\nConsidering the model selection criteria, the AIC value of 730.55 and\nBIC value of 749.02 suggest that Model 113 provides a relatively good\nfit to the data while considering the model's complexity. Lower AIC and\nBIC values indicate better trade-offs between model fit and complexity.\n\nAdditionally, the PRESS value of 730.0172 indicates the predictive\nperformance of the model. Lower PRESS values suggest better predictive\naccuracy, indicating that Model 113 has relatively good predictive\nperformance.\n\nOverall, Model 113 suggests that both **`Frequency (times)`** and\n**`Recency (months)`** are significant predictors of the likelihood of\ndonating blood in March 2007. Furthermore, there is evidence of an\ninteraction effect between these two predictors, indicating that the\nrelationship between frequency and the likelihood of donation depends on\nthe time since the last donation.\\\n\n**Model12**\n\nThe logistic regression model (Model 12) aims to predict whether\nindividuals donated blood in March 2007 based on the following\nvariables: Frequency (times), Recency (months), Monetary (c.c. blood),\nand Time (months).\n\n-   The coefficient estimates and their corresponding statistical\n    significance are as follows:\n\n-   The intercept has a coefficient estimate of -0.4495, indicating that\n    when all other variables are held constant, there is a negative\n    effect on the log odds of donating blood in March 2007.\n\n-   The Frequency (times) variable has a coefficient estimate of 0.1354.\n    This means that for every one-unit increase in the number of times a\n    person has donated blood (Frequency (times)), the log odds of\n    donating blood in March 2007 increase by 0.1354, assuming all other\n    variables are constant.\n\n-   The Recency (months) variable has a coefficient estimate of -0.0986.\n    This implies that for every one-unit increase in the number of\n    months since the last donation (Recency (months)), the log odds of\n    donating blood in March 2007 decrease by 0.0986, holding all other\n    variables constant.\n\n-   The Monetary (c.c. blood) variable has an \"NA\" coefficient estimate.\n    This indicates that due to high correlation with other variables\n    (specifically Frequency (times)), it is not possible to estimate its\n    separate effect on the likelihood of donating blood in March 2007.\n\n-   The Time (months) variable has a coefficient estimate of -0.0231.\n    This suggests that for every one-unit increase in the duration of\n    blood donation experience (Time (months)), the log odds of donating\n    blood in March 2007 decrease by 0.0231, assuming all other variables\n    are constant.\n\n-   The model's goodness of fit and performance can be evaluated using\n    the following metrics:\n\n-   PRESS: PRESS is a measure of predictive error, indicating how well\n    the model predicts new data points. The value for PRESS is not\n    provided in the output.\n\n-   BIC: BIC (Bayesian Information Criterion) is a measure of model\n    complexity. Lower BIC values indicate a better trade-off between\n    goodness of fit and model complexity. The BIC value for this model\n    is 734.3364.\n\n-   AIC: AIC (Akaike Information Criterion) is another measure of model\n    fit that penalizes for model complexity. Lower AIC values indicate a\n    better fit. The AIC value for this model is 715.8668.\n\nIn summary, Model 12 suggests that the frequency of blood donation\n(Frequency (times)), the recency of the last donation (Recency\n(months)), and the duration of blood donation experience (Time (months))\nhave significant associations with the likelihood of donating blood in\nMarch 2007. However, due to high correlation, the separate effect of\nMonetary (c.c. blood) cannot be estimated. that's we decided to remove\nthe Monetary (c.c. blood) variable and rerun the model.\n\n**Model121:**\n\nThe logistic regression model (Model 121) examines the relationship\nbetween the likelihood of donating blood in March 2007 and the\npredictors **`Frequency (times)`**, **`Recency (months)`**, and\n**`Time (months)`**. The model's summary output reveals the following:\n\nThe intercept coefficient is -0.4495, indicating the log-odds of\ndonating blood in March 2007 when all predictor variables are zero.\nHowever, the practical interpretation of the intercept in this context\nmay be limited.\n\nThe coefficient for **`Frequency (times)`** is 0.1354, suggesting that\nfor each unit increase in the frequency of blood donation, the log-odds\nof donating blood in March 2007 increase by 0.1354. Individuals who\ndonate blood more frequently have higher odds of donating blood in March\n2007 compared to those who donate less frequently.\n\nThe coefficient for **`Recency (months)`** is -0.0986, implying that for\neach unit increase in the number of months since the last donation, the\nlog-odds of donating blood in March 2007 decrease by 0.0986. Individuals\nwith a longer time interval since their last donation are less likely to\ndonate blood in March 2007.\n\nThe coefficient for **`Time (months)`** is -0.0231, suggesting that for\neach unit increase in the number of months since the first donation, the\nlog-odds of donating blood in March 2007 decrease by 0.0231. Individuals\nwith a longer overall duration of blood donation experience are less\nlikely to donate blood in March 2007.\n\nThe model's deviance statistics indicate a residual deviance of 707.87\non 744 degrees of freedom, suggesting that the model provides a\nreasonably good fit to the data.\n\nConsidering the model selection criteria, the AIC value of 715.87 and\nBIC value of 734.3364 suggest that Model 121 provides a relatively good\nfit to the data while considering the model's complexity. Lower AIC and\nBIC values indicate better trade-offs between model fit and complexity.\n\nAdditionally, the PRESS value of 716.0328 indicates the predictive\nperformance of the model. Lower PRESS values suggest better predictive\naccuracy, indicating that Model 121 has relatively good predictive\nperformance.\n\nOverall, Model 121 suggests that the frequency of blood donation, the\nrecency of the last donation, and the overall duration of blood donation\nexperience are significant predictors of the likelihood of donating\nblood in March 2007, as evidenced by the statistically significant\ncoefficients.\n\n**Based on the Analysis of Deviance Table and the likelihood ratio test,\nwe can compare Model111, Model111, Model112, Model113 and Model121 to\ndetermine which model is better.**\n\nThe analysis of deviance table and likelihood ratio test compare the fit\nof four models: **Model111**, **Model112**, **Model113**, and\n**Model121** :\n\n-   Model111: This model includes **`Frequency (times)`** with\n    interactions with both **`Recency (months)`** and\n    **`Time (months)`**.\n\n    Model112: This model includes **`Frequency (times)`** with an\n    interaction only with **`Time (months)`** but not with\n    **`Recency (months)`**.\n\n    Model113: This model includes **`Frequency (times)`** with an\n    interaction only with **`Recency (months)`** but not with\n    **`Time (months)`**.\n\n    Model121: This model includes **`Frequency (times)`** without any\n    interactions, but includes both **`Recency (months)`** and\n    **`Time (months)`** as separate predictors.\n\n    Now, let's interpret the analysis of deviance table and likelihood\n    ratio test results:\n\n    Analysis of Deviance Table:\n\n    Model111 vs. Model112: The residual deviance for Model111 is 692.90\n    on 742 degrees of freedom, and for Model112 is 728.64 on 744 degrees\n    of freedom. The deviance difference is -35.738, indicating that\n    Model111 provides a significantly better fit compared to Model112.\n\n    Model111 vs. Model113: The residual deviance for Model111 is 692.90\n    on 742 degrees of freedom, and for Model113 is 722.55 on 744 degrees\n    of freedom. The deviance difference is 6.086, indicating that\n    Model111 provides a significantly better fit compared to Model113.\n\n    Model111 vs. Model121: The residual deviance for Model111 is 692.90\n    on 742 degrees of freedom, and for Model121 is 707.87 on 744 degrees\n    of freedom. The deviance difference is 14.685, indicating that\n    Model111 provides a significantly better fit compared to Model121.\n\n    Likelihood Ratio Test:\n\n    Model111 vs. Model112: The likelihood ratio test yields a\n    significant chi-squared value of 35.738 with 2 degrees of freedom (p\n    \\< 0.001). This indicates that including the interaction with\n    **`Recency (months)`** in Model111 significantly improves the fit\n    compared to Model112, which only includes the interaction with\n    **`Time (months)`**.\n\n    Model111 vs. Model113: The likelihood ratio test yields a\n    significant chi-squared value of 6.086 with 0 degrees of freedom (p\n    \\< 0.001). This indicates that including the interaction with\n    **`Time (months)`** in Model111 significantly improves the fit\n    compared to Model113, which only includes the interaction with\n    **`Recency (months)`**.\n\n    Model111 vs. Model121: The likelihood ratio test yields a\n    significant chi-squared value of 14.685 with 0 degrees of freedom (p\n    \\< 0.001). This indicates that including both **`Recency (months)`**\n    and **`Time (months)`** as separate predictors in Model111\n    significantly improves the fit compared to Model121, which only\n    includes **`Frequency (times)`** without any interactions.\n\n    In summary, Model111, which includes interactions with both\n    **`Recency (months)`** and **`Time (months)`**, provides the best\n    fit among the models tested. Including both interaction terms and\n    the main effects of **`Recency (months)`** and **`Time (months)`**\n    significantly improves the fit compared to the other models.\n\n## Hypothesis 2:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel21 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)`*(`Frequency (times)` + `Monetary (c.c. blood)` + `Time (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model21)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` * (`Frequency (times)` + `Monetary (c.c. blood)` + \n        `Time (months)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.8955  -0.7583  -0.4944  -0.3037   2.5230  \n\nCoefficients: (2 not defined because of singularities)\n                                            Estimate Std. Error z value\n(Intercept)                                -0.508146   0.230896  -2.201\n`Recency (months)`                         -0.097376   0.030389  -3.204\n`Frequency (times)`                         0.191067   0.038652   4.943\n`Monetary (c.c. blood)`                           NA         NA      NA\n`Time (months)`                            -0.031099   0.008141  -3.820\n`Recency (months)`:`Frequency (times)`     -0.008112   0.004104  -1.977\n`Recency (months)`:`Monetary (c.c. blood)`        NA         NA      NA\n`Recency (months)`:`Time (months)`          0.001195   0.000849   1.408\n                                           Pr(>|z|)    \n(Intercept)                                0.027753 *  \n`Recency (months)`                         0.001354 ** \n`Frequency (times)`                        7.68e-07 ***\n`Monetary (c.c. blood)`                          NA    \n`Time (months)`                            0.000133 ***\n`Recency (months)`:`Frequency (times)`     0.048081 *  \n`Recency (months)`:`Monetary (c.c. blood)`       NA    \n`Recency (months)`:`Time (months)`         0.159212    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 703.70  on 742  degrees of freedom\nAIC: 715.7\n\nNumber of Fisher Scoring iterations: 6\n```\n:::\n\n```{.r .cell-code}\nPRESS(model21)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 713.7301\n```\n:::\n\n```{.r .cell-code}\nBIC(model21)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 743.403\n```\n:::\n\n```{.r .cell-code}\nAIC(model21)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 715.6986\n```\n:::\n\n```{.r .cell-code}\nmodel211 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)`*(`Frequency (times)`  + `Time (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model211)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` * (`Frequency (times)` + `Time (months)`), \n    family = binomial(link = \"logit\"), data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.8955  -0.7583  -0.4944  -0.3037   2.5230  \n\nCoefficients:\n                                        Estimate Std. Error z value Pr(>|z|)\n(Intercept)                            -0.508146   0.230896  -2.201 0.027753\n`Recency (months)`                     -0.097376   0.030389  -3.204 0.001354\n`Frequency (times)`                     0.191067   0.038652   4.943 7.68e-07\n`Time (months)`                        -0.031099   0.008141  -3.820 0.000133\n`Recency (months)`:`Frequency (times)` -0.008112   0.004104  -1.977 0.048081\n`Recency (months)`:`Time (months)`      0.001195   0.000849   1.408 0.159212\n                                          \n(Intercept)                            *  \n`Recency (months)`                     ** \n`Frequency (times)`                    ***\n`Time (months)`                        ***\n`Recency (months)`:`Frequency (times)` *  \n`Recency (months)`:`Time (months)`        \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 703.70  on 742  degrees of freedom\nAIC: 715.7\n\nNumber of Fisher Scoring iterations: 6\n```\n:::\n\n```{.r .cell-code}\nPRESS(model211)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 713.7301\n```\n:::\n\n```{.r .cell-code}\nBIC(model211)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 743.403\n```\n:::\n\n```{.r .cell-code}\nAIC(model211)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 715.6986\n```\n:::\n\n```{.r .cell-code}\nmodel212 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)`*(`Frequency (times)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model212)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` * (`Frequency (times)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.3019  -0.8079  -0.4994  -0.2725   2.6070  \n\nCoefficients:\n                                        Estimate Std. Error z value Pr(>|z|)\n(Intercept)                            -0.796449   0.204599  -3.893 9.91e-05\n`Recency (months)`                     -0.092477   0.023485  -3.938 8.23e-05\n`Frequency (times)`                     0.090311   0.025025   3.609 0.000307\n`Recency (months)`:`Frequency (times)` -0.004730   0.003521  -1.343 0.179151\n                                          \n(Intercept)                            ***\n`Recency (months)`                     ***\n`Frequency (times)`                    ***\n`Recency (months)`:`Frequency (times)`    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 722.55  on 744  degrees of freedom\nAIC: 730.55\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nPRESS(model212)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 730.0172\n```\n:::\n\n```{.r .cell-code}\nBIC(model212)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 749.0217\n```\n:::\n\n```{.r .cell-code}\nAIC(model212)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 730.552\n```\n:::\n\n```{.r .cell-code}\nmodel213 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)`*( `Time (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model213)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` * (`Time (months)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.1269  -0.8872  -0.5220  -0.2527   2.6758  \n\nCoefficients:\n                                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                        -0.3057684  0.2196548  -1.392 0.163910    \n`Recency (months)`                 -0.1109247  0.0307413  -3.608 0.000308 ***\n`Time (months)`                     0.0031488  0.0053789   0.585 0.558270    \n`Recency (months)`:`Time (months)` -0.0004051  0.0007352  -0.551 0.581637    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 743.18  on 744  degrees of freedom\nAIC: 751.18\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nPRESS(model213)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 750.8796\n```\n:::\n\n```{.r .cell-code}\nBIC(model213)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 769.6459\n```\n:::\n\n```{.r .cell-code}\nAIC(model213)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 751.1763\n```\n:::\n\n```{.r .cell-code}\nanova(model211, model212, model213)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    (`Frequency (times)` + `Time (months)`)\nModel 2: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    (`Frequency (times)`)\nModel 3: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    (`Time (months)`)\n  Resid. Df Resid. Dev Df Deviance\n1       742     703.70            \n2       744     722.55 -2  -18.854\n3       744     743.18  0  -20.624\n```\n:::\n\n```{.r .cell-code}\nlrtest(model211, model212, model213)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    (`Frequency (times)` + `Time (months)`)\nModel 2: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    (`Frequency (times)`)\nModel 3: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    (`Time (months)`)\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   6 -351.85                         \n2   4 -361.28 -2 18.854  8.054e-05 ***\n3   4 -371.59  0 20.624  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nplot(model21, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-11-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-11-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-11-6.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_model <- tidy(model211)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n**Model21**\n\nThe logistic regression model (Model 21) examines the relationship\nbetween the likelihood of donating blood in March 2007 and the\npredictors Frequency (times), Recency (months), Monetary (c.c. blood),\nand Time (months). However, due to singularities in the model, the\ncoefficients for Monetary (c.c. blood) and its interactions are not\ndefined.\n\nWhen considering the correlation between Frequency (times) and Monetary\n(c.c. blood), we can observe that these two predictors are highly\ncorrelated. This indicates that individuals who donate blood more\nfrequently are likely to have a higher monetary value of blood donated.\nHowever, due to the singularities in the model, it is not possible to\nestimate the individual effects of Monetary (c.c. blood) and the\ninteractions involving it.\n\nThe remaining coefficients in the model can still be interpreted as\nfollows:\n\n-   The intercept coefficient is -0.5081, indicating the log-odds of\n    donating blood in March 2007 when all other predictor variables are\n    zero. However, the practical interpretation of the intercept in this\n    context may be limited.\n\n-   The coefficient for Recency (months) is -0.0974, implying that for\n    each unit increase in the number of months since the last donation,\n    the log-odds of donating blood in March 2007 decrease by 0.0974.\n    Individuals with a longer time interval since their last donation\n    are less likely to donate blood in March 2007.\n\n-   The coefficient for Frequency (times) is 0.1911, suggesting that for\n    each unit increase in the frequency of blood donation, the log-odds\n    of donating blood in March 2007 increase by 0.1911. Individuals who\n    donate blood more frequently have higher odds of donating blood in\n    March 2007 compared to those who donate less frequently.\n\n-   The coefficient for Time (months) is -0.0311, indicating that for\n    each unit increase in the number of months since the first donation,\n    the log-odds of donating blood in March 2007 decrease by 0.0311.\n    Individuals with a longer overall duration of blood donation\n    experience are less likely to donate blood in March 2007.\n\n-   The coefficient for the interaction term Recency (months):Frequency\n    (times) is -0.0081, implying that the effect of the interaction\n    between recency and frequency on the log-odds of donating blood in\n    March 2007 is negative. However, the practical interpretation of\n    this interaction term may be limited due to the singularities in the\n    model.\n\n-   The model's deviance statistics indicate a residual deviance of\n    703.70 on 742 degrees of freedom, suggesting that the model provides\n    a reasonably good fit to the data.\n\n-   Considering the model selection criteria, the AIC value of 715.70\n    and BIC value of 743.40 suggest that Model 21 provides a relatively\n    good fit to the data while considering the model's complexity. Lower\n    AIC and BIC values indicate better trade-offs between model fit and\n    complexity.\n\n-   Additionally, the PRESS value of 713.73 indicates the predictive\n    performance of the model. Lower PRESS values suggest better\n    predictive accuracy, indicating that Model 21 has relatively good\n    predictive performance.\n\n    Overall, Model 21 suggests that the frequency of blood donation, the\n    recency of the last donation, and the overall duration of blood\n    donation experience are significant predictors of the likelihood of\n    donating blood in March 2007, as evidenced by the statistically\n    significant coefficients. However considering the high correlation\n    between coefficients for Monetary (c.c. blood) and Frequency\n    (times), we decided to drop Monetary (c.c. blood) and rerun the\n    model.\n\n    .\n\n    **Model 211**\n\nThe logistic regression model (Model 211) examines the relationship\nbetween the likelihood of donating blood in March 2007 and the\npredictors Recency (months), Frequency (times), and Time (months), as\nwell as their interaction terms. The model's summary output reveals the\nfollowing:\n\n-   The intercept coefficient is -0.5081, indicating the log-odds of\n    donating blood in March 2007 when all predictor variables are zero.\n    However, the practical interpretation of the intercept in this\n    context may be limited.\n\n-   The coefficient for Recency (months) is -0.0974, implying that for\n    each unit increase in the number of months since the last donation,\n    the log-odds of donating blood in March 2007 decrease by 0.0974.\n    Individuals with a longer time interval since their last donation\n    are less likely to donate blood in March 2007.\n\n-   The coefficient for Frequency (times) is 0.1911, suggesting that for\n    each unit increase in the frequency of blood donation, the log-odds\n    of donating blood in March 2007 increase by 0.1911. Individuals who\n    donate blood more frequently have higher odds of donating blood in\n    March 2007 compared to those who donate less frequently.\n\n-   The coefficient for Time (months) is -0.0311, indicating that for\n    each unit increase in the number of months since the first donation,\n    the log-odds of donating blood in March 2007 decrease by 0.0311.\n    Individuals with a longer overall duration of blood donation\n    experience are less likely to donate blood in March 2007.\n\n-   The interaction term coefficients represent the joint effect of two\n    predictors. The coefficient for Recency (months):Frequency (times)\n    is -0.0081, suggesting that the interaction between recency and\n    frequency of blood donation has a negative effect on the log-odds of\n    donating blood in March 2007. The coefficient for Recency\n    (months):Time (months) is 0.0012, indicating that the interaction\n    between recency and the overall duration of blood donation\n    experience has a positive effect on the log-odds of donating blood\n    in March 2007. However, these interaction effects are not\n    statistically significant at conventional significance levels.\n\n-   The model's deviance statistics indicate a residual deviance of\n    703.70 on 742 degrees of freedom, suggesting that the model provides\n    a reasonably good fit to the data.\n\n-   Considering the model selection criteria, the AIC value of 715.7 and\n    BIC value of 743.403 suggest that Model 211 provides a relatively\n    good fit to the data while considering the model's complexity. Lower\n    AIC and BIC values indicate better trade-offs between model fit and\n    complexity.\n\n-   Additionally, the PRESS value of 713.7301 indicates the predictive\n    performance of the model. Lower PRESS values suggest better\n    predictive accuracy, indicating that Model 211 has relatively good\n    predictive performance.\n\n    Overall, Model 211 suggests that the recency of the last donation,\n    the frequency of blood donation, and the overall duration of blood\n    donation experience are significant predictors of the likelihood of\n    donating blood in March 2007. The interaction effects, although not\n    statistically significant, may provide additional insights into the\n    relationship between these predictors.\n\n**Model212**\n\nIn Model212, the logistic regression model examines the relationship\nbetween the likelihood of donating blood in March 2007 and the\npredictors **`Recency (months)`** and **`Frequency (times)`** along with\ntheir interaction.\n\nThe summary output provides the following information:\n\n-   The intercept coefficient is -0.7964, indicating the log-odds of\n    donating blood in March 2007 when both **`Recency (months)`** and\n    **`Frequency (times)`** are zero. However, the practical\n    interpretation of the intercept in this context may be limited.\n\n-   The coefficient for **`Recency (months)`** is -0.0925, suggesting\n    that for each unit increase in the number of months since the last\n    donation, the log-odds of donating blood in March 2007 decrease by\n    0.0925. Individuals with a longer time interval since their last\n    donation are less likely to donate blood in March 2007.\n\n-   The coefficient for **`Frequency (times)`** is 0.0903, indicating\n    that for each unit increase in the frequency of blood donation, the\n    log-odds of donating blood in March 2007 increase by 0.0903.\n    Individuals who donate blood more frequently have higher odds of\n    donating blood in March 2007 compared to those who donate less\n    frequently.\n\n-   The coefficient for the interaction term\n    **`Recency (months)`**:**`Frequency (times)`** is -0.0047, which\n    suggests that the effect of **`Recency (months)`** on the log-odds\n    of donating blood in March 2007 depends on the value of\n    **`Frequency (times)`**. However, this interaction term is not\n    statistically significant (p-value = 0.1791), indicating that the\n    relationship between **`Recency (months)`** and the likelihood of\n    donation does not significantly differ across different levels of\n    **`Frequency (times)`**.\n\nThe model's deviance statistics show a residual deviance of 722.55 on\n744 degrees of freedom, indicating that the model provides a reasonably\ngood fit to the data.\n\nConsidering the model selection criteria, the AIC value of 730.55 and\nBIC value of 749.0217 suggest that Model212 provides a relatively good\nfit to the data while considering the model's complexity. Lower AIC and\nBIC values indicate better trade-offs between model fit and complexity.\n\nAdditionally, the PRESS value of 730.0172 indicates the predictive\nperformance of the model. Lower PRESS values suggest better predictive\naccuracy, indicating that Model212 has relatively good predictive\nperformance.\n\nOverall, Model212 suggests that both **`Recency (months)`** and\n**`Frequency (times)`** are significant predictors of the likelihood of\ndonating blood in March 2007. The effect of **`Recency (months)`** is\nnegative, indicating that individuals with a longer time since their\nlast donation are less likely to donate, while the effect of\n**`Frequency (times)`** is positive, indicating that individuals who\ndonate more frequently are more likely to donate blood in March 2007.\nThe interaction between **`Recency (months)`** and\n**`Frequency (times)`** is not statistically significant in predicting\nblood donation in March 2007.\n\n**Model213** In Model213, the logistic regression model examines the\nrelationship between the likelihood of donating blood in March 2007 and\nthe predictors **`Recency (months)`** and **`Time (months)`** along with\ntheir interaction.\n\nThe summary output provides the following information:\n\n-   The intercept coefficient is -0.3058, indicating the log-odds of\n    donating blood in March 2007 when all predictor variables are zero.\n    However, the practical interpretation of the intercept in this\n    context may be limited.\n\n-   The coefficient for **`Recency (months)`** is -0.1109, suggesting\n    that for each unit increase in the number of months since the last\n    donation, the log-odds of donating blood in March 2007 decrease by\n    0.1109. Individuals with a longer time interval since their last\n    donation are less likely to donate blood in March 2007.\n\n-   The coefficient for **`Time (months)`** is 0.0031, indicating that\n    for each unit increase in the number of months since the first\n    donation, the log-odds of donating blood in March 2007 increase by\n    0.0031. However, this coefficient is not statistically significant\n    (p-value = 0.5583), suggesting no significant association between\n    **`Time (months)`** and the likelihood of blood donation.\n\n-   The coefficient for the interaction term\n    **`Recency (months)`**:**`Time (months)`** is -0.0004, indicating\n    that the effect of **`Recency (months)`** on the log-odds of\n    donating blood in March 2007 depends on the value of\n    **`Time (months)`**. However, this interaction term is not\n    statistically significant (p-value = 0.5816), suggesting no\n    significant interaction effect.\n\nThe model's deviance statistics show a residual deviance of 743.18 on\n744 degrees of freedom, indicating that the model provides a reasonably\ngood fit to the data.\n\nConsidering the model selection criteria, the AIC value of 751.18 and\nBIC value of 769.6459 suggest that Model213 provides a relatively good\nfit to the data while considering the model's complexity. Lower AIC and\nBIC values indicate better trade-offs between model fit and complexity.\n\nAdditionally, the PRESS value of 750.8796 indicates the predictive\nperformance of the model. Lower PRESS values suggest better predictive\naccuracy, indicating that Model213 has relatively good predictive\nperformance.\n\nOverall, Model213 suggests that **`Recency (months)`** is a significant\npredictor of the likelihood of donating blood in March 2007. The effect\nof **`Time (months)`** and the interaction between\n**`Recency (months)`** and **`Time (months)`** on blood donation\nlikelihood are not statistically significant in this model.\n\n**Conclusion**:\n\n-   Model 1: whether he/she donated blood in March 2007 \\~ Recency\n    (months) \\* (Frequency (times) + Monetary (c.c. blood) + Time\n    (months)) Model 2: whether he/she donated blood in March 2007 \\~\n    Recency (months) \\* (Frequency (times) + Time (months))\n\n-   The Residual Deviance for both models is 703.7, and the difference\n    in deviance (Deviance Df) is 0. This indicates that Model 2 fits the\n    data as well as Model 1. The likelihood ratio test also confirms\n    this, as the chi-square test statistic is 0 with 0 degrees of\n    freedom, resulting in a p-value of 1.\n\nTherefore, we can conclude that Model 2, which excludes the predictor\nMonetary (c.c. blood) due to its correlation with Frequency (times),\nprovides an equally good fit to the data compared to Model 1. In terms\nof simplicity and avoiding potential collinearity issues, Model 2 is\npreferred.\n\n**Conclusion:**\n\nThe analysis of deviance table and likelihood ratio test provide\ninformation on the comparison of the three models: Model211, Model212,\nand Model213.\n\nIn the analysis of deviance table:\n\n-   Model211: This model includes the predictors **`Recency (months)`**,\n    **`Frequency (times)`**, and **`Time (months)`** along with their\n    interactions. It has a residual deviance of 703.70 on 742 degrees of\n    freedom.\n\n-   Model212: This model includes the predictors **`Recency (months)`**\n    and **`Frequency (times)`** along with their interaction. It has a\n    residual deviance of 722.55 on 744 degrees of freedom.\n\n-   Model213: This model includes the predictors **`Recency (months)`**\n    and **`Time (months)`** along with their interaction. It has a\n    residual deviance of 743.18 on 744 degrees of freedom.\n\nThe likelihood ratio test compares the models:\n\n-   Model211 vs. Model212: The test indicates that there is a\n    significant difference in deviance between these two models (p-value\n    = 8.054e-05). This suggests that including the predictor\n    **`Time (months)`** in addition to **`Frequency (times)`** and\n    **`Recency (months)`** improves the model fit.\n\n-   Model211 vs. Model213: The test indicates that there is a\n    significant difference in deviance between these two models (p-value\n    \\< 2.2e-16). This suggests that including both\n    **`Frequency (times)`** and **`Time (months)`** in addition to\n    **`Recency (months)`** and their interactions improves the model\n    fit.\n\nBased on these results, Model211, which includes **`Recency (months)`**,\n**`Frequency (times)`**, **`Time (months)`**, and their interactions,\nappears to provide the best fit to the data. It has the lowest residual\ndeviance among the three models. However, it is important to consider\nother factors such as the practical significance and interpretability of\nthe model coefficients when choosing the most appropriate model for\nfurther analysis or prediction.\n\n### Hypothesis 3:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel31 <- glm(`whether he/she donated blood in March 2007` ~ `Monetary (c.c. blood)` * (`Frequency (times)` + `Time (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model31)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Monetary (c.c. blood)` * (`Frequency (times)` + `Time (months)`), \n    family = binomial(link = \"logit\"), data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.8442  -0.7038  -0.5658  -0.2557   2.6044  \n\nCoefficients: (1 not defined because of singularities)\n                                              Estimate Std. Error z value\n(Intercept)                                 -1.542e+00  2.222e-01  -6.939\n`Monetary (c.c. blood)`                      1.373e-03  1.859e-04   7.385\n`Frequency (times)`                                 NA         NA      NA\n`Time (months)`                             -3.275e-02  9.775e-03  -3.350\n`Monetary (c.c. blood)`:`Frequency (times)` -5.465e-06  8.121e-06  -0.673\n`Monetary (c.c. blood)`:`Time (months)`     -6.684e-06  4.387e-06  -1.524\n                                            Pr(>|z|)    \n(Intercept)                                 3.94e-12 ***\n`Monetary (c.c. blood)`                     1.53e-13 ***\n`Frequency (times)`                               NA    \n`Time (months)`                             0.000808 ***\n`Monetary (c.c. blood)`:`Frequency (times)` 0.500977    \n`Monetary (c.c. blood)`:`Time (months)`     0.127560    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 728.20  on 743  degrees of freedom\nAIC: 738.2\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nPRESS(model31)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 739.6641\n```\n:::\n\n```{.r .cell-code}\nBIC(model31)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 761.2839\n```\n:::\n\n```{.r .cell-code}\nAIC(model31)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 738.1968\n```\n:::\n\n```{.r .cell-code}\nmodel311 <- glm(`whether he/she donated blood in March 2007` ~ `Monetary (c.c. blood)` * (`Frequency (times)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model311)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Monetary (c.c. blood)` * (`Frequency (times)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.5259  -0.7187  -0.6204  -0.5886   1.9176  \n\nCoefficients: (1 not defined because of singularities)\n                                              Estimate Std. Error z value\n(Intercept)                                 -1.783e+00  1.615e-01 -11.040\n`Monetary (c.c. blood)`                      4.767e-04  1.204e-04   3.959\n`Frequency (times)`                                 NA         NA      NA\n`Monetary (c.c. blood)`:`Frequency (times)` -5.517e-06  3.481e-06  -1.585\n                                            Pr(>|z|)    \n(Intercept)                                  < 2e-16 ***\n`Monetary (c.c. blood)`                     7.52e-05 ***\n`Frequency (times)`                               NA    \n`Monetary (c.c. blood)`:`Frequency (times)`    0.113    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 786.84  on 745  degrees of freedom\nAIC: 792.84\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code}\nPRESS(model311)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 794.1789\n```\n:::\n\n```{.r .cell-code}\nBIC(model311)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 806.691\n```\n:::\n\n```{.r .cell-code}\nAIC(model311)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 792.8388\n```\n:::\n\n```{.r .cell-code}\nmodel312 <- glm(`whether he/she donated blood in March 2007` ~ `Monetary (c.c. blood)` * (`Time (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model312)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Monetary (c.c. blood)` * (`Time (months)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.8658  -0.6898  -0.5688  -0.2717   2.5392  \n\nCoefficients:\n                                          Estimate Std. Error z value Pr(>|z|)\n(Intercept)                             -1.599e+00  2.069e-01  -7.726 1.11e-14\n`Monetary (c.c. blood)`                  1.365e-03  1.866e-04   7.315 2.57e-13\n`Time (months)`                         -2.783e-02  6.280e-03  -4.432 9.36e-06\n`Monetary (c.c. blood)`:`Time (months)` -9.265e-06  2.150e-06  -4.308 1.64e-05\n                                           \n(Intercept)                             ***\n`Monetary (c.c. blood)`                 ***\n`Time (months)`                         ***\n`Monetary (c.c. blood)`:`Time (months)` ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 728.64  on 744  degrees of freedom\nAIC: 736.64\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code}\nPRESS(model312)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 737.7991\n```\n:::\n\n```{.r .cell-code}\nBIC(model312)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 755.1073\n```\n:::\n\n```{.r .cell-code}\nAIC(model312)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 736.6377\n```\n:::\n\n```{.r .cell-code}\nanova(model31, model311, model312)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Monetary (c.c. blood)` * \n    (`Frequency (times)` + `Time (months)`)\nModel 2: `whether he/she donated blood in March 2007` ~ `Monetary (c.c. blood)` * \n    (`Frequency (times)`)\nModel 3: `whether he/she donated blood in March 2007` ~ `Monetary (c.c. blood)` * \n    (`Time (months)`)\n  Resid. Df Resid. Dev Df Deviance\n1       743     728.20            \n2       745     786.84 -2  -58.642\n3       744     728.64  1   58.201\n```\n:::\n\n```{.r .cell-code}\nlrtest(model31, model311, model312)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Monetary (c.c. blood)` * \n    (`Frequency (times)` + `Time (months)`)\nModel 2: `whether he/she donated blood in March 2007` ~ `Monetary (c.c. blood)` * \n    (`Frequency (times)`)\nModel 3: `whether he/she donated blood in March 2007` ~ `Monetary (c.c. blood)` * \n    (`Time (months)`)\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   5 -364.10                         \n2   3 -393.42 -2 58.642  1.845e-13 ***\n3   4 -364.32  1 58.201  2.366e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nplot(model31, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-13-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-13-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-13-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-13-6.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_model <- tidy(model31)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing missing values (`geom_errorbarh()`).\n```\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n### \n\n**Model 31**\n\nIn Model 31, the logistic regression model is fitted to predict whether\nan individual donated blood in March 2007 using the variables\n**`Monetary (c.c. blood)`**, **`Frequency (times)`**, and\n**`Time (months)`**, along with their interactions.\n\nThe summary of the model shows the estimated coefficients, standard\nerrors, z-values, and p-values for each predictor variable.\n\n-   The intercept term is estimated to be -1.542, indicating the\n    log-odds of donating blood when all predictor variables are zero.\n\n-   **`Monetary (c.c. blood)`** has a positive coefficient estimate of\n    0.001373, suggesting that an increase in the monetary amount of\n    blood donated is associated with an increase in the log-odds of\n    donating blood in March 2007.\n\n-   The coefficient for **`Frequency (times)`** is **`NA`**, indicating\n    that it is not estimable or there may be missing values or\n    collinearity issues with this variable.\n\n-   **`Time (months)`** has a negative coefficient estimate of -0.03275,\n    implying that an increase in the number of months since the last\n    donation is associated with a decrease in the log-odds of donating\n    blood.\n\n-   The interaction terms between **`Monetary (c.c. blood)`** and\n    **`Frequency (times)`**, as well as between\n    **`Monetary (c.c. blood)`** and **`Time (months)`**, have\n    coefficient estimates that are not statistically significant (p \\>\n    0.05).\n\nThe deviance residuals provide information about the model fit, and the\nAIC and BIC values are used for model selection. Lower AIC and BIC\nvalues indicate better model fit and parsimony.\n\nHowever, it is important to note that the coefficient for\n**`Frequency (times)`** is not estimable in this model, which suggests\npotential issues such as missing values or collinearity. So we will test\nother variation in the hypothesis\n\n**Model 311**\n\nIn Model 311, the logistic regression model is fitted to predict whether\nan individual donated blood in March 2007 using the variables\n**`Monetary (c.c. blood)`** and **`Frequency (times)`**, along with\ntheir interaction.\n\nThe summary of the model shows the estimated coefficients, standard\nerrors, z-values, and p-values for each predictor variable.\n\n-   The intercept term is estimated to be -1.783, indicating the\n    log-odds of donating blood when both **`Monetary (c.c. blood)`** and\n    **`Frequency (times)`** are zero.\n\n-   **`Monetary (c.c. blood)`** has a positive coefficient estimate of\n    4.767e-04, suggesting that an increase in the monetary amount of\n    blood donated is associated with an increase in the log-odds of\n    donating blood in March 2007.\n\n-   The coefficient for **`Frequency (times)`** is **`NA`**, indicating\n    that it is not estimable or there may be missing values or\n    collinearity issues with this variable.\n\n-   The interaction term between **`Monetary (c.c. blood)`** and\n    **`Frequency (times)`** has a coefficient estimate of -5.517e-06,\n    which is not statistically significant (p \\> 0.05).\n\nThe deviance residuals provide information about the model fit, and the\nAIC and BIC values are used for model selection. Lower AIC and BIC\nvalues indicate better model fit and parsimony.\n\nHowever, it is important to note that the coefficient for\n**`Frequency (times)`** is not estimable in this model, suggesting\npotential issues such as missing values or collinearity. It is\nrecommended to investigate and address these issues before drawing\nconclusions from the model.\\\n\n**Model 312**\n\nIn Model 312, the logistic regression model is fitted to predict whether\nan individual donated blood in March 2007 using the variables\n**`Monetary (c.c. blood)`** and **`Time (months)`**, along with their\ninteraction.\n\nThe summary of the model shows the estimated coefficients, standard\nerrors, z-values, and p-values for each predictor variable.\n\n-   The intercept term is estimated to be -1.599, indicating the\n    log-odds of donating blood when both **`Monetary (c.c. blood)`** and\n    **`Time (months)`** are zero.\n\n-   **`Monetary (c.c. blood)`** has a positive coefficient estimate of\n    1.365e-03, suggesting that an increase in the monetary amount of\n    blood donated is associated with an increase in the log-odds of\n    donating blood in March 2007.\n\n-   **`Time (months)`** has a negative coefficient estimate of\n    -2.783e-02, indicating that an increase in the number of months\n    since the last donation is associated with a decrease in the\n    log-odds of donating blood.\n\n-   The interaction term between **`Monetary (c.c. blood)`** and\n    **`Time (months)`** has a coefficient estimate of -9.265e-06,\n    indicating that the effect of **`Monetary (c.c. blood)`** on the\n    log-odds of donating blood depends on the number of months since the\n    last donation.\n\nThe deviance residuals provide information about the model fit, and the\nAIC and BIC values are used for model selection. Lower AIC and BIC\nvalues indicate better model fit and parsimony.\n\nOverall, the model suggests that both **`Monetary (c.c. blood)`** and\n**`Time (months)`** are important predictors of blood donation in March\n2007, and their interaction is also significant. However, it is\nimportant to interpret the coefficients in the context of the specific\ndataset and consider other factors that may influence blood donation\nbehavior.\n\n**Conclusion:**\n\nThe analysis of deviance table compares the three models:\n\nModel 1: **`whether he/she donated blood in March 2007`** \\~\n**`Monetary (c.c. blood)`** \\* (**`Frequency (times)`** +\n**`Time (months)`**) Model 2:\n**`whether he/she donated blood in March 2007`** \\~\n**`Monetary (c.c. blood)`** \\* (**`Frequency (times)`**) Model 3:\n**`whether he/she donated blood in March 2007`** \\~\n**`Monetary (c.c. blood)`** \\* (**`Time (months)`**)\n\nThe table shows the degrees of freedom (**`Resid. Df`**), residual\ndeviance (**`Resid. Dev`**), and the change in deviance (**`Deviance`**)\nfor each model.\n\n-   Comparing Model 1 and Model 2:\n\n    -   Residual degrees of freedom are 743 and 745, respectively.\n\n    -   The residual deviance for Model 1 is 728.20, while for Model 2,\n        it is 786.84.\n\n    -   The change in deviance is -58.642 (negative because Model 2 has\n        higher deviance).\n\n-   Comparing Model 1 and Model 3:\n\n    -   Residual degrees of freedom are 743 and 744, respectively.\n\n    -   The residual deviance for Model 1 is 728.20, while for Model 3,\n        it is 728.64.\n\n    -   The change in deviance is 58.201.\n\nThe likelihood ratio test compares the three models based on their\nlog-likelihood values (**`LogLik`**) and the associated chi-square test\nstatistics (**`Chisq`**). The test assesses whether the inclusion of\nadditional predictors in each model significantly improves the model\nfit.\n\n-   Comparing Model 1 and Model 2:\n\n    -   The difference in degrees of freedom is 2.\n\n    -   The chi-square test statistic is 58.642, which is highly\n        significant (p \\< 0.001).\n\n    -   The test indicates that including the interaction between\n        **`Monetary (c.c. blood)`** and **`Frequency (times)`**\n        significantly improves the model fit compared to Model 2.\n\n-   Comparing Model 1 and Model 3:\n\n    -   The difference in degrees of freedom is 1.\n\n    -   The chi-square test statistic is 58.201, which is highly\n        significant (p \\< 0.001).\n\n    -   The test indicates that including the interaction between\n        **`Monetary (c.c. blood)`** and **`Time (months)`**\n        significantly improves the model fit compared to Model 3.\n\nIn summary, both the analysis of deviance table and the likelihood ratio\ntest suggest that including the interactions between\n**`Monetary (c.c. blood)`** and either **`Frequency (times)`** or\n**`Time (months)`** improves the model fit compared to the models\nwithout those interactions.\\\n\n# Hypothesis 4:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4 <- glm(`whether he/she donated blood in March 2007` ~ `Time (months)` * ( `Frequency (times)` + `Recency (months)`), \n             data = BD, family = binomial(link = \"logit\"))\n\nsummary(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Time (months)` * (`Frequency (times)` + `Recency (months)`), \n    family = binomial(link = \"logit\"), data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.7874  -0.7504  -0.4945  -0.1653   2.6039  \n\nCoefficients:\n                                      Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                         -0.9594461  0.2738062  -3.504 0.000458 ***\n`Time (months)`                     -0.0162750  0.0075905  -2.144 0.032024 *  \n`Frequency (times)`                  0.2732404  0.0476950   5.729 1.01e-08 ***\n`Recency (months)`                  -0.0906773  0.0326321  -2.779 0.005456 ** \n`Time (months)`:`Frequency (times)` -0.0019672  0.0005441  -3.616 0.000299 ***\n`Time (months)`:`Recency (months)`  -0.0000985  0.0007792  -0.126 0.899397    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 695.29  on 742  degrees of freedom\nAIC: 707.29\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nPRESS(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 707.3251\n```\n:::\n\n```{.r .cell-code}\nBIC(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 734.9945\n```\n:::\n\n```{.r .cell-code}\nAIC(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 707.2901\n```\n:::\n\n```{.r .cell-code}\nmodel41 <- glm(`whether he/she donated blood in March 2007` ~ `Time (months)` *( `Frequency (times)`), \n             data = BD, family = binomial(link = \"logit\"))\n\nsummary(model41)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Time (months)` * (`Frequency (times)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.8658  -0.6898  -0.5688  -0.2717   2.5392  \n\nCoefficients:\n                                      Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                         -1.5986493  0.2069198  -7.726 1.11e-14 ***\n`Time (months)`                     -0.0278320  0.0062804  -4.432 9.36e-06 ***\n`Frequency (times)`                  0.3413174  0.0466596   7.315 2.57e-13 ***\n`Time (months)`:`Frequency (times)` -0.0023162  0.0005376  -4.308 1.64e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 728.64  on 744  degrees of freedom\nAIC: 736.64\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code}\nPRESS(model41)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 737.7991\n```\n:::\n\n```{.r .cell-code}\nBIC(model41)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 755.1073\n```\n:::\n\n```{.r .cell-code}\nAIC(model41)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 736.6377\n```\n:::\n\n```{.r .cell-code}\nmodel42 <- glm(`whether he/she donated blood in March 2007` ~ `Time (months)` *( `Recency (months)`), \n             data = BD, family = binomial(link = \"logit\"))\n\nsummary(model42)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Time (months)` * (`Recency (months)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.1269  -0.8872  -0.5220  -0.2527   2.6758  \n\nCoefficients:\n                                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                        -0.3057684  0.2196548  -1.392 0.163910    \n`Time (months)`                     0.0031488  0.0053789   0.585 0.558270    \n`Recency (months)`                 -0.1109247  0.0307413  -3.608 0.000308 ***\n`Time (months)`:`Recency (months)` -0.0004051  0.0007352  -0.551 0.581637    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 743.18  on 744  degrees of freedom\nAIC: 751.18\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nPRESS(model42)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 750.8796\n```\n:::\n\n```{.r .cell-code}\nBIC(model42)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 769.6459\n```\n:::\n\n```{.r .cell-code}\nAIC(model42)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 751.1763\n```\n:::\n\n```{.r .cell-code}\nanova(model4, model41, model42)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Time (months)` * \n    (`Frequency (times)` + `Recency (months)`)\nModel 2: `whether he/she donated blood in March 2007` ~ `Time (months)` * \n    (`Frequency (times)`)\nModel 3: `whether he/she donated blood in March 2007` ~ `Time (months)` * \n    (`Recency (months)`)\n  Resid. Df Resid. Dev Df Deviance\n1       742     695.29            \n2       744     728.64 -2  -33.348\n3       744     743.18  0  -14.539\n```\n:::\n\n```{.r .cell-code}\nlrtest(model4, model41, model42)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Time (months)` * \n    (`Frequency (times)` + `Recency (months)`)\nModel 2: `whether he/she donated blood in March 2007` ~ `Time (months)` * \n    (`Frequency (times)`)\nModel 3: `whether he/she donated blood in March 2007` ~ `Time (months)` * \n    (`Recency (months)`)\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   6 -347.65                         \n2   4 -364.32 -2 33.347  5.737e-08 ***\n3   4 -371.59  0 14.539  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nplot(model4, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-15-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-15-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-15-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-15-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-15-6.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_model <- tidy(model4)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n**Model 4**\n\n**Model 4**: **`whether he/she donated blood in March 2007`** \\~\n**`Time (months)`** \\* (**`Frequency (times)`** +\n**`Recency (months)`**), interpretation of the model, is given below:\n\n-   **`Time (months)`**: For each additional month, the log-odds of\n    donating blood in March 2007 decrease by 0.016 (p \\< 0.05). This\n    suggests that as time passes, the likelihood of donating blood\n    decreases.\n\n-   **`Frequency (times)`**: For each additional instance of donating\n    blood, the log-odds of donating blood in March 2007 increase by\n    0.273 (p \\< 0.001). This indicates that individuals who donate blood\n    more frequently are more likely to donate in March 2007.\n\n-   **`Recency (months)`**: For each additional month since the last\n    donation, the log-odds of donating blood in March 2007 decrease by\n    0.091 (p \\< 0.01). This suggests that the more time has passed since\n    the last donation, the less likely an individual is to donate in\n    March 2007.\n\n-   Interaction effects:\n\n    -   **`Time (months)`** and **`Frequency (times)`**: The interaction\n        term indicates that the effect of time on the log-odds of\n        donation varies depending on the frequency of donation. However,\n        the coefficient (-0.002) is not statistically significant (p \\>\n        0.05), suggesting that the interaction effect is not meaningful\n        in this model.\n\n    -   **`Time (months)`** and **`Recency (months)`**: The interaction\n        term indicates that the effect of time on the log-odds of\n        donation varies depending on the recency of the last donation.\n        However, the coefficient (-0.0001) is not statistically\n        significant (p \\> 0.05), suggesting that the interaction effect\n        is not meaningful in this model.\n\nThe model has a residual deviance of 695.29 on 742 degrees of freedom,\nindicating a reasonable fit to the data. The AIC value is 707.29, and\nthe BIC value is not provided. Lower AIC and BIC values indicate better\nmodel fit, so in comparison to other models, this model's AIC value can\nbe used to evaluate its relative performance. The PRESS value of\n734.9945 represents the predicted residual sum of squares (PRESS)\nstatistic, which measures the predictive power of the model.\n\nOverall, this model suggests that both the frequency of donation and the\nrecency of the last donation have a significant impact on the likelihood\nof donating blood in March 2007, while the effect of time is also\nsignificant but relatively small. The interaction terms, however, do not\nprovide additional meaningful insights in this context.\n\n\\\n\n**Model 41**\n\n**Model 41:** **`whether he/she donated blood in March 2007`** \\~\n**`Time (months)`** \\* (**`Frequency (times)`**), interpretation of the\nmodel, is given below:\n\n-   **`Time (months)`**: For each additional month, the log-odds of\n    donating blood in March 2007 decrease by 0.028 (p \\< 0.001). This\n    suggests that as time passes, the likelihood of donating blood\n    decreases.\n\n-   **`Frequency (times)`**: For each additional instance of donating\n    blood, the log-odds of donating blood in March 2007 increase by\n    0.341 (p \\< 0.001). This indicates that individuals who donate blood\n    more frequently are more likely to donate in March 2007.\n\n-   Interaction effect: **`Time (months)`** and **`Frequency (times)`**:\n    The interaction term indicates that the effect of time on the\n    log-odds of donation varies depending on the frequency of donation.\n    The coefficient (-0.002) is statistically significant (p \\< 0.001),\n    suggesting that the interaction effect is meaningful in this model.\n    This interaction suggests that the impact of time on donation\n    likelihood differs for individuals with different donation\n    frequencies.\n\nThe model has a residual deviance of 728.64 on 744 degrees of freedom,\nindicating a reasonable fit to the data. The AIC value is 736.64, and\nthe BIC value is not provided. Lower AIC and BIC values indicate better\nmodel fit, so in comparison to other models, this model's AIC value can\nbe used to evaluate its relative performance. The PRESS value of\n755.1073 represents the predicted residual sum of squares (PRESS)\nstatistic, which measures the predictive power of the model.\n\nOverall, this model suggests that both the frequency of donation and the\ntime since the last donation have a significant impact on the likelihood\nof donating blood in March 2007. The interaction term indicates that the\neffect of time depends on the frequency of donation, implying that the\nrelationship between time and donation likelihood varies for individuals\nwith different donation frequencies.\n\n**Model 42**\n\n**Model 42**: **`whether he/she donated blood in March 2007`** \\~\n**`Time (months)`** \\* (**`Recency (months)`**), interpretation of the\nmodel is given below:\n\n-   **`Time (months)`**: The coefficient estimate of 0.0031488 suggests\n    that for each additional month, the log-odds of donating blood in\n    March 2007 increase by 0.0031488 (p = 0.558). However, the p-value\n    is not statistically significant, indicating that the effect of time\n    on donation likelihood is not significant in this model.\n\n-   **`Recency (months)`**: The coefficient estimate of -0.1109247\n    indicates that for each additional month since the last donation,\n    the log-odds of donating blood in March 2007 decrease by 0.1109247\n    (p \\< 0.001). This suggests that individuals who had a longer time\n    since their last donation are less likely to donate in March 2007.\n\n-   Interaction effect: **`Time (months)`** and **`Recency (months)`**:\n    The interaction term between time and recency indicates how the\n    effect of time on the log-odds of donation varies depending on the\n    recency of donation. The coefficient estimate (-0.0004051) suggests\n    that the interaction effect is not statistically significant (p =\n    0.582), indicating that the relationship between time and donation\n    likelihood does not differ significantly based on recency of\n    donation.\n\nThe model has a residual deviance of 743.18 on 744 degrees of freedom,\nindicating a reasonable fit to the data. The AIC value is 751.18, and\nthe BIC value is not provided. Lower AIC and BIC values indicate better\nmodel fit, so in comparison to other models, this model's AIC value can\nbe used to evaluate its relative performance. The PRESS value of\n769.6459 represents the predicted residual sum of squares (PRESS)\nstatistic, which measures the predictive power of the model.\n\nOverall, this model suggests that the recency of donation has a\nsignificant impact on the likelihood of donating blood in March 2007,\nwhereas the effect of time is not statistically significant. The\ninteraction between time and recency does not significantly influence\nthe relationship between time and donation likelihood.\n\n**Conclusion:**\n\nThe analysis of deviance table and likelihood ratio test provide\ninformation on the comparison of the three models: Model4, Model41, and\nModel42.\n\nIn the analysis of deviance table:\n\n**Model4**: This model includes the predictors Time (months), Frequency\n(times), and Recency (months) along with their interactions. It has a\nresidual deviance of 695.29 on 742 degrees of freedom.\n\n**Model41**: This model includes the predictors Time (months) and\nFrequency (times) along with their interaction. It has a residual\ndeviance of 728.64 on 744 degrees of freedom.\n\n**Model42**: This model includes the predictors Time (months) and\nRecency (months) along with their interaction. It has a residual\ndeviance of 743.18 on 744 degrees of freedom.\n\nThe likelihood ratio test compares the models:\n\n**Model4 vs. Model41**: The test indicates that there is a significant\ndifference in deviance between these two models (p-value = 5.737e-08).\nThis suggests that including the predictor Recency (months) in addition\nto Frequency (times) and Time (months) improves the model fit.\n\n**Model4 vs. Model42**: The test indicates that there is a significant\ndifference in deviance between these two models (p-value \\< 2.2e-16).\nThis suggests that including both Frequency (times) and Recency (months)\nin addition to Time (months) and their interactions improves the model\nfit.\n\nBased on these results, Model4, which includes Time (months), Frequency\n(times), Recency (months), and their interactions, appears to provide\nthe best fit to the data. It has the lowest residual deviance among the\nthree models. However, it is important to consider other factors such as\nthe practical significance and interpretability of the model\ncoefficients when choosing the most appropriate model for further\nanalysis or prediction.\\\n\n### Hypothesis 5:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating new variable for average donations per month\nBD$Avg_donations_per_month <- BD$`Frequency (times)` / BD$`Time (months)`\n\nmodel5 <- glm(`whether he/she donated blood in March 2007` ~ Avg_donations_per_month, data = BD, family = binomial(link = \"logit\"))\n\nsummary(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    Avg_donations_per_month, family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.9616  -0.7031  -0.6010  -0.5436   1.9817  \n\nCoefficients:\n                        Estimate Std. Error z value Pr(>|z|)    \n(Intercept)              -1.9584     0.1562 -12.539  < 2e-16 ***\nAvg_donations_per_month   3.7244     0.5720   6.511 7.45e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 774.64  on 746  degrees of freedom\nAIC: 778.64\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code}\nBIC(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 787.8724\n```\n:::\n\n```{.r .cell-code}\nAIC(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 778.6376\n```\n:::\n\n```{.r .cell-code}\nmodel51 <- glm(`whether he/she donated blood in March 2007` ~ Avg_donations_per_month * (`Recency (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model51)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    Avg_donations_per_month * (`Recency (months)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.4531  -0.8399  -0.5196  -0.2718   2.5964  \n\nCoefficients:\n                                           Estimate Std. Error z value Pr(>|z|)\n(Intercept)                                -0.66286    0.25726  -2.577  0.00998\nAvg_donations_per_month                     1.22879    0.84381   1.456  0.14533\n`Recency (months)`                         -0.12162    0.02919  -4.167 3.08e-05\nAvg_donations_per_month:`Recency (months)`  0.13717    0.16477   0.832  0.40514\n                                              \n(Intercept)                                ** \nAvg_donations_per_month                       \n`Recency (months)`                         ***\nAvg_donations_per_month:`Recency (months)`    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 735.34  on 744  degrees of freedom\nAIC: 743.34\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nBIC(model51)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 761.8086\n```\n:::\n\n```{.r .cell-code}\nAIC(model51)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 743.3389\n```\n:::\n\n```{.r .cell-code}\nanova(model5, model51)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: `whether he/she donated blood in March 2007` ~ Avg_donations_per_month\nModel 2: `whether he/she donated blood in March 2007` ~ Avg_donations_per_month * \n    (`Recency (months)`)\n  Resid. Df Resid. Dev Df Deviance\n1       746     774.64            \n2       744     735.34  2   39.299\n```\n:::\n\n```{.r .cell-code}\nlrtest(model5, model51)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: `whether he/she donated blood in March 2007` ~ Avg_donations_per_month\nModel 2: `whether he/she donated blood in March 2007` ~ Avg_donations_per_month * \n    (`Recency (months)`)\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   2 -387.32                         \n2   4 -367.67  2 39.299  2.927e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nplot(model5, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-17-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-17-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-17-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-17-6.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_model <- tidy(model51)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n**Model 5:**\n\nThe model **`whether he/she donated blood in March 2007`** \\~\nAvg_donations_per_month suggests the following interpretation:\n\n-   Avg_donations_per_month: The coefficient estimate of 3.7244\n    indicates that for each additional average donation per month, the\n    log-odds of donating blood in March 2007 increase by 3.7244 (p \\<\n    2e-16). This suggests that individuals who have a higher average\n    number of donations per month are more likely to donate blood in\n    March 2007.\n\nThe model has a residual deviance of 774.64 on 746 degrees of freedom,\nindicating a reasonable fit to the data. The AIC value is 778.64, and\nthe BIC value is 787.8724. Lower AIC and BIC values indicate better\nmodel fit, so in comparison to other models, this model has relatively\nlower AIC and BIC values.\n\nOverall, this model suggests that the average number of donations per\nmonth is a significant predictor of the likelihood of donating blood in\nMarch 2007. As the average number of donations per month increases, the\nprobability of donating blood also increases.\n\n**Model 51:**\n\nThe model **`whether he/she donated blood in March 2007`** \\~\nAvg_donations_per_month \\* (**`Recency (months)`**) suggests the\nfollowing interpretation:\n\n-   Avg_donations_per_month: The coefficient estimate of 1.22879\n    suggests that for each additional unit increase in the average\n    donations per month, the log-odds of donating blood in March 2007\n    increase by 1.22879 (p = 0.14533). However, the p-value is not\n    statistically significant, indicating that the effect of average\n    donations per month is not significant in this model.\n\n-   Recency (months): The coefficient estimate of -0.12162 suggests that\n    for each additional month since the last donation, the log-odds of\n    donating blood in March 2007 decrease by 0.12162 (p \\< 0.001). This\n    indicates that individuals with a longer time since their last\n    donation are less likely to donate blood in March 2007.\n\n-   Interaction effect: The interaction term between\n    Avg_donations_per_month and Recency (months) indicates how the\n    effect of average donations per month varies depending on the\n    recency of donation. However, the coefficient estimate (0.13717)\n    suggests that the interaction effect is not statistically\n    significant (p = 0.40514), indicating that the relationship between\n    average donations per month and donation likelihood does not differ\n    significantly based on recency of donation.\n\nThe model has a residual deviance of 735.34 on 744 degrees of freedom,\nindicating a reasonable fit to the data. The AIC value is 743.34, and\nthe BIC value is 761.8086.\n\n**Conclusion:**\n\nThe analysis of deviance table and likelihood ratio test provide\ninformation on the comparison of two models: Model5 and Model51.\n\nIn the analysis of deviance table:\n\n**Model5**: This model includes the predictor Avg_donations_per_month.\nIt has a residual deviance of 774.64 on 746 degrees of freedom.\n\n**Model51**: This model includes the predictors Avg_donations_per_month\nand Recency (months), along with their interaction. It has a residual\ndeviance of 735.34 on 744 degrees of freedom.\n\nThe likelihood ratio test compares the models:\n\n**Model5 vs. Model51**: The test indicates that there is a significant\ndifference in deviance between these two models (p-value = 2.927e-09).\nThis suggests that including the predictor Recency (months) in addition\nto Avg_donations_per_month improves the model fit.\n\nBased on these results, **Model51**, which includes both\nAvg_donations_per_month and Recency (months) along with their\ninteraction, provides a better fit to the data compared to Model5, which\nincludes only Avg_donations_per_month. **Model51** has a lower residual\ndeviance, indicating a better fit to the data. However, it is important\nto consider other factors such as the practical significance and\ninterpretability of the model coefficients when choosing the most\nappropriate model for further analysis or prediction.\n\n### Hypothesis 6:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating new variable for average monetary value per month\nBD$Avg_monetary_per_month <- BD$`Monetary (c.c. blood)` / BD$`Time (months)`\n\nmodel6 <- glm(`whether he/she donated blood in March 2007` ~ Avg_monetary_per_month, data = BD, family = binomial(link = \"logit\"))\n\nsummary(model6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    Avg_monetary_per_month, family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.9616  -0.7031  -0.6010  -0.5436   1.9817  \n\nCoefficients:\n                        Estimate Std. Error z value Pr(>|z|)    \n(Intercept)            -1.958369   0.156182 -12.539  < 2e-16 ***\nAvg_monetary_per_month  0.014898   0.002288   6.511 7.45e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 774.64  on 746  degrees of freedom\nAIC: 778.64\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code}\nBIC(model6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 787.8724\n```\n:::\n\n```{.r .cell-code}\nAIC(model6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 778.6376\n```\n:::\n\n```{.r .cell-code}\nmodel61 <- glm(`whether he/she donated blood in March 2007` ~ Avg_monetary_per_month * ( `Recency (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model61)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    Avg_monetary_per_month * (`Recency (months)`), family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.4531  -0.8399  -0.5196  -0.2718   2.5964  \n\nCoefficients:\n                                            Estimate Std. Error z value\n(Intercept)                               -0.6628557  0.2572626  -2.577\nAvg_monetary_per_month                     0.0049152  0.0033753   1.456\n`Recency (months)`                        -0.1216242  0.0291860  -4.167\nAvg_monetary_per_month:`Recency (months)`  0.0005487  0.0006591   0.832\n                                          Pr(>|z|)    \n(Intercept)                                0.00998 ** \nAvg_monetary_per_month                     0.14533    \n`Recency (months)`                        3.08e-05 ***\nAvg_monetary_per_month:`Recency (months)`  0.40514    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 735.34  on 744  degrees of freedom\nAIC: 743.34\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nBIC(model61)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 761.8086\n```\n:::\n\n```{.r .cell-code}\nAIC(model61)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 743.3389\n```\n:::\n\n```{.r .cell-code}\nanova(model6, model61)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: `whether he/she donated blood in March 2007` ~ Avg_monetary_per_month\nModel 2: `whether he/she donated blood in March 2007` ~ Avg_monetary_per_month * \n    (`Recency (months)`)\n  Resid. Df Resid. Dev Df Deviance\n1       746     774.64            \n2       744     735.34  2   39.299\n```\n:::\n\n```{.r .cell-code}\nlrtest(model6, model61)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: `whether he/she donated blood in March 2007` ~ Avg_monetary_per_month\nModel 2: `whether he/she donated blood in March 2007` ~ Avg_monetary_per_month * \n    (`Recency (months)`)\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   2 -387.32                         \n2   4 -367.67  2 39.299  2.927e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nplot(model6, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-19-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-19-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-19-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-19-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-19-6.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_model <- tidy(model61)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n**Model 6:** The model **`whether he/she donated blood in March 2007`**\n\\~ Avg_monetary_per_month includes the predictor Avg_monetary_per_month.\nThe coefficient estimate for Avg_monetary_per_month is 0.014898,\nindicating that for each unit increase in Avg_monetary_per_month, the\nlog-odds of donating blood in March 2007 increase by 0.014898 (p \\<\n2e-16). This suggests that individuals with higher average monetary\ndonations per month are more likely to donate blood in March 2007.\n\nThe model has a residual deviance of 774.64 on 746 degrees of freedom,\nindicating a reasonable fit to the data. The AIC value is 778.64, and\nthe BIC value is not provided. Lower AIC and BIC values indicate better\nmodel fit, so in comparison to other models, this model's AIC value can\nbe used to evaluate its relative performance.\n\nIt is important to note that this model focuses on the effect of average\nmonetary donations per month on the likelihood of blood donation, while\nnot considering other variables. Additional factors and potential\ninteractions with Avg_monetary_per_month should be considered to build a\nmore comprehensive model.\\\n\n**Model 61:**\n\nThe model **`whether he/she donated blood in March 2007`** \\~\nAvg_monetary_per_month \\* (**`Recency (months)`**) includes the\npredictors Avg_monetary_per_month and Recency (months), along with their\ninteraction.\n\nThe coefficient estimate for Avg_monetary_per_month is 0.0049152,\nindicating that for each unit increase in Avg_monetary_per_month, the\nlog-odds of donating blood in March 2007 increase by 0.0049152 (p =\n0.145). However, the p-value is not statistically significant,\nsuggesting that the effect of Avg_monetary_per_month on donation\nlikelihood is not significant in this model.\n\nThe coefficient estimate for Recency (months) is -0.1216242, indicating\nthat for each additional month since the last donation, the log-odds of\ndonating blood in March 2007 decrease by 0.1216242 (p \\< 3.08e-05). This\nsuggests that individuals with a longer time since their last donation\nare less likely to donate in March 2007.\n\nThe interaction term between Avg_monetary_per_month and Recency (months)\nis not statistically significant, as indicated by the coefficient\nestimate of 0.0005487 (p = 0.405). This implies that the relationship\nbetween Avg_monetary_per_month and donation likelihood does not\nsignificantly depend on the recency of donation.\n\nThe model has a residual deviance of 735.34 on 744 degrees of freedom,\nindicating a reasonable fit to the data. The AIC value is 743.34, and\nthe BIC value is not provided. Lower AIC and BIC values indicate better\nmodel fit, so in comparison to other models, this model's AIC value can\nbe used to evaluate its relative performance.\n\nIt is important to note that this model focuses on the effect of average\nmonetary donations per month and recency of donation on the likelihood\nof blood donation, while not considering other variables. Additional\nfactors and potential interactions should be considered to build a more\ncomprehensive model.\n\n**Conclusion:**\n\nThe analysis of deviance table and likelihood ratio test compare Model 6\n(**`whether he/she donated blood in March 2007`** \\~\nAvg_monetary_per_month) with Model 61\n(**`whether he/she donated blood in March 2007`** \\~\nAvg_monetary_per_month \\* (**`Recency (months)`**)).\n\nIn the analysis of deviance table:\n\nModel 6 has a residual deviance of 774.64 on 746 degrees of freedom.\nModel 61 has a residual deviance of 735.34 on 744 degrees of freedom.\nThe difference in deviance between the two models is 39.299 with 2\ndegrees of freedom.\n\nThe likelihood ratio test assesses the significance of the difference in\ndeviance:\n\nThe test statistic has a chi-squared distribution with 2 degrees of\nfreedom. The p-value for the test is 2.927e-09, indicating strong\nevidence against the null hypothesis. Therefore, we can conclude that\nthere is a significant difference in deviance between Model 6 and Model\n61. This suggests that including the interaction term between\nAvg_monetary_per_month and Recency (months) improves the model fit.\n\nBased on these results, Model 61, which includes the interaction between\nAvg_monetary_per_month and Recency (months), provides a better fit to\nthe data compared to Model 6. It captures the potential combined effect\nof average monetary donations per month and recency of donation on the\nlikelihood of blood donation.\n\n### Hypothesis 7:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel71 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)` + `Frequency (times)`, data = BD, family = binomial(link = \"logit\"))\n\nsummary(model71)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` + `Frequency (times)`, family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.0353  -0.8184  -0.4983  -0.2714   2.6125  \n\nCoefficients:\n                    Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -0.64702    0.17346  -3.730 0.000191 ***\n`Recency (months)`  -0.11740    0.01667  -7.044 1.87e-12 ***\n`Frequency (times)`  0.06406    0.01565   4.094 4.24e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 724.78  on 745  degrees of freedom\nAIC: 730.78\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nBIC(model71)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 744.632\n```\n:::\n\n```{.r .cell-code}\nAIC(model71)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 730.7798\n```\n:::\n\n```{.r .cell-code}\nmodel72 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)` + `Frequency (times)`+ `Time (months)`, data = BD, family = binomial(link = \"logit\"))\n\nsummary(model72)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` + `Frequency (times)` + `Time (months)`, \n    family = binomial(link = \"logit\"), data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.4875  -0.7933  -0.4997  -0.1701   2.6450  \n\nCoefficients:\n                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -0.449540   0.180349  -2.493 0.012681 *  \n`Recency (months)`  -0.098584   0.017317  -5.693 1.25e-08 ***\n`Frequency (times)`  0.135390   0.025672   5.274 1.34e-07 ***\n`Time (months)`     -0.023092   0.005964  -3.872 0.000108 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 707.87  on 744  degrees of freedom\nAIC: 715.87\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nBIC(model72)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 734.3364\n```\n:::\n\n```{.r .cell-code}\nAIC(model72)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 715.8668\n```\n:::\n\n```{.r .cell-code}\nmodel73 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)` * `Frequency (times)`, data = BD, family = binomial(link = \"logit\"))\n\nsummary(model73)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` * `Frequency (times)`, family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.3019  -0.8079  -0.4994  -0.2725   2.6070  \n\nCoefficients:\n                                        Estimate Std. Error z value Pr(>|z|)\n(Intercept)                            -0.796449   0.204599  -3.893 9.91e-05\n`Recency (months)`                     -0.092477   0.023485  -3.938 8.23e-05\n`Frequency (times)`                     0.090311   0.025025   3.609 0.000307\n`Recency (months)`:`Frequency (times)` -0.004730   0.003521  -1.343 0.179151\n                                          \n(Intercept)                            ***\n`Recency (months)`                     ***\n`Frequency (times)`                    ***\n`Recency (months)`:`Frequency (times)`    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 722.55  on 744  degrees of freedom\nAIC: 730.55\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nBIC(model73)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 749.0217\n```\n:::\n\n```{.r .cell-code}\nAIC(model73)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 730.552\n```\n:::\n\n```{.r .cell-code}\nmodel74 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)` * (`Frequency (times)`+ `Time (months)`), data = BD, family = binomial(link = \"logit\"))\n\nsummary(model74)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` * (`Frequency (times)` + `Time (months)`), \n    family = binomial(link = \"logit\"), data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.8955  -0.7583  -0.4944  -0.3037   2.5230  \n\nCoefficients:\n                                        Estimate Std. Error z value Pr(>|z|)\n(Intercept)                            -0.508146   0.230896  -2.201 0.027753\n`Recency (months)`                     -0.097376   0.030389  -3.204 0.001354\n`Frequency (times)`                     0.191067   0.038652   4.943 7.68e-07\n`Time (months)`                        -0.031099   0.008141  -3.820 0.000133\n`Recency (months)`:`Frequency (times)` -0.008112   0.004104  -1.977 0.048081\n`Recency (months)`:`Time (months)`      0.001195   0.000849   1.408 0.159212\n                                          \n(Intercept)                            *  \n`Recency (months)`                     ** \n`Frequency (times)`                    ***\n`Time (months)`                        ***\n`Recency (months)`:`Frequency (times)` *  \n`Recency (months)`:`Time (months)`        \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 703.70  on 742  degrees of freedom\nAIC: 715.7\n\nNumber of Fisher Scoring iterations: 6\n```\n:::\n\n```{.r .cell-code}\nBIC(model74)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 743.403\n```\n:::\n\n```{.r .cell-code}\nAIC(model74)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 715.6986\n```\n:::\n\n```{.r .cell-code}\nanova(model71,model72, model73, model74)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Recency (months)` + \n    `Frequency (times)`\nModel 2: `whether he/she donated blood in March 2007` ~ `Recency (months)` + \n    `Frequency (times)` + `Time (months)`\nModel 3: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    `Frequency (times)`\nModel 4: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    (`Frequency (times)` + `Time (months)`)\n  Resid. Df Resid. Dev Df Deviance\n1       745     724.78            \n2       744     707.87  1   16.913\n3       744     722.55  0  -14.685\n4       742     703.70  2   18.854\n```\n:::\n\n```{.r .cell-code}\nlrtest(model71,model72, model73, model74)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Recency (months)` + \n    `Frequency (times)`\nModel 2: `whether he/she donated blood in March 2007` ~ `Recency (months)` + \n    `Frequency (times)` + `Time (months)`\nModel 3: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    `Frequency (times)`\nModel 4: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    (`Frequency (times)` + `Time (months)`)\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   3 -362.39                         \n2   4 -353.93  1 16.913  3.913e-05 ***\n3   4 -361.28  0 14.685  < 2.2e-16 ***\n4   6 -351.85  2 18.854  8.054e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nplot(model72, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-21-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-21-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-21-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-21-6.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_model <- tidy(model74)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntidy_model <- tidy(model72)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-22-2.png){width=672}\n:::\n:::\n\n\n**Model71**\n\nThe logistic regression model (model71) you have fitted without the\ninteraction term examines the individual effects of\n**`Recency (months)`** and **`Frequency (times)`** on the likelihood of\ndonating blood in March 2007. Here is an interpretation of the model:\n\n-   **`Recency (months)`**: The coefficient estimate of -0.1174 suggests\n    that for each additional month since the last donation, the log-odds\n    of donating blood in March 2007 decrease by 0.1174 (p \\< 0.001).\n    This indicates that individuals who had a longer time since their\n    last donation are less likely to donate in March 2007.\n\n-   **`Frequency (times)`**: The coefficient estimate of 0.0641\n    indicates that for each additional time the individual donated\n    blood, the log-odds of donating blood in March 2007 increase by\n    0.0641 (p \\< 0.001). This suggests that individuals who have a\n    higher frequency of donating blood are more likely to donate again\n    in March 2007.\n\nBoth **`Recency (months)`** and **`Frequency (times)`** are\nstatistically significant predictors in the model, indicating that they\nhave independent effects on the likelihood of donation in March 2007.\n\nThe model has a residual deviance of 724.78 on 745 degrees of freedom,\nsuggesting a reasonable fit to the data. The AIC value is 730.78, and\nthe BIC value is 744.632. Lower AIC and BIC values indicate better model\nfit.\n\nWhile this model does not include an interaction term, it provides\ninsight into the individual effects of **`Recency (months)`** and\n**`Frequency (times)`** on donation likelihood. If you suspect an\ninteraction effect between these variables, you may consider adding an\ninteraction term to the model and evaluating its significance and\ninterpretation.\n\n**Model72**\n\nThe logistic regression model (model72) you have fitted includes\n**`Recency (months)`**, **`Frequency (times)`**, and **`Time (months)`**\nas predictors to examine their effects on the likelihood of donating\nblood in March 2007. Here is an interpretation of the model:\n\n-   **`Recency (months)`**: The coefficient estimate of -0.0986 suggests\n    that for each additional month since the last donation, the log-odds\n    of donating blood in March 2007 decrease by 0.0986 (p \\< 0.001).\n    This indicates that individuals who had a longer time since their\n    last donation are less likely to donate in March 2007.\n\n-   **`Frequency (times)`**: The coefficient estimate of 0.1354\n    indicates that for each additional time the individual donated\n    blood, the log-odds of donating blood in March 2007 increase by\n    0.1354 (p \\< 0.001). This suggests that individuals who have a\n    higher frequency of donating blood are more likely to donate again\n    in March 2007.\n\n-   **`Time (months)`**: The coefficient estimate of -0.0231 indicates\n    that for each additional month, the log-odds of donating blood in\n    March 2007 decrease by 0.0231 (p \\< 0.001). This suggests that over\n    time, the likelihood of donating blood decreases.\n\nAll three predictors, **`Recency (months)`**, **`Frequency (times)`**,\nand **`Time (months)`**, are statistically significant, indicating that\nthey have independent effects on the likelihood of donation in March\n2007.\n\nThe model has a residual deviance of 707.87 on 744 degrees of freedom,\nindicating a reasonable fit to the data. The AIC value is 715.87, and\nthe BIC value is 734.3364. Lower AIC and BIC values suggest better model\nfit.\n\nBy including **`Time (months)`** in the model, you account for the\ninfluence of time on donation likelihood, which may help control for\npotential confounding effects.\n\n\\\n**Model73**\n\nThe logistic regression model (model73) you have fitted includes an\ninteraction term between **`Recency (months)`** and\n**`Frequency (times)`** to examine if their combined effect is\nsignificant in predicting the likelihood of donating blood in March\n2007. Here is an interpretation of the model:\n\n-   **`Recency (months)`**: The coefficient estimate of -0.0925 suggests\n    that for each additional month since the last donation, the log-odds\n    of donating blood in March 2007 decrease by 0.0925 (p \\< 0.001).\n    This indicates that individuals who had a longer time since their\n    last donation are less likely to donate in March 2007.\n\n-   **`Frequency (times)`**: The coefficient estimate of 0.0903\n    indicates that for each additional time the individual donated\n    blood, the log-odds of donating blood in March 2007 increase by\n    0.0903 (p \\< 0.001). This suggests that individuals who have a\n    higher frequency of donating blood are more likely to donate again\n    in March 2007.\n\n-   Interaction effect: The coefficient estimate of -0.0047 for the\n    interaction term **`Recency (months)`**:**`Frequency (times)`**\n    indicates that the interaction effect is not statistically\n    significant (p = 0.179). This means that the relationship between\n    the log-odds of donation and the combined effect of recency and\n    frequency does not differ significantly from their individual\n    effects.\n\nAll three predictors, **`Recency (months)`**, **`Frequency (times)`**,\nand their interaction, are statistically significant except for the\ninteraction term, indicating that they have independent effects on the\nlikelihood of donation in March 2007.\n\nThe model has a residual deviance of 722.55 on 744 degrees of freedom,\nindicating a reasonable fit to the data. The AIC value is 730.55, and\nthe BIC value is 749.0217. Lower AIC and BIC values suggest better model\nfit.\n\nThe inclusion of the interaction term allows you to examine the combined\neffect of **`Recency (months)`** and **`Frequency (times)`** on the\nlikelihood of donating blood in March 2007, but in this case, the\ninteraction effect is not statistically significant.\\\n\n**Model74**\n\nThe logistic regression model (model74) you have fitted includes an\ninteraction term between **`Recency (months)`** and the combination of\n**`Frequency (times)`** and **`Time (months)`** to examine if their\ncombined effect is significant in predicting the likelihood of donating\nblood in March 2007. Here is an interpretation of the model:\n\n-   **`Recency (months)`**: The coefficient estimate of -0.0974 suggests\n    that for each additional month since the last donation, the log-odds\n    of donating blood in March 2007 decrease by 0.0974 (p = 0.001). This\n    indicates that individuals who had a longer time since their last\n    donation are less likely to donate in March 2007.\n\n-   **`Frequency (times)`**: The coefficient estimate of 0.1911\n    indicates that for each additional time the individual donated\n    blood, the log-odds of donating blood in March 2007 increase by\n    0.1911 (p \\< 0.001). This suggests that individuals who have a\n    higher frequency of donating blood are more likely to donate again\n    in March 2007.\n\n-   **`Time (months)`**: The coefficient estimate of -0.0311 suggests\n    that for each additional month, the log-odds of donating blood in\n    March 2007 decrease by 0.0311 (p = 0.000133). This indicates that\n    individuals who had a longer time since their first donation are\n    less likely to donate in March 2007.\n\n-   Interaction effects:\n\n    -   The coefficient estimate of -0.0081 for the interaction term\n        **`Recency (months)`**:**`Frequency (times)`** indicates that\n        the combined effect of recency and frequency is not\n        statistically significant (p = 0.048). This means that the\n        relationship between the log-odds of donation and the combined\n        effect of recency and frequency is not significantly different\n        from their individual effects.\n\n    -   The coefficient estimate of 0.0012 for the interaction term\n        **`Recency (months)`**:**`Time (months)`** is not statistically\n        significant (p = 0.159). This suggests that the relationship\n        between the log-odds of donation and the combined effect of\n        recency and time is not significantly different from their\n        individual effects.\n\nAll predictors and their interaction terms, except for the interaction\nbetween **`Recency (months)`** and **`Time (months)`**, are\nstatistically significant, indicating their independent effects on the\nlikelihood of donation in March 2007.\n\nThe model has a residual deviance of 703.70 on 742 degrees of freedom,\nindicating a reasonable fit to the data. The AIC value is 715.70, and\nthe BIC value is 743.403. Lower AIC and BIC values suggest better model\nfit.\n\nOverall, the model suggests that both recency and frequency of donation\nhave significant effects on the likelihood of donating blood in March\n2007. The time since the first donation also has a significant effect,\nbut the interaction between recency and time is not significant.\n\n\\\n**Conclusion:**\n\nThe analysis of deviance table and likelihood ratio test results for the\nfour models are as follows:\n\nAnalysis of Deviance Table:\n\n-   Model 1: **`Recency (months)`** + **`Frequency (times)`**\n\n-   Model 2: **`Recency (months)`** + **`Frequency (times)`** +\n    **`Time (months)`**\n\n-   Model 3: **`Recency (months)`** \\* **`Frequency (times)`**\n\n-   Model 4: **`Recency (months)`** \\* (**`Frequency (times)`** +\n    **`Time (months)`**)\n\nThe table shows the residual degrees of freedom, residual deviance, and\nthe difference in deviance compared to the previous model.\n\nLikelihood ratio test:\n\n-   Model 1 vs. Model 2: The p-value is 3.913e-05, indicating that the\n    addition of the **`Time (months)`** variable in Model 2\n    significantly improves the model fit compared to Model 1.\n\n-   Model 2 vs. Model 3: The p-value is \\< 2.2e-16, suggesting that the\n    inclusion of the interaction term between **`Recency (months)`** and\n    **`Frequency (times)`** in Model 3 significantly improves the model\n    fit compared to Model 2.\n\n-   Model 3 vs. Model 4: The p-value is 8.054e-05, indicating that the\n    addition of the interaction term between **`Recency (months)`** and\n    the combination of **`Frequency (times)`** and **`Time (months)`**\n    in Model 4 significantly improves the model fit compared to Model 3.\n\nBased on these results, it appears that including interaction terms in\nthe models improves the fit and captures additional information about\nthe relationship between the predictors and the likelihood of donating\nblood in March 2007. The likelihood ratio test confirms the significance\nof these additional terms in each model.\n\n\\\n\n\\\n\n### Hypothesis 8:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel81 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)` + `Monetary (c.c. blood)`, \n             data = BD, family = binomial(link = \"logit\"))\n\nsummary(model81)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` + `Monetary (c.c. blood)`, family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.0353  -0.8184  -0.4983  -0.2714   2.6125  \n\nCoefficients:\n                          Estimate Std. Error z value Pr(>|z|)    \n(Intercept)             -6.470e-01  1.735e-01  -3.730 0.000191 ***\n`Recency (months)`      -1.174e-01  1.667e-02  -7.044 1.87e-12 ***\n`Monetary (c.c. blood)`  2.562e-04  6.259e-05   4.094 4.24e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 724.78  on 745  degrees of freedom\nAIC: 730.78\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nBIC(model81)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 744.632\n```\n:::\n\n```{.r .cell-code}\nAIC(model81)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 730.7798\n```\n:::\n\n```{.r .cell-code}\nmodel82 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)` + `Monetary (c.c. blood)`+ `Time (months)`, \n             data = BD, family = binomial(link = \"logit\"))\n\nsummary(model82)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` + `Monetary (c.c. blood)` + `Time (months)`, \n    family = binomial(link = \"logit\"), data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.4875  -0.7933  -0.4997  -0.1701   2.6450  \n\nCoefficients:\n                          Estimate Std. Error z value Pr(>|z|)    \n(Intercept)             -0.4495395  0.1803487  -2.493 0.012681 *  \n`Recency (months)`      -0.0985838  0.0173170  -5.693 1.25e-08 ***\n`Monetary (c.c. blood)`  0.0005416  0.0001027   5.274 1.34e-07 ***\n`Time (months)`         -0.0230925  0.0059643  -3.872 0.000108 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 707.87  on 744  degrees of freedom\nAIC: 715.87\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nBIC(model82)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 734.3364\n```\n:::\n\n```{.r .cell-code}\nAIC(model82)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 715.8668\n```\n:::\n\n```{.r .cell-code}\nmodel83 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)` * `Monetary (c.c. blood)`, \n             data = BD, family = binomial(link = \"logit\"))\n\nsummary(model83)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` * `Monetary (c.c. blood)`, family = binomial(link = \"logit\"), \n    data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.3019  -0.8079  -0.4994  -0.2725   2.6070  \n\nCoefficients:\n                                             Estimate Std. Error z value\n(Intercept)                                -7.964e-01  2.046e-01  -3.893\n`Recency (months)`                         -9.248e-02  2.348e-02  -3.938\n`Monetary (c.c. blood)`                     3.613e-04  1.001e-04   3.609\n`Recency (months)`:`Monetary (c.c. blood)` -1.892e-05  1.408e-05  -1.343\n                                           Pr(>|z|)    \n(Intercept)                                9.91e-05 ***\n`Recency (months)`                         8.23e-05 ***\n`Monetary (c.c. blood)`                    0.000307 ***\n`Recency (months)`:`Monetary (c.c. blood)` 0.179151    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 722.55  on 744  degrees of freedom\nAIC: 730.55\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nBIC(model83)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 749.0217\n```\n:::\n\n```{.r .cell-code}\nAIC(model83)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 730.552\n```\n:::\n\n```{.r .cell-code}\nmodel84 <- glm(`whether he/she donated blood in March 2007` ~ `Recency (months)` * (`Monetary (c.c. blood)` + `Time (months)`), \n             data = BD, family = binomial(link = \"logit\"))\n\nsummary(model84)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = `whether he/she donated blood in March 2007` ~ \n    `Recency (months)` * (`Monetary (c.c. blood)` + `Time (months)`), \n    family = binomial(link = \"logit\"), data = BD)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.8955  -0.7583  -0.4944  -0.3037   2.5230  \n\nCoefficients:\n                                             Estimate Std. Error z value\n(Intercept)                                -5.081e-01  2.309e-01  -2.201\n`Recency (months)`                         -9.738e-02  3.039e-02  -3.204\n`Monetary (c.c. blood)`                     7.643e-04  1.546e-04   4.943\n`Time (months)`                            -3.110e-02  8.141e-03  -3.820\n`Recency (months)`:`Monetary (c.c. blood)` -3.245e-05  1.642e-05  -1.977\n`Recency (months)`:`Time (months)`          1.195e-03  8.490e-04   1.408\n                                           Pr(>|z|)    \n(Intercept)                                0.027753 *  \n`Recency (months)`                         0.001354 ** \n`Monetary (c.c. blood)`                    7.68e-07 ***\n`Time (months)`                            0.000133 ***\n`Recency (months)`:`Monetary (c.c. blood)` 0.048081 *  \n`Recency (months)`:`Time (months)`         0.159212    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 820.89  on 747  degrees of freedom\nResidual deviance: 703.70  on 742  degrees of freedom\nAIC: 715.7\n\nNumber of Fisher Scoring iterations: 6\n```\n:::\n\n```{.r .cell-code}\nBIC(model84)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 743.403\n```\n:::\n\n```{.r .cell-code}\nAIC(model84)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 715.6986\n```\n:::\n\n```{.r .cell-code}\nanova(model81,model82, model83, model84)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Recency (months)` + \n    `Monetary (c.c. blood)`\nModel 2: `whether he/she donated blood in March 2007` ~ `Recency (months)` + \n    `Monetary (c.c. blood)` + `Time (months)`\nModel 3: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    `Monetary (c.c. blood)`\nModel 4: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    (`Monetary (c.c. blood)` + `Time (months)`)\n  Resid. Df Resid. Dev Df Deviance\n1       745     724.78            \n2       744     707.87  1   16.913\n3       744     722.55  0  -14.685\n4       742     703.70  2   18.854\n```\n:::\n\n```{.r .cell-code}\nlrtest(model81,model82, model83, model84)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio test\n\nModel 1: `whether he/she donated blood in March 2007` ~ `Recency (months)` + \n    `Monetary (c.c. blood)`\nModel 2: `whether he/she donated blood in March 2007` ~ `Recency (months)` + \n    `Monetary (c.c. blood)` + `Time (months)`\nModel 3: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    `Monetary (c.c. blood)`\nModel 4: `whether he/she donated blood in March 2007` ~ `Recency (months)` * \n    (`Monetary (c.c. blood)` + `Time (months)`)\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   3 -362.39                         \n2   4 -353.93  1 16.913  3.913e-05 ***\n3   4 -361.28  0 14.685  < 2.2e-16 ***\n4   6 -351.85  2 18.854  8.054e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nplot(model81, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-6.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(model82, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-23-12.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_model <- tidy(model84)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntidy_model <- tidy(model82)\n\nggplot(tidy_model, aes(x = estimate, y = reorder(term, estimate))) +\n  geom_vline(xintercept = 0, color = \"gray70\") +\n  geom_point() +\n  geom_errorbarh(aes(xmin = estimate - std.error,\n                     xmax = estimate + std.error)) +\n  labs(x = \"Coefficient Estimate\",\n       y = \"Variable\",\n       title = \"Coefficient estimates with confidence intervals\")\n```\n\n::: {.cell-output-display}\n![](603_Final_Project_Saisrinivas_Ambatipudi_files/figure-html/unnamed-chunk-24-2.png){width=672}\n:::\n:::\n\n\n**Model81**\n\nThe results of the logistic regression model with **`Recency (months)`**\nand **`Monetary (c.c. blood)`** as predictors are as follows:\n\n-   The intercept estimate is -0.647, indicating the log-odds of\n    donating blood when **`Recency (months)`** and\n    **`Monetary (c.c. blood)`** are both zero.\n\n-   The coefficient for **`Recency (months)`** is -0.117, suggesting\n    that for each additional month since the last donation, the log-odds\n    of donating blood decrease by 0.117.\n\n-   The coefficient for **`Monetary (c.c. blood)`** is 0.000256,\n    indicating that for each additional unit of blood donated in terms\n    of volume, the log-odds of donating blood increase by 0.000256.\n\nAll three predictor variables (**`Recency (months)`**,\n**`Monetary (c.c. blood)`**) are significant at the 0.05 significance\nlevel, as their p-values are less than 0.05.\n\nThe null deviance is 820.89, indicating the deviance when the model only\nincludes the intercept. The residual deviance is 724.78, which is the\ndeviance after fitting the model. The AIC value is 730.78, and the BIC\nvalue is 744.632.\n\nThese results suggest that both **`Recency (months)`** and\n**`Monetary (c.c. blood)`** have significant effects on the likelihood\nof donating blood in March 2007.\n\n**Model82**\n\nThe results of the logistic regression model with\n**`Recency (months)`**, **`Monetary (c.c. blood)`**, and\n**`Time (months)`** as predictors are as follows:\n\n-   The intercept estimate is -0.450, indicating the log-odds of\n    donating blood when **`Recency (months)`**,\n    **`Monetary (c.c. blood)`**, and **`Time (months)`** are all zero.\n\n-   The coefficient for **`Recency (months)`** is -0.099, suggesting\n    that for each additional month since the last donation, the log-odds\n    of donating blood decrease by 0.099.\n\n-   The coefficient for **`Monetary (c.c. blood)`** is 0.001, indicating\n    that for each additional unit of blood donated in terms of volume,\n    the log-odds of donating blood increase by 0.001.\n\n-   The coefficient for **`Time (months)`** is -0.023, suggesting that\n    for each additional month since the first donation, the log-odds of\n    donating blood decrease by 0.023.\n\nAll three predictor variables (**`Recency (months)`**,\n**`Monetary (c.c. blood)`**, **`Time (months)`**) are significant at the\n0.05 significance level, as their p-values are less than 0.05.\n\nThe null deviance is 820.89, indicating the deviance when the model only\nincludes the intercept. The residual deviance is 707.87, which is the\ndeviance after fitting the model. The AIC value is 715.87, and the BIC\nvalue is 734.3364.\n\nThese results suggest that **`Recency (months)`**,\n**`Monetary (c.c. blood)`**, and **`Time (months)`** all have\nsignificant effects on the likelihood of donating blood in March 2007.\n\n**Model83**\n\nThe results of the logistic regression model with\n**`Recency (months)`**, **`Monetary (c.c. blood)`**, and their\ninteraction term as predictors are as follows:\n\n-   The intercept estimate is -0.796, indicating the log-odds of\n    donating blood when both **`Recency (months)`** and\n    **`Monetary (c.c. blood)`** are zero.\n\n-   The coefficient for **`Recency (months)`** is -0.092, suggesting\n    that for each additional month since the last donation, the log-odds\n    of donating blood decrease by 0.092.\n\n-   The coefficient for **`Monetary (c.c. blood)`** is 0.000361,\n    indicating that for each additional unit of blood donated in terms\n    of volume, the log-odds of donating blood increase by 0.000361.\n\n-   The coefficient for the interaction term between\n    **`Recency (months)`** and **`Monetary (c.c. blood)`** is\n    -0.00001892, which suggests that the effect of\n    **`Recency (months)`** on the log-odds of donating blood is modified\n    by the value of **`Monetary (c.c. blood)`**.\n\nNone of the coefficients are significant at the 0.05 significance level,\nas their p-values are greater than 0.05. This means that there is no\nsignificant evidence of an interaction effect between\n**`Recency (months)`** and **`Monetary (c.c. blood)`** on the likelihood\nof donating blood in March 2007.\n\nThe null deviance is 820.89, indicating the deviance when the model only\nincludes the intercept. The residual deviance is 722.55, which is the\ndeviance after fitting the model. The AIC value is 730.55, and the BIC\nvalue is 749.0217.\n\nBased on these results, it seems that the interaction between\n**`Recency (months)`** and **`Monetary (c.c. blood)`** does not provide\na significant improvement in explaining the likelihood of donating blood\nin March 2007 compared to the main effects model.\n\n\\\n**Model84**\n\nThe results of the logistic regression model with\n**`Recency (months)`**, **`Monetary (c.c. blood)`**,\n**`Time (months)`**, and their interaction terms as predictors are as\nfollows:\n\n-   The intercept estimate is -0.508, indicating the log-odds of\n    donating blood when all predictor variables are zero.\n\n-   The coefficient for **`Recency (months)`** is -0.097, suggesting\n    that for each additional month since the last donation, the log-odds\n    of donating blood decrease by 0.097.\n\n-   The coefficient for **`Monetary (c.c. blood)`** is 0.0007643,\n    indicating that for each additional unit of blood donated in terms\n    of volume, the log-odds of donating blood increase by 0.0007643.\n\n-   The coefficient for **`Time (months)`** is -0.0311, suggesting that\n    for each additional month since the first donation, the log-odds of\n    donating blood decrease by 0.0311.\n\n-   The coefficient for the interaction term between\n    **`Recency (months)`** and **`Monetary (c.c. blood)`** is\n    -3.245e-05, suggesting that the effect of **`Recency (months)`** on\n    the log-odds of donating blood is modified by the value of\n    **`Monetary (c.c. blood)`**.\n\n-   The coefficient for the interaction term between\n    **`Recency (months)`** and **`Time (months)`** is 0.001195,\n    indicating that the effect of **`Recency (months)`** on the log-odds\n    of donating blood is modified by the value of **`Time (months)`**.\n\nHowever, none of the coefficients are significant at the 0.05\nsignificance level, as their p-values are greater than 0.05. This means\nthat there is no significant evidence of an interaction effect between\nthe predictor variables on the likelihood of donating blood in March\n2007.\n\nThe null deviance is 820.89, indicating the deviance when the model only\nincludes the intercept. The residual deviance is 703.70, which is the\ndeviance after fitting the model. The AIC value is 715.7, and the BIC\nvalue is 743.403.\n\nBased on these results, it seems that the interaction between\n**`Recency (months)`**, **`Monetary (c.c. blood)`**, and\n**`Time (months)`** does not provide a significant improvement in\nexplaining the likelihood of donating blood in March 2007 compared to\nthe main effects model.\n\n## Conclusion\n\nFollowing are the most fitting models for different Hypothesis applied\non the data:\n\n**Model111**:\n\nIn Model111, the variables Frequency (times), Recency (months), and Time (months) are included. The coefficients show that an increase in the frequency of blood donation leads to a higher likelihood of donation in March 2007. Additionally, a longer time since the last donation (higher Recency value) and a longer overall time (higher Time value) decrease the likelihood of donation. The interaction terms, Frequency (times):Recency (months) and Frequency (times):Time (months), were found to be statistically insignificant. The model's deviance residuals and AIC value indicate a good fit to the data.\n\n**Model4**:\n\nModel4 incorporates the variables Time (months), Frequency (times), and Recency (months) along with their interaction terms. The results demonstrate that Frequency (times), Time (months), and Recency (months) significantly impact blood donation in March 2007. A higher frequency of donations and a shorter time since the last donation (lower Recency value) increase the likelihood of donation. The interaction terms, Time (months):Frequency (times) and Time (months):Recency (months), were found to be statistically significant. The model's deviance residuals and AIC value indicate a satisfactory fit to the data.\n\nComparing these two models, both provide valuable insights into the factors influencing blood donation. However, Model111 focuses on main effects only, providing a more interpretable and simpler approach. On the other hand, Model4 incorporates interaction terms, offering a more comprehensive understanding of the relationships among the variables.It is recommended to consider both Model111 and Model4 for further analysis and decision-making. \n\nIn conclusion, based on the analysis, Model111 and Model4 emerge as the most fitting models for the different hypotheses applied on the data. These models provide valuable insights into the factors influencing blood donation and can serve as effective tools for decision-making and strategic planning in blood donation campaigns and initiatives.\n",
    "supporting": [
      "603_Final_Project_Saisrinivas_Ambatipudi_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}