{
  "hash": "f20fd5bb356f7bf65b8f227151b22ebb",
  "result": {
    "markdown": "---\ntitle: \"Homework 4\"\nauthor: \"Akhilesh Kumar\"\ndescription: \"The fourth homework\"\ndate: \"04/23/2023\"\nformat:\n  html:\n    df-print: paged\n    css: styles.css\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Homework3\n  - Akhilesh\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.0.10     ✔ readr     2.1.4 \n✔ forcats   1.0.0      ✔ stringr   1.5.0 \n✔ ggplot2   3.4.1      ✔ tibble    3.1.8 \n✔ lubridate 1.9.2      ✔ tidyr     1.2.1 \n✔ purrr     0.3.5      \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(ggthemes)\nlibrary(stats)\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n\nLoading required package: effects\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\nlibrary(kableExtra)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'kableExtra'\n\nThe following object is masked from 'package:dplyr':\n\n    group_rows\n```\n:::\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Question 1\n\nFor recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + (53.8 * x1) + (2.84* x2).\n\n## A\n\nA particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. \nFind the predicted selling price and the residual, and interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx1 = 1240\nx2 = 18000\n\nPredicted_selling_price <-  -10536 + (53.8 * x1) + (2.84 * x2)\n\nPredicted_selling_price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nActual_selling_price = 145000\n\nResidual <- Actual_selling_price-Predicted_selling_price\n\nResidual\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37704\n```\n:::\n:::\n\n\nBased on the given data, the prediction equation suggests that a home with 1240 square feet on a lot of 18,000 square feet in Jacksonville, Florida should have a selling price of $107,296. However, the actual selling price of this particular home was $145,000, which is higher than the predicted selling price. This results in a residual of $37,704, indicating that the prediction equation underestimated the selling price of this home.\n\nThis suggests that while the prediction equation provides some insight into the selling prices of homes in Jacksonville, Florida based on size of the home and lot size, it is not a perfect predictor. Other factors, such as the condition of the home, location, and other amenities, may also play a role in determining the selling price of a home. Therefore, it is important to consider multiple factors when predicting the selling price of a home in Jacksonville, Florida.\n\n## B\n\nSince the prediction equation for home selling price is ŷ = −10,536 + (53.8 * x1) + (2.84 * x2), where x1 represents the home size and x2 represents the lot size, the impact of changing home size on the selling price while holding lot size constant, can be determined.\n\nSpecifically, for each additional square foot of home size (x1), the house selling price is expected to increase by 53.8 dollars, assuming lot size is fixed. This is because the coefficient of x1 in the equation is 53.8.\n\nThe impact of lot size (x2) on the selling price is also accounted for in the equation, with a coefficient of 2.84. However, if lot size is held constant, then this coefficient does not affect the output, so only coefficient of x1 is required to be considered .\n\nTherefore, if the home size is increased by one unit (representing one additional square foot), the predicted selling price would increase by 53.8 units, assuming the lot size remains constant.\n\n## C\n\nAccording to this prediction equation, for fixed home size, how much would lot size need \nto increase to have the same impact as a one-square-foot increase in home size?\n\nFor fixed home size,\n53.8 * 1 = 2.84x2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx2 <- 53.8/2.84\nx2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\nIt can be observed that the predicted selling price of a house is estimated to increase by approximately $3 for every additional square foot of lot size, assuming the house size is fixed. Therefore, to achieve a similar impact on the predicted selling price as an increment of one square foot in house size,  lot size should  be increased by roughly 19 square feet. This is because every one-square-foot increase in house size is predicted to increase the selling price by around $53.8, which is equivalent to an increase of approximately 18.94 square feet in lot size. Therefore, an increase in lot size of about 18.94 square feet would have an identical effect on the predicted selling price as an increase of one square foot in home size.\n\n## Question 2\n\n(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.\n\n\n\n## A\n\nTest the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Box plot\ndata(\"salary\")\nggplot(salary, aes(x = sex, y = salary, fill = sex)) +\n  geom_boxplot() +\n  labs(x = \"Sex\", y = \"Salary\", title = \"Salary Comparison between Male & Female\") +\n  theme_void() +\n  theme(axis.title = element_text(color = \"navyblue\", size = 13, face = \"bold\"), \n        axis.text.x = element_text(color = \"navyblue\", size = 10), \n        axis.text.y = element_text(color = \"navyblue\", size = 8), \n        plot.title = element_text(color = \"navyblue\", size = 14, face = \"bold\", hjust = 0.5)) +\n  scale_fill_manual(values = c(\"#FF5C35\", \"#00B945\"))\n```\n\n::: {.cell-output-display}\n![](HW4_AkhileshKumar_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summarize salary data\nsummary_salary <- salary %>%\n  group_by(sex) %>%\n  summarise(average_salary = mean(salary), min_salary = min(salary), max_salary = max(salary))\n\n# Create salary comparison plot\nggplot(summary_salary, aes(x = sex, y = average_salary)) +   \n  geom_point(color = \"red\", size = 4) +\n  geom_errorbar(aes(ymin = min_salary, ymax = max_salary), color = \"#32CD32\", width = 0.5) +\n  labs(x = \"Sex\", y = \"Salary\", title = \"Salary Comparison between Male & Female\") +\n  geom_text(aes(y = max_salary, label = max_salary), size = 3, color = \"#000080\", hjust = -3) +\n  geom_text(aes(y = min_salary, label = min_salary), size = 3, color = \"#000080\", hjust = -3) +\n  geom_text(aes(label = round(average_salary, digits = 2)), size = 3, color = \"#000080\", hjust = -0.5) +\n  theme_minimal() +\n  theme(axis.text.x = element_text(color = \"#33475b\", size = 10, face = \"bold\"),\n        axis.text.y = element_text(color = \"#33475b\", size = 8, face = \"bold\"),\n        axis.title.y = element_text(color = \"#33475b\", size = 13, face = \"bold\"),\n        axis.title.x = element_text(color = \"#33475b\", size = 13, face = \"bold\"),\n        plot.title = element_text(color = \"#000080\", size = 14, face = \"bold\", hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](HW4_AkhileshKumar_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nBased solely on the visuals, it is clear that the average salary for men and women differ. However, it is uncertain if this difference is statistically significant. Additionally, while men generally have a higher mean salary, there is one outlier female who earns the most, indicating a wider salary range for women. Nonetheless, further analysis is necessary to determine whether these findings are significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# t.test to text the null hypothesis that men and women make the same amount. \n\nt.test(salary~sex, data = salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  salary by sex\nt = 1.7744, df = 21.591, p-value = 0.09009\nalternative hypothesis: true difference in means between group Male and group Female is not equal to 0\n95 percent confidence interval:\n -567.8539 7247.1471\nsample estimates:\n  mean in group Male mean in group Female \n            24696.79             21357.14 \n```\n:::\n:::\n\nBased on a Welch Two Sample t-test, I found that the mean salary for men is higher than women. However, the p-value of 0.09 is higher than a significance level of 5%, indicating that the null hypothesis of 'the mean salary for men and women are the same', cannot be rejected. Therefore, It cannot be concluded that there is a significant difference in the mean salary between men and women.\n\n## B\n\nRun a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(salary ~ ., data = salary)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\nThe linear regression analysis shows that there is a significant relationship between salary and the variables degree, rank, sex, year, and years since degree completion. However, the p-value for the variable sex is 0.214, which is higher than the significance level of 0.05, indicating that null hypothesis: that there is no difference in mean salary between males and females, cannot be rejected. Further, at a 95% confidence interval, the difference in mean salary between males and females ranges from -$697.82 to $3,030.56, suggesting that 95% of the time, males will make between $697.82 more and $3,030.56 less than females.\n\n\n## C\n\nInterpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables\n\n\n**degreePhD:**\n\n- The coefficient estimate is 1388.61 with a standard error of 1018.75. \n- The p-value is 0.180, which is greater than 0.05, indicating that the coefficient for \"degreePhD\" is not statistically significant. \n- This means that there is insufficient evidence to suggest that having a PhD degree has a statistically significant effect on salary, after accounting for other variables in the model.\nThis suggests that having a PhD degree does not have a significant effect on salary after accounting for the other variables in the model.\n\n**rankAssoc:**\n\n- The coefficient estimate is 5292.36 with a standard error of 1145.40. \n- The p-value is 3.22e-05, which is less than 0.05, indicating that the coefficient for \"rankAssoc\" is statistically significant. \n- This means that having an associate professor rank is associated with a salary increase of $5292.36 on average, compared to assistant professors, after controlling for the other variables in the model.\n\n**rankProf:**\n\n- The coefficient estimate is 11118.76 with a standard error of 1351.77. \n- The p-value is 1.62e-10, which is less than 0.05, indicating that the coefficient for \"rankProf\" is statistically significant. \n- This means that having a professor rank is associated with a salary increase of $11118.76 on average, compared to assistant professors, after controlling for the other variables in the model.\n\n**sexFemale:**\n\n- The coefficient estimate is 1166.37 with a standard error of 925.57. \n- The p-value is 0.214, which is greater than 0.05, indicating that the coefficient for \"sexFemale\" is not statistically significant. \n- This suggests that gender does not have a significant effect on salary after accounting for the other variables in the model.\n\n**year:**\n\n- The coefficient estimate is 476.31 with a standard error of 94.91. \n- The p-value is 8.65e-06, which is less than 0.05, indicating that the coefficient for \"year\" is statistically significant.\n- This means that for each additional year, there is an increase in salary of $476.31 on average, after controlling for the other variables in the model.\n\n**ysdeg:**\n\n- The coefficient estimate is -124.57 with a standard error of 77.49. \n- The p-value is 0.115, which is greater than 0.05, indicating that the coefficient for \"ysdeg\" is not statistically significant. \n- This suggests that the years since receiving a degree does not have a significant effect on salary after accounting for the other variables in the model.\n\nOverall, the model shows that rank and years of experience are the most significant predictors of salary in this dataset.\n\n## D\n\nChange the baseline category for the rank variable. Interpret the coefficients related to rank again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank <- relevel(salary$rank, ref = 'Prof')\ncolnames(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"degree\" \"rank\"   \"sex\"    \"year\"   \"ysdeg\"  \"salary\"\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(salary ~ ., salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nsexFemale     1166.37     925.57   1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nAfter changing the baseline category for the rank variable, an Associate can expect a 6483.0 dollar decrease in salary compared to Professor, while a Assistant can expect a 11890.3 dollar salary decrease compared to Professor. Both ranks have significance levels well below 0.05 and it can be determined that rank does have a statistically significant impact on salary.\n\nInterpreting the coefficients related to rank after changing the baseline category to \"Prof\", I see that the coefficients for both rankAsst and rankAssoc are negative. This means that the average salary for assistant professors and associate professors is lower than the average salary for full professors, holding all other variables constant.\n\nThe coefficient for rankAsst is -11118.76, indicating that assistant professors earn, on average, $11,118.76 less than full professors when all other variables are held constant. The coefficient for rankAssoc is -5826.40, indicating that associate professors earn, on average, $5,826.40 less than full professors when all other variables are held constant.\n\nThe interpretation of these coefficients assumes that the other variables included in the model (degreePhD, sexFemale, year, and ysdeg) are held constant.\n\n## E\n\nFinkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “[a] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’ ” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.Exclude the variable rank, refit, and summarize how your findings changed, if they did\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(salary ~ degree + sex + year + ysdeg, salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\n\n- The coefficient for the predictor variable degreePhD is -3299.35, with a standard error of 1302.52, and a p-value of 0.014704, indicating a significant negative relationship between having a PhD degree and salary.\n\n- The coefficient for the predictor variable sexFemale is -1286.54, with a standard error of 1313.09, and a p-value of 0.332209, indicating that there is no significant difference in salary between male and female employees.\n\n- The coefficient for the predictor variable year is 351.97, with a standard error of 142.48, and a p-value of 0.017185, indicating a significant positive relationship between the year of employment and salary.\n\n- The coefficient for the predictor variable ysdeg is 339.40, with a standard error of 80.62, and a p-value of 0.000114, indicating a significant positive relationship between the number of years of service and salary.\n\nThe R-squared value of the model is 0.6312, indicating that the predictors explain 63.12% of the variability in salary. The adjusted R-squared value, which adjusts for the number of predictors in the model, is 0.5998.\n\nThe F-statistic of the model is 20.11 with 4 and 47 degrees of freedom, and the p-value is 1.048e-09, indicating that the model is a good fit for the data and that at least one of the predictors is significantly related to salary.\n\n## F\n\nEveryone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.\n\nCreate a new variable that would allow you to test this hypothesis and run another multiple regression  model  to  test  this.  Select  variables  carefully  to  make  sure there  is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$NewDean <- ifelse(salary$ysdeg <= 15, 1, 0)\n\nsummary(lm(salary ~ sex + rank + degree + year+ NewDean, data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex + rank + degree + year + NewDean, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3403.3 -1387.0  -167.0   528.2  9233.8 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  24425.32    1107.52  22.054  < 2e-16 ***\nsexFemale      907.14     840.54   1.079   0.2862    \nrankAsst    -11096.95    1191.00  -9.317 4.54e-12 ***\nrankAssoc    -6124.28    1028.58  -5.954 3.65e-07 ***\ndegreePhD      818.93     797.48   1.027   0.3100    \nyear           434.85      78.89   5.512 1.65e-06 ***\nNewDean       2163.46    1072.04   2.018   0.0496 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2362 on 45 degrees of freedom\nMultiple R-squared:  0.8594,\tAdjusted R-squared:  0.8407 \nF-statistic: 45.86 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nTo test the hypothesis, a dummy variable (NewDean) was created. It is coded as 1 if ysdeg is 15 years or less, and 0 otherwise.\n\n\nThese correlations indicate that there is a relationship between the variables and they might have a similar impact on the response variable (salary). To address this issue, the variable ysdeg was removed due to its overlap with NewDean variable (since the NewDean variable was based on ysdeg).\n\nThen, I fit a new regression model, including the variables of sex, rank, degree, year and NewDean. According to the regression results, employees hired under the new dean are expected to earn $2163.46 more than those hired prior to the new dean's tenure. However, this correlation is only significant at the 0.0496 level. While it is statistically significant, it is not the most powerful predictor of salary.\n\n## Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"house.selling.price\")\nhouse.selling.price\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"case\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Taxes\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Beds\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Baths\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"New\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Price\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Size\"],\"name\":[7],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"3104\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"279900\",\"7\":\"2048\"},{\"1\":\"2\",\"2\":\"1173\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"146500\",\"7\":\"912\"},{\"1\":\"3\",\"2\":\"3076\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"237700\",\"7\":\"1654\"},{\"1\":\"4\",\"2\":\"1608\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"200000\",\"7\":\"2068\"},{\"1\":\"5\",\"2\":\"1454\",\"3\":\"3\",\"4\":\"3\",\"5\":\"0\",\"6\":\"159900\",\"7\":\"1477\"},{\"1\":\"6\",\"2\":\"2997\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"499900\",\"7\":\"3153\"},{\"1\":\"7\",\"2\":\"4054\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"265500\",\"7\":\"1355\"},{\"1\":\"8\",\"2\":\"3002\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"289900\",\"7\":\"2075\"},{\"1\":\"9\",\"2\":\"6627\",\"3\":\"5\",\"4\":\"4\",\"5\":\"0\",\"6\":\"587000\",\"7\":\"3990\"},{\"1\":\"10\",\"2\":\"320\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"70000\",\"7\":\"1160\"},{\"1\":\"11\",\"2\":\"630\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"64500\",\"7\":\"1220\"},{\"1\":\"12\",\"2\":\"1780\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"167000\",\"7\":\"1690\"},{\"1\":\"13\",\"2\":\"1630\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"114600\",\"7\":\"1380\"},{\"1\":\"14\",\"2\":\"1530\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"103000\",\"7\":\"1590\"},{\"1\":\"15\",\"2\":\"930\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"101000\",\"7\":\"1050\"},{\"1\":\"16\",\"2\":\"590\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"70000\",\"7\":\"770\"},{\"1\":\"17\",\"2\":\"1050\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"85000\",\"7\":\"1410\"},{\"1\":\"18\",\"2\":\"20\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"22500\",\"7\":\"1060\"},{\"1\":\"19\",\"2\":\"870\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"90000\",\"7\":\"1300\"},{\"1\":\"20\",\"2\":\"1320\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"133000\",\"7\":\"1500\"},{\"1\":\"21\",\"2\":\"1350\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"90500\",\"7\":\"820\"},{\"1\":\"22\",\"2\":\"5616\",\"3\":\"4\",\"4\":\"3\",\"5\":\"1\",\"6\":\"577500\",\"7\":\"3949\"},{\"1\":\"23\",\"2\":\"680\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"142500\",\"7\":\"1170\"},{\"1\":\"24\",\"2\":\"1840\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"160000\",\"7\":\"1500\"},{\"1\":\"25\",\"2\":\"3680\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"240000\",\"7\":\"2790\"},{\"1\":\"26\",\"2\":\"1660\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"87000\",\"7\":\"1030\"},{\"1\":\"27\",\"2\":\"1620\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"118600\",\"7\":\"1250\"},{\"1\":\"28\",\"2\":\"3100\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"140000\",\"7\":\"1760\"},{\"1\":\"29\",\"2\":\"2070\",\"3\":\"2\",\"4\":\"3\",\"5\":\"0\",\"6\":\"148000\",\"7\":\"1550\"},{\"1\":\"30\",\"2\":\"830\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"69000\",\"7\":\"1120\"},{\"1\":\"31\",\"2\":\"2260\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"176000\",\"7\":\"2000\"},{\"1\":\"32\",\"2\":\"1760\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"86500\",\"7\":\"1350\"},{\"1\":\"33\",\"2\":\"2750\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"180000\",\"7\":\"1840\"},{\"1\":\"34\",\"2\":\"2020\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"179000\",\"7\":\"2510\"},{\"1\":\"35\",\"2\":\"4900\",\"3\":\"3\",\"4\":\"3\",\"5\":\"1\",\"6\":\"338000\",\"7\":\"3110\"},{\"1\":\"36\",\"2\":\"1180\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"130000\",\"7\":\"1760\"},{\"1\":\"37\",\"2\":\"2150\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"163000\",\"7\":\"1710\"},{\"1\":\"38\",\"2\":\"1600\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"125000\",\"7\":\"1110\"},{\"1\":\"39\",\"2\":\"1970\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"100000\",\"7\":\"1360\"},{\"1\":\"40\",\"2\":\"2060\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"100000\",\"7\":\"1250\"},{\"1\":\"41\",\"2\":\"1980\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"100000\",\"7\":\"1250\"},{\"1\":\"42\",\"2\":\"1510\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"146500\",\"7\":\"1480\"},{\"1\":\"43\",\"2\":\"1710\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"144900\",\"7\":\"1520\"},{\"1\":\"44\",\"2\":\"1590\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"183000\",\"7\":\"2020\"},{\"1\":\"45\",\"2\":\"1230\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"69900\",\"7\":\"1010\"},{\"1\":\"46\",\"2\":\"1510\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"60000\",\"7\":\"1640\"},{\"1\":\"47\",\"2\":\"1450\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"127000\",\"7\":\"940\"},{\"1\":\"48\",\"2\":\"970\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"86000\",\"7\":\"1580\"},{\"1\":\"49\",\"2\":\"150\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"50000\",\"7\":\"860\"},{\"1\":\"50\",\"2\":\"1470\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"137000\",\"7\":\"1420\"},{\"1\":\"51\",\"2\":\"1850\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"121300\",\"7\":\"1270\"},{\"1\":\"52\",\"2\":\"820\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"81000\",\"7\":\"980\"},{\"1\":\"53\",\"2\":\"2050\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"188000\",\"7\":\"2300\"},{\"1\":\"54\",\"2\":\"710\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"85000\",\"7\":\"1430\"},{\"1\":\"55\",\"2\":\"1280\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"137000\",\"7\":\"1380\"},{\"1\":\"56\",\"2\":\"1360\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"145000\",\"7\":\"1240\"},{\"1\":\"57\",\"2\":\"830\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"69000\",\"7\":\"1120\"},{\"1\":\"58\",\"2\":\"800\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"109300\",\"7\":\"1120\"},{\"1\":\"59\",\"2\":\"1220\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"131500\",\"7\":\"1900\"},{\"1\":\"60\",\"2\":\"3360\",\"3\":\"4\",\"4\":\"3\",\"5\":\"0\",\"6\":\"200000\",\"7\":\"2430\"},{\"1\":\"61\",\"2\":\"210\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"81900\",\"7\":\"1080\"},{\"1\":\"62\",\"2\":\"380\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"91200\",\"7\":\"1350\"},{\"1\":\"63\",\"2\":\"1920\",\"3\":\"4\",\"4\":\"3\",\"5\":\"0\",\"6\":\"124500\",\"7\":\"1720\"},{\"1\":\"64\",\"2\":\"4350\",\"3\":\"3\",\"4\":\"3\",\"5\":\"0\",\"6\":\"225000\",\"7\":\"4050\"},{\"1\":\"65\",\"2\":\"1510\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"136500\",\"7\":\"1500\"},{\"1\":\"66\",\"2\":\"4154\",\"3\":\"3\",\"4\":\"3\",\"5\":\"0\",\"6\":\"381000\",\"7\":\"2581\"},{\"1\":\"67\",\"2\":\"1976\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"250000\",\"7\":\"2120\"},{\"1\":\"68\",\"2\":\"3605\",\"3\":\"3\",\"4\":\"3\",\"5\":\"1\",\"6\":\"354900\",\"7\":\"2745\"},{\"1\":\"69\",\"2\":\"1400\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"140000\",\"7\":\"1520\"},{\"1\":\"70\",\"2\":\"790\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"89900\",\"7\":\"1280\"},{\"1\":\"71\",\"2\":\"1210\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"137000\",\"7\":\"1620\"},{\"1\":\"72\",\"2\":\"1550\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"103000\",\"7\":\"1520\"},{\"1\":\"73\",\"2\":\"2800\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"183000\",\"7\":\"2030\"},{\"1\":\"74\",\"2\":\"2560\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"140000\",\"7\":\"1390\"},{\"1\":\"75\",\"2\":\"1390\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"160000\",\"7\":\"1880\"},{\"1\":\"76\",\"2\":\"5443\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"434000\",\"7\":\"2891\"},{\"1\":\"77\",\"2\":\"2850\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"130000\",\"7\":\"1340\"},{\"1\":\"78\",\"2\":\"2230\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"123000\",\"7\":\"940\"},{\"1\":\"79\",\"2\":\"20\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"21000\",\"7\":\"580\"},{\"1\":\"80\",\"2\":\"1510\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"85000\",\"7\":\"1410\"},{\"1\":\"81\",\"2\":\"710\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"69900\",\"7\":\"1150\"},{\"1\":\"82\",\"2\":\"1540\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"125000\",\"7\":\"1380\"},{\"1\":\"83\",\"2\":\"1780\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"162600\",\"7\":\"1470\"},{\"1\":\"84\",\"2\":\"2920\",\"3\":\"2\",\"4\":\"2\",\"5\":\"1\",\"6\":\"156900\",\"7\":\"1590\"},{\"1\":\"85\",\"2\":\"1710\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"105900\",\"7\":\"1200\"},{\"1\":\"86\",\"2\":\"1880\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"167500\",\"7\":\"1920\"},{\"1\":\"87\",\"2\":\"1680\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"151800\",\"7\":\"2150\"},{\"1\":\"88\",\"2\":\"3690\",\"3\":\"5\",\"4\":\"3\",\"5\":\"0\",\"6\":\"118300\",\"7\":\"2200\"},{\"1\":\"89\",\"2\":\"900\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"94300\",\"7\":\"860\"},{\"1\":\"90\",\"2\":\"560\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"93900\",\"7\":\"1230\"},{\"1\":\"91\",\"2\":\"2040\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"165000\",\"7\":\"1140\"},{\"1\":\"92\",\"2\":\"4390\",\"3\":\"4\",\"4\":\"3\",\"5\":\"1\",\"6\":\"285000\",\"7\":\"2650\"},{\"1\":\"93\",\"2\":\"690\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"45000\",\"7\":\"1060\"},{\"1\":\"94\",\"2\":\"2100\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"124900\",\"7\":\"1770\"},{\"1\":\"95\",\"2\":\"2880\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"147000\",\"7\":\"1860\"},{\"1\":\"96\",\"2\":\"990\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"176000\",\"7\":\"1060\"},{\"1\":\"97\",\"2\":\"3030\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"196500\",\"7\":\"1730\"},{\"1\":\"98\",\"2\":\"1580\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"132200\",\"7\":\"1370\"},{\"1\":\"99\",\"2\":\"1770\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"88400\",\"7\":\"1560\"},{\"1\":\"100\",\"2\":\"1430\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"127200\",\"7\":\"1340\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## A\n\nUsing the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Price ~ Size + New, data = house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThe coefficient of Size is estimated to be 116.132, which means that for each unit increase in Size, it is expected that the Price would increase by an average of 116.132. The t-value of 13.204 is highly significant (p < 0.001), indicating that the coefficient is significantly different from zero. Therefore, the null hypothesis that there is no linear relationship between Size and Price is rejected.\n\nThe coefficient of New is estimated to be 57736.283, which means that its price would be $57736.283 higher than a house that is not new, all other things being equal. The t-value of 3.095 is also significant (p = 0.00257), indicating that the coefficient is significantly different from zero. Therefore, the null hypothesis that there is no linear relationship between New and Price, is rejected.\n\nThe intercept coefficient is estimated to be -40230.867, which is the expected value of Price when both Size and New are equal to zero. However, since there are no houses with zero Size and zero New, this value does not have any practical meaning in this context.\n\nThe adjusted R-squared of this model is 0.7169, which means that approximately 71.7% of the variability in Price can be explained by Size and New. The F-statistic of 126.3 with p-value < 2.2e-16 indicates that the model as a whole is statistically significant, and that the predictor variables are jointly significant in explaining the variation in the response variable.\n\n## B\n\nReport and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes\n\nBased on the above regression model, the prediction equation for the selling price of a home would be selling price = -40230.867 + 116.132 * size + 57736.283 * new where size = the size of the home and new = 1 if the home is new or new = 0 if the home is not new.\n\n- For new homes, z = 1 so the prediction equation for the selling price of a new home is selling price = -40230.867 + 116.132 * size + 57736.283 or selling price = 17505.416 + 116.132 * size\n\n- For old homes, z = 0 so the prediction equation for the selling price of a not-new home is selling price = -40230.867 + 116.132 * size + 0 or selling price = -40230.867 + 116.132 * size\n\nBased on the regression analysis and the obtained equations, we can infer that the variables Size and New have a positive influence on the selling price of a home. The coefficient of Size denotes that there is a linear association between the size of a home and its selling prce. This implies that for every 1 sq foot increase in the size of a home, we can expect an estimated increase of ~$116 in the selling price, while holding all other factors constant. On the other hand, the coefficient of New indicates that new homes, on average, are sold for ~$57,736 more than old homes of the same size.\n\nSince there is no interaction term in the model, the impact of each variable is analyzed separately. This suggests that the effect of Size on the selling price is consistent for both new and old homes. Moreover, both Size and New have been found to be statistically significant, respectively, based on their small p-values.\n\n## C\n\nFind the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSize <- 3000\n\n#predicted selling price for a new home\nNew_Price = 17505.416 + (116.132 * Size)\n\n#predicted selling price for a not new home\nOld_Price = -40230.867 + (116.132 * Size)\n\nNew_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 365901.4\n```\n:::\n\n```{.r .cell-code}\nOld_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 308165.1\n```\n:::\n:::\n\nBased on the predictive formulas from the regression model, the predicted selling price for a new home of 3000 sq. feet is $365,901 and the predicted selling price for a not-new home of the same size is $308,165.\n\n## D\nFit another model, this time with an interaction term allowing interaction between size and new, and report the regression results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Price ~ Size*New, data = house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n- The new model includes an interaction term between Size and New, allowing for the possibility that the effect of Size on Price differs depending on whether a home is new or not.\n- The coefficient for the interaction term is positive and statistically significant (p < 0.01), indicating that the effect of Size on Price is stronger for new homes compared to not-new homes.\n- The coefficient for New is negative but not statistically significant (p > 0.05), suggesting that being a new home does not have a significant impact on Price when Size and the interaction term are taken into account.\n- The coefficient for Size is positive and highly significant (p < 0.001), indicating that increasing the size of a home leads to a higher predicted selling price, all else being equal.\n- The adjusted R-squared for the model is 0.7363, indicating that the model explains around 74% of the variation in selling prices, after accounting for the effects of Size, New, and the interaction term.\n\n## E\n\nReport the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.\n\nThe predicted selling price, based on the new regression that includes interaction between Size and Newness, would look like:\n\nHouse_Price = -22227.808 + 104.438 * Size - 78527.50 * z + 61.916 * Size * z\n\n\nWhere Size = the size of the home and z = 1 if the home is new or z = 0 if the home is not new.\n\nNew_Price = -22227.808 + 104.438 * Size - 78527.50 * 1  + 61.916 * Size * 1\n\n          = -22227.808 + 104.438 * Size - 78527.50  + 61.916 * Size\n          \n          = -100755 + 166.354 * Size\n\nOld_Price = -22227.808 + 104.438 * Size - 78527.50 * 0 + 61.916 * Size * 0\n\n          = -22227.808 + 104.438 * Size\n\n\n\n## F\n\nFind the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSize <- 3000\n\n# predicted selling price for a new home\n\nNew_Price = -22227.808 + 104.438 * Size - 78527.50 * 1 + 61.916 * Size * 1\n\n#predicted selling price for a not new home\n\nOld_Price = -22227.808 + 104.438 * Size\n\nNew_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 398306.7\n```\n:::\n\n```{.r .cell-code}\nOld_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 291086.2\n```\n:::\n:::\n\nBased on the predictive formulas from the regression model, the predicted selling price for a new home that is 3000 sq. feet is $398,306.70 and the predicted selling price for a not new home of the same size is $291,086.20.\n\n## G\n\nFind the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSize <- 1500\n\n# predicted selling price for a new home\n\nNew_Price = -22227.81 + 104.438 * Size - 78527.50 * 1 + 61.916 * Size * 1\n\n#predicted selling price for a not new home\n\nOld_Price = -22227.81 + 104.438 * Size\n\nNew_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 148775.7\n```\n:::\n\n```{.r .cell-code}\nOld_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 134429.2\n```\n:::\n:::\n\n\nAs size of home goes up, the difference in predicted selling prices between old and new homes become larger.\n\nFor a 3,000-square-foot house, the difference in price between one that’s new and one that’s not is $107220.5.\n\nFor a 1,500-square-food-house, the difference in price between one that’s new and one that’s not is $14352.5.\n\nAs the houses get bigger in size, the impact of whether the house is new or not new increases.\n\n## H\n\nDo you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?\n\nIn the context of predicting the selling price of a house, I analyzed two regression models - one that includes an interaction term between the size of a house and whether it's new or not, and another that does not include the interaction term. I compared the two models to determine which one better represents the relationship between the size of a house, its age, and its selling price.\n\nUpon comparing the two models, I found that the model that allows for interactions does a better job of representing the relationship between the size of a house and whether it's new or not to the selling price. The adjusted R-squared for the model with interaction is 0.7363, which is slightly higher than the adjusted R-squared for the model without interaction, which is 0.7169. This suggests that the model with interaction explains slightly more of the variation in the selling price due to the interaction between size, new and selling price.\n\nFurthermore, the model with interaction includes a created variable Size:New, which is statistically significant. This means that null hypothesis that Size:New is not correlated to selling price can be rejected, and it can be concluded that the interaction between the size of a house and whether it's new or not has a significant impact on its selling price.\n\nThe model that includes the interaction term it more preferable, as it explains slightly more of the variation in the selling price due to the interaction between size, new and selling price. Additionally, the statistical significance of the Size:New variable suggests that this interaction term is necessary to create an accurate equation for predicting the selling price of a house.\n\n\n\n\n\n\n\n",
    "supporting": [
      "HW4_AkhileshKumar_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}