{
  "hash": "1df7e6bf4f00aea5f931ed6ad2386103",
  "result": {
    "markdown": "---\ntitle: \"Homework 5\"\nauthor: \"Caitlin Rowley\"\ndescription: \"Homework 5\"\ndate: \"05/09/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw5\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n# load libraries\nlibrary(tidyr)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(magrittr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'magrittr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:tidyr':\n\n    extract\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(markdown)\nlibrary(ggtext)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggtext' was built under R version 4.2.2\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readxl' was built under R version 4.2.2\n```\n:::\n\n```{.r .cell-code}\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'alr4' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'car' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'carData' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'car'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: effects\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'effects' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'smss' was built under R version 4.2.3\n```\n:::\n\n```{.r .cell-code}\nlibrary(stargazer)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nPlease cite as: \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n R package version 5.2.3. https://CRAN.R-project.org/package=stargazer \n```\n:::\n\n```{.r .cell-code}\nlibrary(MPV)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'MPV' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: lattice\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: KernSmooth\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nKernSmooth 2.23 loaded\nCopyright M. P. Wand 1997-2009\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: randomForest\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'randomForest' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nrandomForest 4.7-1.1\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nType rfNews() to see new features/changes/bug fixes.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'randomForest'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:ggplot2':\n\n    margin\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:dplyr':\n\n    combine\n```\n:::\n\n```{.r .cell-code}\nlibrary(AICcmodavg)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'AICcmodavg' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'AICcmodavg'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:randomForest':\n\n    importance\n```\n:::\n:::\n\n\n### Question 1\n\n(Data file: house.selling.price.2 from smss R package)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"house.selling.price.2\")\nhead(house.selling.price.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      P    S Be Ba New\n1  48.5 1.10  3  1   0\n2  55.0 1.01  3  2   0\n3  68.0 1.45  3  2   0\n4 137.0 2.40  3  3   0\n5 309.4 3.30  4  3   1\n6  17.5 0.40  1  1   0\n```\n:::\n:::\n\n\n| For the house.selling.price.2 data the tables below show a correlation matrix and a model fit using\n| four predictors of selling price.\n\n| Regression Output (Outcome: House Price):\n|                           Estimate Std. Error t value Pr(\\> \\| t\\| )\n| (Intercept) -41.795 12.104 -3.453 0.001\n| Size 64.761 5.630 11.504 0\n| Beds -2.766 3.960 -0.698 0.487\n| Baths 19.203 5.650 3.399 0.001\n| New 18.984 3.873 4.902 0.00000\n| \n| (Hint 1: You should be able to answer A, B, C just using the tables below, although you should\n| feel free to load the data in R and work with it if you so choose. They will be consistent with what\n| you see on the tables.\n| \n| Hint 2: The p-value of a variable in a simple linear regression is the same p-value one would get\n| from a Pearson's correlation (cor.test). The p-value is a function of the magnitude of the correlation\n| coefficient (the higher the coefficient, the lower the p-value) and of sample size (larger samples\n| lead to smaller p-values). For the correlations shown in the tables, they are between variables of\n| the same length.)\n\nWith these four predictors,\n\nA. For backward elimination, which variable would be deleted first? Why?\n\n-   The first variable to be deleted using backward elimination would be BEDS because it is the least statistically significant with a p-value of 0.487.\n\nB. For forward selection, which variable would be added first? Why?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg <- lm(P ~ S + Ba + Be + New, data=house.selling.price.2)\nsummary(reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = P ~ S + Ba + Be + New, data = house.selling.price.2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-36.212  -9.546   1.277   9.406  71.953 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -41.795     12.104  -3.453 0.000855 ***\nS             64.761      5.630  11.504  < 2e-16 ***\nBa            19.203      5.650   3.399 0.001019 ** \nBe            -2.766      3.960  -0.698 0.486763    \nNew           18.984      3.873   4.902  4.3e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.36 on 88 degrees of freedom\nMultiple R-squared:  0.8689,\tAdjusted R-squared:  0.8629 \nF-statistic: 145.8 on 4 and 88 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n-   The first variable to be added using forward selection would be SIZE because it has the highest level of statistical significance with a p-value of 2e-16.\n\nC. Why do you think that BEDS has such a large P-value in the multiple regression model, even though it has a substantial correlation with PRICE?\n\n-   Correlation does not equal causation. So, it is possible that BEDS is highly correlated with PRICE, but that does not mean that there is a statistically significant relationship between the two variables. It is more likely that BEDS has a more statistically significant relationship with SIZE, which we know has a statistically significant relationship with PRICE.\n\nD. Using software with these four predictors, find the model that would be selected using each criterion:\n\n-   reg_1 = SIZE, BEDS, BATHS, NEW (all four predictors)\n\n-   reg_2 = SIZE, BATHS, NEW (backwards elimination - remove BEDS)\n\n-   reg_3 = SIZE (forward selection - add SIZE first)\n\n1\\. R2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_1 <- lm(P ~ S + Ba + Be + New, data=house.selling.price.2)\n\nreg_2 <- lm(P ~ S + Ba + New, data=house.selling.price.2)\n            \nreg_3 <- lm(P ~ S, data=house.selling.price.2)\n\nstargazer(reg_1, reg_2, reg_3, type='text')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n===========================================================================================\n                                              Dependent variable:                          \n                    -----------------------------------------------------------------------\n                                                       P                                   \n                              (1)                     (2)                     (3)          \n-------------------------------------------------------------------------------------------\nS                          64.761***               62.263***               75.607***       \n                            (5.630)                 (4.335)                 (3.865)        \n                                                                                           \nBa                         19.203***               20.072***                               \n                            (5.650)                 (5.495)                                \n                                                                                           \nBe                          -2.766                                                         \n                            (3.960)                                                        \n                                                                                           \nNew                        18.984***               18.371***                               \n                            (3.873)                 (3.761)                                \n                                                                                           \nConstant                  -41.795***              -47.992***              -25.194***       \n                           (12.104)                 (8.209)                 (6.688)        \n                                                                                           \n-------------------------------------------------------------------------------------------\nObservations                  93                      93                      93           \nR2                           0.869                   0.868                   0.808         \nAdjusted R2                  0.863                   0.864                   0.806         \nResidual Std. Error    16.360 (df = 88)        16.313 (df = 89)        19.473 (df = 91)    \nF Statistic         145.763*** (df = 4; 88) 195.313*** (df = 3; 89) 382.628*** (df = 1; 91)\n===========================================================================================\nNote:                                                           *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n\n-   Based on the stargazer table above, the highest R-squared value across the three models is for reg_1, which includes all four predictors (R-squared = 0.869). This indicates a good level of fit for the model, but we should be wary of its accuracy, as R-squared does not decrease based on poor model fit.\n\n2\\. Adjusted R2\n\n-   Based on the stargazer table above, the highest adjusted R-squared value across the three models is for reg_2, which excludes BEDS as a predictor. This indicates a good level of fit for the model, and it is a more reliable measure than R-squared due to it being adjusted for the number of predictors.\n\n3\\. PRESS\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPRESS(reg_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 28390.22\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nPRESS(reg_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 27860.05\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nPRESS(reg_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 38203.29\n```\n:::\n:::\n\n\nWe can see in the above PRESS tests that reg_2 has the lowest value, which indicates that it is the best fit model.\n\n4\\. AIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels <- list(reg_1, reg_2, reg_3)\nmod.names <- c('reg_1', 'reg_2', 'reg_3')\n\naictab(cand.set = models, modnames = mod.names)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nModel selection based on AICc:\n\n      K   AICc Delta_AICc AICcWt Cum.Wt      LL\nreg_2 5 789.83       0.00   0.71   0.71 -389.57\nreg_1 6 791.60       1.77   0.29   1.00 -389.31\nreg_3 3 820.41      30.59   0.00   1.00 -407.07\n```\n:::\n:::\n\n\nWe can see based on the above AIC model that reg_2 has the lowest AIC value. Therefore, because minimizing the AICc value equates to minimizing the number of unnecessary model parameters, reg_2 is the best fit.\n\n5\\. BIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBIC(reg_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 805.8181\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nBIC(reg_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 801.7996\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nBIC(reg_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 827.7417\n```\n:::\n:::\n\n\nWe can see in the above BIC models, which penalize the unnecessary addition of variables to the model, that reg_2 has the lowest value. Thus, it is the best fit model.\n\nE. Explain which model you prefer and why.\n\nBecause we saw that reg_2, or the regression model that excluded BEDS as a predictor, was the best fit model based on the above comparison methods (adjusted R-squared, PRESS, AIC, and BIC) I would prefer this model. The comparison models for which reg_2 was deemed the best fit all account for additional predictor variables, so it is the most comprehensively significant model.\n\n### Question 2\n\n(Data file: trees from base R)\n\n| From the documentation:\n| \"This data set provides measurements of the diameter, height and volume of timber in 31 felled\n| black cherry trees. Note that the diameter (in inches) is erroneously labeled Girth in the data. It is\n| measured at 4 ft 6 in above the ground.\"\n| \n| Tree volume estimation is a big deal, especially in the lumber industry. Use the trees data to build\n| a basic model of tree volume prediction. In particular,\n\nA. Fit a multiple regression model with the Volume as the outcome and Girth and Height as the explanatory variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(trees)\n\ntree <- lm(Volume ~ Girth + Height, data=trees)\nsummary(tree)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Volume ~ Girth + Height, data = trees)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.4065 -2.6493 -0.2876  2.2003  8.4847 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -57.9877     8.6382  -6.713 2.75e-07 ***\nGirth         4.7082     0.2643  17.816  < 2e-16 ***\nHeight        0.3393     0.1302   2.607   0.0145 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.882 on 28 degrees of freedom\nMultiple R-squared:  0.948,\tAdjusted R-squared:  0.9442 \nF-statistic:   255 on 2 and 28 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n-   We can see based on this regression model that both height (p-value=0.0145) and girth (p-value\\<2e-16) are statistically significant predictor variables. The adjusted R-squared value is also very close to 1 (0.9442), so this is a well-fitted model.\n\nB. Run regression diagnostic plots on the model. Based on the plots, do you think any of the regression assumptions is violated?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,3))\nplot(tree, which=1:6)\n```\n\n::: {.cell-output-display}\n![](Rowley_Homework_5_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n-   **Residuals vs. Fitted**: In applying the Residuals vs. Fitted plot, we can observe a violation due to the curvature of the red line. We also see that the distribution of data points does not \"bounce randomly\" about the 0 line. This plot is therefore a **bad fit** for this regression model.\n\n-   **Normal Q-Q**: In applying the Normal Q-Q plot, we observe that the data points do generally fall along the 0 line and do not curve off into extremities, which is indicative of a **good fit** for this regression model.\n\n-   **Scale-Location**: In applying the Scale-Location plot, we observe heteroscedasticity across the data points as well as a non-horizontal red line. Thus, we observe a violation of this plot due to the increase and decrease in the trend line. This plot is therefore a **bad fit** for this regression model.\n\n-   **Cook's Distance**: In applying the Cook's Distance plot, we observe a violation due to several data points yielding a Cook's distance value greater than 1. This plot is therefore a **bad fit** for this regression model.\n\n-   **Residuals vs. Leverage**: In applying the Residuals vs. Leverage plot, we can see that there are no data points outside of the dashed lines marked with '0.5.' This plot is therefore a **good fit** for this regression model.\n\n-   **Cook's Distance vs. Leverage**: In applying the Cook's Distance vs. Leverage plot, we do not really observe any influential data points. This plot does not contribute any value to this regression model.\n\n### Question 3\n\n(Data file: florida in alr R package)\n\n| In the 2000 election for U.S. president, the counting of votes in Florida was controversial. In Palm\n| Beach County in south Florida, for example, voters used a so-called butterfly ballot. Some believe\n| that the layout of the ballot caused some voters to cast votes for Buchanan when their intended\n| choice was Gore.\n| \n| The data has variables for the number of votes for each candidate---Gore, Bush, and Buchanan.\n\nA. Run a simple linear regression model where the Buchanan vote is the outcome and the Bush vote is the explanatory variable. Produce the regression diagnostic plots. Is Palm Beach County an outlier based on the diagnostic plots? Why or why not?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(florida)\n\nvote <- lm(Buchanan ~ Bush, data=florida)\nsummary(vote)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Buchanan ~ Bush, data = florida)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-907.50  -46.10  -29.19   12.26 2610.19 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 4.529e+01  5.448e+01   0.831    0.409    \nBush        4.917e-03  7.644e-04   6.432 1.73e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 353.9 on 65 degrees of freedom\nMultiple R-squared:  0.3889,\tAdjusted R-squared:  0.3795 \nF-statistic: 41.37 on 1 and 65 DF,  p-value: 1.727e-08\n```\n:::\n\n```{.r .cell-code}\npar(mfrow=c(2,3))\nplot(vote, which=1:6)\n```\n\n::: {.cell-output-display}\n![](Rowley_Homework_5_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n-   Based on the above diagnostic plots, Palm Beach appears to be an outlier in each example. Palm Beach violates the regression assumptions in all plots except for the Cook's Distance vs Leverage plot, which we know is not particularly informative.\n\nB. Take the log of both variables (Bush vote and Buchanan Vote) and repeat the analysis in (A.) Does your findings change?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_florida <- florida %>%\n  transform(log_Bush=log(Bush)) %>%\n  transform(log_Buchanan=log(Buchanan))\n\nlog_vote <- lm(log_Buchanan ~ log_Bush, data=log_florida)\nsummary(log_vote)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_Buchanan ~ log_Bush, data = log_florida)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.96075 -0.25949  0.01282  0.23826  1.66564 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2.57712    0.38919  -6.622 8.04e-09 ***\nlog_Bush     0.75772    0.03936  19.251  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4673 on 65 degrees of freedom\nMultiple R-squared:  0.8508,\tAdjusted R-squared:  0.8485 \nF-statistic: 370.6 on 1 and 65 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\npar(mfrow=c(2,3))\nplot(log_vote, which=1:6)\n```\n\n::: {.cell-output-display}\n![](Rowley_Homework_5_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nAfter logging both variables, we can see that Palm Beach is still an outlier in each of the diagnostic plots, and it results in the same regression assumption violations (though to a slightly lesser degree).\n",
    "supporting": [
      "Rowley_Homework_5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}