{
  "hash": "bdcb66c060de54ef65cfda3093ca504b",
  "result": {
    "markdown": "---\ntitle: \"Final Project Check in 2\"\nauthor: \"Emma Narkewicz\"\ndesription: \"Emma Narkewicz Final Check-in 2\"\ndate: \"04/20/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - emma_narkewicz\n  - finalpart2\n  - Burnout\n  - Medical_students\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(sjPlot)\nlibrary(sjmisc)\nlibrary(stargazer)\nlibrary(broom)\n\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Research Question\n\nFor my final project I want to expand on research on the mental health, empathy, and burnout of medical school students using a data set of 886 medical students in Switzerland. The COVID-19 pandemic heightened the mental health challenges of health care workers around the world (Teisman et al., 2021). Numerous studies show that health care workers are prone to compassion fatigue due to working long hours in stressful work environments with continuous exposure to trauma (Jennings, 2009; Rodriguez & Carlotta, 2017; Peters, 2018; Yayha et al., 2021; Carrard et al., 2022; Shin et al., 2022).\n\nThe Association of American Medical Colleges (AAMC) found that 30% of surveyed medical students and residents met the criteria for depression and 10% reported having suicidal thoughts (Pasturel, 2020). Previous studies conducted on samples of health care workers in Switzerland, Iraq, and South Korea examined the impact of gender on burnout, finding that female medical students had higher rates of empathy and burnout than male coworkers (Carrard et al., 2022; Yahya et al., 2021; Shin et al., 2022). A 2009 multi-site study of medical students in the U.S. found statistically significant differences in depression by gender but not by ethnicity (Goebert et al., 2009). In contrast, the same study found statistically significant differences in suicidal ideation by ethnicity, but not by gender, with Black students reporting the highest rates of suicidal ideation & Caucasian students reporting the lowest rates of suicidal ideation (Goebert et al., 2009).\n\n*Research Question: Why are some medical students more likely to experience burnout than others?*\n\n## Hypothesis Testing\n\nI want to explore further how ethnic identity might serve as a protective or risk factor for the burnout of medical students, specifically for international medical students. A 2022 study of medical school students in Croatia found that international medical students experience higher rates of burnout mediated by social and familial loneliness (Gradiski et al., 2022). For my final project I will test whether or not a student's first language being a national language of Switzerland -- where the sample was taken -- impacts their burnout. The commonly spoken national languages of Switzerland are French, German, and Italian (Kużelewska, 2016).\n\n*Hypothesis: Medical students whose native language is a national language of the country where they are studying will experience lower rates of burnout than medical students with other native languages.*\n\nThe reasoning behind my hypothesis is if a medical student's native language is one of the national language of Switzerland, they will have benefit from potential protective factors of social, cultural, and familial connections. In contrast, I expect medical students whose native language is not German, French, or Italian to be at higher risk for burnout mediated through increased stress from coping with different culture, language, and physical separation from their family.\n\n## Descriptive Statistics\n\nThe data set I will be analyzing contains demographic information on 886 medical students in Switzerland. Students answered demographic information about their age, gender, their year in school and well as the results of self-reported empathy, depression, anxiety, and burnout. The data set was downloaded from Kaggle at https://www.kaggle.com/datasets/thedevastator/medical-student-mental-health?select=Codebook+Carrard+et+al.+2022+MedTeach.csv but originally sourced for a 2022 publication in the Medical Teacher Journal by Carrard et al.\n\nImportant variables I want to explore in my data set as potential risk and protective factors:\n\n-   Native Language\n-   Age\n-   Gender\n-   Having a romantic partner\n-   Seeing a psychotherapist\n-   Hours spent studying\n-   Having a job\n-   Jefferson Scale Empathy (JSPE) total empathy score\n-   Questionnaire of Cognitive and Affective Empathy (QCAE) Cognitive empathy score\n-   Questionnaire of Cognitive and Affective Empathy QCAE Affective empathy score\n-   Center for Epidemiologic Studies Depression Scale (CES-D) total score\n-   State & Trait Anxiety (STAI) score\n-   Maslach Burnout Inventory (MBI) Emotional Exhaustion\n-   Maslach Burnout Inventory (MBI) Cynicism\n-   Maslach Burnout Inventory (MBI) Academic Efficacy\n\nEach of the various empathy, mental health, and burnout scales are scored differently, so care needs to be taken in interpreting these findings. For example, a higher score on the emotional exhaustion and cynicism scales of the MBI indicate higher burn out, while a higher score on the MBI personal achievement indicates lower levels of burnout (Maslach et al., 1996).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Readin Final data set\n\nFinalDataSet <- read_csv(\"_data/med_student_burnout.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 886 Columns: 20\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (20): id, age, year, sex, glang, part, job, stud_h, health, psyt, jspe, ...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nFinalDataSet\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 886 × 20\n      id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n 1     2    18     1     1   120     1     0     56      3     0    88       62\n 2     4    26     4     1     1     1     0     20      4     0   109       55\n 3     9    21     3     2     1     0     0     36      3     0   106       64\n 4    10    21     2     2     1     0     1     51      5     0   101       52\n 5    13    21     3     1     1     1     0     22      4     0   102       58\n 6    14    26     5     2     1     1     1     10      2     0   102       48\n 7    17    23     5     2     1     1     0     15      3     0   117       58\n 8    21    23     4     1     1     1     1      8      4     0   118       65\n 9    23    23     4     2     1     1     1     20      2     0   118       69\n10    24    22     2     2     1     1     0     20      5     0   108       56\n# … with 876 more rows, and 8 more variables: qcae_aff <dbl>, amsp <dbl>,\n#   erec_mean <dbl>, cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>,\n#   mbi_ea <dbl>\n```\n:::\n:::\n\n\nPrior to examining the descriptive statistics from the med school data set I recoded qualitative variables stored as numeric values, using the Carrard et al., 2022 code book, replacing 0, 1 with clear demographic information about age, gender, having a partner etc. The explanatory variable NatLang which collapses down into if medical students native language is German, French, or Italian (NatSpeaker) or not (NotNatSpeaker).\n\nFrom the Carrard et al., 2022 code book:\n\n-   Gender\n\n    -   Male = 1\n    -   Female = 2\n    -   Non-binary = 3\n\n-   Partner\n\n    -   Single = 0\n    -   Partnered = 1\n\n-   Job\n\n    -   No = 0\n    -   Yes = 1\n\n-   Therapist in Past 12 months\n\n    -   No = 0\n    -   Yes = 1\n\n-   Health Satisfaction\n\n    -   very dissatisfied = 1\n    -   dissatisfied = 2\n    -   neutral = 3\n    -   satisfied = 4\n    -   very satisfied = 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Coding Nat Lang\n\n(table(select(FinalDataSet, glang)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nglang\n  1  15  20  37  54  60  63  90  92  95  98 102 104 106 108 114 118 120 121 \n717  31  22   3   1   3   5  45   1   1   1  27   4   6   1   1   2   2  13 \n```\n:::\n\n```{.r .cell-code}\n#Recoding categorical variables based on code book\n\nFinalRecoded <- FinalDataSet %>%\n  mutate(NatLang = case_when(\n    glang == 1 | glang == 15 | glang == 90 ~ 1,\n    glang > 1 & glang < 15 | glang > 15  & glang < 90 | glang > 90 ~ 0)\n  ) \n\nFinalRecoded\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 886 × 21\n      id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n 1     2    18     1     1   120     1     0     56      3     0    88       62\n 2     4    26     4     1     1     1     0     20      4     0   109       55\n 3     9    21     3     2     1     0     0     36      3     0   106       64\n 4    10    21     2     2     1     0     1     51      5     0   101       52\n 5    13    21     3     1     1     1     0     22      4     0   102       58\n 6    14    26     5     2     1     1     1     10      2     0   102       48\n 7    17    23     5     2     1     1     0     15      3     0   117       58\n 8    21    23     4     1     1     1     1      8      4     0   118       65\n 9    23    23     4     2     1     1     1     20      2     0   118       69\n10    24    22     2     2     1     1     0     20      5     0   108       56\n# … with 876 more rows, and 9 more variables: qcae_aff <dbl>, amsp <dbl>,\n#   erec_mean <dbl>, cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>,\n#   mbi_ea <dbl>, NatLang <dbl>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Descriptive statistics for quantitative variables\n\nsummary(FinalRecoded)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       id              age             year            sex       \n Min.   :   2.0   Min.   :17.00   Min.   :1.000   Min.   :1.000  \n 1st Qu.: 447.5   1st Qu.:20.00   1st Qu.:1.000   1st Qu.:1.000  \n Median : 876.0   Median :22.00   Median :3.000   Median :2.000  \n Mean   : 889.7   Mean   :22.38   Mean   :3.103   Mean   :1.695  \n 3rd Qu.:1341.8   3rd Qu.:24.00   3rd Qu.:5.000   3rd Qu.:2.000  \n Max.   :1790.0   Max.   :49.00   Max.   :6.000   Max.   :3.000  \n     glang             part             job             stud_h     \n Min.   :  1.00   Min.   :0.0000   Min.   :0.0000   Min.   : 0.00  \n 1st Qu.:  1.00   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:12.00  \n Median :  1.00   Median :1.0000   Median :0.0000   Median :25.00  \n Mean   : 14.33   Mean   :0.5632   Mean   :0.3488   Mean   :25.29  \n 3rd Qu.:  1.00   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:36.00  \n Max.   :121.00   Max.   :1.0000   Max.   :1.0000   Max.   :70.00  \n     health           psyt             jspe          qcae_cog    \n Min.   :1.000   Min.   :0.0000   Min.   : 67.0   Min.   :37.00  \n 1st Qu.:3.000   1st Qu.:0.0000   1st Qu.:101.0   1st Qu.:54.00  \n Median :4.000   Median :0.0000   Median :107.0   Median :58.00  \n Mean   :3.778   Mean   :0.2246   Mean   :106.4   Mean   :58.53  \n 3rd Qu.:5.000   3rd Qu.:0.0000   3rd Qu.:113.0   3rd Qu.:63.00  \n Max.   :5.000   Max.   :1.0000   Max.   :125.0   Max.   :76.00  \n    qcae_aff          amsp         erec_mean           cesd      \n Min.   :18.00   Min.   : 6.00   Min.   :0.3571   Min.   : 0.00  \n 1st Qu.:31.00   1st Qu.:20.00   1st Qu.:0.6667   1st Qu.: 9.00  \n Median :35.00   Median :23.00   Median :0.7262   Median :16.00  \n Mean   :34.78   Mean   :23.15   Mean   :0.7201   Mean   :18.05  \n 3rd Qu.:39.00   3rd Qu.:26.75   3rd Qu.:0.7857   3rd Qu.:25.00  \n Max.   :48.00   Max.   :35.00   Max.   :0.9524   Max.   :56.00  \n     stai_t         mbi_ex          mbi_cy          mbi_ea         NatLang     \n Min.   :20.0   Min.   : 5.00   Min.   : 4.00   Min.   :10.00   Min.   :0.000  \n 1st Qu.:34.0   1st Qu.:13.00   1st Qu.: 6.00   1st Qu.:21.00   1st Qu.:1.000  \n Median :43.0   Median :17.00   Median : 9.00   Median :24.00   Median :1.000  \n Mean   :42.9   Mean   :16.88   Mean   :10.08   Mean   :24.21   Mean   :0.895  \n 3rd Qu.:51.0   3rd Qu.:20.00   3rd Qu.:13.00   3rd Qu.:28.00   3rd Qu.:1.000  \n Max.   :77.0   Max.   :30.00   Max.   :24.00   Max.   :36.00   Max.   :1.000  \n```\n:::\n:::\n\n\nNote that id is not a true numeric variable and therefor the descriptive statistics for it should be disregarded.\n\nMedical students in the sample studied for an average of 25 hours a week, with a maximum of 70 hours.\n\nScores on the Jefferson Scale of Physician Empathy (JSPE) range from 20-140 with a higher score indicating higher empathy. The mean JSPE score in the sample was was 106.2 and the median JSPE score was 107.0 indicating relatively high empathy. There was a broad range from as low to 67-125, with the IQR indicating most medical students scored in the low 100s range.\n\nThere were are scores for all 3 components of MBI burnout: emotional exhaustion, cynicism, and personal achievement.\n\n-   On the mbi-ex, medical school students' scores ranged from 5-30, with a median score of 17 and a mean score of 16.88. According to the MBI score guide, half of medical students in the sample exhibit low-level burnout (scoring 17 or less), and the other half exhibiting moderate burnout in terms of emotional exhaustion.\n\n-   On the mbi-cyn, medical students' scores ranged from 4-24, with a median of 9 and mean of 10.08. According to the scoring guide, the majority of the sample exhibit moderate burnout (6-11) with some exhibiting high level burnout (12+) in the dimension of cynicism.\n\n-   On the mbi-ea, medical students scores ranged from 10-36, with a median score of 24 and a mean score of 24.01. A score of 33 or less indicates high level of burnout and a score between 24-39 indicates moderate level burnout, with medical students falling in the high and moderate burnout range for personal achievement.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Creating character variables to generate props\n\nFinalProp <- FinalRecoded %>%\nmutate(nat = case_when (\n  NatLang == 0 ~ \"Non Native\",\n  NatLang == 1 ~  \"Native\")\n        )%>%\nmutate(gender = case_when(\n         sex == 1  ~ \"Male\",\n         sex == 2 ~ \"Female\", \n         sex == 3 ~ \"Non-Binary\")\n        ) %>%\n  relocate(`gender`, .before = `age`)%>%\n  select(!contains(\"sex\")) %>%\nmutate(partner = case_when(\n         part == 1 ~ \"partnered\",\n         part == 0  ~ \"single\")\n      )%>%\n  relocate(`partner`, .before = `age`)%>%\n  select(!\"part\") %>%\nmutate(paid_job = case_when(\n         job == 0  ~ \"no_job\",\n         job == 1 ~ \"yes_job\")\n        ) %>%\n  relocate(`paid_job`, .before = `age`)%>%\n  select(!\"job\") %>%\nmutate(health_sat = case_when(\n         health == 1  ~ \"very_dis\",\n         health == 2 ~ \"dis\",\n         health == 3 ~ \"neutral\",\n         health == 4 ~ \"sat\",\n         health  == 5 ~ \"very sat\")\n) %>%\n  relocate(`health_sat`, .before = `age`)%>%\n  select(!\"health\") %>%\nmutate(MHcare = case_when(\n         psyt == 0  ~ \"no_ther\",\n         psyt == 1 ~ \"yes_ther\")\n        ) %>%\nrelocate(`MHcare`, .before = `age`)%>%\n  select(!\"psyt\") \n\nFinalProp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 886 × 22\n      id gender partner   paid_job healt…¹ MHcare   age  year glang stud_h  jspe\n   <dbl> <chr>  <chr>     <chr>    <chr>   <chr>  <dbl> <dbl> <dbl>  <dbl> <dbl>\n 1     2 Male   partnered no_job   neutral no_th…    18     1   120     56    88\n 2     4 Male   partnered no_job   sat     no_th…    26     4     1     20   109\n 3     9 Female single    no_job   neutral no_th…    21     3     1     36   106\n 4    10 Female single    yes_job  very s… no_th…    21     2     1     51   101\n 5    13 Male   partnered no_job   sat     no_th…    21     3     1     22   102\n 6    14 Female partnered yes_job  dis     no_th…    26     5     1     10   102\n 7    17 Female partnered no_job   neutral no_th…    23     5     1     15   117\n 8    21 Male   partnered yes_job  sat     no_th…    23     4     1      8   118\n 9    23 Female partnered yes_job  dis     no_th…    23     4     1     20   118\n10    24 Female partnered no_job   very s… no_th…    22     2     1     20   108\n# … with 876 more rows, 11 more variables: qcae_cog <dbl>, qcae_aff <dbl>,\n#   amsp <dbl>, erec_mean <dbl>, cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>,\n#   mbi_cy <dbl>, mbi_ea <dbl>, NatLang <dbl>, nat <chr>, and abbreviated\n#   variable name ¹​health_sat\n```\n:::\n\n```{.r .cell-code}\n#Frequency of categorical & ordinal variables\n prop.table(table(select(FinalProp, nat)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnat\n    Native Non Native \n 0.8950339  0.1049661 \n```\n:::\n\n```{.r .cell-code}\n prop.table(table(select(FinalProp, gender)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngender\n     Female        Male  Non-Binary \n0.683972912 0.310383747 0.005643341 \n```\n:::\n\n```{.r .cell-code}\n prop.table(table(select(FinalProp, partner)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npartner\npartnered    single \n0.5632054 0.4367946 \n```\n:::\n\n```{.r .cell-code}\n prop.table(table(select(FinalProp, paid_job)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npaid_job\n   no_job   yes_job \n0.6512415 0.3487585 \n```\n:::\n\n```{.r .cell-code}\n prop.table(table(select(FinalProp, health_sat)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nhealth_sat\n       dis    neutral        sat   very sat   very_dis \n0.09819413 0.15349887 0.45372460 0.25282167 0.04176072 \n```\n:::\n\n```{.r .cell-code}\n prop.table(table(select(FinalProp, MHcare)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMHcare\n no_ther yes_ther \n0.775395 0.224605 \n```\n:::\n:::\n\n\nFrom the proportion tables above it can be seen that majority (90%) of the sample speaks one of the national languages of Switzerland, while only 10% are non native speakers. The sample is also mostly female (68%), with less than 1% identifying as non-binary. Over half (56%) of the medical students reported having partners, but only about a third of medical students had a paid job (34.9%). The most common (45%) report from medical students was that they were satisfied with their health and less than one quarter (22.5%) of medical student reported seeing a therapist in the last 12 months.\n\nLooking at the gender prop.table, less than 1% of medical students were non-binary. Looking at counts that is only 5 students out of nearly 1000. From an equity standpoint it is great to include diverse gender identities, but for the purposes of analysis & linear regression, there are non non-binary students to meaningfully include in an analysis of gender. Therefor I removed the 5 students who identified as non-binary before conducting analysis. Additionally I recoded the gender dummy variables from 1 & 2 to 0 & 1 for male and female respectiviely.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Counts genders\n (table(select(FinalProp, gender)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngender\n    Female       Male Non-Binary \n       606        275          5 \n```\n:::\n\n```{.r .cell-code}\n#remove non-binary dummy gender & recode \n\nFinalRecoded2 <- FinalRecoded %>%\n  filter(!str_detect(sex, \"3\")) %>%\n  mutate(gender = case_when(\n         sex == 1  ~ 0,\n         sex == 2 ~  1)\n        ) \n  \n#remove non-binary categorical\nFinalProp2 <- FinalProp %>%\n  filter(!str_detect(gender, \"Non-Binary\"))\n```\n:::\n\n\n## Analysis\n\nI created several box plots comparing the MBI burnout scores of medical students speaking native language vs. students speaking non-native language. Additionally, I compared the anxiety & depression scored of medical students native and non-native language speaking students\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Emotional Exhaustion Burnout Score\nggplot(data = FinalProp2, aes(x= nat, y = mbi_ex, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot - mbi_ex Emotional Burnout\", x = \"Native Language Spoken\", y = \"mbi_ex\") \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nNative language speaking and non-native language speaking medical students seemed to have nearly identical median scores for Emotional Exhaustion (mbi_ex). The IQR however for non-native languge speaking students does appear to start & end higher (higher Q1 & Q3 MBI-ex scores) than native students, suggesting the potential for higher emotional exhuastion burnout for non-native language speaking students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Cynicism Score\nggplot(data = FinalProp, aes(x = nat, y = mbi_cy, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot - mbi_cy Cynicism Burnout\", x = \"Native Language Spoken\", y = \"mbi_cy\") \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nNon-native speaking medical students appeared to score slightly higher on average than non-native speaking medical students on Cynicism as measured by the mbi-cy, with a higher median score. The IQR of mbi-cy scores for non-native language speaking medical students is higher for non-native students with a higher Q1 & Q3. There appears to be one high outlier for native language speakers cynicism scores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Academic Efficacy Score\nggplot(data = FinalProp2, aes(x= nat, y = mbi_ea, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot - mbi-ea Academic Efficacy Burnout\", x = \"Native Language Spoken\", y = \"mbi_ea\") \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nLastly, native language speaking and non-native language speaking medical students seemed to have nearly identical median scores for Academic Efficacy burnout (mbi_ea), with one low-outlier of scores for native language speaking medical students. However non-native medical school students have a lower MBI_ea Q1 & Q3 which corresponds with higher burnout on this subscale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Depression Score\nggplot(data = FinalProp, aes(x= nat, y = cesd, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot - cesd measure of Depression\", x = \"Native Language Spoken\", y = \"CESD Score\") \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nNon-native national language speakers have a higher median on CESD score than native national language speakers, suggesting higher depression among native students. The Q1 & Q3 of the non-native language speaking medical students CESD is higher than scores for native language speaking students. There are several high outliers for native and non-native language speaking students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Anxiety Score\nggplot(data = FinalProp2, aes(x= nat, y = stai_t, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot - stai_t measure of Anxiety\", x = \"Native Language Spoken\", y = \"stai_t Score\") \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nNon-native national languages speaking medical students have a higher median, Q1, & Q3 stai_t anxiety score than native language speaking medical students.\n\nHigher depression and anxiety score for non-native students are not the hypothesis being tested, but it is plausible that anxiety & depression mediate the impact of speaking a native language on burnout. Anxiety and depression, as measured by stai_t and cesd scores, will be treated as interaction terms in linear regression model, with graphic models used to evaluate this.\n\n### Gender\n\nPrevious studies on the impact of gender and burnout found that being female predicted higher burnout. In the linear regression model, I will want to control for the impact of gender on burnout scores by including it as an explanatory variable.\n\nOn the plots below, I facet wrapped the box & whiskers plot of emotional burnout comparison by native language to visualize difference in the 3 MBI burnout scales when controlled by gender.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Emotional Exhaustion Burnout Score\nggplot(data = FinalProp2, aes(x= nat, y = mbi_ex, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot Emotional Burnout Controlled by Gender\", x = \"Native Language Spoken\", y = \"MBI_ex Score\") + facet_wrap(vars(`gender`))\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Emotional Cynicism Burnout Score\nggplot(data = FinalProp2, aes(x= nat, y = mbi_cy, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot Cynicism Burnout Controlled by Gender\", x = \"Native Language Spoken\", y = \"MBI_cy Score\") + facet_wrap(vars(`gender`))\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Academic Efficacy Burnout Score\nggplot(data = FinalProp2, aes(x= nat, y = mbi_ex, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot Academic Efficacy Burnout Controlled by Gender\", x = \"Native Language Spoken\", y = \"MBI_ea Score\") + facet_wrap(vars(`gender`))\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nControlling for gender there still seems to be a difference between the MBI scores of native and non-native language speaking MBI burnout scores. Looking at the academic efficacy score, for non-native male med students it appears to be higher than native male med students, suggesting lower academic efficacy burnout counter to my hypothesis.\n\n### Applying feedback from Final Check in 1\n\nIn response to feedback on Check In 1, I kept categorical data coded as dummy variables 0,1 format for the linear regression. I did keep a \"prop\"data set record to use to calculate proportions & frequencies of categorical variables.\n\nIn deciding how to best work with the 3 MBI burnout variables, I reviewed literature on burnout and how prior researchers chose to work with the variables. A 2016 systematic review by Doulougeri et al. of 50 articles on burnout in medical staff as measured by the MBI found that the majority of studies analyzed burn out as sub scales of emotional exhaustion, cynicism (also known as depersonalization), & academic efficacy (also known as professional accomplishment), as opposed to trying to create one total scale.\n\nThis approach also aligns with the finding that burnout is often conceptualized as a multidimensional construct. Maslach designed the MBI to distinguish between the three sub-scales. Studies on burnout almost universally considered the MBI emotional exhaustion (EE) sub-scale in determining burnout, sometimes alone, sometimes with cynicism, and sometimes with both cynicism & academic efficacy. According to the literature, burn out is complex and multidimensional concepts, and impacts both an individual's well being and their ability to perform their job as a medical professional.\n\nBased on all of these factors, I will run three separate models with each of the 3 MBI sub-scales as dependent variables.\n\n## Hypothesis Testing\n\nEach MBI burnout sub-scale score will be a response variable for each of the 3 models. These scales are numeric and continuous.\n\n-   emotional exhaustion\n-   cynicism\n-   academic efficacy\n\nAs mentioned earlier, a higher score on emotional exhaustion & cynicism are considered indicative of burnout, whereas lower scores of academic efficacy are indicative of burnout\n\nThe explanatory variable I am testing in my hypothesis is whether or not a student speaks a native language of the country they are attending medical school in, coded as a binary dummy variable (0 = non-native, 1 = native)\n\nAs previous studies have found a relationship between gender and burnout, I will need to have gender as a control variable in the model. I will also examine if I will need to also control for the influence of having a partner, having a job, or seeing a therapist in past 12 months (all also binary dummy variables) on medical student burnout, by adding them to the regression model and seeing their impact.\n\n### T test\n\nTo test my hypothesis that *Medical students whose native language is a national language of the country where they are studying will experience lower rates of burnout than medical students with other native languages*, I will run a Welch's Independent T-Test on the data to see if there is a statistically significant difference between the burnout of native and non-native medical students. Specifically, I will run a one-sided test, to see if the mean burnout of non-native students is higher than of native students.\n\nThe null hypothesis is that there is no difference in the mean burnout of native medical students than non-native medical students\n\nThe alternative hypothesis is that the mean burnout of native students is less than that non-native medical students. For the emotional exhaustion & cyncicism burnout scores, higher score corresponds to higher burnout, for the academic efficacy, a lower score corresponds with higher burnout.\n\n### Emotional Exhaustion\n\nH0: μ = μ0\n\nHA: μ \\< μ0\n\nThe first T-Test compared the emotional exhaustion scores of native and non-native language speaking medical students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(FinalRecoded)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 21\n     id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n1     2    18     1     1   120     1     0     56      3     0    88       62\n2     4    26     4     1     1     1     0     20      4     0   109       55\n3     9    21     3     2     1     0     0     36      3     0   106       64\n4    10    21     2     2     1     0     1     51      5     0   101       52\n5    13    21     3     1     1     1     0     22      4     0   102       58\n6    14    26     5     2     1     1     1     10      2     0   102       48\n# … with 9 more variables: qcae_aff <dbl>, amsp <dbl>, erec_mean <dbl>,\n#   cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>, mbi_ea <dbl>,\n#   NatLang <dbl>\n```\n:::\n\n```{.r .cell-code}\n#Ttest\nNative <- subset(FinalRecoded, FinalRecoded$NatLang == 1)\nNonNative <- subset(FinalRecoded, FinalRecoded$NatLang == 0)\n\n\n##One side t-test, MBI ex\n\nttest_ex <- t.test(Native$mbi_ex, NonNative$mbi_ex, var.equal = TRUE, alternative = \"less\")\nttest_ex\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Native$mbi_ex and NonNative$mbi_ex\nt = -1.3841, df = 884, p-value = 0.08334\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n     -Inf 0.151154\nsample estimates:\nmean of x mean of y \n 16.79445  17.59140 \n```\n:::\n:::\n\n\nWith a p-value of 0.08 the difference between the mean is statistically significant at the .1 level but not the standard 0.05 level. Therefor I fail to reject the null hypothesis that there is no difference between the native and non-native students MBI_ex scores.\n\n### Cynicism\n\nH0: μ = μ0\n\nHA: μ \\< μ0\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Cynicism\nttest_cy <- t.test(Native$mbi_cy, NonNative$mbi_cy, var.equal = TRUE, alternative = \"less\")\nttest_cy\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Native$mbi_cy and NonNative$mbi_cy\nt = -1.2331, df = 884, p-value = 0.1089\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n      -Inf 0.2080785\nsample estimates:\nmean of x mean of y \n 10.01387  10.63441 \n```\n:::\n:::\n\n\nNext the cynicism MBI burnout scores for native and non-native scores were compared in a T-Test. With a p-value of 0.1089, the difference between the means is not statistically significant at the 0.1 or the 0.05 levels. I fail to reject the null hypothesis that there is no difference between the native and non-native medical students MBI_cy scores.\n\n### Academic Efficacy\n\nH0: μ = μ0\n\nHA: μ \\> μ0\n\nLastly, I performed a T-Test on the final MBI sub-score, the academic efficacy between native and non-native language speaking medical students. As a lower MBI_ea score corresponds with higher burnout on this sub-scale the alternative hypothesis of the one-sided T-test is that\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#T-test Academic Efficacy \n\nttest_ea <- t.test(Native$mbi_ea, NonNative$mbi_ea, var.equal = TRUE, alternative = \"greater\")\nttest_ea\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Native$mbi_ea and NonNative$mbi_ea\nt = -0.29993, df = 884, p-value = 0.6179\nalternative hypothesis: true difference in means is greater than 0\n95 percent confidence interval:\n -0.9891101        Inf\nsample estimates:\nmean of x mean of y \n 24.19168  24.34409 \n```\n:::\n:::\n\n\nWith a p-value of 0.6179 the mean MBI_ea score of native medical students is not greater than the mean MBI_ea score of native people at all, let alone at the statistically significant level.\n\n### Interpretation of Hypothesis Testing & Further Tests\n\nOut of the 3 MBI burnout sub-scales, only the one-sided difference in burnout as measured on the MBI emotional exhaustion scale is statistically significant at the 0.1 level. There is not statistically significant higher burnout on any of the 3 MBI scores at the 0.05 level. I therefor fail to reject the null hypothesis that there is no difference between the mean MBI burnout scores of native and non-native language speaking medical school students.\n\nThough not my hypothesis, I ran Welch's T-tests on anxiety (stai_t) and depression (CESD) scores to see if there was a statistically significant difference between native and non-native speaking medical school students. Once again I ran a one-sided t-test, with the assumption that the mean anxiety and depression of non-native language speaking medical students will be higher than that of native language speaking medical students.\n\nH0: μ = μ0\n\nHA: μ \\< μ0\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# T-test Anxiety\nttest_stai_t <- t.test(Native$stai_t, NonNative$stai_t, var.equal = TRUE, alternative = \"less\")\nttest_stai_t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Native$stai_t and NonNative$stai_t\nt = -2.5743, df = 884, p-value = 0.005103\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n      -Inf -1.214218\nsample estimates:\nmean of x mean of y \n 42.54477  45.91398 \n```\n:::\n:::\n\n\nWith a p-value of 0.005 there is strong statistical significance to reject the null hypothesis that there is no difference in the mean anxiety of native and non-native language speaking medical students. This suggests that med students who speak the non-native language experience higher anxiety levels than native-language speakers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# T-test Depression\nttest_cesd <- t.test(Native$cesd, NonNative$cesd, var.equal = TRUE, alternative = \"less\")\nttest_cesd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Native$cesd and NonNative$cesd\nt = -2.7533, df = 884, p-value = 0.00301\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n      -Inf -1.387275\nsample estimates:\nmean of x mean of y \n 17.68852  21.13978 \n```\n:::\n:::\n\n\nWith a p-value of 0.003 there is strong statistical significance to reject the null hypothesis that there is no difference in the mean depression of native and non-native language speaking medical students. This suggests that med students who speak the non-native language experience higher depression levels than native-language speakers.\n\nThough I failed to reject my null hypothesis of burnout, returning to my research question of\" *Why are some medical students more likely to experience burnout than others?* it seems that native language status, anxiety, depression all interact on one-another to help explain burnout. This will be explored further in the linear regression models.\n\n## Linear Regressions\n\n### Emotional Exhaustion Burnout Model (MBI_ex)\n\nFirst, I created a linear regression model with only native language status as the explanatory variable and mbi_ex emotional exhaustion burnout score as the outcome variable. As seen in the summary of the model below with a p-value of 0.132 and Adjusted R-squared value of 0.001449, variance in native language speaking status alone does explain variance in emotional exhaustion MBI scores. National language is not a statistically significant explanatory variable in the linear regression model. The AIC of this first model is 5422, with the lower the AIC score the better the fit of the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear regression model with only NatLang as explanatory variable\n\nmodel_ex_1 <- lm(mbi_ex ~ NatLang, data = FinalRecoded2)\nsummary(model_ex_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ NatLang, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.7921  -3.7921   0.2079   3.2079  13.2079 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  17.6630     0.5462  32.338   <2e-16 ***\nNatLang      -0.8709     0.5772  -1.509    0.132    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.239 on 879 degrees of freedom\nMultiple R-squared:  0.002584,\tAdjusted R-squared:  0.001449 \nF-statistic: 2.277 on 1 and 879 DF,  p-value: 0.1317\n```\n:::\n\n```{.r .cell-code}\n## AIC \n\nglance(model_ex_1)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5422.286\n```\n:::\n:::\n\n\nThe second linear regression model includes gender as an explanatory variable along with native-language status for the outcome of emotional exhaustion MBI scores. In this regression model gender is statistically significant explanatory variable with a p value of 1.66 x e6, but native-language status is not. The adjusted R-squared value is higher than the first model but still low at 0.02612. The AIC value of this model is 5401 is lower than the first model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear Regression model with NatLang & gender\nmodel_ex_2 <- lm(mbi_ex ~ NatLang + gender , data = FinalRecoded2)\nsummary(model_ex_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ NatLang + gender, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-12.3723  -3.3723  -0.3723   3.6277  14.4441 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  16.3007     0.6089  26.771  < 2e-16 ***\nNatLang      -0.7449     0.5706  -1.305    0.192    \ngender        1.8164     0.3766   4.823 1.66e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.174 on 878 degrees of freedom\nMultiple R-squared:  0.02833,\tAdjusted R-squared:  0.02612 \nF-statistic:  12.8 on 2 and 878 DF,  p-value: 3.317e-06\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ex_2)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5401.246\n```\n:::\n:::\n\n\nIn the third linear regression model was a 3-way interaction of depression (CESD), anxiety (stai_t), & native language as an explanatory variable for MBI emotional exhaustion scores in addition to gender. Adding the 3 way interaction term to the model greatly increased the predictive power of the model, raising the adjusted R-squared value to 0.3885. In this model, Anxiety (stai_t) & Depression \\* Anxiety (ces\\*stai_t) are both statistically significant at the 0.05 level, and Depression (cesd) is statistically significant at the 0.001 level. The AIC of 4997 is the lowest of any model so far, suggesting the best fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear Regression model with NatLang * Anxiety * Depression & gender explanatory variables\nmodel_ex_3 <- lm(mbi_ex ~ gender + NatLang*cesd*stai_t , data = FinalRecoded2)\nsummary(model_ex_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + NatLang * cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.0395  -2.7678  -0.1503   2.5525  14.0706 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)   \n(Intercept)          6.629628   2.729549   2.429  0.01535 * \ngender              -0.060270   0.310448  -0.194  0.84611   \nNatLang              0.684336   2.881436   0.237  0.81233   \ncesd                 0.454730   0.140458   3.237  0.00125 **\nstai_t               0.146600   0.068337   2.145  0.03221 * \nNatLang:cesd        -0.125780   0.148435  -0.847  0.39702   \nNatLang:stai_t      -0.010215   0.072736  -0.140  0.88834   \ncesd:stai_t         -0.004831   0.002364  -2.044  0.04128 * \nNatLang:cesd:stai_t  0.002343   0.002559   0.916  0.36011   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.1 on 872 degrees of freedom\nMultiple R-squared:  0.3941,\tAdjusted R-squared:  0.3885 \nF-statistic: 70.89 on 8 and 872 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ex_3)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4997.202\n```\n:::\n:::\n\n\nTo determine the best model, I added the control variables of hours studied, having a partner, job status, consulting a psychotherapist in past 12 months, & health satisfaction to see the impact on the adjusted R squared value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Control variables\n\nhead(FinalRecoded2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 22\n     id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n1     2    18     1     1   120     1     0     56      3     0    88       62\n2     4    26     4     1     1     1     0     20      4     0   109       55\n3     9    21     3     2     1     0     0     36      3     0   106       64\n4    10    21     2     2     1     0     1     51      5     0   101       52\n5    13    21     3     1     1     1     0     22      4     0   102       58\n6    14    26     5     2     1     1     1     10      2     0   102       48\n# … with 10 more variables: qcae_aff <dbl>, amsp <dbl>, erec_mean <dbl>,\n#   cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>, mbi_ea <dbl>,\n#   NatLang <dbl>, gender <dbl>\n```\n:::\n\n```{.r .cell-code}\n##hours studied strengthens model\nsummary(lm(mbi_ex ~ gender + stud_h + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + NatLang * cesd * stai_t, \n    data = FinalRecoded2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-13.557  -2.759  -0.194   2.566  14.132 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)   \n(Intercept)          6.041386   2.727628   2.215  0.02703 * \ngender              -0.017473   0.309668  -0.056  0.95502   \nstud_h               0.024347   0.008830   2.757  0.00595 **\nNatLang              0.816214   2.870986   0.284  0.77625   \ncesd                 0.449439   0.139943   3.212  0.00137 **\nstai_t               0.143298   0.068090   2.105  0.03562 * \nNatLang:cesd        -0.125427   0.147877  -0.848  0.39657   \nNatLang:stai_t      -0.008967   0.072463  -0.124  0.90154   \ncesd:stai_t         -0.004716   0.002355  -2.002  0.04559 * \nNatLang:cesd:stai_t  0.002219   0.002550   0.870  0.38433   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.084 on 871 degrees of freedom\nMultiple R-squared:  0.3993,\tAdjusted R-squared:  0.3931 \nF-statistic: 64.33 on 9 and 871 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##partner\nsummary(lm(mbi_ex ~ gender + stud_h + part + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + part + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.8288  -2.7626  -0.1144   2.5427  14.2053 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          5.474759   2.732407   2.004 0.045418 *  \ngender              -0.047923   0.309213  -0.155 0.876870    \nstud_h               0.026136   0.008843   2.955 0.003207 ** \npart                 0.640704   0.281038   2.280 0.022862 *  \nNatLang              0.966911   2.864856   0.338 0.735816    \ncesd                 0.466905   0.139817   3.339 0.000875 ***\nstai_t               0.146331   0.067939   2.154 0.031526 *  \nNatLang:cesd        -0.141738   0.147695  -0.960 0.337491    \nNatLang:stai_t      -0.012644   0.072307  -0.175 0.861224    \ncesd:stai_t         -0.004956   0.002352  -2.107 0.035400 *  \nNatLang:cesd:stai_t  0.002492   0.002546   0.979 0.327957    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.075 on 870 degrees of freedom\nMultiple R-squared:  0.4029,\tAdjusted R-squared:  0.396 \nF-statistic:  58.7 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##having job\nsummary(lm(mbi_ex ~ gender + stud_h + part + job + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + part + job + NatLang * \n    cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.8833  -2.7470  -0.0854   2.5207  14.1412 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          5.576368   2.744314   2.032 0.042460 *  \ngender              -0.044168   0.309488  -0.143 0.886549    \nstud_h               0.025410   0.009013   2.819 0.004924 ** \npart                 0.643363   0.281241   2.288 0.022401 *  \njob                 -0.124332   0.295061  -0.421 0.673584    \nNatLang              0.924792   2.867954   0.322 0.747184    \ncesd                 0.464843   0.139968   3.321 0.000934 ***\nstai_t               0.145510   0.068000   2.140 0.032644 *  \nNatLang:cesd        -0.139382   0.147871  -0.943 0.346151    \nNatLang:stai_t      -0.011844   0.072366  -0.164 0.870031    \ncesd:stai_t         -0.004920   0.002355  -2.089 0.036975 *  \nNatLang:cesd:stai_t  0.002448   0.002550   0.960 0.337149    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.076 on 869 degrees of freedom\nMultiple R-squared:  0.403,\tAdjusted R-squared:  0.3954 \nF-statistic: 53.33 on 11 and 869 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## seen psychiatrist\nsummary(lm(mbi_ex ~ gender + stud_h + part + psyt + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + part + psyt + NatLang * \n    cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.8366  -2.7590  -0.1101   2.5433  14.2074 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          5.479195   2.736089   2.003 0.045534 *  \ngender              -0.049039   0.310571  -0.158 0.874572    \nstud_h               0.026166   0.008880   2.947 0.003297 ** \npart                 0.640210   0.281454   2.275 0.023170 *  \npsyt                 0.014441   0.349983   0.041 0.967096    \nNatLang              0.963298   2.867838   0.336 0.737030    \ncesd                 0.467043   0.139937   3.338 0.000881 ***\nstai_t               0.146139   0.068138   2.145 0.032250 *  \nNatLang:cesd        -0.141870   0.147815  -0.960 0.337432    \nNatLang:stai_t      -0.012506   0.072426  -0.173 0.862949    \ncesd:stai_t         -0.004957   0.002354  -2.106 0.035478 *  \nNatLang:cesd:stai_t  0.002491   0.002548   0.978 0.328421    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.077 on 869 degrees of freedom\nMultiple R-squared:  0.4029,\tAdjusted R-squared:  0.3953 \nF-statistic:  53.3 on 11 and 869 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## health sat\nsummary(lm(mbi_ex ~ gender + stud_h + part + health + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + part + health + NatLang * \n    cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.3761  -2.7426  -0.1272   2.5977  14.6000 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          7.504517   2.804689   2.676 0.007598 ** \ngender              -0.041008   0.307841  -0.133 0.894058    \nstud_h               0.025756   0.008805   2.925 0.003532 ** \npart                 0.672159   0.279982   2.401 0.016572 *  \nhealth              -0.414872   0.139647  -2.971 0.003051 ** \nNatLang              0.672755   2.853775   0.236 0.813688    \ncesd                 0.463579   0.139197   3.330 0.000904 ***\nstai_t               0.139753   0.067672   2.065 0.039205 *  \nNatLang:cesd        -0.139787   0.147037  -0.951 0.342022    \nNatLang:stai_t      -0.005416   0.072025  -0.075 0.940076    \ncesd:stai_t         -0.005056   0.002342  -2.159 0.031115 *  \nNatLang:cesd:stai_t  0.002378   0.002535   0.938 0.348603    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.056 on 869 degrees of freedom\nMultiple R-squared:  0.4089,\tAdjusted R-squared:  0.4014 \nF-statistic: 54.64 on 11 and 869 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nVariables that improved model fit were:\n\n-   Hours studied (stud_h)\n-   Having a partner (part)\n-   Health satisfaction (health)\n\nThe best-fitting linear regression model for MBI_ex as determined by adjusted R-squared includes gender, hours studied, health satisfaction, having a partner, and 3-way interaction between native language, depression, and anxiety as explanatory variables. This has an Adjusted R-Squared value of 0.402, suggesting much of the the variance in MBI emotional exhaustion scores of medical school students is explained by variance in the explanatory variables. The AIC value of 4981 is the lowest of any of the linear regression models, suggesting the best fit.\n\n-   Explanatory variables significant at the 0.05 level are:\n\n    -   Having a partner (part)\n    -   Anxiety (stai_t)\n    -   2-way interaction between anxiety & depression (cesd \\* stai_t )\n\n-   Explanatory variables significant at the 0.01 level are:\n\n    -   Hours studying (stud_h)\n    -   Health satisfaction (health)\n\n-   Explanatory variables significant at the 0.01 level are:\n\n    -   Depression (cesd)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model 4\n\nMBI_ex_bestfit <- lm(mbi_ex ~ gender + stud_h + health + part  + NatLang*cesd*stai_t, data = FinalRecoded2)\n\nsummary(MBI_ex_bestfit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + health + part + NatLang * \n    cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.3761  -2.7426  -0.1272   2.5977  14.6000 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          7.504517   2.804689   2.676 0.007598 ** \ngender              -0.041008   0.307841  -0.133 0.894058    \nstud_h               0.025756   0.008805   2.925 0.003532 ** \nhealth              -0.414872   0.139647  -2.971 0.003051 ** \npart                 0.672159   0.279982   2.401 0.016572 *  \nNatLang              0.672755   2.853775   0.236 0.813688    \ncesd                 0.463579   0.139197   3.330 0.000904 ***\nstai_t               0.139753   0.067672   2.065 0.039205 *  \nNatLang:cesd        -0.139787   0.147037  -0.951 0.342022    \nNatLang:stai_t      -0.005416   0.072025  -0.075 0.940076    \ncesd:stai_t         -0.005056   0.002342  -2.159 0.031115 *  \nNatLang:cesd:stai_t  0.002378   0.002535   0.938 0.348603    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.056 on 869 degrees of freedom\nMultiple R-squared:  0.4089,\tAdjusted R-squared:  0.4014 \nF-statistic: 54.64 on 11 and 869 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#AIC \nglance(MBI_ex_bestfit)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4981.395\n```\n:::\n:::\n\n\n### Cynicism Burnout Model (MBI_cy)\n\nFor the cynicism burnout sub scale, I once again started by running a linear regression model with only Native Language as the explanatory variable and mbi_cy score as the outcome variable. NatLang was not a statistically significant explanatory variable with a p-value of 0.186. The Adjusted R-Squared of the model was very low at 0.0085, suggesting that variance NatLang alone does not explain the variance in mbi_cy scores for medical students. The AIC of 5183 serves as a baseline for comparison for goodness of fit with future models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI-cy only nat lang as explanatory variables\nmodel_cy_1 <- lm(mbi_cy ~ NatLang, data = FinalRecoded2)\nsummary(model_cy_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ NatLang, data = FinalRecoded2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.6630 -3.9962 -0.9962  3.0038 14.0038 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  10.6630     0.4769  22.358   <2e-16 ***\nNatLang      -0.6668     0.5040  -1.323    0.186    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.574 on 879 degrees of freedom\nMultiple R-squared:  0.001988,\tAdjusted R-squared:  0.0008526 \nF-statistic: 1.751 on 1 and 879 DF,  p-value: 0.1861\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_cy_1)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5183.262\n```\n:::\n:::\n\n\nAs with the previous emotional exhaustion sub-scale, next I added gender as a the second explanatory variable, as the impact of gender on burnout has been studied. Not only were neither NatLang or gender statistically significant (p-values of 0.191 and 0.783 respectively), but the linear regression model with gender & NatLang as explanatory variables had a worse Adjusted R-Squared than the first model with a negative R-squared of -0.0001993. The AIC of 5185 is higher than in the first model, confirming the worse fit of this model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI-cy  nat lang & gender as explanatory variables\nmodel_cy_2  <- lm(mbi_cy ~ NatLang + gender, data = FinalRecoded2)\nsummary(model_cy_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ NatLang + gender, data = FinalRecoded2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.6859 -3.9339 -0.9339  2.9745 14.0661 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 10.59434    0.53862  19.669   <2e-16 ***\nNatLang     -0.66049    0.50475  -1.309    0.191    \ngender       0.09161    0.33313   0.275    0.783    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.577 on 878 degrees of freedom\nMultiple R-squared:  0.002074,\tAdjusted R-squared:  -0.0001993 \nF-statistic: 0.9123 on 2 and 878 DF,  p-value: 0.402\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_cy_2)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5185.186\n```\n:::\n:::\n\n\nFor the third linear regression model I added the 3 way interaction of NatLang x Anxiety (stai-t score) x Depression (cesd) as an explanatory variable to gender in model 2. The Adjusted R-squared value of 0.1775 suggest a much better fiting model than in the prior 2 models. Gender is statistically significant at the 0.01 level (p-value = 0.0125). Depression (cesd, p-value = 0.07813) & Anxiety (stai_t, p-value = 0.08613) are both significant at the 0.1 level. Contrary to model 2, removing gender as an explanatory variable would lower the adjusted R-squared to gender 0.1685. The AIC of this model is 5027, suggesting the best fit so far.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model 3 MBI_cy 3 way interaction NatLang x cesd x stai_t + gender\nmodel_cy_3 = lm(mbi_cy ~  + gender + NatLang*cesd*stai_t , data = FinalRecoded2)\nsummary(model_cy_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ +gender + NatLang * cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.3237  -3.0923  -0.6276   2.4286  15.6652 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)   \n(Intercept)          3.017407   2.763302   1.092  0.27515   \ngender              -1.017625   0.314287  -3.238  0.00125 **\nNatLang              3.154415   2.917068   1.081  0.27983   \ncesd                 0.250788   0.142195   1.764  0.07813 . \nstai_t               0.118863   0.069182   1.718  0.08613 . \nNatLang:cesd        -0.072387   0.150271  -0.482  0.63013   \nNatLang:stai_t      -0.072897   0.073635  -0.990  0.32246   \ncesd:stai_t         -0.002160   0.002393  -0.903  0.36690   \nNatLang:cesd:stai_t  0.001455   0.002590   0.562  0.57435   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.151 on 872 degrees of freedom\nMultiple R-squared:  0.1849,\tAdjusted R-squared:  0.1775 \nF-statistic: 24.73 on 8 and 872 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_cy_3)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5018.858\n```\n:::\n\n```{.r .cell-code}\n#Test without gender\nsummary(lm(mbi_cy ~  NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ NatLang * cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.4698  -3.1266  -0.6844   2.5435  15.2039 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)  \n(Intercept)          2.689211   2.776402   0.969   0.3330  \nNatLang              3.325117   2.932391   1.134   0.2571  \ncesd                 0.237590   0.142907   1.663   0.0968 .\nstai_t               0.112038   0.069524   1.611   0.1074  \nNatLang:cesd        -0.071845   0.151085  -0.476   0.6345  \nNatLang:stai_t      -0.077049   0.074023  -1.041   0.2982  \ncesd:stai_t         -0.002016   0.002406  -0.838   0.4022  \nNatLang:cesd:stai_t  0.001495   0.002604   0.574   0.5660  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.173 on 873 degrees of freedom\nMultiple R-squared:  0.1751,\tAdjusted R-squared:  0.1685 \nF-statistic: 26.48 on 7 and 873 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\\` To determine the best model, I added the control variables of hours studied, having a partner, job status, consulting a psychotherapist in past 12 months, & health satisfaction to see the impact on the adjusted R squared value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Control variables\n\n\n##hours studied strengthens model\nsummary(lm(mbi_cy ~ gender + stud_h + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + NatLang * cesd * stai_t, \n    data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.6947  -2.9170  -0.5115   2.5003  15.8265 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          4.202266   2.725466   1.542  0.12347    \ngender              -1.103828   0.309423  -3.567  0.00038 ***\nstud_h              -0.049040   0.008823  -5.558 3.62e-08 ***\nNatLang              2.888782   2.868711   1.007  0.31422    \ncesd                 0.261446   0.139832   1.870  0.06186 .  \nstai_t               0.125514   0.068036   1.845  0.06540 .  \nNatLang:cesd        -0.073097   0.147759  -0.495  0.62093    \nNatLang:stai_t      -0.075411   0.072406  -1.041  0.29793    \ncesd:stai_t         -0.002394   0.002354  -1.017  0.30943    \nNatLang:cesd:stai_t  0.001705   0.002548   0.669  0.50350    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.081 on 871 degrees of freedom\nMultiple R-squared:  0.2129,\tAdjusted R-squared:  0.2047 \nF-statistic: 26.17 on 9 and 871 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##partner - lowered adjusted r-squared\nsummary(lm(mbi_cy ~ gender + stud_h + part + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + part + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.7850  -2.9549  -0.5399   2.5005  15.7597 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          4.033722   2.737663   1.473 0.141000    \ngender              -1.112886   0.309808  -3.592 0.000346 ***\nstud_h              -0.048508   0.008860  -5.475 5.73e-08 ***\npart                 0.190578   0.281578   0.677 0.498699    \nNatLang              2.933607   2.870368   1.022 0.307050    \ncesd                 0.266642   0.140086   1.903 0.057316 .  \nstai_t               0.126416   0.068070   1.857 0.063629 .  \nNatLang:cesd        -0.077949   0.147979  -0.527 0.598499    \nNatLang:stai_t      -0.076504   0.072446  -1.056 0.291256    \ncesd:stai_t         -0.002465   0.002357  -1.046 0.295846    \nNatLang:cesd:stai_t  0.001786   0.002551   0.700 0.484009    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.082 on 870 degrees of freedom\nMultiple R-squared:  0.2133,\tAdjusted R-squared:  0.2042 \nF-statistic: 23.58 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##having job - lowered adjusted r-squared\nsummary(lm(mbi_cy ~ gender + stud_h + job + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + job + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.6353  -2.9306  -0.4633   2.5358  15.8792 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          4.085731   2.737852   1.492 0.135980    \ngender              -1.108179   0.309698  -3.578 0.000365 ***\nstud_h              -0.048219   0.008997  -5.360 1.07e-07 ***\njob                  0.139370   0.295455   0.472 0.637250    \nNatLang              2.936696   2.871789   1.023 0.306780    \ncesd                 0.263839   0.139986   1.885 0.059796 .  \nstai_t               0.126449   0.068095   1.857 0.063658 .  \nNatLang:cesd        -0.075814   0.147938  -0.512 0.608452    \nNatLang:stai_t      -0.076325   0.072464  -1.053 0.292508    \ncesd:stai_t         -0.002435   0.002356  -1.034 0.301638    \nNatLang:cesd:stai_t  0.001755   0.002551   0.688 0.491563    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.083 on 870 degrees of freedom\nMultiple R-squared:  0.2131,\tAdjusted R-squared:  0.204 \nF-statistic: 23.56 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## seen psychiatrist - did not improve R-squared\nsummary(lm(mbi_cy ~ gender + stud_h + psyt + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + psyt + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.4672  -2.9080  -0.5373   2.4705  15.8724 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          4.295984   2.727292   1.575  0.11558    \ngender              -1.130528   0.310664  -3.639  0.00029 ***\nstud_h              -0.048290   0.008857  -5.452 6.48e-08 ***\npsyt                 0.338400   0.350042   0.967  0.33394    \nNatLang              2.806847   2.870070   0.978  0.32836    \ncesd                 0.264995   0.139885   1.894  0.05851 .  \nstai_t               0.121060   0.068194   1.775  0.07621 .  \nNatLang:cesd        -0.076487   0.147807  -0.517  0.60495    \nNatLang:stai_t      -0.072240   0.072483  -0.997  0.31921    \ncesd:stai_t         -0.002423   0.002354  -1.029  0.30364    \nNatLang:cesd:stai_t  0.001690   0.002548   0.663  0.50741    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.081 on 870 degrees of freedom\nMultiple R-squared:  0.2137,\tAdjusted R-squared:  0.2047 \nF-statistic: 23.65 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## health sat - improved model\nsummary(lm(mbi_cy ~ gender + stud_h + health + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + health + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.8164  -2.9790  -0.4869   2.4950  15.9812 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          5.157591   2.811583   1.834 0.066935 .  \ngender              -1.099923   0.309279  -3.556 0.000396 ***\nstud_h              -0.049257   0.008820  -5.585 3.13e-08 ***\nhealth              -0.192624   0.140328  -1.373 0.170211    \nNatLang              2.748771   2.869069   0.958 0.338293    \ncesd                 0.259503   0.139768   1.857 0.063695 .  \nstai_t               0.122390   0.068039   1.799 0.072395 .  \nNatLang:cesd        -0.071820   0.147687  -0.486 0.626880    \nNatLang:stai_t      -0.071971   0.072412  -0.994 0.320548    \ncesd:stai_t         -0.002435   0.002353  -1.035 0.301001    \nNatLang:cesd:stai_t  0.001646   0.002547   0.646 0.518354    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.079 on 870 degrees of freedom\nMultiple R-squared:  0.2146,\tAdjusted R-squared:  0.2055 \nF-statistic: 23.77 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n-   Variables that increased the adjusted r-squared of the model were:\n\n    -   Hours studied (stud_h)\n    -   Health satisfaction (health)\n\nThe best-fitting linear regression model for MBI_cy as determined by adjusted R-squared values includes gender, hours studied, health satisfaction, and the 3-way interaction between native language, depression, and anxiety as explanatory variables. This has an Adjusted R-Squared value of 0.2055, suggesting some of the the variance in MBI cynicism scores of medical school students is explained by variance in the explanatory variables. With the AIC level of 4990, the AIC also confirms this is the best-fitting model.\n\n-   Explanatory variables significant at the 0.1 level are:\n\n    -   Depress (cesd)\n    -   Anxiety (stai_t)\n\n-   Explanatory variables significant at the 0.001 level are:\n\n-   Gender\n\n-   Hours studying (stud_h)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model 4\n\nMBI_cy_bestfit <- lm(mbi_cy ~ gender + stud_h + health +  NatLang*cesd*stai_t, data = FinalRecoded2)\nsummary(MBI_cy_bestfit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + health + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.8164  -2.9790  -0.4869   2.4950  15.9812 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          5.157591   2.811583   1.834 0.066935 .  \ngender              -1.099923   0.309279  -3.556 0.000396 ***\nstud_h              -0.049257   0.008820  -5.585 3.13e-08 ***\nhealth              -0.192624   0.140328  -1.373 0.170211    \nNatLang              2.748771   2.869069   0.958 0.338293    \ncesd                 0.259503   0.139768   1.857 0.063695 .  \nstai_t               0.122390   0.068039   1.799 0.072395 .  \nNatLang:cesd        -0.071820   0.147687  -0.486 0.626880    \nNatLang:stai_t      -0.071971   0.072412  -0.994 0.320548    \ncesd:stai_t         -0.002435   0.002353  -1.035 0.301001    \nNatLang:cesd:stai_t  0.001646   0.002547   0.646 0.518354    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.079 on 870 degrees of freedom\nMultiple R-squared:  0.2146,\tAdjusted R-squared:  0.2055 \nF-statistic: 23.77 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(MBI_cy_bestfit)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4990.242\n```\n:::\n:::\n\n\n### Academic Efficacy Burnout MBI-ea\n\nAs with the prior 2 MBI subs scales, I first created a linear regression model with NatLang as the only explanatory variable and academic efficacy burnout MBI_ea as the outcome. NatLang is not a statistically significant explanatory variable in the model with a p-value of 0.852. The Adjusted R-squared of -0.0011 shows the model is a very bad for predicting the outcome variable MBI_ea score. The AIC of this model is 5197.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Academic Efficacy NatLang Alone\nmodel_ea_1 <- lm(mbi_ea ~ NatLang, data = FinalRecoded2)\nsummary(model_ea_1)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ NatLang, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.2205  -3.2205  -0.2205   3.7795  11.7795 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 24.31522    0.48074  50.579   <2e-16 ***\nNatLang     -0.09469    0.50800  -0.186    0.852    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.611 on 879 degrees of freedom\nMultiple R-squared:  3.952e-05,\tAdjusted R-squared:  -0.001098 \nF-statistic: 0.03474 on 1 and 879 DF,  p-value: 0.8522\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ea_1)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5197.324\n```\n:::\n:::\n\n\nFor the second model, I added the second explanatory variable of gender, based on previous findings of its impact on burnout. In this model, neither NatLang (p-value = 0.819) or gender (p-value = 0.351) are statistically significant. The fit of the model is still very poor, as indicated by the Adjusted R-squared of -0.00124. Still, very litle of the variance in academic efficacy burnout is explained by the variance in gender and native language status. The AIC is slightly higher at 5198, suggesting a poor fit of the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear regression model NatLang & gender\nmodel_ea_2 <- lm(mbi_ea ~ NatLang + gender, data = FinalRecoded2)\nsummary(model_ea_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ NatLang + gender, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.4339  -3.1204  -0.1204   3.5661  11.8796 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  24.5503     0.5427  45.238   <2e-16 ***\nNatLang      -0.1164     0.5086  -0.229    0.819    \ngender       -0.3135     0.3356  -0.934    0.351    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.611 on 878 degrees of freedom\nMultiple R-squared:  0.001032,\tAdjusted R-squared:  -0.001243 \nF-statistic: 0.4536 on 2 and 878 DF,  p-value: 0.6355\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ea_2)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5198.449\n```\n:::\n:::\n\n\nFor the third linear regression model, I added the 3-way interaction of NatLang x Depression (cesd) x Anxiety (stai_t) as an explanatory variable in addition to gender, with the outcome variable of mbi_ea score. The adjusted R-squared of this model is 0.2597, suggesting a much better fit than prior models. In this model, anxiety (stai_t) is statistically significant at the 0.05 level. The AIC of 4938 is the lowest of the models so far, suggesting the best fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Model with gender & 3 way interaction NatLang x Depression x Anxiety\nmodel_ea_3 <- lm(mbi_ea ~ gender +  NatLang*cesd*stai_t, data = FinalRecoded2)\nsummary(model_ea_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + NatLang * cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.0246  -2.5302   0.0188   2.5821  15.2910 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         33.040892   2.640002  12.515  < 2e-16 ***\ngender               1.138628   0.300263   3.792  0.00016 ***\nNatLang             -0.921610   2.786906  -0.331  0.74096    \ncesd                -0.122730   0.135850  -0.903  0.36655    \nstai_t              -0.176915   0.066095  -2.677  0.00757 ** \nNatLang:cesd        -0.101544   0.143566  -0.707  0.47957    \nNatLang:stai_t       0.016992   0.070349   0.242  0.80920    \ncesd:stai_t          0.001048   0.002286   0.458  0.64674    \nNatLang:cesd:stai_t  0.001434   0.002475   0.579  0.56252    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.965 on 872 degrees of freedom\nMultiple R-squared:  0.2664,\tAdjusted R-squared:  0.2597 \nF-statistic: 39.58 on 8 and 872 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ea_3)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4938.428\n```\n:::\n\n```{.r .cell-code}\n#3way interaction without gender - worse fit\nsummary(lm(mbi_ea ~  NatLang*cesd*stai_t, data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ NatLang * cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.5816  -2.6526   0.1266   2.6563  15.4490 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         33.4081124  2.6583659  12.567   <2e-16 ***\nNatLang             -1.1126095  2.8077232  -0.396   0.6920    \ncesd                -0.1079627  0.1368312  -0.789   0.4303    \nstai_t              -0.1692785  0.0665684  -2.543   0.0112 *  \nNatLang:cesd        -0.1021503  0.1446617  -0.706   0.4803    \nNatLang:stai_t       0.0216380  0.0708758   0.305   0.7602    \ncesd:stai_t          0.0008866  0.0023035   0.385   0.7004    \nNatLang:cesd:stai_t  0.0013891  0.0024937   0.557   0.5776    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.996 on 873 degrees of freedom\nMultiple R-squared:  0.2543,\tAdjusted R-squared:  0.2483 \nF-statistic: 42.53 on 7 and 873 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nTo determine the best model, I added the control variables of hours studied, having a partner, job status, consulting a psychotherapist in past 12 months, & health satisfaction to see the impact on the adjusted R squared value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Control variables\n\n##hours studied strengthens model \nsummary(lm(mbi_ea ~ gender + stud_h + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + NatLang * cesd * stai_t, \n    data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.7852  -2.4327   0.0613   2.4029  14.2047 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         31.669058   2.582120  12.265  < 2e-16 ***\ngender               1.238434   0.293149   4.225 2.65e-05 ***\nstud_h               0.056779   0.008359   6.793 2.04e-11 ***\nNatLang             -0.614059   2.717831  -0.226  0.82130    \ncesd                -0.135070   0.132477  -1.020  0.30822    \nstai_t              -0.184615   0.064458  -2.864  0.00428 ** \nNatLang:cesd        -0.100722   0.139988  -0.720  0.47202    \nNatLang:stai_t       0.019902   0.068598   0.290  0.77179    \ncesd:stai_t          0.001318   0.002230   0.591  0.55458    \nNatLang:cesd:stai_t  0.001145   0.002414   0.474  0.63537    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.866 on 871 degrees of freedom\nMultiple R-squared:  0.3033,\tAdjusted R-squared:  0.2961 \nF-statistic: 42.13 on 9 and 871 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##partner - weakens model \nsummary(lm(mbi_ea ~ gender + stud_h + part + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + part + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.8188  -2.4552   0.0647   2.4193  14.2476 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         31.579435   2.594144  12.173  < 2e-16 ***\ngender               1.233618   0.293567   4.202 2.92e-05 ***\nstud_h               0.057062   0.008396   6.796 1.99e-11 ***\npart                 0.101340   0.266817   0.380  0.70418    \nNatLang             -0.590223   2.719891  -0.217  0.82826    \ncesd                -0.132307   0.132742  -0.997  0.31918    \nstai_t              -0.184135   0.064502  -2.855  0.00441 ** \nNatLang:cesd        -0.103302   0.140222  -0.737  0.46150    \nNatLang:stai_t       0.019321   0.068648   0.281  0.77844    \ncesd:stai_t          0.001280   0.002233   0.573  0.56664    \nNatLang:cesd:stai_t  0.001188   0.002417   0.491  0.62322    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.868 on 870 degrees of freedom\nMultiple R-squared:  0.3034,\tAdjusted R-squared:  0.2954 \nF-statistic:  37.9 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##having job -weakens model\nsummary(lm(mbi_ea ~ gender + stud_h + job + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + job + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.6939  -2.3959   0.0343   2.4416  14.1748 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         31.818732   2.593577  12.268  < 2e-16 ***\ngender               1.244022   0.293378   4.240 2.47e-05 ***\nstud_h               0.055724   0.008523   6.538 1.06e-10 ***\njob                 -0.179002   0.279885  -0.640  0.52263    \nNatLang             -0.675599   2.720456  -0.248  0.80393    \ncesd                -0.138143   0.132609  -1.042  0.29783    \nstai_t              -0.185816   0.064507  -2.881  0.00407 ** \nNatLang:cesd        -0.097233   0.140142  -0.694  0.48798    \nNatLang:stai_t       0.021076   0.068645   0.307  0.75889    \ncesd:stai_t          0.001372   0.002232   0.615  0.53903    \nNatLang:cesd:stai_t  0.001080   0.002417   0.447  0.65497    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.868 on 870 degrees of freedom\nMultiple R-squared:  0.3036,\tAdjusted R-squared:  0.2956 \nF-statistic: 37.94 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## seen psychiatrist - weakens model\nsummary(lm(mbi_ea ~ gender + stud_h + psyt + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + psyt + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.7875  -2.4098   0.0743   2.3958  14.1929 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         31.661813   2.585228  12.247  < 2e-16 ***\ngender               1.240498   0.294482   4.212 2.79e-05 ***\nstud_h               0.056721   0.008396   6.756 2.60e-11 ***\npsyt                -0.026161   0.331809  -0.079  0.93718    \nNatLang             -0.607725   2.720569  -0.223  0.82329    \ncesd                -0.135344   0.132599  -1.021  0.30768    \nstai_t              -0.184271   0.064642  -2.851  0.00447 ** \nNatLang:cesd        -0.100460   0.140107  -0.717  0.47355    \nNatLang:stai_t       0.019657   0.068707   0.286  0.77487    \ncesd:stai_t          0.001320   0.002231   0.592  0.55416    \nNatLang:cesd:stai_t  0.001146   0.002415   0.475  0.63522    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.869 on 870 degrees of freedom\nMultiple R-squared:  0.3033,\tAdjusted R-squared:  0.2953 \nF-statistic: 37.88 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## health sat - improved model\nsummary(lm(mbi_ea ~ gender + stud_h + health + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + health + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.7305  -2.4347   0.0484   2.4248  13.9423 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         30.460799   2.661451  11.445  < 2e-16 ***\ngender               1.233495   0.292764   4.213 2.78e-05 ***\nstud_h               0.057054   0.008349   6.834 1.55e-11 ***\nhealth               0.243623   0.132835   1.834  0.06699 .  \nNatLang             -0.436979   2.715868  -0.161  0.87221    \ncesd                -0.132613   0.132305  -1.002  0.31646    \nstai_t              -0.180665   0.064406  -2.805  0.00514 ** \nNatLang:cesd        -0.102338   0.139801  -0.732  0.46435    \nNatLang:stai_t       0.015552   0.068546   0.227  0.82057    \ncesd:stai_t          0.001370   0.002227   0.615  0.53857    \nNatLang:cesd:stai_t  0.001220   0.002411   0.506  0.61289    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.861 on 870 degrees of freedom\nMultiple R-squared:  0.306,\tAdjusted R-squared:  0.298 \nF-statistic: 38.36 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n-   Variables that increased the adjusted r-squared of the model were:\n\n    -   Hours studied (stud_h)\n    -   Health satisfaction (health)\n\nThe best-fitting linear regression model for MBI_cy as determined by adjusted R-squared values includes gender, hours studied, health satisfaction, and the 3-way interaction between native language, depression, and anxiety as explanatory variables. This has an Adjusted R-Squared value of 0.298, suggesting some of the the variance in MBI academic efficacy scores of medical school students is explained by variance in the explanatory variables. The AIC of 4893 is the lowest of any of the linear regression models, supporting the fit of this model.\n\n-   Explanatory variables significant at the 0.1 level are:\n\n    -   Health satisfaction (health)\n\n-   Explanatory variables significant at the 0.05 level are:\n\n    -   Anxiety (stai_t)\n\n-   Explanatory variables significant at the 0.001 level are:\n\n-   Gender\n\n-   Hours studied (stud_h)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Best fit model academic efficacy burnout \n\nMBI_ea_bestfit <- lm(mbi_ea ~ gender + stud_h + health +  NatLang*cesd*stai_t, data = FinalRecoded2)\n\n#AIC\nglance(MBI_ea_bestfit)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4893.55\n```\n:::\n\n```{.r .cell-code}\nsummary(MBI_ea_bestfit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + health + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.7305  -2.4347   0.0484   2.4248  13.9423 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         30.460799   2.661451  11.445  < 2e-16 ***\ngender               1.233495   0.292764   4.213 2.78e-05 ***\nstud_h               0.057054   0.008349   6.834 1.55e-11 ***\nhealth               0.243623   0.132835   1.834  0.06699 .  \nNatLang             -0.436979   2.715868  -0.161  0.87221    \ncesd                -0.132613   0.132305  -1.002  0.31646    \nstai_t              -0.180665   0.064406  -2.805  0.00514 ** \nNatLang:cesd        -0.102338   0.139801  -0.732  0.46435    \nNatLang:stai_t       0.015552   0.068546   0.227  0.82057    \ncesd:stai_t          0.001370   0.002227   0.615  0.53857    \nNatLang:cesd:stai_t  0.001220   0.002411   0.506  0.61289    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.861 on 870 degrees of freedom\nMultiple R-squared:  0.306,\tAdjusted R-squared:  0.298 \nF-statistic: 38.36 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n## Diagnostic Models\n\n### MBI Emotional Exhaustion\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Diagnostic Models Emotional Exhaustion\n\n fit_ex <- lm(mbi_ex ~ sex + stud_h + health + job + NatLang*cesd*stai_t, data = FinalRecoded2)\n\n##MBI_ex Residuals vs. Fitted\n\nplot(fit_ex, which = 1) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nThe first diagnostic model of residuals vs. fitted value shows a relatively horizontal line that bounces randomly around the zero line, suggesting linearity and constant variance for the MBI_ex linear regression model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_Ex Normal Q-Q\nplot(fit_ex, which = 2) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nMost of the points of the MBI_ex linear regression Q-Q plot fall along the line, supporting the assumption of normality.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_Ex Scale Location\nplot(fit_ex, which = 3) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nThe Scale-Location plot of the MBI-ex linear regression model is nearly perfectly horizontal without increasing or decreasing, supporting the assumption of constant variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_Ex Cook's Distance\nplot(fit_ex, which = 4) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nThe Cook's distance plot of the MBI_ex linear regression model measures the presence of influential outliers. There appears to be 3 outliers which are influence the model, as shown by at Obs. number at 29, 526, and 756. None of them have a Cook's distance of 1. However with a sample size of n = 881, 4/n = 0.00454 which means taking a closer look at the outliers here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_Ex Residuals vs. leverage \nplot(fit_ex, which = 5) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\nThe Residuals vs. Leverage plot of the MBI_ex linear regression supports the Cook's distance plot that there are some influential observations in the model (outliers) as the red line deviates from the horizontal line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_Ex Cook's Distance vs Leverage\nplot(fit_ex, which = 6) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nThe final diagnostic plot of Cook's Distance vs. Leverage for the MBI-ex plot shows that while there are some residuals, they don't have strong leverage.\n\nOverall the diagnostic models supports the goodness of fit of the emotional exhaustion MBI model and the assumptions of linearity, constant variance, and normality, but there are some outliers that should be examined.\n\n### MBI Cynicism\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Diagnostic model\nfit_cy <- lm(mbi_cy ~ gender + stud_h + health +  NatLang*cesd*stai_t, data = FinalRecoded2)\n\n##MBI_ex Residuals vs. Fitted\nplot(fit_cy, which = 1) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\nThe diagnostic plot of residuals vs. fitted values for the MBI_cy linear regression model is mostly horizontal around the 0 line, though there is some slight funneling in the bottom left half of the plot. This suggests linearity but slight violation of constant variance assumption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_cy Q-Q plot\nplot(fit_cy, which = 2) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\nThe Q-Q plot for the MBI_cy linear regression supports the assumption of normality, as the points all fall along the line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_cy Scale Location\nplot(fit_cy, which = 3) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\nThe Scale-Location plot of the MBI_cy linear regression shows some increasing trend, but is relatively horizontal. The assumption of constant variance is not totally supported but also not totally violated based on the slope of the red line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_cy Cook's distance\nplot(fit_cy, which = 4) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\nThe Cook's distance plot for the MBI-cy linear regression shows 1 influential outlier at observation number 29. This observation does not have a Cook's distance of 1, but is greater than 4/n, which with n=881 is 0.00454, which means taking a closer look at the potential of an influential outlier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_cy Residuals vs Leverage\nplot(fit_cy, which = 5) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\nThe Residuals vs Leverage plot for MBI-cy linear regression model falls within the dashed red line, suggesting that residuals lack leverage to strongly influence the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_cy Cook's dist. vs Leverage\nplot(fit_cy, which = 6) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\nLastly, the diagnostic plot of Cook's dist. vs. Leverage for the MBI_cy linear regression model suggests that any outliers in the model do not have strong leverage on the model.\n\nOverall the diagnostic models mostly support the fit of the cynicism MBI model and the assumptions of linearity and normality, as well as the lack of influential outliers. The diagnostic of residuals vs. fitted and residuals vs variance suggesting some slight violation of the assumption of constant variance.\n\n### MBI Acamemic Efficacy\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ea <- lm(mbi_ea ~ gender + stud_h + health +  NatLang*cesd*stai_t, data = FinalRecoded2)\n\n#MBI_ea Residuals vs. Fitted\nplot(fit_ea, which = 1)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\nThe first diagnostic plot of residuals vs. fitted values for the MBI_ea linear regression has a horizontal trend line without any funneling, supporting the assumptions of linearity and constant variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI_ea Q-Q plot\nplot(fit_ea, which = 2)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\nThe diagnostic Q-Q plot for the MBI-ea linear regression model supports the assumption of normality, as most of the points fall along the line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI_ea scale-location\nplot(fit_ea, which = 3)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\nThe scale-location diagnostic plot for the MBI_ea linear regression model is approximately horizontal, supporting the assumption of constant variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI_ea\nplot(fit_ea, which = 4)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\nThe Cook's distance diagnostic plot for the MBI_ea linear regression model suggests the lack of influential observations (outliers). None of the observations have a Cook's distance near 1, with the highest being less than 0.030, suggesting the outliers don't strongly impact the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI_ea residuals vs. leverage\nplot(fit_ea, which = 5)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\nThe residuals vs. leverage plot for the mbi_ea linear regression model further supports the lack of influential observations (outliers), as does the Cook's Distances vs. Leverage plot below\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI_ea Cooks Distance vs. Leverage\nplot(fit_ea, which = 6)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_CheckIn2_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\nOverall these diagnostic plots support the goodness of fit of the academic efficacy MBI linear regression model, supporting the assumptions of linearity, constant variance, and normality aswell as suggesting the lack of influential outliers.\n\n### Discussion\n\nReturning to my research question:\n\n*Why are some medical students more likely to experience burnout than others?*\n\nThere was not statistical support for my hypothesis that medical students whose native language was a national language where they are in medical school will have lower burnout than medical students speaking the non-native language. I failed to reject the null-hypothesis that there was no difference in the mean burnout scores of native and non-native language speakers. The only MBI sub scale with any statistically significant difference between native & non-native language speakers was for the emotional exhaustion sub-scale, which was only significant at the 0.1 level.\n\nI still find my original hypothesis plausible as being a medical student in a different country would increase rates of burnout due to cultural shock and isolation from family & friends. However, it is unclear if \"native tongue\", the variable in the data set used to code NatLang, truly measures immigrant status or rather ethnicity. Furthermore, the sample used for analysis was of medical students in Switzerland, so these findings cannot be generalized to medical students in all countries.\n\nThrough further T-tests discovered that there was statistically significant difference in anxiety & depression levels for native and non-native language speaking medical students in the direction I expected. Through exploration I discovered that the 3-way interaction term of NatLang x Anxiety x Depression was a strong explanatory variable for burnout on all three sub scales: emotional exhaustion, cyncicism, and academic efficacy. Gender, hours studied, and health satisfaction also explain why some medical students are more likely to experience burnout than others on all three sub scales. For emotional exhaustion burnout, having a partner also impacted burnout.\n\nBased on Adjusted R-squared values, AIC values, and diagnostic plots, the linear regression models are a good fit to explain variance in the outcome variables of burnout on each of the 3 MBI sub-scales.\n\nFuture research might examine how removing outliers and recoding NatLang to include English speakers might impacts significance of the hypothesis & fit of linear regression. While English is not one of the national languages in Switzerland, it is commonly used and on official signage & documents, so it would be interesting to see if there was a statistically significant difference in burnout between medical students with a native tongue of a commonly used language (national language or English) in Switzerland vs. those who do not. Lastly, testing this hypothesis in a global sample would be interesting and allow for more generalizable findings.\n\n## Works Cited\n\nCarrard, V., Bourquin, C., Berney, S, Schlegel, K., Gaume, J., Bart, P-A., Preisig M., Mast, M. A., & Berney, A. (2022). The relationship between medical students' empathy, mental health, and burnout: A cross-sectional study, Medical Teacher, 44:12, 1392-1399, DOI: 10.1080/0142159X.2022.2098708\n\nDoulougeri, K., Georganta, K., & Montgomery, A. (2016). \"Diagnosing\" burnout among healthcare professionals: Can we find consensus?, Cogent Medicine, 3:1, DOI: 10.1080/2331205X.2016.1237605\n\nGradiski, I. P., Borovecki, A., Ćurković, M., San-Martín, M., Delgado Bolton, R. C., & Vivanco, L. (2022). Burnout in International Medical Students: Characterization of Professionalism and Loneliness as Predictive Factors of Burnout. International journal of environmental research and public health, 19(3), 1385. https://doi.org/10.3390/ijerph19031385\n\nGoebert., D., Thompson., D., Takeshita., J., Beach, C., Bryson, P., Ephgrave, K., Kent. A., Kunkel., M., Schechter., J., Tate., J. (2009). Depressive Symptoms in Medical Students and Residents: A Multischool Study. Academic Medicine 84(2):p 236-241, DOI: 10.1097/ACM.0b013e31819391bb\n\nHlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables. R package version 5.2.3. https://CRAN.R-project.org/package=stargazer\n\nJennings, M.L. Medical Student Burnout: Interdisciplinary Exploration and Analysis. J Med Humanit 30, 253--269 (2009). https://doi.org/10.1007/s10912-009-9093-5\n\nKużelewska,E. (2016).Language Policy in Switzerland. Studies in Logic, Grammar and Rhetoric,45(1) 125-140. https://doi.org/10.1515/slgr-2016-0020\n\nMaslach, C., Jackson, S.E., & Jackson, Leiter, M. P. (Eds.) (1996). Maslach Burnout Inventory manual (3rd ed.).\n\nPaturel, A. (2020). Healing the very youngest healers. American Association of Medical Colleges (AAMC). https://www.aamc.org/news-insights/healing-very-youngest-healers#:\\~:text=In%20a%20recent%20study%20%2C%209.4,as%20their%20same%2Dage%20peers.\n\nPeters E. (2018). Compassion fatigue in nursing: A concept analysis. Nursing forum, 53(4), 466--480. https://doi.org/10.1111/nuf.12274\n\nRadloff, L.S. (1977). The CES-D Scale: a self-report depression scale for research in the general population. Applied Psychological Measurement, 1:385-401.\n\nRodriguez, S. Y. S., Carlotta, M. S.. (2017). Predictors of Burnout Syndrome in psychologists. Estudos De Psicologia (campinas), 34(Estud. psicol. (Campinas), 2017 34(1)), 141--150. https://doi.org/10.1590/1982-02752017000100014\n\nShin, H. S., Park, H., & Lee, Y. M. (2022). The relationship between medical students' empathy and burnout levels by gender and study years. Patient education and counseling, 105(2), 432--439. https://doi.org/10.1016/j.pec.2021.05.036\n\nTiesman, H., Weissman, D., Stone., D., Quinlan, K., & Chosewood, L. (2021). Suicide Prevention for Healthcare Workers. CDC. https://blogs.cdc.gov/niosh-science-blog/2021/09/17/suicide-prevention-hcw/\n\nWilliams, B., Beovich, B. Psychometric properties of the Jefferson Scale of Empathy: a COSMIN systematic review protocol. Syst Rev 8, 319 (2019). https://doi.org/10.1186/s13643-019-1240-0\n\nYahya, M. S., Abutiheen, A. A., & Al- Haidary, A. F. (2021). Burnout among medical students of the University of Kerbala and its correlates. Middle East Current Psychiatry, Ain Shams University, 28(1), 78. https://doi.org/10.1186/s43045-021-00152-2\n",
    "supporting": [
      "EmmaNarkewicz_FinalProject_CheckIn2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}