{
  "hash": "503f3b0f114f89f63e73fc9f4b5e093e",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Guanhua Tan\"\ndescription: \"Homework 2\"\ndate: \"03/23/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - t.test\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n:::\n\n\n# Question 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bypass \ns_mean<-19\ns_size <-539\nstandard_error <- 10/539\nstandard_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01855288\n```\n:::\n\n```{.r .cell-code}\n# t-value\nconfidence_level <- 0.9\ntail_area <- (1-confidence_level)/2\nt_score <- qt(p = 1-tail_area, df = s_size-1)\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691\n```\n:::\n\n```{.r .cell-code}\n# plug everything back in\nCI <- c(s_mean - t_score * standard_error,\n        s_mean + t_score * standard_error)\nprint(CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.96943 19.03057\n```\n:::\n:::\n\n18.97 <= CI_bypass <= 19.03\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Angiography\ns_mean_a<-18\ns_size_a<-847\nstandard_error_a <- 9/847\nstandard_error_a\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01062574\n```\n:::\n\n```{.r .cell-code}\n# t-value\nconfidence_level <- 0.9\ntail_area <- (1-confidence_level)/2\nt_score<- qt(p = 1-tail_area, df = s_size-1)\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691\n```\n:::\n\n```{.r .cell-code}\n# plug everything back in\nCI_a <- c(s_mean_a- t_score * standard_error_a,\n        s_mean_a + t_score * standard_error_a)\nprint(CI_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.98249 18.01751\n```\n:::\n:::\n\n17.98 <= CI_angiograpy<= 18.02\n\nThe Confidence Interval is narrower for Angiography surgery because it has a smaller standard_error.\n\n# Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- 567/1031\np2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n\n```{.r .cell-code}\nSE2 <-sqrt(p2*(1-p2)/1031)\ntail_area2 <-(1-0.95)/2\nt_score2 <-qt(p-tail_area2, df=1030)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in qt(p - tail_area2, df = 1030): object 'p' not found\n```\n:::\n\n```{.r .cell-code}\nCI2_A<-p2-t_score2*SE2\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 't_score2' not found\n```\n:::\n\n```{.r .cell-code}\nCI2_B <-p2+t_score2*SE2\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 't_score2' not found\n```\n:::\n\n```{.r .cell-code}\nCI2_A\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'CI2_A' not found\n```\n:::\n\n```{.r .cell-code}\nCI2_B\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'CI2_B' not found\n```\n:::\n:::\n\n0.549 <= P <= 0.551\n\n# Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd_question3 <- (200-30)/4\nMargin3 <-5\nn <- (1.96*sd_question3/Margin3)^2\nn\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\nthe size of students is 277\n\n#Question 4\n\nNull hypothesis: The mean income of female employees is equal to $500 per week.\nH0: μ = $500\nAlternative hypothesis: The mean income of female employees is different from $500 per week.\nHa: μ ≠ $500\nt.test suggests the mean income of female employees is different from $500 per week. We reject the Null hypothesis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfemale_group_mean <-410\nsd_4<-90\nn_4<-9\nt_stat4<-(female_group_mean-500)/(sd_4/sqrt(n_4))\nP_value_4 <-(1-pt(t_stat4, df = n_4-1, lower.tail = F))*2\n\nt_stat4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n\n```{.r .cell-code}\nP_value_4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\nt-statistic is -3.\np-value is 0.017.\n\nB. Report the P-value for Ha: μ < 500. Interpret.\nC. Report and interpret the P-value for Ha: μ > 500.\n\n::: {.cell}\n\n```{.r .cell-code}\nP_value_lower4<-pt(t_stat4, df=n_4-1, lower.tail=TRUE)\nP_value_high4<-pt(t_stat4, df=n_4-1, lower.tail = F)\n\nP_value_lower4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n\n```{.r .cell-code}\nP_value_high4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\nFor Ha: mu<500, we run the pt function and p-value is 0.008, which suggests that we reject the Null hypothesis and the mean income of female employees is much less than 500.\n\nFor Ha: mu >500, we run the pt function and p-value is 0.99, which suggests we fail to reject the Null hypothesis and we are unable to demonstrate the income mean of female employees is greater thant 500.\n\n# Question 5\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question 5\nt_score_5_Jones <-(519.5-500)/10\np_value_5_Jones<- 2*(1-pt(t_score_5_Jones, df=999))\nt_score_5_Jones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\np_value_5_Jones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\nt_score_5_Smith <-(519.7-500)/10\np_value_5_Smith <- 2*(1-pt(t_score_5_Smith, df=999))\nt_score_5_Smith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\np_value_5_Smith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\nB If α=0.5, Smith is statically significant because his p-value is smaller than α.\nC If we don't get the actual p-value, we can only conclude that Smith is statically significant without that there is a very tiny difference between two groups. Also, we will ignore that Smith's p-value is barely smaller than α, which suggests that it is not extremely significant. \n\n# Question 6\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_6<-data.frame(\"Grade Level\"=c(\"Heathy sanck\", \"Unhealth snack\"), \"6th grade\"=c(31,69), \"7th grade\"=c(43,57), \"8th grade\"=c(51,49))\n\nchisq.test(df_6[,-1], correct=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  df_6[, -1]\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\nNull hypothesis: means of 3 grades to choose two types of snack are equal.\nWe should use chisq test to test the correlation between grades and the counts of healthy and unhealthy snacks.\nChisq suggests that we should reject the null hypothesis because p-value is 0.01547, which is smaller than 0.5. In other words, different grades show differen choices of snacks.\n\n\n# Question 7\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question 7\ndf_7<- data.frame(\"Area1\"=c(6.2,9.3,6.8,6.1,6.7,7.5),\n                  \"Area2\"=c(7.5,8.2,8.5,8.2,7.0,9.3),\n                  \"Area3\"=c(5.8,6.5,5.6,7.1,3.0,3.5))\ndf_7_long <- df_7 %>%\n  pivot_longer(cols=c(Area1, Area2, Area3),names_to=\"Area\", values_to = \"Fee\")\n\nmy.anova_7<-aov(Fee ~ Area, df_7_long)\nsummary(my.anova_7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \nArea         2  25.35  12.674   7.993 0.00433 **\nResiduals   15  23.78   1.586                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\nNull hypothesis: mean of three areas are equal.\nWe should use anova test.\nAnova test suggests that we should reject the null hypothesis because p-value is 0.0043, which is much smaller than 0.5. In other words, tutions are highly related to areas.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}