{
  "hash": "359bab3a8c2d66957d14699b67275ab8",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Emma Narkewicz\"\ndescription: \"Template of course blog qmd file\"\ndate: \"02/28/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - confidence_interval\n  - emma_narkewicz\neditor: \n  markdown: \n    wrap: 72\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.4 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.0      ✔ stringr 1.4.1 \n✔ readr   2.1.2      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n:::\n\n\n\n# Question 1\n\nI constructed the 90% confidence interval of each of the two heart\nprocedures manually using the equation: *CI = (X bar) ± (t × s/sqrt(n))*\nand the mean wait time, sample standard deviation, and sample size\nprovided for the Bypass and Angiography heart procedures.\n\nFor both procedures I calculated the t-score based on 2 tails, as there\nwas no information indicating we should only focus on the upper or lower\ntail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating 90% CI  manually of Bypass heart surgery\n## sample mean wait time\ns_mean_bypass <- 19\n## sample sd\ns_sd_bypass <- 10\n## sample size (n)\ns_size_bypass <- 539\n## standard error  (sd/swrt(n))\ns_se_bypass <- s_sd_bypass / sqrt (s_size_bypass)\ns_se_bypass\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4307305\n```\n:::\n\n```{.r .cell-code}\n## Specify confidence level \nconfidence_level_bypass <- 0.9\n##Calculate tail area of 2-tail t-test\ntail_area_bypass <- (1 - confidence_level_bypass)/2\ntail_area_bypass\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\n#calculation t-score using qt\nt_score_bypass <-  qt(p = 1 - tail_area_bypass, df = s_size_bypass - 1)\nt_score_bypass\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691\n```\n:::\n\n```{.r .cell-code}\n##Calculating upper & lower CI bypass\nCI_bypass <- c(s_mean_bypass - t_score_bypass * s_se_bypass, s_mean_bypass + t_score_bypass * s_se_bypass)\nprint(CI_bypass)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n:::\n\n\n-   *The 90% confidence interval for the Bypass wait time is 18.29\n    days - 19.71 days*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculating the 90% CI manually of angiography heart surgery\n##sample mean wait time\ns_mean_angio <- 18\n##sample sd\ns_sd_angio <- 9\n## sample size (n)\ns_size_angio <- 847\n## standard error  (sd/swrt(n)\ns_se_angio <- s_sd_angio / sqrt (s_size_angio)\ns_se_angio\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3092437\n```\n:::\n\n```{.r .cell-code}\n## Specify confidence level \nconfidence_level_angio <- 0.9\n##Calculate tail area of 2-tail t-test\ntail_area_angio <- (1 - confidence_level_angio)/2\ntail_area_angio\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\n#calculation t-score using qt\nt_score_angio <-  qt(p = 1 - tail_area_angio, df = s_size_angio - 1)\nt_score_angio\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.646657\n```\n:::\n\n```{.r .cell-code}\n##Calculating upper & lower CI bypass\nCI_angio <- c(s_mean_angio - t_score_angio * s_se_angio, s_mean_angio + t_score_angio * s_se_angio)\nprint(CI_angio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n:::\n\n\n-   *The 90% confidence interval for the Angiography wait time is 17.49\n    days - 18.51 days*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#narrower CI\ndelta_CI_bypass = 19.71 - 18.29\ndelta_CI_bypass\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.42\n```\n:::\n\n```{.r .cell-code}\ndelta_CI_angio = 18.51 - 17.49\ndelta_CI_angio\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.02\n```\n:::\n:::\n\n\n-   *The confidence interval is narrower for the Angiography (CI delta\n    of 1.02 days) than the confidence interval for the Bypass (CI delta\n    of 1.42 days)*\n\n# Question 2\n\nTo calculate & interpret a 95% CI for the proportion of all adult\nAmericans who believe that a college education is essential for success\nI used prop.test() because this involves estimating a proportion, not a\nprobability. In this test, a \"success\" is defined as an adult American\nreporting a college education is essential for success, with the\nalternative being a response of an adult American reporting a college\neducation is not essential for success.\n\nThe point estimate for the proportion of adult Americans who believe\nthat college is essential is 0.55.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate point estimate college is essential\n\nsample_size_survey <- 1031\npoint_estimate_college_essential <- 567/sample_size_survey\npoint_estimate_college_essential\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n:::\n\n\nSpecific information plugged in was:\n\n-   sample proportion p = point estimate (0.5499515),\n-   number sample \"successes\" x = 567\n-   sample size n = 1031\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Performing prop.test\nprop.test(x = 567, n = 1031, p = point_estimate_college_essential)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  567 out of 1031, null probability point_estimate_college_essential\nX-squared = 6.9637e-30, df = 1, p-value = 1\nalternative hypothesis: true p is not equal to 0.5499515\n95 percent confidence interval:\n 0.5194543 0.5800778\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nThe 95% confidence interval is \\[0.52, 0.58\\]\n\nThis should be interpreted as 95% of confidence intervals calculated\nwith this procedure would contain the true proportion of adult Americans\nwho believe that a college education is essential for success.\n\n# Question 3\n\nSuppose that the financial aid office of UMass Amherst seeks to estimate\nthe mean cost of textbooks per semester for students. The estimate will\nbe useful if it is within \\$5 of the true population mean (i.e. they\nwant the confidence interval to have a length of \\$10 or less). The\nfinancial aid office is pretty sure that the amount spent on books\nvaries widely, with most values between \\$30 and \\$200. They think that\nthe population standard deviation is about a quarter of this range (in\nother words, you can assume they know the population standard\ndeviation).\n\nAssuming the significance level to be 5%, what should be the size of the\nsample?\n\nBecause we are assuming we know the population sd, this signals we\nshould a 2-sided z-test to calculate the sample size. I can solve for\nsample size using the z-score through the Margin of Error (MOE) equation\nthat:\n\nMOE = zscore @ confidence level * (sqrt(sd\\^2/n))\n\nrearranging the equation to solve for n by squaring both sides,\nmultiplying by n, and then dividing by MOE\\^2 results in the equation:\n\nn = (z\\^2 \\* sd\\^2)/ (MOE\\^2)\n\n-   MOE = +/- 5\n-   pop sd = (200-30)/4 = 42.5\n-   at an alpha level 0.05, 2-sided z-score = 1.959964\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#solving for sample size\n\nn = ((1.959964^2) * (42.5^2)) / (5^2) \nn\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5454\n```\n:::\n:::\n\n\n*The ideal sample size is 278*\n\n# Question 4\n\nAccording to a union agreement, the mean income for all senior-level\nworkers in a large service company equals \\$500 per week. A\nrepresentative of a women's group decides to analyze whether the mean\nincome μ for female employees matches this norm. For a random sample of\nnine female employees, ȳ = \\$410 and s = 90\n\n## A\n\nTest whether the mean income of female employees differs from \\$500 per\nweek. Include assumptions, hypotheses, test statistic, and P-value.\nInterpret the result.\n\nAssumptions of a 1-sample t-test:\n\n-   population is normally distributed\n\n-   observations in our sample are generated independently of one\n    another\n\nInformation we are provided is that:\n\n-   Population mean (μ) = 500\n\n-   Sample mean (y bar) = 410\n\n-   Sample sd = 90 s\n\n-   Sample n = 9\n\nNull Hypothesis: (H0) female mean income μ = 500 Alternative Hypothesis:\n(Ha) female mean income μ ≠ 500\n\nCalculate the t statistic using the equation:\n\n*t = (y bar - μ ) / (sd estimate / sqrt(N))*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Calculating tscore\n\nt =  (410 - 500) / (90/sqrt(9))\nt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\n\nThe t-score is -3\n\nTo solve for the p-value from the t-score I will use the pt() function,\nwith a q = the t-statistic of -3, df = 8 (9-1).\n\nIt it is important to note that an assumption of the pt() function is\nyou are looking for the probability of the lower tail, not both tails.\nBecause the t score is negative looking at the lower tail is\nappropriate, but to get the probability for 2-tailed test we need to\nmultiply the lower tail probability by 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculating p-value\n\np_lower_tail = pt(q = t, df =8, lower.tail = TRUE)\np_lower_tail\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nThis gives us the probability that μ is less than 500, but that is only\n1 tail, so we multiply this problity by 2 to get the p value for our\n2-sided t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Two-side t\np_twotail =  p_lower_tail * 2\np_twotail\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nWith a 2-tail p value of 0.017, we can confidently reject the null\nhypothesis that female salary μ = 500 as p\\< 0.05. This suggests that\nthe true mean salary of female workers is not equal to \\$500.\n\n## B\n Report the P-value for Ha: μ \\< 500. Interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#P-value Ha: μ < 500\n\np_lower_tail = pt(q = t, df =8, lower.tail = TRUE)\n\np_lower_tail\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nWith a small p-value of 0.00854 we reject the null hypothesis that μ =\n500, suggesting that the true mean salary of female workers is less than\n$500. \n\n## C\n Report and interpret the P-value for Ha: μ \\> 500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#P-value Ha: μ > 500\n\np_upper_tail = pt(q = t, df =8, lower.tail = FALSE)\n\np_upper_tail\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nWith a large p-value of 0.99 we fail to reject the null hypothesis that\nμ = 500, suggesting that the true means salary of female workers is not\ngreater than \\$500.\n\n# Question 5\n\nJones and Smith separately conduct studies to test H0: μ = 500\nagainst Ha: μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with\nse = 10.0. Smith gets ȳ = 519.7,with se = 10.0.\n\n## A\n\nShow that Show that t = 1.95 and P-value = 0.051 for Jones. Show that t\n= 1.97 and P-value = 0.049 for Smith.\n\nBecause we are provided with standard error not standard deviation, I\nused the equation:\n\nt = (ȳ - μ) / se\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Jones T score\n\nt_Jones = (519.5 - 500) / 10.0\nt_Jones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n:::\n\n\n*For Jones the t score is indeed 1.95*\n\nTo calculate the p-value, I will use pt(), q = 1.95, df = (1000-1) =\n999). Because Jone's t-score is positive, we look at the upper tail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate 1-tail p-value Jones\np_upper_tail_Jones = pt(q = t_Jones, df = 999, lower.tail = FALSE)\np_upper_tail_Jones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.02572777\n```\n:::\n:::\n\n\nThe p value of the upper tail for Jones is 0.02572777, but because the\nalternative hypothesis is 2-tailed, it needs to be multiplied by 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculating p_value Jones\np_Jones = p_upper_tail_Jones * 2\np_Jones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\n\n*This shows the p-value of Jones is indeed 0.51*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Smith T score \nt_Smith = (519.7 - 500) / 10.0\nt_Smith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n:::\n\n\n*The t-score for Smith is indeed 1.97.* The p value is calculated the\nsame way as for Jones, using pt() & the upper tail:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate 1-tail p-value Smith\np_upper_tail_Smith = pt(q = t_Smith, df = 999, lower.tail = FALSE)\np_upper_tail_Smith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.02455713\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Smith p=value\np_Smith = p_upper_tail_Smith * 2\np_Smith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n*Smith's p-value does = 0.049*\n\n## B\n\nUsing an alpha level = 0.05 for both\n\n-   Jones' p-value = 0.51 means a non-statistically significant result,\n    where we fail to reject the null hypothesis that μ = 500\\\n-   Smith's p=value = 0.49 means a statistically significant results,\n    where we reject the null hypothesis that μ = 500\n\n## C\n\nThis example showcases how reporting the actual p-value is important, as\nin this case the p-values are very close between Jones & Smith, which\nare both right on the edge of significance (0.050 +/- 0.01). A p-value\nof 0.049 & a p-value of 0.0000000049 are both less than 0.05 & would\nboth lead us to reject the null hypothesis, but the second p-value is\nhighly significant while the first p-value is only barely significant at\nan alpha level of 0.05. Reporting the p-value itself gives readers &\nother researchers information to much better understand your statistical\nfindings than just reporting if the p value is \\> or \\< 0.05 or if you\ndo or do not reject H0.\n\n# Question 6\n\nA school nurse wants to determine whether age is a factor in whether\nchildren choose a healthy snack after school. She conducts a survey of\n300 middle school students, with the results below. Test at α = 0.05 the\nclaim that the proportion who choose a healthy snack differs by grade\nlevel. What is the null hypothesis? Which test should we use? What is\nthe conclusion?\n\n-   The null hypothesis is that there is no association between the\n    grade of the student and if they choose a healthy snack (they are independent). In this\n    question independence would result in the proportion of students in each\n    grade who choose a healthy snack is the same: H0: p6th = p7th = p8th\n\n-   Because I want to test if there is an association between 2\n    categorical variables, snack preference & grade level, I used a\n    chi-squared test.\n\nFirst I recreated the HW2 snacks data table in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Recreating nurse data\n\nHealth_tab <- matrix(c(31, 43, 51, 69, 57, 49), nrow=2, byrow=TRUE)\ncolnames(Health_tab) <- c('6th','7th','8th')\nrownames(Health_tab) <- c('Healthy','Unhealthy')\nHealth_tab <- as.table(Health_tab)\n\nHealth_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          6th 7th 8th\nHealthy    31  43  51\nUnhealthy  69  57  49\n```\n:::\n:::\n\n\nThen a chi-squared was run on the data set:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Chi Squared test\n\nchisq.test(Health_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  Health_tab\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\n\n-   Conclusion : The p-value of 0.015 from the chi-squared test is less\n    than alpha=0.05, meaning we reject the null hypothesis that there is\n    no association between student grade level and preference for\n    healthy snacks.\n\n-   At a significance level of 0.05 and df = 2, the critical value =\n    5.991. The X-squared = 8.3383 is greater than the critical value,\n    once again supporting rejecting the null hypothesis. This suggests\n    snack preference is not independent of grade level.\n\n# Question 7\n\nPer-pupil costs (in thousands of dollars) for cyber charter school\ntuition for school districts in three areas are shown. Test the claim\nthat there is a difference in means for the three areas, using an\nappropriate test. What is the null hypothesis? Which test should we use?\nWhat is the conclusion?\n\n-   The null hypothesis is that there is no difference between the mean\n    per-pupil cost for cyber charter tuition in 3 different areas, which\n    can be written out as: \n\nH0: μ1 = μ2 = μ3\n\n-   Because we are testing if there is a difference between the means of\n    3 or more groups that differ by the categorical variable of area we\n    should use a ANOVA test\n\n-   I entered in the data below manually, and then pivoted longer to get\n    2 columns, Area and Cost.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nArea_1 <- c( 6.2, 9.3, 6.8, 6.1, 6.7, 7.5)\nArea_2 <- c( 7.5, 8.2, 8.5, 8.2, 7.0, 9.3)\nArea_3 <- c( 5.8, 6.4, 5.6, 7.1, 3.0, 3.5)\n\ncharter_data <- data.frame (Area_1, Area_2, Area_3)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Pivoted Longer\n\npivot_charter <- charter_data %>%\n  pivot_longer(c(Area_1, Area_2, Area_3 ), names_to= \"Area\", values_to=\"Cost\")\n\npivot_charter\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 18 × 2\n   Area    Cost\n   <chr>  <dbl>\n 1 Area_1   6.2\n 2 Area_2   7.5\n 3 Area_3   5.8\n 4 Area_1   9.3\n 5 Area_2   8.2\n 6 Area_3   6.4\n 7 Area_1   6.8\n 8 Area_2   8.5\n 9 Area_3   5.6\n10 Area_1   6.1\n11 Area_2   8.2\n12 Area_3   7.1\n13 Area_1   6.7\n14 Area_2   7  \n15 Area_3   3  \n16 Area_1   7.5\n17 Area_2   9.3\n18 Area_3   3.5\n```\n:::\n:::\n\n\nLastly, I ran the ANOVA, specifying Area as the independent variable &\nCost (per pupil) as the dependent variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Anova \nanova_charter <- aov( Cost ~ Area, data = pivot_charter)\n\nsummary(anova_charter)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \nArea         2  25.66  12.832   8.176 0.00397 **\nResiduals   15  23.54   1.569                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThe resulting p-value of 0.00397 is less than an alpha = 0.05 and\ntherefor significant, leading us to reject out null hypothesis that\nthere is no difference in the mean per-pupil charter school cost between\nthe 3 areas. There does appear to be a difference in per-pupil charter\nschool cost based on which of the 3 areas the school is in.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}