{
  "hash": "eca4dd1d8ef1826be9d89bca89947f9b",
  "result": {
    "markdown": "---\ntitle: \"Final Project check in 2\"\nauthor: \"Thrishul Pola\"\ndescription: \"Final Project Check in 2\"\ndate: \"5/2/2023\"\nformat:\n  html:\n    df-print: paged\n    css: styles.css\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Final_Project_Checkin_2\n---\n\n\n## PREDICTING STUDENT PERFORMANCE IN MATH USING REGRESSION ALGORITHM\n\n# Dataset\n\nProject Description:\n\nThe objective of this project is to predict the math score of students based on the features available in the dataset using various regression algorithms. The dataset consists of data related to students of a particular grade and their scores in Maths, Reading and Writing specified out of 100. The dataset also contains additional features such as gender, race/ethnicity, parental level of education, lunch type, and test preparation course.\n\n## VARIABLE DESCRIPTIONS:\n\n1) gender: specifies gender of the student(male/female)\n\n2) race: specifies race of the student(group A,group B,group C)\n\n3) parental level of education: specifies highest educational qualification of any parent of each student\n\n4) lunch_type: standard/reduced,the type of lunch package selected for the student\n\n5) test_prep: specifies if the test preparation course was completed by the student or not\n\n6) math_score: specifies score in math(our target variable)\n\n7) reading_score: specifies score in reading\n\n8) writing_score: specifies score in writing\n\nAll scores are taken out of 100.\n\n## Importing Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12345)\nlibrary(caret)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'caret' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: ggplot2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: lattice\n```\n:::\n\n```{.r .cell-code}\nlibrary(Metrics)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'Metrics' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'Metrics'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:caret':\n\n    precision, recall\n```\n:::\n\n```{.r .cell-code}\nlibrary(glmnet)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'glmnet' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: Matrix\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoaded glmnet 4.1-7\n```\n:::\n\n```{.r .cell-code}\nlibrary(readr)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nStudentsPerformance <- read_csv(\"_data/StudentsPerformance.csv\", show_col_types = FALSE)\nstr(StudentsPerformance)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [1,000 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ gender         : chr [1:1000] \"female\" \"female\" \"female\" \"male\" ...\n $ race           : chr [1:1000] \"group B\" \"group C\" \"group B\" \"group A\" ...\n $ parent_ed_level: chr [1:1000] \"bachelor's degree\" \"some college\" \"master's degree\" \"associate's degree\" ...\n $ lunch_type     : chr [1:1000] \"standard\" \"standard\" \"standard\" \"free/reduced\" ...\n $ test_prep      : chr [1:1000] \"none\" \"completed\" \"none\" \"none\" ...\n $ math           : num [1:1000] 72 69 90 47 76 71 88 40 64 38 ...\n $ reading        : num [1:1000] 72 90 95 57 78 83 95 43 64 60 ...\n $ writing        : num [1:1000] 74 88 93 44 75 78 92 39 67 50 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   gender = col_character(),\n  ..   race = col_character(),\n  ..   parent_ed_level = col_character(),\n  ..   lunch_type = col_character(),\n  ..   test_prep = col_character(),\n  ..   math = col_double(),\n  ..   reading = col_double(),\n  ..   writing = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(StudentsPerformance)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    gender              race           parent_ed_level     lunch_type       \n Length:1000        Length:1000        Length:1000        Length:1000       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n  test_prep              math           reading          writing      \n Length:1000        Min.   :  0.00   Min.   : 17.00   Min.   : 10.00  \n Class :character   1st Qu.: 57.00   1st Qu.: 59.00   1st Qu.: 57.75  \n Mode  :character   Median : 66.00   Median : 70.00   Median : 69.00  \n                    Mean   : 66.09   Mean   : 69.17   Mean   : 68.05  \n                    3rd Qu.: 77.00   3rd Qu.: 79.00   3rd Qu.: 79.00  \n                    Max.   :100.00   Max.   :100.00   Max.   :100.00  \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(colnames(StudentsPerformance))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"gender\"          \"race\"            \"parent_ed_level\" \"lunch_type\"     \n[5] \"test_prep\"       \"math\"            \"reading\"         \"writing\"        \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(StudentsPerformance)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"race\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"parent_ed_level\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"lunch_type\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"test_prep\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"math\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"reading\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"writing\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"group B\",\"3\":\"bachelor's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"72\",\"7\":\"72\",\"8\":\"74\"},{\"1\":\"female\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"completed\",\"6\":\"69\",\"7\":\"90\",\"8\":\"88\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"master's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"90\",\"7\":\"95\",\"8\":\"93\"},{\"1\":\"male\",\"2\":\"group A\",\"3\":\"associate's degree\",\"4\":\"free/reduced\",\"5\":\"none\",\"6\":\"47\",\"7\":\"57\",\"8\":\"44\"},{\"1\":\"male\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"76\",\"7\":\"78\",\"8\":\"75\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"associate's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"71\",\"7\":\"83\",\"8\":\"78\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n## Data Wrangling\n\n::: {.cell}\n\n```{.r .cell-code}\nStudentsPerformance$total <- StudentsPerformance$math + StudentsPerformance$reading + StudentsPerformance$writing\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(StudentsPerformance$parent_ed_level)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"bachelor's degree\"  \"some college\"       \"master's degree\"   \n[4] \"associate's degree\" \"high school\"        \"some high school\"  \n```\n:::\n:::\n\nSince \"some high school\" and \"high school\" denote the same level of education, we can replace the former with the latter to have a uniform representation of this education level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nStudentsPerformance$parent_ed_level <- ifelse(StudentsPerformance$parent_ed_level == \"some high school\", \"high school\", StudentsPerformance$parent_ed_level)\n\nunique(StudentsPerformance$parent_ed_level)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"bachelor's degree\"  \"some college\"       \"master's degree\"   \n[4] \"associate's degree\" \"high school\"       \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nStudentsPerformance$lunch_type <- ifelse(StudentsPerformance$lunch_type == \"free/reduced\", \"reduced\", StudentsPerformance$lunch_type)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(StudentsPerformance)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"race\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"parent_ed_level\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"lunch_type\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"test_prep\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"math\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"reading\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"writing\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"total\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"group B\",\"3\":\"bachelor's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"72\",\"7\":\"72\",\"8\":\"74\",\"9\":\"218\"},{\"1\":\"female\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"completed\",\"6\":\"69\",\"7\":\"90\",\"8\":\"88\",\"9\":\"247\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"master's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"90\",\"7\":\"95\",\"8\":\"93\",\"9\":\"278\"},{\"1\":\"male\",\"2\":\"group A\",\"3\":\"associate's degree\",\"4\":\"reduced\",\"5\":\"none\",\"6\":\"47\",\"7\":\"57\",\"8\":\"44\",\"9\":\"148\"},{\"1\":\"male\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"76\",\"7\":\"78\",\"8\":\"75\",\"9\":\"229\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"associate's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"71\",\"7\":\"83\",\"8\":\"78\",\"9\":\"232\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\ndf<- StudentsPerformance\n```\n:::\n\n# VISUAL DATA ANALYSIS\n\n## UNIVARIATE ANALYSIS\nIn this context, determining the feature's distribution while disregarding other features is typically carried out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(3, 1))\nplot(density(df$math), main=\"Density Plot: math_score\", ylab=\"Frequency\", sub=paste(\"Skewness:\", round(e1071::skewness(df$math), 2)))\n\npolygon(density(df$math), col=\"red\")\n\nplot(density(df$reading), main=\"Density Plot: reading_score\", ylab=\"Frequency\", sub=paste(\"Skewness:\", round(e1071::skewness(df$reading), 2)))  \n\n# density plot for 'dist'\npolygon(density(df$reading), col=\"red\")\n\nplot(density(df$writing), main=\"Density Plot: writing_score\", ylab=\"Frequency\", sub=paste(\"Skewness:\", round(e1071::skewness(df$writing), 2)))  \n\n# density plot for 'dist'\npolygon(density(df$writing), col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(df, aes(x = math)) +\n  geom_histogram(binwidth = 5) +\n  labs(title = \"Math Scores\", x = \"Score\", y = \"Frequency\") +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 20, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(df, aes(x = reading)) +\n  geom_histogram(binwidth = 5) +\n  labs(title = \"Reading Scores\", x = \"Score\", y = \"Frequency\") +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 20, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(df, aes(x = writing)) +\n  geom_histogram(binwidth = 5) +\n  labs(title = \"Writing Scores\", x = \"Score\", y = \"Frequency\") +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 20, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-12-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(df, aes(x = total)) +\n  geom_histogram(binwidth = 10) +\n  labs(title = \"Total Scores\", x = \"Score\", y = \"Frequency\") +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 20, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-12-4.png){width=672}\n:::\n:::\n\nMultiple distributions that have been graphed, and each of them has a skewness towards the left side of the graph. \n\nA leftward skew indicates that the tail on the left side of the distribution is longer than the tail on the right side. This means that there are more data points or observations with lower values, and fewer with higher values. The distributions being referred to all share this common characteristic of having a leftward skew.\n\n## Box Plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n#math\nggplot(df, aes(x = \"\", y = math)) +\n  geom_boxplot(fill = \"steelblue\", color = \"Black\") +\n  labs(title = \"Box Plot of Math Scores\", x = \"\", y = \"Math Score\") + coord_flip()\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#reading\n\nggplot(df, aes(x = \"\", y = reading)) +\n  geom_boxplot(fill = \"steelblue\", color = \"Black\") +\n  labs(title = \"Box Plot of Reading Scores\", x = \"\", y = \"Reading Score\")  + coord_flip()\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#writing\nggplot(df, aes(x = \"\", y = writing)) +\n  geom_boxplot(fill = \"steelblue\", color = \"Black\") +\n  labs(title = \"Box Plot of Writing Scores\", x = \"\", y = \"Writing Score\")  + coord_flip()\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-13-3.png){width=672}\n:::\n\n```{.r .cell-code}\n#total\nggplot(df, aes(x = \"\", y = total)) +\n  geom_boxplot(fill = \"steelblue\", color = \"Black\") +\n  labs(title = \"Box Plot of Total Scores\", x = \"\", y = \"Total Score\")  + coord_flip()\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-13-4.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\ncat_list <- df$math\ncat_list_1 <- df$reading\ncat_list_2 <- df$writing\ncat_list_3 <- df$total\n# histogram with added parameters\nhist(cat_list,\nmain=\"Math Histogram\",\ncol=\"darkmagenta\",\nfreq=TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(cat_list_1,\nmain=\"Reading Histogram\",\ncol=\"darkmagenta\",\nfreq=TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-14-2.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(cat_list_2,\nmain=\"Writing Histogram\",\ncol=\"darkmagenta\",\nfreq=TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-14-3.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(cat_list_3,\nmain=\"Total Histogram\",\ncol=\"darkmagenta\",\nfreq=TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-14-4.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_list <- c('gender', 'lunch_type', 'test_prep')\n\nfor (col in cat_list) {\n  plt <- ggplot(df, aes_string(x = col)) + \n    geom_bar(stat = \"count\", fill = \"steelblue\") +\n    labs(x = col, y = \"Count\", title = paste(\"Count plot of\", col))\n  print(plt)\n}\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: `aes_string()` was deprecated in ggplot2 3.0.0.\nℹ Please use tidy evaluation ideoms with `aes()`\n```\n:::\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-15-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-15-3.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = factor(parent_ed_level, \n                             levels = c('high school', \n                                        'some college',\n                                        \"associate's degree\", \n                                        \"bachelor's degree\", \n                                        \"master's degree\")))) +\n  geom_bar(fill = \"steelblue\") +\n  labs(x = \"Parent Education Level\", y = \"Count\", \n       title = \"Count plot of Parent Education Level\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Count plot for parental education level\nggplot(df, aes(x = parent_ed_level, fill = parent_ed_level)) +\n  geom_bar(stat = \"count\") +\n  labs(x = \"Parent Education Level\", y = \"Count\", \n       title = \"Count Plot of Parent Education Level\") +\n  scale_x_discrete(limits = c(\"high school\", \"some college\", \"associate's degree\", \"bachelor's degree\", \"master's degree\")) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Count plot for race\nggplot(df, aes(x = race, fill = race)) +\n  geom_bar(stat = \"count\") +\n  labs(x = \"Race/Ethnicity\", y = \"Count\", \n       title = \"Count Plot of Race/Ethnicity\") +\n  scale_x_discrete(limits = c(\"group C\", \"group D\", \"group B\", \"group E\", \"group A\")) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n:::\n\n# MULTIVARIATE ANALYSIS\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nhue <- function(a, b) {\n  if (a == \"parent_ed_level\") {\n    ggplot(df, aes_string(x = a, fill = b)) +\n      geom_bar(position = \"dodge\") +\n      scale_x_discrete(limits = c(\"some high school\", \"high school\", \"some college\", \"associate's degree\", \"bachelor's degree\", \"master's degree\")) +\n      xlab(a) + ylab(\"Count\") + ggtitle(paste(\"Count plot of\", a, \"by\", b)) +\n      theme(axis.text.x = element_text(angle = 45, hjust = 1))\n  } else {\n    ggplot(df, aes_string(x = a, fill = b)) +\n      geom_bar(position = \"dodge\") +\n      xlab(a) + ylab(\"Count\") + ggtitle(paste(\"Count plot of\", a, \"by\", b))\n  }\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhue(\"parent_ed_level\", \"gender\")\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhue(\"parent_ed_level\", \"race\")\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(corrplot)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'corrplot' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ncorrplot 0.92 loaded\n```\n:::\n\n```{.r .cell-code}\nlibrary(reshape2)\n# Compute correlation matrix\ncorr_matrix <- cor(df[, nums])\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in `[.tbl_df`(df, , nums): object 'nums' not found\n```\n:::\n\n```{.r .cell-code}\n# Create heatmap using ggplot2\nggplot(melt(corr_matrix), aes(Var1, Var2, fill = value)) +\n  geom_tile() +\n  scale_fill_gradient(low = \"white\", high = \"darkmagenta\") +\n  labs(title = \"Correlation Heatmap\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in melt(corr_matrix): object 'corr_matrix' not found\n```\n:::\n\n```{.r .cell-code}\n# Create annotated correlation matrix using corrplot\ncorrplot(corr_matrix, method = \"color\", type = \"upper\", \n         tl.col = \"black\", tl.srt = 45, tl.cex = 0.8, addCoef.col = \"black\")\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in corrplot(corr_matrix, method = \"color\", type = \"upper\", tl.col = \"black\", : object 'corr_matrix' not found\n```\n:::\n:::\n\nThe correlation between \"total\" and \"Reading\" as well as \"Writing\" is significantly high, implying a strong linear relationship between these variables. Therefore, it is recommended to remove the \"total\" column since it does not provide any additional information that is not already captured by the other two variables. By dropping the \"total\" column, we can simplify the dataset while still retaining the essential information for our analysis.\n\n::: {.cell}\n\n```{.r .cell-code}\ndf$total <- NULL\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_data <- df\n```\n:::\n\nTo develop a predictive model for math scores of students through feature engineering and selection, a duplicate copy of the original dataset will be created. This copy will serve as a platform for modifying the existing features or creating new ones to capture important information.By working on a copy of the dataset, we can ensure that the original data remains unchanged and the modifications are made in a controlled environment. \n\n::: {.cell}\n\n```{.r .cell-code}\nnew_data <- subset(new_data, select = -writing)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(new_data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"race\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"parent_ed_level\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"lunch_type\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"test_prep\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"math\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"reading\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"group B\",\"3\":\"bachelor's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"72\",\"7\":\"72\"},{\"1\":\"female\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"completed\",\"6\":\"69\",\"7\":\"90\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"master's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"90\",\"7\":\"95\"},{\"1\":\"male\",\"2\":\"group A\",\"3\":\"associate's degree\",\"4\":\"reduced\",\"5\":\"none\",\"6\":\"47\",\"7\":\"57\"},{\"1\":\"male\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"76\",\"7\":\"78\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"associate's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"71\",\"7\":\"83\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(new_data, aes(x = reading, y = math, shape = gender, color = gender)) +\n  geom_point(size = 4) +\n  scale_shape_manual(values = c(1, 2)) +\n   geom_smooth(method = \"lm\", se = FALSE) +\n  labs(title = \"Scatter Plot of Reading and Math Scores by Gender\", x = \"Reading Score\", y = \"Math Score\", shape = \"Gender\", color = \"Gender\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\nIn the scatterplot that has hue parameter set as gender, we can see that male students typically have higher math scores than female students\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplt <- ggplot(new_data, aes(x = reading, y = math, color = factor(gender), shape = factor(lunch_type))) +\n  geom_point(size = 3) +\n  scale_shape_manual(values = c(15, 16)) +  geom_smooth(method = \"lm\", se = FALSE) + \n  labs(title = \"Scatter plot of math vs reading with lunch type as hue\") +\n  theme_minimal()\nprint(plt) \n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplt <- ggplot(new_data, aes(x = reading, y = math, color = factor(gender), shape = factor(test_prep))) +\n  geom_point(size = 3) +\n  scale_shape_manual(values = c(17, 18)) +  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(title = \"Scatter plot of math vs reading with test prep as hue\") +\n  theme_minimal() \nprint(plt)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\nOut of the 3 scatterplots with different classification bases, gender and lunch_type seem the most effective on getting a good math score. So I will eliminate test_prep as one of the predicting features and go ahead with gender and lunch_type.\n\n# CHI-SQUARE TEST FOR FEATURE SELECTION\nHere we consider two features at a time and test the null hypothesis which assumes that the 2 features are independent against the alternative hypothesis that those 2 features are dependent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq <- function(col1,col2) {\n#create a contingency table\ntable <- table(new_data[[col1]],new_data[[col2]])\n#get chi_Sq statistics,p-value,degrees of freedom and expected frequencies.\nresult <- chisq.test(table)\n#set significance level\nalpha <- 0.05\nif (result$p.value <= alpha) {\nprint('Features are associated')\n} else {\nprint('Features are not associated')\n}\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Execute chisq test for all the combinations\nchisq('gender','lunch_type')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Features are not associated\"\n```\n:::\n\n```{.r .cell-code}\nchisq('gender','parent_ed_level')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Features are not associated\"\n```\n:::\n\n```{.r .cell-code}\nchisq('gender','race')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Features are not associated\"\n```\n:::\n\n```{.r .cell-code}\nchisq('gender','test_prep')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Features are not associated\"\n```\n:::\n\n```{.r .cell-code}\nchisq('lunch_type','test_prep')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Features are not associated\"\n```\n:::\n\n```{.r .cell-code}\nchisq('lunch_type','parent_ed_level')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Features are not associated\"\n```\n:::\n\n```{.r .cell-code}\nchisq('lunch_type','race')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Features are not associated\"\n```\n:::\n\n```{.r .cell-code}\nchisq('parent_ed_level','race')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Features are not associated\"\n```\n:::\n\n```{.r .cell-code}\nchisq('parent_ed_level','test_prep')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Features are not associated\"\n```\n:::\n\n```{.r .cell-code}\nchisq('race','test_prep')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Features are not associated\"\n```\n:::\n:::\n\nSince every pair of categorical features is independent we do not eliminate any of these for our feature selection process.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(new_data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"race\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"parent_ed_level\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"lunch_type\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"test_prep\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"math\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"reading\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"group B\",\"3\":\"bachelor's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"72\",\"7\":\"72\"},{\"1\":\"female\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"completed\",\"6\":\"69\",\"7\":\"90\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"master's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"90\",\"7\":\"95\"},{\"1\":\"male\",\"2\":\"group A\",\"3\":\"associate's degree\",\"4\":\"reduced\",\"5\":\"none\",\"6\":\"47\",\"7\":\"57\"},{\"1\":\"male\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"76\",\"7\":\"78\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"associate's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"71\",\"7\":\"83\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nEncoding the categorical features\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_list <- c('gender', 'race', 'lunch_type', 'parent_ed_level')\nfor (col in cat_list) {\n  new_data[[col]] <- factor(new_data[[col]])\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(new_data$race)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\ngroup A group B group C group D group E \n     89     190     319     262     140 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_data$reading <- new_data$reading / 100\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- y/100\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'y' not found\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corrplot)\nlibrary(ggplot2)\nlibrary(reshape2)\n\n# Convert columns to numeric if needed\nnew_data$gender <- as.numeric(new_data$gender)\nnew_data$race <- as.numeric(new_data$race)\nnew_data$parent_ed_level <- as.numeric(new_data$parent_ed_level)\nnew_data$lunch_type <- as.numeric(new_data$lunch_type)\n\n# Calculate correlation matrix\ncorr_matrix <- cor(new_data)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in cor(new_data): 'x' must be numeric\n```\n:::\n\n```{.r .cell-code}\n# Plot heatmap with annotations\nggplot(melt(corr_matrix), aes(Var1, Var2, fill = value, color = \"black\")) +\n  geom_tile() +\n  scale_fill_gradient(low = \"white\", high = \"steelblue\") +\n  geom_text(aes(label = round(value, 2)), size = 3, color = \"black\") +\n  labs(title = \"Correlation Heatmap\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in melt(corr_matrix): object 'corr_matrix' not found\n```\n:::\n:::\n\nBy correlation coefficient we can conclude that there is no high-level of correlation between any of the features\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(df)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"race\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"parent_ed_level\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"lunch_type\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"test_prep\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"math\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"reading\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"writing\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"group B\",\"3\":\"bachelor's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"72\",\"7\":\"72\",\"8\":\"74\"},{\"1\":\"female\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"completed\",\"6\":\"69\",\"7\":\"90\",\"8\":\"88\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"master's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"90\",\"7\":\"95\",\"8\":\"93\"},{\"1\":\"male\",\"2\":\"group A\",\"3\":\"associate's degree\",\"4\":\"reduced\",\"5\":\"none\",\"6\":\"47\",\"7\":\"57\",\"8\":\"44\"},{\"1\":\"male\",\"2\":\"group C\",\"3\":\"some college\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"76\",\"7\":\"78\",\"8\":\"75\"},{\"1\":\"female\",\"2\":\"group B\",\"3\":\"associate's degree\",\"4\":\"standard\",\"5\":\"none\",\"6\":\"71\",\"7\":\"83\",\"8\":\"78\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Multiple Linear Regression\n\n::: {.cell}\n\n```{.r .cell-code}\n# Split the data into training and testing sets\nset.seed(123)\ntrain_idx <- sample(nrow(df), nrow(df) * 0.7)\ntrain_data <- df[train_idx, ]\ntest_data <- df[-train_idx, ]\n\n\nmodel1 <- lm(math ~ reading + writing + gender, data = train_data)\npredictions1 <- predict(model1, newdata = test_data)\nrmse1 <- sqrt(mean((test_data$math - predictions1)^2))\nr_squared1 <- summary(model1)$r.squared\n\n\nmodel2 <- lm(math ~ writing + reading + race + gender , data = train_data)\npredictions2 <- predict(model2, newdata = test_data)\nrmse2 <- sqrt(mean((test_data$math - predictions2)^2))\nr_squared2 <- summary(model2)$r.squared\n\n\nmodel3 <- lm(math ~ lunch_type + gender + reading + writing + race, data = train_data)\npredictions3 <- predict(model3, newdata = test_data)\nrmse3 <- sqrt(mean((test_data$math - predictions3)^2))\nr_squared3 <- summary(model3)$r.squared\n\n# Evaluate the models on the test data\n\ncat(\"Model 1 (math ~ reading + writing + gender): RMSE = \", rmse1, \", R-squared = \", r_squared1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nModel 1 (math ~ reading + writing + gender): RMSE =  6.158159 , R-squared =  0.8362425 \n```\n:::\n\n```{.r .cell-code}\ncat(\"Model 2 (writing + reading + race + gender): RMSE = \", rmse2, \", R-squared = \", r_squared2, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nModel 2 (writing + reading + race + gender): RMSE =  6.052695 , R-squared =  0.8506105 \n```\n:::\n\n```{.r .cell-code}\ncat(\"Model 3 (lunch_type + gender + reading + writing + race): RMSE = \", rmse3, \", R-squared = \", r_squared3 )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nModel 3 (lunch_type + gender + reading + writing + race): RMSE =  5.729597 , R-squared =  0.8631308\n```\n:::\n:::\n\n\n## Model 1 (reading +  writing + gender): \n\nThis model includes only the reading +  writing + gender variable as a predictor of the math variable. \nThe root mean squared error (RMSE) is 6.16, which means that the average prediction error is about 6.16 points. \nThe R-squared value is 0.84, which means that the model explains about 84% of the variance in the math variable using only the reading variable as a predictor.\n\n## Model 2 (writing + reading + race + gender): \n\nThis model includes only the writing + reading + race + gender variables as a predictor of the math variable. \nThe RMSE is 6.05, which is slightly lower than the RMSE of Model 1. \nThe R-squared value is 0.85, which is slightly higher than the R-squared of Model 1.\nThis suggests that the writing variable may be a better predictor of the math variable than the reading variable.\n\n## Model 3 (lunch_type, gender, reading, writing, and race): \n\nThis model includes multiple predictors (lunch_type, gender, reading, writing, and race) to predict the math variable. \nThe RMSE is 5.73, which is the lowest among the three models. \nThe R-squared value is 0.86, which is the highest among the three models. \nThis suggests that including multiple predictors in the model improves the predictive accuracy of the model.\n\n# CONCLUSION\nModel 3, which includes multiple predictors, performs the best in terms of predicting the math variable on the test_data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scatterplot of actual vs. predicted values\nlibrary(ggplot2)\nggplot(data = data.frame(actual = test_data$math, predicted = predictions3)) +\n  geom_point(aes(x = actual, y = predicted)) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\") +\n  labs(x = \"Actual Math Score\", y = \"Predicted Math Score\",\n       title = \"Actual vs. Predicted Math Scores\")\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Residual plot\nresiduals3 <- test_data$math - predictions3\nggplot(data = data.frame(fitted = predictions3, residual = residuals3)) +\n  geom_point(aes(x = fitted, y = residual)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  labs(x = \"Fitted Values\", y = \"Residuals\",\n       title = \"Residual Plot\")\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-39-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Histogram of residuals\nggplot(data = data.frame(residual = residuals3)) +\n  geom_histogram(aes(x = residual), bins = 20, color = \"black\", fill = \"darkmagenta\") +\n  labs(x = \"Residuals\", y = \"Count\",\n       title = \"Histogram of Residuals\")\n```\n\n::: {.cell-output-display}\n![](Thrishul_Final_project_checkin_2_files/figure-html/unnamed-chunk-39-3.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "Thrishul_Final_project_checkin_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}