{
  "hash": "7ec5940e9ea662e4eaabdc21fa3d98d3",
  "result": {
    "markdown": "---\ntitle: \"Final Project Part 3\"\nauthor: \"Hannah Rosenbaum\"\nformat: pdf\neditor: visual\n---\n\n\n## Background\n\nFifty years after the passage of the Title IX Amendment, collegial sports equity has shown relatively minimal change. Allocations of sports budgets often highlight pay discrepancies in participants being \"spent \\[on\\] \\$4,285 per men's participant versus \\$2,588 per women's participant.\" (Feinberg, D., & Hunzinger, E) With these vast differences in individual spending by gender, we see this phenomenon only heightened in the NCAA with women's basketball. Women's basketball not only fares having lower budgets from the NCAA but also, per an ESPN report, \"is underpaying the NCAA for the tournament rights for 29 championships causing the association to lose out on substantial and crucial revenue\\... denoting that the current budget of \\$81 million to \\$112 million multiples more than what the network currently gives.\" (Zimmbalist) Thus, there is not only a discrepancy in budget allocations among the participants by gender but also amongst large broadcast networks.\n\nSignificant systemic issues occur within the gendered branding of 'March Madness.' This can be seen with differentiated treatment of male versus female brackets due to the lack of general awareness of when the women's bracket games even occur. Largely the inequity of the 'March Madness' tournament derives from a differentiation from the NCAA in \"distribution agreements, corporate sponsorships, distribution of revenue, organizational structure and culture all to prioritize Division I men's basketball over everything else\\... to perpetuate gender inequities.\" (Blinder) Likewise, this institutional creation of a high investment in TV rights for men's basketball and minimal airtime for the women's bracket has led to smaller budgeting and fewer avenues to earn revenue. This has led women's teams to be \"starved of a starring role in the national discourse.\" (Blinder) Thus, it creates a circular effect in women's basketball, deriding fewer resources even within facilities at the NCAA tournament in 2021 and in general awareness of TV times.\n\nI am primarily interested in discussing sports equity in women's basketball due to my own personal experience at UF of wanting to watch NCAA basketball for women but having no general knowledge of when women play. I believe that the discussion of equity in sports for women is essential because of the common dismissal of watching women's sports as a pastime.\n\n**Research Questions**\n\n1.  Does the rate of female enrollment in post-secondary education institutions impact the level of female participation in collegiate sports?\n\n2.  What is the relationship between total expenditures on collegiate basketball compared to the total ratio of female athletes in college basketball programs?\n\n3.  What is the relationship between total revenue allocation in NCAA basketball by gender and the total ratio of females playing college basketball?\n\n### Hypothesis\n\n1.  Higher rates of female enrollment at post-secondary institutions do not directly affect female participation in college sports. This hypothesis is because there is no direct correlation between registration and participation in sports, as participation in NCAA sports reflects a small sample size.\n2.  There is a high correlation between expenditure on university sports programs and the percentage of females in university basketball programs by gender. This notion reflects an increased differentiation in total aggregate costs, higher for male than female basketball athletes.\n3.  There is a high correlation between revenue on university sports programs and the percentage of females in university basketball programs by gender. This notion reflects an increased differentiation in total aggregate revenue, higher for male than female basketball athletes. Thus contemplating the idea that 'March Madness' drives profits for male athletes compared to female athletes.\n\n## Descriptive Statistics\n\nThe Equity in Athletics Disclosures Act requires the full financial disclosure of total expenditures, revenue, staffing, and recruiting efforts by men's and women's athletic programs (Mock, J.T.). Data provided by the Equity in Sports project is from all post secondary programs that receive government funding from Title IV funding and is an online database of funding expenses from 2015-2019.\n\nThere are 132,327 rows and a total of 28 columns.\n\n**Feedback from Part 1**\n\nTo measure female participation, I will create a model with `sum_partic_women` as the dependent variable and `ef_female_count` as the explanatory variable.\n\nThe null data in the `data` matrix exist because a given entry has no male or female participation. The columns with null data are `rev_men`, `rev_women`, `exp_men`, `exp_women`.\n\n**Feedback from Part 2**\n\nHypothesis test 1:\n\n-   DV: participation of females in sports, basketball -\n\n-   Key IV: Ratio of participation of females in sports of female students in attendance -\n\n-   Control: percentage of males in sports, basketball -\n\nHypothesis test 2:\n\n-   DV: percentage of females in sports, basketball - I chose this as my dependent variable due to my study wanting to reflect the effect of basketball participation on the total money the university gives to sports.\n\n-   Key IV: expenditure of female sport, basketball. This was my independent variable to measure the total effect of expenses on March Madness.\n\n-   Control: revenue of female sport, expenditure of male sport, percentage of males, sport type. I used the following as controls due to needing to cross-compare how many males played basketball, and total funding for men for basketball to see the overall effect when using my dependent and independent variablese.\n\nHypothesis test 3:\n\n-   DV: percentage of females in sports\n\n-   Key IV: revenue of female sport, basketball\n\n-   Control: expenditure of female sport, revenue of male sport, percentage of males, sport type\n\nRead in Sports Equity data-set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsports <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-29/sports.csv')\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 132327 Columns: 28\n-- Column specification --------------------------------------------------------\nDelimiter: \",\"\nchr  (8): institution_name, city_txt, state_cd, zip_text, classification_nam...\ndbl (20): year, unitid, classification_code, ef_male_count, ef_female_count,...\n\ni Use `spec()` to retrieve the full column specification for this data.\ni Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(wesanderson)\nlibrary(ggplot2)\n```\n:::\n\n\n### Removing \\`Ottawa University-Pheonix\\` due to having zero total male and female attendance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsports = filter(sports, institution_name != \"Ottawa University-Phoenix\")\n```\n:::\n\n\n### Create data-frames: Critical dimensions, Attendance specific, Basketball specific\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- as.data.frame(sports[, c(\"year\", \"institution_name\", \"sports\", \"ef_male_count\", \"ef_female_count\", \"sum_partic_men\", \"sum_partic_women\", 'rev_men', 'rev_women', 'exp_men', 'exp_women')])\n\nattendance_data <- data[,c(\"institution_name\", \"sports\", \"ef_male_count\", \"ef_female_count\", \"sum_partic_men\", \"sum_partic_women\")] %>% group_by(institution_name, sports) %>% summarise(across(everything(), mean), .groups='drop')\n\nbasketball <- as.data.frame(sports[, c(\"year\", \"institution_name\", \"sports\", \"ef_male_count\", \"ef_female_count\", \"sum_partic_men\", \"sum_partic_women\", 'rev_men', 'rev_women', 'exp_men', 'exp_women')])\nbasketball <- filter(basketball, sports=='Basketball')\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ninstitute_lbl <- distinct(as.data.frame(data[, c(\"institution_name\")]))\nsport_lbl <- distinct(as.data.frame(data[, c(\"sports\")]))\n```\n:::\n\n\n### Scatter plots comparing Expenditures against Revenue by Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#data[is.na(data)] <- 0\nplot(data$exp_men, data$rev_men, xlab=\"Male Expenditure\", ylab=\"Male Revenue\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n#ggplot(data = data, aes(x=exp_men, y=rev_men), fill = institute_lbl) + \n#geom_point() +\n#scale_fill_manual(values = wes_palette(length(institute_lbl), name = \"GrandBudapest1\", type = \"continuous\")\n```\n:::\n\n\nWe can see a relationship between revenue and expenditures for men\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(data$exp_women, data$rev_women, xlab=\"Female Expenditure\", ylab=\"Female Revenue\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nSimilarly, we see a sparser relationship between revenue and expenditures for women.\n\n### Descriptive Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 132,317\nColumns: 11\n$ year             <dbl> 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015,~\n$ institution_name <chr> \"Alabama A & M University\", \"Alabama A & M University~\n$ sports           <chr> \"Baseball\", \"Basketball\", \"All Track Combined\", \"Foot~\n$ ef_male_count    <dbl> 1923, 1923, 1923, 1923, 1923, 1923, 1923, 1923, 1923,~\n$ ef_female_count  <dbl> 2300, 2300, 2300, 2300, 2300, 2300, 2300, 2300, 2300,~\n$ sum_partic_men   <dbl> 31, 19, 61, 99, 9, 0, 0, 7, 0, 0, 32, 13, 0, 10, 2, 3~\n$ sum_partic_women <dbl> 0, 16, 46, 0, 0, 21, 25, 10, 16, 9, 0, 20, 68, 7, 10,~\n$ rev_men          <dbl> 345592, 1211095, 183333, 2808949, 78270, NA, NA, 7827~\n$ rev_women        <dbl> NA, 748833, 315574, NA, NA, 410717, 298164, 131145, 3~\n$ exp_men          <dbl> 397818, 817868, 246949, 3059353, 83913, NA, NA, 99612~\n$ exp_women        <dbl> NA, 742460, 251184, NA, NA, 432648, 340259, 113886, 3~\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      year      institution_name      sports          ef_male_count  \n Min.   :2015   Length:132317      Length:132317      Min.   :    0  \n 1st Qu.:2016   Class :character   Class :character   1st Qu.:  514  \n Median :2018   Mode  :character   Mode  :character   Median :  986  \n Mean   :2018                                         Mean   : 2126  \n 3rd Qu.:2019                                         3rd Qu.: 2385  \n Max.   :2019                                         Max.   :35954  \n                                                                     \n ef_female_count sum_partic_men   sum_partic_women    rev_men         \n Min.   :    0   Min.   :  0.00   Min.   :  0.00   Min.   :       65  \n 1st Qu.:  652   1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:    63406  \n Median : 1249   Median :  0.00   Median :  6.00   Median :   158069  \n Mean   : 2496   Mean   : 14.49   Mean   : 10.86   Mean   :   809028  \n 3rd Qu.: 2860   3rd Qu.: 20.00   3rd Qu.: 17.00   3rd Qu.:   400383  \n Max.   :30325   Max.   :331.00   Max.   :327.00   Max.   :156147208  \n                                                   NA's   :70460      \n   rev_women           exp_men           exp_women      \n Min.   :       0   Min.   :      65   Min.   :     65  \n 1st Qu.:   58742   1st Qu.:   63049   1st Qu.:  59294  \n Median :  138292   Median :  159649   Median : 141780  \n Mean   :  279332   Mean   :  662384   Mean   : 331585  \n 3rd Qu.:  331034   3rd Qu.:  423980   3rd Qu.: 361817  \n Max.   :21440365   Max.   :69718059   Max.   :9485162  \n NA's   :63441      NA's   :70460      NA's   :63439    \n```\n:::\n:::\n\n\n### Scatter plots comparing Institution Attendance against Participation by Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(attendance_data$ef_male_count, attendance_data$sum_partic_men, xlab=\"Male Attendance\", ylab=\"Male Participation\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-10-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWe can see there is ahigh concentration of schools with male attendance between 0 and 5000, as attendance gets higher the distribution stays consistent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(attendance_data$ef_female_count, attendance_data$sum_partic_women, xlab=\"Female Attendance\", ylab=\"Female Participation\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWomen generally have a lower participation.\n\n### Scatter plots comparing basketball Participation against Expenditures by Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(basketball$sum_partic_men, basketball$exp_men, xlab=\"Male Participation\", ylab=\"Male Expenditure\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThere is a high concentration of expenditures within schools where team size is smaller.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(basketball$sum_partic_women, basketball$exp_women, xlab=\"Female Participation\", ylab=\"Female Expenditure\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThere is no real trend between female expenditures and participation.\n\n```         \nFor the dataset, I could extrapolate my variables of interest as seen here: <https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-29/readme.md>.\n```\n\n### Hypothesis Test 1\n\nResponse variable: sum_partic_women\n\nExplanatory variable: sum_partic_women / ef_female_count\n\nControl variable: sum_partic_men\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattendance_data$female_participation_ratio <- attendance_data$sum_partic_women / attendance_data$ef_female_count\nattendance_data$female_athlete_participation_ratio <- attendance_data$sum_partic_women / (attendance_data$sum_partic_women + attendance_data$sum_partic_men)\nattendance_data$male_participation_ratio <- attendance_data$sum_partic_men / attendance_data$ef_male_count\n\n#ggplot(data = attendance_data, aes(x=ef_female_count, y=female_participation_ratio)) + geom_point() + scale_color_gradientn(colors=wes_palette(\"GrandBudapest1\"))\nplot(attendance_data$ef_female_count, attendance_data$female_participation_ratio, xlab=\"Female Attendance\", ylab=\"Female Participation Ratio\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(attendance_data$ef_female_count, attendance_data$female_athlete_participation_ratio, xlab=\"Female Attendance\", ylab=\"Atheltic Female Participation Ratio\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-14-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(attendance_data$ef_male_count, attendance_data$male_participation_ratio, xlab=\"Male Attendance\", ylab=\"Male Participation Ratio\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-14-3.pdf){fig-pos='H'}\n:::\n:::\n\n\nBoth plots showing the male/female participation ratio against attendance show a logarithmic pattern.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(log(attendance_data$ef_female_count), log(attendance_data$female_participation_ratio), xlab=\"log(Female Attendance)\", ylab=\"log(Female Participation Ratio)\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(log(attendance_data$ef_female_count), log(attendance_data$female_athlete_participation_ratio), xlab=\"log(Female Attendance)\", ylab=\"log(Atheltic Female Participation Ratio)\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-15-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(log(attendance_data$ef_male_count), log(attendance_data$male_participation_ratio), xlab=\"log(Male Attendance)\", ylab=\"log(Male Participation Ratio)\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-15-3.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhyp_1_fit_1 <- lm(female_participation_ratio ~ ef_female_count, data = filter(attendance_data, female_participation_ratio != Inf))\nhyp_1_fit_2 <- lm(female_participation_ratio ~ ef_female_count, data = filter(attendance_data, female_participation_ratio != Inf & sum_partic_women > 0))\nhyp_1_fit_3 <- lm(female_athlete_participation_ratio ~ ef_female_count, data = filter(attendance_data, female_athlete_participation_ratio != Inf & sum_partic_women > 0))\nsummary(hyp_1_fit_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = female_participation_ratio ~ ef_female_count, data = filter(attendance_data, \n    female_participation_ratio != Inf))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.00673 -0.00621 -0.00547 -0.00002  0.71203 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      6.728e-03  7.947e-05   84.66   <2e-16 ***\nef_female_count -6.975e-07  2.044e-08  -34.13   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01605 on 63166 degrees of freedom\nMultiple R-squared:  0.01811,\tAdjusted R-squared:  0.01809 \nF-statistic:  1165 on 1 and 63166 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_1_fit_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = female_participation_ratio ~ ef_female_count, data = filter(attendance_data, \n    female_participation_ratio != Inf & sum_partic_women > 0))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.02575 -0.01313 -0.00782  0.00427  0.69150 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      2.729e-02  2.515e-04  108.52   <2e-16 ***\nef_female_count -2.868e-06  6.068e-08  -47.26   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02531 on 16114 degrees of freedom\nMultiple R-squared:  0.1218,\tAdjusted R-squared:  0.1217 \nF-statistic:  2234 on 1 and 16114 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_1_fit_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = female_athlete_participation_ratio ~ ef_female_count, \n    data = filter(attendance_data, female_athlete_participation_ratio != \n        Inf & sum_partic_women > 0))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-0.7416 -0.1988 -0.1326  0.3447  0.3774 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     6.226e-01  2.643e-03  235.54   <2e-16 ***\nef_female_count 9.622e-06  6.378e-07   15.09   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.266 on 16115 degrees of freedom\nMultiple R-squared:  0.01393,\tAdjusted R-squared:  0.01387 \nF-statistic: 227.6 on 1 and 16115 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nAIC(hyp_1_fit_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -72766.08\n```\n:::\n\n```{.r .cell-code}\nBIC(hyp_1_fit_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -72743.02\n```\n:::\n\n```{.r .cell-code}\nplot(hyp_1_fit_2)\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-16-2.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-16-3.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-16-4.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhyp_1_fit_4 <- lm(log(female_participation_ratio) ~ log(ef_female_count), data = filter(attendance_data, female_participation_ratio != Inf & sum_partic_women > 0 & ef_female_count > 0))\nhyp_1_fit_5 <- lm(log(female_athlete_participation_ratio) ~ log(ef_female_count), data = filter(attendance_data, female_athlete_participation_ratio != Inf & female_athlete_participation_ratio > 0 & ef_female_count > 0))\n\nsummary(hyp_1_fit_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(female_participation_ratio) ~ log(ef_female_count), \n    data = filter(attendance_data, female_participation_ratio != \n        Inf & sum_partic_women > 0 & ef_female_count > 0))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.5862 -0.3587  0.0456  0.3977  2.4977 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           1.523962   0.037858   40.25   <2e-16 ***\nlog(ef_female_count) -0.835062   0.005171 -161.48   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7151 on 16114 degrees of freedom\nMultiple R-squared:  0.6181,\tAdjusted R-squared:  0.618 \nF-statistic: 2.608e+04 on 1 and 16114 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_1_fit_5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(female_athlete_participation_ratio) ~ log(ef_female_count), \n    data = filter(attendance_data, female_athlete_participation_ratio != \n        Inf & female_athlete_participation_ratio > 0 & ef_female_count > \n        0))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.7085 -0.2825 -0.1368  0.4709  0.7736 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          -1.004208   0.023609  -42.54   <2e-16 ***\nlog(ef_female_count)  0.065751   0.003225   20.39   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4459 on 16114 degrees of freedom\nMultiple R-squared:  0.02515,\tAdjusted R-squared:  0.02509 \nF-statistic: 415.7 on 1 and 16114 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nAIC(hyp_1_fit_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 34930.1\n```\n:::\n\n```{.r .cell-code}\nBIC(hyp_1_fit_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 34953.16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#hist(filter(attendance_data, female_athlete_participation_ratio != Inf & sum_partic_women > 0)$female_athlete_participation_ratio, main=\"\", xlab=\"Female Athletic Participation Ratio\")\n\nggplot(data = filter(attendance_data, female_athlete_participation_ratio != Inf & sum_partic_women > 0), aes(x=female_athlete_participation_ratio, fill=sports)) + geom_histogram() + theme(legend.position='none')\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-18-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nFemale athletic participation has a normal distribution with an outlying spike on the right end.\n\n### Hypothesis Test 2\n\nResponse variable: exp_women\n\nExplanatory variable: sum_partic_women / ef_female_count\n\nControl variable: exp_men\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbasketball$female_participation_ratio <- basketball$sum_partic_women / basketball$ef_female_count\nbasketball$female_athlete_participation_ratio <- basketball$sum_partic_women / (basketball$sum_partic_women + basketball$sum_partic_men)\n\nbasketball$male_participation_ratio <- basketball$sum_partic_men / basketball$ef_male_count\n```\n:::\n\n\n#### Transform basketball table to separate men and women by column\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfemale <- as.data.frame(basketball[, c(\"year\", \"institution_name\", \"sports\", \"ef_female_count\", \"sum_partic_women\", 'rev_women', 'exp_women')])\nfemale$gender <- \"Female\"\nfemale <- female %>% rename(\"ef_count\"=\"ef_female_count\", \"sum_partic\"=\"sum_partic_women\", \"rev\"=\"rev_women\", \"exp\"=\"exp_women\")\n\nmale <- as.data.frame(basketball[, c(\"year\", \"institution_name\", \"sports\", \"ef_male_count\", \"sum_partic_men\", 'rev_men', 'exp_men')])\nmale$gender <- \"Male\"\nmale <- male %>% rename(\"ef_count\"=\"ef_male_count\", \"sum_partic\"=\"sum_partic_men\", \"rev\"=\"rev_men\", \"exp\"=\"exp_men\")\nbasketball_hist <- rbind(male, female)\nbasketball_hist <- filter(basketball_hist, sum_partic > 0)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(basketball$female_participation_ratio, basketball$exp_women, xlab=\"Female Participation Ratio\", ylab=\"Female Expenditures\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(filter(basketball, sum_partic_women > 0)$female_participation_ratio, filter(basketball, sum_partic_women > 0)$exp_women, xlab=\"Female Participation Ratio\", ylab=\"Female Expenditures\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-21-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(filter(basketball, sum_partic_women > 0)$female_athlete_participation_ratio, filter(basketball, sum_partic_women > 0)$exp_women, xlab=\"Female Athletic Participation Ratio\", ylab=\"Female Expenditures\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-21-3.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(basketball$male_participation_ratio, basketball$exp_men, xlab=\"Male Participation Ratio\", ylab=\"Male Expenditures\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-21-4.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe plot showing female athlete participation against expenditures has a very slight trend, but the other three plots show a strong logarithmic pattern.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(log(basketball$female_participation_ratio), log(basketball$exp_women), xlab=\"log(Female Participation Ratio)\", ylab=\"log(Female Expenditures)\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-22-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(log(filter(basketball, sum_partic_women > 0)$female_participation_ratio), log(filter(basketball, sum_partic_women > 0)$exp_women), xlab=\"log(Female Participation Ratio)\", ylab=\"log(Female Expenditures)\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-22-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(log(filter(basketball, sum_partic_women > 0)$female_athlete_participation_ratio), log(filter(basketball, sum_partic_women > 0)$exp_women), xlab=\"log(Female Athletic Participation Ratio)\", ylab=\"log(Female Expenditures)\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-22-3.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(log(basketball$male_participation_ratio), log(basketball$exp_men), xlab=\"log(Male Participation Ratio)\", ylab=\"log(Male Expenditures)\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-22-4.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhyp_2_fit_1 <- lm(exp_women ~ female_participation_ratio, data = filter(basketball, female_participation_ratio != Inf))\nhyp_2_fit_2 <- lm(exp_women ~ female_participation_ratio, data = filter(basketball, female_participation_ratio != Inf & sum_partic_women > 0))\nhyp_2_fit_3 <- lm(exp_women ~ female_athlete_participation_ratio, data = filter(basketball, female_participation_ratio != Inf & sum_partic_women > 0))\nsummary(hyp_2_fit_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = exp_women ~ female_participation_ratio, data = filter(basketball, \n    female_participation_ratio != Inf))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-669197 -493134 -320286   10208 8815838 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  697788      11619   60.06   <2e-16 ***\nfemale_participation_ratio -6077440     300720  -20.21   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 958400 on 9552 degrees of freedom\n  (439 observations deleted due to missingness)\nMultiple R-squared:  0.04101,\tAdjusted R-squared:  0.0409 \nF-statistic: 408.4 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_2_fit_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = exp_women ~ female_participation_ratio, data = filter(basketball, \n    female_participation_ratio != Inf & sum_partic_women > 0))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-669197 -493134 -320286   10208 8815838 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  697788      11619   60.06   <2e-16 ***\nfemale_participation_ratio -6077440     300720  -20.21   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 958400 on 9552 degrees of freedom\nMultiple R-squared:  0.04101,\tAdjusted R-squared:  0.0409 \nF-statistic: 408.4 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_2_fit_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = exp_women ~ female_athlete_participation_ratio, \n    data = filter(basketball, female_participation_ratio != Inf & \n        sum_partic_women > 0))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2056112  -437273  -268066    15346  8284247 \n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                         -785373      53101  -14.79   <2e-16 ***\nfemale_athlete_participation_ratio  2852106     109722   25.99   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 945800 on 9552 degrees of freedom\nMultiple R-squared:  0.06606,\tAdjusted R-squared:  0.06597 \nF-statistic: 675.7 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nAIC(hyp_2_fit_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 290039\n```\n:::\n\n```{.r .cell-code}\nBIC(hyp_2_fit_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 290060.5\n```\n:::\n\n```{.r .cell-code}\nplot(hyp_2_fit_3)\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-23-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-23-2.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-23-3.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-23-4.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Controls\nhyp_2_fit_c1 <- lm(exp_women ~ rev_women, data = filter(basketball, female_participation_ratio != Inf))\nhyp_2_fit_c2 <- lm(exp_women ~ exp_men, data = filter(basketball, female_participation_ratio != Inf))\nhyp_2_fit_c3 <- lm(exp_women ~ sum_partic_men, data = filter(basketball, female_participation_ratio != Inf))\n\nsummary(hyp_2_fit_c1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = exp_women ~ rev_women, data = filter(basketball, \n    female_participation_ratio != Inf))\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-16165268   -106752   -102785    -91699   5879334 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 1.084e+05  7.487e+03   14.48   <2e-16 ***\nrev_women   9.658e-01  8.169e-03  118.23   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 623500 on 9552 degrees of freedom\n  (439 observations deleted due to missingness)\nMultiple R-squared:  0.5941,\tAdjusted R-squared:  0.594 \nF-statistic: 1.398e+04 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_2_fit_c2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = exp_women ~ exp_men, data = filter(basketball, female_participation_ratio != \n    Inf))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-5084097  -131233   -77806    69567  5039235 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 1.715e+05  4.216e+03   40.67   <2e-16 ***\nexp_men     4.335e-01  1.836e-03  236.13   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 374200 on 9439 degrees of freedom\n  (552 observations deleted due to missingness)\nMultiple R-squared:  0.8552,\tAdjusted R-squared:  0.8552 \nF-statistic: 5.576e+04 on 1 and 9439 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_2_fit_c3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = exp_women ~ sum_partic_men, data = filter(basketball, \n    female_participation_ratio != Inf))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-638434 -478799 -364507  -39436 8914009 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      649055      27559  23.552  < 2e-16 ***\nsum_partic_men    -4582       1523  -3.008  0.00264 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 978200 on 9552 degrees of freedom\n  (439 observations deleted due to missingness)\nMultiple R-squared:  0.0009464,\tAdjusted R-squared:  0.0008418 \nF-statistic: 9.049 on 1 and 9552 DF,  p-value: 0.002635\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Logarithmic\nhyp_2_fit_4 <- lm(log(exp_women) ~ log(female_participation_ratio), data = filter(basketball, female_participation_ratio != Inf & sum_partic_women > 0 & exp_women > 0))\nhyp_2_fit_5 <- lm(log(exp_women) ~ log(female_athlete_participation_ratio), data = filter(basketball, female_participation_ratio != Inf & sum_partic_women > 0 & exp_women > 0))\nsummary(hyp_2_fit_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(exp_women) ~ log(female_participation_ratio), \n    data = filter(basketball, female_participation_ratio != Inf & \n        sum_partic_women > 0 & exp_women > 0))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.3169 -0.8131  0.0467  0.9068  3.3624 \n\nCoefficients:\n                                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                     10.14651    0.05119  198.21   <2e-16 ***\nlog(female_participation_ratio) -0.49438    0.01107  -44.65   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.187 on 9552 degrees of freedom\nMultiple R-squared:  0.1726,\tAdjusted R-squared:  0.1726 \nF-statistic:  1993 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_2_fit_5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(exp_women) ~ log(female_athlete_participation_ratio), \n    data = filter(basketball, female_participation_ratio != Inf & \n        sum_partic_women > 0 & exp_women > 0))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.8916 -0.8459 -0.0923  0.8256  4.1097 \n\nCoefficients:\n                                        Estimate Std. Error t value Pr(>|t|)\n(Intercept)                             14.16222    0.05788   244.7   <2e-16\nlog(female_athlete_participation_ratio)  2.36977    0.07452    31.8   <2e-16\n                                           \n(Intercept)                             ***\nlog(female_athlete_participation_ratio) ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.241 on 9552 degrees of freedom\nMultiple R-squared:  0.09572,\tAdjusted R-squared:  0.09563 \nF-statistic:  1011 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nAIC(hyp_2_fit_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30396.6\n```\n:::\n\n```{.r .cell-code}\nBIC(hyp_2_fit_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30418.09\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#hist(filter(basketball, female_athlete_participation_ratio != Inf & sum_partic_women > 0)$exp_women, main=\"\", xlab=\"Female Expenditures\")\n\nggplot(data=filter(basketball, female_athlete_participation_ratio != Inf & sum_partic_women > 0), aes(x=exp_women, fill=sports)) + geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-26-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe female participation histogram within basketball has a heavy concentration toward lower values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#boxplot(exp ~ gender, data=basketball_hist, ylab=\"Expenditures\")\n\nggplot(data=basketball_hist, aes(x=gender, y=exp, fill=gender)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-27-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWithin basketball women and men have a similar mean expenditure, but at a height men receive nearly twice the funds as women.\n\n### Hypothesis Test 3\n\nResponse variable: rev_women\n\nExplanatory variable: sum_partic_women / ef_female_count\n\nControl variable: rev_men\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(basketball$female_participation_ratio, basketball$rev_women, xlab=\"Female Participation Ratio\", ylab=\"Female Revenue\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-28-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(basketball$female_athlete_participation_ratio, basketball$rev_women, xlab=\"Athletic Female Participation Ratio\", ylab=\"Female Revenue\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-28-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(basketball$male_participation_ratio, basketball$rev_men, xlab=\"Male Participation Ratio\", ylab=\"Male Revenue\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-28-3.pdf){fig-pos='H'}\n:::\n:::\n\n\nSimilar to the plots in hypothesis tests one and two, female athletic participation plotted against revenue has a very light trend; but revenue against female participation/female attendance shows a strong logarithmic pattern.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(log(basketball$female_participation_ratio), log(basketball$rev_women), xlab=\"log(Female Participation Ratio)\", ylab=\"log(Female Revenue)\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-29-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(log(basketball$female_athlete_participation_ratio), log(basketball$rev_women), xlab=\"log(Female Athletic Participation Ratio)\", ylab=\"log(Female Revenue)\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-29-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot(log(basketball$male_participation_ratio), log(basketball$rev_men), xlab=\"log(Male Participation Ratio)\", ylab=\"log(Male Revenue)\")\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-29-3.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhyp_3_fit_1 <- lm(rev_women ~ female_participation_ratio, data = filter(basketball, female_participation_ratio != Inf))\nhyp_3_fit_2 <- lm(rev_women ~ female_participation_ratio, data = filter(basketball, female_participation_ratio != Inf & sum_partic_women > 0))\nhyp_3_fit_3 <- lm(rev_women ~ female_athlete_participation_ratio, data = filter(basketball, female_participation_ratio != Inf))\nsummary(hyp_3_fit_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = rev_women ~ female_participation_ratio, data = filter(basketball, \n    female_participation_ratio != Inf))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n -546362  -388437  -240863    59195 20887546 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  570845       9308   61.33   <2e-16 ***\nfemale_participation_ratio -4393071     240902  -18.24   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 767800 on 9552 degrees of freedom\n  (439 observations deleted due to missingness)\nMultiple R-squared:  0.03364,\tAdjusted R-squared:  0.03354 \nF-statistic: 332.5 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_3_fit_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = rev_women ~ female_participation_ratio, data = filter(basketball, \n    female_participation_ratio != Inf & sum_partic_women > 0))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n -546362  -388437  -240863    59195 20887546 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  570845       9308   61.33   <2e-16 ***\nfemale_participation_ratio -4393071     240902  -18.24   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 767800 on 9552 degrees of freedom\nMultiple R-squared:  0.03364,\tAdjusted R-squared:  0.03354 \nF-statistic: 332.5 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_3_fit_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = rev_women ~ female_athlete_participation_ratio, \n    data = filter(basketball, female_participation_ratio != Inf))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1407754  -348702  -220354    43044 21003989 \n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                         -372330      42943   -8.67   <2e-16 ***\nfemale_athlete_participation_ratio  1790705      88733   20.18   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 764900 on 9552 degrees of freedom\n  (439 observations deleted due to missingness)\nMultiple R-squared:  0.04089,\tAdjusted R-squared:  0.04079 \nF-statistic: 407.3 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nAIC(hyp_3_fit_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 285982.1\n```\n:::\n\n```{.r .cell-code}\nBIC(hyp_3_fit_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 286003.6\n```\n:::\n\n```{.r .cell-code}\nplot(hyp_3_fit_3)\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-30-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-30-2.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-30-3.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-30-4.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Controls\nhyp_3_fit_c1 <- lm(rev_women ~ exp_women, data = filter(basketball, female_participation_ratio != Inf))\nhyp_3_fit_c2 <- lm(rev_women ~ rev_men, data = filter(basketball, female_participation_ratio != Inf))\nhyp_3_fit_c3 <- lm(rev_women ~ sum_partic_men, data = filter(basketball, female_participation_ratio != Inf))\n\nsummary(hyp_3_fit_c1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = rev_women ~ exp_women, data = filter(basketball, \n    female_participation_ratio != Inf))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3402605   -94839   -54643    56058 18451560 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 1.281e+05  5.896e+03   21.72   <2e-16 ***\nexp_women   6.151e-01  5.202e-03  118.23   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 497600 on 9552 degrees of freedom\n  (439 observations deleted due to missingness)\nMultiple R-squared:  0.5941,\tAdjusted R-squared:  0.594 \nF-statistic: 1.398e+04 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_3_fit_c2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = rev_women ~ rev_men, data = filter(basketball, female_participation_ratio != \n    Inf))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-5310089  -259684  -173394    73537 20160179 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 3.337e+05  7.284e+03   45.81   <2e-16 ***\nrev_men     1.358e-01  2.239e-03   60.63   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 665700 on 9439 degrees of freedom\n  (552 observations deleted due to missingness)\nMultiple R-squared:  0.2803,\tAdjusted R-squared:  0.2802 \nF-statistic:  3676 on 1 and 9439 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_3_fit_c3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = rev_women ~ sum_partic_men, data = filter(basketball, \n    female_participation_ratio != Inf))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n -507695  -384110  -274416    32257 20960910 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      518316      21999   23.56   <2e-16 ***\nsum_partic_men    -2286       1216   -1.88   0.0602 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 780900 on 9552 degrees of freedom\n  (439 observations deleted due to missingness)\nMultiple R-squared:  0.0003698,\tAdjusted R-squared:  0.0002652 \nF-statistic: 3.534 on 1 and 9552 DF,  p-value: 0.06016\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhyp_3_fit_4 <- lm(log(rev_women) ~ log(female_participation_ratio), data = filter(basketball, female_participation_ratio != Inf & sum_partic_women > 0 & rev_women > 0))\nhyp_3_fit_5 <- lm(log(rev_women) ~ log(female_athlete_participation_ratio), data = filter(basketball, female_participation_ratio != Inf & rev_women > 0))\nsummary(hyp_3_fit_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(rev_women) ~ log(female_participation_ratio), \n    data = filter(basketball, female_participation_ratio != Inf & \n        sum_partic_women > 0 & rev_women > 0))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.2932 -0.7712  0.0441  0.8770  4.1381 \n\nCoefficients:\n                                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                     10.45678    0.04920  212.54   <2e-16 ***\nlog(female_participation_ratio) -0.41592    0.01064  -39.08   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.141 on 9552 degrees of freedom\nMultiple R-squared:  0.1379,\tAdjusted R-squared:  0.1378 \nF-statistic:  1527 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nsummary(hyp_3_fit_5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(rev_women) ~ log(female_athlete_participation_ratio), \n    data = filter(basketball, female_participation_ratio != Inf & \n        rev_women > 0))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.6351 -0.7967 -0.0590  0.8164  4.6339 \n\nCoefficients:\n                                        Estimate Std. Error t value Pr(>|t|)\n(Intercept)                             13.90566    0.05485  253.53   <2e-16\nlog(female_athlete_participation_ratio)  2.08667    0.07063   29.55   <2e-16\n                                           \n(Intercept)                             ***\nlog(female_athlete_participation_ratio) ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.176 on 9552 degrees of freedom\nMultiple R-squared:  0.08373,\tAdjusted R-squared:  0.08364 \nF-statistic: 872.9 on 1 and 9552 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#hist(filter(basketball, female_athlete_participation_ratio != Inf & sum_partic_women > 0)$rev_women, main=\"\", xlab=\"Female Revenue\")\n\nggplot(filter(basketball, female_athlete_participation_ratio != Inf & sum_partic_women > 0), aes(x=rev_women, fill=sports)) + geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-33-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#boxplot(rev ~ gender, data=basketball_hist, ylab=\"Revenue\")\nggplot(data=basketball_hist, aes(x=gender, y=exp, fill=gender)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](FinalProjectPart3_HannahRosenbaum_files/figure-pdf/unnamed-chunk-34-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWomen receive nearly a third the revenue men do at top values.\n\nMy critical variables of interest are the following items:\n\n-   year: Period year\n\n-   institution name: School name\n\n-   sports: Sport name\n\n-   ef_male_count: Total male population\n\n-   ef_female_count: Total female population\n\n-   sum_partic_men: Total male participation\n\n-   sum_partic_women: Total female participation\n\n-   rev_men: Revenue in USD for men\n\n-   rev_women: Revenue in USD for women\n\n-   exp_men: Expenditures in USD for men\n\n-   exp_women: Expenditures in USD for women\n\n## Analysis:\n\nFor hypothesis 1, I added these new columns to the `attendance_data` data set:\n\n1.  female_participation_ratio\n2.  female_athlete_participation_ratio\n3.  male_participation_ratio\n\nI used these metrics to test different approaches to measuring female participation at the collegial level to compare against males.\n\nFor hypotheses 2 & 3, I transformed the `basketball` data set to separate men and women by a new column `gender`, and also de-gendered the metrics to accommodate. The main reason was to use a histogram to better view data and compare gendered differences.\n\n### Model Comparisons and Diagnostics\n\n#### Hypothesis 1 Models:\n\na.  The first model used the female participation ratio as the dependent and effective female count as the explanatory variable. The regression yielded .01809 for an R-Squared, denoting a low correlation between female participation to effective female count, thus indicating a failed hypothesis test.\n\nb.  The second model filters female participation greater the participation an 0. The R-Squared is at .1217, ; this a slight performance improvement but still is statistically insignificant. Thus, the hypothesis still fails on this test. However, in comparison to .013807 and .01809 the best performing model is in the second test and is what is chosen to represent the data set.\n\nc.  The third model is female athlete participation ratio (female participation divided by female and male participation) explained by ef_female_count. The third hypothesis 1 model shows slightly better performance at .013807 but still fails the hypothesis test.\n\n##### Adding logs\n\na.  The first model applies a natural log to the second model from above. This sees a significant improvement in performance with an adjusted r-squared of 0.618.\n\nb.  The second model is similar to the third model above but applying logs. This too sees a great increase in accuracy, but still falls short at 0.02509.\n\n#### Hypothesis 2 Models:\n\na.  The second model measures the expenditure as a dependent and female participation as an explanatory. The R-Squared is .0409.\n\nb.  We see the same R-Squared in a and b due to the filter not removing the used observations.\n\nc.  I then use expenditures by the female athlete participation ratio ; we the R-Squared at .0657. Due to .0657 still being higher than the other R-Squared, , we use this as the model comparisons. However, we still reject this hypothesis.\n\n##### Testing Controls\n\na.  Modeling female expenditures explained by female revenue shows a strong correlation, with an adjsted r-squared of 0.594.\n\nb.  The second model has female expenditures explained by male expenditures results in a significant 0.8552 adjusted r-squared value.\n\nc.  The first model shows female expenditures by male participation has a lacking result of 0.0008418 as an adjusted r-squared.\n\n##### Applying Logs\n\na.  The first model shows a log based female expenditures explaine dby a log based female participation ratio. This resulted in a solid 0.1726 adjusted r-squared.\n\nb.  The second model shows a log based female expenditure explaing by log(female athletic participation ratio). The model produced a smaller 0.09563 adjusted r-squared.\n\n#### Hypothesis 3 Models:\n\na.  The third model measures the revenue as a dependent and female participation as an explanatory. The R-Squared is 0.03354.\n\nb.  We see the same R-Squared in a and b due to the filter not removing the used observations.\n\nc.  I then use revenue by the female athlete participation ratio; we the R-Squared at 0.04079. Due to 0.04079 still being higher than the other R-Squared, we use this as the model comparison. However, we still reject this hypothesis.\n\n##### Testing Controls\n\na.  Modeling female revenue explained by female revenue shows a strong correlation, with an adjusted r-squared of 0.594.\n\nb.  The second model has female revenue explained by male expenditures results in a significant 0.2802 adjusted r-squared value.\n\nc.  The first model shows female revenue by male participation has a lacking result of 0.0002652 as an adjusted r-squared.\n\n##### Applying Logs\n\na.  The first model shows a log based female revenue explained by a log based female participation ratio. This resulted in a solid 0.1378 adjusted r-squared.\n\nb.  The second model shows a log based female revenue explaing by log(female athletic participation ratio). The model produced a smaller 0.08364 adjusted r-squared.\n\n### Interesting Plot Takeaways\n\nFor the boxplot comparing gender to revenue, we see that at the maximum, women make a quarter of the revenue. For the boxplot comparing gender to expenditures, we see that women are given half as much in funding for basketball.\n\n## Conclusion:\n\nThrough testing, I showed all hypotheses passed by having an adjusted r-squared value greater than 10%. Hypothesis 1 proved as female enrollment at schools increases, participation in sports does not necessarily increase, and tends to decrease. Hypothesis 2 shows there is a correlalation between expenditures toward sports and the participation of each gender in that respective sport. I also show that Men have a significatly higher expenditure rate, indicating schools promote mens sports at a higher rate. Hypothesis 3 shows there is a high correlation between revenue on university sports and the participation of each gender in each sport. As shown through these tests, schools promote men's sports at higher rates. THis contributes to the idea that 'March Madness' drives higher profits for mens sports.\n\n## References\n\n-   Blinder, A. (2021, August 3). *Report: N.C.A.A. Prioritized Men's Basketball 'Over Everything Else.'* The New York Times. Retrieved April 12, 2023, from https://www.nytimes.com/2021/08/03/sports/ncaabasketball/ncaa-gender-equity-investigation.html?partner=slack&smid=sl-share.\n\n-   Feinberg, D., & Hunzinger, E. (2021, October 26). *Second NCAA Gender Equity Report Shows Spending Disparities*. US News. Retrieved April 11, 2023, from https://www.usnews.com/news/sports/articles/2021-10-26/second-ncaa-gender-equity-report-shows-spending-disparities#:\\~:text=The%20NCAA%20spent%20%244%2C285%20per,championships%20than%20for%20the%20women%27s.\n\n-   Mock, J. T. (2022, March 29). *rfordatascience/tidytuesday*. GitHub. Retrieved April 10, 2023, from https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-29/readme.md.\n\n-   Zimbalist, A. (2022, October 12). *Female Athletes Are Undervalued, In Both Money And Media Terms*. Forbes. Retrieved April 12, 2023, from https://www.forbes.com/sites/andrewzimbalist/2019/04/10/female-athletes-are-undervalued-in-both-money-and-media-terms/?sh=5006015513ed.\n",
    "supporting": [
      "FinalProjectPart3_HannahRosenbaum_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}