{
  "hash": "3570bd910068842380c2fc21f4f2a6bd",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Diana Rinker\"\ndescription: \"HW2\"\ndate: \"3/25/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n# DACSS 603, spring 2023\n\n# Homework 2, Diana Rinker.\n\nLoading necessary libraries:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2\n──\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ tibble  3.1.8     ✔ purrr   1.0.1\n✔ tidyr   1.3.0     ✔ stringr 1.5.0\n✔ readr   2.1.4     ✔ forcats 1.0.0\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n:::\n\n\n# Question 1\n\n***The time between the date a patient was recommended for heart surgery\nand the surgery date for cardiac patients in Ontario was collected by\nthe Cardiac Care Network (\"Wait Times Data Guide,\" Ministry of Health\nand Long-Term Care, Ontario, Canada, 2006). The sample mean and sample\nstandard deviation for wait times (in days) of patients for two cardiac\nprocedures are given in the accompanying table. Assume that the sample\nis representative of the Ontario population.***\n\n\n::: {.cell}\n\n```{.r .cell-code}\n`Surgical Procedure` <- c(\"Bypass\", \"Angiography\" )\n`Sample Size` <- c(539,847 )\n`Mean Wait Time` <- c(19, 18)\n`Standard Deviation` <- c(10, 9)\ndata<- data.frame(`Surgical Procedure`,`Sample Size`, `Mean Wait Time`, `Standard Deviation` )\nknitr::kable(data )\n```\n\n::: {.cell-output-display}\n|Surgical.Procedure | Sample.Size| Mean.Wait.Time| Standard.Deviation|\n|:------------------|-----------:|--------------:|------------------:|\n|Bypass             |         539|             19|                 10|\n|Angiography        |         847|             18|                  9|\n:::\n:::\n\n\n*Construct the 90% confidence interval to estimate the actual mean wait\ntime for each of the two procedures. Is the confidence interval narrower\nfor angiography or bypass surgery?*\n\nThe formula for the confidence interval of a sample is\n\n$$\nCI =\\bar{X} \\pm  t \\cdot \\frac{s}{\\sqrt n}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculating degree of freedom for each sample: \ndata <- data%>%\n  mutate(confidence_level = 0.9,\n         tail_area = (1-confidence_level)/2,\n         t_score = qt(p = 1-tail_area, df = `Sample.Size` -1),\n         CI.low  = `Mean Wait Time` - t_score * `Standard.Deviation` / sqrt(`Sample.Size`), \n         CI.high= `Mean Wait Time` + t_score * `Standard.Deviation` / sqrt(`Sample.Size`),\n         CI.width = abs(CI.high - CI.low)\n         )\ndata<- data %>%\nselect (Surgical.Procedure, CI.low,CI.high , CI.width, t_score, everything() )\nknitr::kable(data ) \n```\n\n::: {.cell-output-display}\n|Surgical.Procedure |   CI.low|  CI.high| CI.width|  t_score| Sample.Size| Mean.Wait.Time| Standard.Deviation| confidence_level| tail_area|\n|:------------------|--------:|--------:|--------:|--------:|-----------:|--------------:|------------------:|----------------:|---------:|\n|Bypass             | 18.29029| 19.70971| 1.419421| 1.647691|         539|             19|                 10|              0.9|      0.05|\n|Angiography        | 17.49078| 18.50922| 1.018436| 1.646657|         847|             18|                  9|              0.9|      0.05|\n:::\n:::\n\n\nFrom the table above I can see that the width of confidence interval for\nAngiography is smaller than for Bypass.\n\nAlternatvie way to calculate the interval is by simulating the data\nbased on given parameters and running one-sided t.test() :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAngiography.data <- rnorm(n=847, mean =18 , sd = 9)\n# Calculate the sample mean\nmean.q1 <- mean(Angiography.data )\n# Adjust the sample to have a mean of exactly 410\nAngiography.data <- Angiography.data + 18 - mean.q1\n\nt.test(Angiography.data, alternative = \"two.sided\", conf.level = 0.9) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  Angiography.data\nt = 59.128, df = 846, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n90 percent confidence interval:\n 17.49872 18.50128\nsample estimates:\nmean of x \n       18 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nBypass.data <- rnorm(n=539, mean =19 , sd = 10)\n# Calculate the sample mean\nmean.bypass.q1 <- mean(Bypass.data )\n# Adjust the sample to have a mean of exactly 410\nBypass.data  <- Bypass.data  + 19 - mean.bypass.q1\n\nt.test(Bypass.data , alternative = \"two.sided\", conf.level = 0.9) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  Bypass.data\nt = 45.732, df = 538, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n90 percent confidence interval:\n 18.31544 19.68456\nsample estimates:\nmean of x \n       19 \n```\n:::\n:::\n\n\n# Question 2\n\n***A survey of 1031 adult Americans was carried out by the National\nCenter for Public Policy. Assume that the sample is representative of\nadult Americans. Among those surveyed, 567 believed that college\neducation is essential for success. Find the point estimate, p, of the\nproportion of all adult Americans who believe that a college education\nis essential for success. Construct and interpret a 95% confidence\ninterval for p.***\n\nI will assume, that the survey responses are within binomial\ndistribution ( i.e. respondents had an option to agree or disagree that\ncollege education is essential for success).\n\nPoint estimate for this sample is 567/1031\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoint.estimate <- 567/1031\n```\n:::\n\n\nConfidence interval = point estimate ± margin of error. To calculate a\nconfidence interval for the p, I will usr the following formula:\n\n$$ \nCI =\\bar{p} \\pm Zscore \\cdot SE\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSample.proportion <- 567/1031\nSample.Size <- 1031\ndata2<- data.frame(Sample.proportion,Sample.Size  )\ndata2<- data2%>%\n  mutate(SE =(sqrt(Sample.proportion*(1-Sample.proportion)/Sample.Size)), # for binomial distribution\n        z_score = 1.96, # for 95% cofidence interval  \n       CI.low  = Sample.proportion - z_score * SE,\n         CI.high= Sample.proportion + z_score * SE\n        )\nknitr::kable(data2 ) \n```\n\n::: {.cell-output-display}\n| Sample.proportion| Sample.Size|       SE| z_score|    CI.low|   CI.high|\n|-----------------:|-----------:|--------:|-------:|---------:|---------:|\n|         0.5499515|        1031| 0.015494|    1.96| 0.5195833| 0.5803197|\n:::\n:::\n\n\nThis confidence interval can be interpreted as \"The people who agreethat college education is essential for success is between 52% and 58%from general American population\".\n\nI could also calculate  confidence interval by generating a sample data set and using prob.test() function: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#generating data table: \n  # Generating sample for grade 6:\n  successes <- 0\n  p <- 567/1031\n  n<-1031\n  # repeat until the desired number of successes is obtained\n  while (successes != 567) {\n          responses <- rbinom(n=1031, 1, p=p)\n  # count the number of successes\n          successes <- sum(responses)\n  }\nrespondent.n <-seq(1:1031)\ndataset.q2 <-data.frame( respondent.n , responses)\n  \nprop.test(x = sum(dataset.q2$responses), n=n,  p =p )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  sum(dataset.q2$responses) out of n, null probability p\nX-squared = 6.9637e-30, df = 1, p-value = 1\nalternative hypothesis: true p is not equal to 0.5499515\n95 percent confidence interval:\n 0.5194543 0.5800778\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nThis way of calculating  CI provided me with the same  interval as the first one.\n\n\n# Question 3\n\n***Suppose that the financial aid office of UMass Amherst seeks to\nestimate the mean cost of textbooks per semester for students. The\nestimate will be useful if it is within \\$5 of the true population mean\n(i.e. they want the confidence interval to have a length of \\$10 or\nless). The financial aid office is pretty sure that the amount spent on\nbooks varies widely, with most values between \\$30 and \\$200. They think\nthat the population standard deviation is about a quarter of this range\n(in other words, you can assume they know the population standard\ndeviation). Assuming the significance level to be 5%, what should be the\nsize of the sample?***\n\nSince I am given standard deviation of population, I can use the\nfollowing formula for CI for confidence level 95%:\n\n$$\nCI =\\bar{X} \\pm  1.96 \\cdot \\frac{\\sigma}{\\sqrt n}  \n$$ The range of CI will be\n\n$$\nCI range = 10=(\\bar{X} +  1.96 \\cdot \\frac{\\sigma}{\\sqrt n})  -(\\bar{X} -  1.96 \\cdot \\frac{\\sigma}{\\sqrt n})   \n$$\n\n$$\n  2\\cdot (1.96 \\cdot \\frac{\\sigma}{\\sqrt n})  = 10\n$$\n\n$$\n  {\\sqrt n}  = \\frac{1.96\\sigma}{5}\n$$\n\n$$\n n = (\\frac{1.96 \\cdot  42.5}{5})^2 \n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSD.population <- (200-30)/4\nn<- ((1.96*SD.population)/5)^2\nknitr::kable(n) \n```\n\n::: {.cell-output-display}\n|        x|\n|--------:|\n| 277.5556|\n:::\n:::\n\n\nTo calculate confidence interval width of \\$10, financial aid office\nshould collect a sample size of 278 students.\n\n# Question 4\n\n***According to a union agreement, the mean income for all senior-level\nworkers in a large service company equals \\$500 per week. A\nrepresentative of a women's group decides to analyze whether the mean\nincome μ for female employees matches this norm. For a random sample of\nnine female employees, ȳ = \\$410 and s = 90 A. Test whether the mean\nincome of female employees differs from \\$500 per week. Include\nassumptions, hypotheses, test statistic, and P-value. Interpret the\nresult. B. Report the P-value for Ha: μ \\< 500. Interpret. C. Report and\ninterpret the P-value for Ha: μ \\> 500. (Hint: The P-values for the two\npossible one-sided tests must sum to 1.***\n\n#### *A. Two-sided t.test:* \n\n***Test whether the mean income of female employees differs from \\$500\nper week. Include assumptions, hypotheses, test statistic, and P-value.\nInterpret the result.***\n\nAssumption: The sample is representative of all senior-level female\nworkers in that company.\n\nHo: mean of female income is close to the company policy income of\n\\$500. H1: mean of female income is not the same as the company policy\nincome of \\$500.\n\nTo test this hypothesis, I will used one-sample t.test, which will\ncompare mean and cinficance interval of a sample to a policy level of\n\\$500.\n\nT.test() function in R uses t-statistics to evaluate small sample size\n(9).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate a sample with a mean close to 410\nfemale.sample <- rnorm(n=9, mean=410, sd=90)\n# Calculate the sample mean\nsample.mean <- mean(female.sample)\n# Adjust the sample to have a mean of exactly 410\nfemale.sample <- female.sample + 410 - sample.mean\na.ttest.sample<-t.test(female.sample, alternative = \"two.sided\", mu=500)\na.ttest.sample\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  female.sample\nt = -2.2966, df = 8, p-value = 0.05074\nalternative hypothesis: true mean is not equal to 500\n95 percent confidence interval:\n 319.6305 500.3695\nsample estimates:\nmean of x \n      410 \n```\n:::\n:::\n\n\nThe output shows 95% confidence interval (325 - 494) with the p-value\nunder 0.05. This interval does not include policy value of \\$500,\nmeaning that the true female income mean at the company is very unlikely\nto be 500. Therefore I reject Ho, and Accept H1.\n\n#### *B. One-sided, \"less\"*\n\n***Report the P-value for Ha: μ \\< 500. Interpret.***\n\nHo: mean of female income is no less than the company policy income of\n\\$500. H1: mean of female income is lower than the company policy income\nof \\$500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb.ttest.sample<-t.test(female.sample, alternative = \"less\", mu=500)\nb.ttest.sample\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  female.sample\nt = -2.2966, df = 8, p-value = 0.02537\nalternative hypothesis: true mean is less than 500\n95 percent confidence interval:\n     -Inf 482.8735\nsample estimates:\nmean of x \n      410 \n```\n:::\n:::\n\n\nThe confidence interval for this hypothesis is even further from 500,\nthat for two-sided test: (-inf, 455) which does not include 500. I\naccept alternative hypothesis that true female income is lower than 500.\nP-value for one-sided test is twice lower than for two-sided , because\nwe are only estimating one direction from the mean.\n\n#### *C. One-sided, \"greater\".*\n\n***Report and interpret the P-value for Ha: μ \\> 500.***\n\nHo: mean of female income is not greater than the company policy income\nof \\$500. H1: mean of female income is greater than the company policy\nincome of \\$500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc.ttest.sample<-t.test(female.sample, alternative = \"greater\", mu=500)\nc.ttest.sample\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  female.sample\nt = -2.2966, df = 8, p-value = 0.9746\nalternative hypothesis: true mean is greater than 500\n95 percent confidence interval:\n 337.1265      Inf\nsample estimates:\nmean of x \n      410 \n```\n:::\n:::\n\n\nThe confidence interval for this hypothesis includes 500, which\nsuppports H0 that the female income is not greater than company policy.\nAdditionally, p-value is greater than 0.05 which also supports Ho.\n<!-- We can see that the sum if p-values for B and C scenarions ( that female -->\nincome is less or greater than 500) equals to 1.\n\n------------------------------------------------------------------------\n\n# Question 5\n\n***Jones and Smith separately conduct studies to test H0: μ = 500\nagainst Ha: μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se =\n10.0. Smith gets ȳ = 519.7, with se = 10.0.***\n\n***A. Show that t = 1.95 and P-value = 0.051 for Jones. Show that t =\n1.97 and P-value = 0.049 for Smith.***\n\n***B. Using α = 0.05, for each study indicate whether the result is\n\"statistically significant.\"***\n\n***C. Using this example, explain the misleading aspects of reporting\nthe result of a test as \"P ≤ 0.05\" versus \"P \\> 0.05,\" or as \"reject H0\"\nversus \"Do not reject H0,\" without reporting the actual P-value.***\n\n#### *A. Calculating t-statistics for each sample:\n\n***Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97\nand P-value = 0.049 for Smith.***\n\nTo do that, we will create a summary table containing both samples/\nparameters and calculate t-statistic, critical value and p-value\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate a sample with a mean 519.5 for John\n# John.data1<- rnorm(n=1000,  mean =519.5)\n# John.mean <- mean(John.data1)\n# John.data1<- John.data1 + 519.5 - John.mean\n# John.mean <- mean(John.data1)\n# John.mean\n\nn<-c(1000, 1000) \nstudy.name <- c(\"John\", \"Smith\")\nMeans <- c(519.5, 519.7) \nSE <- c(10.0, 10.0) \nsummary <- data.frame(study.name, n, Means, SE)\n\nsummary <- summary%>%\n  mutate(tail_area = (1-0.95)/2,\n         t_score = round( qt(p = 1-tail_area, df = n -1), 2),# Critical t-value \n         CI.low  = Means - t_score * SE, \n         CI.high = Means + t_score * SE,\n         test.statistics = ((Means - 500)/ SE),\n         p.value = (1 - pt(test.statistics, df = n -1)) * 2\n         )\n\n knitr::kable(summary) \n```\n\n::: {.cell-output-display}\n|study.name |    n| Means| SE| tail_area| t_score| CI.low| CI.high| test.statistics|   p.value|\n|:----------|----:|-----:|--:|---------:|-------:|------:|-------:|---------------:|---------:|\n|John       | 1000| 519.5| 10|     0.025|    1.96|  499.9|   539.1|            1.95| 0.0514555|\n|Smith      | 1000| 519.7| 10|     0.025|    1.96|  500.1|   539.3|            1.97| 0.0491143|\n:::\n:::\n\n\nI can see from the table above, that the Confidence Interval (CI) for\nJohn's data inludes 500 value, while Somth's CI doesnt. Also I see that\nthe two datasets result in slightly different test statistics and\ntherefore p-value, which are very close to the tested value. Due to\nJohn's p-value being above 0.05, I will accept HO. However, Smith\np-value is below 0.05 and I would decline HO and accept H1.\n\n#### *B. Interpreting statistical significance.*\n\n***Using α = 0.05, for each study indicate whether the result is\n\"statistically significant.\"***\n\nWe can conclude that the difference between 500 and the mean of Smith's\nsample is **statistically significant to reject Ho**, while John's\nsample mean's difference from 500 is not statistically significant (i.e.\nnot far enough from 500).\n\n#### *C. Potential misleading of comparing p-value to 0.05:*\n\n***Using this example, explain the misleading aspects of reporting the\nresult of a test as \"P ≤ 0.05\" versus \"P \\> 0.05,\" or as \"reject H0\"\nversus \"Do not reject H0,\" without reporting the actual P-value.***\n\nComparing this two almost identical samples allowed us to demonstrate\nhow a tiny difference in sample mean can produce difference in study\noutcomes (rejection vs acceptance of Ho). It is important to remember,\nthat the sample means vary due to randomness of sampling process, and\ntherefore produce variety of confidence intervals, test statistics and\np-values.Reporting actual p-value will demonstrate its closeness to 0.05\ncutoff level, and warn the reader about potential error in conclusion.\n\n------------------------------------------------------------------------\n\n# Question 6\n\n***A school nurse wants to determine whether age is a factor in whether\nchildren choose a healthy snack after school. She conducts a survey of\n300 middle school students, with the results below. Test at α = 0.05 the\nclaim that the proportion who choose a healthy snack differs by grade\nlevel. What is the null hypothesis? Which test should we use? What is\nthe conclusion?***\n\n\n::: {.cell}\n\n```{.r .cell-code}\n`grade level` <- c(\"6\",\"7\",\"8\")\n`Healthy snack` <- c(31,43,51)\n`Unhealthy snack` <- c(69,57,49)\ntable <- data.frame (`grade level`, `Healthy snack`, `Unhealthy snack` )\n# table <- addmargins( table , margin =1:2,  FUN = sum)\nknitr::kable(table)  \n```\n\n::: {.cell-output-display}\n|grade.level | Healthy.snack| Unhealthy.snack|\n|:-----------|-------------:|---------------:|\n|6           |            31|              69|\n|7           |            43|              57|\n|8           |            51|              49|\n:::\n:::\n\n\nThis table represents data for two categorical variables: `grade level`\nand `snack choice`\n\nI will generate a sample data as given above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # Generating sample for grade 6:\n  successes <- 0\n  # repeat until the desired number of successes is obtained\n  while (successes != 31) {\n          grade6 <- rbinom(n=100, 1, 0.31)\n  # count the number of successes\n          successes <- sum(grade6)\n  }\n  \n  # Generating sample for grade 7:\n  successes <- 0\n  while (successes != 43) {\n            grade7 <- rbinom(n=100, 1, 0.43)\n            successes <- sum(grade7)\n            }\n  \n  # Generating sample for grade 8:\n  successes <- 0\n  while (successes != 51) {\n          grade8 <- rbinom(n=100, 1, 0.51)\n          successes <- sum(grade8)\n          }\n  # Combining all grades in one table for analysis:\n  table2<- data.frame(grade6, grade7, grade8)\n  table2<- table2 %>%\n        pivot_longer(c(grade6, grade7, grade8 ), names_to= \"grade\", values_to=\"healthy.choice\")\n\n  xtabs <-xtabs(~table2$grade + table2$healthy.choice)\n  knitr::kable(  xtabs )  \n```\n\n::: {.cell-output-display}\n|       |  0|  1|\n|:------|--:|--:|\n|grade6 | 69| 31|\n|grade7 | 57| 43|\n|grade8 | 49| 51|\n:::\n:::\n\n\nThe school nurse collected this data to test the following hypothesis:\n\nHo: all grades' samples are coming from the same general population, and\nprobability of making healthy choice is equal for all grades.\n\nH1: probability of making healthy choice is not equal for all grades.\n\nI will use a chi-square test to test this hypothesis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  table2$healthy.choice <- as.character (table2$healthy.choice)\n  table2$grade <- as.character(table2$grade)\nch.sq<- chisq.test(table2$grade, table2$healthy.choice ,correct = FALSE)\nch.sq\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  table2$grade and table2$healthy.choice\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\n\nThe p-value of 0.01 makes me to reject H0 hypothesis that all grades\nhave equal probability, and accpet H1, that the kids of different grades\ndiffer in probability of making haealthy snack choice.\n\n------------------------------------------------------------------------\n\n# Question 7\n\nPer-pupil costs (in thousands of dollars) for cyber charter school\ntuition for school districts in three areas are shown. Test the claim\nthat there is a difference in means for the three areas, using an\nappropriate test. What is the null hypothesis? Which test should we use?\nWhat is the conclusion?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nArea.1 <- c( 6.2, 9.3, 6.8, 6.1, 6.7, 7.5)\nArea.2 <- c( 7.5, 8.2, 8.5, 8.2, 7.0, 9.3)\nArea.3 <- c( 5.8, 6.4 ,5.6, 7.1, 3.0, 3.5)\n\ntable.q7 <- data.frame (Area.1, Area.2, Area.3)\nknitr::kable(table.q7 )   \n```\n\n::: {.cell-output-display}\n| Area.1| Area.2| Area.3|\n|------:|------:|------:|\n|    6.2|    7.5|    5.8|\n|    9.3|    8.2|    6.4|\n|    6.8|    8.5|    5.6|\n|    6.1|    8.2|    7.1|\n|    6.7|    7.0|    3.0|\n|    7.5|    9.3|    3.5|\n:::\n:::\n\n\nHo: there is no difference in means between the three areas. H1: At\nleast one of these areas' means is significantly different.\n\nTo test this hypopthesis, I will use ANOVA test to compare means of\nthree samples:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n table.q7  <- table.q7  %>%\n        pivot_longer(c(Area.1, Area.2, Area.3 ), names_to= \"Area\", values_to=\"score\")\n\ntable.q7$Area <- as.factor (table.q7$Area)\nanova.q7 <- aov( score ~ Area, table.q7 )\nsummary(anova.q7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \nArea         2  25.66  12.832   8.176 0.00397 **\nResiduals   15  23.54   1.569                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThe results of ANOVA test demonstrate p-value of 0.00397. I make a\nconclusion that at least one of the three areas' means is significantly\ndifferent from others (i.e reject Ho and accept H1).\n\n---\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}