{
  "hash": "bfd5fa418c652ebfdf845670902909d1",
  "result": {
    "markdown": "---\ntitle: \"Homework 4\"\nauthor: \"Xiaoyan\"\ndescription: \"Template of course blog qmd file\"\ndate: \"04/17/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw4\n  - \n  - \n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(ggplot2)\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'car'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: effects\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n:::\n\n# Question 1\nFor recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home\n(in square feet), and x2 = lot size (in square feet), the prediction equation is\nŷ = −10,536 + 53.8x1 + 2.84x2.\n\nA. A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000.\nFind the predicted selling price and the residual, and interpret.\n\n::: {.cell}\n\n```{.r .cell-code}\n(-10536) + 53.8*1240 + 2.84*18000\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n:::\n\nB. For fixed lot size, how much is the house selling price predicted to increase for each square-\nfoot increase in home size? Why?\n\n53.8\n\nC. According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?\n\n::: {.cell}\n\n```{.r .cell-code}\n53.8 / 2.84\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n# Question 2\n(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.\n\nA. Test the hypothesis that the mean salary for men and women is the same, without regard to\nany other variable but sex. Explain your findings.\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   degree rank    sex year ysdeg salary\n1 Masters Prof   Male   25    35  36350\n2 Masters Prof   Male   13    22  35350\n3 Masters Prof   Male   10    23  28200\n4 Masters Prof Female    7    27  26775\n5     PhD Prof   Male   19    30  33696\n6 Masters Prof   Male   16    21  28516\n```\n:::\n\n```{.r .cell-code}\nunique(salary$rank)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] Prof  Assoc Asst \nLevels: Asst Assoc Prof\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(salary~sex, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8602.8 -4296.6  -100.8  3513.1 16687.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    24697        938  26.330   <2e-16 ***\nsexFemale      -3340       1808  -1.847   0.0706 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5782 on 50 degrees of freedom\nMultiple R-squared:  0.0639,\tAdjusted R-squared:  0.04518 \nF-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706\n```\n:::\n:::\n\nB. Run a multiple linear regression with salary as the outcome variable and everything else as\npredictors, including sex. Assuming no interactions between sex and the other predictors,\nobtain a 95% confidence interval for the difference in salary between males and females.\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(salary~degree+rank+sex+year+ysdeg, data=salary)|>\n  confint()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\nC. Interpret your finding for each predictor variable; discuss (a) statistical significance, \n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(salary~degree+rank+sex+year+ysdeg, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n(b)\ninterpretation of the coefficient / slope in relation to the outcome variable and other variables\n\ndegree, sex, and ysdeg are not statistically significant at this situation. \nAssociate professor make 5292 more than asisstant professor and professor makes 11118 more than assitant professor. \nAs year is a continues varible, one year increase makes 476 more salary\n\nD. Change the baseline category for the rank variable. Interpret the coefficients related to rank\nagain.\n\nBased on this analysis, the assitant professor makes 11118 less then full professor and associate professor make 5826 less than full professor. \n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank<-relevel(salary$rank, ref = \"Prof\")\nsummary(lm(salary~., data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nsexFemale     1166.37     925.57   1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nE. Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote,\n“[a] variable may reflect a position or status bestowed by the employer, in which case if there\nis discrimination in the award of the position or status, the variable may be ‘tainted.’ ” Thus,\nfor example, if discrimination is at work in promotion of faculty to higher ranks, using rank to\nadjust salaries before comparing the sexes may not be acceptable to the courts.\nExclude the variable rank, refit, and summarize how your findings changed, if they did.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(salary~degree+sex+year+ysdeg, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\nF. Everyone in this dataset was hired the year they earned their highest degree. It is also\nknown that a new Dean was appointed 15 years ago, and everyone in the dataset who\nearned their highest degree 15 years ago or less than that has been hired by the new Dean.\nSome people have argued that the new Dean has been making offers that are a lot more\ngenerous to newly hired faculty than the previous one and that this might explain some of\nthe variation in Salary.\nCreate a new variable that would allow you to test this hypothesis and run another multiple\nregression model to test this. Select variables carefully to make sure there is no\nmulticollinearity. Explain why multicollinearity would be a concern in this case and how\nyou avoided it. Do you find support for the hypothesis that the people hired by the new\nDean are making higher than those that were not?\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$newyear<-ifelse(salary$year <= 20,10,0)\ncor.test(salary$newyear, salary$year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  salary$newyear and salary$year\nt = -3.5608, df = 50, p-value = 0.0008223\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.6436643 -0.2016149\nsample estimates:\n       cor \n-0.4497686 \n```\n:::\n\n```{.r .cell-code}\nsummary(lm(salary~degree+sex+newyear+ysdeg, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + newyear + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8248.6 -2611.6  -786.1  2910.8 11147.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 19996.62    4605.45   4.342 7.47e-05 ***\ndegreePhD   -4087.81    1375.85  -2.971  0.00466 ** \nsexFemale   -2693.61    1251.85  -2.152  0.03659 *  \nnewyear      -161.96     432.94  -0.374  0.71001    \nysdeg         467.24      66.54   7.022 7.57e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3973 on 47 degrees of freedom\nMultiple R-squared:  0.5845,\tAdjusted R-squared:  0.5491 \nF-statistic: 16.53 on 4 and 47 DF,  p-value: 1.602e-08\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(salary~degree+sex+newyear+ysdeg+year, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + newyear + ysdeg + year, \n    data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8314.2 -2146.3  -222.6  2240.8 11044.4 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15012.81    4821.50   3.114 0.003175 ** \ndegreePhD   -3411.96    1335.79  -2.554 0.014017 *  \nsexFemale   -1233.85    1329.06  -0.928 0.358065    \nnewyear       202.79     437.23   0.464 0.644984    \nysdeg         341.08      81.38   4.191 0.000125 ***\nyear          375.97     152.72   2.462 0.017633 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3775 on 46 degrees of freedom\nMultiple R-squared:  0.6329,\tAdjusted R-squared:  0.593 \nF-statistic: 15.86 on 5 and 46 DF,  p-value: 4.589e-09\n```\n:::\n:::\n\n# Question 3\n(Data file: house.selling.price in smss R package)\n\nA. Using the house.selling.price data, run and report regression results modeling y = selling\nprice (in dollars) in terms of size of home (in square feet) and whether the home is new (1 =\nyes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the\nmeaning of the coefficient.\n\n::: {.cell}\n\n:::\n\nB. Report and interpret the prediction equation, and form separate equations relating selling\nprice to size for new and for not new homes.\n\n::: {.cell}\n\n:::\n\nC. Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\n\n::: {.cell}\n\n:::\n\nD. Fit another model, this time with an interaction term allowing interaction between size and\nnew, and report the regression results\n\n::: {.cell}\n\n:::\n\nE. Report the lines relating the predicted selling price to the size for homes that are (i) new,\n(ii) not new.\n\n::: {.cell}\n\n:::\n\nF. Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\n\n::: {.cell}\n\n:::\n\nG. Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new.\nComparing to (F), explain how the difference in predicted selling prices changes as the size\nof home increases.\n\n::: {.cell}\n\n:::\n\nH. Do you think the model with interaction or the one without it represents the relationship of\nsize and new to the outcome price? What makes you prefer one model over another?\n\n::: {.cell}\n\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}