{
  "hash": "f03e90856b738a018560192a0867619a",
  "result": {
    "markdown": "---\ntitle: \"Homework - 5\"\nauthor: \"Thrishul\"\ndescription: \"Homework 5\"\ndate: \"05/05/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw5\n---\n\n\n# Question 1\n\n## A\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'alr4' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'car' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'carData' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: effects\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'effects' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(smss)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'smss' was built under R version 4.2.3\n```\n:::\n\n```{.r .cell-code}\nx1 <- 1240\nx2 <- 18000\nactual_price <- 145000\n\npredicted_price <- -10536 + 53.8 * x1 + 2.84 * x2\nresidual <- actual_price - predicted_price\ncat(\"A. Predicted selling price:\", predicted_price, \"\\nResidual:\", residual, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nA. Predicted selling price: 107296 \nResidual: 37704 \n```\n:::\n:::\n\nBased on the given variables, where y represents the selling price, and x1 and x2 represent the house size and lot size respectively, and using the prediction equation for a 1,240 sqft house on an 18,000 sqft lot, the estimated selling price is $107,296. However, the actual selling price of the house is $145,000, indicating that it sold for $37,704 more than the projected selling price.\n\n## B\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhome_size_coefficient <- 53.8\ncat(\"B. House selling price predicted to increase for each square-foot increase in home size:\", home_size_coefficient, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nB. House selling price predicted to increase for each square-foot increase in home size: 53.8 \n```\n:::\n:::\n\n## C\n\n::: {.cell}\n\n```{.r .cell-code}\nhome_size_increase <- 1\nlot_size_coefficient <- 2.84\n\nlot_size_increase <- (home_size_coefficient * home_size_increase) / lot_size_coefficient\ncat(\"C. Lot size increase needed to have the same impact as a one-square-foot increase in home size:\", lot_size_increase, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nC. Lot size increase needed to have the same impact as a one-square-foot increase in home size: 18.94366 \n```\n:::\n:::\n\n# Question 2\n\n## A\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(alr4)\ndata(salary)\n\nt_test <- t.test(salary ~ sex, data = salary)\nt_test\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  salary by sex\nt = 1.7744, df = 21.591, p-value = 0.09009\nalternative hypothesis: true difference in means between group Male and group Female is not equal to 0\n95 percent confidence interval:\n -567.8539 7247.1471\nsample estimates:\n  mean in group Male mean in group Female \n            24696.79             21357.14 \n```\n:::\n:::\n\nIrrespective of educational qualifications or employment hierarchy, the mean salary for men is $24,696.79, while the average income for women is $21,357.14, reflecting a difference of $3,339.65 between the two genders.\n\n## B\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(salary ~ ., data = salary)\nconf_int <- confint(model, level = 0.95)\nconf_int\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\nBased on a multiple linear regression analysis with a 95% confidence level, the estimated pay gap between men and women ranges from -$697.82 to $3,030.57\n\n## C\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nIn summary, there are several factors that impact wage increases, including a person's educational qualifications and job rank. Specifically, individuals with a PhD experience an average wage increase of $1,388.61, while those in the rank of Associate Professor receive an increase of $5,292.36, and full/tenured Professors experience the highest increase of $11,118.75. Gender also plays a role, with females receiving a wage increase of $1,166.37. Additionally, for each year an individual remains at their current rank, they receive an increase of $476.31, except for individuals who have reached their maximum degree/rank level, as their salary decreases by $124.57 for each year after that. Notably, all slopes, except for the one related to maximum degree/rank level, are positive. The individual's rank and the number of years spent at their current rank are both statistically significant, with p-values less than 0.05.\n\n## D\n\n::: {.cell}\n\n```{.r .cell-code}\n# Change the baseline category for rank and rerun the model\nsalary$rank <- relevel(salary$rank, ref = \"Asst\")\nmodel2 <- lm(salary ~ ., data = salary)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThere have been no changes to the values previously stated. Therefore, the wage increases and other factors mentioned in the previous statement remain the same.\n\n## E\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exclude the rank variable and rerun the model\nmodel3 <- lm(salary ~ degree + sex + year + ysdeg, data = salary)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\nWhen the 'rank' variable is removed from the equation, the salary decrease is $3,299.35 for individuals with a PhD and $1,286.54 for females. On the other hand, salary gains occur at a rate of $351.97 for each year spent at the current level and $339.40 for each year after obtaining the highest degree. It is worth noting that half of the slopes are positive, while the other half are negative. Specifically, 'degreePhD', 'year', and 'ysdeg' are all statistically significant with p-values less than 0.05, while 'sexFemale' is not.\n\n## F\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a new variable and run the multiple regression model\nsalary$new_dean <- ifelse(salary$ysdeg <= 15, \"New\", \"Old\")\nmodel4 <- lm(salary ~ degree + sex + new_dean + year*ysdeg, data = salary)\nsummary(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + new_dean + year * ysdeg, \n    data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8396.1 -2171.9  -352.5  2053.3 11061.3 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 16855.764   1508.902  11.171 1.45e-14 ***\ndegreePhD   -3205.140   1431.791  -2.239   0.0302 *  \nsexFemale   -1222.794   1345.288  -0.909   0.3682    \nnew_deanOld   550.409   2119.912   0.260   0.7963    \nyear          462.292    277.040   1.669   0.1021    \nysdeg         332.120    141.753   2.343   0.0236 *  \nyear:ysdeg     -4.525     10.083  -0.449   0.6557    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3814 on 45 degrees of freedom\nMultiple R-squared:  0.6334,\tAdjusted R-squared:  0.5845 \nF-statistic: 12.96 on 6 and 45 DF,  p-value: 1.902e-08\n```\n:::\n:::\n\nIt is highly likely that there is a strong correlation between 'year' and 'ysdeg'. \n\n# QUESTION 3\n\n## A\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(smss)\ndata(house.selling.price)\n\nmodel <- lm(Price ~ Size + New, data = house.selling.price)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nWhen controlling for size, the predictor variables 'New' and 'Size' have p-values of 0.00257 and 2e-16, respectively. Both of these p-values are statistically significant and less than the alpha level of 0.05. This indicates that the null hypothesis can be rejected, and there is likely a relationship between 'New' and 'Price', as well as between 'Size' and 'Price' for new homes. By computing the correlation coefficient, we can observe that the correlation between 'New' and 'Size' is 0.3843, indicating a weak relationship between the two variables.\n\n::: {.cell}\n\n```{.r .cell-code}\ncoefficients <- coef(model)\ncoefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)        Size         New \n-40230.8668    116.1316  57736.2828 \n```\n:::\n:::\n\n## C\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the predicted selling price\nsize <- 3000\nnew <- 1\nnot_new <- 0\n\npredicted_new <- coefficients[1] + coefficients[2] * size + coefficients[3] * new\npredicted_not_new <- coefficients[1] + coefficients[2] * size + coefficients[3] * not_new\n\npredicted_new\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   365900.2 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted_not_new\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   308163.9 \n```\n:::\n:::\n\nif a house is new, the estimated selling price is $365,900.20. However, if the house is not new, the predicted selling price is $308,163.90.\n\n## D\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_interaction <- lm(Price ~ Size * New, data = house.selling.price)\nsummary(model_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n## E\n\n::: {.cell}\n\n```{.r .cell-code}\ncoefficients_interaction <- coef(model_interaction)\ncoefficients_interaction\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n (Intercept)         Size          New     Size:New \n-22227.80793    104.43839 -78527.50235     61.91588 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(data=house.selling.price,aes(x=Size,y=Price, color=New))+\n  geom_point()+\n  geom_smooth(method=\"lm\",se=F)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The following aesthetics were dropped during statistical transformation: colour\nℹ This can happen when ggplot fails to infer the correct grouping structure in\n  the data.\nℹ Did you forget to specify a `group` aesthetic or to convert a numerical\n  variable into a factor?\n```\n:::\n\n::: {.cell-output-display}\n![](Hw5_thrishul_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\nThe scatterplot shows a linear/correlative relationship between the variables, where an increase in size is associated with an increase in price. However, when considering the colors of the dots (which represent the age of the homes), the relationship is not as straightforward. The new houses (light blue dots) are dispersed throughout the graph, mostly along the slope line. On the other hand, the older residences (dots that are not light blue) are mainly clustered in the bottom-right corner of the graph, although there are a few that have a higher price/size than brand new homes.\n\n## F\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the predicted selling price with interaction\npredicted_new_interaction <- coefficients_interaction[1] + coefficients_interaction[2] * size + coefficients_interaction[3] * new + coefficients_interaction[4] * size * new\npredicted_not_new_interaction <- coefficients_interaction[1] + coefficients_interaction[2] * size + coefficients_interaction[3] * not_new + coefficients_interaction[4] * size * not_new\n\npredicted_new_interaction\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   398307.5 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted_not_new_interaction\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   291087.4 \n```\n:::\n:::\n\nAccording to the given data, for a house with the specified measurements, the predicted selling price for a new home is $398,307.50, while for a not-new home, it is $291,087.40.\n\n## G\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the predicted selling price for a home of 1500 square feet\nsize_1500 <- 1500\n\npredicted_new_1500 <- coefficients_interaction[1] + coefficients_interaction[2] * size_1500 + coefficients_interaction[3] * new + coefficients_interaction[4] * size_1500 * new\npredicted_not_new_1500 <- coefficients_interaction[1] + coefficients_interaction[2] * size_1500 + coefficients_interaction[3] * not_new + coefficients_interaction[4] * size_1500 * not_new\n\npredicted_new_1500\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   148776.1 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted_not_new_1500\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   134429.8 \n```\n:::\n:::\n\nThe predicted selling price of a new 1500sqft home is $148,776.10, while the predicted selling price of a 1500sqft home that is not new is $134,429.80. These values are significantly lower than the expected selling prices in Part F, where the property size is doubled to 3000sqft. A new 3000sqft house is expected to sell for $398,307.50, while a new 1500sqft house is expected to sell for $148,694.70. The reduction in size and price by half shows a linear connection between the two variables.\n\nIn comparison to new dwellings, the price of not-new dwellings is more directly proportional to size. A 3000sqft house that is not new is expected to sell for $291,087.40, while a 1500sqft house that is not new is expected to sell for $134,429.80. The price difference between these two values is $156,657.6. Therefore, size has a more significant impact on the selling price of not-new homes than new ones.\n\n## H\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare the adjusted R-squared values\nsummary(model)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7168767\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_interaction)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7363181\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare residuals' distribution\npar(mfrow = c(2, 1))\nhist(residuals(model), main = \"Residuals without Interaction\", xlab = \"Residuals\", col = \"darkmagenta\")\nhist(residuals(model_interaction), main = \"Residuals with Interaction\", xlab = \"Residuals\", col = \"darkmagenta\")\n```\n\n::: {.cell-output-display}\n![](Hw5_thrishul_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\nI think that a model without an interaction term provides a better fit for the relationship between ‘Size’ and ‘New’ regarding the outcome variable price. On the other hand, the model with the interaction term better captures the relationship between ‘Size’ and ‘Price’ rather than ‘Size’ and ‘New’.\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "Hw5_thrishul_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}