{
  "hash": "07bfff3e3d0f6f9bbbd47b5b2e821418",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Alexa Potter\"\ndescription: \"DACSS 603\"\ndate: \"03/25/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n-- Attaching packages --------------------------------------- tidyverse 1.3.2 --\nv ggplot2 3.4.0      v purrr   0.3.5 \nv tibble  3.1.8      v dplyr   1.0.10\nv tidyr   1.2.1      v stringr 1.5.0 \nv readr   2.1.3      v forcats 0.5.2 \n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\n```\n:::\n:::\n\n\n\n# Question 1\n\nThe time between the date a patient was recommended for heart surgery and the surgery date  for cardiac patients in Ontario was collected by the Cardiac Care Network (“Wait Times Data  Guide,” Ministry of Health and Long-Term Care, Ontario, Canada, 2006). The sample mean  and sample standard deviation for wait times (in days) of patients for two cardiac procedures  are given in the accompanying table. Assume that the sample is representative of the Ontario  population \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurgical_procedure <- c('Bypass', 'Angiography')\nsample_size <- c(539,847)\nmean_wait_time <- c(19,18)\nstandard_deviation <- c(10,9)\n\nheart_surgery_df <- data.frame(surgical_procedure, sample_size, mean_wait_time, standard_deviation)\n\nprint(heart_surgery_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  surgical_procedure sample_size mean_wait_time standard_deviation\n1             Bypass         539             19                 10\n2        Angiography         847             18                  9\n```\n:::\n:::\n\n\nConstruct the 90% confidence interval to estimate the actual mean wait time for each of the two  procedures. Is the confidence interval narrower for angiography or bypass surgery? \n\nFirst we need to determine the standard error for procedure. \n\n::: {.cell}\n\n```{.r .cell-code}\nse_bypass <- 10/ sqrt(539)\nse_angiography <- 9 / sqrt(847)\n```\n:::\n\n\nThen we need to set the confidence interval.\n\n::: {.cell}\n\n```{.r .cell-code}\nconfidence_level <- 0.90\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntail_area <- (1-confidence_level)/2\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt_score_bypass <- qt(p = 1-tail_area, df = 539-1)\nt_score_angiography <- qt(p = 1-tail_area, df = 847-1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nCI_bypass <- c(19 - t_score_bypass * se_bypass,\n       19 + t_score_bypass * se_bypass)\nprint(CI_bypass)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n\n```{.r .cell-code}\nCI_angiography <- c(18 - t_score_angiography * se_angiography,\n        18 + t_score_angiography * se_angiography)\nprint(CI_angiography)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n:::\n\nThe confidence interval for angiography is more narrow compared to the bypass confidence interval.\n\n\n\n# Question 2  \n\n A survey of 1031 adult Americans was carried out by the National Center for Public  Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567  believed that college education is essential for success. Find the point estimate, p, of the  proportion of all adult Americans who believe that a college education is essential for success.  Construct and interpret a 95% confidence interval for p. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(567, 1031, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  567 out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\nThe prop.test shows that 95% of confidence intervals calculated would reflect the true percent of adult Americans that believe college education is essential for success is between 51.89682%-58.05580%.\n\n# Question 3  \n\nSuppose that the financial aid office of UMass Amherst seeks to estimate the mean cost  of textbooks per semester for students. The estimate will be useful if it is within $5 of the true  population mean (i.e. they want the confidence interval to have a length of $10 or less). The  financial aid office is pretty sure that the amount spent on books varies widely, with most values  between $30 and $200. They think that the population standard deviation is about a quarter of  this range (in other words, you can assume they know the population standard deviation). \nAssuming the significance level to be 5%, what should be the size of the sample \n\n\nFormula: n = ((z-score * sigma)/ME)^2\n\nz-score for significance level 5% (95% confidence level) = 1.96\nsigma (SD)= (200-30)/4\nME = 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\n((1.96 * ((200-30)/4))/5)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\n\n\n\n# Question 4  \n\nAccording to a union agreement, the mean income for all senior-level workers in a large  service company equals $500 per week. A representative of a women’s group decides to analyze  whether the mean income μ for female employees matches this norm. For a random sample of  nine female employees, ȳ = $410 and s = 90   \n\n## A. Test whether the mean income of female employees differs from $500 per week. Include  assumptions, hypotheses, test statistic, and P-value. Interpret the result. \n\nHypothesis: \nH0: μ = 500\nHA: μ ≠ 500\n\nAssumptions: \n- The data is collected from a representative & randomly selected portion of the total population.\n-  The data is a normal distribution \n- The two groups have the same population variance (homoskedasticity)\n\nFormula for t-test:\nt = (X‾ - μ0) / (s / √n)\nX‾ = 410\nμ0 = 500\ns = 90\nn = 9\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_stat <- (410 - 500) / (90 / sqrt(9))\nt_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\np-value:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2*pt(q=t_stat, df=8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\nSince the p-value is less than 0.05 we can reject the null hypothesis at significance level 0.05. \n\n\n## B. Report the P-value for Ha: μ < 500. Interpret.   \n\n\n::: {.cell}\n\n```{.r .cell-code}\npt(q= t_stat, df=8, lower.tail=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\nSince the p value is less than 0.05 we can reject the null hypothesis at 0.05 significance level. \n\n\n## C. Report and interpret the P-value for Ha: μ > 500.   \n(Hint: The P-values for the two possible one-sided tests must sum to 1.)  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt(q= t_stat, df=8, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\nSince the p value is greater than 0.05 we fail to reject the null hypothesis at 0.05 significance level.\n\n\n# Question 5  \n\nJones and Smith separately conduct studies to test H0: μ = 500 against Ha: μ ≠ 500, each  with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7, with se = 10.0.   \n\n\n## A. Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049  for Smith. \n\nJones  \nt = (ȳ - μ)/se  \n\n\n::: {.cell}\n\n```{.r .cell-code}\njones_t <- (519.5-500)/10\nprint(jones_t)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\n#p-value:\n2*pt(-abs(jones_t),df=1000-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\n\nSmith  \nt = (ȳ - μ)/se  \n\n::: {.cell}\n\n```{.r .cell-code}\nsmith_t <- (519.7-500)/10\nprint(smith_t)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n#p-value:\n2*pt(-abs(smith_t),df=1000-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n\n## B. Using α = 0.05, for each study indicate whether the result is “statistically significant.”   \n\nThe result is statistically significant when the p-value is less than or equal to the alpha level. \n\nAt α = 0.05, Jones' p-value of 0.051 is not statistically significant. \nAt α = 0.05, Smith's p-value of 0.049 is statistically significant. \n\n\n## C. Using this example, explain the misleading aspects of reporting the result of a test as “P ≤  0.05” versus “P > 0.05,” or as “reject H0” versus “Do not reject H0,” without reporting the actual  P-value.   \n\nUsing “P ≤  0.05” versus “P > 0.05,” can leave a gap in the understanding of the full analysis. While one value is statistically significant, these two are extremely close. It's important to state at what value you reject or fail to reject the null hypothesis, because both of these would not be statistically significant at α = 0.01. \n\n# Question 6  \n\nA school nurse wants to determine whether age is a factor in whether children choose a  healthy snack after school. She conducts a survey of 300 middle school students, with the results  below. Test at α = 0.05 the claim that the proportion who choose a healthy snack differs by grade  level. What is the null hypothesis? Which test should we use? What is the conclusion? \n\n::: {.cell}\n\n```{.r .cell-code}\n#grade_level <- c('6th', '7th', '8th')\n#healthy_snack <- c(31,43,51)\n#unhealth_snack <- c(69,57,49)\n\n\nmiddleschool_df <- c(31, 43, 51, 69, 57, 49)\n\n\nmiddleschool_df <- matrix(middleschool_df, nrow=2, ncol = 3, byrow = TRUE)\ncolnames(middleschool_df) <- c(\"6th\", \"7th\", \"8th\") \nrownames(middleschool_df) <- c(\"health_snack\", \"unhealth_snack\")\n\nprint(middleschool_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               6th 7th 8th\nhealth_snack    31  43  51\nunhealth_snack  69  57  49\n```\n:::\n:::\n\n\nFor this analysis we would use the X^2 test as it determines is there is an association between categorical variables. The null hypothesis is that variable 1 is independent of variable 2. In this analysis it would mean that choosing a healthy snack is independent of grade level.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(middleschool_df, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  middleschool_df\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\nWith a p-value of 0.015 and alpha level of 0.05, we can reject the null hypothesis. We can conclude at a significance level of 0.05 the association between grade level and choosing a healthy snack are statistically significant. \n\n \n# Question 7  \n\nPer-pupil costs (in thousands of dollars) for cyber charter school tuition for school  districts in three areas are shown. Test the claim that there is a difference in means for the three  areas, using an appropriate test. What is the null hypothesis? Which test should we use? What is  the conclusion?\n\n::: {.cell}\n\n```{.r .cell-code}\nArea_1 <- c(6.2,9.3,6.8,6.1,6.7,7.5)\nArea_2 <- c(7.5,8.2,8.5,8.2,7.0,9.3)\nArea_3 <- c(5.8,6.4,5.6,7.1,3.0,3.5)\n\n\ncyberschool_df <- data.frame(Area_1, Area_2, Area_3)\ncyberschool_anova_df <- pivot_longer(cyberschool_df, c(Area_1, Area_2, Area_3), names_to = \"Area\") %>%\n                      rename(\"Tuition\" = \"value\")\n\nprint(cyberschool_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Area_1 Area_2 Area_3\n1    6.2    7.5    5.8\n2    9.3    8.2    6.4\n3    6.8    8.5    5.6\n4    6.1    8.2    7.1\n5    6.7    7.0    3.0\n6    7.5    9.3    3.5\n```\n:::\n\n```{.r .cell-code}\nprint(cyberschool_anova_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 18 x 2\n   Area   Tuition\n   <chr>    <dbl>\n 1 Area_1     6.2\n 2 Area_2     7.5\n 3 Area_3     5.8\n 4 Area_1     9.3\n 5 Area_2     8.2\n 6 Area_3     6.4\n 7 Area_1     6.8\n 8 Area_2     8.5\n 9 Area_3     5.6\n10 Area_1     6.1\n11 Area_2     8.2\n12 Area_3     7.1\n13 Area_1     6.7\n14 Area_2     7  \n15 Area_3     3  \n16 Area_1     7.5\n17 Area_2     9.3\n18 Area_3     3.5\n```\n:::\n:::\n\n\n\nThe statistical test to use for this data set is an ANOVA as it is comparing the mean of two or more independent groups.\n\nThe null hypothesis is that there is no difference in mean across variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_cyberschool <- aov(Tuition ~ Area, data = cyberschool_anova_df)\nsummary(anova_cyberschool)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \nArea         2  25.66  12.832   8.176 0.00397 **\nResiduals   15  23.54   1.569                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThe P value is 0.00397. This means we can reject the null hypothesis at 0.01. The conclusion we can draw is that there is at least one mean that is different. \n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}