{
  "hash": "b8283ba50a8a506d743b604c323871e1",
  "result": {
    "markdown": "---\ntitle: \"Final Project Paper Write Up\"\nauthor: \"Emma Narkewicz\"\ndescription: \"Emma Narkewicz Project Write Up\"\ndate: \"05/25/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - emma_narkewicz\n  - final\n  - poster\n  - Burnout\n  - Medical_students\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(sjPlot)\nlibrary(sjmisc)\nlibrary(stargazer)\nlibrary(broom)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(GGally)\nlibrary(wesanderson)\nlibrary(viridis)\nlibrary(lmtest)\nlibrary(zoo)\n\n\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Research Question\n\nFor my final project I will expand on research on the mental health, empathy, and burnout of medical school students using a data set of 886 medical students in Switzerland. The COVID-19 pandemic heightened the mental health challenges of health care workers around the world (Teisman et al., 2021). Numerous studies show that health care workers are prone to compassion fatigue due to working long hours in stressful work environments with continuous exposure to trauma (Jennings, 2009; Rodriguez & Carlotta, 2017; Peters, 2018; Yayha et al., 2021; Carrard et al., 2022; Shin et al., 2022).\n\nThe Association of American Medical Colleges (AAMC) found that 30% of surveyed medical students and residents met the criteria for depression and 10% reported having suicidal thoughts (Pasturel, 2020). Previous studies conducted on samples of health care workers in Switzerland, Iraq, and South Korea examined the impact of gender on burnout, finding that female medical students had higher rates of empathy and burnout than male coworkers (Carrard et al., 2022; Yahya et al., 2021; Shin et al., 2022). A 2009 multi-site study of medical students in the U.S. found statistically significant differences in depression by gender but not by ethnicity (Goebert et al., 2009). In contrast, the same study found statistically significant differences in suicidal ideation by ethnicity, but not by gender, with Black students reporting the highest rates of suicidal ideation & Caucasian students reporting the lowest rates of suicidal ideation (Goebert et al., 2009).\n\n*Research Question: Why are some medical students more likely to experience burnout than others?*\n\n## Hypothesis Testing\n\nI want to explore further how ethnic identity might serve as a protective or risk factor for the burnout of medical students, specifically for international medical students. A 2022 study of medical school students in Croatia found that international medical students experience higher rates of burnout mediated by social and familial loneliness (Gradiski et al., 2022). For my final project I will test whether or not a student's first language being a native language of Switzerland -- where the sample was taken -- impacts their burnout. The commonly spoken languages in Switzerland are the national languages of French, German, & Italian & widespread spoken English (Kużelewska, 2016).\n\n*Hypothesis: Medical students whose native language is a commonly spoken in the country where they are studying will experience lower rates of burnout than medical students with other native languages.*\n\nThe reasoning behind my hypothesis is if a medical student's native language is one of the national language of Switzerland, they will have benefit from potential protective factors of social, cultural, and familial connections. In contrast, I expect medical students whose native language is not German, French, Italian, or English to be at higher risk for burnout mediated through increased stress from coping with different culture, language, and physical separation from their family.\n\n## Descriptive Statistics\n\nThe data set I will be analyzing contains demographic information on 886 medical students in Switzerland. Students answered demographic information about their age, gender, their year in school and well as the results of self-reported empathy, depression, anxiety, and burnout. The data set was downloaded from Kaggle at https://www.kaggle.com/datasets/thedevastator/medical-student-mental-health?select=Codebook+Carrard+et+al.+2022+MedTeach.csv but originally sourced for a 2022 ,publication in the Medical Teacher Journal by Carrard et al.\n\nImportant variables I want to explore in my data set as potential risk and protective factors:\n\n-   Native Language\n-   Age\n-   Gender\n-   Having a romantic partner\n-   Seeing a psychotherapist\n-   Hours spent studying\n-   Having a job\n-   Jefferson Scale Empathy (JSPE) total empathy score\n-   Questionnaire of Cognitive and Affective Empathy (QCAE) Cognitive empathy score\n-   Questionnaire of Cognitive and Affective Empathy QCAE Affective empathy score\n-   Center for Epidemiologic Studies Depression Scale (CES-D) total score\n-   State & Trait Anxiety (STAI) score\n-   Maslach Burnout Inventory (MBI) Emotional Exhaustion\n-   Maslach Burnout Inventory (MBI) Cynicism\n-   Maslach Burnout Inventory (MBI) Academic Efficacy\n\nEach of the various empathy, mental health, and burnout scales are scored differently, so care needs to be taken in interpreting these findings. For example, a higher score on the emotional exhaustion and cynicism scales of the MBI indicate higher burn out, while a higher score on the MBI personal achievement indicates lower levels of burnout (Maslach et al., 1996).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Readin Final data set\n\nFinalDataSet <- read_csv(\"_data/med_student_burnout.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 886 Columns: 20\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (20): id, age, year, sex, glang, part, job, stud_h, health, psyt, jspe, ...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nFinalDataSet\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 886 × 20\n      id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n 1     2    18     1     1   120     1     0     56      3     0    88       62\n 2     4    26     4     1     1     1     0     20      4     0   109       55\n 3     9    21     3     2     1     0     0     36      3     0   106       64\n 4    10    21     2     2     1     0     1     51      5     0   101       52\n 5    13    21     3     1     1     1     0     22      4     0   102       58\n 6    14    26     5     2     1     1     1     10      2     0   102       48\n 7    17    23     5     2     1     1     0     15      3     0   117       58\n 8    21    23     4     1     1     1     1      8      4     0   118       65\n 9    23    23     4     2     1     1     1     20      2     0   118       69\n10    24    22     2     2     1     1     0     20      5     0   108       56\n# … with 876 more rows, and 8 more variables: qcae_aff <dbl>, amsp <dbl>,\n#   erec_mean <dbl>, cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>,\n#   mbi_ea <dbl>\n```\n:::\n:::\n\n\nPrior to examining the descriptive statistics from the med school data set I recoded qualitative variables stored as numeric values, using the Carrard et al., 2022 code book, replacing 0, 1 with clear demographic information about age, gender, having a partner etc. The explanatory variable NatLang which collapses down into if medical students native language is German, French, or Italian (NatSpeaker) or not (NotNatSpeaker).\n\nFrom the Carrard et al., 2022 code book:\n\n-   Gender\n\n    -   Male = 1\n    -   Female = 2\n    -   Non-binary = 3\n\n-   Partner\n\n    -   Single = 0\n    -   Partnered = 1\n\n-   Job\n\n    -   No = 0\n    -   Yes = 1\n\n-   Therapist in Past 12 months\n\n    -   No = 0\n    -   Yes = 1\n\n-   Health Satisfaction\n\n    -   very dissatisfied = 1\n    -   dissatisfied = 2\n    -   neutral = 3\n    -   satisfied = 4\n    -   very satisfied = 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(FinalDataSet)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 20\n     id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n1     2    18     1     1   120     1     0     56      3     0    88       62\n2     4    26     4     1     1     1     0     20      4     0   109       55\n3     9    21     3     2     1     0     0     36      3     0   106       64\n4    10    21     2     2     1     0     1     51      5     0   101       52\n5    13    21     3     1     1     1     0     22      4     0   102       58\n6    14    26     5     2     1     1     1     10      2     0   102       48\n# … with 8 more variables: qcae_aff <dbl>, amsp <dbl>, erec_mean <dbl>,\n#   cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>, mbi_ea <dbl>\n```\n:::\n\n```{.r .cell-code}\n#Recoding categorical variables based on code book\nFinalRecoded <- FinalDataSet %>%\n mutate(NatLang = case_when(\n    glang == 1 | glang == 15 | glang == 20 | glang == 90 ~ 1,\n    glang > 1 & glang < 15 | glang > 15 & glang < 20 |glang > 20 & glang <90 | glang > 90 ~ 0)\n  ) \n  \ntable(select(FinalRecoded, NatLang))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNatLang\n  0   1 \n 71 815 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Descriptive statistics for quantitative variables\nsummary(FinalRecoded)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       id              age             year            sex       \n Min.   :   2.0   Min.   :17.00   Min.   :1.000   Min.   :1.000  \n 1st Qu.: 447.5   1st Qu.:20.00   1st Qu.:1.000   1st Qu.:1.000  \n Median : 876.0   Median :22.00   Median :3.000   Median :2.000  \n Mean   : 889.7   Mean   :22.38   Mean   :3.103   Mean   :1.695  \n 3rd Qu.:1341.8   3rd Qu.:24.00   3rd Qu.:5.000   3rd Qu.:2.000  \n Max.   :1790.0   Max.   :49.00   Max.   :6.000   Max.   :3.000  \n     glang             part             job             stud_h     \n Min.   :  1.00   Min.   :0.0000   Min.   :0.0000   Min.   : 0.00  \n 1st Qu.:  1.00   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:12.00  \n Median :  1.00   Median :1.0000   Median :0.0000   Median :25.00  \n Mean   : 14.33   Mean   :0.5632   Mean   :0.3488   Mean   :25.29  \n 3rd Qu.:  1.00   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:36.00  \n Max.   :121.00   Max.   :1.0000   Max.   :1.0000   Max.   :70.00  \n     health           psyt             jspe          qcae_cog    \n Min.   :1.000   Min.   :0.0000   Min.   : 67.0   Min.   :37.00  \n 1st Qu.:3.000   1st Qu.:0.0000   1st Qu.:101.0   1st Qu.:54.00  \n Median :4.000   Median :0.0000   Median :107.0   Median :58.00  \n Mean   :3.778   Mean   :0.2246   Mean   :106.4   Mean   :58.53  \n 3rd Qu.:5.000   3rd Qu.:0.0000   3rd Qu.:113.0   3rd Qu.:63.00  \n Max.   :5.000   Max.   :1.0000   Max.   :125.0   Max.   :76.00  \n    qcae_aff          amsp         erec_mean           cesd      \n Min.   :18.00   Min.   : 6.00   Min.   :0.3571   Min.   : 0.00  \n 1st Qu.:31.00   1st Qu.:20.00   1st Qu.:0.6667   1st Qu.: 9.00  \n Median :35.00   Median :23.00   Median :0.7262   Median :16.00  \n Mean   :34.78   Mean   :23.15   Mean   :0.7201   Mean   :18.05  \n 3rd Qu.:39.00   3rd Qu.:26.75   3rd Qu.:0.7857   3rd Qu.:25.00  \n Max.   :48.00   Max.   :35.00   Max.   :0.9524   Max.   :56.00  \n     stai_t         mbi_ex          mbi_cy          mbi_ea     \n Min.   :20.0   Min.   : 5.00   Min.   : 4.00   Min.   :10.00  \n 1st Qu.:34.0   1st Qu.:13.00   1st Qu.: 6.00   1st Qu.:21.00  \n Median :43.0   Median :17.00   Median : 9.00   Median :24.00  \n Mean   :42.9   Mean   :16.88   Mean   :10.08   Mean   :24.21  \n 3rd Qu.:51.0   3rd Qu.:20.00   3rd Qu.:13.00   3rd Qu.:28.00  \n Max.   :77.0   Max.   :30.00   Max.   :24.00   Max.   :36.00  \n    NatLang      \n Min.   :0.0000  \n 1st Qu.:1.0000  \n Median :1.0000  \n Mean   :0.9199  \n 3rd Qu.:1.0000  \n Max.   :1.0000  \n```\n:::\n:::\n\n\nNote that id is not a true numeric variable and therefor the descriptive statistics for it should be disregarded.\n\nMedical students in the sample studied for an average of 25 hours a week, with a maximum of 70 hours.\n\nScores on the Jefferson Scale of Physician Empathy (JSPE) range from 20-140 with a higher score indicating higher empathy. The mean JSPE score in the sample was was 106.2 and the median JSPE score was 107.0 indicating relatively high empathy. There was a broad range from as low to 67-125, with the IQR indicating most medical students scored in the low 100s range.\n\nThere were are scores for all 3 components of MBI burnout: emotional exhaustion, cynicism, and personal achievement.\n\n-   On the mbi-ex, medical school students' scores ranged from 5-30, with a median score of 17 and a mean score of 16.88. According to the MBI score guide, half of medical students in the sample exhibit low-level burnout (scoring 17 or less), and the other half exhibiting moderate burnout in terms of emotional exhaustion.\n\n-   On the mbi-cyn, medical students' scores ranged from 4-24, with a median of 9 and mean of 10.08. According to the scoring guide, the majority of the sample exhibit moderate burnout (6-11) with some exhibiting high level burnout (12+) in the dimension of cynicism.\n\n-   On the mbi-ea, medical students scores ranged from 10-36, with a median score of 24 and a mean score of 24.01. A score of 33 or less indicates high level of burnout and a score between 24-39 indicates moderate level burnout, with medical students falling in the high and moderate burnout range for personal achievement.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Creating character variables to generate props\n\nFinalProp <- FinalRecoded %>%\nmutate(nat = case_when (\n  NatLang == 0 ~ \"Non Native\",\n  NatLang == 1 ~  \"Native\")\n        )%>%\nmutate(gender = case_when(\n         sex == 1  ~ \"Male\",\n         sex == 2 ~ \"Female\", \n         sex == 3 ~ \"Non-Binary\")\n        ) %>%\n  relocate(`gender`, .before = `age`)%>%\n  select(!contains(\"sex\")) %>%\nmutate(partner = case_when(\n         part == 1 ~ \"partnered\",\n         part == 0  ~ \"single\")\n      )%>%\n  relocate(`partner`, .before = `age`)%>%\n  select(!\"part\") %>%\nmutate(paid_job = case_when(\n         job == 0  ~ \"no_job\",\n         job == 1 ~ \"yes_job\")\n        ) %>%\n  relocate(`paid_job`, .before = `age`)%>%\n  select(!\"job\") %>%\nmutate(health_sat = case_when(\n         health == 1  ~ \"very_dis\",\n         health == 2 ~ \"dis\",\n         health == 3 ~ \"neutral\",\n         health == 4 ~ \"sat\",\n         health  == 5 ~ \"very sat\")\n) %>%\n  relocate(`health_sat`, .before = `age`)%>%\n  select(!\"health\") %>%\nmutate(MHcare = case_when(\n         psyt == 0  ~ \"no_ther\",\n         psyt == 1 ~ \"yes_ther\")\n        ) %>%\nrelocate(`MHcare`, .before = `age`)%>%\n  select(!\"psyt\") \n\nFinalProp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 886 × 22\n      id gender partner   paid_job healt…¹ MHcare   age  year glang stud_h  jspe\n   <dbl> <chr>  <chr>     <chr>    <chr>   <chr>  <dbl> <dbl> <dbl>  <dbl> <dbl>\n 1     2 Male   partnered no_job   neutral no_th…    18     1   120     56    88\n 2     4 Male   partnered no_job   sat     no_th…    26     4     1     20   109\n 3     9 Female single    no_job   neutral no_th…    21     3     1     36   106\n 4    10 Female single    yes_job  very s… no_th…    21     2     1     51   101\n 5    13 Male   partnered no_job   sat     no_th…    21     3     1     22   102\n 6    14 Female partnered yes_job  dis     no_th…    26     5     1     10   102\n 7    17 Female partnered no_job   neutral no_th…    23     5     1     15   117\n 8    21 Male   partnered yes_job  sat     no_th…    23     4     1      8   118\n 9    23 Female partnered yes_job  dis     no_th…    23     4     1     20   118\n10    24 Female partnered no_job   very s… no_th…    22     2     1     20   108\n# … with 876 more rows, 11 more variables: qcae_cog <dbl>, qcae_aff <dbl>,\n#   amsp <dbl>, erec_mean <dbl>, cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>,\n#   mbi_cy <dbl>, mbi_ea <dbl>, NatLang <dbl>, nat <chr>, and abbreviated\n#   variable name ¹​health_sat\n```\n:::\n\n```{.r .cell-code}\n#Frequency of categorical & ordinal variables\n prop.table(table(select(FinalProp, nat)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnat\n    Native Non Native \n0.91986456 0.08013544 \n```\n:::\n\n```{.r .cell-code}\n prop.table(table(select(FinalProp, gender)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngender\n     Female        Male  Non-Binary \n0.683972912 0.310383747 0.005643341 \n```\n:::\n\n```{.r .cell-code}\n prop.table(table(select(FinalProp, partner)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npartner\npartnered    single \n0.5632054 0.4367946 \n```\n:::\n\n```{.r .cell-code}\n prop.table(table(select(FinalProp, paid_job)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npaid_job\n   no_job   yes_job \n0.6512415 0.3487585 \n```\n:::\n\n```{.r .cell-code}\n prop.table(table(select(FinalProp, health_sat)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nhealth_sat\n       dis    neutral        sat   very sat   very_dis \n0.09819413 0.15349887 0.45372460 0.25282167 0.04176072 \n```\n:::\n\n```{.r .cell-code}\n prop.table(table(select(FinalProp, MHcare)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMHcare\n no_ther yes_ther \n0.775395 0.224605 \n```\n:::\n\n```{.r .cell-code}\n table(select(FinalProp, nat))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnat\n    Native Non Native \n       815         71 \n```\n:::\n:::\n\n\nFrom the proportion tables above it can be seen that majority (90%) of the sample speaks one of the native languages of Switzerland, while only 10% are non native speakers. The sample is also mostly female (68%), with less than 1% identifying as non-binary. Over half (56%) of the medical students reported having partners, but only about a third of medical students had a paid job (34.9%). The most common (45%) report from medical students was that they were satisfied with their health and less than one quarter (22.5%) of medical student reported seeing a therapist in the last 12 months.\n\nLooking at the gender prop.table, less than 1% of medical students were non-binary. Looking at counts that is only 5 students out of nearly 1000. From an equity standpoint it is great to include diverse gender identities, but for the purposes of analysis & linear regression, there are non non-binary students to meaningfully include in an analysis of gender. Therefor I removed the 5 students who identified as non-binary before conducting analysis. Additionally I recoded the gender dummy variables from 1 & 2 to 0 & 1 for male and female respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Counts genders\n (table(select(FinalProp, gender)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngender\n    Female       Male Non-Binary \n       606        275          5 \n```\n:::\n\n```{.r .cell-code}\n#remove non-binary dummy gender & recode \n\nFinalRecoded2 <- FinalRecoded %>%\n  filter(!str_detect(sex, \"3\")) %>%\n  mutate(gender = case_when(\n         sex == 1  ~ 0,\n         sex == 2 ~  1)\n        ) \n  \n#remove non-binary categorical\nFinalProp2 <- FinalProp %>%\n  filter(!str_detect(gender, \"Non-Binary\")) \n\nFinalRecoded2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 881 × 22\n      id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n 1     2    18     1     1   120     1     0     56      3     0    88       62\n 2     4    26     4     1     1     1     0     20      4     0   109       55\n 3     9    21     3     2     1     0     0     36      3     0   106       64\n 4    10    21     2     2     1     0     1     51      5     0   101       52\n 5    13    21     3     1     1     1     0     22      4     0   102       58\n 6    14    26     5     2     1     1     1     10      2     0   102       48\n 7    17    23     5     2     1     1     0     15      3     0   117       58\n 8    21    23     4     1     1     1     1      8      4     0   118       65\n 9    23    23     4     2     1     1     1     20      2     0   118       69\n10    24    22     2     2     1     1     0     20      5     0   108       56\n# … with 871 more rows, and 10 more variables: qcae_aff <dbl>, amsp <dbl>,\n#   erec_mean <dbl>, cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>,\n#   mbi_ea <dbl>, NatLang <dbl>, gender <dbl>\n```\n:::\n:::\n\n\nUsing proportions & tables, I generated Table 1 below for my poster to provide further demographic information broken down by Native Language & Non-Native Language Status. Table 1 shows that the majority of the medical students in the sample speak a native language of Switzerland (89.5%) & are female (68%). 58% of native language speaking medical students have partners, compared to only 56% on non-native language speaking medical students. Job rates among native & non-native medical students were the same, with 35% of med students in each group having a job on top of med school\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Counts by Native Language Status\n\ndrow_table <- data.frame(\"Demographics\" = c(\"Male\", \"Female\", \"Single\", \"Partnered\", \"Unemployed\", \"Employed\"), \"Native Language\" = c(\"252\", \"537\", \"332\",\"457\", \"514\", \"275\"), \"Non-Native Language\"= c(\"23\", \"69\", \"50\",\"42\", \"60\", \"32\"))\n                         \ntable_row <- knitr::kable(drow_table, caption = \"Table 1: Demographic Counts by Native Language Status\") %>%\nkable_styling(bootstrap_options = \"striped\", full_width = FALSE) %>%\n  row_spec(0, color = 'white', background = 'blue') %>%\n   row_spec(2, color = 'black', background = 'lightblue') %>%\n   row_spec(4, color = 'black', background = 'lightblue') %>%\n   row_spec(6, color = 'black', background = 'lightblue') \n\ntable_row \n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 1: Demographic Counts by Native Language Status</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;color: white !important;background-color: blue !important;\"> Demographics </th>\n   <th style=\"text-align:left;color: white !important;background-color: blue !important;\"> Native.Language </th>\n   <th style=\"text-align:left;color: white !important;background-color: blue !important;\"> Non.Native.Language </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Male </td>\n   <td style=\"text-align:left;\"> 252 </td>\n   <td style=\"text-align:left;\"> 23 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> Female </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 537 </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 69 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Single </td>\n   <td style=\"text-align:left;\"> 332 </td>\n   <td style=\"text-align:left;\"> 50 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> Partnered </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 457 </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 42 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Unemployed </td>\n   <td style=\"text-align:left;\"> 514 </td>\n   <td style=\"text-align:left;\"> 60 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> Employed </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 275 </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 32 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nI then created Table 2 below containing mean MBI_ex, MBI_cy, MBI_ea, anxiety (STAI_T), depression (CES-D) scores, as well as mean hours studying weekly. Table 2 shows that non-native language speakers have higher mean mbi_ex, mbi_cy, STAI_T, & CES-D scores than native language speakers. This indicates higher mean burnout in 2/3 sub-scales & higher mean anxiety & depression for non-native language speakers. Native & non-native language speakers met clinical criteria for depression (\\>16) & anxiety (\\>30-40). Non-native language speakers studied more on average than native language speakers, 28.47 hrs/wk vs 25.01 hrs/wk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculating Means for Table\nMean <- FinalRecoded2 %>%\n  group_by(`NatLang`) %>%\n  select(`NatLang`, `mbi_ex`, `mbi_cy`, `mbi_ea`, stai_t, cesd, stud_h) %>%\n  summarise_all(mean, na.rm = TRUE)\n\nMean\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  NatLang mbi_ex mbi_cy mbi_ea stai_t  cesd stud_h\n    <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <dbl>  <dbl>\n1       0   18.0   10.7   24.1   47.6  23.0   28.3\n2       1   16.8   10.0   24.2   42.5  17.6   25.1\n```\n:::\n\n```{.r .cell-code}\ndrow_means <- data.frame(\"Measures\" = c(\"Mean MBI Emotional Exhaustion Score\", \"Mean MBI Cynicism Score\", \"Mean MBI Academic Efficacy Score\", \"Mean Anxiety Score (STAI_T)\", \"Mean Depression Score (CES-D\", \"Mean Hours Studied\"), \"Native Language\" = c(\"16.79\", \"10.00\", \"24.22\", \"43.57\", \"17.70\", \"25.01\"), \"Non-Native Language\"= c(\"17.66\", \"10.66\", \"24.32\", \"45.93\", \"21.21\", \"28.47\"))\n                         \ntable_means <- knitr::kable(drow_means, caption = \"Table 2: Means by Native Language Status\") %>%\n  kable_styling(bootstrap_options = \"striped\", full_width = FALSE) %>%\n   row_spec(0, color = 'white', background = 'blue') %>%\n   row_spec(2, color = 'black', background = 'lightblue') %>%\n   row_spec(4, color = 'black', background = 'lightblue') %>%\n   row_spec(6, color = 'black', background = 'lightblue') \n\n  \ntable_means\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 2: Means by Native Language Status</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;color: white !important;background-color: blue !important;\"> Measures </th>\n   <th style=\"text-align:left;color: white !important;background-color: blue !important;\"> Native.Language </th>\n   <th style=\"text-align:left;color: white !important;background-color: blue !important;\"> Non.Native.Language </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Mean MBI Emotional Exhaustion Score </td>\n   <td style=\"text-align:left;\"> 16.79 </td>\n   <td style=\"text-align:left;\"> 17.66 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> Mean MBI Cynicism Score </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 10.00 </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 10.66 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Mean MBI Academic Efficacy Score </td>\n   <td style=\"text-align:left;\"> 24.22 </td>\n   <td style=\"text-align:left;\"> 24.32 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> Mean Anxiety Score (STAI_T) </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 43.57 </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 45.93 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Mean Depression Score (CES-D </td>\n   <td style=\"text-align:left;\"> 17.70 </td>\n   <td style=\"text-align:left;\"> 21.21 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> Mean Hours Studied </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 25.01 </td>\n   <td style=\"text-align:left;color: black !important;background-color: lightblue !important;\"> 28.47 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Analysis\n\nI created several box plots comparing the MBI burnout scores of medical students speaking native language vs. students speaking non-native language. Additionally, I compared the anxiety & depression scored of medical students native and non-native language speaking students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Emotional Exhaustion Burnout Score\nggplot(data = FinalProp2, aes(x= nat, y = mbi_ex, fill = nat)) + geom_boxplot() + labs(title = \"Figure 1: Box Plot MBI Emotional Exhaustion Score by Native Language\", x = \"Native Language Spoken\", y = \"mbi_ex Score\") + theme(legend.position=\"bottom\") + scale_fill_brewer(palette=\"Accent\")\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nNative language speaking and non-native language speaking medical students seemed to have nearly identical median scores for Emotional Exhaustion (mbi_ex). The IQR however for non-native language speaking students does appear to start & end higher (higher Q1 & Q3 MBI-ex scores) than native students, suggesting the potential for higher emotional exhaustion burnout for non-native language speaking students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Cynicism Score\nggplot(data = FinalProp, aes(x = nat, y = mbi_cy, fill = nat)) + geom_boxplot() +\n  labs(title = \"Figure 2: Box Plot MBI Cynicism Score by Native Language\", x = \"Native Language Spoken\", y = \"mbi_cy\") + theme(legend.position=\"bottom\") + scale_fill_brewer(palette=\"Accent\")\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nNon-native speaking medical students appeared to score slightly higher on average than non-native speaking medical students on Cynicism as measured by the mbi-cy, with a higher median score. The IQR of mbi-cy scores for non-native language speaking medical students is higher for non-native students with a higher Q1 & Q3. There appears to be one high outlier for native language speakers cynicism scores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Academic Efficacy Score\nggplot(data = FinalProp2, aes(x= nat, y = mbi_ea, fill = nat)) + geom_boxplot() +\n  labs(title = \"Figure 3: Box Plot MBI Academic Efficacy Score by Native Language\", x = \"Native Language Spoken\", y = \"mbi_ea\") + theme(legend.position=\"bottom\") + scale_fill_brewer(palette=\"Accent\")\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nLastly, native language speaking and non-native language speaking medical students seemed to have nearly identical median scores for Academic Efficacy burnout (mbi_ea), with one low-outlier of scores for native language speaking medical students. However non-native medical school students have a lower MBI_ea Q1 & Q3 which corresponds with higher burnout on this sub-scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Depression Score\nggplot(data = FinalProp2, aes(x= nat, y = cesd, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot - CESD Depression Score by Native Language\", x = \"Native Language Spoken\", y = \"CESD Score\") + theme(legend.position=\"bottom\") + scale_fill_brewer(palette=\"Accent\")\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nNon-native national language speakers have a higher median on CESD score than native national language speakers, suggesting higher depression among native students. The Q1 & Q3 of the non-native language speaking medical students CESD is higher than scores for native language speaking students. There are several high outliers for native and non-native language speaking students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Anxiety Score\nggplot(data = FinalProp2, aes(x= nat, y = stai_t, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot - STAI_T Anxiety Score by Native Language\", x = \"Native Language Spoken\", y = \"stai_t Score\") + theme(legend.position=\"bottom\")  + scale_fill_brewer(palette=\"Accent\")\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nNon-native national languages speaking medical students have a higher median, Q1, & Q3 stai_t anxiety score than native language speaking medical students.Higher depression and anxiety scores may mediate the impact of speaking a native language on burnout. Anxiety and depression, as measured by STAI_T and CESD scores, will be treated as interaction terms in linear regression model, with graphic models used to evaluate this.\n\n### Gender\n\nPrevious studies on the impact of gender and burnout found that being female predicted higher burnout. In the linear regression model, I will want to control for the impact of gender on burnout scores by including it as an explanatory variable.\n\nOn the plots below, I facet wrapped the box & whiskers plot of emotional burnout comparison by native language to visualize difference in the 3 MBI burnout scales when controlled by gender.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Emotional Exhaustion Burnout Score\n\n\nggplot(data = FinalProp2, aes(x= nat, y = mbi_ex, fill = nat)) + geom_boxplot() +\n  labs(title = \"Figure 6: Box Plot Emotional Exhaustion Burnout by Gender & Native Language\", x = \"Native Language Spoken\", y = \"MBI_ex Score\") + facet_wrap(vars(`gender`)) + theme(legend.position=\"bottom\")  + scale_fill_brewer(palette=\"Accent\")\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Emotional Cynicism Burnout Score\nggplot(data = FinalProp2, aes(x= nat, y = mbi_cy, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot Cynicism Burnout by Gender & Native Language\", x = \"Native Language Spoken\", y = \"MBI_cy Score\") + facet_wrap(vars(`gender`)) + theme(legend.position=\"bottom\")  + scale_fill_brewer(palette=\"Accent\")\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Academic Efficacy Burnout Score\nggplot(data = FinalProp2, aes(x= nat, y = mbi_ex, fill = nat)) + geom_boxplot() +\n  labs(title = \"Box Plot Academic Efficacy Burnout by Gender & Native Language\", x = \"Native Language Spoken\", y = \"MBI_ea Score\") + facet_wrap(vars(`gender`)) + theme(legend.position=\"bottom\")  + scale_fill_brewer(palette=\"Accent\")\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nEven when controlling for gender there still seems to be a difference between the MBI scores of native and non-native language speaking MBI burnout scores. Non-native students have a higher emotional exhaustion (MBI-ex) & cynicism (MBI-cy) burnout scores for both genders. Looking at the academic efficacy score, for non-native male med students it appears to be higher than native male med students, suggesting lower academic efficacy burnout counter to my hypothesis.\n\n### Applying feedback from Final Check in 1\n\nIn response to feedback on Check In 1, I kept categorical data coded as dummy variables 0,1 format for the linear regression. I did keep a \"prop\"data set record to use to calculate proportions & frequencies of categorical variables.\n\nIn deciding how to best work with the 3 MBI burnout variables, I reviewed literature on burnout and how prior researchers chose to work with the variables. A 2016 systematic review by Doulougeri et al. of 50 articles on burnout in medical staff as measured by the MBI found that the majority of studies analyzed burn out as sub scales of emotional exhaustion, cynicism (also known as depersonalization), & academic efficacy (also known as professional accomplishment), as opposed to trying to create one total scale.\n\nThis approach also aligns with the finding that burnout is often conceptualized as a multidimensional construct. Maslach designed the MBI to distinguish between the three sub-scales. Studies on burnout almost universally considered the MBI emotional exhaustion (EE) sub-scale in determining burnout, sometimes alone, sometimes with cynicism, and sometimes with both cynicism & academic efficacy. According to the literature, burn out is complex and multidimensional concepts, and impacts both an individual's well being and their ability to perform their job as a medical professional.Burnout is conceptualized in 3 dimensions: emotional exhaustion (physical & cognitive fatigue); cynicism (de-personalization, indifference); academic efficacy (ability to do school/their job).\n\nBased on all of these factors, I will run three separate models with each of the 3 MBI sub-scales as dependent variables.\n\n## Hypothesis Testing\n\nEach MBI burnout sub-scale score will be a response variable for each of the 3 models. These scales are numeric and continuous.\n\n-   emotional exhaustion\n-   cynicism\n-   academic efficacy\n\nAs mentioned earlier, a higher score on emotional exhaustion & cynicism are considered indicative of burnout, whereas lower scores of academic efficacy are indicative of burnout.\n\nThe explanatory variable I am testing in my hypothesis is whether or not a student speaks a native language of the country they are attending medical school in, coded as a binary dummy variable (0 = non-native, 1 = native)\n\nAs previous studies have found a relationship between gender and burnout, I will need to have gender as a control variable in the model. I will also examine if I will need to also control for the influence of having a partner, having a job, or seeing a therapist in past 12 months (all also binary dummy variables) on medical student burnout, by adding them to the regression model and seeing their impact.\n\n### T test\n\nTo test my hypothesis that *Medical students whose native language is a national language of the country where they are studying will experience lower rates of burnout than medical students with other native languages*, I will run a Welch's Independent T-Test on the data to see if there is a statistically significant difference between the burnout of native and non-native medical students. Specifically, I will run a one-sided test, to see if the mean burnout of non-native students is higher than of native students.\n\nThe null hypothesis is that there is no difference in the mean burnout of native medical students than non-native medical students\n\nThe alternative hypothesis is that the mean burnout of native students is less than that non-native medical students. For the emotional exhaustion & cynicism burnout scores, higher score corresponds to higher burnout, for the academic efficacy, a lower score corresponds with higher burnout.\n\n### Emotional Exhaustion\n\nH0: μ = μ0\n\nHA: μ \\< μ0\n\nThe first T-Test compared the emotional exhaustion scores of native and non-native language speaking medical students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(FinalRecoded2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 22\n     id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n1     2    18     1     1   120     1     0     56      3     0    88       62\n2     4    26     4     1     1     1     0     20      4     0   109       55\n3     9    21     3     2     1     0     0     36      3     0   106       64\n4    10    21     2     2     1     0     1     51      5     0   101       52\n5    13    21     3     1     1     1     0     22      4     0   102       58\n6    14    26     5     2     1     1     1     10      2     0   102       48\n# … with 10 more variables: qcae_aff <dbl>, amsp <dbl>, erec_mean <dbl>,\n#   cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>, mbi_ea <dbl>,\n#   NatLang <dbl>, gender <dbl>\n```\n:::\n\n```{.r .cell-code}\nFinalRecoded2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 881 × 22\n      id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n 1     2    18     1     1   120     1     0     56      3     0    88       62\n 2     4    26     4     1     1     1     0     20      4     0   109       55\n 3     9    21     3     2     1     0     0     36      3     0   106       64\n 4    10    21     2     2     1     0     1     51      5     0   101       52\n 5    13    21     3     1     1     1     0     22      4     0   102       58\n 6    14    26     5     2     1     1     1     10      2     0   102       48\n 7    17    23     5     2     1     1     0     15      3     0   117       58\n 8    21    23     4     1     1     1     1      8      4     0   118       65\n 9    23    23     4     2     1     1     1     20      2     0   118       69\n10    24    22     2     2     1     1     0     20      5     0   108       56\n# … with 871 more rows, and 10 more variables: qcae_aff <dbl>, amsp <dbl>,\n#   erec_mean <dbl>, cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>,\n#   mbi_ea <dbl>, NatLang <dbl>, gender <dbl>\n```\n:::\n\n```{.r .cell-code}\n#Ttest\nNative <- subset(FinalRecoded2, FinalRecoded2$NatLang == 1)\nNonNative <- subset(FinalRecoded2, FinalRecoded2$NatLang == 0)\n\n\n##One side t-test, MBI ex \nttest_ex <- t.test(Native$mbi_ex, NonNative$mbi_ex, var.equal = TRUE, alternative = \"less\")\nttest_ex\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Native$mbi_ex and NonNative$mbi_ex\nt = -1.932, df = 879, p-value = 0.02684\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n       -Inf -0.1861119\nsample estimates:\nmean of x mean of y \n 16.78298  18.04286 \n```\n:::\n:::\n\n\nWith a p-value of 0.02684 the difference between the mean is statistically significant at the 0.05 level. Therefor I reject the null hypothesis that there is no difference between the native and non-native students MBI_ex scores.\n\n### Cynicism\n\nH0: μ = μ0\n\nHA: μ \\< μ0\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Cynicism\nttest_cy <- t.test(Native$mbi_cy, NonNative$mbi_cy, var.equal = TRUE, alternative = \"less\")\nttest_cy\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Native$mbi_cy and NonNative$mbi_cy\nt = -1.1542, df = 879, p-value = 0.1244\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n      -Inf 0.2806803\nsample estimates:\nmean of x mean of y \n 10.01356  10.67143 \n```\n:::\n:::\n\n\nNext the cynicism MBI burnout scores for native and non-native scores were compared in a T-Test. With a p-value of 0.125, the difference between the means is not statistically significant at the 0.1 or the 0.05 levels. I fail to reject the null hypothesis that there is no difference between the native and non-native medical students MBI_cy scores.\n\n### Academic Efficacy\n\nH0: μ = μ0\n\nHA: μ \\> μ0\n\nLastly, I performed a T-Test on the final MBI sub-score, the academic efficacy between native and non-native language speaking medical students. As a lower MBI_ea score corresponds with higher burnout on this sub-scale the alternative hypothesis of the one-sided T-test is that\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#T-test Academic Efficacy \nttest_ea <- t.test(Native$mbi_ea, NonNative$mbi_ea, var.equal = TRUE, alternative = \"greater\")\nttest_ea\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Native$mbi_ea and NonNative$mbi_ea\nt = 0.30068, df = 879, p-value = 0.3819\nalternative hypothesis: true difference in means is greater than 0\n95 percent confidence interval:\n -0.7730962        Inf\nsample estimates:\nmean of x mean of y \n 24.24414  24.07143 \n```\n:::\n:::\n\n\nWith a p-value of 0.4172 the mean MBI_ea score of native medical students is not statistically significant at any level, therefor I fail to reject the null hypothesis that there is no difference between the mean academic efficacy of native & non-native language speakers.\n\n### Interpretation of Hypothesis Testing & Further Tests\n\nOut of the 3 MBI burnout sub-scales, only the one-sided difference in burnout as measured on the MBI emotional exhaustion scale is statistically significant at the 0.05 level. Non-native language speking medical students had higher mean emotional exhaustion burnout scores than native language speaking benefits, indicating higher burnout in this domain.\n\nThere were no statistically significantly difference in the means of native & non-native language speaking students on the MBI cynicism & academic efficacy subscales.\n\nI then ran Welch's T-tests on anxiety (stai_t) and depression (CESD) scores to see if there was a statistically significant difference between native and non-native speaking medical school students. Once again I ran a one-sided t-test, with the assumption that the mean anxiety and depression of non-native language speaking medical students will be higher than that of native language speaking medical students.\n\nH0: μ = μ0\n\nHA: μ \\< μ0\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# T-test Anxiety\nttest_stai_t <- t.test(Native$stai_t, NonNative$stai_t, var.equal = TRUE, alternative = \"less\")\nttest_stai_t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Native$stai_t and NonNative$stai_t\nt = -3.4511, df = 879, p-value = 0.0002925\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n      -Inf -2.676113\nsample estimates:\nmean of x mean of y \n 42.51048  47.62857 \n```\n:::\n:::\n\n\nWith a p-value of 0.0002955 there is strong statistical significance to reject the null hypothesis that there is no difference in the mean anxiety of native and non-native language speaking medical students. This suggests that med students who speak the non-native language experience higher anxiety levels than native-language speakers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# T-test Depression\nttest_cesd <- t.test(Native$cesd, NonNative$cesd, var.equal = TRUE, alternative = \"less\")\nttest_cesd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Native$cesd and NonNative$cesd\nt = -3.7886, df = 879, p-value = 8.091e-05\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n      -Inf -3.038548\nsample estimates:\nmean of x mean of y \n 17.63995  23.01429 \n```\n:::\n:::\n\n\nWith a p-value of 9.4955e-05 there is strong statistical significance to reject the null hypothesis that there is no difference in the mean depression of native and non-native language speaking medical students. This suggests that med students who speak the non-native language experience higher depression levels than native-language speakers.\n\nIn answering my reearch question of\" *Why are some medical students more likely to experience burnout than others?* it seems that native language status, anxiety, depression all interact on one-another to help explain burnout. This will be explored further in the linear regression models.\n\n## Linear Regressions\n\n### Emotional Exhaustion Burnout Model (MBI_ex)\n\nFirst, I created a linear regression model with only native language status as the explanatory variable and mbi_ex emotional exhaustion burnout score as the outcome variable. NatLang is statistically significant at the 0.1 level with a p-value of 0.0537. The negative co-efficient of -1.2599 suggests that native language speakers (1) are predicted to have lower MBI-ex scores.However the Adjusted R-squared value of 0.003096 suggests that variance in native language speaking status alone does not explain variance in emotional exhaustion MBI scores. The AIC of this first model is 5421 & the BIC is 5435, with the lower the AIC & BIC score the better the fit of the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear regression model with only NatLang as explanatory variable\n\nmodel_ex_1 <- lm(mbi_ex ~ NatLang, data = FinalRecoded2)\nsummary(model_ex_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ NatLang, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-12.0429  -3.7830  -0.0429   3.2170  13.2170 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  18.0429     0.6257  28.838   <2e-16 ***\nNatLang      -1.2599     0.6521  -1.932   0.0537 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.235 on 879 degrees of freedom\nMultiple R-squared:  0.004228,\tAdjusted R-squared:  0.003096 \nF-statistic: 3.733 on 1 and 879 DF,  p-value: 0.05368\n```\n:::\n\n```{.r .cell-code}\n## AIC \nglance(model_ex_1)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5420.832\n```\n:::\n\n```{.r .cell-code}\nglance(model_ex_1)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5435.175\n```\n:::\n:::\n\n\nThe second linear regression model includes gender as an explanatory variable along with native-language status for the outcome of emotional exhaustion MBI scores. Native-language status is statistically significant at the 0.1 level with a p-value of 0.0896 & a coefficient of -1.096. This means that speaking a native language predicts a lower MBI-ex score. Gender is statistically significant at the 0.001 level with a p-value of 1.91 x e\\^-06 & a coefficient of 1.8050, suggesting that being female is predicted to increase burnout. The adjusted R-squared value is higher than the first model but still low at 0.02743. The AIC value of 5400 & BIC value of 5419 is lower than the first model, suggesting better fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear Regression model with NatLang & gender\nmodel_ex_2 <- lm(mbi_ex ~ NatLang + gender , data = FinalRecoded2)\nsummary(model_ex_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ NatLang + gender, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-12.3594  -3.4554  -0.3594   3.6406  14.4456 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  16.6504     0.6828  24.385  < 2e-16 ***\nNatLang      -1.0960     0.6450  -1.699   0.0896 .  \ngender        1.8050     0.3765   4.795 1.91e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.17 on 878 degrees of freedom\nMultiple R-squared:  0.02964,\tAdjusted R-squared:  0.02743 \nF-statistic: 13.41 on 2 and 878 DF,  p-value: 1.838e-06\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ex_2)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5400.061\n```\n:::\n\n```{.r .cell-code}\n#BIC\nglance(model_ex_2)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5419.186\n```\n:::\n:::\n\n\nIn the third linear regression model was a 3-way interaction of depression (CESD), anxiety (stai_t), & native language as an explanatory variable for MBI emotional exhaustion scores in addition to gender. Adding the 3 way interaction term to the model greatly increased the predictive power of the model, raising the adjusted R-squared value to 0.3883. In this model, only Depression (cesd) is statistically significant at the 0.05 level, with a p-value of 0.0202 & a coefficient of 0.394. The positive coefficient suggests that increased depression scoreds predict increased burnout. The AIC of 4997 & the BIC of 5045 are the lowest of any model so far, suggesting the best fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear Regression model with NatLang * Anxiety * Depression & gender explanatory variables\nmodel_ex_3 <- lm(mbi_ex ~ gender + NatLang*cesd*stai_t , data = FinalRecoded2)\nsummary(model_ex_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + NatLang * cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.0338  -2.7845  -0.1788   2.5180  14.0456 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)  \n(Intercept)          8.5749820  4.0220182   2.132   0.0333 *\ngender              -0.0551474  0.3105581  -0.178   0.8591  \nNatLang             -1.4582573  4.1237259  -0.354   0.7237  \ncesd                 0.3940699  0.1693940   2.326   0.0202 *\nstai_t               0.0918575  0.0931086   0.987   0.3241  \nNatLang:cesd        -0.0544441  0.1758153  -0.310   0.7569  \nNatLang:stai_t       0.0502754  0.0961606   0.523   0.6012  \ncesd:stai_t         -0.0032785  0.0029065  -1.128   0.2596  \nNatLang:cesd:stai_t  0.0005228  0.0030609   0.171   0.8644  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.1 on 872 degrees of freedom\nMultiple R-squared:  0.3939,\tAdjusted R-squared:  0.3883 \nF-statistic: 70.83 on 8 and 872 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ex_3)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4997.459\n```\n:::\n\n```{.r .cell-code}\n#BIC\nglance(model_ex_3)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5045.269\n```\n:::\n:::\n\n\nTo determine the best model, I added the control variables of hours studied, having a partner, job status, consulting a psychotherapist in past 12 months, & health satisfaction to see the impact on the adjusted R squared value of the 3-way interaction term.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Control variables\n\nhead(FinalRecoded2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 22\n     id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n1     2    18     1     1   120     1     0     56      3     0    88       62\n2     4    26     4     1     1     1     0     20      4     0   109       55\n3     9    21     3     2     1     0     0     36      3     0   106       64\n4    10    21     2     2     1     0     1     51      5     0   101       52\n5    13    21     3     1     1     1     0     22      4     0   102       58\n6    14    26     5     2     1     1     1     10      2     0   102       48\n# … with 10 more variables: qcae_aff <dbl>, amsp <dbl>, erec_mean <dbl>,\n#   cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>, mbi_ea <dbl>,\n#   NatLang <dbl>, gender <dbl>\n```\n:::\n\n```{.r .cell-code}\n##hours studied strengthens model\nsummary(lm(mbi_ex ~ gender + stud_h + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + NatLang * cesd * stai_t, \n    data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.5483  -2.7782  -0.1724   2.5784  14.1136 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)   \n(Intercept)          8.060071   4.010608   2.010  0.04477 * \ngender              -0.012661   0.309723  -0.041  0.96740   \nstud_h               0.024639   0.008810   2.797  0.00528 **\nNatLang             -1.413266   4.107723  -0.344  0.73089   \ncesd                 0.385072   0.168766   2.282  0.02275 * \nstai_t               0.087921   0.092757   0.948  0.34346   \nNatLang:cesd        -0.050396   0.175138  -0.288  0.77361   \nNatLang:stai_t       0.052124   0.095789   0.544  0.58647   \ncesd:stai_t         -0.003130   0.002896  -1.081  0.28007   \nNatLang:cesd:stai_t  0.000372   0.003049   0.122  0.90293   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.084 on 871 degrees of freedom\nMultiple R-squared:  0.3993,\tAdjusted R-squared:  0.3931 \nF-statistic: 64.33 on 9 and 871 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##partner strengthened model\nsummary(lm(mbi_ex ~ gender + stud_h + part + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + part + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.8199  -2.7459  -0.1021   2.5393  14.2138 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)   \n(Intercept)          7.2767968  4.0163840   1.812  0.07037 . \ngender              -0.0432849  0.3093023  -0.140  0.88874   \nstud_h               0.0264412  0.0088263   2.996  0.00282 **\npart                 0.6321501  0.2808580   2.251  0.02465 * \nNatLang             -1.0365435  4.1015851  -0.253  0.80055   \ncesd                 0.4103187  0.1687467   2.432  0.01523 * \nstai_t               0.0944114  0.0925864   1.020  0.30815   \nNatLang:cesd        -0.0747001  0.1750637  -0.427  0.66970   \nNatLang:stai_t       0.0449907  0.0956187   0.471  0.63810   \ncesd:stai_t         -0.0034977  0.0028936  -1.209  0.22709   \nNatLang:cesd:stai_t  0.0007758  0.0030476   0.255  0.79912   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.075 on 870 degrees of freedom\nMultiple R-squared:  0.4028,\tAdjusted R-squared:  0.3959 \nF-statistic: 58.67 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##having job worsened model\nsummary(lm(mbi_ex ~ gender + stud_h + part + job + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + part + job + NatLang * \n    cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.8856  -2.7297  -0.1083   2.5207  14.1378 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)   \n(Intercept)          7.4629570  4.0351276   1.849  0.06473 . \ngender              -0.0384731  0.3095831  -0.124  0.90113   \nstud_h               0.0255808  0.0089943   2.844  0.00456 **\npart                 0.6351052  0.2810401   2.260  0.02408 * \njob                 -0.1485578  0.2954247  -0.503  0.61519   \nNatLang             -1.1526960  4.1098434  -0.280  0.77918   \ncesd                 0.4081265  0.1688755   2.417  0.01587 * \nstai_t               0.0913883  0.0928211   0.985  0.32511   \nNatLang:cesd        -0.0723212  0.1752028  -0.413  0.67987   \nNatLang:stai_t       0.0480548  0.0958536   0.501  0.61626   \ncesd:stai_t         -0.0034376  0.0028973  -1.186  0.23576   \nNatLang:cesd:stai_t  0.0007086  0.0030519   0.232  0.81644   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.077 on 869 degrees of freedom\nMultiple R-squared:  0.4029,\tAdjusted R-squared:  0.3954 \nF-statistic: 53.31 on 11 and 869 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## seen psychiatrist worsened model\nsummary(lm(mbi_ex ~ gender + stud_h + part + psyt + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + part + psyt + NatLang * \n    cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.8209  -2.7455  -0.1015   2.5399  14.2141 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)   \n(Intercept)          7.2770334  4.0189508   1.811  0.07054 . \ngender              -0.0434259  0.3106611  -0.140  0.88886   \nstud_h               0.0264450  0.0088621   2.984  0.00292 **\npart                 0.6320861  0.2812878   2.247  0.02488 * \npsyt                 0.0018233  0.3500261   0.005  0.99585   \nNatLang             -1.0366417  4.1039876  -0.253  0.80064   \ncesd                 0.4103300  0.1688577   2.430  0.01530 * \nstai_t               0.0943979  0.0926755   1.019  0.30868   \nNatLang:cesd        -0.0747099  0.1751745  -0.426  0.66986   \nNatLang:stai_t       0.0449962  0.0956795   0.470  0.63827   \ncesd:stai_t         -0.0034978  0.0028954  -1.208  0.22735   \nNatLang:cesd:stai_t  0.0007757  0.0030494   0.254  0.79926   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.077 on 869 degrees of freedom\nMultiple R-squared:  0.4028,\tAdjusted R-squared:  0.3952 \nF-statistic: 53.27 on 11 and 869 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## health sat strengthened model\nsummary(lm(mbi_ex ~ gender + stud_h + part + health + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ gender + stud_h + part + health + NatLang * \n    cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.3802  -2.7438  -0.0997   2.5740  14.6117 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)   \n(Intercept)          9.3855390  4.0585569   2.313  0.02098 * \ngender              -0.0349557  0.3078865  -0.114  0.90963   \nstud_h               0.0260806  0.0087863   2.968  0.00308 **\npart                 0.6633402  0.2797524   2.371  0.01795 * \nhealth              -0.4210283  0.1396429  -3.015  0.00264 **\nNatLang             -1.3647077  4.0840966  -0.334  0.73835   \ncesd                 0.4141692  0.1679723   2.466  0.01387 * \nstai_t               0.0847493  0.0922146   0.919  0.35833   \nNatLang:cesd        -0.0813649  0.1742693  -0.467  0.64069   \nNatLang:stai_t       0.0549232  0.0952342   0.577  0.56428   \ncesd:stai_t         -0.0036817  0.0028809  -1.278  0.20160   \nNatLang:cesd:stai_t  0.0007711  0.0030336   0.254  0.79940   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.056 on 869 degrees of freedom\nMultiple R-squared:  0.4089,\tAdjusted R-squared:  0.4015 \nF-statistic: 54.66 on 11 and 869 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nVariables that improved model fit were:\n\n-   Hours studied (stud_h)\n-   Having a partner (part)\n-   Health satisfaction (health)\n\nThese 3 explanatory variables will be added to the final model to improve fit. Considering that gender is related to burnout as well as anxiety & depression in earlier exploration of the data, I wanted to explore the a 4-way interaction between anxiety, burnout, gender, & native language status as explanatory for emotional exhaustion burnout.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear regression model of 4 way-interaction of gender * NatLang * CES-D, * STAI-T\nmodel_ex_4 <- lm(mbi_ex ~ stud_h + health + part +  gender*NatLang*cesd*stai_t, data = FinalRecoded2)\nsummary(model_ex_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ stud_h + health + part + gender * NatLang * \n    cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.2858  -2.7670  -0.1719   2.5619  14.5201 \n\nCoefficients:\n                             Estimate Std. Error t value Pr(>|t|)   \n(Intercept)                 21.181036   6.888450   3.075  0.00217 **\nstud_h                       0.027423   0.008806   3.114  0.00191 **\nhealth                      -0.421181   0.139864  -3.011  0.00268 **\npart                         0.670855   0.280743   2.390  0.01708 * \ngender                     -18.064595   9.014920  -2.004  0.04540 * \nNatLang                    -13.746744   6.989403  -1.967  0.04953 * \ncesd                         0.486711   0.425828   1.143  0.25337   \nstai_t                      -0.326192   0.189299  -1.723  0.08522 . \ngender:NatLang              19.123464   9.206935   2.077  0.03809 * \ngender:cesd                  0.001285   0.479181   0.003  0.99786   \nNatLang:cesd                -0.128125   0.433856  -0.295  0.76782   \ngender:stai_t                0.566915   0.226802   2.500  0.01262 * \nNatLang:stai_t               0.475743   0.193961   2.453  0.01437 * \ncesd:stai_t                  0.001664   0.008698   0.191  0.84835   \ngender:NatLang:cesd         -0.048915   0.489803  -0.100  0.92047   \ngender:NatLang:stai_t       -0.587852   0.232808  -2.525  0.01175 * \ngender:cesd:stai_t          -0.007890   0.009481  -0.832  0.40554   \nNatLang:cesd:stai_t         -0.004888   0.008881  -0.550  0.58220   \ngender:NatLang:cesd:stai_t   0.008595   0.009719   0.884  0.37676   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.052 on 862 degrees of freedom\nMultiple R-squared:  0.415,\tAdjusted R-squared:  0.4028 \nF-statistic: 33.97 on 18 and 862 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ex_4)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4986.242\n```\n:::\n\n```{.r .cell-code}\n#BIC\nglance(model_ex_4)$BIC \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5081.863\n```\n:::\n:::\n\n\nThe best-fitting linear regression model for MBI_ex as determined by adjusted R-squared includes gender, hours studied, health satisfaction, having a partner, and 4-way interaction between gender, native language, depression, and anxiety as explanatory variables. This has an Adjusted R-Squared value of 0.4028, suggesting much of the the variance in MBI emotional exhaustion scores of medical school students is explained by variance in the explanatory variables. The AIC value of 4986 is the lowest of any of the linear regression models, however the BIC of 5081 is higher than in the previous model.\n\n-   Explanatory variables significant at the 0.01 level are:\n\n    -   Hours Studied (stud-h)\n    -   Health Satisfaction (health)\n\n-   Explanatory variables significant at the 0.05 level are:\n\n    -   Having a Partner (part)\n    -   Gender (gender)\n    -   Native Language (NatLang)\n    -   2-way Interaction gender \\* NatLang\n    -   2-way Interaction gender \\* stai_t\n    -   2-way Interaction NatLang \\* stai_t\n    -   3-way Interaction gender \\* NatLang \\* stai_t\n\n-   Explanatory variables significant at the 0.1 level are:\n\n    -   Anxiety (stai_t)\n\nGenerally, a 4-way interaction would not be selected for a model, but in this linear regression model my explanatory variable of interest, Native Language (NatLang) is statistically significant at the 0.05 level, as is its 2-way interaction with gender, its 2-way interaction with anxiety (stai_t), & its 3-way interaction with gender & anxiety. I tried generating a 3-way interaction model of gender\\* NatLang\\*stai_t but this interaction was only significant in the 4-way interaction model. National Language is only statistically significant when depression (CES-D) is included in the interaction, though depression itself is not statistically signficant or in any statistically significant interactions.\n\nExamining the coefficients of the statistically significant explanatory variables in the 4-way interaction model:\n\n-   Native Language has a co-efficient of **-13.75** in the model, suggesting that when a medical student speaks the native language (1), their emotional exhaustion MBI score in predicted to decrease by 13.75.\n-   Hours Studied has a co-efficient of **0.0274** in the model, suggesting that with every extra hour studied each week, a medical student's emotional exhaustion MBI score is predicted to increase by 0.0274.\n-   Health has a co-efficient of **-0.4212** in the model, suggesting that with higher health satisfaction, the lower the predicted emotional exhaustion MBI score.\n-   Partner has co-efficient of **0.6709**, suggesting that having a partner (1) is predicted to increase a medical student's emotional exhaustion MBI score by 00.6709.\n-   Gender has a co-efficient of **-18.06** , suggesting that being a female (1) is predicted to decrease the emotional exhaustion MBI score by 18.06.\n-   Anxiety has a co-efficient of **-0.3261**, suggesting that with each unit of increased anxiety score, there is a predicted decrease in emotional exhaustion MBI score of 0.3261.\n-   The 2-way interaction between gender & native language has a co-efficient of **19.23**, suggesting that being a female (1) who speaks a native language (1) is predicted to increase the emotional exhaustion MBI score by 19.23\n-   The 2-way interaction between gender & anxiety (stai_t) has a co-efficient of **0.5669**, suggesting that for a female (1) medical student, with each unit increase in stai_t anxiety score there is predicted to be a 0.5669 unit increase in emotional exhaustion MBI score.\n-   The 2-way interaction between native language & anxiety (stai_t) has a co-efficient of **0.4757** , suggesting that for a native language speaking medical student (1), with each unit increase in stai_t anxiety score there is a 0.4757 unit increase of emotional exhaustion MBI score.\n-   The 3-way interaction between gender, native language, & anxiety (stai_t) has a co-efficient of **-0.5879** suggesting that for female (1) medical student speaking a native language (1), with each unit increase of anxiety score it is predicted that there will be a 0.5879 unit decrease in emotional exhaustion MBI score.\n\nThe predicted impact of the these interactions on the emotional exhaustion score aren't what one would have expected based on previous studies on the role of gender on burnout. Starting with the single explanatory terms,the coefficients for native language, hours studied, & health make sense in directionality. Speaking a native language & being satisfied with your health are predicted to decreases mbi_ex score, while studying more hours is expected to increase mbi_ex schools. Being female & having a higher STAI_T anxiety being predicted to decrease mbi-ex score & having a partner being predicted to increase mbi_ex score are counter to what one would expect.\n\nThe statistically significant 2 & 3-way interactions are somewhat confusing, which is one of the reasons 4-way interactions are not commonly used.In the 2-way interaction of gender & native language, being female & speaking a native language is predicted to increase mbi_ex score, which is the opposite predicted impact of either explanatory variables on it own. An increase anxiety score for a female in the 2-way interaction between gender & anxiety (STAI-T) is predicted to increase mbi_ex score, once again the opposite predicted impact of either explanatory variable on its own. The increase in anxiety score for a native language speaker is also predicted to increase the mbi_ex score according to the 2-way interaction of native language & anxiety. Lastly, in the 3 way interaction between native language, gender, & anxiety, for a female medical student that speaks a native language, an increase in anxiety score is predicted to decrease mbi_ex score. As mentioned, not all of these coefficients make sense. It makes sense that anxiety, gender, & native language all interact with one another & impact emotional exhaustion burnout. Further research is required to understand these interactions, & if there are unexpected protective factors found from having multiple factors that on their own might increase emotional exhaustion burnout. For example, for the 3-way interaction between native language, gender, & anxiety, potentially being a female medical student who speaks a native language may bring social support that mitigates anxiety increasing mbi_ex burnout.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Emotional Exhaustion Stargazer model\n\nstargazer(model_ex_1, model_ex_2, model_ex_3, model_ex_4, align = TRUE, column.sep.width = \"-1pt\",  no.space = TRUE, type = \"text\", title=\"Table 3: Comparison MBI Emotional Exhaustion Regression Results\", column.labels=c(\"Model 1\",\"Model 2\", \"Model 3\", \"Model 4\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nTable 3: Comparison MBI Emotional Exhaustion Regression Results\n========================================================================================================================\n                                                                Dependent variable:                                     \n                           ---------------------------------------------------------------------------------------------\n                                                                      mbi_ex                                            \n                                 Model 1                Model 2                 Model 3                 Model 4         \n                                   (1)                    (2)                     (3)                     (4)           \n------------------------------------------------------------------------------------------------------------------------\nstud_h                                                                                                  0.027***        \n                                                                                                        (0.009)         \nhealth                                                                                                 -0.421***        \n                                                                                                        (0.140)         \npart                                                                                                    0.671**         \n                                                                                                        (0.281)         \nNatLang                          -1.260*                -1.096*                 -1.458                 -13.747**        \n                                 (0.652)                (0.645)                 (4.124)                 (6.989)         \ncesd                                                                            0.394**                  0.487          \n                                                                                (0.169)                 (0.426)         \nstai_t                                                                           0.092                  -0.326*         \n                                                                                (0.093)                 (0.189)         \ngender:NatLang                                                                                          19.123**        \n                                                                                                        (9.207)         \ngender:cesd                                                                                              0.001          \n                                                                                                        (0.479)         \nNatLang:cesd                                                                    -0.054                   -0.128         \n                                                                                (0.176)                 (0.434)         \ngender:stai_t                                                                                           0.567**         \n                                                                                                        (0.227)         \nNatLang:stai_t                                                                   0.050                  0.476**         \n                                                                                (0.096)                 (0.194)         \ncesd:stai_t                                                                     -0.003                   0.002          \n                                                                                (0.003)                 (0.009)         \ngender:NatLang:cesd                                                                                      -0.049         \n                                                                                                        (0.490)         \ngender:NatLang:stai_t                                                                                   -0.588**        \n                                                                                                        (0.233)         \ngender:cesd:stai_t                                                                                       -0.008         \n                                                                                                        (0.009)         \nNatLang:cesd:stai_t                                                              0.001                   -0.005         \n                                                                                (0.003)                 (0.009)         \ngender:NatLang:cesd:stai_t                                                                               0.009          \n                                                                                                        (0.010)         \ngender                                                 1.805***                 -0.055                 -18.065**        \n                                                        (0.376)                 (0.311)                 (9.015)         \nConstant                        18.043***              16.650***                8.575**                21.181***        \n                                 (0.626)                (0.683)                 (4.022)                 (6.888)         \n------------------------------------------------------------------------------------------------------------------------\nObservations                       881                    881                     881                     881           \nR2                                0.004                  0.030                   0.394                   0.415          \nAdjusted R2                       0.003                  0.027                   0.388                   0.403          \nResidual Std. Error          5.235 (df = 879)      5.170 (df = 878)        4.100 (df = 872)         4.052 (df = 862)    \nF Statistic                3.733* (df = 1; 879) 13.407*** (df = 2; 878) 70.834*** (df = 8; 872) 33.971*** (df = 18; 862)\n========================================================================================================================\nNote:                                                                                        *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n\n### Cynicism Burnout Model (MBI_cy)\n\nFor the cynicism burnout sub scale, I once again started by running a linear regression model with only Native Language as the explanatory variable and mbi_cy score as the outcome variable. NatLang was not a statistically significant explanatory variable with a p-value of 0.249. The Adjusted R-Squared of the model was very low at 0.0003772, suggesting that variance NatLang alone does not explain the variance in mbi_cy scores for medical students. The AIC of 5184 & BIC of 5198 serves as a baseline for comparison for goodness of fit with future models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI-cy only nat lang as explanatory variables\nmodel_cy_1 <- lm(mbi_cy ~ NatLang, data = FinalRecoded2)\nsummary(model_cy_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ NatLang, data = FinalRecoded2)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-6.671 -4.014 -1.014  2.986 13.986 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  10.6714     0.5469  19.513   <2e-16 ***\nNatLang      -0.6579     0.5700  -1.154    0.249    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.576 on 879 degrees of freedom\nMultiple R-squared:  0.001513,\tAdjusted R-squared:  0.0003772 \nF-statistic: 1.332 on 1 and 879 DF,  p-value: 0.2487\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_cy_1)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5183.681\n```\n:::\n\n```{.r .cell-code}\n#BIC \nglance(model_cy_1)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5198.024\n```\n:::\n:::\n\n\nAs with the previous emotional exhaustion sub-scale, next I added gender as a the second explanatory variable, as the impact of gender on burnout has been studied. Not only were neither NatLang or gender statistically significant (p-values of 0.256 and 0.783 respectively), but the linear regression model with gender & NatLang as explanatory variables had a worse Adjusted R-Squared than the first model with a negative R-squared of -0.0006754. The AIC of 5185 & BIC of 5204 are higher than in the first model, confirming the worse fit of this model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI-cy  nat lang & gender as explanatory variables\nmodel_cy_2  <- lm(mbi_cy ~ NatLang + gender, data = FinalRecoded2)\nsummary(model_cy_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ NatLang + gender, data = FinalRecoded2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.6923 -3.9513 -0.9513  2.9572 14.0487 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 10.60086    0.60458  17.534   <2e-16 ***\nNatLang     -0.64956    0.57110  -1.137    0.256    \ngender       0.09148    0.33332   0.274    0.784    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.578 on 878 degrees of freedom\nMultiple R-squared:  0.001599,\tAdjusted R-squared:  -0.0006754 \nF-statistic: 0.703 on 2 and 878 DF,  p-value: 0.4954\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_cy_2)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5185.606\n```\n:::\n\n```{.r .cell-code}\n#BIC\nglance(model_cy_2)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5204.73\n```\n:::\n:::\n\n\nFor the third linear regression model I added the 3 way interaction of NatLang x Anxiety (stai-t score) x Depression (cesd) as an explanatory variable to gender in model 2. In this model, only gender is statistically significant at the 0.01 level with a p-value of 0.00115 & a coefficient of -1.0259, suggesting being a female is predicted to decreases MBI-cy scores. The Adjusted R-Squared 0f 0.1769, AIC of 5019 & 5067 suggest this is the best fitting model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model 3 MBI_cy 3 way interaction NatLang x cesd x stai_t + gender\nmodel_cy_3 = lm(mbi_cy ~ gender + NatLang*cesd*stai_t , data = FinalRecoded2)\nsummary(model_cy_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + NatLang * cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.3570  -3.1360  -0.6554   2.4028  15.6703 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)   \n(Intercept)          2.703013   4.072554   0.664  0.50705   \ngender              -1.025924   0.314460  -3.262  0.00115 **\nNatLang              3.266459   4.175540   0.782  0.43426   \ncesd                 0.249619   0.171522   1.455  0.14594   \nstai_t               0.111180   0.094279   1.179  0.23861   \nNatLang:cesd        -0.064808   0.178024  -0.364  0.71591   \nNatLang:stai_t      -0.059324   0.097369  -0.609  0.54250   \ncesd:stai_t         -0.001900   0.002943  -0.646  0.51862   \nNatLang:cesd:stai_t  0.001046   0.003099   0.338  0.73579   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.152 on 872 degrees of freedom\nMultiple R-squared:  0.1844,\tAdjusted R-squared:  0.1769 \nF-statistic: 24.64 on 8 and 872 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_cy_3)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5019.46\n```\n:::\n\n```{.r .cell-code}\n#BIC\nglance(model_cy_3)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5067.27\n```\n:::\n:::\n\n\nTo determine the best model, I added the control variables of hours studied, having a partner, job status, consulting a psychotherapist in past 12 months, & health satisfaction to see the impact on the adjusted R squared value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Control variables\n\n\n##hours studied strengthens model\nsummary(lm(mbi_cy ~ gender + stud_h + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + NatLang * cesd * stai_t, \n    data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.6866  -2.9484  -0.4393   2.4740  15.8145 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          3.722222   4.009230   0.928 0.353451    \ngender              -1.110020   0.309617  -3.585 0.000356 ***\nstud_h              -0.048770   0.008807  -5.537 4.06e-08 ***\nNatLang              3.177403   4.106312   0.774 0.439268    \ncesd                 0.267431   0.168708   1.585 0.113291    \nstai_t               0.118972   0.092725   1.283 0.199813    \nNatLang:cesd        -0.072822   0.175078  -0.416 0.677556    \nNatLang:stai_t      -0.062984   0.095756  -0.658 0.510869    \ncesd:stai_t         -0.002195   0.002895  -0.758 0.448563    \nNatLang:cesd:stai_t  0.001345   0.003048   0.441 0.659257    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.083 on 871 degrees of freedom\nMultiple R-squared:  0.2121,\tAdjusted R-squared:  0.204 \nF-statistic: 26.06 on 9 and 871 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##partner - lowered adjusted r-squared\nsummary(lm(mbi_cy ~ gender + stud_h + part + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + part + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-10.772  -2.949  -0.474   2.486  15.751 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          3.501753   4.025753   0.870 0.384629    \ngender              -1.118640   0.310024  -3.608 0.000326 ***\nstud_h              -0.048263   0.008847  -5.455 6.37e-08 ***\npart                 0.177932   0.281513   0.632 0.527516    \nNatLang              3.283440   4.111153   0.799 0.424702    \ncesd                 0.274537   0.169140   1.623 0.104924    \nstai_t               0.120799   0.092802   1.302 0.193371    \nNatLang:cesd        -0.079663   0.175472  -0.454 0.649948    \nNatLang:stai_t      -0.064992   0.095842  -0.678 0.497877    \ncesd:stai_t         -0.002298   0.002900  -0.792 0.428353    \nNatLang:cesd:stai_t  0.001458   0.003055   0.477 0.633210    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.084 on 870 degrees of freedom\nMultiple R-squared:  0.2125,\tAdjusted R-squared:  0.2034 \nF-statistic: 23.47 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##having job - lowered adjusted r-squared\nsummary(lm(mbi_cy ~ gender + stud_h + job + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + job + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.6235  -2.9342  -0.4671   2.4881  15.8699 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          3.538480   4.028776   0.878  0.38002    \ngender              -1.114817   0.309910  -3.597  0.00034 ***\nstud_h              -0.047929   0.008980  -5.338  1.2e-07 ***\njob                  0.143800   0.295950   0.486  0.62717    \nNatLang              3.291540   4.114825   0.800  0.42397    \ncesd                 0.269667   0.168845   1.597  0.11060    \nstai_t               0.121928   0.092965   1.312  0.19002    \nNatLang:cesd        -0.075235   0.175225  -0.429  0.66777    \nNatLang:stai_t      -0.065982   0.095997  -0.687  0.49205    \ncesd:stai_t         -0.002254   0.002899  -0.778  0.43691    \nNatLang:cesd:stai_t  0.001411   0.003053   0.462  0.64395    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.085 on 870 degrees of freedom\nMultiple R-squared:  0.2123,\tAdjusted R-squared:  0.2033 \nF-statistic: 23.45 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## seen psychiatrist - did not improve R-squared\nsummary(lm(mbi_cy ~ gender + stud_h + psyt + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + psyt + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.4572  -2.9218  -0.5125   2.4757  15.8605 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          3.751392   4.009500   0.936 0.349725    \ngender              -1.136738   0.310863  -3.657 0.000271 ***\nstud_h              -0.048024   0.008842  -5.432 7.25e-08 ***\npsyt                 0.338149   0.350199   0.966 0.334517    \nNatLang              3.166259   4.106488   0.771 0.440894    \ncesd                 0.270001   0.168736   1.600 0.109930    \nstai_t               0.116605   0.092761   1.257 0.209076    \nNatLang:cesd        -0.075098   0.175100  -0.429 0.668112    \nNatLang:stai_t      -0.062098   0.095764  -0.648 0.516869    \ncesd:stai_t         -0.002227   0.002895  -0.769 0.441934    \nNatLang:cesd:stai_t  0.001332   0.003049   0.437 0.662237    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.083 on 870 degrees of freedom\nMultiple R-squared:  0.213,\tAdjusted R-squared:  0.2039 \nF-statistic: 23.54 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## health sat - improved model\nsummary(lm(mbi_cy ~ gender + stud_h + health + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + health + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.8162  -2.9928  -0.4667   2.4683  15.9657 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          4.698604   4.070738   1.154 0.248719    \ngender              -1.105546   0.309482  -3.572 0.000373 ***\nstud_h              -0.048975   0.008804  -5.563 3.54e-08 ***\nhealth              -0.191435   0.140404  -1.363 0.173092    \nNatLang              3.019741   4.105918   0.735 0.462257    \ncesd                 0.268615   0.168627   1.593 0.111534    \nstai_t               0.114433   0.092739   1.234 0.217566    \nNatLang:cesd        -0.075307   0.175001  -0.430 0.667067    \nNatLang:stai_t      -0.058308   0.095770  -0.609 0.542796    \ncesd:stai_t         -0.002270   0.002894  -0.784 0.432989    \nNatLang:cesd:stai_t  0.001333   0.003047   0.438 0.661762    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.081 on 870 degrees of freedom\nMultiple R-squared:  0.2138,\tAdjusted R-squared:  0.2048 \nF-statistic: 23.66 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model 4\n\nMBI_cy_bestfit <- lm(mbi_cy ~ gender + stud_h + health +  NatLang*cesd*stai_t, data = FinalRecoded2)\nsummary(MBI_cy_bestfit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_cy ~ gender + stud_h + health + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.8162  -2.9928  -0.4667   2.4683  15.9657 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          4.698604   4.070738   1.154 0.248719    \ngender              -1.105546   0.309482  -3.572 0.000373 ***\nstud_h              -0.048975   0.008804  -5.563 3.54e-08 ***\nhealth              -0.191435   0.140404  -1.363 0.173092    \nNatLang              3.019741   4.105918   0.735 0.462257    \ncesd                 0.268615   0.168627   1.593 0.111534    \nstai_t               0.114433   0.092739   1.234 0.217566    \nNatLang:cesd        -0.075307   0.175001  -0.430 0.667067    \nNatLang:stai_t      -0.058308   0.095770  -0.609 0.542796    \ncesd:stai_t         -0.002270   0.002894  -0.784 0.432989    \nNatLang:cesd:stai_t  0.001333   0.003047   0.438 0.661762    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.081 on 870 degrees of freedom\nMultiple R-squared:  0.2138,\tAdjusted R-squared:  0.2048 \nF-statistic: 23.66 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(MBI_cy_bestfit)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4991.097\n```\n:::\n\n```{.r .cell-code}\n#BIC\nglance(MBI_cy_bestfit)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5048.47\n```\n:::\n:::\n\n\n-   Variables that increased the adjusted r-squared of the model were:\n\n    -   Hours studied (stud_h)\n    -   Health satisfaction (health)\n\nA 4-way interaction model for MBI-cy did not improve the prediction of MBI-cy like it did in the MBI-ex.The best-fitting linear regression model for MBI_cy as determined by adjusted R-squared values & AIC & BIC includes gender, hours studied, health satisfaction, and the 3-way interaction between native language, depression, and anxiety as explanatory variables. This has an Adjusted R-Squared value of 0.2048, suggesting some of the the variance in MBI cynicism scores of medical school students is explained by variance in the explanatory variables. The AIC of 4991 & BIC of 5048 also confirms this is the best-fitting model.\n\n-   Explanatory variables significant at the 0.001 level are:\n\n    -   Gender\n    -   Hours studying (stud_h)\n\nIn this model, gender has a coefficient of -1.105546, suggesting being female is predicted to decrease MBI-cy score. Hours studying has a coefficient of -0.048975, suggesting that studying more hours predicts lower MBI-cy score. These coefficients are both counter to what would be expected.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Cynicism Stargazer model\n\nstargazer(model_cy_1, model_cy_2, model_cy_3, MBI_cy_bestfit, align = TRUE, column.sep.width = \"-1pt\",  no.space = TRUE, type = \"text\", title=\"Table 4: Comparison MBI Cynicism Regression Results\", column.labels=c(\"Model 1\",\"Model 2\", \"Model 3\", \"Model 4\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nTable 4: Comparison MBI Cynicism Regression Results\n============================================================================================================\n                                                      Dependent variable:                                   \n                    ----------------------------------------------------------------------------------------\n                                                             mbi_cy                                         \n                          Model 1             Model 2               Model 3                 Model 4         \n                            (1)                 (2)                   (3)                     (4)           \n------------------------------------------------------------------------------------------------------------\nNatLang                   -0.658              -0.650                 3.266                   3.020          \n                          (0.570)             (0.571)               (4.176)                 (4.106)         \ncesd                                                                 0.250                   0.269          \n                                                                    (0.172)                 (0.169)         \nstai_t                                                               0.111                   0.114          \n                                                                    (0.094)                 (0.093)         \nNatLang:cesd                                                        -0.065                   -0.075         \n                                                                    (0.178)                 (0.175)         \nNatLang:stai_t                                                      -0.059                   -0.058         \n                                                                    (0.097)                 (0.096)         \ncesd:stai_t                                                         -0.002                   -0.002         \n                                                                    (0.003)                 (0.003)         \nNatLang:cesd:stai_t                                                  0.001                   0.001          \n                                                                    (0.003)                 (0.003)         \ngender                                         0.091               -1.026***               -1.106***        \n                                              (0.333)               (0.314)                 (0.309)         \nstud_h                                                                                     -0.049***        \n                                                                                            (0.009)         \nhealth                                                                                       -0.191         \n                                                                                            (0.140)         \nConstant                 10.671***           10.601***               2.703                   4.699          \n                          (0.547)             (0.605)               (4.073)                 (4.071)         \n------------------------------------------------------------------------------------------------------------\nObservations                881                 881                   881                     881           \nR2                         0.002               0.002                 0.184                   0.214          \nAdjusted R2               0.0004              -0.001                 0.177                   0.205          \nResidual Std. Error  4.576 (df = 879)    4.578 (df = 878)      4.152 (df = 872)         4.081 (df = 870)    \nF Statistic         1.332 (df = 1; 879) 0.703 (df = 2; 878) 24.641*** (df = 8; 872) 23.659*** (df = 10; 870)\n============================================================================================================\nNote:                                                                            *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n\n### Academic Efficacy Burnout MBI-ea\n\nAs with the prior 2 MBI sub-scales, I first created a linear regression model with NatLang as the only explanatory variable and academic efficacy burnout MBI_ea as the outcome. NatLang is not a statistically significant explanatory variable in the model with a p-value of 0.764. The Adjusted R-squared of -0.001035 shows the model is a very bad for predicting the outcome variable MBI_ea score. The AIC of this model is 5197 & BIC of this model is 5212.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Academic Efficacy NatLang Alone\nmodel_ea_1 <- lm(mbi_ea ~ NatLang, data = FinalRecoded2)\nsummary(model_ea_1)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ NatLang, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.2441  -3.2441  -0.2441   3.7559  11.7559 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  24.0714     0.5511  43.678   <2e-16 ***\nNatLang       0.1727     0.5744   0.301    0.764    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.611 on 879 degrees of freedom\nMultiple R-squared:  0.0001028,\tAdjusted R-squared:  -0.001035 \nF-statistic: 0.09041 on 1 and 879 DF,  p-value: 0.7637\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ea_1)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5197.268\n```\n:::\n\n```{.r .cell-code}\n#BIC\nglance(model_ea_1)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5211.611\n```\n:::\n:::\n\n\nFor the second model, I added the second explanatory variable of gender, based on previous findings of its impact on burnout. In this model, neither NatLang (p-value = 0.801) or gender (p-value = 0.363) are statistically significant. The fit of the model is still very poor, as indicated by the Adjusted R-squared of -0.001231. Still, very little of the variance in academic efficacy burnout is explained by the variance in gender and native language status. The AIC & BIC are slightly higher at 5198 at 5218, suggesting a poor fit of this model compared to the previous model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear regression model NatLang & gender\nmodel_ea_2 <- lm(mbi_ea ~ NatLang + gender, data = FinalRecoded2)\nsummary(model_ea_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ NatLang + gender, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.4521  -3.1466  -0.1466   3.5479  11.8534 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  24.3071     0.6090  39.913   <2e-16 ***\nNatLang       0.1450     0.5753   0.252    0.801    \ngender       -0.3055     0.3358  -0.910    0.363    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.611 on 878 degrees of freedom\nMultiple R-squared:  0.001045,\tAdjusted R-squared:  -0.001231 \nF-statistic: 0.4591 on 2 and 878 DF,  p-value: 0.632\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ea_2)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5198.438\n```\n:::\n\n```{.r .cell-code}\n#BIC\nglance(model_ea_2)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5217.562\n```\n:::\n:::\n\n\nFor the third linear regression model, I added the 3-way interaction of NatLang x Depression (cesd) x Anxiety (stai_t) as an explanatory variable in addition to gender, with the outcome variable of mbi_ea score. In this model, gender is statistically significant at the 0.001 level with a p-value of 0.00167 & a coefficient of 1.13175. The positive coefficient suggests being female medical student predicts increased academic efficacy scores, which translate to lower burnout. This is counter to the expectation that women experience worse burnout than men. The Adjusted R-Squared of this model is 0.261, suggesting a much better fit than prior models. The AIC of 4937 & BIC of 4985 are the lowest of the models so far, also suggesting the best fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Model with gender & 3 way interaction NatLang x Depression x Anxiety\nmodel_ea_3 <- lm(mbi_ea ~ gender +  NatLang*cesd*stai_t, data = FinalRecoded2)\nsummary(model_ea_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + NatLang * cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.1109  -2.5462   0.0327   2.5598  15.3027 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         27.813080   3.885897   7.157 1.74e-12 ***\ngender               1.131753   0.300048   3.772 0.000173 ***\nNatLang              4.651150   3.984162   1.167 0.243364    \ncesd                -0.011546   0.163661  -0.071 0.943774    \nstai_t              -0.050205   0.089957  -0.558 0.576925    \nNatLang:cesd        -0.218781   0.169865  -1.288 0.198098    \nNatLang:stai_t      -0.118535   0.092906  -1.276 0.202344    \ncesd:stai_t         -0.001632   0.002808  -0.581 0.561367    \nNatLang:cesd:stai_t  0.004288   0.002957   1.450 0.147380    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.962 on 872 degrees of freedom\nMultiple R-squared:  0.2678,\tAdjusted R-squared:  0.261 \nF-statistic: 39.86 on 8 and 872 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(model_ea_3)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4936.793\n```\n:::\n\n```{.r .cell-code}\n#BIC\nglance(model_ea_3)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4984.603\n```\n:::\n:::\n\n\nTo determine the best model, I added the control variables of hours studied, having a partner, job status, consulting a psychotherapist in past 12 months, & health satisfaction to see the impact on the adjusted R squared value. I also tried the 4 way interaction model between gender x natlang x CES-D x STAI-T to predict MBI academic efficacy, but this did not improve the fit of the model or make natlang statistically significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Control variables\n\n##hours studied strengthens model \nsummary(lm(mbi_ea ~ gender + stud_h + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + NatLang * cesd * stai_t, \n    data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.8518  -2.3631   0.0706   2.3959  14.1986 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         26.624521   3.792084   7.021 4.43e-12 ***\ngender               1.229823   0.292848   4.200 2.95e-05 ***\nstud_h               0.056874   0.008330   6.827 1.62e-11 ***\nNatLang              4.755003   3.883908   1.224    0.221    \ncesd                -0.032317   0.159571  -0.203    0.840    \nstai_t              -0.059291   0.087703  -0.676    0.499    \nNatLang:cesd        -0.209436   0.165595  -1.265    0.206    \nNatLang:stai_t      -0.114267   0.090570  -1.262    0.207    \ncesd:stai_t         -0.001289   0.002738  -0.471    0.638    \nNatLang:cesd:stai_t  0.003940   0.002883   1.367    0.172    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.862 on 871 degrees of freedom\nMultiple R-squared:  0.305,\tAdjusted R-squared:  0.2978 \nF-statistic: 42.46 on 9 and 871 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##partner - weakens model \nsummary(lm(mbi_ea ~ gender + stud_h + part + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + part + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.8874  -2.3859   0.0561   2.3968  14.2425 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         26.493652   3.808242   6.957 6.84e-12 ***\ngender               1.224707   0.293273   4.176 3.27e-05 ***\nstud_h               0.057175   0.008369   6.832 1.57e-11 ***\npart                 0.105619   0.266303   0.397    0.692    \nNatLang              4.817945   3.889028   1.239    0.216    \ncesd                -0.028098   0.160002  -0.176    0.861    \nstai_t              -0.058206   0.087788  -0.663    0.507    \nNatLang:cesd        -0.213497   0.165991  -1.286    0.199    \nNatLang:stai_t      -0.115459   0.090663  -1.273    0.203    \ncesd:stai_t         -0.001350   0.002744  -0.492    0.623    \nNatLang:cesd:stai_t  0.004008   0.002890   1.387    0.166    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.864 on 870 degrees of freedom\nMultiple R-squared:  0.3051,\tAdjusted R-squared:  0.2971 \nF-statistic:  38.2 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##having job -weakens model\nsummary(lm(mbi_ea ~ gender + stud_h + job + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + job + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.7756  -2.3896   0.0396   2.4330  14.1723 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         26.816122   3.810460   7.038 3.97e-12 ***\ngender               1.234825   0.293116   4.213 2.79e-05 ***\nstud_h               0.055997   0.008493   6.593 7.45e-11 ***\njob                 -0.149950   0.279912  -0.536    0.592    \nNatLang              4.635984   3.891845   1.191    0.234    \ncesd                -0.034648   0.159695  -0.217    0.828    \nstai_t              -0.062373   0.087928  -0.709    0.478    \nNatLang:cesd        -0.206920   0.165729  -1.249    0.212    \nNatLang:stai_t      -0.111141   0.090795  -1.224    0.221    \ncesd:stai_t         -0.001226   0.002742  -0.447    0.655    \nNatLang:cesd:stai_t  0.003871   0.002887   1.341    0.180    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.864 on 870 degrees of freedom\nMultiple R-squared:  0.3052,\tAdjusted R-squared:  0.2972 \nF-statistic: 38.21 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## seen psychiatrist - weakens model\nsummary(lm(mbi_ea ~ gender + stud_h + psyt + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + psyt + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.8539  -2.3522   0.0854   2.3919  14.1874 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         26.622372   3.794358   7.016 4.58e-12 ***\ngender               1.231791   0.294183   4.187 3.11e-05 ***\nstud_h               0.056819   0.008367   6.791 2.07e-11 ***\npsyt                -0.024910   0.331408  -0.075    0.940    \nNatLang              4.755824   3.886142   1.224    0.221    \ncesd                -0.032506   0.159682  -0.204    0.839    \nstai_t              -0.059116   0.087784  -0.673    0.501    \nNatLang:cesd        -0.209268   0.165705  -1.263    0.207    \nNatLang:stai_t      -0.114333   0.090626  -1.262    0.207    \ncesd:stai_t         -0.001286   0.002740  -0.469    0.639    \nNatLang:cesd:stai_t  0.003941   0.002885   1.366    0.172    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.864 on 870 degrees of freedom\nMultiple R-squared:  0.305,\tAdjusted R-squared:  0.297 \nF-statistic: 38.17 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## health sat - improved model\nsummary(lm(mbi_ea ~ gender + stud_h + health + NatLang*cesd*stai_t , data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + health + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.7917  -2.4047   0.0251   2.4301  13.9331 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         25.335057   3.846352   6.587 7.77e-11 ***\ngender               1.223914   0.292423   4.185 3.14e-05 ***\nstud_h               0.057144   0.008319   6.869 1.23e-11 ***\nhealth               0.252819   0.132665   1.906    0.057 .  \nNatLang              4.963220   3.879593   1.279    0.201    \ncesd                -0.033881   0.159332  -0.213    0.832    \nstai_t              -0.053297   0.087628  -0.608    0.543    \nNatLang:cesd        -0.206154   0.165354  -1.247    0.213    \nNatLang:stai_t      -0.120443   0.090491  -1.331    0.184    \ncesd:stai_t         -0.001189   0.002734  -0.435    0.664    \nNatLang:cesd:stai_t  0.003955   0.002879   1.374    0.170    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.856 on 870 degrees of freedom\nMultiple R-squared:  0.3078,\tAdjusted R-squared:  0.2999 \nF-statistic:  38.7 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n##4way interaction \nsummary(lm(mbi_ea ~ gender*NatLang*cesd*stai_t, data = FinalRecoded2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender * NatLang * cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.3685  -2.4832   0.0514   2.5795  15.2401 \n\nCoefficients:\n                            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                31.267590   6.688580   4.675 3.41e-06 ***\ngender                     -3.431569   8.816710  -0.389    0.697    \nNatLang                     2.040716   6.835435   0.299    0.765    \ncesd                        0.023367   0.416056   0.056    0.955    \nstai_t                     -0.182517   0.185025  -0.986    0.324    \ngender:NatLang              2.872413   9.004829   0.319    0.750    \ngender:cesd                -0.021423   0.468730  -0.046    0.964    \nNatLang:cesd               -0.246782   0.424149  -0.582    0.561    \ngender:stai_t               0.173021   0.221765   0.780    0.435    \nNatLang:stai_t             -0.006712   0.189646  -0.035    0.972    \ncesd:stai_t                -0.001190   0.008502  -0.140    0.889    \ngender:NatLang:cesd         0.028545   0.479327   0.060    0.953    \ngender:NatLang:stai_t      -0.133128   0.227624  -0.585    0.559    \ngender:cesd:stai_t         -0.001122   0.009275  -0.121    0.904    \nNatLang:cesd:stai_t         0.003698   0.008686   0.426    0.670    \ngender:NatLang:cesd:stai_t  0.000934   0.009512   0.098    0.922    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.967 on 865 degrees of freedom\nMultiple R-squared:  0.2718,\tAdjusted R-squared:  0.2592 \nF-statistic: 21.53 on 15 and 865 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n-   Variables that increased the adjusted r-squared of the model were:\n\n    -   Hours studied (stud_h)\n    -   Health satisfaction (health)\n\nThe best-fitting linear regression model for MBI_cy as determined by adjusted R-squared values includes gender, hours studied, health satisfaction, and the 3-way interaction between native language, depression, and anxiety as explanatory variables. This has an Adjusted R-Squared value of 0.298, suggesting some of the the variance in MBI academic efficacy scores of medical school students is explained by variance in the explanatory variables. The AIC of 4893 & BIC of 4951 are the lowest of any of the linear regression models, supporting the fit of this model.\n\n-   Explanatory variables significant at the 0.1 level are:\n\n    -   Health satisfaction (health)\n\n-   Explanatory variables significant at the 0.05 level are:\n\n    -   Anxiety (stai_t)\n\n-   Explanatory variables significant at the 0.001 level are:\n\n-   Gender\n\n-   Hours studied (stud_h)\n\nThe coefficient of health satisfaction is 0.2346, suggesting the more satisfied with health, the higher predicted MBI-ea score (lower burnout). The coefficient for anxiety is -0.180668, suggesting higher anxiety scores predict lower MBI_ea scores (higher burnout). Gender has a coefficient of 1.233, suggesting that being female predicts increased MBI_ea scores (lower burnout). Lastly, stud_h has a coefficient of 0.057054, suggesting the more hours studied the higher the predicted MBI-ea scores (lower burnout). The last 2 coefficients are not what are expected. In none of the models for predicting MBI_ea is NatLang statistically significant explanatory variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Best fit model academic efficacy burnout \n\nMBI_ea_bestfit <- lm(mbi_ea ~ gender + stud_h + health +  NatLang*cesd*stai_t, data = FinalRecoded2)\nsummary(MBI_ea_bestfit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ea ~ gender + stud_h + health + NatLang * cesd * \n    stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.7917  -2.4047   0.0251   2.4301  13.9331 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         25.335057   3.846352   6.587 7.77e-11 ***\ngender               1.223914   0.292423   4.185 3.14e-05 ***\nstud_h               0.057144   0.008319   6.869 1.23e-11 ***\nhealth               0.252819   0.132665   1.906    0.057 .  \nNatLang              4.963220   3.879593   1.279    0.201    \ncesd                -0.033881   0.159332  -0.213    0.832    \nstai_t              -0.053297   0.087628  -0.608    0.543    \nNatLang:cesd        -0.206154   0.165354  -1.247    0.213    \nNatLang:stai_t      -0.120443   0.090491  -1.331    0.184    \ncesd:stai_t         -0.001189   0.002734  -0.435    0.664    \nNatLang:cesd:stai_t  0.003955   0.002879   1.374    0.170    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.856 on 870 degrees of freedom\nMultiple R-squared:  0.3078,\tAdjusted R-squared:  0.2999 \nF-statistic:  38.7 on 10 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n.\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object '.' not found\n```\n:::\n\n```{.r .cell-code}\n#AIC\nglance(MBI_ea_bestfit)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4891.194\n```\n:::\n\n```{.r .cell-code}\n#BIC\nglance(MBI_ea_bestfit)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4948.566\n```\n:::\n:::\n\n\nAll models for MBI_ea can be compared in the stargazer table below\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Academic Efficacy Stargazer model\n\nstargazer(model_ea_1, model_ea_2, model_ea_3, MBI_ea_bestfit, align = TRUE, column.sep.width = \"-1pt\",  no.space = TRUE, type = \"text\", title=\"Table 4: Comparison MBI Academic Efficacy Regression Results\", column.labels=c(\"Model 1\",\"Model 2\", \"Model 3\", \"Model 4\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nTable 4: Comparison MBI Academic Efficacy Regression Results\n============================================================================================================\n                                                      Dependent variable:                                   \n                    ----------------------------------------------------------------------------------------\n                                                             mbi_ea                                         \n                          Model 1             Model 2               Model 3                 Model 4         \n                            (1)                 (2)                   (3)                     (4)           \n------------------------------------------------------------------------------------------------------------\nNatLang                    0.173               0.145                 4.651                   4.963          \n                          (0.574)             (0.575)               (3.984)                 (3.880)         \ncesd                                                                -0.012                   -0.034         \n                                                                    (0.164)                 (0.159)         \nstai_t                                                              -0.050                   -0.053         \n                                                                    (0.090)                 (0.088)         \nNatLang:cesd                                                        -0.219                   -0.206         \n                                                                    (0.170)                 (0.165)         \nNatLang:stai_t                                                      -0.119                   -0.120         \n                                                                    (0.093)                 (0.090)         \ncesd:stai_t                                                         -0.002                   -0.001         \n                                                                    (0.003)                 (0.003)         \nNatLang:cesd:stai_t                                                  0.004                   0.004          \n                                                                    (0.003)                 (0.003)         \ngender                                        -0.305               1.132***                 1.224***        \n                                              (0.336)               (0.300)                 (0.292)         \nstud_h                                                                                      0.057***        \n                                                                                            (0.008)         \nhealth                                                                                       0.253*         \n                                                                                            (0.133)         \nConstant                 24.071***           24.307***             27.813***               25.335***        \n                          (0.551)             (0.609)               (3.886)                 (3.846)         \n------------------------------------------------------------------------------------------------------------\nObservations                881                 881                   881                     881           \nR2                        0.0001               0.001                 0.268                   0.308          \nAdjusted R2               -0.001              -0.001                 0.261                   0.300          \nResidual Std. Error  4.611 (df = 879)    4.611 (df = 878)      3.962 (df = 872)         3.856 (df = 870)    \nF Statistic         0.090 (df = 1; 879) 0.459 (df = 2; 878) 39.859*** (df = 8; 872) 38.695*** (df = 10; 870)\n============================================================================================================\nNote:                                                                            *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n\n## Diagnostic Models\n\n### MBI Emotional Exhaustion\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Diagnostic Models Emotional Exhaustion\n\n fit_ex <- lm(mbi_ex ~ sex + stud_h + health + job + gender*NatLang*cesd*stai_t, data = FinalRecoded2)\n\n##MBI_ex Residuals vs. Fitted\n\n\nplot(fit_ex, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-40-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-40-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-40-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-40-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-40-6.png){width=672}\n:::\n:::\n\n\nThe first diagnostic model of residuals vs. fitted value shows a relatively horizontal line that bounces randomly around the zero line, suggesting linearity and constant variance for the MBI_ex linear regression model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_Ex Normal Q-Q\nplot(fit_ex, which = 2) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\nMost of the points of the MBI_ex linear regression Q-Q plot fall along the line, supporting the assumption of normality.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_Ex Scale Location\nplot(fit_ex, which = 3) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\nThe Scale-Location plot of the MBI-ex linear regression model is nearly perfectly horizontal without increasing or decreasing, supporting the assumption of constant variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_Ex Cook's Distance\nplot(fit_ex, which = 4) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\nThe Cook's distance plot of the MBI_ex linear regression model measures the presence of influential outliers. There appears to be 3 outliers which are influence the model, as shown by at Obs. number at 1, 526, and 756. None of them have a Cook's distance of 1, with the most being 0.20. However with a sample size of n = 881, 4/n = 0.00454 which means taking a closer look at the leverage of outliers in the next 2 diagnostic plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_Ex Residuals vs. leverage \nplot(fit_ex, which = 5) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\nNot points in the Residuals vs. Leverage plot of the MBI_ex fall outside of the dotted lines, including the 3 observations from the prior Cook's distance plot, suggesting that these observations are not influential in the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_Ex Cook's Distance vs Leverage\nplot(fit_ex, which = 6) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\nThe final diagnostic plot of Cook's Distance vs. Leverage for the MBI-ex plot shows that while there are some residuals, they don't have strong leverage. Observation 1 & 526 both have a leverage of over 0.5, but this is paired with a low Cook's distance making them not influential.\n\nOverall the diagnostic models supports the goodness of fit of the emotional exhaustion MBI model and the assumptions of linearity, constant variance, and normality, but there are some outliers though they do not appear to influence the model strongly.\n\n### MBI Cynicism\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Diagnostic model\nfit_cy <- lm(mbi_cy ~ gender + stud_h + health +  NatLang*cesd*stai_t, data = FinalRecoded2)\n\n##MBI_ex Residuals vs. Fitted\nplot(fit_cy, which = 1) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\nThe diagnostic plot of residuals vs. fitted values for the MBI_cy linear regression model is mostly horizontal around the 0 line, though there is some slight funneling in the bottom left half of the plot. This suggests linearity but slight violation of constant variance assumption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_cy Q-Q plot\nplot(fit_cy, which = 2) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\nThe Q-Q plot for the MBI_cy linear regression supports the assumption of normality, as the points all fall along the line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_cy Scale Location\nplot(fit_cy, which = 3) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\nThe Scale-Location plot of the MBI_cy linear regression shows some increasing trend, suggesting the model may violate the assumption of constant variance.\n\nTo test further if the model violates the assumption of constant variance, I will run a Breusch-Pagan Test on the model.\n\n-   The Null Hypothesis (H0) for this test is that residuals are homoscedastic (i.e. evenly spread)\n\n-   The Alternative Hypothesis (HA) hypothesis is that heteroscedasticity is present (residuals are not evenly distributed)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Breusch-Pagan Test\nlibrary(zoo)\nlibrary(lmtest)\nbptest(fit_cy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  fit_cy\nBP = 41.719, df = 10, p-value = 8.413e-06\n```\n:::\n:::\n\n\nWith a p-value of 3.722e-06, we confidently reject the null hypothesis that residuals are homoscedastic at the 0.05 significance level. This confirms that that this model violates the assumption of linearity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_cy Cook's distance\nplot(fit_cy, which = 4) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\nThe Cook's distance plot for the MBI-cy linear regression shows 1 influential outlier at observation number 29. This observation does not have a Cook's distance of 1, but is greater than 4/n, which with n=881 is 0.00454, which means taking a closer look at the potential of an influential outlier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_cy Residuals vs Leverage\nplot(fit_cy, which = 5) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\nThe Residuals vs Leverage plot for MBI-cy linear regression model falls within the dashed red line, suggesting that residuals lack leverage to strongly influence the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##MBI_cy Cook's dist. vs Leverage\nplot(fit_cy, which = 6) \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\nLastly, the diagnostic plot of Cook's dist. vs. Leverage for the MBI_cy linear regression model suggests that any outliers in the model do not have strong leverage on the model.\n\nOverall the diagnostic models mostly support the fit of the cynicism MBI model and the assumptions of linearity and normality, as well as the lack of influential outliers. The diagnostic of scale location plot & Breusch-Pagan test suggesting violation of the assumption of constant variance.\n\n### MBI Acamemic Efficacy\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ea <- lm(mbi_ea ~ gender + stud_h + health +  NatLang*cesd*stai_t, data = FinalRecoded2)\n\n#MBI_ea Residuals vs. Fitted\nplot(fit_ea, which = 1)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\nThe first diagnostic plot of residuals vs. fitted values for the MBI_ea linear regression has a horizontal trend line without any funneling, supporting the assumptions of linearity and constant variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI_ea Q-Q plot\nplot(fit_ea, which = 2)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\nThe diagnostic Q-Q plot for the MBI-ea linear regression model supports the assumption of normality, as most of the points fall along the line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI_ea scale-location\nplot(fit_ea, which = 3)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\nThe scale-location diagnostic plot for the MBI_ea linear regression model is approximately horizontal, supporting the assumption of constant variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI_ea\nplot(fit_ea, which = 4)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\nThe Cook's distance diagnostic plot for the MBI_ea linear regression model suggests the lack of influential observations (outliers). None of the observations have a Cook's distance near 1, with the highest being less than 0.030, suggesting the outliers don't strongly impact the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI_ea residuals vs. leverage\nplot(fit_ea, which = 5)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\nThe residuals vs. leverage plot for the mbi_ea linear regression model further supports the lack of influential observations (outliers), as does the Cook's Distances vs. Leverage plot below\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#MBI_ea Cooks Distance vs. Leverage\nplot(fit_ea, which = 6)\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\nOverall these diagnostic plots support the goodness of fit of the academic efficacy MBI linear regression model, supporting the assumptions of linearity, constant variance, and normality as well as suggesting the lack of influential outliers.\n\n### Discussion\n\nThe relationship between variables was further explored though visualizations. Figure 4 below is a correlation table between hours studied (stud_h), CES-D scores. STAI-T scores & the 3 MBI sub-scales. Most correlations are positive & shown in red, with the exception of mostly blue negative correlations between variables & MBI-ea (where lower scores = higher burnout). The strongest correlation is between depression & anxiety (0.7). Depression & anxiety are moderately correlated with the 3 MBI sub-scores. Hours studied has a low correlation with the other variables. Interestingly, while the 3 MBI sub-scores are supposed to be scored separately, they are moderately correlated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Correlation Table\nFinalRecoded2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 881 × 22\n      id   age  year   sex glang  part   job stud_h health  psyt  jspe qcae_cog\n   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>    <dbl>\n 1     2    18     1     1   120     1     0     56      3     0    88       62\n 2     4    26     4     1     1     1     0     20      4     0   109       55\n 3     9    21     3     2     1     0     0     36      3     0   106       64\n 4    10    21     2     2     1     0     1     51      5     0   101       52\n 5    13    21     3     1     1     1     0     22      4     0   102       58\n 6    14    26     5     2     1     1     1     10      2     0   102       48\n 7    17    23     5     2     1     1     0     15      3     0   117       58\n 8    21    23     4     1     1     1     1      8      4     0   118       65\n 9    23    23     4     2     1     1     1     20      2     0   118       69\n10    24    22     2     2     1     1     0     20      5     0   108       56\n# … with 871 more rows, and 10 more variables: qcae_aff <dbl>, amsp <dbl>,\n#   erec_mean <dbl>, cesd <dbl>, stai_t <dbl>, mbi_ex <dbl>, mbi_cy <dbl>,\n#   mbi_ea <dbl>, NatLang <dbl>, gender <dbl>\n```\n:::\n\n```{.r .cell-code}\nFinalCorr <- FinalRecoded2[, c(8,16,17,18, 19, 20)]\n\nggcorr(FinalCorr, method = c(\"everything\", \"pearson\"), label = TRUE)  + ggplot2::labs(title = \"Figure 4: Correlation Table between Continuous Variables\")\n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualization TwoContinous,1 categorical\n\nFinalRecoded2$NatLang <- as.factor(FinalRecoded2$NatLang)\n\ntwi_mbi_ee <- lm(mbi_ex ~ NatLang*cesd*stai_t, data = FinalRecoded2)\nsummary(twi_mbi_ee)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mbi_ex ~ NatLang * cesd * stai_t, data = FinalRecoded2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.0436  -2.7980  -0.1549   2.5024  14.0240 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)  \n(Intercept)           8.5812961  4.0196295   2.135   0.0331 *\nNatLang1             -1.4746673  4.1204029  -0.358   0.7205  \ncesd                  0.3925847  0.1690935   2.322   0.0205 *\nstai_t                0.0909869  0.0929279   0.979   0.3278  \nNatLang1:cesd        -0.0535969  0.1756531  -0.305   0.7603  \nNatLang1:stai_t       0.0505873  0.0960912   0.526   0.5987  \ncesd:stai_t          -0.0032561  0.0029022  -1.122   0.2622  \nNatLang1:cesd:stai_t  0.0005094  0.0030582   0.167   0.8677  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.098 on 873 degrees of freedom\nMultiple R-squared:  0.3939,\tAdjusted R-squared:  0.389 \nF-statistic: 81.04 on 7 and 873 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n#model prediction\npred <- expand.grid(cesd=c(min(FinalRecoded2$cesd),0,max(FinalRecoded2$cesd)),stai_t=c(min(FinalRecoded2$stai_t),0,max(FinalRecoded2$stai_t)), NatLang = factor(0:1))\npred$mbi_ex <- predict(twi_mbi_ee,pred)\n\n\n\n#new facet labels\nsupp.labs <- c(\"Non-Native Language\", \"Native Language\")\nnames(supp.labs) <- c(0, 1)\n\n\nggplot(FinalRecoded2,aes(x=cesd,y=mbi_ex,color=stai_t))  +geom_point()+facet_grid(~NatLang, labeller = labeller(NatLang = supp.labs)) +\ngeom_line(data=pred,aes(group=stai_t)) + labs(title = \"Figure 5: Plot Emotional Burnout by Gender & Native Language\", x = \"CES-D Depression Score\", y = \"MBI_ex Score\") + theme(legend.position=\"bottom\") \n```\n\n::: {.cell-output-display}\n![](EmmaNarkewicz_FinalProject_WriteUp_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\nFigure 5 shows the 3-way interaction of gender, depression scores, & NatLang on MBI-ex scores. The graph shows that depression & anxiety scores are positively correlated, as are depression & MBI_ex scores. The slope of the 2 darker lines of MBI-ex score vs. CES-D are slightly steeper for Non-Native med students than Native students the plot, suggesting that when Non-Native & Native med students have the same CES-D score, the Native med student is predicted to have higher emotional exhaustion burnout.\n\nReturning to my research question:\n\n*Why are some medical students more likely to experience burnout than others?*\n\nThere is statistical supports my hypothesis that medical students whose native language was a commonly spoken language where they are in medical school will have lower burnout than medical students speaking the non-native language on the MBI emotional exhaustion sub-scale, but not the MBI cynicism or MBI academic efficacy sub-scores. With p-score of 0.0283 in the Welch's One-Sided T-test, I reject the hypothesis that there is no difference in the mean MBI-ex scores between native & not-native language speaking students. The difference in means between native & native language speakers on the MBI-cy & MBI-ea are not statistically significant.\n\nThrough further T-tests discovered that there was statistically significant difference in anxiety & depression levels for native and non-native language speaking medical students in the direction I expected. Through running various linear regression models, I found that the importance 3-way interaction between NatLang x Anxiety x Depression was a strong explanatory variable for burnout on all three sub scales based on the Adjusted-R Squared values. Gender, hours studied, and health satisfaction also explain why some medical students are more likely to experience burnout than others on all three sub scales. For emotional exhaustion burnout, having a partner also impacted burnout.\n\nBased on Adjusted R-squared values, AIC values, and diagnostic plots, the linear regression models are a good fit to explain variance in the outcome variables of burnout on each of the 3 MBI sub-scales. In the MBI-cy sub-scale, there was a violation to the assumption of constant variance in the Scale Location plot & Breusch-Pagan Test. In the linear regression models, Native Language was found to be a statistically significant predictor of emotional exhaustion burnout, but not cynicism or academic efficacy burn-out. A systematic review of burnout found that emotional exhaustion burnout, characterized by emotional & physical fatigue, is most frequently used to measure the concept burnout (Doulougeri et al., 2016).\n\nThis current sample had relatively few non-native language speaking medical students (71) & was in the country of Switzerland, meaning the findings can't be generalized. Future research should be done testing the impact of speaking a native language on burnout in a larger, global sample of medical students. It also might be that speaking a non-native language is proxy for immigration status, so that should be examined as well. There were also many interesting interactions with NatLang in the models, including with gender, anxiety, & depression. Future research should be done to understand the relationship between these variable in order to make more meaningful interventions. Additionally, it is important to investigate potential protective factors against burnout such as health satisfaction, as there were not many identified in this sample.\n\nConducting this final project was challenging but interesting. Having 3 outcome variables was a lot of work to conduct tests for, & the 3 & 4-way interactions were not easy to interpret or visualize. Overall I am proud of this work & the statistical knowledge I have gained in this course.\n\nMedical students & health care workers around the world do life saving work, under stressful & long work conditions. It is critical that we better understand, identify, & treat the mental health needs & burnout of health care workers. It is neither fair nor feasible to expect health care workers to sacrifice their health & well-being in service of others.\n\n## Works Cited\n\nCarrard, V., Bourquin, C., Berney, S, Schlegel, K., Gaume, J., Bart, P-A., Preisig M., Mast, M. A., & Berney, A. (2022). The relationship between medical students' empathy, mental health, and burnout: A cross-sectional study, Medical Teacher, 44:12, 1392-1399, DOI: 10.1080/0142159X.2022.2098708\n\nDoulougeri, K., Georganta, K., & Montgomery, A. (2016). \"Diagnosing\" burnout among healthcare professionals: Can we find consensus?, Cogent Medicine, 3:1, DOI: 10.1080/2331205X.2016.1237605\n\nGradiski, I. P., Borovecki, A., Ćurković, M., San-Martín, M., Delgado Bolton, R. C., & Vivanco, L. (2022). Burnout in International Medical Students: Characterization of Professionalism and Loneliness as Predictive Factors of Burnout. International journal of environmental research and public health, 19(3), 1385. https://doi.org/10.3390/ijerph19031385\n\nGoebert., D., Thompson., D., Takeshita., J., Beach, C., Bryson, P., Ephgrave, K., Kent. A., Kunkel., M., Schechter., J., Tate., J. (2009). Depressive Symptoms in Medical Students and Residents: A Multischool Study. Academic Medicine 84(2):p 236-241, DOI: 10.1097/ACM.0b013e31819391bb\n\nHlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables. R package version 5.2.3. https://CRAN.R-project.org/package=stargazer\n\nJennings, M.L. Medical Student Burnout: Interdisciplinary Exploration and Analysis. J Med Humanit 30, 253--269 (2009). https://doi.org/10.1007/s10912-009-9093-5\n\nKużelewska,E. (2016).Language Policy in Switzerland. Studies in Logic, Grammar and Rhetoric,45(1) 125-140. https://doi.org/10.1515/slgr-2016-0020\n\nMaslach, C., Jackson, S.E., & Jackson, Leiter, M. P. (Eds.) (1996). Maslach Burnout Inventory manual (3rd ed.).\n\nPaturel, A. (2020). Healing the very youngest healers. American Association of Medical Colleges (AAMC). https://www.aamc.org/news-insights/healing-very-youngest-healers#:\\~:text=In%20a%20recent%20study%20%2C%209.4,as%20their%20same%2Dage%20peers.\n\nPeters E. (2018). Compassion fatigue in nursing: A concept analysis. Nursing forum, 53(4), 466--480. https://doi.org/10.1111/nuf.12274\n\nRadloff, L.S. (1977). The CES-D Scale: a self-report depression scale for research in the general population. Applied Psychological Measurement, 1:385-401.\n\nRodriguez, S. Y. S., Carlotta, M. S.. (2017). Predictors of Burnout Syndrome in psychologists. Estudos De Psicologia (campinas), 34(Estud. psicol. (Campinas), 2017 34(1)), 141--150. https://doi.org/10.1590/1982-02752017000100014\n\nShin, H. S., Park, H., & Lee, Y. M. (2022). The relationship between medical students' empathy and burnout levels by gender and study years. Patient education and counseling, 105(2), 432--439. https://doi.org/10.1016/j.pec.2021.05.036\n\nTiesman, H., Weissman, D., Stone., D., Quinlan, K., & Chosewood, L. (2021). Suicide Prevention for Healthcare Workers. CDC. https://blogs.cdc.gov/niosh-science-blog/2021/09/17/suicide-prevention-hcw/\n\nWilliams, B., Beovich, B. Psychometric properties of the Jefferson Scale of Empathy: a COSMIN systematic review protocol. Syst Rev 8, 319 (2019). https://doi.org/10.1186/s13643-019-1240-0\n\nYahya, M. S., Abutiheen, A. A., & Al- Haidary, A. F. (2021). Burnout among medical students of the University of Kerbala and its correlates. Middle East Current Psychiatry, Ain Shams University, 28(1), 78. https://doi.org/10.1186/s43045-021-00152-2\n",
    "supporting": [
      "EmmaNarkewicz_FinalProject_WriteUp_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}