{
  "hash": "3b7dda0a3b5786ef153e2966e16feabc",
  "result": {
    "markdown": "---\ntitle: \"Homework 4\"\nauthor: \"Alexa Potter\"\ndescription: \"DACSS 603\"\ndate: \"04/24/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw4\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(car)\nlibrary(smss)\ndata(\"house.selling.price\", package = \"smss\")\ndf <- house.selling.price\nlibrary(alr4)\ndata(\"salary\", package = \"alr4\")\ndf <- salary\n```\n:::\n\n\n\n# Question 1\n\nFor recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.   \n\n\n## A \n\nA particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000.  Find the predicted selling price and the residual, and interpret.   \n\n::: {.cell}\n\n```{.r .cell-code}\na_predicted = (-10536 + (53.8*(1240)) + (2.84*(18000)))\na_predicted\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n\n```{.r .cell-code}\na_actual = 145000\n\na_residual = a_actual - a_predicted\n\na_residual\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37704\n```\n:::\n:::\n\nThe predicted selling price is $107,296. The residual is $37,704. This means the buyer bought the house $37,704 over recent data predicitons.   \n\n## B  \n\nFor fixed lot size, how much is the house selling price predicted to increase for each square foot increase in home size? Why?    \n\n::: {.cell}\n\n```{.r .cell-code}\n(-10536 + (53.8*(1000)) + (2.84*(1000)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 46104\n```\n:::\n\n```{.r .cell-code}\n(-10536 + (53.8*(1001)) + (2.84*(1000)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 46157.8\n```\n:::\n:::\n\nThe house selling price is predicted to increase by $53.80. This is the coefficient to the home size variable, each x1 unit increases by 53.8.  \n\n\n## C  \n\nAccording to this prediction equation, for fixed home size, how much would lot size need  to increase to have the same impact as a one-square-foot increase in home size?     \n\n\n::: {.cell}\n\n```{.r .cell-code}\n53.8/2.84\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\nLot size would need to increase by 18.94 to have the same impact as a 1 square foot increase in home size. \n\n\n# Question 2  \n\n(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all  faculty in a small Midwestern college collected in the early 1980s for presentation in legal  proceedings for which discrimination against women in salary was at issue. All persons in the data  hold tenured or tenure track positions; temporary faculty are not included. The variables include  degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a  factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree,  and salary, academic year salary in dollars.   \n  \n  \n\n::: {.cell}\n\n```{.r .cell-code}\nsalary\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    degree  rank    sex year ysdeg salary\n1  Masters  Prof   Male   25    35  36350\n2  Masters  Prof   Male   13    22  35350\n3  Masters  Prof   Male   10    23  28200\n4  Masters  Prof Female    7    27  26775\n5      PhD  Prof   Male   19    30  33696\n6  Masters  Prof   Male   16    21  28516\n7      PhD  Prof Female    0    32  24900\n8  Masters  Prof   Male   16    18  31909\n9      PhD  Prof   Male   13    30  31850\n10     PhD  Prof   Male   13    31  32850\n11 Masters  Prof   Male   12    22  27025\n12 Masters Assoc   Male   15    19  24750\n13 Masters  Prof   Male    9    17  28200\n14     PhD Assoc   Male    9    27  23712\n15 Masters  Prof   Male    9    24  25748\n16 Masters  Prof   Male    7    15  29342\n17 Masters  Prof   Male   13    20  31114\n18     PhD Assoc   Male   11    14  24742\n19     PhD Assoc   Male   10    15  22906\n20     PhD  Prof   Male    6    21  24450\n21     PhD  Asst   Male   16    23  19175\n22     PhD Assoc   Male    8    31  20525\n23 Masters  Prof   Male    7    13  27959\n24 Masters  Prof Female    8    24  38045\n25 Masters Assoc   Male    9    12  24832\n26 Masters  Prof   Male    5    18  25400\n27 Masters Assoc   Male   11    14  24800\n28 Masters  Prof Female    5    16  25500\n29     PhD Assoc   Male    3     7  26182\n30     PhD Assoc   Male    3    17  23725\n31     PhD  Asst Female   10    15  21600\n32     PhD Assoc   Male   11    31  23300\n33     PhD  Asst   Male    9    14  23713\n34     PhD Assoc Female    4    33  20690\n35     PhD Assoc Female    6    29  22450\n36 Masters Assoc   Male    1     9  20850\n37 Masters  Asst Female    8    14  18304\n38 Masters  Asst   Male    4     4  17095\n39 Masters  Asst   Male    4     5  16700\n40 Masters  Asst   Male    4     4  17600\n41 Masters  Asst   Male    3     4  18075\n42     PhD  Asst   Male    3    11  18000\n43 Masters Assoc   Male    0     7  20999\n44 Masters  Asst Female    3     3  17250\n45 Masters  Asst   Male    2     3  16500\n46 Masters  Asst   Male    2     1  16094\n47 Masters  Asst Female    2     6  16150\n48 Masters  Asst Female    2     2  15350\n49 Masters  Asst   Male    1     1  16244\n50 Masters  Asst Female    1     1  16686\n51 Masters  Asst Female    1     1  15000\n52 Masters  Asst Female    0     2  20300\n```\n:::\n:::\n\n\n\n## A  \n\nTest the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(salary~sex, data=salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  salary by sex\nt = 1.7744, df = 21.591, p-value = 0.09009\nalternative hypothesis: true difference in means between group Male and group Female is not equal to 0\n95 percent confidence interval:\n -567.8539 7247.1471\nsample estimates:\n  mean in group Male mean in group Female \n            24696.79             21357.14 \n```\n:::\n:::\n\nWe can use the independent t-test here because it is comparing the means of continuous and categorical variables.   \nThe p value here is not significant which means we fail to reject the null hypothesis that all population means are equal. \n\n## B  \n\nRun a multiple linear regression with salary as the outcome variable and everything else as  predictors, including sex. Assuming no interactions between sex and the other predictors,  obtain a 95% confidence interval for the difference in salary between males and females.  \n\nLinear regression:  \n\n::: {.cell}\n\n```{.r .cell-code}\nlm_salary <- lm(salary ~ degree + rank + sex + year + ysdeg, data =  salary)\nsummary(lm_salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n95% Confidence Interval for sexFemale is -697.8183 to 3030.56452  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lm_salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\n\n\n## C    \n\nInterpret your finding for each predictor variable; discuss (a) statistical significance, (b)  interpretation of the coefficient / slope in relation to the outcome variable and other variables    \n\ndegree  \n\nDegree is not statistically significant. Individuals with degree \"PhD\" make 1388.61 more than \"Master's\".  \n\nrank  \n\nRank is statistically significant. Individuals with rank \"Prof\" make 11118.76 more than \"Asst\" (constant) and individuals with rank \"Assoc\" make 5292.36 more than \"Asst\"\n\nsex  \nSex is not statistically significant. sexFemale reflects women make 1166.37 more than men. \n\nyear  \nYear is statistically significant. With each increase in year an individual makes 476.31 more. \n\nysdeg   \nYears since degree is not statistically significant. It also have a negative relationship with salary. This means the more years away from their degree, an individual makes 124.57 less. \n\n## D  \n\nChange the baseline category for the rank variable. Interpret the coefficients related to rank again.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank <- relevel(salary$rank, ref = \"Prof\")\nlm_salary2 <- lm(salary ~ degree + rank + sex + year + ysdeg, data =  salary)\nsummary(lm_salary2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nsexFemale     1166.37     925.57   1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nChanging the baseline of rank to \"Prof\" does not change the statisitically significant variables. It does however, change the relationship with \"Asst\" and \"Assoc\" level of rank, as well as degree level of \"Masters\". These variables now have a negative relationship.\n\n## E  \n\nFinkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote,  “[a] variable may reflect a position or status bestowed by the employer, in which case if there  is discrimination in the award of the position or status, the variable may be ‘tainted.’ ” Thus,  for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to  adjust salaries before comparing the sexes may not be acceptable to the courts.  \nExclude the variable rank, refit, and summarize how your findings changed, if they did.   \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_salary3 <- lm(salary ~ degree + sex + year + ysdeg, data =  salary)\nsummary(lm_salary3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\nWithout the variable of rank, the statistically significant variables are now deegree, year, and ysdeg. Without rank females also make 1286.54 less than males so. Years since degree now has a postive relationship. \n\n\n# Question 3  \n\n(Data file: house.selling.price in smss R package)  \n\n\n## A  \n\nUsing the house.selling.price data, run and report regression results modeling y = selling  price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 =  yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the  meaning of the coefficient.  \n  \n\n::: {.cell}\n\n```{.r .cell-code}\nhouse.selling.price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    case Taxes Beds Baths New  Price Size\n1      1  3104    4     2   0 279900 2048\n2      2  1173    2     1   0 146500  912\n3      3  3076    4     2   0 237700 1654\n4      4  1608    3     2   0 200000 2068\n5      5  1454    3     3   0 159900 1477\n6      6  2997    3     2   1 499900 3153\n7      7  4054    3     2   0 265500 1355\n8      8  3002    3     2   1 289900 2075\n9      9  6627    5     4   0 587000 3990\n10    10   320    3     2   0  70000 1160\n11    11   630    3     2   0  64500 1220\n12    12  1780    3     2   0 167000 1690\n13    13  1630    3     2   0 114600 1380\n14    14  1530    3     2   0 103000 1590\n15    15   930    3     1   0 101000 1050\n16    16   590    2     1   0  70000  770\n17    17  1050    3     2   0  85000 1410\n18    18    20    3     1   0  22500 1060\n19    19   870    2     2   0  90000 1300\n20    20  1320    3     2   0 133000 1500\n21    21  1350    2     1   0  90500  820\n22    22  5616    4     3   1 577500 3949\n23    23   680    2     1   0 142500 1170\n24    24  1840    3     2   0 160000 1500\n25    25  3680    4     2   0 240000 2790\n26    26  1660    3     1   0  87000 1030\n27    27  1620    3     2   0 118600 1250\n28    28  3100    3     2   0 140000 1760\n29    29  2070    2     3   0 148000 1550\n30    30   830    3     2   0  69000 1120\n31    31  2260    4     2   0 176000 2000\n32    32  1760    3     1   0  86500 1350\n33    33  2750    3     2   1 180000 1840\n34    34  2020    4     2   0 179000 2510\n35    35  4900    3     3   1 338000 3110\n36    36  1180    4     2   0 130000 1760\n37    37  2150    3     2   0 163000 1710\n38    38  1600    2     1   0 125000 1110\n39    39  1970    3     2   0 100000 1360\n40    40  2060    3     1   0 100000 1250\n41    41  1980    3     1   0 100000 1250\n42    42  1510    3     2   0 146500 1480\n43    43  1710    3     2   0 144900 1520\n44    44  1590    3     2   0 183000 2020\n45    45  1230    3     2   0  69900 1010\n46    46  1510    2     2   0  60000 1640\n47    47  1450    2     2   0 127000  940\n48    48   970    3     2   0  86000 1580\n49    49   150    2     2   0  50000  860\n50    50  1470    3     2   0 137000 1420\n51    51  1850    3     2   0 121300 1270\n52    52   820    2     1   0  81000  980\n53    53  2050    4     2   0 188000 2300\n54    54   710    3     2   0  85000 1430\n55    55  1280    3     2   0 137000 1380\n56    56  1360    3     2   0 145000 1240\n57    57   830    3     2   0  69000 1120\n58    58   800    3     2   0 109300 1120\n59    59  1220    3     2   0 131500 1900\n60    60  3360    4     3   0 200000 2430\n61    61   210    3     2   0  81900 1080\n62    62   380    2     1   0  91200 1350\n63    63  1920    4     3   0 124500 1720\n64    64  4350    3     3   0 225000 4050\n65    65  1510    3     2   0 136500 1500\n66    66  4154    3     3   0 381000 2581\n67    67  1976    3     2   1 250000 2120\n68    68  3605    3     3   1 354900 2745\n69    69  1400    3     2   0 140000 1520\n70    70   790    2     2   0  89900 1280\n71    71  1210    3     2   0 137000 1620\n72    72  1550    3     2   0 103000 1520\n73    73  2800    3     2   0 183000 2030\n74    74  2560    3     2   0 140000 1390\n75    75  1390    4     2   0 160000 1880\n76    76  5443    3     2   0 434000 2891\n77    77  2850    2     1   0 130000 1340\n78    78  2230    2     2   0 123000  940\n79    79    20    2     1   0  21000  580\n80    80  1510    4     2   0  85000 1410\n81    81   710    3     2   0  69900 1150\n82    82  1540    3     2   0 125000 1380\n83    83  1780    3     2   1 162600 1470\n84    84  2920    2     2   1 156900 1590\n85    85  1710    3     2   1 105900 1200\n86    86  1880    3     2   0 167500 1920\n87    87  1680    3     2   0 151800 2150\n88    88  3690    5     3   0 118300 2200\n89    89   900    2     2   0  94300  860\n90    90   560    3     1   0  93900 1230\n91    91  2040    4     2   0 165000 1140\n92    92  4390    4     3   1 285000 2650\n93    93   690    3     1   0  45000 1060\n94    94  2100    3     2   0 124900 1770\n95    95  2880    4     2   0 147000 1860\n96    96   990    2     2   0 176000 1060\n97    97  3030    3     2   0 196500 1730\n98    98  1580    3     2   0 132200 1370\n99    99  1770    3     2   0  88400 1560\n100  100  1430    3     2   0 127200 1340\n```\n:::\n\n```{.r .cell-code}\nhouse_lm <- lm(Price ~ Size + New, data = house.selling.price)\nsummary(house_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThis model shows both size and new variables are statistically significant to price. A new house has a price of57736.283 more than a not new home and for each unit increase of size, price increases 116.132. \n\n## B  \n\nReport and interpret the prediction equation, and form separate equations relating selling  price to size for new and for not new homes.   \n\ny = -40230.867+116.132*X1(size) + 57736.283*X2(new)\n\nIf the house is not new, X2 is cancelled out by 0  \n\n## C    \n\nFind the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.     \ny = -40230.867+116.132*X1(size) + 57736.283*X2(new)  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#i\n\n-40230.867+(116.132*3000) + (57736.283*1)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 365901.4\n```\n:::\n\n```{.r .cell-code}\n#ii  \n-40230.867+(116.132*3000) + (57736.283*0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 308165.1\n```\n:::\n:::\n\n\n\n## D  \n\nFit another model, this time with an interaction term allowing interaction between size and  new, and report the regression results   \n \n\n::: {.cell}\n\n```{.r .cell-code}\nhouse_lm2 <- lm(Price ~ Size*New, data = house.selling.price)\nsummary(house_lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThese results now show \"new\" is not statistically significant but \"size\" and \"size:new\" is. \n\n## E  \n\nReport the lines relating the predicted selling price to the size for homes that are (i) new,  (ii) not new.  \n\ni.\ny = -22227.808 + 104.438*X1(size) - 78527.502*X2(new) + 61.916*X1(size)*X2(new)  \n\nii.\ny = -22227.808 + 104.438*X1(size) \n\n## F   \n\nFind the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.   \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#i\n\n-22227.808 + (104.438*3000) - 78527.502 + (61.916*3000)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 398306.7\n```\n:::\n\n```{.r .cell-code}\n#ii\n-22227.808 + (104.438*3000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 291086.2\n```\n:::\n:::\n\n\n\n## G  \n\nFind the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new.  Comparing to (F), explain how the difference in predicted selling prices changes as the size  of home increases.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#i\n\n-22227.808 + (104.438*1500) - 78527.502 + (61.916*1500)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 148775.7\n```\n:::\n\n```{.r .cell-code}\n#ii\n-22227.808 + (104.438*1500)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 134429.2\n```\n:::\n:::\n\nWith the interaction of size*new, predicted selling prices changes by an increase of over 200% as the size of home increases in these instances. As the size increases, the percentage also increases in predicted selling price. \n\n## H  \n\nDo you think the model with interaction or the one without it represents the relationship of  size and new to the outcome price? What makes you prefer one model over another?  \n\nR squared in the interaction model is higher as well as the standard error number is lower. BAsed on these two factors I would determine the interaction model is preferred. \n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}