{
  "hash": "8d3f0c2141b9c6a07cdc1d16b819f5c3",
  "result": {
    "markdown": "---\ntitle: \"Final_checkIn 2\"\nauthor: \"Sai Padma  pothula\"\ndesription: \"\"\ndate: \"05/02/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Final checkIn 1\n  - sai Pothula\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.5.0 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(ggplot2)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth <- read_csv(\"~/Desktop/603_Spring_2023/posts/_data/student_mental.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 101 Columns: 11\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (10): Timestamp, Choose your gender, What is your course?, Your current ...\ndbl  (1): Age\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(health) <- c('Timestamp', 'Gender', 'Age', 'Course', 'Year', 'CGPA', 'Married', 'Depression', 'Anxiety', 'Panic_Attack', 'Treatment')\nindx <- apply(health, 2, function(x) any(is.na(x)))\nindx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Timestamp       Gender          Age       Course         Year         CGPA \n       FALSE        FALSE         TRUE        FALSE        FALSE        FALSE \n     Married   Depression      Anxiety Panic_Attack    Treatment \n       FALSE        FALSE        FALSE        FALSE        FALSE \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwhich(is.na(health$Age))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 44\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth[44,'Age'] <- median(health$Age, na.rm =T)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Assuming you have a data frame named 'health'\n\n# Group by Age and calculate the count\ngrouped_data <- health %>%\n  group_by(Age) %>%\n  summarize(count = n())\n\n# Create the bar plot using ggplot2\nggplot(grouped_data, aes(x = Age, y = count, fill = count)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = count), vjust = -0.5, size = 3) +\n  labs(title = \"Distribution of Age\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_checkin_2_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nThis graph provides a visual representation of the population count across different age groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHealth_SummaryStat <- health %>%\n  group_by(Gender) %>%\n  summarise(count = n(),\n            percentage = round((n()/ nrow(health)), digits = 4))\nHealth_SummaryStat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  Gender count percentage\n  <chr>  <int>      <dbl>\n1 Female    75      0.743\n2 Male      26      0.257\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nHealth_SummaryStat2 <- health %>%\n  group_by(Depression) %>%\n  summarise(count = n(),\n            percentage = round((n()/ nrow(health)), digits = 4))\n\ncolors <- c(\"pink\", \"cyan\", \"blue\")  # Define colors for the pie chart\n\n# Create the pie chart using the pie() function\npie(Health_SummaryStat2$percentage, labels = Health_SummaryStat2$Depression,\n    col = colors,\n    main = \"Pie Chart of Depression\",\n    cex.main = 1.2,\n    cex.lab = 1.2)\n\n# Add a legend\nlegend(\"topright\", legend = Health_SummaryStat2$Depression,\n       fill = colors, cex = 1.2)\n```\n\n::: {.cell-output-display}\n![](final_project_checkin_2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nThis pie chart depicts that 34.6% of the sample exhibited symptoms of depression, which is significantly higher than the average population rate of 5.0% among adults.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the colors for the pie chart\ncolors <- c(\"Maroon\", \"Coral\")\n\n# Create the data for the pie chart\npie_data <- Health_SummaryStat$percentage\nnames(pie_data) <- Health_SummaryStat$Gender\n\n# Create the pie chart using the pie() function\npie(pie_data, labels = names(pie_data),\n    col = colors,\n    main = \"Pie Chart of Gender\",\n    cex.main = 1.2,\n    cex.lab = 1.2)\n\n# Add the percentage values inside the pie chart\nlabel_pos <- 1.2 * max(pie_data)\npercent_labels <- paste(round(pie_data * 100, digits = 2), \"%\", sep = \"\")\ntext(x = label_pos * sin(2 * pi * cumsum(pie_data)), \n     y = -label_pos * cos(2 * pi * cumsum(pie_data)),\n     labels = percent_labels, cex = 1.2)\n\n# Add a legend\nlegend(\"topright\", legend = names(pie_data),\n       fill = colors, cex = 1.2)\n```\n\n::: {.cell-output-display}\n![](final_project_checkin_2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\nThis pie chart illustrates that females comprise 74.3% of the observations, while males account for the remaining 25.7%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth %>%\n  count(Gender, Depression, sort = F) %>%\n  group_by(Gender) %>%\n  mutate(prop = round((n / sum(n)), digits = 4)) %>%\n  ggplot(aes(x = Gender, y = prop, fill = Depression)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = paste(Gender, prop * 100, \"%\")), position = position_stack(vjust = 0.5)) +\n  labs(title = \"Barplot of Depression amongst Genders\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_checkin_2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\nThis bar plot provides a visual representation of depression cases among males and females. The results indicate that, on average, females had a higher incidence of depression compared to males. The percentage of females experiencing depression was 38.67%, while for males it was 23.08%. This suggests a higher prevalence of depression among females in the observed population.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth$CGPA <- as.factor(health$CGPA)\nlevels(health$CGPA)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"0 - 1.99\"    \"2.00 - 2.49\" \"2.50 - 2.99\" \"3.00 - 3.49\" \"3.50 - 4.00\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth %>%\n  group_by(CGPA) %>%\n  summarize(count = n()) %>%\n  ggplot(aes(x = CGPA, y = count)) +\n  geom_bar(stat = \"identity\",\n           fill = \"lightblue\",  # Replace with the desired color name or hexadecimal color code\n           color = \"black\",\n           width = 0.5) +\n  geom_text(aes(label = count),\n            vjust = -0.5,\n            color = \"black\") +\n  labs(title = \"Distribution of CGPA\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_checkin_2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\nThis bar graph provides a visual representation of the distribution of CGPA (Cumulative Grade Point Average) among a group of individuals. \n\nThe graph shows that the majority of the members, specifically 48 individuals, have a CGPA in the range of 3.50-4.00, indicating a high level of academic achievement. On the other hand, there are only 4 individuals who have a CGPA in the lower range of 0-1.99, suggesting a lower level of academic performance.\n\nAdditionally, there are 43 members who fall within the CGPA range of 3.00-3.49, indicating a moderate level of academic achievement. Furthermore, 4 members have a CGPA between 2.50-2.99, and 2 members have a CGPA ranging from 2.00-2.49.\n\nOverall, this distribution suggests a varied range of CGPA scores among the group, with a significant number of individuals achieving high CGPA scores and a smaller number falling into lower CGPA ranges.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth %>%\n  count(CGPA, Depression, sort = F) %>%\n  mutate(proportion = round((n / sum(n)), digits = 4)) %>%\n  ggplot(aes(x = CGPA, y = proportion, fill = Depression)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Barplot of Depression vs CGPA\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_checkin_2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\nBased on the given data, we cannot observe any clear patterns or a straightforward relationship between CGPA (Cumulative Grade Point Average) and depression. However, there seems to be a non-monotonic increase in the rate of depression as CGPA increases. It is important to note that the group sizes for each CGPA category may be inadequate to draw definitive conclusions. \n\nIf we had access to more precise CGPA values rather than the broad ranges provided, we would have been able to obtain a clearer and more accurate understanding of the relationship between CGPA and depression. However, based on the available data, we can observe a slight positive association between CGPA and the rate of depression. This suggests that as CGPA increases, there is a tendency for the depression rate to also increase, although the relationship may not be linear or consistent across all CGPA ranges.\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth %>%\n  filter(grepl('BIT|KOE|BCS|Engineering|Biomedical science', Course)) %>%\n  count(Course, Depression, sort = T) %>%\n  group_by(Course) %>%\n  mutate(prop = round((n / sum(n)), digits = 4)) %>%\n  ggplot(aes(x = Course, y = n, fill = Depression)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = paste(Course, n)),\n            position = position_stack(vjust = 0.5),\n            color = \"black\") +\n  labs(title = \"Barplot of Depression amongst the top 5 Courses\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_checkin_2_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nEngineering students seem to have the most cases of depression, and surprisingly 0 came out of the Bio medical group. Group sizes too small to make any conclusive associations.\n",
    "supporting": [
      "final_project_checkin_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}