<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Meredith Derian-Toth">
<meta name="dcterms.date" content="2023-04-30">
<meta name="description" content="DACSS603_Homework 4">

<title>Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Homework 4">
<meta name="twitter:description" content="DACSS603_Homework 4">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1." id="toc-question-1." class="nav-link active" data-scroll-target="#question-1.">Question 1.</a></li>
  <li><a href="#question-2." id="toc-question-2." class="nav-link" data-scroll-target="#question-2.">Question 2.</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 4</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw2</div>
    <div class="quarto-category">confidence intervals</div>
  </div>
  </div>

<div>
  <div class="description">
    DACSS603_Homework 4
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Meredith Derian-Toth </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 30, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>, <span class="at">message =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"alr4"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"smss"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="question-1." class="level2">
<h2 class="anchored" data-anchor-id="question-1.">Question 1.</h2>
<p>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.</p>
<section id="a-a-particular-home-of-1240-square-feet-on-a-lot-of-18000-square-feet-sold-for-145000.-find-the-predicted-selling-price-and-the-residual-and-interpret." class="level4">
<h4 class="anchored" data-anchor-id="a-a-particular-home-of-1240-square-feet-on-a-lot-of-18000-square-feet-sold-for-145000.-find-the-predicted-selling-price-and-the-residual-and-interpret.">a) A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ŷ = −10,536 + 53.8x1 + 2.84x2</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#x1 = size of home</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#x2 = size of lot</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#y = selling price</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">1240</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">&lt;-</span><span class="dv">18000</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>Predict_Sell_Price<span class="ot">&lt;-</span>(<span class="sc">-</span><span class="dv">10536</span>) <span class="sc">+</span> (<span class="fl">53.8</span><span class="sc">*</span>x1) <span class="sc">+</span> (<span class="fl">2.84</span><span class="sc">*</span>x2)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Predict_Sell_Price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107296</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>residual1a<span class="ot">&lt;-</span><span class="dv">145000</span><span class="sc">-</span>Predict_Sell_Price</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(residual1a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37704</code></pre>
</div>
</div>
<p>The predicted selling price is $107,296, and the residual is 37704. The residual is positive, which means the price could go as high as 37,704 + 107,296. In other words, the predicted price is an underestimate.</p>
</section>
<section id="b-for-fixed-lot-size-how-much-is-the-house-selling-price-predicted-to-increase-for-each-square-foot-increase-in-home-size-why" class="level4">
<h4 class="anchored" data-anchor-id="b-for-fixed-lot-size-how-much-is-the-house-selling-price-predicted-to-increase-for-each-square-foot-increase-in-home-size-why">b) For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?</h4>
<p>Looking at the equation: ŷ = −10,536 + 53.8x1 + 2.84x2 where x1 = size of home, x2 = size of lot, and y = selling price. When x2 remains constant, the predicted selling price will increase by x1, which is 53.8. This is because 53.8 is the coefficient of the variable that is not fixed.</p>
</section>
<section id="c-according-to-this-prediction-equation-for-fixed-home-size-how-much-would-lot-size-need-to-increase-to-have-the-same-impact-as-a-one-square-foot-increase-in-home-size" class="level4">
<h4 class="anchored" data-anchor-id="c-according-to-this-prediction-equation-for-fixed-home-size-how-much-would-lot-size-need-to-increase-to-have-the-same-impact-as-a-one-square-foot-increase-in-home-size">c) According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.94366</code></pre>
</div>
</div>
<p>Lot size would need to increase by almost 19 times itself in order to have the same impact as a one-square foot increase in home size.</p>
</section>
</section>
<section id="question-2." class="level2">
<h2 class="anchored" data-anchor-id="question-2.">Question 2.</h2>
<p>(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include:</p>
<p>1) degree - a factor with levels PhD and MS.<br>
2) rank - a factor with levels Asst, Assoc, and Prof.<br>
3) sex - a factor with levels Male and Female.<br>
4) Year - years in current rank.<br>
5) ysdeg - years since highest degree.<br>
6) salary - academic year salary in dollars.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   degree rank    sex year ysdeg salary
1 Masters Prof   Male   25    35  36350
2 Masters Prof   Male   13    22  35350
3 Masters Prof   Male   10    23  28200
4 Masters Prof Female    7    27  26775
5     PhD Prof   Male   19    30  33696
6 Masters Prof   Male   16    21  28516</code></pre>
</div>
</div>
<section id="a-test-the-hypothesis-that-the-mean-salary-for-men-and-women-is-the-same-without-regard-to-any-other-variable-but-sex.-explain-your-findings." class="level4">
<h4 class="anchored" data-anchor-id="a-test-the-hypothesis-that-the-mean-salary-for-men-and-women-is-the-same-without-regard-to-any-other-variable-but-sex.-explain-your-findings.">a) Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary<span class="sc">~</span>sex, <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sex, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8602.8 -4296.6  -100.8  3513.1 16687.9 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    24697        938  26.330   &lt;2e-16 ***
sexFemale      -3340       1808  -1.847   0.0706 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5782 on 50 degrees of freedom
Multiple R-squared:  0.0639,    Adjusted R-squared:  0.04518 
F-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706</code></pre>
</div>
</div>
<p>When looking at just sex and salary, there is a difference in average salary between male and female faculty members. Female faculty members make on average $3,340 less than their male colleagues. This difference is not statistically significant as the p value is above .05 ( p value = 0.0706).</p>
</section>
<section id="b-run-a-multiple-linear-regression-with-salary-as-the-outcome-variable-and-everything-else-as-predictors-including-sex.-assuming-no-interactions-between-sex-and-the-other-predictors-obtain-a-95-confidence-interval-for-the-difference-in-salary-between-males-and-females." class="level4">
<h4 class="anchored" data-anchor-id="b-run-a-multiple-linear-regression-with-salary-as-the-outcome-variable-and-everything-else-as-predictors-including-sex.-assuming-no-interactions-between-sex-and-the-other-predictors-obtain-a-95-confidence-interval-for-the-difference-in-salary-between-males-and-females.">b) Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> degree <span class="sc">+</span> rank <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary) <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">confint</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept) 14134.4059 17357.68946
sexFemale    -697.8183  3030.56452
degreePhD    -663.2482  3440.47485
rankAssoc    2985.4107  7599.31080
rankProf     8396.1546 13841.37340
year          285.1433   667.47476
ysdeg        -280.6397    31.49105</code></pre>
</div>
</div>
<p>The 95% confidence interval for the difference in salary between men and women is -697.81 to 3030.56. This means a woman’s salary could be as low as 697.81 less than a male’s or as high as 3030.56 more than a male’s.</p>
</section>
<section id="c-interpret-your-finding-for-each-predictor-variable-discuss-a-statistical-significance-b-interpretation-of-the-coefficient-slope-in-relation-to-the-outcome-variable-and-other-variables" class="level4">
<h4 class="anchored" data-anchor-id="c-interpret-your-finding-for-each-predictor-variable-discuss-a-statistical-significance-b-interpretation-of-the-coefficient-slope-in-relation-to-the-outcome-variable-and-other-variables">c) Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> degree <span class="sc">+</span> rank <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sex + degree + rank + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
sexFemale    1166.37     925.57   1.260    0.214    
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>According to the results of the regression:<br>
(1) sexFemale has a positive coeficient of 1166.37 and a nonsigificant p value of 0.214. This means that females tend to have higher salarys with an average of $1,166 more than men. And that being female does not have a significant affect on salary.<br>
(2) degreePhD has a positive coefficient of 1388.61 and nonsignificant p value of 0.180. This means, those with a PhD have a higher salary on average by $1,388 than those who have a MA. It also means that having a PhD does not affect salary significantly.<br>
(3) rankAssoc has a positive coefficient of 5292.36 and a significant p value of 3.22e-05. This means, tenure faculty members who rank as an Assoc have higher salaries in general by $5,292, and the relationship between professor ranking and salary is significant.<br>
(4) rankProf has a positive coefficient of 11118.76 and a significant p value of 1.62e-10. This means, those who are ranked as professors make significantly more money than those of other rankings (by about $11,118).<br>
(5) year has a positive coefficient of 476.31 and a significant p value of 8.65e-06. This means that the longer you are in your ranking, the higher your salary will be (by about $476 per year), and that the relationship between years in ranking and salary is significant.<br>
(6) ysdeg has a negative coefficient with a nonsignificant p value of 0.115. This means that the more years past your education, the less you are getting paid. Which could mean that the newer employees are getting offered more money. However, there is not a significant relationship between years since your education and salary.</p>
</section>
<section id="d-change-the-baseline-category-for-the-rank-variable.-interpret-the-coefficients-related-to-rank-again." class="level4">
<h4 class="anchored" data-anchor-id="d-change-the-baseline-category-for-the-rank-variable.-interpret-the-coefficients-related-to-rank-again.">d) Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">'Prof'</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> degree <span class="sc">+</span> rank <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sex + degree + rank + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  26864.81    1375.29  19.534  &lt; 2e-16 ***
sexFemale     1166.37     925.57   1.260    0.214    
degreePhD     1388.61    1018.75   1.363    0.180    
rankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***
rankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***
year           476.31      94.91   5.018 8.65e-06 ***
ysdeg         -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>When the baseline category of rank is changed to professor, the coefficients for rankAsst and rankAssoc both become negative, and the p values remain significant. This means Full Professors make significantly higher salaries than do Assistant Professors (by 11,118 more dollars) or Associate professors ($5,826 more).</p>
</section>
<section id="e-finkelstein-1980-in-a-discussion-of-the-use-of-regression-in-discrimination-cases-wrote-a-variable-may-reflect-a-position-or-status-bestowed-by-the-employer-in-which-case-if-there-is-discrimination-in-the-award-of-the-position-or-status-the-variable-may-be-tainted." class="level4">
<h4 class="anchored" data-anchor-id="e-finkelstein-1980-in-a-discussion-of-the-use-of-regression-in-discrimination-cases-wrote-a-variable-may-reflect-a-position-or-status-bestowed-by-the-employer-in-which-case-if-there-is-discrimination-in-the-award-of-the-position-or-status-the-variable-may-be-tainted.">e) Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “[a] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’”</h4>
<p>Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.</p>
<p>Exclude the variable rank, refit, and summarize how your findings changed, if they did.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> degree <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sex + degree + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
sexFemale   -1286.54    1313.09  -0.980 0.332209    
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
year          351.97     142.48   2.470 0.017185 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>When removing rank, the model changes. The coefficient for sexFemale is now negative, which means women make less in salary than men by about $1,286.54. However, the p value is still not significant and the adjusted R- Square for the model has reduced from .83 to .6.</p>
</section>
<section id="f-everyone-in-this-dataset-was-hired-the-year-they-earned-their-highest-degree.-it-is-also-known-that-a-new-dean-was-appointed-15-years-ago-and-everyone-in-the-dataset-who-earned-their-highest-degree-15-years-ago-or-less-than-that-has-been-hired-by-the-new-dean." class="level4">
<h4 class="anchored" data-anchor-id="f-everyone-in-this-dataset-was-hired-the-year-they-earned-their-highest-degree.-it-is-also-known-that-a-new-dean-was-appointed-15-years-ago-and-everyone-in-the-dataset-who-earned-their-highest-degree-15-years-ago-or-less-than-that-has-been-hired-by-the-new-dean.">f) Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean.</h4>
<p>Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</p>
<p>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>salary<span class="ot">&lt;-</span>salary<span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">New_Dean =</span> <span class="fu">case_when</span>(ysdeg <span class="sc">&lt;=</span><span class="dv">15</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                   ysdeg <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in salary %&gt;% mutate(New_Dean = case_when(ysdeg &lt;= 15 ~ 1, ysdeg &gt; : could not find function "%&gt;%"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>MultiCoTest<span class="ot">&lt;-</span><span class="fu">cor</span>(salary<span class="sc">$</span>ysdeg, salary<span class="sc">$</span>New_Dean, <span class="at">method =</span> <span class="st">'pearson'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in cor(salary$ysdeg, salary$New_Dean, method = "pearson"): supply both 'x' and 'y' or a matrix-like 'x'</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MultiCoTest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in print(MultiCoTest): object 'MultiCoTest' not found</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> degree <span class="sc">+</span> rank <span class="sc">+</span> year <span class="sc">+</span> New_Dean, <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(predvars, data, env): object 'New_Dean' not found</code></pre>
</div>
</div>
<p>Multi-colinearity could be a problem with this new variable because of the existing variable of “ysdeg”. This variable is the number of years since your highest degree obtained, therefore if the new variable is not different enough from this variable it will cause issues of multicolinearity.</p>
<p>Therefore, I created a dummy variable of “hired by the new dean” which equals to “1” or “not hired by the new dean” which equals to “0”, and then ran tests of multicolineary to test the relationship before running the regression again. The correlation between ysdeg and New_Dean is -0.843, which could mean multicolinearity. Therefore we ran the model without the ysdeg variable.</p>
<p>The results of the new model suggest that those hired by the new dean are making statistically significantly more money by about $2,163, with a p value of .0496. This is just barely statistically significant, however the results support the hypothesis that the new dean is offering higher salaries than the previous one.</p>
</section>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house.selling.price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  case Taxes Beds Baths New  Price Size
1    1  3104    4     2   0 279900 2048
2    2  1173    2     1   0 146500  912
3    3  3076    4     2   0 237700 1654
4    4  1608    3     2   0 200000 2068
5    5  1454    3     3   0 159900 1477
6    6  2997    3     2   1 499900 3153</code></pre>
</div>
</div>
<section id="a-using-the-house.selling.price-data-run-and-report-regression-results-modeling-y-selling-price-in-dollars-in-terms-of-size-of-home-in-square-feet-and-whether-the-home-is-new-1-yes-0-no.-in-particular-for-each-variable-discuss-statistical-significance-and-interpret-the-meaning-of-the-coefficient." class="level4">
<h4 class="anchored" data-anchor-id="a-using-the-house.selling.price-data-run-and-report-regression-results-modeling-y-selling-price-in-dollars-in-terms-of-size-of-home-in-square-feet-and-whether-the-home-is-new-1-yes-0-no.-in-particular-for-each-variable-discuss-statistical-significance-and-interpret-the-meaning-of-the-coefficient.">a) Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable: discuss statistical significance and interpret the meaning of the coefficient.</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The results of the regression show that the size of the house and whether the house is new both have a statistically significant relationship with the selling price. For the size of the house, the price increases by 116 dollars with every square foot (p value = &lt; 2e-16). And if the house is new it increases the price by an average of $57,736 (p value = 0.00257).</p>
</section>
<section id="b-report-and-interpret-the-prediction-equation-and-form-separate-equations-relating-selling-price-to-size-for-new-and-for-not-new-homes." class="level4">
<h4 class="anchored" data-anchor-id="b-report-and-interpret-the-prediction-equation-and-form-separate-equations-relating-selling-price-to-size-for-new-and-for-not-new-homes.">b) Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</h4>
<p>Prediction Equation: ŷ = -40230.87 + 116.13x1 + 57736.28x2<br>
Where x1 = Size<br>
And x2 = New (or not new)</p>
<p>For new homes:<br>
ŷ = -40230.87 + 116.13x1 - 57736.28(1)</p>
<p>For not new homes:<br>
ŷ = -40230.87 + 116.13x1 - 57736.28(0) therefore<br>
ŷ = -40230.87 + 116.13x1</p>
</section>
<section id="c-find-the-predicted-selling-price-for-a-home-of-3000-square-feet-that-is-i-new-ii-not-new." class="level4">
<h4 class="anchored" data-anchor-id="c-find-the-predicted-selling-price-for-a-home-of-3000-square-feet-that-is-i-new-ii-not-new.">c) Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">3000</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>x3<span class="ot">&lt;-</span><span class="dv">0</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>ŷ <span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">40230.87</span>) <span class="sc">+</span> (<span class="fl">116.13</span><span class="sc">*</span>x1) <span class="sc">+</span> (<span class="fl">57736.28</span><span class="sc">*</span>x2)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>ŷ</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 365895.4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>ŷ2 <span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">40230.87</span>) <span class="sc">+</span> (<span class="fl">116.13</span><span class="sc">*</span>x1) <span class="sc">+</span> (<span class="fl">57736.28</span><span class="sc">*</span>x3)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>ŷ2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 308159.1</code></pre>
</div>
</div>
<p>(i) The predicted selling price of a house that is new and 3000 square feet is $365,895.40.<br>
(ii) The predicted selling price of a house that is not new and 3000 square feet is $308,159.10.</p>
</section>
<section id="d-fit-another-model-this-time-with-an-interaction-term-allowing-interaction-between-size-and-new-and-report-the-regression-results." class="level4">
<h4 class="anchored" data-anchor-id="d-fit-another-model-this-time-with-an-interaction-term-allowing-interaction-between-size-and-new-and-report-the-regression-results.">d) Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results.</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size <span class="sc">*</span> New, <span class="at">data =</span> house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New + Size * New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The results of the regression show that the size of the house as a significant relationship to the selling price with a p value of &lt; 2e-16. The price of the house increases by 104 dollars for every square foot. Whether the house is new is now no longer a significant relationship to the price of the house with a p value of 0.127 and a negative coefficient. This means newer homes decrease the price. However the relationship between size and newness has a significant relationship to selling price with a p value of 0.00527.</p>
</section>
<section id="e-report-the-lines-relating-the-predicted-selling-price-to-the-size-for-homes-that-are-i-new-ii-not-new." class="level4">
<h4 class="anchored" data-anchor-id="e-report-the-lines-relating-the-predicted-selling-price-to-the-size-for-homes-that-are-i-new-ii-not-new.">e) Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</h4>
<p>ŷ = -22227.81 + 104.44x1 - 78527.50x2 + 61.92x3</p>
<p>(i) New Homes:<br>
ŷ = -22227.81 + 104.44x1 - 78527.50(1) + 61.92x3</p>
<p>(ii) Not New Homes:<br>
ŷ = -22227.81 + 104.44x1 - 78527.50(0) + 61.92x3 Therefore<br>
ŷ = -22227.81 + 104.44x1 + 61.92x3</p>
</section>
<section id="f-find-the-predicted-selling-price-for-a-home-of-3000-square-feet-that-is-i-new-ii-not-new." class="level4">
<h4 class="anchored" data-anchor-id="f-find-the-predicted-selling-price-for-a-home-of-3000-square-feet-that-is-i-new-ii-not-new.">f) Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#New Home</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">3000</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>x3<span class="ot">&lt;-</span>x2<span class="sc">*</span>x1</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>predict_selling_price_fi<span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">22227.81</span>) <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span>x1) <span class="sc">-</span> (<span class="fl">78527.50</span><span class="sc">*</span>x2) <span class="sc">+</span> (<span class="fl">61.92</span><span class="sc">*</span>x3)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predict_selling_price_fi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 398324.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Not New Home</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">3000</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>x4<span class="ot">&lt;-</span><span class="dv">0</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>x3<span class="ot">&lt;-</span>x4<span class="sc">*</span>x1</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>predict_selling_price_fii<span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">22227.81</span>) <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span>x1) <span class="sc">-</span> (<span class="fl">78527.50</span><span class="sc">*</span>x4) <span class="sc">+</span> (<span class="fl">61.92</span><span class="sc">*</span>x3)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predict_selling_price_fii)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 291092.2</code></pre>
</div>
</div>
<p>(i) New home of 3000 square feet has a predicted selling price of $398,324.70<br>
(ii) Not new home of 3000 square feet has a predicted selling price of $291,092.20</p>
</section>
<section id="g-find-the-predicted-selling-price-for-a-home-of-1500-square-feet-that-is-i-new-ii-not-new.-comparing-to-f-explain-how-the-difference-in-predicted-selling-prices-changes-as-the-size-of-home-increases." class="level4">
<h4 class="anchored" data-anchor-id="g-find-the-predicted-selling-price-for-a-home-of-1500-square-feet-that-is-i-new-ii-not-new.-comparing-to-f-explain-how-the-difference-in-predicted-selling-prices-changes-as-the-size-of-home-increases.">g) Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#New Home</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">1500</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>x3<span class="ot">&lt;-</span>x2<span class="sc">*</span>x1</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>predict_selling_price_fi<span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">22227.81</span>) <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span>x1) <span class="sc">-</span> (<span class="fl">78527.50</span><span class="sc">*</span>x2) <span class="sc">+</span> (<span class="fl">61.92</span><span class="sc">*</span>x3)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predict_selling_price_fi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 148784.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Not New Home</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">1500</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>x4<span class="ot">&lt;-</span><span class="dv">0</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>x3<span class="ot">&lt;-</span>x4<span class="sc">*</span>x1</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>predict_selling_price_fii<span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">22227.81</span>) <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span>x1) <span class="sc">-</span> (<span class="fl">78527.50</span><span class="sc">*</span>x4) <span class="sc">+</span> (<span class="fl">61.92</span><span class="sc">*</span>x3)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predict_selling_price_fii)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 134432.2</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fl">398324.70</span><span class="sc">/</span><span class="fl">148784.70</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.677189</code></pre>
</div>
</div>
<p>(i) New home of 1500 square feet has a predicted selling price of $148784.70<br>
(ii) Not new home of 1500 square feet has a predicted selling price of $134432.20<br>
The price of a home went from 148784.70 dollars for a 1500 square foot house to $398,324.70 for a 3000 square foot house. This is a price increase of 2.7x with 2x increase in square feet. This means that the price increases a higher rate than 1-1 for square feet to dollar. According to the coefficient of the model, 104.438, for every 1 square foot increase the price increases by 104.44 dollars.</p>
</section>
<section id="h-do-you-think-the-model-with-interaction-or-the-one-without-it-represents-the-relationship-of-size-and-new-to-the-outcome-price-what-makes-you-prefer-one-model-over-another" class="level4">
<h4 class="anchored" data-anchor-id="h-do-you-think-the-model-with-interaction-or-the-one-without-it-represents-the-relationship-of-size-and-new-to-the-outcome-price-what-makes-you-prefer-one-model-over-another">h) Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</h4>
<p><strong>The Non-interaction Model</strong>: (Intercept) -40230.867 Adjusted R-squared: 0.7169 p-value: &lt; 2.2e-16</p>
<p>(i) The predicted selling price of a house that is new and 3000 square feet is $365,895.40.<br>
(ii) The predicted selling price of a house that is not new and 3000 square feet is $308,159.10.</p>
<p><strong>The interaction Model</strong>: (Intercept) -22227.808 Adjusted R-squared: 0.7363 p-value: &lt; 2.2e-16</p>
<p>(i) New home of 3000 square feet has a predicted selling price of $398,324.70<br>
(ii) Not new home of 3000 square feet has a predicted selling price of $291,092.20</p>
<p>I believe the second model, with the interaction between “newness” and size is a more predictive model for the selling price. First looking at the adjusted R-squared, it is larger in interaction model (0.7363) compared to the non-interaction model (0.7169). Second, comparing the two models, we see that “New” is significant in the first model (p value of 0.00257), however it is no longer significant when we run the model with the interaction (p value of 0.12697). This means, the interaction of “newness” and size is more predictive than “newness” alone. Lastly, when comparing the predicted selling price for a 3000 square foot house, the interaction model allows for more variation. This would reflect more real world scenarios than the first, non-interactive, model.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb49" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 4"</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Meredith Derian-Toth"</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "DACSS603_Homework 4"</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "04/30/2023"</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw2</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - confidence intervals </span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup}</span></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>, <span class="at">message =</span> <span class="cn">FALSE</span>)</span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a><span class="in">```{r loading packages}</span></span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"alr4"</span>)</span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"smss"</span>)</span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb49-25"><a href="#cb49-25" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb49-26"><a href="#cb49-26" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-27"><a href="#cb49-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-28"><a href="#cb49-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 1. </span></span>
<span id="cb49-29"><a href="#cb49-29" aria-hidden="true" tabindex="-1"></a>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.</span>
<span id="cb49-30"><a href="#cb49-30" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb49-31"><a href="#cb49-31" aria-hidden="true" tabindex="-1"></a><span class="fu">#### a\) A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.  </span></span>
<span id="cb49-32"><a href="#cb49-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-33"><a href="#cb49-33" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 1a}</span></span>
<span id="cb49-34"><a href="#cb49-34" aria-hidden="true" tabindex="-1"></a><span class="co">#ŷ = −10,536 + 53.8x1 + 2.84x2</span></span>
<span id="cb49-35"><a href="#cb49-35" aria-hidden="true" tabindex="-1"></a><span class="co">#x1 = size of home</span></span>
<span id="cb49-36"><a href="#cb49-36" aria-hidden="true" tabindex="-1"></a><span class="co">#x2 = size of lot</span></span>
<span id="cb49-37"><a href="#cb49-37" aria-hidden="true" tabindex="-1"></a><span class="co">#y = selling price</span></span>
<span id="cb49-38"><a href="#cb49-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-39"><a href="#cb49-39" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">1240</span></span>
<span id="cb49-40"><a href="#cb49-40" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">&lt;-</span><span class="dv">18000</span></span>
<span id="cb49-41"><a href="#cb49-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-42"><a href="#cb49-42" aria-hidden="true" tabindex="-1"></a>Predict_Sell_Price<span class="ot">&lt;-</span>(<span class="sc">-</span><span class="dv">10536</span>) <span class="sc">+</span> (<span class="fl">53.8</span><span class="sc">*</span>x1) <span class="sc">+</span> (<span class="fl">2.84</span><span class="sc">*</span>x2)</span>
<span id="cb49-43"><a href="#cb49-43" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Predict_Sell_Price)</span>
<span id="cb49-44"><a href="#cb49-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-45"><a href="#cb49-45" aria-hidden="true" tabindex="-1"></a>residual1a<span class="ot">&lt;-</span><span class="dv">145000</span><span class="sc">-</span>Predict_Sell_Price</span>
<span id="cb49-46"><a href="#cb49-46" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(residual1a)</span>
<span id="cb49-47"><a href="#cb49-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-48"><a href="#cb49-48" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-49"><a href="#cb49-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-50"><a href="#cb49-50" aria-hidden="true" tabindex="-1"></a>The predicted selling price is $107,296, and the residual is 37704. The residual is positive, which means the price could go as high as 37,704 + 107,296. In other words, the predicted price is an underestimate. </span>
<span id="cb49-51"><a href="#cb49-51" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-52"><a href="#cb49-52" aria-hidden="true" tabindex="-1"></a><span class="fu">#### b\) For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?</span></span>
<span id="cb49-53"><a href="#cb49-53" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb49-54"><a href="#cb49-54" aria-hidden="true" tabindex="-1"></a>Looking at the equation: ŷ = −10,536 + 53.8x1 + 2.84x2 where x1 = size of home, x2 = size of lot, and y = selling price. When x2 remains constant, the predicted selling price will increase by x1, which is 53.8. This is because 53.8 is the coefficient of the variable that is not fixed. </span>
<span id="cb49-55"><a href="#cb49-55" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb49-56"><a href="#cb49-56" aria-hidden="true" tabindex="-1"></a><span class="fu">#### c\) According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</span></span>
<span id="cb49-57"><a href="#cb49-57" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb49-58"><a href="#cb49-58" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 1c}</span></span>
<span id="cb49-59"><a href="#cb49-59" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span>)</span>
<span id="cb49-60"><a href="#cb49-60" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-61"><a href="#cb49-61" aria-hidden="true" tabindex="-1"></a>Lot size would need to increase by almost 19 times itself in order to have the same impact as a one-square foot increase in home size. </span>
<span id="cb49-62"><a href="#cb49-62" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb49-63"><a href="#cb49-63" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 2. </span></span>
<span id="cb49-64"><a href="#cb49-64" aria-hidden="true" tabindex="-1"></a>(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include:  </span>
<span id="cb49-65"><a href="#cb49-65" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-66"><a href="#cb49-66" aria-hidden="true" tabindex="-1"></a>1<span class="sc">\)</span> degree - a factor with levels PhD and MS.  </span>
<span id="cb49-67"><a href="#cb49-67" aria-hidden="true" tabindex="-1"></a>2<span class="sc">\)</span> rank - a factor with levels Asst, Assoc, and Prof.   </span>
<span id="cb49-68"><a href="#cb49-68" aria-hidden="true" tabindex="-1"></a>3<span class="sc">\)</span> sex - a factor with levels Male and Female.   </span>
<span id="cb49-69"><a href="#cb49-69" aria-hidden="true" tabindex="-1"></a>4<span class="sc">\)</span> Year - years in current rank.   </span>
<span id="cb49-70"><a href="#cb49-70" aria-hidden="true" tabindex="-1"></a>5<span class="sc">\)</span> ysdeg - years since highest degree.   </span>
<span id="cb49-71"><a href="#cb49-71" aria-hidden="true" tabindex="-1"></a>6<span class="sc">\)</span> salary - academic year salary in dollars.    </span>
<span id="cb49-72"><a href="#cb49-72" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb49-73"><a href="#cb49-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-74"><a href="#cb49-74" aria-hidden="true" tabindex="-1"></a><span class="in">```{r loading data}</span></span>
<span id="cb49-75"><a href="#cb49-75" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span>
<span id="cb49-76"><a href="#cb49-76" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(salary)</span>
<span id="cb49-77"><a href="#cb49-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-78"><a href="#cb49-78" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-79"><a href="#cb49-79" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-80"><a href="#cb49-80" aria-hidden="true" tabindex="-1"></a><span class="fu">#### a\) Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.  </span></span>
<span id="cb49-81"><a href="#cb49-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-82"><a href="#cb49-82" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 2a}</span></span>
<span id="cb49-83"><a href="#cb49-83" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary<span class="sc">~</span>sex, <span class="at">data =</span> salary))</span>
<span id="cb49-84"><a href="#cb49-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-85"><a href="#cb49-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-86"><a href="#cb49-86" aria-hidden="true" tabindex="-1"></a>When looking at just sex and salary, there is a difference in average salary between male and female faculty members. Female faculty members make on average $3,340 less than their male colleagues. This difference is not statistically significant as the p value is above .05 ( p value = 0.0706).  </span>
<span id="cb49-87"><a href="#cb49-87" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-88"><a href="#cb49-88" aria-hidden="true" tabindex="-1"></a><span class="fu">#### b\) Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.  </span></span>
<span id="cb49-89"><a href="#cb49-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-90"><a href="#cb49-90" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 1b}</span></span>
<span id="cb49-91"><a href="#cb49-91" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> degree <span class="sc">+</span> rank <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary) <span class="sc">|&gt;</span></span>
<span id="cb49-92"><a href="#cb49-92" aria-hidden="true" tabindex="-1"></a>          <span class="fu">confint</span>()</span>
<span id="cb49-93"><a href="#cb49-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-94"><a href="#cb49-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-95"><a href="#cb49-95" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-96"><a href="#cb49-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-97"><a href="#cb49-97" aria-hidden="true" tabindex="-1"></a>The 95% confidence interval for the difference in salary between men and women is -697.81 to 3030.56. This means a woman's salary could be as low as 697.81 less than a male's or as high as 3030.56 more than a male's.</span>
<span id="cb49-98"><a href="#cb49-98" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-99"><a href="#cb49-99" aria-hidden="true" tabindex="-1"></a><span class="fu">#### c\) Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables</span></span>
<span id="cb49-100"><a href="#cb49-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-101"><a href="#cb49-101" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 2c}</span></span>
<span id="cb49-102"><a href="#cb49-102" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> degree <span class="sc">+</span> rank <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary))</span>
<span id="cb49-103"><a href="#cb49-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-104"><a href="#cb49-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-105"><a href="#cb49-105" aria-hidden="true" tabindex="-1"></a>According to the results of the regression:  </span>
<span id="cb49-106"><a href="#cb49-106" aria-hidden="true" tabindex="-1"></a>(1<span class="sc">\)</span> sexFemale has a positive coeficient of 1166.37 and a nonsigificant p value of 0.214. This means that females tend to have higher salarys with an average of $1,166 more than men. And that being female does not have a significant affect on salary.   </span>
<span id="cb49-107"><a href="#cb49-107" aria-hidden="true" tabindex="-1"></a>(2<span class="sc">\)</span> degreePhD has a positive coefficient of 1388.61 and nonsignificant p value of 0.180. This means, those with a PhD have a higher salary on average by $1,388 than those who have a MA. It also means that having a PhD does not affect salary significantly.   </span>
<span id="cb49-108"><a href="#cb49-108" aria-hidden="true" tabindex="-1"></a>(3<span class="sc">\)</span> rankAssoc has a positive coefficient of 5292.36 and a significant p value of 3.22e-05. This means, tenure faculty members who rank as an Assoc have higher salaries in general by $5,292, and the relationship between professor ranking and salary is significant.   </span>
<span id="cb49-109"><a href="#cb49-109" aria-hidden="true" tabindex="-1"></a>(4<span class="sc">\)</span> rankProf has a positive coefficient of 11118.76 and a significant p value of 1.62e-10. This means, those who are ranked as professors make significantly more money than those of other rankings (by about $11,118).  </span>
<span id="cb49-110"><a href="#cb49-110" aria-hidden="true" tabindex="-1"></a>(5<span class="sc">\)</span> year has a positive coefficient of 476.31 and a significant p value of 8.65e-06. This means that the longer you are in your ranking, the higher your salary will be (by about $476 per year), and that the relationship between years in ranking and salary is significant.   </span>
<span id="cb49-111"><a href="#cb49-111" aria-hidden="true" tabindex="-1"></a>(6<span class="sc">\)</span> ysdeg has a negative coefficient with a nonsignificant p value of 0.115. This means that the more years past your education, the less you are getting paid. Which could mean that the newer employees are getting offered more money. However, there is not a significant relationship between years since your education and salary.   </span>
<span id="cb49-112"><a href="#cb49-112" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-113"><a href="#cb49-113" aria-hidden="true" tabindex="-1"></a><span class="fu">#### d\) Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</span></span>
<span id="cb49-114"><a href="#cb49-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-115"><a href="#cb49-115" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 2d}</span></span>
<span id="cb49-116"><a href="#cb49-116" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">'Prof'</span>)</span>
<span id="cb49-117"><a href="#cb49-117" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> degree <span class="sc">+</span> rank <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary))</span>
<span id="cb49-118"><a href="#cb49-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-119"><a href="#cb49-119" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-120"><a href="#cb49-120" aria-hidden="true" tabindex="-1"></a>When the baseline category of rank is changed to professor, the coefficients for rankAsst and rankAssoc both become negative, and the p values remain significant. This means Full Professors make significantly higher salaries than do Assistant  Professors (by 11,118 more dollars) or Associate professors ($5,826 more).  </span>
<span id="cb49-121"><a href="#cb49-121" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-122"><a href="#cb49-122" aria-hidden="true" tabindex="-1"></a><span class="fu">#### e\) Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “[a] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’ ” </span></span>
<span id="cb49-123"><a href="#cb49-123" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-124"><a href="#cb49-124" aria-hidden="true" tabindex="-1"></a>Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.</span>
<span id="cb49-125"><a href="#cb49-125" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-126"><a href="#cb49-126" aria-hidden="true" tabindex="-1"></a>Exclude the variable rank, refit, and summarize how your findings changed, if they did.  </span>
<span id="cb49-127"><a href="#cb49-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-128"><a href="#cb49-128" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 2e}</span></span>
<span id="cb49-129"><a href="#cb49-129" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> degree <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary))</span>
<span id="cb49-130"><a href="#cb49-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-131"><a href="#cb49-131" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-132"><a href="#cb49-132" aria-hidden="true" tabindex="-1"></a>When removing rank, the model changes. The coefficient for sexFemale is now negative, which means women make less in salary than men by about $1,286.54. However, the p value is still not significant and the adjusted R- Square for the model has reduced from .83 to .6. </span>
<span id="cb49-133"><a href="#cb49-133" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-134"><a href="#cb49-134" aria-hidden="true" tabindex="-1"></a><span class="fu">#### f\) Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean.</span></span>
<span id="cb49-135"><a href="#cb49-135" aria-hidden="true" tabindex="-1"></a>Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</span>
<span id="cb49-136"><a href="#cb49-136" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-137"><a href="#cb49-137" aria-hidden="true" tabindex="-1"></a>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how</span>
<span id="cb49-138"><a href="#cb49-138" aria-hidden="true" tabindex="-1"></a>you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</span>
<span id="cb49-139"><a href="#cb49-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-140"><a href="#cb49-140" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 2f}</span></span>
<span id="cb49-141"><a href="#cb49-141" aria-hidden="true" tabindex="-1"></a>salary<span class="ot">&lt;-</span>salary<span class="sc">%&gt;%</span></span>
<span id="cb49-142"><a href="#cb49-142" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">New_Dean =</span> <span class="fu">case_when</span>(ysdeg <span class="sc">&lt;=</span><span class="dv">15</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb49-143"><a href="#cb49-143" aria-hidden="true" tabindex="-1"></a>                   ysdeg <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="dv">0</span>))</span>
<span id="cb49-144"><a href="#cb49-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-145"><a href="#cb49-145" aria-hidden="true" tabindex="-1"></a>MultiCoTest<span class="ot">&lt;-</span><span class="fu">cor</span>(salary<span class="sc">$</span>ysdeg, salary<span class="sc">$</span>New_Dean, <span class="at">method =</span> <span class="st">'pearson'</span>)</span>
<span id="cb49-146"><a href="#cb49-146" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MultiCoTest)</span>
<span id="cb49-147"><a href="#cb49-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-148"><a href="#cb49-148" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> degree <span class="sc">+</span> rank <span class="sc">+</span> year <span class="sc">+</span> New_Dean, <span class="at">data =</span> salary))</span>
<span id="cb49-149"><a href="#cb49-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-150"><a href="#cb49-150" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-151"><a href="#cb49-151" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-152"><a href="#cb49-152" aria-hidden="true" tabindex="-1"></a>Multi-colinearity could be a problem with this new variable because of the existing variable of "ysdeg". This variable is the number of years since your highest degree obtained, therefore if the new variable is not different enough from this variable it will cause issues of multicolinearity. </span>
<span id="cb49-153"><a href="#cb49-153" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-154"><a href="#cb49-154" aria-hidden="true" tabindex="-1"></a>Therefore, I created a dummy variable of "hired by the new dean" which equals to "1" or "not hired by the new dean" which equals to "0", and then ran tests of multicolineary to test the relationship before running the regression again. The correlation between ysdeg and New_Dean is -0.843, which could mean multicolinearity. Therefore we ran the model without the ysdeg variable. </span>
<span id="cb49-155"><a href="#cb49-155" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-156"><a href="#cb49-156" aria-hidden="true" tabindex="-1"></a>The results of the new model suggest that those hired by the new dean are making statistically significantly more money by about $2,163, with a p value of .0496. This is just barely statistically significant, however the results support the hypothesis that the new dean is offering higher salaries than the previous one.</span>
<span id="cb49-157"><a href="#cb49-157" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-158"><a href="#cb49-158" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 3    </span></span>
<span id="cb49-159"><a href="#cb49-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-160"><a href="#cb49-160" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 3}</span></span>
<span id="cb49-161"><a href="#cb49-161" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price)</span>
<span id="cb49-162"><a href="#cb49-162" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house.selling.price)</span>
<span id="cb49-163"><a href="#cb49-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-164"><a href="#cb49-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-165"><a href="#cb49-165" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-166"><a href="#cb49-166" aria-hidden="true" tabindex="-1"></a><span class="fu">#### a\) Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable: discuss statistical significance and interpret the meaning of the coefficient.  </span></span>
<span id="cb49-167"><a href="#cb49-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-168"><a href="#cb49-168" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 3a}</span></span>
<span id="cb49-169"><a href="#cb49-169" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price))</span>
<span id="cb49-170"><a href="#cb49-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-171"><a href="#cb49-171" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-172"><a href="#cb49-172" aria-hidden="true" tabindex="-1"></a>The results of the regression show that the size of the house and whether the house is new both have a statistically significant relationship with the selling price. For the size of the house, the price increases by 116 dollars with every square foot (p value = &lt; 2e-16). And if the house is new it increases the price by an average of $57,736 (p value = 0.00257).</span>
<span id="cb49-173"><a href="#cb49-173" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-174"><a href="#cb49-174" aria-hidden="true" tabindex="-1"></a><span class="fu">#### b\) Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</span></span>
<span id="cb49-175"><a href="#cb49-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-176"><a href="#cb49-176" aria-hidden="true" tabindex="-1"></a>Prediction Equation:</span>
<span id="cb49-177"><a href="#cb49-177" aria-hidden="true" tabindex="-1"></a>ŷ = -40230.87 + 116.13x1 + 57736.28x2  </span>
<span id="cb49-178"><a href="#cb49-178" aria-hidden="true" tabindex="-1"></a>Where x1 = Size  </span>
<span id="cb49-179"><a href="#cb49-179" aria-hidden="true" tabindex="-1"></a>And x2 = New (or not new)  </span>
<span id="cb49-180"><a href="#cb49-180" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb49-181"><a href="#cb49-181" aria-hidden="true" tabindex="-1"></a>For new homes:  </span>
<span id="cb49-182"><a href="#cb49-182" aria-hidden="true" tabindex="-1"></a>ŷ = -40230.87 + 116.13x1 - 57736.28(1)  </span>
<span id="cb49-183"><a href="#cb49-183" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-184"><a href="#cb49-184" aria-hidden="true" tabindex="-1"></a>For not new homes:  </span>
<span id="cb49-185"><a href="#cb49-185" aria-hidden="true" tabindex="-1"></a>ŷ = -40230.87 + 116.13x1 - 57736.28(0) therefore  </span>
<span id="cb49-186"><a href="#cb49-186" aria-hidden="true" tabindex="-1"></a>ŷ = -40230.87 + 116.13x1 </span>
<span id="cb49-187"><a href="#cb49-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-188"><a href="#cb49-188" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-189"><a href="#cb49-189" aria-hidden="true" tabindex="-1"></a><span class="fu">#### c\) Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.  </span></span>
<span id="cb49-190"><a href="#cb49-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-191"><a href="#cb49-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 3c}</span></span>
<span id="cb49-192"><a href="#cb49-192" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">3000</span></span>
<span id="cb49-193"><a href="#cb49-193" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb49-194"><a href="#cb49-194" aria-hidden="true" tabindex="-1"></a>x3<span class="ot">&lt;-</span><span class="dv">0</span></span>
<span id="cb49-195"><a href="#cb49-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-196"><a href="#cb49-196" aria-hidden="true" tabindex="-1"></a>ŷ <span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">40230.87</span>) <span class="sc">+</span> (<span class="fl">116.13</span><span class="sc">*</span>x1) <span class="sc">+</span> (<span class="fl">57736.28</span><span class="sc">*</span>x2)</span>
<span id="cb49-197"><a href="#cb49-197" aria-hidden="true" tabindex="-1"></a>ŷ</span>
<span id="cb49-198"><a href="#cb49-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-199"><a href="#cb49-199" aria-hidden="true" tabindex="-1"></a>ŷ2 <span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">40230.87</span>) <span class="sc">+</span> (<span class="fl">116.13</span><span class="sc">*</span>x1) <span class="sc">+</span> (<span class="fl">57736.28</span><span class="sc">*</span>x3)</span>
<span id="cb49-200"><a href="#cb49-200" aria-hidden="true" tabindex="-1"></a>ŷ2</span>
<span id="cb49-201"><a href="#cb49-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-202"><a href="#cb49-202" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-203"><a href="#cb49-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-204"><a href="#cb49-204" aria-hidden="true" tabindex="-1"></a>(i<span class="sc">\)</span> The predicted selling price of a house that is new and 3000 square feet is $365,895.40.  </span>
<span id="cb49-205"><a href="#cb49-205" aria-hidden="true" tabindex="-1"></a>(ii<span class="sc">\)</span> The predicted selling price of a house that is not new and 3000 square feet is $308,159.10.  </span>
<span id="cb49-206"><a href="#cb49-206" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-207"><a href="#cb49-207" aria-hidden="true" tabindex="-1"></a><span class="fu">#### d\) Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results.  </span></span>
<span id="cb49-208"><a href="#cb49-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-209"><a href="#cb49-209" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 3d}</span></span>
<span id="cb49-210"><a href="#cb49-210" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size <span class="sc">*</span> New, <span class="at">data =</span> house.selling.price))</span>
<span id="cb49-211"><a href="#cb49-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-212"><a href="#cb49-212" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-213"><a href="#cb49-213" aria-hidden="true" tabindex="-1"></a>The results of the regression show that the size of the house as a significant relationship to the selling price with a p value of &lt; 2e-16. The price of the house increases by 104 dollars for every square foot. Whether the house is new is now no longer a significant relationship to the price of the house with a p value of 0.127 and a negative coefficient. This means newer homes decrease the price. However the relationship between size and newness has a significant relationship to selling price with a p value of 0.00527. </span>
<span id="cb49-214"><a href="#cb49-214" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-215"><a href="#cb49-215" aria-hidden="true" tabindex="-1"></a><span class="fu">#### e\) Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.  </span></span>
<span id="cb49-216"><a href="#cb49-216" aria-hidden="true" tabindex="-1"></a>ŷ = -22227.81 + 104.44x1 - 78527.50x2 + 61.92x3  </span>
<span id="cb49-217"><a href="#cb49-217" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-218"><a href="#cb49-218" aria-hidden="true" tabindex="-1"></a>(i<span class="sc">\)</span> New Homes:  </span>
<span id="cb49-219"><a href="#cb49-219" aria-hidden="true" tabindex="-1"></a>ŷ = -22227.81 + 104.44x1 - 78527.50(1) + 61.92x3  </span>
<span id="cb49-220"><a href="#cb49-220" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb49-221"><a href="#cb49-221" aria-hidden="true" tabindex="-1"></a>(ii<span class="sc">\)</span> Not New Homes:  </span>
<span id="cb49-222"><a href="#cb49-222" aria-hidden="true" tabindex="-1"></a>ŷ = -22227.81 + 104.44x1 - 78527.50(0) + 61.92x3 Therefore  </span>
<span id="cb49-223"><a href="#cb49-223" aria-hidden="true" tabindex="-1"></a>ŷ = -22227.81 + 104.44x1 + 61.92x3  </span>
<span id="cb49-224"><a href="#cb49-224" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb49-225"><a href="#cb49-225" aria-hidden="true" tabindex="-1"></a><span class="fu">#### f\) Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.  </span></span>
<span id="cb49-226"><a href="#cb49-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-227"><a href="#cb49-227" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 3f}</span></span>
<span id="cb49-228"><a href="#cb49-228" aria-hidden="true" tabindex="-1"></a><span class="co">#New Home</span></span>
<span id="cb49-229"><a href="#cb49-229" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">3000</span></span>
<span id="cb49-230"><a href="#cb49-230" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb49-231"><a href="#cb49-231" aria-hidden="true" tabindex="-1"></a>x3<span class="ot">&lt;-</span>x2<span class="sc">*</span>x1</span>
<span id="cb49-232"><a href="#cb49-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-233"><a href="#cb49-233" aria-hidden="true" tabindex="-1"></a>predict_selling_price_fi<span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">22227.81</span>) <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span>x1) <span class="sc">-</span> (<span class="fl">78527.50</span><span class="sc">*</span>x2) <span class="sc">+</span> (<span class="fl">61.92</span><span class="sc">*</span>x3)</span>
<span id="cb49-234"><a href="#cb49-234" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predict_selling_price_fi)</span>
<span id="cb49-235"><a href="#cb49-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-236"><a href="#cb49-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-237"><a href="#cb49-237" aria-hidden="true" tabindex="-1"></a><span class="co">#Not New Home</span></span>
<span id="cb49-238"><a href="#cb49-238" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">3000</span></span>
<span id="cb49-239"><a href="#cb49-239" aria-hidden="true" tabindex="-1"></a>x4<span class="ot">&lt;-</span><span class="dv">0</span></span>
<span id="cb49-240"><a href="#cb49-240" aria-hidden="true" tabindex="-1"></a>x3<span class="ot">&lt;-</span>x4<span class="sc">*</span>x1</span>
<span id="cb49-241"><a href="#cb49-241" aria-hidden="true" tabindex="-1"></a>predict_selling_price_fii<span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">22227.81</span>) <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span>x1) <span class="sc">-</span> (<span class="fl">78527.50</span><span class="sc">*</span>x4) <span class="sc">+</span> (<span class="fl">61.92</span><span class="sc">*</span>x3)</span>
<span id="cb49-242"><a href="#cb49-242" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predict_selling_price_fii)</span>
<span id="cb49-243"><a href="#cb49-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-244"><a href="#cb49-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-245"><a href="#cb49-245" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-246"><a href="#cb49-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-247"><a href="#cb49-247" aria-hidden="true" tabindex="-1"></a>(i<span class="sc">\)</span> New home of 3000 square feet has a predicted selling price of $398,324.70  </span>
<span id="cb49-248"><a href="#cb49-248" aria-hidden="true" tabindex="-1"></a>(ii<span class="sc">\)</span> Not new home of 3000 square feet has a predicted selling price of $291,092.20  </span>
<span id="cb49-249"><a href="#cb49-249" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb49-250"><a href="#cb49-250" aria-hidden="true" tabindex="-1"></a><span class="fu">#### g\) Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.     </span></span>
<span id="cb49-251"><a href="#cb49-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-252"><a href="#cb49-252" aria-hidden="true" tabindex="-1"></a><span class="in">```{r 3g}</span></span>
<span id="cb49-253"><a href="#cb49-253" aria-hidden="true" tabindex="-1"></a><span class="co">#New Home</span></span>
<span id="cb49-254"><a href="#cb49-254" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">1500</span></span>
<span id="cb49-255"><a href="#cb49-255" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb49-256"><a href="#cb49-256" aria-hidden="true" tabindex="-1"></a>x3<span class="ot">&lt;-</span>x2<span class="sc">*</span>x1</span>
<span id="cb49-257"><a href="#cb49-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-258"><a href="#cb49-258" aria-hidden="true" tabindex="-1"></a>predict_selling_price_fi<span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">22227.81</span>) <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span>x1) <span class="sc">-</span> (<span class="fl">78527.50</span><span class="sc">*</span>x2) <span class="sc">+</span> (<span class="fl">61.92</span><span class="sc">*</span>x3)</span>
<span id="cb49-259"><a href="#cb49-259" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predict_selling_price_fi)</span>
<span id="cb49-260"><a href="#cb49-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-261"><a href="#cb49-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-262"><a href="#cb49-262" aria-hidden="true" tabindex="-1"></a><span class="co">#Not New Home</span></span>
<span id="cb49-263"><a href="#cb49-263" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="dv">1500</span></span>
<span id="cb49-264"><a href="#cb49-264" aria-hidden="true" tabindex="-1"></a>x4<span class="ot">&lt;-</span><span class="dv">0</span></span>
<span id="cb49-265"><a href="#cb49-265" aria-hidden="true" tabindex="-1"></a>x3<span class="ot">&lt;-</span>x4<span class="sc">*</span>x1</span>
<span id="cb49-266"><a href="#cb49-266" aria-hidden="true" tabindex="-1"></a>predict_selling_price_fii<span class="ot">&lt;-</span> (<span class="sc">-</span><span class="fl">22227.81</span>) <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span>x1) <span class="sc">-</span> (<span class="fl">78527.50</span><span class="sc">*</span>x4) <span class="sc">+</span> (<span class="fl">61.92</span><span class="sc">*</span>x3)</span>
<span id="cb49-267"><a href="#cb49-267" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predict_selling_price_fii)</span>
<span id="cb49-268"><a href="#cb49-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-269"><a href="#cb49-269" aria-hidden="true" tabindex="-1"></a><span class="fl">398324.70</span><span class="sc">/</span><span class="fl">148784.70</span></span>
<span id="cb49-270"><a href="#cb49-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-271"><a href="#cb49-271" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-272"><a href="#cb49-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-273"><a href="#cb49-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-274"><a href="#cb49-274" aria-hidden="true" tabindex="-1"></a>(i<span class="sc">\)</span> New home of 1500 square feet has a predicted selling price of $148784.70  </span>
<span id="cb49-275"><a href="#cb49-275" aria-hidden="true" tabindex="-1"></a>(ii<span class="sc">\)</span> Not new home of 1500 square feet has a predicted selling price of $134432.20  </span>
<span id="cb49-276"><a href="#cb49-276" aria-hidden="true" tabindex="-1"></a>The price of a home went from 148784.70 dollars for a 1500 square foot house to $398,324.70 for a 3000 square foot house. This is a price increase of 2.7x with 2x increase in square feet. This means that the price increases a higher rate than 1-1 for square feet to dollar. According to the coefficient of the model, 104.438, for every 1 square foot increase the price increases by 104.44 dollars.    </span>
<span id="cb49-277"><a href="#cb49-277" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-278"><a href="#cb49-278" aria-hidden="true" tabindex="-1"></a><span class="fu">#### h\) Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?   </span></span>
<span id="cb49-279"><a href="#cb49-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-280"><a href="#cb49-280" aria-hidden="true" tabindex="-1"></a>**The Non-interaction Model**:</span>
<span id="cb49-281"><a href="#cb49-281" aria-hidden="true" tabindex="-1"></a>(Intercept) -40230.867</span>
<span id="cb49-282"><a href="#cb49-282" aria-hidden="true" tabindex="-1"></a>Adjusted R-squared:  0.7169 </span>
<span id="cb49-283"><a href="#cb49-283" aria-hidden="true" tabindex="-1"></a>p-value: &lt; 2.2e-16</span>
<span id="cb49-284"><a href="#cb49-284" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-285"><a href="#cb49-285" aria-hidden="true" tabindex="-1"></a>(i<span class="sc">\)</span> The predicted selling price of a house that is new and 3000 square feet is $365,895.40.  </span>
<span id="cb49-286"><a href="#cb49-286" aria-hidden="true" tabindex="-1"></a>(ii<span class="sc">\)</span> The predicted selling price of a house that is not new and 3000 square feet is $308,159.10.  </span>
<span id="cb49-287"><a href="#cb49-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-288"><a href="#cb49-288" aria-hidden="true" tabindex="-1"></a>**The interaction Model**:</span>
<span id="cb49-289"><a href="#cb49-289" aria-hidden="true" tabindex="-1"></a>(Intercept) -22227.808</span>
<span id="cb49-290"><a href="#cb49-290" aria-hidden="true" tabindex="-1"></a>Adjusted R-squared:  0.7363 </span>
<span id="cb49-291"><a href="#cb49-291" aria-hidden="true" tabindex="-1"></a>p-value: &lt; 2.2e-16</span>
<span id="cb49-292"><a href="#cb49-292" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-293"><a href="#cb49-293" aria-hidden="true" tabindex="-1"></a>(i<span class="sc">\)</span> New home of 3000 square feet has a predicted selling price of $398,324.70  </span>
<span id="cb49-294"><a href="#cb49-294" aria-hidden="true" tabindex="-1"></a>(ii<span class="sc">\)</span> Not new home of 3000 square feet has a predicted selling price of $291,092.20  </span>
<span id="cb49-295"><a href="#cb49-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-296"><a href="#cb49-296" aria-hidden="true" tabindex="-1"></a>I believe the second model, with the interaction between "newness" and size is a more predictive model for the selling price. First looking at the adjusted R-squared, it is larger in interaction model (0.7363) compared to the non-interaction model (0.7169). Second, comparing the two models, we see that "New" is significant in the first model (p value of 0.00257), however it is no longer significant when we run the model with the interaction (p value of 0.12697). This means, the interaction of "newness" and size is more predictive than "newness" alone. Lastly, when comparing the predicted selling price for a 3000 square foot house, the interaction model allows for more variation. This would reflect more real world scenarios than the first, non-interactive, model. </span>
<span id="cb49-297"><a href="#cb49-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-298"><a href="#cb49-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-299"><a href="#cb49-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-300"><a href="#cb49-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-301"><a href="#cb49-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-302"><a href="#cb49-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-303"><a href="#cb49-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-304"><a href="#cb49-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-305"><a href="#cb49-305" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>