<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Felix Betanourt">
<meta name="dcterms.date" content="2023-04-25">

<title>Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Homework 4">
<meta name="twitter:description" content="">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#homework-4" id="toc-homework-4" class="nav-link active" data-scroll-target="#homework-4">Homework 4</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 4</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw4</div>
    <div class="quarto-category">simple regression</div>
    <div class="quarto-category">multiple regression</div>
    <div class="quarto-category">non-linear function</div>
    <div class="quarto-category">p-value</div>
    <div class="quarto-category">model fitting</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Felix Betanourt </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 25, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="homework-4" class="level2">
<h2 class="anchored" data-anchor-id="homework-4">Homework 4</h2>
<p>DACSS 603, Spring 2023</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading packages</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(dplyr))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(tidyverse))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(formattable)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(kableExtra))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(alr4))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(smss))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Some of the questions use data from the alr4 and smss R packages. You would need to call in those packages in R (no need for an install.packages() call in your .qmd file, though—just use library()) and load the data using the data() function.</p>
<p>Question 1</p>
<p>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.</p>
<p>A. A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</p>
<p>Predicted value:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> <span class="fl">53.8</span><span class="sc">*</span><span class="dv">1240</span> <span class="sc">+</span> <span class="fl">2.84</span><span class="sc">*</span><span class="dv">18000</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>predicted</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107296</code></pre>
</div>
</div>
<p>Residual:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>residual <span class="ot">&lt;-</span> <span class="dv">145000-107296</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>residual </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37704</code></pre>
</div>
</div>
<p>The predicted value is $107,296 therefore the the residual is $37,704. The residual is positive, which means that the model is under-predicting. Would be appropriate to check with other actual values and adjusting the regression model for better fit.</p>
<p>B. For fixed lot size, how much is the house selling price predicted to increase for each square foot increase in home size? Why?</p>
<p>The slope for lot size is 2.84, this means that for every square foot the price should increase by $2.84.</p>
<p>C. According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> (<span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>x2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.94366</code></pre>
</div>
</div>
<p>lot size should increase almost 19 times to have the same impact in the price as home size.</p>
<p>Question 2</p>
<p>(Data file: salary in alr4 R package).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   52 obs. of  6 variables:
 $ degree: Factor w/ 2 levels "Masters","PhD": 1 1 1 1 2 1 2 1 2 2 ...
 $ rank  : Factor w/ 3 levels "Asst","Assoc",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ sex   : Factor w/ 2 levels "Male","Female": 1 1 1 2 1 1 2 1 1 1 ...
 $ year  : int  25 13 10 7 19 16 0 16 13 13 ...
 $ ysdeg : int  35 22 23 27 30 21 32 18 30 31 ...
 $ salary: int  36350 35350 28200 26775 33696 28516 24900 31909 31850 32850 ...</code></pre>
</div>
</div>
<p>The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue.</p>
<p>All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</p>
<p>A. Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by sex
t = 1.7744, df = 21.591, p-value = 0.09009
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -567.8539 7247.1471
sample estimates:
  mean in group Male mean in group Female 
            24696.79             21357.14 </code></pre>
</div>
</div>
<p>Since p-value &gt; 0.05 , there is not significant difference between salary means for Males and Females.</p>
<p>B. Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#salary2 &lt;- salary%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a> <span class="co"># mutate(degree_o = case_when(</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#      degree == "Masters" ~ 0,</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#       degree == "PhD" ~ 1,</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>   <span class="co">#     )) %&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co">#  mutate(rank_o = case_when(</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a> <span class="co">#        rank == "Asst" ~ 1,</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#       rank == "Assoc" ~ 2,</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>   <span class="co">#      rank == "Prof" ~ 3,</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="co">#     )) %&gt;%</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co">#  mutate(sex_o = case_when(</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a> <span class="co">#        sex == "Male" ~ 0,</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="co">#       sex == "Female" ~ 1,</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>   <span class="co">#      ))</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ysdeg <span class="sc">+</span> year <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> degree, <span class="at">data=</span>salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ysdeg + year + rank + sex + degree, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
ysdeg        -124.57      77.49  -1.608    0.115    
year          476.31      94.91   5.018 8.65e-06 ***
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
degreePhD    1388.61    1018.75   1.363    0.180    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> salary, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by sex
t = 1.7744, df = 21.591, p-value = 0.09009
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -567.8539 7247.1471
sample estimates:
  mean in group Male mean in group Female 
            24696.79             21357.14 </code></pre>
</div>
</div>
<p>C. Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables.</p>
<ol type="a">
<li><p>The variables that predict salary are years in current rank, and rank, as those are variables with p-value&lt;0.05.</p></li>
<li><p>In terms of the coefficients:</p></li>
</ol>
<ul>
<li>Years in current rank: for each year in current rank the salary increases by 476 units.</li>
<li>Rank: the benchmark is assistant therefore by being associate there the salary is 5,292 higher than assistant and 11,118 higher for professor.</li>
<li>Gender/sex: females makes 1,166 more in salary than males. Not a significant variable to explain salary.</li>
<li>Degree: having a PhD means 1,388 more dollars than holding a Masters. Not a significant variable to explain salary.</li>
<li>Years since highest degree earned: in this case, more years means less salary, specifically 124 dollars less per year since highest degree was earned. Also, not a significant variable to explain salary.</li>
</ul>
<p>D. Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Assoc"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ysdeg <span class="sc">+</span> year <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> degree, <span class="at">data=</span>salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ysdeg + year + rank + sex + degree, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 21038.41    1109.12  18.969  &lt; 2e-16 ***
ysdeg        -124.57      77.49  -1.608    0.115    
year          476.31      94.91   5.018 8.65e-06 ***
rankAsst    -5292.36    1145.40  -4.621 3.22e-05 ***
rankProf     5826.40    1012.93   5.752 7.28e-07 ***
sexFemale    1166.37     925.57   1.260    0.214    
degreePhD    1388.61    1018.75   1.363    0.180    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(salary$salary - model2$fitted.values)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Being Assistant means 5,292 dollars less in salary compared to being Associate, and at the same time being Professor is 5,826 dollars more than Associate.</p>
<p>E. Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “[a] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts. Exclude the variable rank, refit, and summarize how your findings changed, if they did.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ysdeg <span class="sc">+</span> year <span class="sc">+</span> sex <span class="sc">+</span> degree, <span class="at">data=</span>salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ysdeg + year + sex + degree, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
ysdeg         339.40      80.62   4.210 0.000114 ***
year          351.97     142.48   2.470 0.017185 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>By excluding rank, we have these changes in the model:</p>
<ul>
<li><p>R squared is reduced from 0.85 to 0.63, this means that the rank has an relevant weight in explaining salary.</p></li>
<li><p>In this model years since highest degree earned has a significant relationship with salary, as well as Degree. Both variables were not significant in the model when rank is included.</p></li>
<li><p>Years in current rank reduces significance over salary, from a p-value &lt; 0.001 to a p-value &lt; 0.05.</p></li>
</ul>
<p>F. Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean.</p>
<p>Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</p>
<p>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>tenure <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="st">"15 or less"</span>, <span class="st">"More than 15"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>tenure <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(salary<span class="sc">$</span>tenure)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>salary2 <span class="ot">&lt;-</span> salary<span class="sc">%&gt;%</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">degree_o =</span> <span class="fu">case_when</span>(</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>        degree <span class="sc">==</span> <span class="st">"Masters"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>         degree <span class="sc">==</span> <span class="st">"PhD"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>        )) <span class="sc">%&gt;%</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rank_o =</span> <span class="fu">case_when</span>(</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>        rank <span class="sc">==</span> <span class="st">"Asst"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>        rank <span class="sc">==</span> <span class="st">"Assoc"</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>         rank <span class="sc">==</span> <span class="st">"Prof"</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>         )) <span class="sc">%&gt;%</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex_o =</span> <span class="fu">case_when</span>(</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>         sex <span class="sc">==</span> <span class="st">"Male"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>         sex <span class="sc">==</span> <span class="st">"Female"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>         )) <span class="sc">%&gt;%</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tenure_o =</span> <span class="fu">case_when</span>(</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>         tenure <span class="sc">==</span> <span class="st">"15 or less"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>         tenure <span class="sc">==</span> <span class="st">"More than 15"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>         ))</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> tenure_o, <span class="at">data =</span> salary2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by tenure_o
t = 5.6848, df = 48.319, p-value = 7.427e-07
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 4746.660 9940.417
sample estimates:
mean in group 0 mean in group 1 
       27469.42        20125.88 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(salary2[, <span class="fu">c</span>(<span class="st">"ysdeg"</span>, <span class="st">"rank_o"</span>, <span class="st">"year"</span>, <span class="st">"sex_o"</span>, <span class="st">"tenure_o"</span>, <span class="st">"degree_o"</span>)], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cor_matrix, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         ysdeg rank_o  year sex_o tenure_o degree_o
ysdeg     1.00   0.70  0.64 -0.09    -0.84     0.48
rank_o    0.70   1.00  0.51 -0.23    -0.72     0.01
year      0.64   0.51  1.00 -0.38    -0.54     0.14
sex_o    -0.09  -0.23 -0.38  1.00     0.09    -0.08
tenure_o -0.84  -0.72 -0.54  0.09     1.00    -0.24
degree_o  0.48   0.01  0.14 -0.08    -0.24     1.00</code></pre>
</div>
</div>
<p>Years since highest degree earned has an strong correlation with tenure (new variable result of dividing the population in when they were hired). It was expected because tenure is a variable created based on years since highest degree earned (Everyone in this dataset was hired the year they earned their highest degree).</p>
<p>So there is multicollinearity for these 2 variables, so I will exclude years since highest degree earned from the model and keep tenure.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> year <span class="sc">+</span> tenure_o <span class="sc">+</span> rank <span class="sc">+</span> sex_o <span class="sc">+</span> degree_o, <span class="at">data=</span>salary2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ year + tenure_o + rank + sex_o + degree_o, 
    data = salary2)

Residuals:
    Min      1Q  Median      3Q     Max 
-3403.3 -1387.0  -167.0   528.2  9233.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 18301.04    1301.36  14.063  &lt; 2e-16 ***
year          434.85      78.89   5.512 1.65e-06 ***
tenure_o     2163.46    1072.04   2.018   0.0496 *  
rankAsst    -4972.66     997.17  -4.987 9.61e-06 ***
rankProf     6124.28    1028.58   5.954 3.65e-07 ***
sex_o         907.14     840.54   1.079   0.2862    
degree_o      818.93     797.48   1.027   0.3100    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2362 on 45 degrees of freedom
Multiple R-squared:  0.8594,    Adjusted R-squared:  0.8407 
F-statistic: 45.86 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Seems that with a significant p-value (&lt;0.05), being hired 15 years ago or less means higher salary than faculty with more than 15 years. Specifically, being in the group of 15 years or less means 2,163 dollars more than the other group.</p>
<p>Question 3</p>
<p>(Data file: house.selling.price in smss R package)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>house <span class="ot">&lt;-</span> house.selling.price</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(house)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100 obs. of  7 variables:
 $ case : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Taxes: int  3104 1173 3076 1608 1454 2997 4054 3002 6627 320 ...
 $ Beds : int  4 2 4 3 3 3 3 3 5 3 ...
 $ Baths: int  2 1 2 2 3 2 2 2 4 2 ...
 $ New  : int  0 0 0 0 0 1 0 1 0 0 ...
 $ Price: int  279900 146500 237700 200000 159900 499900 265500 289900 587000 70000 ...
 $ Size : int  2048 912 1654 2068 1477 3153 1355 2075 3990 1160 ...</code></pre>
</div>
</div>
<p>A. Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data=</span>house))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Both independent variables (Size and if New or not) are statistically significant to predict the home price. In particular, for every square feet the home price increases by $116.13, and when the house is new the price is higher in $57,736 compared when is not new.</p>
<p>B. Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</p>
<p>The prediction equation is:</p>
<p>y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = home is new (1 = yes; 0 = no), the prediction equation for new homes is</p>
<p>ŷ = -40230.867 + 116.132x1 + 57736.283</p>
<p>For the no new homes prediction equation we need to calculate the slope for no new (value 0 in the variable):</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>slope_nonew <span class="ot">&lt;-</span> <span class="fu">coef</span>(model5)[<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">coef</span>(model5)[<span class="dv">3</span>]</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>slope_nonew</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  -97967.15 </code></pre>
</div>
</div>
<p>Prediction equation for No New home:</p>
<p>ŷ = -40230.867 + 116.132x1 - 97967.15</p>
<p>C. Find the predicted selling price for a home of 3000 square feet that is (i) new</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>predicted_new_house <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span> <span class="sc">+</span> <span class="fl">57736.283</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>predicted_new_house</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 365901.4</code></pre>
</div>
</div>
<ol start="2" type="i">
<li>not new</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>predicted_nonew_house <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span> <span class="sc">-</span> <span class="fl">97967.15</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>predicted_nonew_house</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 210198</code></pre>
</div>
</div>
<p>D. Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size<span class="sc">*</span>New, <span class="at">data=</span>house))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New + Size * New, data = house)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>E. Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</p>
<p>The prediction formula for this model is:</p>
<p>ŷ = -22227.808 + 104.438<em>size - 78527.502</em>new (0 or 1) + 61.916<em>size</em>new (0 or 1).</p>
<p>To predict price for new or not new houses, we would need just to use the values 1 or 0 in the “new” variable.</p>
<p>F. Find the predicted selling price for a home of 3000 square feet that is (i) new,</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="dv">1</span>, </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="dv">3000</span>  </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>predicted_price <span class="ot">&lt;-</span> <span class="fu">predict</span>(model7, newdata)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>predicted_price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
398307.5 </code></pre>
</div>
</div>
<ol start="2" type="i">
<li>not new.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="dv">0</span>, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="dv">3000</span>  </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>predicted_price2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model7, newdata)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>predicted_price2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
291087.4 </code></pre>
</div>
</div>
<p>G. Find the predicted selling price for a home of 1500 square feet that is (i) new,</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="dv">1</span>, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="dv">1500</span>  </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>predicted_price3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model7, newdata)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>predicted_price3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
148776.1 </code></pre>
</div>
</div>
<ol start="2" type="i">
<li>not new.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>newdata2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="dv">0</span>, </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="dv">1500</span>  </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>predicted_price4 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model7, newdata2)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>predicted_price4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
134429.8 </code></pre>
</div>
</div>
<p>Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Difference in price for model in question F</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>diff_f <span class="ot">&lt;-</span> predicted_price <span class="sc">-</span> predicted_price2</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>diff_f</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
107220.1 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>diff_g <span class="ot">&lt;-</span> predicted_price3 <span class="sc">-</span> predicted_price4</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>diff_g</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
14346.32 </code></pre>
</div>
</div>
<p>Seems that the difference in price between new or not new homes is bigger when the size is higher. For instance, for a new house with 3000 sqf is $107k higher than no new. But for 1500 sqf the new house is only $14k more.</p>
<p>H. Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another</p>
<p>Both models seems good to predict price given p-value for F-statistics is significant in both models, however the the value of F itself is a lot higher in the model with no interaction size-new, which means that there is better fit in this model compared to the interaction model.</p>
<p>The R2 and Adjusted R2 are similar in both models, so the interaction doesn’t seems to add more explanation to the variations to the home price.</p>
<p>On the other hand, the interaction model provides an additional insight which is that the difference in price between new and no new houses is moderated by the size. This moderation is relevant to understand the price variation and it is not captured in the no-interaction model.</p>
<p>For those reasons, I would rather use the model with the interaction.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb52" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 4"</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Felix Betanourt"</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "DACSS 603 HW4"</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "04/25/2023"</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw4</span></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - simple regression</span></span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - multiple regression</span></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - non-linear function</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a><span class="co">  - p-value</span></span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a><span class="co">  - model fitting</span></span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a><span class="an">editor:</span><span class="co"> </span></span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a><span class="co">  markdown: </span></span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a><span class="co">    wrap: 72</span></span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-26"><a href="#cb52-26" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-27"><a href="#cb52-27" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb52-28"><a href="#cb52-28" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb52-29"><a href="#cb52-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-30"><a href="#cb52-30" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span>
<span id="cb52-31"><a href="#cb52-31" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-32"><a href="#cb52-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-33"><a href="#cb52-33" aria-hidden="true" tabindex="-1"></a><span class="fu">## Homework 4</span></span>
<span id="cb52-34"><a href="#cb52-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-35"><a href="#cb52-35" aria-hidden="true" tabindex="-1"></a>DACSS 603, Spring 2023</span>
<span id="cb52-36"><a href="#cb52-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-39"><a href="#cb52-39" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-40"><a href="#cb52-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading packages</span></span>
<span id="cb52-41"><a href="#cb52-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-42"><a href="#cb52-42" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(dplyr))</span>
<span id="cb52-43"><a href="#cb52-43" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(tidyverse))</span>
<span id="cb52-44"><a href="#cb52-44" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(formattable)</span>
<span id="cb52-45"><a href="#cb52-45" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(kableExtra))</span>
<span id="cb52-46"><a href="#cb52-46" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb52-47"><a href="#cb52-47" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(alr4))</span>
<span id="cb52-48"><a href="#cb52-48" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(smss))</span>
<span id="cb52-49"><a href="#cb52-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-50"><a href="#cb52-50" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-51"><a href="#cb52-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-52"><a href="#cb52-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-53"><a href="#cb52-53" aria-hidden="true" tabindex="-1"></a>Some of the questions use data from the alr4 and smss R packages. You would need to call in those packages in R (no need for an  install.packages() call in your .qmd file, though—just use library()) and load the data using the data() function.</span>
<span id="cb52-54"><a href="#cb52-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-55"><a href="#cb52-55" aria-hidden="true" tabindex="-1"></a>Question 1</span>
<span id="cb52-56"><a href="#cb52-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-57"><a href="#cb52-57" aria-hidden="true" tabindex="-1"></a>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.</span>
<span id="cb52-58"><a href="#cb52-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-59"><a href="#cb52-59" aria-hidden="true" tabindex="-1"></a>A. A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</span>
<span id="cb52-60"><a href="#cb52-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-61"><a href="#cb52-61" aria-hidden="true" tabindex="-1"></a>Predicted value:</span>
<span id="cb52-62"><a href="#cb52-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-65"><a href="#cb52-65" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-66"><a href="#cb52-66" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> <span class="fl">53.8</span><span class="sc">*</span><span class="dv">1240</span> <span class="sc">+</span> <span class="fl">2.84</span><span class="sc">*</span><span class="dv">18000</span></span>
<span id="cb52-67"><a href="#cb52-67" aria-hidden="true" tabindex="-1"></a>predicted</span>
<span id="cb52-68"><a href="#cb52-68" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-69"><a href="#cb52-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-70"><a href="#cb52-70" aria-hidden="true" tabindex="-1"></a>Residual:</span>
<span id="cb52-71"><a href="#cb52-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-74"><a href="#cb52-74" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-75"><a href="#cb52-75" aria-hidden="true" tabindex="-1"></a>residual <span class="ot">&lt;-</span> <span class="dv">145000-107296</span></span>
<span id="cb52-76"><a href="#cb52-76" aria-hidden="true" tabindex="-1"></a>residual </span>
<span id="cb52-77"><a href="#cb52-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-78"><a href="#cb52-78" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-79"><a href="#cb52-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-80"><a href="#cb52-80" aria-hidden="true" tabindex="-1"></a>The predicted value is $107,296 therefore the the residual is $37,704. The residual is positive, which means that the model is under-predicting. Would be appropriate to check with other actual values and adjusting the regression model for better fit.</span>
<span id="cb52-81"><a href="#cb52-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-82"><a href="#cb52-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-83"><a href="#cb52-83" aria-hidden="true" tabindex="-1"></a>B. For fixed lot size, how much is the house selling price predicted to increase for each square foot increase in home size? Why?</span>
<span id="cb52-84"><a href="#cb52-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-85"><a href="#cb52-85" aria-hidden="true" tabindex="-1"></a>The slope for lot size is 2.84, this means that for every square foot the price should increase by $2.84.</span>
<span id="cb52-86"><a href="#cb52-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-87"><a href="#cb52-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-88"><a href="#cb52-88" aria-hidden="true" tabindex="-1"></a>C. According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</span>
<span id="cb52-89"><a href="#cb52-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-92"><a href="#cb52-92" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-93"><a href="#cb52-93" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> (<span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span>)</span>
<span id="cb52-94"><a href="#cb52-94" aria-hidden="true" tabindex="-1"></a>x2</span>
<span id="cb52-95"><a href="#cb52-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-96"><a href="#cb52-96" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-97"><a href="#cb52-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-98"><a href="#cb52-98" aria-hidden="true" tabindex="-1"></a>lot size should increase almost 19 times to have the same impact in the price as home size. </span>
<span id="cb52-99"><a href="#cb52-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-100"><a href="#cb52-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-101"><a href="#cb52-101" aria-hidden="true" tabindex="-1"></a>Question 2</span>
<span id="cb52-102"><a href="#cb52-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-103"><a href="#cb52-103" aria-hidden="true" tabindex="-1"></a>(Data file: salary in alr4 R package). </span>
<span id="cb52-104"><a href="#cb52-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-107"><a href="#cb52-107" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-108"><a href="#cb52-108" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(salary)</span>
<span id="cb52-109"><a href="#cb52-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-110"><a href="#cb52-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-111"><a href="#cb52-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-112"><a href="#cb52-112" aria-hidden="true" tabindex="-1"></a>The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. </span>
<span id="cb52-113"><a href="#cb52-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-114"><a href="#cb52-114" aria-hidden="true" tabindex="-1"></a>All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</span>
<span id="cb52-115"><a href="#cb52-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-116"><a href="#cb52-116" aria-hidden="true" tabindex="-1"></a>A. Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</span>
<span id="cb52-117"><a href="#cb52-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-120"><a href="#cb52-120" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-121"><a href="#cb52-121" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> salary)</span>
<span id="cb52-122"><a href="#cb52-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-123"><a href="#cb52-123" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-124"><a href="#cb52-124" aria-hidden="true" tabindex="-1"></a>Since p-value &gt; 0.05 , there is not significant difference between salary means for Males and Females.</span>
<span id="cb52-125"><a href="#cb52-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-126"><a href="#cb52-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-127"><a href="#cb52-127" aria-hidden="true" tabindex="-1"></a>B. Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</span>
<span id="cb52-128"><a href="#cb52-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-131"><a href="#cb52-131" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-132"><a href="#cb52-132" aria-hidden="true" tabindex="-1"></a><span class="co">#salary2 &lt;- salary%&gt;%</span></span>
<span id="cb52-133"><a href="#cb52-133" aria-hidden="true" tabindex="-1"></a> <span class="co"># mutate(degree_o = case_when(</span></span>
<span id="cb52-134"><a href="#cb52-134" aria-hidden="true" tabindex="-1"></a>  <span class="co">#      degree == "Masters" ~ 0,</span></span>
<span id="cb52-135"><a href="#cb52-135" aria-hidden="true" tabindex="-1"></a>  <span class="co">#       degree == "PhD" ~ 1,</span></span>
<span id="cb52-136"><a href="#cb52-136" aria-hidden="true" tabindex="-1"></a>   <span class="co">#     )) %&gt;%</span></span>
<span id="cb52-137"><a href="#cb52-137" aria-hidden="true" tabindex="-1"></a><span class="co">#  mutate(rank_o = case_when(</span></span>
<span id="cb52-138"><a href="#cb52-138" aria-hidden="true" tabindex="-1"></a> <span class="co">#        rank == "Asst" ~ 1,</span></span>
<span id="cb52-139"><a href="#cb52-139" aria-hidden="true" tabindex="-1"></a>  <span class="co">#       rank == "Assoc" ~ 2,</span></span>
<span id="cb52-140"><a href="#cb52-140" aria-hidden="true" tabindex="-1"></a>   <span class="co">#      rank == "Prof" ~ 3,</span></span>
<span id="cb52-141"><a href="#cb52-141" aria-hidden="true" tabindex="-1"></a>    <span class="co">#     )) %&gt;%</span></span>
<span id="cb52-142"><a href="#cb52-142" aria-hidden="true" tabindex="-1"></a><span class="co">#  mutate(sex_o = case_when(</span></span>
<span id="cb52-143"><a href="#cb52-143" aria-hidden="true" tabindex="-1"></a> <span class="co">#        sex == "Male" ~ 0,</span></span>
<span id="cb52-144"><a href="#cb52-144" aria-hidden="true" tabindex="-1"></a>  <span class="co">#       sex == "Female" ~ 1,</span></span>
<span id="cb52-145"><a href="#cb52-145" aria-hidden="true" tabindex="-1"></a>   <span class="co">#      ))</span></span>
<span id="cb52-146"><a href="#cb52-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-147"><a href="#cb52-147" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ysdeg <span class="sc">+</span> year <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> degree, <span class="at">data=</span>salary))</span>
<span id="cb52-148"><a href="#cb52-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-149"><a href="#cb52-149" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> salary, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb52-150"><a href="#cb52-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-151"><a href="#cb52-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-152"><a href="#cb52-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-153"><a href="#cb52-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-154"><a href="#cb52-154" aria-hidden="true" tabindex="-1"></a>C. Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables.</span>
<span id="cb52-155"><a href="#cb52-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-156"><a href="#cb52-156" aria-hidden="true" tabindex="-1"></a>a) The variables that predict salary are years in current rank, and rank, as those are variables with p-value&lt;0.05.</span>
<span id="cb52-157"><a href="#cb52-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-158"><a href="#cb52-158" aria-hidden="true" tabindex="-1"></a>b) In terms of the coefficients:</span>
<span id="cb52-159"><a href="#cb52-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-160"><a href="#cb52-160" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Years in current rank: for each year in current rank the salary increases by 476 units.</span>
<span id="cb52-161"><a href="#cb52-161" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rank: the benchmark is assistant therefore by being associate there the salary is 5,292 higher than assistant and 11,118 higher for professor.</span>
<span id="cb52-162"><a href="#cb52-162" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Gender/sex: females makes 1,166 more in salary than males. Not a significant variable to explain salary.</span>
<span id="cb52-163"><a href="#cb52-163" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Degree: having a PhD means 1,388 more dollars than holding a Masters. Not a significant variable to explain salary.</span>
<span id="cb52-164"><a href="#cb52-164" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Years since highest degree earned: in this case, more years means less salary, specifically 124 dollars less per year since highest degree was earned. Also, not a significant variable to explain salary.</span>
<span id="cb52-165"><a href="#cb52-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-166"><a href="#cb52-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-167"><a href="#cb52-167" aria-hidden="true" tabindex="-1"></a>D. Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</span>
<span id="cb52-168"><a href="#cb52-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-171"><a href="#cb52-171" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-172"><a href="#cb52-172" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Assoc"</span>)</span>
<span id="cb52-173"><a href="#cb52-173" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ysdeg <span class="sc">+</span> year <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> degree, <span class="at">data=</span>salary))</span>
<span id="cb52-174"><a href="#cb52-174" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(salary$salary - model2$fitted.values)</span></span>
<span id="cb52-175"><a href="#cb52-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-176"><a href="#cb52-176" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-177"><a href="#cb52-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-178"><a href="#cb52-178" aria-hidden="true" tabindex="-1"></a>Being Assistant means 5,292 dollars less in salary compared to being Associate, and at the same time being Professor is 5,826 dollars more than Associate.</span>
<span id="cb52-179"><a href="#cb52-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-180"><a href="#cb52-180" aria-hidden="true" tabindex="-1"></a>E. Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “<span class="co">[</span><span class="ot">a</span><span class="co">]</span> variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’ ” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.</span>
<span id="cb52-181"><a href="#cb52-181" aria-hidden="true" tabindex="-1"></a>Exclude the variable rank, refit, and summarize how your findings changed, if they did.</span>
<span id="cb52-182"><a href="#cb52-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-185"><a href="#cb52-185" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-186"><a href="#cb52-186" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ysdeg <span class="sc">+</span> year <span class="sc">+</span> sex <span class="sc">+</span> degree, <span class="at">data=</span>salary))</span>
<span id="cb52-187"><a href="#cb52-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-188"><a href="#cb52-188" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-189"><a href="#cb52-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-190"><a href="#cb52-190" aria-hidden="true" tabindex="-1"></a>By excluding rank, we have these changes in the model:</span>
<span id="cb52-191"><a href="#cb52-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-192"><a href="#cb52-192" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>R squared is reduced from 0.85 to 0.63, this means that the rank has an relevant weight in explaining salary.</span>
<span id="cb52-193"><a href="#cb52-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-194"><a href="#cb52-194" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>In this model years since highest degree earned has a significant relationship with salary, as well as Degree. Both variables were not significant in the model when rank is included.</span>
<span id="cb52-195"><a href="#cb52-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-196"><a href="#cb52-196" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Years in current rank reduces significance over salary, from a p-value &lt; 0.001 to a p-value &lt; 0.05.</span>
<span id="cb52-197"><a href="#cb52-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-198"><a href="#cb52-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-199"><a href="#cb52-199" aria-hidden="true" tabindex="-1"></a>F. Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. </span>
<span id="cb52-200"><a href="#cb52-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-201"><a href="#cb52-201" aria-hidden="true" tabindex="-1"></a>Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</span>
<span id="cb52-202"><a href="#cb52-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-203"><a href="#cb52-203" aria-hidden="true" tabindex="-1"></a>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</span>
<span id="cb52-204"><a href="#cb52-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-207"><a href="#cb52-207" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-208"><a href="#cb52-208" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>tenure <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="st">"15 or less"</span>, <span class="st">"More than 15"</span>)</span>
<span id="cb52-209"><a href="#cb52-209" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>tenure <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(salary<span class="sc">$</span>tenure)</span>
<span id="cb52-210"><a href="#cb52-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-211"><a href="#cb52-211" aria-hidden="true" tabindex="-1"></a>salary2 <span class="ot">&lt;-</span> salary<span class="sc">%&gt;%</span></span>
<span id="cb52-212"><a href="#cb52-212" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">degree_o =</span> <span class="fu">case_when</span>(</span>
<span id="cb52-213"><a href="#cb52-213" aria-hidden="true" tabindex="-1"></a>        degree <span class="sc">==</span> <span class="st">"Masters"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb52-214"><a href="#cb52-214" aria-hidden="true" tabindex="-1"></a>         degree <span class="sc">==</span> <span class="st">"PhD"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb52-215"><a href="#cb52-215" aria-hidden="true" tabindex="-1"></a>        )) <span class="sc">%&gt;%</span></span>
<span id="cb52-216"><a href="#cb52-216" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rank_o =</span> <span class="fu">case_when</span>(</span>
<span id="cb52-217"><a href="#cb52-217" aria-hidden="true" tabindex="-1"></a>        rank <span class="sc">==</span> <span class="st">"Asst"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb52-218"><a href="#cb52-218" aria-hidden="true" tabindex="-1"></a>        rank <span class="sc">==</span> <span class="st">"Assoc"</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb52-219"><a href="#cb52-219" aria-hidden="true" tabindex="-1"></a>         rank <span class="sc">==</span> <span class="st">"Prof"</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb52-220"><a href="#cb52-220" aria-hidden="true" tabindex="-1"></a>         )) <span class="sc">%&gt;%</span></span>
<span id="cb52-221"><a href="#cb52-221" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex_o =</span> <span class="fu">case_when</span>(</span>
<span id="cb52-222"><a href="#cb52-222" aria-hidden="true" tabindex="-1"></a>         sex <span class="sc">==</span> <span class="st">"Male"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb52-223"><a href="#cb52-223" aria-hidden="true" tabindex="-1"></a>         sex <span class="sc">==</span> <span class="st">"Female"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb52-224"><a href="#cb52-224" aria-hidden="true" tabindex="-1"></a>         )) <span class="sc">%&gt;%</span></span>
<span id="cb52-225"><a href="#cb52-225" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tenure_o =</span> <span class="fu">case_when</span>(</span>
<span id="cb52-226"><a href="#cb52-226" aria-hidden="true" tabindex="-1"></a>         tenure <span class="sc">==</span> <span class="st">"15 or less"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb52-227"><a href="#cb52-227" aria-hidden="true" tabindex="-1"></a>         tenure <span class="sc">==</span> <span class="st">"More than 15"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb52-228"><a href="#cb52-228" aria-hidden="true" tabindex="-1"></a>         ))</span>
<span id="cb52-229"><a href="#cb52-229" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb52-230"><a href="#cb52-230" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> tenure_o, <span class="at">data =</span> salary2)</span>
<span id="cb52-231"><a href="#cb52-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-232"><a href="#cb52-232" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(salary2[, <span class="fu">c</span>(<span class="st">"ysdeg"</span>, <span class="st">"rank_o"</span>, <span class="st">"year"</span>, <span class="st">"sex_o"</span>, <span class="st">"tenure_o"</span>, <span class="st">"degree_o"</span>)], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb52-233"><a href="#cb52-233" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cor_matrix, <span class="dv">2</span>)</span>
<span id="cb52-234"><a href="#cb52-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-235"><a href="#cb52-235" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-236"><a href="#cb52-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-237"><a href="#cb52-237" aria-hidden="true" tabindex="-1"></a>Years since highest degree earned has an strong correlation with tenure (new variable result of dividing the population in when they were hired). It was expected because tenure is a variable created based on years since highest degree earned (Everyone in this dataset was hired the year they earned their highest degree).</span>
<span id="cb52-238"><a href="#cb52-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-239"><a href="#cb52-239" aria-hidden="true" tabindex="-1"></a>So there is multicollinearity for these 2 variables, so I will exclude years since highest degree earned from the model and keep tenure.</span>
<span id="cb52-240"><a href="#cb52-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-241"><a href="#cb52-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-244"><a href="#cb52-244" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-245"><a href="#cb52-245" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> year <span class="sc">+</span> tenure_o <span class="sc">+</span> rank <span class="sc">+</span> sex_o <span class="sc">+</span> degree_o, <span class="at">data=</span>salary2))</span>
<span id="cb52-246"><a href="#cb52-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-247"><a href="#cb52-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-248"><a href="#cb52-248" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-249"><a href="#cb52-249" aria-hidden="true" tabindex="-1"></a>Seems that with a significant p-value (&lt;0.05), being hired 15 years ago or less means higher salary than faculty with more than 15 years. Specifically, being in the group of 15 years or less means 2,163 dollars more than the other group.</span>
<span id="cb52-250"><a href="#cb52-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-251"><a href="#cb52-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-252"><a href="#cb52-252" aria-hidden="true" tabindex="-1"></a>Question 3</span>
<span id="cb52-253"><a href="#cb52-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-254"><a href="#cb52-254" aria-hidden="true" tabindex="-1"></a>(Data file: house.selling.price in smss R package)</span>
<span id="cb52-255"><a href="#cb52-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-258"><a href="#cb52-258" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-259"><a href="#cb52-259" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb52-260"><a href="#cb52-260" aria-hidden="true" tabindex="-1"></a>house <span class="ot">&lt;-</span> house.selling.price</span>
<span id="cb52-261"><a href="#cb52-261" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(house)</span>
<span id="cb52-262"><a href="#cb52-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-263"><a href="#cb52-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-264"><a href="#cb52-264" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-265"><a href="#cb52-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-266"><a href="#cb52-266" aria-hidden="true" tabindex="-1"></a>A. Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</span>
<span id="cb52-267"><a href="#cb52-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-270"><a href="#cb52-270" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-271"><a href="#cb52-271" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data=</span>house))</span>
<span id="cb52-272"><a href="#cb52-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-273"><a href="#cb52-273" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-274"><a href="#cb52-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-275"><a href="#cb52-275" aria-hidden="true" tabindex="-1"></a>Both independent variables (Size and if New or not) are statistically significant to predict the home price. In particular, for every square feet the home price increases by $116.13, and when the house is new the price is higher in $57,736 compared when is not new.</span>
<span id="cb52-276"><a href="#cb52-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-277"><a href="#cb52-277" aria-hidden="true" tabindex="-1"></a>B. Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</span>
<span id="cb52-278"><a href="#cb52-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-279"><a href="#cb52-279" aria-hidden="true" tabindex="-1"></a>The prediction equation is:</span>
<span id="cb52-280"><a href="#cb52-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-281"><a href="#cb52-281" aria-hidden="true" tabindex="-1"></a>y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = home is new (1 = yes; 0 = no), the prediction equation for new homes is</span>
<span id="cb52-282"><a href="#cb52-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-283"><a href="#cb52-283" aria-hidden="true" tabindex="-1"></a>ŷ = -40230.867 + 116.132x1 + 57736.283</span>
<span id="cb52-284"><a href="#cb52-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-285"><a href="#cb52-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-286"><a href="#cb52-286" aria-hidden="true" tabindex="-1"></a>For the no new homes prediction equation we need to calculate the slope for no new (value 0 in the variable):</span>
<span id="cb52-287"><a href="#cb52-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-290"><a href="#cb52-290" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-291"><a href="#cb52-291" aria-hidden="true" tabindex="-1"></a>slope_nonew <span class="ot">&lt;-</span> <span class="fu">coef</span>(model5)[<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">coef</span>(model5)[<span class="dv">3</span>]</span>
<span id="cb52-292"><a href="#cb52-292" aria-hidden="true" tabindex="-1"></a>slope_nonew</span>
<span id="cb52-293"><a href="#cb52-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-294"><a href="#cb52-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-295"><a href="#cb52-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-296"><a href="#cb52-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-297"><a href="#cb52-297" aria-hidden="true" tabindex="-1"></a>Prediction equation for No New home:</span>
<span id="cb52-298"><a href="#cb52-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-299"><a href="#cb52-299" aria-hidden="true" tabindex="-1"></a>ŷ = -40230.867 + 116.132x1 - 97967.15</span>
<span id="cb52-300"><a href="#cb52-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-301"><a href="#cb52-301" aria-hidden="true" tabindex="-1"></a>C. Find the predicted selling price for a home of 3000 square feet that is (i) new</span>
<span id="cb52-302"><a href="#cb52-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-305"><a href="#cb52-305" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-306"><a href="#cb52-306" aria-hidden="true" tabindex="-1"></a>predicted_new_house <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span> <span class="sc">+</span> <span class="fl">57736.283</span></span>
<span id="cb52-307"><a href="#cb52-307" aria-hidden="true" tabindex="-1"></a>predicted_new_house</span>
<span id="cb52-308"><a href="#cb52-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-309"><a href="#cb52-309" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-310"><a href="#cb52-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-311"><a href="#cb52-311" aria-hidden="true" tabindex="-1"></a>(ii) not new</span>
<span id="cb52-312"><a href="#cb52-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-315"><a href="#cb52-315" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-316"><a href="#cb52-316" aria-hidden="true" tabindex="-1"></a>predicted_nonew_house <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span> <span class="sc">-</span> <span class="fl">97967.15</span></span>
<span id="cb52-317"><a href="#cb52-317" aria-hidden="true" tabindex="-1"></a>predicted_nonew_house</span>
<span id="cb52-318"><a href="#cb52-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-319"><a href="#cb52-319" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-320"><a href="#cb52-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-321"><a href="#cb52-321" aria-hidden="true" tabindex="-1"></a>D. Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</span>
<span id="cb52-322"><a href="#cb52-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-325"><a href="#cb52-325" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-326"><a href="#cb52-326" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (model7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size<span class="sc">*</span>New, <span class="at">data=</span>house))</span>
<span id="cb52-327"><a href="#cb52-327" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-328"><a href="#cb52-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-329"><a href="#cb52-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-330"><a href="#cb52-330" aria-hidden="true" tabindex="-1"></a>E. Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</span>
<span id="cb52-331"><a href="#cb52-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-332"><a href="#cb52-332" aria-hidden="true" tabindex="-1"></a>The prediction formula for this model is:</span>
<span id="cb52-333"><a href="#cb52-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-334"><a href="#cb52-334" aria-hidden="true" tabindex="-1"></a>ŷ = -22227.808 + 104.438*size - 78527.502*new (0 or 1) + 61.916*size*new (0 or 1).</span>
<span id="cb52-335"><a href="#cb52-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-336"><a href="#cb52-336" aria-hidden="true" tabindex="-1"></a>To predict price for new or not new houses, we would need just to use the values 1 or 0 in the "new" variable.</span>
<span id="cb52-337"><a href="#cb52-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-338"><a href="#cb52-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-339"><a href="#cb52-339" aria-hidden="true" tabindex="-1"></a>F. Find the predicted selling price for a home of 3000 square feet that is (i) new, </span>
<span id="cb52-340"><a href="#cb52-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-343"><a href="#cb52-343" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-344"><a href="#cb52-344" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb52-345"><a href="#cb52-345" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="dv">1</span>, </span>
<span id="cb52-346"><a href="#cb52-346" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="dv">3000</span>  </span>
<span id="cb52-347"><a href="#cb52-347" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-348"><a href="#cb52-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-349"><a href="#cb52-349" aria-hidden="true" tabindex="-1"></a>predicted_price <span class="ot">&lt;-</span> <span class="fu">predict</span>(model7, newdata)</span>
<span id="cb52-350"><a href="#cb52-350" aria-hidden="true" tabindex="-1"></a>predicted_price</span>
<span id="cb52-351"><a href="#cb52-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-352"><a href="#cb52-352" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-353"><a href="#cb52-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-354"><a href="#cb52-354" aria-hidden="true" tabindex="-1"></a>(ii) not new.</span>
<span id="cb52-357"><a href="#cb52-357" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-358"><a href="#cb52-358" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb52-359"><a href="#cb52-359" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="dv">0</span>, </span>
<span id="cb52-360"><a href="#cb52-360" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="dv">3000</span>  </span>
<span id="cb52-361"><a href="#cb52-361" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-362"><a href="#cb52-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-363"><a href="#cb52-363" aria-hidden="true" tabindex="-1"></a>predicted_price2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model7, newdata)</span>
<span id="cb52-364"><a href="#cb52-364" aria-hidden="true" tabindex="-1"></a>predicted_price2</span>
<span id="cb52-365"><a href="#cb52-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-366"><a href="#cb52-366" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-367"><a href="#cb52-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-368"><a href="#cb52-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-369"><a href="#cb52-369" aria-hidden="true" tabindex="-1"></a>G. Find the predicted selling price for a home of 1500 square feet that is (i) new, </span>
<span id="cb52-370"><a href="#cb52-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-373"><a href="#cb52-373" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-374"><a href="#cb52-374" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb52-375"><a href="#cb52-375" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="dv">1</span>, </span>
<span id="cb52-376"><a href="#cb52-376" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="dv">1500</span>  </span>
<span id="cb52-377"><a href="#cb52-377" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-378"><a href="#cb52-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-379"><a href="#cb52-379" aria-hidden="true" tabindex="-1"></a>predicted_price3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model7, newdata)</span>
<span id="cb52-380"><a href="#cb52-380" aria-hidden="true" tabindex="-1"></a>predicted_price3</span>
<span id="cb52-381"><a href="#cb52-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-382"><a href="#cb52-382" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-383"><a href="#cb52-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-384"><a href="#cb52-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-385"><a href="#cb52-385" aria-hidden="true" tabindex="-1"></a>(ii) not new. </span>
<span id="cb52-386"><a href="#cb52-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-389"><a href="#cb52-389" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-390"><a href="#cb52-390" aria-hidden="true" tabindex="-1"></a>newdata2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb52-391"><a href="#cb52-391" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="dv">0</span>, </span>
<span id="cb52-392"><a href="#cb52-392" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="dv">1500</span>  </span>
<span id="cb52-393"><a href="#cb52-393" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-394"><a href="#cb52-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-395"><a href="#cb52-395" aria-hidden="true" tabindex="-1"></a>predicted_price4 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model7, newdata2)</span>
<span id="cb52-396"><a href="#cb52-396" aria-hidden="true" tabindex="-1"></a>predicted_price4</span>
<span id="cb52-397"><a href="#cb52-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-398"><a href="#cb52-398" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-399"><a href="#cb52-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-400"><a href="#cb52-400" aria-hidden="true" tabindex="-1"></a>Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</span>
<span id="cb52-401"><a href="#cb52-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-404"><a href="#cb52-404" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-405"><a href="#cb52-405" aria-hidden="true" tabindex="-1"></a><span class="co">#Difference in price for model in question F</span></span>
<span id="cb52-406"><a href="#cb52-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-407"><a href="#cb52-407" aria-hidden="true" tabindex="-1"></a>diff_f <span class="ot">&lt;-</span> predicted_price <span class="sc">-</span> predicted_price2</span>
<span id="cb52-408"><a href="#cb52-408" aria-hidden="true" tabindex="-1"></a>diff_f</span>
<span id="cb52-409"><a href="#cb52-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-410"><a href="#cb52-410" aria-hidden="true" tabindex="-1"></a>diff_g <span class="ot">&lt;-</span> predicted_price3 <span class="sc">-</span> predicted_price4</span>
<span id="cb52-411"><a href="#cb52-411" aria-hidden="true" tabindex="-1"></a>diff_g</span>
<span id="cb52-412"><a href="#cb52-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-413"><a href="#cb52-413" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-414"><a href="#cb52-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-415"><a href="#cb52-415" aria-hidden="true" tabindex="-1"></a>Seems that the difference in price between new or not new homes is bigger when the size is higher. For instance, for a new house with 3000 sqf is $107k higher than no new. But for 1500 sqf the new house is only $14k more. </span>
<span id="cb52-416"><a href="#cb52-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-417"><a href="#cb52-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-418"><a href="#cb52-418" aria-hidden="true" tabindex="-1"></a>H. Do you think the model with interaction or the one without it represents the relationship of </span>
<span id="cb52-419"><a href="#cb52-419" aria-hidden="true" tabindex="-1"></a>size and new to the outcome price? What makes you prefer one model over another</span>
<span id="cb52-420"><a href="#cb52-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-421"><a href="#cb52-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-422"><a href="#cb52-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-423"><a href="#cb52-423" aria-hidden="true" tabindex="-1"></a>Both models seems good to predict price given p-value for F-statistics is significant in both models, however the the value of F itself is a lot higher in the model with no interaction size-new, which means that there is better fit in this model compared to the interaction model.</span>
<span id="cb52-424"><a href="#cb52-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-425"><a href="#cb52-425" aria-hidden="true" tabindex="-1"></a>The R2 and Adjusted R2 are similar in both models, so the interaction doesn't seems to add more explanation to the variations to the home price.</span>
<span id="cb52-426"><a href="#cb52-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-427"><a href="#cb52-427" aria-hidden="true" tabindex="-1"></a>On the other hand, the interaction model provides an additional insight which is that the difference in price between new and no new houses is moderated by the size. This moderation is relevant to understand the price variation and it is not captured in the no-interaction model.</span>
<span id="cb52-428"><a href="#cb52-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-429"><a href="#cb52-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-430"><a href="#cb52-430" aria-hidden="true" tabindex="-1"></a>For those reasons, I would rather use the model with the interaction.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>