<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Felix Betanourt">
<meta name="dcterms.date" content="2023-05-25">

<title>Final Project - Burnout in the workplace</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<meta name="twitter:title" content="Final Project - Burnout in the workplace">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-6-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction." id="toc-introduction." class="nav-link active" data-scroll-target="#introduction."><strong>Introduction</strong>.</a></li>
  <li><a href="#research-question." id="toc-research-question." class="nav-link" data-scroll-target="#research-question.">Research Question.</a></li>
  <li><a href="#hypotheses." id="toc-hypotheses." class="nav-link" data-scroll-target="#hypotheses.">Hypotheses.</a></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data analysis</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><strong>References</strong>:</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Project - Burnout in the workplace</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">final project</div>
    <div class="quarto-category">burnout</div>
    <div class="quarto-category">employee burnout</div>
    <div class="quarto-category">descriptives</div>
    <div class="quarto-category">regression</div>
    <div class="quarto-category">Research question</div>
    <div class="quarto-category">hyphoteses</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Felix Betanourt </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 25, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="introduction." class="level3">
<h3 class="anchored" data-anchor-id="introduction."><strong>Introduction</strong>.</h3>
<p>Burnout is a pervasive issue in many professions, and its consequences can be significant for individuals and organizations alike. According to Maslach and Leiter (2016), burnout is characterized by emotional exhaustion, depersonalization, and reduced personal accomplishment. It is prevalent in a variety of fields, including healthcare (West et al., 2016), among other professions. Burnout can have serious consequences, including decreased job satisfaction, increased absenteeism, and turnover (West et al., 2016).</p>
<p>There is a growing body of research exploring the causes and consequences of burnout, as well as potential solutions. Some scholars have identified factors such as job demands, lack of control, and social support as contributing to burnout (Bakker &amp; Demerouti, 2017).</p>
<p>Malesic (2022) emphasizes on working conditions as key factor in burnout in organizations. In particular when the employer doesn’t reward enough, or unfairness is a common practice, or there is a lack of community among coworkers, then the ability and willingness to keep doing the job disintegrate.</p>
<p>Lee &amp; Eissenstat (2017), for instance, affirm that psychological job demands and work-to-family conflict, as well as control over working hours/schedule, decision-making authority, and role clarity, have significant effects on burnout.</p>
</section>
<section id="research-question." class="level3">
<h3 class="anchored" data-anchor-id="research-question.">Research Question.</h3>
<p>This research paper aims to provide a comprehensive understanding of <strong>how the type of business and seniority level explain the level of burnout.</strong></p>
</section>
<section id="hypotheses." class="level3">
<h3 class="anchored" data-anchor-id="hypotheses.">Hypotheses.</h3>
<p>In this research we expect that:</p>
<p>H1. Working in Services (vs product type of business) predicts a significantly higher burnout rate, especially in Female workers.</p>
<p>H2. Fewer years of experience (lower seniority) is significantly related to a higher burnout rate.</p>
<p>H3. The numbers of work hours allocated affect the burnout rate significantly in employees working from home setup (vs on site).</p>
</section>
<section id="data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="data-analysis">Data analysis</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading packages</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(dplyr))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(tidyverse))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(data.table))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(psych))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(scales))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(lattice))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(formattable))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(kableExtra))</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(ggplot2))</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Reading the data.</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>burn <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"_data/burnout.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The dataset was obtained from:</p>
<p>https://www.kaggle.com/datasets/blurredmachine/are-your-employees-burning-out</p>
<p>Let’s see the strucutre of the dataset:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Structure</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(burn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   22750 obs. of  9 variables:
 $ Employee.ID         : chr  "fffe32003000360033003200" "fffe3700360033003500" "fffe31003300320037003900" "fffe32003400380032003900" ...
 $ Date.of.Joining     : chr  "2008-09-30" "2008-11-30" "2008-03-10" "2008-11-03" ...
 $ Gender              : chr  "Female" "Male" "Female" "Male" ...
 $ Company.Type        : chr  "Service" "Service" "Product" "Service" ...
 $ WFH.Setup.Available : chr  "No" "Yes" "Yes" "Yes" ...
 $ Designation         : num  2 1 2 1 3 2 3 2 3 3 ...
 $ Resource.Allocation : num  3 2 NA 1 7 4 6 4 6 6 ...
 $ Mental.Fatigue.Score: num  3.8 5 5.8 2.6 6.9 3.6 7.9 4.4 NA NA ...
 $ Burn.Rate           : num  0.16 0.36 0.49 0.2 0.52 0.29 0.62 0.33 0.56 0.67 ...</code></pre>
</div>
</div>
<p>The dataset contain 9 variables and 22750 observations.</p>
<p>Four of the variables are categorical and five are numeric (including one as date).</p>
<p>According to the source of the data, here is an definition of each variable:</p>
<p>Employee ID: The unique ID allocated for each employee.</p>
<p>Date of Joining: The date-time when the employee has joined the organization.</p>
<p>Gender: The gender of the employee</p>
<p>Company Type: The type of company where the employee is working</p>
<p>WFH Setup Available: Is the work from home facility available for the employee</p>
<p>Designation: The designation (designations refer to the expertise and qualifications a person must complete certain jobs) of the employee of work in the organization. In the range of [0.0, 5.0] bigger is higher designation.</p>
<p>Resource Allocation: The amount of resource allocated to the employee to work, ie. number of working hours.In the range of [1.0, 10.0] (higher means more resource)</p>
<p>Mental Fatigue Score: The level of fatigue mentally the employee is facing.In the range of [0.0, 10.0] where 0.0 means no fatigue and 10.0 means completely fatigue.</p>
<p>Burnout Rate: The value we need to predict for each employee telling the rate of Bur out while working.In the range of [0.0, 1.0] where the higher the value is more is the Burnout.</p>
<p>Let’s see a Summary for each variable.</p>
<p>But first let’s do some data wrangling:</p>
<ul>
<li>simplify the name of the variables</li>
<li>transform the Date of hire into tenure in years</li>
<li>eliminate ID form the df as it is not relevant for the analysis</li>
<li>create new variables for categorical variables as numeric to simplify analysis: Gender (0= Male, 1=Female), WFH (1=Yes, 0=No), Type of Business (0=Service, 1=Product)</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#simplify some variable names and transforming date</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>burn <span class="ot">&lt;-</span> <span class="fu">rename</span>(burn, <span class="at">fatigue =</span> Mental.Fatigue.Score, <span class="at">hours =</span> Resource.Allocation, <span class="at">WFH =</span> WFH.Setup.Available, <span class="at">doh =</span> Date.of.Joining, <span class="at">id =</span> Employee.ID, <span class="at">business =</span> Company.Type, <span class="at">designation =</span> Designation, <span class="at">burn.rate =</span> Burn.Rate, <span class="at">gender =</span> Gender)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#transforming date of hire to tenure</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>burn<span class="sc">$</span>doh <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(burn<span class="sc">$</span>doh)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>burn<span class="sc">$</span>tenure <span class="ot">&lt;-</span> <span class="fu">difftime</span>(<span class="st">"2023-4-20"</span>, burn<span class="sc">$</span>doh, <span class="at">units =</span> <span class="st">"weeks"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>burn<span class="sc">$</span>tenure <span class="ot">&lt;-</span> burn<span class="sc">$</span>tenure<span class="sc">/</span><span class="dv">52</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>burn<span class="sc">$</span>tenure <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(burn<span class="sc">$</span>tenure)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">#eliminate ID as it's not relevant for the analysis. They are just the identification for each individual</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>burn2 <span class="ot">&lt;-</span> burn <span class="sc">%&gt;%</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>id)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>burn2 <span class="ot">&lt;-</span> burn2<span class="sc">%&gt;%</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gender.f =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        gender <span class="sc">==</span> <span class="st">"Male"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>         gender <span class="sc">==</span> <span class="st">"Female"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        )) <span class="sc">%&gt;%</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">business.p =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>         business <span class="sc">==</span> <span class="st">"Service"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>         business <span class="sc">==</span> <span class="st">"Product"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>         )) <span class="sc">%&gt;%</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">WFH.y =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>         WFH <span class="sc">==</span> <span class="st">"Yes"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>         WFH <span class="sc">==</span> <span class="st">"No"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>         ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="descriptives-and-exploratory-visualization." class="level4">
<h4 class="anchored" data-anchor-id="descriptives-and-exploratory-visualization.">Descriptives and exploratory visualization.</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a df with only continuous variables</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>burn3 <span class="ot">&lt;-</span> burn2 <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>gender, <span class="sc">-</span>doh, <span class="sc">-</span>WFH, <span class="sc">-</span>business)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>describe_data <span class="ot">&lt;-</span> <span class="fu">describe</span>(<span class="at">x=</span>burn3) <span class="sc">%&gt;%</span> </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">c</span>(vars, n, mean, sd, median, min, max))</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(describe_data) <span class="sc">%&gt;%</span> </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="st">"striped"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">vars</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">designation</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">22750</td>
<td style="text-align: right;">2.1787253</td>
<td style="text-align: right;">1.1351447</td>
<td style="text-align: right;">2.00000</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">5.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">hours</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">21369</td>
<td style="text-align: right;">4.4813983</td>
<td style="text-align: right;">2.0472111</td>
<td style="text-align: right;">4.00000</td>
<td style="text-align: right;">1.00000</td>
<td style="text-align: right;">10.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fatigue</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">20633</td>
<td style="text-align: right;">5.7281879</td>
<td style="text-align: right;">1.9208387</td>
<td style="text-align: right;">5.90000</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">10.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">burn.rate</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">21626</td>
<td style="text-align: right;">0.4520055</td>
<td style="text-align: right;">0.1982264</td>
<td style="text-align: right;">0.45000</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tenure</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">22750</td>
<td style="text-align: right;">14.8510224</td>
<td style="text-align: right;">0.2894181</td>
<td style="text-align: right;">14.84936</td>
<td style="text-align: right;">14.34936</td>
<td style="text-align: right;">15.35211</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender.f</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">22750</td>
<td style="text-align: right;">0.5234286</td>
<td style="text-align: right;">0.4994618</td>
<td style="text-align: right;">1.00000</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">business.p</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">22750</td>
<td style="text-align: right;">0.3480000</td>
<td style="text-align: right;">0.4763465</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">WFH.y</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">22750</td>
<td style="text-align: right;">0.5402198</td>
<td style="text-align: right;">0.4983907</td>
<td style="text-align: right;">1.00000</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.00000</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Histograms for Burnout Rate, mental Fatigue, Work hours allocated, Designation Level and tenure.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(burn2<span class="sc">$</span>burn.rate, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"#a1e9f0"</span>, <span class="at">main =</span> <span class="st">"Histogram for Burnout Rate"</span>, <span class="at">xlab =</span> <span class="st">"Burn Rate"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(burn2<span class="sc">$</span>fatigue, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"#a1e9f0"</span>, <span class="at">main =</span> <span class="st">"Histogram for Mental Fatigue"</span>, <span class="at">xlab =</span> <span class="st">"Values"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(burn2<span class="sc">$</span>hours, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"#a1e9f0"</span>, <span class="at">main =</span> <span class="st">"Histogram of hours allocated"</span>, <span class="at">xlab =</span> <span class="st">"Work Hours allocated"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-6-3.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(burn2<span class="sc">$</span>designation, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"#a1e9f0"</span>, <span class="at">main =</span> <span class="st">"Histogram of Designation"</span>, <span class="at">xlab =</span> <span class="st">"Designation Level"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-6-4.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(burn2<span class="sc">$</span>tenure, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"#a1e9f0"</span>, <span class="at">main =</span> <span class="st">"Histogram of Tenure"</span>, <span class="at">xlab =</span> <span class="st">"Tenure"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-6-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can note that Burnout Rate shows a distribution close to a normal distribution while a bit skewed to the right. Hours allocated seems also skewed to the right.</p>
<p>In the case of Mental Fatigue, the distribution seems also a bit skewed to the left.</p>
<p>In the case of tenure seems a very homogeneous distribution. Seems that all employees in this data sample were hired within 12 months period.</p>
<p>Let’s visualize Gender, Type of Business and Work setting (WFH):</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(burn) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span>business, <span class="at">fill=</span>gender),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>WFH)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Seems that there are more females working from home than males regardless the type of business.</p>
</section>
<section id="explore-relationships" class="level4">
<h4 class="anchored" data-anchor-id="explore-relationships">Explore relationships</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>box2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(<span class="at">x=</span>business, <span class="at">y=</span>burn.rate, <span class="at">fill=</span>gender)) <span class="sc">+</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.7</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Box Plot - Burnout Rate by Gender, Type of business and Work From home (yes or no)"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Type Of Business"</span>, <span class="at">y =</span> <span class="st">"Burnout Rate"</span>)<span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>WFH, <span class="at">scale=</span><span class="st">"free"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>box2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>box3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(<span class="at">x=</span>business, <span class="at">y=</span>hours, <span class="at">fill=</span>gender)) <span class="sc">+</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.7</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Box Plot - Hours allocated, Type of business and Work From home (yes or no)"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Type Of Business"</span>, <span class="at">y =</span> <span class="st">"Hours Allocated"</span>)<span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>WFH, <span class="at">scale=</span><span class="st">"free"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>box3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It looks like the Burnout rate is higher in the employees working on site compared to employees working from home, and males shows higher rate compared to females in both type of businesses but it seems a higher difference among employees working from home.</p>
<p>On the other hand, the numbers of hours allocated seems higher for employees working on site and particularly males regardless the type of business.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>scatter1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(designation,burn.rate))<span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>WFH))<span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Burnout Rate vs Designation grouped by Gender and WFH setup"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Designation"</span>, <span class="at">y =</span> <span class="st">"Burnout Rate"</span>)<span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>scatter1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>scatter2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(hours,burn.rate))<span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>WFH))<span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Burnout Rate vs Hours allocated grouped by Gender and WFH setup"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Hours allocation"</span>, <span class="at">y =</span> <span class="st">"Burnout Rate"</span>)<span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>scatter2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>scatter3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(fatigue,burn.rate))<span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>WFH))<span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"gam"</span>)<span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Burnout Rate vs Mental Fatigue grouped by Gender and WFH setup"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Mental Fatigue"</span>, <span class="at">y =</span> <span class="st">"Burnout Rate"</span>)<span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>business)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>scatter3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ s(x, bs = "cs")'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>scatter4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(hours,fatigue))<span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>WFH))<span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Hours allocated vs Mental Fatigue grouped by Gender and WFH setup"</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Hours allocated"</span>, <span class="at">y =</span> <span class="st">"Mental fatigue"</span>)<span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>scatter4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>scatter5 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(designation, hours))<span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>WFH))<span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Hours allocated vs Designation grouped by Gender and WFH setup"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Designation"</span>, <span class="at">y =</span> <span class="st">"Hours allocated"</span>)<span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>scatter5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-9-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the charts we can see that there is a positive relationship between:</p>
<ul>
<li>Designation and burnout rate</li>
<li>Amount of hours allocated and burnout rate</li>
<li>Mental fatigue and burnout rate</li>
<li>Hours allocated and Mental fatigue</li>
</ul>
<p>All of those relationship exist regardless the gender and seems moderated by the work from home setup.</p>
<p>Seems that working from home has a key role in the relationship of the variables.</p>
<p>Lastly the relationship between Burnout rate and Fatigue doesn’t look completely lineal, but let’s check the so I will create a new variable by doing a quadratic transformation of Fatigue, and using it later for the regression.</p>
<p>Let’s analyze these initial findings with a few statistics.</p>
<ol type="1">
<li>First let’s see how is the relationship between Burnout Rate, type of business, WFH and gender:</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Three-way ANOVA</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>aov.model1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(burn.rate <span class="sc">~</span> business <span class="sc">*</span> gender <span class="sc">*</span> WFH, <span class="at">data =</span> burn2)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov.model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                       Df Sum Sq Mean Sq  F value   Pr(&gt;F)    
business                1    0.0    0.02    0.446 0.504133    
gender                  1   20.4   20.40  584.657  &lt; 2e-16 ***
WFH                     1   74.3   74.28 2128.566  &lt; 2e-16 ***
business:gender         1    0.0    0.02    0.546 0.459774    
business:WFH            1    0.1    0.09    2.465 0.116406    
gender:WFH              1    0.4    0.45   12.861 0.000336 ***
business:gender:WFH     1    0.1    0.06    1.736 0.187602    
Residuals           21618  754.4    0.03                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
1124 observations deleted due to missingness</code></pre>
</div>
</div>
<p>As we can see in this three-way ANOVA, type of business seems not relevant to explain burnout rate as the F value is not significant, but gender and WFH are both significant and also are when combined.</p>
<p>Let’s explore the relationship among continuous variables using a correlation matrix:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cor Matrix</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>cor_matrix2 <span class="ot">&lt;-</span> <span class="fu">cor</span>(burn2[, <span class="fu">c</span>(<span class="st">"burn.rate"</span>, <span class="st">"hours"</span>, <span class="st">"designation"</span>, <span class="st">"fatigue"</span>)], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cor_matrix2, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            burn.rate hours designation fatigue
burn.rate        1.00  0.86        0.74    0.94
hours            0.86  1.00        0.88    0.80
designation      0.74  0.88        1.00    0.69
fatigue          0.94  0.80        0.69    1.00</code></pre>
</div>
</div>
<p>The first thing we have to notice is that Hours allocated shows strong correlation with almost all the rest fo the variables, this could represent multicollinearity. So I may need to exclude some variables the Regression analysis.</p>
<p>In this case seems that designation has a very strong positive correlation with hours allocated, seems that the company assign to more senior employees more work hours.</p>
<p>But to explain burnout seems more logic to think that number of work hours explain burnout, so I rather use hours and not designation in the model and avoid multicollinearity.</p>
<p>Also I’ll use backward Stepwise regression to keep only the relevant variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a multiple regression model with predictor variables</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>lm.model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(burn.rate <span class="sc">~</span> fatigue <span class="sc">+</span> gender.f <span class="sc">+</span> business.p <span class="sc">+</span> hours <span class="sc">+</span> WFH.y, <span class="at">data =</span> burn2)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = burn.rate ~ fatigue + gender.f + business.p + hours + 
    WFH.y, data = burn2)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.157101 -0.041106 -0.000602  0.040688  0.201499 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.0801515  0.0016618 -48.232  &lt; 2e-16 ***
fatigue      0.0739451  0.0003566 207.364  &lt; 2e-16 ***
gender.f    -0.0045718  0.0008294  -5.512 3.59e-08 ***
business.p  -0.0004356  0.0008608  -0.506    0.613    
hours        0.0262183  0.0003355  78.151  &lt; 2e-16 ***
WFH.y       -0.0117741  0.0008602 -13.688  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.05579 on 18584 degrees of freedom
  (4160 observations deleted due to missingness)
Multiple R-squared:  0.9205,    Adjusted R-squared:  0.9205 
F-statistic: 4.303e+04 on 5 and 18584 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step Model - Forward</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>step_model1 <span class="ot">&lt;-</span> <span class="fu">step</span>(lm.model1, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">criterion=</span> <span class="st">"AIC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-107298.9
burn.rate ~ fatigue + gender.f + business.p + hours + WFH.y

             Df Sum of Sq     RSS     AIC
- business.p  1     0.001  57.852 -107301
&lt;none&gt;                     57.851 -107299
- gender.f    1     0.095  57.946 -107270
- WFH.y       1     0.583  58.434 -107114
- hours       1    19.012  76.864 -102018
- fatigue     1   133.857 191.708  -85028

Step:  AIC=-107300.6
burn.rate ~ fatigue + gender.f + hours + WFH.y

           Df Sum of Sq     RSS     AIC
&lt;none&gt;                   57.852 -107301
- gender.f  1     0.094  57.946 -107272
- WFH.y     1     0.583  58.435 -107116
- hours     1    19.014  76.866 -102020
- fatigue   1   133.857 191.709  -85030</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = burn.rate ~ fatigue + gender.f + hours + WFH.y, 
    data = burn2)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.156953 -0.041084 -0.000499  0.040699  0.201211 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.0803079  0.0016327 -49.186  &lt; 2e-16 ***
fatigue      0.0739452  0.0003566 207.369  &lt; 2e-16 ***
gender.f    -0.0045675  0.0008293  -5.508 3.69e-08 ***
hours        0.0262190  0.0003355  78.155  &lt; 2e-16 ***
WFH.y       -0.0117739  0.0008602 -13.688  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.05579 on 18585 degrees of freedom
  (4160 observations deleted due to missingness)
Multiple R-squared:  0.9205,    Adjusted R-squared:  0.9205 
F-statistic: 5.379e+04 on 4 and 18585 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Type of business is not relevant to the model to explain Burnout. so it is excluded from the model.</p>
<p>And Fatigue, Gender, Working hours and WFH setting, all with a p-value &lt; 0.001 explain 92% of the burnout rate.</p>
<p>In particular, any increase in units of Fatigue increases burnout rate by 0.07 points (or 7% as the burnout scale goes from 0 to 1). As well as Working hours, any additional hour allocated increases burnout rate by 0.02 points (or 2% increase).</p>
<p>On the other side, being Male is significantly associated with higher burnout rates (0.004 points) and working on-site is also associated to higher burnout rates (increases the burnout rate by 1%, or 0.01 points).</p>
<p>Let’s check assumptions.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(step_model1, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Doesn’t seems there are assumptions violations in this model.</p>
<p>However based on the scatter plot above about Burnout Rate and Fatigue, the relationship doesn’t seem very linear, therefore if we apply a polynomial regression by doing a quadratic transformation of fatigue the model would adjust a bit better.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>lm.model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(burn.rate <span class="sc">~</span> business.p <span class="sc">+</span> hours <span class="sc">+</span> gender.f <span class="sc">+</span> <span class="fu">I</span>(fatigue<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> fatigue <span class="sc">+</span>  WFH.y, <span class="at">data =</span> burn2)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Step Model - Forward</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>step_model2 <span class="ot">&lt;-</span> <span class="fu">step</span>(lm.model2, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">criterion=</span> <span class="st">"AIC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-108108.5
burn.rate ~ business.p + hours + gender.f + I(fatigue^2) + fatigue + 
    WFH.y

               Df Sum of Sq    RSS     AIC
- business.p    1    0.0008 55.380 -108110
&lt;none&gt;                      55.380 -108109
- gender.f      1    0.0610 55.441 -108090
- WFH.y         1    0.3857 55.765 -107981
- I(fatigue^2)  1    2.4715 57.851 -107299
- fatigue       1   10.8741 66.254 -104778
- hours         1   15.8119 71.192 -103441

Step:  AIC=-108110.3
burn.rate ~ hours + gender.f + I(fatigue^2) + fatigue + WFH.y

               Df Sum of Sq    RSS     AIC
&lt;none&gt;                      55.380 -108110
- gender.f      1    0.0609 55.441 -108092
- WFH.y         1    0.3857 55.766 -107983
- I(fatigue^2)  1    2.4715 57.852 -107301
- fatigue       1   10.8741 66.255 -104780
- hours         1   15.8129 71.193 -103443</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = burn.rate ~ hours + gender.f + I(fatigue^2) + fatigue + 
    WFH.y, data = burn2)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.150292 -0.041127 -0.000951  0.039024  0.190195 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -2.834e-02  2.410e-03 -11.757  &lt; 2e-16 ***
hours         2.437e-02  3.345e-04  72.844  &lt; 2e-16 ***
gender.f     -3.671e-03  8.120e-04  -4.521 6.18e-06 ***
I(fatigue^2)  2.277e-03  7.906e-05  28.799  &lt; 2e-16 ***
fatigue       5.153e-02  8.530e-04  60.407  &lt; 2e-16 ***
WFH.y        -9.613e-03  8.450e-04 -11.377  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.05459 on 18584 degrees of freedom
  (4160 observations deleted due to missingness)
Multiple R-squared:  0.9239,    Adjusted R-squared:  0.9239 
F-statistic: 4.512e+04 on 5 and 18584 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(step_model2, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FelixBetancourt_Final_May20_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The model keeps the significant relationships we explained before and seems to fit better now. The new quadratic Fatigue is significant in the model, so I’ll include it.</p>
<p>Hours allocated, Gender, Fatigue and WFH or not seems to explain significantly the burnout in the employees included in the study. Being Hours allocated and fatigue the most relevant variables in the model to explain burnout (higher t value).</p>
<p>Specifically, under this model burnout rate increases by 0.05 points (or 5%) per each unit increase in Fatigue and 0.02 (or 2%) per each hour allocated.</p>
<p>But let’s compare models.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#PRESS</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>pr <span class="ot">&lt;-</span> <span class="fu">resid</span>(lm.model1)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">lm.influence</span>(lm.model1)<span class="sc">$</span>hat)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>pr2 <span class="ot">&lt;-</span> pr<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>pr3 <span class="ot">&lt;-</span> <span class="fu">resid</span>(lm.model2)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">lm.influence</span>(lm.model1)<span class="sc">$</span>hat)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>pr4 <span class="ot">&lt;-</span> pr3<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="co">#df for table</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>metrics_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"Model 1"</span>, <span class="st">"Model 2 - Quadratic"</span>),</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">c</span>(<span class="fu">AIC</span>(lm.model1), <span class="fu">AIC</span>(lm.model2)),</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">BIC =</span> <span class="fu">c</span>(<span class="fu">BIC</span>(lm.model1), <span class="fu">BIC</span>(lm.model2)),</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">PRESS =</span> <span class="fu">c</span>(<span class="fu">sum</span>(pr2), <span class="fu">sum</span>(pr4))</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(metrics_df, <span class="at">caption =</span> <span class="st">"Models Comparison"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="st">"striped"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>Models Comparison</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">PRESS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Model 1</td>
<td style="text-align: right;">-54540.72</td>
<td style="text-align: right;">-54485.91</td>
<td style="text-align: right;">57.88767</td>
</tr>
<tr class="even">
<td style="text-align: left;">Model 2 - Quadratic</td>
<td style="text-align: right;">-55350.38</td>
<td style="text-align: right;">-55287.74</td>
<td style="text-align: right;">55.41337</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Considering that:</p>
<ol type="1">
<li>R2 for model 1 is 0.9205 and for model 2 (with quadratic fatigue) is 0.9235</li>
<li>AIC, BIC and PRESS are very close among the two models</li>
<li>and, that in the model 2 any slightly violations of assumptions founded in model 1.</li>
</ol>
<p>We can say that both models works very well to explain burnout rate. But I feel more comfortable with Model 2 where the Mental Fatigue has a quadratic transformation as the R2 is higher for this model.</p>
</section>
</section>
<section id="conclusions" class="level3">
<h3 class="anchored" data-anchor-id="conclusions">Conclusions</h3>
<p>There is a positive relationship between burnout and designation level.</p>
<p>This means that Alternative Hypothesis 2 can’t be accepted as it states a negative relationship between those two variables.</p>
<p>On the other hand, Alternative Hypothesis 1 stated that being in Services and being female is related to a higher burnout rate, and the results indicate that the type of business is not relevant to predict burnout, and being female is neither associated with higher burnout.</p>
<p>However, gender explains in part the burnout. In particular, being female is associated with a lower burnout rate compared to male employees.</p>
<p>Lastly, concerning Alternative Hypothesis 3, the number of hours allocated is positively related to burnout; in particular, working on-site is associated with more working hours for males and females compared to employees working from home. However, within the group of employees working on-site, males seem to have significantly more hours allocated than females.</p>
<p>Ultimately, the number of working hours and mental fatigue are the most relevant variables to explain burnout. Gender and WFH setup seems relevant regarding how the hours are allocated. Being male working on site absorbs more work hours, therefore more burnout.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references"><strong>References</strong>:</h3>
<p>Bakker, A. B., &amp; Demerouti, E. (2017). Job demands-resources theory: Taking stock and looking forward. Journal of Occupational Health Psychology, 22(3), 273–285.</p>
<p>Lee, Y., Eissenstat, S. (2017). A longitudinal examination of the causes and effects of burnout based on the job demands-resources model. International Journal for Educational and Vocational Guidance, 18(3), 337–354.</p>
<p>Malesic, J. (2022). The end of Burnout. University of California Press.</p>
<p>Maslach, C., &amp; Leiter, M. P. (2016). Understanding the burnout experience: Recent research and its implications for psychiatry. World Psychiatry, 15(2), 103–111.</p>
<p>West, C. P., Dyrbye, L. N., Erwin, P., Shanafelt, T. D., (2016). Interventions to promote physician well-being and mitigate burnout: A systematic review and meta-analysis. The Lancet, 388(10057), 2272–228</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb42" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Project - Burnout in the workplace"</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Felix Betanourt"</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "DACSS 603 Final Project"</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/25/2023"</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - final project</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - burnout</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - employee burnout</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - descriptives</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a><span class="co">  - regression</span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a><span class="co">  - Research question</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a><span class="co">  - hyphoteses</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a><span class="fu">### **Introduction**.</span></span>
<span id="cb42-32"><a href="#cb42-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-33"><a href="#cb42-33" aria-hidden="true" tabindex="-1"></a>Burnout is a pervasive issue in many professions, and its consequences can be significant for individuals and organizations alike. According to Maslach and Leiter (2016), burnout is characterized by emotional exhaustion, depersonalization, and reduced personal accomplishment. It is prevalent in a variety of fields, including healthcare (West et al., 2016), among other professions. Burnout can have serious consequences, including decreased job satisfaction, increased absenteeism, and turnover (West et al., 2016).</span>
<span id="cb42-34"><a href="#cb42-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-35"><a href="#cb42-35" aria-hidden="true" tabindex="-1"></a>There is a growing body of research exploring the causes and consequences of burnout, as well as potential solutions. Some scholars have identified factors such as job demands, lack of control, and social support as contributing to burnout (Bakker &amp; Demerouti, 2017).</span>
<span id="cb42-36"><a href="#cb42-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-37"><a href="#cb42-37" aria-hidden="true" tabindex="-1"></a>Malesic (2022) emphasizes on working conditions as key factor in burnout in organizations. In particular when the employer doesn't reward enough, or unfairness is a common practice, or there is a lack of community among coworkers, then the ability and willingness to keep doing the job disintegrate.</span>
<span id="cb42-38"><a href="#cb42-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-39"><a href="#cb42-39" aria-hidden="true" tabindex="-1"></a>Lee &amp; Eissenstat (2017), for instance, affirm that psychological job demands and work-to-family conflict, as well as control over working hours/schedule, decision-making authority, and role clarity, have significant effects on burnout.</span>
<span id="cb42-40"><a href="#cb42-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-41"><a href="#cb42-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-42"><a href="#cb42-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-43"><a href="#cb42-43" aria-hidden="true" tabindex="-1"></a><span class="fu">### Research Question.</span></span>
<span id="cb42-44"><a href="#cb42-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-45"><a href="#cb42-45" aria-hidden="true" tabindex="-1"></a>This research paper aims to provide a comprehensive understanding of **how the type of business and seniority level explain the level of burnout.**</span>
<span id="cb42-46"><a href="#cb42-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-47"><a href="#cb42-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-48"><a href="#cb42-48" aria-hidden="true" tabindex="-1"></a><span class="fu">### Hypotheses.</span></span>
<span id="cb42-49"><a href="#cb42-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-50"><a href="#cb42-50" aria-hidden="true" tabindex="-1"></a>In this research we expect that:</span>
<span id="cb42-51"><a href="#cb42-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-52"><a href="#cb42-52" aria-hidden="true" tabindex="-1"></a>H1.  Working in Services (vs product type of business) predicts a significantly higher burnout rate, especially in Female workers.</span>
<span id="cb42-53"><a href="#cb42-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-54"><a href="#cb42-54" aria-hidden="true" tabindex="-1"></a>H2.  Fewer years of experience (lower seniority) is significantly related to a higher burnout rate.</span>
<span id="cb42-55"><a href="#cb42-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-56"><a href="#cb42-56" aria-hidden="true" tabindex="-1"></a>H3.  The numbers of work hours allocated affect the burnout rate significantly in employees working from home setup (vs on site).</span>
<span id="cb42-57"><a href="#cb42-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-58"><a href="#cb42-58" aria-hidden="true" tabindex="-1"></a><span class="fu">### Data analysis</span></span>
<span id="cb42-59"><a href="#cb42-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-62"><a href="#cb42-62" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-63"><a href="#cb42-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading packages</span></span>
<span id="cb42-64"><a href="#cb42-64" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(dplyr))</span>
<span id="cb42-65"><a href="#cb42-65" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(tidyverse))</span>
<span id="cb42-66"><a href="#cb42-66" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(data.table))</span>
<span id="cb42-67"><a href="#cb42-67" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(psych))</span>
<span id="cb42-68"><a href="#cb42-68" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(scales))</span>
<span id="cb42-69"><a href="#cb42-69" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(lattice))</span>
<span id="cb42-70"><a href="#cb42-70" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(formattable))</span>
<span id="cb42-71"><a href="#cb42-71" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(kableExtra))</span>
<span id="cb42-72"><a href="#cb42-72" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(ggplot2))</span>
<span id="cb42-73"><a href="#cb42-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-74"><a href="#cb42-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Reading the data.</span></span>
<span id="cb42-75"><a href="#cb42-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-76"><a href="#cb42-76" aria-hidden="true" tabindex="-1"></a>burn <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"_data/burnout.csv"</span>)</span>
<span id="cb42-77"><a href="#cb42-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-78"><a href="#cb42-78" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-79"><a href="#cb42-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-80"><a href="#cb42-80" aria-hidden="true" tabindex="-1"></a>The dataset was obtained from:</span>
<span id="cb42-81"><a href="#cb42-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-82"><a href="#cb42-82" aria-hidden="true" tabindex="-1"></a>https://www.kaggle.com/datasets/blurredmachine/are-your-employees-burning-out</span>
<span id="cb42-83"><a href="#cb42-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-84"><a href="#cb42-84" aria-hidden="true" tabindex="-1"></a>Let's see the strucutre of the dataset:</span>
<span id="cb42-85"><a href="#cb42-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-88"><a href="#cb42-88" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-89"><a href="#cb42-89" aria-hidden="true" tabindex="-1"></a><span class="co">#Structure</span></span>
<span id="cb42-90"><a href="#cb42-90" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(burn)</span>
<span id="cb42-91"><a href="#cb42-91" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-92"><a href="#cb42-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-93"><a href="#cb42-93" aria-hidden="true" tabindex="-1"></a>The dataset contain 9 variables and 22750 observations.</span>
<span id="cb42-94"><a href="#cb42-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-95"><a href="#cb42-95" aria-hidden="true" tabindex="-1"></a>Four of the variables are categorical and five are numeric (including one as date).</span>
<span id="cb42-96"><a href="#cb42-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-97"><a href="#cb42-97" aria-hidden="true" tabindex="-1"></a>According to the source of the data, here is an definition of each variable:</span>
<span id="cb42-98"><a href="#cb42-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-99"><a href="#cb42-99" aria-hidden="true" tabindex="-1"></a>Employee ID: The unique ID allocated for each employee.</span>
<span id="cb42-100"><a href="#cb42-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-101"><a href="#cb42-101" aria-hidden="true" tabindex="-1"></a>Date of Joining: The date-time when the employee has joined the organization.</span>
<span id="cb42-102"><a href="#cb42-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-103"><a href="#cb42-103" aria-hidden="true" tabindex="-1"></a>Gender: The gender of the employee</span>
<span id="cb42-104"><a href="#cb42-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-105"><a href="#cb42-105" aria-hidden="true" tabindex="-1"></a>Company Type: The type of company where the employee is working</span>
<span id="cb42-106"><a href="#cb42-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-107"><a href="#cb42-107" aria-hidden="true" tabindex="-1"></a>WFH Setup Available: Is the work from home facility available for the employee</span>
<span id="cb42-108"><a href="#cb42-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-109"><a href="#cb42-109" aria-hidden="true" tabindex="-1"></a>Designation: The designation (designations refer to the expertise and qualifications a person must complete certain jobs) of the employee of work in the organization. In the range of <span class="sc">\[</span>0.0, 5.0<span class="sc">\]</span> bigger is higher designation.</span>
<span id="cb42-110"><a href="#cb42-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-111"><a href="#cb42-111" aria-hidden="true" tabindex="-1"></a>Resource Allocation: The amount of resource allocated to the employee to work, ie. number of working hours.In the range of <span class="sc">\[</span>1.0, 10.0<span class="sc">\]</span> (higher means more resource)</span>
<span id="cb42-112"><a href="#cb42-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-113"><a href="#cb42-113" aria-hidden="true" tabindex="-1"></a>Mental Fatigue Score: The level of fatigue mentally the employee is facing.In the range of <span class="sc">\[</span>0.0, 10.0<span class="sc">\]</span> where 0.0 means no fatigue and 10.0 means completely fatigue.</span>
<span id="cb42-114"><a href="#cb42-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-115"><a href="#cb42-115" aria-hidden="true" tabindex="-1"></a>Burnout Rate: The value we need to predict for each employee telling the rate of Bur out while working.In the range of <span class="sc">\[</span>0.0, 1.0<span class="sc">\]</span> where the higher the value is more is the Burnout.</span>
<span id="cb42-116"><a href="#cb42-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-117"><a href="#cb42-117" aria-hidden="true" tabindex="-1"></a>Let's see a Summary for each variable.</span>
<span id="cb42-118"><a href="#cb42-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-119"><a href="#cb42-119" aria-hidden="true" tabindex="-1"></a>But first let's do some data wrangling:</span>
<span id="cb42-120"><a href="#cb42-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-121"><a href="#cb42-121" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>simplify the name of the variables</span>
<span id="cb42-122"><a href="#cb42-122" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>transform the Date of hire into tenure in years</span>
<span id="cb42-123"><a href="#cb42-123" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>eliminate ID form the df as it is not relevant for the analysis</span>
<span id="cb42-124"><a href="#cb42-124" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>create new variables for categorical variables as numeric to simplify analysis: Gender (0= Male, 1=Female), WFH (1=Yes, 0=No), Type of Business (0=Service, 1=Product)</span>
<span id="cb42-125"><a href="#cb42-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-128"><a href="#cb42-128" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-129"><a href="#cb42-129" aria-hidden="true" tabindex="-1"></a><span class="co">#simplify some variable names and transforming date</span></span>
<span id="cb42-130"><a href="#cb42-130" aria-hidden="true" tabindex="-1"></a>burn <span class="ot">&lt;-</span> <span class="fu">rename</span>(burn, <span class="at">fatigue =</span> Mental.Fatigue.Score, <span class="at">hours =</span> Resource.Allocation, <span class="at">WFH =</span> WFH.Setup.Available, <span class="at">doh =</span> Date.of.Joining, <span class="at">id =</span> Employee.ID, <span class="at">business =</span> Company.Type, <span class="at">designation =</span> Designation, <span class="at">burn.rate =</span> Burn.Rate, <span class="at">gender =</span> Gender)</span>
<span id="cb42-131"><a href="#cb42-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-132"><a href="#cb42-132" aria-hidden="true" tabindex="-1"></a><span class="co">#transforming date of hire to tenure</span></span>
<span id="cb42-133"><a href="#cb42-133" aria-hidden="true" tabindex="-1"></a>burn<span class="sc">$</span>doh <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(burn<span class="sc">$</span>doh)</span>
<span id="cb42-134"><a href="#cb42-134" aria-hidden="true" tabindex="-1"></a>burn<span class="sc">$</span>tenure <span class="ot">&lt;-</span> <span class="fu">difftime</span>(<span class="st">"2023-4-20"</span>, burn<span class="sc">$</span>doh, <span class="at">units =</span> <span class="st">"weeks"</span>)</span>
<span id="cb42-135"><a href="#cb42-135" aria-hidden="true" tabindex="-1"></a>burn<span class="sc">$</span>tenure <span class="ot">&lt;-</span> burn<span class="sc">$</span>tenure<span class="sc">/</span><span class="dv">52</span></span>
<span id="cb42-136"><a href="#cb42-136" aria-hidden="true" tabindex="-1"></a>burn<span class="sc">$</span>tenure <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(burn<span class="sc">$</span>tenure)</span>
<span id="cb42-137"><a href="#cb42-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-138"><a href="#cb42-138" aria-hidden="true" tabindex="-1"></a><span class="co">#eliminate ID as it's not relevant for the analysis. They are just the identification for each individual</span></span>
<span id="cb42-139"><a href="#cb42-139" aria-hidden="true" tabindex="-1"></a>burn2 <span class="ot">&lt;-</span> burn <span class="sc">%&gt;%</span></span>
<span id="cb42-140"><a href="#cb42-140" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>id)</span>
<span id="cb42-141"><a href="#cb42-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-142"><a href="#cb42-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-143"><a href="#cb42-143" aria-hidden="true" tabindex="-1"></a>burn2 <span class="ot">&lt;-</span> burn2<span class="sc">%&gt;%</span></span>
<span id="cb42-144"><a href="#cb42-144" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gender.f =</span> <span class="fu">case_when</span>(</span>
<span id="cb42-145"><a href="#cb42-145" aria-hidden="true" tabindex="-1"></a>        gender <span class="sc">==</span> <span class="st">"Male"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb42-146"><a href="#cb42-146" aria-hidden="true" tabindex="-1"></a>         gender <span class="sc">==</span> <span class="st">"Female"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb42-147"><a href="#cb42-147" aria-hidden="true" tabindex="-1"></a>        )) <span class="sc">%&gt;%</span></span>
<span id="cb42-148"><a href="#cb42-148" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">business.p =</span> <span class="fu">case_when</span>(</span>
<span id="cb42-149"><a href="#cb42-149" aria-hidden="true" tabindex="-1"></a>         business <span class="sc">==</span> <span class="st">"Service"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb42-150"><a href="#cb42-150" aria-hidden="true" tabindex="-1"></a>         business <span class="sc">==</span> <span class="st">"Product"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb42-151"><a href="#cb42-151" aria-hidden="true" tabindex="-1"></a>         )) <span class="sc">%&gt;%</span></span>
<span id="cb42-152"><a href="#cb42-152" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">WFH.y =</span> <span class="fu">case_when</span>(</span>
<span id="cb42-153"><a href="#cb42-153" aria-hidden="true" tabindex="-1"></a>         WFH <span class="sc">==</span> <span class="st">"Yes"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb42-154"><a href="#cb42-154" aria-hidden="true" tabindex="-1"></a>         WFH <span class="sc">==</span> <span class="st">"No"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb42-155"><a href="#cb42-155" aria-hidden="true" tabindex="-1"></a>         ))</span>
<span id="cb42-156"><a href="#cb42-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-157"><a href="#cb42-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-158"><a href="#cb42-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-159"><a href="#cb42-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-160"><a href="#cb42-160" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Descriptives and exploratory visualization.</span></span>
<span id="cb42-161"><a href="#cb42-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-162"><a href="#cb42-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-165"><a href="#cb42-165" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-166"><a href="#cb42-166" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a df with only continuous variables</span></span>
<span id="cb42-167"><a href="#cb42-167" aria-hidden="true" tabindex="-1"></a>burn3 <span class="ot">&lt;-</span> burn2 <span class="sc">%&gt;%</span></span>
<span id="cb42-168"><a href="#cb42-168" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>gender, <span class="sc">-</span>doh, <span class="sc">-</span>WFH, <span class="sc">-</span>business)</span>
<span id="cb42-169"><a href="#cb42-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-170"><a href="#cb42-170" aria-hidden="true" tabindex="-1"></a>describe_data <span class="ot">&lt;-</span> <span class="fu">describe</span>(<span class="at">x=</span>burn3) <span class="sc">%&gt;%</span> </span>
<span id="cb42-171"><a href="#cb42-171" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">c</span>(vars, n, mean, sd, median, min, max))</span>
<span id="cb42-172"><a href="#cb42-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-173"><a href="#cb42-173" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(describe_data) <span class="sc">%&gt;%</span> </span>
<span id="cb42-174"><a href="#cb42-174" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="st">"striped"</span>)</span>
<span id="cb42-175"><a href="#cb42-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-176"><a href="#cb42-176" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-177"><a href="#cb42-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-178"><a href="#cb42-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-179"><a href="#cb42-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-180"><a href="#cb42-180" aria-hidden="true" tabindex="-1"></a>Histograms for Burnout Rate, mental Fatigue, Work hours allocated, Designation Level and tenure.</span>
<span id="cb42-181"><a href="#cb42-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-182"><a href="#cb42-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-185"><a href="#cb42-185" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-186"><a href="#cb42-186" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(burn2<span class="sc">$</span>burn.rate, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"#a1e9f0"</span>, <span class="at">main =</span> <span class="st">"Histogram for Burnout Rate"</span>, <span class="at">xlab =</span> <span class="st">"Burn Rate"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb42-187"><a href="#cb42-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-188"><a href="#cb42-188" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(burn2<span class="sc">$</span>fatigue, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"#a1e9f0"</span>, <span class="at">main =</span> <span class="st">"Histogram for Mental Fatigue"</span>, <span class="at">xlab =</span> <span class="st">"Values"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb42-189"><a href="#cb42-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-190"><a href="#cb42-190" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(burn2<span class="sc">$</span>hours, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"#a1e9f0"</span>, <span class="at">main =</span> <span class="st">"Histogram of hours allocated"</span>, <span class="at">xlab =</span> <span class="st">"Work Hours allocated"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb42-191"><a href="#cb42-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-192"><a href="#cb42-192" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(burn2<span class="sc">$</span>designation, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"#a1e9f0"</span>, <span class="at">main =</span> <span class="st">"Histogram of Designation"</span>, <span class="at">xlab =</span> <span class="st">"Designation Level"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb42-193"><a href="#cb42-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-194"><a href="#cb42-194" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(burn2<span class="sc">$</span>tenure, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"#a1e9f0"</span>, <span class="at">main =</span> <span class="st">"Histogram of Tenure"</span>, <span class="at">xlab =</span> <span class="st">"Tenure"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb42-195"><a href="#cb42-195" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-196"><a href="#cb42-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-197"><a href="#cb42-197" aria-hidden="true" tabindex="-1"></a>We can note that Burnout Rate shows a distribution close to a normal distribution while a bit skewed to the right. Hours allocated seems also skewed to the right.</span>
<span id="cb42-198"><a href="#cb42-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-199"><a href="#cb42-199" aria-hidden="true" tabindex="-1"></a>In the case of Mental Fatigue, the distribution seems also a bit skewed to the left.</span>
<span id="cb42-200"><a href="#cb42-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-201"><a href="#cb42-201" aria-hidden="true" tabindex="-1"></a>In the case of tenure seems a very homogeneous distribution. Seems that all employees in this data sample were hired within 12 months period.</span>
<span id="cb42-202"><a href="#cb42-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-203"><a href="#cb42-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-204"><a href="#cb42-204" aria-hidden="true" tabindex="-1"></a>Let's visualize Gender, Type of Business and Work setting (WFH):</span>
<span id="cb42-205"><a href="#cb42-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-208"><a href="#cb42-208" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-209"><a href="#cb42-209" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(burn) <span class="sc">+</span></span>
<span id="cb42-210"><a href="#cb42-210" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span>business, <span class="at">fill=</span>gender),</span>
<span id="cb42-211"><a href="#cb42-211" aria-hidden="true" tabindex="-1"></a>           <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb42-212"><a href="#cb42-212" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>WFH)</span>
<span id="cb42-213"><a href="#cb42-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-214"><a href="#cb42-214" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-215"><a href="#cb42-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-216"><a href="#cb42-216" aria-hidden="true" tabindex="-1"></a>Seems that there are more females working from home than males regardless the type of business.</span>
<span id="cb42-217"><a href="#cb42-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-218"><a href="#cb42-218" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Explore relationships</span></span>
<span id="cb42-219"><a href="#cb42-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-222"><a href="#cb42-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-223"><a href="#cb42-223" aria-hidden="true" tabindex="-1"></a>box2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(<span class="at">x=</span>business, <span class="at">y=</span>burn.rate, <span class="at">fill=</span>gender)) <span class="sc">+</span> </span>
<span id="cb42-224"><a href="#cb42-224" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.7</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb42-225"><a href="#cb42-225" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Box Plot - Burnout Rate by Gender, Type of business and Work From home (yes or no)"</span>,</span>
<span id="cb42-226"><a href="#cb42-226" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Type Of Business"</span>, <span class="at">y =</span> <span class="st">"Burnout Rate"</span>)<span class="sc">+</span></span>
<span id="cb42-227"><a href="#cb42-227" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>WFH, <span class="at">scale=</span><span class="st">"free"</span>)</span>
<span id="cb42-228"><a href="#cb42-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-229"><a href="#cb42-229" aria-hidden="true" tabindex="-1"></a>box2</span>
<span id="cb42-230"><a href="#cb42-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-231"><a href="#cb42-231" aria-hidden="true" tabindex="-1"></a>box3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(<span class="at">x=</span>business, <span class="at">y=</span>hours, <span class="at">fill=</span>gender)) <span class="sc">+</span> </span>
<span id="cb42-232"><a href="#cb42-232" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.7</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb42-233"><a href="#cb42-233" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Box Plot - Hours allocated, Type of business and Work From home (yes or no)"</span>,</span>
<span id="cb42-234"><a href="#cb42-234" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Type Of Business"</span>, <span class="at">y =</span> <span class="st">"Hours Allocated"</span>)<span class="sc">+</span></span>
<span id="cb42-235"><a href="#cb42-235" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>WFH, <span class="at">scale=</span><span class="st">"free"</span>)</span>
<span id="cb42-236"><a href="#cb42-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-237"><a href="#cb42-237" aria-hidden="true" tabindex="-1"></a>box3</span>
<span id="cb42-238"><a href="#cb42-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-239"><a href="#cb42-239" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-240"><a href="#cb42-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-241"><a href="#cb42-241" aria-hidden="true" tabindex="-1"></a>It looks like the Burnout rate is higher in the employees working on site compared to employees working from home, and males shows higher rate compared to females in both type of businesses but it seems a higher difference among employees working from home.</span>
<span id="cb42-242"><a href="#cb42-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-243"><a href="#cb42-243" aria-hidden="true" tabindex="-1"></a>On the other hand, the numbers of hours allocated seems higher for employees working on site and particularly males regardless the type of business.</span>
<span id="cb42-244"><a href="#cb42-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-247"><a href="#cb42-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-248"><a href="#cb42-248" aria-hidden="true" tabindex="-1"></a>scatter1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(designation,burn.rate))<span class="sc">+</span></span>
<span id="cb42-249"><a href="#cb42-249" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>WFH))<span class="sc">+</span></span>
<span id="cb42-250"><a href="#cb42-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb42-251"><a href="#cb42-251" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Burnout Rate vs Designation grouped by Gender and WFH setup"</span>,</span>
<span id="cb42-252"><a href="#cb42-252" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Designation"</span>, <span class="at">y =</span> <span class="st">"Burnout Rate"</span>)<span class="sc">+</span></span>
<span id="cb42-253"><a href="#cb42-253" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span>
<span id="cb42-254"><a href="#cb42-254" aria-hidden="true" tabindex="-1"></a>scatter1</span>
<span id="cb42-255"><a href="#cb42-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-256"><a href="#cb42-256" aria-hidden="true" tabindex="-1"></a>scatter2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(hours,burn.rate))<span class="sc">+</span></span>
<span id="cb42-257"><a href="#cb42-257" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>WFH))<span class="sc">+</span></span>
<span id="cb42-258"><a href="#cb42-258" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb42-259"><a href="#cb42-259" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Burnout Rate vs Hours allocated grouped by Gender and WFH setup"</span>,</span>
<span id="cb42-260"><a href="#cb42-260" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Hours allocation"</span>, <span class="at">y =</span> <span class="st">"Burnout Rate"</span>)<span class="sc">+</span></span>
<span id="cb42-261"><a href="#cb42-261" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span>
<span id="cb42-262"><a href="#cb42-262" aria-hidden="true" tabindex="-1"></a>scatter2</span>
<span id="cb42-263"><a href="#cb42-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-264"><a href="#cb42-264" aria-hidden="true" tabindex="-1"></a>scatter3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(fatigue,burn.rate))<span class="sc">+</span></span>
<span id="cb42-265"><a href="#cb42-265" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>WFH))<span class="sc">+</span></span>
<span id="cb42-266"><a href="#cb42-266" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"gam"</span>)<span class="sc">+</span></span>
<span id="cb42-267"><a href="#cb42-267" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Burnout Rate vs Mental Fatigue grouped by Gender and WFH setup"</span>,</span>
<span id="cb42-268"><a href="#cb42-268" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Mental Fatigue"</span>, <span class="at">y =</span> <span class="st">"Burnout Rate"</span>)<span class="sc">+</span></span>
<span id="cb42-269"><a href="#cb42-269" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>business)</span>
<span id="cb42-270"><a href="#cb42-270" aria-hidden="true" tabindex="-1"></a>scatter3</span>
<span id="cb42-271"><a href="#cb42-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-272"><a href="#cb42-272" aria-hidden="true" tabindex="-1"></a>scatter4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(hours,fatigue))<span class="sc">+</span></span>
<span id="cb42-273"><a href="#cb42-273" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>WFH))<span class="sc">+</span></span>
<span id="cb42-274"><a href="#cb42-274" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb42-275"><a href="#cb42-275" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Hours allocated vs Mental Fatigue grouped by Gender and WFH setup"</span>,</span>
<span id="cb42-276"><a href="#cb42-276" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Hours allocated"</span>, <span class="at">y =</span> <span class="st">"Mental fatigue"</span>)<span class="sc">+</span></span>
<span id="cb42-277"><a href="#cb42-277" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span>
<span id="cb42-278"><a href="#cb42-278" aria-hidden="true" tabindex="-1"></a>scatter4</span>
<span id="cb42-279"><a href="#cb42-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-280"><a href="#cb42-280" aria-hidden="true" tabindex="-1"></a>scatter5 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burn2, <span class="fu">aes</span>(designation, hours))<span class="sc">+</span></span>
<span id="cb42-281"><a href="#cb42-281" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>WFH))<span class="sc">+</span></span>
<span id="cb42-282"><a href="#cb42-282" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb42-283"><a href="#cb42-283" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Hours allocated vs Designation grouped by Gender and WFH setup"</span>,</span>
<span id="cb42-284"><a href="#cb42-284" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Designation"</span>, <span class="at">y =</span> <span class="st">"Hours allocated"</span>)<span class="sc">+</span></span>
<span id="cb42-285"><a href="#cb42-285" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span>
<span id="cb42-286"><a href="#cb42-286" aria-hidden="true" tabindex="-1"></a>scatter5</span>
<span id="cb42-287"><a href="#cb42-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-288"><a href="#cb42-288" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-289"><a href="#cb42-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-290"><a href="#cb42-290" aria-hidden="true" tabindex="-1"></a>From the charts we can see that there is a positive relationship between:</span>
<span id="cb42-291"><a href="#cb42-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-292"><a href="#cb42-292" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Designation and burnout rate</span>
<span id="cb42-293"><a href="#cb42-293" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Amount of hours allocated and burnout rate</span>
<span id="cb42-294"><a href="#cb42-294" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Mental fatigue and burnout rate</span>
<span id="cb42-295"><a href="#cb42-295" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Hours allocated and Mental fatigue</span>
<span id="cb42-296"><a href="#cb42-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-297"><a href="#cb42-297" aria-hidden="true" tabindex="-1"></a>All of those relationship exist regardless the gender and seems moderated by the work from home setup.</span>
<span id="cb42-298"><a href="#cb42-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-299"><a href="#cb42-299" aria-hidden="true" tabindex="-1"></a>Seems that working from home has a key role in the relationship of the variables.</span>
<span id="cb42-300"><a href="#cb42-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-301"><a href="#cb42-301" aria-hidden="true" tabindex="-1"></a>Lastly the relationship between Burnout rate and Fatigue doesn't look completely lineal, but let's check the so I will create a new variable by doing a quadratic transformation of Fatigue, and using it later for the regression.</span>
<span id="cb42-302"><a href="#cb42-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-303"><a href="#cb42-303" aria-hidden="true" tabindex="-1"></a>Let's  analyze these initial findings with a few statistics.</span>
<span id="cb42-304"><a href="#cb42-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-305"><a href="#cb42-305" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>First let's see how is the relationship between Burnout Rate, type of business, WFH and gender:</span>
<span id="cb42-306"><a href="#cb42-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-309"><a href="#cb42-309" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-310"><a href="#cb42-310" aria-hidden="true" tabindex="-1"></a><span class="co"># Three-way ANOVA</span></span>
<span id="cb42-311"><a href="#cb42-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-312"><a href="#cb42-312" aria-hidden="true" tabindex="-1"></a>aov.model1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(burn.rate <span class="sc">~</span> business <span class="sc">*</span> gender <span class="sc">*</span> WFH, <span class="at">data =</span> burn2)</span>
<span id="cb42-313"><a href="#cb42-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-314"><a href="#cb42-314" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov.model1)</span>
<span id="cb42-315"><a href="#cb42-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-316"><a href="#cb42-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-317"><a href="#cb42-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-318"><a href="#cb42-318" aria-hidden="true" tabindex="-1"></a>As we can see in this three-way ANOVA, type of business seems not relevant to explain burnout rate as the F value is not significant, but gender and WFH are both significant and also are when combined.</span>
<span id="cb42-319"><a href="#cb42-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-320"><a href="#cb42-320" aria-hidden="true" tabindex="-1"></a>Let's explore the relationship among continuous variables using a correlation matrix:</span>
<span id="cb42-321"><a href="#cb42-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-324"><a href="#cb42-324" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-325"><a href="#cb42-325" aria-hidden="true" tabindex="-1"></a><span class="co"># Cor Matrix</span></span>
<span id="cb42-326"><a href="#cb42-326" aria-hidden="true" tabindex="-1"></a>cor_matrix2 <span class="ot">&lt;-</span> <span class="fu">cor</span>(burn2[, <span class="fu">c</span>(<span class="st">"burn.rate"</span>, <span class="st">"hours"</span>, <span class="st">"designation"</span>, <span class="st">"fatigue"</span>)], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb42-327"><a href="#cb42-327" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cor_matrix2, <span class="dv">2</span>)</span>
<span id="cb42-328"><a href="#cb42-328" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-329"><a href="#cb42-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-330"><a href="#cb42-330" aria-hidden="true" tabindex="-1"></a>The first thing we have to notice is that Hours allocated shows strong correlation with almost all the rest fo the variables, this could represent multicollinearity. So I may need to exclude some variables the Regression analysis.</span>
<span id="cb42-331"><a href="#cb42-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-332"><a href="#cb42-332" aria-hidden="true" tabindex="-1"></a>In this case seems that designation has a very strong positive correlation with hours allocated, seems that the company assign to more senior employees more work hours.</span>
<span id="cb42-333"><a href="#cb42-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-334"><a href="#cb42-334" aria-hidden="true" tabindex="-1"></a>But to explain burnout seems more logic to think that number of work hours explain burnout, so I rather use hours and not designation in the model and avoid multicollinearity.</span>
<span id="cb42-335"><a href="#cb42-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-336"><a href="#cb42-336" aria-hidden="true" tabindex="-1"></a>Also I'll use backward Stepwise regression to keep only the relevant variables. </span>
<span id="cb42-337"><a href="#cb42-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-340"><a href="#cb42-340" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-341"><a href="#cb42-341" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a multiple regression model with predictor variables</span></span>
<span id="cb42-342"><a href="#cb42-342" aria-hidden="true" tabindex="-1"></a>lm.model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(burn.rate <span class="sc">~</span> fatigue <span class="sc">+</span> gender.f <span class="sc">+</span> business.p <span class="sc">+</span> hours <span class="sc">+</span> WFH.y, <span class="at">data =</span> burn2)</span>
<span id="cb42-343"><a href="#cb42-343" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.model1)</span>
<span id="cb42-344"><a href="#cb42-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-345"><a href="#cb42-345" aria-hidden="true" tabindex="-1"></a><span class="co"># Step Model - Forward</span></span>
<span id="cb42-346"><a href="#cb42-346" aria-hidden="true" tabindex="-1"></a>step_model1 <span class="ot">&lt;-</span> <span class="fu">step</span>(lm.model1, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">criterion=</span> <span class="st">"AIC"</span>)</span>
<span id="cb42-347"><a href="#cb42-347" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_model1)</span>
<span id="cb42-348"><a href="#cb42-348" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-349"><a href="#cb42-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-350"><a href="#cb42-350" aria-hidden="true" tabindex="-1"></a>Type of business is not relevant to the model to explain Burnout. so it is excluded from the model.</span>
<span id="cb42-351"><a href="#cb42-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-352"><a href="#cb42-352" aria-hidden="true" tabindex="-1"></a>And Fatigue, Gender, Working hours and WFH setting, all with a p-value &lt; 0.001 explain 92% of the burnout rate.</span>
<span id="cb42-353"><a href="#cb42-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-354"><a href="#cb42-354" aria-hidden="true" tabindex="-1"></a>In particular, any increase in units of Fatigue increases burnout rate by 0.07 points (or 7% as the burnout scale goes from 0 to 1). As well as Working hours, any additional hour allocated increases burnout rate by 0.02 points (or 2% increase).</span>
<span id="cb42-355"><a href="#cb42-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-356"><a href="#cb42-356" aria-hidden="true" tabindex="-1"></a>On the other side, being Male is significantly associated with higher burnout rates (0.004 points) and working on-site is also associated to higher burnout rates (increases the burnout rate by 1%, or 0.01 points).</span>
<span id="cb42-357"><a href="#cb42-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-358"><a href="#cb42-358" aria-hidden="true" tabindex="-1"></a>Let's check assumptions.</span>
<span id="cb42-359"><a href="#cb42-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-362"><a href="#cb42-362" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-363"><a href="#cb42-363" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb42-364"><a href="#cb42-364" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(step_model1, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb42-365"><a href="#cb42-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-366"><a href="#cb42-366" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-367"><a href="#cb42-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-368"><a href="#cb42-368" aria-hidden="true" tabindex="-1"></a>Doesn't seems there are assumptions violations in this model.</span>
<span id="cb42-369"><a href="#cb42-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-370"><a href="#cb42-370" aria-hidden="true" tabindex="-1"></a>However based on the scatter plot above about Burnout Rate and Fatigue, the relationship doesn't seem very linear, therefore if we apply a polynomial regression by doing a quadratic transformation of fatigue the model would adjust a bit better.</span>
<span id="cb42-371"><a href="#cb42-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-372"><a href="#cb42-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-375"><a href="#cb42-375" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-376"><a href="#cb42-376" aria-hidden="true" tabindex="-1"></a>lm.model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(burn.rate <span class="sc">~</span> business.p <span class="sc">+</span> hours <span class="sc">+</span> gender.f <span class="sc">+</span> <span class="fu">I</span>(fatigue<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> fatigue <span class="sc">+</span>  WFH.y, <span class="at">data =</span> burn2)</span>
<span id="cb42-377"><a href="#cb42-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-378"><a href="#cb42-378" aria-hidden="true" tabindex="-1"></a><span class="co"># Step Model - Forward</span></span>
<span id="cb42-379"><a href="#cb42-379" aria-hidden="true" tabindex="-1"></a>step_model2 <span class="ot">&lt;-</span> <span class="fu">step</span>(lm.model2, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">criterion=</span> <span class="st">"AIC"</span>)</span>
<span id="cb42-380"><a href="#cb42-380" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_model2)</span>
<span id="cb42-381"><a href="#cb42-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-382"><a href="#cb42-382" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb42-383"><a href="#cb42-383" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(step_model2, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb42-384"><a href="#cb42-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-385"><a href="#cb42-385" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-386"><a href="#cb42-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-387"><a href="#cb42-387" aria-hidden="true" tabindex="-1"></a>The model keeps the significant relationships we explained before and seems to fit better now. The new quadratic Fatigue is significant in the model, so I'll include it.</span>
<span id="cb42-388"><a href="#cb42-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-389"><a href="#cb42-389" aria-hidden="true" tabindex="-1"></a>Hours allocated, Gender, Fatigue and WFH or not seems to explain significantly the burnout in the employees included in the study. Being Hours allocated and fatigue the most relevant variables in the model to explain burnout (higher t value).</span>
<span id="cb42-390"><a href="#cb42-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-391"><a href="#cb42-391" aria-hidden="true" tabindex="-1"></a>Specifically, under this model burnout rate increases by 0.05 points (or 5%) per each unit increase in Fatigue and 0.02 (or 2%) per each hour allocated.</span>
<span id="cb42-392"><a href="#cb42-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-393"><a href="#cb42-393" aria-hidden="true" tabindex="-1"></a>But let's compare models.</span>
<span id="cb42-394"><a href="#cb42-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-397"><a href="#cb42-397" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-398"><a href="#cb42-398" aria-hidden="true" tabindex="-1"></a><span class="co">#PRESS</span></span>
<span id="cb42-399"><a href="#cb42-399" aria-hidden="true" tabindex="-1"></a>pr <span class="ot">&lt;-</span> <span class="fu">resid</span>(lm.model1)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">lm.influence</span>(lm.model1)<span class="sc">$</span>hat)</span>
<span id="cb42-400"><a href="#cb42-400" aria-hidden="true" tabindex="-1"></a>pr2 <span class="ot">&lt;-</span> pr<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb42-401"><a href="#cb42-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-402"><a href="#cb42-402" aria-hidden="true" tabindex="-1"></a>pr3 <span class="ot">&lt;-</span> <span class="fu">resid</span>(lm.model2)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">lm.influence</span>(lm.model1)<span class="sc">$</span>hat)</span>
<span id="cb42-403"><a href="#cb42-403" aria-hidden="true" tabindex="-1"></a>pr4 <span class="ot">&lt;-</span> pr3<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb42-404"><a href="#cb42-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-405"><a href="#cb42-405" aria-hidden="true" tabindex="-1"></a><span class="co">#df for table</span></span>
<span id="cb42-406"><a href="#cb42-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-407"><a href="#cb42-407" aria-hidden="true" tabindex="-1"></a>metrics_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb42-408"><a href="#cb42-408" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"Model 1"</span>, <span class="st">"Model 2 - Quadratic"</span>),</span>
<span id="cb42-409"><a href="#cb42-409" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">c</span>(<span class="fu">AIC</span>(lm.model1), <span class="fu">AIC</span>(lm.model2)),</span>
<span id="cb42-410"><a href="#cb42-410" aria-hidden="true" tabindex="-1"></a>  <span class="at">BIC =</span> <span class="fu">c</span>(<span class="fu">BIC</span>(lm.model1), <span class="fu">BIC</span>(lm.model2)),</span>
<span id="cb42-411"><a href="#cb42-411" aria-hidden="true" tabindex="-1"></a>  <span class="at">PRESS =</span> <span class="fu">c</span>(<span class="fu">sum</span>(pr2), <span class="fu">sum</span>(pr4))</span>
<span id="cb42-412"><a href="#cb42-412" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb42-413"><a href="#cb42-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-414"><a href="#cb42-414" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(metrics_df, <span class="at">caption =</span> <span class="st">"Models Comparison"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb42-415"><a href="#cb42-415" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="st">"striped"</span>)</span>
<span id="cb42-416"><a href="#cb42-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-417"><a href="#cb42-417" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb42-418"><a href="#cb42-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-419"><a href="#cb42-419" aria-hidden="true" tabindex="-1"></a>Considering that:</span>
<span id="cb42-420"><a href="#cb42-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-421"><a href="#cb42-421" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>R2 for model 1 is 0.9205 and for model 2 (with quadratic fatigue) is 0.9235</span>
<span id="cb42-422"><a href="#cb42-422" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>AIC, BIC and PRESS are very close among the two models</span>
<span id="cb42-423"><a href="#cb42-423" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>and, that in the model 2 any slightly violations of assumptions founded in model 1.</span>
<span id="cb42-424"><a href="#cb42-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-425"><a href="#cb42-425" aria-hidden="true" tabindex="-1"></a>We can say that both models works very well to explain burnout rate. But I feel more comfortable with Model 2 where the Mental Fatigue has a quadratic transformation as the R2 is higher for this model.</span>
<span id="cb42-426"><a href="#cb42-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-427"><a href="#cb42-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-428"><a href="#cb42-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-429"><a href="#cb42-429" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusions</span></span>
<span id="cb42-430"><a href="#cb42-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-431"><a href="#cb42-431" aria-hidden="true" tabindex="-1"></a>There is a positive relationship between burnout and designation level.</span>
<span id="cb42-432"><a href="#cb42-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-433"><a href="#cb42-433" aria-hidden="true" tabindex="-1"></a>This means that Alternative Hypothesis 2 can’t be accepted as it states a negative relationship between those two variables.</span>
<span id="cb42-434"><a href="#cb42-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-435"><a href="#cb42-435" aria-hidden="true" tabindex="-1"></a>On the other hand, Alternative Hypothesis 1 stated that being in Services and being female is related to a higher burnout rate, and the results indicate that the type of business is not relevant to predict burnout, and being female is neither associated with higher burnout.</span>
<span id="cb42-436"><a href="#cb42-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-437"><a href="#cb42-437" aria-hidden="true" tabindex="-1"></a>However, gender explains in part the burnout. In particular, being female is associated with a lower burnout rate compared to male employees.</span>
<span id="cb42-438"><a href="#cb42-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-439"><a href="#cb42-439" aria-hidden="true" tabindex="-1"></a>Lastly, concerning Alternative Hypothesis 3, the number of hours allocated is positively related to burnout; in particular, working on-site is associated with more working hours for males and females compared to employees working from home. However, within the group of employees working on-site, males seem to have significantly more hours allocated than females.</span>
<span id="cb42-440"><a href="#cb42-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-441"><a href="#cb42-441" aria-hidden="true" tabindex="-1"></a>Ultimately, the number of working hours and mental fatigue are the most relevant variables to explain burnout. Gender and WFH setup seems relevant regarding how the hours are allocated. Being male working on site absorbs more work hours, therefore more burnout.</span>
<span id="cb42-442"><a href="#cb42-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-443"><a href="#cb42-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-444"><a href="#cb42-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-445"><a href="#cb42-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-446"><a href="#cb42-446" aria-hidden="true" tabindex="-1"></a><span class="fu">### **References**:</span></span>
<span id="cb42-447"><a href="#cb42-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-448"><a href="#cb42-448" aria-hidden="true" tabindex="-1"></a>Bakker, A. B., &amp; Demerouti, E. (2017). Job demands-resources theory: Taking stock and looking forward. Journal of Occupational Health Psychology, 22(3), 273--285.</span>
<span id="cb42-449"><a href="#cb42-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-450"><a href="#cb42-450" aria-hidden="true" tabindex="-1"></a>Lee, Y., Eissenstat, S. (2017). A longitudinal examination of the causes and effects of burnout based on the job demands-resources model. International Journal for Educational and Vocational Guidance, 18(3), 337--354.</span>
<span id="cb42-451"><a href="#cb42-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-452"><a href="#cb42-452" aria-hidden="true" tabindex="-1"></a>Malesic, J. (2022). The end of Burnout. University of California Press.</span>
<span id="cb42-453"><a href="#cb42-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-454"><a href="#cb42-454" aria-hidden="true" tabindex="-1"></a>Maslach, C., &amp; Leiter, M. P. (2016). Understanding the burnout experience: Recent research and its implications for psychiatry. World Psychiatry, 15(2), 103--111.</span>
<span id="cb42-455"><a href="#cb42-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-456"><a href="#cb42-456" aria-hidden="true" tabindex="-1"></a>West, C. P., Dyrbye, L. N., Erwin, P., Shanafelt, T. D., (2016). Interventions to promote physician well-being and mitigate burnout: A systematic review and meta-analysis. The Lancet, 388(10057), 2272--228</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>