<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Thrishul Pola">
<meta name="dcterms.date" content="2023-05-02">
<meta name="description" content="Final Project">

<title>Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="styles.css">
<meta name="twitter:title" content="Final Project">
<meta name="twitter:description" content="Final Project">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-5-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#research-question" id="toc-research-question" class="nav-link active" data-scroll-target="#research-question">Research Question</a>
  <ul class="collapse">
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">Hypothesis</a></li>
  <li><a href="#importing-libraries" id="toc-importing-libraries" class="nav-link" data-scroll-target="#importing-libraries">Importing Libraries</a></li>
  <li><a href="#reading-and-analysing-dataset" id="toc-reading-and-analysing-dataset" class="nav-link" data-scroll-target="#reading-and-analysing-dataset">Reading and Analysing Dataset</a></li>
  </ul></li>
  <li><a href="#dataset-description" id="toc-dataset-description" class="nav-link" data-scroll-target="#dataset-description">Dataset Description</a>
  <ul class="collapse">
  <li><a href="#math-scores-based-on-reading-and-writing-scores" id="toc-math-scores-based-on-reading-and-writing-scores" class="nav-link" data-scroll-target="#math-scores-based-on-reading-and-writing-scores">Math Scores based on Reading and Writing Scores</a></li>
  <li><a href="#math-scores-based-on-gender" id="toc-math-scores-based-on-gender" class="nav-link" data-scroll-target="#math-scores-based-on-gender">Math Scores based on Gender</a></li>
  <li><a href="#math-scores-based-on-race" id="toc-math-scores-based-on-race" class="nav-link" data-scroll-target="#math-scores-based-on-race">Math Scores based on Race</a></li>
  <li><a href="#math-scores-based-on-parents-education-level" id="toc-math-scores-based-on-parents-education-level" class="nav-link" data-scroll-target="#math-scores-based-on-parents-education-level">Math Scores based on Parents Education Level</a></li>
  <li><a href="#correlation-matrix-of-math-reading-and-writing-scores" id="toc-correlation-matrix-of-math-reading-and-writing-scores" class="nav-link" data-scroll-target="#correlation-matrix-of-math-reading-and-writing-scores">Correlation Matrix of Math, Reading, and Writing Scores</a></li>
  <li><a href="#comparison-of-math-scores-between-male-and-female-students" id="toc-comparison-of-math-scores-between-male-and-female-students" class="nav-link" data-scroll-target="#comparison-of-math-scores-between-male-and-female-students">Comparison of Math Scores between Male and Female Students</a>
  <ul class="collapse">
  <li><a href="#t-test" id="toc-t-test" class="nav-link" data-scroll-target="#t-test">T-Test</a></li>
  <li><a href="#one-way-anova-test" id="toc-one-way-anova-test" class="nav-link" data-scroll-target="#one-way-anova-test">One-way ANOVA Test</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#linear-regression-models-for-predicting-math-scores" id="toc-linear-regression-models-for-predicting-math-scores" class="nav-link" data-scroll-target="#linear-regression-models-for-predicting-math-scores">Linear Regression Models for Predicting Math Scores</a>
  <ul class="collapse">
  <li><a href="#model-1" id="toc-model-1" class="nav-link" data-scroll-target="#model-1">Model 1</a></li>
  <li><a href="#model-2" id="toc-model-2" class="nav-link" data-scroll-target="#model-2">Model 2</a></li>
  <li><a href="#model-3" id="toc-model-3" class="nav-link" data-scroll-target="#model-3">Model 3</a></li>
  <li><a href="#model-comparison-using-aic-and-bic" id="toc-model-comparison-using-aic-and-bic" class="nav-link" data-scroll-target="#model-comparison-using-aic-and-bic">Model Comparison using AIC and BIC</a></li>
  </ul></li>
  <li><a href="#regression-diagnostics" id="toc-regression-diagnostics" class="nav-link" data-scroll-target="#regression-diagnostics">Regression Diagnostics</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">Bibliography</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Project</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Final_Project</div>
  </div>
  </div>

<div>
  <div class="description">
    Final Project
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Thrishul Pola </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 2, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="research-question" class="level1">
<h1>Research Question</h1>
<p>Can the reading and writing scores, along with gender, be used as predictors for students math exam scores?</p>
<section id="hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis">Hypothesis</h2>
<p>The math exam scores of students are positively associated with their reading and writing scores.</p>
<p>The math exam scores of male students are higher than those of female students.</p>
</section>
<section id="importing-libraries" class="level2">
<h2 class="anchored" data-anchor-id="importing-libraries">Importing Libraries</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fBasics) </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(funModeling)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>}))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="reading-and-analysing-dataset" class="level2">
<h2 class="anchored" data-anchor-id="reading-and-analysing-dataset">Reading and Analysing Dataset</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/S.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>names_columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"gender"</span>,<span class="st">"race"</span>,<span class="st">"parent_education"</span>,<span class="st">"lunch"</span>,<span class="st">"test_prep"</span>,<span class="st">"math_score"</span>,<span class="st">"reading_score"</span>,<span class="st">"writing_score"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data) <span class="ot">&lt;-</span> names_columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="dataset-description" class="level1">
<h1>Dataset Description</h1>
<p>The “Students Performance in Exams” dataset contains information about the marks obtained by students in different subjects. The dataset consists of 1000 rows and 8 features.</p>
<p>The categorical features in the dataset include:</p>
<p>Gender: Indicates whether the student is female or male. Race/Ethnicity: Represents the group to which the student belongs, categorized as Group A, Group B, Group C, Group D, or Group E. Parental Level of Education: Reflects the educational level of the student’s parents, such as associate’s degree, bachelor’s degree, high school, etc. Lunch: Specifies the type of lunch provided to the student, categorized as either free/reduced or standard. Test Preparation Course: Indicates whether the student completed a test preparation course or not.</p>
<p>The numerical features in the dataset are:</p>
<p>Math Score: Represents the marks obtained by the student in the math subject. Reading Score: Represents the marks obtained by the student in the reading subject. Writing Score: Represents the marks obtained by the student in the writing subject. All the scores in the dataset are measured on a scale of 0 to 100.</p>
<p>The dataset provides valuable insights into the performance of students in exams across various subjects. By analyzing this data, we can explore the relationships between different features and understand the factors that influence students’ academic achievements.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    gender              race           parent_education      lunch          
 Length:1000        Length:1000        Length:1000        Length:1000       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
  test_prep           math_score     reading_score    writing_score   
 Length:1000        Min.   :  0.00   Min.   : 17.00   Min.   : 10.00  
 Class :character   1st Qu.: 57.00   1st Qu.: 59.00   1st Qu.: 57.75  
 Mode  :character   Median : 66.00   Median : 70.00   Median : 69.00  
                    Mean   : 66.09   Mean   : 69.17   Mean   : 68.05  
                    3rd Qu.: 77.00   3rd Qu.: 79.00   3rd Qu.: 79.00  
                    Max.   :100.00   Max.   :100.00   Max.   :100.00  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["gender"],"name":[1],"type":["chr"],"align":["left"]},{"label":["race"],"name":[2],"type":["chr"],"align":["left"]},{"label":["parent_education"],"name":[3],"type":["chr"],"align":["left"]},{"label":["lunch"],"name":[4],"type":["chr"],"align":["left"]},{"label":["test_prep"],"name":[5],"type":["chr"],"align":["left"]},{"label":["math_score"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["reading_score"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["writing_score"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"female","2":"group B","3":"bachelor's degree","4":"standard","5":"none","6":"72","7":"72","8":"74"},{"1":"female","2":"group C","3":"some college","4":"standard","5":"completed","6":"69","7":"90","8":"88"},{"1":"female","2":"group B","3":"master's degree","4":"standard","5":"none","6":"90","7":"95","8":"93"},{"1":"male","2":"group A","3":"associate's degree","4":"free/reduced","5":"none","6":"47","7":"57","8":"44"},{"1":"male","2":"group C","3":"some college","4":"standard","5":"none","6":"76","7":"78","8":"75"},{"1":"female","2":"group B","3":"associate's degree","4":"standard","5":"none","6":"71","7":"83","8":"78"},{"1":"female","2":"group B","3":"some college","4":"standard","5":"completed","6":"88","7":"95","8":"92"},{"1":"male","2":"group B","3":"some college","4":"free/reduced","5":"none","6":"40","7":"43","8":"39"},{"1":"male","2":"group D","3":"high school","4":"free/reduced","5":"completed","6":"64","7":"64","8":"67"},{"1":"female","2":"group B","3":"high school","4":"free/reduced","5":"none","6":"38","7":"60","8":"50"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [1,000 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ gender          : chr [1:1000] "female" "female" "female" "male" ...
 $ race            : chr [1:1000] "group B" "group C" "group B" "group A" ...
 $ parent_education: chr [1:1000] "bachelor's degree" "some college" "master's degree" "associate's degree" ...
 $ lunch           : chr [1:1000] "standard" "standard" "standard" "free/reduced" ...
 $ test_prep       : chr [1:1000] "none" "completed" "none" "none" ...
 $ math_score      : num [1:1000] 72 69 90 47 76 71 88 40 64 38 ...
 $ reading_score   : num [1:1000] 72 90 95 57 78 83 95 43 64 60 ...
 $ writing_score   : num [1:1000] 74 88 93 44 75 78 92 39 67 50 ...
 - attr(*, "spec")=
  .. cols(
  ..   gender = col_character(),
  ..   `race/ethnicity` = col_character(),
  ..   `parental level of education` = col_character(),
  ..   lunch = col_character(),
  ..   `test preparation course` = col_character(),
  ..   math = col_double(),
  ..   reading = col_double(),
  ..   writing = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anyNA</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `&lt;scale&gt;` argument of `guides()` cannot be `FALSE`. Use "none" instead as
of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the funModeling package.
  Please report the issue at &lt;https://github.com/pablo14/funModeling/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["var"],"name":[1],"type":["chr"],"align":["left"]},{"label":["frequency"],"name":[2],"type":["int"],"align":["right"]},{"label":["percentage"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["cumulative_perc"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"female","2":"518","3":"51.8","4":"51.8"},{"1":"male","2":"482","3":"48.2","4":"100.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>It can be observed that among the students included, approximately 51.8% of them are female students. This indicates that the majority of the students in the dataset are female.</p>
<p>On the other hand, approximately 48.2% of the students in the dataset are male students. This suggests that male students make up a slightly smaller portion of the total student population compared to female students.</p>
<p>Overall, the dataset represents a relatively balanced distribution in terms of gender, with a slightly higher proportion of female students.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>race)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["var"],"name":[1],"type":["chr"],"align":["left"]},{"label":["frequency"],"name":[2],"type":["int"],"align":["right"]},{"label":["percentage"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["cumulative_perc"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"group C","2":"319","3":"31.9","4":"31.9"},{"1":"group D","2":"262","3":"26.2","4":"58.1"},{"1":"group B","2":"190","3":"19.0","4":"77.1"},{"1":"group E","2":"140","3":"14.0","4":"91.1"},{"1":"group A","2":"89","3":"8.9","4":"100.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>It can be observed that Group C is the most prevalent race/ethnicity among the students. This suggests that a larger number of students in the dataset belong to Group C compared to the other race/ethnicity categories while Group A is the least represented race/ethnicity among the students.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>parent_education)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["var"],"name":[1],"type":["chr"],"align":["left"]},{"label":["frequency"],"name":[2],"type":["int"],"align":["right"]},{"label":["percentage"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["cumulative_perc"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"some college","2":"226","3":"22.6","4":"22.6"},{"1":"associate's degree","2":"222","3":"22.2","4":"44.8"},{"1":"high school","2":"196","3":"19.6","4":"64.4"},{"1":"some high school","2":"179","3":"17.9","4":"82.3"},{"1":"bachelor's degree","2":"118","3":"11.8","4":"94.1"},{"1":"master's degree","2":"59","3":"5.9","4":"100.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Above chart reveal the distribution of parent education levels among the students in the dataset. Out of the total number of students, 226 individuals (22.6%) reported having their parents pursued some college education</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>lunch)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["var"],"name":[1],"type":["chr"],"align":["left"]},{"label":["frequency"],"name":[2],"type":["int"],"align":["right"]},{"label":["percentage"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["cumulative_perc"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"standard","2":"645","3":"64.5","4":"64.5"},{"1":"free/reduced","2":"355","3":"35.5","4":"100.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Standard Price Lunch: 64.5% Approximately 64.5% of the students in the dataset eat lunch at the standard price. This indicates that the majority of the students opt for the standard-priced lunch option.</p>
<p>Free/Reduced Lunch: 35.5% About 35.5% of the students in the dataset eat lunch at a free or reduced price. This suggests that a smaller portion of the students qualify for and choose the free or reduced lunch option.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data,<span class="fu">aes</span>(data<span class="sc">$</span>gender, <span class="at">fill=</span>data<span class="sc">$</span>race))<span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="fu">position_dodge</span>())<span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Ethnic Group distribution by Gender"</span>)<span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Gender"</span>)<span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I have compared the gender with their race type and its interesting to see that the majority of students in the dataset are from group C followed by group D race.</p>
<p>So, keeping all the analysed information in mind i want to conduct the correlation analysis for the variables Math, Reading and Writing scores and see if there is any correlation between the variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">profiling_num</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["variable"],"name":[1],"type":["chr"],"align":["left"]},{"label":["mean"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std_dev"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["variation_coef"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p_01"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["p_05"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["p_25"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["p_50"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["p_75"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["p_95"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["p_99"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["skewness"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["kurtosis"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["iqr"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["range_98"],"name":[15],"type":["chr"],"align":["left"]},{"label":["range_80"],"name":[16],"type":["chr"],"align":["left"]}],"data":[{"1":"math_score","2":"66.089","3":"15.16308","4":"0.2294342","5":"27.99","6":"40.95","7":"57.00","8":"66","9":"77","10":"90.05","11":"98.01","12":"-0.2785166","13":"3.267597","14":"20.00","15":"[27.99, 98.01]","16":"[47, 86]"},{"1":"reading_score","2":"69.169","3":"14.60019","4":"0.2110800","5":"31.99","6":"44.00","7":"59.00","8":"70","9":"79","10":"92.00","11":"100.00","12":"-0.2587157","13":"2.926081","14":"20.00","15":"[31.99, 100]","16":"[51, 87.1]"},{"1":"writing_score","2":"68.054","3":"15.19566","4":"0.2232882","5":"31.98","6":"42.95","7":"57.75","8":"69","9":"79","10":"92.00","11":"100.00","12":"-0.2890096","13":"2.960808","14":"21.25","15":"[31.98, 100]","16":"[48, 87]"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_num</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on our hypothesis that the math exam scores of students are positively associated with their reading and writing scores, the findings from the profiling analysis and also plot chart provide evidence supporting this hypothesis. The average scores for math, reading, and writing are relatively close, indicating a positive association between these subjects.</p>
<section id="math-scores-based-on-reading-and-writing-scores" class="level2">
<h2 class="anchored" data-anchor-id="math-scores-based-on-reading-and-writing-scores">Math Scores based on Reading and Writing Scores</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># scatter plot</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> reading_score, <span class="at">y =</span> writing_score, <span class="at">color =</span> math_score)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Reading Score"</span>, <span class="at">y =</span> <span class="st">"Writing Score"</span>, </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores based on Reading and Writing Scores"</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="math-scores-based-on-gender" class="level2">
<h2 class="anchored" data-anchor-id="math-scores-based-on-gender">Math Scores based on Gender</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by gender</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> gender, <span class="at">y =</span> mean_math_score)) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Gender"</span>, <span class="at">y =</span> <span class="st">"Mean Math Score"</span>, </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Mean Math Scores by Gender"</span>) <span class="sc">+</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The chart reveals that the mean math score for males is approximately 68.73, indicating a relatively higher average performance in math compared to females . On the other hand,females have a mean math score of around 63.63, suggesting a slightly lower average performance in math compared to males . These findings highlight a gender-based difference in math scores, with males demonstrating a higher average math score compared to females.</p>
</section>
<section id="math-scores-based-on-race" class="level2">
<h2 class="anchored" data-anchor-id="math-scores-based-on-race">Math Scores based on Race</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by race</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(race) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Race"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>, </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Race"</span>) <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> mean_math_score, </span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Mean: "</span>, <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>))),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>These findings highlight the variations in math scores across different race categories, with Group E demonstrating the highest average score and Group A showing the lowest average score performance.</p>
</section>
<section id="math-scores-based-on-parents-education-level" class="level2">
<h2 class="anchored" data-anchor-id="math-scores-based-on-parents-education-level">Math Scores based on Parents Education Level</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> parent_education, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Parental Education Level"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Parental Education Level"</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Even thought there is a little difference in the math scores there is not significant difference based on their parents education level</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by lunch type</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lunch) <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> lunch, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Lunch Type"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Lunch Type"</span>) <span class="sc">+</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> lunch, <span class="at">y =</span> mean_math_score,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Mean: "</span>, <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>))),</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It is interesting to see the math score of students based on their lunch type. Students how are taking standard meal are performing better at math as compared to people taking free or reduced lunch option.</p>
</section>
<section id="correlation-matrix-of-math-reading-and-writing-scores" class="level2">
<h2 class="anchored" data-anchor-id="correlation-matrix-of-math-reading-and-writing-scores">Correlation Matrix of Math, Reading, and Writing Scores</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>num_data <span class="ot">&lt;-</span> data[, <span class="fu">c</span>( <span class="st">"math_score"</span>, <span class="st">"reading_score"</span>, <span class="st">"writing_score"</span>)]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>m<span class="ot">&lt;-</span><span class="fu">cor</span>(num_data)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>m</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              math_score reading_score writing_score
math_score     1.0000000     0.8175797     0.8026420
reading_score  0.8175797     1.0000000     0.9545981
writing_score  0.8026420     0.9545981     1.0000000</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(m, <span class="at">method=</span><span class="st">"circle"</span>, <span class="at">type=</span><span class="st">'upper'</span>, <span class="at">tl.cex=</span><span class="fl">0.8</span>, <span class="at">tl.col =</span> <span class="st">'black'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The correlation analysis reveals interesting insights into the relationships between math scores, reading scores, and writing scores. The strong positive correlation coefficient of 0.8176 between math_score and reading_score suggests that students who excel in math also tend to perform well in reading. Similarly, the high correlation coefficient of 0.8026 between math_score and writing_score indicates a strong positive association, indicating that students who demonstrate proficiency in math often display strong writing skills as well. Furthermore, the very high correlation coefficient of 0.9546 between reading_score and writing_score highlights a robust positive relationship, indicating that students who excel in reading are highly likely to excel in writing.</p>
<p>Taken together, these findings provide substantial evidence supporting our hypothesis that math exam scores are positively associated with both reading and writing scores. These results suggest that students who demonstrate proficiency in one subject area are more likely to excel in the other subjects as well, reinforcing the idea of a positive relationship between math scores and reading/writing scores.</p>
</section>
<section id="comparison-of-math-scores-between-male-and-female-students" class="level2">
<h2 class="anchored" data-anchor-id="comparison-of-math-scores-between-male-and-female-students">Comparison of Math Scores between Male and Female Students</h2>
<section id="t-test" class="level3">
<h3 class="anchored" data-anchor-id="t-test">T-Test</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test for math scores</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>ttest_math <span class="ot">&lt;-</span> <span class="fu">t.test</span>(math_score <span class="sc">~</span> gender, <span class="at">data =</span> data)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>ttest_math</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  math_score by gender
t = -5.398, df = 997.98, p-value = 8.421e-08
alternative hypothesis: true difference in means between group female and group male is not equal to 0
95 percent confidence interval:
 -6.947209 -3.242813
sample estimates:
mean in group female   mean in group male 
            63.63320             68.72822 </code></pre>
</div>
</div>
</section>
<section id="one-way-anova-test" class="level3">
<h3 class="anchored" data-anchor-id="one-way-anova-test">One-way ANOVA Test</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-way ANOVA for all three subjects</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>anova_scores <span class="ot">&lt;-</span> <span class="fu">aov</span>(math_score <span class="sc">+</span> reading_score <span class="sc">+</span> writing_score <span class="sc">~</span> gender, <span class="at">data =</span> data)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
gender        1   31297   31297   17.39 3.31e-05 ***
Residuals   998 1796315    1800                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Based on the analysis conducted, we performed a Welch Two Sample t-test to examine the differences in math scores between male and female students. The results indicate that there is a statistically significant disparity in the mean math scores between the two groups (t = -5.398, df = 997.98, p-value = 8.421e-08). It was found that the mean math score for females (63.63) is significantly lower compared to males (68.73) with a 95% confidence interval ranging from -6.947209 to -3.242813.</p>
<p>Furthermore, we conducted a one-way ANOVA to explore the impact of gender on math, reading, and writing scores. The ANOVA results demonstrate a significant effect of gender on math scores (F = 17.39, p &lt; 0.001). However, this analysis does not provide information regarding the relationship between math scores and reading/writing scores.</p>
<p>In summary, our analysis reveals a significant difference in math scores between male and female students, with males demonstrating higher performance in this subject compared to females. These findings highlight the influence of gender on academic achievement, particularly in the context of math</p>
</section>
</section>
</section>
<section id="linear-regression-models-for-predicting-math-scores" class="level1">
<h1>Linear Regression Models for Predicting Math Scores</h1>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>train_idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(data), <span class="fu">nrow</span>(data) <span class="sc">*</span> <span class="fl">0.7</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> data[train_idx, ]</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> data[<span class="sc">-</span>train_idx, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="model-1" class="level3">
<h3 class="anchored" data-anchor-id="model-1">Model 1</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> reading_score <span class="sc">+</span> writing_score, <span class="at">data =</span> train_data)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>predictions1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1, <span class="at">newdata =</span> test_data)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>rmse1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test_data<span class="sc">$</span>math_score <span class="sc">-</span> predictions1)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>r_squared1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(model1)<span class="sc">$</span>r.squared</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>rmse1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.753639</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>r_squared1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6630448</code></pre>
</div>
</div>
<p>This model includes reading score and writing score as predictors for math score. The root mean squared error (RMSE) for predicting math scores on the test data is approximately 8.75. The R-squared value, which represents the proportion of variance in math scores explained by the model, is approximately 0.663. This suggests that reading score and writing score collectively account for about 66.3% of the variation in math scores.</p>
</section>
<section id="model-2" class="level3">
<h3 class="anchored" data-anchor-id="model-2">Model 2</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> writing_score <span class="sc">*</span> reading_score <span class="sc">+</span> gender , <span class="at">data =</span> train_data)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>predictions2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model2, <span class="at">newdata =</span> test_data)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>rmse2 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test_data<span class="sc">$</span>math_score <span class="sc">-</span> predictions2)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>r_squared2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(model2)<span class="sc">$</span>r.squared</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>rmse2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.148844</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>r_squared2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8366321</code></pre>
</div>
</div>
<p>This model extends Model 1 by including an interaction term between writing score and reading score, as well as the gender variable. The RMSE for this model is approximately 6.15, indicating a slight improvement in prediction accuracy compared to Model 1. The R-squared value increases to approximately 0.837, suggesting that the addition of the interaction term and gender variable accounts for a higher proportion of the variation in math scores.</p>
</section>
<section id="model-3" class="level3">
<h3 class="anchored" data-anchor-id="model-3">Model 3</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span>  ., <span class="at">data =</span> train_data)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>predictions3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model3, <span class="at">newdata =</span> test_data)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>rmse3 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test_data<span class="sc">$</span>math_score <span class="sc">-</span> predictions3)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>r_squared3 <span class="ot">&lt;-</span> <span class="fu">summary</span>(model3)<span class="sc">$</span>r.squared</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>rmse3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.697975</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>r_squared3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8774988</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = math_score ~ ., data = train_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.6908  -3.3311   0.0567   3.2723  14.3230 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       -12.69377    1.50380  -8.441  &lt; 2e-16 ***
gendermale                         13.39247    0.43457  30.818  &lt; 2e-16 ***
racegroup B                         0.24651    0.84199   0.293  0.76979    
racegroup C                        -0.08452    0.77853  -0.109  0.91358    
racegroup D                         0.16262    0.79821   0.204  0.83862    
racegroup E                         5.15433    0.87327   5.902 5.64e-09 ***
parent_educationbachelor's degree  -0.53390    0.72488  -0.737  0.46166    
parent_educationhigh school         1.34623    0.63690   2.114  0.03490 *  
parent_educationmaster's degree    -2.37927    0.90659  -2.624  0.00887 ** 
parent_educationsome college       -0.06383    0.59119  -0.108  0.91405    
parent_educationsome high school    1.16923    0.64611   1.810  0.07079 .  
lunchstandard                       3.02912    0.43865   6.906 1.14e-11 ***
test_prepnone                       3.77531    0.45966   8.213 1.07e-15 ***
reading_score                       0.22861    0.04978   4.592 5.22e-06 ***
writing_score                       0.74989    0.05098  14.711  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.253 on 685 degrees of freedom
Multiple R-squared:  0.8775,    Adjusted R-squared:  0.875 
F-statistic: 350.5 on 14 and 685 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>This model includes all available variables as predictors for math score. The RMSE decreases further to approximately 5.70, indicating improved prediction accuracy compared to both Model 1 and Model 2. The R-squared value increases to approximately 0.877, indicating that this model explains approximately 87.7% of the variance in math scores when considering all available predictors.</p>
</section>
<section id="model-comparison-using-aic-and-bic" class="level3">
<h3 class="anchored" data-anchor-id="model-comparison-using-aic-and-bic">Model Comparison using AIC and BIC</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [1,000 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ gender          : chr [1:1000] "female" "female" "female" "male" ...
 $ race            : chr [1:1000] "group B" "group C" "group B" "group A" ...
 $ parent_education: chr [1:1000] "bachelor's degree" "some college" "master's degree" "associate's degree" ...
 $ lunch           : chr [1:1000] "standard" "standard" "standard" "free/reduced" ...
 $ test_prep       : chr [1:1000] "none" "completed" "none" "none" ...
 $ math_score      : num [1:1000] 72 69 90 47 76 71 88 40 64 38 ...
 $ reading_score   : num [1:1000] 72 90 95 57 78 83 95 43 64 60 ...
 $ writing_score   : num [1:1000] 74 88 93 44 75 78 92 39 67 50 ...
 - attr(*, "spec")=
  .. cols(
  ..   gender = col_character(),
  ..   `race/ethnicity` = col_character(),
  ..   `parental level of education` = col_character(),
  ..   lunch = col_character(),
  ..   `test preparation course` = col_character(),
  ..   math = col_double(),
  ..   reading = col_double(),
  ..   writing = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model1,model2, model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["AIC"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"4","2":"5009.934","_rn_":"model1"},{"1":"6","2":"4507.172","_rn_":"model2"},{"1":"16","2":"4325.654","_rn_":"model3"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(model1,model2, model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"4","2":"5028.138","_rn_":"model1"},{"1":"6","2":"4534.478","_rn_":"model2"},{"1":"16","2":"4398.471","_rn_":"model3"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>When comparing the models using the Akaike Information Criterion (AIC) and Bayesian Information Criterion (BIC), lower values indicate better model fit.</p>
<p>Model 1: AIC = 5009.934, BIC = 5028.138 Model 2: AIC = 4507.172, BIC = 4534.478 Model 3: AIC = 4325.654, BIC = 4398.471</p>
<p>The AIC and BIC values for each model suggest that Model 3 has the best fit among the three models. However, adding gender to reading and writing score made the model better and fit. it is very near to the model3 which includes all the variables.</p>
<p>As the AIC and BIC scores are less compared to Model1 &amp; Model2, Im choosing Model3 to perform Residual Diagnostics</p>
</section>
</section>
<section id="regression-diagnostics" class="level1">
<h1>Regression Diagnostics</h1>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-25-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="FinalProject_checkin_2_Thrishul_files/figure-html/unnamed-chunk-25-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As we can see the Residual Diagnosis plots above for Model3, in all the plots the red line fitted values are straight and linear accross all the plots indicating that the model is better fit.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Please cite as: </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model1, model2, model3, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
=============================================================================================================
                                                              Dependent variable:                            
                                  ---------------------------------------------------------------------------
                                                                  math_score                                 
                                            (1)                      (2)                       (3)           
-------------------------------------------------------------------------------------------------------------
reading_score                             0.539***                 0.276***                 0.229***         
                                          (0.077)                  (0.077)                   (0.050)         
                                                                                                             
gendermale                                                        13.197***                 13.392***        
                                                                   (0.486)                   (0.435)         
                                                                                                             
writing_score:reading_score                                         0.001                                    
                                                                   (0.001)                                   
                                                                                                             
racegroup B                                                                                   0.247          
                                                                                             (0.842)         
                                                                                                             
racegroup C                                                                                  -0.085          
                                                                                             (0.779)         
                                                                                                             
racegroup D                                                                                   0.163          
                                                                                             (0.798)         
                                                                                                             
racegroup E                                                                                 5.154***         
                                                                                             (0.873)         
                                                                                                             
parent_educationbachelor's degree                                                            -0.534          
                                                                                             (0.725)         
                                                                                                             
parent_educationhigh school                                                                  1.346**         
                                                                                             (0.637)         
                                                                                                             
parent_educationmaster's degree                                                             -2.379***        
                                                                                             (0.907)         
                                                                                                             
parent_educationsome college                                                                 -0.064          
                                                                                             (0.591)         
                                                                                                             
parent_educationsome high school                                                             1.169*          
                                                                                             (0.646)         
                                                                                                             
lunchstandard                                                                               3.029***         
                                                                                             (0.439)         
                                                                                                             
test_prepnone                                                                               3.775***         
                                                                                             (0.460)         
                                                                                                             
writing_score                             0.304***                 0.553***                 0.750***         
                                          (0.073)                  (0.074)                   (0.051)         
                                                                                                             
Constant                                  8.214***                  -2.079                 -12.694***        
                                          (1.631)                  (3.629)                   (1.504)         
                                                                                                             
-------------------------------------------------------------------------------------------------------------
Observations                                700                      700                       700           
R2                                         0.663                    0.837                     0.877          
Adjusted R2                                0.662                    0.836                     0.875          
Residual Std. Error                   8.637 (df = 697)         6.022 (df = 695)         5.253 (df = 685)     
F Statistic                       685.762*** (df = 2; 697) 889.801*** (df = 4; 695) 350.484*** (df = 14; 685)
=============================================================================================================
Note:                                                                             *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>In Model 1, we found that an increase in the reading score is linked to a higher math score. The coefficient for the reading score was statistically significant (p &lt; 0.01) and had a positive value of 0.539. This suggests that students who perform better in reading tend to have higher math scores. Similarly, the coefficient for the writing score was also statistically significant (p &lt; 0.01) with a positive value of 0.304. This implies that students who excel in writing also tend to have higher math scores.</p>
<p>When we examined Model 2, which includes additional variables, we observed that the coefficients for reading_score and writing_score remained statistically significant and positive. This finding reaffirms the results from Model 1, indicating a consistent relationship between reading, writing, and math scores. It suggests that students who perform well in both reading and writing are likely to have higher math scores.</p>
<p>In Model 3, where we considered all available variables, we found that the coefficients for reading_score and writing_score continued to be statistically significant and positive. This further supports our hypothesis that math scores are positively associated with both reading and writing scores. It suggests that students who demonstrate strong abilities in reading and writing are more likely to achieve higher math scores.</p>
<p>These findings provide evidence supporting our hypothesis that math exam scores are positively associated with reading and writing scores and that there is a gender difference in math performance, with males outperforming females.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>In conclusion, our research focused on examining the factors influencing math scores among students. We analyzed a dataset containing information on various variables such as gender, race/ethnicity, parental education, lunch type, test preparation, and scores in reading and writing.</p>
<p>Our findings revealed several important insights. Firstly, gender played a significant role, with male students showing higher math scores compared to females.</p>
<p>The scores in reading and writing were strongly correlated with math scores. Higher scores in reading and writing were associated with higher math scores.</p>
<p>Additionally, the type of lunch and completion of a test preparation course were also found to have a positive impact on math scores. Students who had a standard lunch and completed a test preparation course tended to perform better in math.</p>
<p>Overall, our research suggests that reading and writing, gender, and lunch type are important factors influencing math scores among students.</p>
<p>It is important to note that this research was based on a specific dataset and may not capture all possible factors influencing math scores. Further research and exploration are recommended to gain a comprehensive understanding of the complex dynamics affecting students’ math performance.</p>
</section>
<section id="bibliography" class="level1">
<h1>Bibliography</h1>
<p>Dataset : “Students Performance in Exams” Dataset. Retrieved from https://www.kaggle.com/datasets/spscientist/students-performance-in-exams</p>
<p>Johnson, R. A. (2010). Applied Multivariate Statistical Analysis (6th ed.). Pearson Education.</p>
<p>Field, A. (2013). Discovering Statistics Using R. SAGE Publications Ltd.</p>
<p>Wickham, H. (2016). ggplot2: Elegant Graphics for Data Analysis. Springer.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb56" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Project"</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Thrishul Pola"</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Final Project"</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "5/2/2023"</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - Final_Project</span></span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a><span class="fu"># Research Question</span></span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a>Can the reading and writing scores, along with gender, be used as predictors for students math exam scores?</span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis</span></span>
<span id="cb56-23"><a href="#cb56-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-24"><a href="#cb56-24" aria-hidden="true" tabindex="-1"></a>The math exam scores of students are positively associated with their reading and writing scores.</span>
<span id="cb56-25"><a href="#cb56-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-26"><a href="#cb56-26" aria-hidden="true" tabindex="-1"></a>The math exam scores of male students are higher than those of female students.</span>
<span id="cb56-27"><a href="#cb56-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-28"><a href="#cb56-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Importing Libraries</span></span>
<span id="cb56-29"><a href="#cb56-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-32"><a href="#cb56-32" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-33"><a href="#cb56-33" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb56-34"><a href="#cb56-34" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb56-35"><a href="#cb56-35" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb56-36"><a href="#cb56-36" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb56-37"><a href="#cb56-37" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fBasics) </span>
<span id="cb56-38"><a href="#cb56-38" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb56-39"><a href="#cb56-39" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(funModeling)</span>
<span id="cb56-40"><a href="#cb56-40" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb56-41"><a href="#cb56-41" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb56-42"><a href="#cb56-42" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb56-43"><a href="#cb56-43" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb56-44"><a href="#cb56-44" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-45"><a href="#cb56-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-46"><a href="#cb56-46" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reading and Analysing Dataset</span></span>
<span id="cb56-49"><a href="#cb56-49" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-50"><a href="#cb56-50" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/S.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb56-51"><a href="#cb56-51" aria-hidden="true" tabindex="-1"></a>names_columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"gender"</span>,<span class="st">"race"</span>,<span class="st">"parent_education"</span>,<span class="st">"lunch"</span>,<span class="st">"test_prep"</span>,<span class="st">"math_score"</span>,<span class="st">"reading_score"</span>,<span class="st">"writing_score"</span>)</span>
<span id="cb56-52"><a href="#cb56-52" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data) <span class="ot">&lt;-</span> names_columns</span>
<span id="cb56-53"><a href="#cb56-53" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-54"><a href="#cb56-54" aria-hidden="true" tabindex="-1"></a><span class="fu"># Dataset Description</span></span>
<span id="cb56-55"><a href="#cb56-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-56"><a href="#cb56-56" aria-hidden="true" tabindex="-1"></a>The "Students Performance in Exams" dataset contains information about the marks obtained by students in different subjects. The dataset consists of 1000 rows and 8 features.</span>
<span id="cb56-57"><a href="#cb56-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-58"><a href="#cb56-58" aria-hidden="true" tabindex="-1"></a>The categorical features in the dataset include:</span>
<span id="cb56-59"><a href="#cb56-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-60"><a href="#cb56-60" aria-hidden="true" tabindex="-1"></a>Gender: Indicates whether the student is female or male.</span>
<span id="cb56-61"><a href="#cb56-61" aria-hidden="true" tabindex="-1"></a>Race/Ethnicity: Represents the group to which the student belongs, categorized as Group A, Group B, Group C, Group D, or Group E.</span>
<span id="cb56-62"><a href="#cb56-62" aria-hidden="true" tabindex="-1"></a>Parental Level of Education: Reflects the educational level of the student's parents, such as associate's degree, bachelor's degree, high school, etc.</span>
<span id="cb56-63"><a href="#cb56-63" aria-hidden="true" tabindex="-1"></a>Lunch: Specifies the type of lunch provided to the student, categorized as either free/reduced or standard.</span>
<span id="cb56-64"><a href="#cb56-64" aria-hidden="true" tabindex="-1"></a>Test Preparation Course: Indicates whether the student completed a test preparation course or not.</span>
<span id="cb56-65"><a href="#cb56-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-66"><a href="#cb56-66" aria-hidden="true" tabindex="-1"></a>The numerical features in the dataset are:</span>
<span id="cb56-67"><a href="#cb56-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-68"><a href="#cb56-68" aria-hidden="true" tabindex="-1"></a>Math Score: Represents the marks obtained by the student in the math subject.</span>
<span id="cb56-69"><a href="#cb56-69" aria-hidden="true" tabindex="-1"></a>Reading Score: Represents the marks obtained by the student in the reading subject.</span>
<span id="cb56-70"><a href="#cb56-70" aria-hidden="true" tabindex="-1"></a>Writing Score: Represents the marks obtained by the student in the writing subject.</span>
<span id="cb56-71"><a href="#cb56-71" aria-hidden="true" tabindex="-1"></a>All the scores in the dataset are measured on a scale of 0 to 100.</span>
<span id="cb56-72"><a href="#cb56-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-73"><a href="#cb56-73" aria-hidden="true" tabindex="-1"></a>The dataset provides valuable insights into the performance of students in exams across various subjects. By analyzing this data, we can explore the relationships between different features and understand the factors that influence students' academic achievements.</span>
<span id="cb56-76"><a href="#cb56-76" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-77"><a href="#cb56-77" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span>
<span id="cb56-78"><a href="#cb56-78" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data, <span class="dv">10</span>)</span>
<span id="cb56-79"><a href="#cb56-79" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-82"><a href="#cb56-82" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-83"><a href="#cb56-83" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span>
<span id="cb56-84"><a href="#cb56-84" aria-hidden="true" tabindex="-1"></a><span class="fu">anyNA</span>(data)</span>
<span id="cb56-85"><a href="#cb56-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-88"><a href="#cb56-88" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-89"><a href="#cb56-89" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>gender)</span>
<span id="cb56-90"><a href="#cb56-90" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-91"><a href="#cb56-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-92"><a href="#cb56-92" aria-hidden="true" tabindex="-1"></a>It can be observed that among the students included, approximately 51.8% of them are female students. This indicates that the majority of the students in the dataset are female.</span>
<span id="cb56-93"><a href="#cb56-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-94"><a href="#cb56-94" aria-hidden="true" tabindex="-1"></a>On the other hand, approximately 48.2% of the students in the dataset are male students. This suggests that male students make up a slightly smaller portion of the total student population compared to female students.</span>
<span id="cb56-95"><a href="#cb56-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-96"><a href="#cb56-96" aria-hidden="true" tabindex="-1"></a>Overall, the dataset represents a relatively balanced distribution in terms of gender, with a slightly higher proportion of female students.</span>
<span id="cb56-97"><a href="#cb56-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-100"><a href="#cb56-100" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-101"><a href="#cb56-101" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>race)</span>
<span id="cb56-102"><a href="#cb56-102" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-103"><a href="#cb56-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-104"><a href="#cb56-104" aria-hidden="true" tabindex="-1"></a>It can be observed that Group C is the most prevalent race/ethnicity among the students. This suggests that a larger number of students in the dataset belong to Group C compared to the other race/ethnicity categories while  Group A is the least represented race/ethnicity among the students.</span>
<span id="cb56-105"><a href="#cb56-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-108"><a href="#cb56-108" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-109"><a href="#cb56-109" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>parent_education)</span>
<span id="cb56-110"><a href="#cb56-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-111"><a href="#cb56-111" aria-hidden="true" tabindex="-1"></a>Above chart reveal the distribution of parent education levels among the students in the dataset. Out of the total number of students, 226 individuals (22.6%) reported having their parents pursued some college education</span>
<span id="cb56-112"><a href="#cb56-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-115"><a href="#cb56-115" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-116"><a href="#cb56-116" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>lunch)</span>
<span id="cb56-117"><a href="#cb56-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-118"><a href="#cb56-118" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-119"><a href="#cb56-119" aria-hidden="true" tabindex="-1"></a>Standard Price Lunch: 64.5%</span>
<span id="cb56-120"><a href="#cb56-120" aria-hidden="true" tabindex="-1"></a>Approximately 64.5% of the students in the dataset eat lunch at the standard price. This indicates that the majority of the students opt for the standard-priced lunch option.</span>
<span id="cb56-121"><a href="#cb56-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-122"><a href="#cb56-122" aria-hidden="true" tabindex="-1"></a>Free/Reduced Lunch: 35.5%</span>
<span id="cb56-123"><a href="#cb56-123" aria-hidden="true" tabindex="-1"></a>About 35.5% of the students in the dataset eat lunch at a free or reduced price. This suggests that a smaller portion of the students qualify for and choose the free or reduced lunch option.</span>
<span id="cb56-124"><a href="#cb56-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-127"><a href="#cb56-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-128"><a href="#cb56-128" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data,<span class="fu">aes</span>(data<span class="sc">$</span>gender, <span class="at">fill=</span>data<span class="sc">$</span>race))<span class="sc">+</span></span>
<span id="cb56-129"><a href="#cb56-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="fu">position_dodge</span>())<span class="sc">+</span></span>
<span id="cb56-130"><a href="#cb56-130" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Ethnic Group distribution by Gender"</span>)<span class="sc">+</span></span>
<span id="cb56-131"><a href="#cb56-131" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Gender"</span>)<span class="sc">+</span></span>
<span id="cb56-132"><a href="#cb56-132" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Frequency"</span>)</span>
<span id="cb56-133"><a href="#cb56-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-134"><a href="#cb56-134" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-135"><a href="#cb56-135" aria-hidden="true" tabindex="-1"></a>I have compared the gender with their race type and its interesting to see that the majority of students in the dataset are from group C followed by group D race.</span>
<span id="cb56-136"><a href="#cb56-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-137"><a href="#cb56-137" aria-hidden="true" tabindex="-1"></a>So, keeping all the analysed information in mind i want to conduct the correlation analysis for the variables Math, Reading and Writing scores and see if there is any correlation between the variables.</span>
<span id="cb56-138"><a href="#cb56-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-139"><a href="#cb56-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-140"><a href="#cb56-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-143"><a href="#cb56-143" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-144"><a href="#cb56-144" aria-hidden="true" tabindex="-1"></a><span class="fu">profiling_num</span>(data)</span>
<span id="cb56-145"><a href="#cb56-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-146"><a href="#cb56-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-147"><a href="#cb56-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-148"><a href="#cb56-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-151"><a href="#cb56-151" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-152"><a href="#cb56-152" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_num</span>(data)</span>
<span id="cb56-153"><a href="#cb56-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-154"><a href="#cb56-154" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-155"><a href="#cb56-155" aria-hidden="true" tabindex="-1"></a>Based on our hypothesis that the math exam scores of students are positively associated with their reading and writing scores, the findings from the profiling analysis and also plot chart provide evidence supporting this hypothesis. The average scores for math, reading, and writing are relatively close, indicating a positive association between these subjects.</span>
<span id="cb56-156"><a href="#cb56-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-157"><a href="#cb56-157" aria-hidden="true" tabindex="-1"></a><span class="fu">## Math Scores based on Reading and Writing Scores</span></span>
<span id="cb56-158"><a href="#cb56-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-161"><a href="#cb56-161" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-162"><a href="#cb56-162" aria-hidden="true" tabindex="-1"></a><span class="co"># scatter plot</span></span>
<span id="cb56-163"><a href="#cb56-163" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> reading_score, <span class="at">y =</span> writing_score, <span class="at">color =</span> math_score)) <span class="sc">+</span></span>
<span id="cb56-164"><a href="#cb56-164" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb56-165"><a href="#cb56-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Reading Score"</span>, <span class="at">y =</span> <span class="st">"Writing Score"</span>, </span>
<span id="cb56-166"><a href="#cb56-166" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores based on Reading and Writing Scores"</span>) <span class="sc">+</span></span>
<span id="cb56-167"><a href="#cb56-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb56-168"><a href="#cb56-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-169"><a href="#cb56-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-170"><a href="#cb56-170" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-171"><a href="#cb56-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-172"><a href="#cb56-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-173"><a href="#cb56-173" aria-hidden="true" tabindex="-1"></a><span class="fu">## Math Scores based on Gender</span></span>
<span id="cb56-176"><a href="#cb56-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-177"><a href="#cb56-177" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by gender</span></span>
<span id="cb56-178"><a href="#cb56-178" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb56-179"><a href="#cb56-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender) <span class="sc">%&gt;%</span></span>
<span id="cb56-180"><a href="#cb56-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb56-181"><a href="#cb56-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-182"><a href="#cb56-182" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb56-183"><a href="#cb56-183" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> gender, <span class="at">y =</span> mean_math_score)) <span class="sc">+</span></span>
<span id="cb56-184"><a href="#cb56-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb56-185"><a href="#cb56-185" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Gender"</span>, <span class="at">y =</span> <span class="st">"Mean Math Score"</span>, </span>
<span id="cb56-186"><a href="#cb56-186" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Mean Math Scores by Gender"</span>) <span class="sc">+</span></span>
<span id="cb56-187"><a href="#cb56-187" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb56-188"><a href="#cb56-188" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span>
<span id="cb56-189"><a href="#cb56-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-190"><a href="#cb56-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-191"><a href="#cb56-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-192"><a href="#cb56-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-193"><a href="#cb56-193" aria-hidden="true" tabindex="-1"></a>The chart reveals that the mean math score for males is approximately 68.73, indicating a relatively higher average performance in math compared to females . On the other hand,females have a mean math score of around 63.63, suggesting a slightly lower average performance in math compared to males . These findings highlight a gender-based difference in math scores, with males demonstrating a higher average math score compared to females.</span>
<span id="cb56-194"><a href="#cb56-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-195"><a href="#cb56-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-196"><a href="#cb56-196" aria-hidden="true" tabindex="-1"></a><span class="fu">## Math Scores based on Race</span></span>
<span id="cb56-199"><a href="#cb56-199" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-200"><a href="#cb56-200" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by race</span></span>
<span id="cb56-201"><a href="#cb56-201" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb56-202"><a href="#cb56-202" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(race) <span class="sc">%&gt;%</span></span>
<span id="cb56-203"><a href="#cb56-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb56-204"><a href="#cb56-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-205"><a href="#cb56-205" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb56-206"><a href="#cb56-206" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb56-207"><a href="#cb56-207" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb56-208"><a href="#cb56-208" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Race"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>, </span>
<span id="cb56-209"><a href="#cb56-209" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Race"</span>) <span class="sc">+</span></span>
<span id="cb56-210"><a href="#cb56-210" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb56-211"><a href="#cb56-211" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> mean_math_score, </span>
<span id="cb56-212"><a href="#cb56-212" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Mean: "</span>, <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>))),</span>
<span id="cb56-213"><a href="#cb56-213" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span>
<span id="cb56-214"><a href="#cb56-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-215"><a href="#cb56-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-216"><a href="#cb56-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-217"><a href="#cb56-217" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-218"><a href="#cb56-218" aria-hidden="true" tabindex="-1"></a>These findings highlight the variations in math scores across different race categories, with Group E demonstrating the highest average score and Group A showing the lowest average score performance.</span>
<span id="cb56-219"><a href="#cb56-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-220"><a href="#cb56-220" aria-hidden="true" tabindex="-1"></a><span class="fu">## Math Scores based on Parents Education Level</span></span>
<span id="cb56-221"><a href="#cb56-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-224"><a href="#cb56-224" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-225"><a href="#cb56-225" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb56-226"><a href="#cb56-226" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> parent_education, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb56-227"><a href="#cb56-227" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb56-228"><a href="#cb56-228" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Parental Education Level"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>, </span>
<span id="cb56-229"><a href="#cb56-229" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Parental Education Level"</span>) <span class="sc">+</span></span>
<span id="cb56-230"><a href="#cb56-230" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb56-231"><a href="#cb56-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-232"><a href="#cb56-232" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-233"><a href="#cb56-233" aria-hidden="true" tabindex="-1"></a>Even thought there is a little difference in the math scores there is not significant difference based on their parents education level</span>
<span id="cb56-234"><a href="#cb56-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-235"><a href="#cb56-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-236"><a href="#cb56-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-239"><a href="#cb56-239" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-240"><a href="#cb56-240" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb56-241"><a href="#cb56-241" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb56-242"><a href="#cb56-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-243"><a href="#cb56-243" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by lunch type</span></span>
<span id="cb56-244"><a href="#cb56-244" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb56-245"><a href="#cb56-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lunch) <span class="sc">%&gt;%</span></span>
<span id="cb56-246"><a href="#cb56-246" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb56-247"><a href="#cb56-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-248"><a href="#cb56-248" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb56-249"><a href="#cb56-249" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> lunch, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb56-250"><a href="#cb56-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb56-251"><a href="#cb56-251" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Lunch Type"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>,</span>
<span id="cb56-252"><a href="#cb56-252" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Lunch Type"</span>) <span class="sc">+</span></span>
<span id="cb56-253"><a href="#cb56-253" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb56-254"><a href="#cb56-254" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> lunch, <span class="at">y =</span> mean_math_score,</span>
<span id="cb56-255"><a href="#cb56-255" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Mean: "</span>, <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>))),</span>
<span id="cb56-256"><a href="#cb56-256" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span>
<span id="cb56-257"><a href="#cb56-257" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-258"><a href="#cb56-258" aria-hidden="true" tabindex="-1"></a>It is interesting to see the math score of students based on their lunch type. Students how are taking standard meal are performing better at math as compared to people taking free or reduced lunch option. </span>
<span id="cb56-259"><a href="#cb56-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-260"><a href="#cb56-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-261"><a href="#cb56-261" aria-hidden="true" tabindex="-1"></a><span class="fu">## Correlation Matrix of Math, Reading, and Writing Scores</span></span>
<span id="cb56-262"><a href="#cb56-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-265"><a href="#cb56-265" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-266"><a href="#cb56-266" aria-hidden="true" tabindex="-1"></a>num_data <span class="ot">&lt;-</span> data[, <span class="fu">c</span>( <span class="st">"math_score"</span>, <span class="st">"reading_score"</span>, <span class="st">"writing_score"</span>)]</span>
<span id="cb56-267"><a href="#cb56-267" aria-hidden="true" tabindex="-1"></a>m<span class="ot">&lt;-</span><span class="fu">cor</span>(num_data)</span>
<span id="cb56-268"><a href="#cb56-268" aria-hidden="true" tabindex="-1"></a>m</span>
<span id="cb56-269"><a href="#cb56-269" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(m, <span class="at">method=</span><span class="st">"circle"</span>, <span class="at">type=</span><span class="st">'upper'</span>, <span class="at">tl.cex=</span><span class="fl">0.8</span>, <span class="at">tl.col =</span> <span class="st">'black'</span>)</span>
<span id="cb56-270"><a href="#cb56-270" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-271"><a href="#cb56-271" aria-hidden="true" tabindex="-1"></a>The correlation analysis reveals interesting insights into the relationships between math scores, reading scores, and writing scores. The strong positive correlation coefficient of 0.8176 between math_score and reading_score suggests that students who excel in math also tend to perform well in reading. Similarly, the high correlation coefficient of 0.8026 between math_score and writing_score indicates a strong positive association, indicating that students who demonstrate proficiency in math often display strong writing skills as well. Furthermore, the very high correlation coefficient of 0.9546 between reading_score and writing_score highlights a robust positive relationship, indicating that students who excel in reading are highly likely to excel in writing.</span>
<span id="cb56-272"><a href="#cb56-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-273"><a href="#cb56-273" aria-hidden="true" tabindex="-1"></a>Taken together, these findings provide substantial evidence supporting our hypothesis that math exam scores are positively associated with both reading and writing scores. These results suggest that students who demonstrate proficiency in one subject area are more likely to excel in the other subjects as well, reinforcing the idea of a positive relationship between math scores and reading/writing scores.</span>
<span id="cb56-274"><a href="#cb56-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-275"><a href="#cb56-275" aria-hidden="true" tabindex="-1"></a><span class="fu">## Comparison of Math Scores between Male and Female Students</span></span>
<span id="cb56-276"><a href="#cb56-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-277"><a href="#cb56-277" aria-hidden="true" tabindex="-1"></a><span class="fu">### T-Test</span></span>
<span id="cb56-280"><a href="#cb56-280" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-281"><a href="#cb56-281" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test for math scores</span></span>
<span id="cb56-282"><a href="#cb56-282" aria-hidden="true" tabindex="-1"></a>ttest_math <span class="ot">&lt;-</span> <span class="fu">t.test</span>(math_score <span class="sc">~</span> gender, <span class="at">data =</span> data)</span>
<span id="cb56-283"><a href="#cb56-283" aria-hidden="true" tabindex="-1"></a>ttest_math</span>
<span id="cb56-284"><a href="#cb56-284" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-285"><a href="#cb56-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-286"><a href="#cb56-286" aria-hidden="true" tabindex="-1"></a><span class="fu">### One-way ANOVA Test</span></span>
<span id="cb56-289"><a href="#cb56-289" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-290"><a href="#cb56-290" aria-hidden="true" tabindex="-1"></a><span class="co"># One-way ANOVA for all three subjects</span></span>
<span id="cb56-291"><a href="#cb56-291" aria-hidden="true" tabindex="-1"></a>anova_scores <span class="ot">&lt;-</span> <span class="fu">aov</span>(math_score <span class="sc">+</span> reading_score <span class="sc">+</span> writing_score <span class="sc">~</span> gender, <span class="at">data =</span> data)</span>
<span id="cb56-292"><a href="#cb56-292" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_scores)</span>
<span id="cb56-293"><a href="#cb56-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-294"><a href="#cb56-294" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-295"><a href="#cb56-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-296"><a href="#cb56-296" aria-hidden="true" tabindex="-1"></a>Based on the analysis conducted, we performed a Welch Two Sample t-test to examine the differences in math scores between male and female students. The results indicate that there is a statistically significant disparity in the mean math scores between the two groups (t = -5.398, df = 997.98, p-value = 8.421e-08). It was found that the mean math score for females (63.63) is significantly lower compared to males (68.73) with a 95% confidence interval ranging from -6.947209 to -3.242813.</span>
<span id="cb56-297"><a href="#cb56-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-298"><a href="#cb56-298" aria-hidden="true" tabindex="-1"></a>Furthermore, we conducted a one-way ANOVA to explore the impact of gender on math, reading, and writing scores. The ANOVA results demonstrate a significant effect of gender on math scores (F = 17.39, p &lt; 0.001). However, this analysis does not provide information regarding the relationship between math scores and reading/writing scores.</span>
<span id="cb56-299"><a href="#cb56-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-300"><a href="#cb56-300" aria-hidden="true" tabindex="-1"></a>In summary, our analysis reveals a significant difference in math scores between male and female students, with males demonstrating higher performance in this subject compared to females. These findings highlight the influence of gender on academic achievement, particularly in the context of math</span>
<span id="cb56-301"><a href="#cb56-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-302"><a href="#cb56-302" aria-hidden="true" tabindex="-1"></a><span class="fu"># Linear Regression Models for Predicting Math Scores</span></span>
<span id="cb56-303"><a href="#cb56-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-306"><a href="#cb56-306" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-307"><a href="#cb56-307" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb56-308"><a href="#cb56-308" aria-hidden="true" tabindex="-1"></a>train_idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(data), <span class="fu">nrow</span>(data) <span class="sc">*</span> <span class="fl">0.7</span>)</span>
<span id="cb56-309"><a href="#cb56-309" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> data[train_idx, ]</span>
<span id="cb56-310"><a href="#cb56-310" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> data[<span class="sc">-</span>train_idx, ]</span>
<span id="cb56-311"><a href="#cb56-311" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-312"><a href="#cb56-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-313"><a href="#cb56-313" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 1</span></span>
<span id="cb56-316"><a href="#cb56-316" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-317"><a href="#cb56-317" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> reading_score <span class="sc">+</span> writing_score, <span class="at">data =</span> train_data)</span>
<span id="cb56-318"><a href="#cb56-318" aria-hidden="true" tabindex="-1"></a>predictions1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1, <span class="at">newdata =</span> test_data)</span>
<span id="cb56-319"><a href="#cb56-319" aria-hidden="true" tabindex="-1"></a>rmse1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test_data<span class="sc">$</span>math_score <span class="sc">-</span> predictions1)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb56-320"><a href="#cb56-320" aria-hidden="true" tabindex="-1"></a>r_squared1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(model1)<span class="sc">$</span>r.squared</span>
<span id="cb56-321"><a href="#cb56-321" aria-hidden="true" tabindex="-1"></a>rmse1</span>
<span id="cb56-322"><a href="#cb56-322" aria-hidden="true" tabindex="-1"></a>r_squared1</span>
<span id="cb56-323"><a href="#cb56-323" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-324"><a href="#cb56-324" aria-hidden="true" tabindex="-1"></a>This model includes reading score and writing score as predictors for math score. The root mean squared error (RMSE) for predicting math scores on the test data is approximately 8.75. The R-squared value, which represents the proportion of variance in math scores explained by the model, is approximately 0.663. This suggests that reading score and writing score collectively account for about 66.3% of the variation in math scores.</span>
<span id="cb56-325"><a href="#cb56-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-326"><a href="#cb56-326" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 2</span></span>
<span id="cb56-329"><a href="#cb56-329" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-330"><a href="#cb56-330" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> writing_score <span class="sc">*</span> reading_score <span class="sc">+</span> gender , <span class="at">data =</span> train_data)</span>
<span id="cb56-331"><a href="#cb56-331" aria-hidden="true" tabindex="-1"></a>predictions2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model2, <span class="at">newdata =</span> test_data)</span>
<span id="cb56-332"><a href="#cb56-332" aria-hidden="true" tabindex="-1"></a>rmse2 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test_data<span class="sc">$</span>math_score <span class="sc">-</span> predictions2)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb56-333"><a href="#cb56-333" aria-hidden="true" tabindex="-1"></a>r_squared2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(model2)<span class="sc">$</span>r.squared</span>
<span id="cb56-334"><a href="#cb56-334" aria-hidden="true" tabindex="-1"></a>rmse2</span>
<span id="cb56-335"><a href="#cb56-335" aria-hidden="true" tabindex="-1"></a>r_squared2</span>
<span id="cb56-336"><a href="#cb56-336" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-337"><a href="#cb56-337" aria-hidden="true" tabindex="-1"></a>This model extends Model 1 by including an interaction term between writing score and reading score, as well as the gender variable. The RMSE for this model is approximately 6.15, indicating a slight improvement in prediction accuracy compared to Model 1. The R-squared value increases to approximately 0.837, suggesting that the addition of the interaction term and gender variable accounts for a higher proportion of the variation in math scores.</span>
<span id="cb56-338"><a href="#cb56-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-339"><a href="#cb56-339" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 3</span></span>
<span id="cb56-342"><a href="#cb56-342" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-343"><a href="#cb56-343" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span>  ., <span class="at">data =</span> train_data)</span>
<span id="cb56-344"><a href="#cb56-344" aria-hidden="true" tabindex="-1"></a>predictions3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model3, <span class="at">newdata =</span> test_data)</span>
<span id="cb56-345"><a href="#cb56-345" aria-hidden="true" tabindex="-1"></a>rmse3 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test_data<span class="sc">$</span>math_score <span class="sc">-</span> predictions3)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb56-346"><a href="#cb56-346" aria-hidden="true" tabindex="-1"></a>r_squared3 <span class="ot">&lt;-</span> <span class="fu">summary</span>(model3)<span class="sc">$</span>r.squared</span>
<span id="cb56-347"><a href="#cb56-347" aria-hidden="true" tabindex="-1"></a>rmse3</span>
<span id="cb56-348"><a href="#cb56-348" aria-hidden="true" tabindex="-1"></a>r_squared3</span>
<span id="cb56-349"><a href="#cb56-349" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span>
<span id="cb56-350"><a href="#cb56-350" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-351"><a href="#cb56-351" aria-hidden="true" tabindex="-1"></a>This model includes all available variables as predictors for math score. The RMSE decreases further to approximately 5.70, indicating improved prediction accuracy compared to both Model 1 and Model 2. The R-squared value increases to approximately 0.877, indicating that this model explains approximately 87.7% of the variance in math scores when considering all available predictors.</span>
<span id="cb56-352"><a href="#cb56-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-353"><a href="#cb56-353" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model Comparison using AIC and BIC</span></span>
<span id="cb56-354"><a href="#cb56-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-357"><a href="#cb56-357" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-358"><a href="#cb56-358" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span>
<span id="cb56-359"><a href="#cb56-359" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model1,model2, model3)</span>
<span id="cb56-360"><a href="#cb56-360" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(model1,model2, model3)</span>
<span id="cb56-361"><a href="#cb56-361" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-362"><a href="#cb56-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-363"><a href="#cb56-363" aria-hidden="true" tabindex="-1"></a>When comparing the models using the Akaike Information Criterion (AIC) and Bayesian Information Criterion (BIC), lower values indicate better model fit. </span>
<span id="cb56-364"><a href="#cb56-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-365"><a href="#cb56-365" aria-hidden="true" tabindex="-1"></a>Model 1: AIC = 5009.934, BIC = 5028.138</span>
<span id="cb56-366"><a href="#cb56-366" aria-hidden="true" tabindex="-1"></a>Model 2: AIC = 4507.172, BIC = 4534.478</span>
<span id="cb56-367"><a href="#cb56-367" aria-hidden="true" tabindex="-1"></a>Model 3: AIC = 4325.654, BIC = 4398.471</span>
<span id="cb56-368"><a href="#cb56-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-369"><a href="#cb56-369" aria-hidden="true" tabindex="-1"></a>The AIC and BIC values for each model suggest that Model 3 has the best fit among the three models. However, adding gender to reading and writing score made the model better and fit. it is very near to the model3 which includes all the variables.</span>
<span id="cb56-370"><a href="#cb56-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-371"><a href="#cb56-371" aria-hidden="true" tabindex="-1"></a>As the AIC and BIC scores are less compared to Model1 &amp; Model2, Im choosing Model3 to perform Residual Diagnostics </span>
<span id="cb56-372"><a href="#cb56-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-373"><a href="#cb56-373" aria-hidden="true" tabindex="-1"></a><span class="fu"># Regression Diagnostics</span></span>
<span id="cb56-374"><a href="#cb56-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-377"><a href="#cb56-377" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-378"><a href="#cb56-378" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model3)</span>
<span id="cb56-379"><a href="#cb56-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-380"><a href="#cb56-380" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-381"><a href="#cb56-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-382"><a href="#cb56-382" aria-hidden="true" tabindex="-1"></a>As we can see the Residual Diagnosis plots above for Model3, in all the plots the red line fitted values are straight and linear accross all the plots indicating that the model is better fit.</span>
<span id="cb56-383"><a href="#cb56-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-386"><a href="#cb56-386" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-387"><a href="#cb56-387" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb56-388"><a href="#cb56-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-389"><a href="#cb56-389" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model1, model2, model3, <span class="at">type =</span> <span class="st">"text"</span>)</span>
<span id="cb56-390"><a href="#cb56-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-391"><a href="#cb56-391" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-392"><a href="#cb56-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-393"><a href="#cb56-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-394"><a href="#cb56-394" aria-hidden="true" tabindex="-1"></a>In Model 1, we found that an increase in the reading score is linked to a higher math score. The coefficient for the reading score was statistically significant (p &lt; 0.01) and had a positive value of 0.539. This suggests that students who perform better in reading tend to have higher math scores. Similarly, the coefficient for the writing score was also statistically significant (p &lt; 0.01) with a positive value of 0.304. This implies that students who excel in writing also tend to have higher math scores.</span>
<span id="cb56-395"><a href="#cb56-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-396"><a href="#cb56-396" aria-hidden="true" tabindex="-1"></a>When we examined Model 2, which includes additional variables, we observed that the coefficients for reading_score and writing_score remained statistically significant and positive. This finding reaffirms the results from Model 1, indicating a consistent relationship between reading, writing, and math scores. It suggests that students who perform well in both reading and writing are likely to have higher math scores.</span>
<span id="cb56-397"><a href="#cb56-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-398"><a href="#cb56-398" aria-hidden="true" tabindex="-1"></a>In Model 3, where we considered all available variables, we found that the coefficients for reading_score and writing_score continued to be statistically significant and positive. This further supports our hypothesis that math scores are positively associated with both reading and writing scores. It suggests that students who demonstrate strong abilities in reading and writing are more likely to achieve higher math scores.</span>
<span id="cb56-399"><a href="#cb56-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-400"><a href="#cb56-400" aria-hidden="true" tabindex="-1"></a>These findings provide evidence supporting our hypothesis that math exam scores are positively associated with reading and writing scores and that there is a gender difference in math performance, with males outperforming females.</span>
<span id="cb56-401"><a href="#cb56-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-402"><a href="#cb56-402" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusion</span></span>
<span id="cb56-403"><a href="#cb56-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-404"><a href="#cb56-404" aria-hidden="true" tabindex="-1"></a>In conclusion, our research focused on examining the factors influencing math scores among students. We analyzed a dataset containing information on various variables such as gender, race/ethnicity, parental education, lunch type, test preparation, and scores in reading and writing.</span>
<span id="cb56-405"><a href="#cb56-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-406"><a href="#cb56-406" aria-hidden="true" tabindex="-1"></a>Our findings revealed several important insights. Firstly, gender played a significant role, with male students showing higher math scores compared to females. </span>
<span id="cb56-407"><a href="#cb56-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-408"><a href="#cb56-408" aria-hidden="true" tabindex="-1"></a>The scores in reading and writing were strongly correlated with math scores. Higher scores in reading and writing were associated with higher math scores.</span>
<span id="cb56-409"><a href="#cb56-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-410"><a href="#cb56-410" aria-hidden="true" tabindex="-1"></a>Additionally, the type of lunch and completion of a test preparation course were also found to have a positive impact on math scores. Students who had a standard lunch and completed a test preparation course tended to perform better in math.</span>
<span id="cb56-411"><a href="#cb56-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-412"><a href="#cb56-412" aria-hidden="true" tabindex="-1"></a>Overall, our research suggests that reading and writing, gender, and lunch type are important factors influencing math scores among students. </span>
<span id="cb56-413"><a href="#cb56-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-414"><a href="#cb56-414" aria-hidden="true" tabindex="-1"></a>It is important to note that this research was based on a specific dataset and may not capture all possible factors influencing math scores. Further research and exploration are recommended to gain a comprehensive understanding of the complex dynamics affecting students' math performance.</span>
<span id="cb56-415"><a href="#cb56-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-416"><a href="#cb56-416" aria-hidden="true" tabindex="-1"></a><span class="fu"># Bibliography</span></span>
<span id="cb56-417"><a href="#cb56-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-418"><a href="#cb56-418" aria-hidden="true" tabindex="-1"></a>Dataset : "Students Performance in Exams" Dataset. Retrieved from https://www.kaggle.com/datasets/spscientist/students-performance-in-exams</span>
<span id="cb56-419"><a href="#cb56-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-420"><a href="#cb56-420" aria-hidden="true" tabindex="-1"></a>Johnson, R. A. (2010). Applied Multivariate Statistical Analysis (6th ed.). Pearson Education.</span>
<span id="cb56-421"><a href="#cb56-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-422"><a href="#cb56-422" aria-hidden="true" tabindex="-1"></a>Field, A. (2013). Discovering Statistics Using R. SAGE Publications Ltd.</span>
<span id="cb56-423"><a href="#cb56-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-424"><a href="#cb56-424" aria-hidden="true" tabindex="-1"></a>Wickham, H. (2016). ggplot2: Elegant Graphics for Data Analysis. Springer.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>