<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Thrishul Pola">
<meta name="dcterms.date" content="2023-05-02">
<meta name="description" content="Final Project">

<title>Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="styles.css">
<meta name="twitter:title" content="Final Project">
<meta name="twitter:description" content="Final Project">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/FinalProject_Thrishul_files/figure-html/unnamed-chunk-5-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#research-question" id="toc-research-question" class="nav-link active" data-scroll-target="#research-question">Research Question</a>
  <ul class="collapse">
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">Hypothesis</a></li>
  <li><a href="#importing-libraries" id="toc-importing-libraries" class="nav-link" data-scroll-target="#importing-libraries">Importing Libraries</a></li>
  <li><a href="#reading-and-analysing-dataset" id="toc-reading-and-analysing-dataset" class="nav-link" data-scroll-target="#reading-and-analysing-dataset">Reading and Analysing Dataset</a></li>
  </ul></li>
  <li><a href="#dataset-description" id="toc-dataset-description" class="nav-link" data-scroll-target="#dataset-description">Dataset Description</a>
  <ul class="collapse">
  <li><a href="#math-scores-based-on-reading-and-writing-scores" id="toc-math-scores-based-on-reading-and-writing-scores" class="nav-link" data-scroll-target="#math-scores-based-on-reading-and-writing-scores">Math Scores based on Reading and Writing Scores</a></li>
  <li><a href="#math-scores-based-on-gender" id="toc-math-scores-based-on-gender" class="nav-link" data-scroll-target="#math-scores-based-on-gender">Math Scores based on Gender</a></li>
  <li><a href="#math-scores-based-on-race" id="toc-math-scores-based-on-race" class="nav-link" data-scroll-target="#math-scores-based-on-race">Math Scores based on Race</a></li>
  <li><a href="#math-scores-based-on-parents-education-level" id="toc-math-scores-based-on-parents-education-level" class="nav-link" data-scroll-target="#math-scores-based-on-parents-education-level">Math Scores based on Parents Education Level</a></li>
  <li><a href="#correlation-matrix-of-math-reading-and-writing-scores" id="toc-correlation-matrix-of-math-reading-and-writing-scores" class="nav-link" data-scroll-target="#correlation-matrix-of-math-reading-and-writing-scores">Correlation Matrix of Math, Reading, and Writing Scores</a>
  <ul class="collapse">
  <li><a href="#statistical-analysis---homogeneity-of-variance-test" id="toc-statistical-analysis---homogeneity-of-variance-test" class="nav-link" data-scroll-target="#statistical-analysis---homogeneity-of-variance-test">Statistical Analysis - Homogeneity of Variance Test</a></li>
  <li><a href="#welchs-t-test" id="toc-welchs-t-test" class="nav-link" data-scroll-target="#welchs-t-test">Welch’s T-Test</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#linear-regression-models" id="toc-linear-regression-models" class="nav-link" data-scroll-target="#linear-regression-models">Linear Regression Models</a>
  <ul class="collapse">
  <li><a href="#model-comparison-using-aic-and-bic" id="toc-model-comparison-using-aic-and-bic" class="nav-link" data-scroll-target="#model-comparison-using-aic-and-bic">Model Comparison using AIC and BIC</a></li>
  <li><a href="#diagnostics" id="toc-diagnostics" class="nav-link" data-scroll-target="#diagnostics">Diagnostics</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">Bibliography</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Project</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Final_Project</div>
    <div class="quarto-category">Thrishul</div>
  </div>
  </div>

<div>
  <div class="description">
    Final Project
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Thrishul Pola </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 2, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="research-question" class="level1">
<h1>Research Question</h1>
<p>Why do some students have higher math exam scores?</p>
<section id="hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis">Hypothesis</h2>
<p>We hypothesize that math exam scores are positively associated with students’ reading and writing scores.</p>
<p>The math exam scores of male students are higher than those of female students.</p>
<p>Numerous studies have indicated a positive relationship between reading, writing, and math abilities. The skills required for success in these subjects often overlap, as they involve critical thinking, problem-solving, and comprehension of complex information. For example, research by Smith and Johnson found that students with higher reading and writing proficiency tend to exhibit better math performance.</p>
<p>Additionally, cognitive theories, such as the aptitude-treatment interaction (ATI) framework proposed by Cronbach and Snow, support the idea that students who possess strong language skills, including reading and writing, are better equipped to understand and apply mathematical concepts. Language acts as a cognitive tool that aids in the comprehension and reasoning required for solving math problems.</p>
</section>
<section id="importing-libraries" class="level2">
<h2 class="anchored" data-anchor-id="importing-libraries">Importing Libraries</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fBasics) </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(funModeling)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>}))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="reading-and-analysing-dataset" class="level2">
<h2 class="anchored" data-anchor-id="reading-and-analysing-dataset">Reading and Analysing Dataset</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/S.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>names_columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"gender"</span>,<span class="st">"race"</span>,<span class="st">"parent_education"</span>,<span class="st">"lunch"</span>,<span class="st">"test_prep"</span>,<span class="st">"math_score"</span>,<span class="st">"reading_score"</span>,<span class="st">"writing_score"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data) <span class="ot">&lt;-</span> names_columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="dataset-description" class="level1">
<h1>Dataset Description</h1>
<p>The dataset contains information on exam scores for students at a public school. The data is collected from a single public school and is not specified for any particular year.</p>
<p>The “Students Performance in Exams” dataset contains information about the marks obtained by students in different subjects. The dataset consists of 1000 rows and 8 features.</p>
<p>The categorical features in the dataset include:</p>
<p>Gender: Indicates whether the student is female or male. Race/Ethnicity: As the race is a very sensitive topic the person who collected this data have hidden the actual race categories. The race category represents the group to which the student belongs, categorized as Group A, Group B, Group C, Group D, or Group E. Parental Level of Education: Reflects the educational level of the student’s parents, such as associate’s degree, bachelor’s degree, high school, etc. Lunch: Specifies the type of lunch provided to the student, categorized as either free/reduced or standard. Test Preparation Course: Indicates whether the student completed a test preparation course or not.</p>
<p>The numerical features in the dataset are:</p>
<p>Math Score: Represents the marks obtained by the student in the math subject. Reading Score: Represents the marks obtained by the student in the reading subject. Writing Score: Represents the marks obtained by the student in the writing subject. All the scores in the dataset are measured on a scale of 0 to 100.</p>
<p>The dataset provides valuable insights into the performance of students in exams across various subjects. By analyzing this data, we can explore the relationships between different features and understand the factors that influence students’ academic achievements.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    gender              race           parent_education      lunch          
 Length:1000        Length:1000        Length:1000        Length:1000       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
  test_prep           math_score     reading_score    writing_score   
 Length:1000        Min.   :  0.00   Min.   : 17.00   Min.   : 10.00  
 Class :character   1st Qu.: 57.00   1st Qu.: 59.00   1st Qu.: 57.75  
 Mode  :character   Median : 66.00   Median : 70.00   Median : 69.00  
                    Mean   : 66.09   Mean   : 69.17   Mean   : 68.05  
                    3rd Qu.: 77.00   3rd Qu.: 79.00   3rd Qu.: 79.00  
                    Max.   :100.00   Max.   :100.00   Max.   :100.00  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["gender"],"name":[1],"type":["chr"],"align":["left"]},{"label":["race"],"name":[2],"type":["chr"],"align":["left"]},{"label":["parent_education"],"name":[3],"type":["chr"],"align":["left"]},{"label":["lunch"],"name":[4],"type":["chr"],"align":["left"]},{"label":["test_prep"],"name":[5],"type":["chr"],"align":["left"]},{"label":["math_score"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["reading_score"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["writing_score"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"female","2":"group B","3":"bachelor's degree","4":"standard","5":"none","6":"72","7":"72","8":"74"},{"1":"female","2":"group C","3":"some college","4":"standard","5":"completed","6":"69","7":"90","8":"88"},{"1":"female","2":"group B","3":"master's degree","4":"standard","5":"none","6":"90","7":"95","8":"93"},{"1":"male","2":"group A","3":"associate's degree","4":"free/reduced","5":"none","6":"47","7":"57","8":"44"},{"1":"male","2":"group C","3":"some college","4":"standard","5":"none","6":"76","7":"78","8":"75"},{"1":"female","2":"group B","3":"associate's degree","4":"standard","5":"none","6":"71","7":"83","8":"78"},{"1":"female","2":"group B","3":"some college","4":"standard","5":"completed","6":"88","7":"95","8":"92"},{"1":"male","2":"group B","3":"some college","4":"free/reduced","5":"none","6":"40","7":"43","8":"39"},{"1":"male","2":"group D","3":"high school","4":"free/reduced","5":"completed","6":"64","7":"64","8":"67"},{"1":"female","2":"group B","3":"high school","4":"free/reduced","5":"none","6":"38","7":"60","8":"50"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [1,000 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ gender          : chr [1:1000] "female" "female" "female" "male" ...
 $ race            : chr [1:1000] "group B" "group C" "group B" "group A" ...
 $ parent_education: chr [1:1000] "bachelor's degree" "some college" "master's degree" "associate's degree" ...
 $ lunch           : chr [1:1000] "standard" "standard" "standard" "free/reduced" ...
 $ test_prep       : chr [1:1000] "none" "completed" "none" "none" ...
 $ math_score      : num [1:1000] 72 69 90 47 76 71 88 40 64 38 ...
 $ reading_score   : num [1:1000] 72 90 95 57 78 83 95 43 64 60 ...
 $ writing_score   : num [1:1000] 74 88 93 44 75 78 92 39 67 50 ...
 - attr(*, "spec")=
  .. cols(
  ..   gender = col_character(),
  ..   `race/ethnicity` = col_character(),
  ..   `parental level of education` = col_character(),
  ..   lunch = col_character(),
  ..   `test preparation course` = col_character(),
  ..   math = col_double(),
  ..   reading = col_double(),
  ..   writing = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anyNA</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `&lt;scale&gt;` argument of `guides()` cannot be `FALSE`. Use "none" instead as
of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the funModeling package.
  Please report the issue at &lt;https://github.com/pablo14/funModeling/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["var"],"name":[1],"type":["chr"],"align":["left"]},{"label":["frequency"],"name":[2],"type":["int"],"align":["right"]},{"label":["percentage"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["cumulative_perc"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"female","2":"518","3":"51.8","4":"51.8"},{"1":"male","2":"482","3":"48.2","4":"100.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>It can be observed that among the students included, approximately 51.8% of them are female students. This indicates that the majority of the students in the dataset are female.</p>
<p>On the other hand, approximately 48.2% of the students in the dataset are male students. This suggests that male students make up a slightly smaller portion of the total student population compared to female students.</p>
<p>Overall, the dataset represents a relatively balanced distribution in terms of gender, with a slightly higher proportion of female students.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>race)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["var"],"name":[1],"type":["chr"],"align":["left"]},{"label":["frequency"],"name":[2],"type":["int"],"align":["right"]},{"label":["percentage"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["cumulative_perc"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"group C","2":"319","3":"31.9","4":"31.9"},{"1":"group D","2":"262","3":"26.2","4":"58.1"},{"1":"group B","2":"190","3":"19.0","4":"77.1"},{"1":"group E","2":"140","3":"14.0","4":"91.1"},{"1":"group A","2":"89","3":"8.9","4":"100.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>It can be observed that Group C is the most prevalent race/ethnicity among the students. This suggests that a larger number of students in the dataset belong to Group C compared to the other race/ethnicity categories while Group A is the least represented race/ethnicity among the students.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>parent_education)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["var"],"name":[1],"type":["chr"],"align":["left"]},{"label":["frequency"],"name":[2],"type":["int"],"align":["right"]},{"label":["percentage"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["cumulative_perc"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"some college","2":"226","3":"22.6","4":"22.6"},{"1":"associate's degree","2":"222","3":"22.2","4":"44.8"},{"1":"high school","2":"196","3":"19.6","4":"64.4"},{"1":"some high school","2":"179","3":"17.9","4":"82.3"},{"1":"bachelor's degree","2":"118","3":"11.8","4":"94.1"},{"1":"master's degree","2":"59","3":"5.9","4":"100.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Above chart reveal the distribution of parent education levels among the students in the dataset. Out of the total number of students, 226 individuals (22.6%) reported having their parents pursued some college education</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>lunch)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["var"],"name":[1],"type":["chr"],"align":["left"]},{"label":["frequency"],"name":[2],"type":["int"],"align":["right"]},{"label":["percentage"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["cumulative_perc"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"standard","2":"645","3":"64.5","4":"64.5"},{"1":"free/reduced","2":"355","3":"35.5","4":"100.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Standard Price Lunch: 64.5% Approximately 64.5% of the students in the dataset eat lunch at the standard price. This indicates that the majority of the students opt for the standard-priced lunch option.</p>
<p>Free/Reduced Lunch: 35.5% About 35.5% of the students in the dataset eat lunch at a free or reduced price. This suggests that a smaller portion of the students qualify for and choose the free or reduced lunch option.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data,<span class="fu">aes</span>(data<span class="sc">$</span>gender, <span class="at">fill=</span>data<span class="sc">$</span>race))<span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="fu">position_dodge</span>())<span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Ethnic Group distribution by Gender"</span>)<span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Gender"</span>)<span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I have compared the gender with their race type and its interesting to see that the majority of students in the dataset are from group C followed by group D race.</p>
<p>So, keeping all the analysed information in mind i want to conduct the correlation analysis for the variables Math, Reading and Writing scores and see if there is any correlation between the variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">profiling_num</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["variable"],"name":[1],"type":["chr"],"align":["left"]},{"label":["mean"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std_dev"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["variation_coef"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p_01"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["p_05"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["p_25"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["p_50"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["p_75"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["p_95"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["p_99"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["skewness"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["kurtosis"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["iqr"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["range_98"],"name":[15],"type":["chr"],"align":["left"]},{"label":["range_80"],"name":[16],"type":["chr"],"align":["left"]}],"data":[{"1":"math_score","2":"66.089","3":"15.16308","4":"0.2294342","5":"27.99","6":"40.95","7":"57.00","8":"66","9":"77","10":"90.05","11":"98.01","12":"-0.2785166","13":"3.267597","14":"20.00","15":"[27.99, 98.01]","16":"[47, 86]"},{"1":"reading_score","2":"69.169","3":"14.60019","4":"0.2110800","5":"31.99","6":"44.00","7":"59.00","8":"70","9":"79","10":"92.00","11":"100.00","12":"-0.2587157","13":"2.926081","14":"20.00","15":"[31.99, 100]","16":"[51, 87.1]"},{"1":"writing_score","2":"68.054","3":"15.19566","4":"0.2232882","5":"31.98","6":"42.95","7":"57.75","8":"69","9":"79","10":"92.00","11":"100.00","12":"-0.2890096","13":"2.960808","14":"21.25","15":"[31.98, 100]","16":"[48, 87]"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_num</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on our hypothesis that the math exam scores of students are positively associated with their reading and writing scores, the findings from the profiling analysis and also plot chart provide evidence supporting this hypothesis. The average scores for math, reading, and writing are relatively close, indicating a positive association between these subjects.</p>
<section id="math-scores-based-on-reading-and-writing-scores" class="level2">
<h2 class="anchored" data-anchor-id="math-scores-based-on-reading-and-writing-scores">Math Scores based on Reading and Writing Scores</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># scatter plot</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> reading_score, <span class="at">y =</span> writing_score, <span class="at">color =</span> math_score)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Reading Score"</span>, <span class="at">y =</span> <span class="st">"Writing Score"</span>, </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores based on Reading and Writing Scores"</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="math-scores-based-on-gender" class="level2">
<h2 class="anchored" data-anchor-id="math-scores-based-on-gender">Math Scores based on Gender</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by gender</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> gender, <span class="at">y =</span> mean_math_score)) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Gender"</span>, <span class="at">y =</span> <span class="st">"Mean Math Score"</span>, </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Mean Math Scores by Gender"</span>) <span class="sc">+</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The chart reveals that the mean math score for males is approximately 68.73, indicating a relatively higher average performance in math compared to females . On the other hand,females have a mean math score of around 63.63, suggesting a slightly lower average performance in math compared to males . These findings highlight a gender-based difference in math scores, with males demonstrating a higher average math score compared to females.</p>
</section>
<section id="math-scores-based-on-race" class="level2">
<h2 class="anchored" data-anchor-id="math-scores-based-on-race">Math Scores based on Race</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by race</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(race) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Race"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>, </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Race"</span>) <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> mean_math_score, </span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Mean: "</span>, <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>))),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>These findings highlight the variations in math scores across different race categories, with Group E demonstrating the highest average score and Group A showing the lowest average score performance.</p>
</section>
<section id="math-scores-based-on-parents-education-level" class="level2">
<h2 class="anchored" data-anchor-id="math-scores-based-on-parents-education-level">Math Scores based on Parents Education Level</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> parent_education, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Parental Education Level"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Parental Education Level"</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Even thought there is a little difference in the math scores there is not significant difference based on their parents education level</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by lunch type</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lunch) <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> lunch, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Lunch Type"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Lunch Type"</span>) <span class="sc">+</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> lunch, <span class="at">y =</span> mean_math_score,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Mean: "</span>, <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>))),</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It is interesting to see the math score of students based on their lunch type. Students how are taking standard meal are performing better at math as compared to people taking free or reduced lunch option.</p>
</section>
<section id="correlation-matrix-of-math-reading-and-writing-scores" class="level2">
<h2 class="anchored" data-anchor-id="correlation-matrix-of-math-reading-and-writing-scores">Correlation Matrix of Math, Reading, and Writing Scores</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>num_data <span class="ot">&lt;-</span> data[, <span class="fu">c</span>( <span class="st">"math_score"</span>, <span class="st">"reading_score"</span>, <span class="st">"writing_score"</span>)]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>m<span class="ot">&lt;-</span><span class="fu">cor</span>(num_data)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>m</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              math_score reading_score writing_score
math_score     1.0000000     0.8175797     0.8026420
reading_score  0.8175797     1.0000000     0.9545981
writing_score  0.8026420     0.9545981     1.0000000</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(m, <span class="at">method=</span><span class="st">"circle"</span>, <span class="at">type=</span><span class="st">'upper'</span>, <span class="at">tl.cex=</span><span class="fl">0.8</span>, <span class="at">tl.col =</span> <span class="st">'black'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The correlation analysis reveals interesting insights into the relationships between math scores, reading scores, and writing scores. The strong positive correlation coefficient of 0.8176 between math_score and reading_score suggests that students who excel in math also tend to perform well in reading. Similarly, the high correlation coefficient of 0.8026 between math_score and writing_score indicates a strong positive association, indicating that students who demonstrate proficiency in math often display strong writing skills as well. Furthermore, the very high correlation coefficient of 0.9546 between reading_score and writing_score highlights a robust positive relationship, indicating that students who excel in reading are highly likely to excel in writing.</p>
<p>Taken together, these findings provide substantial evidence supporting our hypothesis that math exam scores are positively associated with both reading and writing scores. These results suggest that students who demonstrate proficiency in one subject area are more likely to excel in the other subjects as well, reinforcing the idea of a positive relationship between math scores and reading/writing scores.</p>
<p>To address the assumption of homogeneous variance in the math scores between two groups, we can perform a statistical test before deciding which t-test to use (Student’s t-test or Welch’s t-test)</p>
<section id="statistical-analysis---homogeneity-of-variance-test" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis---homogeneity-of-variance-test">Statistical Analysis - Homogeneity of Variance Test</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>var_test <span class="ot">&lt;-</span> <span class="fu">bartlett.test</span>(math_score <span class="sc">~</span> gender, <span class="at">data =</span> data)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (var_test<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>) {</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(math_score <span class="sc">~</span> gender, <span class="at">data =</span> data, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(math_score <span class="sc">~</span> gender, <span class="at">data =</span> data, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the t-test results</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  math_score by gender
t = -5.3832, df = 998, p-value = 9.12e-08
alternative hypothesis: true difference in means between group female and group male is not equal to 0
95 percent confidence interval:
 -6.952285 -3.237737
sample estimates:
mean in group female   mean in group male 
            63.63320             68.72822 </code></pre>
</div>
</div>
<p>The t-statistic value is -5.3832 with a degrees of freedom (df) value of 998. The p-value is 9.12e-08, which is less than the significance level of 0.05. This suggests strong evidence to reject the null hypothesis. Therefore, we can conclude that there is a significant difference in the mean math scores between the female and male groups.</p>
<p>The sample mean for the female group is 63.63320, while the sample mean for the male group is 68.72822. This indicates that, on average, male students have higher math scores compared to female students.</p>
<p>In your case, the p-value of the Bartlett’s test is less than 0.05 (9.12e-08), indicating that the variances of math scores between the female and male groups are significantly different. Therefore, you use Welch’s t-test (var.equal = FALSE) to compare the means of the two groups.</p>
</section>
<section id="welchs-t-test" class="level3">
<h3 class="anchored" data-anchor-id="welchs-t-test">Welch’s T-Test</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Statistical Analysis</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(math_score <span class="sc">~</span> gender, <span class="at">data =</span> data, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the t-test results</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  math_score by gender
t = -5.398, df = 997.98, p-value = 8.421e-08
alternative hypothesis: true difference in means between group female and group male is not equal to 0
95 percent confidence interval:
 -6.947209 -3.242813
sample estimates:
mean in group female   mean in group male 
            63.63320             68.72822 </code></pre>
</div>
</div>
<p>The Welch’s t-test was performed to examine the difference in mean math scores between female and male students. The results indicate a significant disparity in math performance between the two genders. On average, male students outperformed female students in math, as evidenced by a higher mean math score. The t-value of -5.3832, with 998 degrees of freedom, and an extremely small p-value of 9.12e-08 provide strong evidence against the null hypothesis. The 95% confidence interval (-6.952285 to -3.237737) further supports the conclusion of a significant difference in math scores between males and females. These findings highlight a gender-based discrepancy, with male students demonstrating superior math performance compared to their female counterparts.</p>
</section>
</section>
</section>
<section id="linear-regression-models" class="level1">
<h1>Linear Regression Models</h1>
<p>Before performing the Linear Regression im converting the parent education level as ordinal variable with lower education as lower number and higher education as higher number.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert parent's level of education to an ordinal variable</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>parent_education <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>parent_education, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"some high school"</span>, <span class="st">"high school"</span>, <span class="st">"some college"</span>, <span class="st">"associate's degree"</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"bachelor's degree"</span>, <span class="st">"master's degree"</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>))</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify the ordinal variable</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>parent_education)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 6 levels "1","2","3","4",..: 5 3 6 4 3 4 3 3 2 2 ...</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the models without train and test data splitting</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> reading_score <span class="sc">+</span> writing_score, <span class="at">data =</span> data)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = math_score ~ reading_score + writing_score, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-23.8779  -6.1750   0.2693   6.0184  24.8727 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    7.52409    1.32823   5.665 1.93e-08 ***
reading_score  0.60129    0.06304   9.538  &lt; 2e-16 ***
writing_score  0.24942    0.06057   4.118 4.14e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.667 on 997 degrees of freedom
Multiple R-squared:  0.674, Adjusted R-squared:  0.6733 
F-statistic:  1031 on 2 and 997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> reading_score <span class="sc">*</span> gender, <span class="at">data =</span> data)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = math_score ~ reading_score * gender, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-23.0844  -4.2217  -0.0883   4.0897  18.4037 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              -7.49742    1.48584  -5.046 5.36e-07 ***
reading_score             0.97965    0.02007  48.800  &lt; 2e-16 ***
gendermale               16.48372    2.06757   7.973 4.24e-15 ***
reading_score:gendermale -0.06719    0.02940  -2.285   0.0225 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.563 on 996 degrees of freedom
Multiple R-squared:  0.8132,    Adjusted R-squared:  0.8127 
F-statistic:  1446 on 3 and 996 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> writing_score <span class="sc">*</span> gender, <span class="at">data =</span> data)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = math_score ~ writing_score * gender, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-19.373  -3.989   0.025   4.199  18.521 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              -5.99575    1.37398  -4.364 1.41e-05 ***
writing_score             0.96083    0.01858  51.727  &lt; 2e-16 ***
gendermale               17.28203    1.90102   9.091  &lt; 2e-16 ***
writing_score:gendermale -0.05354    0.02748  -1.948   0.0517 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.27 on 996 degrees of freedom
Multiple R-squared:  0.8295,    Adjusted R-squared:  0.829 
F-statistic:  1616 on 3 and 996 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> ., <span class="at">data =</span> data)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = math_score ~ ., data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.4995  -3.6824   0.1218   3.3932  14.1178 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -11.05233    1.18049  -9.362  &lt; 2e-16 ***
gendermale         13.24045    0.37193  35.599  &lt; 2e-16 ***
racegroup B         0.83537    0.69230   1.207   0.2279    
racegroup C         0.17823    0.64899   0.275   0.7837    
racegroup D         0.09840    0.67014   0.147   0.8833    
racegroup E         5.07770    0.73714   6.888 1.00e-11 ***
parent_education2   0.01557    0.55859   0.028   0.9778    
parent_education3  -0.15190    0.54678  -0.278   0.7812    
parent_education4  -0.55216    0.54989  -1.004   0.3156    
parent_education5  -1.59906    0.65701  -2.434   0.0151 *  
parent_education6  -2.40823    0.82760  -2.910   0.0037 ** 
lunchstandard       3.21271    0.37420   8.585  &lt; 2e-16 ***
test_prepnone       3.50227    0.39658   8.831  &lt; 2e-16 ***
reading_score       0.26351    0.04205   6.266 5.52e-10 ***
writing_score       0.70156    0.04352  16.120  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.362 on 985 degrees of freedom
Multiple R-squared:  0.8767,    Adjusted R-squared:  0.875 
F-statistic: 500.3 on 14 and 985 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Model 1: math_score ~ reading_score + writing_score</p>
<p>Both reading_score and writing_score have statistically significant coefficients (p &lt; 0.001). The positive estimates suggest that an increase in reading_score and writing_score is associated with an increase in math_score. The adjusted R-squared value of 0.6733 indicates that the model explains approximately 67.33% of the variance in math_score.</p>
<p>Model 2: math_score ~ reading_score * gender</p>
<p>The coefficient for reading_score is statistically significant (p &lt; 0.001) with a positive estimate, indicating that an increase in reading_score is associated with a higher math_score. The coefficient for gender_male is statistically significant (p &lt; 0.001) with a positive estimate, indicating that, on average, male students have higher math scores than female students. The interaction term reading_score:gender_male is statistically significant (p = 0.0225) and negative, suggesting that the positive effect of reading_score on math_score is slightly weaker for male students compared to female students.</p>
<p>Model 3: math_score ~ writing_score * gender</p>
<p>The coefficient for writing_score is statistically significant (p &lt; 0.001) with a positive estimate, indicating that an increase in writing_score is associated with a higher math_score. The coefficient for gender_male is statistically significant (p &lt; 0.001) with a positive estimate, indicating that, on average, male students have higher math scores than female students. The interaction term writing_score:gender_male has a p-value of 0.0517, which is marginally significant. It suggests that there might be a difference in the effect of writing_score on math_score between male and female students, although further investigation is needed to confirm its significance.</p>
<p>Model 4: This model includes all available predictor variables.</p>
<p>Several variables have statistically significant coefficients, including gender, race (specifically race group E), parent’s education level (bachelor’s degree and master’s degree), lunch type (standard), test preparation (none), reading_score, and writing_score.</p>
<p>The adjusted R-squared value of 0.875 indicates that the model explains approximately 87.5% of the variance in math_score.</p>
<p>Overall, the results from these models provide evidence supporting the hypothesis that math exam scores are positively associated with students’ reading and writing scores. Gender appears to have a significant influence on math scores, with male students generally having higher scores than female students. Other factors such as race, parent’s education level, lunch type, and test preparation also show significant associations with math scores.</p>
<p>Based on these conclusions, we can see that all four models show significant associations between the predictors and the math score. The fourth model, which includes multiple predictors, provides the highest adjusted R-squared value, indicating a better fit to the data. However, it’s important to note that including more predictors may increase the risk of overfitting the model.</p>
<p>Therefore, Im choosing model 3 which provides a good fit to the data and explains a significant amount of variance in the math scores.</p>
<section id="model-comparison-using-aic-and-bic" class="level3">
<h3 class="anchored" data-anchor-id="model-comparison-using-aic-and-bic">Model Comparison using AIC and BIC</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model1,model2, model3, model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["AIC"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"4","2":"7161.804","_rn_":"model1"},{"1":"5","2":"6606.765","_rn_":"model2"},{"1":"5","2":"6515.346","_rn_":"model3"},{"1":"16","2":"6213.415","_rn_":"model4"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(model1,model2, model3, model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"4","2":"7181.435","_rn_":"model1"},{"1":"5","2":"6631.304","_rn_":"model2"},{"1":"5","2":"6539.885","_rn_":"model3"},{"1":"16","2":"6291.939","_rn_":"model4"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Based on these results, we can make the following conclusions:</p>
<p>The models differ in the number of degrees of freedom, which is determined by the number of predictors included in each model.</p>
<p>The lower the BIC and AIC values, the better the model fits the data while considering model complexity.</p>
<p>Comparing the BIC values, Model 4 has the lowest BIC (6291.939), followed by Model 3 (6539.885), Model 2 (6631.304), and Model 1 (7181.435).</p>
<p>Comparing the AIC values, Model 4 has the lowest AIC (6213.415), followed by Model 3 (6515.346), Model 2 (6606.765), and Model 1 (7161.804).</p>
<p>Based on both the BIC and AIC criteria, Model 4 is the preferred model among Model 1, Model 2, Model 3, and Model 4. It exhibits the lowest values for both BIC and AIC, indicating a better trade-off between model fit and complexity.</p>
<p>Even though my hypothesis is valid (Model 3) Based on the AIC and BIC scores im choosing model4 to perform diagnostics.</p>
</section>
<section id="diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics">Diagnostics</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-22-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-22-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="FinalProject_Thrishul_files/figure-html/unnamed-chunk-22-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on the interpretation of the diagnostic plots for the model4, it appears that the assumptions of the linear regression model are reasonably met.</p>
<p>Residuals vs Fitted:</p>
<p>The residuals vs.&nbsp;fitted plot shows a random scatter of all residuals near to the horizontal line at zero. This suggests that there is almost no systematic pattern or trend in the residuals. It indicates that the linear regression model adequately captures the relationship between the predictors and the response variable.</p>
<p>Normal Q-Q:</p>
<p>The normal quantile-quantile (Q-Q) plot displays the residuals following a roughly straight line, closely aligned with the theoretical diagonal line. This indicates that the residuals approximately follow a normal distribution. Therefore, the assumption of normality for the residuals is reasonably satisfied.</p>
<p>Scale-Location:</p>
<p>The scale-location plot reveals an approximately constant spread or dispersion of residuals across the range of predicted values. The points on the plot are randomly scattered around a horizontal line, indicating homoscedasticity. This suggests that the assumption of constant variance for the residuals is met.</p>
<p>Residuals vs Leverage:</p>
<p>The residuals vs.&nbsp;leverage plot shows that most of the data points fall within the dashed lines, indicating that there are less influential observations with high leverage. Therefore, there are less influential outliers that significantly affect the model.</p>
<p>Overall, based on these diagnostic plots, the model model3 appears to be a reasonable and valid representation of the relationship between the predictors and the response variable. The assumptions of linearity, normality of residuals, constant variance, and absence of influential outliers are reasonably met.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Please cite as: </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model1, model2, model3, model4, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
===================================================================================================================================
                                                                    Dependent variable:                                            
                         ----------------------------------------------------------------------------------------------------------
                                                                         math_score                                                
                                    (1)                        (2)                        (3)                        (4)           
-----------------------------------------------------------------------------------------------------------------------------------
reading_score                     0.601***                   0.980***                                             0.264***         
                                  (0.063)                    (0.020)                                               (0.042)         
                                                                                                                                   
writing_score                     0.249***                                              0.961***                  0.702***         
                                  (0.061)                                               (0.019)                    (0.044)         
                                                                                                                                   
gendermale                                                  16.484***                  17.282***                  13.240***        
                                                             (2.068)                    (1.901)                    (0.372)         
                                                                                                                                   
reading_score:gendermale                                     -0.067**                                                              
                                                             (0.029)                                                               
                                                                                                                                   
writing_score:gendermale                                                                -0.054*                                    
                                                                                        (0.027)                                    
                                                                                                                                   
racegroup B                                                                                                         0.835          
                                                                                                                   (0.692)         
                                                                                                                                   
racegroup C                                                                                                         0.178          
                                                                                                                   (0.649)         
                                                                                                                                   
racegroup D                                                                                                         0.098          
                                                                                                                   (0.670)         
                                                                                                                                   
racegroup E                                                                                                       5.078***         
                                                                                                                   (0.737)         
                                                                                                                                   
parent_education2                                                                                                   0.016          
                                                                                                                   (0.559)         
                                                                                                                                   
parent_education3                                                                                                  -0.152          
                                                                                                                   (0.547)         
                                                                                                                                   
parent_education4                                                                                                  -0.552          
                                                                                                                   (0.550)         
                                                                                                                                   
parent_education5                                                                                                 -1.599**         
                                                                                                                   (0.657)         
                                                                                                                                   
parent_education6                                                                                                 -2.408***        
                                                                                                                   (0.828)         
                                                                                                                                   
lunchstandard                                                                                                     3.213***         
                                                                                                                   (0.374)         
                                                                                                                                   
test_prepnone                                                                                                     3.502***         
                                                                                                                   (0.397)         
                                                                                                                                   
Constant                          7.524***                  -7.497***                  -5.996***                 -11.052***        
                                  (1.328)                    (1.486)                    (1.374)                    (1.180)         
                                                                                                                                   
-----------------------------------------------------------------------------------------------------------------------------------
Observations                       1,000                      1,000                      1,000                      1,000          
R2                                 0.674                      0.813                      0.830                      0.877          
Adjusted R2                        0.673                      0.813                      0.829                      0.875          
Residual Std. Error           8.667 (df = 997)           6.563 (df = 996)           6.270 (df = 996)          5.362 (df = 985)     
F Statistic              1,030.553*** (df = 2; 997) 1,445.519*** (df = 3; 996) 1,615.677*** (df = 3; 996) 500.291*** (df = 14; 985)
===================================================================================================================================
Note:                                                                                                   *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Model 1 includes only the reading and writing scores as predictors. The results indicate that both reading_score and writing_score have a significant positive effect on math_score (p &lt; 0.01). For every one-unit increase in reading score, the math score is expected to increase by 0.601 units. Similarly, a one-unit increase in writing score is associated with a 0.249 unit increase in math score. These findings support my hypothesis that strong reading and writing skills positively contribute to math performance.</p>
<p>In Model 2, I added the gender variable to examine the potential impact of gender on math scores. The coefficient for gender_male is statistically significant (p &lt; 0.01), suggesting that being male is associated with higher math scores. Specifically, males are expected to have math scores that are 16.484 units higher than females. This finding supports my hypothesis that gender may play a role in math performance.</p>
<p>Building upon Model 2, Model 3 introduces an interaction term between writing_score and gender to explore whether the relationship between writing skills and math scores differs between males and females. The interaction term is marginally significant (p &lt; 0.1), indicating a potential difference in the relationship. This suggests that the impact of writing skills on math scores may vary between genders. This finding aligns with my hypothesis, which proposed that the relationship between writing skills and math performance might differ based on gender.</p>
<p>Finally, Model 4 expands the analysis to include additional predictors such as race and parent’s education level. The results reveal several significant effects. Students from race group E are expected to have math scores that are 5.078 units higher compared to the reference group (race group A). Additionally, parent’s education level shows some significant associations. For instance, students whose parents have completed education level 5 (highest level) are expected to have math scores 1.599 units lower than those whose parents have education level 1 (lowest level). These findings provide further evidence that race and parent’s education may impact math performance.</p>
<p>In summary, the regression models provide support for my hypothesis that reading and writing skills, gender, race, and parent’s education level are influential factors in math performance. The findings indicate that reading and writing skills positively influence math scores, while gender, race, and parent’s education level also play a role.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>In conclusion, this research aimed to investigate the factors influencing math performance among a sample of students. The analysis considered several variables, including reading and writing scores, gender, race, and parent’s education level, to understand their impact on math scores.</p>
<p>The regression models provided valuable insights into the relationships between these variables and math performance. The findings consistently demonstrated the positive influence of reading and writing skills on math scores, supporting the idea that strong literacy skills contribute to overall academic achievement.</p>
<p>Furthermore, gender was found to be a significant factor, with males exhibiting higher math scores compared to females. This suggests that gender differences may exist in math performance and highlights the importance of exploring gender-related factors in educational settings.</p>
<p>The inclusion of race as a predictor revealed that students from racegroup E tended to have higher math scores compared to the reference group. This finding underscores the need to consider the influence of race or cultural background when examining educational outcomes, as it can shed light on disparities and potential areas for targeted interventions.</p>
<p>The impact of parent’s education level on math performance was also explored. The results showed that higher parent’s education levels were associated with lower math scores, suggesting a complex relationship between parental influence and academic achievement. Further research is warranted to better understand the underlying mechanisms and potential interventions to support students from diverse educational backgrounds.</p>
</section>
<section id="bibliography" class="level1">
<h1>Bibliography</h1>
<p>Dataset : “Students Performance in Exams” Dataset. Retrieved from https://www.kaggle.com/datasets/spscientist/students-performance-in-exams</p>
<p>Johnson, R. A. (2010). Applied Multivariate Statistical Analysis (6th ed.). Pearson Education.</p>
<p>Field, A. (2013). Discovering Statistics Using R. SAGE Publications Ltd.</p>
<p>Wickham, H. (2016). ggplot2: Elegant Graphics for Data Analysis. Springer.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb49" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Project"</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Thrishul Pola"</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Final Project"</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "5/2/2023"</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - Final_Project</span></span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - Thrishul</span></span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a><span class="fu"># Research Question</span></span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a>Why do some students have higher math exam scores?</span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis</span></span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-25"><a href="#cb49-25" aria-hidden="true" tabindex="-1"></a>We hypothesize that math exam scores are positively associated with students' reading and writing scores.</span>
<span id="cb49-26"><a href="#cb49-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-27"><a href="#cb49-27" aria-hidden="true" tabindex="-1"></a>The math exam scores of male students are higher than those of female students.</span>
<span id="cb49-28"><a href="#cb49-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-29"><a href="#cb49-29" aria-hidden="true" tabindex="-1"></a>Numerous studies have indicated a positive relationship between reading, writing, and math abilities. The skills required for success in these subjects often overlap, as they involve critical thinking, problem-solving, and comprehension of complex information. For example, research by Smith and Johnson found that students with higher reading and writing proficiency tend to exhibit better math performance.</span>
<span id="cb49-30"><a href="#cb49-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-31"><a href="#cb49-31" aria-hidden="true" tabindex="-1"></a>Additionally, cognitive theories, such as the aptitude-treatment interaction (ATI) framework proposed by Cronbach and Snow, support the idea that students who possess strong language skills, including reading and writing, are better equipped to understand and apply mathematical concepts. Language acts as a cognitive tool that aids in the comprehension and reasoning required for solving math problems.</span>
<span id="cb49-32"><a href="#cb49-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-33"><a href="#cb49-33" aria-hidden="true" tabindex="-1"></a><span class="fu">## Importing Libraries</span></span>
<span id="cb49-34"><a href="#cb49-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-37"><a href="#cb49-37" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-38"><a href="#cb49-38" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb49-39"><a href="#cb49-39" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb49-40"><a href="#cb49-40" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb49-41"><a href="#cb49-41" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb49-42"><a href="#cb49-42" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fBasics) </span>
<span id="cb49-43"><a href="#cb49-43" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb49-44"><a href="#cb49-44" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(funModeling)</span>
<span id="cb49-45"><a href="#cb49-45" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb49-46"><a href="#cb49-46" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb49-47"><a href="#cb49-47" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb49-48"><a href="#cb49-48" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb49-49"><a href="#cb49-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-50"><a href="#cb49-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-51"><a href="#cb49-51" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reading and Analysing Dataset</span></span>
<span id="cb49-54"><a href="#cb49-54" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-55"><a href="#cb49-55" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/S.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb49-56"><a href="#cb49-56" aria-hidden="true" tabindex="-1"></a>names_columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"gender"</span>,<span class="st">"race"</span>,<span class="st">"parent_education"</span>,<span class="st">"lunch"</span>,<span class="st">"test_prep"</span>,<span class="st">"math_score"</span>,<span class="st">"reading_score"</span>,<span class="st">"writing_score"</span>)</span>
<span id="cb49-57"><a href="#cb49-57" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data) <span class="ot">&lt;-</span> names_columns</span>
<span id="cb49-58"><a href="#cb49-58" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-59"><a href="#cb49-59" aria-hidden="true" tabindex="-1"></a><span class="fu"># Dataset Description</span></span>
<span id="cb49-60"><a href="#cb49-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-61"><a href="#cb49-61" aria-hidden="true" tabindex="-1"></a>The dataset contains information on exam scores for students at a public school. The data is collected from a single public school and is not specified for any particular year.</span>
<span id="cb49-62"><a href="#cb49-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-63"><a href="#cb49-63" aria-hidden="true" tabindex="-1"></a>The "Students Performance in Exams" dataset contains information about the marks obtained by students in different subjects. The dataset consists of 1000 rows and 8 features.</span>
<span id="cb49-64"><a href="#cb49-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-65"><a href="#cb49-65" aria-hidden="true" tabindex="-1"></a>The categorical features in the dataset include:</span>
<span id="cb49-66"><a href="#cb49-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-67"><a href="#cb49-67" aria-hidden="true" tabindex="-1"></a>Gender: Indicates whether the student is female or male.</span>
<span id="cb49-68"><a href="#cb49-68" aria-hidden="true" tabindex="-1"></a>Race/Ethnicity: As the race is a very sensitive topic the person who collected this data have hidden the actual race categories. The race category represents the group to which the student belongs, categorized as Group A, Group B, Group C, Group D, or Group E.</span>
<span id="cb49-69"><a href="#cb49-69" aria-hidden="true" tabindex="-1"></a>Parental Level of Education: Reflects the educational level of the student's parents, such as associate's degree, bachelor's degree, high school, etc.</span>
<span id="cb49-70"><a href="#cb49-70" aria-hidden="true" tabindex="-1"></a>Lunch: Specifies the type of lunch provided to the student, categorized as either free/reduced or standard.</span>
<span id="cb49-71"><a href="#cb49-71" aria-hidden="true" tabindex="-1"></a>Test Preparation Course: Indicates whether the student completed a test preparation course or not.</span>
<span id="cb49-72"><a href="#cb49-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-73"><a href="#cb49-73" aria-hidden="true" tabindex="-1"></a>The numerical features in the dataset are:</span>
<span id="cb49-74"><a href="#cb49-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-75"><a href="#cb49-75" aria-hidden="true" tabindex="-1"></a>Math Score: Represents the marks obtained by the student in the math subject.</span>
<span id="cb49-76"><a href="#cb49-76" aria-hidden="true" tabindex="-1"></a>Reading Score: Represents the marks obtained by the student in the reading subject.</span>
<span id="cb49-77"><a href="#cb49-77" aria-hidden="true" tabindex="-1"></a>Writing Score: Represents the marks obtained by the student in the writing subject.</span>
<span id="cb49-78"><a href="#cb49-78" aria-hidden="true" tabindex="-1"></a>All the scores in the dataset are measured on a scale of 0 to 100.</span>
<span id="cb49-79"><a href="#cb49-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-80"><a href="#cb49-80" aria-hidden="true" tabindex="-1"></a>The dataset provides valuable insights into the performance of students in exams across various subjects. By analyzing this data, we can explore the relationships between different features and understand the factors that influence students' academic achievements.</span>
<span id="cb49-83"><a href="#cb49-83" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-84"><a href="#cb49-84" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span>
<span id="cb49-85"><a href="#cb49-85" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data, <span class="dv">10</span>)</span>
<span id="cb49-86"><a href="#cb49-86" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-89"><a href="#cb49-89" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-90"><a href="#cb49-90" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span>
<span id="cb49-91"><a href="#cb49-91" aria-hidden="true" tabindex="-1"></a><span class="fu">anyNA</span>(data)</span>
<span id="cb49-92"><a href="#cb49-92" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-93"><a href="#cb49-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-96"><a href="#cb49-96" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-97"><a href="#cb49-97" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>gender)</span>
<span id="cb49-98"><a href="#cb49-98" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-99"><a href="#cb49-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-100"><a href="#cb49-100" aria-hidden="true" tabindex="-1"></a>It can be observed that among the students included, approximately 51.8% of them are female students. This indicates that the majority of the students in the dataset are female.</span>
<span id="cb49-101"><a href="#cb49-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-102"><a href="#cb49-102" aria-hidden="true" tabindex="-1"></a>On the other hand, approximately 48.2% of the students in the dataset are male students. This suggests that male students make up a slightly smaller portion of the total student population compared to female students.</span>
<span id="cb49-103"><a href="#cb49-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-104"><a href="#cb49-104" aria-hidden="true" tabindex="-1"></a>Overall, the dataset represents a relatively balanced distribution in terms of gender, with a slightly higher proportion of female students.</span>
<span id="cb49-105"><a href="#cb49-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-108"><a href="#cb49-108" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-109"><a href="#cb49-109" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>race)</span>
<span id="cb49-110"><a href="#cb49-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-111"><a href="#cb49-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-112"><a href="#cb49-112" aria-hidden="true" tabindex="-1"></a>It can be observed that Group C is the most prevalent race/ethnicity among the students. This suggests that a larger number of students in the dataset belong to Group C compared to the other race/ethnicity categories while  Group A is the least represented race/ethnicity among the students.</span>
<span id="cb49-113"><a href="#cb49-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-116"><a href="#cb49-116" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-117"><a href="#cb49-117" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>parent_education)</span>
<span id="cb49-118"><a href="#cb49-118" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-119"><a href="#cb49-119" aria-hidden="true" tabindex="-1"></a>Above chart reveal the distribution of parent education levels among the students in the dataset. Out of the total number of students, 226 individuals (22.6%) reported having their parents pursued some college education</span>
<span id="cb49-120"><a href="#cb49-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-123"><a href="#cb49-123" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-124"><a href="#cb49-124" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(data<span class="sc">$</span>lunch)</span>
<span id="cb49-125"><a href="#cb49-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-126"><a href="#cb49-126" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-127"><a href="#cb49-127" aria-hidden="true" tabindex="-1"></a>Standard Price Lunch: 64.5%</span>
<span id="cb49-128"><a href="#cb49-128" aria-hidden="true" tabindex="-1"></a>Approximately 64.5% of the students in the dataset eat lunch at the standard price. This indicates that the majority of the students opt for the standard-priced lunch option.</span>
<span id="cb49-129"><a href="#cb49-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-130"><a href="#cb49-130" aria-hidden="true" tabindex="-1"></a>Free/Reduced Lunch: 35.5%</span>
<span id="cb49-131"><a href="#cb49-131" aria-hidden="true" tabindex="-1"></a>About 35.5% of the students in the dataset eat lunch at a free or reduced price. This suggests that a smaller portion of the students qualify for and choose the free or reduced lunch option.</span>
<span id="cb49-132"><a href="#cb49-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-135"><a href="#cb49-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-136"><a href="#cb49-136" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data,<span class="fu">aes</span>(data<span class="sc">$</span>gender, <span class="at">fill=</span>data<span class="sc">$</span>race))<span class="sc">+</span></span>
<span id="cb49-137"><a href="#cb49-137" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="fu">position_dodge</span>())<span class="sc">+</span></span>
<span id="cb49-138"><a href="#cb49-138" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Ethnic Group distribution by Gender"</span>)<span class="sc">+</span></span>
<span id="cb49-139"><a href="#cb49-139" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Gender"</span>)<span class="sc">+</span></span>
<span id="cb49-140"><a href="#cb49-140" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Frequency"</span>)</span>
<span id="cb49-141"><a href="#cb49-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-142"><a href="#cb49-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-143"><a href="#cb49-143" aria-hidden="true" tabindex="-1"></a>I have compared the gender with their race type and its interesting to see that the majority of students in the dataset are from group C followed by group D race.</span>
<span id="cb49-144"><a href="#cb49-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-145"><a href="#cb49-145" aria-hidden="true" tabindex="-1"></a>So, keeping all the analysed information in mind i want to conduct the correlation analysis for the variables Math, Reading and Writing scores and see if there is any correlation between the variables.</span>
<span id="cb49-146"><a href="#cb49-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-149"><a href="#cb49-149" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-150"><a href="#cb49-150" aria-hidden="true" tabindex="-1"></a><span class="fu">profiling_num</span>(data)</span>
<span id="cb49-151"><a href="#cb49-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-152"><a href="#cb49-152" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_num</span>(data)</span>
<span id="cb49-153"><a href="#cb49-153" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-154"><a href="#cb49-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-155"><a href="#cb49-155" aria-hidden="true" tabindex="-1"></a>Based on our hypothesis that the math exam scores of students are positively associated with their reading and writing scores, the findings from the profiling analysis and also plot chart provide evidence supporting this hypothesis. The average scores for math, reading, and writing are relatively close, indicating a positive association between these subjects.</span>
<span id="cb49-156"><a href="#cb49-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-157"><a href="#cb49-157" aria-hidden="true" tabindex="-1"></a><span class="fu">## Math Scores based on Reading and Writing Scores</span></span>
<span id="cb49-158"><a href="#cb49-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-161"><a href="#cb49-161" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-162"><a href="#cb49-162" aria-hidden="true" tabindex="-1"></a><span class="co"># scatter plot</span></span>
<span id="cb49-163"><a href="#cb49-163" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> reading_score, <span class="at">y =</span> writing_score, <span class="at">color =</span> math_score)) <span class="sc">+</span></span>
<span id="cb49-164"><a href="#cb49-164" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb49-165"><a href="#cb49-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Reading Score"</span>, <span class="at">y =</span> <span class="st">"Writing Score"</span>, </span>
<span id="cb49-166"><a href="#cb49-166" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores based on Reading and Writing Scores"</span>) <span class="sc">+</span></span>
<span id="cb49-167"><a href="#cb49-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb49-168"><a href="#cb49-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-169"><a href="#cb49-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-170"><a href="#cb49-170" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-171"><a href="#cb49-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-172"><a href="#cb49-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-173"><a href="#cb49-173" aria-hidden="true" tabindex="-1"></a><span class="fu">## Math Scores based on Gender</span></span>
<span id="cb49-176"><a href="#cb49-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-177"><a href="#cb49-177" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by gender</span></span>
<span id="cb49-178"><a href="#cb49-178" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb49-179"><a href="#cb49-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender) <span class="sc">%&gt;%</span></span>
<span id="cb49-180"><a href="#cb49-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb49-181"><a href="#cb49-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-182"><a href="#cb49-182" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb49-183"><a href="#cb49-183" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> gender, <span class="at">y =</span> mean_math_score)) <span class="sc">+</span></span>
<span id="cb49-184"><a href="#cb49-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb49-185"><a href="#cb49-185" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Gender"</span>, <span class="at">y =</span> <span class="st">"Mean Math Score"</span>, </span>
<span id="cb49-186"><a href="#cb49-186" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Mean Math Scores by Gender"</span>) <span class="sc">+</span></span>
<span id="cb49-187"><a href="#cb49-187" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb49-188"><a href="#cb49-188" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span>
<span id="cb49-189"><a href="#cb49-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-190"><a href="#cb49-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-191"><a href="#cb49-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-192"><a href="#cb49-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-193"><a href="#cb49-193" aria-hidden="true" tabindex="-1"></a>The chart reveals that the mean math score for males is approximately 68.73, indicating a relatively higher average performance in math compared to females . On the other hand,females have a mean math score of around 63.63, suggesting a slightly lower average performance in math compared to males . These findings highlight a gender-based difference in math scores, with males demonstrating a higher average math score compared to females.</span>
<span id="cb49-194"><a href="#cb49-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-195"><a href="#cb49-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-196"><a href="#cb49-196" aria-hidden="true" tabindex="-1"></a><span class="fu">## Math Scores based on Race</span></span>
<span id="cb49-199"><a href="#cb49-199" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-200"><a href="#cb49-200" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by race</span></span>
<span id="cb49-201"><a href="#cb49-201" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb49-202"><a href="#cb49-202" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(race) <span class="sc">%&gt;%</span></span>
<span id="cb49-203"><a href="#cb49-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb49-204"><a href="#cb49-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-205"><a href="#cb49-205" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb49-206"><a href="#cb49-206" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb49-207"><a href="#cb49-207" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb49-208"><a href="#cb49-208" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Race"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>, </span>
<span id="cb49-209"><a href="#cb49-209" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Race"</span>) <span class="sc">+</span></span>
<span id="cb49-210"><a href="#cb49-210" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb49-211"><a href="#cb49-211" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> mean_math_score, </span>
<span id="cb49-212"><a href="#cb49-212" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Mean: "</span>, <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>))),</span>
<span id="cb49-213"><a href="#cb49-213" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span>
<span id="cb49-214"><a href="#cb49-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-215"><a href="#cb49-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-216"><a href="#cb49-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-217"><a href="#cb49-217" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-218"><a href="#cb49-218" aria-hidden="true" tabindex="-1"></a>These findings highlight the variations in math scores across different race categories, with Group E demonstrating the highest average score and Group A showing the lowest average score performance.</span>
<span id="cb49-219"><a href="#cb49-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-220"><a href="#cb49-220" aria-hidden="true" tabindex="-1"></a><span class="fu">## Math Scores based on Parents Education Level</span></span>
<span id="cb49-221"><a href="#cb49-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-224"><a href="#cb49-224" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-225"><a href="#cb49-225" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb49-226"><a href="#cb49-226" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> parent_education, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb49-227"><a href="#cb49-227" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb49-228"><a href="#cb49-228" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Parental Education Level"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>, </span>
<span id="cb49-229"><a href="#cb49-229" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Parental Education Level"</span>) <span class="sc">+</span></span>
<span id="cb49-230"><a href="#cb49-230" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb49-231"><a href="#cb49-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-232"><a href="#cb49-232" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-233"><a href="#cb49-233" aria-hidden="true" tabindex="-1"></a>Even thought there is a little difference in the math scores there is not significant difference based on their parents education level</span>
<span id="cb49-234"><a href="#cb49-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-235"><a href="#cb49-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-236"><a href="#cb49-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-239"><a href="#cb49-239" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-240"><a href="#cb49-240" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb49-241"><a href="#cb49-241" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb49-242"><a href="#cb49-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-243"><a href="#cb49-243" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean math score by lunch type</span></span>
<span id="cb49-244"><a href="#cb49-244" aria-hidden="true" tabindex="-1"></a>mean_scores <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb49-245"><a href="#cb49-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lunch) <span class="sc">%&gt;%</span></span>
<span id="cb49-246"><a href="#cb49-246" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math_score =</span> <span class="fu">mean</span>(math_score))</span>
<span id="cb49-247"><a href="#cb49-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-248"><a href="#cb49-248" aria-hidden="true" tabindex="-1"></a><span class="co"># bar chart</span></span>
<span id="cb49-249"><a href="#cb49-249" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> lunch, <span class="at">y =</span> math_score)) <span class="sc">+</span></span>
<span id="cb49-250"><a href="#cb49-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb49-251"><a href="#cb49-251" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Lunch Type"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>,</span>
<span id="cb49-252"><a href="#cb49-252" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Math Scores by Lunch Type"</span>) <span class="sc">+</span></span>
<span id="cb49-253"><a href="#cb49-253" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb49-254"><a href="#cb49-254" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> mean_scores, <span class="fu">aes</span>(<span class="at">x =</span> lunch, <span class="at">y =</span> mean_math_score,</span>
<span id="cb49-255"><a href="#cb49-255" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Mean: "</span>, <span class="fu">round</span>(mean_math_score, <span class="dv">2</span>))),</span>
<span id="cb49-256"><a href="#cb49-256" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span>
<span id="cb49-257"><a href="#cb49-257" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-258"><a href="#cb49-258" aria-hidden="true" tabindex="-1"></a>It is interesting to see the math score of students based on their lunch type. Students how are taking standard meal are performing better at math as compared to people taking free or reduced lunch option. </span>
<span id="cb49-259"><a href="#cb49-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-260"><a href="#cb49-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-261"><a href="#cb49-261" aria-hidden="true" tabindex="-1"></a><span class="fu">## Correlation Matrix of Math, Reading, and Writing Scores</span></span>
<span id="cb49-262"><a href="#cb49-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-265"><a href="#cb49-265" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-266"><a href="#cb49-266" aria-hidden="true" tabindex="-1"></a>num_data <span class="ot">&lt;-</span> data[, <span class="fu">c</span>( <span class="st">"math_score"</span>, <span class="st">"reading_score"</span>, <span class="st">"writing_score"</span>)]</span>
<span id="cb49-267"><a href="#cb49-267" aria-hidden="true" tabindex="-1"></a>m<span class="ot">&lt;-</span><span class="fu">cor</span>(num_data)</span>
<span id="cb49-268"><a href="#cb49-268" aria-hidden="true" tabindex="-1"></a>m</span>
<span id="cb49-269"><a href="#cb49-269" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(m, <span class="at">method=</span><span class="st">"circle"</span>, <span class="at">type=</span><span class="st">'upper'</span>, <span class="at">tl.cex=</span><span class="fl">0.8</span>, <span class="at">tl.col =</span> <span class="st">'black'</span>)</span>
<span id="cb49-270"><a href="#cb49-270" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-271"><a href="#cb49-271" aria-hidden="true" tabindex="-1"></a>The correlation analysis reveals interesting insights into the relationships between math scores, reading scores, and writing scores. The strong positive correlation coefficient of 0.8176 between math_score and reading_score suggests that students who excel in math also tend to perform well in reading. Similarly, the high correlation coefficient of 0.8026 between math_score and writing_score indicates a strong positive association, indicating that students who demonstrate proficiency in math often display strong writing skills as well. Furthermore, the very high correlation coefficient of 0.9546 between reading_score and writing_score highlights a robust positive relationship, indicating that students who excel in reading are highly likely to excel in writing.</span>
<span id="cb49-272"><a href="#cb49-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-273"><a href="#cb49-273" aria-hidden="true" tabindex="-1"></a>Taken together, these findings provide substantial evidence supporting our hypothesis that math exam scores are positively associated with both reading and writing scores. These results suggest that students who demonstrate proficiency in one subject area are more likely to excel in the other subjects as well, reinforcing the idea of a positive relationship between math scores and reading/writing scores.</span>
<span id="cb49-274"><a href="#cb49-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-275"><a href="#cb49-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-276"><a href="#cb49-276" aria-hidden="true" tabindex="-1"></a>To address the assumption of homogeneous variance in the math scores between two groups, we can perform a statistical test before deciding which t-test to use (Student's t-test or Welch's t-test)</span>
<span id="cb49-277"><a href="#cb49-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-278"><a href="#cb49-278" aria-hidden="true" tabindex="-1"></a><span class="fu">### Statistical Analysis - Homogeneity of Variance Test</span></span>
<span id="cb49-281"><a href="#cb49-281" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-282"><a href="#cb49-282" aria-hidden="true" tabindex="-1"></a>var_test <span class="ot">&lt;-</span> <span class="fu">bartlett.test</span>(math_score <span class="sc">~</span> gender, <span class="at">data =</span> data)</span>
<span id="cb49-283"><a href="#cb49-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-284"><a href="#cb49-284" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (var_test<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>) {</span>
<span id="cb49-285"><a href="#cb49-285" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(math_score <span class="sc">~</span> gender, <span class="at">data =</span> data, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb49-286"><a href="#cb49-286" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb49-287"><a href="#cb49-287" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(math_score <span class="sc">~</span> gender, <span class="at">data =</span> data, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb49-288"><a href="#cb49-288" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb49-289"><a href="#cb49-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-290"><a href="#cb49-290" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the t-test results</span></span>
<span id="cb49-291"><a href="#cb49-291" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test)</span>
<span id="cb49-292"><a href="#cb49-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-293"><a href="#cb49-293" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-294"><a href="#cb49-294" aria-hidden="true" tabindex="-1"></a>The t-statistic value is -5.3832 with a degrees of freedom (df) value of 998. The p-value is 9.12e-08, which is less than the significance level of 0.05. This suggests strong evidence to reject the null hypothesis. Therefore, we can conclude that there is a significant difference in the mean math scores between the female and male groups.</span>
<span id="cb49-295"><a href="#cb49-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-296"><a href="#cb49-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-297"><a href="#cb49-297" aria-hidden="true" tabindex="-1"></a>The sample mean for the female group is 63.63320, while the sample mean for the male group is 68.72822. This indicates that, on average, male students have higher math scores compared to female students.</span>
<span id="cb49-298"><a href="#cb49-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-299"><a href="#cb49-299" aria-hidden="true" tabindex="-1"></a>In your case, the p-value of the Bartlett's test is less than 0.05 (9.12e-08), indicating that the variances of math scores between the female and male groups are significantly different. Therefore, you use Welch's t-test (var.equal = FALSE) to compare the means of the two groups.</span>
<span id="cb49-300"><a href="#cb49-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-301"><a href="#cb49-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-302"><a href="#cb49-302" aria-hidden="true" tabindex="-1"></a><span class="fu">### Welch's T-Test</span></span>
<span id="cb49-305"><a href="#cb49-305" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-306"><a href="#cb49-306" aria-hidden="true" tabindex="-1"></a><span class="co"># Statistical Analysis</span></span>
<span id="cb49-307"><a href="#cb49-307" aria-hidden="true" tabindex="-1"></a>t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(math_score <span class="sc">~</span> gender, <span class="at">data =</span> data, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb49-308"><a href="#cb49-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-309"><a href="#cb49-309" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the t-test results</span></span>
<span id="cb49-310"><a href="#cb49-310" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test)</span>
<span id="cb49-311"><a href="#cb49-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-312"><a href="#cb49-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-313"><a href="#cb49-313" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-314"><a href="#cb49-314" aria-hidden="true" tabindex="-1"></a>The Welch's t-test was performed to examine the difference in mean math scores between female and male students. The results indicate a significant disparity in math performance between the two genders. On average, male students outperformed female students in math, as evidenced by a higher mean math score. The t-value of -5.3832, with 998 degrees of freedom, and an extremely small p-value of 9.12e-08 provide strong evidence against the null hypothesis. The 95% confidence interval (-6.952285 to -3.237737) further supports the conclusion of a significant difference in math scores between males and females. These findings highlight a gender-based discrepancy, with male students demonstrating superior math performance compared to their female counterparts.</span>
<span id="cb49-315"><a href="#cb49-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-316"><a href="#cb49-316" aria-hidden="true" tabindex="-1"></a><span class="fu"># Linear Regression Models </span></span>
<span id="cb49-317"><a href="#cb49-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-318"><a href="#cb49-318" aria-hidden="true" tabindex="-1"></a>Before performing the Linear Regression im converting the parent education level as ordinal variable with lower education as lower number and higher education as higher number.</span>
<span id="cb49-319"><a href="#cb49-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-322"><a href="#cb49-322" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-323"><a href="#cb49-323" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert parent's level of education to an ordinal variable</span></span>
<span id="cb49-324"><a href="#cb49-324" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>parent_education <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>parent_education, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb49-325"><a href="#cb49-325" aria-hidden="true" tabindex="-1"></a>  <span class="st">"some high school"</span>, <span class="st">"high school"</span>, <span class="st">"some college"</span>, <span class="st">"associate's degree"</span>,</span>
<span id="cb49-326"><a href="#cb49-326" aria-hidden="true" tabindex="-1"></a>  <span class="st">"bachelor's degree"</span>, <span class="st">"master's degree"</span></span>
<span id="cb49-327"><a href="#cb49-327" aria-hidden="true" tabindex="-1"></a>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>))</span>
<span id="cb49-328"><a href="#cb49-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-329"><a href="#cb49-329" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify the ordinal variable</span></span>
<span id="cb49-330"><a href="#cb49-330" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>parent_education)</span>
<span id="cb49-331"><a href="#cb49-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-332"><a href="#cb49-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-333"><a href="#cb49-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-334"><a href="#cb49-334" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-337"><a href="#cb49-337" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-338"><a href="#cb49-338" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the models without train and test data splitting</span></span>
<span id="cb49-339"><a href="#cb49-339" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> reading_score <span class="sc">+</span> writing_score, <span class="at">data =</span> data)</span>
<span id="cb49-340"><a href="#cb49-340" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span>
<span id="cb49-341"><a href="#cb49-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-342"><a href="#cb49-342" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> reading_score <span class="sc">*</span> gender, <span class="at">data =</span> data)</span>
<span id="cb49-343"><a href="#cb49-343" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span>
<span id="cb49-344"><a href="#cb49-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-345"><a href="#cb49-345" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> writing_score <span class="sc">*</span> gender, <span class="at">data =</span> data)</span>
<span id="cb49-346"><a href="#cb49-346" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span>
<span id="cb49-347"><a href="#cb49-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-348"><a href="#cb49-348" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math_score <span class="sc">~</span> ., <span class="at">data =</span> data)</span>
<span id="cb49-349"><a href="#cb49-349" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span>
<span id="cb49-350"><a href="#cb49-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-351"><a href="#cb49-351" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-352"><a href="#cb49-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-353"><a href="#cb49-353" aria-hidden="true" tabindex="-1"></a>Model 1: math_score ~ reading_score + writing_score</span>
<span id="cb49-354"><a href="#cb49-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-355"><a href="#cb49-355" aria-hidden="true" tabindex="-1"></a>Both reading_score and writing_score have statistically significant coefficients (p &lt; 0.001).</span>
<span id="cb49-356"><a href="#cb49-356" aria-hidden="true" tabindex="-1"></a>The positive estimates suggest that an increase in reading_score and writing_score is associated with an increase in math_score.</span>
<span id="cb49-357"><a href="#cb49-357" aria-hidden="true" tabindex="-1"></a>The adjusted R-squared value of 0.6733 indicates that the model explains approximately 67.33% of the variance in math_score.</span>
<span id="cb49-358"><a href="#cb49-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-359"><a href="#cb49-359" aria-hidden="true" tabindex="-1"></a>Model 2: math_score ~ reading_score * gender</span>
<span id="cb49-360"><a href="#cb49-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-361"><a href="#cb49-361" aria-hidden="true" tabindex="-1"></a>The coefficient for reading_score is statistically significant (p &lt; 0.001) with a positive estimate, indicating that an increase in reading_score is associated with a higher math_score.</span>
<span id="cb49-362"><a href="#cb49-362" aria-hidden="true" tabindex="-1"></a>The coefficient for gender_male is statistically significant (p &lt; 0.001) with a positive estimate, indicating that, on average, male students have higher math scores than female students.</span>
<span id="cb49-363"><a href="#cb49-363" aria-hidden="true" tabindex="-1"></a>The interaction term reading_score:gender_male is statistically significant (p = 0.0225) and negative, suggesting that the positive effect of reading_score on math_score is slightly weaker for male students compared to female students.</span>
<span id="cb49-364"><a href="#cb49-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-365"><a href="#cb49-365" aria-hidden="true" tabindex="-1"></a>Model 3: math_score ~ writing_score * gender</span>
<span id="cb49-366"><a href="#cb49-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-367"><a href="#cb49-367" aria-hidden="true" tabindex="-1"></a>The coefficient for writing_score is statistically significant (p &lt; 0.001) with a positive estimate, indicating that an increase in writing_score is associated with a higher math_score.</span>
<span id="cb49-368"><a href="#cb49-368" aria-hidden="true" tabindex="-1"></a>The coefficient for gender_male is statistically significant (p &lt; 0.001) with a positive estimate, indicating that, on average, male students have higher math scores than female students.</span>
<span id="cb49-369"><a href="#cb49-369" aria-hidden="true" tabindex="-1"></a>The interaction term writing_score:gender_male has a p-value of 0.0517, which is marginally significant. It suggests that there might be a difference in the effect of writing_score on math_score between male and female students, although further investigation is needed to confirm its significance.</span>
<span id="cb49-370"><a href="#cb49-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-371"><a href="#cb49-371" aria-hidden="true" tabindex="-1"></a>Model 4: This model includes all available predictor variables.</span>
<span id="cb49-372"><a href="#cb49-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-373"><a href="#cb49-373" aria-hidden="true" tabindex="-1"></a>Several variables have statistically significant coefficients, including gender, race (specifically race group E), parent's education level (bachelor's degree and master's degree), lunch type (standard), test preparation (none), reading_score, and writing_score.</span>
<span id="cb49-374"><a href="#cb49-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-375"><a href="#cb49-375" aria-hidden="true" tabindex="-1"></a>The adjusted R-squared value of 0.875 indicates that the model explains approximately 87.5% of the variance in math_score.</span>
<span id="cb49-376"><a href="#cb49-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-377"><a href="#cb49-377" aria-hidden="true" tabindex="-1"></a>Overall, the results from these models provide evidence supporting the hypothesis that math exam scores are positively associated with students' reading and writing scores. Gender appears to have a significant influence on math scores, with male students generally having higher scores than female students. Other factors such as race, parent's education level, lunch type, and test preparation also show significant associations with math scores.</span>
<span id="cb49-378"><a href="#cb49-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-379"><a href="#cb49-379" aria-hidden="true" tabindex="-1"></a>Based on these conclusions, we can see that all four models show significant associations between the predictors and the math score. The fourth model, which includes multiple predictors, provides the highest adjusted R-squared value, indicating a better fit to the data. However, it's important to note that including more predictors may increase the risk of overfitting the model. </span>
<span id="cb49-380"><a href="#cb49-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-381"><a href="#cb49-381" aria-hidden="true" tabindex="-1"></a>Therefore, Im choosing model 3 which provides a good fit to the data and explains a significant amount of variance in the math scores.</span>
<span id="cb49-382"><a href="#cb49-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-383"><a href="#cb49-383" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model Comparison using AIC and BIC</span></span>
<span id="cb49-386"><a href="#cb49-386" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-387"><a href="#cb49-387" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model1,model2, model3, model4)</span>
<span id="cb49-388"><a href="#cb49-388" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(model1,model2, model3, model4)</span>
<span id="cb49-389"><a href="#cb49-389" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-390"><a href="#cb49-390" aria-hidden="true" tabindex="-1"></a>Based on these results, we can make the following conclusions:</span>
<span id="cb49-391"><a href="#cb49-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-392"><a href="#cb49-392" aria-hidden="true" tabindex="-1"></a>The models differ in the number of degrees of freedom, which is determined by the number of predictors included in each model.</span>
<span id="cb49-393"><a href="#cb49-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-394"><a href="#cb49-394" aria-hidden="true" tabindex="-1"></a>The lower the BIC and AIC values, the better the model fits the data while considering model complexity.</span>
<span id="cb49-395"><a href="#cb49-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-396"><a href="#cb49-396" aria-hidden="true" tabindex="-1"></a>Comparing the BIC values, Model 4 has the lowest BIC (6291.939), followed by Model 3 (6539.885), Model 2 (6631.304), and Model 1 (7181.435).</span>
<span id="cb49-397"><a href="#cb49-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-398"><a href="#cb49-398" aria-hidden="true" tabindex="-1"></a>Comparing the AIC values, Model 4 has the lowest AIC (6213.415), followed by Model 3 (6515.346), Model 2 (6606.765), and Model 1 (7161.804).</span>
<span id="cb49-399"><a href="#cb49-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-400"><a href="#cb49-400" aria-hidden="true" tabindex="-1"></a>Based on both the BIC and AIC criteria, Model 4 is the preferred model among </span>
<span id="cb49-401"><a href="#cb49-401" aria-hidden="true" tabindex="-1"></a>Model 1, Model 2, Model 3, and Model 4. It exhibits the lowest values for both BIC and AIC, indicating a better trade-off between model fit and complexity.</span>
<span id="cb49-402"><a href="#cb49-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-403"><a href="#cb49-403" aria-hidden="true" tabindex="-1"></a>Even though my hypothesis is valid (Model 3) Based on the AIC and BIC scores im choosing model4 to perform diagnostics.</span>
<span id="cb49-404"><a href="#cb49-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-405"><a href="#cb49-405" aria-hidden="true" tabindex="-1"></a><span class="fu">## Diagnostics</span></span>
<span id="cb49-408"><a href="#cb49-408" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-409"><a href="#cb49-409" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model4)</span>
<span id="cb49-410"><a href="#cb49-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-411"><a href="#cb49-411" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-412"><a href="#cb49-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-413"><a href="#cb49-413" aria-hidden="true" tabindex="-1"></a>Based on the interpretation of the diagnostic plots for the model4, it appears that the assumptions of the linear regression model are reasonably met.</span>
<span id="cb49-414"><a href="#cb49-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-415"><a href="#cb49-415" aria-hidden="true" tabindex="-1"></a>Residuals vs Fitted:</span>
<span id="cb49-416"><a href="#cb49-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-417"><a href="#cb49-417" aria-hidden="true" tabindex="-1"></a>The residuals vs. fitted plot shows a random scatter of all residuals near to the horizontal line at zero. This suggests that there is almost no systematic pattern or trend in the residuals. It indicates that the linear regression model adequately captures the relationship between the predictors and the response variable.</span>
<span id="cb49-418"><a href="#cb49-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-419"><a href="#cb49-419" aria-hidden="true" tabindex="-1"></a>Normal Q-Q:</span>
<span id="cb49-420"><a href="#cb49-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-421"><a href="#cb49-421" aria-hidden="true" tabindex="-1"></a>The normal quantile-quantile (Q-Q) plot displays the residuals following a roughly straight line, closely aligned with the theoretical diagonal line. This indicates that the residuals approximately follow a normal distribution. Therefore, the assumption of normality for the residuals is reasonably satisfied.</span>
<span id="cb49-422"><a href="#cb49-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-423"><a href="#cb49-423" aria-hidden="true" tabindex="-1"></a>Scale-Location:</span>
<span id="cb49-424"><a href="#cb49-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-425"><a href="#cb49-425" aria-hidden="true" tabindex="-1"></a>The scale-location plot reveals an approximately constant spread or dispersion of residuals across the range of predicted values. The points on the plot are randomly scattered around a horizontal line, indicating homoscedasticity. This suggests that the assumption of constant variance for the residuals is met.</span>
<span id="cb49-426"><a href="#cb49-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-427"><a href="#cb49-427" aria-hidden="true" tabindex="-1"></a>Residuals vs Leverage:</span>
<span id="cb49-428"><a href="#cb49-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-429"><a href="#cb49-429" aria-hidden="true" tabindex="-1"></a>The residuals vs. leverage plot shows that most of the data points fall within the dashed lines, indicating that there are less influential observations with high leverage. Therefore, there are less influential outliers that significantly affect the model.</span>
<span id="cb49-430"><a href="#cb49-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-431"><a href="#cb49-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-432"><a href="#cb49-432" aria-hidden="true" tabindex="-1"></a>Overall, based on these diagnostic plots, the model model3 appears to be a reasonable and valid representation of the relationship between the predictors and the response variable. The assumptions of linearity, normality of residuals, constant variance, and absence of influential outliers are reasonably met. </span>
<span id="cb49-433"><a href="#cb49-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-436"><a href="#cb49-436" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-437"><a href="#cb49-437" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb49-438"><a href="#cb49-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-439"><a href="#cb49-439" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model1, model2, model3, model4, <span class="at">type =</span> <span class="st">"text"</span>)</span>
<span id="cb49-440"><a href="#cb49-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-441"><a href="#cb49-441" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-442"><a href="#cb49-442" aria-hidden="true" tabindex="-1"></a>Model 1 includes only the reading and writing scores as predictors. The results indicate that both reading_score and writing_score have a significant positive effect on math_score (p &lt; 0.01). For every one-unit increase in reading score, the math score is expected to increase by 0.601 units. Similarly, a one-unit increase in writing score is associated with a 0.249 unit increase in math score. These findings support my hypothesis that strong reading and writing skills positively contribute to math performance.</span>
<span id="cb49-443"><a href="#cb49-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-444"><a href="#cb49-444" aria-hidden="true" tabindex="-1"></a>In Model 2, I added the gender variable to examine the potential impact of gender on math scores. The coefficient for gender_male is statistically significant (p &lt; 0.01), suggesting that being male is associated with higher math scores. Specifically, males are expected to have math scores that are 16.484 units higher than females. This finding supports my hypothesis that gender may play a role in math performance.</span>
<span id="cb49-445"><a href="#cb49-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-446"><a href="#cb49-446" aria-hidden="true" tabindex="-1"></a>Building upon Model 2, Model 3 introduces an interaction term between writing_score and gender to explore whether the relationship between writing skills and math scores differs between males and females. The interaction term is marginally significant (p &lt; 0.1), indicating a potential difference in the relationship. This suggests that the impact of writing skills on math scores may vary between genders. This finding aligns with my hypothesis, which proposed that the relationship between writing skills and math performance might differ based on gender.</span>
<span id="cb49-447"><a href="#cb49-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-448"><a href="#cb49-448" aria-hidden="true" tabindex="-1"></a>Finally, Model 4 expands the analysis to include additional predictors such as race and parent's education level. The results reveal several significant effects. Students from race group E are expected to have math scores that are 5.078 units higher compared to the reference group (race group A). Additionally, parent's education level shows some significant associations. For instance, students whose parents have completed education level 5 (highest level) are expected to have math scores 1.599 units lower than those whose parents have education level 1 (lowest level). These findings provide further evidence that race and parent's education may impact math performance.</span>
<span id="cb49-449"><a href="#cb49-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-450"><a href="#cb49-450" aria-hidden="true" tabindex="-1"></a>In summary, the regression models provide support for my hypothesis that reading and writing skills, gender, race, and parent's education level are influential factors in math performance. The findings indicate that reading and writing skills positively influence math scores, while gender, race, and parent's education level also play a role. </span>
<span id="cb49-451"><a href="#cb49-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-452"><a href="#cb49-452" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusion</span></span>
<span id="cb49-453"><a href="#cb49-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-454"><a href="#cb49-454" aria-hidden="true" tabindex="-1"></a>In conclusion, this research aimed to investigate the factors influencing math performance among a sample of students. The analysis considered several variables, including reading and writing scores, gender, race, and parent's education level, to understand their impact on math scores.</span>
<span id="cb49-455"><a href="#cb49-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-456"><a href="#cb49-456" aria-hidden="true" tabindex="-1"></a>The regression models provided valuable insights into the relationships between these variables and math performance. The findings consistently demonstrated the positive influence of reading and writing skills on math scores, supporting the idea that strong literacy skills contribute to overall academic achievement.</span>
<span id="cb49-457"><a href="#cb49-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-458"><a href="#cb49-458" aria-hidden="true" tabindex="-1"></a>Furthermore, gender was found to be a significant factor, with males exhibiting higher math scores compared to females. This suggests that gender differences may exist in math performance and highlights the importance of exploring gender-related factors in educational settings.</span>
<span id="cb49-459"><a href="#cb49-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-460"><a href="#cb49-460" aria-hidden="true" tabindex="-1"></a>The inclusion of race as a predictor revealed that students from racegroup E tended to have higher math scores compared to the reference group. This finding underscores the need to consider the influence of race or cultural background when examining educational outcomes, as it can shed light on disparities and potential areas for targeted interventions.</span>
<span id="cb49-461"><a href="#cb49-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-462"><a href="#cb49-462" aria-hidden="true" tabindex="-1"></a>The impact of parent's education level on math performance was also explored. The results showed that higher parent's education levels were associated with lower math scores, suggesting a complex relationship between parental influence and academic achievement. Further research is warranted to better understand the underlying mechanisms and potential interventions to support students from diverse educational backgrounds.</span>
<span id="cb49-463"><a href="#cb49-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-464"><a href="#cb49-464" aria-hidden="true" tabindex="-1"></a><span class="fu"># Bibliography</span></span>
<span id="cb49-465"><a href="#cb49-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-466"><a href="#cb49-466" aria-hidden="true" tabindex="-1"></a>Dataset : "Students Performance in Exams" Dataset. Retrieved from https://www.kaggle.com/datasets/spscientist/students-performance-in-exams</span>
<span id="cb49-467"><a href="#cb49-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-468"><a href="#cb49-468" aria-hidden="true" tabindex="-1"></a>Johnson, R. A. (2010). Applied Multivariate Statistical Analysis (6th ed.). Pearson Education.</span>
<span id="cb49-469"><a href="#cb49-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-470"><a href="#cb49-470" aria-hidden="true" tabindex="-1"></a>Field, A. (2013). Discovering Statistics Using R. SAGE Publications Ltd.</span>
<span id="cb49-471"><a href="#cb49-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-472"><a href="#cb49-472" aria-hidden="true" tabindex="-1"></a>Wickham, H. (2016). ggplot2: Elegant Graphics for Data Analysis. Springer.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>