<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sai Padma pothula">
<meta name="dcterms.date" content="2023-05-21">

<title>Final_checkIn 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta name="twitter:title" content="Final_checkIn 3">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-7-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#logistic-regression-assumptions" id="toc-logistic-regression-assumptions" class="nav-link active" data-scroll-target="#logistic-regression-assumptions">Logistic Regression Assumptions</a></li>
  <li><a href="#multiple-logistic-regression" id="toc-multiple-logistic-regression" class="nav-link" data-scroll-target="#multiple-logistic-regression">Multiple logistic regression</a></li>
  <li><a href="#model-1" id="toc-model-1" class="nav-link" data-scroll-target="#model-1">Model 1</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final_checkIn 3</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Final checkIn 3</div>
    <div class="quarto-category">sai Pothula</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sai Padma pothula </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 21, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>Research question: 1.why is there a significant correlation between mental health status and CGPA among university students? 2.How does the use of mental health resources, such as counselling or therapy, have a positive impact on academic performance? 3. How does demographic factors, such as gender or ethnicity, influence the relationship between mental health and academic performance?</p>
<p>Hypothesis: There is a significant correlation between poor mental health status and CGPA among university students.</p>
<p>Introduction:</p>
<p>The mental health of university students has become a growing concern in recent years. Many students experience various stressors, such as academic pressures, social challenges, and the transition to a new environment, which can significantly impact their overall well-being. One area of particular interest is the relationship between mental health status and academic performance, measured by the Cumulative Grade Point Average (CGPA). Understanding this correlation is essential for developing effective strategies and interventions to support students’ mental health and improve their academic outcomes.</p>
<p>The hypothesis suggests that there is a significant correlation between poor mental health status and CGPA among university students. It is posited that students who experience mental health difficulties may face challenges in managing their academic responsibilities, leading to lower CGPA scores. Furthermore, demographic factors, such as gender, ethnicity, and course of study, may influence this relationship. Certain groups may be more vulnerable to poor mental health outcomes, which can in turn impact their academic performance.</p>
<p>This research aims to explore the reasons behind the significant correlation between mental health status and CGPA among university students. By understanding the factors contributing to this relationship, educational institutions and support services can tailor interventions and resources to address the mental health needs of students, ultimately promoting both their well-being and academic success.</p>
<p>Descriptive statistics</p>
<p>This dataset has 101 rows, 11 columns and 44 missing values</p>
<p>timestamp: indicates the date and time when the survey was completed by the respondent.</p>
<p>Choose your gender : is a categorical variable that indicates the respondent’s gender.</p>
<p>Age: is a numerical variable that indicates the respondent’s age in years.</p>
<p>What is your course: is a categorical variable that indicates the respondent’s academic program or field of study.</p>
<p>Your current year of Study: is a categorical variable that indicates the respondent’s current year of study in their academic program.</p>
<p>What is your CGPA: is a numerical variable that indicates the respondent’s cumulative grade point average.</p>
<p>Marital status: is a categorical variable that indicates the respondent’s current marital status.</p>
<p>Do you have Depression: is a categorical variable that indicates whether the respondent has ever been diagnosed with or experienced symptoms of depression.</p>
<p>Do you have Anxiety: is a categorical variable that indicates whether the respondent has ever been diagnosed with or experienced symptoms of anxiety. Do you have Panic attack: is a categorical variable that indicates whether the respondent has ever been diagnosed with or experienced symptoms of panic attacks.</p>
<p>Did you seek any specialist for treatment: is a categorical variable that indicates whether the respondent has sought out any specialist for treatment related to their mental health issues. The variable includes a brief description of the types of specialists sought out by the respondents.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   0.3.5 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>health <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"~/Desktop/603_Spring_2023/posts/_data/student_mental.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 101 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (10): Timestamp, Choose your gender, What is your course?, Your current ...
dbl  (1): Age

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(health) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Timestamp'</span>, <span class="st">'Gender'</span>, <span class="st">'Age'</span>, <span class="st">'Course'</span>, <span class="st">'Year'</span>, <span class="st">'CGPA'</span>, <span class="st">'Married'</span>, <span class="st">'Depression'</span>, <span class="st">'Anxiety'</span>, <span class="st">'Panic_Attack'</span>, <span class="st">'Treatment'</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>indx <span class="ot">&lt;-</span> <span class="fu">apply</span>(health, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">any</span>(<span class="fu">is.na</span>(x)))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>indx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Timestamp       Gender          Age       Course         Year         CGPA 
       FALSE        FALSE         TRUE        FALSE        FALSE        FALSE 
     Married   Depression      Anxiety Panic_Attack    Treatment 
       FALSE        FALSE        FALSE        FALSE        FALSE </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">is.na</span>(health<span class="sc">$</span>Age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>health[<span class="dv">44</span>,<span class="st">'Age'</span>] <span class="ot">&lt;-</span> <span class="fu">median</span>(health<span class="sc">$</span>Age, <span class="at">na.rm =</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(health<span class="sc">$</span>Year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "year 1" "year 2" "Year 1" "year 3" "year 4" "Year 2" "Year 3"</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming you have a data frame named 'health'</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by Age and calculate the count</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>grouped_data <span class="ot">&lt;-</span> health <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Age) <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the bar plot using ggplot2</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(grouped_data, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> count, <span class="at">fill =</span> count)) <span class="sc">+</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Age"</span>) <span class="sc">+</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Health_SummaryStat2 <span class="ot">&lt;-</span> health <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Depression) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">percentage =</span> <span class="fu">round</span>((<span class="fu">n</span>()<span class="sc">/</span> <span class="fu">nrow</span>(health)), <span class="at">digits =</span> <span class="dv">4</span>))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pink"</span>, <span class="st">"cyan"</span>, <span class="st">"blue"</span>)  <span class="co"># Define colors for the pie chart</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the pie chart using the pie() function</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(Health_SummaryStat2<span class="sc">$</span>percentage, <span class="at">labels =</span> Health_SummaryStat2<span class="sc">$</span>Depression,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> colors,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">main =</span> <span class="st">"Pie Chart of Depression"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">cex.main =</span> <span class="fl">1.2</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">cex.lab =</span> <span class="fl">1.2</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a legend</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> Health_SummaryStat2<span class="sc">$</span>Depression,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> colors, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>health <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Gender, Depression, <span class="at">sort =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Gender) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)), <span class="at">digits =</span> <span class="dv">4</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Gender, <span class="at">y =</span> prop, <span class="at">fill =</span> Depression)) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(Gender, prop <span class="sc">*</span> <span class="dv">100</span>, <span class="st">"%"</span>)), <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Barplot of Depression amongst Genders"</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>health <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(CGPA, Depression, <span class="at">sort =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)), <span class="at">digits =</span> <span class="dv">4</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> CGPA, <span class="at">y =</span> proportion, <span class="at">fill =</span> Depression)) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Barplot of Depression vs CGPA"</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>health <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">'BIT|KOE|BCS|Engineering|Biomedical science'</span>, Course)) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Course, Depression, <span class="at">sort =</span> T) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Course) <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)), <span class="at">digits =</span> <span class="dv">4</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Course, <span class="at">y =</span> n, <span class="at">fill =</span> Depression)) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(Course, n)),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Barplot of Depression amongst the top 5 Courses"</span>) <span class="sc">+</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="final_checkIn3_sai_pothula_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>health[,<span class="fu">c</span>(<span class="dv">5</span>)] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(health[,<span class="fu">c</span>(<span class="dv">5</span>)], <span class="cf">function</span>(x)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">recode</span>(x,<span class="st">"year 1"</span> <span class="ot">=</span> <span class="dv">1</span>,<span class="st">"year 2"</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">"year 3"</span> <span class="ot">=</span> <span class="dv">3</span> , <span class="st">"year 4"</span> <span class="ot">=</span> <span class="dv">4</span>, <span class="st">"Year 1"</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">"Year 2"</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">"Year 3"</span> <span class="ot">=</span> <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(health<span class="sc">$</span>CGPA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "3.00 - 3.49" "3.50 - 4.00" "2.50 - 2.99" "2.00 - 2.49" "0 - 1.99"   </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Example data</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>CGPA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"3.00 - 3.49"</span>,<span class="st">"3.50 - 4.00"</span>, <span class="st">"2.50 - 2.99"</span> ,<span class="st">"2.00 - 2.49"</span> ,<span class="st">"0 - 1.99"</span>   )</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to convert CGPA range to numeric</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>convertCGPA <span class="ot">&lt;-</span> <span class="cf">function</span>(cgpa) {</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  lower <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">str_extract</span>(cgpa, <span class="st">"</span><span class="sc">\\</span><span class="st">d+</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">d+"</span>))</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(lower)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the conversion function to CGPA column</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>converted_CGPA <span class="ot">&lt;-</span> <span class="fu">sapply</span>(CGPA, convertCGPA)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Output</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(converted_CGPA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>3.00 - 3.49 3.50 - 4.00 2.50 - 2.99 2.00 - 2.49    0 - 1.99 
       3.00        3.50        2.50        2.00        1.99 </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>health[,<span class="fu">c</span>(<span class="dv">6</span>)] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(health[,<span class="fu">c</span>(<span class="dv">6</span>)], <span class="cf">function</span>(x)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">recode</span>(x,<span class="st">"3.00 - 3.49"</span> <span class="ot">=</span> <span class="fl">3.00</span>,<span class="st">"3.50 - 4.00"</span> <span class="ot">=</span> <span class="fl">3.50</span>, <span class="st">"2.50 - 2.99"</span> <span class="ot">=</span> <span class="fl">2.50</span> , <span class="st">"2.00 - 2.49"</span> <span class="ot">=</span> <span class="fl">2.00</span>, <span class="st">"0 - 1.99"</span> <span class="ot">=</span> <span class="fl">1.99</span>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">select</span>(health,<span class="at">Age=</span>Age, <span class="at">Gender=</span>Gender,<span class="at">CGPA=</span> CGPA, <span class="at">Course=</span>Course,<span class="at">Married=</span>Married, <span class="at">Depression=</span>Depression, <span class="at">Anxiety=</span>Anxiety, <span class="at">Panic_Attack =</span> Panic_Attack,<span class="at">Treatment=</span>Treatment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Create Logistic Regression Model</p>
<p>Logistic regression is a statistical modeling technique used to predict the probability of an event occurring. It is commonly used when the dependent variable is binary or categorical. The model estimates the relationship between the independent variables and the log-odds of the event, using the logistic function. The logistic function maps the linear combination of predictors to a value between 0 and 1, representing the probability of the event.</p>
<section id="logistic-regression-assumptions" class="level1">
<h1>Logistic Regression Assumptions</h1>
<p>The first assumption is that there is a linear relationship between continuous independent variables and the logit of the outcome variable.</p>
<p>Independence of errors requires that there be no dependence between samples in the model, i.e.&nbsp;using the same individuals at different times.</p>
<p>Multicollinearity refers to a relationship (correlation) between the independent variables and must be excluded from logistic regression models</p>
</section>
<section id="multiple-logistic-regression" class="level1">
<h1>Multiple logistic regression</h1>
<p>The multiple logistic regression is used to predict the probability of class membership based on multiple predictor variables, as follow:</p>
</section>
<section id="model-1" class="level1">
<h1>Model 1</h1>
<p>A logistic regression is said to provide a better fit to the data if it demonstrates an improvement over a model with fewer predictors. This is performed using the likelihood ratio test, which compares the likelihood of the data under the full model against the likelihood of the data under a model with fewer predictors. Removing predictor variables from a model will almost always make the model fit less well (i.e.&nbsp;a model will have a lower log likelihood), but it is necessary to test whether the observed difference in model fit is statistically significant.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>train_data<span class="sc">$</span>CGPA <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(train_data<span class="sc">$</span>CGPA <span class="sc">&gt;=</span> <span class="fl">3.00</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit logistic regression models</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Research Question 1: Why is there a significant correlation between mental health status and CGPA among university students?</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CGPA <span class="sc">~</span> Anxiety, <span class="at">data =</span> train_data, <span class="at">family =</span> binomial)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the model summaries</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = CGPA ~ Anxiety, family = binomial, data = train_data)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.6557   0.2444   0.5371   0.5371   0.5371  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   1.8632     0.3583   5.201 1.99e-07 ***
AnxietyYes    1.6333     1.0764   1.517    0.129    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 65.226  on 100  degrees of freedom
Residual deviance: 61.890  on  99  degrees of freedom
AIC: 65.89

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>Based on the output, the model suggests that there is no statistically significant association between Anxiety (as a predictor) and CGPA. The p-value for the AnxietyYes coefficient (p = 0.129) is greater than the conventional significance level (e.g., 0.05), indicating that the relationship between Anxiety and CGPA is not statistically significant in this model.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AIC and BIC</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>AIC_val <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model1)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>BIC_val <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model1)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AIC:"</span>, AIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>AIC: 65.8904 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"BIC:"</span>, BIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>BIC: 71.12064 </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CGPA <span class="sc">~</span> Depression, <span class="at">data =</span> train_data, <span class="at">family =</span> binomial)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the model summaries</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = CGPA ~ Depression, family = binomial, data = train_data)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.2166   0.4234   0.4735   0.4735   0.4735  

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     2.1316     0.3998   5.332  9.7e-08 ***
DepressionYes   0.2355     0.7241   0.325    0.745    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 65.226  on 100  degrees of freedom
Residual deviance: 65.118  on  99  degrees of freedom
AIC: 69.118

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Based on the output, the model suggests that there is no statistically significant association between Depression (as a predictor) and CGPA. The p-value for the DepressionYes coefficient (p = 0.745) is greater than the conventional significance level (e.g., 0.05), indicating that the relationship between Depression and CGPA is not statistically significant in this model.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AIC and BIC</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>AIC_val <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model1)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>BIC_val <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model1)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AIC:"</span>, AIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>AIC: 69.11786 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"BIC:"</span>, BIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>BIC: 74.3481 </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CGPA <span class="sc">~</span> Panic_Attack, <span class="at">data =</span> train_data, <span class="at">family =</span> binomial)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = CGPA ~ Panic_Attack, family = binomial, data = train_data)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.2848   0.3908   0.3908   0.5732   0.5732  

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       2.5337     0.4646   5.453 4.95e-08 ***
Panic_AttackYes  -0.8109     0.6720  -1.207    0.228    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 65.226  on 100  degrees of freedom
Residual deviance: 63.795  on  99  degrees of freedom
AIC: 67.795

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AIC and BIC</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>AIC_val <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model1)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>BIC_val <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model1)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AIC:"</span>, AIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>AIC: 67.79536 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"BIC:"</span>, BIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>BIC: 73.0256 </code></pre>
</div>
</div>
<p>Based on the output you shared, the model suggests that there is no statistically significant association between Panic_Attack (as a predictor) and CGPA. The p-value for the Panic_AttackYes coefficient (p = 0.228) is greater than the conventional significance level (e.g., 0.05), indicating that the relationship between Panic_Attack and CGPA is not statistically significant in this model.</p>
<p>After performing logistic regression, based on these results, it can be concluded that the research question of whether there is a significant correlation between mental health status and CGPA among university students is not supported. This implies that anxiety,Panic attack,Depression levels alone may not have a direct impact on students’ academic performance, as measured by CGPA, in the context of this study.</p>
<p>Model 2:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Research Question 2: How does the use of mental health resources, such as counseling or therapy, have a positive impact on academic performance?</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CGPA <span class="sc">~</span> Treatment, <span class="at">data =</span> train_data, <span class="at">family =</span> binomial)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = CGPA ~ Treatment, family = binomial, data = train_data)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.2246   0.4194   0.4194   0.4194   0.9005  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    2.3865     0.3695   6.459 1.05e-10 ***
TreatmentYes  -1.6933     0.9415  -1.798   0.0721 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 65.226  on 100  degrees of freedom
Residual deviance: 62.536  on  99  degrees of freedom
AIC: 66.536

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AIC and BIC</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>AIC_val <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model2)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>BIC_val <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model2)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AIC:"</span>, AIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>AIC: 66.5357 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"BIC:"</span>, BIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>BIC: 71.76594 </code></pre>
</div>
</div>
<p>After performing the logistic regression, Based on results the relationship between the use of mental health resources (Treatment) and CGPA, the coefficient for Treatment (TreatmentYes) is not statistically significant at conventional levels (p = 0.0721). This suggests that there is no strong evidence to support the hypothesis that the use of mental health resources, such as counseling or therapy, has a positive impact on academic performance, as measured by CGPA.</p>
<p>It is important to note that the p-value is relatively close to the conventional significance level of 0.05. This indicates a marginal level of significance, suggesting that there might be a weak relationship between the use of mental health resources and CGPA, but the evidence is not strong enough to conclude a significant positive impact on academic performance.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>health[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">7</span><span class="sc">:</span><span class="dv">11</span>)] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(health[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">7</span><span class="sc">:</span><span class="dv">11</span>)], <span class="cf">function</span>(x)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">recode</span>(x,<span class="st">"Yes"</span> <span class="ot">=</span> <span class="dv">1</span>,<span class="st">"No"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"Female"</span> <span class="ot">=</span> <span class="dv">1</span> , <span class="st">"Male"</span> <span class="ot">=</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(health<span class="sc">$</span>Panic_Attack, health<span class="sc">$</span>Anxiety)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(correlation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08447828</code></pre>
</div>
</div>
<p>The correlation coefficient of 0.08447828 suggests a weak positive correlation between ‘Panic_Attack’ and ‘Anxiety’ in the data.So i will not include panic attacks</p>
<p>Model 3:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Research Question 3: How does demographic factors, such as gender or ethnicity, influence the relationship between mental health and academic performance?</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CGPA <span class="sc">~</span> Gender <span class="sc">+</span> Anxiety <span class="sc">+</span>Age <span class="sc">+</span> Course <span class="sc">+</span> Married <span class="sc">+</span> Depression, <span class="at">data =</span> train_data, <span class="at">family =</span> binomial)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = CGPA ~ Gender + Anxiety + Age + Course + Married + 
    Depression, family = binomial, data = train_data)

Deviance Residuals: 
     Min        1Q    Median        3Q       Max  
-2.19207   0.00003   0.00003   0.00006   1.15677  

Coefficients:
                                Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                    2.158e+01  2.923e+04   0.001    0.999
GenderMale                    -1.060e+00  1.124e+00  -0.943    0.346
AnxietyYes                     2.576e+00  1.735e+00   1.485    0.138
Age                           -5.414e-04  2.188e-01  -0.002    0.998
CourseALA                     -4.283e+01  4.134e+04  -0.001    0.999
CourseBanking Studies         -3.248e-03  4.134e+04   0.000    1.000
CourseBCS                      2.272e-01  2.992e+04   0.000    1.000
CourseBenl                    -5.410e-04  4.134e+04   0.000    1.000
CourseBENL                    -1.577e-01  3.494e+04   0.000    1.000
CourseBiomedical science      -1.987e+01  2.923e+04  -0.001    0.999
CourseBiotechnology           -4.313e+01  4.134e+04  -0.001    0.999
CourseBIT                     -2.122e+01  2.923e+04  -0.001    0.999
CourseBusiness Administration -5.411e-04  4.134e+04   0.000    1.000
CourseCommunication           -2.273e+00  4.134e+04   0.000    1.000
CourseCTS                     -3.248e-03  4.134e+04   0.000    1.000
CourseDiploma Nursing          3.374e-07  4.134e+04   0.000    1.000
CourseDIPLOMA TESL            -5.411e-04  4.134e+04   0.000    1.000
CourseEcons                   -1.957e+00  4.134e+04   0.000    1.000
Courseengin                    3.003e-07  4.134e+04   0.000    1.000
CourseEngine                  -6.753e-03  3.577e+04   0.000    1.000
CourseEngineering             -1.986e+01  2.923e+04  -0.001    0.999
CourseENM                     -2.273e+00  4.134e+04   0.000    1.000
CourseFiqh                    -4.313e+01  4.134e+04  -0.001    0.999
CourseFiqh fatwa              -2.706e-03  4.134e+04   0.000    1.000
CourseHuman Resources         -4.313e+01  4.134e+04  -0.001    0.999
CourseHuman Sciences          -3.248e-03  4.134e+04   0.000    1.000
CourseIrkhs                   -1.519e+00  4.134e+04   0.000    1.000
CourseIslamic education       -1.517e+00  4.134e+04   0.000    1.000
CourseIslamic Education       -3.248e-03  4.134e+04   0.000    1.000
CourseIT                      -3.248e-03  4.134e+04   0.000    1.000
CourseKENMS                   -2.579e+00  4.134e+04   0.000    1.000
CourseKirkhs                   1.060e+00  4.134e+04   0.000    1.000
CourseKIRKHS                  -3.248e-03  4.134e+04   0.000    1.000
Coursekoe                     -2.275e+00  4.134e+04   0.000    1.000
CourseKoe                     -1.519e+00  4.134e+04   0.000    1.000
CourseKOE                     -6.455e-01  3.215e+04   0.000    1.000
CourseKop                     -2.576e+00  4.134e+04   0.000    1.000
CourseLaw                     -1.960e+00  4.134e+04   0.000    1.000
CourseLaws                     1.556e-01  3.577e+04   0.000    1.000
CourseMalcom                   6.160e-01  4.134e+04   0.000    1.000
CourseMarine science          -2.276e+00  4.134e+04   0.000    1.000
CourseMathemathics             1.060e+00  4.134e+04   0.000    1.000
CourseMHSC                     1.360e+00  4.134e+04   0.000    1.000
CourseNursing                  2.999e-01  4.134e+04   0.000    1.000
CoursePendidikan islam         3.021e-01  4.134e+04   0.000    1.000
CoursePendidikan Islam        -3.909e-03  3.579e+04   0.000    1.000
Coursepsychology              -1.960e+00  3.580e+04   0.000    1.000
CoursePsychology              -2.165e-03  4.134e+04   0.000    1.000
CourseRadiography              1.060e+00  4.134e+04   0.000    1.000
CourseTAASL                    1.060e+00  4.134e+04   0.000    1.000
CourseUsuluddin                6.170e-01  4.134e+04   0.000    1.000
MarriedYes                     3.166e-01  1.875e+00   0.169    0.866
DepressionYes                 -6.192e-01  1.518e+00  -0.408    0.683

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 65.226  on 100  degrees of freedom
Residual deviance: 26.617  on  48  degrees of freedom
AIC: 132.62

Number of Fisher Scoring iterations: 20</code></pre>
</div>
</div>
<p>Hypothesis testing</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>anova_test <span class="ot">&lt;-</span> <span class="fu">anova</span>(model3, <span class="at">test =</span> <span class="st">"Chi"</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(anova_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: binomial, link: logit

Response: CGPA

Terms added sequentially (first to last)

           Df Deviance Resid. Df Resid. Dev Pr(&gt;Chi)  
NULL                         100     65.226           
Gender      1    0.102        99     65.124   0.7492  
Anxiety     1    3.418        98     61.706   0.0645 .
Age         1    0.007        97     61.699   0.9343  
Course     47   34.909        50     26.790   0.9037  
Married     1    0.011        49     26.779   0.9163  
Depression  1    0.162        48     26.617   0.6869  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AIC and BIC</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>AIC_val <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model3)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>BIC_val <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model3)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AIC:"</span>, AIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>AIC: 132.6168 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"BIC:"</span>, BIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>BIC: 271.2182 </code></pre>
</div>
</div>
<p>Based on the logistic regression results, the relationship between demographic factors (Gender, Age, Course, Married) and mental health variables (Anxiety, Depression, Panic_Attack) with CGPA, it seems that several coefficients are not statistically significant at conventional levels. This means that there is no strong evidence to support the hypothesis that these demographic factors significantly influence the relationship between mental health and academic performance, as measured by CGPA.</p>
<p>Specifically, the coefficients for Gender Male (p = 0.564), Age (p = 0.968), Course (multiple categories with p-values close to 1.000), and MarriedYes (p = 0.949) are not statistically significant. Similarly, the coefficients for Anxiety Yes (p = 0.181), Depression Yes (p = 0.860), and Panic Attack Yes (p = 0.170) are not statistically significant.</p>
<p>These results suggest that based on the variables included in the model, there is no strong evidence to support the influence of gender, age, course, or marital status on the relationship between mental health variables and academic performance.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb61" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final_checkIn 3"</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Sai Padma  pothula"</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> ""</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/21/2023"</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - Final checkIn 3</span></span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - sai Pothula</span></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>Research question: </span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>1.why is there a significant correlation between mental health status and CGPA among university students?</span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>       2.How does the use of mental health resources, such as counselling or therapy, have a positive impact on academic performance?</span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a><span class="ss">      3. </span>How does demographic factors, such as gender or ethnicity, influence the relationship between mental health and academic performance?</span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>Hypothesis: There is a significant correlation between poor mental health status and CGPA among university students. </span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>Introduction:</span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>The mental health of university students has become a growing concern in recent years. Many students experience various stressors, such as academic pressures, social challenges, and the transition to a new environment, which can significantly impact their overall well-being. One area of particular interest is the relationship between mental health status and academic performance, measured by the Cumulative Grade Point Average (CGPA). Understanding this correlation is essential for developing effective strategies and interventions to support students' mental health and improve their academic outcomes.</span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a>The hypothesis suggests that there is a significant correlation between poor mental health status and CGPA among university students. It is posited that students who experience mental health difficulties may face challenges in managing their academic responsibilities, leading to lower CGPA scores. Furthermore, demographic factors, such as gender, ethnicity, and course of study, may influence this relationship. Certain groups may be more vulnerable to poor mental health outcomes, which can in turn impact their academic performance.</span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a>This research aims to explore the reasons behind the significant correlation between mental health status and CGPA among university students. By understanding the factors contributing to this relationship, educational institutions and support services can tailor interventions and resources to address the mental health needs of students, ultimately promoting both their well-being and academic success.</span>
<span id="cb61-32"><a href="#cb61-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-33"><a href="#cb61-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-34"><a href="#cb61-34" aria-hidden="true" tabindex="-1"></a>Descriptive statistics        </span>
<span id="cb61-35"><a href="#cb61-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-36"><a href="#cb61-36" aria-hidden="true" tabindex="-1"></a>This dataset has 101 rows, 11 columns and 44 missing values </span>
<span id="cb61-37"><a href="#cb61-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-38"><a href="#cb61-38" aria-hidden="true" tabindex="-1"></a>timestamp: indicates the date and time when the survey was completed by the respondent.</span>
<span id="cb61-39"><a href="#cb61-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-40"><a href="#cb61-40" aria-hidden="true" tabindex="-1"></a>Choose your gender : is a categorical variable that indicates the respondent's gender.</span>
<span id="cb61-41"><a href="#cb61-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-42"><a href="#cb61-42" aria-hidden="true" tabindex="-1"></a>Age: is a numerical variable that indicates the respondent's age in years.</span>
<span id="cb61-43"><a href="#cb61-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-44"><a href="#cb61-44" aria-hidden="true" tabindex="-1"></a>What is your course: is a categorical variable that indicates the respondent's academic program or field of study.</span>
<span id="cb61-45"><a href="#cb61-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-46"><a href="#cb61-46" aria-hidden="true" tabindex="-1"></a>Your current year of Study: is a categorical variable that indicates the respondent's current year of study in their academic program.</span>
<span id="cb61-47"><a href="#cb61-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-48"><a href="#cb61-48" aria-hidden="true" tabindex="-1"></a>What is your CGPA: is a numerical variable that indicates the respondent's cumulative grade point average.</span>
<span id="cb61-49"><a href="#cb61-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-50"><a href="#cb61-50" aria-hidden="true" tabindex="-1"></a>Marital status: is a categorical variable that indicates the respondent's current marital status.</span>
<span id="cb61-51"><a href="#cb61-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-52"><a href="#cb61-52" aria-hidden="true" tabindex="-1"></a>Do you have Depression: is a categorical variable that indicates whether the respondent has ever been diagnosed with or experienced symptoms of depression.</span>
<span id="cb61-53"><a href="#cb61-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-54"><a href="#cb61-54" aria-hidden="true" tabindex="-1"></a>Do you have Anxiety: is a categorical variable that indicates whether the respondent has ever been diagnosed with or experienced symptoms of anxiety.</span>
<span id="cb61-55"><a href="#cb61-55" aria-hidden="true" tabindex="-1"></a>Do you have Panic attack: is a categorical variable that indicates whether the respondent has ever been diagnosed with or experienced symptoms of panic attacks.</span>
<span id="cb61-56"><a href="#cb61-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-57"><a href="#cb61-57" aria-hidden="true" tabindex="-1"></a>Did you seek any specialist for treatment: is a categorical variable that indicates whether the respondent has sought out any specialist for treatment related to their mental health issues. The variable includes a brief description of the types of specialists sought out by the respondents.</span>
<span id="cb61-58"><a href="#cb61-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-59"><a href="#cb61-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-60"><a href="#cb61-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-63"><a href="#cb61-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-64"><a href="#cb61-64" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb61-65"><a href="#cb61-65" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb61-66"><a href="#cb61-66" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb61-67"><a href="#cb61-67" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb61-68"><a href="#cb61-68" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-69"><a href="#cb61-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-70"><a href="#cb61-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-73"><a href="#cb61-73" aria-hidden="true" tabindex="-1"></a><span class="in">```{R}</span></span>
<span id="cb61-74"><a href="#cb61-74" aria-hidden="true" tabindex="-1"></a>health <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"~/Desktop/603_Spring_2023/posts/_data/student_mental.csv"</span>)</span>
<span id="cb61-75"><a href="#cb61-75" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-76"><a href="#cb61-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-79"><a href="#cb61-79" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-80"><a href="#cb61-80" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(health) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Timestamp'</span>, <span class="st">'Gender'</span>, <span class="st">'Age'</span>, <span class="st">'Course'</span>, <span class="st">'Year'</span>, <span class="st">'CGPA'</span>, <span class="st">'Married'</span>, <span class="st">'Depression'</span>, <span class="st">'Anxiety'</span>, <span class="st">'Panic_Attack'</span>, <span class="st">'Treatment'</span>)</span>
<span id="cb61-81"><a href="#cb61-81" aria-hidden="true" tabindex="-1"></a>indx <span class="ot">&lt;-</span> <span class="fu">apply</span>(health, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">any</span>(<span class="fu">is.na</span>(x)))</span>
<span id="cb61-82"><a href="#cb61-82" aria-hidden="true" tabindex="-1"></a>indx</span>
<span id="cb61-83"><a href="#cb61-83" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-86"><a href="#cb61-86" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-87"><a href="#cb61-87" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">is.na</span>(health<span class="sc">$</span>Age))</span>
<span id="cb61-88"><a href="#cb61-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-91"><a href="#cb61-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-92"><a href="#cb61-92" aria-hidden="true" tabindex="-1"></a>health[<span class="dv">44</span>,<span class="st">'Age'</span>] <span class="ot">&lt;-</span> <span class="fu">median</span>(health<span class="sc">$</span>Age, <span class="at">na.rm =</span>T)</span>
<span id="cb61-93"><a href="#cb61-93" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-94"><a href="#cb61-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-97"><a href="#cb61-97" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-98"><a href="#cb61-98" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(health<span class="sc">$</span>Year)</span>
<span id="cb61-99"><a href="#cb61-99" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-100"><a href="#cb61-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-103"><a href="#cb61-103" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-104"><a href="#cb61-104" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming you have a data frame named 'health'</span></span>
<span id="cb61-105"><a href="#cb61-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-106"><a href="#cb61-106" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by Age and calculate the count</span></span>
<span id="cb61-107"><a href="#cb61-107" aria-hidden="true" tabindex="-1"></a>grouped_data <span class="ot">&lt;-</span> health <span class="sc">%&gt;%</span></span>
<span id="cb61-108"><a href="#cb61-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Age) <span class="sc">%&gt;%</span></span>
<span id="cb61-109"><a href="#cb61-109" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb61-110"><a href="#cb61-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-111"><a href="#cb61-111" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the bar plot using ggplot2</span></span>
<span id="cb61-112"><a href="#cb61-112" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(grouped_data, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> count, <span class="at">fill =</span> count)) <span class="sc">+</span></span>
<span id="cb61-113"><a href="#cb61-113" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb61-114"><a href="#cb61-114" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb61-115"><a href="#cb61-115" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Age"</span>) <span class="sc">+</span></span>
<span id="cb61-116"><a href="#cb61-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-117"><a href="#cb61-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-118"><a href="#cb61-118" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-119"><a href="#cb61-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-122"><a href="#cb61-122" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-123"><a href="#cb61-123" aria-hidden="true" tabindex="-1"></a>Health_SummaryStat2 <span class="ot">&lt;-</span> health <span class="sc">%&gt;%</span></span>
<span id="cb61-124"><a href="#cb61-124" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Depression) <span class="sc">%&gt;%</span></span>
<span id="cb61-125"><a href="#cb61-125" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(),</span>
<span id="cb61-126"><a href="#cb61-126" aria-hidden="true" tabindex="-1"></a>            <span class="at">percentage =</span> <span class="fu">round</span>((<span class="fu">n</span>()<span class="sc">/</span> <span class="fu">nrow</span>(health)), <span class="at">digits =</span> <span class="dv">4</span>))</span>
<span id="cb61-127"><a href="#cb61-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-128"><a href="#cb61-128" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pink"</span>, <span class="st">"cyan"</span>, <span class="st">"blue"</span>)  <span class="co"># Define colors for the pie chart</span></span>
<span id="cb61-129"><a href="#cb61-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-130"><a href="#cb61-130" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the pie chart using the pie() function</span></span>
<span id="cb61-131"><a href="#cb61-131" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(Health_SummaryStat2<span class="sc">$</span>percentage, <span class="at">labels =</span> Health_SummaryStat2<span class="sc">$</span>Depression,</span>
<span id="cb61-132"><a href="#cb61-132" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> colors,</span>
<span id="cb61-133"><a href="#cb61-133" aria-hidden="true" tabindex="-1"></a>    <span class="at">main =</span> <span class="st">"Pie Chart of Depression"</span>,</span>
<span id="cb61-134"><a href="#cb61-134" aria-hidden="true" tabindex="-1"></a>    <span class="at">cex.main =</span> <span class="fl">1.2</span>,</span>
<span id="cb61-135"><a href="#cb61-135" aria-hidden="true" tabindex="-1"></a>    <span class="at">cex.lab =</span> <span class="fl">1.2</span>)</span>
<span id="cb61-136"><a href="#cb61-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-137"><a href="#cb61-137" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a legend</span></span>
<span id="cb61-138"><a href="#cb61-138" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> Health_SummaryStat2<span class="sc">$</span>Depression,</span>
<span id="cb61-139"><a href="#cb61-139" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> colors, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb61-140"><a href="#cb61-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-141"><a href="#cb61-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-142"><a href="#cb61-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-143"><a href="#cb61-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-144"><a href="#cb61-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-147"><a href="#cb61-147" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-148"><a href="#cb61-148" aria-hidden="true" tabindex="-1"></a>health <span class="sc">%&gt;%</span></span>
<span id="cb61-149"><a href="#cb61-149" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Gender, Depression, <span class="at">sort =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb61-150"><a href="#cb61-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Gender) <span class="sc">%&gt;%</span></span>
<span id="cb61-151"><a href="#cb61-151" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)), <span class="at">digits =</span> <span class="dv">4</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb61-152"><a href="#cb61-152" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Gender, <span class="at">y =</span> prop, <span class="at">fill =</span> Depression)) <span class="sc">+</span></span>
<span id="cb61-153"><a href="#cb61-153" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb61-154"><a href="#cb61-154" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(Gender, prop <span class="sc">*</span> <span class="dv">100</span>, <span class="st">"%"</span>)), <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb61-155"><a href="#cb61-155" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Barplot of Depression amongst Genders"</span>) <span class="sc">+</span></span>
<span id="cb61-156"><a href="#cb61-156" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-157"><a href="#cb61-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-158"><a href="#cb61-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-161"><a href="#cb61-161" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-162"><a href="#cb61-162" aria-hidden="true" tabindex="-1"></a>health <span class="sc">%&gt;%</span></span>
<span id="cb61-163"><a href="#cb61-163" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(CGPA, Depression, <span class="at">sort =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb61-164"><a href="#cb61-164" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)), <span class="at">digits =</span> <span class="dv">4</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb61-165"><a href="#cb61-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> CGPA, <span class="at">y =</span> proportion, <span class="at">fill =</span> Depression)) <span class="sc">+</span></span>
<span id="cb61-166"><a href="#cb61-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb61-167"><a href="#cb61-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Barplot of Depression vs CGPA"</span>) <span class="sc">+</span></span>
<span id="cb61-168"><a href="#cb61-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-169"><a href="#cb61-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-170"><a href="#cb61-170" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-171"><a href="#cb61-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-174"><a href="#cb61-174" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-175"><a href="#cb61-175" aria-hidden="true" tabindex="-1"></a>health <span class="sc">%&gt;%</span></span>
<span id="cb61-176"><a href="#cb61-176" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">'BIT|KOE|BCS|Engineering|Biomedical science'</span>, Course)) <span class="sc">%&gt;%</span></span>
<span id="cb61-177"><a href="#cb61-177" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Course, Depression, <span class="at">sort =</span> T) <span class="sc">%&gt;%</span></span>
<span id="cb61-178"><a href="#cb61-178" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Course) <span class="sc">%&gt;%</span></span>
<span id="cb61-179"><a href="#cb61-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)), <span class="at">digits =</span> <span class="dv">4</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb61-180"><a href="#cb61-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Course, <span class="at">y =</span> n, <span class="at">fill =</span> Depression)) <span class="sc">+</span></span>
<span id="cb61-181"><a href="#cb61-181" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb61-182"><a href="#cb61-182" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(Course, n)),</span>
<span id="cb61-183"><a href="#cb61-183" aria-hidden="true" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb61-184"><a href="#cb61-184" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb61-185"><a href="#cb61-185" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Barplot of Depression amongst the top 5 Courses"</span>) <span class="sc">+</span></span>
<span id="cb61-186"><a href="#cb61-186" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-187"><a href="#cb61-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-188"><a href="#cb61-188" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-189"><a href="#cb61-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-192"><a href="#cb61-192" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-193"><a href="#cb61-193" aria-hidden="true" tabindex="-1"></a>health[,<span class="fu">c</span>(<span class="dv">5</span>)] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(health[,<span class="fu">c</span>(<span class="dv">5</span>)], <span class="cf">function</span>(x)</span>
<span id="cb61-194"><a href="#cb61-194" aria-hidden="true" tabindex="-1"></a><span class="fu">recode</span>(x,<span class="st">"year 1"</span> <span class="ot">=</span> <span class="dv">1</span>,<span class="st">"year 2"</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">"year 3"</span> <span class="ot">=</span> <span class="dv">3</span> , <span class="st">"year 4"</span> <span class="ot">=</span> <span class="dv">4</span>, <span class="st">"Year 1"</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">"Year 2"</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">"Year 3"</span> <span class="ot">=</span> <span class="dv">3</span>))</span>
<span id="cb61-195"><a href="#cb61-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-196"><a href="#cb61-196" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-197"><a href="#cb61-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-198"><a href="#cb61-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-199"><a href="#cb61-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-202"><a href="#cb61-202" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-203"><a href="#cb61-203" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(health<span class="sc">$</span>CGPA)</span>
<span id="cb61-204"><a href="#cb61-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-205"><a href="#cb61-205" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-206"><a href="#cb61-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-207"><a href="#cb61-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-210"><a href="#cb61-210" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-211"><a href="#cb61-211" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb61-212"><a href="#cb61-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-213"><a href="#cb61-213" aria-hidden="true" tabindex="-1"></a><span class="co"># Example data</span></span>
<span id="cb61-214"><a href="#cb61-214" aria-hidden="true" tabindex="-1"></a>CGPA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"3.00 - 3.49"</span>,<span class="st">"3.50 - 4.00"</span>, <span class="st">"2.50 - 2.99"</span> ,<span class="st">"2.00 - 2.49"</span> ,<span class="st">"0 - 1.99"</span>   )</span>
<span id="cb61-215"><a href="#cb61-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-216"><a href="#cb61-216" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to convert CGPA range to numeric</span></span>
<span id="cb61-217"><a href="#cb61-217" aria-hidden="true" tabindex="-1"></a>convertCGPA <span class="ot">&lt;-</span> <span class="cf">function</span>(cgpa) {</span>
<span id="cb61-218"><a href="#cb61-218" aria-hidden="true" tabindex="-1"></a>  lower <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">str_extract</span>(cgpa, <span class="st">"</span><span class="sc">\\</span><span class="st">d+</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">d+"</span>))</span>
<span id="cb61-219"><a href="#cb61-219" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(lower)</span>
<span id="cb61-220"><a href="#cb61-220" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb61-221"><a href="#cb61-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-222"><a href="#cb61-222" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the conversion function to CGPA column</span></span>
<span id="cb61-223"><a href="#cb61-223" aria-hidden="true" tabindex="-1"></a>converted_CGPA <span class="ot">&lt;-</span> <span class="fu">sapply</span>(CGPA, convertCGPA)</span>
<span id="cb61-224"><a href="#cb61-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-225"><a href="#cb61-225" aria-hidden="true" tabindex="-1"></a><span class="co"># Output</span></span>
<span id="cb61-226"><a href="#cb61-226" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(converted_CGPA)</span>
<span id="cb61-227"><a href="#cb61-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-228"><a href="#cb61-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-231"><a href="#cb61-231" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-232"><a href="#cb61-232" aria-hidden="true" tabindex="-1"></a>health[,<span class="fu">c</span>(<span class="dv">6</span>)] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(health[,<span class="fu">c</span>(<span class="dv">6</span>)], <span class="cf">function</span>(x)</span>
<span id="cb61-233"><a href="#cb61-233" aria-hidden="true" tabindex="-1"></a><span class="fu">recode</span>(x,<span class="st">"3.00 - 3.49"</span> <span class="ot">=</span> <span class="fl">3.00</span>,<span class="st">"3.50 - 4.00"</span> <span class="ot">=</span> <span class="fl">3.50</span>, <span class="st">"2.50 - 2.99"</span> <span class="ot">=</span> <span class="fl">2.50</span> , <span class="st">"2.00 - 2.49"</span> <span class="ot">=</span> <span class="fl">2.00</span>, <span class="st">"0 - 1.99"</span> <span class="ot">=</span> <span class="fl">1.99</span>  ))</span>
<span id="cb61-234"><a href="#cb61-234" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-235"><a href="#cb61-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-238"><a href="#cb61-238" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-239"><a href="#cb61-239" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">select</span>(health,<span class="at">Age=</span>Age, <span class="at">Gender=</span>Gender,<span class="at">CGPA=</span> CGPA, <span class="at">Course=</span>Course,<span class="at">Married=</span>Married, <span class="at">Depression=</span>Depression, <span class="at">Anxiety=</span>Anxiety, <span class="at">Panic_Attack =</span> Panic_Attack,<span class="at">Treatment=</span>Treatment)</span>
<span id="cb61-240"><a href="#cb61-240" aria-hidden="true" tabindex="-1"></a><span class="in">```</span>   </span>
<span id="cb61-241"><a href="#cb61-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-242"><a href="#cb61-242" aria-hidden="true" tabindex="-1"></a>Create Logistic Regression Model</span>
<span id="cb61-243"><a href="#cb61-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-244"><a href="#cb61-244" aria-hidden="true" tabindex="-1"></a>Logistic regression is a statistical modeling technique used to predict the probability of an event occurring. It is commonly used when the dependent variable is binary or categorical. The model estimates the relationship between the independent variables and the log-odds of the event, using the logistic function. The logistic function maps the linear combination of predictors to a value between 0 and 1, representing the probability of the event.</span>
<span id="cb61-245"><a href="#cb61-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-246"><a href="#cb61-246" aria-hidden="true" tabindex="-1"></a><span class="fu"># Logistic Regression Assumptions</span></span>
<span id="cb61-247"><a href="#cb61-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-248"><a href="#cb61-248" aria-hidden="true" tabindex="-1"></a>The first assumption is that there is a linear relationship between continuous independent variables and the logit of the outcome variable.</span>
<span id="cb61-249"><a href="#cb61-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-250"><a href="#cb61-250" aria-hidden="true" tabindex="-1"></a>Independence of errors requires that there be no dependence between samples in the model, i.e. using the same individuals at different times.</span>
<span id="cb61-251"><a href="#cb61-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-252"><a href="#cb61-252" aria-hidden="true" tabindex="-1"></a>Multicollinearity refers to a relationship (correlation) between the independent variables and must be excluded from logistic regression models</span>
<span id="cb61-253"><a href="#cb61-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-254"><a href="#cb61-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-255"><a href="#cb61-255" aria-hidden="true" tabindex="-1"></a><span class="fu"># Multiple logistic regression</span></span>
<span id="cb61-256"><a href="#cb61-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-257"><a href="#cb61-257" aria-hidden="true" tabindex="-1"></a>The multiple logistic regression is used to predict the probability of class membership based on multiple predictor variables, as follow:</span>
<span id="cb61-258"><a href="#cb61-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-259"><a href="#cb61-259" aria-hidden="true" tabindex="-1"></a><span class="fu"># Model 1</span></span>
<span id="cb61-260"><a href="#cb61-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-261"><a href="#cb61-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-262"><a href="#cb61-262" aria-hidden="true" tabindex="-1"></a>A logistic regression is said to provide a better fit to the data if it demonstrates an improvement over a model with fewer predictors. This is performed using the likelihood ratio test, which compares the likelihood of the data under the full model against the likelihood of the data under a model with fewer predictors. Removing predictor variables from a model will almost always make the model fit less well (i.e. a model will have a lower log likelihood), but it is necessary to test whether the observed difference in model fit is statistically significant.</span>
<span id="cb61-263"><a href="#cb61-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-266"><a href="#cb61-266" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-267"><a href="#cb61-267" aria-hidden="true" tabindex="-1"></a>train_data<span class="sc">$</span>CGPA <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(train_data<span class="sc">$</span>CGPA <span class="sc">&gt;=</span> <span class="fl">3.00</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb61-268"><a href="#cb61-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-269"><a href="#cb61-269" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-270"><a href="#cb61-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-273"><a href="#cb61-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-274"><a href="#cb61-274" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit logistic regression models</span></span>
<span id="cb61-275"><a href="#cb61-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-276"><a href="#cb61-276" aria-hidden="true" tabindex="-1"></a><span class="co"># Research Question 1: Why is there a significant correlation between mental health status and CGPA among university students?</span></span>
<span id="cb61-277"><a href="#cb61-277" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CGPA <span class="sc">~</span> Anxiety, <span class="at">data =</span> train_data, <span class="at">family =</span> binomial)</span>
<span id="cb61-278"><a href="#cb61-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-279"><a href="#cb61-279" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the model summaries</span></span>
<span id="cb61-280"><a href="#cb61-280" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span>
<span id="cb61-281"><a href="#cb61-281" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-282"><a href="#cb61-282" aria-hidden="true" tabindex="-1"></a>Based on the output, the model suggests that there is no statistically significant association between Anxiety (as a predictor) and CGPA. The p-value for the AnxietyYes coefficient (p = 0.129) is greater than the conventional significance level (e.g., 0.05), indicating that the relationship between Anxiety and CGPA is not statistically significant in this model.</span>
<span id="cb61-283"><a href="#cb61-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-286"><a href="#cb61-286" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-287"><a href="#cb61-287" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AIC and BIC</span></span>
<span id="cb61-288"><a href="#cb61-288" aria-hidden="true" tabindex="-1"></a>AIC_val <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model1)</span>
<span id="cb61-289"><a href="#cb61-289" aria-hidden="true" tabindex="-1"></a>BIC_val <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model1)</span>
<span id="cb61-290"><a href="#cb61-290" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AIC:"</span>, AIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb61-291"><a href="#cb61-291" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"BIC:"</span>, BIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb61-292"><a href="#cb61-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-293"><a href="#cb61-293" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-294"><a href="#cb61-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-297"><a href="#cb61-297" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-298"><a href="#cb61-298" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CGPA <span class="sc">~</span> Depression, <span class="at">data =</span> train_data, <span class="at">family =</span> binomial)</span>
<span id="cb61-299"><a href="#cb61-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-300"><a href="#cb61-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-301"><a href="#cb61-301" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the model summaries</span></span>
<span id="cb61-302"><a href="#cb61-302" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span>
<span id="cb61-303"><a href="#cb61-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-304"><a href="#cb61-304" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-305"><a href="#cb61-305" aria-hidden="true" tabindex="-1"></a>Based on the output, the model suggests that there is no statistically significant association between Depression (as a predictor) and CGPA. The p-value for the DepressionYes coefficient (p = 0.745) is greater than the conventional significance level (e.g., 0.05), indicating that the relationship between Depression and CGPA is not statistically significant in this model.</span>
<span id="cb61-306"><a href="#cb61-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-309"><a href="#cb61-309" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-310"><a href="#cb61-310" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AIC and BIC</span></span>
<span id="cb61-311"><a href="#cb61-311" aria-hidden="true" tabindex="-1"></a>AIC_val <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model1)</span>
<span id="cb61-312"><a href="#cb61-312" aria-hidden="true" tabindex="-1"></a>BIC_val <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model1)</span>
<span id="cb61-313"><a href="#cb61-313" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AIC:"</span>, AIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb61-314"><a href="#cb61-314" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"BIC:"</span>, BIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb61-315"><a href="#cb61-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-316"><a href="#cb61-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-317"><a href="#cb61-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-320"><a href="#cb61-320" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-321"><a href="#cb61-321" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CGPA <span class="sc">~</span> Panic_Attack, <span class="at">data =</span> train_data, <span class="at">family =</span> binomial)</span>
<span id="cb61-322"><a href="#cb61-322" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span>
<span id="cb61-323"><a href="#cb61-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-324"><a href="#cb61-324" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-325"><a href="#cb61-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-328"><a href="#cb61-328" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-329"><a href="#cb61-329" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AIC and BIC</span></span>
<span id="cb61-330"><a href="#cb61-330" aria-hidden="true" tabindex="-1"></a>AIC_val <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model1)</span>
<span id="cb61-331"><a href="#cb61-331" aria-hidden="true" tabindex="-1"></a>BIC_val <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model1)</span>
<span id="cb61-332"><a href="#cb61-332" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AIC:"</span>, AIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb61-333"><a href="#cb61-333" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"BIC:"</span>, BIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb61-334"><a href="#cb61-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-335"><a href="#cb61-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-336"><a href="#cb61-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-337"><a href="#cb61-337" aria-hidden="true" tabindex="-1"></a>Based on the output you shared, the model suggests that there is no statistically significant association between Panic_Attack (as a predictor) and CGPA. The p-value for the Panic_AttackYes coefficient (p = 0.228) is greater than the conventional significance level (e.g., 0.05), indicating that the relationship between Panic_Attack and CGPA is not statistically significant in this model.</span>
<span id="cb61-338"><a href="#cb61-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-339"><a href="#cb61-339" aria-hidden="true" tabindex="-1"></a>After performing logistic regression, based on these results, it can be concluded that the research question of whether there is a significant correlation between mental health status and CGPA among university students is not supported. This implies that anxiety,Panic attack,Depression levels alone may not have a direct impact on students' academic performance, as measured by CGPA, in the context of this study.</span>
<span id="cb61-340"><a href="#cb61-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-341"><a href="#cb61-341" aria-hidden="true" tabindex="-1"></a>Model 2:</span>
<span id="cb61-342"><a href="#cb61-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-345"><a href="#cb61-345" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-346"><a href="#cb61-346" aria-hidden="true" tabindex="-1"></a><span class="co"># Research Question 2: How does the use of mental health resources, such as counseling or therapy, have a positive impact on academic performance?</span></span>
<span id="cb61-347"><a href="#cb61-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-348"><a href="#cb61-348" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CGPA <span class="sc">~</span> Treatment, <span class="at">data =</span> train_data, <span class="at">family =</span> binomial)</span>
<span id="cb61-349"><a href="#cb61-349" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span>
<span id="cb61-350"><a href="#cb61-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-351"><a href="#cb61-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-352"><a href="#cb61-352" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-353"><a href="#cb61-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-356"><a href="#cb61-356" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-357"><a href="#cb61-357" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AIC and BIC</span></span>
<span id="cb61-358"><a href="#cb61-358" aria-hidden="true" tabindex="-1"></a>AIC_val <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model2)</span>
<span id="cb61-359"><a href="#cb61-359" aria-hidden="true" tabindex="-1"></a>BIC_val <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model2)</span>
<span id="cb61-360"><a href="#cb61-360" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AIC:"</span>, AIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb61-361"><a href="#cb61-361" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"BIC:"</span>, BIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb61-362"><a href="#cb61-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-363"><a href="#cb61-363" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-364"><a href="#cb61-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-365"><a href="#cb61-365" aria-hidden="true" tabindex="-1"></a>After performing the logistic regression, Based on results the relationship between the use of mental health resources (Treatment) and CGPA, the coefficient for Treatment (TreatmentYes) is not statistically significant at conventional levels (p = 0.0721). This suggests that there is no strong evidence to support the hypothesis that the use of mental health resources, such as counseling or therapy, has a positive impact on academic performance, as measured by CGPA.</span>
<span id="cb61-366"><a href="#cb61-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-367"><a href="#cb61-367" aria-hidden="true" tabindex="-1"></a>It is important to note that the p-value is relatively close to the conventional significance level of 0.05. This indicates a marginal level of significance, suggesting that there might be a weak relationship between the use of mental health resources and CGPA, but the evidence is not strong enough to conclude a significant positive impact on academic performance.</span>
<span id="cb61-368"><a href="#cb61-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-369"><a href="#cb61-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-372"><a href="#cb61-372" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-373"><a href="#cb61-373" aria-hidden="true" tabindex="-1"></a>health[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">7</span><span class="sc">:</span><span class="dv">11</span>)] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(health[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">7</span><span class="sc">:</span><span class="dv">11</span>)], <span class="cf">function</span>(x)</span>
<span id="cb61-374"><a href="#cb61-374" aria-hidden="true" tabindex="-1"></a><span class="fu">recode</span>(x,<span class="st">"Yes"</span> <span class="ot">=</span> <span class="dv">1</span>,<span class="st">"No"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"Female"</span> <span class="ot">=</span> <span class="dv">1</span> , <span class="st">"Male"</span> <span class="ot">=</span> <span class="dv">0</span>))</span>
<span id="cb61-375"><a href="#cb61-375" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-376"><a href="#cb61-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-377"><a href="#cb61-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-378"><a href="#cb61-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-381"><a href="#cb61-381" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-382"><a href="#cb61-382" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(health<span class="sc">$</span>Panic_Attack, health<span class="sc">$</span>Anxiety)</span>
<span id="cb61-383"><a href="#cb61-383" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(correlation)</span>
<span id="cb61-384"><a href="#cb61-384" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-385"><a href="#cb61-385" aria-hidden="true" tabindex="-1"></a>The correlation coefficient of 0.08447828 suggests a weak positive correlation between 'Panic_Attack' and 'Anxiety' in the data.So i will not include panic attacks</span>
<span id="cb61-386"><a href="#cb61-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-387"><a href="#cb61-387" aria-hidden="true" tabindex="-1"></a>Model 3:</span>
<span id="cb61-388"><a href="#cb61-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-391"><a href="#cb61-391" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-392"><a href="#cb61-392" aria-hidden="true" tabindex="-1"></a><span class="co"># Research Question 3: How does demographic factors, such as gender or ethnicity, influence the relationship between mental health and academic performance?</span></span>
<span id="cb61-393"><a href="#cb61-393" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CGPA <span class="sc">~</span> Gender <span class="sc">+</span> Anxiety <span class="sc">+</span>Age <span class="sc">+</span> Course <span class="sc">+</span> Married <span class="sc">+</span> Depression, <span class="at">data =</span> train_data, <span class="at">family =</span> binomial)</span>
<span id="cb61-394"><a href="#cb61-394" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span>
<span id="cb61-395"><a href="#cb61-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-396"><a href="#cb61-396" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-397"><a href="#cb61-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-398"><a href="#cb61-398" aria-hidden="true" tabindex="-1"></a>Hypothesis testing</span>
<span id="cb61-401"><a href="#cb61-401" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-402"><a href="#cb61-402" aria-hidden="true" tabindex="-1"></a>anova_test <span class="ot">&lt;-</span> <span class="fu">anova</span>(model3, <span class="at">test =</span> <span class="st">"Chi"</span>)</span>
<span id="cb61-403"><a href="#cb61-403" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(anova_test)</span>
<span id="cb61-404"><a href="#cb61-404" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-405"><a href="#cb61-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-406"><a href="#cb61-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-409"><a href="#cb61-409" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-410"><a href="#cb61-410" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AIC and BIC</span></span>
<span id="cb61-411"><a href="#cb61-411" aria-hidden="true" tabindex="-1"></a>AIC_val <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model3)</span>
<span id="cb61-412"><a href="#cb61-412" aria-hidden="true" tabindex="-1"></a>BIC_val <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model3)</span>
<span id="cb61-413"><a href="#cb61-413" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AIC:"</span>, AIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb61-414"><a href="#cb61-414" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"BIC:"</span>, BIC_val, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb61-415"><a href="#cb61-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-416"><a href="#cb61-416" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-417"><a href="#cb61-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-418"><a href="#cb61-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-419"><a href="#cb61-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-420"><a href="#cb61-420" aria-hidden="true" tabindex="-1"></a>Based on the logistic regression results, the relationship between demographic factors (Gender, Age, Course, Married) and mental health variables (Anxiety, Depression, Panic_Attack) with CGPA, it seems that several coefficients are not statistically significant at conventional levels. This means that there is no strong evidence to support the hypothesis that these demographic factors significantly influence the relationship between mental health and academic performance, as measured by CGPA.</span>
<span id="cb61-421"><a href="#cb61-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-422"><a href="#cb61-422" aria-hidden="true" tabindex="-1"></a>Specifically, the coefficients for Gender Male (p = 0.564), Age (p = 0.968), Course (multiple categories with p-values close to 1.000), and MarriedYes (p = 0.949) are not statistically significant. Similarly, the coefficients for Anxiety Yes (p = 0.181), Depression Yes (p = 0.860), and Panic Attack Yes (p = 0.170) are not statistically significant.</span>
<span id="cb61-423"><a href="#cb61-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-424"><a href="#cb61-424" aria-hidden="true" tabindex="-1"></a>These results suggest that based on the variables included in the model, there is no strong evidence to support the influence of gender, age, course, or marital status on the relationship between mental health variables and academic performance.</span>
<span id="cb61-425"><a href="#cb61-425" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>