<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Young Soo Choi">
<meta name="dcterms.date" content="2023-05-22">
<meta name="description" content="Final Project">

<title>The effect of a manager’s intervention in the game on the team’s scoring ability in the KBO League</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta name="twitter:title" content="The effect of a manager’s intervention in the game on the team’s scoring ability in the KBO League">
<meta name="twitter:description" content="Final Project">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/FP_young_files/figure-html/unnamed-chunk-4-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#intro" id="toc-intro" class="nav-link active" data-scroll-target="#intro">Intro</a>
  <ul class="collapse">
  <li><a href="#research-problems" id="toc-research-problems" class="nav-link" data-scroll-target="#research-problems">Research Problems</a></li>
  <li><a href="#major-concepts" id="toc-major-concepts" class="nav-link" data-scroll-target="#major-concepts">Major Concepts</a></li>
  <li><a href="#hypothesis-and-research-design" id="toc-hypothesis-and-research-design" class="nav-link" data-scroll-target="#hypothesis-and-research-design">Hypothesis and Research Design</a></li>
  </ul></li>
  <li><a href="#looking-at-the-data" id="toc-looking-at-the-data" class="nav-link" data-scroll-target="#looking-at-the-data">Looking at the Data</a>
  <ul class="collapse">
  <li><a href="#operational-definition" id="toc-operational-definition" class="nav-link" data-scroll-target="#operational-definition">Operational Definition</a></li>
  <li><a href="#data-load" id="toc-data-load" class="nav-link" data-scroll-target="#data-load">Data Load</a></li>
  <li><a href="#looking-at-the-average-intervention-by-year" id="toc-looking-at-the-average-intervention-by-year" class="nav-link" data-scroll-target="#looking-at-the-average-intervention-by-year">Looking at the average intervention by year</a></li>
  </ul></li>
  <li><a href="#hypothesis-testing-haactual-scores" id="toc-hypothesis-testing-haactual-scores" class="nav-link" data-scroll-target="#hypothesis-testing-haactual-scores">Hypothesis Testing: Ha(Actual Scores)</a>
  <ul class="collapse">
  <li><a href="#ha-1" id="toc-ha-1" class="nav-link" data-scroll-target="#ha-1">Ha-1</a></li>
  <li><a href="#ha-2" id="toc-ha-2" class="nav-link" data-scroll-target="#ha-2">Ha-2</a></li>
  </ul></li>
  <li><a href="#hypothesis-testing-hbexpected-scores" id="toc-hypothesis-testing-hbexpected-scores" class="nav-link" data-scroll-target="#hypothesis-testing-hbexpected-scores">Hypothesis Testing: Hb(Expected Scores)</a>
  <ul class="collapse">
  <li><a href="#expected-run-scored" id="toc-expected-run-scored" class="nav-link" data-scroll-target="#expected-run-scored">Expected Run Scored</a></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison">Model Comparison</a></li>
  <li><a href="#hb-1" id="toc-hb-1" class="nav-link" data-scroll-target="#hb-1">Hb-1</a></li>
  <li><a href="#hb-2" id="toc-hb-2" class="nav-link" data-scroll-target="#hb-2">Hb-2</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#regarding-ha" id="toc-regarding-ha" class="nav-link" data-scroll-target="#regarding-ha">Regarding Ha</a></li>
  <li><a href="#regarding-hb" id="toc-regarding-hb" class="nav-link" data-scroll-target="#regarding-hb">Regarding Hb</a></li>
  <li><a href="#discussions" id="toc-discussions" class="nav-link" data-scroll-target="#discussions">Discussions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">The effect of a manager’s intervention in the game on the team’s scoring ability in the KBO League</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">final project</div>
  </div>
  </div>

<div>
  <div class="description">
    Final Project
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Young Soo Choi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 22, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="intro" class="level1">
<h1>Intro</h1>
<section id="research-problems" class="level2">
<h2 class="anchored" data-anchor-id="research-problems">Research Problems</h2>
<p>The debate about the role of a manager in baseball games has always been a hot potato. In the case of the United States, MLB(Major League Baseball), various quantitative analyses have been conducted on this topic since the famous Moneyball(2004, Lewis, M.), and most studies conclude that the role of the coach in the team’s victory or defeat is not significant.</p>
<p>Then, what is the case in Korea? Baseball is also prevalent in Korea as the most popular professional sport, and quantitative analysis has been conducted on these topics along with the activation of data analysis techniques over the past decade. However, the number is not large, but if you look at representative studies, there is a result of studying the difference in team performance according to the manager’s tendency.(Lee, Kim, and Lee, 2007)</p>
<p>If so, what is the relationship between the specific manager’s behavior and the team’s performance, other than the relationship between the manager’s tendency and performance? More specifically, does the team’s performance improve if the manager intervenes a lot in the game? Unfortunately, it was difficult to find a study on these problems targeting KBO(Korean Baseball Organization) league in Korea.</p>
<p>With this awareness of the problem, this study aims to check whether the manager’s intervention improves the team’s performance in baseball games in Korean professional baseball(KBO league). In other words, the research question is, <strong>“What is the relationship between the manager’s intervention and the team’s performance in the KBO League?”</strong></p>
</section>
<section id="major-concepts" class="level2">
<h2 class="anchored" data-anchor-id="major-concepts">Major Concepts</h2>
<p>Before review the problem, let’s look at some important concepts. First of all, baseball’s team performance is divided into wins and losses, and of course, the more wins, the better. And the victory of the game is given to the team that scores more points, so the team’s performance is more advantageous the more points they score and allow fewer runs. In addition, the manager of baseball directs the overall game, such as setting the team’s batting order and replacing pitchers at an appropriate time, and in terms of offense, he can directly intervene in the game through various operations such as bunt and steal direction. Finally, the KBO League is a Korean professional baseball league that started with six teams in 1982, and 10 teams have been participating since 2015. Currently, each team plays 144 games in a season, with a total of 720 games.</p>
</section>
<section id="hypothesis-and-research-design" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-and-research-design">Hypothesis and Research Design</h2>
<p>Based on the research problems and major concepts discussed above, the hypothesis of this study was established as follows.</p>
<p><strong>Ha-1: In the KBO League, teams with a lot of managers’ intervention in games have higher scoring ability than teams that do not.</strong></p>
<p><em>(High Group Average Score &gt; Normal Group Average Score &gt; Low Group Average Score)</em></p>
<p><strong>Ha-2: In the KBO League, the more the manager intervenes in the game, the higher the team’s scoring ability.</strong></p>
<p><em>(In the regression model of scoring and intervention, regression coefficient for intervention &gt; 0)</em></p>
<p><strong>Hb-1: In the KBO League, the difference between the actual score and the expected score of the team with a lot of intervention in the game will be greater than that of the team that does not.</strong></p>
<p><em>(The difference between the actual score and the expected score of high group &gt; The difference between the actual score and the expected score of normal group &gt; The difference between the actual score and the expected score of low group)</em></p>
<p><strong>Hb-2: In the KBO League, the more interventions there are in the game, the greater the difference between actual scores and expected scores.</strong></p>
<p><em>(In the regression model of the difference between the actual score and the expected score and intervention, regression coefficient for intervention &gt; 0)</em></p>
<p>Since baseball games are quite complex, I would like to verify research problems in various ways. Therefore, hypotheses were also defined in four forms as above.</p>
<p>For Ha-1, teams will be classified according to the frequency of game intervention and the average of which groups have a high average score will be compared. For Ha-2, we will conduct a regression analysis on how the team’s average score moves as the game intervention increases.</p>
<p>For Hb, we will use the concept of expected score. Expected score refers to the expected score considering the team’s basic offensive power, and an expected score generation formula can be obtained through regression analysis using batting indicators such as batting average and slugging rate. From this point of view, the manager’s intervention can confirm whether the team’s actual score is higher or lower than the team’s expected score.</p>
<p>Hb-1 will classify groups according to the frequency of intervention in the game, such as Ha-1, and compare the average of the expected scores of the teams in each group with the actual scores. Like Ha-2, Hb-2 will be analyzed the difference between the team’s actual score and the expected score depending on the degree of intervention in the game using regression.</p>
</section>
</section>
<section id="looking-at-the-data" class="level1">
<h1>Looking at the Data</h1>
<section id="operational-definition" class="level2">
<h2 class="anchored" data-anchor-id="operational-definition">Operational Definition</h2>
<p>Until now, the concept of manager’s intervention in the game has been used. But how can we measure this. In fact, it is a subject that allows for extensive research on this alone. However, in this study, to simplify the analysis, I would like to operatively define it so that existing data can be used as it is. In other words, the team’s annual bunt(sacrifice hit, sh) and steal attempts(steal, st + stolen caught, sc) are defined as the manager’s intervention in the game.</p>
</section>
<section id="data-load" class="level2">
<h2 class="anchored" data-anchor-id="data-load">Data Load</h2>
<p>Before the full-fledged analysis, I would like to set the scope of the study first. Baseball shows quite different aspects from time to time, especially the average score showing quite differently from time to time. In particular, the KBO League has continued to expand its teams, and the proportion of stadiums used and foreign players has been determined every year. Considering this, only data after 2015 when the 10-team system was established will be used.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setenv</span>(<span class="at">LANG =</span> <span class="st">"en"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loading data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>kbo_df<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"~/R/603_Spring_2023/posts/_data/kbo_df.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 313 Columns: 28
── Column specification
────────────────────────────────────────────────────────
Delimiter: "," chr (1): team dbl (27): ...1, year, game, win, lose, tie,
run_scored, run_allowed, batters...
ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
Specify the column types or set `show_col_types = FALSE` to quiet this message.
• `` -&gt; `...1`</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>kbo_df<span class="ot">&lt;-</span>kbo_df[<span class="dv">254</span><span class="sc">:</span><span class="dv">313</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">28</span>]</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kbo_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 27
   year team   game   win  lose   tie run_scored run_allowed batters   tpa    ab
  &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  2015 Bears   144    79    65     0        807         776    1704  5759  4957
2  2015 Dinos   144    84    57     3        844         655    1960  5727  4967
3  2015 Eagl…   144    68    76     0        717         800    1899  5713  4850
4  2015 Gian…   144    66    77     1        765         802    1821  5680  4972
5  2015 Heros   144    78    65     1        904         790    1769  5811  5069
6  2015 Land…   144    69    73     2        693         724    1845  5588  4861
# ℹ 16 more variables: hit &lt;dbl&gt;, double &lt;dbl&gt;, triple &lt;dbl&gt;, hr &lt;dbl&gt;,
#   bb &lt;dbl&gt;, ibb &lt;dbl&gt;, hbp &lt;dbl&gt;, so &lt;dbl&gt;, rbi &lt;dbl&gt;, r &lt;dbl&gt;, sh &lt;dbl&gt;,
#   sf &lt;dbl&gt;, sb &lt;dbl&gt;, cs &lt;dbl&gt;, gidp &lt;dbl&gt;, e &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="looking-at-the-average-intervention-by-year" class="level2">
<h2 class="anchored" data-anchor-id="looking-at-the-average-intervention-by-year">Looking at the average intervention by year</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># making average variables by years</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># for sh</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="do">## create an empty data frame to store the results</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>sh_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">integer</span>(), <span class="at">avr_sh =</span> <span class="fu">numeric</span>())</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="do">## loop over the years</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2015</span><span class="sc">:</span><span class="dv">2020</span>) {</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="do">## filter the data for the current year and calculate the sum of sh variable</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  year_sh <span class="ot">&lt;-</span> kbo_df <span class="sc">%&gt;%</span> </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">==</span> i) <span class="sc">%&gt;%</span> </span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">year_av_sh =</span> <span class="fu">sum</span>(sh)<span class="sc">/</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(year_av_sh)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  <span class="do">## add the result to the data frame</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  sh_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(sh_df, <span class="fu">data.frame</span>(<span class="at">year =</span> i, <span class="at">avr_sh =</span> year_sh))</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="co"># for sb</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>sb_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">integer</span>(), <span class="at">avr_sb =</span> <span class="fu">numeric</span>())</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2015</span><span class="sc">:</span><span class="dv">2020</span>) {</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>  year_sb <span class="ot">&lt;-</span> kbo_df <span class="sc">%&gt;%</span> </span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">==</span> i) <span class="sc">%&gt;%</span> </span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">year_av_sb =</span> <span class="fu">sum</span>(sb)<span class="sc">/</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(year_av_sb)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>  sb_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(sb_df, <span class="fu">data.frame</span>(<span class="at">year=</span>i, <span class="at">avr_sb=</span>year_sb))</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a><span class="co"># for cs</span></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>cs_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">integer</span>(), <span class="at">avr_cs =</span> <span class="fu">numeric</span>())</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2015</span><span class="sc">:</span><span class="dv">2020</span>) {</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>  year_cs <span class="ot">&lt;-</span> kbo_df <span class="sc">%&gt;%</span> </span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">==</span> i) <span class="sc">%&gt;%</span> </span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">year_av_cs =</span> <span class="fu">sum</span>(cs)<span class="sc">/</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(year_av_cs)</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>  cs_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(cs_df, <span class="fu">data.frame</span>(<span class="at">year=</span>i, <span class="at">avr_cs=</span>year_cs))</span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print the results data frame</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>sa_df<span class="ot">&lt;-</span><span class="fu">left_join</span>(sb_df, cs_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(year)`</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sa_df<span class="ot">&lt;-</span><span class="fu">mutate</span>(sa_df, <span class="at">avr_sa=</span>avr_sb<span class="sc">+</span>avr_cs)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>int_da<span class="ot">&lt;-</span><span class="fu">left_join</span>(sh_df, sa_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(year)`</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>int_da<span class="ot">&lt;-</span><span class="fu">mutate</span>(int_da, <span class="at">avr_int=</span>avr_sh<span class="sc">+</span>avr_sa)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>int_da</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  year avr_sh avr_sb avr_cs avr_sa avr_int
1 2015   83.4  120.2   52.6  172.8   256.2
2 2016   65.1  105.8   54.7  160.5   225.6
3 2017   60.0   77.8   40.7  118.5   178.5
4 2018   44.7   92.8   41.0  133.8   178.5
5 2019   43.6   98.9   42.3  141.2   184.8
6 2020   48.6   89.2   37.7  126.9   175.5</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># drawing a graph</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(int_da, <span class="fu">aes</span>(<span class="at">x=</span>year)) <span class="sc">+</span> </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> avr_sh, <span class="at">color =</span> <span class="st">"Sacrifice Hit"</span>)) <span class="sc">+</span> </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> avr_sa, <span class="at">color=</span><span class="st">"Steal Attempts"</span>)) <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> avr_int, <span class="at">color =</span> <span class="st">"Total Intervention"</span>)) <span class="sc">+</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Trend of Game Intervention in KBO League"</span>, <span class="at">color =</span> <span class="st">"Variable"</span>, <span class="at">y =</span> <span class="st">"Average Value"</span>) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="st">""</span>, </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">breaks =</span> <span class="fu">c</span>(<span class="st">"Sacrifice Hit"</span>, <span class="st">"Steal Attempts"</span>, <span class="st">"Total Intervention"</span>),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"darkred"</span>, <span class="st">"steelblue"</span>, <span class="st">"purple"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FP_young_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looking at the frequency of intervention in the game since 2015, it can be seen that the overall trend has been downward, but the total frequency of intervention has been stable since 2017.</p>
</section>
</section>
<section id="hypothesis-testing-haactual-scores" class="level1">
<h1>Hypothesis Testing: Ha(Actual Scores)</h1>
<section id="ha-1" class="level2">
<h2 class="anchored" data-anchor-id="ha-1">Ha-1</h2>
<p>To verify Ha-1, each team by year is divided into three groups according to the frequency of game intervention. Teams with more than 1 sd intervention are assigned to the high group compared to the overall average frequency of intervention for the year. In the low group, on the contrary, fewer teams than 1 sd are involved, and the rest are assigned to the normal group.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># merge those data</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>int_df<span class="ot">&lt;-</span><span class="fu">merge</span>(<span class="fu">merge</span>(sh_df, sb_df, <span class="at">by =</span> <span class="st">"year"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>), cs_df, <span class="at">by=</span><span class="st">"year"</span>, <span class="at">all=</span><span class="cn">TRUE</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># left join to original data</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>tot_df<span class="ot">&lt;-</span><span class="fu">left_join</span>(kbo_df, int_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(year)`</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># making intervention variables</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>tot_df<span class="ot">&lt;-</span>tot_df <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">st_att=</span>sb<span class="sc">+</span>cs, <span class="at">inter =</span> sh<span class="sc">+</span>st_att, <span class="at">avr_inter=</span>avr_sh<span class="sc">+</span>avr_sb<span class="sc">+</span>avr_cs)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>tot_df[, <span class="fu">c</span>(<span class="st">'year'</span>,<span class="st">'team'</span>,<span class="st">'sh'</span>,<span class="st">'st_att'</span>,<span class="st">'inter'</span>,<span class="st">'avr_inter'</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 60 × 6
    year team       sh st_att inter avr_inter
   &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
 1  2015 Bears      75    158   233      256.
 2  2015 Dinos      64    264   328      256.
 3  2015 Eagles    139    127   266      256.
 4  2015 Giants     80    154   234      256.
 5  2015 Heros      61    147   208      256.
 6  2015 Landers   110    153   263      256.
 7  2015 Lions      76    209   285      256.
 8  2015 Tigers     79    165   244      256.
 9  2015 Twins      75    175   250      256.
10  2015 Wiz        75    176   251      256.
# ℹ 50 more rows</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># making sd of intervention by each year</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>sd_int<span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">integer</span>(), <span class="at">sd_i=</span> <span class="fu">numeric</span>())</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2015</span><span class="sc">:</span><span class="dv">2020</span>) {</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  year_sd <span class="ot">&lt;-</span> tot_df <span class="sc">%&gt;%</span> </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">==</span> i) <span class="sc">%&gt;%</span> </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">year_sd_int =</span> <span class="fu">sd</span>(inter)) <span class="sc">%&gt;%</span> </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(year_sd_int)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  sd_int<span class="ot">&lt;-</span> <span class="fu">rbind</span>(sd_int, <span class="fu">data.frame</span>(<span class="at">year =</span> i, <span class="at">sd_i=</span> year_sd))</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>tot_df<span class="ot">&lt;-</span><span class="fu">left_join</span>(tot_df, sd_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(year)`</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># making three type variables</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>tot_df<span class="ot">&lt;-</span>tot_df <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">inter_fre_sd=</span><span class="fu">ifelse</span>(inter<span class="sc">&gt;</span>avr_inter<span class="sc">+</span>sd_i, <span class="st">"high"</span>, </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">ifelse</span>(inter<span class="sc">&lt;</span>avr_inter<span class="sc">-</span>sd_i, <span class="st">"low"</span>, <span class="st">"normal"</span>)))</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>tot_df[, <span class="fu">c</span>(<span class="st">'year'</span>,<span class="st">'team'</span>,<span class="st">'run_scored'</span>, <span class="st">'inter_fre_sd'</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 60 × 4
    year team    run_scored inter_fre_sd
   &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;       
 1  2015 Bears          807 normal      
 2  2015 Dinos          844 high        
 3  2015 Eagles         717 normal      
 4  2015 Giants         765 normal      
 5  2015 Heros          904 low         
 6  2015 Landers        693 normal      
 7  2015 Lions          897 normal      
 8  2015 Tigers         648 normal      
 9  2015 Twins          653 normal      
10  2015 Wiz            670 normal      
# ℹ 50 more rows</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># making table</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(tot_df<span class="sc">$</span>inter_fre_sd, tot_df<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        
         2015 2016 2017 2018 2019 2020
  high      1    2    2    2    0    2
  low       1    2    1    1    2    2
  normal    8    6    7    7    8    6</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(tot_df<span class="sc">$</span>inter_fre_sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
  high    low normal 
     9      9     42 </code></pre>
</div>
</div>
<p>Of the 60 data in the six-year period, 9 were assigned to the high group and 9 to the low group, respectively, and the rest were normal groups. Now let’s verify the average difference between them.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the score by groups</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>tot_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(inter_fre_sd) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avr_run=</span><span class="fu">mean</span>(run_scored))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  inter_fre_sd avr_run
  &lt;chr&gt;          &lt;dbl&gt;
1 high            766.
2 low             748.
3 normal          755.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># anova</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>ha1<span class="ot">&lt;-</span><span class="fu">aov</span>(run_scored<span class="sc">~</span>inter_fre_sd, <span class="at">data=</span>tot_df)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ha1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)
inter_fre_sd  2   1478     739   0.084  0.919
Residuals    57 500775    8786               </code></pre>
</div>
</div>
<p>Looking at the average difference between each group, the high group has the highest average score and the low group has the lowest average score. In other words, when compared simply, the average score of the group with a lot of game intervention is higher. However, since the <strong>value of p as an AVONA result is 0.919</strong>, there is no statistical significance of this result.(at the 0.05 level of significance). In other words, it is difficult to accept it as a meaningful result.</p>
</section>
<section id="ha-2" class="level2">
<h2 class="anchored" data-anchor-id="ha-2">Ha-2</h2>
<p>Next, I will examine how game intervention has a relationship with scoring through regression analysis between game intervention and score.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regression</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>ha2<span class="ot">&lt;-</span><span class="fu">lm</span>(run_scored<span class="sc">~</span>inter, tot_df)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ha2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = run_scored ~ inter, data = tot_df)

Residuals:
     Min       1Q   Median       3Q      Max 
-192.376  -81.702    5.755   65.895  195.249 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 719.7232    58.6681  12.268   &lt;2e-16 ***
inter         0.1792     0.2874   0.624    0.535    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 92.75 on 58 degrees of freedom
Multiple R-squared:  0.006658,  Adjusted R-squared:  -0.01047 
F-statistic: 0.3888 on 1 and 58 DF,  p-value: 0.5354</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tot_df, <span class="fu">aes</span>(inter, run_scored),</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Intervention"</span>,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Run Scored"</span>) <span class="sc">+</span> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="fl">0.1792</span>, <span class="at">intercept =</span> <span class="fl">719.7232</span>, <span class="at">color =</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regression of Intervention and Run Scored in KBO League"</span>, <span class="at">x =</span> <span class="st">"Intervention"</span>, <span class="at">y =</span> <span class="st">"Run Scored"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FP_young_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Similar to the previous simple average comparison, the higher the number of interventions in the game, the higher the score. In other words, the coefficient of intervention in the game was 0.1792, indicating that the score per game increased by 0.1792 points. However, the R square value was 0.006658, and the randomness of game intervention was very low to explain the team’s score, and the <strong>p value of the slope of the regression equation was also 0.5354</strong>, which was not significant at the 0.05 level.</p>
<p>Next, I will check if there are any violations of various assumptions necessary for regression analysis.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the assumptions</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>))</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ha2, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FP_young_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As a result of the confirmation, there seems to be no particular violation.</p>
</section>
</section>
<section id="hypothesis-testing-hbexpected-scores" class="level1">
<h1>Hypothesis Testing: Hb(Expected Scores)</h1>
<section id="expected-run-scored" class="level2">
<h2 class="anchored" data-anchor-id="expected-run-scored">Expected Run Scored</h2>
<p>Next, I will analyze the effect of game intervention using expected scores. First, we need to look at the meaning of expected scores.</p>
<p>In baseball, scoring is done through a combination of various offensive acts. For example, if a home run comes out after a hit, you will get two points, but if a double play comes out after a hit, you will not be able to score and increase the out count by two. As such, each batting event is correlated with scoring, and this relationship can be used to obtain the team’s expected score, which can be said to show the team’s basic offensive power.</p>
<p>However, the question here is what variables will be used to predict the team’s expected score.</p>
<p>First, I obtained a regression equation between them and scoring using all batting indicators.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regression with every batting stat</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>exp_m_1<span class="ot">&lt;-</span><span class="fu">lm</span>(run_scored<span class="sc">~</span>hit<span class="sc">+</span>double<span class="sc">+</span>triple<span class="sc">+</span>hr<span class="sc">+</span>bb<span class="sc">+</span>ibb<span class="sc">+</span>hbp<span class="sc">+</span>so<span class="sc">+</span>sf<span class="sc">+</span>gidp, tot_df)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exp_m_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = run_scored ~ hit + double + triple + hr + bb + ibb + 
    hbp + so + sf + gidp, data = tot_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-54.750  -9.564   0.773  12.749  33.562 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -413.66438   82.53095  -5.012 7.42e-06 ***
hit            0.48736    0.05270   9.248 2.53e-12 ***
double         0.32361    0.15117   2.141   0.0373 *  
triple         1.10204    0.46735   2.358   0.0224 *  
hr             0.93490    0.11086   8.433 4.18e-11 ***
bb             0.45364    0.05571   8.143 1.16e-10 ***
ibb           -0.09291    0.56884  -0.163   0.8709    
hbp            0.26767    0.16555   1.617   0.1123    
so            -0.01222    0.04394  -0.278   0.7820    
sf             0.56138    0.39545   1.420   0.1621    
gidp          -0.08900    0.25885  -0.344   0.7325    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.79 on 49 degrees of freedom
Multiple R-squared:  0.9618,    Adjusted R-squared:  0.954 
F-statistic: 123.4 on 10 and 49 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Although the explanatory power was quite high (R square: 0.9618), the regression coefficient for some variables was not significant at the 0.05 level.</p>
<p>I will now refit the model except for those variables. The results are as follows.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regression with every significant batting stat</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>exp_m_1_m<span class="ot">&lt;-</span><span class="fu">lm</span>(run_scored<span class="sc">~</span>hit<span class="sc">+</span>double<span class="sc">+</span>triple<span class="sc">+</span>hr<span class="sc">+</span>bb, tot_df)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exp_m_1_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = run_scored ~ hit + double + triple + hr + bb, data = tot_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-47.545 -14.651   2.097  16.132  32.664 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -437.25592   46.03536  -9.498 4.10e-13 ***
hit            0.51153    0.04939  10.357 1.95e-14 ***
double         0.33971    0.14676   2.315 0.024455 *  
triple         1.48367    0.42211   3.515 0.000899 ***
hr             0.92489    0.09362   9.880 1.05e-13 ***
bb             0.46009    0.05072   9.072 1.91e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 20.15 on 54 degrees of freedom
Multiple R-squared:  0.9563,    Adjusted R-squared:  0.9523 
F-statistic: 236.6 on 5 and 54 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The regression coefficient of all variables is significant at the 0.05 level, and the R square value is 0.9563. Now let’s call this model <strong>EM 1</strong>(expected score model 1).</p>
<p>Next, I will find out the on-base percentage and slugging percentage, which can be said to be a combination of these indicators, and then check the relationship between scoring and them.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OBP = (Hits + Walks + Hit-by-Pitches) / (At-Bats + Walks + Hit-by-Pitches + Sacrifice Flies)</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>exp_df<span class="ot">&lt;-</span>tot_df <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">obp=</span>(hit<span class="sc">+</span>bb<span class="sc">+</span>ibb<span class="sc">+</span>hbp)<span class="sc">/</span>(ab<span class="sc">+</span>bb<span class="sc">+</span>ibb<span class="sc">+</span>hbp<span class="sc">+</span>sf))</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># SLG = (1B + 2B x 2 + 3B x 3 + HR x 4) / AB</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>exp_df<span class="ot">&lt;-</span>exp_df<span class="sc">%&gt;%</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tb=</span>hit<span class="sc">-</span>(double<span class="sc">+</span>triple<span class="sc">+</span>hr)<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>double<span class="sc">+</span><span class="dv">3</span><span class="sc">*</span>triple<span class="sc">+</span><span class="dv">4</span><span class="sc">*</span>hr)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>exp_df<span class="ot">&lt;-</span>exp_df<span class="sc">%&gt;%</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">slg=</span>tb<span class="sc">/</span>ab)</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>exp_df[,<span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"team"</span>, <span class="st">"run_scored"</span>, <span class="st">"obp"</span>, <span class="st">"slg"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 60 × 5
    year team    run_scored   obp   slg
   &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1  2015 Bears          807 0.373 0.435
 2  2015 Dinos          844 0.370 0.455
 3  2015 Eagles         717 0.364 0.405
 4  2015 Giants         765 0.358 0.446
 5  2015 Heros          904 0.374 0.486
 6  2015 Landers        693 0.350 0.410
 7  2015 Lions          897 0.380 0.469
 8  2015 Tigers         648 0.328 0.392
 9  2015 Twins          653 0.341 0.399
10  2015 Wiz            670 0.348 0.402
# ℹ 50 more rows</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting regression model using obp and slg</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>exp_m_2<span class="ot">&lt;-</span><span class="fu">lm</span>(run_scored<span class="sc">~</span>obp<span class="sc">+</span>slg, exp_df)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exp_m_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = run_scored ~ obp + slg, data = exp_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-56.288 -18.876   1.651  19.630  46.770 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -912.09      80.51 -11.328 3.20e-16 ***
obp          3019.45     341.62   8.839 2.84e-12 ***
slg          1411.78     157.31   8.975 1.70e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 25.4 on 57 degrees of freedom
Multiple R-squared:  0.9268,    Adjusted R-squared:  0.9242 
F-statistic: 360.9 on 2 and 57 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>If you look at the regression equation derived using only the on-base rate and the slugging rate instead of numerous variables, we can explain about 93% of the randomness of the score using only the on-base rate and the slugging rate. (R Square = 0.9268). In addition, the regression coefficient of the long hit rate and the on-base rate was also found to be significant at the 0.05 level. Now let’s call this model <strong>EM 2</strong>(expected score model 2)</p>
</section>
<section id="model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison">Model Comparison</h2>
<p>Now let’s compare the two models, EM 1 and EM 2, and decide which model to choose. First of all, when comparing the R square values, the model (EM 1) using every significant batting variables is .9563, and the model (EM 2) using the on-base rate and the slugging rate is 0.9268.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># AIC</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(exp_m_1_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 538.3475</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(exp_m_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 563.3476</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># BIC</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(exp_m_1_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 553.0079</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(exp_m_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 571.725</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PRESS</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>runsco<span class="ot">&lt;-</span>tot_df<span class="sc">$</span>run_scored</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((runsco <span class="sc">-</span> <span class="fu">predict</span>(exp_m_1_m, <span class="at">newdata =</span> tot_df))<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21929.6</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((runsco <span class="sc">-</span> <span class="fu">predict</span>(exp_m_2, <span class="at">newdata =</span> exp_df))<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 36763.51</code></pre>
</div>
</div>
<p>AIC is 538.3, 563.3, BIC is 553.0, 571.7, and PRESS is 21929.6, 36763.5, respectively. That is, EM 1 shows better performance in all aspects. But there is one thing to consider here. It is the multicollinearity of variables. Most of the batting indicators in baseball are highly correlated. Simply put, a good batter is likely to have a lot of hits and home runs are likely to have a lot of home runs. Actual data show a high correlation between hits, doubles, and home runs.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the multicollinearity</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(tot_df[,<span class="dv">12</span><span class="sc">:</span><span class="dv">16</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FP_young_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(tot_df[,<span class="dv">12</span><span class="sc">:</span><span class="dv">16</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             hit    double      triple          hr        bb
hit    1.0000000 0.7380595  0.38683193  0.54309756 0.2894128
double 0.7380595 1.0000000  0.28915285  0.46159048 0.1254726
triple 0.3868319 0.2891529  1.00000000 -0.01066422 0.2474792
hr     0.5430976 0.4615905 -0.01066422  1.00000000 0.0922088
bb     0.2894128 0.1254726  0.24747916  0.09220880 1.0000000</code></pre>
</div>
</div>
<p>Considering these points, I will choose EM 2 instead of EM 1. This is because EM 2 is much simpler using only two variables, and its explanatory power is not that low compared to EM 1.</p>
<p>Now, we can use this to get the expected score of each team and the difference between the actual score and the expected score.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get expected score by obp, slg</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>exp_df<span class="sc">$</span>exp_score<span class="ot">&lt;-</span><span class="fu">predict</span>(exp_m_2, <span class="at">newdata =</span> exp_df)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>exp_df<span class="ot">&lt;-</span>exp_df <span class="sc">%&gt;%</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">run_diff=</span>run_scored<span class="sc">-</span>exp_score)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>exp_df[,<span class="fu">c</span>(<span class="st">"year"</span>,<span class="st">"team"</span>,<span class="st">"run_scored"</span>,<span class="st">"exp_score"</span>,<span class="st">"run_diff"</span>,<span class="st">"inter_fre_sd"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 60 × 6
    year team    run_scored exp_score run_diff inter_fre_sd
   &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;       
 1  2015 Bears          807      826.  -19.2   normal      
 2  2015 Dinos          844      847.   -2.75  high        
 3  2015 Eagles         717      757.  -39.9   normal      
 4  2015 Giants         765      799.  -34.3   normal      
 5  2015 Heros          904      903.    0.924 low         
 6  2015 Landers        693      724.  -31.4   normal      
 7  2015 Lions          897      898.   -1.34  normal      
 8  2015 Tigers         648      631.   16.6   normal      
 9  2015 Twins          653      681.  -27.8   normal      
10  2015 Wiz            670      706.  -35.8   normal      
# ℹ 50 more rows</code></pre>
</div>
</div>
</section>
<section id="hb-1" class="level2">
<h2 class="anchored" data-anchor-id="hb-1">Hb-1</h2>
<p>Hypothesis hb1 can now be verified. The basic logic is as follows. If the manager’s intervention in the game has a positive effect on the team’s score, the difference between the actual score and the expected score will be high in the group with a high degree of intervention in the game. If not, the difference between the actual score of the high group and the expected score will be lower than that of the low group.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the score by groups</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>exp_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(inter_fre_sd) <span class="sc">%&gt;%</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avr_run_diff=</span><span class="fu">mean</span>(run_diff))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  inter_fre_sd avr_run_diff
  &lt;chr&gt;               &lt;dbl&gt;
1 high               -3.78 
2 low                 8.26 
3 normal             -0.959</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># anova</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>hb1<span class="ot">&lt;-</span><span class="fu">aov</span>(run_diff<span class="sc">~</span>inter_fre_sd, <span class="at">data=</span>exp_df)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)
inter_fre_sd  2    782   390.8   0.619  0.542
Residuals    57  35982   631.3               </code></pre>
</div>
</div>
<p>The result was the opposite of the result compared to the simple score discussed earlier. In other words, the difference between the actual score and the expected score of the group with high game intervention was lower than that of the group that did not. Considering the team’s basic offensive power, the manager’s intervention in the game rather makes the actual score lower than the team’s expected score. In other words, the manager’s intervention in the game rather reduces the team’s scoring ability.</p>
<p>However, the <strong>ANOVA results also showed that this did not have statistical significance at the 0.05 level.</strong>(p value: 0.542)</p>
</section>
<section id="hb-2" class="level2">
<h2 class="anchored" data-anchor-id="hb-2">Hb-2</h2>
<p>Next, I will conduct a regression analysis to find out the effect of game intervention on the difference between actual and expected scores.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regression</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>hb2<span class="ot">&lt;-</span><span class="fu">lm</span>(run_diff<span class="sc">~</span>inter, exp_df)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hb2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = run_diff ~ inter, data = exp_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-52.554 -17.939   1.632  19.984  41.424 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 37.03480   15.13122   2.448   0.0174 *
inter       -0.18531    0.07412  -2.500   0.0153 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 23.92 on 58 degrees of freedom
Multiple R-squared:  0.09729,   Adjusted R-squared:  0.08173 
F-statistic: 6.251 on 1 and 58 DF,  p-value: 0.01526</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(exp_df, <span class="fu">aes</span>(inter, run_diff),</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Intervention"</span>,</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Actual Score - Expected Score"</span>) <span class="sc">+</span> </span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="sc">-</span><span class="fl">0.18531</span>, <span class="at">intercept =</span> <span class="fl">37.03480</span>, <span class="at">color =</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regression of Intervention and Run Differential in KBO League"</span>, <span class="at">x =</span> <span class="st">"Intervention"</span>, <span class="at">y =</span> <span class="st">"Actual Score - Expected Score"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FP_young_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As a result of the regression analysis, the regression coefficient of the actual score and the expected score was <strong>-0.185</strong>. In other words, the increase in game intervention negatively affects the difference between actual and expected scores, and in interpretation, the increase in game intervention has the effect of reducing actual scores compared to the team’s offensive power.</p>
<p>The R square value was 0.097 and the <strong>p-value was 0.015, which was found to be significant at the 0.05 level.</strong></p>
<p>Finally, as a result of checking whether there is a violation of assumptions necessary for regression analysis, it does not appear that special treatment is required.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the assumptions</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>))</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hb2, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FP_young_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<section id="regarding-ha" class="level2">
<h2 class="anchored" data-anchor-id="regarding-ha">Regarding Ha</h2>
<p>First of all, looking at each hypothesis, in the case of Ha-1, the average score of the group with many game interventions was high (high: 765.9, normal: 754.9, low: 748.1), and in the case of Ha-2, the unit of game intervention increased the team’s score by 0.1792. (Run Scored = 719.7232 + 0.1792*Intervention)</p>
<p>In other words, it was interpreted that the coach’s intervention in the game had a positive effect on the team’s scoring ability.</p>
<p>However, in the case of Ha-1, the p value was 0.919, and in the case of Ha-2, the p value of the regression coefficient was 0.5354. In other words, <strong>both hypotheses cannot be said to be statistically significant at the 0.05 significance level.</strong></p>
</section>
<section id="regarding-hb" class="level2">
<h2 class="anchored" data-anchor-id="regarding-hb">Regarding Hb</h2>
<p>In the case of analysis using expected scores, the difference between actual scores and expected scores was used as a dependent variable(Run Differential.</p>
<p>In the case of Hb-1, contrary to Ha, it was found that the gap between actual and expected scores was high when the intervention in the game was low. (high: -3.78, normal: -0.96, low: 8.26) This implies that intervention in the game is negative for the team’s scoring ability. However, as a result of ANOVA analysis on this, the p value was 0.542, which was <strong>not significant at the significance level of 0.05.</strong></p>
<p>Next, in the case of Hb-2, it was found that game intervention had a negative effect on the gap between actual and expected scores. (Run Differential = 37.03480 -0.18531*Intervention)</p>
<p>In other words, like Hb-1, it can be interpreted that the manager’s intervention in the game negatively affects the team’s scoring ability. In addition, <strong>the regression coefficient of intervention was also found to be significant at the significance level of 0.05 as the p value is 0.0153</strong>.</p>
</section>
<section id="discussions" class="level2">
<h2 class="anchored" data-anchor-id="discussions">Discussions</h2>
<p><strong>Of the four hypotheses, only Hb-2 was able to draw statistically significant conclusions, and that hypothesis was wrong and could be concluded at the significance level of 0.05.</strong> In other words, it can be concluded that the manager’s intervention in the game in KBO league baseball rather suppresses the actual score considering the team’s expected score level.</p>
<p>This conclusion is consistent with the recent trend of negatively evaluating and avoiding the manager’s intervention in the game. However, when looking at the baseball game as a whole, pitching and defense should be considered in addition to hitting. In other words, only when additional research is conducted on these aspects, more rigorous discussions on the role of managers in baseball can be made.</p>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Lewis, M. (2004). Moneyball: The art of winning an unfair game. New York: Norton.</p>
<p>Smart, D., &amp; Wolfe, R. (2003). The contribution of leadership and human resources to organizational success: An empirical assessment of performance in Major League Baseball. European Sport Management Quarterly, 3, 165–188.</p>
<p>Winfree, J., &amp; Wolfe, R. (2008). Major League Baseball Managers: Do They Matter? Journal of Sport Management 22(3):303-321.</p>
<p>Lee, J., Kim, Y., &amp; Lee, J. (2007). Relationship between Leadership of Korean Professional Baseball Coaches and Performance of Their Teams. Soonchunhyang Natural Science Research 13(2):145-155.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb72" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "The effect of a manager's intervention in the game on the team's scoring ability in the KBO League"</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Young Soo Choi"</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Final Project"</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/22/2023"</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - final project</span></span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a><span class="fu"># Intro</span></span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## Research Problems</span></span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-20"><a href="#cb72-20" aria-hidden="true" tabindex="-1"></a>The debate about the role of a manager in baseball games has always been a hot potato. In the case of the United States, MLB(Major League Baseball), various quantitative analyses have been conducted on this topic since the famous Moneyball(2004, Lewis, M.), and most studies conclude that the role of the coach in the team's victory or defeat is not significant.</span>
<span id="cb72-21"><a href="#cb72-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-22"><a href="#cb72-22" aria-hidden="true" tabindex="-1"></a>Then, what is the case in Korea? Baseball is also prevalent in Korea as the most popular professional sport, and quantitative analysis has been conducted on these topics along with the activation of data analysis techniques over the past decade. However, the number is not large, but if you look at representative studies, there is a result of studying the difference in team performance according to the manager's tendency.(Lee, Kim, and Lee, 2007)</span>
<span id="cb72-23"><a href="#cb72-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-24"><a href="#cb72-24" aria-hidden="true" tabindex="-1"></a>If so, what is the relationship between the specific manager's behavior and the team's performance, other than the relationship between the manager's tendency and performance? More specifically, does the team's performance improve if the manager intervenes a lot in the game? Unfortunately, it was difficult to find a study on these problems targeting KBO(Korean Baseball Organization) league in Korea.</span>
<span id="cb72-25"><a href="#cb72-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-26"><a href="#cb72-26" aria-hidden="true" tabindex="-1"></a>With this awareness of the problem, this study aims to check whether the manager's intervention improves the team's performance in baseball games in Korean professional baseball(KBO league). In other words, the research question is, **"What is the relationship between the manager's intervention and the team's performance in the KBO League?"**</span>
<span id="cb72-27"><a href="#cb72-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-28"><a href="#cb72-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Major Concepts</span></span>
<span id="cb72-29"><a href="#cb72-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-30"><a href="#cb72-30" aria-hidden="true" tabindex="-1"></a>Before review the problem, let's look at some important concepts. First of all, baseball's team performance is divided into wins and losses, and of course, the more wins, the better. And the victory of the game is given to the team that scores more points, so the team's performance is more advantageous the more points they score and allow fewer runs. In addition, the manager of baseball directs the overall game, such as setting the team's batting order and replacing pitchers at an appropriate time, and in terms of offense, he can directly intervene in the game through various operations such as bunt and steal direction. Finally, the KBO League is a Korean professional baseball league that started with six teams in 1982, and 10 teams have been participating since 2015. Currently, each team plays 144 games in a season, with a total of 720 games.</span>
<span id="cb72-31"><a href="#cb72-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-32"><a href="#cb72-32" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis and Research Design</span></span>
<span id="cb72-33"><a href="#cb72-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-34"><a href="#cb72-34" aria-hidden="true" tabindex="-1"></a>Based on the research problems and major concepts discussed above, the hypothesis of this study was established as follows.</span>
<span id="cb72-35"><a href="#cb72-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-36"><a href="#cb72-36" aria-hidden="true" tabindex="-1"></a>**Ha-1: In the KBO League, teams with a lot of managers' intervention in games have higher scoring ability than teams that do not.**</span>
<span id="cb72-37"><a href="#cb72-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-38"><a href="#cb72-38" aria-hidden="true" tabindex="-1"></a>*(High Group Average Score \&gt; Normal Group Average Score \&gt; Low Group Average Score)*</span>
<span id="cb72-39"><a href="#cb72-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-40"><a href="#cb72-40" aria-hidden="true" tabindex="-1"></a>**Ha-2: In the KBO League, the more the manager intervenes in the game, the higher the team's scoring ability.**</span>
<span id="cb72-41"><a href="#cb72-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-42"><a href="#cb72-42" aria-hidden="true" tabindex="-1"></a>*(In the regression model of scoring and intervention, regression coefficient for intervention \&gt; 0)*</span>
<span id="cb72-43"><a href="#cb72-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-44"><a href="#cb72-44" aria-hidden="true" tabindex="-1"></a>**Hb-1: In the KBO League, the difference between the actual score and the expected score of the team with a lot of intervention in the game will be greater than that of the team that does not.**</span>
<span id="cb72-45"><a href="#cb72-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-46"><a href="#cb72-46" aria-hidden="true" tabindex="-1"></a>*(The difference between the actual score and the expected score of high group \&gt; The difference between the actual score and the expected score of normal group \&gt; The difference between the actual score and the expected score of low group)*</span>
<span id="cb72-47"><a href="#cb72-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-48"><a href="#cb72-48" aria-hidden="true" tabindex="-1"></a>**Hb-2: In the KBO League, the more interventions there are in the game, the greater the difference between actual scores and expected scores.**</span>
<span id="cb72-49"><a href="#cb72-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-50"><a href="#cb72-50" aria-hidden="true" tabindex="-1"></a>*(In the regression model of the difference between the actual score and the expected score and intervention, regression coefficient for intervention \&gt; 0)*</span>
<span id="cb72-51"><a href="#cb72-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-52"><a href="#cb72-52" aria-hidden="true" tabindex="-1"></a>Since baseball games are quite complex, I would like to verify research problems in various ways. Therefore, hypotheses were also defined in four forms as above.</span>
<span id="cb72-53"><a href="#cb72-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-54"><a href="#cb72-54" aria-hidden="true" tabindex="-1"></a>For Ha-1, teams will be classified according to the frequency of game intervention and the average of which groups have a high average score will be compared. For Ha-2, we will conduct a regression analysis on how the team's average score moves as the game intervention increases.</span>
<span id="cb72-55"><a href="#cb72-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-56"><a href="#cb72-56" aria-hidden="true" tabindex="-1"></a>For Hb, we will use the concept of expected score. Expected score refers to the expected score considering the team's basic offensive power, and an expected score generation formula can be obtained through regression analysis using batting indicators such as batting average and slugging rate. From this point of view, the manager's intervention can confirm whether the team's actual score is higher or lower than the team's expected score.</span>
<span id="cb72-57"><a href="#cb72-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-58"><a href="#cb72-58" aria-hidden="true" tabindex="-1"></a>Hb-1 will classify groups according to the frequency of intervention in the game, such as Ha-1, and compare the average of the expected scores of the teams in each group with the actual scores. Like Ha-2, Hb-2 will be analyzed the difference between the team's actual score and the expected score depending on the degree of intervention in the game using regression.</span>
<span id="cb72-59"><a href="#cb72-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-60"><a href="#cb72-60" aria-hidden="true" tabindex="-1"></a><span class="fu"># Looking at the Data</span></span>
<span id="cb72-61"><a href="#cb72-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-62"><a href="#cb72-62" aria-hidden="true" tabindex="-1"></a><span class="fu">## Operational Definition</span></span>
<span id="cb72-63"><a href="#cb72-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-64"><a href="#cb72-64" aria-hidden="true" tabindex="-1"></a>Until now, the concept of manager's intervention in the game has been used. But how can we measure this. In fact, it is a subject that allows for extensive research on this alone. However, in this study, to simplify the analysis, I would like to operatively define it so that existing data can be used as it is. In other words, the team's annual bunt(sacrifice hit, sh) and steal attempts(steal, st + stolen caught, sc) are defined as the manager's intervention in the game.</span>
<span id="cb72-65"><a href="#cb72-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-66"><a href="#cb72-66" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Load</span></span>
<span id="cb72-67"><a href="#cb72-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-68"><a href="#cb72-68" aria-hidden="true" tabindex="-1"></a>Before the full-fledged analysis, I would like to set the scope of the study first. Baseball shows quite different aspects from time to time, especially the average score showing quite differently from time to time. In particular, the KBO League has continued to expand its teams, and the proportion of stadiums used and foreign players has been determined every year. Considering this, only data after 2015 when the 10-team system was established will be used.</span>
<span id="cb72-69"><a href="#cb72-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-72"><a href="#cb72-72" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-73"><a href="#cb72-73" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setenv</span>(<span class="at">LANG =</span> <span class="st">"en"</span>)</span>
<span id="cb72-74"><a href="#cb72-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-75"><a href="#cb72-75" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb72-76"><a href="#cb72-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-77"><a href="#cb72-77" aria-hidden="true" tabindex="-1"></a><span class="co"># loading data</span></span>
<span id="cb72-78"><a href="#cb72-78" aria-hidden="true" tabindex="-1"></a>kbo_df<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"~/R/603_Spring_2023/posts/_data/kbo_df.csv"</span>)</span>
<span id="cb72-79"><a href="#cb72-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-80"><a href="#cb72-80" aria-hidden="true" tabindex="-1"></a>kbo_df<span class="ot">&lt;-</span>kbo_df[<span class="dv">254</span><span class="sc">:</span><span class="dv">313</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">28</span>]</span>
<span id="cb72-81"><a href="#cb72-81" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kbo_df)</span>
<span id="cb72-82"><a href="#cb72-82" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-83"><a href="#cb72-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-84"><a href="#cb72-84" aria-hidden="true" tabindex="-1"></a><span class="fu">## Looking at the average intervention by year</span></span>
<span id="cb72-85"><a href="#cb72-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-88"><a href="#cb72-88" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-89"><a href="#cb72-89" aria-hidden="true" tabindex="-1"></a><span class="co"># making average variables by years</span></span>
<span id="cb72-90"><a href="#cb72-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-91"><a href="#cb72-91" aria-hidden="true" tabindex="-1"></a><span class="co"># for sh</span></span>
<span id="cb72-92"><a href="#cb72-92" aria-hidden="true" tabindex="-1"></a><span class="do">## create an empty data frame to store the results</span></span>
<span id="cb72-93"><a href="#cb72-93" aria-hidden="true" tabindex="-1"></a>sh_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">integer</span>(), <span class="at">avr_sh =</span> <span class="fu">numeric</span>())</span>
<span id="cb72-94"><a href="#cb72-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-95"><a href="#cb72-95" aria-hidden="true" tabindex="-1"></a><span class="do">## loop over the years</span></span>
<span id="cb72-96"><a href="#cb72-96" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2015</span><span class="sc">:</span><span class="dv">2020</span>) {</span>
<span id="cb72-97"><a href="#cb72-97" aria-hidden="true" tabindex="-1"></a>  <span class="do">## filter the data for the current year and calculate the sum of sh variable</span></span>
<span id="cb72-98"><a href="#cb72-98" aria-hidden="true" tabindex="-1"></a>  year_sh <span class="ot">&lt;-</span> kbo_df <span class="sc">%&gt;%</span> </span>
<span id="cb72-99"><a href="#cb72-99" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">==</span> i) <span class="sc">%&gt;%</span> </span>
<span id="cb72-100"><a href="#cb72-100" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">year_av_sh =</span> <span class="fu">sum</span>(sh)<span class="sc">/</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb72-101"><a href="#cb72-101" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(year_av_sh)</span>
<span id="cb72-102"><a href="#cb72-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-103"><a href="#cb72-103" aria-hidden="true" tabindex="-1"></a>  <span class="do">## add the result to the data frame</span></span>
<span id="cb72-104"><a href="#cb72-104" aria-hidden="true" tabindex="-1"></a>  sh_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(sh_df, <span class="fu">data.frame</span>(<span class="at">year =</span> i, <span class="at">avr_sh =</span> year_sh))</span>
<span id="cb72-105"><a href="#cb72-105" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb72-106"><a href="#cb72-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-107"><a href="#cb72-107" aria-hidden="true" tabindex="-1"></a><span class="co"># for sb</span></span>
<span id="cb72-108"><a href="#cb72-108" aria-hidden="true" tabindex="-1"></a>sb_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">integer</span>(), <span class="at">avr_sb =</span> <span class="fu">numeric</span>())</span>
<span id="cb72-109"><a href="#cb72-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-110"><a href="#cb72-110" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2015</span><span class="sc">:</span><span class="dv">2020</span>) {</span>
<span id="cb72-111"><a href="#cb72-111" aria-hidden="true" tabindex="-1"></a>  year_sb <span class="ot">&lt;-</span> kbo_df <span class="sc">%&gt;%</span> </span>
<span id="cb72-112"><a href="#cb72-112" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">==</span> i) <span class="sc">%&gt;%</span> </span>
<span id="cb72-113"><a href="#cb72-113" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">year_av_sb =</span> <span class="fu">sum</span>(sb)<span class="sc">/</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb72-114"><a href="#cb72-114" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(year_av_sb)</span>
<span id="cb72-115"><a href="#cb72-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-116"><a href="#cb72-116" aria-hidden="true" tabindex="-1"></a>  sb_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(sb_df, <span class="fu">data.frame</span>(<span class="at">year=</span>i, <span class="at">avr_sb=</span>year_sb))</span>
<span id="cb72-117"><a href="#cb72-117" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb72-118"><a href="#cb72-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-119"><a href="#cb72-119" aria-hidden="true" tabindex="-1"></a><span class="co"># for cs</span></span>
<span id="cb72-120"><a href="#cb72-120" aria-hidden="true" tabindex="-1"></a>cs_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">integer</span>(), <span class="at">avr_cs =</span> <span class="fu">numeric</span>())</span>
<span id="cb72-121"><a href="#cb72-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-122"><a href="#cb72-122" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2015</span><span class="sc">:</span><span class="dv">2020</span>) {</span>
<span id="cb72-123"><a href="#cb72-123" aria-hidden="true" tabindex="-1"></a>  year_cs <span class="ot">&lt;-</span> kbo_df <span class="sc">%&gt;%</span> </span>
<span id="cb72-124"><a href="#cb72-124" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">==</span> i) <span class="sc">%&gt;%</span> </span>
<span id="cb72-125"><a href="#cb72-125" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">year_av_cs =</span> <span class="fu">sum</span>(cs)<span class="sc">/</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb72-126"><a href="#cb72-126" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(year_av_cs)</span>
<span id="cb72-127"><a href="#cb72-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-128"><a href="#cb72-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-129"><a href="#cb72-129" aria-hidden="true" tabindex="-1"></a>  cs_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(cs_df, <span class="fu">data.frame</span>(<span class="at">year=</span>i, <span class="at">avr_cs=</span>year_cs))</span>
<span id="cb72-130"><a href="#cb72-130" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb72-131"><a href="#cb72-131" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-132"><a href="#cb72-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-135"><a href="#cb72-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-136"><a href="#cb72-136" aria-hidden="true" tabindex="-1"></a><span class="co"># print the results data frame</span></span>
<span id="cb72-137"><a href="#cb72-137" aria-hidden="true" tabindex="-1"></a>sa_df<span class="ot">&lt;-</span><span class="fu">left_join</span>(sb_df, cs_df)</span>
<span id="cb72-138"><a href="#cb72-138" aria-hidden="true" tabindex="-1"></a>sa_df<span class="ot">&lt;-</span><span class="fu">mutate</span>(sa_df, <span class="at">avr_sa=</span>avr_sb<span class="sc">+</span>avr_cs)</span>
<span id="cb72-139"><a href="#cb72-139" aria-hidden="true" tabindex="-1"></a>int_da<span class="ot">&lt;-</span><span class="fu">left_join</span>(sh_df, sa_df)</span>
<span id="cb72-140"><a href="#cb72-140" aria-hidden="true" tabindex="-1"></a>int_da<span class="ot">&lt;-</span><span class="fu">mutate</span>(int_da, <span class="at">avr_int=</span>avr_sh<span class="sc">+</span>avr_sa)</span>
<span id="cb72-141"><a href="#cb72-141" aria-hidden="true" tabindex="-1"></a>int_da</span>
<span id="cb72-142"><a href="#cb72-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-143"><a href="#cb72-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-146"><a href="#cb72-146" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-147"><a href="#cb72-147" aria-hidden="true" tabindex="-1"></a><span class="co"># drawing a graph</span></span>
<span id="cb72-148"><a href="#cb72-148" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb72-149"><a href="#cb72-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-150"><a href="#cb72-150" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(int_da, <span class="fu">aes</span>(<span class="at">x=</span>year)) <span class="sc">+</span> </span>
<span id="cb72-151"><a href="#cb72-151" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> avr_sh, <span class="at">color =</span> <span class="st">"Sacrifice Hit"</span>)) <span class="sc">+</span> </span>
<span id="cb72-152"><a href="#cb72-152" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> avr_sa, <span class="at">color=</span><span class="st">"Steal Attempts"</span>)) <span class="sc">+</span></span>
<span id="cb72-153"><a href="#cb72-153" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> avr_int, <span class="at">color =</span> <span class="st">"Total Intervention"</span>)) <span class="sc">+</span></span>
<span id="cb72-154"><a href="#cb72-154" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Trend of Game Intervention in KBO League"</span>, <span class="at">color =</span> <span class="st">"Variable"</span>, <span class="at">y =</span> <span class="st">"Average Value"</span>) <span class="sc">+</span></span>
<span id="cb72-155"><a href="#cb72-155" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="st">""</span>, </span>
<span id="cb72-156"><a href="#cb72-156" aria-hidden="true" tabindex="-1"></a>                      <span class="at">breaks =</span> <span class="fu">c</span>(<span class="st">"Sacrifice Hit"</span>, <span class="st">"Steal Attempts"</span>, <span class="st">"Total Intervention"</span>),</span>
<span id="cb72-157"><a href="#cb72-157" aria-hidden="true" tabindex="-1"></a>                      <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"darkred"</span>, <span class="st">"steelblue"</span>, <span class="st">"purple"</span>))</span>
<span id="cb72-158"><a href="#cb72-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-159"><a href="#cb72-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-160"><a href="#cb72-160" aria-hidden="true" tabindex="-1"></a>Looking at the frequency of intervention in the game since 2015, it can be seen that the overall trend has been downward, but the total frequency of intervention has been stable since 2017.</span>
<span id="cb72-161"><a href="#cb72-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-162"><a href="#cb72-162" aria-hidden="true" tabindex="-1"></a><span class="fu"># Hypothesis Testing: Ha(Actual Scores)</span></span>
<span id="cb72-163"><a href="#cb72-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-164"><a href="#cb72-164" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ha-1</span></span>
<span id="cb72-165"><a href="#cb72-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-166"><a href="#cb72-166" aria-hidden="true" tabindex="-1"></a>To verify Ha-1, each team by year is divided into three groups according to the frequency of game intervention. Teams with more than 1 sd intervention are assigned to the high group compared to the overall average frequency of intervention for the year. In the low group, on the contrary, fewer teams than 1 sd are involved, and the rest are assigned to the normal group.</span>
<span id="cb72-167"><a href="#cb72-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-170"><a href="#cb72-170" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-171"><a href="#cb72-171" aria-hidden="true" tabindex="-1"></a><span class="co"># merge those data</span></span>
<span id="cb72-172"><a href="#cb72-172" aria-hidden="true" tabindex="-1"></a>int_df<span class="ot">&lt;-</span><span class="fu">merge</span>(<span class="fu">merge</span>(sh_df, sb_df, <span class="at">by =</span> <span class="st">"year"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>), cs_df, <span class="at">by=</span><span class="st">"year"</span>, <span class="at">all=</span><span class="cn">TRUE</span>)</span>
<span id="cb72-173"><a href="#cb72-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-174"><a href="#cb72-174" aria-hidden="true" tabindex="-1"></a><span class="co"># left join to original data</span></span>
<span id="cb72-175"><a href="#cb72-175" aria-hidden="true" tabindex="-1"></a>tot_df<span class="ot">&lt;-</span><span class="fu">left_join</span>(kbo_df, int_df)</span>
<span id="cb72-176"><a href="#cb72-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-177"><a href="#cb72-177" aria-hidden="true" tabindex="-1"></a><span class="co"># making intervention variables</span></span>
<span id="cb72-178"><a href="#cb72-178" aria-hidden="true" tabindex="-1"></a>tot_df<span class="ot">&lt;-</span>tot_df <span class="sc">%&gt;%</span></span>
<span id="cb72-179"><a href="#cb72-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">st_att=</span>sb<span class="sc">+</span>cs, <span class="at">inter =</span> sh<span class="sc">+</span>st_att, <span class="at">avr_inter=</span>avr_sh<span class="sc">+</span>avr_sb<span class="sc">+</span>avr_cs)</span>
<span id="cb72-180"><a href="#cb72-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-181"><a href="#cb72-181" aria-hidden="true" tabindex="-1"></a>tot_df[, <span class="fu">c</span>(<span class="st">'year'</span>,<span class="st">'team'</span>,<span class="st">'sh'</span>,<span class="st">'st_att'</span>,<span class="st">'inter'</span>,<span class="st">'avr_inter'</span>)]</span>
<span id="cb72-182"><a href="#cb72-182" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-183"><a href="#cb72-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-186"><a href="#cb72-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-187"><a href="#cb72-187" aria-hidden="true" tabindex="-1"></a><span class="co"># making sd of intervention by each year</span></span>
<span id="cb72-188"><a href="#cb72-188" aria-hidden="true" tabindex="-1"></a>sd_int<span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">integer</span>(), <span class="at">sd_i=</span> <span class="fu">numeric</span>())</span>
<span id="cb72-189"><a href="#cb72-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-190"><a href="#cb72-190" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2015</span><span class="sc">:</span><span class="dv">2020</span>) {</span>
<span id="cb72-191"><a href="#cb72-191" aria-hidden="true" tabindex="-1"></a>  year_sd <span class="ot">&lt;-</span> tot_df <span class="sc">%&gt;%</span> </span>
<span id="cb72-192"><a href="#cb72-192" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">==</span> i) <span class="sc">%&gt;%</span> </span>
<span id="cb72-193"><a href="#cb72-193" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">year_sd_int =</span> <span class="fu">sd</span>(inter)) <span class="sc">%&gt;%</span> </span>
<span id="cb72-194"><a href="#cb72-194" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(year_sd_int)</span>
<span id="cb72-195"><a href="#cb72-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-196"><a href="#cb72-196" aria-hidden="true" tabindex="-1"></a>  sd_int<span class="ot">&lt;-</span> <span class="fu">rbind</span>(sd_int, <span class="fu">data.frame</span>(<span class="at">year =</span> i, <span class="at">sd_i=</span> year_sd))</span>
<span id="cb72-197"><a href="#cb72-197" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb72-198"><a href="#cb72-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-199"><a href="#cb72-199" aria-hidden="true" tabindex="-1"></a>tot_df<span class="ot">&lt;-</span><span class="fu">left_join</span>(tot_df, sd_int)</span>
<span id="cb72-200"><a href="#cb72-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-201"><a href="#cb72-201" aria-hidden="true" tabindex="-1"></a><span class="co"># making three type variables</span></span>
<span id="cb72-202"><a href="#cb72-202" aria-hidden="true" tabindex="-1"></a>tot_df<span class="ot">&lt;-</span>tot_df <span class="sc">%&gt;%</span></span>
<span id="cb72-203"><a href="#cb72-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">inter_fre_sd=</span><span class="fu">ifelse</span>(inter<span class="sc">&gt;</span>avr_inter<span class="sc">+</span>sd_i, <span class="st">"high"</span>, </span>
<span id="cb72-204"><a href="#cb72-204" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">ifelse</span>(inter<span class="sc">&lt;</span>avr_inter<span class="sc">-</span>sd_i, <span class="st">"low"</span>, <span class="st">"normal"</span>)))</span>
<span id="cb72-205"><a href="#cb72-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-206"><a href="#cb72-206" aria-hidden="true" tabindex="-1"></a>tot_df[, <span class="fu">c</span>(<span class="st">'year'</span>,<span class="st">'team'</span>,<span class="st">'run_scored'</span>, <span class="st">'inter_fre_sd'</span>)]</span>
<span id="cb72-207"><a href="#cb72-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-208"><a href="#cb72-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-209"><a href="#cb72-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-212"><a href="#cb72-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-213"><a href="#cb72-213" aria-hidden="true" tabindex="-1"></a><span class="co"># making table</span></span>
<span id="cb72-214"><a href="#cb72-214" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(tot_df<span class="sc">$</span>inter_fre_sd, tot_df<span class="sc">$</span>year)</span>
<span id="cb72-215"><a href="#cb72-215" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(tot_df<span class="sc">$</span>inter_fre_sd)</span>
<span id="cb72-216"><a href="#cb72-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-217"><a href="#cb72-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-218"><a href="#cb72-218" aria-hidden="true" tabindex="-1"></a>Of the 60 data in the six-year period, 9 were assigned to the high group and 9 to the low group, respectively, and the rest were normal groups. Now let's verify the average difference between them.</span>
<span id="cb72-219"><a href="#cb72-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-222"><a href="#cb72-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-223"><a href="#cb72-223" aria-hidden="true" tabindex="-1"></a><span class="co"># check the score by groups</span></span>
<span id="cb72-224"><a href="#cb72-224" aria-hidden="true" tabindex="-1"></a>tot_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(inter_fre_sd) <span class="sc">%&gt;%</span></span>
<span id="cb72-225"><a href="#cb72-225" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avr_run=</span><span class="fu">mean</span>(run_scored))</span>
<span id="cb72-226"><a href="#cb72-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-227"><a href="#cb72-227" aria-hidden="true" tabindex="-1"></a><span class="co"># anova</span></span>
<span id="cb72-228"><a href="#cb72-228" aria-hidden="true" tabindex="-1"></a>ha1<span class="ot">&lt;-</span><span class="fu">aov</span>(run_scored<span class="sc">~</span>inter_fre_sd, <span class="at">data=</span>tot_df)</span>
<span id="cb72-229"><a href="#cb72-229" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ha1)</span>
<span id="cb72-230"><a href="#cb72-230" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-231"><a href="#cb72-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-232"><a href="#cb72-232" aria-hidden="true" tabindex="-1"></a>Looking at the average difference between each group, the high group has the highest average score and the low group has the lowest average score. In other words, when compared simply, the average score of the group with a lot of game intervention is higher. However, since the **value of p as an AVONA result is 0.919**, there is no statistical significance of this result.(at the 0.05 level of significance). In other words, it is difficult to accept it as a meaningful result.</span>
<span id="cb72-233"><a href="#cb72-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-234"><a href="#cb72-234" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ha-2</span></span>
<span id="cb72-235"><a href="#cb72-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-236"><a href="#cb72-236" aria-hidden="true" tabindex="-1"></a>Next, I will examine how game intervention has a relationship with scoring through regression analysis between game intervention and score.</span>
<span id="cb72-237"><a href="#cb72-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-240"><a href="#cb72-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-241"><a href="#cb72-241" aria-hidden="true" tabindex="-1"></a><span class="co"># regression</span></span>
<span id="cb72-242"><a href="#cb72-242" aria-hidden="true" tabindex="-1"></a>ha2<span class="ot">&lt;-</span><span class="fu">lm</span>(run_scored<span class="sc">~</span>inter, tot_df)</span>
<span id="cb72-243"><a href="#cb72-243" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ha2)</span>
<span id="cb72-244"><a href="#cb72-244" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-245"><a href="#cb72-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-248"><a href="#cb72-248" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-249"><a href="#cb72-249" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tot_df, <span class="fu">aes</span>(inter, run_scored),</span>
<span id="cb72-250"><a href="#cb72-250" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Intervention"</span>,</span>
<span id="cb72-251"><a href="#cb72-251" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Run Scored"</span>) <span class="sc">+</span> </span>
<span id="cb72-252"><a href="#cb72-252" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb72-253"><a href="#cb72-253" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="fl">0.1792</span>, <span class="at">intercept =</span> <span class="fl">719.7232</span>, <span class="at">color =</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb72-254"><a href="#cb72-254" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regression of Intervention and Run Scored in KBO League"</span>, <span class="at">x =</span> <span class="st">"Intervention"</span>, <span class="at">y =</span> <span class="st">"Run Scored"</span>)</span>
<span id="cb72-255"><a href="#cb72-255" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-256"><a href="#cb72-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-257"><a href="#cb72-257" aria-hidden="true" tabindex="-1"></a>Similar to the previous simple average comparison, the higher the number of interventions in the game, the higher the score. In other words, the coefficient of intervention in the game was 0.1792, indicating that the score per game increased by 0.1792 points. However, the R square value was 0.006658, and the randomness of game intervention was very low to explain the team's score, and the **p value of the slope of the regression equation was also 0.5354**, which was not significant at the 0.05 level.</span>
<span id="cb72-258"><a href="#cb72-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-259"><a href="#cb72-259" aria-hidden="true" tabindex="-1"></a>Next, I will check if there are any violations of various assumptions necessary for regression analysis.</span>
<span id="cb72-260"><a href="#cb72-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-263"><a href="#cb72-263" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-264"><a href="#cb72-264" aria-hidden="true" tabindex="-1"></a><span class="co"># check the assumptions</span></span>
<span id="cb72-265"><a href="#cb72-265" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>))</span>
<span id="cb72-266"><a href="#cb72-266" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ha2, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb72-267"><a href="#cb72-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-268"><a href="#cb72-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-269"><a href="#cb72-269" aria-hidden="true" tabindex="-1"></a>As a result of the confirmation, there seems to be no particular violation.</span>
<span id="cb72-270"><a href="#cb72-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-271"><a href="#cb72-271" aria-hidden="true" tabindex="-1"></a><span class="fu"># Hypothesis Testing: Hb(Expected Scores)</span></span>
<span id="cb72-272"><a href="#cb72-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-273"><a href="#cb72-273" aria-hidden="true" tabindex="-1"></a><span class="fu">## Expected Run Scored</span></span>
<span id="cb72-274"><a href="#cb72-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-275"><a href="#cb72-275" aria-hidden="true" tabindex="-1"></a>Next, I will analyze the effect of game intervention using expected scores. First, we need to look at the meaning of expected scores.</span>
<span id="cb72-276"><a href="#cb72-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-277"><a href="#cb72-277" aria-hidden="true" tabindex="-1"></a>In baseball, scoring is done through a combination of various offensive acts. For example, if a home run comes out after a hit, you will get two points, but if a double play comes out after a hit, you will not be able to score and increase the out count by two. As such, each batting event is correlated with scoring, and this relationship can be used to obtain the team's expected score, which can be said to show the team's basic offensive power.</span>
<span id="cb72-278"><a href="#cb72-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-279"><a href="#cb72-279" aria-hidden="true" tabindex="-1"></a>However, the question here is what variables will be used to predict the team's expected score.</span>
<span id="cb72-280"><a href="#cb72-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-281"><a href="#cb72-281" aria-hidden="true" tabindex="-1"></a>First, I obtained a regression equation between them and scoring using all batting indicators.</span>
<span id="cb72-282"><a href="#cb72-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-285"><a href="#cb72-285" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-286"><a href="#cb72-286" aria-hidden="true" tabindex="-1"></a><span class="co"># regression with every batting stat</span></span>
<span id="cb72-287"><a href="#cb72-287" aria-hidden="true" tabindex="-1"></a>exp_m_1<span class="ot">&lt;-</span><span class="fu">lm</span>(run_scored<span class="sc">~</span>hit<span class="sc">+</span>double<span class="sc">+</span>triple<span class="sc">+</span>hr<span class="sc">+</span>bb<span class="sc">+</span>ibb<span class="sc">+</span>hbp<span class="sc">+</span>so<span class="sc">+</span>sf<span class="sc">+</span>gidp, tot_df)</span>
<span id="cb72-288"><a href="#cb72-288" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exp_m_1)</span>
<span id="cb72-289"><a href="#cb72-289" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-290"><a href="#cb72-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-291"><a href="#cb72-291" aria-hidden="true" tabindex="-1"></a>Although the explanatory power was quite high (R square: 0.9618), the regression coefficient for some variables was not significant at the 0.05 level.</span>
<span id="cb72-292"><a href="#cb72-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-293"><a href="#cb72-293" aria-hidden="true" tabindex="-1"></a>I will now refit the model except for those variables. The results are as follows.</span>
<span id="cb72-294"><a href="#cb72-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-297"><a href="#cb72-297" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-298"><a href="#cb72-298" aria-hidden="true" tabindex="-1"></a><span class="co"># regression with every significant batting stat</span></span>
<span id="cb72-299"><a href="#cb72-299" aria-hidden="true" tabindex="-1"></a>exp_m_1_m<span class="ot">&lt;-</span><span class="fu">lm</span>(run_scored<span class="sc">~</span>hit<span class="sc">+</span>double<span class="sc">+</span>triple<span class="sc">+</span>hr<span class="sc">+</span>bb, tot_df)</span>
<span id="cb72-300"><a href="#cb72-300" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exp_m_1_m)</span>
<span id="cb72-301"><a href="#cb72-301" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-302"><a href="#cb72-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-303"><a href="#cb72-303" aria-hidden="true" tabindex="-1"></a>The regression coefficient of all variables is significant at the 0.05 level, and the R square value is 0.9563. Now let's call this model **EM 1**(expected score model 1).</span>
<span id="cb72-304"><a href="#cb72-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-305"><a href="#cb72-305" aria-hidden="true" tabindex="-1"></a>Next, I will find out the on-base percentage and slugging percentage, which can be said to be a combination of these indicators, and then check the relationship between scoring and them.</span>
<span id="cb72-306"><a href="#cb72-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-309"><a href="#cb72-309" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-310"><a href="#cb72-310" aria-hidden="true" tabindex="-1"></a><span class="co"># OBP = (Hits + Walks + Hit-by-Pitches) / (At-Bats + Walks + Hit-by-Pitches + Sacrifice Flies)</span></span>
<span id="cb72-311"><a href="#cb72-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-312"><a href="#cb72-312" aria-hidden="true" tabindex="-1"></a>exp_df<span class="ot">&lt;-</span>tot_df <span class="sc">%&gt;%</span></span>
<span id="cb72-313"><a href="#cb72-313" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">obp=</span>(hit<span class="sc">+</span>bb<span class="sc">+</span>ibb<span class="sc">+</span>hbp)<span class="sc">/</span>(ab<span class="sc">+</span>bb<span class="sc">+</span>ibb<span class="sc">+</span>hbp<span class="sc">+</span>sf))</span>
<span id="cb72-314"><a href="#cb72-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-315"><a href="#cb72-315" aria-hidden="true" tabindex="-1"></a><span class="co"># SLG = (1B + 2B x 2 + 3B x 3 + HR x 4) / AB</span></span>
<span id="cb72-316"><a href="#cb72-316" aria-hidden="true" tabindex="-1"></a>exp_df<span class="ot">&lt;-</span>exp_df<span class="sc">%&gt;%</span></span>
<span id="cb72-317"><a href="#cb72-317" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tb=</span>hit<span class="sc">-</span>(double<span class="sc">+</span>triple<span class="sc">+</span>hr)<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>double<span class="sc">+</span><span class="dv">3</span><span class="sc">*</span>triple<span class="sc">+</span><span class="dv">4</span><span class="sc">*</span>hr)</span>
<span id="cb72-318"><a href="#cb72-318" aria-hidden="true" tabindex="-1"></a>exp_df<span class="ot">&lt;-</span>exp_df<span class="sc">%&gt;%</span></span>
<span id="cb72-319"><a href="#cb72-319" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">slg=</span>tb<span class="sc">/</span>ab)</span>
<span id="cb72-320"><a href="#cb72-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-321"><a href="#cb72-321" aria-hidden="true" tabindex="-1"></a>exp_df[,<span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"team"</span>, <span class="st">"run_scored"</span>, <span class="st">"obp"</span>, <span class="st">"slg"</span>)]</span>
<span id="cb72-322"><a href="#cb72-322" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-323"><a href="#cb72-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-326"><a href="#cb72-326" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-327"><a href="#cb72-327" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting regression model using obp and slg</span></span>
<span id="cb72-328"><a href="#cb72-328" aria-hidden="true" tabindex="-1"></a>exp_m_2<span class="ot">&lt;-</span><span class="fu">lm</span>(run_scored<span class="sc">~</span>obp<span class="sc">+</span>slg, exp_df)</span>
<span id="cb72-329"><a href="#cb72-329" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exp_m_2)</span>
<span id="cb72-330"><a href="#cb72-330" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-331"><a href="#cb72-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-332"><a href="#cb72-332" aria-hidden="true" tabindex="-1"></a>If you look at the regression equation derived using only the on-base rate and the slugging rate instead of numerous variables, we can explain about 93% of the randomness of the score using only the on-base rate and the slugging rate. (R Square = 0.9268). In addition, the regression coefficient of the long hit rate and the on-base rate was also found to be significant at the 0.05 level. Now let's call this model **EM 2**(expected score model 2)</span>
<span id="cb72-333"><a href="#cb72-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-334"><a href="#cb72-334" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model Comparison</span></span>
<span id="cb72-335"><a href="#cb72-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-336"><a href="#cb72-336" aria-hidden="true" tabindex="-1"></a>Now let's compare the two models, EM 1 and EM 2, and decide which model to choose. First of all, when comparing the R square values, the model (EM 1) using every significant batting variables is .9563, and the model (EM 2) using the on-base rate and the slugging rate is 0.9268.</span>
<span id="cb72-337"><a href="#cb72-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-340"><a href="#cb72-340" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-341"><a href="#cb72-341" aria-hidden="true" tabindex="-1"></a><span class="co"># AIC</span></span>
<span id="cb72-342"><a href="#cb72-342" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(exp_m_1_m)</span>
<span id="cb72-343"><a href="#cb72-343" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(exp_m_2)</span>
<span id="cb72-344"><a href="#cb72-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-345"><a href="#cb72-345" aria-hidden="true" tabindex="-1"></a><span class="co"># BIC</span></span>
<span id="cb72-346"><a href="#cb72-346" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(exp_m_1_m)</span>
<span id="cb72-347"><a href="#cb72-347" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(exp_m_2)</span>
<span id="cb72-348"><a href="#cb72-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-349"><a href="#cb72-349" aria-hidden="true" tabindex="-1"></a><span class="co"># PRESS</span></span>
<span id="cb72-350"><a href="#cb72-350" aria-hidden="true" tabindex="-1"></a>runsco<span class="ot">&lt;-</span>tot_df<span class="sc">$</span>run_scored</span>
<span id="cb72-351"><a href="#cb72-351" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((runsco <span class="sc">-</span> <span class="fu">predict</span>(exp_m_1_m, <span class="at">newdata =</span> tot_df))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb72-352"><a href="#cb72-352" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((runsco <span class="sc">-</span> <span class="fu">predict</span>(exp_m_2, <span class="at">newdata =</span> exp_df))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb72-353"><a href="#cb72-353" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-354"><a href="#cb72-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-355"><a href="#cb72-355" aria-hidden="true" tabindex="-1"></a>AIC is 538.3, 563.3, BIC is 553.0, 571.7, and PRESS is 21929.6, 36763.5, respectively. That is, EM 1 shows better performance in all aspects. But there is one thing to consider here. It is the multicollinearity of variables. Most of the batting indicators in baseball are highly correlated. Simply put, a good batter is likely to have a lot of hits and home runs are likely to have a lot of home runs. Actual data show a high correlation between hits, doubles, and home runs.</span>
<span id="cb72-356"><a href="#cb72-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-359"><a href="#cb72-359" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-360"><a href="#cb72-360" aria-hidden="true" tabindex="-1"></a><span class="co"># check the multicollinearity</span></span>
<span id="cb72-361"><a href="#cb72-361" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(tot_df[,<span class="dv">12</span><span class="sc">:</span><span class="dv">16</span>])</span>
<span id="cb72-362"><a href="#cb72-362" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(tot_df[,<span class="dv">12</span><span class="sc">:</span><span class="dv">16</span>])</span>
<span id="cb72-363"><a href="#cb72-363" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-364"><a href="#cb72-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-365"><a href="#cb72-365" aria-hidden="true" tabindex="-1"></a>Considering these points, I will choose EM 2 instead of EM 1. This is because EM 2 is much simpler using only two variables, and its explanatory power is not that low compared to EM 1.</span>
<span id="cb72-366"><a href="#cb72-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-367"><a href="#cb72-367" aria-hidden="true" tabindex="-1"></a>Now, we can use this to get the expected score of each team and the difference between the actual score and the expected score.</span>
<span id="cb72-368"><a href="#cb72-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-371"><a href="#cb72-371" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-372"><a href="#cb72-372" aria-hidden="true" tabindex="-1"></a><span class="co"># get expected score by obp, slg</span></span>
<span id="cb72-373"><a href="#cb72-373" aria-hidden="true" tabindex="-1"></a>exp_df<span class="sc">$</span>exp_score<span class="ot">&lt;-</span><span class="fu">predict</span>(exp_m_2, <span class="at">newdata =</span> exp_df)</span>
<span id="cb72-374"><a href="#cb72-374" aria-hidden="true" tabindex="-1"></a>exp_df<span class="ot">&lt;-</span>exp_df <span class="sc">%&gt;%</span></span>
<span id="cb72-375"><a href="#cb72-375" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">run_diff=</span>run_scored<span class="sc">-</span>exp_score)</span>
<span id="cb72-376"><a href="#cb72-376" aria-hidden="true" tabindex="-1"></a>exp_df[,<span class="fu">c</span>(<span class="st">"year"</span>,<span class="st">"team"</span>,<span class="st">"run_scored"</span>,<span class="st">"exp_score"</span>,<span class="st">"run_diff"</span>,<span class="st">"inter_fre_sd"</span>)]</span>
<span id="cb72-377"><a href="#cb72-377" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-378"><a href="#cb72-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-379"><a href="#cb72-379" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hb-1</span></span>
<span id="cb72-380"><a href="#cb72-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-381"><a href="#cb72-381" aria-hidden="true" tabindex="-1"></a>Hypothesis hb1 can now be verified. The basic logic is as follows. If the manager's intervention in the game has a positive effect on the team's score, the difference between the actual score and the expected score will be high in the group with a high degree of intervention in the game. If not, the difference between the actual score of the high group and the expected score will be lower than that of the low group.</span>
<span id="cb72-382"><a href="#cb72-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-385"><a href="#cb72-385" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-386"><a href="#cb72-386" aria-hidden="true" tabindex="-1"></a><span class="co"># check the score by groups</span></span>
<span id="cb72-387"><a href="#cb72-387" aria-hidden="true" tabindex="-1"></a>exp_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(inter_fre_sd) <span class="sc">%&gt;%</span></span>
<span id="cb72-388"><a href="#cb72-388" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avr_run_diff=</span><span class="fu">mean</span>(run_diff))</span>
<span id="cb72-389"><a href="#cb72-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-390"><a href="#cb72-390" aria-hidden="true" tabindex="-1"></a><span class="co"># anova</span></span>
<span id="cb72-391"><a href="#cb72-391" aria-hidden="true" tabindex="-1"></a>hb1<span class="ot">&lt;-</span><span class="fu">aov</span>(run_diff<span class="sc">~</span>inter_fre_sd, <span class="at">data=</span>exp_df)</span>
<span id="cb72-392"><a href="#cb72-392" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hb1)</span>
<span id="cb72-393"><a href="#cb72-393" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-394"><a href="#cb72-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-395"><a href="#cb72-395" aria-hidden="true" tabindex="-1"></a>The result was the opposite of the result compared to the simple score discussed earlier. In other words, the difference between the actual score and the expected score of the group with high game intervention was lower than that of the group that did not. Considering the team's basic offensive power, the manager's intervention in the game rather makes the actual score lower than the team's expected score. In other words, the manager's intervention in the game rather reduces the team's scoring ability.</span>
<span id="cb72-396"><a href="#cb72-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-397"><a href="#cb72-397" aria-hidden="true" tabindex="-1"></a>However, the **ANOVA results also showed that this did not have statistical significance at the 0.05 level.**(p value: 0.542)</span>
<span id="cb72-398"><a href="#cb72-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-399"><a href="#cb72-399" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hb-2</span></span>
<span id="cb72-400"><a href="#cb72-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-401"><a href="#cb72-401" aria-hidden="true" tabindex="-1"></a>Next, I will conduct a regression analysis to find out the effect of game intervention on the difference between actual and expected scores.</span>
<span id="cb72-402"><a href="#cb72-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-405"><a href="#cb72-405" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-406"><a href="#cb72-406" aria-hidden="true" tabindex="-1"></a><span class="co"># regression</span></span>
<span id="cb72-407"><a href="#cb72-407" aria-hidden="true" tabindex="-1"></a>hb2<span class="ot">&lt;-</span><span class="fu">lm</span>(run_diff<span class="sc">~</span>inter, exp_df)</span>
<span id="cb72-408"><a href="#cb72-408" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hb2)</span>
<span id="cb72-409"><a href="#cb72-409" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-410"><a href="#cb72-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-413"><a href="#cb72-413" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-414"><a href="#cb72-414" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(exp_df, <span class="fu">aes</span>(inter, run_diff),</span>
<span id="cb72-415"><a href="#cb72-415" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Intervention"</span>,</span>
<span id="cb72-416"><a href="#cb72-416" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Actual Score - Expected Score"</span>) <span class="sc">+</span> </span>
<span id="cb72-417"><a href="#cb72-417" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb72-418"><a href="#cb72-418" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="sc">-</span><span class="fl">0.18531</span>, <span class="at">intercept =</span> <span class="fl">37.03480</span>, <span class="at">color =</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb72-419"><a href="#cb72-419" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regression of Intervention and Run Differential in KBO League"</span>, <span class="at">x =</span> <span class="st">"Intervention"</span>, <span class="at">y =</span> <span class="st">"Actual Score - Expected Score"</span>)</span>
<span id="cb72-420"><a href="#cb72-420" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-421"><a href="#cb72-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-422"><a href="#cb72-422" aria-hidden="true" tabindex="-1"></a>As a result of the regression analysis, the regression coefficient of the actual score and the expected score was **-0.185**. In other words, the increase in game intervention negatively affects the difference between actual and expected scores, and in interpretation, the increase in game intervention has the effect of reducing actual scores compared to the team's offensive power.</span>
<span id="cb72-423"><a href="#cb72-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-424"><a href="#cb72-424" aria-hidden="true" tabindex="-1"></a>The R square value was 0.097 and the **p-value was 0.015, which was found to be significant at the 0.05 level.**</span>
<span id="cb72-425"><a href="#cb72-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-426"><a href="#cb72-426" aria-hidden="true" tabindex="-1"></a>Finally, as a result of checking whether there is a violation of assumptions necessary for regression analysis, it does not appear that special treatment is required.</span>
<span id="cb72-427"><a href="#cb72-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-430"><a href="#cb72-430" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb72-431"><a href="#cb72-431" aria-hidden="true" tabindex="-1"></a><span class="co"># check the assumptions</span></span>
<span id="cb72-432"><a href="#cb72-432" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>))</span>
<span id="cb72-433"><a href="#cb72-433" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hb2, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb72-434"><a href="#cb72-434" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb72-435"><a href="#cb72-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-436"><a href="#cb72-436" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusion</span></span>
<span id="cb72-437"><a href="#cb72-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-438"><a href="#cb72-438" aria-hidden="true" tabindex="-1"></a><span class="fu">## Regarding Ha</span></span>
<span id="cb72-439"><a href="#cb72-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-440"><a href="#cb72-440" aria-hidden="true" tabindex="-1"></a>First of all, looking at each hypothesis, in the case of Ha-1, the average score of the group with many game interventions was high (high: 765.9, normal: 754.9, low: 748.1), and in the case of Ha-2, the unit of game intervention increased the team's score by 0.1792. (Run Scored = 719.7232 + 0.1792<span class="sc">\*</span>Intervention)</span>
<span id="cb72-441"><a href="#cb72-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-442"><a href="#cb72-442" aria-hidden="true" tabindex="-1"></a>In other words, it was interpreted that the coach's intervention in the game had a positive effect on the team's scoring ability.</span>
<span id="cb72-443"><a href="#cb72-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-444"><a href="#cb72-444" aria-hidden="true" tabindex="-1"></a>However, in the case of Ha-1, the p value was 0.919, and in the case of Ha-2, the p value of the regression coefficient was 0.5354. In other words, **both hypotheses cannot be said to be statistically significant at the 0.05 significance level.**</span>
<span id="cb72-445"><a href="#cb72-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-446"><a href="#cb72-446" aria-hidden="true" tabindex="-1"></a><span class="fu">## Regarding Hb</span></span>
<span id="cb72-447"><a href="#cb72-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-448"><a href="#cb72-448" aria-hidden="true" tabindex="-1"></a>In the case of analysis using expected scores, the difference between actual scores and expected scores was used as a dependent variable(Run Differential.</span>
<span id="cb72-449"><a href="#cb72-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-450"><a href="#cb72-450" aria-hidden="true" tabindex="-1"></a>In the case of Hb-1, contrary to Ha, it was found that the gap between actual and expected scores was high when the intervention in the game was low. (high: -3.78, normal: -0.96, low: 8.26) This implies that intervention in the game is negative for the team's scoring ability. However, as a result of ANOVA analysis on this, the p value was 0.542, which was **not significant at the significance level of 0.05.**</span>
<span id="cb72-451"><a href="#cb72-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-452"><a href="#cb72-452" aria-hidden="true" tabindex="-1"></a>Next, in the case of Hb-2, it was found that game intervention had a negative effect on the gap between actual and expected scores. (Run Differential = 37.03480 -0.18531<span class="sc">\*</span>Intervention)</span>
<span id="cb72-453"><a href="#cb72-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-454"><a href="#cb72-454" aria-hidden="true" tabindex="-1"></a>In other words, like Hb-1, it can be interpreted that the manager's intervention in the game negatively affects the team's scoring ability. In addition, **the regression coefficient of intervention was also found to be significant at the significance level of 0.05 as the p value is 0.0153**.</span>
<span id="cb72-455"><a href="#cb72-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-456"><a href="#cb72-456" aria-hidden="true" tabindex="-1"></a><span class="fu">## Discussions</span></span>
<span id="cb72-457"><a href="#cb72-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-458"><a href="#cb72-458" aria-hidden="true" tabindex="-1"></a>**Of the four hypotheses, only Hb-2 was able to draw statistically significant conclusions, and that hypothesis was wrong and could be concluded at the significance level of 0.05.** In other words, it can be concluded that the manager's intervention in the game in KBO league baseball rather suppresses the actual score considering the team's expected score level.</span>
<span id="cb72-459"><a href="#cb72-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-460"><a href="#cb72-460" aria-hidden="true" tabindex="-1"></a>This conclusion is consistent with the recent trend of negatively evaluating and avoiding the manager's intervention in the game. However, when looking at the baseball game as a whole, pitching and defense should be considered in addition to hitting. In other words, only when additional research is conducted on these aspects, more rigorous discussions on the role of managers in baseball can be made.</span>
<span id="cb72-461"><a href="#cb72-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-462"><a href="#cb72-462" aria-hidden="true" tabindex="-1"></a><span class="fu"># References</span></span>
<span id="cb72-463"><a href="#cb72-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-464"><a href="#cb72-464" aria-hidden="true" tabindex="-1"></a>Lewis, M. (2004). Moneyball: The art of winning an unfair game. New York: Norton.</span>
<span id="cb72-465"><a href="#cb72-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-466"><a href="#cb72-466" aria-hidden="true" tabindex="-1"></a>Smart, D., &amp; Wolfe, R. (2003). The contribution of leadership and human resources to organizational success: An empirical assessment of performance in Major League Baseball. European Sport Management Quarterly, 3, 165--188.</span>
<span id="cb72-467"><a href="#cb72-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-468"><a href="#cb72-468" aria-hidden="true" tabindex="-1"></a>Winfree, J., &amp; Wolfe, R. (2008). Major League Baseball Managers: Do They Matter? Journal of Sport Management 22(3):303-321.</span>
<span id="cb72-469"><a href="#cb72-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-470"><a href="#cb72-470" aria-hidden="true" tabindex="-1"></a>Lee, J., Kim, Y., &amp; Lee, J. (2007). Relationship between Leadership of Korean Professional Baseball Coaches and Performance of Their Teams. Soonchunhyang Natural Science Research 13(2):145-155.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>