<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sai Padma pothula">
<meta name="dcterms.date" content="2023-05-02">

<title>Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Homework 4">
<meta name="twitter:description" content="">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 4</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Homework 4</div>
    <div class="quarto-category">sai Pothula</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sai Padma pothula </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 2, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: effects</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Please cite as: </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
</div>
</div>
<p>A:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> (<span class="fl">53.8</span> <span class="sc">*</span> <span class="dv">1240</span>) <span class="sc">+</span> (<span class="fl">2.84</span> <span class="sc">*</span> <span class="dv">18000</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107296</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>actual_value <span class="ot">=</span> <span class="dv">145000</span> <span class="sc">-</span> y</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>actual_value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37704</code></pre>
</div>
</div>
<p>The actual selling price exceeded the predicted selling price by $37,704, indicating that the home sold for a higher price than what was estimated by the model.</p>
<p>1B: When the lot size is fixed, the coefficient of x1 (53.8) captures the specific impact of the home size on the predicted selling price, controlling for the influence of lot size. Therefore, for a fixed lot size, the house selling price is predicted to increase by $53.8 for each additional square foot increase in home size, as determined by the coefficient of x1 in the model.</p>
<p>1C: One-square-foot increase in home size is associated with an increase in price of $53.8. One- square-foot increase in lot size is associated with an increase in price of $2.84.(53.8 / 2.84) to have the same impact as a one-square-foot increase in home size, the lot size would need to increase by approximately 18.90 square feet according to the given prediction equation.</p>
<p>2A:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> salary <span class="sc">~</span> sex, <span class="at">data =</span> salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by sex
t = 1.7744, df = 21.591, p-value = 0.09009
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -567.8539 7247.1471
sample estimates:
  mean in group Male mean in group Female 
            24696.79             21357.14 </code></pre>
</div>
</div>
<p>The results of the t-test indicate that there is a difference between the mean salary for men and women. However, with a p-value of 0.09009, we do not have enough evidence to reject the null hypothesis at the 95% confidence level. In other words, we cannot conclude that there is a statistically significant difference in the mean salary between men and women when considering only the variable of sex.</p>
<p>2B</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary) <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">confint</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept) 14134.4059 17357.68946
degreePhD    -663.2482  3440.47485
rankAssoc    2985.4107  7599.31080
rankProf     8396.1546 13841.37340
sexFemale    -697.8183  3030.56452
year          285.1433   667.47476
ysdeg        -280.6397    31.49105</code></pre>
</div>
</div>
<p>The 95% confidence interval for the “sexFemale” variable is (-697, 3031). This confidence interval indicates that, when considering other variables, female faculty members may earn approximately $697 less to $3031 more in salary compared to male faculty members. This range provides an estimate of the potential difference in salaries between the genders, while taking into account the influence of other factors in the dataset.</p>
<p>2C:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ., data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Among the predictor variables examined, both rank and years in the current rank have statistically significant effects on salary. Controlling for all other factors, being at the Associate rank is associated with an average salary increase of $5,292.36 compared to the Assistant rank, while being a full professor corresponds to an average salary increase of $11,118.76 relative to the Assistant rank.</p>
<p>Additionally, each additional year in the current rank is linked to an average salary increase of $476.31. On the other hand, the number of years since obtaining the highest degree does not have a statistically significant impact on salary, suggesting that it does not contribute significantly to changes in salary when controlling for other factors.</p>
<p>Regarding sex, controlling for all other variables, being a female professor is associated with a salary increase of $1,166 compared to being a male professor. However, this result is not statistically significant, as indicated by the p-value of 0.214.</p>
<p>Finally, the variable of degree does not show a statistically significant effect on salary when controlling for other variables. Specifically, having a PhD is associated with a salary increase of $1,388.61 compared to having a master’s degree, but this result is not statistically significant with a p-value of 0.180.</p>
<p>In summary, among the examined predictor variables, rank and years in the current rank have statistically significant impacts on salary, while the effects of sex, degree, and years since obtaining the highest degree are not statistically significant when controlling for other factors.</p>
<p>2D:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">'Prof'</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ., data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  26864.81    1375.29  19.534  &lt; 2e-16 ***
degreePhD     1388.61    1018.75   1.363    0.180    
rankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***
rankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***
sexFemale     1166.37     925.57   1.260    0.214    
year           476.31      94.91   5.018 8.65e-06 ***
ysdeg         -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>n the updated model, the coefficients for the dummy variables representing the two categories other than the reference category (Prof) are as follows: rankAsst being -11118 and rankAssoc being -5826. These coefficients indicate the difference in salary compared to the reference category (Full Professors), while controlling for other variables.</p>
<p>Specifically, the coefficient of -11118 for rankAsst suggests that Assistant Professors earn $11118 less on average than Full Professors, considering the influence of other factors. Similarly, the coefficient of -5826 for rankAssoc indicates that Associate Professors earn $5826 less on average than Full Professors, controlling for other variables.</p>
<p>In summary, the new model presents the same information as before, but in a different way, emphasizing the salary differences between each rank category (Assistant and Associate Professors) and the reference category (Full Professors) while taking into account the impact of other variables.</p>
<p>2E</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the initial model</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
year          351.97     142.48   2.470 0.017185 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>With the exclusion of the “rank” variable from the model, the findings regarding the impact of different predictor variables on salary have changed.</p>
<p>Degree: Without the “rank” variable, the variable “degreePhD” now becomes a statistically significant predictor. When controlling for all other factors, having a PhD (compared to a master’s degree) is associated with a decrease in salary of $3,299.35. This is notably different from when the “rank” variable was included, where there was no statistical significance and a PhD increased salary by $1,388.61.</p>
<p>Years Since Highest Degree: In the absence of the “rank” variable, the variable “ysdeg” (years since obtaining the highest degree) becomes a statistically significant predictor. Controlling for other variables, each passing year now results in an increase in salary of $339.40. This differs from the previous model with the “rank” variable, where there was no statistical significance and a decrease in salary was suggested.</p>
<p>Year: The variable “year” remains statistically significant even after excluding the “rank” variable, although the p-value has increased. Controlling for other factors, each additional year of experience now contributes $351.97 to salary.</p>
<p>Sex: The result for the variable “sex” remains not statistically significant, indicating that its impact on salary did not change significantly. However, the direction of the effect has changed from positive to negative.</p>
<p>2F</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>newDean <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Run regression analysis with newDean included as a predictor variable</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>lm_salary_NewDean <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> newDean, <span class="at">data =</span> salary)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_salary_NewDean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + newDean, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-3403.3 -1387.0  -167.0   528.2  9233.8 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  26588.79    1168.06  22.763  &lt; 2e-16 ***
degreePhD      818.93     797.48   1.027   0.3100    
rankAsst    -11096.95    1191.00  -9.317 4.54e-12 ***
rankAssoc    -6124.28    1028.58  -5.954 3.65e-07 ***
sexFemale      907.14     840.54   1.079   0.2862    
year           434.85      78.89   5.512 1.65e-06 ***
newDean      -2163.46    1072.04  -2.018   0.0496 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2362 on 45 degrees of freedom
Multiple R-squared:  0.8594,    Adjusted R-squared:  0.8407 
F-statistic: 45.86 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The analysis provides evidence supporting the hypothesis that individuals hired by the new Dean are earning higher salaries compared to those who were not. The statistical significance of the “newDean” variable, with a p-value of 0.0496, indicates that there is a notable difference in salaries between these two groups, even when considering other variables. Specifically, the findings suggest that faculty members who were not hired by the new Dean earn an average of $2,163.46 less, holding other factors constant. 3</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>A</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In the regression model, both the “Size” and “New” variables exhibit positive associations with the “Price” of the house. Furthermore, these associations are statistically significant at the 5% level. Specifically, a one-square-foot increase in the size of the house is associated with an average increase in price of $116, while controlling for whether the house is new or not. Additionally, new houses, when compared to old houses of the same size, have an average price difference of $57,736, indicating that new houses tend to be more expensive.</p>
<p>B y = −40,230.867 + 116.132(Size) + 57736.283(New).</p>
<p>Where:</p>
<p>y represents the predicted selling price.</p>
<p>y = −40,230.867 + 116.132(Size) + 57736.283(1). #New house y = −40,230.867 + 116.132(Size) #Old house New houses have high prices</p>
<p>C</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#New house</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>y_new <span class="ot">=</span> <span class="sc">-</span><span class="fl">40230.867</span><span class="sc">+</span>(<span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span>)<span class="sc">+</span>(<span class="fl">57736.283</span><span class="sc">*</span><span class="dv">1</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>y_new</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 365901.4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Old house </span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>y_old <span class="ot">=</span> <span class="sc">-</span><span class="fl">40230.867</span><span class="sc">+</span>(<span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span>)<span class="sc">+</span>(<span class="fl">57736.283</span><span class="sc">*</span><span class="dv">0</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>y_old</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 308165.1</code></pre>
</div>
</div>
<p>The predicted selling price for a new 3,000 square foot home is $365,901.40. The predicted selling price for a 3,000 square foot home that is not new is $308,165.10.</p>
<p>D</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size <span class="sc">*</span> New, <span class="at">data =</span> house.selling.price)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New + Size * New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>E</p>
<p>New_home_P = −22227.808+104.438∗size+−78527.502∗1+61.916∗Size∗1 = −100755.3+166.354∗size</p>
<p>Old_home_P = −22227.808+104.438∗size+−78527.502∗0+61.916∗Size∗0 = −22227.808+104.438∗size</p>
<p>F</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>New_home <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span>) <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> (<span class="fl">61.916</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>Old_home <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>New_home</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 398306.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>Old_home</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 291086.2</code></pre>
</div>
</div>
<p>G</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>New_home <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span>) <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> (<span class="fl">61.916</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>Old_home <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>New_home</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 148775.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>Old_home</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 134429.2</code></pre>
</div>
</div>
<p>For homes with a size of 3000 square feet, the predicted selling price is $398,306.70 for new homes and $291,086.20 for not new homes. This indicates a significant difference of $107,220.50 in the sale price between new and not new homes of the same size.</p>
<p>In contrast, for homes with a size of 1500 square feet, the predicted selling price is $148,775.70 for new homes and $134,429.20 for not new homes. The difference in sale price between new and not new homes in this case is smaller, amounting to $14,346.50.</p>
<p>The disparity in the price difference between new and not new homes for different sizes can be explained by the structure of the prediction equation. According to the predictive model, a house needs to have a size of approximately 606 square feet before it can be sold at a profit. In other words, only the square footage beyond this threshold contributes to the increase in the sale price.</p>
<p>For instance, a 1500 square foot home has approximately 894 “money-making” square feet, while a 3000 square foot home has around 2394 such square feet. Each additional money-making square foot adds approximately $166.354 to the sale price.</p>
<p>Therefore, the observed differences in sale prices align with the predictive model’s expectations, reflecting the influence of the size of the home on its profitability and the corresponding impact on the selling price.</p>
<p>H: The inclusion of the interaction term in the model improves the representation of the relationship between size, newness, and the selling price. This is supported by the statistical significance of the interaction term, as indicated by its low p-value. Additionally, the adjusted R-squared value for the model with the interaction (0.7363) is higher compared to the model without the interaction (0.7169).</p>
<p>These findings suggest that the interaction between size and newness plays a significant role in explaining the variation in the selling price. The higher adjusted R-squared value indicates that the model with the interaction term captures a greater proportion of the variability in the data, providing a better fit to the observed selling prices.</p>
<p>Therefore, the model with the interaction term is more reliable and informative in understanding how both size and newness influence the predicted selling price, taking into account their combined effect on the outcome variable.</p>


<!-- -->


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb44" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 4"</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Sai Padma  pothula"</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> ""</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/02/2023"</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - Homework 4</span></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - sai Pothula</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-27"><a href="#cb44-27" aria-hidden="true" tabindex="-1"></a>A:</span>
<span id="cb44-30"><a href="#cb44-30" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-31"><a href="#cb44-31" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> (<span class="fl">53.8</span> <span class="sc">*</span> <span class="dv">1240</span>) <span class="sc">+</span> (<span class="fl">2.84</span> <span class="sc">*</span> <span class="dv">18000</span>)</span>
<span id="cb44-32"><a href="#cb44-32" aria-hidden="true" tabindex="-1"></a>y</span>
<span id="cb44-33"><a href="#cb44-33" aria-hidden="true" tabindex="-1"></a>actual_value <span class="ot">=</span> <span class="dv">145000</span> <span class="sc">-</span> y</span>
<span id="cb44-34"><a href="#cb44-34" aria-hidden="true" tabindex="-1"></a>actual_value</span>
<span id="cb44-35"><a href="#cb44-35" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-36"><a href="#cb44-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-37"><a href="#cb44-37" aria-hidden="true" tabindex="-1"></a>The actual selling price exceeded the predicted selling price by $37,704, indicating that the home sold for a higher price than what was estimated by the model.</span>
<span id="cb44-38"><a href="#cb44-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-39"><a href="#cb44-39" aria-hidden="true" tabindex="-1"></a>1B: When the lot size is fixed, the coefficient of x1 (53.8) captures the specific impact of the home size on the predicted selling price, controlling for the influence of lot size. Therefore, for a fixed lot size, the house selling price is predicted to increase by $53.8 for each additional square foot increase in home size, as determined by the coefficient of x1 in the model.</span>
<span id="cb44-40"><a href="#cb44-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-41"><a href="#cb44-41" aria-hidden="true" tabindex="-1"></a>1C: One-square-foot increase in home size is associated with an increase in price of $53.8. One-</span>
<span id="cb44-42"><a href="#cb44-42" aria-hidden="true" tabindex="-1"></a>square-foot increase in lot size is associated with an increase in price of $2.84.(53.8 / 2.84) to have the same impact as a one-square-foot increase in home size, the lot size would need to increase by approximately 18.90 square feet according to the given prediction equation.</span>
<span id="cb44-43"><a href="#cb44-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-44"><a href="#cb44-44" aria-hidden="true" tabindex="-1"></a>2A:</span>
<span id="cb44-47"><a href="#cb44-47" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-48"><a href="#cb44-48" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span>
<span id="cb44-49"><a href="#cb44-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-50"><a href="#cb44-50" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-51"><a href="#cb44-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-54"><a href="#cb44-54" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-55"><a href="#cb44-55" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> salary <span class="sc">~</span> sex, <span class="at">data =</span> salary)</span>
<span id="cb44-56"><a href="#cb44-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-57"><a href="#cb44-57" aria-hidden="true" tabindex="-1"></a>The results of the t-test indicate that there is a difference between the mean salary for men  and women. However, with a p-value of 0.09009, we do not have enough evidence to reject the null hypothesis at the 95% confidence level. In other words, we cannot conclude that there is a statistically significant difference in the mean salary between men and women when considering only the variable of sex.</span>
<span id="cb44-58"><a href="#cb44-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-59"><a href="#cb44-59" aria-hidden="true" tabindex="-1"></a>2B</span>
<span id="cb44-62"><a href="#cb44-62" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-63"><a href="#cb44-63" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary) <span class="sc">|&gt;</span></span>
<span id="cb44-64"><a href="#cb44-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">confint</span>() </span>
<span id="cb44-65"><a href="#cb44-65" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-66"><a href="#cb44-66" aria-hidden="true" tabindex="-1"></a>The 95% confidence interval for the "sexFemale" variable is (-697, 3031). This confidence interval indicates that, when considering other variables, female faculty members may earn approximately $697 less to $3031 more in salary compared to male faculty members. This range provides an estimate of the potential difference in salaries between the genders, while taking into account the influence of other factors in the dataset.</span>
<span id="cb44-67"><a href="#cb44-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-68"><a href="#cb44-68" aria-hidden="true" tabindex="-1"></a>2C:</span>
<span id="cb44-71"><a href="#cb44-71" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-72"><a href="#cb44-72" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary))</span>
<span id="cb44-73"><a href="#cb44-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-74"><a href="#cb44-74" aria-hidden="true" tabindex="-1"></a>Among the predictor variables examined, both rank and years in the current rank have statistically significant effects on salary. Controlling for all other factors, being at the Associate rank is associated with an average salary increase of $5,292.36 compared to the Assistant rank, while being a full professor corresponds to an average salary increase of $11,118.76 relative to the Assistant rank.</span>
<span id="cb44-75"><a href="#cb44-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-76"><a href="#cb44-76" aria-hidden="true" tabindex="-1"></a>Additionally, each additional year in the current rank is linked to an average salary increase of $476.31. On the other hand, the number of years since obtaining the highest degree does not have a statistically significant impact on salary, suggesting that it does not contribute significantly to changes in salary when controlling for other factors.</span>
<span id="cb44-77"><a href="#cb44-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-78"><a href="#cb44-78" aria-hidden="true" tabindex="-1"></a>Regarding sex, controlling for all other variables, being a female professor is associated with a salary increase of $1,166 compared to being a male professor. However, this result is not statistically significant, as indicated by the p-value of 0.214.</span>
<span id="cb44-79"><a href="#cb44-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-80"><a href="#cb44-80" aria-hidden="true" tabindex="-1"></a>Finally, the variable of degree does not show a statistically significant effect on salary when controlling for other variables. Specifically, having a PhD is associated with a salary increase of $1,388.61 compared to having a master's degree, but this result is not statistically significant with a p-value of 0.180.</span>
<span id="cb44-81"><a href="#cb44-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-82"><a href="#cb44-82" aria-hidden="true" tabindex="-1"></a>In summary, among the examined predictor variables, rank and years in the current rank have statistically significant impacts on salary, while the effects of sex, degree, and years since obtaining the highest degree are not statistically significant when controlling for other factors.</span>
<span id="cb44-83"><a href="#cb44-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-84"><a href="#cb44-84" aria-hidden="true" tabindex="-1"></a>2D:</span>
<span id="cb44-87"><a href="#cb44-87" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-88"><a href="#cb44-88" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">'Prof'</span>)</span>
<span id="cb44-89"><a href="#cb44-89" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary))</span>
<span id="cb44-90"><a href="#cb44-90" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-91"><a href="#cb44-91" aria-hidden="true" tabindex="-1"></a>n the updated model, the coefficients for the dummy variables representing the two categories other than the reference category (Prof) are as follows: rankAsst being -11118 and rankAssoc being -5826. These coefficients indicate the difference in salary compared to the reference category (Full Professors), while controlling for other variables.</span>
<span id="cb44-92"><a href="#cb44-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-93"><a href="#cb44-93" aria-hidden="true" tabindex="-1"></a>Specifically, the coefficient of -11118 for rankAsst suggests that Assistant Professors earn $11118 less on average than Full Professors, considering the influence of other factors. Similarly, the coefficient of -5826 for rankAssoc indicates that Associate Professors earn $5826 less on average than Full Professors, controlling for other variables.</span>
<span id="cb44-94"><a href="#cb44-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-95"><a href="#cb44-95" aria-hidden="true" tabindex="-1"></a>In summary, the new model presents the same information as before, but in a different way, emphasizing the salary differences between each rank category (Assistant and Associate Professors) and the reference category (Full Professors) while taking into account the impact of other variables.</span>
<span id="cb44-96"><a href="#cb44-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-97"><a href="#cb44-97" aria-hidden="true" tabindex="-1"></a>2E</span>
<span id="cb44-100"><a href="#cb44-100" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-101"><a href="#cb44-101" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb44-102"><a href="#cb44-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-103"><a href="#cb44-103" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the initial model</span></span>
<span id="cb44-104"><a href="#cb44-104" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb44-105"><a href="#cb44-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-106"><a href="#cb44-106" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-107"><a href="#cb44-107" aria-hidden="true" tabindex="-1"></a>With the exclusion of the "rank" variable from the model, the findings regarding the impact of different predictor variables on salary have changed.</span>
<span id="cb44-108"><a href="#cb44-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-109"><a href="#cb44-109" aria-hidden="true" tabindex="-1"></a>Degree:</span>
<span id="cb44-110"><a href="#cb44-110" aria-hidden="true" tabindex="-1"></a>Without the "rank" variable, the variable "degreePhD" now becomes a statistically significant predictor. When controlling for all other factors, having a PhD (compared to a master's degree) is associated with a decrease in salary of $3,299.35. This is notably different from when the "rank" variable was included, where there was no statistical significance and a PhD increased salary by $1,388.61.</span>
<span id="cb44-111"><a href="#cb44-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-112"><a href="#cb44-112" aria-hidden="true" tabindex="-1"></a>Years Since Highest Degree:</span>
<span id="cb44-113"><a href="#cb44-113" aria-hidden="true" tabindex="-1"></a>In the absence of the "rank" variable, the variable "ysdeg" (years since obtaining the highest degree) becomes a statistically significant predictor. Controlling for other variables, each passing year now results in an increase in salary of $339.40. This differs from the previous model with the "rank" variable, where there was no statistical significance and a decrease in salary was suggested.</span>
<span id="cb44-114"><a href="#cb44-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-115"><a href="#cb44-115" aria-hidden="true" tabindex="-1"></a>Year:</span>
<span id="cb44-116"><a href="#cb44-116" aria-hidden="true" tabindex="-1"></a>The variable "year" remains statistically significant even after excluding the "rank" variable, although the p-value has increased. Controlling for other factors, each additional year of experience now contributes $351.97 to salary.</span>
<span id="cb44-117"><a href="#cb44-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-118"><a href="#cb44-118" aria-hidden="true" tabindex="-1"></a>Sex:</span>
<span id="cb44-119"><a href="#cb44-119" aria-hidden="true" tabindex="-1"></a>The result for the variable "sex" remains not statistically significant, indicating that its impact on salary did not change significantly. However, the direction of the effect has changed from positive to negative.</span>
<span id="cb44-120"><a href="#cb44-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-121"><a href="#cb44-121" aria-hidden="true" tabindex="-1"></a>2F</span>
<span id="cb44-124"><a href="#cb44-124" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-125"><a href="#cb44-125" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>newDean <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb44-126"><a href="#cb44-126" aria-hidden="true" tabindex="-1"></a><span class="co"># Run regression analysis with newDean included as a predictor variable</span></span>
<span id="cb44-127"><a href="#cb44-127" aria-hidden="true" tabindex="-1"></a>lm_salary_NewDean <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> newDean, <span class="at">data =</span> salary)</span>
<span id="cb44-128"><a href="#cb44-128" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_salary_NewDean)</span>
<span id="cb44-129"><a href="#cb44-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-130"><a href="#cb44-130" aria-hidden="true" tabindex="-1"></a>The analysis provides evidence supporting the hypothesis that individuals hired by the new Dean are earning higher salaries compared to those who were not. The statistical significance of the "newDean" variable, with a p-value of 0.0496, indicates that there is a notable difference in salaries between these two groups, even when considering other variables. Specifically, the findings suggest that faculty members who were not hired by the new Dean earn an average of $2,163.46 less, holding other factors constant.</span>
<span id="cb44-131"><a href="#cb44-131" aria-hidden="true" tabindex="-1"></a>3</span>
<span id="cb44-132"><a href="#cb44-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-135"><a href="#cb44-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-136"><a href="#cb44-136" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price)</span>
<span id="cb44-137"><a href="#cb44-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-138"><a href="#cb44-138" aria-hidden="true" tabindex="-1"></a>A</span>
<span id="cb44-141"><a href="#cb44-141" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-142"><a href="#cb44-142" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price)</span>
<span id="cb44-143"><a href="#cb44-143" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb44-144"><a href="#cb44-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-145"><a href="#cb44-145" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-146"><a href="#cb44-146" aria-hidden="true" tabindex="-1"></a>In the regression model, both the "Size" and "New" variables exhibit positive associations with the "Price" of the house. Furthermore, these associations are statistically significant at the 5% level. Specifically, a one-square-foot increase in the size of the house is associated with an average increase in price of $116, while controlling for whether the house is new or not. Additionally, new houses, when compared to old houses of the same size, have an average price difference of $57,736, indicating that new houses tend to be more expensive.</span>
<span id="cb44-147"><a href="#cb44-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-148"><a href="#cb44-148" aria-hidden="true" tabindex="-1"></a>B</span>
<span id="cb44-149"><a href="#cb44-149" aria-hidden="true" tabindex="-1"></a>y = −40,230.867 + 116.132(Size) + 57736.283(New).</span>
<span id="cb44-150"><a href="#cb44-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-151"><a href="#cb44-151" aria-hidden="true" tabindex="-1"></a>Where:</span>
<span id="cb44-152"><a href="#cb44-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-153"><a href="#cb44-153" aria-hidden="true" tabindex="-1"></a>y represents the predicted selling price.</span>
<span id="cb44-154"><a href="#cb44-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-155"><a href="#cb44-155" aria-hidden="true" tabindex="-1"></a>y = −40,230.867 + 116.132(Size) + 57736.283(1). #New house </span>
<span id="cb44-156"><a href="#cb44-156" aria-hidden="true" tabindex="-1"></a>y = −40,230.867 + 116.132(Size) #Old house </span>
<span id="cb44-157"><a href="#cb44-157" aria-hidden="true" tabindex="-1"></a>New houses have high prices </span>
<span id="cb44-158"><a href="#cb44-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-159"><a href="#cb44-159" aria-hidden="true" tabindex="-1"></a>C</span>
<span id="cb44-162"><a href="#cb44-162" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-163"><a href="#cb44-163" aria-hidden="true" tabindex="-1"></a><span class="co">#New house</span></span>
<span id="cb44-164"><a href="#cb44-164" aria-hidden="true" tabindex="-1"></a>y_new <span class="ot">=</span> <span class="sc">-</span><span class="fl">40230.867</span><span class="sc">+</span>(<span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span>)<span class="sc">+</span>(<span class="fl">57736.283</span><span class="sc">*</span><span class="dv">1</span>)</span>
<span id="cb44-165"><a href="#cb44-165" aria-hidden="true" tabindex="-1"></a>y_new</span>
<span id="cb44-166"><a href="#cb44-166" aria-hidden="true" tabindex="-1"></a><span class="co">#Old house </span></span>
<span id="cb44-167"><a href="#cb44-167" aria-hidden="true" tabindex="-1"></a>y_old <span class="ot">=</span> <span class="sc">-</span><span class="fl">40230.867</span><span class="sc">+</span>(<span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span>)<span class="sc">+</span>(<span class="fl">57736.283</span><span class="sc">*</span><span class="dv">0</span>)</span>
<span id="cb44-168"><a href="#cb44-168" aria-hidden="true" tabindex="-1"></a>y_old</span>
<span id="cb44-169"><a href="#cb44-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-170"><a href="#cb44-170" aria-hidden="true" tabindex="-1"></a>The predicted selling price for a new 3,000 square foot home is $365,901.40. The predicted selling price for a 3,000 square foot home that is not new is $308,165.10.</span>
<span id="cb44-171"><a href="#cb44-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-172"><a href="#cb44-172" aria-hidden="true" tabindex="-1"></a>D</span>
<span id="cb44-175"><a href="#cb44-175" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-176"><a href="#cb44-176" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size <span class="sc">*</span> New, <span class="at">data =</span> house.selling.price)</span>
<span id="cb44-177"><a href="#cb44-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-178"><a href="#cb44-178" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb44-179"><a href="#cb44-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-180"><a href="#cb44-180" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-181"><a href="#cb44-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-182"><a href="#cb44-182" aria-hidden="true" tabindex="-1"></a>E</span>
<span id="cb44-183"><a href="#cb44-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-184"><a href="#cb44-184" aria-hidden="true" tabindex="-1"></a>New_home_P = −22227.808+104.438∗size+−78527.502∗1+61.916∗Size∗1 = −100755.3+166.354∗size</span>
<span id="cb44-185"><a href="#cb44-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-186"><a href="#cb44-186" aria-hidden="true" tabindex="-1"></a>Old_home_P = −22227.808+104.438∗size+−78527.502∗0+61.916∗Size∗0 = −22227.808+104.438∗size</span>
<span id="cb44-187"><a href="#cb44-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-188"><a href="#cb44-188" aria-hidden="true" tabindex="-1"></a>F</span>
<span id="cb44-191"><a href="#cb44-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-192"><a href="#cb44-192" aria-hidden="true" tabindex="-1"></a>New_home <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span>) <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> (<span class="fl">61.916</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb44-193"><a href="#cb44-193" aria-hidden="true" tabindex="-1"></a>Old_home <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb44-194"><a href="#cb44-194" aria-hidden="true" tabindex="-1"></a>New_home</span>
<span id="cb44-195"><a href="#cb44-195" aria-hidden="true" tabindex="-1"></a>Old_home</span>
<span id="cb44-196"><a href="#cb44-196" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-197"><a href="#cb44-197" aria-hidden="true" tabindex="-1"></a>G</span>
<span id="cb44-200"><a href="#cb44-200" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-201"><a href="#cb44-201" aria-hidden="true" tabindex="-1"></a>New_home <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span>) <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> (<span class="fl">61.916</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb44-202"><a href="#cb44-202" aria-hidden="true" tabindex="-1"></a>Old_home <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb44-203"><a href="#cb44-203" aria-hidden="true" tabindex="-1"></a>New_home</span>
<span id="cb44-204"><a href="#cb44-204" aria-hidden="true" tabindex="-1"></a>Old_home</span>
<span id="cb44-205"><a href="#cb44-205" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-206"><a href="#cb44-206" aria-hidden="true" tabindex="-1"></a>For homes with a size of 3000 square feet, the predicted selling price is $398,306.70 for new homes and $291,086.20 for not new homes. This indicates a significant difference of $107,220.50 in the sale price between new and not new homes of the same size.</span>
<span id="cb44-207"><a href="#cb44-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-208"><a href="#cb44-208" aria-hidden="true" tabindex="-1"></a>In contrast, for homes with a size of 1500 square feet, the predicted selling price is $148,775.70 for new homes and $134,429.20 for not new homes. The difference in sale price between new and not new homes in this case is smaller, amounting to $14,346.50.</span>
<span id="cb44-209"><a href="#cb44-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-210"><a href="#cb44-210" aria-hidden="true" tabindex="-1"></a>The disparity in the price difference between new and not new homes for different sizes can be explained by the structure of the prediction equation. According to the predictive model, a house needs to have a size of approximately 606 square feet before it can be sold at a profit. In other words, only the square footage beyond this threshold contributes to the increase in the sale price.</span>
<span id="cb44-211"><a href="#cb44-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-212"><a href="#cb44-212" aria-hidden="true" tabindex="-1"></a>For instance, a 1500 square foot home has approximately 894 "money-making" square feet, while a 3000 square foot home has around 2394 such square feet. Each additional money-making square foot adds approximately $166.354 to the sale price.</span>
<span id="cb44-213"><a href="#cb44-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-214"><a href="#cb44-214" aria-hidden="true" tabindex="-1"></a>Therefore, the observed differences in sale prices align with the predictive model's expectations, reflecting the influence of the size of the home on its profitability and the corresponding impact on the selling price.</span>
<span id="cb44-215"><a href="#cb44-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-216"><a href="#cb44-216" aria-hidden="true" tabindex="-1"></a>H: The inclusion of the interaction term in the model improves the representation of the relationship between size, newness, and the selling price. This is supported by the statistical significance of the interaction term, as indicated by its low p-value. Additionally, the adjusted R-squared value for the model with the interaction (0.7363) is higher compared to the model without the interaction (0.7169).</span>
<span id="cb44-217"><a href="#cb44-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-218"><a href="#cb44-218" aria-hidden="true" tabindex="-1"></a>These findings suggest that the interaction between size and newness plays a significant role in explaining the variation in the selling price. The higher adjusted R-squared value indicates that the model with the interaction term captures a greater proportion of the variability in the data, providing a better fit to the observed selling prices.</span>
<span id="cb44-219"><a href="#cb44-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-220"><a href="#cb44-220" aria-hidden="true" tabindex="-1"></a>Therefore, the model with the interaction term is more reliable and informative in understanding how both size and newness influence the predicted selling price, taking into account their combined effect on the outcome variable.</span>
<span id="cb44-221"><a href="#cb44-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-222"><a href="#cb44-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-223"><a href="#cb44-223" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>