---
title: "Homework - 2"
author: "Hannah Rosenbaum"
description: "Homework 2"
date: "05/04/2023"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - hw2
  - desriptive statistics 
  - probability
---

# Question 1

CI = x_bar +- (t \* s/n\*\*0.5)

## Bypass

x_bar = 19

n = 539

s = 10

t = (1 - 0.9) / 2 = 0.05

CI = (19 - (0.05 \* 10/539\*\*0.5), 19 + (0.05 \* 10/539\*\*0.5))

= (18.978, 19.021)

## Angiography

x_bar = 18

n = 847

s = 9

t = (1 - 0.9) / 2 = 0.05

CI = (18 - (0.05 \* 9/847\*\*0.5), 18 + (0.05 \* 9/847\*\*0.5))

= (17.984, 18.015)

The confidence interval is narrower for Angiography (0.031) by a difference of 0.012.

# Question 2

n = 1031

t = 0.05

p = 567 \* 0.05 / 1031

= 0.0272

# Question 3

CI = x_bar +- (t \* s/n\*\*0.5)

x_bar = 5

t = 0.05

n = n

CI = (30, 200)

s = 42.5

30 = 5 - (0.05 \* 42.5 / (n\*\*0.5))

-25 \* n\*\*0.5 = 2.125

n = 735.766

# Question 4

x_bar = 500

### a

alpha = 0.05

p = 1 - (410/500) = 0.18

The p-value is greater than the alpha.

### b

p = 1 - (410 / 500 + 90) = 0.305

The p-value is greater than the alpha.

### c

p = 1 - (410/500) = 0.18

The p-value is greater than the alpha.

# Question 5

### a

t = (519.5 - 500) / (10 / sqrt(1000))

= 19.5 / 0.316

= 61.71

t = (519.7 - 500) / (10 / sqrt(1000))

= 19.7 / 0.316

= 62.342

### b

Jones' test is statistically significant by a factor of 0.01. The test Smith concluded is not statistically significant by 0.01.

### c

Simply stating you 'reject the hypothesis' does not convey the significance of the p-value gathered. If the conclusion includes an extreme difference between the p-value found and alpha-value stated, then you can show a test has passed or failed.

# Question 6

H0 = Children in higher grades eat healthy food at higher rates.

Creating a confidence interval of 95%.

Children in grade seven eat more healthily than in grade six, and children in grade eight eat better than in grade seven.

# Question 7

H0 = There is a significant difference in means between Area 1-Area 2 and Area 1-Area 3.

A t-test should be performed.

There is not a significant difference in Area 1's means compared to 2 and 3.
