<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Akhilesh Kumar Meghwal">
<meta name="dcterms.date" content="2023-02-27">
<meta name="description" content="The second homework">

<title>Homework 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="styles.css">
<meta name="twitter:title" content="Homework 2">
<meta name="twitter:description" content="The second homework">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a>
  <ul class="collapse">
  <li><a href="#data-table" id="toc-data-table" class="nav-link" data-scroll-target="#data-table">Data table</a></li>
  <li><a href="#confidence-interval-calculation-for-bypass-and-angiography" id="toc-confidence-interval-calculation-for-bypass-and-angiography" class="nav-link" data-scroll-target="#confidence-interval-calculation-for-bypass-and-angiography">Confidence Interval Calculation for Bypass and Angiography</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#sample-proportions-test" id="toc-sample-proportions-test" class="nav-link" data-scroll-target="#sample-proportions-test">1-sample proportions test</a></li>
  <li><a href="#conclusion-1" id="toc-conclusion-1" class="nav-link" data-scroll-target="#conclusion-1">Conclusion</a></li>
  </ul></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a>
  <ul class="collapse">
  <li><a href="#sample-size-calculation" id="toc-sample-size-calculation" class="nav-link" data-scroll-target="#sample-size-calculation">Sample Size Calculation</a></li>
  <li><a href="#conclusion-2" id="toc-conclusion-2" class="nav-link" data-scroll-target="#conclusion-2">Conclusion</a></li>
  </ul></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a>
  <ul class="collapse">
  <li><a href="#question-4-a" id="toc-question-4-a" class="nav-link" data-scroll-target="#question-4-a">Question 4-A</a></li>
  <li><a href="#test-statistic-and-p-value-calculation" id="toc-test-statistic-and-p-value-calculation" class="nav-link" data-scroll-target="#test-statistic-and-p-value-calculation">Test Statistic and p value calculation</a></li>
  <li><a href="#conclusion-3" id="toc-conclusion-3" class="nav-link" data-scroll-target="#conclusion-3">Conclusion</a></li>
  <li><a href="#question-4-b" id="toc-question-4-b" class="nav-link" data-scroll-target="#question-4-b">Question 4-B</a></li>
  <li><a href="#p-value-calculation" id="toc-p-value-calculation" class="nav-link" data-scroll-target="#p-value-calculation">p-value calculation</a></li>
  <li><a href="#conclusion-4" id="toc-conclusion-4" class="nav-link" data-scroll-target="#conclusion-4">Conclusion</a></li>
  <li><a href="#question-4-c" id="toc-question-4-c" class="nav-link" data-scroll-target="#question-4-c">Question 4-C</a></li>
  <li><a href="#p-value-calculation-1" id="toc-p-value-calculation-1" class="nav-link" data-scroll-target="#p-value-calculation-1">p-value calculation</a></li>
  <li><a href="#conclusion-5" id="toc-conclusion-5" class="nav-link" data-scroll-target="#conclusion-5">Conclusion</a></li>
  </ul></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a>
  <ul class="collapse">
  <li><a href="#question-5-a" id="toc-question-5-a" class="nav-link" data-scroll-target="#question-5-a">Question 5-A</a></li>
  <li><a href="#calculating-t-statistic-and-p-value-for-jones" id="toc-calculating-t-statistic-and-p-value-for-jones" class="nav-link" data-scroll-target="#calculating-t-statistic-and-p-value-for-jones">Calculating t-statistic and p-value for Jones</a></li>
  <li><a href="#calculating-t-statistic-and-p-value-for-smith" id="toc-calculating-t-statistic-and-p-value-for-smith" class="nav-link" data-scroll-target="#calculating-t-statistic-and-p-value-for-smith">Calculating t-statistic and p-value for Smith</a></li>
  <li><a href="#conclusion-6" id="toc-conclusion-6" class="nav-link" data-scroll-target="#conclusion-6">Conclusion</a></li>
  <li><a href="#question-5-b" id="toc-question-5-b" class="nav-link" data-scroll-target="#question-5-b">Question 5-B</a></li>
  <li><a href="#conclusion-7" id="toc-conclusion-7" class="nav-link" data-scroll-target="#conclusion-7">Conclusion</a></li>
  <li><a href="#question-5-c" id="toc-question-5-c" class="nav-link" data-scroll-target="#question-5-c">Question 5-C</a></li>
  <li><a href="#conclusion-8" id="toc-conclusion-8" class="nav-link" data-scroll-target="#conclusion-8">Conclusion</a></li>
  </ul></li>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6">Question 6</a>
  <ul class="collapse">
  <li><a href="#null-hypothesis" id="toc-null-hypothesis" class="nav-link" data-scroll-target="#null-hypothesis">Null Hypothesis</a></li>
  <li><a href="#which-test-should-we-use-chi-square" id="toc-which-test-should-we-use-chi-square" class="nav-link" data-scroll-target="#which-test-should-we-use-chi-square">Which test should we use? (Chi Square)?</a></li>
  <li><a href="#chi-square-test" id="toc-chi-square-test" class="nav-link" data-scroll-target="#chi-square-test">Chi-square Test</a></li>
  <li><a href="#conclusion-9" id="toc-conclusion-9" class="nav-link" data-scroll-target="#conclusion-9">Conclusion</a></li>
  </ul></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">Question 7</a>
  <ul class="collapse">
  <li><a href="#null-hypothesis-1" id="toc-null-hypothesis-1" class="nav-link" data-scroll-target="#null-hypothesis-1">Null Hypothesis</a></li>
  <li><a href="#which-test-should-we-use-anova" id="toc-which-test-should-we-use-anova" class="nav-link" data-scroll-target="#which-test-should-we-use-anova">Which test should we use? (Anova)</a></li>
  <li><a href="#anova-test" id="toc-anova-test" class="nav-link" data-scroll-target="#anova-test">Anova Test</a></li>
  <li><a href="#conclusion-10" id="toc-conclusion-10" class="nav-link" data-scroll-target="#conclusion-10">Conclusion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 2</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Homework2</div>
    <div class="quarto-category">Akhilesh</div>
  </div>
  </div>

<div>
  <div class="description">
    The second homework
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Akhilesh Kumar Meghwal </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 27, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<p>The time between the date a patient was recommended for heart surgery and the surgery date for cardiac patients in Ontario was collected by the Cardiac Care Network (“Wait Times Data Guide,” Ministry of Health and Long-Term Care, Ontario, Canada, 2006). The sample mean and sample standard deviation for wait times (in days) of patients for two cardiac procedures are given in the accompanying table. Assume that the sample is representative of the Ontario population</p>
<section id="data-table" class="level3">
<h3 class="anchored" data-anchor-id="data-table">Data table</h3>
<div class="cell-output-display">
<table class="table table-striped" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Surgical Procedure</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Sample Size</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean Wait Time</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Standard Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Bypass</td>
<td style="text-align: center;">539</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="even">
<td style="text-align: center;">Angiography</td>
<td style="text-align: center;">847</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">9</td>
</tr>
</tbody>
</table>


</div>
<p>Construct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?</p>
</section>
<section id="confidence-interval-calculation-for-bypass-and-angiography" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval-calculation-for-bypass-and-angiography">Confidence Interval Calculation for Bypass and Angiography</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 90% confidence interval</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>confidence_level <span class="ot">&lt;-</span> <span class="fl">0.90</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Tail area</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>tail_area <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">-</span>confidence_level)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># t_score Calculation</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>t_score <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="dv">1</span><span class="sc">-</span>tail_area, <span class="at">df =</span> sample_size<span class="dv">-1</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard Error Calculation</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>standard_error <span class="ot">&lt;-</span> standard_deviation<span class="sc">/</span><span class="fu">sqrt</span>(sample_size)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Confidence Interval Calculation for Bypass and Angiography</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>confidence_interval <span class="ot">&lt;-</span> <span class="fu">c</span>(mean_wait_time <span class="sc">-</span> t_score <span class="sc">*</span> standard_error,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        mean_wait_time <span class="sc">+</span> t_score <span class="sc">*</span> standard_error)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>confidence_interval</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.29029 17.49078 19.70971 18.50922</code></pre>
</div>
</div>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>The Cardiac Care Network collected data on the time between the date a patient was recommended for heart surgery and the surgery date for cardiac patients in Ontario. The sample mean and standard deviation of wait times (in days) for two cardiac procedures, bypass and angiography, were reported in a table.</p>
<p>To estimate the actual mean wait time for each of the two procedures, a 90% confidence interval was constructed using the t-distribution. The confidence interval for bypass surgery is between 18.29 and 19.71 days, while the confidence interval for angiography is between 17.49 and 18.51 days.</p>
<p>These results suggest that, with 90% confidence, the true mean wait time for bypass surgery is likely to fall between 18.29 and 19.71 days, and the true mean wait time for angiography is likely to fall between 17.49 and 18.51 days. Comparing the two confidence intervals, we can see that the interval for bypass surgery is slightly wider than the interval for angiography. This indicates that there is slightly more uncertainty in the estimate of the true mean wait time for bypass surgery than for angiography.</p>
<p>Overall, the confidence intervals provide important information about the precision of the sample means as estimates of the true population means. The intervals convey the range of values within which the population mean is likely to fall with a certain level of confidence, and they can help healthcare providers and policymakers make informed decisions about resource allocation and patient care.</p>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>A survey of 1031 adult Americans was carried out by the National Center for Public Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 believed that college education is essential for success. Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success. Construct and interpret a 95% confidence interval for p.</p>
<section id="sample-proportions-test" class="level3">
<h3 class="anchored" data-anchor-id="sample-proportions-test">1-sample proportions test</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">567</span>, <span class="dv">1031</span>, <span class="at">conf.level =</span> .<span class="dv">95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  567 out of 1031, null probability 0.5
X-squared = 10.091, df = 1, p-value = 0.00149
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.5189682 0.5805580
sample estimates:
        p 
0.5499515 </code></pre>
</div>
</div>
</section>
<section id="conclusion-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-1">Conclusion</h3>
<p>The National Center for Public Policy conducted a survey of 1031 adult Americans to determine the proportion of people who believe that a college education is essential for success. Among the 1031 adults surveyed, 567 believed that a college education is essential for success.</p>
<p>Using the prop.test() function in R with a 95% confidence level, the point estimate of the proportion of all adult Americans who believe that a college education is essential for success is 0.5499515, suggesting that 54.99% of adult Americans believe that a college education is essential for success. We can use this proportion as a point estimate of the true proportion of adult Americans who hold this belief.Additionally, the confidence interval at a 95% confidence level for this proportion is [0.5189682, 0.5805580].</p>
<p>The interpretation of this confidence interval is that if we were to repeat this survey many times and construct a confidence interval for each survey, approximately 95% of these intervals would contain the true population proportion. Therefore, we can conclude that with 95% confidence, the proportion of all adult Americans who believe that a college education is essential for success is somewhere between 0.5189682 and 0.5805580 and that a majority of adult Americans believe that a college education is essential for success, as the lower bound of the interval is above 0.5.</p>
<p>Since the confidence interval does not include 0.5 (the null probability), we can conclude that the proportion of all adult Americans who believe that a college education is essential for success is significantly different from 0.5 at the 0.05 significance level.</p>
</section>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<p>Suppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within $5 of the true population mean (i.e.&nbsp;they want the confidence interval to have a length of $10 or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between $30 and $200. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation). Assuming the significance level to be 5%, what should be the size of the sample</p>
<section id="sample-size-calculation" class="level3">
<h3 class="anchored" data-anchor-id="sample-size-calculation">Sample Size Calculation</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define variables</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>M_Error <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>standard_deviation <span class="ot">&lt;-</span> (<span class="dv">200-30</span>)<span class="sc">/</span><span class="dv">4</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>z_alpha <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="at">p =</span> <span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate required sample size</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(((z_alpha <span class="sc">*</span> standard_deviation) <span class="sc">/</span> M_Error)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Required Sample Size, Round up to nearest integer</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The required sample size is:"</span>, sample_size)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The required sample size is: 278</code></pre>
</div>
</div>
</section>
<section id="conclusion-2" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-2">Conclusion</h3>
<p>The financial aid office of UMass Amherst wants to estimate the mean cost of textbooks per semester for their students. They want the estimate to be accurate within $5 of the true population mean, and the confidence interval should have a length of $10 or less. The office has some prior knowledge that the amount spent on textbooks varies widely, with most values between $30 and $200, and they assume that the population standard deviation is about a quarter of this range.</p>
<p>To determine the sample size needed for their estimation, they use a formula that takes into account the margin of error, confidence level, and estimated population standard deviation. The calculated sample size is 278, meaning that they would need to survey 278 students to estimate the mean cost of textbooks per semester within $5 with a 95% confidence interval.</p>
<p>This estimation is important for the financial aid office to determine the appropriate amount of financial assistance to provide to students for textbooks. If the estimate is inaccurate or the confidence interval is too wide, they risk providing inadequate or excessive support, which can affect the academic success and financial well-being of the students. Therefore, it is crucial for the financial aid office to carefully plan and conduct their survey to obtain reliable and useful estimates.</p>
</section>
</section>
<section id="question-4" class="level2">
<h2 class="anchored" data-anchor-id="question-4">Question 4</h2>
<p>According to a union agreement, the mean income for all senior-level workers in a large service company equals $500 per week. A representative of a women’s group decides to analyze whether the mean income μ for female employees matches this norm. For a random sample of nine female employees, ȳ = $410 and s = 90</p>
<p>A. Test whether the mean income of female employees differs from $500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result. B. Report the P-value for Ha: μ &lt; 500. Interpret. C. Report and interpret the P-value for Ha: μ &gt; 500. (Hint: The P-values for the two possible one-sided tests must sum to 1.</p>
<section id="question-4-a" class="level3">
<h3 class="anchored" data-anchor-id="question-4-a">Question 4-A</h3>
<p>Two assumptions for the analysis:</p>
<ol type="1">
<li>Sample is randomly selected, and</li>
<li>Population follows a normal distribution.</li>
</ol>
<p>The null hypothesis is that the mean income of female employees is equal to $500 per week, represented as H0: μ = 500.</p>
<p>The alternative hypothesis is that the mean income of female employees differs from $500 per week, represented as Ha: μ ≠ 500.</p>
<p>We will reject the null hypothesis if the p-value is less than or equal to 0.05, indicating that the observed sample mean of $410 is significantly different from the population mean of $500.</p>
</section>
<section id="test-statistic-and-p-value-calculation" class="level3">
<h3 class="anchored" data-anchor-id="test-statistic-and-p-value-calculation">Test Statistic and p value calculation</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="ot">&lt;-</span> <span class="dv">410</span> <span class="co"># sample mean</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">500</span> <span class="co"># population mean</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>standard_deviation <span class="ot">&lt;-</span> <span class="dv">90</span> <span class="co"># standard deviation</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">9</span> <span class="co"># sample size</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating test-statistic</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>t_score <span class="ot">&lt;-</span> (sample_mean<span class="sc">-</span>mu)<span class="sc">/</span>(standard_deviation<span class="sc">/</span><span class="fu">sqrt</span>(sample_size))</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"test-statistic:"</span>, t_score, <span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>test-statistic: -3 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>p_val <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(t_score, <span class="at">df =</span> sample_size <span class="sc">-</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"p value :"</span>, p_val)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>p value : 0.01707168</code></pre>
</div>
</div>
</section>
<section id="conclusion-3" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-3">Conclusion</h3>
<p>In this analysis, we are investigating whether the mean income of female employees in a large service company differs from the norm of $500 per week, according to a union agreement. We have a sample of nine randomly selected female employees, with a sample mean of $410 and a sample standard deviation of $90.</p>
<p>Based on our assumptions of random sampling and normal population distribution, we conduct a hypothesis test with a significance level of 0.05. Our null hypothesis is that the population mean of female employee income is equal to $500 per week, while our alternative hypothesis is that the mean income differs from $500 per week.</p>
<p>Our test results in a test-statistic of -3 and a p-value of 0.01707168, which is less than the significance level of 0.05. Therefore, we reject the null hypothesis and conclude that the mean income of female employees in this service company is significantly different from $500 per week.</p>
</section>
<section id="question-4-b" class="level3">
<h3 class="anchored" data-anchor-id="question-4-b">Question 4-B</h3>
<p>Two assumptions for the analysis:</p>
<ol type="1">
<li>Sample is randomly selected, and</li>
<li>Population follows a normal distribution.</li>
</ol>
<p>The null hypothesis is that the mean income of female employees is equal to $500 per week, represented as H0: mu = 500.</p>
<p>The alternative hypothesis is that the mean income of female employees is less than $500 per week, represented as Ha: mu &lt; 500.</p>
<p>We will reject the null hypothesis if the p-value is less than 0.05, indicating that the observed sample mean of $410 is significantly lower than the population mean of $500.</p>
</section>
<section id="p-value-calculation" class="level3">
<h3 class="anchored" data-anchor-id="p-value-calculation">p-value calculation</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pt</span>(t_score, sample_size<span class="dv">-1</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.008535841</code></pre>
</div>
</div>
</section>
<section id="conclusion-4" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-4">Conclusion</h3>
<p>Performed one-tailed t-test to test the hypothesis. The p-value associated with this test statistic is 0.008535841.</p>
<p>Since the p-value is less than the significance level of 0.05, we reject the null hypothesis and conclude that there is sufficient evidence to support the claim that the mean income of female employees is lower than $500 per week. This implies that female employees in this service company are paid less than the senior-level workers as per the union agreement.</p>
</section>
<section id="question-4-c" class="level3">
<h3 class="anchored" data-anchor-id="question-4-c">Question 4-C</h3>
<p>Two assumptions for the analysis:</p>
<ol type="1">
<li>Sample is randomly selected, and</li>
<li>Population follows a normal distribution.</li>
</ol>
<p>The null hypothesis is that the mean income of female employees is equal to $500 per week, represented as H0: mu = 500.</p>
<p>The alternative hypothesis is that the mean income of female employees is greater than $500 per week, represented as Ha: mu &gt; 500.</p>
<p>We will reject the null hypothesis if the p-value is less than 0.05, indicating that the observed sample mean of $410 is significantly higher than the population mean of $500.</p>
</section>
<section id="p-value-calculation-1" class="level3">
<h3 class="anchored" data-anchor-id="p-value-calculation-1">p-value calculation</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pt</span>(t_score, sample_size<span class="dv">-1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9914642</code></pre>
</div>
</div>
</section>
<section id="conclusion-5" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-5">Conclusion</h3>
<p>The p-value is 0.9914642, which is greater than the significance level of 0.05. Therefore, we fail to reject the null hypothesis and conclude that there is insufficient evidence to support the claim that the mean income of female employees is greater than $500 per week. In other words, we cannot conclude that female employees earn significantly more than the agreed-upon mean income for all senior-level workers in the company.</p>
</section>
</section>
<section id="question-5" class="level2">
<h2 class="anchored" data-anchor-id="question-5">Question 5</h2>
<p>Jones and Smith separately conduct studies to test H0: μ = 500 against Ha: μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7, with se = 10.0.</p>
<p>A. Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith. B. Using α = 0.05, for each study indicate whether the result is “statistically significant.” C. Using this example, explain the misleading aspects of reporting the result of a test as “P ≤ 0.05” versus “P &gt; 0.05,” or as “reject H0” versus “Do not reject H0,” without reporting the actual P-value.</p>
<section id="question-5-a" class="level3">
<h3 class="anchored" data-anchor-id="question-5-a">Question 5-A</h3>
<p>Two assumptions for the analysis:</p>
<ol type="1">
<li>Sample is randomly selected, and</li>
<li>Population follows a normal distribution.</li>
</ol>
<p>The null hypothesis for both studies is that the population mean is equal to 500, represented as H0: μ = 500.</p>
<p>The alternative hypothesis for both studies is that the population mean is not equal to 500, represented as Ha: μ ≠ 500.</p>
<p>We will reject the null hypothesis at a p-value less than 0.05</p>
</section>
<section id="calculating-t-statistic-and-p-value-for-jones" class="level3">
<h3 class="anchored" data-anchor-id="calculating-t-statistic-and-p-value-for-jones">Calculating t-statistic and p-value for Jones</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="ot">&lt;-</span> <span class="fl">519.5</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>standard_error <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>t_score_jones <span class="ot">&lt;-</span> (sample_mean<span class="sc">-</span>mu)<span class="sc">/</span>(standard_error)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>t_score_jones</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.95</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(t_score_jones, sample_size<span class="dv">-1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05145555</code></pre>
</div>
</div>
</section>
<section id="calculating-t-statistic-and-p-value-for-smith" class="level3">
<h3 class="anchored" data-anchor-id="calculating-t-statistic-and-p-value-for-smith">Calculating t-statistic and p-value for Smith</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="ot">&lt;-</span> <span class="fl">519.7</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>standard_error <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>t_score_smith <span class="ot">&lt;-</span> (sample_mean<span class="sc">-</span>mu)<span class="sc">/</span>(standard_error)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>t_score_smith</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.97</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(t_score_smith, sample_size<span class="dv">-1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04911426</code></pre>
</div>
</div>
</section>
<section id="conclusion-6" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-6">Conclusion</h3>
<p>Jones has a test-statistic of 1.95 and a p-value of 0.05145555, while Smith has a test-statistic of 1.97 and a p-value of 0.05145555.</p>
</section>
<section id="question-5-b" class="level3">
<h3 class="anchored" data-anchor-id="question-5-b">Question 5-B</h3>
</section>
<section id="conclusion-7" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-7">Conclusion</h3>
<p>Based on the given information, the result is statistically significant for Smith, but not for Jones.</p>
<p>For Jones, the p-value (0.05145555) is greater than the significance level (α = 0.05), which means that we fail to reject the null hypothesis. This indicates that the result is not statistically significant for Jones.</p>
<p>For Smith, the p-value (0.04911426) is less than the significance level (α = 0.05), which means that we reject the null hypothesis. This indicates that the result is statistically significant for Smith.</p>
</section>
<section id="question-5-c" class="level3">
<h3 class="anchored" data-anchor-id="question-5-c">Question 5-C</h3>
</section>
<section id="conclusion-8" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-8">Conclusion</h3>
<p>The misleading aspect of reporting the result of a test as “P ≤ 0.05” versus “P &gt; 0.05” or as “reject H0” versus “do not reject H0” without reporting the actual P-value is that it can mask the degree of uncertainty in the results. In this example, if we only reported “P ≤ 0.05” for Smith’s study, we would conclude that the result is statistically significant. However, we would miss the fact that the P-value is very close to the significance level, indicating that the result may not be very strong or may be subject to random chance. Similarly, if we only reported “P &gt; 0.05” for Jones’s study, we would conclude that the result is not statistically significant, but we would miss the fact that the P-value is very close to the significance level, indicating that the result may be borderline significant. Therefore, it is important to report the actual P-value to provide a more accurate interpretation of the results.</p>
<p>If we fail to report the P-value and simply state whether the P-value is less than/equal to or greater than the defined significance level of the test, one cannot determine the strength of the conclusion. In the Jones/Smith example, reporting the results only as <em>P ≤ 0.05</em> versus <em>P &gt; 0.05</em> will lead to different conclusions about very similar results.</p>
</section>
</section>
<section id="question-6" class="level2">
<h2 class="anchored" data-anchor-id="question-6">Question 6</h2>
<p>A school nurse wants to determine whether age is a factor in whether children choose a healthy snack after school. She conducts a survey of 300 middle school students, with the results below. Test at α = 0.05 the claim that the proportion who choose a healthy snack differs by grade level. What is the null hypothesis? Which test should we use? What is the conclusion?</p>
<section id="null-hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="null-hypothesis">Null Hypothesis</h3>
<p>The null hypothesis is that there is no association between grade level and the proportion of students who choose a healthy snack.</p>
<p>The alternative hypothesis is that there is an association between grade level and the proportion of students who choose a healthy snack.</p>
</section>
<section id="which-test-should-we-use-chi-square" class="level3">
<h3 class="anchored" data-anchor-id="which-test-should-we-use-chi-square">Which test should we use? (Chi Square)?</h3>
<p>In the case of the school nurse’s survey data on snack choices, a chi-square test of independence should be used because the data is categorical (healthy snack vs unhealthy snack) and the research question is about whether there is a relationship between snack choice and grade level. The chi-square test is used to determine whether there is a significant association between two categorical variables.</p>
</section>
<section id="chi-square-test" class="level3">
<h3 class="anchored" data-anchor-id="chi-square-test">Chi-square Test</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the contingency table</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>snack_table <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">31</span>, <span class="dv">43</span>, <span class="dv">51</span>, <span class="dv">69</span>, <span class="dv">57</span>, <span class="dv">49</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(snack_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Healthy snack"</span>, <span class="st">"Unhealthy snack"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(snack_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"6th grade"</span>, <span class="st">"7th grade"</span>, <span class="st">"8th grade"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>snack_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                6th grade 7th grade 8th grade
Healthy snack          31        43        51
Unhealthy snack        69        57        49</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct the chi-square test of independence</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(snack_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  snack_table
X-squared = 8.3383, df = 2, p-value = 0.01547</code></pre>
</div>
</div>
</section>
<section id="conclusion-9" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-9">Conclusion</h3>
<p>Since the p-value is less than the significance level of 0.05,</p>
<p>The output of the chisq.test function indicates that the chi-square test statistic is 8.3383 with 2 degrees of freedom, and the corresponding p-value is 0.01547. So we can reject the null hypothesis that there is no association between snack choice and grade level, and conclude that there is evidence of a significant association between two categorical variables: snack choice and grade level at a significance level of 0.05.</p>
<p>Based on the results of the chi-square test of independence, it is found that there is a statistically significant association between snack choice and grade level among the surveyed students. Specifically, the data indicates that the proportion of students who choose healthy snacks differs significantly across grade levels. The contingency table and chi-square test showed that more 6th-grade students (31) chose healthy snacks compared to 7th-grade students (43) and 8th-grade students (51). On the other hand, more 8th-grade students (49) chose unhealthy snacks compared to 6th-grade students (69) and 7th-grade students (57).</p>
<p>Therefore, we can conclude that grade level is a factor in whether children choose a healthy snack after school. The proportion of students who choose a healthy snack appears to differ across the three grade levels. Overall, these results suggest that the school may need to target their health promotion efforts towards the specific grade levels where unhealthy snack choices are more prevalent. The results may also inform further research into the factors that influence snack choices among middle school students.</p>
</section>
</section>
<section id="question-7" class="level2">
<h2 class="anchored" data-anchor-id="question-7">Question 7</h2>
<p>Per-pupil costs (in thousands of dollars) for cyber charter school tuition for school districts in three areas are shown. Test the claim that there is a difference in means for the three areas, using an appropriate test. What is the null hypothesis? Which test should we use? What is the conclusion?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the data</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Area =</span> <span class="fu">c</span>(<span class="st">"Area 1"</span>, <span class="st">"Area 2"</span>, <span class="st">"Area 3"</span>),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value1 =</span> <span class="fu">c</span>(<span class="fl">6.2</span>, <span class="fl">7.5</span>, <span class="fl">5.8</span>),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value2 =</span> <span class="fu">c</span>(<span class="fl">9.3</span>, <span class="fl">8.2</span>, <span class="fl">6.4</span>),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value3 =</span> <span class="fu">c</span>(<span class="fl">6.8</span>, <span class="fl">8.5</span>, <span class="fl">5.6</span>),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value4 =</span> <span class="fu">c</span>(<span class="fl">6.1</span>, <span class="fl">8.2</span>, <span class="fl">7.1</span>),</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value5 =</span> <span class="fu">c</span>(<span class="fl">6.7</span>, <span class="fl">7.0</span>, <span class="fl">3.0</span>),</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value6 =</span> <span class="fu">c</span>(<span class="fl">7.5</span>, <span class="fl">9.3</span>, <span class="fl">3.5</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>data1<span class="ot">=</span>data</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co"># # Alternatively, you can set the row names separately</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data1) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="co"># # Display table without boundaries/borders</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(data1, <span class="at">row.names =</span> <span class="cn">FALSE</span>, <span class="at">col.names =</span> <span class="cn">NULL</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">border =</span> <span class="cn">NA</span>, <span class="at">digits =</span> <span class="dv">1</span>)<span class="sc">%&gt;%</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="at">full_width =</span> <span class="cn">TRUE</span>, <span class="at">position =</span> <span class="st">'center'</span>, <span class="at">font_size =</span> <span class="dv">14</span>, <span class="at">stripe_color=</span><span class="st">'black'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td style="text-align: left;">Area 1</td>
<td style="text-align: right;">6.2</td>
<td style="text-align: right;">9.3</td>
<td style="text-align: right;">6.8</td>
<td style="text-align: right;">6.1</td>
<td style="text-align: right;">6.7</td>
<td style="text-align: right;">7.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Area 2</td>
<td style="text-align: right;">7.5</td>
<td style="text-align: right;">8.2</td>
<td style="text-align: right;">8.5</td>
<td style="text-align: right;">8.2</td>
<td style="text-align: right;">7.0</td>
<td style="text-align: right;">9.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Area 3</td>
<td style="text-align: right;">5.8</td>
<td style="text-align: right;">6.4</td>
<td style="text-align: right;">5.6</td>
<td style="text-align: right;">7.1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.5</td>
</tr>
</tbody>
</table>


</div>
</div>
<section id="null-hypothesis-1" class="level3">
<h3 class="anchored" data-anchor-id="null-hypothesis-1">Null Hypothesis</h3>
<p>In order to investigate if there is a difference in means for the per-pupil costs of cyber charter school tuition in three different areas, we can use Analysis of Variance (ANOVA) test. ANOVA is a statistical test that compares means of three or more groups.</p>
<p>Null Hypothesis: The null hypothesis for the ANOVA test would state that there is no significant difference between the means of the per-pupil costs for cyber charter school tuition in the three areas. This can be expressed mathematically as H0: μ1 = μ2 = μ3, where μ1, μ2, and μ3 represent the means of the per-pupil costs for cyber charter school tuition in Area 1, Area 2, and Area 3, respectively.</p>
<p>Alternative Hypothesis: On the other hand, the alternative hypothesis (H1) suggests that at least one mean is significantly different from the others.</p>
</section>
<section id="which-test-should-we-use-anova" class="level3">
<h3 class="anchored" data-anchor-id="which-test-should-we-use-anova">Which test should we use? (Anova)</h3>
<p>To test the claim that there is a difference in means for the three areas, we can use the analysis of variance (ANOVA) test.</p>
<p>In this case, since we are comparing means across three areas, we can use a one-way ANOVA. We will use the following R code to conduct the test:</p>
<p>To conduct the ANOVA test in R, we can use the aov function.</p>
</section>
<section id="anova-test" class="level3">
<h3 class="anchored" data-anchor-id="anova-test">Anova Test</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the data to long format</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>data_long <span class="ot">&lt;-</span> <span class="fu">gather</span>(data, <span class="at">key =</span> <span class="st">"Variable"</span>, <span class="at">value =</span> <span class="st">"Value"</span>, <span class="sc">-</span>Area)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct ANOVA test</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">aov</span>(Value <span class="sc">~</span> Area, <span class="at">data =</span> data_long)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the ANOVA table</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)   
Area         2  25.66  12.832   8.176 0.00397 **
Residuals   15  23.54   1.569                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="conclusion-10" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-10">Conclusion</h3>
<p>The ANOVA table shows that the F value is 8.176 and the p-value is 0.00397. Since the p-value is less than the significance level of 0.05, we reject the null hypothesis and conclude that there is evidence of a difference in means for the three areas.</p>
<p>Therefore, we can infer that the per-pupil costs for cyber charter school tuition differ among the three areas. Specifically, we found that the mean per-pupil costs for cyber charter school tuition in Area 1 (mean = 7.1) and Area 2 (mean = 8.1) were higher than the mean per-pupil costs in Area 3 (mean = 5.23). The ANOVA test supports the conclusion that there is a significant difference between the means of the per-pupil costs for cyber charter school tuition in the three areas.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb30" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 2"</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Akhilesh Kumar Meghwal"</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "The second homework"</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "02/27/2023"</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - Homework2</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - Akhilesh</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE, warnings=FALSE}</span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 1</span></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>The time between the date a patient was recommended for heart surgery and the surgery date </span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a>for cardiac patients in Ontario was collected by the Cardiac Care Network (“Wait Times Data </span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a>Guide,” Ministry of Health and Long-Term Care, Ontario, Canada, 2006). The sample mean </span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a>and sample standard deviation for wait times (in days) of patients for two cardiac procedures </span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>are given in the accompanying table. Assume that the sample is representative of the Ontario </span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a>population</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a><span class="fu">### Data table</span></span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='asis', echo=FALSE, fig.show='hold', out.width='100%', out.height='10%'}</span></span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the data frame</span></span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a>surgical_procedure <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Bypass"</span>, <span class="st">"Angiography"</span>)</span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">539</span>, <span class="dv">847</span>)</span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a>mean_wait_time <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">18</span>)</span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a>standard_deviation <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">9</span>)</span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a>surgery <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(surgical_procedure, sample_size, mean_wait_time, standard_deviation)</span>
<span id="cb30-50"><a href="#cb30-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the table with kable</span></span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-53"><a href="#cb30-53" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(surgery, <span class="at">align =</span> <span class="st">"c"</span>, <span class="at">booktabs =</span> <span class="cn">TRUE</span>, </span>
<span id="cb30-54"><a href="#cb30-54" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Surgical Procedure"</span>, <span class="st">"Sample Size"</span>, <span class="st">"Mean Wait Time"</span>, <span class="st">"Standard Deviation"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb30-55"><a href="#cb30-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">'center'</span>, <span class="at">font_size =</span> <span class="dv">14</span>, <span class="at">stripe_color=</span><span class="st">'black'</span>)</span>
<span id="cb30-56"><a href="#cb30-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-57"><a href="#cb30-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-58"><a href="#cb30-58" aria-hidden="true" tabindex="-1"></a>Construct the 90% confidence interval to estimate the actual mean wait time for each of the two </span>
<span id="cb30-59"><a href="#cb30-59" aria-hidden="true" tabindex="-1"></a>procedures. Is the confidence interval narrower for angiography or bypass surgery?</span>
<span id="cb30-60"><a href="#cb30-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-61"><a href="#cb30-61" aria-hidden="true" tabindex="-1"></a><span class="fu">### Confidence Interval Calculation for Bypass and Angiography</span></span>
<span id="cb30-62"><a href="#cb30-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-65"><a href="#cb30-65" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-66"><a href="#cb30-66" aria-hidden="true" tabindex="-1"></a><span class="co"># 90% confidence interval</span></span>
<span id="cb30-67"><a href="#cb30-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-68"><a href="#cb30-68" aria-hidden="true" tabindex="-1"></a>confidence_level <span class="ot">&lt;-</span> <span class="fl">0.90</span></span>
<span id="cb30-69"><a href="#cb30-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-70"><a href="#cb30-70" aria-hidden="true" tabindex="-1"></a><span class="co"># Tail area</span></span>
<span id="cb30-71"><a href="#cb30-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-72"><a href="#cb30-72" aria-hidden="true" tabindex="-1"></a>tail_area <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">-</span>confidence_level)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb30-73"><a href="#cb30-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-74"><a href="#cb30-74" aria-hidden="true" tabindex="-1"></a><span class="co"># t_score Calculation</span></span>
<span id="cb30-75"><a href="#cb30-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-76"><a href="#cb30-76" aria-hidden="true" tabindex="-1"></a>t_score <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="dv">1</span><span class="sc">-</span>tail_area, <span class="at">df =</span> sample_size<span class="dv">-1</span>)</span>
<span id="cb30-77"><a href="#cb30-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-78"><a href="#cb30-78" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard Error Calculation</span></span>
<span id="cb30-79"><a href="#cb30-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-80"><a href="#cb30-80" aria-hidden="true" tabindex="-1"></a>standard_error <span class="ot">&lt;-</span> standard_deviation<span class="sc">/</span><span class="fu">sqrt</span>(sample_size)</span>
<span id="cb30-81"><a href="#cb30-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-82"><a href="#cb30-82" aria-hidden="true" tabindex="-1"></a><span class="co"># Confidence Interval Calculation for Bypass and Angiography</span></span>
<span id="cb30-83"><a href="#cb30-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-84"><a href="#cb30-84" aria-hidden="true" tabindex="-1"></a>confidence_interval <span class="ot">&lt;-</span> <span class="fu">c</span>(mean_wait_time <span class="sc">-</span> t_score <span class="sc">*</span> standard_error,</span>
<span id="cb30-85"><a href="#cb30-85" aria-hidden="true" tabindex="-1"></a>        mean_wait_time <span class="sc">+</span> t_score <span class="sc">*</span> standard_error)</span>
<span id="cb30-86"><a href="#cb30-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-87"><a href="#cb30-87" aria-hidden="true" tabindex="-1"></a>confidence_interval</span>
<span id="cb30-88"><a href="#cb30-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-89"><a href="#cb30-89" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-90"><a href="#cb30-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-91"><a href="#cb30-91" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion </span></span>
<span id="cb30-92"><a href="#cb30-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-93"><a href="#cb30-93" aria-hidden="true" tabindex="-1"></a>The Cardiac Care Network collected data on the time between the date a patient was recommended for heart surgery and the surgery date for cardiac patients in Ontario. The sample mean and standard deviation of wait times (in days) for two cardiac procedures, bypass and angiography, were reported in a table.</span>
<span id="cb30-94"><a href="#cb30-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-95"><a href="#cb30-95" aria-hidden="true" tabindex="-1"></a>To estimate the actual mean wait time for each of the two procedures, a 90% confidence interval was constructed using the t-distribution. The confidence interval for bypass surgery is between 18.29 and 19.71 days, while the confidence interval for angiography is between 17.49 and 18.51 days.</span>
<span id="cb30-96"><a href="#cb30-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-97"><a href="#cb30-97" aria-hidden="true" tabindex="-1"></a>These results suggest that, with 90% confidence, the true mean wait time for bypass surgery is likely to fall between 18.29 and 19.71 days, and the true mean wait time for angiography is likely to fall between 17.49 and 18.51 days. Comparing the two confidence intervals, we can see that the interval for bypass surgery is slightly wider than the interval for angiography. This indicates that there is slightly more uncertainty in the estimate of the true mean wait time for bypass surgery than for angiography.</span>
<span id="cb30-98"><a href="#cb30-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-99"><a href="#cb30-99" aria-hidden="true" tabindex="-1"></a>Overall, the confidence intervals provide important information about the precision of the sample means as estimates of the true population means. The intervals convey the range of values within which the population mean is likely to fall with a certain level of confidence, and they can help healthcare providers and policymakers make informed decisions about resource allocation and patient care.</span>
<span id="cb30-100"><a href="#cb30-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-101"><a href="#cb30-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-102"><a href="#cb30-102" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 2</span></span>
<span id="cb30-103"><a href="#cb30-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-104"><a href="#cb30-104" aria-hidden="true" tabindex="-1"></a>A survey of 1031 adult Americans was carried out by the National Center for Public </span>
<span id="cb30-105"><a href="#cb30-105" aria-hidden="true" tabindex="-1"></a>Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 </span>
<span id="cb30-106"><a href="#cb30-106" aria-hidden="true" tabindex="-1"></a>believed that college education is essential for success. Find the point estimate, p, of the </span>
<span id="cb30-107"><a href="#cb30-107" aria-hidden="true" tabindex="-1"></a>proportion of all adult Americans who believe that a college education is essential for success. </span>
<span id="cb30-108"><a href="#cb30-108" aria-hidden="true" tabindex="-1"></a>Construct and interpret a 95% confidence interval for p.</span>
<span id="cb30-109"><a href="#cb30-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-110"><a href="#cb30-110" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1-sample proportions test</span></span>
<span id="cb30-111"><a href="#cb30-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-114"><a href="#cb30-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-115"><a href="#cb30-115" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">567</span>, <span class="dv">1031</span>, <span class="at">conf.level =</span> .<span class="dv">95</span>)</span>
<span id="cb30-116"><a href="#cb30-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-117"><a href="#cb30-117" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-118"><a href="#cb30-118" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion </span></span>
<span id="cb30-119"><a href="#cb30-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-120"><a href="#cb30-120" aria-hidden="true" tabindex="-1"></a>The National Center for Public Policy conducted a survey of 1031 adult Americans to determine the proportion of people who believe that a college education is essential for success. Among the 1031 adults surveyed, 567 believed that a college education is essential for success.</span>
<span id="cb30-121"><a href="#cb30-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-122"><a href="#cb30-122" aria-hidden="true" tabindex="-1"></a>Using the prop.test() function in R with a 95% confidence level, the point estimate of the proportion of all adult Americans who believe that a college education is essential for success is 0.5499515, suggesting that 54.99% of adult Americans believe that a college education is essential for success. We can use this proportion as a point estimate of the true proportion of adult Americans who hold this belief.Additionally, the confidence interval at a 95% confidence level for this proportion is <span class="co">[</span><span class="ot">0.5189682, 0.5805580</span><span class="co">]</span>.</span>
<span id="cb30-123"><a href="#cb30-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-124"><a href="#cb30-124" aria-hidden="true" tabindex="-1"></a>The interpretation of this confidence interval is that if we were to repeat this survey many times and construct a confidence interval for each survey, approximately 95% of these intervals would contain the true population proportion. Therefore, we can conclude that with 95% confidence, the proportion of all adult Americans who believe that a college education is essential for success is somewhere between 0.5189682 and 0.5805580 and that a majority of adult Americans believe that a college education is essential for success, as the lower bound of the interval is above 0.5.</span>
<span id="cb30-125"><a href="#cb30-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-126"><a href="#cb30-126" aria-hidden="true" tabindex="-1"></a>Since the confidence interval does not include 0.5 (the null probability), we can conclude that the proportion of all adult Americans who believe that a college education is essential for success is significantly different from 0.5 at the 0.05 significance level.</span>
<span id="cb30-127"><a href="#cb30-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-128"><a href="#cb30-128" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 3</span></span>
<span id="cb30-129"><a href="#cb30-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-130"><a href="#cb30-130" aria-hidden="true" tabindex="-1"></a>Suppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within $5 of the true population mean (i.e. they want the confidence interval to have a length of $10 or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between $30 and $200. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation). Assuming the significance level to be 5%, what should be the size of the sample</span>
<span id="cb30-131"><a href="#cb30-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-132"><a href="#cb30-132" aria-hidden="true" tabindex="-1"></a><span class="fu">### Sample Size Calculation</span></span>
<span id="cb30-133"><a href="#cb30-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-136"><a href="#cb30-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-137"><a href="#cb30-137" aria-hidden="true" tabindex="-1"></a><span class="co"># Define variables</span></span>
<span id="cb30-138"><a href="#cb30-138" aria-hidden="true" tabindex="-1"></a>M_Error <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb30-139"><a href="#cb30-139" aria-hidden="true" tabindex="-1"></a>standard_deviation <span class="ot">&lt;-</span> (<span class="dv">200-30</span>)<span class="sc">/</span><span class="dv">4</span></span>
<span id="cb30-140"><a href="#cb30-140" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb30-141"><a href="#cb30-141" aria-hidden="true" tabindex="-1"></a>z_alpha <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="at">p =</span> <span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-142"><a href="#cb30-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-143"><a href="#cb30-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-144"><a href="#cb30-144" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate required sample size</span></span>
<span id="cb30-145"><a href="#cb30-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-146"><a href="#cb30-146" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(((z_alpha <span class="sc">*</span> standard_deviation) <span class="sc">/</span> M_Error)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb30-147"><a href="#cb30-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-148"><a href="#cb30-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-149"><a href="#cb30-149" aria-hidden="true" tabindex="-1"></a><span class="co"># Required Sample Size, Round up to nearest integer</span></span>
<span id="cb30-150"><a href="#cb30-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-151"><a href="#cb30-151" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The required sample size is:"</span>, sample_size)</span>
<span id="cb30-152"><a href="#cb30-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-153"><a href="#cb30-153" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion </span></span>
<span id="cb30-154"><a href="#cb30-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-155"><a href="#cb30-155" aria-hidden="true" tabindex="-1"></a>The financial aid office of UMass Amherst wants to estimate the mean cost of textbooks per semester for their students. They want the estimate to be accurate within $5 of the true population mean, and the confidence interval should have a length of $10 or less. The office has some prior knowledge that the amount spent on textbooks varies widely, with most values between $30 and $200, and they assume that the population standard deviation is about a quarter of this range.</span>
<span id="cb30-156"><a href="#cb30-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-157"><a href="#cb30-157" aria-hidden="true" tabindex="-1"></a>To determine the sample size needed for their estimation, they use a formula that takes into account the margin of error, confidence level, and estimated population standard deviation. The calculated sample size is 278, meaning that they would need to survey 278 students to estimate the mean cost of textbooks per semester within $5 with a 95% confidence interval.</span>
<span id="cb30-158"><a href="#cb30-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-159"><a href="#cb30-159" aria-hidden="true" tabindex="-1"></a>This estimation is important for the financial aid office to determine the appropriate amount of financial assistance to provide to students for textbooks. If the estimate is inaccurate or the confidence interval is too wide, they risk providing inadequate or excessive support, which can affect the academic success and financial well-being of the students. Therefore, it is crucial for the financial aid office to carefully plan and conduct their survey to obtain reliable and useful estimates.</span>
<span id="cb30-160"><a href="#cb30-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-161"><a href="#cb30-161" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 4</span></span>
<span id="cb30-162"><a href="#cb30-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-163"><a href="#cb30-163" aria-hidden="true" tabindex="-1"></a>According to a union agreement, the mean income for all senior-level workers in a large </span>
<span id="cb30-164"><a href="#cb30-164" aria-hidden="true" tabindex="-1"></a>service company equals $500 per week. A representative of a women’s group decides to analyze </span>
<span id="cb30-165"><a href="#cb30-165" aria-hidden="true" tabindex="-1"></a>whether the mean income μ for female employees matches this norm. For a random sample of </span>
<span id="cb30-166"><a href="#cb30-166" aria-hidden="true" tabindex="-1"></a>nine female employees, ȳ = $410 and s = 90</span>
<span id="cb30-167"><a href="#cb30-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-168"><a href="#cb30-168" aria-hidden="true" tabindex="-1"></a>  A. Test whether the mean income of female employees differs from $500 per week. Include </span>
<span id="cb30-169"><a href="#cb30-169" aria-hidden="true" tabindex="-1"></a>    assumptions, hypotheses, test statistic, and P-value. Interpret the result.</span>
<span id="cb30-170"><a href="#cb30-170" aria-hidden="true" tabindex="-1"></a>  B. Report the P-value for Ha: μ &lt; 500. Interpret.</span>
<span id="cb30-171"><a href="#cb30-171" aria-hidden="true" tabindex="-1"></a>  C. Report and interpret the P-value for Ha: μ &gt; 500.</span>
<span id="cb30-172"><a href="#cb30-172" aria-hidden="true" tabindex="-1"></a>  (Hint: The P-values for the two possible one-sided tests must sum to 1.</span>
<span id="cb30-173"><a href="#cb30-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-174"><a href="#cb30-174" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 4-A</span></span>
<span id="cb30-175"><a href="#cb30-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-176"><a href="#cb30-176" aria-hidden="true" tabindex="-1"></a>Two assumptions for the analysis: </span>
<span id="cb30-177"><a href="#cb30-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-178"><a href="#cb30-178" aria-hidden="true" tabindex="-1"></a>(1) Sample is randomly selected, and </span>
<span id="cb30-179"><a href="#cb30-179" aria-hidden="true" tabindex="-1"></a>(2) Population follows a normal distribution.</span>
<span id="cb30-180"><a href="#cb30-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-181"><a href="#cb30-181" aria-hidden="true" tabindex="-1"></a>The null hypothesis is that the mean income of female employees is equal to $500 per week, represented as H0: μ = 500. </span>
<span id="cb30-182"><a href="#cb30-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-183"><a href="#cb30-183" aria-hidden="true" tabindex="-1"></a>The alternative hypothesis is that the mean income of female employees differs from $500 per week, represented as Ha: μ ≠ 500.</span>
<span id="cb30-184"><a href="#cb30-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-185"><a href="#cb30-185" aria-hidden="true" tabindex="-1"></a>We will reject the null hypothesis if the p-value is less than or equal to 0.05, indicating that the observed sample mean of $410 is significantly different from the population mean of $500.</span>
<span id="cb30-186"><a href="#cb30-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-187"><a href="#cb30-187" aria-hidden="true" tabindex="-1"></a><span class="fu">### Test Statistic and p value calculation</span></span>
<span id="cb30-188"><a href="#cb30-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-191"><a href="#cb30-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-192"><a href="#cb30-192" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="ot">&lt;-</span> <span class="dv">410</span> <span class="co"># sample mean</span></span>
<span id="cb30-193"><a href="#cb30-193" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">500</span> <span class="co"># population mean</span></span>
<span id="cb30-194"><a href="#cb30-194" aria-hidden="true" tabindex="-1"></a>standard_deviation <span class="ot">&lt;-</span> <span class="dv">90</span> <span class="co"># standard deviation</span></span>
<span id="cb30-195"><a href="#cb30-195" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">9</span> <span class="co"># sample size</span></span>
<span id="cb30-196"><a href="#cb30-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-197"><a href="#cb30-197" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating test-statistic</span></span>
<span id="cb30-198"><a href="#cb30-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-199"><a href="#cb30-199" aria-hidden="true" tabindex="-1"></a>t_score <span class="ot">&lt;-</span> (sample_mean<span class="sc">-</span>mu)<span class="sc">/</span>(standard_deviation<span class="sc">/</span><span class="fu">sqrt</span>(sample_size))</span>
<span id="cb30-200"><a href="#cb30-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-201"><a href="#cb30-201" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"test-statistic:"</span>, t_score, <span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span>
<span id="cb30-202"><a href="#cb30-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-203"><a href="#cb30-203" aria-hidden="true" tabindex="-1"></a>p_val <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(t_score, <span class="at">df =</span> sample_size <span class="sc">-</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-204"><a href="#cb30-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-205"><a href="#cb30-205" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"p value :"</span>, p_val)</span>
<span id="cb30-206"><a href="#cb30-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-207"><a href="#cb30-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-208"><a href="#cb30-208" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion  </span></span>
<span id="cb30-209"><a href="#cb30-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-210"><a href="#cb30-210" aria-hidden="true" tabindex="-1"></a>In this analysis, we are investigating whether the mean income of female employees in a large service company differs from the norm of $500 per week, according to a union agreement. We have a sample of nine randomly selected female employees, with a sample mean of $410 and a sample standard deviation of $90.</span>
<span id="cb30-211"><a href="#cb30-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-212"><a href="#cb30-212" aria-hidden="true" tabindex="-1"></a>Based on our assumptions of random sampling and normal population distribution, we conduct a hypothesis test with a significance level of 0.05. Our null hypothesis is that the population mean of female employee income is equal to $500 per week, while our alternative hypothesis is that the mean income differs from $500 per week.</span>
<span id="cb30-213"><a href="#cb30-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-214"><a href="#cb30-214" aria-hidden="true" tabindex="-1"></a>Our test results in a test-statistic of -3 and a p-value of 0.01707168, which is less than the significance level of 0.05. Therefore, we reject the null hypothesis and conclude that the mean income of female employees in this service company is significantly different from $500 per week.</span>
<span id="cb30-215"><a href="#cb30-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-216"><a href="#cb30-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-217"><a href="#cb30-217" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 4-B</span></span>
<span id="cb30-218"><a href="#cb30-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-219"><a href="#cb30-219" aria-hidden="true" tabindex="-1"></a>Two assumptions for the analysis: </span>
<span id="cb30-220"><a href="#cb30-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-221"><a href="#cb30-221" aria-hidden="true" tabindex="-1"></a>(1) Sample is randomly selected, and </span>
<span id="cb30-222"><a href="#cb30-222" aria-hidden="true" tabindex="-1"></a>(2) Population follows a normal distribution.</span>
<span id="cb30-223"><a href="#cb30-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-224"><a href="#cb30-224" aria-hidden="true" tabindex="-1"></a>The null hypothesis is that the mean income of female employees is equal to $500 per week, represented as H0: mu = 500.</span>
<span id="cb30-225"><a href="#cb30-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-226"><a href="#cb30-226" aria-hidden="true" tabindex="-1"></a>The alternative hypothesis is that the mean income of female employees is less than $500 per week, represented as Ha: mu &lt; 500.</span>
<span id="cb30-227"><a href="#cb30-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-228"><a href="#cb30-228" aria-hidden="true" tabindex="-1"></a>We will reject the null hypothesis if the p-value is less than 0.05, indicating that the observed sample mean of $410 is significantly lower than the population mean of $500.</span>
<span id="cb30-229"><a href="#cb30-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-230"><a href="#cb30-230" aria-hidden="true" tabindex="-1"></a><span class="fu">### p-value calculation</span></span>
<span id="cb30-231"><a href="#cb30-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-234"><a href="#cb30-234" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-235"><a href="#cb30-235" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pt</span>(t_score, sample_size<span class="dv">-1</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-236"><a href="#cb30-236" aria-hidden="true" tabindex="-1"></a>p</span>
<span id="cb30-237"><a href="#cb30-237" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-238"><a href="#cb30-238" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion </span></span>
<span id="cb30-239"><a href="#cb30-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-240"><a href="#cb30-240" aria-hidden="true" tabindex="-1"></a>Performed one-tailed t-test to test the hypothesis. The p-value associated with this test statistic is 0.008535841.</span>
<span id="cb30-241"><a href="#cb30-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-242"><a href="#cb30-242" aria-hidden="true" tabindex="-1"></a>Since the p-value is less than the significance level of 0.05, we reject the null hypothesis and conclude that there is sufficient evidence to support the claim that the mean income of female employees is lower than $500 per week. This implies that female employees in this service company are paid less than the senior-level workers as per the union agreement.</span>
<span id="cb30-243"><a href="#cb30-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-244"><a href="#cb30-244" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 4-C</span></span>
<span id="cb30-245"><a href="#cb30-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-246"><a href="#cb30-246" aria-hidden="true" tabindex="-1"></a>Two assumptions for the analysis: </span>
<span id="cb30-247"><a href="#cb30-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-248"><a href="#cb30-248" aria-hidden="true" tabindex="-1"></a>(1) Sample is randomly selected, and </span>
<span id="cb30-249"><a href="#cb30-249" aria-hidden="true" tabindex="-1"></a>(2) Population follows a normal distribution.</span>
<span id="cb30-250"><a href="#cb30-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-251"><a href="#cb30-251" aria-hidden="true" tabindex="-1"></a>The null hypothesis is that the mean income of female employees is equal to $500 per week, represented as H0: mu = 500.</span>
<span id="cb30-252"><a href="#cb30-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-253"><a href="#cb30-253" aria-hidden="true" tabindex="-1"></a>The alternative hypothesis is that the mean income of female employees is greater than $500 per week, represented as Ha: mu &gt; 500.</span>
<span id="cb30-254"><a href="#cb30-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-255"><a href="#cb30-255" aria-hidden="true" tabindex="-1"></a>We will reject the null hypothesis if the p-value is less than 0.05, indicating that the observed sample mean of $410 is significantly higher than the population mean of $500.</span>
<span id="cb30-256"><a href="#cb30-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-257"><a href="#cb30-257" aria-hidden="true" tabindex="-1"></a><span class="fu">### p-value calculation</span></span>
<span id="cb30-258"><a href="#cb30-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-261"><a href="#cb30-261" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-262"><a href="#cb30-262" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pt</span>(t_score, sample_size<span class="dv">-1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-263"><a href="#cb30-263" aria-hidden="true" tabindex="-1"></a>p</span>
<span id="cb30-264"><a href="#cb30-264" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-265"><a href="#cb30-265" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion </span></span>
<span id="cb30-266"><a href="#cb30-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-267"><a href="#cb30-267" aria-hidden="true" tabindex="-1"></a>The p-value is 0.9914642, which is greater than the significance level of 0.05. Therefore, we fail to reject the null hypothesis and conclude that there is insufficient evidence to support the claim that the mean income of female employees is greater than $500 per week. In other words, we cannot conclude that female employees earn significantly more than the agreed-upon mean income for all senior-level workers in the company.</span>
<span id="cb30-268"><a href="#cb30-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-269"><a href="#cb30-269" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 5</span></span>
<span id="cb30-270"><a href="#cb30-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-271"><a href="#cb30-271" aria-hidden="true" tabindex="-1"></a>Jones and Smith separately conduct studies to test H0: μ = 500 against Ha: μ ≠ 500, each </span>
<span id="cb30-272"><a href="#cb30-272" aria-hidden="true" tabindex="-1"></a>with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7,</span>
<span id="cb30-273"><a href="#cb30-273" aria-hidden="true" tabindex="-1"></a>with se = 10.0.</span>
<span id="cb30-274"><a href="#cb30-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-275"><a href="#cb30-275" aria-hidden="true" tabindex="-1"></a>  A. Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 </span>
<span id="cb30-276"><a href="#cb30-276" aria-hidden="true" tabindex="-1"></a>     for Smith.</span>
<span id="cb30-277"><a href="#cb30-277" aria-hidden="true" tabindex="-1"></a>  B. Using α = 0.05, for each study indicate whether the result is “statistically significant.”</span>
<span id="cb30-278"><a href="#cb30-278" aria-hidden="true" tabindex="-1"></a>  C. Using this example, explain the misleading aspects of reporting the result of a test as “P ≤      0.05” versus “P &gt; 0.05,” or as “reject H0” versus “Do not reject H0,” without reporting the      actual P-value.</span>
<span id="cb30-279"><a href="#cb30-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-280"><a href="#cb30-280" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 5-A</span></span>
<span id="cb30-281"><a href="#cb30-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-282"><a href="#cb30-282" aria-hidden="true" tabindex="-1"></a>Two assumptions for the analysis: </span>
<span id="cb30-283"><a href="#cb30-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-284"><a href="#cb30-284" aria-hidden="true" tabindex="-1"></a>(1) Sample is randomly selected, and </span>
<span id="cb30-285"><a href="#cb30-285" aria-hidden="true" tabindex="-1"></a>(2) Population follows a normal distribution.</span>
<span id="cb30-286"><a href="#cb30-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-287"><a href="#cb30-287" aria-hidden="true" tabindex="-1"></a>The null hypothesis for both studies is that the population mean is equal to 500, represented as H0: μ = 500.</span>
<span id="cb30-288"><a href="#cb30-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-289"><a href="#cb30-289" aria-hidden="true" tabindex="-1"></a>The alternative hypothesis for both studies is that the population mean is not equal to 500, represented as Ha: μ ≠ 500.</span>
<span id="cb30-290"><a href="#cb30-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-291"><a href="#cb30-291" aria-hidden="true" tabindex="-1"></a>We will reject the null hypothesis at a p-value less than 0.05</span>
<span id="cb30-292"><a href="#cb30-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-293"><a href="#cb30-293" aria-hidden="true" tabindex="-1"></a><span class="fu">### Calculating t-statistic and p-value for Jones</span></span>
<span id="cb30-294"><a href="#cb30-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-297"><a href="#cb30-297" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-298"><a href="#cb30-298" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="ot">&lt;-</span> <span class="fl">519.5</span></span>
<span id="cb30-299"><a href="#cb30-299" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb30-300"><a href="#cb30-300" aria-hidden="true" tabindex="-1"></a>standard_error <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb30-301"><a href="#cb30-301" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb30-302"><a href="#cb30-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-303"><a href="#cb30-303" aria-hidden="true" tabindex="-1"></a>t_score_jones <span class="ot">&lt;-</span> (sample_mean<span class="sc">-</span>mu)<span class="sc">/</span>(standard_error)</span>
<span id="cb30-304"><a href="#cb30-304" aria-hidden="true" tabindex="-1"></a>t_score_jones</span>
<span id="cb30-305"><a href="#cb30-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-306"><a href="#cb30-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-307"><a href="#cb30-307" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(t_score_jones, sample_size<span class="dv">-1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-308"><a href="#cb30-308" aria-hidden="true" tabindex="-1"></a>p</span>
<span id="cb30-309"><a href="#cb30-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-310"><a href="#cb30-310" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-311"><a href="#cb30-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-312"><a href="#cb30-312" aria-hidden="true" tabindex="-1"></a><span class="fu">### Calculating t-statistic and p-value for Smith</span></span>
<span id="cb30-313"><a href="#cb30-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-316"><a href="#cb30-316" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-317"><a href="#cb30-317" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="ot">&lt;-</span> <span class="fl">519.7</span></span>
<span id="cb30-318"><a href="#cb30-318" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb30-319"><a href="#cb30-319" aria-hidden="true" tabindex="-1"></a>standard_error <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb30-320"><a href="#cb30-320" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb30-321"><a href="#cb30-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-322"><a href="#cb30-322" aria-hidden="true" tabindex="-1"></a>t_score_smith <span class="ot">&lt;-</span> (sample_mean<span class="sc">-</span>mu)<span class="sc">/</span>(standard_error)</span>
<span id="cb30-323"><a href="#cb30-323" aria-hidden="true" tabindex="-1"></a>t_score_smith</span>
<span id="cb30-324"><a href="#cb30-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-325"><a href="#cb30-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-326"><a href="#cb30-326" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(t_score_smith, sample_size<span class="dv">-1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-327"><a href="#cb30-327" aria-hidden="true" tabindex="-1"></a>p</span>
<span id="cb30-328"><a href="#cb30-328" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-329"><a href="#cb30-329" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion </span></span>
<span id="cb30-330"><a href="#cb30-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-331"><a href="#cb30-331" aria-hidden="true" tabindex="-1"></a>Jones has a test-statistic of 1.95 and a p-value of 0.05145555, while Smith has a test-statistic of 1.97 and a p-value of 0.05145555.</span>
<span id="cb30-332"><a href="#cb30-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-333"><a href="#cb30-333" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 5-B</span></span>
<span id="cb30-334"><a href="#cb30-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-335"><a href="#cb30-335" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion </span></span>
<span id="cb30-336"><a href="#cb30-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-337"><a href="#cb30-337" aria-hidden="true" tabindex="-1"></a>Based on the given information, the result is statistically significant for Smith, but not for Jones.</span>
<span id="cb30-338"><a href="#cb30-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-339"><a href="#cb30-339" aria-hidden="true" tabindex="-1"></a>For Jones, the p-value (0.05145555) is greater than the significance level (α = 0.05), which means that we fail to reject the null hypothesis. This indicates that the result is not statistically significant for Jones.</span>
<span id="cb30-340"><a href="#cb30-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-341"><a href="#cb30-341" aria-hidden="true" tabindex="-1"></a>For Smith, the p-value (0.04911426) is less than the significance level (α = 0.05), which means that we reject the null hypothesis. This indicates that the result is statistically significant for Smith.</span>
<span id="cb30-342"><a href="#cb30-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-343"><a href="#cb30-343" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 5-C</span></span>
<span id="cb30-344"><a href="#cb30-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-345"><a href="#cb30-345" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion </span></span>
<span id="cb30-346"><a href="#cb30-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-347"><a href="#cb30-347" aria-hidden="true" tabindex="-1"></a>The misleading aspect of reporting the result of a test as "P ≤ 0.05" versus "P &gt; 0.05" or as "reject H0" versus "do not reject H0" without reporting the actual P-value is that it can mask the degree of uncertainty in the results. In this example, if we only reported "P ≤ 0.05" for Smith's study, we would conclude that the result is statistically significant. However, we would miss the fact that the P-value is very close to the significance level, indicating that the result may not be very strong or may be subject to random chance. Similarly, if we only reported "P &gt; 0.05" for Jones's study, we would conclude that the result is not statistically significant, but we would miss the fact that the P-value is very close to the significance level, indicating that the result may be borderline significant. Therefore, it is important to report the actual P-value to provide a more accurate interpretation of the results.</span>
<span id="cb30-348"><a href="#cb30-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-349"><a href="#cb30-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-350"><a href="#cb30-350" aria-hidden="true" tabindex="-1"></a>If we fail to report the P-value and simply state whether the P-value is less than/equal to or greater than the defined significance level of the test, one cannot determine the strength of the conclusion. In the Jones/Smith example, reporting the results only as *P ≤ 0.05* versus *P &gt; 0.05* will lead to different conclusions about very similar results.</span>
<span id="cb30-351"><a href="#cb30-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-352"><a href="#cb30-352" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 6</span></span>
<span id="cb30-353"><a href="#cb30-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-354"><a href="#cb30-354" aria-hidden="true" tabindex="-1"></a>A school nurse wants to determine whether age is a factor in whether children choose a healthy snack after school. She conducts a survey of 300 middle school students, with the results </span>
<span id="cb30-355"><a href="#cb30-355" aria-hidden="true" tabindex="-1"></a>below. Test at α = 0.05 the claim that the proportion who choose a healthy snack differs by grade level. What is the null hypothesis? Which test should we use? What is the conclusion?</span>
<span id="cb30-356"><a href="#cb30-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-357"><a href="#cb30-357" aria-hidden="true" tabindex="-1"></a><span class="fu">### Null Hypothesis </span></span>
<span id="cb30-358"><a href="#cb30-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-359"><a href="#cb30-359" aria-hidden="true" tabindex="-1"></a>The null hypothesis is that there is no association between grade level and the proportion of students who choose a healthy snack. </span>
<span id="cb30-360"><a href="#cb30-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-361"><a href="#cb30-361" aria-hidden="true" tabindex="-1"></a>The alternative hypothesis is that there is an association between grade level and the proportion of students who choose a healthy snack.</span>
<span id="cb30-362"><a href="#cb30-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-363"><a href="#cb30-363" aria-hidden="true" tabindex="-1"></a><span class="fu">### Which test should we use? (Chi Square)?</span></span>
<span id="cb30-364"><a href="#cb30-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-365"><a href="#cb30-365" aria-hidden="true" tabindex="-1"></a>In the case of the school nurse's survey data on snack choices, a chi-square test of independence should be used because the data is categorical (healthy snack vs unhealthy snack) and the research question is about whether there is a relationship between snack choice and grade level. The chi-square test is used to determine whether there is a significant association between two categorical variables.</span>
<span id="cb30-366"><a href="#cb30-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-367"><a href="#cb30-367" aria-hidden="true" tabindex="-1"></a><span class="fu">### Chi-square Test</span></span>
<span id="cb30-368"><a href="#cb30-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-371"><a href="#cb30-371" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-372"><a href="#cb30-372" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the contingency table</span></span>
<span id="cb30-373"><a href="#cb30-373" aria-hidden="true" tabindex="-1"></a>snack_table <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">31</span>, <span class="dv">43</span>, <span class="dv">51</span>, <span class="dv">69</span>, <span class="dv">57</span>, <span class="dv">49</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-374"><a href="#cb30-374" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(snack_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Healthy snack"</span>, <span class="st">"Unhealthy snack"</span>)</span>
<span id="cb30-375"><a href="#cb30-375" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(snack_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"6th grade"</span>, <span class="st">"7th grade"</span>, <span class="st">"8th grade"</span>)</span>
<span id="cb30-376"><a href="#cb30-376" aria-hidden="true" tabindex="-1"></a>snack_table</span>
<span id="cb30-377"><a href="#cb30-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-378"><a href="#cb30-378" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct the chi-square test of independence</span></span>
<span id="cb30-379"><a href="#cb30-379" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(snack_table)</span>
<span id="cb30-380"><a href="#cb30-380" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-381"><a href="#cb30-381" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion</span></span>
<span id="cb30-382"><a href="#cb30-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-383"><a href="#cb30-383" aria-hidden="true" tabindex="-1"></a>Since the p-value is less than the significance level of 0.05, </span>
<span id="cb30-384"><a href="#cb30-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-385"><a href="#cb30-385" aria-hidden="true" tabindex="-1"></a>The output of the chisq.test function indicates that the chi-square test statistic is 8.3383 with 2 degrees of freedom, and the corresponding p-value is 0.01547. So we can reject the null hypothesis that there is no association between snack choice and grade level, and conclude that there is evidence of a significant association between two categorical variables: snack choice and grade level at a significance level of 0.05.</span>
<span id="cb30-386"><a href="#cb30-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-387"><a href="#cb30-387" aria-hidden="true" tabindex="-1"></a>Based on the results of the chi-square test of independence, it is found that there is a statistically significant association between snack choice and grade level among the surveyed students. Specifically, the data indicates that the proportion of students who choose healthy snacks differs significantly across grade levels. The contingency table and chi-square test showed that more 6th-grade students (31) chose healthy snacks compared to 7th-grade students (43) and 8th-grade students (51). On the other hand, more 8th-grade students (49) chose unhealthy snacks compared to 6th-grade students (69) and 7th-grade students (57).</span>
<span id="cb30-388"><a href="#cb30-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-389"><a href="#cb30-389" aria-hidden="true" tabindex="-1"></a>Therefore, we can conclude that grade level is a factor in whether children choose a healthy snack after school. The proportion of students who choose a healthy snack appears to differ across the three grade levels. Overall, these results suggest that the school may need to target their health promotion efforts towards the specific grade levels where unhealthy snack choices are more prevalent. The results may also inform further research into the factors that influence snack choices among middle school students.</span>
<span id="cb30-390"><a href="#cb30-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-391"><a href="#cb30-391" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 7</span></span>
<span id="cb30-392"><a href="#cb30-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-393"><a href="#cb30-393" aria-hidden="true" tabindex="-1"></a>Per-pupil costs (in thousands of dollars) for cyber charter school tuition for school districts in three areas are shown. Test the claim that there is a difference in means for the three areas, using an appropriate test. What is the null hypothesis? Which test should we use? What is the conclusion?</span>
<span id="cb30-394"><a href="#cb30-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-397"><a href="#cb30-397" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-398"><a href="#cb30-398" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the data</span></span>
<span id="cb30-399"><a href="#cb30-399" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb30-400"><a href="#cb30-400" aria-hidden="true" tabindex="-1"></a>  <span class="at">Area =</span> <span class="fu">c</span>(<span class="st">"Area 1"</span>, <span class="st">"Area 2"</span>, <span class="st">"Area 3"</span>),</span>
<span id="cb30-401"><a href="#cb30-401" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value1 =</span> <span class="fu">c</span>(<span class="fl">6.2</span>, <span class="fl">7.5</span>, <span class="fl">5.8</span>),</span>
<span id="cb30-402"><a href="#cb30-402" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value2 =</span> <span class="fu">c</span>(<span class="fl">9.3</span>, <span class="fl">8.2</span>, <span class="fl">6.4</span>),</span>
<span id="cb30-403"><a href="#cb30-403" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value3 =</span> <span class="fu">c</span>(<span class="fl">6.8</span>, <span class="fl">8.5</span>, <span class="fl">5.6</span>),</span>
<span id="cb30-404"><a href="#cb30-404" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value4 =</span> <span class="fu">c</span>(<span class="fl">6.1</span>, <span class="fl">8.2</span>, <span class="fl">7.1</span>),</span>
<span id="cb30-405"><a href="#cb30-405" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value5 =</span> <span class="fu">c</span>(<span class="fl">6.7</span>, <span class="fl">7.0</span>, <span class="fl">3.0</span>),</span>
<span id="cb30-406"><a href="#cb30-406" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value6 =</span> <span class="fu">c</span>(<span class="fl">7.5</span>, <span class="fl">9.3</span>, <span class="fl">3.5</span>)</span>
<span id="cb30-407"><a href="#cb30-407" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-408"><a href="#cb30-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-409"><a href="#cb30-409" aria-hidden="true" tabindex="-1"></a>data1<span class="ot">=</span>data</span>
<span id="cb30-410"><a href="#cb30-410" aria-hidden="true" tabindex="-1"></a><span class="co"># # Alternatively, you can set the row names separately</span></span>
<span id="cb30-411"><a href="#cb30-411" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data1) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb30-412"><a href="#cb30-412" aria-hidden="true" tabindex="-1"></a><span class="co"># # Display table without boundaries/borders</span></span>
<span id="cb30-413"><a href="#cb30-413" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(data1, <span class="at">row.names =</span> <span class="cn">FALSE</span>, <span class="at">col.names =</span> <span class="cn">NULL</span>,</span>
<span id="cb30-414"><a href="#cb30-414" aria-hidden="true" tabindex="-1"></a>             <span class="at">border =</span> <span class="cn">NA</span>, <span class="at">digits =</span> <span class="dv">1</span>)<span class="sc">%&gt;%</span></span>
<span id="cb30-415"><a href="#cb30-415" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="at">full_width =</span> <span class="cn">TRUE</span>, <span class="at">position =</span> <span class="st">'center'</span>, <span class="at">font_size =</span> <span class="dv">14</span>, <span class="at">stripe_color=</span><span class="st">'black'</span>)</span>
<span id="cb30-416"><a href="#cb30-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-417"><a href="#cb30-417" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-418"><a href="#cb30-418" aria-hidden="true" tabindex="-1"></a><span class="fu">### Null Hypothesis</span></span>
<span id="cb30-419"><a href="#cb30-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-420"><a href="#cb30-420" aria-hidden="true" tabindex="-1"></a>In order to investigate if there is a difference in means for the per-pupil costs of cyber charter school tuition in three different areas, we can use Analysis of Variance (ANOVA) test. ANOVA is a statistical test that compares means of three or more groups.</span>
<span id="cb30-421"><a href="#cb30-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-422"><a href="#cb30-422" aria-hidden="true" tabindex="-1"></a>Null Hypothesis: The null hypothesis for the ANOVA test would state that there is no significant difference between the means of the per-pupil costs for cyber charter school tuition in the three areas. This can be expressed mathematically as H0: μ1 = μ2 = μ3, where μ1, μ2, and μ3 represent the means of the per-pupil costs for cyber charter school tuition in Area 1, Area 2, and Area 3, respectively.</span>
<span id="cb30-423"><a href="#cb30-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-424"><a href="#cb30-424" aria-hidden="true" tabindex="-1"></a>Alternative Hypothesis: On the other hand, the alternative hypothesis (H1) suggests that at least one mean is significantly different from the others.</span>
<span id="cb30-425"><a href="#cb30-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-426"><a href="#cb30-426" aria-hidden="true" tabindex="-1"></a><span class="fu">### Which test should we use? (Anova)</span></span>
<span id="cb30-427"><a href="#cb30-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-428"><a href="#cb30-428" aria-hidden="true" tabindex="-1"></a>To test the claim that there is a difference in means for the three areas, we can use the analysis of variance (ANOVA) test. </span>
<span id="cb30-429"><a href="#cb30-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-430"><a href="#cb30-430" aria-hidden="true" tabindex="-1"></a>In this case, since we are comparing means across three areas, we can use a one-way ANOVA. We will use the following R code to conduct the test:</span>
<span id="cb30-431"><a href="#cb30-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-432"><a href="#cb30-432" aria-hidden="true" tabindex="-1"></a>To conduct the ANOVA test in R, we can use the aov function.</span>
<span id="cb30-433"><a href="#cb30-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-434"><a href="#cb30-434" aria-hidden="true" tabindex="-1"></a><span class="fu">### Anova Test</span></span>
<span id="cb30-435"><a href="#cb30-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-438"><a href="#cb30-438" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-439"><a href="#cb30-439" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the data to long format</span></span>
<span id="cb30-440"><a href="#cb30-440" aria-hidden="true" tabindex="-1"></a>data_long <span class="ot">&lt;-</span> <span class="fu">gather</span>(data, <span class="at">key =</span> <span class="st">"Variable"</span>, <span class="at">value =</span> <span class="st">"Value"</span>, <span class="sc">-</span>Area)</span>
<span id="cb30-441"><a href="#cb30-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-442"><a href="#cb30-442" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct ANOVA test</span></span>
<span id="cb30-443"><a href="#cb30-443" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">aov</span>(Value <span class="sc">~</span> Area, <span class="at">data =</span> data_long)</span>
<span id="cb30-444"><a href="#cb30-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-445"><a href="#cb30-445" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the ANOVA table</span></span>
<span id="cb30-446"><a href="#cb30-446" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(result)</span>
<span id="cb30-447"><a href="#cb30-447" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-448"><a href="#cb30-448" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conclusion</span></span>
<span id="cb30-449"><a href="#cb30-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-450"><a href="#cb30-450" aria-hidden="true" tabindex="-1"></a>The ANOVA table shows that the F value is 8.176 and the p-value is 0.00397. Since the p-value is less than the significance level of 0.05, we reject the null hypothesis and conclude that there is evidence of a difference in means for the three areas. </span>
<span id="cb30-451"><a href="#cb30-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-452"><a href="#cb30-452" aria-hidden="true" tabindex="-1"></a>Therefore, we can infer that the per-pupil costs for cyber charter school tuition differ among the three areas. Specifically, we found that the mean per-pupil costs for cyber charter school tuition in Area 1 (mean = 7.1) and Area 2 (mean = 8.1) were higher than the mean per-pupil costs in Area 3 (mean = 5.23). The ANOVA test supports the conclusion that there is a significant difference between the means of the per-pupil costs for cyber charter school tuition in the three areas.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>