<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Young Soo Choi">
<meta name="dcterms.date" content="2023-04-25">
<meta name="description" content="hw4">

<title>Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Homework 4">
<meta name="twitter:description" content="hw4">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/HW4_young_files/figure-html/unnamed-chunk-17-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a>
  <ul class="collapse">
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">(A)</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">(B)</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">(C)</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#a-1" id="toc-a-1" class="nav-link" data-scroll-target="#a-1">(A)</a></li>
  <li><a href="#b-1" id="toc-b-1" class="nav-link" data-scroll-target="#b-1">(B)</a></li>
  <li><a href="#c-1" id="toc-c-1" class="nav-link" data-scroll-target="#c-1">(C)</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">(D)</a></li>
  <li><a href="#e" id="toc-e" class="nav-link" data-scroll-target="#e">(E)</a></li>
  <li><a href="#f" id="toc-f" class="nav-link" data-scroll-target="#f">(F)</a></li>
  </ul></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a>
  <ul class="collapse">
  <li><a href="#a-2" id="toc-a-2" class="nav-link" data-scroll-target="#a-2">(A)</a></li>
  <li><a href="#b-2" id="toc-b-2" class="nav-link" data-scroll-target="#b-2">(B)</a></li>
  <li><a href="#c-2" id="toc-c-2" class="nav-link" data-scroll-target="#c-2">(C)</a></li>
  <li><a href="#d-1" id="toc-d-1" class="nav-link" data-scroll-target="#d-1">(D)</a></li>
  <li><a href="#e-1" id="toc-e-1" class="nav-link" data-scroll-target="#e-1">(E)</a></li>
  <li><a href="#f-1" id="toc-f-1" class="nav-link" data-scroll-target="#f-1">(F)</a></li>
  <li><a href="#g" id="toc-g" class="nav-link" data-scroll-target="#g">(G)</a></li>
  <li><a href="#h" id="toc-h" class="nav-link" data-scroll-target="#h">(H)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 4</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw4</div>
  </div>
  </div>

<div>
  <div class="description">
    hw4
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Young Soo Choi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 25, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="question-1" class="level1">
<h1>Question 1</h1>
<section id="a" class="level2">
<h2 class="anchored" data-anchor-id="a">(A)</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">=</span><span class="dv">1240</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">=</span><span class="dv">18000</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>pred_price<span class="ot">&lt;-</span><span class="sc">-</span><span class="dv">10536</span><span class="fl">+53.8</span><span class="sc">*</span>x1<span class="fl">+2.84</span><span class="sc">*</span>x2</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>pred_price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107296</code></pre>
</div>
</div>
<p>When the given values for size of home and size of lot are 1240 and 18000, the predicted selling price is 107296.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="dv">145000</span><span class="sc">-</span>pred_price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37704</code></pre>
</div>
</div>
<p>And the residual is 37704. This means that, in the given model, the selling price that cannot be explained by size of home and los is 37704.</p>
</section>
<section id="b" class="level2">
<h2 class="anchored" data-anchor-id="b">(B)</h2>
<p>It is increasing by 53.8. Since the coefficient of x1(size of home) is 53.8, if x2(size of lot) is constant, y(predicted selling price) increases by 53.8.</p>
</section>
<section id="c" class="level2">
<h2 class="anchored" data-anchor-id="c">(C)</h2>
<p>As discussed above, when x2 is constant and x1 increases by 1 unit, y increases by 53.8. Likewise, if x1 is constant and x2 increases by one unit, y increases by 2.84, the coefficient of x2 in the above equation.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.94366</code></pre>
</div>
</div>
<p>Using this relationship, the amount of increase in x2 that gives the same effect as the increase in x1 by one unit is 18.94. That is, if x2 increases 18.94, y increases as x1 increases by one unit.</p>
</section>
</section>
<section id="question-2" class="level1">
<h1>Question 2</h1>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data loading</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'alr4' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: effects</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'effects' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "degree" "rank"   "sex"    "year"   "ysdeg"  "salary"</code></pre>
</div>
</div>
<section id="a-1" class="level2">
<h2 class="anchored" data-anchor-id="a-1">(A)</h2>
<p>It is necessary to implement a t-test to verify the hypothesis that the average salary of men and women is the same.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary<span class="sc">~</span>sex, <span class="at">data=</span>salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by sex
t = 1.7744, df = 21.591, p-value = 0.09009
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -567.8539 7247.1471
sample estimates:
  mean in group Male mean in group Female 
            24696.79             21357.14 </code></pre>
</div>
</div>
<p>Using r’s t.test function, the alternative hypothesis is that the difference between the two will not be zero (that is, there is a salary difference between men and women), and the null hypothesis is that there is no salary difference between men and women. However, as a result of the t-test, the p value is greater than 0.05, so the null hypothesis cannot be rejected at the significance level of 0.05. This means that there is no salary difference between men and women.</p>
</section>
<section id="b-1" class="level2">
<h2 class="anchored" data-anchor-id="b-1">(B)</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>sal.lm<span class="ot">&lt;-</span><span class="fu">lm</span>(salary<span class="sc">~</span>., <span class="at">data=</span>salary)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sal.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ., data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The results of deriving multiple regression equations for wages using all variables were obtained. According to the above equation, salary is 1166.37 high if the sex is female.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(sal.lm, <span class="st">"sexFemale"</span>, <span class="at">level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              2.5 %   97.5 %
sexFemale -697.8183 3030.565</code></pre>
</div>
</div>
<p>Using the above values, the 95% confidence interval of the sex difference between men and women is from -697.8 to 3030.6. Since this confidence interval includes 0, it can be said that the coefficient of the regression equation for sex is not significant at the 5% level of significance.</p>
</section>
<section id="c-1" class="level2">
<h2 class="anchored" data-anchor-id="c-1">(C)</h2>
<p>In summary, the multiple regression equation derived above can be expressed as follows.</p>
<p>Salary = 15746.1 + 1388.6<em>degreePhD + 5292.4</em>rankAssoc + 11118.8<em>rankProf + 1166.4</em>sexFemale + 476.3<em>years -124.6</em>ysdeg</p>
<p>Prior to the discussion, all significance levels are set at 0.05.</p>
<p>For degree, (a) salary difference between masters and phD is not statistically significant.(p-value is greater than 0.05) (b) And according to the coefficient, the salary of the phD is greater than masters’ by 1388.7. Taken together, when other variables are the same, the Ph.D.&nbsp;owner is paid1388.7 higher than the master’s, but this is not statistically significant.</p>
<p>For rank, (a) salary difference between Asst, Assoc, and Prof is statistically significant.(p-value is less than 0.05) (b) And according to the coefficient, the salary of the Assoc is greater than Asst’s by 5292.4 and the salary of the Prof is greater than Asst’s by 11118.8. Overall, the associate professor receives 5292.4 higher salary than the assistant professor, and the professor receives 11118.8 higher salary than the assistant professor, when any other variables are the same. And it is statistically significant.</p>
<p>For sex, (a) salary difference between male and female is not statistically significant.(p-value is greater than 0.05) (b) And according to the coefficient, the salary of the female is greater than male’s by 1166.4. In general, when other variables are constant, female professors are paid 1166.4 higher than male professors, but this is not statistically significant.</p>
<p>For year, (a) coefficient of year is statistically significant.(p-value is less than 0.05) (b) And according to the coefficient, when the number of years increases by 1, the salary increases by 476.3. In other words, if the number of years of service increases by one year, the salary increases by 476.3 when other variables are constant, which is statistically significant.</p>
<p>For ysdeg, (a) coefficient of ysdeg is not statistically significant.(p-value is greater than 0.05) (b) And according to the coefficient, when the number of ysdeg increases by 1, the salary decreases by 124.6. In the end, according to this model, if years since highest degree increases when other variables are the same, income decreases by 124.6, but this is not statistically significant.</p>
</section>
<section id="d" class="level2">
<h2 class="anchored" data-anchor-id="d">(D)</h2>
<p>The baseline can be changed using the relevel function. Through this, Assoc was changed to a baseline instead of Asst and a multiple regression model was derived.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank.a <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Assoc"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>sal.lm<span class="fl">.2</span><span class="ot">&lt;-</span><span class="fu">lm</span>(salary<span class="sc">~</span>degree<span class="sc">+</span>rank.a<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sal.lm<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank.a + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 21038.41    1109.12  18.969  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rank.aAsst  -5292.36    1145.40  -4.621 3.22e-05 ***
rank.aProf   5826.40    1012.93   5.752 7.28e-07 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fl">5826.40</span><span class="sc">-</span>(<span class="sc">-</span><span class="fl">5292.36</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11118.76</code></pre>
</div>
</div>
<p>Checking the above coefficients, salary decreases by 5292.4 compared to assoc when it is asst. Prof has a higher salary by 5826.4 compared to assoc. Comparing prop to asst, the difference is 11118.8, which is the same as the difference when the baseline is not changed. In other words, even if the baseline is changed, only the form of the multiple regression model changes and the meaning is the same.</p>
</section>
<section id="e" class="level2">
<h2 class="anchored" data-anchor-id="e">(E)</h2>
<p>Except for the rank variable, multiple regression equations were derived again.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>sal.lm.nr<span class="ot">&lt;-</span><span class="fu">lm</span>(salary<span class="sc">~</span>degree<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sal.lm.nr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
year          351.97     142.48   2.470 0.017185 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>There are many changes. First of all, Ph.D.&nbsp;ownership acts in the direction of reducing salaries, which is statistically significant (all significance levels are 0.05), and gender has also changed its direction of influence. It was found that women’s salary was lower than that of men, but it was not statistically significant. The influence of ysdeg also changed, and when rank was included, this variable had a negative effect on salary, but now it has a positive effect. And this result is also significant. Finally, year did not change the direction of influence, but the coefficient was slightly reduced. be statistically significant as well.</p>
</section>
<section id="f" class="level2">
<h2 class="anchored" data-anchor-id="f">(F)</h2>
<p>First, a new variable(ysdeg.dean) with an “old” when ysdeg exceeds 15 and a “new” if not was created.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:car':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>new.sal<span class="ot">&lt;-</span>salary <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">ysdeg.dean =</span> <span class="fu">ifelse</span>(ysdeg<span class="sc">&gt;</span><span class="dv">15</span>, <span class="st">"old"</span>, <span class="st">"new"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Next, in order to check the multicollinearity, the vif value was checked using the vif function.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>vif<span class="ot">&lt;-</span><span class="fu">vif</span>(<span class="fu">lm</span>(salary<span class="sc">~</span>degree<span class="sc">+</span>rank<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg.dean, <span class="at">data=</span>new.sal))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>vif</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>               GVIF Df GVIF^(1/(2*Df))
degree     1.341872  1        1.158392
rank       2.964200  2        1.312130
sex        1.295820  1        1.138341
year       1.726209  1        1.313853
ysdeg.dean 2.678486  1        1.636608</code></pre>
</div>
</div>
<p>Here, there is no value over 5, so it seems that there is no variable with strong multicollinearity. Therefore, I derived multiple regression equations including all variables and confirmed the effect of ysdeg reclassified into old and new.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>sal.lm.on<span class="ot">&lt;-</span><span class="fu">lm</span>(salary<span class="sc">~</span>degree<span class="sc">+</span>rank<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg.dean, <span class="at">data=</span>new.sal)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sal.lm.on)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg.dean, 
    data = new.sal)

Residuals:
    Min      1Q  Median      3Q     Max 
-3403.3 -1387.0  -167.0   528.2  9233.8 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   15491.84     806.32  19.213  &lt; 2e-16 ***
degreePhD       818.93     797.48   1.027   0.3100    
rankAssoc      4972.66     997.17   4.987 9.61e-06 ***
rankProf      11096.95    1191.00   9.317 4.54e-12 ***
sexFemale       907.14     840.54   1.079   0.2862    
year            434.85      78.89   5.512 1.65e-06 ***
ysdeg.deanold -2163.46    1072.04  -2.018   0.0496 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2362 on 45 degrees of freedom
Multiple R-squared:  0.8594,    Adjusted R-squared:  0.8407 
F-statistic: 45.86 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>As a result of the confirmation, if all other variables were the same, if ysdeg was old, the salary was 2163.5 lower than if it was new. In addition, the p value of this coefficient is 0.0496, so it is statistically significant at the significance level of 0.05. In other words, the perception that the new dean is more generous in salary is thought to be grounded.</p>
</section>
</section>
<section id="question-3" class="level1">
<h1>Question 3</h1>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'smss' was built under R version 4.2.3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(house.selling.price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "case"  "Taxes" "Beds"  "Baths" "New"   "Price" "Size" </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(house.selling.price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100</code></pre>
</div>
</div>
<section id="a-2" class="level2">
<h2 class="anchored" data-anchor-id="a-2">(A)</h2>
<p>A multiple regression model was derived with Size and New as independent variables and price as dependent variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>lm.<span class="fl">3.</span>a<span class="ot">&lt;-</span><span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New, <span class="at">data=</span>house.selling.price)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.<span class="fl">3.</span>a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>As a result, as the size increases by one unit, the price increases by 116.1, and in the case of New, the price is 57736.3 higher than that of Old. These are all statistically significant (significance level 0.05).</p>
</section>
<section id="b-2" class="level2">
<h2 class="anchored" data-anchor-id="b-2">(B)</h2>
<p>For new home: Price = 17505.42 + 116.132<em>Size For old home; Price = -40230.867 + 116.132</em>Size</p>
<p>This relationship can also be seen in the figure below.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(house.selling.price, <span class="fu">aes</span>(Size, Price, <span class="at">color=</span><span class="fu">as.factor</span>(New)),</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Size"</span>,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Price"</span>) <span class="sc">+</span> </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>), <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"Old"</span>, <span class="st">"New"</span>)) <span class="sc">+</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="fl">116.132</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">40230.867</span>, <span class="at">color =</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="fl">116.132</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">40230.867+57736.283</span>, <span class="at">color=</span><span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HW4_young_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In interpretation, regardless of whether the house is new or old, the increase in price is the same as the unit increase in size. However, the intercept of new is 17505.42, which is as large as 57736.283 compared to the intercept of old. That is, the slope of the regression line representing each case is the same, but the new regression line is vertically higher than the old regression line by 57736.283.</p>
</section>
<section id="c-2" class="level2">
<h2 class="anchored" data-anchor-id="c-2">(C)</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>Size<span class="ot">=</span><span class="dv">3000</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>new.home.Price <span class="ot">&lt;-</span> <span class="fl">17505.42</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span>Size</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>old.home.Price <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span>Size</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>new.home.Price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 365901.4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>old.home.Price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 308165.1</code></pre>
</div>
</div>
<p>According to fitted model, when size is 3000, predicted selling price for a new home is 365901.4 and for an old home is 308165.1</p>
</section>
<section id="d-1" class="level2">
<h2 class="anchored" data-anchor-id="d-1">(D)</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>lm.<span class="fl">3.</span>d<span class="ot">&lt;-</span><span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">*</span>New, <span class="at">data=</span>house.selling.price)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.<span class="fl">3.</span>d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size * New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In the regression model that includes the interaction term, the price is rather lowered when new(-78527.5). However, according to the interaction term between Size and new, in the case of new, the sales price increases by 61.916 as the size increases by one unit. Even if it is new, the price is lower than old until it reaches a specific size, and it can be seen that the price of new is higher than old only when it exceeds that specific size.</p>
</section>
<section id="e-1" class="level2">
<h2 class="anchored" data-anchor-id="e-1">(E)</h2>
<p>For new home: Price = -100755.3 + 166.354<em>Size For old home; Price = -22227.808 + 104.438</em>Size</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(house.selling.price, <span class="fu">aes</span>(Size, Price, <span class="at">color=</span><span class="fu">as.factor</span>(New)),</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Size"</span>,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Price"</span>) <span class="sc">+</span> </span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>), <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"Old"</span>, <span class="st">"New"</span>)) <span class="sc">+</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="fl">104.438</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">22227.808</span>, <span class="at">color =</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="fl">166.354</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">100755.3</span>, <span class="at">color=</span><span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HW4_young_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As shown in the figure, in the case of new, the intercept is lower than old, but the slope of new is larger than that of old.</p>
</section>
<section id="f-1" class="level2">
<h2 class="anchored" data-anchor-id="f-1">(F)</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>Size<span class="ot">=</span><span class="dv">3000</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>new.home.Price<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">100755.3</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span>Size</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>old.home.Price<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span>Size</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>new.home.Price<span class="fl">.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 398306.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>old.home.Price<span class="fl">.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 291086.2</code></pre>
</div>
</div>
<p>Predicted selling price of new home is 398306.7 and of new home is 291086.2.</p>
</section>
<section id="g" class="level2">
<h2 class="anchored" data-anchor-id="g">(G)</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>Size<span class="ot">=</span><span class="dv">1500</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>new.home.Price<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">100755.3</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span>Size</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>old.home.Price<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span>Size</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>new.home.Price<span class="fl">.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 148775.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>old.home.Price<span class="fl">.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 134429.2</code></pre>
</div>
</div>
<p>Predicted selling price of new home is 148775.7 and of new home is 134429.2. The price difference is smaller than when the size is 3000. In the case of new, the slope of the model is larger than that of old, so the larger the size, the higher the price of new. In other words, as the size increases, the price difference between new and old will gradually increase, which can be seen from the regression equation between the two and the graph above.</p>
</section>
<section id="h" class="level2">
<h2 class="anchored" data-anchor-id="h">(H)</h2>
<p>Looking at the r-square value of each model, the r-square value of the model including the interaction term is larger(model with interaction term: 0.7443, model without it: 0.7226). Even looking at the adjusted r-square value that corrects the increased amount of explanation as the variable increasesr(model with interaction term: 0.7363, model without it: 0.7169), it can be said that the explanatory power of the model including the interaction term is higher. However, which model to use and prefer is not determined simply by these explanations. In this case, it was easy to compare the cases of new and old by simply modifying the expression, but if the number of variables increases or there are more than three categories of nominal variables, it will be increasingly difficult to derive or interpret the regression model. In other words, in selecting models and variables, various variables such as interpretability as well as simple explanatory power should be considered.</p>
<p>For this case, I prefer a model with interaction terms. It is interesting that the older the house, the smaller the price increase due to the increase in its area, in that the two variables interact to change the influence of the variable.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb63" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 4"</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Young Soo Choi"</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "hw4"</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "04/25/2023"</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw4</span></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a><span class="fu"># Question 1</span></span>
<span id="cb63-17"><a href="#cb63-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-18"><a href="#cb63-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## (A)</span></span>
<span id="cb63-19"><a href="#cb63-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-22"><a href="#cb63-22" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-23"><a href="#cb63-23" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">=</span><span class="dv">1240</span></span>
<span id="cb63-24"><a href="#cb63-24" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">=</span><span class="dv">18000</span></span>
<span id="cb63-25"><a href="#cb63-25" aria-hidden="true" tabindex="-1"></a>pred_price<span class="ot">&lt;-</span><span class="sc">-</span><span class="dv">10536</span><span class="fl">+53.8</span><span class="sc">*</span>x1<span class="fl">+2.84</span><span class="sc">*</span>x2</span>
<span id="cb63-26"><a href="#cb63-26" aria-hidden="true" tabindex="-1"></a>pred_price</span>
<span id="cb63-27"><a href="#cb63-27" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-28"><a href="#cb63-28" aria-hidden="true" tabindex="-1"></a>When the given values for size of home and size of lot are 1240 and 18000, the predicted selling price is 107296.</span>
<span id="cb63-29"><a href="#cb63-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-32"><a href="#cb63-32" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-33"><a href="#cb63-33" aria-hidden="true" tabindex="-1"></a><span class="dv">145000</span><span class="sc">-</span>pred_price</span>
<span id="cb63-34"><a href="#cb63-34" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-35"><a href="#cb63-35" aria-hidden="true" tabindex="-1"></a>And the residual is 37704. This means that, in the given model, the selling price that cannot be explained by size of home and los is 37704.</span>
<span id="cb63-36"><a href="#cb63-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-37"><a href="#cb63-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## (B)</span></span>
<span id="cb63-38"><a href="#cb63-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-39"><a href="#cb63-39" aria-hidden="true" tabindex="-1"></a>It is increasing by 53.8. Since the coefficient of x1(size of home) is 53.8, if x2(size of lot) is constant, y(predicted selling price) increases by 53.8.</span>
<span id="cb63-40"><a href="#cb63-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-41"><a href="#cb63-41" aria-hidden="true" tabindex="-1"></a><span class="fu">## (C)</span></span>
<span id="cb63-42"><a href="#cb63-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-43"><a href="#cb63-43" aria-hidden="true" tabindex="-1"></a>As discussed above, when x2 is constant and x1 increases by 1 unit, y increases by 53.8. Likewise, if x1 is constant and x2 increases by one unit, y increases by 2.84, the coefficient of x2 in the above equation.</span>
<span id="cb63-44"><a href="#cb63-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-47"><a href="#cb63-47" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-48"><a href="#cb63-48" aria-hidden="true" tabindex="-1"></a><span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span>
<span id="cb63-49"><a href="#cb63-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-50"><a href="#cb63-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-51"><a href="#cb63-51" aria-hidden="true" tabindex="-1"></a>Using this relationship, the amount of increase in x2 that gives the same effect as the increase in x1 by one unit is 18.94. That is, if x2 increases 18.94, y increases as x1 increases by one unit.</span>
<span id="cb63-52"><a href="#cb63-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-53"><a href="#cb63-53" aria-hidden="true" tabindex="-1"></a><span class="fu"># Question 2</span></span>
<span id="cb63-54"><a href="#cb63-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-57"><a href="#cb63-57" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-58"><a href="#cb63-58" aria-hidden="true" tabindex="-1"></a><span class="co"># data loading</span></span>
<span id="cb63-59"><a href="#cb63-59" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb63-60"><a href="#cb63-60" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span>
<span id="cb63-61"><a href="#cb63-61" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-62"><a href="#cb63-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-65"><a href="#cb63-65" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-66"><a href="#cb63-66" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(salary)</span>
<span id="cb63-67"><a href="#cb63-67" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-68"><a href="#cb63-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-69"><a href="#cb63-69" aria-hidden="true" tabindex="-1"></a><span class="fu">## (A)</span></span>
<span id="cb63-70"><a href="#cb63-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-71"><a href="#cb63-71" aria-hidden="true" tabindex="-1"></a>It is necessary to implement a t-test to verify the hypothesis that the average salary of men and women is the same.</span>
<span id="cb63-72"><a href="#cb63-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-75"><a href="#cb63-75" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-76"><a href="#cb63-76" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary<span class="sc">~</span>sex, <span class="at">data=</span>salary)</span>
<span id="cb63-77"><a href="#cb63-77" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-78"><a href="#cb63-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-79"><a href="#cb63-79" aria-hidden="true" tabindex="-1"></a>Using r's t.test function, the alternative hypothesis is that the difference between the two will not be zero (that is, there is a salary difference between men and women), and the null hypothesis is that there is no salary difference between men and women. However, as a result of the t-test, the p value is greater than 0.05, so the null hypothesis cannot be rejected at the significance level of 0.05. This means that there is no salary difference between men and women.</span>
<span id="cb63-80"><a href="#cb63-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-81"><a href="#cb63-81" aria-hidden="true" tabindex="-1"></a><span class="fu">## (B)</span></span>
<span id="cb63-82"><a href="#cb63-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-85"><a href="#cb63-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-86"><a href="#cb63-86" aria-hidden="true" tabindex="-1"></a>sal.lm<span class="ot">&lt;-</span><span class="fu">lm</span>(salary<span class="sc">~</span>., <span class="at">data=</span>salary)</span>
<span id="cb63-87"><a href="#cb63-87" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sal.lm)</span>
<span id="cb63-88"><a href="#cb63-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-89"><a href="#cb63-89" aria-hidden="true" tabindex="-1"></a>The results of deriving multiple regression equations for wages using all variables were obtained. According to the above equation, salary is 1166.37 high if the sex is female.</span>
<span id="cb63-90"><a href="#cb63-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-93"><a href="#cb63-93" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-94"><a href="#cb63-94" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(sal.lm, <span class="st">"sexFemale"</span>, <span class="at">level=</span><span class="fl">0.95</span>)</span>
<span id="cb63-95"><a href="#cb63-95" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-96"><a href="#cb63-96" aria-hidden="true" tabindex="-1"></a>Using the above values, the 95% confidence interval of the sex difference between men and women is from -697.8 to 3030.6. Since this confidence interval includes 0, it can be said that the coefficient of the regression equation for sex is not significant at the 5% level of significance.</span>
<span id="cb63-97"><a href="#cb63-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-98"><a href="#cb63-98" aria-hidden="true" tabindex="-1"></a><span class="fu">## (C)</span></span>
<span id="cb63-99"><a href="#cb63-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-100"><a href="#cb63-100" aria-hidden="true" tabindex="-1"></a>In summary, the multiple regression equation derived above can be expressed as follows.</span>
<span id="cb63-101"><a href="#cb63-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-102"><a href="#cb63-102" aria-hidden="true" tabindex="-1"></a>Salary = 15746.1 + 1388.6*degreePhD + 5292.4*rankAssoc + 11118.8*rankProf + 1166.4*sexFemale + 476.3*years -124.6*ysdeg</span>
<span id="cb63-103"><a href="#cb63-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-104"><a href="#cb63-104" aria-hidden="true" tabindex="-1"></a>Prior to the discussion, all significance levels are set at 0.05.</span>
<span id="cb63-105"><a href="#cb63-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-106"><a href="#cb63-106" aria-hidden="true" tabindex="-1"></a>For degree, (a) salary difference between masters and phD is not statistically significant.(p-value is greater than 0.05) (b) And according to the coefficient, the salary of the phD is greater than masters' by 1388.7. Taken together, when other variables are the same, the Ph.D. owner is paid1388.7 higher than the master's, but this is not statistically significant.</span>
<span id="cb63-107"><a href="#cb63-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-108"><a href="#cb63-108" aria-hidden="true" tabindex="-1"></a>For rank, (a) salary difference between Asst, Assoc, and Prof is statistically significant.(p-value is less than 0.05) (b) And according to the coefficient, the salary of the Assoc is greater than Asst's by 5292.4 and the salary of the Prof is greater than Asst's by 11118.8.  Overall, the associate professor receives 5292.4 higher salary than the assistant professor, and the professor receives 11118.8 higher salary than the assistant professor, when any other variables are the same. And it is statistically significant.</span>
<span id="cb63-109"><a href="#cb63-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-110"><a href="#cb63-110" aria-hidden="true" tabindex="-1"></a>For sex, (a) salary difference between male and female is not statistically significant.(p-value is greater than 0.05) (b) And according to the coefficient, the salary of the female is greater than male's by 1166.4. In general, when other variables are constant, female professors are paid 1166.4 higher than male professors, but this is not statistically significant.</span>
<span id="cb63-111"><a href="#cb63-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-112"><a href="#cb63-112" aria-hidden="true" tabindex="-1"></a>For year, (a) coefficient of year is statistically significant.(p-value is less than 0.05) (b) And according to the coefficient, when the number of years increases by 1, the salary increases by 476.3.</span>
<span id="cb63-113"><a href="#cb63-113" aria-hidden="true" tabindex="-1"></a>In other words, if the number of years of service increases by one year, the salary increases by 476.3 when other variables are constant, which is statistically significant.</span>
<span id="cb63-114"><a href="#cb63-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-115"><a href="#cb63-115" aria-hidden="true" tabindex="-1"></a>For ysdeg, (a) coefficient of ysdeg is not statistically significant.(p-value is greater than 0.05) (b) And according to the coefficient, when the number of ysdeg increases by 1, the salary decreases by 124.6. In the end, according to this model, if years since highest degree increases when other variables are the same, income decreases by 124.6, but this is not statistically significant.</span>
<span id="cb63-116"><a href="#cb63-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-117"><a href="#cb63-117" aria-hidden="true" tabindex="-1"></a><span class="fu">## (D)</span></span>
<span id="cb63-118"><a href="#cb63-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-119"><a href="#cb63-119" aria-hidden="true" tabindex="-1"></a>The baseline can be changed using the relevel function. Through this, Assoc was changed to a baseline instead of Asst and a multiple regression model was derived.</span>
<span id="cb63-120"><a href="#cb63-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-123"><a href="#cb63-123" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-124"><a href="#cb63-124" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank.a <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Assoc"</span>)</span>
<span id="cb63-125"><a href="#cb63-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-126"><a href="#cb63-126" aria-hidden="true" tabindex="-1"></a>sal.lm<span class="fl">.2</span><span class="ot">&lt;-</span><span class="fu">lm</span>(salary<span class="sc">~</span>degree<span class="sc">+</span>rank.a<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb63-127"><a href="#cb63-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-128"><a href="#cb63-128" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sal.lm<span class="fl">.2</span>)</span>
<span id="cb63-129"><a href="#cb63-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-130"><a href="#cb63-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-133"><a href="#cb63-133" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-134"><a href="#cb63-134" aria-hidden="true" tabindex="-1"></a><span class="fl">5826.40</span><span class="sc">-</span>(<span class="sc">-</span><span class="fl">5292.36</span>)</span>
<span id="cb63-135"><a href="#cb63-135" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-136"><a href="#cb63-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-137"><a href="#cb63-137" aria-hidden="true" tabindex="-1"></a>Checking the above coefficients, salary decreases by 5292.4 compared to assoc when it is asst. Prof has a higher salary by 5826.4 compared to assoc. Comparing prop to asst, the difference is 11118.8, which is the same as the difference when the baseline is not changed. In other words, even if the baseline is changed, only the form of the multiple regression model changes and the meaning is the same.</span>
<span id="cb63-138"><a href="#cb63-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-139"><a href="#cb63-139" aria-hidden="true" tabindex="-1"></a><span class="fu">## (E)</span></span>
<span id="cb63-140"><a href="#cb63-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-141"><a href="#cb63-141" aria-hidden="true" tabindex="-1"></a>Except for the rank variable, multiple regression equations were derived again.</span>
<span id="cb63-142"><a href="#cb63-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-145"><a href="#cb63-145" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-146"><a href="#cb63-146" aria-hidden="true" tabindex="-1"></a>sal.lm.nr<span class="ot">&lt;-</span><span class="fu">lm</span>(salary<span class="sc">~</span>degree<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb63-147"><a href="#cb63-147" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sal.lm.nr)</span>
<span id="cb63-148"><a href="#cb63-148" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-149"><a href="#cb63-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-150"><a href="#cb63-150" aria-hidden="true" tabindex="-1"></a>There are many changes. First of all, Ph.D. ownership acts in the direction of reducing salaries, which is statistically significant (all significance levels are 0.05), and gender has also changed its direction of influence. It was found that women's salary was lower than that of men, but it was not statistically significant. The influence of ysdeg also changed, and when rank was included, this variable had a negative effect on salary, but now it has a positive effect. And this result is also significant. Finally, year did not change the direction of influence, but the coefficient was slightly reduced. be statistically significant as well.</span>
<span id="cb63-151"><a href="#cb63-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-152"><a href="#cb63-152" aria-hidden="true" tabindex="-1"></a><span class="fu">## (F)</span></span>
<span id="cb63-153"><a href="#cb63-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-154"><a href="#cb63-154" aria-hidden="true" tabindex="-1"></a>First, a new variable(ysdeg.dean) with an "old" when ysdeg exceeds 15 and a "new" if not was created.</span>
<span id="cb63-155"><a href="#cb63-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-158"><a href="#cb63-158" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-159"><a href="#cb63-159" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb63-160"><a href="#cb63-160" aria-hidden="true" tabindex="-1"></a>new.sal<span class="ot">&lt;-</span>salary <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">ysdeg.dean =</span> <span class="fu">ifelse</span>(ysdeg<span class="sc">&gt;</span><span class="dv">15</span>, <span class="st">"old"</span>, <span class="st">"new"</span>))</span>
<span id="cb63-161"><a href="#cb63-161" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-162"><a href="#cb63-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-163"><a href="#cb63-163" aria-hidden="true" tabindex="-1"></a>Next, in order to check the multicollinearity, the vif value was checked using the vif function. </span>
<span id="cb63-164"><a href="#cb63-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-167"><a href="#cb63-167" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-168"><a href="#cb63-168" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb63-169"><a href="#cb63-169" aria-hidden="true" tabindex="-1"></a>vif<span class="ot">&lt;-</span><span class="fu">vif</span>(<span class="fu">lm</span>(salary<span class="sc">~</span>degree<span class="sc">+</span>rank<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg.dean, <span class="at">data=</span>new.sal))</span>
<span id="cb63-170"><a href="#cb63-170" aria-hidden="true" tabindex="-1"></a>vif</span>
<span id="cb63-171"><a href="#cb63-171" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-172"><a href="#cb63-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-173"><a href="#cb63-173" aria-hidden="true" tabindex="-1"></a>Here, there is no value over 5, so it seems that there is no variable with strong multicollinearity. Therefore, I derived multiple regression equations including all variables and confirmed the effect of ysdeg reclassified into old and new.</span>
<span id="cb63-174"><a href="#cb63-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-177"><a href="#cb63-177" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-178"><a href="#cb63-178" aria-hidden="true" tabindex="-1"></a>sal.lm.on<span class="ot">&lt;-</span><span class="fu">lm</span>(salary<span class="sc">~</span>degree<span class="sc">+</span>rank<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg.dean, <span class="at">data=</span>new.sal)</span>
<span id="cb63-179"><a href="#cb63-179" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sal.lm.on)</span>
<span id="cb63-180"><a href="#cb63-180" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-181"><a href="#cb63-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-182"><a href="#cb63-182" aria-hidden="true" tabindex="-1"></a>As a result of the confirmation, if all other variables were the same, if ysdeg was old, the salary was 2163.5 lower than if it was new. In addition, the p value of this coefficient is 0.0496, so it is statistically significant at the significance level of 0.05. In other words, the perception that the new dean is more generous in salary is thought to be grounded.</span>
<span id="cb63-183"><a href="#cb63-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-184"><a href="#cb63-184" aria-hidden="true" tabindex="-1"></a><span class="fu"># Question 3</span></span>
<span id="cb63-185"><a href="#cb63-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-188"><a href="#cb63-188" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-189"><a href="#cb63-189" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb63-190"><a href="#cb63-190" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price)</span>
<span id="cb63-191"><a href="#cb63-191" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(house.selling.price)</span>
<span id="cb63-192"><a href="#cb63-192" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(house.selling.price)</span>
<span id="cb63-193"><a href="#cb63-193" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-194"><a href="#cb63-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-195"><a href="#cb63-195" aria-hidden="true" tabindex="-1"></a><span class="fu">## (A)</span></span>
<span id="cb63-196"><a href="#cb63-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-197"><a href="#cb63-197" aria-hidden="true" tabindex="-1"></a>A multiple regression model was derived with Size and New as independent variables and price as dependent variables.</span>
<span id="cb63-198"><a href="#cb63-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-201"><a href="#cb63-201" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-202"><a href="#cb63-202" aria-hidden="true" tabindex="-1"></a>lm.<span class="fl">3.</span>a<span class="ot">&lt;-</span><span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New, <span class="at">data=</span>house.selling.price)</span>
<span id="cb63-203"><a href="#cb63-203" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.<span class="fl">3.</span>a)</span>
<span id="cb63-204"><a href="#cb63-204" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-205"><a href="#cb63-205" aria-hidden="true" tabindex="-1"></a>As a result, as the size increases by one unit, the price increases by 116.1, and in the case of New, the price is 57736.3 higher than that of Old. These are all statistically significant (significance level 0.05).</span>
<span id="cb63-206"><a href="#cb63-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-207"><a href="#cb63-207" aria-hidden="true" tabindex="-1"></a><span class="fu">## (B)</span></span>
<span id="cb63-208"><a href="#cb63-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-209"><a href="#cb63-209" aria-hidden="true" tabindex="-1"></a>For new home: Price = 17505.42 + 116.132*Size</span>
<span id="cb63-210"><a href="#cb63-210" aria-hidden="true" tabindex="-1"></a>For old home; Price = -40230.867 + 116.132*Size</span>
<span id="cb63-211"><a href="#cb63-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-212"><a href="#cb63-212" aria-hidden="true" tabindex="-1"></a>This relationship can also be seen in the figure below.</span>
<span id="cb63-213"><a href="#cb63-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-216"><a href="#cb63-216" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-217"><a href="#cb63-217" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb63-218"><a href="#cb63-218" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(house.selling.price, <span class="fu">aes</span>(Size, Price, <span class="at">color=</span><span class="fu">as.factor</span>(New)),</span>
<span id="cb63-219"><a href="#cb63-219" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Size"</span>,</span>
<span id="cb63-220"><a href="#cb63-220" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Price"</span>) <span class="sc">+</span> </span>
<span id="cb63-221"><a href="#cb63-221" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb63-222"><a href="#cb63-222" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>), <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"Old"</span>, <span class="st">"New"</span>)) <span class="sc">+</span></span>
<span id="cb63-223"><a href="#cb63-223" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="fl">116.132</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">40230.867</span>, <span class="at">color =</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb63-224"><a href="#cb63-224" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="fl">116.132</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">40230.867+57736.283</span>, <span class="at">color=</span><span class="st">"blue"</span>)</span>
<span id="cb63-225"><a href="#cb63-225" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-226"><a href="#cb63-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-227"><a href="#cb63-227" aria-hidden="true" tabindex="-1"></a>In interpretation, regardless of whether the house is new or old, the increase in price is the same as the unit increase in size. However, the intercept of new is 17505.42, which is as large as 57736.283 compared to the intercept of old. That is, the slope of the regression line representing each case is the same, but the new regression line is vertically higher than the old regression line by 57736.283.</span>
<span id="cb63-228"><a href="#cb63-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-229"><a href="#cb63-229" aria-hidden="true" tabindex="-1"></a><span class="fu">## (C)</span></span>
<span id="cb63-230"><a href="#cb63-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-233"><a href="#cb63-233" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-234"><a href="#cb63-234" aria-hidden="true" tabindex="-1"></a>Size<span class="ot">=</span><span class="dv">3000</span></span>
<span id="cb63-235"><a href="#cb63-235" aria-hidden="true" tabindex="-1"></a>new.home.Price <span class="ot">&lt;-</span> <span class="fl">17505.42</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span>Size</span>
<span id="cb63-236"><a href="#cb63-236" aria-hidden="true" tabindex="-1"></a>old.home.Price <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span>Size</span>
<span id="cb63-237"><a href="#cb63-237" aria-hidden="true" tabindex="-1"></a>new.home.Price</span>
<span id="cb63-238"><a href="#cb63-238" aria-hidden="true" tabindex="-1"></a>old.home.Price</span>
<span id="cb63-239"><a href="#cb63-239" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-240"><a href="#cb63-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-241"><a href="#cb63-241" aria-hidden="true" tabindex="-1"></a>According to fitted model, when size is 3000, predicted selling price for a new home is 365901.4 and for an old home is 308165.1</span>
<span id="cb63-242"><a href="#cb63-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-243"><a href="#cb63-243" aria-hidden="true" tabindex="-1"></a><span class="fu">## (D)</span></span>
<span id="cb63-244"><a href="#cb63-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-247"><a href="#cb63-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-248"><a href="#cb63-248" aria-hidden="true" tabindex="-1"></a>lm.<span class="fl">3.</span>d<span class="ot">&lt;-</span><span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">*</span>New, <span class="at">data=</span>house.selling.price)</span>
<span id="cb63-249"><a href="#cb63-249" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.<span class="fl">3.</span>d)</span>
<span id="cb63-250"><a href="#cb63-250" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-251"><a href="#cb63-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-252"><a href="#cb63-252" aria-hidden="true" tabindex="-1"></a>In the regression model that includes the interaction term, the price is rather lowered when new(-78527.5). However, according to the interaction term between Size and new, in the case of new, the sales price increases by 61.916 as the size increases by one unit. Even if it is new, the price is lower than old until it reaches a specific size, and it can be seen that the price of new is higher than old only when it exceeds that specific size.</span>
<span id="cb63-253"><a href="#cb63-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-254"><a href="#cb63-254" aria-hidden="true" tabindex="-1"></a><span class="fu">## (E)</span></span>
<span id="cb63-255"><a href="#cb63-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-256"><a href="#cb63-256" aria-hidden="true" tabindex="-1"></a>For new home: Price = -100755.3 + 166.354*Size</span>
<span id="cb63-257"><a href="#cb63-257" aria-hidden="true" tabindex="-1"></a>For old home; Price = -22227.808 + 104.438*Size</span>
<span id="cb63-258"><a href="#cb63-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-261"><a href="#cb63-261" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-262"><a href="#cb63-262" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(house.selling.price, <span class="fu">aes</span>(Size, Price, <span class="at">color=</span><span class="fu">as.factor</span>(New)),</span>
<span id="cb63-263"><a href="#cb63-263" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Size"</span>,</span>
<span id="cb63-264"><a href="#cb63-264" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Price"</span>) <span class="sc">+</span> </span>
<span id="cb63-265"><a href="#cb63-265" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb63-266"><a href="#cb63-266" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>), <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"Old"</span>, <span class="st">"New"</span>)) <span class="sc">+</span></span>
<span id="cb63-267"><a href="#cb63-267" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="fl">104.438</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">22227.808</span>, <span class="at">color =</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb63-268"><a href="#cb63-268" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="fl">166.354</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">100755.3</span>, <span class="at">color=</span><span class="st">"blue"</span>)</span>
<span id="cb63-269"><a href="#cb63-269" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-270"><a href="#cb63-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-271"><a href="#cb63-271" aria-hidden="true" tabindex="-1"></a>As shown in the figure, in the case of new, the intercept is lower than old, but the slope of new is larger than that of old.</span>
<span id="cb63-272"><a href="#cb63-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-273"><a href="#cb63-273" aria-hidden="true" tabindex="-1"></a><span class="fu">## (F)</span></span>
<span id="cb63-274"><a href="#cb63-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-277"><a href="#cb63-277" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-278"><a href="#cb63-278" aria-hidden="true" tabindex="-1"></a>Size<span class="ot">=</span><span class="dv">3000</span></span>
<span id="cb63-279"><a href="#cb63-279" aria-hidden="true" tabindex="-1"></a>new.home.Price<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">100755.3</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span>Size</span>
<span id="cb63-280"><a href="#cb63-280" aria-hidden="true" tabindex="-1"></a>old.home.Price<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span>Size</span>
<span id="cb63-281"><a href="#cb63-281" aria-hidden="true" tabindex="-1"></a>new.home.Price<span class="fl">.2</span></span>
<span id="cb63-282"><a href="#cb63-282" aria-hidden="true" tabindex="-1"></a>old.home.Price<span class="fl">.2</span></span>
<span id="cb63-283"><a href="#cb63-283" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-284"><a href="#cb63-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-285"><a href="#cb63-285" aria-hidden="true" tabindex="-1"></a>Predicted selling price of new home is 398306.7 and of new home is 291086.2.</span>
<span id="cb63-286"><a href="#cb63-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-287"><a href="#cb63-287" aria-hidden="true" tabindex="-1"></a><span class="fu">## (G)</span></span>
<span id="cb63-288"><a href="#cb63-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-291"><a href="#cb63-291" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-292"><a href="#cb63-292" aria-hidden="true" tabindex="-1"></a>Size<span class="ot">=</span><span class="dv">1500</span></span>
<span id="cb63-293"><a href="#cb63-293" aria-hidden="true" tabindex="-1"></a>new.home.Price<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">100755.3</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span>Size</span>
<span id="cb63-294"><a href="#cb63-294" aria-hidden="true" tabindex="-1"></a>old.home.Price<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span>Size</span>
<span id="cb63-295"><a href="#cb63-295" aria-hidden="true" tabindex="-1"></a>new.home.Price<span class="fl">.2</span></span>
<span id="cb63-296"><a href="#cb63-296" aria-hidden="true" tabindex="-1"></a>old.home.Price<span class="fl">.2</span></span>
<span id="cb63-297"><a href="#cb63-297" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-298"><a href="#cb63-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-299"><a href="#cb63-299" aria-hidden="true" tabindex="-1"></a>Predicted selling price of new home is 148775.7 and of new home is 134429.2. The price difference is smaller than when the size is 3000. </span>
<span id="cb63-300"><a href="#cb63-300" aria-hidden="true" tabindex="-1"></a>In the case of new, the slope of the model is larger than that of old, so the larger the size, the higher the price of new. In other words, as the size increases, the price difference between new and old will gradually increase, which can be seen from the regression equation between the two and the graph above.</span>
<span id="cb63-301"><a href="#cb63-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-302"><a href="#cb63-302" aria-hidden="true" tabindex="-1"></a><span class="fu">## (H)</span></span>
<span id="cb63-303"><a href="#cb63-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-304"><a href="#cb63-304" aria-hidden="true" tabindex="-1"></a>Looking at the r-square value of each model, the r-square value of the model including the interaction term is larger(model with interaction term: 0.7443, model without it: 0.7226). Even looking at the adjusted r-square value that corrects the increased amount of explanation as the variable increasesr(model with interaction term: 0.7363, model without it: 0.7169), it can be said that the explanatory power of the model including the interaction term is higher.</span>
<span id="cb63-305"><a href="#cb63-305" aria-hidden="true" tabindex="-1"></a>However, which model to use and prefer is not determined simply by these explanations. In this case, it was easy to compare the cases of new and old by simply modifying the expression, but if the number of variables increases or there are more than three categories of nominal variables, it will be increasingly difficult to derive or interpret the regression model.</span>
<span id="cb63-306"><a href="#cb63-306" aria-hidden="true" tabindex="-1"></a>In other words, in selecting models and variables, various variables such as interpretability as well as simple explanatory power should be considered.</span>
<span id="cb63-307"><a href="#cb63-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-308"><a href="#cb63-308" aria-hidden="true" tabindex="-1"></a>For this case, I prefer a model with interaction terms. It is interesting that the older the house, the smaller the price increase due to the increase in its area, in that the two variables interact to change the influence of the variable.</span>
<span id="cb63-309"><a href="#cb63-309" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>