<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Akhilesh Kumar">
<meta name="dcterms.date" content="2023-04-23">
<meta name="description" content="The fourth homework">

<title>Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="styles.css">
<meta name="twitter:title" content="Homework 4">
<meta name="twitter:description" content="The fourth homework">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/HW4_AkhileshKumar_files/figure-html/unnamed-chunk-5-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">A</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">B</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">C</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#a-1" id="toc-a-1" class="nav-link" data-scroll-target="#a-1">A</a></li>
  <li><a href="#b-1" id="toc-b-1" class="nav-link" data-scroll-target="#b-1">B</a></li>
  <li><a href="#c-1" id="toc-c-1" class="nav-link" data-scroll-target="#c-1">C</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">D</a></li>
  <li><a href="#e" id="toc-e" class="nav-link" data-scroll-target="#e">E</a></li>
  <li><a href="#f" id="toc-f" class="nav-link" data-scroll-target="#f">F</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  <li><a href="#a-2" id="toc-a-2" class="nav-link" data-scroll-target="#a-2">A</a></li>
  <li><a href="#b-2" id="toc-b-2" class="nav-link" data-scroll-target="#b-2">B</a></li>
  <li><a href="#c-2" id="toc-c-2" class="nav-link" data-scroll-target="#c-2">C</a></li>
  <li><a href="#d-1" id="toc-d-1" class="nav-link" data-scroll-target="#d-1">D</a></li>
  <li><a href="#e-1" id="toc-e-1" class="nav-link" data-scroll-target="#e-1">E</a></li>
  <li><a href="#f-1" id="toc-f-1" class="nav-link" data-scroll-target="#f-1">F</a></li>
  <li><a href="#g" id="toc-g" class="nav-link" data-scroll-target="#g">G</a></li>
  <li><a href="#h" id="toc-h" class="nav-link" data-scroll-target="#h">H</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 4</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Homework3</div>
    <div class="quarto-category">Akhilesh</div>
  </div>
  </div>

<div>
  <div class="description">
    The fourth homework
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Akhilesh Kumar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 23, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.0.10     ✔ readr     2.1.4 
✔ forcats   1.0.0      ✔ stringr   1.5.0 
✔ ggplot2   3.4.1      ✔ tibble    3.1.8 
✔ lubridate 1.9.2      ✔ tidyr     1.2.1 
✔ purrr     0.3.5      
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car
Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some

Loading required package: effects
lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'

The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<p>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + (53.8 * x1) + (2.84* x2).</p>
</section>
<section id="a" class="level2">
<h2 class="anchored" data-anchor-id="a">A</h2>
<p>A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">=</span> <span class="dv">1240</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">=</span> <span class="dv">18000</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>Predicted_selling_price <span class="ot">&lt;-</span>  <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> (<span class="fl">53.8</span> <span class="sc">*</span> x1) <span class="sc">+</span> (<span class="fl">2.84</span> <span class="sc">*</span> x2)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>Predicted_selling_price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107296</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Actual_selling_price <span class="ot">=</span> <span class="dv">145000</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>Residual <span class="ot">&lt;-</span> Actual_selling_price<span class="sc">-</span>Predicted_selling_price</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>Residual</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37704</code></pre>
</div>
</div>
<p>Based on the given data, the prediction equation suggests that a home with 1240 square feet on a lot of 18,000 square feet in Jacksonville, Florida should have a selling price of $107,296. However, the actual selling price of this particular home was $145,000, which is higher than the predicted selling price. This results in a residual of $37,704, indicating that the prediction equation underestimated the selling price of this home.</p>
<p>This suggests that while the prediction equation provides some insight into the selling prices of homes in Jacksonville, Florida based on size of the home and lot size, it is not a perfect predictor. Other factors, such as the condition of the home, location, and other amenities, may also play a role in determining the selling price of a home. Therefore, it is important to consider multiple factors when predicting the selling price of a home in Jacksonville, Florida.</p>
</section>
<section id="b" class="level2">
<h2 class="anchored" data-anchor-id="b">B</h2>
<p>Since the prediction equation for home selling price is ŷ = −10,536 + (53.8 * x1) + (2.84 * x2), where x1 represents the home size and x2 represents the lot size, the impact of changing home size on the selling price while holding lot size constant, can be determined.</p>
<p>Specifically, for each additional square foot of home size (x1), the house selling price is expected to increase by 53.8 dollars, assuming lot size is fixed. This is because the coefficient of x1 in the equation is 53.8.</p>
<p>The impact of lot size (x2) on the selling price is also accounted for in the equation, with a coefficient of 2.84. However, if lot size is held constant, then this coefficient does not affect the output, so only coefficient of x1 is required to be considered .</p>
<p>Therefore, if the home size is increased by one unit (representing one additional square foot), the predicted selling price would increase by 53.8 units, assuming the lot size remains constant.</p>
</section>
<section id="c" class="level2">
<h2 class="anchored" data-anchor-id="c">C</h2>
<p>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</p>
<p>For fixed home size, 53.8 * 1 = 2.84x2</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>x2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.94366</code></pre>
</div>
</div>
<p>It can be observed that the predicted selling price of a house is estimated to increase by approximately $3 for every additional square foot of lot size, assuming the house size is fixed. Therefore, to achieve a similar impact on the predicted selling price as an increment of one square foot in house size, lot size should be increased by roughly 19 square feet. This is because every one-square-foot increase in house size is predicted to increase the selling price by around $53.8, which is equivalent to an increase of approximately 18.94 square feet in lot size. Therefore, an increase in lot size of about 18.94 square feet would have an identical effect on the predicted selling price as an increase of one square foot in home size.</p>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</p>
</section>
<section id="a-1" class="level2">
<h2 class="anchored" data-anchor-id="a-1">A</h2>
<p>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"salary"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(salary, <span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> salary, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Salary"</span>, <span class="at">title =</span> <span class="st">"Salary Comparison between Male &amp; Female"</span>) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"navyblue"</span>, <span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>), </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"navyblue"</span>, <span class="at">size =</span> <span class="dv">10</span>), </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"navyblue"</span>, <span class="at">size =</span> <span class="dv">8</span>), </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"navyblue"</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FF5C35"</span>, <span class="st">"#00B945"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HW4_AkhileshKumar_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize salary data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>summary_salary <span class="ot">&lt;-</span> salary <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">average_salary =</span> <span class="fu">mean</span>(salary), <span class="at">min_salary =</span> <span class="fu">min</span>(salary), <span class="at">max_salary =</span> <span class="fu">max</span>(salary))</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create salary comparison plot</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summary_salary, <span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> average_salary)) <span class="sc">+</span>   </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> min_salary, <span class="at">ymax =</span> max_salary), <span class="at">color =</span> <span class="st">"#32CD32"</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Salary"</span>, <span class="at">title =</span> <span class="st">"Salary Comparison between Male &amp; Female"</span>) <span class="sc">+</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y =</span> max_salary, <span class="at">label =</span> max_salary), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"#000080"</span>, <span class="at">hjust =</span> <span class="sc">-</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y =</span> min_salary, <span class="at">label =</span> min_salary), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"#000080"</span>, <span class="at">hjust =</span> <span class="sc">-</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(average_salary, <span class="at">digits =</span> <span class="dv">2</span>)), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"#000080"</span>, <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#33475b"</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#33475b"</span>, <span class="at">size =</span> <span class="dv">8</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#33475b"</span>, <span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#33475b"</span>, <span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#000080"</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HW4_AkhileshKumar_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based solely on the visuals, it is clear that the average salary for men and women differ. However, it is uncertain if this difference is statistically significant. Additionally, while men generally have a higher mean salary, there is one outlier female who earns the most, indicating a wider salary range for women. Nonetheless, further analysis is necessary to determine whether these findings are significant.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t.test to text the null hypothesis that men and women make the same amount. </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary<span class="sc">~</span>sex, <span class="at">data =</span> salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by sex
t = 1.7744, df = 21.591, p-value = 0.09009
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -567.8539 7247.1471
sample estimates:
  mean in group Male mean in group Female 
            24696.79             21357.14 </code></pre>
</div>
</div>
<p>Based on a Welch Two Sample t-test, I found that the mean salary for men is higher than women. However, the p-value of 0.09 is higher than a significance level of 5%, indicating that the null hypothesis of ‘the mean salary for men and women are the same’, cannot be rejected. Therefore, It cannot be concluded that there is a significant difference in the mean salary between men and women.</p>
</section>
<section id="b-1" class="level2">
<h2 class="anchored" data-anchor-id="b-1">B</h2>
<p>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ., data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept) 14134.4059 17357.68946
degreePhD    -663.2482  3440.47485
rankAssoc    2985.4107  7599.31080
rankProf     8396.1546 13841.37340
sexFemale    -697.8183  3030.56452
year          285.1433   667.47476
ysdeg        -280.6397    31.49105</code></pre>
</div>
</div>
<p>The linear regression analysis shows that there is a significant relationship between salary and the variables degree, rank, sex, year, and years since degree completion. However, the p-value for the variable sex is 0.214, which is higher than the significance level of 0.05, indicating that null hypothesis: that there is no difference in mean salary between males and females, cannot be rejected. Further, at a 95% confidence interval, the difference in mean salary between males and females ranges from -$697.82 to $3,030.56, suggesting that 95% of the time, males will make between $697.82 more and $3,030.56 less than females.</p>
</section>
<section id="c-1" class="level2">
<h2 class="anchored" data-anchor-id="c-1">C</h2>
<p>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables</p>
<p><strong>degreePhD:</strong></p>
<ul>
<li>The coefficient estimate is 1388.61 with a standard error of 1018.75.</li>
<li>The p-value is 0.180, which is greater than 0.05, indicating that the coefficient for “degreePhD” is not statistically significant.</li>
<li>This means that there is insufficient evidence to suggest that having a PhD degree has a statistically significant effect on salary, after accounting for other variables in the model. This suggests that having a PhD degree does not have a significant effect on salary after accounting for the other variables in the model.</li>
</ul>
<p><strong>rankAssoc:</strong></p>
<ul>
<li>The coefficient estimate is 5292.36 with a standard error of 1145.40.</li>
<li>The p-value is 3.22e-05, which is less than 0.05, indicating that the coefficient for “rankAssoc” is statistically significant.</li>
<li>This means that having an associate professor rank is associated with a salary increase of $5292.36 on average, compared to assistant professors, after controlling for the other variables in the model.</li>
</ul>
<p><strong>rankProf:</strong></p>
<ul>
<li>The coefficient estimate is 11118.76 with a standard error of 1351.77.</li>
<li>The p-value is 1.62e-10, which is less than 0.05, indicating that the coefficient for “rankProf” is statistically significant.</li>
<li>This means that having a professor rank is associated with a salary increase of $11118.76 on average, compared to assistant professors, after controlling for the other variables in the model.</li>
</ul>
<p><strong>sexFemale:</strong></p>
<ul>
<li>The coefficient estimate is 1166.37 with a standard error of 925.57.</li>
<li>The p-value is 0.214, which is greater than 0.05, indicating that the coefficient for “sexFemale” is not statistically significant.</li>
<li>This suggests that gender does not have a significant effect on salary after accounting for the other variables in the model.</li>
</ul>
<p><strong>year:</strong></p>
<ul>
<li>The coefficient estimate is 476.31 with a standard error of 94.91.</li>
<li>The p-value is 8.65e-06, which is less than 0.05, indicating that the coefficient for “year” is statistically significant.</li>
<li>This means that for each additional year, there is an increase in salary of $476.31 on average, after controlling for the other variables in the model.</li>
</ul>
<p><strong>ysdeg:</strong></p>
<ul>
<li>The coefficient estimate is -124.57 with a standard error of 77.49.</li>
<li>The p-value is 0.115, which is greater than 0.05, indicating that the coefficient for “ysdeg” is not statistically significant.</li>
<li>This suggests that the years since receiving a degree does not have a significant effect on salary after accounting for the other variables in the model.</li>
</ul>
<p>Overall, the model shows that rank and years of experience are the most significant predictors of salary in this dataset.</p>
</section>
<section id="d" class="level2">
<h2 class="anchored" data-anchor-id="d">D</h2>
<p>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">'Prof'</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "degree" "rank"   "sex"    "year"   "ysdeg"  "salary"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> ., salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ., data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  26864.81    1375.29  19.534  &lt; 2e-16 ***
degreePhD     1388.61    1018.75   1.363    0.180    
rankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***
rankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***
sexFemale     1166.37     925.57   1.260    0.214    
year           476.31      94.91   5.018 8.65e-06 ***
ysdeg         -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>After changing the baseline category for the rank variable, an Associate can expect a 6483.0 dollar decrease in salary compared to Professor, while a Assistant can expect a 11890.3 dollar salary decrease compared to Professor. Both ranks have significance levels well below 0.05 and it can be determined that rank does have a statistically significant impact on salary.</p>
<p>Interpreting the coefficients related to rank after changing the baseline category to “Prof”, I see that the coefficients for both rankAsst and rankAssoc are negative. This means that the average salary for assistant professors and associate professors is lower than the average salary for full professors, holding all other variables constant.</p>
<p>The coefficient for rankAsst is -11118.76, indicating that assistant professors earn, on average, $11,118.76 less than full professors when all other variables are held constant. The coefficient for rankAssoc is -5826.40, indicating that associate professors earn, on average, $5,826.40 less than full professors when all other variables are held constant.</p>
<p>The interpretation of these coefficients assumes that the other variables included in the model (degreePhD, sexFemale, year, and ysdeg) are held constant.</p>
</section>
<section id="e" class="level2">
<h2 class="anchored" data-anchor-id="e">E</h2>
<p>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “<a href="#a">a</a> variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.Exclude the variable rank, refit, and summarize how your findings changed, if they did</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
year          351.97     142.48   2.470 0.017185 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<ul>
<li><p>The coefficient for the predictor variable degreePhD is -3299.35, with a standard error of 1302.52, and a p-value of 0.014704, indicating a significant negative relationship between having a PhD degree and salary.</p></li>
<li><p>The coefficient for the predictor variable sexFemale is -1286.54, with a standard error of 1313.09, and a p-value of 0.332209, indicating that there is no significant difference in salary between male and female employees.</p></li>
<li><p>The coefficient for the predictor variable year is 351.97, with a standard error of 142.48, and a p-value of 0.017185, indicating a significant positive relationship between the year of employment and salary.</p></li>
<li><p>The coefficient for the predictor variable ysdeg is 339.40, with a standard error of 80.62, and a p-value of 0.000114, indicating a significant positive relationship between the number of years of service and salary.</p></li>
</ul>
<p>The R-squared value of the model is 0.6312, indicating that the predictors explain 63.12% of the variability in salary. The adjusted R-squared value, which adjusts for the number of predictors in the model, is 0.5998.</p>
<p>The F-statistic of the model is 20.11 with 4 and 47 degrees of freedom, and the p-value is 1.048e-09, indicating that the model is a good fit for the data and that at least one of the predictors is significantly related to salary.</p>
</section>
<section id="f" class="level2">
<h2 class="anchored" data-anchor-id="f">F</h2>
<p>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</p>
<p>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>NewDean <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> rank <span class="sc">+</span> degree <span class="sc">+</span> year<span class="sc">+</span> NewDean, <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sex + rank + degree + year + NewDean, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-3403.3 -1387.0  -167.0   528.2  9233.8 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  24425.32    1107.52  22.054  &lt; 2e-16 ***
sexFemale      907.14     840.54   1.079   0.2862    
rankAsst    -11096.95    1191.00  -9.317 4.54e-12 ***
rankAssoc    -6124.28    1028.58  -5.954 3.65e-07 ***
degreePhD      818.93     797.48   1.027   0.3100    
year           434.85      78.89   5.512 1.65e-06 ***
NewDean       2163.46    1072.04   2.018   0.0496 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2362 on 45 degrees of freedom
Multiple R-squared:  0.8594,    Adjusted R-squared:  0.8407 
F-statistic: 45.86 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>To test the hypothesis, a dummy variable (NewDean) was created. It is coded as 1 if ysdeg is 15 years or less, and 0 otherwise.</p>
<p>These correlations indicate that there is a relationship between the variables and they might have a similar impact on the response variable (salary). To address this issue, the variable ysdeg was removed due to its overlap with NewDean variable (since the NewDean variable was based on ysdeg).</p>
<p>Then, I fit a new regression model, including the variables of sex, rank, degree, year and NewDean. According to the regression results, employees hired under the new dean are expected to earn $2163.46 more than those hired prior to the new dean’s tenure. However, this correlation is only significant at the 0.0496 level. While it is statistically significant, it is not the most powerful predictor of salary.</p>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>house.selling.price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["case"],"name":[1],"type":["int"],"align":["right"]},{"label":["Taxes"],"name":[2],"type":["int"],"align":["right"]},{"label":["Beds"],"name":[3],"type":["int"],"align":["right"]},{"label":["Baths"],"name":[4],"type":["int"],"align":["right"]},{"label":["New"],"name":[5],"type":["int"],"align":["right"]},{"label":["Price"],"name":[6],"type":["int"],"align":["right"]},{"label":["Size"],"name":[7],"type":["int"],"align":["right"]}],"data":[{"1":"1","2":"3104","3":"4","4":"2","5":"0","6":"279900","7":"2048"},{"1":"2","2":"1173","3":"2","4":"1","5":"0","6":"146500","7":"912"},{"1":"3","2":"3076","3":"4","4":"2","5":"0","6":"237700","7":"1654"},{"1":"4","2":"1608","3":"3","4":"2","5":"0","6":"200000","7":"2068"},{"1":"5","2":"1454","3":"3","4":"3","5":"0","6":"159900","7":"1477"},{"1":"6","2":"2997","3":"3","4":"2","5":"1","6":"499900","7":"3153"},{"1":"7","2":"4054","3":"3","4":"2","5":"0","6":"265500","7":"1355"},{"1":"8","2":"3002","3":"3","4":"2","5":"1","6":"289900","7":"2075"},{"1":"9","2":"6627","3":"5","4":"4","5":"0","6":"587000","7":"3990"},{"1":"10","2":"320","3":"3","4":"2","5":"0","6":"70000","7":"1160"},{"1":"11","2":"630","3":"3","4":"2","5":"0","6":"64500","7":"1220"},{"1":"12","2":"1780","3":"3","4":"2","5":"0","6":"167000","7":"1690"},{"1":"13","2":"1630","3":"3","4":"2","5":"0","6":"114600","7":"1380"},{"1":"14","2":"1530","3":"3","4":"2","5":"0","6":"103000","7":"1590"},{"1":"15","2":"930","3":"3","4":"1","5":"0","6":"101000","7":"1050"},{"1":"16","2":"590","3":"2","4":"1","5":"0","6":"70000","7":"770"},{"1":"17","2":"1050","3":"3","4":"2","5":"0","6":"85000","7":"1410"},{"1":"18","2":"20","3":"3","4":"1","5":"0","6":"22500","7":"1060"},{"1":"19","2":"870","3":"2","4":"2","5":"0","6":"90000","7":"1300"},{"1":"20","2":"1320","3":"3","4":"2","5":"0","6":"133000","7":"1500"},{"1":"21","2":"1350","3":"2","4":"1","5":"0","6":"90500","7":"820"},{"1":"22","2":"5616","3":"4","4":"3","5":"1","6":"577500","7":"3949"},{"1":"23","2":"680","3":"2","4":"1","5":"0","6":"142500","7":"1170"},{"1":"24","2":"1840","3":"3","4":"2","5":"0","6":"160000","7":"1500"},{"1":"25","2":"3680","3":"4","4":"2","5":"0","6":"240000","7":"2790"},{"1":"26","2":"1660","3":"3","4":"1","5":"0","6":"87000","7":"1030"},{"1":"27","2":"1620","3":"3","4":"2","5":"0","6":"118600","7":"1250"},{"1":"28","2":"3100","3":"3","4":"2","5":"0","6":"140000","7":"1760"},{"1":"29","2":"2070","3":"2","4":"3","5":"0","6":"148000","7":"1550"},{"1":"30","2":"830","3":"3","4":"2","5":"0","6":"69000","7":"1120"},{"1":"31","2":"2260","3":"4","4":"2","5":"0","6":"176000","7":"2000"},{"1":"32","2":"1760","3":"3","4":"1","5":"0","6":"86500","7":"1350"},{"1":"33","2":"2750","3":"3","4":"2","5":"1","6":"180000","7":"1840"},{"1":"34","2":"2020","3":"4","4":"2","5":"0","6":"179000","7":"2510"},{"1":"35","2":"4900","3":"3","4":"3","5":"1","6":"338000","7":"3110"},{"1":"36","2":"1180","3":"4","4":"2","5":"0","6":"130000","7":"1760"},{"1":"37","2":"2150","3":"3","4":"2","5":"0","6":"163000","7":"1710"},{"1":"38","2":"1600","3":"2","4":"1","5":"0","6":"125000","7":"1110"},{"1":"39","2":"1970","3":"3","4":"2","5":"0","6":"100000","7":"1360"},{"1":"40","2":"2060","3":"3","4":"1","5":"0","6":"100000","7":"1250"},{"1":"41","2":"1980","3":"3","4":"1","5":"0","6":"100000","7":"1250"},{"1":"42","2":"1510","3":"3","4":"2","5":"0","6":"146500","7":"1480"},{"1":"43","2":"1710","3":"3","4":"2","5":"0","6":"144900","7":"1520"},{"1":"44","2":"1590","3":"3","4":"2","5":"0","6":"183000","7":"2020"},{"1":"45","2":"1230","3":"3","4":"2","5":"0","6":"69900","7":"1010"},{"1":"46","2":"1510","3":"2","4":"2","5":"0","6":"60000","7":"1640"},{"1":"47","2":"1450","3":"2","4":"2","5":"0","6":"127000","7":"940"},{"1":"48","2":"970","3":"3","4":"2","5":"0","6":"86000","7":"1580"},{"1":"49","2":"150","3":"2","4":"2","5":"0","6":"50000","7":"860"},{"1":"50","2":"1470","3":"3","4":"2","5":"0","6":"137000","7":"1420"},{"1":"51","2":"1850","3":"3","4":"2","5":"0","6":"121300","7":"1270"},{"1":"52","2":"820","3":"2","4":"1","5":"0","6":"81000","7":"980"},{"1":"53","2":"2050","3":"4","4":"2","5":"0","6":"188000","7":"2300"},{"1":"54","2":"710","3":"3","4":"2","5":"0","6":"85000","7":"1430"},{"1":"55","2":"1280","3":"3","4":"2","5":"0","6":"137000","7":"1380"},{"1":"56","2":"1360","3":"3","4":"2","5":"0","6":"145000","7":"1240"},{"1":"57","2":"830","3":"3","4":"2","5":"0","6":"69000","7":"1120"},{"1":"58","2":"800","3":"3","4":"2","5":"0","6":"109300","7":"1120"},{"1":"59","2":"1220","3":"3","4":"2","5":"0","6":"131500","7":"1900"},{"1":"60","2":"3360","3":"4","4":"3","5":"0","6":"200000","7":"2430"},{"1":"61","2":"210","3":"3","4":"2","5":"0","6":"81900","7":"1080"},{"1":"62","2":"380","3":"2","4":"1","5":"0","6":"91200","7":"1350"},{"1":"63","2":"1920","3":"4","4":"3","5":"0","6":"124500","7":"1720"},{"1":"64","2":"4350","3":"3","4":"3","5":"0","6":"225000","7":"4050"},{"1":"65","2":"1510","3":"3","4":"2","5":"0","6":"136500","7":"1500"},{"1":"66","2":"4154","3":"3","4":"3","5":"0","6":"381000","7":"2581"},{"1":"67","2":"1976","3":"3","4":"2","5":"1","6":"250000","7":"2120"},{"1":"68","2":"3605","3":"3","4":"3","5":"1","6":"354900","7":"2745"},{"1":"69","2":"1400","3":"3","4":"2","5":"0","6":"140000","7":"1520"},{"1":"70","2":"790","3":"2","4":"2","5":"0","6":"89900","7":"1280"},{"1":"71","2":"1210","3":"3","4":"2","5":"0","6":"137000","7":"1620"},{"1":"72","2":"1550","3":"3","4":"2","5":"0","6":"103000","7":"1520"},{"1":"73","2":"2800","3":"3","4":"2","5":"0","6":"183000","7":"2030"},{"1":"74","2":"2560","3":"3","4":"2","5":"0","6":"140000","7":"1390"},{"1":"75","2":"1390","3":"4","4":"2","5":"0","6":"160000","7":"1880"},{"1":"76","2":"5443","3":"3","4":"2","5":"0","6":"434000","7":"2891"},{"1":"77","2":"2850","3":"2","4":"1","5":"0","6":"130000","7":"1340"},{"1":"78","2":"2230","3":"2","4":"2","5":"0","6":"123000","7":"940"},{"1":"79","2":"20","3":"2","4":"1","5":"0","6":"21000","7":"580"},{"1":"80","2":"1510","3":"4","4":"2","5":"0","6":"85000","7":"1410"},{"1":"81","2":"710","3":"3","4":"2","5":"0","6":"69900","7":"1150"},{"1":"82","2":"1540","3":"3","4":"2","5":"0","6":"125000","7":"1380"},{"1":"83","2":"1780","3":"3","4":"2","5":"1","6":"162600","7":"1470"},{"1":"84","2":"2920","3":"2","4":"2","5":"1","6":"156900","7":"1590"},{"1":"85","2":"1710","3":"3","4":"2","5":"1","6":"105900","7":"1200"},{"1":"86","2":"1880","3":"3","4":"2","5":"0","6":"167500","7":"1920"},{"1":"87","2":"1680","3":"3","4":"2","5":"0","6":"151800","7":"2150"},{"1":"88","2":"3690","3":"5","4":"3","5":"0","6":"118300","7":"2200"},{"1":"89","2":"900","3":"2","4":"2","5":"0","6":"94300","7":"860"},{"1":"90","2":"560","3":"3","4":"1","5":"0","6":"93900","7":"1230"},{"1":"91","2":"2040","3":"4","4":"2","5":"0","6":"165000","7":"1140"},{"1":"92","2":"4390","3":"4","4":"3","5":"1","6":"285000","7":"2650"},{"1":"93","2":"690","3":"3","4":"1","5":"0","6":"45000","7":"1060"},{"1":"94","2":"2100","3":"3","4":"2","5":"0","6":"124900","7":"1770"},{"1":"95","2":"2880","3":"4","4":"2","5":"0","6":"147000","7":"1860"},{"1":"96","2":"990","3":"2","4":"2","5":"0","6":"176000","7":"1060"},{"1":"97","2":"3030","3":"3","4":"2","5":"0","6":"196500","7":"1730"},{"1":"98","2":"1580","3":"3","4":"2","5":"0","6":"132200","7":"1370"},{"1":"99","2":"1770","3":"3","4":"2","5":"0","6":"88400","7":"1560"},{"1":"100","2":"1430","3":"3","4":"2","5":"0","6":"127200","7":"1340"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</section>
<section id="a-2" class="level2">
<h2 class="anchored" data-anchor-id="a-2">A</h2>
<p>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The coefficient of Size is estimated to be 116.132, which means that for each unit increase in Size, it is expected that the Price would increase by an average of 116.132. The t-value of 13.204 is highly significant (p &lt; 0.001), indicating that the coefficient is significantly different from zero. Therefore, the null hypothesis that there is no linear relationship between Size and Price is rejected.</p>
<p>The coefficient of New is estimated to be 57736.283, which means that its price would be $57736.283 higher than a house that is not new, all other things being equal. The t-value of 3.095 is also significant (p = 0.00257), indicating that the coefficient is significantly different from zero. Therefore, the null hypothesis that there is no linear relationship between New and Price, is rejected.</p>
<p>The intercept coefficient is estimated to be -40230.867, which is the expected value of Price when both Size and New are equal to zero. However, since there are no houses with zero Size and zero New, this value does not have any practical meaning in this context.</p>
<p>The adjusted R-squared of this model is 0.7169, which means that approximately 71.7% of the variability in Price can be explained by Size and New. The F-statistic of 126.3 with p-value &lt; 2.2e-16 indicates that the model as a whole is statistically significant, and that the predictor variables are jointly significant in explaining the variation in the response variable.</p>
</section>
<section id="b-2" class="level2">
<h2 class="anchored" data-anchor-id="b-2">B</h2>
<p>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes</p>
<p>Based on the above regression model, the prediction equation for the selling price of a home would be selling price = -40230.867 + 116.132 * size + 57736.283 * new where size = the size of the home and new = 1 if the home is new or new = 0 if the home is not new.</p>
<ul>
<li><p>For new homes, z = 1 so the prediction equation for the selling price of a new home is selling price = -40230.867 + 116.132 * size + 57736.283 or selling price = 17505.416 + 116.132 * size</p></li>
<li><p>For old homes, z = 0 so the prediction equation for the selling price of a not-new home is selling price = -40230.867 + 116.132 * size + 0 or selling price = -40230.867 + 116.132 * size</p></li>
</ul>
<p>Based on the regression analysis and the obtained equations, we can infer that the variables Size and New have a positive influence on the selling price of a home. The coefficient of Size denotes that there is a linear association between the size of a home and its selling prce. This implies that for every 1 sq foot increase in the size of a home, we can expect an estimated increase of ~$116 in the selling price, while holding all other factors constant. On the other hand, the coefficient of New indicates that new homes, on average, are sold for ~$57,736 more than old homes of the same size.</p>
<p>Since there is no interaction term in the model, the impact of each variable is analyzed separately. This suggests that the effect of Size on the selling price is consistent for both new and old homes. Moreover, both Size and New have been found to be statistically significant, respectively, based on their small p-values.</p>
</section>
<section id="c-2" class="level2">
<h2 class="anchored" data-anchor-id="c-2">C</h2>
<p>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>Size <span class="ot">&lt;-</span> <span class="dv">3000</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co">#predicted selling price for a new home</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>New_Price <span class="ot">=</span> <span class="fl">17505.416</span> <span class="sc">+</span> (<span class="fl">116.132</span> <span class="sc">*</span> Size)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="co">#predicted selling price for a not new home</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>Old_Price <span class="ot">=</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> (<span class="fl">116.132</span> <span class="sc">*</span> Size)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>New_Price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 365901.4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>Old_Price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 308165.1</code></pre>
</div>
</div>
<p>Based on the predictive formulas from the regression model, the predicted selling price for a new home of 3000 sq. feet is $365,901 and the predicted selling price for a not-new home of the same size is $308,165.</p>
</section>
<section id="d-1" class="level2">
<h2 class="anchored" data-anchor-id="d-1">D</h2>
<p>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size<span class="sc">*</span>New, <span class="at">data =</span> house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size * New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>The new model includes an interaction term between Size and New, allowing for the possibility that the effect of Size on Price differs depending on whether a home is new or not.</li>
<li>The coefficient for the interaction term is positive and statistically significant (p &lt; 0.01), indicating that the effect of Size on Price is stronger for new homes compared to not-new homes.</li>
<li>The coefficient for New is negative but not statistically significant (p &gt; 0.05), suggesting that being a new home does not have a significant impact on Price when Size and the interaction term are taken into account.</li>
<li>The coefficient for Size is positive and highly significant (p &lt; 0.001), indicating that increasing the size of a home leads to a higher predicted selling price, all else being equal.</li>
<li>The adjusted R-squared for the model is 0.7363, indicating that the model explains around 74% of the variation in selling prices, after accounting for the effects of Size, New, and the interaction term.</li>
</ul>
</section>
<section id="e-1" class="level2">
<h2 class="anchored" data-anchor-id="e-1">E</h2>
<p>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</p>
<p>The predicted selling price, based on the new regression that includes interaction between Size and Newness, would look like:</p>
<p>House_Price = -22227.808 + 104.438 * Size - 78527.50 * z + 61.916 * Size * z</p>
<p>Where Size = the size of the home and z = 1 if the home is new or z = 0 if the home is not new.</p>
<p>New_Price = -22227.808 + 104.438 * Size - 78527.50 * 1 + 61.916 * Size * 1</p>
<pre><code>      = -22227.808 + 104.438 * Size - 78527.50  + 61.916 * Size
      
      = -100755 + 166.354 * Size</code></pre>
<p>Old_Price = -22227.808 + 104.438 * Size - 78527.50 * 0 + 61.916 * Size * 0</p>
<pre><code>      = -22227.808 + 104.438 * Size</code></pre>
</section>
<section id="f-1" class="level2">
<h2 class="anchored" data-anchor-id="f-1">F</h2>
<p>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>Size <span class="ot">&lt;-</span> <span class="dv">3000</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># predicted selling price for a new home</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>New_Price <span class="ot">=</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span> <span class="sc">*</span> Size <span class="sc">-</span> <span class="fl">78527.50</span> <span class="sc">*</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fl">61.916</span> <span class="sc">*</span> Size <span class="sc">*</span> <span class="dv">1</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co">#predicted selling price for a not new home</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>Old_Price <span class="ot">=</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span> <span class="sc">*</span> Size</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>New_Price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 398306.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>Old_Price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 291086.2</code></pre>
</div>
</div>
<p>Based on the predictive formulas from the regression model, the predicted selling price for a new home that is 3000 sq. feet is $398,306.70 and the predicted selling price for a not new home of the same size is $291,086.20.</p>
</section>
<section id="g" class="level2">
<h2 class="anchored" data-anchor-id="g">G</h2>
<p>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>Size <span class="ot">&lt;-</span> <span class="dv">1500</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># predicted selling price for a new home</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>New_Price <span class="ot">=</span> <span class="sc">-</span><span class="fl">22227.81</span> <span class="sc">+</span> <span class="fl">104.438</span> <span class="sc">*</span> Size <span class="sc">-</span> <span class="fl">78527.50</span> <span class="sc">*</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fl">61.916</span> <span class="sc">*</span> Size <span class="sc">*</span> <span class="dv">1</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co">#predicted selling price for a not new home</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>Old_Price <span class="ot">=</span> <span class="sc">-</span><span class="fl">22227.81</span> <span class="sc">+</span> <span class="fl">104.438</span> <span class="sc">*</span> Size</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>New_Price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 148775.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>Old_Price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 134429.2</code></pre>
</div>
</div>
<p>As size of home goes up, the difference in predicted selling prices between old and new homes become larger.</p>
<p>For a 3,000-square-foot house, the difference in price between one that’s new and one that’s not is $107220.5.</p>
<p>For a 1,500-square-food-house, the difference in price between one that’s new and one that’s not is $14352.5.</p>
<p>As the houses get bigger in size, the impact of whether the house is new or not new increases.</p>
</section>
<section id="h" class="level2">
<h2 class="anchored" data-anchor-id="h">H</h2>
<p>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</p>
<p>In the context of predicting the selling price of a house, I analyzed two regression models - one that includes an interaction term between the size of a house and whether it’s new or not, and another that does not include the interaction term. I compared the two models to determine which one better represents the relationship between the size of a house, its age, and its selling price.</p>
<p>Upon comparing the two models, I found that the model that allows for interactions does a better job of representing the relationship between the size of a house and whether it’s new or not to the selling price. The adjusted R-squared for the model with interaction is 0.7363, which is slightly higher than the adjusted R-squared for the model without interaction, which is 0.7169. This suggests that the model with interaction explains slightly more of the variation in the selling price due to the interaction between size, new and selling price.</p>
<p>Furthermore, the model with interaction includes a created variable Size:New, which is statistically significant. This means that null hypothesis that Size:New is not correlated to selling price can be rejected, and it can be concluded that the interaction between the size of a house and whether it’s new or not has a significant impact on its selling price.</p>
<p>The model that includes the interaction term it more preferable, as it explains slightly more of the variation in the selling price due to the interaction between size, new and selling price. Additionally, the statistical significance of the Size:New variable suggests that this interaction term is necessary to create an accurate equation for predicting the selling price of a house.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb49" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 4"</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Akhilesh Kumar"</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "The fourth homework"</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "04/23/2023"</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - Homework3</span></span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - Akhilesh</span></span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb49-25"><a href="#cb49-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb49-26"><a href="#cb49-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb49-27"><a href="#cb49-27" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb49-28"><a href="#cb49-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-29"><a href="#cb49-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-30"><a href="#cb49-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-31"><a href="#cb49-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 1</span></span>
<span id="cb49-32"><a href="#cb49-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-33"><a href="#cb49-33" aria-hidden="true" tabindex="-1"></a>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + (53.8 * x1) + (2.84* x2).</span>
<span id="cb49-34"><a href="#cb49-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-35"><a href="#cb49-35" aria-hidden="true" tabindex="-1"></a><span class="fu">## A</span></span>
<span id="cb49-36"><a href="#cb49-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-37"><a href="#cb49-37" aria-hidden="true" tabindex="-1"></a>A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. </span>
<span id="cb49-38"><a href="#cb49-38" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price and the residual, and interpret.</span>
<span id="cb49-39"><a href="#cb49-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-42"><a href="#cb49-42" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-43"><a href="#cb49-43" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">=</span> <span class="dv">1240</span></span>
<span id="cb49-44"><a href="#cb49-44" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">=</span> <span class="dv">18000</span></span>
<span id="cb49-45"><a href="#cb49-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-46"><a href="#cb49-46" aria-hidden="true" tabindex="-1"></a>Predicted_selling_price <span class="ot">&lt;-</span>  <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> (<span class="fl">53.8</span> <span class="sc">*</span> x1) <span class="sc">+</span> (<span class="fl">2.84</span> <span class="sc">*</span> x2)</span>
<span id="cb49-47"><a href="#cb49-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-48"><a href="#cb49-48" aria-hidden="true" tabindex="-1"></a>Predicted_selling_price</span>
<span id="cb49-49"><a href="#cb49-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-50"><a href="#cb49-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-53"><a href="#cb49-53" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-54"><a href="#cb49-54" aria-hidden="true" tabindex="-1"></a>Actual_selling_price <span class="ot">=</span> <span class="dv">145000</span></span>
<span id="cb49-55"><a href="#cb49-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-56"><a href="#cb49-56" aria-hidden="true" tabindex="-1"></a>Residual <span class="ot">&lt;-</span> Actual_selling_price<span class="sc">-</span>Predicted_selling_price</span>
<span id="cb49-57"><a href="#cb49-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-58"><a href="#cb49-58" aria-hidden="true" tabindex="-1"></a>Residual</span>
<span id="cb49-59"><a href="#cb49-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-60"><a href="#cb49-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-61"><a href="#cb49-61" aria-hidden="true" tabindex="-1"></a>Based on the given data, the prediction equation suggests that a home with 1240 square feet on a lot of 18,000 square feet in Jacksonville, Florida should have a selling price of $107,296. However, the actual selling price of this particular home was $145,000, which is higher than the predicted selling price. This results in a residual of $37,704, indicating that the prediction equation underestimated the selling price of this home.</span>
<span id="cb49-62"><a href="#cb49-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-63"><a href="#cb49-63" aria-hidden="true" tabindex="-1"></a>This suggests that while the prediction equation provides some insight into the selling prices of homes in Jacksonville, Florida based on size of the home and lot size, it is not a perfect predictor. Other factors, such as the condition of the home, location, and other amenities, may also play a role in determining the selling price of a home. Therefore, it is important to consider multiple factors when predicting the selling price of a home in Jacksonville, Florida.</span>
<span id="cb49-64"><a href="#cb49-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-65"><a href="#cb49-65" aria-hidden="true" tabindex="-1"></a><span class="fu">## B</span></span>
<span id="cb49-66"><a href="#cb49-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-67"><a href="#cb49-67" aria-hidden="true" tabindex="-1"></a>Since the prediction equation for home selling price is ŷ = −10,536 + (53.8 * x1) + (2.84 * x2), where x1 represents the home size and x2 represents the lot size, the impact of changing home size on the selling price while holding lot size constant, can be determined.</span>
<span id="cb49-68"><a href="#cb49-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-69"><a href="#cb49-69" aria-hidden="true" tabindex="-1"></a>Specifically, for each additional square foot of home size (x1), the house selling price is expected to increase by 53.8 dollars, assuming lot size is fixed. This is because the coefficient of x1 in the equation is 53.8.</span>
<span id="cb49-70"><a href="#cb49-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-71"><a href="#cb49-71" aria-hidden="true" tabindex="-1"></a>The impact of lot size (x2) on the selling price is also accounted for in the equation, with a coefficient of 2.84. However, if lot size is held constant, then this coefficient does not affect the output, so only coefficient of x1 is required to be considered .</span>
<span id="cb49-72"><a href="#cb49-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-73"><a href="#cb49-73" aria-hidden="true" tabindex="-1"></a>Therefore, if the home size is increased by one unit (representing one additional square foot), the predicted selling price would increase by 53.8 units, assuming the lot size remains constant.</span>
<span id="cb49-74"><a href="#cb49-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-75"><a href="#cb49-75" aria-hidden="true" tabindex="-1"></a><span class="fu">## C</span></span>
<span id="cb49-76"><a href="#cb49-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-77"><a href="#cb49-77" aria-hidden="true" tabindex="-1"></a>According to this prediction equation, for fixed home size, how much would lot size need </span>
<span id="cb49-78"><a href="#cb49-78" aria-hidden="true" tabindex="-1"></a>to increase to have the same impact as a one-square-foot increase in home size?</span>
<span id="cb49-79"><a href="#cb49-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-80"><a href="#cb49-80" aria-hidden="true" tabindex="-1"></a>For fixed home size,</span>
<span id="cb49-81"><a href="#cb49-81" aria-hidden="true" tabindex="-1"></a>53.8 * 1 = 2.84x2</span>
<span id="cb49-82"><a href="#cb49-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-85"><a href="#cb49-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-86"><a href="#cb49-86" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span>
<span id="cb49-87"><a href="#cb49-87" aria-hidden="true" tabindex="-1"></a>x2</span>
<span id="cb49-88"><a href="#cb49-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-89"><a href="#cb49-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-90"><a href="#cb49-90" aria-hidden="true" tabindex="-1"></a>It can be observed that the predicted selling price of a house is estimated to increase by approximately $3 for every additional square foot of lot size, assuming the house size is fixed. Therefore, to achieve a similar impact on the predicted selling price as an increment of one square foot in house size,  lot size should  be increased by roughly 19 square feet. This is because every one-square-foot increase in house size is predicted to increase the selling price by around $53.8, which is equivalent to an increase of approximately 18.94 square feet in lot size. Therefore, an increase in lot size of about 18.94 square feet would have an identical effect on the predicted selling price as an increase of one square foot in home size.</span>
<span id="cb49-91"><a href="#cb49-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-92"><a href="#cb49-92" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 2</span></span>
<span id="cb49-93"><a href="#cb49-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-94"><a href="#cb49-94" aria-hidden="true" tabindex="-1"></a>(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</span>
<span id="cb49-95"><a href="#cb49-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-96"><a href="#cb49-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-97"><a href="#cb49-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-98"><a href="#cb49-98" aria-hidden="true" tabindex="-1"></a><span class="fu">## A</span></span>
<span id="cb49-99"><a href="#cb49-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-100"><a href="#cb49-100" aria-hidden="true" tabindex="-1"></a>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</span>
<span id="cb49-101"><a href="#cb49-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-102"><a href="#cb49-102" aria-hidden="true" tabindex="-1"></a><span class="in">```{r,  warning=FALSE}</span></span>
<span id="cb49-103"><a href="#cb49-103" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot</span></span>
<span id="cb49-104"><a href="#cb49-104" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"salary"</span>)</span>
<span id="cb49-105"><a href="#cb49-105" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(salary, <span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> salary, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb49-106"><a href="#cb49-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb49-107"><a href="#cb49-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Salary"</span>, <span class="at">title =</span> <span class="st">"Salary Comparison between Male &amp; Female"</span>) <span class="sc">+</span></span>
<span id="cb49-108"><a href="#cb49-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb49-109"><a href="#cb49-109" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"navyblue"</span>, <span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>), </span>
<span id="cb49-110"><a href="#cb49-110" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"navyblue"</span>, <span class="at">size =</span> <span class="dv">10</span>), </span>
<span id="cb49-111"><a href="#cb49-111" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"navyblue"</span>, <span class="at">size =</span> <span class="dv">8</span>), </span>
<span id="cb49-112"><a href="#cb49-112" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"navyblue"</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb49-113"><a href="#cb49-113" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FF5C35"</span>, <span class="st">"#00B945"</span>))</span>
<span id="cb49-114"><a href="#cb49-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-115"><a href="#cb49-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-116"><a href="#cb49-116" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-117"><a href="#cb49-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-118"><a href="#cb49-118" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-119"><a href="#cb49-119" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize salary data</span></span>
<span id="cb49-120"><a href="#cb49-120" aria-hidden="true" tabindex="-1"></a>summary_salary <span class="ot">&lt;-</span> salary <span class="sc">%&gt;%</span></span>
<span id="cb49-121"><a href="#cb49-121" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span></span>
<span id="cb49-122"><a href="#cb49-122" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">average_salary =</span> <span class="fu">mean</span>(salary), <span class="at">min_salary =</span> <span class="fu">min</span>(salary), <span class="at">max_salary =</span> <span class="fu">max</span>(salary))</span>
<span id="cb49-123"><a href="#cb49-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-124"><a href="#cb49-124" aria-hidden="true" tabindex="-1"></a><span class="co"># Create salary comparison plot</span></span>
<span id="cb49-125"><a href="#cb49-125" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summary_salary, <span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> average_salary)) <span class="sc">+</span>   </span>
<span id="cb49-126"><a href="#cb49-126" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb49-127"><a href="#cb49-127" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> min_salary, <span class="at">ymax =</span> max_salary), <span class="at">color =</span> <span class="st">"#32CD32"</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb49-128"><a href="#cb49-128" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Salary"</span>, <span class="at">title =</span> <span class="st">"Salary Comparison between Male &amp; Female"</span>) <span class="sc">+</span></span>
<span id="cb49-129"><a href="#cb49-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y =</span> max_salary, <span class="at">label =</span> max_salary), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"#000080"</span>, <span class="at">hjust =</span> <span class="sc">-</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb49-130"><a href="#cb49-130" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y =</span> min_salary, <span class="at">label =</span> min_salary), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"#000080"</span>, <span class="at">hjust =</span> <span class="sc">-</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb49-131"><a href="#cb49-131" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(average_salary, <span class="at">digits =</span> <span class="dv">2</span>)), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"#000080"</span>, <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb49-132"><a href="#cb49-132" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb49-133"><a href="#cb49-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#33475b"</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb49-134"><a href="#cb49-134" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#33475b"</span>, <span class="at">size =</span> <span class="dv">8</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb49-135"><a href="#cb49-135" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#33475b"</span>, <span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb49-136"><a href="#cb49-136" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#33475b"</span>, <span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb49-137"><a href="#cb49-137" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#000080"</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb49-138"><a href="#cb49-138" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-139"><a href="#cb49-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-140"><a href="#cb49-140" aria-hidden="true" tabindex="-1"></a>Based solely on the visuals, it is clear that the average salary for men and women differ. However, it is uncertain if this difference is statistically significant. Additionally, while men generally have a higher mean salary, there is one outlier female who earns the most, indicating a wider salary range for women. Nonetheless, further analysis is necessary to determine whether these findings are significant.</span>
<span id="cb49-141"><a href="#cb49-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-142"><a href="#cb49-142" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-143"><a href="#cb49-143" aria-hidden="true" tabindex="-1"></a><span class="co"># t.test to text the null hypothesis that men and women make the same amount. </span></span>
<span id="cb49-144"><a href="#cb49-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-145"><a href="#cb49-145" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary<span class="sc">~</span>sex, <span class="at">data =</span> salary)</span>
<span id="cb49-146"><a href="#cb49-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-147"><a href="#cb49-147" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-148"><a href="#cb49-148" aria-hidden="true" tabindex="-1"></a>Based on a Welch Two Sample t-test, I found that the mean salary for men is higher than women. However, the p-value of 0.09 is higher than a significance level of 5%, indicating that the null hypothesis of 'the mean salary for men and women are the same', cannot be rejected. Therefore, It cannot be concluded that there is a significant difference in the mean salary between men and women.</span>
<span id="cb49-149"><a href="#cb49-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-150"><a href="#cb49-150" aria-hidden="true" tabindex="-1"></a><span class="fu">## B</span></span>
<span id="cb49-151"><a href="#cb49-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-152"><a href="#cb49-152" aria-hidden="true" tabindex="-1"></a>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</span>
<span id="cb49-153"><a href="#cb49-153" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-154"><a href="#cb49-154" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary)</span>
<span id="cb49-155"><a href="#cb49-155" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb49-156"><a href="#cb49-156" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-157"><a href="#cb49-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-158"><a href="#cb49-158" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-159"><a href="#cb49-159" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model)</span>
<span id="cb49-160"><a href="#cb49-160" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-161"><a href="#cb49-161" aria-hidden="true" tabindex="-1"></a>The linear regression analysis shows that there is a significant relationship between salary and the variables degree, rank, sex, year, and years since degree completion. However, the p-value for the variable sex is 0.214, which is higher than the significance level of 0.05, indicating that null hypothesis: that there is no difference in mean salary between males and females, cannot be rejected. Further, at a 95% confidence interval, the difference in mean salary between males and females ranges from -$697.82 to $3,030.56, suggesting that 95% of the time, males will make between $697.82 more and $3,030.56 less than females.</span>
<span id="cb49-162"><a href="#cb49-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-163"><a href="#cb49-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-164"><a href="#cb49-164" aria-hidden="true" tabindex="-1"></a><span class="fu">## C</span></span>
<span id="cb49-165"><a href="#cb49-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-166"><a href="#cb49-166" aria-hidden="true" tabindex="-1"></a>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables</span>
<span id="cb49-167"><a href="#cb49-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-168"><a href="#cb49-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-169"><a href="#cb49-169" aria-hidden="true" tabindex="-1"></a>**degreePhD:**</span>
<span id="cb49-170"><a href="#cb49-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-171"><a href="#cb49-171" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient estimate is 1388.61 with a standard error of 1018.75. </span>
<span id="cb49-172"><a href="#cb49-172" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The p-value is 0.180, which is greater than 0.05, indicating that the coefficient for "degreePhD" is not statistically significant. </span>
<span id="cb49-173"><a href="#cb49-173" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>This means that there is insufficient evidence to suggest that having a PhD degree has a statistically significant effect on salary, after accounting for other variables in the model.</span>
<span id="cb49-174"><a href="#cb49-174" aria-hidden="true" tabindex="-1"></a>This suggests that having a PhD degree does not have a significant effect on salary after accounting for the other variables in the model.</span>
<span id="cb49-175"><a href="#cb49-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-176"><a href="#cb49-176" aria-hidden="true" tabindex="-1"></a>**rankAssoc:**</span>
<span id="cb49-177"><a href="#cb49-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-178"><a href="#cb49-178" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient estimate is 5292.36 with a standard error of 1145.40. </span>
<span id="cb49-179"><a href="#cb49-179" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The p-value is 3.22e-05, which is less than 0.05, indicating that the coefficient for "rankAssoc" is statistically significant. </span>
<span id="cb49-180"><a href="#cb49-180" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>This means that having an associate professor rank is associated with a salary increase of $5292.36 on average, compared to assistant professors, after controlling for the other variables in the model.</span>
<span id="cb49-181"><a href="#cb49-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-182"><a href="#cb49-182" aria-hidden="true" tabindex="-1"></a>**rankProf:**</span>
<span id="cb49-183"><a href="#cb49-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-184"><a href="#cb49-184" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient estimate is 11118.76 with a standard error of 1351.77. </span>
<span id="cb49-185"><a href="#cb49-185" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The p-value is 1.62e-10, which is less than 0.05, indicating that the coefficient for "rankProf" is statistically significant. </span>
<span id="cb49-186"><a href="#cb49-186" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>This means that having a professor rank is associated with a salary increase of $11118.76 on average, compared to assistant professors, after controlling for the other variables in the model.</span>
<span id="cb49-187"><a href="#cb49-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-188"><a href="#cb49-188" aria-hidden="true" tabindex="-1"></a>**sexFemale:**</span>
<span id="cb49-189"><a href="#cb49-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-190"><a href="#cb49-190" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient estimate is 1166.37 with a standard error of 925.57. </span>
<span id="cb49-191"><a href="#cb49-191" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The p-value is 0.214, which is greater than 0.05, indicating that the coefficient for "sexFemale" is not statistically significant. </span>
<span id="cb49-192"><a href="#cb49-192" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>This suggests that gender does not have a significant effect on salary after accounting for the other variables in the model.</span>
<span id="cb49-193"><a href="#cb49-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-194"><a href="#cb49-194" aria-hidden="true" tabindex="-1"></a>**year:**</span>
<span id="cb49-195"><a href="#cb49-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-196"><a href="#cb49-196" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient estimate is 476.31 with a standard error of 94.91. </span>
<span id="cb49-197"><a href="#cb49-197" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The p-value is 8.65e-06, which is less than 0.05, indicating that the coefficient for "year" is statistically significant.</span>
<span id="cb49-198"><a href="#cb49-198" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>This means that for each additional year, there is an increase in salary of $476.31 on average, after controlling for the other variables in the model.</span>
<span id="cb49-199"><a href="#cb49-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-200"><a href="#cb49-200" aria-hidden="true" tabindex="-1"></a>**ysdeg:**</span>
<span id="cb49-201"><a href="#cb49-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-202"><a href="#cb49-202" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient estimate is -124.57 with a standard error of 77.49. </span>
<span id="cb49-203"><a href="#cb49-203" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The p-value is 0.115, which is greater than 0.05, indicating that the coefficient for "ysdeg" is not statistically significant. </span>
<span id="cb49-204"><a href="#cb49-204" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>This suggests that the years since receiving a degree does not have a significant effect on salary after accounting for the other variables in the model.</span>
<span id="cb49-205"><a href="#cb49-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-206"><a href="#cb49-206" aria-hidden="true" tabindex="-1"></a>Overall, the model shows that rank and years of experience are the most significant predictors of salary in this dataset.</span>
<span id="cb49-207"><a href="#cb49-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-208"><a href="#cb49-208" aria-hidden="true" tabindex="-1"></a><span class="fu">## D</span></span>
<span id="cb49-209"><a href="#cb49-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-210"><a href="#cb49-210" aria-hidden="true" tabindex="-1"></a>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</span>
<span id="cb49-211"><a href="#cb49-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-212"><a href="#cb49-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-213"><a href="#cb49-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-214"><a href="#cb49-214" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">'Prof'</span>)</span>
<span id="cb49-215"><a href="#cb49-215" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(salary)</span>
<span id="cb49-216"><a href="#cb49-216" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> ., salary))</span>
<span id="cb49-217"><a href="#cb49-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-218"><a href="#cb49-218" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-219"><a href="#cb49-219" aria-hidden="true" tabindex="-1"></a>After changing the baseline category for the rank variable, an Associate can expect a 6483.0 dollar decrease in salary compared to Professor, while a Assistant can expect a 11890.3 dollar salary decrease compared to Professor. Both ranks have significance levels well below 0.05 and it can be determined that rank does have a statistically significant impact on salary.</span>
<span id="cb49-220"><a href="#cb49-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-221"><a href="#cb49-221" aria-hidden="true" tabindex="-1"></a>Interpreting the coefficients related to rank after changing the baseline category to "Prof", I see that the coefficients for both rankAsst and rankAssoc are negative. This means that the average salary for assistant professors and associate professors is lower than the average salary for full professors, holding all other variables constant.</span>
<span id="cb49-222"><a href="#cb49-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-223"><a href="#cb49-223" aria-hidden="true" tabindex="-1"></a>The coefficient for rankAsst is -11118.76, indicating that assistant professors earn, on average, $11,118.76 less than full professors when all other variables are held constant. The coefficient for rankAssoc is -5826.40, indicating that associate professors earn, on average, $5,826.40 less than full professors when all other variables are held constant.</span>
<span id="cb49-224"><a href="#cb49-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-225"><a href="#cb49-225" aria-hidden="true" tabindex="-1"></a>The interpretation of these coefficients assumes that the other variables included in the model (degreePhD, sexFemale, year, and ysdeg) are held constant.</span>
<span id="cb49-226"><a href="#cb49-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-227"><a href="#cb49-227" aria-hidden="true" tabindex="-1"></a><span class="fu">## E</span></span>
<span id="cb49-228"><a href="#cb49-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-229"><a href="#cb49-229" aria-hidden="true" tabindex="-1"></a>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “<span class="co">[</span><span class="ot">a</span><span class="co">]</span> variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’ ” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.Exclude the variable rank, refit, and summarize how your findings changed, if they did</span>
<span id="cb49-230"><a href="#cb49-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-231"><a href="#cb49-231" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-232"><a href="#cb49-232" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, salary))</span>
<span id="cb49-233"><a href="#cb49-233" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-234"><a href="#cb49-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-235"><a href="#cb49-235" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient for the predictor variable degreePhD is -3299.35, with a standard error of 1302.52, and a p-value of 0.014704, indicating a significant negative relationship between having a PhD degree and salary.</span>
<span id="cb49-236"><a href="#cb49-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-237"><a href="#cb49-237" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient for the predictor variable sexFemale is -1286.54, with a standard error of 1313.09, and a p-value of 0.332209, indicating that there is no significant difference in salary between male and female employees.</span>
<span id="cb49-238"><a href="#cb49-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-239"><a href="#cb49-239" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient for the predictor variable year is 351.97, with a standard error of 142.48, and a p-value of 0.017185, indicating a significant positive relationship between the year of employment and salary.</span>
<span id="cb49-240"><a href="#cb49-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-241"><a href="#cb49-241" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient for the predictor variable ysdeg is 339.40, with a standard error of 80.62, and a p-value of 0.000114, indicating a significant positive relationship between the number of years of service and salary.</span>
<span id="cb49-242"><a href="#cb49-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-243"><a href="#cb49-243" aria-hidden="true" tabindex="-1"></a>The R-squared value of the model is 0.6312, indicating that the predictors explain 63.12% of the variability in salary. The adjusted R-squared value, which adjusts for the number of predictors in the model, is 0.5998.</span>
<span id="cb49-244"><a href="#cb49-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-245"><a href="#cb49-245" aria-hidden="true" tabindex="-1"></a>The F-statistic of the model is 20.11 with 4 and 47 degrees of freedom, and the p-value is 1.048e-09, indicating that the model is a good fit for the data and that at least one of the predictors is significantly related to salary.</span>
<span id="cb49-246"><a href="#cb49-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-247"><a href="#cb49-247" aria-hidden="true" tabindex="-1"></a><span class="fu">## F</span></span>
<span id="cb49-248"><a href="#cb49-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-249"><a href="#cb49-249" aria-hidden="true" tabindex="-1"></a>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</span>
<span id="cb49-250"><a href="#cb49-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-251"><a href="#cb49-251" aria-hidden="true" tabindex="-1"></a>Create a new variable that would allow you to test this hypothesis and run another multiple regression  model  to  test  this.  Select  variables  carefully  to  make  sure there  is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</span>
<span id="cb49-252"><a href="#cb49-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-253"><a href="#cb49-253" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-254"><a href="#cb49-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-255"><a href="#cb49-255" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>NewDean <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb49-256"><a href="#cb49-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-257"><a href="#cb49-257" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> rank <span class="sc">+</span> degree <span class="sc">+</span> year<span class="sc">+</span> NewDean, <span class="at">data =</span> salary))</span>
<span id="cb49-258"><a href="#cb49-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-259"><a href="#cb49-259" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-260"><a href="#cb49-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-261"><a href="#cb49-261" aria-hidden="true" tabindex="-1"></a>To test the hypothesis, a dummy variable (NewDean) was created. It is coded as 1 if ysdeg is 15 years or less, and 0 otherwise.</span>
<span id="cb49-262"><a href="#cb49-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-263"><a href="#cb49-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-264"><a href="#cb49-264" aria-hidden="true" tabindex="-1"></a>These correlations indicate that there is a relationship between the variables and they might have a similar impact on the response variable (salary). To address this issue, the variable ysdeg was removed due to its overlap with NewDean variable (since the NewDean variable was based on ysdeg).</span>
<span id="cb49-265"><a href="#cb49-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-266"><a href="#cb49-266" aria-hidden="true" tabindex="-1"></a>Then, I fit a new regression model, including the variables of sex, rank, degree, year and NewDean. According to the regression results, employees hired under the new dean are expected to earn $2163.46 more than those hired prior to the new dean's tenure. However, this correlation is only significant at the 0.0496 level. While it is statistically significant, it is not the most powerful predictor of salary.</span>
<span id="cb49-267"><a href="#cb49-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-268"><a href="#cb49-268" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 3</span></span>
<span id="cb49-269"><a href="#cb49-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-270"><a href="#cb49-270" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-271"><a href="#cb49-271" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb49-272"><a href="#cb49-272" aria-hidden="true" tabindex="-1"></a>house.selling.price</span>
<span id="cb49-273"><a href="#cb49-273" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-274"><a href="#cb49-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-275"><a href="#cb49-275" aria-hidden="true" tabindex="-1"></a><span class="fu">## A</span></span>
<span id="cb49-276"><a href="#cb49-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-277"><a href="#cb49-277" aria-hidden="true" tabindex="-1"></a>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</span>
<span id="cb49-278"><a href="#cb49-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-279"><a href="#cb49-279" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-280"><a href="#cb49-280" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price))</span>
<span id="cb49-281"><a href="#cb49-281" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-282"><a href="#cb49-282" aria-hidden="true" tabindex="-1"></a>The coefficient of Size is estimated to be 116.132, which means that for each unit increase in Size, it is expected that the Price would increase by an average of 116.132. The t-value of 13.204 is highly significant (p &lt; 0.001), indicating that the coefficient is significantly different from zero. Therefore, the null hypothesis that there is no linear relationship between Size and Price is rejected.</span>
<span id="cb49-283"><a href="#cb49-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-284"><a href="#cb49-284" aria-hidden="true" tabindex="-1"></a>The coefficient of New is estimated to be 57736.283, which means that its price would be $57736.283 higher than a house that is not new, all other things being equal. The t-value of 3.095 is also significant (p = 0.00257), indicating that the coefficient is significantly different from zero. Therefore, the null hypothesis that there is no linear relationship between New and Price, is rejected.</span>
<span id="cb49-285"><a href="#cb49-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-286"><a href="#cb49-286" aria-hidden="true" tabindex="-1"></a>The intercept coefficient is estimated to be -40230.867, which is the expected value of Price when both Size and New are equal to zero. However, since there are no houses with zero Size and zero New, this value does not have any practical meaning in this context.</span>
<span id="cb49-287"><a href="#cb49-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-288"><a href="#cb49-288" aria-hidden="true" tabindex="-1"></a>The adjusted R-squared of this model is 0.7169, which means that approximately 71.7% of the variability in Price can be explained by Size and New. The F-statistic of 126.3 with p-value &lt; 2.2e-16 indicates that the model as a whole is statistically significant, and that the predictor variables are jointly significant in explaining the variation in the response variable.</span>
<span id="cb49-289"><a href="#cb49-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-290"><a href="#cb49-290" aria-hidden="true" tabindex="-1"></a><span class="fu">## B</span></span>
<span id="cb49-291"><a href="#cb49-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-292"><a href="#cb49-292" aria-hidden="true" tabindex="-1"></a>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes</span>
<span id="cb49-293"><a href="#cb49-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-294"><a href="#cb49-294" aria-hidden="true" tabindex="-1"></a>Based on the above regression model, the prediction equation for the selling price of a home would be selling price = -40230.867 + 116.132 * size + 57736.283 * new where size = the size of the home and new = 1 if the home is new or new = 0 if the home is not new.</span>
<span id="cb49-295"><a href="#cb49-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-296"><a href="#cb49-296" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>For new homes, z = 1 so the prediction equation for the selling price of a new home is selling price = -40230.867 + 116.132 * size + 57736.283 or selling price = 17505.416 + 116.132 * size</span>
<span id="cb49-297"><a href="#cb49-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-298"><a href="#cb49-298" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>For old homes, z = 0 so the prediction equation for the selling price of a not-new home is selling price = -40230.867 + 116.132 * size + 0 or selling price = -40230.867 + 116.132 * size</span>
<span id="cb49-299"><a href="#cb49-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-300"><a href="#cb49-300" aria-hidden="true" tabindex="-1"></a>Based on the regression analysis and the obtained equations, we can infer that the variables Size and New have a positive influence on the selling price of a home. The coefficient of Size denotes that there is a linear association between the size of a home and its selling prce. This implies that for every 1 sq foot increase in the size of a home, we can expect an estimated increase of ~$116 in the selling price, while holding all other factors constant. On the other hand, the coefficient of New indicates that new homes, on average, are sold for ~$57,736 more than old homes of the same size.</span>
<span id="cb49-301"><a href="#cb49-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-302"><a href="#cb49-302" aria-hidden="true" tabindex="-1"></a>Since there is no interaction term in the model, the impact of each variable is analyzed separately. This suggests that the effect of Size on the selling price is consistent for both new and old homes. Moreover, both Size and New have been found to be statistically significant, respectively, based on their small p-values.</span>
<span id="cb49-303"><a href="#cb49-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-304"><a href="#cb49-304" aria-hidden="true" tabindex="-1"></a><span class="fu">## C</span></span>
<span id="cb49-305"><a href="#cb49-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-306"><a href="#cb49-306" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</span>
<span id="cb49-307"><a href="#cb49-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-308"><a href="#cb49-308" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-309"><a href="#cb49-309" aria-hidden="true" tabindex="-1"></a>Size <span class="ot">&lt;-</span> <span class="dv">3000</span></span>
<span id="cb49-310"><a href="#cb49-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-311"><a href="#cb49-311" aria-hidden="true" tabindex="-1"></a><span class="co">#predicted selling price for a new home</span></span>
<span id="cb49-312"><a href="#cb49-312" aria-hidden="true" tabindex="-1"></a>New_Price <span class="ot">=</span> <span class="fl">17505.416</span> <span class="sc">+</span> (<span class="fl">116.132</span> <span class="sc">*</span> Size)</span>
<span id="cb49-313"><a href="#cb49-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-314"><a href="#cb49-314" aria-hidden="true" tabindex="-1"></a><span class="co">#predicted selling price for a not new home</span></span>
<span id="cb49-315"><a href="#cb49-315" aria-hidden="true" tabindex="-1"></a>Old_Price <span class="ot">=</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> (<span class="fl">116.132</span> <span class="sc">*</span> Size)</span>
<span id="cb49-316"><a href="#cb49-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-317"><a href="#cb49-317" aria-hidden="true" tabindex="-1"></a>New_Price</span>
<span id="cb49-318"><a href="#cb49-318" aria-hidden="true" tabindex="-1"></a>Old_Price</span>
<span id="cb49-319"><a href="#cb49-319" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-320"><a href="#cb49-320" aria-hidden="true" tabindex="-1"></a>Based on the predictive formulas from the regression model, the predicted selling price for a new home of 3000 sq. feet is $365,901 and the predicted selling price for a not-new home of the same size is $308,165.</span>
<span id="cb49-321"><a href="#cb49-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-322"><a href="#cb49-322" aria-hidden="true" tabindex="-1"></a><span class="fu">## D</span></span>
<span id="cb49-323"><a href="#cb49-323" aria-hidden="true" tabindex="-1"></a>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</span>
<span id="cb49-324"><a href="#cb49-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-325"><a href="#cb49-325" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-326"><a href="#cb49-326" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size<span class="sc">*</span>New, <span class="at">data =</span> house.selling.price))</span>
<span id="cb49-327"><a href="#cb49-327" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-328"><a href="#cb49-328" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The new model includes an interaction term between Size and New, allowing for the possibility that the effect of Size on Price differs depending on whether a home is new or not.</span>
<span id="cb49-329"><a href="#cb49-329" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient for the interaction term is positive and statistically significant (p &lt; 0.01), indicating that the effect of Size on Price is stronger for new homes compared to not-new homes.</span>
<span id="cb49-330"><a href="#cb49-330" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient for New is negative but not statistically significant (p &gt; 0.05), suggesting that being a new home does not have a significant impact on Price when Size and the interaction term are taken into account.</span>
<span id="cb49-331"><a href="#cb49-331" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The coefficient for Size is positive and highly significant (p &lt; 0.001), indicating that increasing the size of a home leads to a higher predicted selling price, all else being equal.</span>
<span id="cb49-332"><a href="#cb49-332" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The adjusted R-squared for the model is 0.7363, indicating that the model explains around 74% of the variation in selling prices, after accounting for the effects of Size, New, and the interaction term.</span>
<span id="cb49-333"><a href="#cb49-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-334"><a href="#cb49-334" aria-hidden="true" tabindex="-1"></a><span class="fu">## E</span></span>
<span id="cb49-335"><a href="#cb49-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-336"><a href="#cb49-336" aria-hidden="true" tabindex="-1"></a>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</span>
<span id="cb49-337"><a href="#cb49-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-338"><a href="#cb49-338" aria-hidden="true" tabindex="-1"></a>The predicted selling price, based on the new regression that includes interaction between Size and Newness, would look like:</span>
<span id="cb49-339"><a href="#cb49-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-340"><a href="#cb49-340" aria-hidden="true" tabindex="-1"></a>House_Price = -22227.808 + 104.438 * Size - 78527.50 * z + 61.916 * Size * z</span>
<span id="cb49-341"><a href="#cb49-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-342"><a href="#cb49-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-343"><a href="#cb49-343" aria-hidden="true" tabindex="-1"></a>Where Size = the size of the home and z = 1 if the home is new or z = 0 if the home is not new.</span>
<span id="cb49-344"><a href="#cb49-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-345"><a href="#cb49-345" aria-hidden="true" tabindex="-1"></a>New_Price = -22227.808 + 104.438 * Size - 78527.50 * 1  + 61.916 * Size * 1</span>
<span id="cb49-346"><a href="#cb49-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-347"><a href="#cb49-347" aria-hidden="true" tabindex="-1"></a><span class="in">          = -22227.808 + 104.438 * Size - 78527.50  + 61.916 * Size</span></span>
<span id="cb49-348"><a href="#cb49-348" aria-hidden="true" tabindex="-1"></a><span class="in">          </span></span>
<span id="cb49-349"><a href="#cb49-349" aria-hidden="true" tabindex="-1"></a><span class="in">          = -100755 + 166.354 * Size</span></span>
<span id="cb49-350"><a href="#cb49-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-351"><a href="#cb49-351" aria-hidden="true" tabindex="-1"></a>Old_Price = -22227.808 + 104.438 * Size - 78527.50 * 0 + 61.916 * Size * 0</span>
<span id="cb49-352"><a href="#cb49-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-353"><a href="#cb49-353" aria-hidden="true" tabindex="-1"></a><span class="in">          = -22227.808 + 104.438 * Size</span></span>
<span id="cb49-354"><a href="#cb49-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-355"><a href="#cb49-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-356"><a href="#cb49-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-357"><a href="#cb49-357" aria-hidden="true" tabindex="-1"></a><span class="fu">## F</span></span>
<span id="cb49-358"><a href="#cb49-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-359"><a href="#cb49-359" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</span>
<span id="cb49-360"><a href="#cb49-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-361"><a href="#cb49-361" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-362"><a href="#cb49-362" aria-hidden="true" tabindex="-1"></a>Size <span class="ot">&lt;-</span> <span class="dv">3000</span></span>
<span id="cb49-363"><a href="#cb49-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-364"><a href="#cb49-364" aria-hidden="true" tabindex="-1"></a><span class="co"># predicted selling price for a new home</span></span>
<span id="cb49-365"><a href="#cb49-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-366"><a href="#cb49-366" aria-hidden="true" tabindex="-1"></a>New_Price <span class="ot">=</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span> <span class="sc">*</span> Size <span class="sc">-</span> <span class="fl">78527.50</span> <span class="sc">*</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fl">61.916</span> <span class="sc">*</span> Size <span class="sc">*</span> <span class="dv">1</span></span>
<span id="cb49-367"><a href="#cb49-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-368"><a href="#cb49-368" aria-hidden="true" tabindex="-1"></a><span class="co">#predicted selling price for a not new home</span></span>
<span id="cb49-369"><a href="#cb49-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-370"><a href="#cb49-370" aria-hidden="true" tabindex="-1"></a>Old_Price <span class="ot">=</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span> <span class="sc">*</span> Size</span>
<span id="cb49-371"><a href="#cb49-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-372"><a href="#cb49-372" aria-hidden="true" tabindex="-1"></a>New_Price</span>
<span id="cb49-373"><a href="#cb49-373" aria-hidden="true" tabindex="-1"></a>Old_Price</span>
<span id="cb49-374"><a href="#cb49-374" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-375"><a href="#cb49-375" aria-hidden="true" tabindex="-1"></a>Based on the predictive formulas from the regression model, the predicted selling price for a new home that is 3000 sq. feet is $398,306.70 and the predicted selling price for a not new home of the same size is $291,086.20.</span>
<span id="cb49-376"><a href="#cb49-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-377"><a href="#cb49-377" aria-hidden="true" tabindex="-1"></a><span class="fu">## G</span></span>
<span id="cb49-378"><a href="#cb49-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-379"><a href="#cb49-379" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases</span>
<span id="cb49-380"><a href="#cb49-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-381"><a href="#cb49-381" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb49-382"><a href="#cb49-382" aria-hidden="true" tabindex="-1"></a>Size <span class="ot">&lt;-</span> <span class="dv">1500</span></span>
<span id="cb49-383"><a href="#cb49-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-384"><a href="#cb49-384" aria-hidden="true" tabindex="-1"></a><span class="co"># predicted selling price for a new home</span></span>
<span id="cb49-385"><a href="#cb49-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-386"><a href="#cb49-386" aria-hidden="true" tabindex="-1"></a>New_Price <span class="ot">=</span> <span class="sc">-</span><span class="fl">22227.81</span> <span class="sc">+</span> <span class="fl">104.438</span> <span class="sc">*</span> Size <span class="sc">-</span> <span class="fl">78527.50</span> <span class="sc">*</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fl">61.916</span> <span class="sc">*</span> Size <span class="sc">*</span> <span class="dv">1</span></span>
<span id="cb49-387"><a href="#cb49-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-388"><a href="#cb49-388" aria-hidden="true" tabindex="-1"></a><span class="co">#predicted selling price for a not new home</span></span>
<span id="cb49-389"><a href="#cb49-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-390"><a href="#cb49-390" aria-hidden="true" tabindex="-1"></a>Old_Price <span class="ot">=</span> <span class="sc">-</span><span class="fl">22227.81</span> <span class="sc">+</span> <span class="fl">104.438</span> <span class="sc">*</span> Size</span>
<span id="cb49-391"><a href="#cb49-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-392"><a href="#cb49-392" aria-hidden="true" tabindex="-1"></a>New_Price</span>
<span id="cb49-393"><a href="#cb49-393" aria-hidden="true" tabindex="-1"></a>Old_Price</span>
<span id="cb49-394"><a href="#cb49-394" aria-hidden="true" tabindex="-1"></a><span class="in">```</span> </span>
<span id="cb49-395"><a href="#cb49-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-396"><a href="#cb49-396" aria-hidden="true" tabindex="-1"></a>As size of home goes up, the difference in predicted selling prices between old and new homes become larger.</span>
<span id="cb49-397"><a href="#cb49-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-398"><a href="#cb49-398" aria-hidden="true" tabindex="-1"></a>For a 3,000-square-foot house, the difference in price between one that’s new and one that’s not is $107220.5.</span>
<span id="cb49-399"><a href="#cb49-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-400"><a href="#cb49-400" aria-hidden="true" tabindex="-1"></a>For a 1,500-square-food-house, the difference in price between one that’s new and one that’s not is $14352.5.</span>
<span id="cb49-401"><a href="#cb49-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-402"><a href="#cb49-402" aria-hidden="true" tabindex="-1"></a>As the houses get bigger in size, the impact of whether the house is new or not new increases.</span>
<span id="cb49-403"><a href="#cb49-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-404"><a href="#cb49-404" aria-hidden="true" tabindex="-1"></a><span class="fu">## H</span></span>
<span id="cb49-405"><a href="#cb49-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-406"><a href="#cb49-406" aria-hidden="true" tabindex="-1"></a>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</span>
<span id="cb49-407"><a href="#cb49-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-408"><a href="#cb49-408" aria-hidden="true" tabindex="-1"></a>In the context of predicting the selling price of a house, I analyzed two regression models - one that includes an interaction term between the size of a house and whether it's new or not, and another that does not include the interaction term. I compared the two models to determine which one better represents the relationship between the size of a house, its age, and its selling price.</span>
<span id="cb49-409"><a href="#cb49-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-410"><a href="#cb49-410" aria-hidden="true" tabindex="-1"></a>Upon comparing the two models, I found that the model that allows for interactions does a better job of representing the relationship between the size of a house and whether it's new or not to the selling price. The adjusted R-squared for the model with interaction is 0.7363, which is slightly higher than the adjusted R-squared for the model without interaction, which is 0.7169. This suggests that the model with interaction explains slightly more of the variation in the selling price due to the interaction between size, new and selling price.</span>
<span id="cb49-411"><a href="#cb49-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-412"><a href="#cb49-412" aria-hidden="true" tabindex="-1"></a>Furthermore, the model with interaction includes a created variable Size:New, which is statistically significant. This means that null hypothesis that Size:New is not correlated to selling price can be rejected, and it can be concluded that the interaction between the size of a house and whether it's new or not has a significant impact on its selling price.</span>
<span id="cb49-413"><a href="#cb49-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-414"><a href="#cb49-414" aria-hidden="true" tabindex="-1"></a>The model that includes the interaction term it more preferable, as it explains slightly more of the variation in the selling price due to the interaction between size, new and selling price. Additionally, the statistical significance of the Size:New variable suggests that this interaction term is necessary to create an accurate equation for predicting the selling price of a house.</span>
<span id="cb49-415"><a href="#cb49-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-416"><a href="#cb49-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-417"><a href="#cb49-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-418"><a href="#cb49-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-419"><a href="#cb49-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-420"><a href="#cb49-420" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>