<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emma Narkewicz">
<meta name="dcterms.date" content="2023-05-01">
<meta name="description" content="Emma Narkewicz HW4">

<title>Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Homework 4">
<meta name="twitter:description" content="Emma Narkewicz HW4">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a>
  <ul class="collapse">
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">A</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">B</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">C</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#a-1" id="toc-a-1" class="nav-link" data-scroll-target="#a-1">A</a></li>
  <li><a href="#b-1" id="toc-b-1" class="nav-link" data-scroll-target="#b-1">B</a></li>
  <li><a href="#c-1" id="toc-c-1" class="nav-link" data-scroll-target="#c-1">C</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">D</a></li>
  <li><a href="#e" id="toc-e" class="nav-link" data-scroll-target="#e">E</a></li>
  <li><a href="#f" id="toc-f" class="nav-link" data-scroll-target="#f">F</a></li>
  </ul></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a>
  <ul class="collapse">
  <li><a href="#a-2" id="toc-a-2" class="nav-link" data-scroll-target="#a-2">A</a></li>
  <li><a href="#b-2" id="toc-b-2" class="nav-link" data-scroll-target="#b-2">B</a></li>
  <li><a href="#c-2" id="toc-c-2" class="nav-link" data-scroll-target="#c-2">C</a></li>
  <li><a href="#d-1" id="toc-d-1" class="nav-link" data-scroll-target="#d-1">D</a></li>
  <li><a href="#e-1" id="toc-e-1" class="nav-link" data-scroll-target="#e-1">E</a></li>
  <li><a href="#f-1" id="toc-f-1" class="nav-link" data-scroll-target="#f-1">F</a></li>
  <li><a href="#g" id="toc-g" class="nav-link" data-scroll-target="#g">G</a></li>
  <li><a href="#h" id="toc-h" class="nav-link" data-scroll-target="#h">H</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 4</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw4</div>
    <div class="quarto-category">linear regression</div>
    <div class="quarto-category">emma_narkewicz</div>
  </div>
  </div>

<div>
  <div class="description">
    Emma Narkewicz HW4
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emma Narkewicz </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 1, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="question-1" class="level1">
<h1>Question 1</h1>
<p>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.</p>
<section id="a" class="level2">
<h2 class="anchored" data-anchor-id="a">A</h2>
<p>A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</p>
<p>To solve for the predicted price, I plugged in x1 = 1,240 &amp; x2 = 18,000</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Predicted Price</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> (<span class="fl">53.8</span> <span class="sc">*</span> <span class="dv">1240</span>) <span class="sc">+</span> (<span class="fl">2.84</span> <span class="sc">*</span> <span class="dv">18000</span>)  </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>pp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107296</code></pre>
</div>
</div>
<p>From the equation, the predicted selling price of the house is $107,296</p>
<p>The residual can be calculated using the equation:</p>
<p>Residual = (actual y-value) - (predicted y value)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Residual</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>R <span class="ot">=</span> <span class="dv">145000</span> <span class="sc">-</span> <span class="dv">107296</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>R</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37704</code></pre>
</div>
</div>
<p>The residual of positive $37,704 indicates that the house sold for more than the model predicted, meaning the model under-predicted the selling price.</p>
</section>
<section id="b" class="level2">
<h2 class="anchored" data-anchor-id="b">B</h2>
<p>For fixed lot size, how much is the house selling price predicted to increase for each square- foot increase in home size? Why?</p>
<p>Based on the prediction equation for a fixed lot size (x2), the price of the house is expected to increase $53.8 dollars for each square foot of house size. This is because with a fixed lot size (x2) t the 53.8x1 in the prediction equation explains the increase in house price per each square foot of house size</p>
<p>ŷ = −10,536 + 53.8x1 + 2.84x2.</p>
</section>
<section id="c" class="level2">
<h2 class="anchored" data-anchor-id="c">C</h2>
<p>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</p>
<p>Home size = x1 = 1 Lot size = x2</p>
<p>53.81 (x1) = 2.84x2 53.8 = 2.84x2</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.94366</code></pre>
</div>
</div>
<p>Based on the prediction equation, the lot size would need to increase by 18.94 square feet to have the same impact as a 1-square-foot increase in home size.</p>
</section>
</section>
<section id="question-2" class="level1">
<h1>Question 2</h1>
<p>(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</p>
<section id="a-1" class="level2">
<h2 class="anchored" data-anchor-id="a-1">A</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: effects</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   degree rank    sex year ysdeg salary
1 Masters Prof   Male   25    35  36350
2 Masters Prof   Male   13    22  35350
3 Masters Prof   Male   10    23  28200
4 Masters Prof Female    7    27  26775
5     PhD Prof   Male   19    30  33696
6 Masters Prof   Male   16    21  28516</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     degree      rank        sex          year            ysdeg      
 Masters:34   Asst :18   Male  :38   Min.   : 0.000   Min.   : 1.00  
 PhD    :18   Assoc:14   Female:14   1st Qu.: 3.000   1st Qu.: 6.75  
              Prof :20               Median : 7.000   Median :15.50  
                                     Mean   : 7.481   Mean   :16.12  
                                     3rd Qu.:11.000   3rd Qu.:23.25  
                                     Max.   :25.000   Max.   :35.00  
     salary     
 Min.   :15000  
 1st Qu.:18247  
 Median :23719  
 Mean   :23798  
 3rd Qu.:27258  
 Max.   :38045  </code></pre>
</div>
</div>
<p>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</p>
<p>To test the hypothesis if the mean salary for men and women is the same, I created a linear regression model for salary with only sex as the explanatory variable.</p>
<p>The null hypothesis is that mean salary men and women is the same - H0: μm = μw</p>
<p>The alternative hypothesis is that the mean salary of men and women is not the same - Ha: μm ≠ μw</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Hypothesis testing with linear regression only</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sex, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8602.8 -4296.6  -100.8  3513.1 16687.9 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    24697        938  26.330   &lt;2e-16 ***
sexFemale      -3340       1808  -1.847   0.0706 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5782 on 50 degrees of freedom
Multiple R-squared:  0.0639,    Adjusted R-squared:  0.04518 
F-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706</code></pre>
</div>
</div>
<p>The resulting coefficient for the sexFemale explanatory variable is -3340, suggesting Female staff make on average $3,340 less than Male professors. In the linear regression model, sexFemale has a p-value of 0.0706 meaning at the 0.05 level we fail to reject the null hypothesis that there is no difference in the mean salaries for men and women. We could however reject the null hypothesis at the 0.1 significance level.</p>
</section>
<section id="b-1" class="level2">
<h2 class="anchored" data-anchor-id="b-1">B</h2>
<p>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">##95% confidence interval</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> ysdeg <span class="sc">+</span> year, <span class="at">data =</span> salary) <span class="sc">|&gt;</span> <span class="fu">confint</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept) 14134.4059 17357.68946
degreePhD    -663.2482  3440.47485
rankAssoc    2985.4107  7599.31080
rankProf     8396.1546 13841.37340
sexFemale    -697.8183  3030.56452
ysdeg        -280.6397    31.49105
year          285.1433   667.47476</code></pre>
</div>
</div>
<p>The 95% confidence interval for the sexFemale is (-663, 3340) which can be interpreted as women making between $663 less or $3340 more than their male colleagues.</p>
<p>Compared to to the coefficient of -3340 in the model with only sex as an explanatory variable, this suggests that controlling for rank, degree, years since degree, and years of experience explains some of the difference between male and female salaries.</p>
</section>
<section id="c-1" class="level2">
<h2 class="anchored" data-anchor-id="c-1">C</h2>
<p>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> ysdeg <span class="sc">+</span> year, <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + ysdeg + year, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
ysdeg        -124.57      77.49  -1.608    0.115    
year          476.31      94.91   5.018 8.65e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>degree PhD has a p=value of 0.180, meaning it is not statistically significant at the 0.1 or 0.05 level. It has a positive coefficient of 1388.61 suggesting that that having a PhD increases a person’s salary by $1388 over having a Master’s degree. This is the 3rd largest coefficient of any of the explanatory variables in the model.</p></li>
<li><p>rankAssoc has as p-value of 3.22 * e^-05, meaning it a statistically significant explanatory variable at the 0.001 level. It has a positive coefficient of 5293.36 suggesting that being an associate professor results in $5292 larger salary than an Assistant professor. This is the 2nd largest coefficient of any of the explanatory variables in the model.</p></li>
<li><p>rankProf has a p-value of 1.62 * e^-10, meaning it is a statistically significant explanatory variable at the 0.001 level. It has a positive coefficient of 11,118, suggesting that having a rank of full professorship results in a salary of $11,118 more than an Assistant professor. This is the largest coefficient of any of the explanatory variables in the model, suggesting it is responsible for the largest change in salary of any variable in the model.</p></li>
<li><p>sexFemale has a p-value of 0.214, meaning it is not statistically significant at the 0.1 or 0.05 level. The coefficient of 1166 suggests that being female increases salary by $1166, which is surprising given the well-known phenomenon of the wage gap.</p></li>
<li><p>ysdeg has a p-value of 0.115, meaning it is not statistically significant at the 0.1 or 0.05 level. The coefficient of -124 suggests that every year since getting a degree, an individual’s salary decreases by $124.</p></li>
<li><p>year has a p-value of 8.65 * e^-06, meaning it is statistically significant at the 0.001 level. The coefficient of 476 suggests that that every year someone is in their job as a professor, their salary increases by $476.</p></li>
</ul>
</section>
<section id="d" class="level2">
<h2 class="anchored" data-anchor-id="d">D</h2>
<p>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Relevel </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">'Prof'</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> ysdeg <span class="sc">+</span> year, <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + ysdeg + year, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  26864.81    1375.29  19.534  &lt; 2e-16 ***
degreePhD     1388.61    1018.75   1.363    0.180    
rankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***
rankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***
sexFemale     1166.37     925.57   1.260    0.214    
ysdeg         -124.57      77.49  -1.608    0.115    
year           476.31      94.91   5.018 8.65e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>After re-leveling the rank to Prof instead of Assistant professor and re-running the linear regression model, rankAsst now has a coefficient of -11118 and rankAssociate has a coefficient of -5826. This means an Assistant professor makes $11,118 less than a full professsor and a an Associate professor makes $5,826 less than a full professors. These are the same coefficients for the rankProf and RankAssoc in the previous model, expect negative, as they now represent the distance from the top rank (professor) as opposed to the lowest rank (assistant).</p>
</section>
<section id="e" class="level2">
<h2 class="anchored" data-anchor-id="e">E</h2>
<p>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “<a href="#a-1">a</a> variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.</p>
<p>Exclude the variable rank, refit, and summarize how your findings changed, if they did.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Rerun model excluding rank</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> ysdeg <span class="sc">+</span> year, <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + ysdeg + year, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
ysdeg         339.40      80.62   4.210 0.000114 ***
year          351.97     142.48   2.470 0.017185 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>Rerunning the model excluding rank changes the coefficient of sexFemale to negative -1286, from previously being positive +1166. However, with a p-value of 0.332 the explanatory variable of sexFemale is still not statistically significant at any level after removing rank.</p>
</section>
<section id="f" class="level2">
<h2 class="anchored" data-anchor-id="f">F</h2>
<p>Everyone in this data set was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the data set who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</p>
<p>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</p>
<p>I created a new variable “New_Dean” where anyone who earned their highest degree (ysdeg) over 15 years ago are coded as a 0 &amp; anyone who earned their highest degree (ysdeg) 15 or less years ago coded as a 1.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#recreating new variable</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>salary_Dean <span class="ot">&lt;-</span> salary <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">New_Dean =</span> <span class="fu">case_when</span>(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    ysdeg <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">"0"</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">"1"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in salary %&gt;% mutate(New_Dean = case_when(ysdeg &gt; 15 ~ "0", ysdeg &lt;= : could not find function "%&gt;%"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>salary_Dean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'salary_Dean' not found</code></pre>
</div>
</div>
<p>Multicollinearity occurs when one explanatory variable is predicted by another variable in the model to a substantial degree. This can be caused by an explanatory variable is a combination of another variable in the model or there are two almost identical variables in the model.</p>
<p>To avoid multicollinearity in this model while testing if being hired by the New Dean results in a higher salary, I will not include ysdeg in the linear regression model. This is because the New Dean explanatory variable was created from the ysdeg model, meaning that they are likely substantially correlated.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Testing New Dean Hypothesis after removing ysdeg</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> New_Dean <span class="sc">+</span> year, <span class="at">data =</span> salary_Dean))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in is.data.frame(data): object 'salary_Dean' not found</code></pre>
</div>
</div>
<p>According to the linear regression model, having been hired by the New Dean does result in a higher salary of $2,163, as indicated by the coefficient to this variable. Furthermore, the New Dean explanatory variable is just barely statistically significant at the 0.05 level with a p-value of 0.0496.</p>
</section>
</section>
<section id="question-3" class="level1">
<h1>Question 3</h1>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Load data</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house.selling.price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  case Taxes Beds Baths New  Price Size
1    1  3104    4     2   0 279900 2048
2    2  1173    2     1   0 146500  912
3    3  3076    4     2   0 237700 1654
4    4  1608    3     2   0 200000 2068
5    5  1454    3     3   0 159900 1477
6    6  2997    3     2   1 499900 3153</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(house.selling.price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      case            Taxes           Beds       Baths           New      
 Min.   :  1.00   Min.   :  20   Min.   :2   Min.   :1.00   Min.   :0.00  
 1st Qu.: 25.75   1st Qu.:1178   1st Qu.:3   1st Qu.:2.00   1st Qu.:0.00  
 Median : 50.50   Median :1614   Median :3   Median :2.00   Median :0.00  
 Mean   : 50.50   Mean   :1908   Mean   :3   Mean   :1.96   Mean   :0.11  
 3rd Qu.: 75.25   3rd Qu.:2238   3rd Qu.:3   3rd Qu.:2.00   3rd Qu.:0.00  
 Max.   :100.00   Max.   :6627   Max.   :5   Max.   :4.00   Max.   :1.00  
     Price             Size     
 Min.   : 21000   Min.   : 580  
 1st Qu.: 93225   1st Qu.:1215  
 Median :132600   Median :1474  
 Mean   :155331   Mean   :1629  
 3rd Qu.:169625   3rd Qu.:1865  
 Max.   :587000   Max.   :4050  </code></pre>
</div>
</div>
<section id="a-2" class="level2">
<h2 class="anchored" data-anchor-id="a-2">A</h2>
<p>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression model y = selling price, explanatory variables = Size &amp; New</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p><em>Size</em> of a house statistically significant at the 0.0001 level with a p-value less than 2 * e^-16. The coefficient of the Size variable is 116 suggesting that for every square-foot the size of a house increases, the predicted price increases by $116.</p></li>
<li><p><em>New</em> The newness of a house is statistically significant at the 0.05 level with a p-value of 0.00257. The coefficient of 57735 suggests that the predicted price of a new house is $57736.283 more than a house than is not new.</p></li>
</ul>
</section>
<section id="b-2" class="level2">
<h2 class="anchored" data-anchor-id="b-2">B</h2>
<p>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</p>
<p>Y = -40230.867 + 116.132(x1) + 57726.263(x2)</p>
<p>where x1 = size of house in square feet, x2 = if a house is new (1 = yes, 0 = no)</p>
<p>This prediction equation can be interpreted that the predicted price of a house in $ can be calculated by multiplying the size of the house in square feet by ~ $116, subtracting the intercept of -$40,230 from the price, and adding $57,726 if the house is new.</p>
<p>Seperate equations for the selling price for new and not new houses can be generated by subbing in x2 =1 for new houses and x2 =0 for not new houses and calculating the resulting equation</p>
<p>Ynew house = -40230.867 + 116.132(x1) + 57726.263(1) = -40,230.867 + 57,726.263 + 116.132 (x1) <em>Ynew house = 17495.4 + 116.132(x1)</em> <em>where x1 = size of house in square-feet</em></p>
<p>This equation can be interpreted as the Predicted Price of a new house in dollars can be calculated from $17;495 + $116 for every square foot in size the house is.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#substraction of intercepts</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fl">57726.263</span> <span class="sc">-</span> <span class="fl">40230.867</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17495.4</code></pre>
</div>
</div>
<p>Ynot new = -40230.867 + 116.132(x1) + 57726.263(0) = -40230.867 + 116.132(x1) + 0</p>
<p>*Ynotnew = -40230.867 + 116.132(x1) ** <em>where x1 = size of house in square-feet</em></p>
<p>This equation can be interpreted as the price of a not-new house in dollars is calculated as $116 for every square-foot a house increases in size, minus $40,230.</p>
</section>
<section id="c-2" class="level2">
<h2 class="anchored" data-anchor-id="c-2">C</h2>
<p>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</p>
<ol type="i">
<li>for a new house where x1 = 3000 Y = 17495.4 + 116.132(x1) Y = 17495.4 + 116.132 (3000)</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Arithmitic</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fl">116.132</span> <span class="sc">*</span> <span class="dv">3000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 348396</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="dv">348396</span> <span class="sc">+</span> <span class="fl">17495.4</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 365891.4</code></pre>
</div>
</div>
<p>Y = 17495.4 + 34896 Y = 365891.4 <em>The predicted price of a new house with a size of 3000 square feet is $365,891.4</em></p>
<ol start="2" type="i">
<li>For a non-new house where x1 = 3000 Y = -40230.867 + 116.132(x1) Y = = -40230.867 + 116.132(3000)</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Arithmetic</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fl">116.132</span> <span class="sc">*</span> <span class="dv">3000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 348396</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="dv">348396</span> <span class="sc">-</span> <span class="fl">40230.867</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 308165.1</code></pre>
</div>
</div>
<pre><code>Y = -40230.867 + 348396
Y = 308165.1</code></pre>
<p><em>The predicted price of a not new house with a size of 3000 square feet is $308,165.1</em></p>
</section>
<section id="d-1" class="level2">
<h2 class="anchored" data-anchor-id="d-1">D</h2>
<p>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression model y = selling price, explanatory variables = Interaction Size * New</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">*</span> New, <span class="at">data =</span> house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size * New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In the model with the interaction between Size * New, the Adjusted R-squared of the model is 0.7363 as opposed to the model with Size &amp; New as explanatory variables without an interaction, which had an adjusted R-squared of 0.7169. In the interaction model:</p>
<ul>
<li><p><em>Size</em> has a p-value of less than 2*e-^16, being statistically significant at the 0.05 level. The coefficient of 104.438 suggest that the price of the house increases $104 for every square foot a house increases in size</p></li>
<li><p><em>New</em> has a p-value of 0.12697, not being statistically significant at the 0.05 or 0.1 levels. The coefficient of -78527.502 suggests that if a house is new, regardless of size, the predicted price of the house decreases by $78527. In the previous model without the interaction between new &amp; size, new had a positive coefficient and was statistically significant.</p></li>
<li><p><em>Size x New</em> has a p-value of 0.00527, which is statistically significant at the 0.01 level. This suggests there is a interaction between the newness of a house and the size of a house. The coefficient of 61.916 suggests the predicted price of only new houses increases by $61.9 for each square foot the size of the house increases.</p></li>
</ul>
<p>Written out as an equation for predicted price, where x1 = size of house in square feet &amp; x2 = newness of house</p>
<p><em>Y = -22227.808 + 104.438(x1) - 78527.502(x2) + 61.916(x1)(x2)</em></p>
</section>
<section id="e-1" class="level2">
<h2 class="anchored" data-anchor-id="e-1">E</h2>
<p>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</p>
<ul>
<li><ol type="i">
<li>new, x2 = 1. Plugging that into the prediction equation: Y = -22227.808 + 104.438(x1) - 78527.502(x2) + 61.916(x1)(x2) Y = -22227.808 + 104.438(x1) - 78527.502(1) + 61.916(x1)(1) Y = -22227.808 + 104.438(x1) - 78527.502 + 61.916(x1)</li>
</ol></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Arithmetic</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">-</span><span class="fl">78527.502</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -100755.3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fl">104.438</span> <span class="sc">+</span> <span class="fl">61.916</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 166.354</code></pre>
</div>
</div>
<p><em>Ynew = -100755.3 + 166.354(x1)</em></p>
<ul>
<li><ol start="2" type="i">
<li>not new, x2 = 0. Plugging that into the prediction equation: Y = -22227.808 + 104.438(x1) - 78527.502(0) + 61.916(x1)(0) Y = -22227.808 + 104.438(x1) - 0 + 0 <em>Ynotnew = -22227.808 + 104.438(x1)</em></li>
</ol></li>
</ul>
</section>
<section id="f-1" class="level2">
<h2 class="anchored" data-anchor-id="f-1">F</h2>
<p>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</p>
<ul>
<li><ol type="i">
<li>new, x1 = 3000 square feet Ynew = -100755.3 + 166.354(x1) Ynew = -100755.3 + 166.354(3000)</li>
</ol></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fl">166.354</span> <span class="sc">*</span> <span class="dv">3000</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 499062</code></pre>
</div>
</div>
<p>Ynew = -100755.3 + 499062</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">100755.3</span> <span class="sc">+</span> <span class="dv">499062</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 398306.7</code></pre>
</div>
</div>
<p>Ynew = 398306.7 <em>The predicted selling price of a new house 3000 square feet in size is $398306.7</em></p>
<ul>
<li><ol start="2" type="i">
<li>not new, x1 = 3000 square feet Ynotnew = -22227.808 + 104.438(x1) Ynotnew = -22227.808 + 104.438(3000)</li>
</ol></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fl">104.438</span> <span class="sc">*</span> <span class="dv">3000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 313314</code></pre>
</div>
</div>
<p>Ynotnew = -22227.808 + 313314</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="dv">313314</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 291086.2</code></pre>
</div>
</div>
<p>Ynotnew = 291086.2 <em>The predicted selling price of a not new house 3000 square feet in size is $291,086.2</em></p>
</section>
<section id="g" class="level2">
<h2 class="anchored" data-anchor-id="g">G</h2>
<p>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</p>
<ul>
<li><ol type="i">
<li>new, x1 = 1500 square feet Ynew = -100755.3 + 166.354(x1) Ynew = -100755.3 + 166.354(1500)</li>
</ol></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fl">166.354</span> <span class="sc">*</span> <span class="dv">1500</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 249531</code></pre>
</div>
</div>
<p>Ynew = -100755.3 + 249531</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">100755.3</span> <span class="sc">+</span> <span class="dv">249531</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 148775.7</code></pre>
</div>
</div>
<p>Ynew = 148775.7</p>
<p><em>The predicted selling price of a new house 1500 square feet in size is $148,775.7</em></p>
<ul>
<li><ol start="2" type="i">
<li>not new, x1 = 1500 square feet Ynotnew = -22227.808 + 104.438(x1) Ynotnew = -22227.808 + 104.438(1500)</li>
</ol></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a> <span class="fl">104.438</span> <span class="sc">*</span> <span class="dv">1500</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 156657</code></pre>
</div>
</div>
<p>Ynotnew = -22227.808 + 156657</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="dv">156657</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 134429.2</code></pre>
</div>
</div>
<p>Ynotnew = 134429.2 <em>The predicted selling price of a not new house 1500 square feet in size is $ 134429.2</em></p>
<ul>
<li>Difference in prices new &amp; not new by size</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Difference new, not new x1 = 3000 square feet</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fl">398306.7</span> <span class="sc">-</span> <span class="fl">291086.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107220.5</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Difference new, not new x1 = 1500 square feet</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a> <span class="fl">148775.7</span> <span class="sc">-</span> <span class="fl">134429.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14346.5</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Division </span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fl">107220.5</span><span class="sc">/</span><span class="fl">14346.5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.473635</code></pre>
</div>
</div>
<p>The difference between the price of a new &amp; not house 3000 feet in size is $107,220.5</p>
<p>The difference between the price of a new &amp; not new house 1500 feet in size is $14,346.5</p>
<p>A house that is 3000 square feet in size is twice the size of a house 1500 square feet in size, the difference between a new &amp; not new houses is 7.473635x more for a house that is 3000 square feet than a house that is 15000 square feet in size. This suggests that the larger the size of a house the more influence the newness of a house has on price.</p>
</section>
<section id="h" class="level2">
<h2 class="anchored" data-anchor-id="h">H</h2>
<p>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</p>
<p>Based on the statistical significance of the interaction between New:Size at the 0.001 level &amp; the higher Adjusted R-Squared of the model with the interaction term 0.7363) than the adjusted R-squared of the model without the interaction term (0.7169) both make me prefer the model with the interacction term over the other interms of best representing the relationship of size and new to the outcome price.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb77" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 4"</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Emma Narkewicz"</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Emma Narkewicz HW4"</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/01/2023"</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw4</span></span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - linear regression</span></span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - emma_narkewicz</span></span>
<span id="cb77-16"><a href="#cb77-16" aria-hidden="true" tabindex="-1"></a><span class="an">editor:</span><span class="co"> </span></span>
<span id="cb77-17"><a href="#cb77-17" aria-hidden="true" tabindex="-1"></a><span class="co">  markdown: </span></span>
<span id="cb77-18"><a href="#cb77-18" aria-hidden="true" tabindex="-1"></a><span class="co">    wrap: 72</span></span>
<span id="cb77-19"><a href="#cb77-19" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb77-20"><a href="#cb77-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-21"><a href="#cb77-21" aria-hidden="true" tabindex="-1"></a><span class="fu"># Question 1</span></span>
<span id="cb77-22"><a href="#cb77-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-23"><a href="#cb77-23" aria-hidden="true" tabindex="-1"></a>For recent data in Jacksonville, Florida, on y = selling price of home</span>
<span id="cb77-24"><a href="#cb77-24" aria-hidden="true" tabindex="-1"></a>(in dollars), x1 = size of home (in square feet), and x2 = lot size (in</span>
<span id="cb77-25"><a href="#cb77-25" aria-hidden="true" tabindex="-1"></a>square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.</span>
<span id="cb77-26"><a href="#cb77-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-27"><a href="#cb77-27" aria-hidden="true" tabindex="-1"></a><span class="fu">## A</span></span>
<span id="cb77-28"><a href="#cb77-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-29"><a href="#cb77-29" aria-hidden="true" tabindex="-1"></a>A particular home of 1240 square feet on a lot of 18,000 square feet</span>
<span id="cb77-30"><a href="#cb77-30" aria-hidden="true" tabindex="-1"></a>sold for \$145,000. Find the predicted selling price and the residual,</span>
<span id="cb77-31"><a href="#cb77-31" aria-hidden="true" tabindex="-1"></a>and interpret.</span>
<span id="cb77-32"><a href="#cb77-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-33"><a href="#cb77-33" aria-hidden="true" tabindex="-1"></a>To solve for the predicted price, I plugged in x1 = 1,240 &amp; x2 = 18,000</span>
<span id="cb77-34"><a href="#cb77-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-37"><a href="#cb77-37" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-38"><a href="#cb77-38" aria-hidden="true" tabindex="-1"></a><span class="co">#Predicted Price</span></span>
<span id="cb77-39"><a href="#cb77-39" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> (<span class="fl">53.8</span> <span class="sc">*</span> <span class="dv">1240</span>) <span class="sc">+</span> (<span class="fl">2.84</span> <span class="sc">*</span> <span class="dv">18000</span>)  </span>
<span id="cb77-40"><a href="#cb77-40" aria-hidden="true" tabindex="-1"></a>pp</span>
<span id="cb77-41"><a href="#cb77-41" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-42"><a href="#cb77-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-43"><a href="#cb77-43" aria-hidden="true" tabindex="-1"></a>From the equation, the predicted selling price of the house is \$107,296</span>
<span id="cb77-44"><a href="#cb77-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-45"><a href="#cb77-45" aria-hidden="true" tabindex="-1"></a>The residual can be calculated using the equation:</span>
<span id="cb77-46"><a href="#cb77-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-47"><a href="#cb77-47" aria-hidden="true" tabindex="-1"></a>Residual = (actual y-value) - (predicted y value)</span>
<span id="cb77-48"><a href="#cb77-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-51"><a href="#cb77-51" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-52"><a href="#cb77-52" aria-hidden="true" tabindex="-1"></a><span class="co">#Residual</span></span>
<span id="cb77-53"><a href="#cb77-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-54"><a href="#cb77-54" aria-hidden="true" tabindex="-1"></a>R <span class="ot">=</span> <span class="dv">145000</span> <span class="sc">-</span> <span class="dv">107296</span></span>
<span id="cb77-55"><a href="#cb77-55" aria-hidden="true" tabindex="-1"></a>R</span>
<span id="cb77-56"><a href="#cb77-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-57"><a href="#cb77-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-58"><a href="#cb77-58" aria-hidden="true" tabindex="-1"></a>The residual of positive \$37,704 indicates that the house sold for more</span>
<span id="cb77-59"><a href="#cb77-59" aria-hidden="true" tabindex="-1"></a>than the model predicted, meaning the model under-predicted the selling</span>
<span id="cb77-60"><a href="#cb77-60" aria-hidden="true" tabindex="-1"></a>price.</span>
<span id="cb77-61"><a href="#cb77-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-62"><a href="#cb77-62" aria-hidden="true" tabindex="-1"></a><span class="fu">## B</span></span>
<span id="cb77-63"><a href="#cb77-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-64"><a href="#cb77-64" aria-hidden="true" tabindex="-1"></a>For fixed lot size, how much is the house selling price predicted to</span>
<span id="cb77-65"><a href="#cb77-65" aria-hidden="true" tabindex="-1"></a>increase for each square- foot increase in home size? Why?</span>
<span id="cb77-66"><a href="#cb77-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-67"><a href="#cb77-67" aria-hidden="true" tabindex="-1"></a>Based on the prediction equation for a fixed lot size (x2), the price of</span>
<span id="cb77-68"><a href="#cb77-68" aria-hidden="true" tabindex="-1"></a>the house is expected to increase \$53.8 dollars for each square foot of</span>
<span id="cb77-69"><a href="#cb77-69" aria-hidden="true" tabindex="-1"></a>house size. This is because with a fixed lot size (x2) t the 53.8x1 in</span>
<span id="cb77-70"><a href="#cb77-70" aria-hidden="true" tabindex="-1"></a>the prediction equation explains the increase in house price per each</span>
<span id="cb77-71"><a href="#cb77-71" aria-hidden="true" tabindex="-1"></a>square foot of house size</span>
<span id="cb77-72"><a href="#cb77-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-73"><a href="#cb77-73" aria-hidden="true" tabindex="-1"></a>ŷ = −10,536 + 53.8x1 + 2.84x2.</span>
<span id="cb77-74"><a href="#cb77-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-75"><a href="#cb77-75" aria-hidden="true" tabindex="-1"></a><span class="fu">## C</span></span>
<span id="cb77-76"><a href="#cb77-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-77"><a href="#cb77-77" aria-hidden="true" tabindex="-1"></a>According to this prediction equation, for fixed home size, how much</span>
<span id="cb77-78"><a href="#cb77-78" aria-hidden="true" tabindex="-1"></a>would lot size need to increase to have the same impact as a</span>
<span id="cb77-79"><a href="#cb77-79" aria-hidden="true" tabindex="-1"></a>one-square-foot increase in home size?</span>
<span id="cb77-80"><a href="#cb77-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-81"><a href="#cb77-81" aria-hidden="true" tabindex="-1"></a>Home size = x1 = 1 Lot size = x2</span>
<span id="cb77-82"><a href="#cb77-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-83"><a href="#cb77-83" aria-hidden="true" tabindex="-1"></a>53.81 (x1) = 2.84x2 53.8 = 2.84x2</span>
<span id="cb77-84"><a href="#cb77-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-87"><a href="#cb77-87" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-88"><a href="#cb77-88" aria-hidden="true" tabindex="-1"></a><span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span>
<span id="cb77-89"><a href="#cb77-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-90"><a href="#cb77-90" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-91"><a href="#cb77-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-92"><a href="#cb77-92" aria-hidden="true" tabindex="-1"></a>Based on the prediction equation, the lot size would need to increase by</span>
<span id="cb77-93"><a href="#cb77-93" aria-hidden="true" tabindex="-1"></a>18.94 square feet to have the same impact as a 1-square-foot increase in</span>
<span id="cb77-94"><a href="#cb77-94" aria-hidden="true" tabindex="-1"></a>home size.</span>
<span id="cb77-95"><a href="#cb77-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-96"><a href="#cb77-96" aria-hidden="true" tabindex="-1"></a><span class="fu"># Question 2</span></span>
<span id="cb77-97"><a href="#cb77-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-98"><a href="#cb77-98" aria-hidden="true" tabindex="-1"></a>(Data file: salary in alr4 R package). The data file concerns salary and</span>
<span id="cb77-99"><a href="#cb77-99" aria-hidden="true" tabindex="-1"></a>other characteristics of all faculty in a small Midwestern college</span>
<span id="cb77-100"><a href="#cb77-100" aria-hidden="true" tabindex="-1"></a>collected in the early 1980s for presentation in legal proceedings for</span>
<span id="cb77-101"><a href="#cb77-101" aria-hidden="true" tabindex="-1"></a>which discrimination against women in salary was at issue. All persons</span>
<span id="cb77-102"><a href="#cb77-102" aria-hidden="true" tabindex="-1"></a>in the data hold tenured or tenure track positions; temporary faculty</span>
<span id="cb77-103"><a href="#cb77-103" aria-hidden="true" tabindex="-1"></a>are not included. The variables include degree, a factor with levels PhD</span>
<span id="cb77-104"><a href="#cb77-104" aria-hidden="true" tabindex="-1"></a>and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor</span>
<span id="cb77-105"><a href="#cb77-105" aria-hidden="true" tabindex="-1"></a>with levels Male and Female; Year, years in current rank; ysdeg, years</span>
<span id="cb77-106"><a href="#cb77-106" aria-hidden="true" tabindex="-1"></a>since highest degree, and salary, academic year salary in dollars.</span>
<span id="cb77-107"><a href="#cb77-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-108"><a href="#cb77-108" aria-hidden="true" tabindex="-1"></a><span class="fu">## A {#a-1}</span></span>
<span id="cb77-109"><a href="#cb77-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-112"><a href="#cb77-112" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-113"><a href="#cb77-113" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb77-114"><a href="#cb77-114" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(salary)</span>
<span id="cb77-115"><a href="#cb77-115" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salary)</span>
<span id="cb77-116"><a href="#cb77-116" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-117"><a href="#cb77-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-118"><a href="#cb77-118" aria-hidden="true" tabindex="-1"></a>Test the hypothesis that the mean salary for men and women is the same,</span>
<span id="cb77-119"><a href="#cb77-119" aria-hidden="true" tabindex="-1"></a>without regard to any other variable but sex. Explain your findings.</span>
<span id="cb77-120"><a href="#cb77-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-121"><a href="#cb77-121" aria-hidden="true" tabindex="-1"></a>To test the hypothesis if the mean salary for men and women is the same,</span>
<span id="cb77-122"><a href="#cb77-122" aria-hidden="true" tabindex="-1"></a>I created a linear regression model for salary with only sex as the</span>
<span id="cb77-123"><a href="#cb77-123" aria-hidden="true" tabindex="-1"></a>explanatory variable.</span>
<span id="cb77-124"><a href="#cb77-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-125"><a href="#cb77-125" aria-hidden="true" tabindex="-1"></a>The null hypothesis is that mean salary men and women is the same - H0:</span>
<span id="cb77-126"><a href="#cb77-126" aria-hidden="true" tabindex="-1"></a>μm = μw</span>
<span id="cb77-127"><a href="#cb77-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-128"><a href="#cb77-128" aria-hidden="true" tabindex="-1"></a>The alternative hypothesis is that the mean salary of men and women is</span>
<span id="cb77-129"><a href="#cb77-129" aria-hidden="true" tabindex="-1"></a>not the same - Ha: μm ≠ μw</span>
<span id="cb77-130"><a href="#cb77-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-133"><a href="#cb77-133" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-134"><a href="#cb77-134" aria-hidden="true" tabindex="-1"></a><span class="do">##Hypothesis testing with linear regression only</span></span>
<span id="cb77-135"><a href="#cb77-135" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> salary))</span>
<span id="cb77-136"><a href="#cb77-136" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-137"><a href="#cb77-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-138"><a href="#cb77-138" aria-hidden="true" tabindex="-1"></a>The resulting coefficient for the sexFemale explanatory variable is</span>
<span id="cb77-139"><a href="#cb77-139" aria-hidden="true" tabindex="-1"></a>-3340, suggesting Female staff make on average \$3,340 less than Male</span>
<span id="cb77-140"><a href="#cb77-140" aria-hidden="true" tabindex="-1"></a>professors. In the linear regression model, sexFemale has a p-value of</span>
<span id="cb77-141"><a href="#cb77-141" aria-hidden="true" tabindex="-1"></a>0.0706 meaning at the 0.05 level we fail to reject the null hypothesis</span>
<span id="cb77-142"><a href="#cb77-142" aria-hidden="true" tabindex="-1"></a>that there is no difference in the mean salaries for men and women. We</span>
<span id="cb77-143"><a href="#cb77-143" aria-hidden="true" tabindex="-1"></a>could however reject the null hypothesis at the 0.1 significance level.</span>
<span id="cb77-144"><a href="#cb77-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-145"><a href="#cb77-145" aria-hidden="true" tabindex="-1"></a><span class="fu">## B</span></span>
<span id="cb77-146"><a href="#cb77-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-147"><a href="#cb77-147" aria-hidden="true" tabindex="-1"></a>Run a multiple linear regression with salary as the outcome variable and</span>
<span id="cb77-148"><a href="#cb77-148" aria-hidden="true" tabindex="-1"></a>everything else as predictors, including sex. Assuming no interactions</span>
<span id="cb77-149"><a href="#cb77-149" aria-hidden="true" tabindex="-1"></a>between sex and the other predictors, obtain a 95% confidence interval</span>
<span id="cb77-150"><a href="#cb77-150" aria-hidden="true" tabindex="-1"></a>for the difference in salary between males and females.</span>
<span id="cb77-151"><a href="#cb77-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-154"><a href="#cb77-154" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-155"><a href="#cb77-155" aria-hidden="true" tabindex="-1"></a><span class="do">##95% confidence interval</span></span>
<span id="cb77-156"><a href="#cb77-156" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> ysdeg <span class="sc">+</span> year, <span class="at">data =</span> salary) <span class="sc">|&gt;</span> <span class="fu">confint</span>()</span>
<span id="cb77-157"><a href="#cb77-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-158"><a href="#cb77-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-159"><a href="#cb77-159" aria-hidden="true" tabindex="-1"></a>The 95% confidence interval for the sexFemale is (-663, 3340) which can</span>
<span id="cb77-160"><a href="#cb77-160" aria-hidden="true" tabindex="-1"></a>be interpreted as women making between \$663 less or \$3340 more than</span>
<span id="cb77-161"><a href="#cb77-161" aria-hidden="true" tabindex="-1"></a>their male colleagues.</span>
<span id="cb77-162"><a href="#cb77-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-163"><a href="#cb77-163" aria-hidden="true" tabindex="-1"></a>Compared to to the coefficient of -3340 in the model with only sex as an</span>
<span id="cb77-164"><a href="#cb77-164" aria-hidden="true" tabindex="-1"></a>explanatory variable, this suggests that controlling for rank, degree,</span>
<span id="cb77-165"><a href="#cb77-165" aria-hidden="true" tabindex="-1"></a>years since degree, and years of experience explains some of the</span>
<span id="cb77-166"><a href="#cb77-166" aria-hidden="true" tabindex="-1"></a>difference between male and female salaries.</span>
<span id="cb77-167"><a href="#cb77-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-168"><a href="#cb77-168" aria-hidden="true" tabindex="-1"></a><span class="fu">## C</span></span>
<span id="cb77-169"><a href="#cb77-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-170"><a href="#cb77-170" aria-hidden="true" tabindex="-1"></a>Interpret your finding for each predictor variable; discuss (a)</span>
<span id="cb77-171"><a href="#cb77-171" aria-hidden="true" tabindex="-1"></a>statistical significance, (b) interpretation of the coefficient / slope</span>
<span id="cb77-172"><a href="#cb77-172" aria-hidden="true" tabindex="-1"></a>in relation to the outcome variable and other variables</span>
<span id="cb77-173"><a href="#cb77-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-176"><a href="#cb77-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-177"><a href="#cb77-177" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> ysdeg <span class="sc">+</span> year, <span class="at">data =</span> salary))</span>
<span id="cb77-178"><a href="#cb77-178" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-179"><a href="#cb77-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-180"><a href="#cb77-180" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>degree PhD has a p=value of 0.180, meaning it is not statistically</span>
<span id="cb77-181"><a href="#cb77-181" aria-hidden="true" tabindex="-1"></a>    significant at the 0.1 or 0.05 level. It has a positive coefficient</span>
<span id="cb77-182"><a href="#cb77-182" aria-hidden="true" tabindex="-1"></a>    of 1388.61 suggesting that that having a PhD increases a person's</span>
<span id="cb77-183"><a href="#cb77-183" aria-hidden="true" tabindex="-1"></a>    salary by \$1388 over having a Master's degree. This is the 3rd</span>
<span id="cb77-184"><a href="#cb77-184" aria-hidden="true" tabindex="-1"></a>    largest coefficient of any of the explanatory variables in the</span>
<span id="cb77-185"><a href="#cb77-185" aria-hidden="true" tabindex="-1"></a>    model.</span>
<span id="cb77-186"><a href="#cb77-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-187"><a href="#cb77-187" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>rankAssoc has as p-value of 3.22 <span class="sc">\*</span> e\^-05, meaning it a</span>
<span id="cb77-188"><a href="#cb77-188" aria-hidden="true" tabindex="-1"></a>    statistically significant explanatory variable at the 0.001 level.</span>
<span id="cb77-189"><a href="#cb77-189" aria-hidden="true" tabindex="-1"></a>    It has a positive coefficient of 5293.36 suggesting that being an</span>
<span id="cb77-190"><a href="#cb77-190" aria-hidden="true" tabindex="-1"></a>    associate professor results in \$5292 larger salary than an</span>
<span id="cb77-191"><a href="#cb77-191" aria-hidden="true" tabindex="-1"></a>    Assistant professor. This is the 2nd largest coefficient of any of</span>
<span id="cb77-192"><a href="#cb77-192" aria-hidden="true" tabindex="-1"></a>    the explanatory variables in the model.</span>
<span id="cb77-193"><a href="#cb77-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-194"><a href="#cb77-194" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>rankProf has a p-value of 1.62 <span class="sc">\*</span> e\^-10, meaning it is a</span>
<span id="cb77-195"><a href="#cb77-195" aria-hidden="true" tabindex="-1"></a>    statistically significant explanatory variable at the 0.001 level.</span>
<span id="cb77-196"><a href="#cb77-196" aria-hidden="true" tabindex="-1"></a>    It has a positive coefficient of 11,118, suggesting that having a</span>
<span id="cb77-197"><a href="#cb77-197" aria-hidden="true" tabindex="-1"></a>    rank of full professorship results in a salary of \$11,118 more than</span>
<span id="cb77-198"><a href="#cb77-198" aria-hidden="true" tabindex="-1"></a>    an Assistant professor. This is the largest coefficient of any of</span>
<span id="cb77-199"><a href="#cb77-199" aria-hidden="true" tabindex="-1"></a>    the explanatory variables in the model, suggesting it is responsible</span>
<span id="cb77-200"><a href="#cb77-200" aria-hidden="true" tabindex="-1"></a>    for the largest change in salary of any variable in the model.</span>
<span id="cb77-201"><a href="#cb77-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-202"><a href="#cb77-202" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>sexFemale has a p-value of 0.214, meaning it is not statistically</span>
<span id="cb77-203"><a href="#cb77-203" aria-hidden="true" tabindex="-1"></a>    significant at the 0.1 or 0.05 level. The coefficient of 1166</span>
<span id="cb77-204"><a href="#cb77-204" aria-hidden="true" tabindex="-1"></a>    suggests that being female increases salary by \$1166, which is</span>
<span id="cb77-205"><a href="#cb77-205" aria-hidden="true" tabindex="-1"></a>    surprising given the well-known phenomenon of the wage gap.</span>
<span id="cb77-206"><a href="#cb77-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-207"><a href="#cb77-207" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>ysdeg has a p-value of 0.115, meaning it is not statistically</span>
<span id="cb77-208"><a href="#cb77-208" aria-hidden="true" tabindex="-1"></a>    significant at the 0.1 or 0.05 level. The coefficient of -124</span>
<span id="cb77-209"><a href="#cb77-209" aria-hidden="true" tabindex="-1"></a>    suggests that every year since getting a degree, an individual's</span>
<span id="cb77-210"><a href="#cb77-210" aria-hidden="true" tabindex="-1"></a>    salary decreases by \$124.</span>
<span id="cb77-211"><a href="#cb77-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-212"><a href="#cb77-212" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>year has a p-value of 8.65 <span class="sc">\*</span> e\^-06, meaning it is statistically</span>
<span id="cb77-213"><a href="#cb77-213" aria-hidden="true" tabindex="-1"></a>    significant at the 0.001 level. The coefficient of 476 suggests that</span>
<span id="cb77-214"><a href="#cb77-214" aria-hidden="true" tabindex="-1"></a>    that every year someone is in their job as a professor, their salary</span>
<span id="cb77-215"><a href="#cb77-215" aria-hidden="true" tabindex="-1"></a>    increases by \$476.</span>
<span id="cb77-216"><a href="#cb77-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-217"><a href="#cb77-217" aria-hidden="true" tabindex="-1"></a><span class="fu">## D</span></span>
<span id="cb77-218"><a href="#cb77-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-219"><a href="#cb77-219" aria-hidden="true" tabindex="-1"></a>Change the baseline category for the rank variable. Interpret the</span>
<span id="cb77-220"><a href="#cb77-220" aria-hidden="true" tabindex="-1"></a>coefficients related to rank again.</span>
<span id="cb77-221"><a href="#cb77-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-224"><a href="#cb77-224" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-225"><a href="#cb77-225" aria-hidden="true" tabindex="-1"></a><span class="co">#Relevel </span></span>
<span id="cb77-226"><a href="#cb77-226" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">'Prof'</span>)</span>
<span id="cb77-227"><a href="#cb77-227" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> ysdeg <span class="sc">+</span> year, <span class="at">data =</span> salary))</span>
<span id="cb77-228"><a href="#cb77-228" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-229"><a href="#cb77-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-230"><a href="#cb77-230" aria-hidden="true" tabindex="-1"></a>After re-leveling the rank to Prof instead of Assistant professor and</span>
<span id="cb77-231"><a href="#cb77-231" aria-hidden="true" tabindex="-1"></a>re-running the linear regression model, rankAsst now has a coefficient</span>
<span id="cb77-232"><a href="#cb77-232" aria-hidden="true" tabindex="-1"></a>of -11118 and rankAssociate has a coefficient of -5826. This means an</span>
<span id="cb77-233"><a href="#cb77-233" aria-hidden="true" tabindex="-1"></a>Assistant professor makes \$11,118 less than a full professsor and a an</span>
<span id="cb77-234"><a href="#cb77-234" aria-hidden="true" tabindex="-1"></a>Associate professor makes \$5,826 less than a full professors. These are</span>
<span id="cb77-235"><a href="#cb77-235" aria-hidden="true" tabindex="-1"></a>the same coefficients for the rankProf and RankAssoc in the previous</span>
<span id="cb77-236"><a href="#cb77-236" aria-hidden="true" tabindex="-1"></a>model, expect negative, as they now represent the distance from the top</span>
<span id="cb77-237"><a href="#cb77-237" aria-hidden="true" tabindex="-1"></a>rank (professor) as opposed to the lowest rank (assistant).</span>
<span id="cb77-238"><a href="#cb77-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-239"><a href="#cb77-239" aria-hidden="true" tabindex="-1"></a><span class="fu">## E</span></span>
<span id="cb77-240"><a href="#cb77-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-241"><a href="#cb77-241" aria-hidden="true" tabindex="-1"></a>Finkelstein (1980), in a discussion of the use of regression in</span>
<span id="cb77-242"><a href="#cb77-242" aria-hidden="true" tabindex="-1"></a>discrimination cases, wrote, "<span class="co">[</span><span class="ot">a</span><span class="co">](#a-1)</span> variable may reflect a position</span>
<span id="cb77-243"><a href="#cb77-243" aria-hidden="true" tabindex="-1"></a>or status bestowed by the employer, in which case if there is</span>
<span id="cb77-244"><a href="#cb77-244" aria-hidden="true" tabindex="-1"></a>discrimination in the award of the position or status, the variable may</span>
<span id="cb77-245"><a href="#cb77-245" aria-hidden="true" tabindex="-1"></a>be 'tainted.'" Thus, for example, if discrimination is at work in</span>
<span id="cb77-246"><a href="#cb77-246" aria-hidden="true" tabindex="-1"></a>promotion of faculty to higher ranks, using rank to adjust salaries</span>
<span id="cb77-247"><a href="#cb77-247" aria-hidden="true" tabindex="-1"></a>before comparing the sexes may not be acceptable to the courts.</span>
<span id="cb77-248"><a href="#cb77-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-249"><a href="#cb77-249" aria-hidden="true" tabindex="-1"></a>Exclude the variable rank, refit, and summarize how your findings</span>
<span id="cb77-250"><a href="#cb77-250" aria-hidden="true" tabindex="-1"></a>changed, if they did.</span>
<span id="cb77-251"><a href="#cb77-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-254"><a href="#cb77-254" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-255"><a href="#cb77-255" aria-hidden="true" tabindex="-1"></a><span class="co">#Rerun model excluding rank</span></span>
<span id="cb77-256"><a href="#cb77-256" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> ysdeg <span class="sc">+</span> year, <span class="at">data =</span> salary))</span>
<span id="cb77-257"><a href="#cb77-257" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-258"><a href="#cb77-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-259"><a href="#cb77-259" aria-hidden="true" tabindex="-1"></a>Rerunning the model excluding rank changes the coefficient of sexFemale</span>
<span id="cb77-260"><a href="#cb77-260" aria-hidden="true" tabindex="-1"></a>to negative -1286, from previously being positive +1166. However, with a</span>
<span id="cb77-261"><a href="#cb77-261" aria-hidden="true" tabindex="-1"></a>p-value of 0.332 the explanatory variable of sexFemale is still not</span>
<span id="cb77-262"><a href="#cb77-262" aria-hidden="true" tabindex="-1"></a>statistically significant at any level after removing rank.</span>
<span id="cb77-263"><a href="#cb77-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-264"><a href="#cb77-264" aria-hidden="true" tabindex="-1"></a><span class="fu">## F</span></span>
<span id="cb77-265"><a href="#cb77-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-266"><a href="#cb77-266" aria-hidden="true" tabindex="-1"></a>Everyone in this data set was hired the year they earned their highest</span>
<span id="cb77-267"><a href="#cb77-267" aria-hidden="true" tabindex="-1"></a>degree. It is also known that a new Dean was appointed 15 years ago, and</span>
<span id="cb77-268"><a href="#cb77-268" aria-hidden="true" tabindex="-1"></a>everyone in the data set who earned their highest degree 15 years ago or</span>
<span id="cb77-269"><a href="#cb77-269" aria-hidden="true" tabindex="-1"></a>less than that has been hired by the new Dean. Some people have argued</span>
<span id="cb77-270"><a href="#cb77-270" aria-hidden="true" tabindex="-1"></a>that the new Dean has been making offers that are a lot more generous to</span>
<span id="cb77-271"><a href="#cb77-271" aria-hidden="true" tabindex="-1"></a>newly hired faculty than the previous one and that this might explain</span>
<span id="cb77-272"><a href="#cb77-272" aria-hidden="true" tabindex="-1"></a>some of the variation in Salary.</span>
<span id="cb77-273"><a href="#cb77-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-274"><a href="#cb77-274" aria-hidden="true" tabindex="-1"></a>Create a new variable that would allow you to test this hypothesis and</span>
<span id="cb77-275"><a href="#cb77-275" aria-hidden="true" tabindex="-1"></a>run another multiple regression model to test this. Select variables</span>
<span id="cb77-276"><a href="#cb77-276" aria-hidden="true" tabindex="-1"></a>carefully to make sure there is no multicollinearity. Explain why</span>
<span id="cb77-277"><a href="#cb77-277" aria-hidden="true" tabindex="-1"></a>multicollinearity would be a concern in this case and how you avoided</span>
<span id="cb77-278"><a href="#cb77-278" aria-hidden="true" tabindex="-1"></a>it. Do you find support for the hypothesis that the people hired by the</span>
<span id="cb77-279"><a href="#cb77-279" aria-hidden="true" tabindex="-1"></a>new Dean are making higher than those that were not?</span>
<span id="cb77-280"><a href="#cb77-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-281"><a href="#cb77-281" aria-hidden="true" tabindex="-1"></a>I created a new variable "New_Dean" where anyone who earned their</span>
<span id="cb77-282"><a href="#cb77-282" aria-hidden="true" tabindex="-1"></a>highest degree (ysdeg) over 15 years ago are coded as a 0 &amp; anyone who</span>
<span id="cb77-283"><a href="#cb77-283" aria-hidden="true" tabindex="-1"></a>earned their highest degree (ysdeg) 15 or less years ago coded as a 1.</span>
<span id="cb77-284"><a href="#cb77-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-287"><a href="#cb77-287" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-288"><a href="#cb77-288" aria-hidden="true" tabindex="-1"></a><span class="co">#recreating new variable</span></span>
<span id="cb77-289"><a href="#cb77-289" aria-hidden="true" tabindex="-1"></a>salary_Dean <span class="ot">&lt;-</span> salary <span class="sc">%&gt;%</span></span>
<span id="cb77-290"><a href="#cb77-290" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">New_Dean =</span> <span class="fu">case_when</span>(</span>
<span id="cb77-291"><a href="#cb77-291" aria-hidden="true" tabindex="-1"></a>    ysdeg <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">"0"</span>,</span>
<span id="cb77-292"><a href="#cb77-292" aria-hidden="true" tabindex="-1"></a>    ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">"1"</span>))</span>
<span id="cb77-293"><a href="#cb77-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-294"><a href="#cb77-294" aria-hidden="true" tabindex="-1"></a>salary_Dean</span>
<span id="cb77-295"><a href="#cb77-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-296"><a href="#cb77-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-297"><a href="#cb77-297" aria-hidden="true" tabindex="-1"></a>Multicollinearity occurs when one explanatory variable is predicted by</span>
<span id="cb77-298"><a href="#cb77-298" aria-hidden="true" tabindex="-1"></a>another variable in the model to a substantial degree. This can be</span>
<span id="cb77-299"><a href="#cb77-299" aria-hidden="true" tabindex="-1"></a>caused by an explanatory variable is a combination of another variable</span>
<span id="cb77-300"><a href="#cb77-300" aria-hidden="true" tabindex="-1"></a>in the model or there are two almost identical variables in the model.</span>
<span id="cb77-301"><a href="#cb77-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-302"><a href="#cb77-302" aria-hidden="true" tabindex="-1"></a>To avoid multicollinearity in this model while testing if being hired by</span>
<span id="cb77-303"><a href="#cb77-303" aria-hidden="true" tabindex="-1"></a>the New Dean results in a higher salary, I will not include ysdeg in the</span>
<span id="cb77-304"><a href="#cb77-304" aria-hidden="true" tabindex="-1"></a>linear regression model. This is because the New Dean explanatory</span>
<span id="cb77-305"><a href="#cb77-305" aria-hidden="true" tabindex="-1"></a>variable was created from the ysdeg model, meaning that they are likely</span>
<span id="cb77-306"><a href="#cb77-306" aria-hidden="true" tabindex="-1"></a>substantially correlated.</span>
<span id="cb77-307"><a href="#cb77-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-310"><a href="#cb77-310" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-311"><a href="#cb77-311" aria-hidden="true" tabindex="-1"></a><span class="do">##Testing New Dean Hypothesis after removing ysdeg</span></span>
<span id="cb77-312"><a href="#cb77-312" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> New_Dean <span class="sc">+</span> year, <span class="at">data =</span> salary_Dean))</span>
<span id="cb77-313"><a href="#cb77-313" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-314"><a href="#cb77-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-315"><a href="#cb77-315" aria-hidden="true" tabindex="-1"></a>According to the linear regression model, having been hired by the New</span>
<span id="cb77-316"><a href="#cb77-316" aria-hidden="true" tabindex="-1"></a>Dean does result in a higher salary of \$2,163, as indicated by the</span>
<span id="cb77-317"><a href="#cb77-317" aria-hidden="true" tabindex="-1"></a>coefficient to this variable. Furthermore, the New Dean explanatory</span>
<span id="cb77-318"><a href="#cb77-318" aria-hidden="true" tabindex="-1"></a>variable is just barely statistically significant at the 0.05 level with</span>
<span id="cb77-319"><a href="#cb77-319" aria-hidden="true" tabindex="-1"></a>a p-value of 0.0496.</span>
<span id="cb77-320"><a href="#cb77-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-321"><a href="#cb77-321" aria-hidden="true" tabindex="-1"></a><span class="fu"># Question 3</span></span>
<span id="cb77-322"><a href="#cb77-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-325"><a href="#cb77-325" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-326"><a href="#cb77-326" aria-hidden="true" tabindex="-1"></a><span class="co">#Load data</span></span>
<span id="cb77-327"><a href="#cb77-327" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb77-328"><a href="#cb77-328" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb77-329"><a href="#cb77-329" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house.selling.price)</span>
<span id="cb77-330"><a href="#cb77-330" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(house.selling.price)</span>
<span id="cb77-331"><a href="#cb77-331" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-332"><a href="#cb77-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-333"><a href="#cb77-333" aria-hidden="true" tabindex="-1"></a><span class="fu">## A</span></span>
<span id="cb77-334"><a href="#cb77-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-335"><a href="#cb77-335" aria-hidden="true" tabindex="-1"></a>Using the house.selling.price data, run and report regression results</span>
<span id="cb77-336"><a href="#cb77-336" aria-hidden="true" tabindex="-1"></a>modeling y = selling price (in dollars) in terms of size of home (in</span>
<span id="cb77-337"><a href="#cb77-337" aria-hidden="true" tabindex="-1"></a>square feet) and whether the home is new (1 = yes; 0 = no). In</span>
<span id="cb77-338"><a href="#cb77-338" aria-hidden="true" tabindex="-1"></a>particular, for each variable; discuss statistical significance and</span>
<span id="cb77-339"><a href="#cb77-339" aria-hidden="true" tabindex="-1"></a>interpret the meaning of the coefficient.</span>
<span id="cb77-340"><a href="#cb77-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-343"><a href="#cb77-343" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-344"><a href="#cb77-344" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression model y = selling price, explanatory variables = Size &amp; New</span></span>
<span id="cb77-345"><a href="#cb77-345" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price))</span>
<span id="cb77-346"><a href="#cb77-346" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-347"><a href="#cb77-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-348"><a href="#cb77-348" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>*Size* of a house statistically significant at the 0.0001 level with</span>
<span id="cb77-349"><a href="#cb77-349" aria-hidden="true" tabindex="-1"></a>    a p-value less than 2 <span class="sc">\*</span> e\^-16. The coefficient of the Size</span>
<span id="cb77-350"><a href="#cb77-350" aria-hidden="true" tabindex="-1"></a>    variable is 116 suggesting that for every square-foot the size of a</span>
<span id="cb77-351"><a href="#cb77-351" aria-hidden="true" tabindex="-1"></a>    house increases, the predicted price increases by \$116.</span>
<span id="cb77-352"><a href="#cb77-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-353"><a href="#cb77-353" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>*New* The newness of a house is statistically significant at the</span>
<span id="cb77-354"><a href="#cb77-354" aria-hidden="true" tabindex="-1"></a>    0.05 level with a p-value of 0.00257. The coefficient of 57735</span>
<span id="cb77-355"><a href="#cb77-355" aria-hidden="true" tabindex="-1"></a>    suggests that the predicted price of a new house is \$57736.283 more</span>
<span id="cb77-356"><a href="#cb77-356" aria-hidden="true" tabindex="-1"></a>    than a house than is not new.</span>
<span id="cb77-357"><a href="#cb77-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-358"><a href="#cb77-358" aria-hidden="true" tabindex="-1"></a><span class="fu">## B</span></span>
<span id="cb77-359"><a href="#cb77-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-360"><a href="#cb77-360" aria-hidden="true" tabindex="-1"></a>Report and interpret the prediction equation, and form separate</span>
<span id="cb77-361"><a href="#cb77-361" aria-hidden="true" tabindex="-1"></a>equations relating selling price to size for new and for not new homes.</span>
<span id="cb77-362"><a href="#cb77-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-363"><a href="#cb77-363" aria-hidden="true" tabindex="-1"></a>Y = -40230.867 + 116.132(x1) + 57726.263(x2)</span>
<span id="cb77-364"><a href="#cb77-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-365"><a href="#cb77-365" aria-hidden="true" tabindex="-1"></a>where x1 = size of house in square feet, x2 = if a house is new (1 =</span>
<span id="cb77-366"><a href="#cb77-366" aria-hidden="true" tabindex="-1"></a>yes, 0 = no)</span>
<span id="cb77-367"><a href="#cb77-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-368"><a href="#cb77-368" aria-hidden="true" tabindex="-1"></a>This prediction equation can be interpreted that the predicted price of</span>
<span id="cb77-369"><a href="#cb77-369" aria-hidden="true" tabindex="-1"></a>a house in \$ can be calculated by multiplying the size of the house in</span>
<span id="cb77-370"><a href="#cb77-370" aria-hidden="true" tabindex="-1"></a>square feet by \~ \$116, subtracting the intercept of -\$40,230 from the</span>
<span id="cb77-371"><a href="#cb77-371" aria-hidden="true" tabindex="-1"></a>price, and adding \$57,726 if the house is new.</span>
<span id="cb77-372"><a href="#cb77-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-373"><a href="#cb77-373" aria-hidden="true" tabindex="-1"></a>Seperate equations for the selling price for new and not new houses can</span>
<span id="cb77-374"><a href="#cb77-374" aria-hidden="true" tabindex="-1"></a>be generated by subbing in x2 =1 for new houses and x2 =0 for not new</span>
<span id="cb77-375"><a href="#cb77-375" aria-hidden="true" tabindex="-1"></a>houses and calculating the resulting equation</span>
<span id="cb77-376"><a href="#cb77-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-377"><a href="#cb77-377" aria-hidden="true" tabindex="-1"></a>Ynew house = -40230.867 + 116.132(x1) + 57726.263(1) = -40,230.867 +</span>
<span id="cb77-378"><a href="#cb77-378" aria-hidden="true" tabindex="-1"></a>57,726.263 + 116.132 (x1) *Ynew house = 17495.4 + 116.132(x1)* *where x1</span>
<span id="cb77-379"><a href="#cb77-379" aria-hidden="true" tabindex="-1"></a>= size of house in square-feet*</span>
<span id="cb77-380"><a href="#cb77-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-381"><a href="#cb77-381" aria-hidden="true" tabindex="-1"></a>This equation can be interpreted as the Predicted Price of a new house</span>
<span id="cb77-382"><a href="#cb77-382" aria-hidden="true" tabindex="-1"></a>in dollars can be calculated from \$17;495 + \$116 for every square foot</span>
<span id="cb77-383"><a href="#cb77-383" aria-hidden="true" tabindex="-1"></a>in size the house is.</span>
<span id="cb77-384"><a href="#cb77-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-387"><a href="#cb77-387" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-388"><a href="#cb77-388" aria-hidden="true" tabindex="-1"></a><span class="co">#substraction of intercepts</span></span>
<span id="cb77-389"><a href="#cb77-389" aria-hidden="true" tabindex="-1"></a><span class="fl">57726.263</span> <span class="sc">-</span> <span class="fl">40230.867</span></span>
<span id="cb77-390"><a href="#cb77-390" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-391"><a href="#cb77-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-392"><a href="#cb77-392" aria-hidden="true" tabindex="-1"></a>Ynot new = -40230.867 + 116.132(x1) + 57726.263(0) = -40230.867 +</span>
<span id="cb77-393"><a href="#cb77-393" aria-hidden="true" tabindex="-1"></a>116.132(x1) + 0</span>
<span id="cb77-394"><a href="#cb77-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-395"><a href="#cb77-395" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span>Ynotnew = -40230.867 + 116.132(x1) <span class="sc">\*\*</span> *where x1 = size of house in</span>
<span id="cb77-396"><a href="#cb77-396" aria-hidden="true" tabindex="-1"></a>square-feet*</span>
<span id="cb77-397"><a href="#cb77-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-398"><a href="#cb77-398" aria-hidden="true" tabindex="-1"></a>This equation can be interpreted as the price of a not-new house in</span>
<span id="cb77-399"><a href="#cb77-399" aria-hidden="true" tabindex="-1"></a>dollars is calculated as \$116 for every square-foot a house increases</span>
<span id="cb77-400"><a href="#cb77-400" aria-hidden="true" tabindex="-1"></a>in size, minus \$40,230.</span>
<span id="cb77-401"><a href="#cb77-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-402"><a href="#cb77-402" aria-hidden="true" tabindex="-1"></a><span class="fu">## C</span></span>
<span id="cb77-403"><a href="#cb77-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-404"><a href="#cb77-404" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 3000 square feet that is</span>
<span id="cb77-405"><a href="#cb77-405" aria-hidden="true" tabindex="-1"></a>(i) new, (ii) not new.</span>
<span id="cb77-406"><a href="#cb77-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-407"><a href="#cb77-407" aria-hidden="true" tabindex="-1"></a>i.  for a new house where x1 = 3000 Y = 17495.4 + 116.132(x1) Y =</span>
<span id="cb77-408"><a href="#cb77-408" aria-hidden="true" tabindex="-1"></a>    17495.4 + 116.132 (3000)</span>
<span id="cb77-409"><a href="#cb77-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-412"><a href="#cb77-412" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-413"><a href="#cb77-413" aria-hidden="true" tabindex="-1"></a><span class="co">#Arithmitic</span></span>
<span id="cb77-414"><a href="#cb77-414" aria-hidden="true" tabindex="-1"></a><span class="fl">116.132</span> <span class="sc">*</span> <span class="dv">3000</span></span>
<span id="cb77-415"><a href="#cb77-415" aria-hidden="true" tabindex="-1"></a><span class="dv">348396</span> <span class="sc">+</span> <span class="fl">17495.4</span> </span>
<span id="cb77-416"><a href="#cb77-416" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-417"><a href="#cb77-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-418"><a href="#cb77-418" aria-hidden="true" tabindex="-1"></a>Y = 17495.4 + 34896 Y = 365891.4 *The predicted price of a new house</span>
<span id="cb77-419"><a href="#cb77-419" aria-hidden="true" tabindex="-1"></a>with a size of 3000 square feet is \$365,891.4*</span>
<span id="cb77-420"><a href="#cb77-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-421"><a href="#cb77-421" aria-hidden="true" tabindex="-1"></a>ii. For a non-new house where x1 = 3000 Y = -40230.867 + 116.132(x1) Y =</span>
<span id="cb77-422"><a href="#cb77-422" aria-hidden="true" tabindex="-1"></a>    = -40230.867 + 116.132(3000)</span>
<span id="cb77-423"><a href="#cb77-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-426"><a href="#cb77-426" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-427"><a href="#cb77-427" aria-hidden="true" tabindex="-1"></a><span class="co">#Arithmetic</span></span>
<span id="cb77-428"><a href="#cb77-428" aria-hidden="true" tabindex="-1"></a><span class="fl">116.132</span> <span class="sc">*</span> <span class="dv">3000</span></span>
<span id="cb77-429"><a href="#cb77-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-430"><a href="#cb77-430" aria-hidden="true" tabindex="-1"></a><span class="dv">348396</span> <span class="sc">-</span> <span class="fl">40230.867</span></span>
<span id="cb77-431"><a href="#cb77-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-432"><a href="#cb77-432" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-433"><a href="#cb77-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-434"><a href="#cb77-434" aria-hidden="true" tabindex="-1"></a><span class="in">    Y = -40230.867 + 348396</span></span>
<span id="cb77-435"><a href="#cb77-435" aria-hidden="true" tabindex="-1"></a><span class="in">    Y = 308165.1</span></span>
<span id="cb77-436"><a href="#cb77-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-437"><a href="#cb77-437" aria-hidden="true" tabindex="-1"></a>*The predicted price of a not new house with a size of 3000 square feet</span>
<span id="cb77-438"><a href="#cb77-438" aria-hidden="true" tabindex="-1"></a>is \$308,165.1*</span>
<span id="cb77-439"><a href="#cb77-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-440"><a href="#cb77-440" aria-hidden="true" tabindex="-1"></a><span class="fu">## D</span></span>
<span id="cb77-441"><a href="#cb77-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-442"><a href="#cb77-442" aria-hidden="true" tabindex="-1"></a>Fit another model, this time with an interaction term allowing</span>
<span id="cb77-443"><a href="#cb77-443" aria-hidden="true" tabindex="-1"></a>interaction between size and new, and report the regression results</span>
<span id="cb77-444"><a href="#cb77-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-447"><a href="#cb77-447" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-448"><a href="#cb77-448" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression model y = selling price, explanatory variables = Interaction Size * New</span></span>
<span id="cb77-449"><a href="#cb77-449" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">*</span> New, <span class="at">data =</span> house.selling.price))</span>
<span id="cb77-450"><a href="#cb77-450" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-451"><a href="#cb77-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-452"><a href="#cb77-452" aria-hidden="true" tabindex="-1"></a>In the model with the interaction between Size <span class="sc">\*</span> New, the Adjusted</span>
<span id="cb77-453"><a href="#cb77-453" aria-hidden="true" tabindex="-1"></a>R-squared of the model is 0.7363 as opposed to the model with Size &amp; New</span>
<span id="cb77-454"><a href="#cb77-454" aria-hidden="true" tabindex="-1"></a>as explanatory variables without an interaction, which had an adjusted</span>
<span id="cb77-455"><a href="#cb77-455" aria-hidden="true" tabindex="-1"></a>R-squared of 0.7169. In the interaction model:</span>
<span id="cb77-456"><a href="#cb77-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-457"><a href="#cb77-457" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>*Size* has a p-value of less than 2<span class="sc">\*</span>e-\^16, being statistically</span>
<span id="cb77-458"><a href="#cb77-458" aria-hidden="true" tabindex="-1"></a>    significant at the 0.05 level. The coefficient of 104.438 suggest</span>
<span id="cb77-459"><a href="#cb77-459" aria-hidden="true" tabindex="-1"></a>    that the price of the house increases \$104 for every square foot a</span>
<span id="cb77-460"><a href="#cb77-460" aria-hidden="true" tabindex="-1"></a>    house increases in size</span>
<span id="cb77-461"><a href="#cb77-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-462"><a href="#cb77-462" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>*New* has a p-value of 0.12697, not being statistically significant</span>
<span id="cb77-463"><a href="#cb77-463" aria-hidden="true" tabindex="-1"></a>    at the 0.05 or 0.1 levels. The coefficient of -78527.502 suggests</span>
<span id="cb77-464"><a href="#cb77-464" aria-hidden="true" tabindex="-1"></a>    that if a house is new, regardless of size, the predicted price of</span>
<span id="cb77-465"><a href="#cb77-465" aria-hidden="true" tabindex="-1"></a>    the house decreases by \$78527. In the previous model without the</span>
<span id="cb77-466"><a href="#cb77-466" aria-hidden="true" tabindex="-1"></a>    interaction between new &amp; size, new had a positive coefficient and</span>
<span id="cb77-467"><a href="#cb77-467" aria-hidden="true" tabindex="-1"></a>    was statistically significant.</span>
<span id="cb77-468"><a href="#cb77-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-469"><a href="#cb77-469" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>*Size x New* has a p-value of 0.00527, which is statistically</span>
<span id="cb77-470"><a href="#cb77-470" aria-hidden="true" tabindex="-1"></a>    significant at the 0.01 level. This suggests there is a interaction</span>
<span id="cb77-471"><a href="#cb77-471" aria-hidden="true" tabindex="-1"></a>    between the newness of a house and the size of a house. The</span>
<span id="cb77-472"><a href="#cb77-472" aria-hidden="true" tabindex="-1"></a>    coefficient of 61.916 suggests the predicted price of only new</span>
<span id="cb77-473"><a href="#cb77-473" aria-hidden="true" tabindex="-1"></a>    houses increases by \$61.9 for each square foot the size of the</span>
<span id="cb77-474"><a href="#cb77-474" aria-hidden="true" tabindex="-1"></a>    house increases.</span>
<span id="cb77-475"><a href="#cb77-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-476"><a href="#cb77-476" aria-hidden="true" tabindex="-1"></a>Written out as an equation for predicted price, where x1 = size of house</span>
<span id="cb77-477"><a href="#cb77-477" aria-hidden="true" tabindex="-1"></a>in square feet &amp; x2 = newness of house</span>
<span id="cb77-478"><a href="#cb77-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-479"><a href="#cb77-479" aria-hidden="true" tabindex="-1"></a>*Y = -22227.808 + 104.438(x1) - 78527.502(x2) + 61.916(x1)(x2)*</span>
<span id="cb77-480"><a href="#cb77-480" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-481"><a href="#cb77-481" aria-hidden="true" tabindex="-1"></a><span class="fu">## E</span></span>
<span id="cb77-482"><a href="#cb77-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-483"><a href="#cb77-483" aria-hidden="true" tabindex="-1"></a>Report the lines relating the predicted selling price to the size for</span>
<span id="cb77-484"><a href="#cb77-484" aria-hidden="true" tabindex="-1"></a>homes that are (i) new, (ii) not new.</span>
<span id="cb77-485"><a href="#cb77-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-486"><a href="#cb77-486" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span></span>
<span id="cb77-487"><a href="#cb77-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-488"><a href="#cb77-488" aria-hidden="true" tabindex="-1"></a>    (i) new, x2 = 1. Plugging that into the prediction equation: Y =</span>
<span id="cb77-489"><a href="#cb77-489" aria-hidden="true" tabindex="-1"></a>        -22227.808 + 104.438(x1) - 78527.502(x2) + 61.916(x1)(x2) Y =</span>
<span id="cb77-490"><a href="#cb77-490" aria-hidden="true" tabindex="-1"></a>        -22227.808 + 104.438(x1) - 78527.502(1) + 61.916(x1)(1) Y =</span>
<span id="cb77-491"><a href="#cb77-491" aria-hidden="true" tabindex="-1"></a>        -22227.808 + 104.438(x1) - 78527.502 + 61.916(x1)</span>
<span id="cb77-492"><a href="#cb77-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-495"><a href="#cb77-495" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-496"><a href="#cb77-496" aria-hidden="true" tabindex="-1"></a><span class="co">#Arithmetic</span></span>
<span id="cb77-497"><a href="#cb77-497" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">-</span><span class="fl">78527.502</span></span>
<span id="cb77-498"><a href="#cb77-498" aria-hidden="true" tabindex="-1"></a><span class="fl">104.438</span> <span class="sc">+</span> <span class="fl">61.916</span></span>
<span id="cb77-499"><a href="#cb77-499" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-500"><a href="#cb77-500" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-501"><a href="#cb77-501" aria-hidden="true" tabindex="-1"></a>*Ynew = -100755.3 + 166.354(x1)*</span>
<span id="cb77-502"><a href="#cb77-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-503"><a href="#cb77-503" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span></span>
<span id="cb77-504"><a href="#cb77-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-505"><a href="#cb77-505" aria-hidden="true" tabindex="-1"></a>    (ii) not new, x2 = 0. Plugging that into the prediction equation: Y</span>
<span id="cb77-506"><a href="#cb77-506" aria-hidden="true" tabindex="-1"></a>         = -22227.808 + 104.438(x1) - 78527.502(0) + 61.916(x1)(0) Y =</span>
<span id="cb77-507"><a href="#cb77-507" aria-hidden="true" tabindex="-1"></a>         -22227.808 + 104.438(x1) - 0 + 0 *Ynotnew = -22227.808 +</span>
<span id="cb77-508"><a href="#cb77-508" aria-hidden="true" tabindex="-1"></a>         104.438(x1)*</span>
<span id="cb77-509"><a href="#cb77-509" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-510"><a href="#cb77-510" aria-hidden="true" tabindex="-1"></a><span class="fu">## F</span></span>
<span id="cb77-511"><a href="#cb77-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-512"><a href="#cb77-512" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 3000 square feet that is</span>
<span id="cb77-513"><a href="#cb77-513" aria-hidden="true" tabindex="-1"></a>(i) new, (ii) not new.</span>
<span id="cb77-514"><a href="#cb77-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-515"><a href="#cb77-515" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span></span>
<span id="cb77-516"><a href="#cb77-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-517"><a href="#cb77-517" aria-hidden="true" tabindex="-1"></a>    (i) new, x1 = 3000 square feet Ynew = -100755.3 + 166.354(x1) Ynew =</span>
<span id="cb77-518"><a href="#cb77-518" aria-hidden="true" tabindex="-1"></a>        -100755.3 + 166.354(3000)</span>
<span id="cb77-519"><a href="#cb77-519" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-522"><a href="#cb77-522" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-523"><a href="#cb77-523" aria-hidden="true" tabindex="-1"></a><span class="fl">166.354</span> <span class="sc">*</span> <span class="dv">3000</span> </span>
<span id="cb77-524"><a href="#cb77-524" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-525"><a href="#cb77-525" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-526"><a href="#cb77-526" aria-hidden="true" tabindex="-1"></a>Ynew = -100755.3 + 499062</span>
<span id="cb77-527"><a href="#cb77-527" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-530"><a href="#cb77-530" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-531"><a href="#cb77-531" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">100755.3</span> <span class="sc">+</span> <span class="dv">499062</span></span>
<span id="cb77-532"><a href="#cb77-532" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-533"><a href="#cb77-533" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-534"><a href="#cb77-534" aria-hidden="true" tabindex="-1"></a>Ynew = 398306.7 *The predicted selling price of a new house 3000 square</span>
<span id="cb77-535"><a href="#cb77-535" aria-hidden="true" tabindex="-1"></a>feet in size is \$398306.7*</span>
<span id="cb77-536"><a href="#cb77-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-537"><a href="#cb77-537" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span></span>
<span id="cb77-538"><a href="#cb77-538" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-539"><a href="#cb77-539" aria-hidden="true" tabindex="-1"></a>    (ii) not new, x1 = 3000 square feet Ynotnew = -22227.808 +</span>
<span id="cb77-540"><a href="#cb77-540" aria-hidden="true" tabindex="-1"></a>         104.438(x1) Ynotnew = -22227.808 + 104.438(3000)</span>
<span id="cb77-541"><a href="#cb77-541" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-544"><a href="#cb77-544" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-545"><a href="#cb77-545" aria-hidden="true" tabindex="-1"></a><span class="fl">104.438</span> <span class="sc">*</span> <span class="dv">3000</span></span>
<span id="cb77-546"><a href="#cb77-546" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-547"><a href="#cb77-547" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-548"><a href="#cb77-548" aria-hidden="true" tabindex="-1"></a>Ynotnew = -22227.808 + 313314</span>
<span id="cb77-549"><a href="#cb77-549" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-552"><a href="#cb77-552" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-553"><a href="#cb77-553" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="dv">313314</span></span>
<span id="cb77-554"><a href="#cb77-554" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-555"><a href="#cb77-555" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-556"><a href="#cb77-556" aria-hidden="true" tabindex="-1"></a>Ynotnew = 291086.2 *The predicted selling price of a not new house 3000</span>
<span id="cb77-557"><a href="#cb77-557" aria-hidden="true" tabindex="-1"></a>square feet in size is \$291,086.2*</span>
<span id="cb77-558"><a href="#cb77-558" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-559"><a href="#cb77-559" aria-hidden="true" tabindex="-1"></a><span class="fu">## G</span></span>
<span id="cb77-560"><a href="#cb77-560" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-561"><a href="#cb77-561" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 1500 square feet that is</span>
<span id="cb77-562"><a href="#cb77-562" aria-hidden="true" tabindex="-1"></a>(i) new, (ii) not new. Comparing to (F), explain how the difference in</span>
<span id="cb77-563"><a href="#cb77-563" aria-hidden="true" tabindex="-1"></a>predicted selling prices changes as the size of home increases.</span>
<span id="cb77-564"><a href="#cb77-564" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-565"><a href="#cb77-565" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span></span>
<span id="cb77-566"><a href="#cb77-566" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-567"><a href="#cb77-567" aria-hidden="true" tabindex="-1"></a>    (i) new, x1 = 1500 square feet Ynew = -100755.3 + 166.354(x1) Ynew =</span>
<span id="cb77-568"><a href="#cb77-568" aria-hidden="true" tabindex="-1"></a>        -100755.3 + 166.354(1500)</span>
<span id="cb77-569"><a href="#cb77-569" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-572"><a href="#cb77-572" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-573"><a href="#cb77-573" aria-hidden="true" tabindex="-1"></a><span class="fl">166.354</span> <span class="sc">*</span> <span class="dv">1500</span></span>
<span id="cb77-574"><a href="#cb77-574" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-575"><a href="#cb77-575" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-576"><a href="#cb77-576" aria-hidden="true" tabindex="-1"></a>Ynew = -100755.3 + 249531</span>
<span id="cb77-577"><a href="#cb77-577" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-580"><a href="#cb77-580" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-581"><a href="#cb77-581" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">100755.3</span> <span class="sc">+</span> <span class="dv">249531</span></span>
<span id="cb77-582"><a href="#cb77-582" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-583"><a href="#cb77-583" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-584"><a href="#cb77-584" aria-hidden="true" tabindex="-1"></a>Ynew = 148775.7</span>
<span id="cb77-585"><a href="#cb77-585" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-586"><a href="#cb77-586" aria-hidden="true" tabindex="-1"></a>*The predicted selling price of a new house 1500 square feet in size is</span>
<span id="cb77-587"><a href="#cb77-587" aria-hidden="true" tabindex="-1"></a>\$148,775.7*</span>
<span id="cb77-588"><a href="#cb77-588" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-589"><a href="#cb77-589" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span></span>
<span id="cb77-590"><a href="#cb77-590" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-591"><a href="#cb77-591" aria-hidden="true" tabindex="-1"></a>    (ii) not new, x1 = 1500 square feet Ynotnew = -22227.808 +</span>
<span id="cb77-592"><a href="#cb77-592" aria-hidden="true" tabindex="-1"></a>         104.438(x1) Ynotnew = -22227.808 + 104.438(1500)</span>
<span id="cb77-593"><a href="#cb77-593" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-596"><a href="#cb77-596" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-597"><a href="#cb77-597" aria-hidden="true" tabindex="-1"></a> <span class="fl">104.438</span> <span class="sc">*</span> <span class="dv">1500</span></span>
<span id="cb77-598"><a href="#cb77-598" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-599"><a href="#cb77-599" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-600"><a href="#cb77-600" aria-hidden="true" tabindex="-1"></a>Ynotnew = -22227.808 + 156657</span>
<span id="cb77-601"><a href="#cb77-601" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-604"><a href="#cb77-604" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-605"><a href="#cb77-605" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="dv">156657</span></span>
<span id="cb77-606"><a href="#cb77-606" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-607"><a href="#cb77-607" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-608"><a href="#cb77-608" aria-hidden="true" tabindex="-1"></a>Ynotnew = 134429.2 *The predicted selling price of a not new house 1500</span>
<span id="cb77-609"><a href="#cb77-609" aria-hidden="true" tabindex="-1"></a>square feet in size is \$ 134429.2*</span>
<span id="cb77-610"><a href="#cb77-610" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-611"><a href="#cb77-611" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Difference in prices new &amp; not new by size</span>
<span id="cb77-612"><a href="#cb77-612" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-615"><a href="#cb77-615" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb77-616"><a href="#cb77-616" aria-hidden="true" tabindex="-1"></a><span class="co">#Difference new, not new x1 = 3000 square feet</span></span>
<span id="cb77-617"><a href="#cb77-617" aria-hidden="true" tabindex="-1"></a><span class="fl">398306.7</span> <span class="sc">-</span> <span class="fl">291086.2</span></span>
<span id="cb77-618"><a href="#cb77-618" aria-hidden="true" tabindex="-1"></a><span class="do">##Difference new, not new x1 = 1500 square feet</span></span>
<span id="cb77-619"><a href="#cb77-619" aria-hidden="true" tabindex="-1"></a> <span class="fl">148775.7</span> <span class="sc">-</span> <span class="fl">134429.2</span></span>
<span id="cb77-620"><a href="#cb77-620" aria-hidden="true" tabindex="-1"></a><span class="co">#Division </span></span>
<span id="cb77-621"><a href="#cb77-621" aria-hidden="true" tabindex="-1"></a><span class="fl">107220.5</span><span class="sc">/</span><span class="fl">14346.5</span></span>
<span id="cb77-622"><a href="#cb77-622" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb77-623"><a href="#cb77-623" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-624"><a href="#cb77-624" aria-hidden="true" tabindex="-1"></a>The difference between the price of a new &amp; not house 3000 feet in size</span>
<span id="cb77-625"><a href="#cb77-625" aria-hidden="true" tabindex="-1"></a>is \$107,220.5</span>
<span id="cb77-626"><a href="#cb77-626" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-627"><a href="#cb77-627" aria-hidden="true" tabindex="-1"></a>The difference between the price of a new &amp; not new house 1500 feet in</span>
<span id="cb77-628"><a href="#cb77-628" aria-hidden="true" tabindex="-1"></a>size is \$14,346.5</span>
<span id="cb77-629"><a href="#cb77-629" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-630"><a href="#cb77-630" aria-hidden="true" tabindex="-1"></a>A house that is 3000 square feet in size is twice the size of a house</span>
<span id="cb77-631"><a href="#cb77-631" aria-hidden="true" tabindex="-1"></a>1500 square feet in size, the difference between a new &amp; not new houses</span>
<span id="cb77-632"><a href="#cb77-632" aria-hidden="true" tabindex="-1"></a>is 7.473635x more for a house that is 3000 square feet than a house that</span>
<span id="cb77-633"><a href="#cb77-633" aria-hidden="true" tabindex="-1"></a>is 15000 square feet in size. This suggests that the larger the size of</span>
<span id="cb77-634"><a href="#cb77-634" aria-hidden="true" tabindex="-1"></a>a house the more influence the newness of a house has on price.</span>
<span id="cb77-635"><a href="#cb77-635" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-636"><a href="#cb77-636" aria-hidden="true" tabindex="-1"></a><span class="fu">## H</span></span>
<span id="cb77-637"><a href="#cb77-637" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-638"><a href="#cb77-638" aria-hidden="true" tabindex="-1"></a>Do you think the model with interaction or the one without it represents</span>
<span id="cb77-639"><a href="#cb77-639" aria-hidden="true" tabindex="-1"></a>the relationship of size and new to the outcome price? What makes you</span>
<span id="cb77-640"><a href="#cb77-640" aria-hidden="true" tabindex="-1"></a>prefer one model over another?</span>
<span id="cb77-641"><a href="#cb77-641" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-642"><a href="#cb77-642" aria-hidden="true" tabindex="-1"></a>Based on the statistical significance of the interaction between</span>
<span id="cb77-643"><a href="#cb77-643" aria-hidden="true" tabindex="-1"></a>New:Size at the 0.001 level &amp; the higher Adjusted R-Squared of the model</span>
<span id="cb77-644"><a href="#cb77-644" aria-hidden="true" tabindex="-1"></a>with the interaction term 0.7363) than the adjusted R-squared of the</span>
<span id="cb77-645"><a href="#cb77-645" aria-hidden="true" tabindex="-1"></a>model without the interaction term (0.7169) both make me prefer the</span>
<span id="cb77-646"><a href="#cb77-646" aria-hidden="true" tabindex="-1"></a>model with the interacction term over the other interms of best</span>
<span id="cb77-647"><a href="#cb77-647" aria-hidden="true" tabindex="-1"></a>representing the relationship of size and new to the outcome price.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>