<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Darron Bunt">
<meta name="dcterms.date" content="2023-05-07">
<meta name="description" content="Homework Assignment 4 - Darron Bunt">

<title>Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta name="twitter:title" content="Homework 4">
<meta name="twitter:description" content="Homework Assignment 4 - Darron Bunt">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 4</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw4</div>
  </div>
  </div>

<div>
  <div class="description">
    Homework Assignment 4 - Darron Bunt
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Darron Bunt </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 7, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car
Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some

Loading required package: effects
lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="question-1" class="level1">
<h1>Question 1</h1>
<p><em>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.</em></p>
<section id="a" class="level4">
<h4 class="anchored" data-anchor-id="a">A</h4>
<p><strong>A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the predicted selling price and the residual</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ŷ = −10,536 + 53.8x1 + 2.84x2, where x1 = 1,240 and x2 = 18,000</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>PredPrice <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> (<span class="fl">53.8</span><span class="sc">*</span><span class="dv">1240</span>) <span class="sc">+</span> (<span class="fl">2.84</span><span class="sc">*</span><span class="dv">18000</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>PredPrice</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107296</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the residual - actual selling price - predicted selling price</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>ActualPrice <span class="ot">&lt;-</span> <span class="dv">145000</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>Residual <span class="ot">&lt;-</span> ActualPrice <span class="sc">-</span> PredPrice</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>Residual </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37704</code></pre>
</div>
</div>
<p>The predicted selling price is $107,296 and the residual is $37,704.</p>
<p>The actual selling price was more than the model would have predicted.</p>
</section>
<section id="b" class="level4">
<h4 class="anchored" data-anchor-id="b">B</h4>
<p><strong>For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?</strong></p>
<p>For a fixed lot size, each square-foot increase is predicted to increase the sale price by $53.80 - the value of x1.</p>
<p>If we increase the square footage of the example house in question by one square foot, we can observe this difference in the predicted price.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate predicted house price for a 1,241 square foot home</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>House2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> (<span class="fl">53.8</span><span class="sc">*</span><span class="dv">1241</span>) <span class="sc">+</span> (<span class="fl">2.84</span><span class="sc">*</span><span class="dv">18000</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>House2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107349.8</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the difference in predicted price for a 1,241 square foot home vs. a 1,240 square foot home</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>House2Diff <span class="ot">&lt;-</span> House2 <span class="sc">-</span> PredPrice</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>House2Diff</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53.8</code></pre>
</div>
</div>
</section>
<section id="c" class="level4">
<h4 class="anchored" data-anchor-id="c">C</h4>
<p><strong>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</strong></p>
<p>Based on this prediction equation, every square-foot increase in home size increases the value by $53.80 (the value of x1) and each square-foot increase in lot size increases the price by $2.84 (the value of x2).</p>
<p>In order to calculate how much lot size would need to increase in order to have the same impact as a one-square-foot increase in home size, we need to see how many times $2.84 goes into $53.80</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Divide $53.80 by $2.84</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>HowManyFeet <span class="ot">&lt;-</span> <span class="fl">53.80</span> <span class="sc">/</span> <span class="fl">2.84</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>HowManyFeet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.94366</code></pre>
</div>
</div>
<p>Lot size would need to increase 18.94 square feet in order to have the same impact on predicted selling price as a one square foot increase in home size.</p>
</section>
</section>
<section id="question-2" class="level1">
<h1>Question 2</h1>
<p>(Data file: salary in alr4 R package).</p>
<p><em>The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</em></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load salary data file</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="a-1" class="level4">
<h4 class="anchored" data-anchor-id="a-1">A</h4>
<p><strong>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</strong></p>
<p>Null hypothesis: That the mean salary for men and women, without regard to any other variable but sex, <strong>is</strong> the same Alternative hypothesis: That the mean salary for men and women, without regard to any other variable but sex, <strong>is not</strong> the same.</p>
<p>In order to test the hypothesis I am going to run a t-test to determine whether the difference in means is statistically significant.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a two-sample t-test</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> salary <span class="sc">~</span> sex, <span class="at">data =</span> salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by sex
t = 1.7744, df = 21.591, p-value = 0.09009
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -567.8539 7247.1471
sample estimates:
  mean in group Male mean in group Female 
            24696.79             21357.14 </code></pre>
</div>
</div>
<p>The t-test shows that there is indeed a difference between the mean salary for men ($23,696.79) and women ($21,357.14), but with a p-value of 0.09009, we fail to reject the null hypothesis at the 95% confidence level - that is to say, we do not have the evidence that we need to reject the hypothesis that the mean salary for men and women, without regard to any other variable but sex, is the same.</p>
</section>
<section id="b-1" class="level4">
<h4 class="anchored" data-anchor-id="b-1">B</h4>
<p><strong>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run multiple linear regression with salary as outcome variable and everything else (including sex) as predictors</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>lm_salary <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ., data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain 95% confidence interval for the difference in salary between males and females.</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lm_salary, <span class="st">"sexFemale"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              2.5 %   97.5 %
sexFemale -697.8183 3030.565</code></pre>
</div>
</div>
<p>The 95% confidence interval for the difference in salary between males and females is (-697.82, 3,030.57).</p>
</section>
<section id="c-1" class="level4">
<h4 class="anchored" data-anchor-id="c-1">C</h4>
<p><strong>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables</strong></p>
<ul>
<li>Degree
<ul>
<li>Controlling for everything else, a professor with a PhD makes $1,388.61 more than a professor with only a master’s. The p-value is 0.180, so the result is not statistically significant.</li>
</ul></li>
<li>Rank
<ul>
<li>The p-values for rankAssoc and rankProf are both less than 0.05, indicating a statistically significant relationship between salary and rank. Controlling for everything else, a professor at the Associate rank makes $5,292.36 more than one at the rank of Assistant, and a full professor makes $11,118.76 more.</li>
</ul></li>
<li>Sex
<ul>
<li>Controlling for everything else, a female professor makes $1,166 more than a male professor. With a p-value of 0.214, this is not a statistically significant result.</li>
</ul></li>
<li>Year
<ul>
<li>Year, the years a professor has in their current rank, also had a statistically significant impact on salary. Each additional year of experience added $476.31 in salary.</li>
</ul></li>
<li>Years Since Highest Degree
<ul>
<li>The result here was not statistically significant but suggests that, when controlling for all other factors, each year that has passed since one obtained their degree results in a $124.57 decrease in salary.</li>
</ul></li>
</ul>
<p>Overall, of the predictor variables considered, rank and year have a statistically significant impact on salary.</p>
</section>
<section id="d" class="level4">
<h4 class="anchored" data-anchor-id="d">D</h4>
<p><strong>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the baseline category for rank to "Prof"</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Prof"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ., data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  26864.81    1375.29  19.534  &lt; 2e-16 ***
degreePhD     1388.61    1018.75   1.363    0.180    
rankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***
rankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***
sexFemale     1166.37     925.57   1.260    0.214    
year           476.31      94.91   5.018 8.65e-06 ***
ysdeg         -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the baseline category for rank to "Assoc"</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Assoc"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ., data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 21038.41    1109.12  18.969  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankProf     5826.40    1012.93   5.752 7.28e-07 ***
rankAsst    -5292.36    1145.40  -4.621 3.22e-05 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Interpret the coefficients related to rank again.</strong></p>
<p>No matter which category is the baseline for rank, the results remain statistically significant.</p>
<ul>
<li><p>With professor as the baseline, we that assistant professors are expected to make $11,118.76 less and associate professors $5,826.40 less.</p></li>
<li><p>With associate professor as the baseline, we see that full professors are expected to make $5,826.40 more, while assistant professors are expected to make $5,292.36 less.</p></li>
<li><p>And, as we calculated previously, with assistant as the baseline, a professor at the Associate rank makes $5,292.36 more than one at the rank of Assistant, and a full professor makes $11,118.76 more.</p></li>
</ul>
<p>The numbers always remain the same; it’s the same information, just presented in slightly different ways depending on which rank is acting as the baseline variable.</p>
</section>
<section id="e" class="level4">
<h4 class="anchored" data-anchor-id="e">E</h4>
<p><em>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “<a href="#a">a</a> variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.</em></p>
<p><strong>Exclude the variable rank, refit, and summarize how your findings changed, if they did.</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run multiple linear regression again, but exclude the variable "rank"</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>lm_salary_NR <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_salary_NR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
year          351.97     142.48   2.470 0.017185 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p><strong>Summarize how your findings changed, if they did.</strong></p>
<ul>
<li><p>With rank included as a predictor variable, rank and year had a statistically significant impact on salary.</p></li>
<li><p>With rank excluded, degree, year, and ysdeg had a statistically significant impact on salary</p>
<ul>
<li><strong>Degree</strong>
<ul>
<li>Without the “rank” variable, “degreePhD” becomes a statistically significant predictor variable. When controlling for all other factors, a PhD (vs.&nbsp;a master’s) now results in a $3,299.35 decrease in salary (much different than with rank included, where there was no statistical significance, but a PhD increased salary by $1,388.61).</li>
</ul></li>
<li><strong>Years Since Highest Degree</strong>
<ul>
<li>Without the “rank” variable, “ysdeg” (years since receiving one’s highest degree) becomes a statistically significant predictor variable. When controlling for all other factors, each year that has passed now results in a $339.40 increase in salary (much different than with rank included, where there was no statistical significance and a decrease).</li>
</ul></li>
<li><strong>Year</strong>
<ul>
<li>“year” remains statistically significant, though the p-value has increased. When controlling for all other factors, each additional year of experience adds $351.97 in salary.</li>
</ul></li>
<li><strong>Sex</strong>
<ul>
<li>The result for sex was still not statistically significant, but the its impact on salary did change from a positive one to a negative one.</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="f" class="level4">
<h4 class="anchored" data-anchor-id="f">F</h4>
<p><em>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</em></p>
<p><strong>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new variable that indicates whether the professor was hired by the new dean or not - ysdeg &gt;16 years ago and ysdeg &lt;= 15 years ago</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>newDean <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 0 WAS hired by new Dean; 1 is was NOT hired by new Dean</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Multicollinarity refers to a situation where 2+ variables in a regression model are highly correlated with each other - that is, they are measuring either the same or similar things. If variables that are highly correlated with each other are included in the same regression model, this can lead to unreliable results.</p>
<p>In our case, newDean is highly correlated with ysdeg - the numerical data from ysdeg was used to create the binary variable newDean (0 if ysdeg is 16+; 1 if ysdeg is 15 or less). Accordingly, when we run our regression analysis, we need to include newDean, but <strong>exclude</strong> ysdeg.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run regression analysis with newDean included as a predictor variable</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>lm_salary_NewDean <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> newDean, <span class="at">data =</span> salary)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_salary_NewDean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + newDean, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-3403.3 -1387.0  -167.0   528.2  9233.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 20464.50     952.41  21.487  &lt; 2e-16 ***
degreePhD     818.93     797.48   1.027   0.3100    
rankProf     6124.28    1028.58   5.954 3.65e-07 ***
rankAsst    -4972.66     997.17  -4.987 9.61e-06 ***
sexFemale     907.14     840.54   1.079   0.2862    
year          434.85      78.89   5.512 1.65e-06 ***
newDean     -2163.46    1072.04  -2.018   0.0496 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2362 on 45 degrees of freedom
Multiple R-squared:  0.8594,    Adjusted R-squared:  0.8407 
F-statistic: 45.86 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</strong></p>
<p>Yes, there is support for the hypothesis that people hired by the new Dean are making more than those who were not. The p-value is significant at the 5% level (0.0496), and the results suggest that faculty who were not hired by the new Dean make $2,163.46 less, when controlling for other variables.</p>
</section>
</section>
<section id="question-3" class="level1">
<h1>Question 3</h1>
<p>(Data file: house.selling.price in smss R package)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data file</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="a-2" class="level4">
<h4 class="anchored" data-anchor-id="a-2">A</h4>
<p><strong>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression results modeling Size, New as predictor variables for Price</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>Price_SzNew <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Price_SzNew)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>for each variable; discuss statistical significance and interpret the meaning of the coefficient.</strong></p>
<ul>
<li>Size
<ul>
<li>Size had a statistically significant impact on selling price; controlling for newness, each additional square foot added $116.13 to the sale price.</li>
</ul></li>
<li>New
<ul>
<li>New also had a statistically significant impact on selling price; controlling for square footage, a new house sold for $57,736.28 more than houses that were not new.</li>
</ul></li>
</ul>
</section>
<section id="b-2" class="level4">
<h4 class="anchored" data-anchor-id="b-2">B</h4>
<p><strong>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</strong></p>
<p>The equation would be ŷ = −40,230.867 + 116.132(Size) + 57736.283(New).</p>
<p>If a house is new: ŷ = −40,230.867 + 116.132(Size) + 57,736.283 If a house is not new: ŷ = −40,230.867 + 116.132(Size)</p>
<p>New/not new is a binary variable, and only new houses see an increase in sale price.</p>
</section>
<section id="c-2" class="level4">
<h4 class="anchored" data-anchor-id="c-2">C</h4>
<p><strong>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</strong></p>
<p>New: ŷ = −40,230.867 + (116.132<em>3000) + 57,736.283 Not new: ŷ = −40,230.867 + (116.132</em>3000)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>New3000 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> (<span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span>) <span class="sc">+</span> <span class="fl">57736.283</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>NotNew3000 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> (<span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>New3000</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 365901.4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>NotNew3000</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 308165.1</code></pre>
</div>
</div>
<p>The predicted selling price for a new 3,000 square foot home is $365,901.40. The predicted selling price for a 3,000 square foot home that is not new is $308,165.10.</p>
</section>
<section id="d-1" class="level4">
<h4 class="anchored" data-anchor-id="d-1">D</h4>
<p><strong>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a model allowing interaction between size and new</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>Price_SzNewInt <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size<span class="sc">:</span>New, <span class="at">data =</span> house.selling.price)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Price_SzNewInt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New + Size:New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="e-1" class="level4">
<h4 class="anchored" data-anchor-id="e-1">E</h4>
<p><strong>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</strong></p>
<p>ŷ = −22,227.808 + 104.438(Size) + (-78527.502(New)) + 61.916(Size*New)</p>
<p>New: −22,227.808 + 104.438(Size) + (-78527.502(New)) + 61.916(Size*New)</p>
<p>Not new: −22,227.808 + 104.438(Size)</p>
</section>
<section id="f-1" class="level4">
<h4 class="anchored" data-anchor-id="f-1">F</h4>
<p><strong>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>NewInt3000 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span>) <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> (<span class="fl">61.916</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>NotNewInt3000 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>NewInt3000</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 398306.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>NotNewInt3000</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 291086.2</code></pre>
</div>
</div>
<p>The predicted selling price for a new, 3000 square-foot home is $398,306.70. The predicted selling price for a 3000 square-foot home that is not new is $291,086.20.</p>
</section>
<section id="g" class="level4">
<h4 class="anchored" data-anchor-id="g">G</h4>
<p><strong>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>NewInt1500 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span>) <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> (<span class="fl">61.916</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>NotNewInt1500 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>NewInt1500</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 148775.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>NotNewInt1500</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 134429.2</code></pre>
</div>
</div>
<p><strong>Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</strong></p>
<ul>
<li>For 3000 square foot homes:
<ul>
<li>New: $398,306.70</li>
<li>Not New: $291,086.20</li>
</ul></li>
<li>For 1500 square foot homes:
<ul>
<li>New: $148,775.70</li>
<li>Not New: $134,429.20</li>
</ul></li>
</ul>
<p>There is a $107,220.50 difference in sale price for the new/not new 3000 square foot homes but only a $14,346.50 difference in sale price for the new/not new 1500 square foot homes. Given the structure of the prediction equation, this makes a lot of sense - based on the predictive model, a house needs to be roughly 606 feet before it can be sold at a profit. A 1,500 square foot home has only roughly 894 “money making” square feet, while the 3000 square foot home has roughly 2394, and each money making square foot available adds 166.354 to the sale price.</p>
</section>
<section id="h" class="level4">
<h4 class="anchored" data-anchor-id="h">H</h4>
<p><strong>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</strong></p>
<p>I think the model with the interaction more closely represents the relationship of size and newness to the outcome price. The p value for the model with interaction indicated statistical significance; further, the adjusted r squared for the model with interaction (0.7363) was higher than that for the model without (0.7169).</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb49" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 4"</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Darron Bunt"</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Homework Assignment 4 - Darron Bunt"</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/07/2023"</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw4</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-25"><a href="#cb49-25" aria-hidden="true" tabindex="-1"></a><span class="fu"># Question 1 </span></span>
<span id="cb49-26"><a href="#cb49-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-27"><a href="#cb49-27" aria-hidden="true" tabindex="-1"></a>*For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.*</span>
<span id="cb49-28"><a href="#cb49-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-29"><a href="#cb49-29" aria-hidden="true" tabindex="-1"></a><span class="fu">####  A</span></span>
<span id="cb49-30"><a href="#cb49-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-31"><a href="#cb49-31" aria-hidden="true" tabindex="-1"></a>**A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret**</span>
<span id="cb49-32"><a href="#cb49-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-35"><a href="#cb49-35" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-36"><a href="#cb49-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the predicted selling price and the residual</span></span>
<span id="cb49-37"><a href="#cb49-37" aria-hidden="true" tabindex="-1"></a><span class="co"># ŷ = −10,536 + 53.8x1 + 2.84x2, where x1 = 1,240 and x2 = 18,000</span></span>
<span id="cb49-38"><a href="#cb49-38" aria-hidden="true" tabindex="-1"></a>PredPrice <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> (<span class="fl">53.8</span><span class="sc">*</span><span class="dv">1240</span>) <span class="sc">+</span> (<span class="fl">2.84</span><span class="sc">*</span><span class="dv">18000</span>)</span>
<span id="cb49-39"><a href="#cb49-39" aria-hidden="true" tabindex="-1"></a>PredPrice</span>
<span id="cb49-40"><a href="#cb49-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-41"><a href="#cb49-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the residual - actual selling price - predicted selling price</span></span>
<span id="cb49-42"><a href="#cb49-42" aria-hidden="true" tabindex="-1"></a>ActualPrice <span class="ot">&lt;-</span> <span class="dv">145000</span></span>
<span id="cb49-43"><a href="#cb49-43" aria-hidden="true" tabindex="-1"></a>Residual <span class="ot">&lt;-</span> ActualPrice <span class="sc">-</span> PredPrice</span>
<span id="cb49-44"><a href="#cb49-44" aria-hidden="true" tabindex="-1"></a>Residual </span>
<span id="cb49-45"><a href="#cb49-45" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-46"><a href="#cb49-46" aria-hidden="true" tabindex="-1"></a>The predicted selling price is $107,296 and the residual is $37,704.</span>
<span id="cb49-47"><a href="#cb49-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-48"><a href="#cb49-48" aria-hidden="true" tabindex="-1"></a>The actual selling price was more than the model would have predicted.</span>
<span id="cb49-49"><a href="#cb49-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-50"><a href="#cb49-50" aria-hidden="true" tabindex="-1"></a><span class="fu">####  B</span></span>
<span id="cb49-51"><a href="#cb49-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-52"><a href="#cb49-52" aria-hidden="true" tabindex="-1"></a>**For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?**</span>
<span id="cb49-53"><a href="#cb49-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-54"><a href="#cb49-54" aria-hidden="true" tabindex="-1"></a>For a fixed lot size, each square-foot increase is predicted to increase the sale price by $53.80 - the value of x1. </span>
<span id="cb49-55"><a href="#cb49-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-56"><a href="#cb49-56" aria-hidden="true" tabindex="-1"></a>If we increase the square footage of the example house in question by one square foot, we can observe this difference in the predicted price. </span>
<span id="cb49-57"><a href="#cb49-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-60"><a href="#cb49-60" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-61"><a href="#cb49-61" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate predicted house price for a 1,241 square foot home</span></span>
<span id="cb49-62"><a href="#cb49-62" aria-hidden="true" tabindex="-1"></a>House2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> (<span class="fl">53.8</span><span class="sc">*</span><span class="dv">1241</span>) <span class="sc">+</span> (<span class="fl">2.84</span><span class="sc">*</span><span class="dv">18000</span>)</span>
<span id="cb49-63"><a href="#cb49-63" aria-hidden="true" tabindex="-1"></a>House2</span>
<span id="cb49-64"><a href="#cb49-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-65"><a href="#cb49-65" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the difference in predicted price for a 1,241 square foot home vs. a 1,240 square foot home</span></span>
<span id="cb49-66"><a href="#cb49-66" aria-hidden="true" tabindex="-1"></a>House2Diff <span class="ot">&lt;-</span> House2 <span class="sc">-</span> PredPrice</span>
<span id="cb49-67"><a href="#cb49-67" aria-hidden="true" tabindex="-1"></a>House2Diff</span>
<span id="cb49-68"><a href="#cb49-68" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-69"><a href="#cb49-69" aria-hidden="true" tabindex="-1"></a><span class="fu">####  C</span></span>
<span id="cb49-70"><a href="#cb49-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-71"><a href="#cb49-71" aria-hidden="true" tabindex="-1"></a>**According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?**</span>
<span id="cb49-72"><a href="#cb49-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-73"><a href="#cb49-73" aria-hidden="true" tabindex="-1"></a>Based on this prediction equation, every square-foot increase in home size increases the value by $53.80 (the value of x1) and each square-foot increase in lot size increases the price by $2.84 (the value of x2).</span>
<span id="cb49-74"><a href="#cb49-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-75"><a href="#cb49-75" aria-hidden="true" tabindex="-1"></a>In order to calculate how much lot size would need to increase in order to have the same impact as a one-square-foot increase in home size, we need to see how many times $2.84 goes into $53.80</span>
<span id="cb49-76"><a href="#cb49-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-79"><a href="#cb49-79" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-80"><a href="#cb49-80" aria-hidden="true" tabindex="-1"></a><span class="co"># Divide $53.80 by $2.84</span></span>
<span id="cb49-81"><a href="#cb49-81" aria-hidden="true" tabindex="-1"></a>HowManyFeet <span class="ot">&lt;-</span> <span class="fl">53.80</span> <span class="sc">/</span> <span class="fl">2.84</span></span>
<span id="cb49-82"><a href="#cb49-82" aria-hidden="true" tabindex="-1"></a>HowManyFeet</span>
<span id="cb49-83"><a href="#cb49-83" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-84"><a href="#cb49-84" aria-hidden="true" tabindex="-1"></a>Lot size would need to increase 18.94 square feet in order to have the same impact on predicted selling price as a one square foot increase in home size. </span>
<span id="cb49-85"><a href="#cb49-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-86"><a href="#cb49-86" aria-hidden="true" tabindex="-1"></a><span class="fu"># Question 2</span></span>
<span id="cb49-87"><a href="#cb49-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-88"><a href="#cb49-88" aria-hidden="true" tabindex="-1"></a>(Data file: salary in alr4 R package).</span>
<span id="cb49-89"><a href="#cb49-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-90"><a href="#cb49-90" aria-hidden="true" tabindex="-1"></a>*The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.*</span>
<span id="cb49-91"><a href="#cb49-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-94"><a href="#cb49-94" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-95"><a href="#cb49-95" aria-hidden="true" tabindex="-1"></a><span class="co"># Load salary data file</span></span>
<span id="cb49-96"><a href="#cb49-96" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span>
<span id="cb49-97"><a href="#cb49-97" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-98"><a href="#cb49-98" aria-hidden="true" tabindex="-1"></a><span class="fu">#### A</span></span>
<span id="cb49-99"><a href="#cb49-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-100"><a href="#cb49-100" aria-hidden="true" tabindex="-1"></a>**Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.**</span>
<span id="cb49-101"><a href="#cb49-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-102"><a href="#cb49-102" aria-hidden="true" tabindex="-1"></a>Null hypothesis: That the mean salary for men and women, without regard to any other variable but sex, **is** the same</span>
<span id="cb49-103"><a href="#cb49-103" aria-hidden="true" tabindex="-1"></a>Alternative hypothesis: That the mean salary for men and women, without regard to any other variable but sex, **is not** the same.</span>
<span id="cb49-104"><a href="#cb49-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-105"><a href="#cb49-105" aria-hidden="true" tabindex="-1"></a>In order to test the hypothesis I am going to run a t-test to determine whether the difference in means is statistically significant.</span>
<span id="cb49-106"><a href="#cb49-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-109"><a href="#cb49-109" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-110"><a href="#cb49-110" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a two-sample t-test</span></span>
<span id="cb49-111"><a href="#cb49-111" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> salary <span class="sc">~</span> sex, <span class="at">data =</span> salary)</span>
<span id="cb49-112"><a href="#cb49-112" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-113"><a href="#cb49-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-114"><a href="#cb49-114" aria-hidden="true" tabindex="-1"></a>The t-test shows that there is indeed a difference between the mean salary for men ($23,696.79) and women ($21,357.14), but with a p-value of 0.09009, we fail to reject the null hypothesis at the 95% confidence level - that is to say, we do not have the evidence that we need to reject the hypothesis that the mean salary for men and women, without regard to any other variable but sex, is the same.</span>
<span id="cb49-115"><a href="#cb49-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-116"><a href="#cb49-116" aria-hidden="true" tabindex="-1"></a><span class="fu">#### B</span></span>
<span id="cb49-117"><a href="#cb49-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-118"><a href="#cb49-118" aria-hidden="true" tabindex="-1"></a>**Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.**</span>
<span id="cb49-119"><a href="#cb49-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-122"><a href="#cb49-122" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-123"><a href="#cb49-123" aria-hidden="true" tabindex="-1"></a><span class="co"># Run multiple linear regression with salary as outcome variable and everything else (including sex) as predictors</span></span>
<span id="cb49-124"><a href="#cb49-124" aria-hidden="true" tabindex="-1"></a>lm_salary <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary)</span>
<span id="cb49-125"><a href="#cb49-125" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_salary)</span>
<span id="cb49-126"><a href="#cb49-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-127"><a href="#cb49-127" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain 95% confidence interval for the difference in salary between males and females.</span></span>
<span id="cb49-128"><a href="#cb49-128" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lm_salary, <span class="st">"sexFemale"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb49-129"><a href="#cb49-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-130"><a href="#cb49-130" aria-hidden="true" tabindex="-1"></a>The 95% confidence interval for the difference in salary between males and females is (-697.82, 3,030.57).</span>
<span id="cb49-131"><a href="#cb49-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-132"><a href="#cb49-132" aria-hidden="true" tabindex="-1"></a><span class="fu">#### C</span></span>
<span id="cb49-133"><a href="#cb49-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-134"><a href="#cb49-134" aria-hidden="true" tabindex="-1"></a>**Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables**</span>
<span id="cb49-135"><a href="#cb49-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-136"><a href="#cb49-136" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Degree</span>
<span id="cb49-137"><a href="#cb49-137" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>Controlling for everything else, a professor with a PhD makes $1,388.61 more than a professor with only a master's. The p-value is 0.180, so the result is not statistically significant.</span>
<span id="cb49-138"><a href="#cb49-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-139"><a href="#cb49-139" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Rank</span>
<span id="cb49-140"><a href="#cb49-140" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>The p-values for rankAssoc and rankProf are both less than 0.05, indicating a statistically significant relationship between salary and rank. Controlling for everything else, a professor at the Associate rank makes $5,292.36 more than one at the rank of Assistant, and a full professor makes $11,118.76 more. </span>
<span id="cb49-141"><a href="#cb49-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-142"><a href="#cb49-142" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Sex</span>
<span id="cb49-143"><a href="#cb49-143" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>Controlling for everything else, a female professor makes $1,166 more than a male professor. With a p-value of 0.214, this is not a statistically significant result.</span>
<span id="cb49-144"><a href="#cb49-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-145"><a href="#cb49-145" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Year</span>
<span id="cb49-146"><a href="#cb49-146" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>Year, the years a professor has in their current rank, also had a statistically significant impact on salary. Each additional year of experience added $476.31 in salary.</span>
<span id="cb49-147"><a href="#cb49-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-148"><a href="#cb49-148" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Years Since Highest Degree</span>
<span id="cb49-149"><a href="#cb49-149" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>The result here was not statistically significant but suggests that, when controlling for all other factors, each year that has passed since one obtained their degree results in a $124.57 decrease in salary.</span>
<span id="cb49-150"><a href="#cb49-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-151"><a href="#cb49-151" aria-hidden="true" tabindex="-1"></a>Overall, of the predictor variables considered, rank and year have a statistically significant impact on salary. </span>
<span id="cb49-152"><a href="#cb49-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-153"><a href="#cb49-153" aria-hidden="true" tabindex="-1"></a><span class="fu">#### D</span></span>
<span id="cb49-154"><a href="#cb49-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-155"><a href="#cb49-155" aria-hidden="true" tabindex="-1"></a>**Change the baseline category for the rank variable. Interpret the coefficients related to rank again.**</span>
<span id="cb49-156"><a href="#cb49-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-159"><a href="#cb49-159" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-160"><a href="#cb49-160" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the baseline category for rank to "Prof"</span></span>
<span id="cb49-161"><a href="#cb49-161" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Prof"</span>)</span>
<span id="cb49-162"><a href="#cb49-162" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary))</span>
<span id="cb49-163"><a href="#cb49-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-164"><a href="#cb49-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-167"><a href="#cb49-167" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-168"><a href="#cb49-168" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the baseline category for rank to "Assoc"</span></span>
<span id="cb49-169"><a href="#cb49-169" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Assoc"</span>)</span>
<span id="cb49-170"><a href="#cb49-170" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary))</span>
<span id="cb49-171"><a href="#cb49-171" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-172"><a href="#cb49-172" aria-hidden="true" tabindex="-1"></a>**Interpret the coefficients related to rank again.**</span>
<span id="cb49-173"><a href="#cb49-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-174"><a href="#cb49-174" aria-hidden="true" tabindex="-1"></a>No matter which category is the baseline for rank, the results remain statistically significant.</span>
<span id="cb49-175"><a href="#cb49-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-176"><a href="#cb49-176" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>With professor as the baseline, we that assistant professors are expected to make $11,118.76 less and associate professors $5,826.40 less.</span>
<span id="cb49-177"><a href="#cb49-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-178"><a href="#cb49-178" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>With associate professor as the baseline, we see that full professors are expected to make $5,826.40 more, while assistant professors are expected to make $5,292.36 less.</span>
<span id="cb49-179"><a href="#cb49-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-180"><a href="#cb49-180" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>And, as we calculated previously, with assistant as the baseline, a professor at the Associate rank makes $5,292.36 more than one at the rank of Assistant, and a full professor makes $11,118.76 more.</span>
<span id="cb49-181"><a href="#cb49-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-182"><a href="#cb49-182" aria-hidden="true" tabindex="-1"></a>The numbers always remain the same; it's the same information, just presented in slightly different ways depending on which rank is acting as the baseline variable. </span>
<span id="cb49-183"><a href="#cb49-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-184"><a href="#cb49-184" aria-hidden="true" tabindex="-1"></a><span class="fu">#### E</span></span>
<span id="cb49-185"><a href="#cb49-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-186"><a href="#cb49-186" aria-hidden="true" tabindex="-1"></a>*Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “[a] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’ ” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.*</span>
<span id="cb49-187"><a href="#cb49-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-188"><a href="#cb49-188" aria-hidden="true" tabindex="-1"></a>**Exclude the variable rank, refit, and summarize how your findings changed, if they did.**</span>
<span id="cb49-189"><a href="#cb49-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-192"><a href="#cb49-192" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-193"><a href="#cb49-193" aria-hidden="true" tabindex="-1"></a><span class="co"># Run multiple linear regression again, but exclude the variable "rank"</span></span>
<span id="cb49-194"><a href="#cb49-194" aria-hidden="true" tabindex="-1"></a>lm_salary_NR <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb49-195"><a href="#cb49-195" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_salary_NR)</span>
<span id="cb49-196"><a href="#cb49-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-197"><a href="#cb49-197" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-198"><a href="#cb49-198" aria-hidden="true" tabindex="-1"></a>**Summarize how your findings changed, if they did.**</span>
<span id="cb49-199"><a href="#cb49-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-200"><a href="#cb49-200" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>With rank included as a predictor variable, rank and year had a statistically significant impact on salary. </span>
<span id="cb49-201"><a href="#cb49-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-202"><a href="#cb49-202" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>With rank excluded, degree, year, and ysdeg had a statistically significant impact on salary</span>
<span id="cb49-203"><a href="#cb49-203" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>**Degree** </span>
<span id="cb49-204"><a href="#cb49-204" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>Without the "rank" variable, "degreePhD" becomes a statistically significant predictor variable. When controlling for all other factors, a PhD (vs. a master's) now results in a $3,299.35 decrease in salary (much different than with rank included, where there was no statistical significance, but a PhD increased salary by $1,388.61).</span>
<span id="cb49-205"><a href="#cb49-205" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>**Years Since Highest Degree** </span>
<span id="cb49-206"><a href="#cb49-206" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>Without the "rank" variable, "ysdeg" (years since receiving one's highest degree) becomes a statistically significant predictor variable. When controlling for all other factors, each year that has passed now results in a $339.40 increase in salary (much different than with rank included, where there was no statistical significance and a decrease). </span>
<span id="cb49-207"><a href="#cb49-207" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>**Year** </span>
<span id="cb49-208"><a href="#cb49-208" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>"year" remains statistically significant, though the p-value has increased. When controlling for all other factors, each additional year of experience adds $351.97 in salary.</span>
<span id="cb49-209"><a href="#cb49-209" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>**Sex** </span>
<span id="cb49-210"><a href="#cb49-210" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>The result for sex was still not statistically significant, but the its impact on salary did change from a positive one to a negative one. </span>
<span id="cb49-211"><a href="#cb49-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-212"><a href="#cb49-212" aria-hidden="true" tabindex="-1"></a><span class="fu">#### F</span></span>
<span id="cb49-213"><a href="#cb49-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-214"><a href="#cb49-214" aria-hidden="true" tabindex="-1"></a>*Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.*</span>
<span id="cb49-215"><a href="#cb49-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-216"><a href="#cb49-216" aria-hidden="true" tabindex="-1"></a>**Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?**</span>
<span id="cb49-217"><a href="#cb49-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-220"><a href="#cb49-220" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-221"><a href="#cb49-221" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new variable that indicates whether the professor was hired by the new dean or not - ysdeg &gt;16 years ago and ysdeg &lt;= 15 years ago</span></span>
<span id="cb49-222"><a href="#cb49-222" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>newDean <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb49-223"><a href="#cb49-223" aria-hidden="true" tabindex="-1"></a><span class="co"># 0 WAS hired by new Dean; 1 is was NOT hired by new Dean</span></span>
<span id="cb49-224"><a href="#cb49-224" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-225"><a href="#cb49-225" aria-hidden="true" tabindex="-1"></a>Multicollinarity refers to a situation where 2+ variables in a regression model are highly correlated with each other - that is, they are measuring either the same or similar things. If variables that are highly correlated with each other are included in the same regression model, this can lead to unreliable results. </span>
<span id="cb49-226"><a href="#cb49-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-227"><a href="#cb49-227" aria-hidden="true" tabindex="-1"></a>In our case, newDean is highly correlated with ysdeg - the numerical data from ysdeg was used to create the binary variable newDean (0 if ysdeg is 16+; 1 if ysdeg is 15 or less). Accordingly, when we run our regression analysis, we need to include newDean, but **exclude** ysdeg.</span>
<span id="cb49-228"><a href="#cb49-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-231"><a href="#cb49-231" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-232"><a href="#cb49-232" aria-hidden="true" tabindex="-1"></a><span class="co"># Run regression analysis with newDean included as a predictor variable</span></span>
<span id="cb49-233"><a href="#cb49-233" aria-hidden="true" tabindex="-1"></a>lm_salary_NewDean <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> newDean, <span class="at">data =</span> salary)</span>
<span id="cb49-234"><a href="#cb49-234" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_salary_NewDean)</span>
<span id="cb49-235"><a href="#cb49-235" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-236"><a href="#cb49-236" aria-hidden="true" tabindex="-1"></a>**Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?**</span>
<span id="cb49-237"><a href="#cb49-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-238"><a href="#cb49-238" aria-hidden="true" tabindex="-1"></a>Yes, there is support for the hypothesis that people hired by the new Dean are making more than those who were not. The p-value is significant at the 5% level (0.0496), and the results suggest that faculty who were not hired by the new Dean make $2,163.46 less, when controlling for other variables. </span>
<span id="cb49-239"><a href="#cb49-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-240"><a href="#cb49-240" aria-hidden="true" tabindex="-1"></a><span class="fu"># Question 3</span></span>
<span id="cb49-241"><a href="#cb49-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-242"><a href="#cb49-242" aria-hidden="true" tabindex="-1"></a>(Data file: house.selling.price in smss R package)</span>
<span id="cb49-243"><a href="#cb49-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-246"><a href="#cb49-246" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-247"><a href="#cb49-247" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data file</span></span>
<span id="cb49-248"><a href="#cb49-248" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb49-249"><a href="#cb49-249" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-250"><a href="#cb49-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-251"><a href="#cb49-251" aria-hidden="true" tabindex="-1"></a><span class="fu">#### A</span></span>
<span id="cb49-252"><a href="#cb49-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-253"><a href="#cb49-253" aria-hidden="true" tabindex="-1"></a>**Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.**</span>
<span id="cb49-254"><a href="#cb49-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-257"><a href="#cb49-257" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-258"><a href="#cb49-258" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression results modeling Size, New as predictor variables for Price</span></span>
<span id="cb49-259"><a href="#cb49-259" aria-hidden="true" tabindex="-1"></a>Price_SzNew <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price)</span>
<span id="cb49-260"><a href="#cb49-260" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Price_SzNew)</span>
<span id="cb49-261"><a href="#cb49-261" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-262"><a href="#cb49-262" aria-hidden="true" tabindex="-1"></a>**for each variable; discuss statistical significance and interpret the meaning of the coefficient.**</span>
<span id="cb49-263"><a href="#cb49-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-264"><a href="#cb49-264" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Size</span>
<span id="cb49-265"><a href="#cb49-265" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>Size had a statistically significant impact on selling price; controlling for newness, each additional square foot added $116.13 to the sale price.</span>
<span id="cb49-266"><a href="#cb49-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-267"><a href="#cb49-267" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>New</span>
<span id="cb49-268"><a href="#cb49-268" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>New also had a statistically significant impact on selling price; controlling for square footage, a new house sold for $57,736.28 more than houses that were not new.</span>
<span id="cb49-269"><a href="#cb49-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-270"><a href="#cb49-270" aria-hidden="true" tabindex="-1"></a><span class="fu">#### B</span></span>
<span id="cb49-271"><a href="#cb49-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-272"><a href="#cb49-272" aria-hidden="true" tabindex="-1"></a>**Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.**</span>
<span id="cb49-273"><a href="#cb49-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-274"><a href="#cb49-274" aria-hidden="true" tabindex="-1"></a>The equation would be ŷ = −40,230.867 + 116.132(Size) + 57736.283(New). </span>
<span id="cb49-275"><a href="#cb49-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-276"><a href="#cb49-276" aria-hidden="true" tabindex="-1"></a>If a house is new: ŷ = −40,230.867 + 116.132(Size) + 57,736.283</span>
<span id="cb49-277"><a href="#cb49-277" aria-hidden="true" tabindex="-1"></a>If a house is not new: ŷ = −40,230.867 + 116.132(Size) </span>
<span id="cb49-278"><a href="#cb49-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-279"><a href="#cb49-279" aria-hidden="true" tabindex="-1"></a>New/not new is a binary variable, and only new houses see an increase in sale price. </span>
<span id="cb49-280"><a href="#cb49-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-281"><a href="#cb49-281" aria-hidden="true" tabindex="-1"></a><span class="fu">#### C </span></span>
<span id="cb49-282"><a href="#cb49-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-283"><a href="#cb49-283" aria-hidden="true" tabindex="-1"></a>**Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.**</span>
<span id="cb49-284"><a href="#cb49-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-285"><a href="#cb49-285" aria-hidden="true" tabindex="-1"></a>New: ŷ = −40,230.867 + (116.132*3000) + 57,736.283</span>
<span id="cb49-286"><a href="#cb49-286" aria-hidden="true" tabindex="-1"></a>Not new: ŷ = −40,230.867 + (116.132*3000)</span>
<span id="cb49-287"><a href="#cb49-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-290"><a href="#cb49-290" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-291"><a href="#cb49-291" aria-hidden="true" tabindex="-1"></a>New3000 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> (<span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span>) <span class="sc">+</span> <span class="fl">57736.283</span></span>
<span id="cb49-292"><a href="#cb49-292" aria-hidden="true" tabindex="-1"></a>NotNew3000 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> (<span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb49-293"><a href="#cb49-293" aria-hidden="true" tabindex="-1"></a>New3000</span>
<span id="cb49-294"><a href="#cb49-294" aria-hidden="true" tabindex="-1"></a>NotNew3000</span>
<span id="cb49-295"><a href="#cb49-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-296"><a href="#cb49-296" aria-hidden="true" tabindex="-1"></a>The predicted selling price for a new 3,000 square foot home is $365,901.40. The predicted selling price for a 3,000 square foot home that is not new is $308,165.10. </span>
<span id="cb49-297"><a href="#cb49-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-298"><a href="#cb49-298" aria-hidden="true" tabindex="-1"></a><span class="fu">#### D </span></span>
<span id="cb49-299"><a href="#cb49-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-300"><a href="#cb49-300" aria-hidden="true" tabindex="-1"></a>**Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results**</span>
<span id="cb49-301"><a href="#cb49-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-304"><a href="#cb49-304" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-305"><a href="#cb49-305" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a model allowing interaction between size and new</span></span>
<span id="cb49-306"><a href="#cb49-306" aria-hidden="true" tabindex="-1"></a>Price_SzNewInt <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size<span class="sc">:</span>New, <span class="at">data =</span> house.selling.price)</span>
<span id="cb49-307"><a href="#cb49-307" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Price_SzNewInt)</span>
<span id="cb49-308"><a href="#cb49-308" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-309"><a href="#cb49-309" aria-hidden="true" tabindex="-1"></a><span class="fu">#### E </span></span>
<span id="cb49-310"><a href="#cb49-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-311"><a href="#cb49-311" aria-hidden="true" tabindex="-1"></a>**Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.**</span>
<span id="cb49-312"><a href="#cb49-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-313"><a href="#cb49-313" aria-hidden="true" tabindex="-1"></a>ŷ = −22,227.808 + 104.438(Size) + (-78527.502(New)) + 61.916(Size*New)</span>
<span id="cb49-314"><a href="#cb49-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-315"><a href="#cb49-315" aria-hidden="true" tabindex="-1"></a>New: −22,227.808 + 104.438(Size) + (-78527.502(New)) + 61.916(Size*New)</span>
<span id="cb49-316"><a href="#cb49-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-317"><a href="#cb49-317" aria-hidden="true" tabindex="-1"></a>Not new: −22,227.808 + 104.438(Size)</span>
<span id="cb49-318"><a href="#cb49-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-319"><a href="#cb49-319" aria-hidden="true" tabindex="-1"></a><span class="fu">#### F </span></span>
<span id="cb49-320"><a href="#cb49-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-321"><a href="#cb49-321" aria-hidden="true" tabindex="-1"></a>**Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.**</span>
<span id="cb49-322"><a href="#cb49-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-325"><a href="#cb49-325" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-326"><a href="#cb49-326" aria-hidden="true" tabindex="-1"></a>NewInt3000 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span>) <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> (<span class="fl">61.916</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb49-327"><a href="#cb49-327" aria-hidden="true" tabindex="-1"></a>NotNewInt3000 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb49-328"><a href="#cb49-328" aria-hidden="true" tabindex="-1"></a>NewInt3000</span>
<span id="cb49-329"><a href="#cb49-329" aria-hidden="true" tabindex="-1"></a>NotNewInt3000</span>
<span id="cb49-330"><a href="#cb49-330" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-331"><a href="#cb49-331" aria-hidden="true" tabindex="-1"></a>The predicted selling price for a new, 3000 square-foot home is $398,306.70. The predicted selling price for a 3000 square-foot home that is not new is $291,086.20.</span>
<span id="cb49-332"><a href="#cb49-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-333"><a href="#cb49-333" aria-hidden="true" tabindex="-1"></a><span class="fu">#### G </span></span>
<span id="cb49-334"><a href="#cb49-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-335"><a href="#cb49-335" aria-hidden="true" tabindex="-1"></a>**Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.**</span>
<span id="cb49-336"><a href="#cb49-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-339"><a href="#cb49-339" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-340"><a href="#cb49-340" aria-hidden="true" tabindex="-1"></a>NewInt1500 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span>) <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> (<span class="fl">61.916</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb49-341"><a href="#cb49-341" aria-hidden="true" tabindex="-1"></a>NotNewInt1500 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> (<span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb49-342"><a href="#cb49-342" aria-hidden="true" tabindex="-1"></a>NewInt1500</span>
<span id="cb49-343"><a href="#cb49-343" aria-hidden="true" tabindex="-1"></a>NotNewInt1500</span>
<span id="cb49-344"><a href="#cb49-344" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb49-345"><a href="#cb49-345" aria-hidden="true" tabindex="-1"></a>**Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.**</span>
<span id="cb49-346"><a href="#cb49-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-347"><a href="#cb49-347" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>For 3000 square foot homes:</span>
<span id="cb49-348"><a href="#cb49-348" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>New: $398,306.70</span>
<span id="cb49-349"><a href="#cb49-349" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>Not New: $291,086.20</span>
<span id="cb49-350"><a href="#cb49-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-351"><a href="#cb49-351" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>For 1500 square foot homes:</span>
<span id="cb49-352"><a href="#cb49-352" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>New: $148,775.70</span>
<span id="cb49-353"><a href="#cb49-353" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>Not New: $134,429.20</span>
<span id="cb49-354"><a href="#cb49-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-355"><a href="#cb49-355" aria-hidden="true" tabindex="-1"></a>There is a $107,220.50 difference in sale price for the new/not new 3000 square foot homes but only a $14,346.50 difference in sale price for the new/not new 1500 square foot homes. Given the structure of the prediction equation, this makes a lot of sense - based on the predictive model, a house needs to be roughly 606 feet before it can be sold at a profit. A 1,500 square foot home has only roughly 894 "money making" square feet, while the 3000 square foot home has roughly 2394, and each money making square foot available adds 166.354 to the sale price.</span>
<span id="cb49-356"><a href="#cb49-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-357"><a href="#cb49-357" aria-hidden="true" tabindex="-1"></a><span class="fu">#### H</span></span>
<span id="cb49-358"><a href="#cb49-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-359"><a href="#cb49-359" aria-hidden="true" tabindex="-1"></a>**Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?**</span>
<span id="cb49-360"><a href="#cb49-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-361"><a href="#cb49-361" aria-hidden="true" tabindex="-1"></a>I think the model with the interaction more closely represents the relationship of size and newness to the outcome price. The p value for the model with interaction indicated statistical significance; further, the adjusted r squared for the model with interaction (0.7363) was higher than that for the model without (0.7169). </span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>