<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Akhilesh Kumar">
<meta name="dcterms.date" content="2023-05-09">
<meta name="description" content="The fifth homework">

<title>Homework 5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="styles.css">
<meta name="twitter:title" content="Homework 5">
<meta name="twitter:description" content="The fifth homework">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/HW5_AkhileshKumar_files/figure-html/unnamed-chunk-2-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">A</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">B</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">C</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">D</a>
  <ul class="collapse">
  <li><a href="#a.-r2" id="toc-a.-r2" class="nav-link" data-scroll-target="#a.-r2">a. R^2</a></li>
  <li><a href="#b.-adjusted-r2" id="toc-b.-adjusted-r2" class="nav-link" data-scroll-target="#b.-adjusted-r2">b. Adjusted R^2</a></li>
  <li><a href="#c.-press" id="toc-c.-press" class="nav-link" data-scroll-target="#c.-press">c.&nbsp;PRESS</a></li>
  <li><a href="#d.-aic" id="toc-d.-aic" class="nav-link" data-scroll-target="#d.-aic">d.&nbsp;AIC</a></li>
  <li><a href="#e.-bic" id="toc-e.-bic" class="nav-link" data-scroll-target="#e.-bic">e. BIC</a></li>
  </ul></li>
  <li><a href="#e" id="toc-e" class="nav-link" data-scroll-target="#e">E</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#a-1" id="toc-a-1" class="nav-link" data-scroll-target="#a-1">A</a></li>
  <li><a href="#b-1" id="toc-b-1" class="nav-link" data-scroll-target="#b-1">B</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  <li><a href="#a-2" id="toc-a-2" class="nav-link" data-scroll-target="#a-2">A</a></li>
  <li><a href="#b-2" id="toc-b-2" class="nav-link" data-scroll-target="#b-2">B</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 5</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Homework5</div>
    <div class="quarto-category">Akhilesh Kumar</div>
  </div>
  </div>

<div>
  <div class="description">
    The fifth homework
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Akhilesh Kumar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 9, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.0.10     ✔ readr     2.1.4 
✔ forcats   1.0.0      ✔ stringr   1.5.0 
✔ ggplot2   3.4.1      ✔ tibble    3.1.8 
✔ lubridate 1.9.2      ✔ tidyr     1.2.1 
✔ purrr     0.3.5      </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car
Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some

Loading required package: effects
lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MPV)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice
Loading required package: KernSmooth
KernSmooth 2.23 loaded
Copyright M. P. Wand 1997-2009
Loading required package: randomForest
randomForest 4.7-1.1
Type rfNews() to see new features/changes/bug fixes.

Attaching package: 'randomForest'

The following object is masked from 'package:dplyr':

    combine

The following object is masked from 'package:ggplot2':

    margin</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<p>(Data file: house.selling.price.2 from smss R package)</p>
<p>For the house.selling.price.2 data the tables below show a correlation matrix and a model fit using four predictors of selling price.</p>
<p>I prepared summary, correlation table, correlation plot, linear regression model for house.selling.price.2</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price<span class="fl">.2</span>, <span class="at">package=</span><span class="st">"smss"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Head, house.selling.price.2 </span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house.selling.price<span class="fl">.2</span>,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["P"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["S"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Be"],"name":[3],"type":["int"],"align":["right"]},{"label":["Ba"],"name":[4],"type":["int"],"align":["right"]},{"label":["New"],"name":[5],"type":["int"],"align":["right"]}],"data":[{"1":"48.5","2":"1.10","3":"3","4":"1","5":"0","_rn_":"1"},{"1":"55.0","2":"1.01","3":"3","4":"2","5":"0","_rn_":"2"},{"1":"68.0","2":"1.45","3":"3","4":"2","5":"0","_rn_":"3"},{"1":"137.0","2":"2.40","3":"3","4":"3","5":"0","_rn_":"4"},{"1":"309.4","2":"3.30","3":"4","4":"3","5":"1","_rn_":"5"},{"1":"17.5","2":"0.40","3":"1","4":"1","5":"0","_rn_":"6"},{"1":"19.6","2":"1.28","3":"3","4":"1","5":"0","_rn_":"7"},{"1":"24.5","2":"0.74","3":"3","4":"1","5":"0","_rn_":"8"},{"1":"34.8","2":"0.78","3":"2","4":"1","5":"0","_rn_":"9"},{"1":"32.0","2":"0.97","3":"3","4":"1","5":"0","_rn_":"10"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary, house.selling.price.2 </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(house.selling.price<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       P                S              Be              Ba       
 Min.   : 17.50   Min.   :0.40   Min.   :1.000   Min.   :1.000  
 1st Qu.: 72.90   1st Qu.:1.33   1st Qu.:3.000   1st Qu.:2.000  
 Median : 96.00   Median :1.57   Median :3.000   Median :2.000  
 Mean   : 99.53   Mean   :1.65   Mean   :3.183   Mean   :1.957  
 3rd Qu.:115.00   3rd Qu.:1.98   3rd Qu.:4.000   3rd Qu.:2.000  
 Max.   :309.40   Max.   :3.85   Max.   :5.000   Max.   :3.000  
      New        
 Min.   :0.0000  
 1st Qu.:0.0000  
 Median :0.0000  
 Mean   :0.3011  
 3rd Qu.:1.0000  
 Max.   :1.0000  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creating house_price_2 object for house.selling.price.2</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>house_price_2<span class="ot">&lt;-</span>house.selling.price<span class="fl">.2</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation matrix</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>correlation_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(house_price_2)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(correlation_matrix, <span class="at">border =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            P         S        Be        Ba       New
P   1.0000000 0.8988136 0.5902675 0.7136960 0.3565540
S   0.8988136 1.0000000 0.6691137 0.6624828 0.1762879
Be  0.5902675 0.6691137 1.0000000 0.3337966 0.2672091
Ba  0.7136960 0.6624828 0.3337966 1.0000000 0.1820651
New 0.3565540 0.1762879 0.2672091 0.1820651 1.0000000</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a correlation plot</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>col <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>))(<span class="at">n =</span> <span class="dv">100</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(correlation_matrix, <span class="at">type =</span> <span class="st">"upper"</span>, <span class="at">tl.col =</span> <span class="st">"black"</span>, <span class="at">tl.srt =</span> <span class="dv">45</span>, <span class="at">tl.cex =</span> <span class="fl">1.2</span>, <span class="at">method =</span> <span class="st">"circle"</span>, <span class="at">col =</span> col, <span class="at">diag =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HW5_AkhileshKumar_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Correlation Analysis</strong></p>
<p>The correlation table shows the strength and direction of the relationship between variables. The values on the off-diagonal represent the correlation coefficient between two variables. A strong positive correlation is observed between P and S (0.8988), while a moderate positive correlation exists between P and Ba (0.7137). P and Be exhibit a weak positive correlation (0.5903). In contrast, P and New have a weak positive correlation (0.3566).</p>
<p>Overall, the correlation table indicates that the predictor variables are moderately to strongly correlated with the response variable, with S demonstrating the strongest correlation. However, it is important to remember that correlation does not imply causation, and further analysis is necessary to determine the causal relationship between the variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression for all predictors</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>fit_house_price_2<span class="ot">&lt;-</span><span class="fu">lm</span>(P<span class="sc">~</span>.,house_price_2)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co">#summary linear model house price 2  </span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_house_price_2)                   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ ., data = house_price_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-36.212  -9.546   1.277   9.406  71.953 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -41.795     12.104  -3.453 0.000855 ***
S             64.761      5.630  11.504  &lt; 2e-16 ***
Be            -2.766      3.960  -0.698 0.486763    
Ba            19.203      5.650   3.399 0.001019 ** 
New           18.984      3.873   4.902  4.3e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.36 on 88 degrees of freedom
Multiple R-squared:  0.8689,    Adjusted R-squared:  0.8629 
F-statistic: 145.8 on 4 and 88 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Regression Analysis</strong></p>
<p>The linear regression analysis shows that the variables S, Ba, and New are statistically significant predictors of the response variable P, with p-values less than 0.05. The intercept term is also statistically significant. The model explains a large portion of the variation in the response variable, with a multiple R-squared value of 0.8689. The residual standard error of 16.36 indicates that the model’s predicted values are within 16.36 units of the actual values on average.</p>
</section>
<section id="a" class="level2">
<h2 class="anchored" data-anchor-id="a">A</h2>
<p>For backward elimination, which variable would be deleted first? Why?</p>
<p>In backward elimination, the variable with the highest p-value is deleted first. This is because the p-value measures the statistical significance of each variable, and a high p-value indicates that there is a high probability that the variable’s coefficient is not significantly different from zero, and therefore the variable is not contributing significantly to the model.</p>
<p>For question 1.A, the variable “Be/Beds” has the highest p-value of 0.486763, which is greater than the significance level of 0.05, it would be the first variable to be removed. This conclusion can be confirmed by using the step() function.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit full model</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>fit_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># perform backward stepwise selection</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>fit_backward <span class="ot">&lt;-</span> <span class="fu">step</span>(fit_full, <span class="at">direction =</span> <span class="st">"backward"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=524.7
P ~ S + Be + Ba + New

       Df Sum of Sq   RSS    AIC
- Be    1       131 23684 523.21
&lt;none&gt;              23553 524.70
- Ba    1      3092 26645 534.17
- New   1      6432 29985 545.15
- S     1     35419 58972 608.06

Step:  AIC=523.21
P ~ S + Ba + New

       Df Sum of Sq   RSS    AIC
&lt;none&gt;              23684 523.21
- Ba    1      3550 27234 534.20
- New   1      6349 30033 543.30
- S     1     54898 78582 632.75</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_backward)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ S + Ba + New, data = house_price_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-34.804  -9.496   0.917   7.931  73.338 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -47.992      8.209  -5.847 8.15e-08 ***
S             62.263      4.335  14.363  &lt; 2e-16 ***
Ba            20.072      5.495   3.653 0.000438 ***
New           18.371      3.761   4.885 4.54e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.31 on 89 degrees of freedom
Multiple R-squared:  0.8681,    Adjusted R-squared:  0.8637 
F-statistic: 195.3 on 3 and 89 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Backward Elimination Analysis:</strong></p>
<p>The backward stepwise selection approach was used to determine the best predictors of house prices. Backward elimination starts with a full model, and successively drops variables that do not contribute to the model meaningfully. Therefore, since the variable Be has the largest <em>p-value</em> of 0.4867 it would be eliminated first.</p>
<p>The final model included three predictor variables, namely S, Ba, and New, with a significant positive effect on the response variable P. The adjusted R-squared value of 0.8637 indicates that these variables explain approximately 86.37% of the variability in P. The significant F-statistic and low p-value further support the idea that the model is a good fit for the data. Overall, the results suggest that the selected variables can be used as reliable predictors of house prices.</p>
</section>
<section id="b" class="level2">
<h2 class="anchored" data-anchor-id="b">B</h2>
<p>For forward selection, which variable would be added first? Why?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform forward selection</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>forward_model <span class="ot">&lt;-</span> <span class="fu">step</span>(fit_full, <span class="at">direction =</span> <span class="st">"forward"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=524.7
P ~ S + Be + Ba + New</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(forward_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ S + Be + Ba + New, data = house_price_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-36.212  -9.546   1.277   9.406  71.953 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -41.795     12.104  -3.453 0.000855 ***
S             64.761      5.630  11.504  &lt; 2e-16 ***
Be            -2.766      3.960  -0.698 0.486763    
Ba            19.203      5.650   3.399 0.001019 ** 
New           18.984      3.873   4.902  4.3e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.36 on 88 degrees of freedom
Multiple R-squared:  0.8689,    Adjusted R-squared:  0.8629 
F-statistic: 145.8 on 4 and 88 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Forward Selection Analysis:</strong></p>
<p>In forward selection, the variable with the lowest p-value is added first, as a smaller p-value indicates a stronger evidence against the null hypothesis that the predictor has no effect on the response variable.</p>
<p>In the full model, we can see that the variable with the lowest p-value is S (p-value &lt; 2e-16), indicating that it is highly significant in predicting the house price. Therefore, if we were to use forward selection based on p-values, S would be added first to the model, followed by Ba, New, and finally Be, in that order, as none of the other variables have p-values lower than S.</p>
</section>
<section id="c" class="level2">
<h2 class="anchored" data-anchor-id="c">C</h2>
<p>Why do you think that BEDS has such a large P-value in the multiple regression model, even though it has a substantial correlation with PRICE?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit multiple regression model</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate VIF for each predictor variable</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>vif <span class="ot">&lt;-</span> <span class="fu">vif</span>(fit)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print VIF values</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vif)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       S       Be       Ba      New 
3.005554 1.985583 1.887778 1.096606 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of PRICE against BEDS</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(house_price_2<span class="sc">$</span>Be, house_price_2<span class="sc">$</span>P, <span class="at">xlab =</span> <span class="st">"BEDS"</span>, <span class="at">ylab =</span> <span class="st">"Price"</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a linear regression line to the plot</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(P <span class="sc">~</span> Be, <span class="at">data =</span> house_price_2), <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HW5_AkhileshKumar_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># size of Dataset, house_price_2</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(house_price_2)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 93</code></pre>
</div>
</div>
<p><strong>Analysis:</strong></p>
<p>Regression model can be impacted by various factors such as multicollinearity, other predictors, unaccounted confounding factors, and small sample size.</p>
<ul>
<li><p>While the VIF values above indicate no significant multicollinearity among predictor variables, the presence of outliers and non-linearity can still affect the model’s accuracy and interpretability.</p></li>
<li><p>Despite a strong correlation between BEDS and PRICE, the large p-value of BEDS in the multiple regression model suggests that its relationship with PRICE is not significant after controlling for other predictor variables. Other predictors included in the model might explain some of the variability that BEDS previously accounted for, or there could be other unaccounted confounding factors that affect the relationship. Therefore, a thorough examination of other predictors and potential confounding factors is necessary for an accurate interpretation of the regression analysis results.</p></li>
<li><p>Moreover, sample size can affect the precision of estimates, and a small sample size of 93 may be inadequate, which could contribute to the large p-value and substantial correlation observed.</p></li>
</ul>
</section>
<section id="d" class="level2">
<h2 class="anchored" data-anchor-id="d">D</h2>
<p>Using software with these four predictors, find the model that would be selected using each criterion:</p>
<ol type="1">
<li>R2</li>
<li>Adjusted R2</li>
<li>PRESS</li>
<li>AIC</li>
<li>BIC</li>
</ol>
<p>Prepared different linear regression models fitted to the “house_price_2” dataset with different combination of independent variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ S, data = house_price_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-56.407 -10.656   2.126  11.412  85.091 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -25.194      6.688  -3.767 0.000293 ***
S             75.607      3.865  19.561  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.47 on 91 degrees of freedom
Multiple R-squared:  0.8079,    Adjusted R-squared:  0.8058 
F-statistic: 382.6 on 1 and 91 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S<span class="sc">+</span>New, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ S + New, data = house_price_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-47.207  -9.763  -0.091   9.984  76.405 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -26.089      5.977  -4.365 3.39e-05 ***
S             72.575      3.508  20.690  &lt; 2e-16 ***
New           19.587      3.995   4.903 4.16e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.4 on 90 degrees of freedom
Multiple R-squared:  0.8484,    Adjusted R-squared:  0.845 
F-statistic: 251.8 on 2 and 90 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ ., data = house_price_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-36.212  -9.546   1.277   9.406  71.953 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -41.795     12.104  -3.453 0.000855 ***
S             64.761      5.630  11.504  &lt; 2e-16 ***
Be            -2.766      3.960  -0.698 0.486763    
Ba            19.203      5.650   3.399 0.001019 ** 
New           18.984      3.873   4.902  4.3e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.36 on 88 degrees of freedom
Multiple R-squared:  0.8689,    Adjusted R-squared:  0.8629 
F-statistic: 145.8 on 4 and 88 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ . - Be, data = house_price_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-34.804  -9.496   0.917   7.931  73.338 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -47.992      8.209  -5.847 8.15e-08 ***
S             62.263      4.335  14.363  &lt; 2e-16 ***
Ba            20.072      5.495   3.653 0.000438 ***
New           18.371      3.761   4.885 4.54e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.31 on 89 degrees of freedom
Multiple R-squared:  0.8681,    Adjusted R-squared:  0.8637 
F-statistic: 195.3 on 3 and 89 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be <span class="sc">-</span>Ba, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ . - Be - Ba, data = house_price_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-47.207  -9.763  -0.091   9.984  76.405 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -26.089      5.977  -4.365 3.39e-05 ***
S             72.575      3.508  20.690  &lt; 2e-16 ***
New           19.587      3.995   4.903 4.16e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.4 on 90 degrees of freedom
Multiple R-squared:  0.8484,    Adjusted R-squared:  0.845 
F-statistic: 251.8 on 2 and 90 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="a.-r2" class="level3">
<h3 class="anchored" data-anchor-id="a.-r2">a. R^2</h3>
<p>The model with the most explanatory variables has the highest R-squared value of 0.8689, it indicates that this model accounts for 86.89% of the variability in the response variable. Based on this criterion, selecting a model that maximizes the R-squared value would lead to the selection of the model with all predictor variables included, resulting in the equation: ŷ = -41.79 + 64.76(Size) - 2.77(Beds) + 19.2(Baths) + 18.98(New).</p>
</section>
<section id="b.-adjusted-r2" class="level3">
<h3 class="anchored" data-anchor-id="b.-adjusted-r2">b. Adjusted R^2</h3>
<p>The adjusted R-squared value of the model with Size, Baths, and New as explanatory variables and excluding Beds is 0.8637, indicating that this model explains around 86.37% of the variation in the response variable. It also considers the possibility that some of the variables may not be significant or may be redundant.</p>
<p>Based on the adjusted R-squared criterion, the model with Size, Baths, and New is the most appropriate for predicting selling price, as it has the highest adjusted R-squared value among the tested models. The model is represented by ŷ = -47.99 + 62.26(Size) + 20.07(Baths) + 18.37(New).</p>
</section>
<section id="c.-press" class="level3">
<h3 class="anchored" data-anchor-id="c.-press">c.&nbsp;PRESS</h3>
<p>I prepared different linear regression models, fitted on the “house_price_2” dataset with varying combinations of independent variables, and PRESS is used to evaluate the predictive performance of the models.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38203.29</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S<span class="sc">+</span>New, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31066</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(<span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28390.22</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27860.05</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be <span class="sc">-</span>Ba, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31066</code></pre>
</div>
</div>
<p>Based on the Predictive Residual Sum of Squares (PRESS) criterion, a smaller value indicates a better predictive model. Five regression models were evaluated, and the results indicate that the model with Size, Baths, and New as predictors (excluding Bed) has the lowest PRESS value of 27,860.05. This finding suggests that this model is the most effective in predicting the selling price of houses in this dataset.</p>
<p>Thus, based on the PRESS criterion, it is reasonable to select the model with Size, Baths, and New as variables for predicting selling price.</p>
</section>
<section id="d.-aic" class="level3">
<h3 class="anchored" data-anchor-id="d.-aic">d.&nbsp;AIC</h3>
<p>I prepared different linear regression models, fitted on the “house_price_2” dataset with varying combinations of independent variables, and AIC is used to evaluate the predictive performance of the models.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 820.1439</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S<span class="sc">+</span>New, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 800.1262</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 790.6225</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 789.1366</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be <span class="sc">-</span>Ba, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 800.1262</code></pre>
</div>
</div>
<p>When considering the Akaike Information Criterion (AIC), a lower AIC value indicates a better model fit. In this case, the AIC values have been calculated for five different regression models. The results show that the model with Size, Baths, and New as predictors (excluding Bed and Basement) has the lowest AIC value of 789.1366. This suggests that this model provides the best balance between model complexity and goodness of fit, compared to the other models.</p>
<p>Therefore, based on the AIC criterion, it seems reasonable to select the model with Size, Baths, and New; as variables for predicting selling price.</p>
</section>
<section id="e.-bic" class="level3">
<h3 class="anchored" data-anchor-id="e.-bic">e. BIC</h3>
<p>I prepared different linear regression models, fitted on the “house_price_2” dataset with varying combinations of independent variables, and BIC is used to evaluate the predictive performance of the models.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 827.7417</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S<span class="sc">+</span>New, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 810.2566</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 805.8181</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 801.7996</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be <span class="sc">-</span>Ba, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 810.2566</code></pre>
</div>
</div>
<p>The Bayesian Information Criterion (BIC) is a statistical criterion used for model selection in regression analysis that balances the goodness of fit of the model with its complexity. A lower BIC value indicates a better fit of the model to the data, while also taking into account the number of predictors included in the model.</p>
<p>In this case, the model with the lowest BIC value is the one that includes all predictors except for Bed, with a BIC value of 801.7996. This suggests that this model is the best fit for the data while also being the least complex. Therefore, based on the BIC criterion, it would be reasonable to select the model with Size, Baths, and New as predictors for predicting selling price, while excluding Bed.</p>
</section>
</section>
<section id="e" class="level2">
<h2 class="anchored" data-anchor-id="e">E</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be, <span class="at">data =</span> house_price_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ . - Be, data = house_price_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-34.804  -9.496   0.917   7.931  73.338 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -47.992      8.209  -5.847 8.15e-08 ***
S             62.263      4.335  14.363  &lt; 2e-16 ***
Ba            20.072      5.495   3.653 0.000438 ***
New           18.371      3.761   4.885 4.54e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.31 on 89 degrees of freedom
Multiple R-squared:  0.8681,    Adjusted R-squared:  0.8637 
F-statistic: 195.3 on 3 and 89 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Based on the various criteria analyzed, including R-Squared, Adjusted R-Squared, PRESS, AIC, and BIC, the model with the highest overall performance and thus the best fit for predicting selling price is the one that excludes Beds and includes Size, Baths, and New as variables. This model has a lower PRESS value, a lower AIC value, and a lower BIC value than the model that includes all variables. Additionally, it has a slightly higher adjusted R-squared value than the full model. Therefore, the preferred model for predicting selling price is: ŷ = -47.99 + 62.26(Size) + 20.07(Baths) + 18.37(New). It is important to note that while R-Squared is not the sole determinant of model strength, it can still provide some insight into the model’s performance.</p>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>(Data file: trees from base R) From the documentation: “This data set provides measurements of the diameter, height and volume of timber in 31 felled black cherry trees. Note that the diameter (in inches) is erroneously labeled Girth in the data. It is measured at 4 ft 6 in above the ground.” Tree volume estimation is a big deal, especially in the lumber industry. Use the trees data to build a basic model of tree volume prediction. In particular,</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"trees"</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(trees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Girth"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Height"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Volume"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"8.3","2":"70","3":"10.3","_rn_":"1"},{"1":"8.6","2":"65","3":"10.3","_rn_":"2"},{"1":"8.8","2":"63","3":"10.2","_rn_":"3"},{"1":"10.5","2":"72","3":"16.4","_rn_":"4"},{"1":"10.7","2":"81","3":"18.8","_rn_":"5"},{"1":"10.8","2":"83","3":"19.7","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(trees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     Girth           Height       Volume     
 Min.   : 8.30   Min.   :63   Min.   :10.20  
 1st Qu.:11.05   1st Qu.:72   1st Qu.:19.40  
 Median :12.90   Median :76   Median :24.20  
 Mean   :13.25   Mean   :76   Mean   :30.17  
 3rd Qu.:15.25   3rd Qu.:80   3rd Qu.:37.30  
 Max.   :20.60   Max.   :87   Max.   :77.00  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#renaming erroneously labelled variable Girth to Diameter</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>trees_d<span class="ot">&lt;-</span>trees <span class="sc">%&gt;%</span>          </span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Diameter=</span>Girth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Prepared Data and Summary of trees dataset; renamed the variable Girth to Diameter since in the instructions it says,that Girth is labelled erroneously.</p>
</section>
<section id="a-1" class="level2">
<h2 class="anchored" data-anchor-id="a-1">A</h2>
<p>Fit a multiple regression model with the Volume as the outcome and Girth and Height as the explanatory variables</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Diameter <span class="sc">+</span> Height, <span class="at">data =</span> trees_d)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Volume ~ Diameter + Height, data = trees_d)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.4065 -2.6493 -0.2876  2.2003  8.4847 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -57.9877     8.6382  -6.713 2.75e-07 ***
Diameter      4.7082     0.2643  17.816  &lt; 2e-16 ***
Height        0.3393     0.1302   2.607   0.0145 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.882 on 28 degrees of freedom
Multiple R-squared:  0.948, Adjusted R-squared:  0.9442 
F-statistic:   255 on 2 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The linear regression model predicts tree volume based on the diameter and height of the tree. Both predictors have small p-values, indicating statistical significance and supporting the idea that they are related to tree volume. The model has a high degree of linear correlation, with an R-squared value close to 1.00 at 0.948, indicating that it explains a large proportion of the variance in the data. The adjusted R-squared value is also high at 0.9442, indicating that the model is not overfitting to the data.</p>
</section>
<section id="b-1" class="level2">
<h2 class="anchored" data-anchor-id="b-1">B</h2>
<p>Run regression diagnostic plots on the model. Based on the plots, do you think any of the regression assumptions is violated?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)); </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">pch=</span><span class="dv">15</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HW5_AkhileshKumar_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="HW5_AkhileshKumar_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Residuals vs.&nbsp;Fitted</strong></p>
<p>The residuals vs.&nbsp;fitted values plot is a useful tool for detecting non-linear patterns in the residuals. When the red line is approximately flat and horizontal at zero, it suggests that the residuals follow a linear pattern. In the case of the trees dataset, the red line is not perfectly horizontal, but it deviates only slightly. This indicates that the residuals exhibit a roughly non-linear pattern and that a non-linear model may be more appropriate for this data. Thus, the assumption of linearity in the regression model is violated.</p>
<p><strong>Normal Q-Q</strong></p>
<p>This plot is used to check if the residuals of a regression model are normally distributed. If the points in the plot follow a straight diagonal line, it can be assumed that the residuals have a normal distribution. In this dataset, the points generally follow a straight diagonal line, indicating that the residuals are normally distributed. However, there are a few observations near the top of the plot that deviate from the line, suggesting some potential non-normality. Overall, it’s difficult to confidently determine if the assumption of normality is violated based on this plot alone.</p>
<p><strong>Scale-Location</strong></p>
<p>The plot being referred to is the Scale-Location plot. It checks the assumption of equal variance, or homoscedasticity, among the residuals in the regression model. A horizontal red line across the plot indicates that the assumption of equal variance is likely met. However, in this case, the red line is not horizontal, which may suggest that equal variance is violated. This violation is also suggested by the non-horizontal trend-line in the Scale-Location plot. Therefore, the assumption of constant variance may be violated for this dataset.</p>
<p><strong>Cook’s Distance</strong></p>
<p>Determine Influential Variables:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>cooks_D <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(model)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>influential <span class="ot">&lt;-</span> cooks_D[(cooks_D <span class="sc">&gt;</span> (<span class="dv">3</span> <span class="sc">*</span> <span class="fu">mean</span>(cooks_D, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))]</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>influential</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        3        18        31 
0.1673192 0.1775359 0.6052326 </code></pre>
</div>
</div>
<p>The Cook’s Distance plot is used to identify influential observations in a regression model by combining leverage and residual information. It provides a summary of how much the model changes if a certain data point is removed. For this dataset, the plot indicates that observations 31, 18, and 3 have the highest Cook’s Distances, which are also confirmed by the Cook’s Distance function. These observations are considered highly influential.</p>
<p><strong>Residuals vs.&nbsp;Leverage</strong></p>
<p>This plot is designed to identify influential observations with high leverage, where points outside the Cook’s distance lines are deemed influential. Here, the presence of highly leveraged observations suggests the existence of influential points in the data.</p>
<p><strong>Cooks Distance vs Leverage</strong></p>
<p>Similar to the Cook’s Distance plot, this plot also helps identify highly influential data points. In this case, we can see that data points 3, 18, and 31 are highly influential, which is consistent with the Cook’s Distance plot.</p>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<p>(Data file: florida in alr R package) In the 2000 election for U.S. president, the counting of votes in Florida was controversial. In Palm Beach County in south Florida, for example, voters used a so-called butterfly ballot. Some believe that the layout of the ballot caused some voters to cast votes for Buchanan when their intended choice was Gore.</p>
<p>The data has variables for the number of votes for each candidate—Gore, Bush, and Buchanan.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"florida"</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(florida)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Gore"],"name":[1],"type":["int"],"align":["right"]},{"label":["Bush"],"name":[2],"type":["int"],"align":["right"]},{"label":["Buchanan"],"name":[3],"type":["int"],"align":["right"]}],"data":[{"1":"47300","2":"34062","3":"262","_rn_":"ALACHUA"},{"1":"2392","2":"5610","3":"73","_rn_":"BAKER"},{"1":"18850","2":"38637","3":"248","_rn_":"BAY"},{"1":"3072","2":"5413","3":"65","_rn_":"BRADFORD"},{"1":"97318","2":"115185","3":"570","_rn_":"BREVARD"},{"1":"386518","2":"177279","3":"789","_rn_":"BROWARD"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(florida)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      Gore             Bush           Buchanan     
 Min.   :   788   Min.   :  1316   Min.   :   9.0  
 1st Qu.:  3055   1st Qu.:  4746   1st Qu.:  46.5  
 Median : 14152   Median : 20196   Median : 114.0  
 Mean   : 43341   Mean   : 43356   Mean   : 258.5  
 3rd Qu.: 45974   3rd Qu.: 56542   3rd Qu.: 285.5  
 Max.   :386518   Max.   :289456   Max.   :3407.0  </code></pre>
</div>
</div>
</section>
<section id="a-2" class="level2">
<h2 class="anchored" data-anchor-id="a-2">A</h2>
<p>Run a simple linear regression model where the Buchanan vote is the outcome and the Bush vote is the explanatory variable. Produce the regression diagnostic plots. Is Palm Beach County an outlier based on the diagnostic plots? Why or why not?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Buchanan <span class="sc">~</span> Bush, <span class="at">data =</span> florida)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Buchanan ~ Bush, data = florida)

Residuals:
    Min      1Q  Median      3Q     Max 
-907.50  -46.10  -29.19   12.26 2610.19 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.529e+01  5.448e+01   0.831    0.409    
Bush        4.917e-03  7.644e-04   6.432 1.73e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 353.9 on 65 degrees of freedom
Multiple R-squared:  0.3889,    Adjusted R-squared:  0.3795 
F-statistic: 41.37 on 1 and 65 DF,  p-value: 1.727e-08</code></pre>
</div>
</div>
<p><strong>Analysis:</strong></p>
<p>The linear regression model aims to predict Buchanan’s votes based on the number of votes for Bush in Florida. The model found a significant relationship between the two variables, with Bush’s coefficient estimate at 0.0049 and a very small p-value of 1.73e-08, which means that the probability of getting such a result by chance is almost zero. The intercept estimate, however, is not significant with a p-value of 0.409. The R-squared value of 0.3889 suggests that the model explains 38.89% of the variance in Buchanan’s votes. The adjusted R-squared value of 0.3795 is slightly lower, indicating that adding the Bush variable did not significantly improve the model’s fit. The residual standard error of 353.9 suggests that the model’s predictions may deviate from the actual values by an average of 353.9 votes.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">pch =</span><span class="dv">15</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HW5_AkhileshKumar_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Analysis:</strong></p>
<p>Based on the diagnostic plots, Palm Beach County is an outlier. First, when looking at the residuals vs fitted plot, the Palm Beach County residual is very large. When referring to the summary of the simple regression model, the third quartile for residuals is 12.26, yet the max is 2610.19. This is a significant jump and indicative of the value being an outlier. The normal Q-Q plot also indicates that the residuals for the model are generally normal except for the Palm Beach County residual, as it greatly deviates from the line in the plot. The Cook’s distance plot shows two points that may be of concern as outliers if you follow the metric of observations scoring over 1, which are DADE and Palm Beach at about 2. The residuals and leverages plot shows the Palm Beach County standardized residual value beyond the dashed line indicating Cook’s distance. This also suggests that the observation is an outlier and the observation has the potential to influence the regression model.</p>
</section>
<section id="b-2" class="level2">
<h2 class="anchored" data-anchor-id="b-2">B</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> <span class="fu">log</span>(Buchanan) <span class="sc">~</span> <span class="fu">log</span>(Bush), <span class="at">data =</span> florida)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Buchanan) ~ log(Bush), data = florida)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.96075 -0.25949  0.01282  0.23826  1.66564 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.57712    0.38919  -6.622 8.04e-09 ***
log(Bush)    0.75772    0.03936  19.251  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4673 on 65 degrees of freedom
Multiple R-squared:  0.8508,    Adjusted R-squared:  0.8485 
F-statistic: 370.6 on 1 and 65 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Analysis:</strong></p>
<p>This is a linear regression model where the dependent variable is the natural logarithm of Buchanan’s votes and the independent variable is the natural logarithm of Bush’s votes in Florida. The model shows a significant positive relationship between the two variables, with a coefficient estimate of 0.75772 for log(Bush) and a very small p-value of &lt;2e-16, indicating that the relationship is not due to chance. The intercept estimate of -2.57712 is also significant with a small p-value of 8.04e-09. The model’s R-squared value of 0.8508 indicates that 85.08% of the variance in Buchanan’s votes is explained by the model, and the adjusted R-squared value of 0.8485 suggests that adding the Bush variable did not significantly improve the model’s fit. The residual standard error of 0.4673 suggests that the model’s predictions may deviate from the actual values by an average of 0.4673 votes.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">pch =</span><span class="dv">15</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HW5_AkhileshKumar_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="HW5_AkhileshKumar_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Analysis:</strong></p>
<p>After examining the diagnostic plots, it appears that Palm Beach County is still an outlier. The residuals vs fitted plot shows that the Palm Beach County residual remains unusually large. The normal Q-Q plot also indicates that the residuals for the model are generally normal except for the Palm Beach County residual, which significantly deviates from the line in the plot. According to the Cook’s distance plot, Palm Beach County is an outlier with a score of about 0.3, which exceeds the threshold of 0.2. In addition, the residuals and leverages plot shows that the standardized residual value for Palm Beach County is beyond the dashed line indicating Cook’s distance, further suggesting that this observation is an outlier and has the potential to influence the regression model.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb92" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 5"</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Akhilesh Kumar"</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "The fifth homework"</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/9/2023"</span></span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb92-11"><a href="#cb92-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb92-12"><a href="#cb92-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb92-13"><a href="#cb92-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb92-14"><a href="#cb92-14" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb92-15"><a href="#cb92-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - Homework5</span></span>
<span id="cb92-16"><a href="#cb92-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - Akhilesh Kumar</span></span>
<span id="cb92-17"><a href="#cb92-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb92-18"><a href="#cb92-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-19"><a href="#cb92-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb92-20"><a href="#cb92-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb92-21"><a href="#cb92-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb92-22"><a href="#cb92-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb92-23"><a href="#cb92-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb92-24"><a href="#cb92-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MPV)</span>
<span id="cb92-25"><a href="#cb92-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb92-26"><a href="#cb92-26" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb92-27"><a href="#cb92-27" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-28"><a href="#cb92-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-29"><a href="#cb92-29" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 1</span></span>
<span id="cb92-30"><a href="#cb92-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-31"><a href="#cb92-31" aria-hidden="true" tabindex="-1"></a>(Data file: house.selling.price.2 from smss R package)</span>
<span id="cb92-32"><a href="#cb92-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-33"><a href="#cb92-33" aria-hidden="true" tabindex="-1"></a>For the house.selling.price.2 data the tables below show a correlation matrix and a model fit using four predictors of selling price.</span>
<span id="cb92-34"><a href="#cb92-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-35"><a href="#cb92-35" aria-hidden="true" tabindex="-1"></a>I prepared summary, correlation table, correlation plot, linear regression model for house.selling.price.2</span>
<span id="cb92-36"><a href="#cb92-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-37"><a href="#cb92-37" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb92-38"><a href="#cb92-38" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price<span class="fl">.2</span>, <span class="at">package=</span><span class="st">"smss"</span>)</span>
<span id="cb92-39"><a href="#cb92-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-40"><a href="#cb92-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Head, house.selling.price.2 </span></span>
<span id="cb92-41"><a href="#cb92-41" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house.selling.price<span class="fl">.2</span>,<span class="dv">10</span>)</span>
<span id="cb92-42"><a href="#cb92-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-43"><a href="#cb92-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary, house.selling.price.2 </span></span>
<span id="cb92-44"><a href="#cb92-44" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(house.selling.price<span class="fl">.2</span>)</span>
<span id="cb92-45"><a href="#cb92-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-46"><a href="#cb92-46" aria-hidden="true" tabindex="-1"></a><span class="co"># creating house_price_2 object for house.selling.price.2</span></span>
<span id="cb92-47"><a href="#cb92-47" aria-hidden="true" tabindex="-1"></a>house_price_2<span class="ot">&lt;-</span>house.selling.price<span class="fl">.2</span></span>
<span id="cb92-48"><a href="#cb92-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-49"><a href="#cb92-49" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation matrix</span></span>
<span id="cb92-50"><a href="#cb92-50" aria-hidden="true" tabindex="-1"></a>correlation_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(house_price_2)</span>
<span id="cb92-51"><a href="#cb92-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-52"><a href="#cb92-52" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(correlation_matrix, <span class="at">border =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb92-53"><a href="#cb92-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-54"><a href="#cb92-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a correlation plot</span></span>
<span id="cb92-55"><a href="#cb92-55" aria-hidden="true" tabindex="-1"></a>col <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>))(<span class="at">n =</span> <span class="dv">100</span>)</span>
<span id="cb92-56"><a href="#cb92-56" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(correlation_matrix, <span class="at">type =</span> <span class="st">"upper"</span>, <span class="at">tl.col =</span> <span class="st">"black"</span>, <span class="at">tl.srt =</span> <span class="dv">45</span>, <span class="at">tl.cex =</span> <span class="fl">1.2</span>, <span class="at">method =</span> <span class="st">"circle"</span>, <span class="at">col =</span> col, <span class="at">diag =</span> <span class="cn">FALSE</span>)</span>
<span id="cb92-57"><a href="#cb92-57" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-58"><a href="#cb92-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-59"><a href="#cb92-59" aria-hidden="true" tabindex="-1"></a>**Correlation Analysis**</span>
<span id="cb92-60"><a href="#cb92-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-61"><a href="#cb92-61" aria-hidden="true" tabindex="-1"></a>The correlation table shows the strength and direction of the relationship between variables. The values on the off-diagonal represent the correlation coefficient between two variables. A strong positive correlation is observed between P and S (0.8988), while a moderate positive correlation exists between P and Ba (0.7137). P and Be exhibit a weak positive correlation (0.5903). In contrast, P and New have a weak positive correlation (0.3566).</span>
<span id="cb92-62"><a href="#cb92-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-63"><a href="#cb92-63" aria-hidden="true" tabindex="-1"></a>Overall, the correlation table indicates that the predictor variables are moderately to strongly correlated with the response variable, with S demonstrating the strongest correlation. However, it is important to remember that correlation does not imply causation, and further analysis is necessary to determine the causal relationship between the variables.</span>
<span id="cb92-64"><a href="#cb92-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-65"><a href="#cb92-65" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb92-66"><a href="#cb92-66" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression for all predictors</span></span>
<span id="cb92-67"><a href="#cb92-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-68"><a href="#cb92-68" aria-hidden="true" tabindex="-1"></a>fit_house_price_2<span class="ot">&lt;-</span><span class="fu">lm</span>(P<span class="sc">~</span>.,house_price_2)</span>
<span id="cb92-69"><a href="#cb92-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-70"><a href="#cb92-70" aria-hidden="true" tabindex="-1"></a><span class="co">#summary linear model house price 2  </span></span>
<span id="cb92-71"><a href="#cb92-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-72"><a href="#cb92-72" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_house_price_2)                   </span>
<span id="cb92-73"><a href="#cb92-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-74"><a href="#cb92-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-75"><a href="#cb92-75" aria-hidden="true" tabindex="-1"></a>**Regression Analysis**</span>
<span id="cb92-76"><a href="#cb92-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-77"><a href="#cb92-77" aria-hidden="true" tabindex="-1"></a>The linear regression analysis shows that the variables S, Ba, and New are statistically significant predictors of the response variable P, with p-values less than 0.05. The intercept term is also statistically significant. The model explains a large portion of the variation in the response variable, with a multiple R-squared value of 0.8689. The residual standard error of 16.36 indicates that the model's predicted values are within 16.36 units of the actual values on average.</span>
<span id="cb92-78"><a href="#cb92-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-79"><a href="#cb92-79" aria-hidden="true" tabindex="-1"></a><span class="fu">## A</span></span>
<span id="cb92-80"><a href="#cb92-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-81"><a href="#cb92-81" aria-hidden="true" tabindex="-1"></a>For backward elimination, which variable would be deleted first? Why?</span>
<span id="cb92-82"><a href="#cb92-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-83"><a href="#cb92-83" aria-hidden="true" tabindex="-1"></a>In backward elimination, the variable with the highest p-value is deleted first. This is because the p-value measures the statistical significance of each variable, and a high p-value indicates that there is a high probability that the variable's coefficient is not significantly different from zero, and therefore the variable is not contributing significantly to the model.</span>
<span id="cb92-84"><a href="#cb92-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-85"><a href="#cb92-85" aria-hidden="true" tabindex="-1"></a>For question 1.A, the variable "Be/Beds" has the highest p-value of 0.486763, which is greater than the significance level of 0.05, it would be the first variable to be removed. This conclusion can be confirmed by using the step() function.</span>
<span id="cb92-86"><a href="#cb92-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-87"><a href="#cb92-87" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb92-88"><a href="#cb92-88" aria-hidden="true" tabindex="-1"></a><span class="co"># fit full model</span></span>
<span id="cb92-89"><a href="#cb92-89" aria-hidden="true" tabindex="-1"></a>fit_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2)</span>
<span id="cb92-90"><a href="#cb92-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-91"><a href="#cb92-91" aria-hidden="true" tabindex="-1"></a><span class="co"># perform backward stepwise selection</span></span>
<span id="cb92-92"><a href="#cb92-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-93"><a href="#cb92-93" aria-hidden="true" tabindex="-1"></a>fit_backward <span class="ot">&lt;-</span> <span class="fu">step</span>(fit_full, <span class="at">direction =</span> <span class="st">"backward"</span>)</span>
<span id="cb92-94"><a href="#cb92-94" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_backward)</span>
<span id="cb92-95"><a href="#cb92-95" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-96"><a href="#cb92-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-97"><a href="#cb92-97" aria-hidden="true" tabindex="-1"></a>**Backward Elimination Analysis:**</span>
<span id="cb92-98"><a href="#cb92-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-99"><a href="#cb92-99" aria-hidden="true" tabindex="-1"></a>The backward stepwise selection approach was used to determine the best predictors of house prices. Backward elimination starts with a full model, and successively drops variables that do not contribute to the model meaningfully. Therefore, since the variable Be has the largest *p-value* of 0.4867 it would be eliminated first.</span>
<span id="cb92-100"><a href="#cb92-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-101"><a href="#cb92-101" aria-hidden="true" tabindex="-1"></a>The final model included three predictor variables, namely S, Ba, and New, with a significant positive effect on the response variable P. The adjusted R-squared value of 0.8637 indicates that these variables explain approximately 86.37% of the variability in P. The significant F-statistic and low p-value further support the idea that the model is a good fit for the data. Overall, the results suggest that the selected variables can be used as reliable predictors of house prices.</span>
<span id="cb92-102"><a href="#cb92-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-103"><a href="#cb92-103" aria-hidden="true" tabindex="-1"></a><span class="fu">## B</span></span>
<span id="cb92-104"><a href="#cb92-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-105"><a href="#cb92-105" aria-hidden="true" tabindex="-1"></a>For forward selection, which variable would be added first? Why?</span>
<span id="cb92-106"><a href="#cb92-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-107"><a href="#cb92-107" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb92-108"><a href="#cb92-108" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform forward selection</span></span>
<span id="cb92-109"><a href="#cb92-109" aria-hidden="true" tabindex="-1"></a>forward_model <span class="ot">&lt;-</span> <span class="fu">step</span>(fit_full, <span class="at">direction =</span> <span class="st">"forward"</span>)</span>
<span id="cb92-110"><a href="#cb92-110" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(forward_model)</span>
<span id="cb92-111"><a href="#cb92-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-112"><a href="#cb92-112" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-113"><a href="#cb92-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-114"><a href="#cb92-114" aria-hidden="true" tabindex="-1"></a>**Forward Selection Analysis:**</span>
<span id="cb92-115"><a href="#cb92-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-116"><a href="#cb92-116" aria-hidden="true" tabindex="-1"></a>In forward selection, the variable with the lowest p-value is added first, as a smaller p-value indicates a stronger evidence against the null hypothesis that the predictor has no effect on the response variable.</span>
<span id="cb92-117"><a href="#cb92-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-118"><a href="#cb92-118" aria-hidden="true" tabindex="-1"></a>In the full model, we can see that the variable with the lowest p-value is S (p-value <span class="sc">\&lt;</span> 2e-16), indicating that it is highly significant in predicting the house price. Therefore, if we were to use forward selection based on p-values, S would be added first to the model, followed by Ba, New, and finally Be, in that order, as none of the other variables have p-values lower than S.</span>
<span id="cb92-119"><a href="#cb92-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-120"><a href="#cb92-120" aria-hidden="true" tabindex="-1"></a><span class="fu">## C</span></span>
<span id="cb92-121"><a href="#cb92-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-122"><a href="#cb92-122" aria-hidden="true" tabindex="-1"></a>Why do you think that BEDS has such a large P-value in the multiple regression model, even though it has a substantial correlation with PRICE?</span>
<span id="cb92-123"><a href="#cb92-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-124"><a href="#cb92-124" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb92-125"><a href="#cb92-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-126"><a href="#cb92-126" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit multiple regression model</span></span>
<span id="cb92-127"><a href="#cb92-127" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2)</span>
<span id="cb92-128"><a href="#cb92-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-129"><a href="#cb92-129" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate VIF for each predictor variable</span></span>
<span id="cb92-130"><a href="#cb92-130" aria-hidden="true" tabindex="-1"></a>vif <span class="ot">&lt;-</span> <span class="fu">vif</span>(fit)</span>
<span id="cb92-131"><a href="#cb92-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-132"><a href="#cb92-132" aria-hidden="true" tabindex="-1"></a><span class="co"># Print VIF values</span></span>
<span id="cb92-133"><a href="#cb92-133" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vif)</span>
<span id="cb92-134"><a href="#cb92-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-135"><a href="#cb92-135" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of PRICE against BEDS</span></span>
<span id="cb92-136"><a href="#cb92-136" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(house_price_2<span class="sc">$</span>Be, house_price_2<span class="sc">$</span>P, <span class="at">xlab =</span> <span class="st">"BEDS"</span>, <span class="at">ylab =</span> <span class="st">"Price"</span>)</span>
<span id="cb92-137"><a href="#cb92-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-138"><a href="#cb92-138" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a linear regression line to the plot</span></span>
<span id="cb92-139"><a href="#cb92-139" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(P <span class="sc">~</span> Be, <span class="at">data =</span> house_price_2), <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb92-140"><a href="#cb92-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-141"><a href="#cb92-141" aria-hidden="true" tabindex="-1"></a><span class="co"># size of Dataset, house_price_2</span></span>
<span id="cb92-142"><a href="#cb92-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-143"><a href="#cb92-143" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(house_price_2)</span>
<span id="cb92-144"><a href="#cb92-144" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(n)</span>
<span id="cb92-145"><a href="#cb92-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-146"><a href="#cb92-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-147"><a href="#cb92-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-148"><a href="#cb92-148" aria-hidden="true" tabindex="-1"></a>**Analysis:**</span>
<span id="cb92-149"><a href="#cb92-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-150"><a href="#cb92-150" aria-hidden="true" tabindex="-1"></a>Regression model can be impacted by various factors such as multicollinearity, other predictors, unaccounted confounding factors, and small sample size.</span>
<span id="cb92-151"><a href="#cb92-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-152"><a href="#cb92-152" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>While the VIF values above indicate no significant multicollinearity among predictor variables, the presence of outliers and non-linearity can still affect the model's accuracy and interpretability.</span>
<span id="cb92-153"><a href="#cb92-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-154"><a href="#cb92-154" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Despite a strong correlation between BEDS and PRICE, the large p-value of BEDS in the multiple regression model suggests that its relationship with PRICE is not significant after controlling for other predictor variables. Other predictors included in the model might explain some of the variability that BEDS previously accounted for, or there could be other unaccounted confounding factors that affect the relationship. Therefore, a thorough examination of other predictors and potential confounding factors is necessary for an accurate interpretation of the regression analysis results.</span>
<span id="cb92-155"><a href="#cb92-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-156"><a href="#cb92-156" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Moreover, sample size can affect the precision of estimates, and a small sample size of 93 may be inadequate, which could contribute to the large p-value and substantial correlation observed.</span>
<span id="cb92-157"><a href="#cb92-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-158"><a href="#cb92-158" aria-hidden="true" tabindex="-1"></a><span class="fu">## D</span></span>
<span id="cb92-159"><a href="#cb92-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-160"><a href="#cb92-160" aria-hidden="true" tabindex="-1"></a>Using software with these four predictors, find the model that would be selected using each criterion:</span>
<span id="cb92-161"><a href="#cb92-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-162"><a href="#cb92-162" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>R2</span>
<span id="cb92-163"><a href="#cb92-163" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Adjusted R2</span>
<span id="cb92-164"><a href="#cb92-164" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>PRESS</span>
<span id="cb92-165"><a href="#cb92-165" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>AIC</span>
<span id="cb92-166"><a href="#cb92-166" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>BIC</span>
<span id="cb92-167"><a href="#cb92-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-168"><a href="#cb92-168" aria-hidden="true" tabindex="-1"></a>Prepared different linear regression models fitted to the "house_price_2" dataset with different combination of independent variables.</span>
<span id="cb92-169"><a href="#cb92-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-172"><a href="#cb92-172" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-173"><a href="#cb92-173" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-174"><a href="#cb92-174" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S<span class="sc">+</span>New, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-175"><a href="#cb92-175" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2))</span>
<span id="cb92-176"><a href="#cb92-176" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-177"><a href="#cb92-177" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be <span class="sc">-</span>Ba, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-178"><a href="#cb92-178" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-179"><a href="#cb92-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-180"><a href="#cb92-180" aria-hidden="true" tabindex="-1"></a><span class="fu">### a. R\^2</span></span>
<span id="cb92-181"><a href="#cb92-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-182"><a href="#cb92-182" aria-hidden="true" tabindex="-1"></a>The model with the most explanatory variables has the highest R-squared value of 0.8689, it indicates that this model accounts for 86.89% of the variability in the response variable. Based on this criterion, selecting a model that maximizes the R-squared value would lead to the selection of the model with all predictor variables included, resulting in the equation: ŷ = -41.79 + 64.76(Size) - 2.77(Beds) + 19.2(Baths) + 18.98(New).</span>
<span id="cb92-183"><a href="#cb92-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-184"><a href="#cb92-184" aria-hidden="true" tabindex="-1"></a><span class="fu">### b. Adjusted R\^2</span></span>
<span id="cb92-185"><a href="#cb92-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-186"><a href="#cb92-186" aria-hidden="true" tabindex="-1"></a>The adjusted R-squared value of the model with Size, Baths, and New as explanatory variables and excluding Beds is 0.8637, indicating that this model explains around 86.37% of the variation in the response variable. It also considers the possibility that some of the variables may not be significant or may be redundant.</span>
<span id="cb92-187"><a href="#cb92-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-188"><a href="#cb92-188" aria-hidden="true" tabindex="-1"></a>Based on the adjusted R-squared criterion, the model with Size, Baths, and New is the most appropriate for predicting selling price, as it has the highest adjusted R-squared value among the tested models. The model is represented by ŷ = -47.99 + 62.26(Size) + 20.07(Baths) + 18.37(New).</span>
<span id="cb92-189"><a href="#cb92-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-190"><a href="#cb92-190" aria-hidden="true" tabindex="-1"></a><span class="fu">### c. PRESS</span></span>
<span id="cb92-191"><a href="#cb92-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-192"><a href="#cb92-192" aria-hidden="true" tabindex="-1"></a>I prepared different linear regression models, fitted on the "house_price_2" dataset with varying combinations of independent variables, and PRESS is used to evaluate the predictive performance of the models.</span>
<span id="cb92-193"><a href="#cb92-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-196"><a href="#cb92-196" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-197"><a href="#cb92-197" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-198"><a href="#cb92-198" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S<span class="sc">+</span>New, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-199"><a href="#cb92-199" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(<span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2))</span>
<span id="cb92-200"><a href="#cb92-200" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-201"><a href="#cb92-201" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be <span class="sc">-</span>Ba, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-202"><a href="#cb92-202" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-203"><a href="#cb92-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-204"><a href="#cb92-204" aria-hidden="true" tabindex="-1"></a>Based on the Predictive Residual Sum of Squares (PRESS) criterion, a smaller value indicates a better predictive model. Five regression models were evaluated, and the results indicate that the model with Size, Baths, and New as predictors (excluding Bed) has the lowest PRESS value of 27,860.05. This finding suggests that this model is the most effective in predicting the selling price of houses in this dataset.</span>
<span id="cb92-205"><a href="#cb92-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-206"><a href="#cb92-206" aria-hidden="true" tabindex="-1"></a>Thus, based on the PRESS criterion, it is reasonable to select the model with Size, Baths, and New as variables for predicting selling price.</span>
<span id="cb92-207"><a href="#cb92-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-208"><a href="#cb92-208" aria-hidden="true" tabindex="-1"></a><span class="fu">### d. AIC</span></span>
<span id="cb92-209"><a href="#cb92-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-210"><a href="#cb92-210" aria-hidden="true" tabindex="-1"></a>I prepared different linear regression models, fitted on the "house_price_2" dataset with varying combinations of independent variables, and AIC is used to evaluate the predictive performance of the models.</span>
<span id="cb92-211"><a href="#cb92-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-214"><a href="#cb92-214" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-215"><a href="#cb92-215" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-216"><a href="#cb92-216" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S<span class="sc">+</span>New, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-217"><a href="#cb92-217" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2))</span>
<span id="cb92-218"><a href="#cb92-218" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-219"><a href="#cb92-219" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be <span class="sc">-</span>Ba, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-220"><a href="#cb92-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-221"><a href="#cb92-221" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-222"><a href="#cb92-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-223"><a href="#cb92-223" aria-hidden="true" tabindex="-1"></a>When considering the Akaike Information Criterion (AIC), a lower AIC value indicates a better model fit. In this case, the AIC values have been calculated for five different regression models. The results show that the model with Size, Baths, and New as predictors (excluding Bed and Basement) has the lowest AIC value of 789.1366. This suggests that this model provides the best balance between model complexity and goodness of fit, compared to the other models.</span>
<span id="cb92-224"><a href="#cb92-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-225"><a href="#cb92-225" aria-hidden="true" tabindex="-1"></a>Therefore, based on the AIC criterion, it seems reasonable to select the model with Size, Baths, and New; as variables for predicting selling price.</span>
<span id="cb92-226"><a href="#cb92-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-227"><a href="#cb92-227" aria-hidden="true" tabindex="-1"></a><span class="fu">### e. BIC</span></span>
<span id="cb92-228"><a href="#cb92-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-229"><a href="#cb92-229" aria-hidden="true" tabindex="-1"></a>I prepared different linear regression models, fitted on the "house_price_2" dataset with varying combinations of independent variables, and BIC is used to evaluate the predictive performance of the models.</span>
<span id="cb92-230"><a href="#cb92-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-233"><a href="#cb92-233" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-234"><a href="#cb92-234" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-235"><a href="#cb92-235" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> S<span class="sc">+</span>New, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-236"><a href="#cb92-236" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> ., <span class="at">data =</span> house_price_2))</span>
<span id="cb92-237"><a href="#cb92-237" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-238"><a href="#cb92-238" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be <span class="sc">-</span>Ba, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-239"><a href="#cb92-239" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-240"><a href="#cb92-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-241"><a href="#cb92-241" aria-hidden="true" tabindex="-1"></a>The Bayesian Information Criterion (BIC) is a statistical criterion used for model selection in regression analysis that balances the goodness of fit of the model with its complexity. A lower BIC value indicates a better fit of the model to the data, while also taking into account the number of predictors included in the model.</span>
<span id="cb92-242"><a href="#cb92-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-243"><a href="#cb92-243" aria-hidden="true" tabindex="-1"></a>In this case, the model with the lowest BIC value is the one that includes all predictors except for Bed, with a BIC value of 801.7996. This suggests that this model is the best fit for the data while also being the least complex. Therefore, based on the BIC criterion, it would be reasonable to select the model with Size, Baths, and New as predictors for predicting selling price, while excluding Bed.</span>
<span id="cb92-244"><a href="#cb92-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-245"><a href="#cb92-245" aria-hidden="true" tabindex="-1"></a><span class="fu">## E</span></span>
<span id="cb92-246"><a href="#cb92-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-247"><a href="#cb92-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb92-248"><a href="#cb92-248" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(P <span class="sc">~</span> . <span class="sc">-</span>Be, <span class="at">data =</span> house_price_2))</span>
<span id="cb92-249"><a href="#cb92-249" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-250"><a href="#cb92-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-251"><a href="#cb92-251" aria-hidden="true" tabindex="-1"></a>Based on the various criteria analyzed, including R-Squared, Adjusted R-Squared, PRESS, AIC, and BIC, the model with the highest overall performance and thus the best fit for predicting selling price is the one that excludes Beds and includes Size, Baths, and New as variables. This model has a lower PRESS value, a lower AIC value, and a lower BIC value than the model that includes all variables. Additionally, it has a slightly higher adjusted R-squared value than the full model. Therefore, the preferred model for predicting selling price is: ŷ = -47.99 + 62.26(Size) + 20.07(Baths) + 18.37(New). It is important to note that while R-Squared is not the sole determinant of model strength, it can still provide some insight into the model's performance.</span>
<span id="cb92-252"><a href="#cb92-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-253"><a href="#cb92-253" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 2</span></span>
<span id="cb92-254"><a href="#cb92-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-255"><a href="#cb92-255" aria-hidden="true" tabindex="-1"></a>(Data file: trees from base R) From the documentation: "This data set provides measurements of the diameter, height and volume of timber in 31 felled black cherry trees. Note that the diameter (in inches) is erroneously labeled Girth in the data. It is measured at 4 ft 6 in above the ground." Tree volume estimation is a big deal, especially in the lumber industry. Use the trees data to build a basic model of tree volume prediction. In particular,</span>
<span id="cb92-256"><a href="#cb92-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-259"><a href="#cb92-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-260"><a href="#cb92-260" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"trees"</span>)</span>
<span id="cb92-261"><a href="#cb92-261" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(trees)</span>
<span id="cb92-262"><a href="#cb92-262" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(trees)</span>
<span id="cb92-263"><a href="#cb92-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-264"><a href="#cb92-264" aria-hidden="true" tabindex="-1"></a><span class="co">#renaming erroneously labelled variable Girth to Diameter</span></span>
<span id="cb92-265"><a href="#cb92-265" aria-hidden="true" tabindex="-1"></a>trees_d<span class="ot">&lt;-</span>trees <span class="sc">%&gt;%</span>          </span>
<span id="cb92-266"><a href="#cb92-266" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Diameter=</span>Girth)</span>
<span id="cb92-267"><a href="#cb92-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-268"><a href="#cb92-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-269"><a href="#cb92-269" aria-hidden="true" tabindex="-1"></a>Prepared Data and Summary of trees dataset; renamed the variable Girth to Diameter since in the instructions it says,that Girth is labelled erroneously.</span>
<span id="cb92-270"><a href="#cb92-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-271"><a href="#cb92-271" aria-hidden="true" tabindex="-1"></a><span class="fu">## A</span></span>
<span id="cb92-272"><a href="#cb92-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-273"><a href="#cb92-273" aria-hidden="true" tabindex="-1"></a>Fit a multiple regression model with the Volume as the outcome and Girth and Height as the explanatory variables</span>
<span id="cb92-274"><a href="#cb92-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-277"><a href="#cb92-277" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-278"><a href="#cb92-278" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Diameter <span class="sc">+</span> Height, <span class="at">data =</span> trees_d)</span>
<span id="cb92-279"><a href="#cb92-279" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb92-280"><a href="#cb92-280" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-281"><a href="#cb92-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-282"><a href="#cb92-282" aria-hidden="true" tabindex="-1"></a>The linear regression model predicts tree volume based on the diameter and height of the tree. Both predictors have small p-values, indicating statistical significance and supporting the idea that they are related to tree volume. The model has a high degree of linear correlation, with an R-squared value close to 1.00 at 0.948, indicating that it explains a large proportion of the variance in the data. The adjusted R-squared value is also high at 0.9442, indicating that the model is not overfitting to the data.</span>
<span id="cb92-283"><a href="#cb92-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-284"><a href="#cb92-284" aria-hidden="true" tabindex="-1"></a><span class="fu">## B</span></span>
<span id="cb92-285"><a href="#cb92-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-286"><a href="#cb92-286" aria-hidden="true" tabindex="-1"></a>Run regression diagnostic plots on the model. Based on the plots, do you think any of the regression assumptions is violated?</span>
<span id="cb92-287"><a href="#cb92-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-290"><a href="#cb92-290" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-291"><a href="#cb92-291" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)); </span>
<span id="cb92-292"><a href="#cb92-292" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">pch=</span><span class="dv">15</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb92-293"><a href="#cb92-293" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-294"><a href="#cb92-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-295"><a href="#cb92-295" aria-hidden="true" tabindex="-1"></a>**Residuals vs. Fitted**</span>
<span id="cb92-296"><a href="#cb92-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-297"><a href="#cb92-297" aria-hidden="true" tabindex="-1"></a>The residuals vs. fitted values plot is a useful tool for detecting non-linear patterns in the residuals. When the red line is approximately flat and horizontal at zero, it suggests that the residuals follow a linear pattern. In the case of the trees dataset, the red line is not perfectly horizontal, but it deviates only slightly. This indicates that the residuals exhibit a roughly non-linear pattern and that a non-linear model may be more appropriate for this data. Thus, the assumption of linearity in the regression model is violated.</span>
<span id="cb92-298"><a href="#cb92-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-299"><a href="#cb92-299" aria-hidden="true" tabindex="-1"></a>**Normal Q-Q**</span>
<span id="cb92-300"><a href="#cb92-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-301"><a href="#cb92-301" aria-hidden="true" tabindex="-1"></a>This plot is used to check if the residuals of a regression model are normally distributed. If the points in the plot follow a straight diagonal line, it can be assumed that the residuals have a normal distribution. In this dataset, the points generally follow a straight diagonal line, indicating that the residuals are normally distributed. However, there are a few observations near the top of the plot that deviate from the line, suggesting some potential non-normality. Overall, it's difficult to confidently determine if the assumption of normality is violated based on this plot alone.</span>
<span id="cb92-302"><a href="#cb92-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-303"><a href="#cb92-303" aria-hidden="true" tabindex="-1"></a>**Scale-Location**</span>
<span id="cb92-304"><a href="#cb92-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-305"><a href="#cb92-305" aria-hidden="true" tabindex="-1"></a>The plot being referred to is the Scale-Location plot. It checks the assumption of equal variance, or homoscedasticity, among the residuals in the regression model. A horizontal red line across the plot indicates that the assumption of equal variance is likely met. However, in this case, the red line is not horizontal, which may suggest that equal variance is violated. This violation is also suggested by the non-horizontal trend-line in the Scale-Location plot. Therefore, the assumption of constant variance may be violated for this dataset.</span>
<span id="cb92-306"><a href="#cb92-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-307"><a href="#cb92-307" aria-hidden="true" tabindex="-1"></a>**Cook's Distance**</span>
<span id="cb92-308"><a href="#cb92-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-309"><a href="#cb92-309" aria-hidden="true" tabindex="-1"></a>Determine Influential Variables:</span>
<span id="cb92-310"><a href="#cb92-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-311"><a href="#cb92-311" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE}</span></span>
<span id="cb92-312"><a href="#cb92-312" aria-hidden="true" tabindex="-1"></a>cooks_D <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(model)</span>
<span id="cb92-313"><a href="#cb92-313" aria-hidden="true" tabindex="-1"></a>influential <span class="ot">&lt;-</span> cooks_D[(cooks_D <span class="sc">&gt;</span> (<span class="dv">3</span> <span class="sc">*</span> <span class="fu">mean</span>(cooks_D, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))]</span>
<span id="cb92-314"><a href="#cb92-314" aria-hidden="true" tabindex="-1"></a>influential</span>
<span id="cb92-315"><a href="#cb92-315" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-316"><a href="#cb92-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-317"><a href="#cb92-317" aria-hidden="true" tabindex="-1"></a>The Cook's Distance plot is used to identify influential observations in a regression model by combining leverage and residual information. It provides a summary of how much the model changes if a certain data point is removed. For this dataset, the plot indicates that observations 31, 18, and 3 have the highest Cook's Distances, which are also confirmed by the Cook's Distance function. These observations are considered highly influential.</span>
<span id="cb92-318"><a href="#cb92-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-319"><a href="#cb92-319" aria-hidden="true" tabindex="-1"></a>**Residuals vs. Leverage**</span>
<span id="cb92-320"><a href="#cb92-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-321"><a href="#cb92-321" aria-hidden="true" tabindex="-1"></a>This plot is designed to identify influential observations with high leverage, where points outside the Cook's distance lines are deemed influential. Here, the presence of highly leveraged observations suggests the existence of influential points in the data.</span>
<span id="cb92-322"><a href="#cb92-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-323"><a href="#cb92-323" aria-hidden="true" tabindex="-1"></a>**Cooks Distance vs Leverage**</span>
<span id="cb92-324"><a href="#cb92-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-325"><a href="#cb92-325" aria-hidden="true" tabindex="-1"></a>Similar to the Cook's Distance plot, this plot also helps identify highly influential data points. In this case, we can see that data points 3, 18, and 31 are highly influential, which is consistent with the Cook's Distance plot.</span>
<span id="cb92-326"><a href="#cb92-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-327"><a href="#cb92-327" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 3</span></span>
<span id="cb92-328"><a href="#cb92-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-329"><a href="#cb92-329" aria-hidden="true" tabindex="-1"></a>(Data file: florida in alr R package) In the 2000 election for U.S. president, the counting of votes in Florida was controversial. In Palm Beach County in south Florida, for example, voters used a so-called butterfly ballot. Some believe that the layout of the ballot caused some voters to cast votes for Buchanan when their intended choice was Gore.</span>
<span id="cb92-330"><a href="#cb92-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-331"><a href="#cb92-331" aria-hidden="true" tabindex="-1"></a>The data has variables for the number of votes for each candidate---Gore, Bush, and Buchanan.</span>
<span id="cb92-332"><a href="#cb92-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-335"><a href="#cb92-335" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-336"><a href="#cb92-336" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"florida"</span>)</span>
<span id="cb92-337"><a href="#cb92-337" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(florida)</span>
<span id="cb92-338"><a href="#cb92-338" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(florida)</span>
<span id="cb92-339"><a href="#cb92-339" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-340"><a href="#cb92-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-341"><a href="#cb92-341" aria-hidden="true" tabindex="-1"></a><span class="fu">## A</span></span>
<span id="cb92-342"><a href="#cb92-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-343"><a href="#cb92-343" aria-hidden="true" tabindex="-1"></a>Run a simple linear regression model where the Buchanan vote is the outcome and the Bush vote is the explanatory variable. Produce the regression diagnostic plots. Is Palm Beach County an outlier based on the diagnostic plots? Why or why not?</span>
<span id="cb92-344"><a href="#cb92-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-347"><a href="#cb92-347" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-348"><a href="#cb92-348" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Buchanan <span class="sc">~</span> Bush, <span class="at">data =</span> florida)</span>
<span id="cb92-349"><a href="#cb92-349" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb92-350"><a href="#cb92-350" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-351"><a href="#cb92-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-352"><a href="#cb92-352" aria-hidden="true" tabindex="-1"></a>**Analysis:**</span>
<span id="cb92-353"><a href="#cb92-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-354"><a href="#cb92-354" aria-hidden="true" tabindex="-1"></a>The linear regression model aims to predict Buchanan's votes based on the number of votes for Bush in Florida. The model found a significant relationship between the two variables, with Bush's coefficient estimate at 0.0049 and a very small p-value of 1.73e-08, which means that the probability of getting such a result by chance is almost zero. The intercept estimate, however, is not significant with a p-value of 0.409. The R-squared value of 0.3889 suggests that the model explains 38.89% of the variance in Buchanan's votes. The adjusted R-squared value of 0.3795 is slightly lower, indicating that adding the Bush variable did not significantly improve the model's fit. The residual standard error of 353.9 suggests that the model's predictions may deviate from the actual values by an average of 353.9 votes.</span>
<span id="cb92-355"><a href="#cb92-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-358"><a href="#cb92-358" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-359"><a href="#cb92-359" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb92-360"><a href="#cb92-360" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">pch =</span><span class="dv">15</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb92-361"><a href="#cb92-361" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-362"><a href="#cb92-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-363"><a href="#cb92-363" aria-hidden="true" tabindex="-1"></a>**Analysis:**</span>
<span id="cb92-364"><a href="#cb92-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-365"><a href="#cb92-365" aria-hidden="true" tabindex="-1"></a>Based on the diagnostic plots, Palm Beach County is an outlier. First, when looking at the residuals vs fitted plot, the Palm Beach County residual is very large. When referring to the summary of the simple regression model, the third quartile for residuals is 12.26, yet the max is 2610.19. This is a significant jump and indicative of the value being an outlier. The normal Q-Q plot also indicates that the residuals for the model are generally normal except for the Palm Beach County residual, as it greatly deviates from the line in the plot. The Cook's distance plot shows two points that may be of concern as outliers if you follow the metric of observations scoring over 1, which are DADE and Palm Beach at about 2. The residuals and leverages plot shows the Palm Beach County standardized residual value beyond the dashed line indicating Cook's distance. This also suggests that the observation is an outlier and the observation has the potential to influence the regression model.</span>
<span id="cb92-366"><a href="#cb92-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-367"><a href="#cb92-367" aria-hidden="true" tabindex="-1"></a><span class="fu">## B</span></span>
<span id="cb92-368"><a href="#cb92-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-371"><a href="#cb92-371" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-372"><a href="#cb92-372" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> <span class="fu">log</span>(Buchanan) <span class="sc">~</span> <span class="fu">log</span>(Bush), <span class="at">data =</span> florida)</span>
<span id="cb92-373"><a href="#cb92-373" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb92-374"><a href="#cb92-374" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-375"><a href="#cb92-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-376"><a href="#cb92-376" aria-hidden="true" tabindex="-1"></a>**Analysis:**</span>
<span id="cb92-377"><a href="#cb92-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-378"><a href="#cb92-378" aria-hidden="true" tabindex="-1"></a>This is a linear regression model where the dependent variable is the natural logarithm of Buchanan's votes and the independent variable is the natural logarithm of Bush's votes in Florida. The model shows a significant positive relationship between the two variables, with a coefficient estimate of 0.75772 for log(Bush) and a very small p-value of <span class="sc">\&lt;</span>2e-16, indicating that the relationship is not due to chance. The intercept estimate of -2.57712 is also significant with a small p-value of 8.04e-09. The model's R-squared value of 0.8508 indicates that 85.08% of the variance in Buchanan's votes is explained by the model, and the adjusted R-squared value of 0.8485 suggests that adding the Bush variable did not significantly improve the model's fit. The residual standard error of 0.4673 suggests that the model's predictions may deviate from the actual values by an average of 0.4673 votes.</span>
<span id="cb92-379"><a href="#cb92-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-382"><a href="#cb92-382" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb92-383"><a href="#cb92-383" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb92-384"><a href="#cb92-384" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">pch =</span><span class="dv">15</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb92-385"><a href="#cb92-385" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb92-386"><a href="#cb92-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-387"><a href="#cb92-387" aria-hidden="true" tabindex="-1"></a>**Analysis:**</span>
<span id="cb92-388"><a href="#cb92-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-389"><a href="#cb92-389" aria-hidden="true" tabindex="-1"></a>After examining the diagnostic plots, it appears that Palm Beach County is still an outlier. The residuals vs fitted plot shows that the Palm Beach County residual remains unusually large. The normal Q-Q plot also indicates that the residuals for the model are generally normal except for the Palm Beach County residual, which significantly deviates from the line in the plot. According to the Cook's distance plot, Palm Beach County is an outlier with a score of about 0.3, which exceeds the threshold of 0.2. In addition, the residuals and leverages plot shows that the standardized residual value for Palm Beach County is beyond the dashed line indicating Cook's distance, further suggesting that this observation is an outlier and has the potential to influence the regression model.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>