<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jerin Jacob">
<meta name="dcterms.date" content="2023-03-10">
<meta name="description" content="Final project qmd file for 603">

<title>Final Project 603</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Final Project 603">
<meta name="twitter:description" content="Final project qmd file for 603">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/Jerin_Jacob_Final_Project_files/figure-html/unnamed-chunk-13-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#reading-the-data" id="toc-reading-the-data" class="nav-link active" data-scroll-target="#reading-the-data">Reading the data</a>
  <ul class="collapse">
  <li><a href="#column-description" id="toc-column-description" class="nav-link" data-scroll-target="#column-description"><strong>COLUMN DESCRIPTION</strong></a></li>
  </ul></li>
  <li><a href="#cleaning-the-data" id="toc-cleaning-the-data" class="nav-link" data-scroll-target="#cleaning-the-data">Cleaning the Data</a></li>
  <li><a href="#summary-of-each-variables" id="toc-summary-of-each-variables" class="nav-link" data-scroll-target="#summary-of-each-variables">Summary of each variables</a>
  <ul class="collapse">
  <li><a href="#check-correlation-between-box-office-and-opening" id="toc-check-correlation-between-box-office-and-opening" class="nav-link" data-scroll-target="#check-correlation-between-box-office-and-opening">Check correlation between Box Office and Opening</a></li>
  </ul></li>
  <li><a href="#running-different-models-to-get-the-best-fit" id="toc-running-different-models-to-get-the-best-fit" class="nav-link" data-scroll-target="#running-different-models-to-get-the-best-fit">Running different models to get the best fit</a></li>
  <li><a href="#selecting-a-model-and-interpretation-of-the-result" id="toc-selecting-a-model-and-interpretation-of-the-result" class="nav-link" data-scroll-target="#selecting-a-model-and-interpretation-of-the-result">Selecting a model and Interpretation of the result</a></li>
  <li><a href="#visualising-the-regression-model." id="toc-visualising-the-regression-model." class="nav-link" data-scroll-target="#visualising-the-regression-model.">Visualising the regression model.</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion:</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References:</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Project 603</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">finalproject</div>
  </div>
  </div>

<div>
  <div class="description">
    Final project qmd file for 603
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jerin Jacob </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 10, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>Now a days, movies are a well marketed entertainment product. Just like any other products in the market, movies are also having an allocated a marketing budget and promotional activities are done in scale. This often result in the opening weekend’s gross ticketing volume to rise. But are the pre-release promotional activities helping the movie to collect more or is it just creating a hype initially? Or does the movie’s gross collection is not at all dependant on pre release promotions? This dataset has 200 highest grossing movies of 2022. It has both the opening week’s gross as well as the total gross collection of the movies, along with other variables. Assuming that opening week’s collection is depending on the pre-release promotion, by looking on the relationship between opening week’s gross and total gross, I am trying to see how the pre-release activities help the producers earn more in boxoffice.</p>
<p><strong>Research Question</strong>: To what extent does the success of a movie depend on its opening week’s collection?</p>
<p><strong>Hypothesis</strong>: Opening week’s collection is positively correlated with the Box Office total collection.</p>
<p>Loading all the packages required for the project.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="reading-the-data" class="level2">
<h2 class="anchored" data-anchor-id="reading-the-data">Reading the data</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"_data/project_data.xlsx"</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Rank                                     Release      Budget     Box Office
1    1                           Top Gun: Maverick 177 million $1.493 billion
2    2                    Avatar: The Way of Water 460 million $2.319 billion
3    3              Black Panther: Wakanda Forever 250 million $859.1 million
4    4 Doctor Strange in the Multiverse of Madness 200 million $955.8 million
5    5                    Jurassic World: Dominion 185 million $1.004 billion
6    6                    Minions: The Rise of Gru 100 million $940.5 million
      Gross max_th   Opening perc_tot_gr open_th  Open Close
1 718732821   4751 126707459        17.6    4735 44708 44911
2 636955746   4340 134100226        21.1    4202 44911    NA
3 453474324   4396 181339761        40.0    4396 44876    NA
4 411331607   4534 187420998        45.6    4534 44687    NA
5 376851080   4697 145075625        38.5    4676 44722 44827
6 369695210   4427 107010140        28.9    4391 44743    NA
                          Distributor  int_gross world_gross
1                  Paramount Pictures  770000000  1488732821
2                20th Century Studios 1539273359  2176229105
3 Walt Disney Studios Motion Pictures  389276658   842750982
4 Walt Disney Studios Motion Pictures  544444197   955775804
5                  Universal Pictures  625127000  1001978080
6                  Universal Pictures  569933000   939628210</code></pre>
</div>
</div>
<p>There are 14 variables with 200 rows.</p>
<section id="column-description" class="level3">
<h3 class="anchored" data-anchor-id="column-description"><strong>COLUMN DESCRIPTION</strong></h3>
<p>‘Rank’: rank of the movie ‘Release’: release date of the movie ‘Budget’: The budget of the movie production ‘Box Office’: The total Box Office collection ‘Gross’: domestic gross of the movie ‘max_th’: maximum number of theaters the movie was released in ‘Opening’: gross on opening weekend ‘perc_tot_gr’: domestic percentage of the total gross ‘open_th’: number of theaters the movie opened in ‘Open’: opening date ‘Close’: closing date ‘Distributor’: name of the distributor ‘int_gross’: international gross ‘world_gross’: worldwide gross</p>
<ul>
<li><p>‘Release’: release date of the movie</p></li>
<li><p>‘Distributor’: name of the distributor</p></li>
<li><p>‘Small_Dist’: Whether a small distributor or not</p></li>
<li></li>
<li><p>‘Open_date’: Date of release</p></li>
<li><p>‘season’: The season in which the movie was released</p></li>
<li><p>‘Opening’: gross on opening weekend</p></li>
<li><p>‘open_th’: number of theaters the movie opened in</p></li>
<li><p>‘max_th’: maximum number of theaters the movie was released in</p></li>
</ul>
</section>
</section>
<section id="cleaning-the-data" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-the-data">Cleaning the Data</h2>
<p>For our purpose of analysis, we need to clean and transform the data a bit.</p>
<p>First, the Budget and Boxoffice columns are cleaned using stringr function so that the column values are numeric. We are getting rid of the character part in those values including ‘$’ and the value unit. Also, there are certain values which are in Indian Rupees and South Korean won. So we need to convert thoses values to US dollars. The data for columns Budget and Box office were taken from Wikipedia.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Budget =</span> <span class="fu">gsub</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">$"</span>, <span class="st">""</span>, Budget)) <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Budget =</span> <span class="fu">sub</span>(<span class="st">".*-"</span>, <span class="st">""</span>, Budget)) <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">gsub</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">$"</span>, <span class="st">""</span>, <span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)) </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>df[<span class="fu">c</span>(<span class="st">'Budget'</span>, <span class="st">'Unit'</span>)] <span class="ot">&lt;-</span> <span class="fu">str_split_fixed</span>(df<span class="sc">$</span>Budget, <span class="st">' '</span>, <span class="dv">2</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Budget <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df<span class="sc">$</span>Budget)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Budget <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>Unit <span class="sc">==</span> <span class="st">"million"</span>, df<span class="sc">$</span>Budget <span class="sc">*</span> <span class="dv">1000000</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">ifelse</span>(df<span class="sc">$</span>Unit <span class="sc">==</span> <span class="st">"billion"</span>, df<span class="sc">$</span>Budget <span class="sc">*</span> <span class="dv">1000000000</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">ifelse</span>(df<span class="sc">$</span>Unit <span class="sc">==</span> <span class="st">"Kmillion"</span>, df<span class="sc">$</span>Budget <span class="sc">*</span> <span class="dv">1000000</span><span class="sc">*</span><span class="fl">0.00074</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">ifelse</span>(df<span class="sc">$</span>Unit <span class="sc">==</span> <span class="st">"Kbillion"</span>, df<span class="sc">$</span>Budget <span class="sc">*</span> <span class="dv">1000000000</span><span class="sc">*</span><span class="fl">0.00074</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                                         <span class="fu">ifelse</span>(df<span class="sc">$</span>Unit <span class="sc">==</span> <span class="st">"crore"</span>, df<span class="sc">$</span>Budget <span class="sc">*</span> <span class="dv">10000000</span><span class="sc">*</span><span class="dv">80</span>, df<span class="sc">$</span>Budget)))))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>df[<span class="fu">c</span>(<span class="st">'Box Office'</span>, <span class="st">'BXUnit'</span>)] <span class="ot">&lt;-</span> <span class="fu">str_split_fixed</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>, <span class="st">' '</span>, <span class="dv">2</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>BXUnit <span class="sc">==</span> <span class="st">"million"</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">*</span> <span class="dv">1000000</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">ifelse</span>(df<span class="sc">$</span>BXUnit <span class="sc">==</span> <span class="st">"billion"</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">*</span> <span class="dv">1000000000</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">ifelse</span>(df<span class="sc">$</span>BXUnit <span class="sc">==</span> <span class="st">"Kmillion"</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">*</span> <span class="dv">1000000</span><span class="sc">*</span><span class="fl">0.00074</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">ifelse</span>(df<span class="sc">$</span>BXUnit <span class="sc">==</span> <span class="st">"Kbillion"</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">*</span> <span class="dv">1000000000</span><span class="sc">*</span><span class="fl">0.00074</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                                         <span class="fu">ifelse</span>(df<span class="sc">$</span>BXUnit <span class="sc">==</span> <span class="st">"crore"</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">*</span> <span class="dv">10000000</span><span class="sc">*</span><span class="dv">80</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Since the original dataset from Kaggle had a column named world_gross, we can compare both variables and assume that the highest value in either of the column can be considerd as the final world_gross.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">&lt;</span> df<span class="sc">$</span>world_gross, df<span class="sc">$</span>world_gross, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We can count the number of movies in the list for each distributor and any distributor who don’t have more than 3 movies in their name can be considered as a smaller distributor and thus assuming that they won’t have cash rich promotional campaigns that would lead to an audience pull to the theatre in the initial week.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Distributor) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Count=</span><span class="fu">n_distinct</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)) </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Small_Dist <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>Count <span class="sc">&lt;=</span> <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We can convert the dbl to date format and set the reference date so that the dates are correct. After that, from the Open_date, we can categorize thsoe dates to the season so that it can be used as a confounder. Seasons might have some effect on the theatre footfall and thereby, box office collections.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Open_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(df<span class="sc">$</span>Open, <span class="at">origin =</span> <span class="st">"1899-12-30"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column with the season for each date</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">season =</span> <span class="fu">case_when</span>(</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">between</span>(<span class="fu">month</span>(Open_date), <span class="dv">3</span>, <span class="dv">5</span>) <span class="sc">~</span> <span class="st">"Spring"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">between</span>(<span class="fu">month</span>(Open_date), <span class="dv">6</span>, <span class="dv">8</span>) <span class="sc">~</span> <span class="st">"Summer"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">between</span>(<span class="fu">month</span>(Open_date), <span class="dv">9</span>, <span class="dv">11</span>) <span class="sc">~</span> <span class="st">"Fall"</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Winter"</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 20
# Groups:   Distributor [4]
   Rank Release    Budget `Box Office`  Gross max_th Opening perc_tot_gr open_th
  &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;        &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;
1     1 Top Gun: … 1.77e8   1493000000 7.19e8   4751  1.27e8        17.6    4735
2     2 Avatar: T… 4.6 e8   2319000000 6.37e8   4340  1.34e8        21.1    4202
3     3 Black Pan… 2.5 e8    859100000 4.53e8   4396  1.81e8        40      4396
4     4 Doctor St… 2   e8    955800000 4.11e8   4534  1.87e8        45.6    4534
5     5 Jurassic … 1.85e8   1004000000 3.77e8   4697  1.45e8        38.5    4676
6     6 Minions: … 1   e8    940500000 3.70e8   4427  1.07e8        28.9    4391
# ℹ 11 more variables: Open &lt;dbl&gt;, Close &lt;dbl&gt;, Distributor &lt;chr&gt;,
#   int_gross &lt;dbl&gt;, world_gross &lt;dbl&gt;, Unit &lt;chr&gt;, BXUnit &lt;chr&gt;, Count &lt;int&gt;,
#   Small_Dist &lt;dbl&gt;, Open_date &lt;date&gt;, season &lt;chr&gt;</code></pre>
</div>
</div>
<p>Checking for NA values in each variable. There are 90 NA values in Budget variable, 38 in Box Office, 155 in Close date variable and 3 in int_gross. All othe variables seems to be good in terms of NA values.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       Rank     Release      Budget  Box Office       Gross      max_th 
          0           0          90          38           0           0 
    Opening perc_tot_gr     open_th        Open       Close Distributor 
          0           0           0           0         155           0 
  int_gross world_gross        Unit      BXUnit       Count  Small_Dist 
          3           0           0           0           0           0 
  Open_date      season 
          0           0 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>Small_Dist)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
140  60 </code></pre>
</div>
</div>
<p>Since 155 values of Close are NAs, it is better not to include that variable in the analysis. Most of the NA values are for the movies by small distributors, which need to be noted.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="sc">-</span>Close)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(df)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking for NA's</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       Rank     Release      Budget  Box Office       Gross      max_th 
          0           0           0           0           0           0 
    Opening perc_tot_gr     open_th        Open Distributor   int_gross 
          0           0           0           0           0           0 
world_gross        Unit      BXUnit       Count  Small_Dist   Open_date 
          0           0           0           0           0           0 
     season 
          0 </code></pre>
</div>
</div>
<p>Have an idea about the structure of the dataset.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>gropd_df [104 × 19] (S3: grouped_df/tbl_df/tbl/data.frame)
 $ Rank       : num [1:104] 1 2 3 4 5 6 7 8 9 10 ...
 $ Release    : chr [1:104] "Top Gun: Maverick" "Avatar: The Way of Water" "Black Panther: Wakanda Forever" "Doctor Strange in the Multiverse of Madness" ...
 $ Budget     : num [1:104] 1.77e+08 4.60e+08 2.50e+08 2.00e+08 1.85e+08 1.00e+08 2.00e+08 2.50e+08 1.10e+08 2.60e+08 ...
 $ Box Office : num [1:104] 1.49e+09 2.32e+09 8.59e+08 9.56e+08 1.00e+09 ...
 $ Gross      : num [1:104] 7.19e+08 6.37e+08 4.53e+08 4.11e+08 3.77e+08 ...
 $ max_th     : num [1:104] 4751 4340 4396 4534 4697 ...
 $ Opening    : num [1:104] 1.27e+08 1.34e+08 1.81e+08 1.87e+08 1.45e+08 ...
 $ perc_tot_gr: num [1:104] 17.6 21.1 40 45.6 38.5 28.9 36.3 42 37.8 39.8 ...
 $ open_th    : num [1:104] 4735 4202 4396 4534 4676 ...
 $ Open       : num [1:104] 44708 44911 44876 44687 44722 ...
 $ Distributor: chr [1:104] "Paramount Pictures" "20th Century Studios" "Walt Disney Studios Motion Pictures" "Walt Disney Studios Motion Pictures" ...
 $ int_gross  : num [1:104] 7.70e+08 1.54e+09 3.89e+08 5.44e+08 6.25e+08 ...
 $ world_gross: num [1:104] 1.49e+09 2.18e+09 8.43e+08 9.56e+08 1.00e+09 ...
 $ Unit       : chr [1:104] "million" "million" "million" "million" ...
 $ BXUnit     : chr [1:104] "billion" "billion" "million" "million" ...
 $ Count      : int [1:104] 12 4 9 9 19 19 6 9 12 6 ...
 $ Small_Dist : num [1:104] 0 0 0 0 0 0 0 0 0 0 ...
 $ Open_date  : Date[1:104], format: "2022-05-27" "2022-12-16" ...
 $ season     : chr [1:104] "Spring" "Winter" "Fall" "Spring" ...
 - attr(*, "groups")= tibble [32 × 2] (S3: tbl_df/tbl/data.frame)
  ..$ Distributor: chr [1:32] "-" "20th Century Studios" "A24" "Blue Fox Entertainment" ...
  ..$ .rows      : list&lt;int&gt; [1:32] 
  .. ..$ : int [1:3] 87 94 95
  .. ..$ : int [1:4] 2 35 38 42
  .. ..$ : int [1:5] 26 54 60 67 102
  .. ..$ : int 100
  .. ..$ : int 66
  .. ..$ : int 97
  .. ..$ : int 62
  .. ..$ : int 103
  .. ..$ : int [1:3] 25 32 49
  .. ..$ : int 76
  .. ..$ : int [1:6] 37 41 63 74 80 86
  .. ..$ : int 82
  .. ..$ : int 89
  .. ..$ : int [1:3] 85 98 104
  .. ..$ : int [1:3] 50 51 73
  .. ..$ : int [1:3] 77 81 83
  .. ..$ : int 58
  .. ..$ : int [1:10] 1 9 16 17 24 31 52 55 79 99
  .. ..$ : int 88
  .. ..$ : int 90
  .. ..$ : int 84
  .. ..$ : int [1:2] 39 64
  .. ..$ : int [1:6] 13 18 22 34 44 48
  .. ..$ : int 93
  .. ..$ : int [1:2] 28 45
  .. ..$ : int 91
  .. ..$ : int [1:5] 30 69 70 72 78
  .. ..$ : int [1:19] 5 6 11 14 19 23 27 29 33 43 ...
  .. ..$ : int [1:7] 3 4 8 15 40 56 71
  .. ..$ : int [1:6] 7 10 12 20 21 36
  .. ..$ : int [1:2] 96 101
  .. ..$ : int 92
  .. ..@ ptype: int(0) 
  ..- attr(*, ".drop")= logi TRUE
 - attr(*, "na.action")= 'omit' Named int [1:96] 40 42 47 54 61 63 66 69 75 77 ...
  ..- attr(*, "names")= chr [1:96] "40" "42" "47" "54" ...</code></pre>
</div>
</div>
<p>Using the glimpse() function, let’s have a look at how our data would look like!</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 104
Columns: 19
Groups: Distributor [32]
$ Rank         &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17…
$ Release      &lt;chr&gt; "Top Gun: Maverick", "Avatar: The Way of Water", "Black P…
$ Budget       &lt;dbl&gt; 1.77e+08, 4.60e+08, 2.50e+08, 2.00e+08, 1.85e+08, 1.00e+0…
$ `Box Office` &lt;dbl&gt; 1493000000, 2319000000, 859100000, 955800000, 1004000000,…
$ Gross        &lt;dbl&gt; 718732821, 636955746, 453474324, 411331607, 376851080, 36…
$ max_th       &lt;dbl&gt; 4751, 4340, 4396, 4534, 4697, 4427, 4417, 4375, 4258, 440…
$ Opening      &lt;dbl&gt; 126707459, 134100226, 181339761, 187420998, 145075625, 10…
$ perc_tot_gr  &lt;dbl&gt; 17.6, 21.1, 40.0, 45.6, 38.5, 28.9, 36.3, 42.0, 37.8, 39.…
$ open_th      &lt;dbl&gt; 4735, 4202, 4396, 4534, 4676, 4391, 4417, 4375, 4234, 440…
$ Open         &lt;dbl&gt; 44708, 44911, 44876, 44687, 44722, 44743, 44624, 44750, 4…
$ Distributor  &lt;chr&gt; "Paramount Pictures", "20th Century Studios", "Walt Disne…
$ int_gross    &lt;dbl&gt; 770000000, 1539273359, 389276658, 544444197, 625127000, 5…
$ world_gross  &lt;dbl&gt; 1488732821, 2176229105, 842750982, 955775804, 1001978080,…
$ Unit         &lt;chr&gt; "million", "million", "million", "million", "million", "m…
$ BXUnit       &lt;chr&gt; "billion", "billion", "million", "million", "billion", "m…
$ Count        &lt;int&gt; 12, 4, 9, 9, 19, 19, 6, 9, 12, 6, 19, 6, 9, 19, 9, 12, 12…
$ Small_Dist   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ Open_date    &lt;date&gt; 2022-05-27, 2022-12-16, 2022-11-11, 2022-05-06, 2022-06-…
$ season       &lt;chr&gt; "Spring", "Winter", "Fall", "Spring", "Summer", "Summer",…</code></pre>
</div>
</div>
</section>
<section id="summary-of-each-variables" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-each-variables">Summary of each variables</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      Rank          Release              Budget            Box Office       
 Min.   :  1.00   Length:104         Min.   :1.500e+05   Min.   :3.250e+05  
 1st Qu.: 26.75   Class :character   1st Qu.:1.665e+07   1st Qu.:2.170e+07  
 Median : 56.50   Mode  :character   Median :3.550e+07   Median :6.535e+07  
 Mean   : 67.90                      Mean   :1.059e+10   Mean   :1.467e+10  
 3rd Qu.:102.50                      3rd Qu.:9.000e+07   3rd Qu.:1.966e+08  
 Max.   :196.00                      Max.   :3.200e+11   Max.   :4.000e+11  
     Gross               max_th        Opening           perc_tot_gr   
 Min.   :   325042   Min.   :   5   Min.   :     8416   Min.   : 0.10  
 1st Qu.:  3755174   1st Qu.:1005   1st Qu.:   825579   1st Qu.:21.25  
 Median : 17247468   Median :3131   Median :  5128384   Median :31.85  
 Mean   : 67815629   Mean   :2584   Mean   : 20890734   Mean   :29.89  
 3rd Qu.: 69210756   3rd Qu.:3848   3rd Qu.: 19126885   3rd Qu.:39.85  
 Max.   :718732821   Max.   :4751   Max.   :187420998   Max.   :62.90  
    open_th            Open       Distributor          int_gross        
 Min.   :   2.0   Min.   :44568   Length:104         Min.   :6.752e+04  
 1st Qu.: 661.5   1st Qu.:44673   Class :character   1st Qu.:2.542e+06  
 Median :3075.0   Median :44768   Mode  :character   Median :2.467e+07  
 Mean   :2400.9   Mean   :44757                      Mean   :8.879e+07  
 3rd Qu.:3770.0   3rd Qu.:44841                      3rd Qu.:6.163e+07  
 Max.   :4735.0   Max.   :44925                      Max.   :1.539e+09  
  world_gross            Unit              BXUnit              Count       
 Min.   :8.416e+03   Length:104         Length:104         Min.   : 1.000  
 1st Qu.:9.576e+06   Class :character   Class :character   1st Qu.: 4.750  
 Median :4.348e+07   Mode  :character   Mode  :character   Median : 9.000  
 Mean   :1.563e+08                                         Mean   : 8.721  
 3rd Qu.:1.445e+08                                         3rd Qu.:12.000  
 Max.   :2.176e+09                                         Max.   :19.000  
   Small_Dist       Open_date             season         
 Min.   :0.0000   Min.   :2022-01-07   Length:104        
 1st Qu.:0.0000   1st Qu.:2022-04-22   Class :character  
 Median :0.0000   Median :2022-07-25   Mode  :character  
 Mean   :0.2115   Mean   :2022-07-15                     
 3rd Qu.:0.0000   3rd Qu.:2022-10-07                     
 Max.   :1.0000   Max.   :2022-12-30                     </code></pre>
</div>
</div>
<p>Let’s look on the distribution of data</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Jerin_Jacob_Final_Project_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>Opening)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Jerin_Jacob_Final_Project_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histogram for "Box Office" variable with colors</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">main =</span> <span class="st">"Box Office Distribution"</span>, <span class="at">xlab =</span> <span class="st">"Box Office"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Jerin_Jacob_Final_Project_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histogram for "Opening" variable with colors</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>Opening, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">main =</span> <span class="st">"Opening Distribution"</span>, <span class="at">xlab =</span> <span class="st">"Opening"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Jerin_Jacob_Final_Project_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="check-correlation-between-box-office-and-opening" class="level3">
<h3 class="anchored" data-anchor-id="check-correlation-between-box-office-and-opening">Check correlation between Box Office and Opening</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Opening, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  df$Opening and df$`Box Office`
t = -1.0944, df = 102, p-value = 0.2764
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.29421354  0.08665663
sample estimates:
       cor 
-0.1077295 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="fu">log</span>(df<span class="sc">$</span>Opening), <span class="fu">log</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  log(df$Opening) and log(df$`Box Office`)
t = 4.8371, df = 102, p-value = 4.681e-06
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.2610906 0.5765810
sample estimates:
      cor 
0.4319587 </code></pre>
</div>
</div>
<p>The data appears to be skewed. Therefore we can try some data transformation. Log transformation would be the first option. Let’s visualize the correlation of variables in the dataset.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset the desired variables</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>pairs_df <span class="ot">&lt;-</span> df[, <span class="fu">c</span>(<span class="st">"Budget"</span>, <span class="st">"Box Office"</span>, <span class="st">"Opening"</span>, <span class="st">"open_th"</span>, <span class="st">"max_th"</span>)]</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot matrix with colors</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(pairs_df, <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="fu">length</span>(pairs_df)), <span class="at">pch =</span> <span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Jerin_Jacob_Final_Project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the visualization, we can conclude that all the variables are correlated by open_th and max_th are moving exactly the same in the graph which means we should drop one of them to avoid the multicollinearity.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histogram for the logarithm of "Box Office" variable with colors</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">log</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>), <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">main =</span> <span class="st">"Box Office Distribution (Log)"</span>, <span class="at">xlab =</span> <span class="st">"Log(Box Office)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Jerin_Jacob_Final_Project_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histogram for the logarithm of "Opening" variable with colors</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">log</span>(df<span class="sc">$</span>Opening), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">main =</span> <span class="st">"Opening Distribution (Log)"</span>, <span class="at">xlab =</span> <span class="st">"Log(Opening)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Jerin_Jacob_Final_Project_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The log transformation made the data look like a normal distribution.</p>
</section>
</section>
<section id="running-different-models-to-get-the-best-fit" class="level2">
<h2 class="anchored" data-anchor-id="running-different-models-to-get-the-best-fit">Running different models to get the best fit</h2>
<p>Log transformed model with only the predictor and the dependant variable</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the multiple regression model using the log-transformed data</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening), <span class="at">data =</span> df)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the model summary</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model1)</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model1)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Log transformation for all continous variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening) <span class="sc">+</span> <span class="fu">log</span>(Budget) <span class="sc">+</span> <span class="fu">log</span>(open_th) <span class="sc">+</span> Small_Dist <span class="sc">+</span> season, <span class="at">data =</span> df)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model2)</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The R-square has significantly improved for this model. Let us try more models.</p>
<p>Log transformation for only Box Office, Opening and Budget.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening) <span class="sc">+</span> <span class="fu">log</span>(Budget) <span class="sc">+</span> open_th <span class="sc">+</span> Small_Dist <span class="sc">+</span> season, <span class="at">data =</span> df)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model3)</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model3)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Log transformation for only Box Office, Opening and Budget. Removing season confounder.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening) <span class="sc">+</span> <span class="fu">log</span>(Budget) <span class="sc">+</span> open_th <span class="sc">+</span> Small_Dist, <span class="at">data =</span> df)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model4)</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model4)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>R square values are further below the previous model. Let us try the log transformed model with only the Budget and Small_Distributor as confounders.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening) <span class="sc">+</span> <span class="fu">log</span>(Budget) <span class="sc">+</span> open_th, <span class="at">data =</span> df)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model5)</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model5)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now, we can run a log transformed model with only the Opening and Budget.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>model6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening) <span class="sc">+</span> <span class="fu">log</span>(Budget), <span class="at">data =</span> df)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model6)</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model6)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let us run models after quadratic transformation</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>model_quad1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">poly</span>(Opening, <span class="dv">2</span>, <span class="at">raw=</span><span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">log</span>(Budget) <span class="sc">+</span> open_th <span class="sc">+</span> Small_Dist <span class="sc">+</span> season, <span class="at">data =</span> df)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model_quad1)</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model_quad1)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="selecting-a-model-and-interpretation-of-the-result" class="level2">
<h2 class="anchored" data-anchor-id="selecting-a-model-and-interpretation-of-the-result">Selecting a model and Interpretation of the result</h2>
<p>Now that we have multiple models, we can select the best model out of them using following criteria; a) R-squared b) Adjusted R-squared c) PRESS d) AIC (Akaike Information Criterion) e) BIC (Bayesian Information Criterion)</p>
<p>In the model selection process, we can follow the rule of thumb as, for R-squared and Adjusted R-square, higher is better while for PRESS, AIC and BIC, lower is better.</p>
<p>Create a functions to get R-squared, Adjusted R-squared &amp; PRESS</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>rsquared <span class="ot">&lt;-</span> <span class="cf">function</span>(fit) <span class="fu">summary</span>(fit)<span class="sc">$</span>r.squared</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>adj_rsquared <span class="ot">&lt;-</span> <span class="cf">function</span>(fit) <span class="fu">summary</span>(fit)<span class="sc">$</span>adj.r.squared</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>PRESS <span class="ot">&lt;-</span> <span class="cf">function</span>(fit) {</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  pr <span class="ot">&lt;-</span> <span class="fu">residuals</span>(fit)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">lm.influence</span>(fit)<span class="sc">$</span>hat)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(pr<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>For AIC and BIC, the functions AIC() and BIC() can be used</p>
<p>Now, applying the functions to model objects</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>(model1, model2, model3, model4, model5, model6, model_quad1)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>model_comparison <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">models =</span> <span class="fu">c</span>(<span class="st">'model1'</span>, <span class="st">'model2'</span>, <span class="st">'model3'</span>, <span class="st">'model4'</span>, <span class="st">'model5'</span>, <span class="st">'model6'</span>, <span class="st">'model_quad1'</span>),</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">rSquared =</span> <span class="fu">sapply</span>(models, rsquared),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">adj_rSquared =</span> <span class="fu">sapply</span>(models, adj_rsquared),</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">PRESS =</span> <span class="fu">sapply</span>(models, PRESS),</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">AIC =</span> <span class="fu">sapply</span>(models, AIC),</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">BIC =</span> <span class="fu">sapply</span>(models, BIC)) <span class="sc">|&gt;</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       models  rSquared adj_rSquared    PRESS      AIC      BIC
1      model1 0.1865883    0.1786137 637.0491 486.5987 494.5319
2      model2 0.7330391    0.7135732 257.5371 382.7287 406.5282
3      model3 0.7348150    0.7154786 253.7251 382.0345 405.8341
4      model4 0.7185101    0.7071368 253.9816 382.2401 398.1064
5      model5 0.7104267    0.7017395 253.7536 383.1845 396.4065
6      model6 0.6883896    0.6822191 269.4781 388.8124 399.3900
7 model_quad1 0.6951725    0.6695029 289.9369 398.5236 424.9675</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Please cite as: </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model1, model2, model3, model4, model5, model6, model_quad1, <span class="at">type =</span> <span class="st">'text'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
==================================================================================================================================================================================================
                                                                                                      Dependent variable:                                                                         
                              --------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                       log(`Box Office`)                                                                          
                                        (1)                    (2)                    (3)                    (4)                     (5)                     (6)                     (7)          
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
log(Opening)                         0.518***                0.631***               0.792***               0.790***               0.750***                 0.294***                               
                                      (0.107)                (0.133)                (0.178)                (0.178)                 (0.178)                 (0.069)                                
                                                                                                                                                                                                  
poly(Opening, 2, raw = TRUE)1                                                                                                                                                      0.00000*       
                                                                                                                                                                                  (0.00000)       
                                                                                                                                                                                                  
poly(Opening, 2, raw = TRUE)2                                                                                                                                                       -0.000        
                                                                                                                                                                                   (0.000)        
                                                                                                                                                                                                  
log(Budget)                                                  0.710***               0.642***               0.657***               0.665***                 0.746***                0.758***       
                                                             (0.056)                (0.063)                (0.063)                 (0.064)                 (0.059)                 (0.060)        
                                                                                                                                                                                                  
log(open_th)                                                -0.337***                                                                                                                             
                                                             (0.121)                                                                                                                              
                                                                                                                                                                                                  
open_th                                                                            -0.001***              -0.001***               -0.001***                                         0.0001        
                                                                                    (0.0002)               (0.0002)               (0.0002)                                         (0.0001)       
                                                                                                                                                                                                  
Small_Dist                                                   0.795**                 0.649*                 0.634*                                                                  0.467         
                                                             (0.377)                (0.372)                (0.376)                                                                 (0.398)        
                                                                                                                                                                                                  
seasonSpring                                                 0.804**                0.880**                                                                                         0.800*        
                                                             (0.405)                (0.404)                                                                                        (0.437)        
                                                                                                                                                                                                  
seasonSummer                                                  0.048                  0.005                                                                                          -0.104        
                                                             (0.379)                (0.377)                                                                                        (0.411)        
                                                                                                                                                                                                  
seasonWinter                                                  0.086                  0.271                                                                                          0.072         
                                                             (0.410)                (0.414)                                                                                        (0.443)        
                                                                                                                                                                                                  
Constant                             10.425***                -1.967                -3.845**               -3.907**                -3.308*                  0.606                  4.037***       
                                      (1.640)                (1.518)                (1.915)                (1.899)                 (1.883)                 (1.278)                 (1.116)        
                                                                                                                                                                                                  
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Observations                            104                    104                    104                    104                     104                     104                     104          
R2                                     0.187                  0.733                  0.735                  0.719                   0.710                   0.688                   0.695         
Adjusted R2                            0.179                  0.714                  0.715                  0.707                   0.702                   0.682                   0.670         
Residual Std. Error              2.463 (df = 102)        1.454 (df = 96)        1.450 (df = 96)        1.471 (df = 99)        1.484 (df = 100)         1.532 (df = 101)        1.562 (df = 95)    
F Statistic                   23.398*** (df = 1; 102) 37.658*** (df = 7; 96) 38.002*** (df = 7; 96) 63.175*** (df = 4; 99) 81.779*** (df = 3; 100) 111.561*** (df = 2; 101) 27.081*** (df = 8; 95)
==================================================================================================================================================================================================
Note:                                                                                                                                                                  *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Out of all the models we ran, model3 looks as the best fit.</p>
<p>The linear regression model predicts the logarithm of Box Office collections based on the logarithm of Opening weekend collections, logarithm of Budget, number of theaters the movie opened in, Small_Dist (a binary variable indicating whether the distributor is small or not), and the season in which the movie was released (Spring, Summer, or Winter).</p>
<p>The coefficients of the independent variables show the direction and magnitude of their effect on the dependent variable. The p-value associated with each coefficient indicates whether the coefficient is statistically significant or not.</p>
<p>The intercept coefficient is -3.845, which means that if all independent variables are zero, the model predicts that the logarithm of Box Office collections is -3.845. However, since all the independent variables are not zero in practice, this value is not meaningful.</p>
<p>The coefficient of the logarithm of Opening weekend collections is 0.792, which means that a one percent increase in Opening weekend collections is associated with a 0.792 percent increase in Box Office collections.</p>
<p>The coefficient of the logarithm of Budget is 0.642, which means that a one percent increase in Budget is associated with a 0.642 percent increase in Box Office collections.</p>
<p>The coefficient of the number of theaters the movie opened in (open_th) is negative (-0.00068), which means that as the number of theaters increases by one, the predicted logarithm of Box Office collections decreases by 0.00068. This is something to be studied further, as it goes against our logic and expectation.</p>
<p>The coefficient of Small_Dist is 0.649, which means that the Box Office collections of movies released by small distributors are 0.649 times higher than those of movies released by large distributors, holding other variables constant. This also need more detailed study.</p>
<p>The coefficients associated with season indicate the difference in Box Office collections between movies released in that season and movies released in Fall (omitted reference level). For example, the coefficient of season Spring is 0.88, which means that the predicted Box Office collections of movies released in Spring are 0.88 times higher than those of movies released in Fall.</p>
<p>The adjusted R-squared of the model is 0.7155, which means that 71.55% of the variation in the logarithm of Box Office collections can be explained by the independent variables in the model.</p>
</section>
<section id="visualising-the-regression-model." class="level2">
<h2 class="anchored" data-anchor-id="visualising-the-regression-model.">Visualising the regression model.</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the color palette</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"orange"</span>, <span class="st">"purple"</span>, <span class="st">"pink"</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a blank plot with the desired layout</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through the diagnostic plots and assign colors</span></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>) {</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(model3, <span class="at">which =</span> i, <span class="at">col =</span> colors[i])</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Jerin_Jacob_Final_Project_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Scale-Location plot suggests some level of heteroskedacity. So, it is better to check if there is a serious problem of heteroskedacity,we can run Breusch-Pagan test.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  model3
BP = 16.322, df = 7, p-value = 0.02233</code></pre>
</div>
</div>
<p>The p-value for Breusch-Pagan test is 0.02233. This is possibly a heteroskedacity. We need to look more into this.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion:</h2>
<p>The model that we build shows that the Box Office collection of a movie is affected positively by the Opening week collection. 1 percentage of increase in Opening week collection results in 0.792 percent increase in Box office collection after taking into account the intercept(-3.845). But the Breusch-Pagan test for heteroskedacity gives a low p-value which suggests that the model is showing heteroskedacity.</p>
<p>The dataset has only 200 rows out of which 96 rows were dropped as they have NA values. Also, many movies in this dataset had Box office collections much lesser than their budget. But that does not necessarily mean that those movies made a loss. In the age of online streaming platforms, many movies are making money not from Box Office only. But our study was focused only on the revenue from theatre collection. Also, in the future study, the variable transformation to address the heteroskedacity should be done.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References:</h2>
<ol type="1">
<li><p>Nasir, Suphan &amp; Öcal, Figen. (2016). Film Marketing: The Impact of Publicity Activities on Demand Generation. 10.4018/978-1-5225-0143-5.ch019.</p></li>
<li><p><em>Elizabeth Cooper-Martin (1991) ,“Consumers and Movies: Some Findings on Experiential Products”, in NA - Advances in Consumer Research Volume 18, eds.&nbsp;Rebecca H. Holman and Michael R. Solomon, Provo, UT : Association for Consumer Research, Pages: 372-378.</em></p></li>
<li><p>Kaggle.com (Original dataset)</p></li>
<li><p>Wikipedia.com (Movie pages to get budget and box office collections)</p></li>
</ol>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb62" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Project 603"</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Jerin Jacob"</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Final project qmd file for 603"</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "03/10/2023"</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a><span class="co">  </span></span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - finalproject</span></span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a>Now a days, movies are a well marketed entertainment product. Just like any other products in the market, movies are also having an allocated a marketing budget and promotional activities are done in scale. This often result in the opening weekend's gross ticketing volume to rise. But are the pre-release promotional activities helping the movie to collect more or is it just creating a hype initially? Or does the movie's gross collection is not at all dependant on pre release promotions? This dataset has 200 highest grossing movies of 2022. It has both the opening week's gross as well as the total gross collection of the movies, along with other variables. Assuming that opening week's collection is depending on the pre-release promotion, by looking on the relationship between opening week's gross and total gross, I am trying to see how the pre-release activities help the producers earn more in boxoffice.</span>
<span id="cb62-18"><a href="#cb62-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-19"><a href="#cb62-19" aria-hidden="true" tabindex="-1"></a>**Research Question**: To what extent does the success of a movie depend on its opening week's collection?</span>
<span id="cb62-20"><a href="#cb62-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-21"><a href="#cb62-21" aria-hidden="true" tabindex="-1"></a>**Hypothesis**: Opening week's collection is positively correlated with the Box Office total collection.</span>
<span id="cb62-22"><a href="#cb62-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-23"><a href="#cb62-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-24"><a href="#cb62-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-25"><a href="#cb62-25" aria-hidden="true" tabindex="-1"></a>Loading all the packages required for the project. </span>
<span id="cb62-26"><a href="#cb62-26" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=T}</span></span>
<span id="cb62-27"><a href="#cb62-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb62-28"><a href="#cb62-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb62-29"><a href="#cb62-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb62-30"><a href="#cb62-30" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb62-31"><a href="#cb62-31" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb62-32"><a href="#cb62-32" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-33"><a href="#cb62-33" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reading the data</span></span>
<span id="cb62-36"><a href="#cb62-36" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-37"><a href="#cb62-37" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"_data/project_data.xlsx"</span>) <span class="sc">|&gt;</span></span>
<span id="cb62-38"><a href="#cb62-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb62-39"><a href="#cb62-39" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span>
<span id="cb62-40"><a href="#cb62-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-41"><a href="#cb62-41" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-42"><a href="#cb62-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-43"><a href="#cb62-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-44"><a href="#cb62-44" aria-hidden="true" tabindex="-1"></a>There are 14 variables with 200 rows.</span>
<span id="cb62-45"><a href="#cb62-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-46"><a href="#cb62-46" aria-hidden="true" tabindex="-1"></a><span class="fu">### **COLUMN DESCRIPTION**</span></span>
<span id="cb62-47"><a href="#cb62-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-48"><a href="#cb62-48" aria-hidden="true" tabindex="-1"></a>'Rank': rank of the movie</span>
<span id="cb62-49"><a href="#cb62-49" aria-hidden="true" tabindex="-1"></a>'Release': release date of the movie</span>
<span id="cb62-50"><a href="#cb62-50" aria-hidden="true" tabindex="-1"></a>'Budget': The budget of the movie production</span>
<span id="cb62-51"><a href="#cb62-51" aria-hidden="true" tabindex="-1"></a>'Box Office': The total Box Office collection</span>
<span id="cb62-52"><a href="#cb62-52" aria-hidden="true" tabindex="-1"></a>'Gross': domestic gross of the movie</span>
<span id="cb62-53"><a href="#cb62-53" aria-hidden="true" tabindex="-1"></a>'max_th': maximum number of theaters the movie was released in</span>
<span id="cb62-54"><a href="#cb62-54" aria-hidden="true" tabindex="-1"></a>'Opening': gross on opening weekend</span>
<span id="cb62-55"><a href="#cb62-55" aria-hidden="true" tabindex="-1"></a>'perc_tot_gr': domestic percentage of the total gross</span>
<span id="cb62-56"><a href="#cb62-56" aria-hidden="true" tabindex="-1"></a>'open_th': number of theaters the movie opened in</span>
<span id="cb62-57"><a href="#cb62-57" aria-hidden="true" tabindex="-1"></a>'Open': opening date</span>
<span id="cb62-58"><a href="#cb62-58" aria-hidden="true" tabindex="-1"></a>'Close': closing date</span>
<span id="cb62-59"><a href="#cb62-59" aria-hidden="true" tabindex="-1"></a>'Distributor': name of the distributor</span>
<span id="cb62-60"><a href="#cb62-60" aria-hidden="true" tabindex="-1"></a>'int_gross': international gross</span>
<span id="cb62-61"><a href="#cb62-61" aria-hidden="true" tabindex="-1"></a>'world_gross': worldwide gross</span>
<span id="cb62-62"><a href="#cb62-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-63"><a href="#cb62-63" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>'Release': release date of the movie</span>
<span id="cb62-64"><a href="#cb62-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-65"><a href="#cb62-65" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>'Distributor': name of the distributor</span>
<span id="cb62-66"><a href="#cb62-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-67"><a href="#cb62-67" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>'Small_Dist': Whether a small distributor or not</span>
<span id="cb62-68"><a href="#cb62-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-69"><a href="#cb62-69" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span></span>
<span id="cb62-70"><a href="#cb62-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-71"><a href="#cb62-71" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>'Open_date': Date of release</span>
<span id="cb62-72"><a href="#cb62-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-73"><a href="#cb62-73" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>'season': The season in which the movie was released</span>
<span id="cb62-74"><a href="#cb62-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-75"><a href="#cb62-75" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>'Opening': gross on opening weekend</span>
<span id="cb62-76"><a href="#cb62-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-77"><a href="#cb62-77" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>'open_th': number of theaters the movie opened in</span>
<span id="cb62-78"><a href="#cb62-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-79"><a href="#cb62-79" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>'max_th': maximum number of theaters the movie was released in</span>
<span id="cb62-80"><a href="#cb62-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-81"><a href="#cb62-81" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb62-82"><a href="#cb62-82" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cleaning the Data</span></span>
<span id="cb62-83"><a href="#cb62-83" aria-hidden="true" tabindex="-1"></a>For our purpose of analysis, we need to clean and transform the data a bit. </span>
<span id="cb62-84"><a href="#cb62-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-85"><a href="#cb62-85" aria-hidden="true" tabindex="-1"></a>First, the Budget and Boxoffice columns are cleaned using stringr function so that the column values are numeric. We are getting rid of the character part in those values including '$' and the value unit. Also, there are certain values which are in Indian Rupees and South Korean won. So we need to convert thoses values to US dollars. The data for columns Budget and Box office were taken from Wikipedia. </span>
<span id="cb62-88"><a href="#cb62-88" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-89"><a href="#cb62-89" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> </span>
<span id="cb62-90"><a href="#cb62-90" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Budget =</span> <span class="fu">gsub</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">$"</span>, <span class="st">""</span>, Budget)) <span class="sc">|&gt;</span></span>
<span id="cb62-91"><a href="#cb62-91" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Budget =</span> <span class="fu">sub</span>(<span class="st">".*-"</span>, <span class="st">""</span>, Budget)) <span class="sc">|&gt;</span></span>
<span id="cb62-92"><a href="#cb62-92" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">gsub</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">$"</span>, <span class="st">""</span>, <span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)) </span>
<span id="cb62-93"><a href="#cb62-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-94"><a href="#cb62-94" aria-hidden="true" tabindex="-1"></a>df[<span class="fu">c</span>(<span class="st">'Budget'</span>, <span class="st">'Unit'</span>)] <span class="ot">&lt;-</span> <span class="fu">str_split_fixed</span>(df<span class="sc">$</span>Budget, <span class="st">' '</span>, <span class="dv">2</span>)</span>
<span id="cb62-95"><a href="#cb62-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-96"><a href="#cb62-96" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Budget <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df<span class="sc">$</span>Budget)</span>
<span id="cb62-97"><a href="#cb62-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-98"><a href="#cb62-98" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Budget <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>Unit <span class="sc">==</span> <span class="st">"million"</span>, df<span class="sc">$</span>Budget <span class="sc">*</span> <span class="dv">1000000</span>,</span>
<span id="cb62-99"><a href="#cb62-99" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">ifelse</span>(df<span class="sc">$</span>Unit <span class="sc">==</span> <span class="st">"billion"</span>, df<span class="sc">$</span>Budget <span class="sc">*</span> <span class="dv">1000000000</span>,</span>
<span id="cb62-100"><a href="#cb62-100" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">ifelse</span>(df<span class="sc">$</span>Unit <span class="sc">==</span> <span class="st">"Kmillion"</span>, df<span class="sc">$</span>Budget <span class="sc">*</span> <span class="dv">1000000</span><span class="sc">*</span><span class="fl">0.00074</span>,</span>
<span id="cb62-101"><a href="#cb62-101" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">ifelse</span>(df<span class="sc">$</span>Unit <span class="sc">==</span> <span class="st">"Kbillion"</span>, df<span class="sc">$</span>Budget <span class="sc">*</span> <span class="dv">1000000000</span><span class="sc">*</span><span class="fl">0.00074</span>,</span>
<span id="cb62-102"><a href="#cb62-102" aria-hidden="true" tabindex="-1"></a>                                         <span class="fu">ifelse</span>(df<span class="sc">$</span>Unit <span class="sc">==</span> <span class="st">"crore"</span>, df<span class="sc">$</span>Budget <span class="sc">*</span> <span class="dv">10000000</span><span class="sc">*</span><span class="dv">80</span>, df<span class="sc">$</span>Budget)))))</span>
<span id="cb62-103"><a href="#cb62-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-104"><a href="#cb62-104" aria-hidden="true" tabindex="-1"></a>df[<span class="fu">c</span>(<span class="st">'Box Office'</span>, <span class="st">'BXUnit'</span>)] <span class="ot">&lt;-</span> <span class="fu">str_split_fixed</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>, <span class="st">' '</span>, <span class="dv">2</span>)</span>
<span id="cb62-105"><a href="#cb62-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-106"><a href="#cb62-106" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)</span>
<span id="cb62-107"><a href="#cb62-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-108"><a href="#cb62-108" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>BXUnit <span class="sc">==</span> <span class="st">"million"</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">*</span> <span class="dv">1000000</span>,</span>
<span id="cb62-109"><a href="#cb62-109" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">ifelse</span>(df<span class="sc">$</span>BXUnit <span class="sc">==</span> <span class="st">"billion"</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">*</span> <span class="dv">1000000000</span>,</span>
<span id="cb62-110"><a href="#cb62-110" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">ifelse</span>(df<span class="sc">$</span>BXUnit <span class="sc">==</span> <span class="st">"Kmillion"</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">*</span> <span class="dv">1000000</span><span class="sc">*</span><span class="fl">0.00074</span>,</span>
<span id="cb62-111"><a href="#cb62-111" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">ifelse</span>(df<span class="sc">$</span>BXUnit <span class="sc">==</span> <span class="st">"Kbillion"</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">*</span> <span class="dv">1000000000</span><span class="sc">*</span><span class="fl">0.00074</span>,</span>
<span id="cb62-112"><a href="#cb62-112" aria-hidden="true" tabindex="-1"></a>                                         <span class="fu">ifelse</span>(df<span class="sc">$</span>BXUnit <span class="sc">==</span> <span class="st">"crore"</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">*</span> <span class="dv">10000000</span><span class="sc">*</span><span class="dv">80</span>, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)))))</span>
<span id="cb62-113"><a href="#cb62-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-114"><a href="#cb62-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-115"><a href="#cb62-115" aria-hidden="true" tabindex="-1"></a>Since the original dataset from Kaggle had a column named world_gross, we can compare both variables and assume that the highest value in either of the column can be considerd as the final world_gross.  </span>
<span id="cb62-116"><a href="#cb62-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-119"><a href="#cb62-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-120"><a href="#cb62-120" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span> <span class="sc">&lt;</span> df<span class="sc">$</span>world_gross, df<span class="sc">$</span>world_gross, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)</span>
<span id="cb62-121"><a href="#cb62-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-122"><a href="#cb62-122" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-123"><a href="#cb62-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-124"><a href="#cb62-124" aria-hidden="true" tabindex="-1"></a>We can count the number of movies in the list for each distributor and any distributor who don't have more than 3 movies in their name can be considered as a smaller distributor and thus assuming that they won't have cash rich promotional campaigns that would lead to an audience pull to the theatre in the initial week.  </span>
<span id="cb62-127"><a href="#cb62-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-128"><a href="#cb62-128" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Distributor) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Count=</span><span class="fu">n_distinct</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)) </span>
<span id="cb62-129"><a href="#cb62-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-130"><a href="#cb62-130" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Small_Dist <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>Count <span class="sc">&lt;=</span> <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb62-131"><a href="#cb62-131" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-132"><a href="#cb62-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-133"><a href="#cb62-133" aria-hidden="true" tabindex="-1"></a>We can convert the dbl to date format and set the reference date so that the dates are correct. After that, from the Open_date, we can categorize thsoe dates to the season so that it can be used as a confounder. Seasons might have some effect on the theatre footfall and thereby, box office collections.</span>
<span id="cb62-136"><a href="#cb62-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-137"><a href="#cb62-137" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Open_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(df<span class="sc">$</span>Open, <span class="at">origin =</span> <span class="st">"1899-12-30"</span>)</span>
<span id="cb62-138"><a href="#cb62-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-139"><a href="#cb62-139" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column with the season for each date</span></span>
<span id="cb62-140"><a href="#cb62-140" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb62-141"><a href="#cb62-141" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">season =</span> <span class="fu">case_when</span>(</span>
<span id="cb62-142"><a href="#cb62-142" aria-hidden="true" tabindex="-1"></a>    <span class="fu">between</span>(<span class="fu">month</span>(Open_date), <span class="dv">3</span>, <span class="dv">5</span>) <span class="sc">~</span> <span class="st">"Spring"</span>,</span>
<span id="cb62-143"><a href="#cb62-143" aria-hidden="true" tabindex="-1"></a>    <span class="fu">between</span>(<span class="fu">month</span>(Open_date), <span class="dv">6</span>, <span class="dv">8</span>) <span class="sc">~</span> <span class="st">"Summer"</span>,</span>
<span id="cb62-144"><a href="#cb62-144" aria-hidden="true" tabindex="-1"></a>    <span class="fu">between</span>(<span class="fu">month</span>(Open_date), <span class="dv">9</span>, <span class="dv">11</span>) <span class="sc">~</span> <span class="st">"Fall"</span>,</span>
<span id="cb62-145"><a href="#cb62-145" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Winter"</span></span>
<span id="cb62-146"><a href="#cb62-146" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb62-147"><a href="#cb62-147" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-148"><a href="#cb62-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-149"><a href="#cb62-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-152"><a href="#cb62-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-153"><a href="#cb62-153" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span>
<span id="cb62-154"><a href="#cb62-154" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-155"><a href="#cb62-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-156"><a href="#cb62-156" aria-hidden="true" tabindex="-1"></a>Checking for NA values in each variable. There are 90 NA values in Budget variable, 38 in Box Office, 155 in Close date variable and 3 in int_gross. All othe variables seems to be good in terms of NA values.</span>
<span id="cb62-159"><a href="#cb62-159" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-160"><a href="#cb62-160" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(df))</span>
<span id="cb62-161"><a href="#cb62-161" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>Small_Dist)</span>
<span id="cb62-162"><a href="#cb62-162" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-163"><a href="#cb62-163" aria-hidden="true" tabindex="-1"></a>Since 155 values of Close are NAs, it is better not to include that variable in the analysis. Most of the NA values are for the movies by small distributors, which need to be noted.</span>
<span id="cb62-166"><a href="#cb62-166" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-167"><a href="#cb62-167" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="sc">-</span>Close)</span>
<span id="cb62-168"><a href="#cb62-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-169"><a href="#cb62-169" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(df)</span>
<span id="cb62-170"><a href="#cb62-170" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking for NA's</span></span>
<span id="cb62-171"><a href="#cb62-171" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(df))</span>
<span id="cb62-172"><a href="#cb62-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-173"><a href="#cb62-173" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-174"><a href="#cb62-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-175"><a href="#cb62-175" aria-hidden="true" tabindex="-1"></a>Have an idea about the structure of the dataset.</span>
<span id="cb62-178"><a href="#cb62-178" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-179"><a href="#cb62-179" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span>
<span id="cb62-180"><a href="#cb62-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-181"><a href="#cb62-181" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-182"><a href="#cb62-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-183"><a href="#cb62-183" aria-hidden="true" tabindex="-1"></a>Using the glimpse() function, let's have a look at how our data would look like!</span>
<span id="cb62-184"><a href="#cb62-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-187"><a href="#cb62-187" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-188"><a href="#cb62-188" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df )</span>
<span id="cb62-189"><a href="#cb62-189" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-190"><a href="#cb62-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-191"><a href="#cb62-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-192"><a href="#cb62-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-193"><a href="#cb62-193" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary of each variables</span></span>
<span id="cb62-194"><a href="#cb62-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-195"><a href="#cb62-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-198"><a href="#cb62-198" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-199"><a href="#cb62-199" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span>
<span id="cb62-200"><a href="#cb62-200" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-201"><a href="#cb62-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-202"><a href="#cb62-202" aria-hidden="true" tabindex="-1"></a>Let's look on the distribution of data</span>
<span id="cb62-203"><a href="#cb62-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-206"><a href="#cb62-206" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-207"><a href="#cb62-207" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)</span>
<span id="cb62-208"><a href="#cb62-208" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>Opening)</span>
<span id="cb62-209"><a href="#cb62-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-210"><a href="#cb62-210" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histogram for "Box Office" variable with colors</span></span>
<span id="cb62-211"><a href="#cb62-211" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">main =</span> <span class="st">"Box Office Distribution"</span>, <span class="at">xlab =</span> <span class="st">"Box Office"</span>)</span>
<span id="cb62-212"><a href="#cb62-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-213"><a href="#cb62-213" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histogram for "Opening" variable with colors</span></span>
<span id="cb62-214"><a href="#cb62-214" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>Opening, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">main =</span> <span class="st">"Opening Distribution"</span>, <span class="at">xlab =</span> <span class="st">"Opening"</span>)</span>
<span id="cb62-215"><a href="#cb62-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-216"><a href="#cb62-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-217"><a href="#cb62-217" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-218"><a href="#cb62-218" aria-hidden="true" tabindex="-1"></a><span class="fu">### Check correlation between Box Office and Opening</span></span>
<span id="cb62-221"><a href="#cb62-221" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-222"><a href="#cb62-222" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Opening, df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>)</span>
<span id="cb62-223"><a href="#cb62-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-224"><a href="#cb62-224" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="fu">log</span>(df<span class="sc">$</span>Opening), <span class="fu">log</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>))</span>
<span id="cb62-225"><a href="#cb62-225" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-226"><a href="#cb62-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-227"><a href="#cb62-227" aria-hidden="true" tabindex="-1"></a>The data appears to be skewed. Therefore we can try some data transformation. Log transformation would be the first option.</span>
<span id="cb62-228"><a href="#cb62-228" aria-hidden="true" tabindex="-1"></a>Let's visualize the correlation of variables in the dataset.</span>
<span id="cb62-231"><a href="#cb62-231" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-232"><a href="#cb62-232" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset the desired variables</span></span>
<span id="cb62-233"><a href="#cb62-233" aria-hidden="true" tabindex="-1"></a>pairs_df <span class="ot">&lt;-</span> df[, <span class="fu">c</span>(<span class="st">"Budget"</span>, <span class="st">"Box Office"</span>, <span class="st">"Opening"</span>, <span class="st">"open_th"</span>, <span class="st">"max_th"</span>)]</span>
<span id="cb62-234"><a href="#cb62-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-235"><a href="#cb62-235" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot matrix with colors</span></span>
<span id="cb62-236"><a href="#cb62-236" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(pairs_df, <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="fu">length</span>(pairs_df)), <span class="at">pch =</span> <span class="dv">19</span>)</span>
<span id="cb62-237"><a href="#cb62-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-238"><a href="#cb62-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-239"><a href="#cb62-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-240"><a href="#cb62-240" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-241"><a href="#cb62-241" aria-hidden="true" tabindex="-1"></a>From the visualization, we can conclude that all the variables are correlated by open_th and max_th are moving exactly the same in the graph which means we should drop one of them to avoid the multicollinearity.</span>
<span id="cb62-242"><a href="#cb62-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-245"><a href="#cb62-245" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-246"><a href="#cb62-246" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histogram for the logarithm of "Box Office" variable with colors</span></span>
<span id="cb62-247"><a href="#cb62-247" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">log</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>), <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">main =</span> <span class="st">"Box Office Distribution (Log)"</span>, <span class="at">xlab =</span> <span class="st">"Log(Box Office)"</span>)</span>
<span id="cb62-248"><a href="#cb62-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-249"><a href="#cb62-249" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histogram for the logarithm of "Opening" variable with colors</span></span>
<span id="cb62-250"><a href="#cb62-250" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">log</span>(df<span class="sc">$</span>Opening), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">main =</span> <span class="st">"Opening Distribution (Log)"</span>, <span class="at">xlab =</span> <span class="st">"Log(Opening)"</span>)</span>
<span id="cb62-251"><a href="#cb62-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-252"><a href="#cb62-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-253"><a href="#cb62-253" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-254"><a href="#cb62-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-255"><a href="#cb62-255" aria-hidden="true" tabindex="-1"></a>The log transformation made the data look like a normal distribution.</span>
<span id="cb62-256"><a href="#cb62-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-257"><a href="#cb62-257" aria-hidden="true" tabindex="-1"></a><span class="fu">## Running different models to get the best fit</span></span>
<span id="cb62-258"><a href="#cb62-258" aria-hidden="true" tabindex="-1"></a>Log transformed model with only the predictor and the dependant variable</span>
<span id="cb62-261"><a href="#cb62-261" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-262"><a href="#cb62-262" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the multiple regression model using the log-transformed data</span></span>
<span id="cb62-263"><a href="#cb62-263" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening), <span class="at">data =</span> df)</span>
<span id="cb62-264"><a href="#cb62-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-265"><a href="#cb62-265" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the model summary</span></span>
<span id="cb62-266"><a href="#cb62-266" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model1)</span></span>
<span id="cb62-267"><a href="#cb62-267" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model1)</span></span>
<span id="cb62-268"><a href="#cb62-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-269"><a href="#cb62-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-270"><a href="#cb62-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-271"><a href="#cb62-271" aria-hidden="true" tabindex="-1"></a>Log transformation for all continous variables.</span>
<span id="cb62-274"><a href="#cb62-274" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-275"><a href="#cb62-275" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening) <span class="sc">+</span> <span class="fu">log</span>(Budget) <span class="sc">+</span> <span class="fu">log</span>(open_th) <span class="sc">+</span> Small_Dist <span class="sc">+</span> season, <span class="at">data =</span> df)</span>
<span id="cb62-276"><a href="#cb62-276" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model2)</span></span>
<span id="cb62-277"><a href="#cb62-277" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model2)</span></span>
<span id="cb62-278"><a href="#cb62-278" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-279"><a href="#cb62-279" aria-hidden="true" tabindex="-1"></a>The R-square has significantly improved for this model. Let us try more models.</span>
<span id="cb62-280"><a href="#cb62-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-281"><a href="#cb62-281" aria-hidden="true" tabindex="-1"></a>Log transformation for only Box Office, Opening and Budget. </span>
<span id="cb62-284"><a href="#cb62-284" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-285"><a href="#cb62-285" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening) <span class="sc">+</span> <span class="fu">log</span>(Budget) <span class="sc">+</span> open_th <span class="sc">+</span> Small_Dist <span class="sc">+</span> season, <span class="at">data =</span> df)</span>
<span id="cb62-286"><a href="#cb62-286" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model3)</span></span>
<span id="cb62-287"><a href="#cb62-287" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model3)</span></span>
<span id="cb62-288"><a href="#cb62-288" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-289"><a href="#cb62-289" aria-hidden="true" tabindex="-1"></a>Log transformation for only Box Office, Opening and Budget. Removing season confounder.</span>
<span id="cb62-290"><a href="#cb62-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-293"><a href="#cb62-293" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-294"><a href="#cb62-294" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening) <span class="sc">+</span> <span class="fu">log</span>(Budget) <span class="sc">+</span> open_th <span class="sc">+</span> Small_Dist, <span class="at">data =</span> df)</span>
<span id="cb62-295"><a href="#cb62-295" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model4)</span></span>
<span id="cb62-296"><a href="#cb62-296" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model4)</span></span>
<span id="cb62-297"><a href="#cb62-297" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-298"><a href="#cb62-298" aria-hidden="true" tabindex="-1"></a>R square values are further below the previous model.</span>
<span id="cb62-299"><a href="#cb62-299" aria-hidden="true" tabindex="-1"></a>Let us try the log transformed model with only the Budget and Small_Distributor as confounders.</span>
<span id="cb62-302"><a href="#cb62-302" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-303"><a href="#cb62-303" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening) <span class="sc">+</span> <span class="fu">log</span>(Budget) <span class="sc">+</span> open_th, <span class="at">data =</span> df)</span>
<span id="cb62-304"><a href="#cb62-304" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model5)</span></span>
<span id="cb62-305"><a href="#cb62-305" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model5)</span></span>
<span id="cb62-306"><a href="#cb62-306" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-307"><a href="#cb62-307" aria-hidden="true" tabindex="-1"></a>Now, we can run a log transformed model with only the Opening and Budget.</span>
<span id="cb62-308"><a href="#cb62-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-311"><a href="#cb62-311" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-312"><a href="#cb62-312" aria-hidden="true" tabindex="-1"></a>model6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">log</span>(Opening) <span class="sc">+</span> <span class="fu">log</span>(Budget), <span class="at">data =</span> df)</span>
<span id="cb62-313"><a href="#cb62-313" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model6)</span></span>
<span id="cb62-314"><a href="#cb62-314" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model6)</span></span>
<span id="cb62-315"><a href="#cb62-315" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-316"><a href="#cb62-316" aria-hidden="true" tabindex="-1"></a>Let us run models after quadratic transformation</span>
<span id="cb62-317"><a href="#cb62-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-320"><a href="#cb62-320" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-321"><a href="#cb62-321" aria-hidden="true" tabindex="-1"></a>model_quad1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(<span class="st">`</span><span class="at">Box Office</span><span class="st">`</span>) <span class="sc">~</span> <span class="fu">poly</span>(Opening, <span class="dv">2</span>, <span class="at">raw=</span><span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">log</span>(Budget) <span class="sc">+</span> open_th <span class="sc">+</span> Small_Dist <span class="sc">+</span> season, <span class="at">data =</span> df)</span>
<span id="cb62-322"><a href="#cb62-322" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(model_quad1)</span></span>
<span id="cb62-323"><a href="#cb62-323" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(model_quad1)</span></span>
<span id="cb62-324"><a href="#cb62-324" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-325"><a href="#cb62-325" aria-hidden="true" tabindex="-1"></a><span class="fu">## Selecting a model and Interpretation of the result</span></span>
<span id="cb62-326"><a href="#cb62-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-327"><a href="#cb62-327" aria-hidden="true" tabindex="-1"></a>Now that we have multiple models, we can select the best model out of them using following criteria;</span>
<span id="cb62-328"><a href="#cb62-328" aria-hidden="true" tabindex="-1"></a>a) R-squared</span>
<span id="cb62-329"><a href="#cb62-329" aria-hidden="true" tabindex="-1"></a>b) Adjusted R-squared</span>
<span id="cb62-330"><a href="#cb62-330" aria-hidden="true" tabindex="-1"></a>c) PRESS</span>
<span id="cb62-331"><a href="#cb62-331" aria-hidden="true" tabindex="-1"></a>d) AIC (Akaike Information Criterion)</span>
<span id="cb62-332"><a href="#cb62-332" aria-hidden="true" tabindex="-1"></a>e) BIC (Bayesian Information Criterion)</span>
<span id="cb62-333"><a href="#cb62-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-334"><a href="#cb62-334" aria-hidden="true" tabindex="-1"></a>In the model selection process, we can follow the rule of thumb as, for R-squared and Adjusted R-square, higher is better while for PRESS, AIC and BIC, lower is better.</span>
<span id="cb62-335"><a href="#cb62-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-336"><a href="#cb62-336" aria-hidden="true" tabindex="-1"></a>Create a functions to get R-squared, Adjusted R-squared &amp; PRESS </span>
<span id="cb62-339"><a href="#cb62-339" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-340"><a href="#cb62-340" aria-hidden="true" tabindex="-1"></a>rsquared <span class="ot">&lt;-</span> <span class="cf">function</span>(fit) <span class="fu">summary</span>(fit)<span class="sc">$</span>r.squared</span>
<span id="cb62-341"><a href="#cb62-341" aria-hidden="true" tabindex="-1"></a>adj_rsquared <span class="ot">&lt;-</span> <span class="cf">function</span>(fit) <span class="fu">summary</span>(fit)<span class="sc">$</span>adj.r.squared</span>
<span id="cb62-342"><a href="#cb62-342" aria-hidden="true" tabindex="-1"></a>PRESS <span class="ot">&lt;-</span> <span class="cf">function</span>(fit) {</span>
<span id="cb62-343"><a href="#cb62-343" aria-hidden="true" tabindex="-1"></a>  pr <span class="ot">&lt;-</span> <span class="fu">residuals</span>(fit)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">lm.influence</span>(fit)<span class="sc">$</span>hat)</span>
<span id="cb62-344"><a href="#cb62-344" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(pr<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb62-345"><a href="#cb62-345" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb62-346"><a href="#cb62-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-347"><a href="#cb62-347" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-348"><a href="#cb62-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-349"><a href="#cb62-349" aria-hidden="true" tabindex="-1"></a>For AIC and BIC, the functions AIC() and BIC() can be used</span>
<span id="cb62-350"><a href="#cb62-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-351"><a href="#cb62-351" aria-hidden="true" tabindex="-1"></a>Now, applying the functions to model objects</span>
<span id="cb62-352"><a href="#cb62-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-355"><a href="#cb62-355" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-356"><a href="#cb62-356" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>(model1, model2, model3, model4, model5, model6, model_quad1)</span>
<span id="cb62-357"><a href="#cb62-357" aria-hidden="true" tabindex="-1"></a>model_comparison <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">models =</span> <span class="fu">c</span>(<span class="st">'model1'</span>, <span class="st">'model2'</span>, <span class="st">'model3'</span>, <span class="st">'model4'</span>, <span class="st">'model5'</span>, <span class="st">'model6'</span>, <span class="st">'model_quad1'</span>),</span>
<span id="cb62-358"><a href="#cb62-358" aria-hidden="true" tabindex="-1"></a>           <span class="at">rSquared =</span> <span class="fu">sapply</span>(models, rsquared),</span>
<span id="cb62-359"><a href="#cb62-359" aria-hidden="true" tabindex="-1"></a>           <span class="at">adj_rSquared =</span> <span class="fu">sapply</span>(models, adj_rsquared),</span>
<span id="cb62-360"><a href="#cb62-360" aria-hidden="true" tabindex="-1"></a>           <span class="at">PRESS =</span> <span class="fu">sapply</span>(models, PRESS),</span>
<span id="cb62-361"><a href="#cb62-361" aria-hidden="true" tabindex="-1"></a>           <span class="at">AIC =</span> <span class="fu">sapply</span>(models, AIC),</span>
<span id="cb62-362"><a href="#cb62-362" aria-hidden="true" tabindex="-1"></a>           <span class="at">BIC =</span> <span class="fu">sapply</span>(models, BIC)) <span class="sc">|&gt;</span></span>
<span id="cb62-363"><a href="#cb62-363" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span>
<span id="cb62-364"><a href="#cb62-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-365"><a href="#cb62-365" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-366"><a href="#cb62-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-369"><a href="#cb62-369" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-370"><a href="#cb62-370" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb62-371"><a href="#cb62-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-372"><a href="#cb62-372" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model1, model2, model3, model4, model5, model6, model_quad1, <span class="at">type =</span> <span class="st">'text'</span>)</span>
<span id="cb62-373"><a href="#cb62-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-374"><a href="#cb62-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-375"><a href="#cb62-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-376"><a href="#cb62-376" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-377"><a href="#cb62-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-378"><a href="#cb62-378" aria-hidden="true" tabindex="-1"></a>Out of all the models we ran, model3 looks as the best fit.</span>
<span id="cb62-379"><a href="#cb62-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-380"><a href="#cb62-380" aria-hidden="true" tabindex="-1"></a>The linear regression model predicts the logarithm of Box Office collections based on the logarithm of Opening weekend collections, logarithm of Budget, number of theaters the movie opened in, Small_Dist (a binary variable indicating whether the distributor is small or not), and the season in which the movie was released (Spring, Summer, or Winter). </span>
<span id="cb62-381"><a href="#cb62-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-382"><a href="#cb62-382" aria-hidden="true" tabindex="-1"></a>The coefficients of the independent variables show the direction and magnitude of their effect on the dependent variable. The p-value associated with each coefficient indicates whether the coefficient is statistically significant or not.</span>
<span id="cb62-383"><a href="#cb62-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-384"><a href="#cb62-384" aria-hidden="true" tabindex="-1"></a>The intercept coefficient is -3.845, which means that if all independent variables are zero, the model predicts that the logarithm of Box Office collections is -3.845. However, since all the independent variables are not zero in practice, this value is not meaningful.</span>
<span id="cb62-385"><a href="#cb62-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-386"><a href="#cb62-386" aria-hidden="true" tabindex="-1"></a>The coefficient of the logarithm of Opening weekend collections is 0.792, which means that a one percent increase in Opening weekend collections is associated with a 0.792 percent increase in Box Office collections.</span>
<span id="cb62-387"><a href="#cb62-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-388"><a href="#cb62-388" aria-hidden="true" tabindex="-1"></a>The coefficient of the logarithm of Budget is 0.642, which means that a one percent increase in Budget is associated with a 0.642 percent increase in Box Office collections.</span>
<span id="cb62-389"><a href="#cb62-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-390"><a href="#cb62-390" aria-hidden="true" tabindex="-1"></a>The coefficient of the number of theaters the movie opened in (open_th) is negative (-0.00068), which means that as the number of theaters increases by one, the predicted logarithm of Box Office collections decreases by 0.00068. This is something to be studied further, as it goes against our logic and expectation.</span>
<span id="cb62-391"><a href="#cb62-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-392"><a href="#cb62-392" aria-hidden="true" tabindex="-1"></a>The coefficient of Small_Dist is 0.649, which means that the Box Office collections of movies released by small distributors are 0.649 times higher than those of movies released by large distributors, holding other variables constant. This also need more detailed study.</span>
<span id="cb62-393"><a href="#cb62-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-394"><a href="#cb62-394" aria-hidden="true" tabindex="-1"></a>The coefficients associated with season indicate the difference in Box Office collections between movies released in that season and movies released in Fall (omitted reference level). For example, the coefficient of season Spring is 0.88, which means that the predicted Box Office collections of movies released in Spring are 0.88 times higher than those of movies released in Fall.</span>
<span id="cb62-395"><a href="#cb62-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-396"><a href="#cb62-396" aria-hidden="true" tabindex="-1"></a>The adjusted R-squared of the model is 0.7155, which means that 71.55% of the variation in the logarithm of Box Office collections can be explained by the independent variables in the model.</span>
<span id="cb62-397"><a href="#cb62-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-398"><a href="#cb62-398" aria-hidden="true" tabindex="-1"></a><span class="fu">## Visualising the regression model.</span></span>
<span id="cb62-399"><a href="#cb62-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-402"><a href="#cb62-402" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-403"><a href="#cb62-403" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb62-404"><a href="#cb62-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-405"><a href="#cb62-405" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the color palette</span></span>
<span id="cb62-406"><a href="#cb62-406" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"orange"</span>, <span class="st">"purple"</span>, <span class="st">"pink"</span>)</span>
<span id="cb62-407"><a href="#cb62-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-408"><a href="#cb62-408" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a blank plot with the desired layout</span></span>
<span id="cb62-409"><a href="#cb62-409" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb62-410"><a href="#cb62-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-411"><a href="#cb62-411" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through the diagnostic plots and assign colors</span></span>
<span id="cb62-412"><a href="#cb62-412" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>) {</span>
<span id="cb62-413"><a href="#cb62-413" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(model3, <span class="at">which =</span> i, <span class="at">col =</span> colors[i])</span>
<span id="cb62-414"><a href="#cb62-414" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb62-415"><a href="#cb62-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-416"><a href="#cb62-416" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-417"><a href="#cb62-417" aria-hidden="true" tabindex="-1"></a>The Scale-Location plot suggests some level of heteroskedacity. So, it is better to check if there is a serious problem of heteroskedacity,we can run Breusch-Pagan test.</span>
<span id="cb62-420"><a href="#cb62-420" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb62-421"><a href="#cb62-421" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb62-422"><a href="#cb62-422" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(model3)</span>
<span id="cb62-423"><a href="#cb62-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-424"><a href="#cb62-424" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb62-425"><a href="#cb62-425" aria-hidden="true" tabindex="-1"></a>The p-value for Breusch-Pagan test is 0.02233. This is possibly a heteroskedacity. We need to look more into this.</span>
<span id="cb62-426"><a href="#cb62-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-427"><a href="#cb62-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-428"><a href="#cb62-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-429"><a href="#cb62-429" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion:</span></span>
<span id="cb62-430"><a href="#cb62-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-431"><a href="#cb62-431" aria-hidden="true" tabindex="-1"></a>The model that we build shows that the Box Office collection of a movie is affected positively by the Opening week collection. 1 percentage of increase in Opening week collection results in 0.792 percent increase in Box office collection after taking into account the intercept(-3.845). But the Breusch-Pagan test for heteroskedacity gives a low p-value which suggests that the model is showing heteroskedacity. </span>
<span id="cb62-432"><a href="#cb62-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-433"><a href="#cb62-433" aria-hidden="true" tabindex="-1"></a>The dataset has only 200 rows out of which 96 rows were dropped as they have NA values. Also, many movies in this dataset had Box office collections much lesser than their budget. But that does not necessarily mean that those movies made a loss. In the age of online streaming platforms, many movies are making money not from Box Office only. But our study was focused only on the revenue from theatre collection. Also, in the future study, the variable transformation to address the heteroskedacity should be done. </span>
<span id="cb62-434"><a href="#cb62-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-435"><a href="#cb62-435" aria-hidden="true" tabindex="-1"></a><span class="fu">## References:</span></span>
<span id="cb62-436"><a href="#cb62-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-437"><a href="#cb62-437" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Nasir, Suphan &amp; Öcal, Figen. (2016). Film Marketing: The Impact of Publicity Activities on Demand Generation. 10.4018/978-1-5225-0143-5.ch019.</span>
<span id="cb62-438"><a href="#cb62-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-439"><a href="#cb62-439" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>*Elizabeth Cooper-Martin (1991) ,"Consumers and Movies: Some Findings on Experiential Products", in NA - Advances in Consumer Research Volume 18, eds. Rebecca H. Holman and Michael R. Solomon, Provo, UT : Association for Consumer Research, Pages: 372-378.*</span>
<span id="cb62-440"><a href="#cb62-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-441"><a href="#cb62-441" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Kaggle.com (Original dataset)</span>
<span id="cb62-442"><a href="#cb62-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-443"><a href="#cb62-443" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Wikipedia.com (Movie pages to get budget and box office collections)</span>
<span id="cb62-444"><a href="#cb62-444" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>