<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Caitlin Rowley">
<meta name="dcterms.date" content="2023-05-09">
<meta name="description" content="Homework 5">

<title>Homework 5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Homework 5">
<meta name="twitter:description" content="Homework 5">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/Rowley_Homework_5_files/figure-html/unnamed-chunk-13-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 5</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw5</div>
    <div class="quarto-category">desriptive statistics</div>
    <div class="quarto-category">probability</div>
  </div>
  </div>

<div>
  <div class="description">
    Homework 5
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Caitlin Rowley </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 9, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'magrittr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    extract</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(markdown)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggtext)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggtext' was built under R version 4.2.2</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readxl' was built under R version 4.2.2</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'alr4' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'carData' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: effects</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'effects' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'smss' was built under R version 4.2.3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Please cite as: </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MPV)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'MPV' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: KernSmooth</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>KernSmooth 2.23 loaded
Copyright M. P. Wand 1997-2009</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: randomForest</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'randomForest' was built under R version 4.2.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>randomForest 4.7-1.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Type rfNews() to see new features/changes/bug fixes.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'randomForest'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    margin</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AICcmodavg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'AICcmodavg' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'AICcmodavg'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:randomForest':

    importance</code></pre>
</div>
</div>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<p>(Data file: house.selling.price.2 from smss R package)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price.2"</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house.selling.price<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      P    S Be Ba New
1  48.5 1.10  3  1   0
2  55.0 1.01  3  2   0
3  68.0 1.45  3  2   0
4 137.0 2.40  3  3   0
5 309.4 3.30  4  3   1
6  17.5 0.40  1  1   0</code></pre>
</div>
</div>
<p>For the house.selling.price.2 data the tables below show a correlation matrix and a model fit using<br>
four predictors of selling price.</p>
<p>Regression Output (Outcome: House Price):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Estimate Std. Error t value Pr(&gt; | t| )<br>
(Intercept) -41.795 12.104 -3.453 0.001<br>
Size 64.761 5.630 11.504 0<br>
Beds -2.766 3.960 -0.698 0.487<br>
Baths 19.203 5.650 3.399 0.001<br>
New 18.984 3.873 4.902 0.00000<br>
<br>
(Hint 1: You should be able to answer A, B, C just using the tables below, although you should<br>
feel free to load the data in R and work with it if you so choose. They will be consistent with what<br>
you see on the tables.<br>
<br>
Hint 2: The p-value of a variable in a simple linear regression is the same p-value one would get<br>
from a Pearson’s correlation (cor.test). The p-value is a function of the magnitude of the correlation<br>
coefficient (the higher the coefficient, the lower the p-value) and of sample size (larger samples<br>
lead to smaller p-values). For the correlations shown in the tables, they are between variables of<br>
the same length.)</p>
<p>With these four predictors,</p>
<p>A. For backward elimination, which variable would be deleted first? Why?</p>
<ul>
<li>The first variable to be deleted using backward elimination would be BEDS because it is the least statistically significant with a p-value of 0.487.</li>
</ul>
<p>B. For forward selection, which variable would be added first? Why?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> S <span class="sc">+</span> Ba <span class="sc">+</span> Be <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price<span class="fl">.2</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ S + Ba + Be + New, data = house.selling.price.2)

Residuals:
    Min      1Q  Median      3Q     Max 
-36.212  -9.546   1.277   9.406  71.953 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -41.795     12.104  -3.453 0.000855 ***
S             64.761      5.630  11.504  &lt; 2e-16 ***
Ba            19.203      5.650   3.399 0.001019 ** 
Be            -2.766      3.960  -0.698 0.486763    
New           18.984      3.873   4.902  4.3e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.36 on 88 degrees of freedom
Multiple R-squared:  0.8689,    Adjusted R-squared:  0.8629 
F-statistic: 145.8 on 4 and 88 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>The first variable to be added using forward selection would be SIZE because it has the highest level of statistical significance with a p-value of 2e-16.</li>
</ul>
<p>C. Why do you think that BEDS has such a large P-value in the multiple regression model, even though it has a substantial correlation with PRICE?</p>
<ul>
<li>Correlation does not equal causation. So, it is possible that BEDS is highly correlated with PRICE, but that does not mean that there is a statistically significant relationship between the two variables. It is more likely that BEDS has a more statistically significant relationship with SIZE, which we know has a statistically significant relationship with PRICE.</li>
</ul>
<p>D. Using software with these four predictors, find the model that would be selected using each criterion:</p>
<ul>
<li><p>reg_1 = SIZE, BEDS, BATHS, NEW (all four predictors)</p></li>
<li><p>reg_2 = SIZE, BATHS, NEW (backwards elimination - remove BEDS)</p></li>
<li><p>reg_3 = SIZE (forward selection - add SIZE first)</p></li>
</ul>
<p>1. R2</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>reg_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> S <span class="sc">+</span> Ba <span class="sc">+</span> Be <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price<span class="fl">.2</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>reg_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> S <span class="sc">+</span> Ba <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price<span class="fl">.2</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>reg_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> S, <span class="at">data=</span>house.selling.price<span class="fl">.2</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(reg_1, reg_2, reg_3, <span class="at">type=</span><span class="st">'text'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
===========================================================================================
                                              Dependent variable:                          
                    -----------------------------------------------------------------------
                                                       P                                   
                              (1)                     (2)                     (3)          
-------------------------------------------------------------------------------------------
S                          64.761***               62.263***               75.607***       
                            (5.630)                 (4.335)                 (3.865)        
                                                                                           
Ba                         19.203***               20.072***                               
                            (5.650)                 (5.495)                                
                                                                                           
Be                          -2.766                                                         
                            (3.960)                                                        
                                                                                           
New                        18.984***               18.371***                               
                            (3.873)                 (3.761)                                
                                                                                           
Constant                  -41.795***              -47.992***              -25.194***       
                           (12.104)                 (8.209)                 (6.688)        
                                                                                           
-------------------------------------------------------------------------------------------
Observations                  93                      93                      93           
R2                           0.869                   0.868                   0.808         
Adjusted R2                  0.863                   0.864                   0.806         
Residual Std. Error    16.360 (df = 88)        16.313 (df = 89)        19.473 (df = 91)    
F Statistic         145.763*** (df = 4; 88) 195.313*** (df = 3; 89) 382.628*** (df = 1; 91)
===========================================================================================
Note:                                                           *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<ul>
<li>Based on the stargazer table above, the highest R-squared value across the three models is for reg_1, which includes all four predictors (R-squared = 0.869). This indicates a good level of fit for the model, but we should be wary of its accuracy, as R-squared does not decrease based on poor model fit.</li>
</ul>
<p>2. Adjusted R2</p>
<ul>
<li>Based on the stargazer table above, the highest adjusted R-squared value across the three models is for reg_2, which excludes BEDS as a predictor. This indicates a good level of fit for the model, and it is a more reliable measure than R-squared due to it being adjusted for the number of predictors.</li>
</ul>
<p>3. PRESS</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(reg_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28390.22</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(reg_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27860.05</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(reg_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38203.29</code></pre>
</div>
</div>
<p>We can see in the above PRESS tests that reg_2 has the lowest value, which indicates that it is the best fit model.</p>
<p>4. AIC</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>(reg_1, reg_2, reg_3)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>mod.names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'reg_1'</span>, <span class="st">'reg_2'</span>, <span class="st">'reg_3'</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">aictab</span>(<span class="at">cand.set =</span> models, <span class="at">modnames =</span> mod.names)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Model selection based on AICc:

      K   AICc Delta_AICc AICcWt Cum.Wt      LL
reg_2 5 789.83       0.00   0.71   0.71 -389.57
reg_1 6 791.60       1.77   0.29   1.00 -389.31
reg_3 3 820.41      30.59   0.00   1.00 -407.07</code></pre>
</div>
</div>
<p>We can see based on the above AIC model that reg_2 has the lowest AIC value. Therefore, because minimizing the AICc value equates to minimizing the number of unnecessary model parameters, reg_2 is the best fit.</p>
<p>5. BIC</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(reg_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 805.8181</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(reg_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 801.7996</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(reg_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 827.7417</code></pre>
</div>
</div>
<p>We can see in the above BIC models, which penalize the unnecessary addition of variables to the model, that reg_2 has the lowest value. Thus, it is the best fit model.</p>
<p>E. Explain which model you prefer and why.</p>
<p>Because we saw that reg_2, or the regression model that excluded BEDS as a predictor, was the best fit model based on the above comparison methods (adjusted R-squared, PRESS, AIC, and BIC) I would prefer this model. The comparison models for which reg_2 was deemed the best fit all account for additional predictor variables, so it is the most comprehensively significant model.</p>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<p>(Data file: trees from base R)</p>
<p>From the documentation:<br>
“This data set provides measurements of the diameter, height and volume of timber in 31 felled<br>
black cherry trees. Note that the diameter (in inches) is erroneously labeled Girth in the data. It is<br>
measured at 4 ft 6 in above the ground.”<br>
<br>
Tree volume estimation is a big deal, especially in the lumber industry. Use the trees data to build<br>
a basic model of tree volume prediction. In particular,</p>
<p>A. Fit a multiple regression model with the Volume as the outcome and Girth and Height as the explanatory variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(trees)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>tree <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Girth <span class="sc">+</span> Height, <span class="at">data=</span>trees)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Volume ~ Girth + Height, data = trees)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.4065 -2.6493 -0.2876  2.2003  8.4847 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -57.9877     8.6382  -6.713 2.75e-07 ***
Girth         4.7082     0.2643  17.816  &lt; 2e-16 ***
Height        0.3393     0.1302   2.607   0.0145 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.882 on 28 degrees of freedom
Multiple R-squared:  0.948, Adjusted R-squared:  0.9442 
F-statistic:   255 on 2 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>We can see based on this regression model that both height (p-value=0.0145) and girth (p-value&lt;2e-16) are statistically significant predictor variables. The adjusted R-squared value is also very close to 1 (0.9442), so this is a well-fitted model.</li>
</ul>
<p>B. Run regression diagnostic plots on the model. Based on the plots, do you think any of the regression assumptions is violated?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tree, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Rowley_Homework_5_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p><strong>Residuals vs.&nbsp;Fitted</strong>: In applying the Residuals vs.&nbsp;Fitted plot, we can observe a violation due to the curvature of the red line. We also see that the distribution of data points does not “bounce randomly” about the 0 line. This plot is therefore a <strong>bad fit</strong> for this regression model.</p></li>
<li><p><strong>Normal Q-Q</strong>: In applying the Normal Q-Q plot, we observe that the data points do generally fall along the 0 line and do not curve off into extremities, which is indicative of a <strong>good fit</strong> for this regression model.</p></li>
<li><p><strong>Scale-Location</strong>: In applying the Scale-Location plot, we observe heteroscedasticity across the data points as well as a non-horizontal red line. Thus, we observe a violation of this plot due to the increase and decrease in the trend line. This plot is therefore a <strong>bad fit</strong> for this regression model.</p></li>
<li><p><strong>Cook’s Distance</strong>: In applying the Cook’s Distance plot, we observe a violation due to several data points yielding a Cook’s distance value greater than 1. This plot is therefore a <strong>bad fit</strong> for this regression model.</p></li>
<li><p><strong>Residuals vs.&nbsp;Leverage</strong>: In applying the Residuals vs.&nbsp;Leverage plot, we can see that there are no data points outside of the dashed lines marked with ‘0.5.’ This plot is therefore a <strong>good fit</strong> for this regression model.</p></li>
<li><p><strong>Cook’s Distance vs.&nbsp;Leverage</strong>: In applying the Cook’s Distance vs.&nbsp;Leverage plot, we do not really observe any influential data points. This plot does not contribute any value to this regression model.</p></li>
</ul>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<p>(Data file: florida in alr R package)</p>
<p>In the 2000 election for U.S. president, the counting of votes in Florida was controversial. In Palm<br>
Beach County in south Florida, for example, voters used a so-called butterfly ballot. Some believe<br>
that the layout of the ballot caused some voters to cast votes for Buchanan when their intended<br>
choice was Gore.<br>
<br>
The data has variables for the number of votes for each candidate—Gore, Bush, and Buchanan.</p>
<p>A. Run a simple linear regression model where the Buchanan vote is the outcome and the Bush vote is the explanatory variable. Produce the regression diagnostic plots. Is Palm Beach County an outlier based on the diagnostic plots? Why or why not?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(florida)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>vote <span class="ot">&lt;-</span> <span class="fu">lm</span>(Buchanan <span class="sc">~</span> Bush, <span class="at">data=</span>florida)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vote)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Buchanan ~ Bush, data = florida)

Residuals:
    Min      1Q  Median      3Q     Max 
-907.50  -46.10  -29.19   12.26 2610.19 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.529e+01  5.448e+01   0.831    0.409    
Bush        4.917e-03  7.644e-04   6.432 1.73e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 353.9 on 65 degrees of freedom
Multiple R-squared:  0.3889,    Adjusted R-squared:  0.3795 
F-statistic: 41.37 on 1 and 65 DF,  p-value: 1.727e-08</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vote, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Rowley_Homework_5_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Based on the above diagnostic plots, Palm Beach appears to be an outlier in each example. Palm Beach violates the regression assumptions in all plots except for the Cook’s Distance vs Leverage plot, which we know is not particularly informative.</li>
</ul>
<p>B. Take the log of both variables (Bush vote and Buchanan Vote) and repeat the analysis in (A.) Does your findings change?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>log_florida <span class="ot">&lt;-</span> florida <span class="sc">%&gt;%</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(<span class="at">log_Bush=</span><span class="fu">log</span>(Bush)) <span class="sc">%&gt;%</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(<span class="at">log_Buchanan=</span><span class="fu">log</span>(Buchanan))</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>log_vote <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Buchanan <span class="sc">~</span> log_Bush, <span class="at">data=</span>log_florida)</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_vote)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Buchanan ~ log_Bush, data = log_florida)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.96075 -0.25949  0.01282  0.23826  1.66564 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.57712    0.38919  -6.622 8.04e-09 ***
log_Bush     0.75772    0.03936  19.251  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4673 on 65 degrees of freedom
Multiple R-squared:  0.8508,    Adjusted R-squared:  0.8485 
F-statistic: 370.6 on 1 and 65 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(log_vote, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Rowley_Homework_5_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>After logging both variables, we can see that Palm Beach is still an outlier in each of the diagnostic plots, and it results in the same regression assumption violations (though to a slightly lesser degree).</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb74" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 5"</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Caitlin Rowley"</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Homework 5"</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/09/2023"</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw5</span></span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - desriptive statistics </span></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - probability</span></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-21"><a href="#cb74-21" aria-hidden="true" tabindex="-1"></a><span class="co"># load libraries</span></span>
<span id="cb74-22"><a href="#cb74-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb74-23"><a href="#cb74-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb74-24"><a href="#cb74-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb74-25"><a href="#cb74-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb74-26"><a href="#cb74-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(markdown)</span>
<span id="cb74-27"><a href="#cb74-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggtext)</span>
<span id="cb74-28"><a href="#cb74-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb74-29"><a href="#cb74-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb74-30"><a href="#cb74-30" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb74-31"><a href="#cb74-31" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb74-32"><a href="#cb74-32" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MPV)</span>
<span id="cb74-33"><a href="#cb74-33" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AICcmodavg)</span>
<span id="cb74-34"><a href="#cb74-34" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-35"><a href="#cb74-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-36"><a href="#cb74-36" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 1</span></span>
<span id="cb74-37"><a href="#cb74-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-38"><a href="#cb74-38" aria-hidden="true" tabindex="-1"></a>(Data file: house.selling.price.2 from smss R package)</span>
<span id="cb74-39"><a href="#cb74-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-42"><a href="#cb74-42" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-43"><a href="#cb74-43" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price.2"</span>)</span>
<span id="cb74-44"><a href="#cb74-44" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house.selling.price<span class="fl">.2</span>)</span>
<span id="cb74-45"><a href="#cb74-45" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-46"><a href="#cb74-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-47"><a href="#cb74-47" aria-hidden="true" tabindex="-1"></a>| For the house.selling.price.2 data the tables below show a correlation matrix and a model fit using</span>
<span id="cb74-48"><a href="#cb74-48" aria-hidden="true" tabindex="-1"></a>| four predictors of selling price.</span>
<span id="cb74-49"><a href="#cb74-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-50"><a href="#cb74-50" aria-hidden="true" tabindex="-1"></a>| Regression Output (Outcome: House Price):</span>
<span id="cb74-51"><a href="#cb74-51" aria-hidden="true" tabindex="-1"></a>|                           Estimate Std. Error t value Pr(<span class="sc">\&gt;</span> \| t\| )</span>
<span id="cb74-52"><a href="#cb74-52" aria-hidden="true" tabindex="-1"></a>| (Intercept) -41.795 12.104 -3.453 0.001</span>
<span id="cb74-53"><a href="#cb74-53" aria-hidden="true" tabindex="-1"></a>| Size 64.761 5.630 11.504 0</span>
<span id="cb74-54"><a href="#cb74-54" aria-hidden="true" tabindex="-1"></a>| Beds -2.766 3.960 -0.698 0.487</span>
<span id="cb74-55"><a href="#cb74-55" aria-hidden="true" tabindex="-1"></a>| Baths 19.203 5.650 3.399 0.001</span>
<span id="cb74-56"><a href="#cb74-56" aria-hidden="true" tabindex="-1"></a>| New 18.984 3.873 4.902 0.00000</span>
<span id="cb74-57"><a href="#cb74-57" aria-hidden="true" tabindex="-1"></a>| </span>
<span id="cb74-58"><a href="#cb74-58" aria-hidden="true" tabindex="-1"></a>| (Hint 1: You should be able to answer A, B, C just using the tables below, although you should</span>
<span id="cb74-59"><a href="#cb74-59" aria-hidden="true" tabindex="-1"></a>| feel free to load the data in R and work with it if you so choose. They will be consistent with what</span>
<span id="cb74-60"><a href="#cb74-60" aria-hidden="true" tabindex="-1"></a>| you see on the tables.</span>
<span id="cb74-61"><a href="#cb74-61" aria-hidden="true" tabindex="-1"></a>| </span>
<span id="cb74-62"><a href="#cb74-62" aria-hidden="true" tabindex="-1"></a>| Hint 2: The p-value of a variable in a simple linear regression is the same p-value one would get</span>
<span id="cb74-63"><a href="#cb74-63" aria-hidden="true" tabindex="-1"></a>| from a Pearson's correlation (cor.test). The p-value is a function of the magnitude of the correlation</span>
<span id="cb74-64"><a href="#cb74-64" aria-hidden="true" tabindex="-1"></a>| coefficient (the higher the coefficient, the lower the p-value) and of sample size (larger samples</span>
<span id="cb74-65"><a href="#cb74-65" aria-hidden="true" tabindex="-1"></a>| lead to smaller p-values). For the correlations shown in the tables, they are between variables of</span>
<span id="cb74-66"><a href="#cb74-66" aria-hidden="true" tabindex="-1"></a>| the same length.)</span>
<span id="cb74-67"><a href="#cb74-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-68"><a href="#cb74-68" aria-hidden="true" tabindex="-1"></a>With these four predictors,</span>
<span id="cb74-69"><a href="#cb74-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-70"><a href="#cb74-70" aria-hidden="true" tabindex="-1"></a>A. For backward elimination, which variable would be deleted first? Why?</span>
<span id="cb74-71"><a href="#cb74-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-72"><a href="#cb74-72" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The first variable to be deleted using backward elimination would be BEDS because it is the least statistically significant with a p-value of 0.487.</span>
<span id="cb74-73"><a href="#cb74-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-74"><a href="#cb74-74" aria-hidden="true" tabindex="-1"></a>B. For forward selection, which variable would be added first? Why?</span>
<span id="cb74-75"><a href="#cb74-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-78"><a href="#cb74-78" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-79"><a href="#cb74-79" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> S <span class="sc">+</span> Ba <span class="sc">+</span> Be <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price<span class="fl">.2</span>)</span>
<span id="cb74-80"><a href="#cb74-80" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span>
<span id="cb74-81"><a href="#cb74-81" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-82"><a href="#cb74-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-83"><a href="#cb74-83" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The first variable to be added using forward selection would be SIZE because it has the highest level of statistical significance with a p-value of 2e-16.</span>
<span id="cb74-84"><a href="#cb74-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-85"><a href="#cb74-85" aria-hidden="true" tabindex="-1"></a>C. Why do you think that BEDS has such a large P-value in the multiple regression model, even though it has a substantial correlation with PRICE?</span>
<span id="cb74-86"><a href="#cb74-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-87"><a href="#cb74-87" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Correlation does not equal causation. So, it is possible that BEDS is highly correlated with PRICE, but that does not mean that there is a statistically significant relationship between the two variables. It is more likely that BEDS has a more statistically significant relationship with SIZE, which we know has a statistically significant relationship with PRICE.</span>
<span id="cb74-88"><a href="#cb74-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-89"><a href="#cb74-89" aria-hidden="true" tabindex="-1"></a>D. Using software with these four predictors, find the model that would be selected using each criterion:</span>
<span id="cb74-90"><a href="#cb74-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-91"><a href="#cb74-91" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>reg_1 = SIZE, BEDS, BATHS, NEW (all four predictors)</span>
<span id="cb74-92"><a href="#cb74-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-93"><a href="#cb74-93" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>reg_2 = SIZE, BATHS, NEW (backwards elimination - remove BEDS)</span>
<span id="cb74-94"><a href="#cb74-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-95"><a href="#cb74-95" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>reg_3 = SIZE (forward selection - add SIZE first)</span>
<span id="cb74-96"><a href="#cb74-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-97"><a href="#cb74-97" aria-hidden="true" tabindex="-1"></a>1<span class="sc">\.</span> R2</span>
<span id="cb74-98"><a href="#cb74-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-101"><a href="#cb74-101" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-102"><a href="#cb74-102" aria-hidden="true" tabindex="-1"></a>reg_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> S <span class="sc">+</span> Ba <span class="sc">+</span> Be <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price<span class="fl">.2</span>)</span>
<span id="cb74-103"><a href="#cb74-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-104"><a href="#cb74-104" aria-hidden="true" tabindex="-1"></a>reg_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> S <span class="sc">+</span> Ba <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price<span class="fl">.2</span>)</span>
<span id="cb74-105"><a href="#cb74-105" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb74-106"><a href="#cb74-106" aria-hidden="true" tabindex="-1"></a>reg_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(P <span class="sc">~</span> S, <span class="at">data=</span>house.selling.price<span class="fl">.2</span>)</span>
<span id="cb74-107"><a href="#cb74-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-108"><a href="#cb74-108" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(reg_1, reg_2, reg_3, <span class="at">type=</span><span class="st">'text'</span>)</span>
<span id="cb74-109"><a href="#cb74-109" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-110"><a href="#cb74-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-111"><a href="#cb74-111" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Based on the stargazer table above, the highest R-squared value across the three models is for reg_1, which includes all four predictors (R-squared = 0.869). This indicates a good level of fit for the model, but we should be wary of its accuracy, as R-squared does not decrease based on poor model fit.</span>
<span id="cb74-112"><a href="#cb74-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-113"><a href="#cb74-113" aria-hidden="true" tabindex="-1"></a>2<span class="sc">\.</span> Adjusted R2</span>
<span id="cb74-114"><a href="#cb74-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-115"><a href="#cb74-115" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Based on the stargazer table above, the highest adjusted R-squared value across the three models is for reg_2, which excludes BEDS as a predictor. This indicates a good level of fit for the model, and it is a more reliable measure than R-squared due to it being adjusted for the number of predictors.</span>
<span id="cb74-116"><a href="#cb74-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-117"><a href="#cb74-117" aria-hidden="true" tabindex="-1"></a>3<span class="sc">\.</span> PRESS</span>
<span id="cb74-118"><a href="#cb74-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-121"><a href="#cb74-121" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-122"><a href="#cb74-122" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(reg_1)</span>
<span id="cb74-123"><a href="#cb74-123" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-124"><a href="#cb74-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-127"><a href="#cb74-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-128"><a href="#cb74-128" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(reg_2)</span>
<span id="cb74-129"><a href="#cb74-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-130"><a href="#cb74-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-133"><a href="#cb74-133" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-134"><a href="#cb74-134" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(reg_3)</span>
<span id="cb74-135"><a href="#cb74-135" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-136"><a href="#cb74-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-137"><a href="#cb74-137" aria-hidden="true" tabindex="-1"></a>We can see in the above PRESS tests that reg_2 has the lowest value, which indicates that it is the best fit model.</span>
<span id="cb74-138"><a href="#cb74-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-139"><a href="#cb74-139" aria-hidden="true" tabindex="-1"></a>4<span class="sc">\.</span> AIC</span>
<span id="cb74-140"><a href="#cb74-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-143"><a href="#cb74-143" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-144"><a href="#cb74-144" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>(reg_1, reg_2, reg_3)</span>
<span id="cb74-145"><a href="#cb74-145" aria-hidden="true" tabindex="-1"></a>mod.names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'reg_1'</span>, <span class="st">'reg_2'</span>, <span class="st">'reg_3'</span>)</span>
<span id="cb74-146"><a href="#cb74-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-147"><a href="#cb74-147" aria-hidden="true" tabindex="-1"></a><span class="fu">aictab</span>(<span class="at">cand.set =</span> models, <span class="at">modnames =</span> mod.names)</span>
<span id="cb74-148"><a href="#cb74-148" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-149"><a href="#cb74-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-150"><a href="#cb74-150" aria-hidden="true" tabindex="-1"></a>We can see based on the above AIC model that reg_2 has the lowest AIC value. Therefore, because minimizing the AICc value equates to minimizing the number of unnecessary model parameters, reg_2 is the best fit.</span>
<span id="cb74-151"><a href="#cb74-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-152"><a href="#cb74-152" aria-hidden="true" tabindex="-1"></a>5<span class="sc">\.</span> BIC</span>
<span id="cb74-153"><a href="#cb74-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-156"><a href="#cb74-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-157"><a href="#cb74-157" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(reg_1)</span>
<span id="cb74-158"><a href="#cb74-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-159"><a href="#cb74-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-162"><a href="#cb74-162" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-163"><a href="#cb74-163" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(reg_2)</span>
<span id="cb74-164"><a href="#cb74-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-165"><a href="#cb74-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-168"><a href="#cb74-168" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-169"><a href="#cb74-169" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(reg_3)</span>
<span id="cb74-170"><a href="#cb74-170" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-171"><a href="#cb74-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-172"><a href="#cb74-172" aria-hidden="true" tabindex="-1"></a>We can see in the above BIC models, which penalize the unnecessary addition of variables to the model, that reg_2 has the lowest value. Thus, it is the best fit model.</span>
<span id="cb74-173"><a href="#cb74-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-174"><a href="#cb74-174" aria-hidden="true" tabindex="-1"></a>E. Explain which model you prefer and why.</span>
<span id="cb74-175"><a href="#cb74-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-176"><a href="#cb74-176" aria-hidden="true" tabindex="-1"></a>Because we saw that reg_2, or the regression model that excluded BEDS as a predictor, was the best fit model based on the above comparison methods (adjusted R-squared, PRESS, AIC, and BIC) I would prefer this model. The comparison models for which reg_2 was deemed the best fit all account for additional predictor variables, so it is the most comprehensively significant model.</span>
<span id="cb74-177"><a href="#cb74-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-178"><a href="#cb74-178" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 2</span></span>
<span id="cb74-179"><a href="#cb74-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-180"><a href="#cb74-180" aria-hidden="true" tabindex="-1"></a>(Data file: trees from base R)</span>
<span id="cb74-181"><a href="#cb74-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-182"><a href="#cb74-182" aria-hidden="true" tabindex="-1"></a>| From the documentation:</span>
<span id="cb74-183"><a href="#cb74-183" aria-hidden="true" tabindex="-1"></a>| "This data set provides measurements of the diameter, height and volume of timber in 31 felled</span>
<span id="cb74-184"><a href="#cb74-184" aria-hidden="true" tabindex="-1"></a>| black cherry trees. Note that the diameter (in inches) is erroneously labeled Girth in the data. It is</span>
<span id="cb74-185"><a href="#cb74-185" aria-hidden="true" tabindex="-1"></a>| measured at 4 ft 6 in above the ground."</span>
<span id="cb74-186"><a href="#cb74-186" aria-hidden="true" tabindex="-1"></a>| </span>
<span id="cb74-187"><a href="#cb74-187" aria-hidden="true" tabindex="-1"></a>| Tree volume estimation is a big deal, especially in the lumber industry. Use the trees data to build</span>
<span id="cb74-188"><a href="#cb74-188" aria-hidden="true" tabindex="-1"></a>| a basic model of tree volume prediction. In particular,</span>
<span id="cb74-189"><a href="#cb74-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-190"><a href="#cb74-190" aria-hidden="true" tabindex="-1"></a>A. Fit a multiple regression model with the Volume as the outcome and Girth and Height as the explanatory variables.</span>
<span id="cb74-191"><a href="#cb74-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-194"><a href="#cb74-194" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-195"><a href="#cb74-195" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(trees)</span>
<span id="cb74-196"><a href="#cb74-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-197"><a href="#cb74-197" aria-hidden="true" tabindex="-1"></a>tree <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Girth <span class="sc">+</span> Height, <span class="at">data=</span>trees)</span>
<span id="cb74-198"><a href="#cb74-198" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tree)</span>
<span id="cb74-199"><a href="#cb74-199" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-200"><a href="#cb74-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-201"><a href="#cb74-201" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>We can see based on this regression model that both height (p-value=0.0145) and girth (p-value<span class="sc">\&lt;</span>2e-16) are statistically significant predictor variables. The adjusted R-squared value is also very close to 1 (0.9442), so this is a well-fitted model.</span>
<span id="cb74-202"><a href="#cb74-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-203"><a href="#cb74-203" aria-hidden="true" tabindex="-1"></a>B. Run regression diagnostic plots on the model. Based on the plots, do you think any of the regression assumptions is violated?</span>
<span id="cb74-204"><a href="#cb74-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-207"><a href="#cb74-207" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-208"><a href="#cb74-208" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb74-209"><a href="#cb74-209" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tree, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb74-210"><a href="#cb74-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-211"><a href="#cb74-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-212"><a href="#cb74-212" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Residuals vs. Fitted**: In applying the Residuals vs. Fitted plot, we can observe a violation due to the curvature of the red line. We also see that the distribution of data points does not "bounce randomly" about the 0 line. This plot is therefore a **bad fit** for this regression model.</span>
<span id="cb74-213"><a href="#cb74-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-214"><a href="#cb74-214" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Normal Q-Q**: In applying the Normal Q-Q plot, we observe that the data points do generally fall along the 0 line and do not curve off into extremities, which is indicative of a **good fit** for this regression model.</span>
<span id="cb74-215"><a href="#cb74-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-216"><a href="#cb74-216" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Scale-Location**: In applying the Scale-Location plot, we observe heteroscedasticity across the data points as well as a non-horizontal red line. Thus, we observe a violation of this plot due to the increase and decrease in the trend line. This plot is therefore a **bad fit** for this regression model.</span>
<span id="cb74-217"><a href="#cb74-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-218"><a href="#cb74-218" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Cook's Distance**: In applying the Cook's Distance plot, we observe a violation due to several data points yielding a Cook's distance value greater than 1. This plot is therefore a **bad fit** for this regression model.</span>
<span id="cb74-219"><a href="#cb74-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-220"><a href="#cb74-220" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Residuals vs. Leverage**: In applying the Residuals vs. Leverage plot, we can see that there are no data points outside of the dashed lines marked with '0.5.' This plot is therefore a **good fit** for this regression model.</span>
<span id="cb74-221"><a href="#cb74-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-222"><a href="#cb74-222" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Cook's Distance vs. Leverage**: In applying the Cook's Distance vs. Leverage plot, we do not really observe any influential data points. This plot does not contribute any value to this regression model.</span>
<span id="cb74-223"><a href="#cb74-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-224"><a href="#cb74-224" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 3</span></span>
<span id="cb74-225"><a href="#cb74-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-226"><a href="#cb74-226" aria-hidden="true" tabindex="-1"></a>(Data file: florida in alr R package)</span>
<span id="cb74-227"><a href="#cb74-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-228"><a href="#cb74-228" aria-hidden="true" tabindex="-1"></a>| In the 2000 election for U.S. president, the counting of votes in Florida was controversial. In Palm</span>
<span id="cb74-229"><a href="#cb74-229" aria-hidden="true" tabindex="-1"></a>| Beach County in south Florida, for example, voters used a so-called butterfly ballot. Some believe</span>
<span id="cb74-230"><a href="#cb74-230" aria-hidden="true" tabindex="-1"></a>| that the layout of the ballot caused some voters to cast votes for Buchanan when their intended</span>
<span id="cb74-231"><a href="#cb74-231" aria-hidden="true" tabindex="-1"></a>| choice was Gore.</span>
<span id="cb74-232"><a href="#cb74-232" aria-hidden="true" tabindex="-1"></a>| </span>
<span id="cb74-233"><a href="#cb74-233" aria-hidden="true" tabindex="-1"></a>| The data has variables for the number of votes for each candidate---Gore, Bush, and Buchanan.</span>
<span id="cb74-234"><a href="#cb74-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-235"><a href="#cb74-235" aria-hidden="true" tabindex="-1"></a>A. Run a simple linear regression model where the Buchanan vote is the outcome and the Bush vote is the explanatory variable. Produce the regression diagnostic plots. Is Palm Beach County an outlier based on the diagnostic plots? Why or why not?</span>
<span id="cb74-236"><a href="#cb74-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-239"><a href="#cb74-239" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-240"><a href="#cb74-240" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(florida)</span>
<span id="cb74-241"><a href="#cb74-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-242"><a href="#cb74-242" aria-hidden="true" tabindex="-1"></a>vote <span class="ot">&lt;-</span> <span class="fu">lm</span>(Buchanan <span class="sc">~</span> Bush, <span class="at">data=</span>florida)</span>
<span id="cb74-243"><a href="#cb74-243" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vote)</span>
<span id="cb74-244"><a href="#cb74-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-245"><a href="#cb74-245" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb74-246"><a href="#cb74-246" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vote, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb74-247"><a href="#cb74-247" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-248"><a href="#cb74-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-249"><a href="#cb74-249" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Based on the above diagnostic plots, Palm Beach appears to be an outlier in each example. Palm Beach violates the regression assumptions in all plots except for the Cook's Distance vs Leverage plot, which we know is not particularly informative.</span>
<span id="cb74-250"><a href="#cb74-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-251"><a href="#cb74-251" aria-hidden="true" tabindex="-1"></a>B. Take the log of both variables (Bush vote and Buchanan Vote) and repeat the analysis in (A.) Does your findings change?</span>
<span id="cb74-252"><a href="#cb74-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-255"><a href="#cb74-255" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-256"><a href="#cb74-256" aria-hidden="true" tabindex="-1"></a>log_florida <span class="ot">&lt;-</span> florida <span class="sc">%&gt;%</span></span>
<span id="cb74-257"><a href="#cb74-257" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(<span class="at">log_Bush=</span><span class="fu">log</span>(Bush)) <span class="sc">%&gt;%</span></span>
<span id="cb74-258"><a href="#cb74-258" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(<span class="at">log_Buchanan=</span><span class="fu">log</span>(Buchanan))</span>
<span id="cb74-259"><a href="#cb74-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-260"><a href="#cb74-260" aria-hidden="true" tabindex="-1"></a>log_vote <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Buchanan <span class="sc">~</span> log_Bush, <span class="at">data=</span>log_florida)</span>
<span id="cb74-261"><a href="#cb74-261" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_vote)</span>
<span id="cb74-262"><a href="#cb74-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-263"><a href="#cb74-263" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb74-264"><a href="#cb74-264" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(log_vote, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb74-265"><a href="#cb74-265" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-266"><a href="#cb74-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-267"><a href="#cb74-267" aria-hidden="true" tabindex="-1"></a>After logging both variables, we can see that Palm Beach is still an outlier in each of the diagnostic plots, and it results in the same regression assumption violations (though to a slightly lesser degree).</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>