<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Caitlin Rowley">
<meta name="dcterms.date" content="2023-04-11">
<meta name="description" content="Homework 3">

<title>Homework 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta name="twitter:title" content="Homework 3">
<meta name="twitter:description" content="Homework 3">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/Rowley_Homework_3_files/figure-html/unnamed-chunk-3-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 3</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw3</div>
    <div class="quarto-category">desriptive statistics</div>
    <div class="quarto-category">probability</div>
  </div>
  </div>

<div>
  <div class="description">
    Homework 3
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Caitlin Rowley </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 11, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'magrittr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    extract</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(markdown)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggtext)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggtext' was built under R version 4.2.2</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readxl' was built under R version 4.2.2</code></pre>
</div>
</div>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<p>United Nations (Data file: UN11in alr4) The data in the file UN11 contains several variables,<br>
including ppgdp, the gross national product per person in U.S. dollars, and fertility, the birth<br>
rate per 1000 females, both from the year 2009. The data are for 199 localities, mostly UN<br>
member countries, but also other areas such as Hong Kong that are not independent countries.<br>
The data were collected from the United Nations (2011). We will study the dependence of<br>
fertility on ppgdp.<br>
(a) Identify the predictor and the response.<br>
(b) Draw the scatterplot of fertility on the vertical axis versus ppgdp on the horizontal axis<br>
and summarize the information in this graph. Does a straight-line mean function seem to<br>
be plausible for a summary of this graph?<br>
(c) Draw the scatterplot of log(fertility) versus log(ppgdp) using natural logarithms. Does<br>
the simple linear regression model seem plausible for a summary of this graph? If you use<br>
a different base of logarithms, the shape of the graph won’t change, but the values on the<br>
axes will change.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in data:</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>UN11 <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">url</span>(<span class="st">'https://github.com/omerfyalcin/colab-data/blob/main/UN.rds?raw=true'</span>))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(UN11)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                  region  group fertility   ppgdp lifeExpF pctUrban
Afghanistan         Asia  other     5.968   499.0    49.49       23
Albania           Europe  other     1.525  3677.2    80.40       53
Algeria           Africa africa     2.142  4473.0    75.00       67
American Samoa      &lt;NA&gt;   &lt;NA&gt;        NA      NA       NA       NA
Angola            Africa africa     5.135  4321.9    53.17       59
Anguilla       Caribbean  other     2.000 13750.1    81.10      100
               infantMortality
Afghanistan          124.53500
Albania               16.56100
Algeria               21.45800
American Samoa        11.29389
Angola                96.19100
Anguilla                    NA</code></pre>
</div>
</div>
<section id="a" class="level4">
<h4 class="anchored" data-anchor-id="a">A)</h4>
<p>In studying the dependence of fertility on GDP, fertility is the predictor and GDP is the response.</p>
</section>
<section id="b" class="level4">
<h4 class="anchored" data-anchor-id="b">B)</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate scatterplot:</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>scatter_1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(UN11, <span class="fu">aes</span>(<span class="at">x=</span>ppgdp, <span class="at">y=</span>fertility)) <span class="sc">+</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="at">color=</span><span class="st">"black"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>scatter_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 14 rows containing missing values (geom_point).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Rowley_Homework_3_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># with linear trend</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>scatter_2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(UN11, <span class="fu">aes</span>(<span class="at">x=</span>ppgdp, <span class="at">y=</span>fertility)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">TRUE</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>scatter_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 14 rows containing non-finite values (stat_smooth).
Removed 14 rows containing missing values (geom_point).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Rowley_Homework_3_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In viewing this scatterplot, we can see that higher rates of birth correlates with lower per-person GPD. A straight-line mean function does not seem plausible for this graph, as the line extends far beyond the range of data points.</p>
</section>
<section id="c" class="level4">
<h4 class="anchored" data-anchor-id="c">C)</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate scatterplot using natural logarithms:</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>scatter_3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(UN11, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(ppgdp), <span class="at">y=</span><span class="fu">log</span>(fertility))) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">TRUE</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>scatter_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 14 rows containing non-finite values (stat_smooth).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 14 rows containing missing values (geom_point).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Rowley_Homework_3_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Using natural logarithms, we see a much more plausible summary for this graph.</p>
</section>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<p>Annual income, in dollars, is an explanatory variable in a regression analysis. For a British<br>
version of the report on the analysis, all responses are converted to British pounds sterling (1 pound<br>
equals about 1.33 dollars, as of 2016).<br>
(a) How, if at all, does the slope of the prediction equation change?<br>
(b) How, if at all, does the correlation change?</p>
<section id="a-1" class="level4">
<h4 class="anchored" data-anchor-id="a-1">A)</h4>
<p>The slope of the prediction will need to be divided by 1.33 to account for the conversion to British pounds.</p>
</section>
<section id="b-1" class="level4">
<h4 class="anchored" data-anchor-id="b-1">B)</h4>
<p>The correlation will not change.</p>
</section>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<p>Water runoff in the Sierras (Data file: water in alr4) Can Southern California’s water<br>
supply in future years be predicted from past data? One factor affecting water availability is stream<br>
runoff. If runoff could be predicted, engineers, planners, and policy makers could do their jobs<br>
more efficiently. The data file contains 43 years’ worth of precipitation measurements taken at six<br>
sites in the Sierra Nevada mountains (labeled APMAM, APSAB, APSLAKE, OPBPC, OPRC, and<br>
OPSLAKE) and stream runoff volume at a site near Bishop, California, labeled BSAAM. Draw<br>
the scatterplot matrix for these data and summarize the information available from these<br>
plots. (Hint: Use the pairs() function.)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'alr4' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'carData' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: effects</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'effects' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'alr4'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked _by_ '.GlobalEnv':

    UN11</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(water)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Year APMAM APSAB APSLAKE OPBPC  OPRC OPSLAKE  BSAAM
1 1948  9.13  3.58    3.91  4.10  7.43    6.47  54235
2 1949  5.28  4.82    5.20  7.55 11.11   10.26  67567
3 1950  4.20  3.77    3.67  9.52 12.20   11.35  66161
4 1951  4.60  4.46    3.93 11.14 15.15   11.13  68094
5 1952  7.15  4.99    4.88 16.34 20.05   22.81 107080
6 1953  9.70  5.65    4.91  8.88  8.15    7.41  67594</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(water)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Rowley_Homework_3_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on the scatterplot matrix, stream runoff near Bishop, California appears to be correlated with precipitation at “O” sites, but not with “A” sites or year.</p>
</section>
<section id="question-4" class="level3">
<h3 class="anchored" data-anchor-id="question-4">Question 4</h3>
<p>Professor ratings (Data file: Rateprof in alr4) In the website and online forum<br>
RateMyProfessors.com, students rate and comment on their instructors. Launched in 1999, the site<br>
includes millions of ratings on thousands of instructors. The data file includes the summaries of<br>
the ratings of 364 instructors at a large campus in the Midwest (Bleske-Rechek and Fritsch, 2011).<br>
Each instructor included in the data had at least 10 ratings over a several year period. Students<br>
provided ratings of 1–5 on quality, helpfulness, clarity, easiness of instructor’s courses, and<br>
raterInterest in the subject matter covered in the instructor’s courses. The data file provides the<br>
averages of these five ratings. Create a scatterplot matrix of these five variables. Provide a<br>
brief description of the relationships between the five ratings.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Rateprof)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  gender numYears numRaters numCourses pepper discipline              dept
1   male        7        11          5     no        Hum           English
2   male        6        11          5     no        Hum Religious Studies
3   male       10        43          2     no        Hum               Art
4   male       11        24          5     no        Hum           English
5   male       11        19          7     no        Hum           Spanish
6   male       10        15          9     no        Hum           Spanish
   quality helpfulness  clarity easiness raterInterest sdQuality sdHelpfulness
1 4.636364    4.636364 4.636364 4.818182      3.545455 0.5518564     0.6741999
2 4.318182    4.545455 4.090909 4.363636      4.000000 0.9020179     0.9341987
3 4.790698    4.720930 4.860465 4.604651      3.432432 0.4529343     0.6663898
4 4.250000    4.458333 4.041667 2.791667      3.181818 0.9325048     0.9315329
5 4.684211    4.684211 4.684211 4.473684      4.214286 0.6500112     0.8200699
6 4.233333    4.266667 4.200000 4.533333      3.916667 0.8632717     1.0327956
  sdClarity sdEasiness sdRaterInterest
1 0.5045250  0.4045199       1.1281521
2 0.9438798  0.5045250       1.0744356
3 0.4129681  0.5407021       1.2369438
4 0.9990938  0.5882300       1.3322506
5 0.5823927  0.6117753       0.9749613
6 0.7745967  0.6399405       0.6685579</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(Rateprof[,<span class="dv">8</span><span class="sc">:</span><span class="dv">12</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Rowley_Homework_3_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Quality</strong>: Based on the scatterplot matrix, we can see that there is a positive correlation between quality and helpfulness, as well as between quality and clarity (though we see one outlier in this data set that represents a comparitively higher rate of clarity linked with a lower rate of quality). There is a slightly positive correlation between quality and easiness, but no definitive correlation between quality and rater interest.</p>
<p><strong>Helpfulness</strong>: Based on the scatterplot matrix, we see (as mentioned) a positive correlation between helpfulness and quality, as well as between helpfulness and clarity (though the spread of data points is slightly larger). Similar to quality, there is a slightly positive correlation between helpfulness and easiness, but no definitive correlation between helpfulness and rater interest.</p>
<p><strong>Clarity</strong>: Based on the scatterplot, we see (as mentioned) a positive correlation between clarity and quality, as well as between clarity and helpfulness (though the spread of data points is slightly larger). Similarly to quality and helpfulness, there is no definitive correlation between clarity and easiness or clarity and rater interest.</p>
<p><strong>Easiness</strong>: There are slightly positive correlations between easiness and quality, easiness and helpfulness, and easiness and clarity. There is no definitive correlation between easiness and rater interest.</p>
<p><strong>Rater Interest</strong>: There are no definitive correlations between rater interest and any of the remaining four variables.</p>
<p>Overall, quality, helpfulness, and clarity provide more insight related to professor rating than easiness and rater interest.</p>
</section>
<section id="question-5" class="level3">
<h3 class="anchored" data-anchor-id="question-5">Question 5</h3>
<p>For the student.survey data file in the smss package, conduct regression analyses relating<br>
(by convention, y denotes the outcome variable, x denotes the explanatory variable)<br>
(i) y = political ideology and x = religiosity,<br>
(ii) y = high school GPA and x = hours of TV watching.<br>
(You can use ?student.survey in the R console, after loading the package, to see what each variable<br>
means.)<br>
(a) Graphically portray how the explanatory variable relates to the outcome variable in<br>
each of the two cases<br>
(b) Summarize and interpret results of inferential analyses.</p>
<section id="a-2" class="level4">
<h4 class="anchored" data-anchor-id="a-2">A)</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'smss' was built under R version 4.2.3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(student.survey)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(student.survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  subj ge ag  hi  co   dh   dr tv sp ne ah    ve pa           pi           re
1    1  m 32 2.2 3.5    0  5.0  3  5  0  0 FALSE  r conservative   most weeks
2    2  f 23 2.1 3.5 1200  0.3 15  7  5  6 FALSE  d      liberal occasionally
3    3  f 27 3.3 3.0 1300  1.5  0  4  3  0 FALSE  d      liberal   most weeks
4    4  f 35 3.5 3.2 1500  8.0  5  5  6  3 FALSE  i     moderate occasionally
5    5  m 23 3.1 3.5 1600 10.0  6  6  3  0 FALSE  i very liberal        never
6    6  m 39 3.5 3.5  350  3.0  4  5  7  0 FALSE  d      liberal occasionally
     ab    aa    ld
1 FALSE FALSE FALSE
2 FALSE FALSE    NA
3 FALSE FALSE    NA
4 FALSE FALSE FALSE
5 FALSE FALSE FALSE
6 FALSE FALSE    NA</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>survey <span class="ot">&lt;-</span> student.survey <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"poli_ideo"</span><span class="ot">=</span><span class="st">"pi"</span>, <span class="st">"relig"</span><span class="ot">=</span><span class="st">"re"</span>, <span class="st">"TV"</span><span class="ot">=</span><span class="st">"tv"</span>, <span class="st">"gpa_hs"</span><span class="ot">=</span><span class="st">"hi"</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(poli_ideo <span class="sc">~</span> relig, <span class="at">data=</span>survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in model.response(mf, "numeric"): using type = "numeric" with a factor
response will be ignored</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in Ops.ordered(y, z$residuals): '-' is not meaningful for ordered
factors</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = poli_ideo ~ relig, data = survey)

Coefficients:
(Intercept)      relig.L      relig.Q      relig.C  
     3.5253       2.1864       0.1049      -0.6958  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> survey, <span class="fu">aes</span>(<span class="at">x =</span> relig, <span class="at">fill =</span> poli_ideo)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> <span class="fu">scale_fill_brewer</span>(<span class="at">palette=</span><span class="st">"PiYG"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Rowley_Homework_3_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(gpa_hs <span class="sc">~</span> TV, <span class="at">data=</span>survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gpa_hs ~ TV, data = survey)

Coefficients:
(Intercept)           TV  
    3.44135     -0.01831  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> survey, <span class="fu">aes</span>(<span class="at">x=</span>TV, <span class="at">y=</span>gpa_hs)) <span class="sc">+</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Rowley_Homework_3_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="b-2" class="level4">
<h4 class="anchored" data-anchor-id="b-2">B)</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"stargazer"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Installing package into 'C:/Users/caitr/AppData/Local/R/win-library/4.2'
(as 'lib' is unspecified)</code></pre>
</div>
<div class="cell-output cell-output-error">
<pre><code>Error in contrib.url(repos, "source"): trying to use CRAN without setting a mirror</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Please cite as: </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>poli_relig <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">as.numeric</span>(poli_ideo) <span class="sc">~</span> <span class="fu">as.numeric</span>(relig), </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> survey)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>gpa_tv <span class="ot">&lt;-</span> <span class="fu">lm</span>(gpa_hs <span class="sc">~</span> TV, <span class="at">data =</span> survey)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(poli_relig, gpa_tv, <span class="at">type =</span> <span class="st">'text'</span>, <span class="at">dep.var.labels =</span> <span class="fu">c</span>(<span class="st">'Political Ideology'</span>, <span class="st">'High School GPA'</span>), <span class="at">covariate.labels =</span> <span class="fu">c</span>(<span class="st">'Religiosity'</span>, <span class="st">'Hours of TV'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
================================================================
                                     Dependent variable:        
                              ----------------------------------
                              Political Ideology High School GPA
                                     (1)               (2)      
----------------------------------------------------------------
Religiosity                        0.970***                     
                                   (0.179)                      
                                                                
Hours of TV                                         -0.018**    
                                                     (0.009)    
                                                                
Constant                           0.931**          3.441***    
                                   (0.425)           (0.085)    
                                                                
----------------------------------------------------------------
Observations                          60               60       
R2                                  0.336             0.072     
Adjusted R2                         0.324             0.056     
Residual Std. Error (df = 58)       1.345             0.447     
F Statistic (df = 1; 58)          29.336***          4.471**    
================================================================
Note:                                *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Based on this inferential analysis, we can see that there is a statistically significant and positive correlation between religiosity and political ideology (p-value&lt;0.01). Specifically, there is for every “one unit of increase” in religiosity, there is a “0.970-unit increase” in political ideology. However, the adjusted R-squared value is 0.324, which suggests that a linear regression is not a very good fit for this model.</p>
<p>However, we also see that there is a statistically significant negative correlation between hours of TV watch and high school GPA (p-value&lt;0.05). Specifically, for every one hour of TV watched, there is a 0.018-unit decline in GPA. However, the adjusted R-squared value is 0.056, which suggests that a linear regression is a very unreliable fit for this model.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb64" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 3"</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Caitlin Rowley"</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Homework 3"</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "04/11/2023"</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw3</span></span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - desriptive statistics </span></span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - probability</span></span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-20"><a href="#cb64-20" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-21"><a href="#cb64-21" aria-hidden="true" tabindex="-1"></a><span class="co"># load libraries</span></span>
<span id="cb64-22"><a href="#cb64-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb64-23"><a href="#cb64-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb64-24"><a href="#cb64-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb64-25"><a href="#cb64-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb64-26"><a href="#cb64-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(markdown)</span>
<span id="cb64-27"><a href="#cb64-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggtext)</span>
<span id="cb64-28"><a href="#cb64-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb64-29"><a href="#cb64-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-30"><a href="#cb64-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-31"><a href="#cb64-31" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 1</span></span>
<span id="cb64-32"><a href="#cb64-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-33"><a href="#cb64-33" aria-hidden="true" tabindex="-1"></a>| United Nations (Data file: UN11in alr4) The data in the file UN11 contains several variables,</span>
<span id="cb64-34"><a href="#cb64-34" aria-hidden="true" tabindex="-1"></a>| including ppgdp, the gross national product per person in U.S. dollars, and fertility, the birth</span>
<span id="cb64-35"><a href="#cb64-35" aria-hidden="true" tabindex="-1"></a>| rate per 1000 females, both from the year 2009. The data are for 199 localities, mostly UN</span>
<span id="cb64-36"><a href="#cb64-36" aria-hidden="true" tabindex="-1"></a>| member countries, but also other areas such as Hong Kong that are not independent countries.</span>
<span id="cb64-37"><a href="#cb64-37" aria-hidden="true" tabindex="-1"></a>| The data were collected from the United Nations (2011). We will study the dependence of</span>
<span id="cb64-38"><a href="#cb64-38" aria-hidden="true" tabindex="-1"></a>| fertility on ppgdp.</span>
<span id="cb64-39"><a href="#cb64-39" aria-hidden="true" tabindex="-1"></a>| (a) Identify the predictor and the response.</span>
<span id="cb64-40"><a href="#cb64-40" aria-hidden="true" tabindex="-1"></a>| (b) Draw the scatterplot of fertility on the vertical axis versus ppgdp on the horizontal axis</span>
<span id="cb64-41"><a href="#cb64-41" aria-hidden="true" tabindex="-1"></a>| and summarize the information in this graph. Does a straight-line mean function seem to</span>
<span id="cb64-42"><a href="#cb64-42" aria-hidden="true" tabindex="-1"></a>| be plausible for a summary of this graph?</span>
<span id="cb64-43"><a href="#cb64-43" aria-hidden="true" tabindex="-1"></a>| (c) Draw the scatterplot of log(fertility) versus log(ppgdp) using natural logarithms. Does</span>
<span id="cb64-44"><a href="#cb64-44" aria-hidden="true" tabindex="-1"></a>| the simple linear regression model seem plausible for a summary of this graph? If you use</span>
<span id="cb64-45"><a href="#cb64-45" aria-hidden="true" tabindex="-1"></a>| a different base of logarithms, the shape of the graph won't change, but the values on the</span>
<span id="cb64-46"><a href="#cb64-46" aria-hidden="true" tabindex="-1"></a>| axes will change.</span>
<span id="cb64-47"><a href="#cb64-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-50"><a href="#cb64-50" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-51"><a href="#cb64-51" aria-hidden="true" tabindex="-1"></a><span class="co"># read in data:</span></span>
<span id="cb64-52"><a href="#cb64-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-53"><a href="#cb64-53" aria-hidden="true" tabindex="-1"></a>UN11 <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">url</span>(<span class="st">'https://github.com/omerfyalcin/colab-data/blob/main/UN.rds?raw=true'</span>))</span>
<span id="cb64-54"><a href="#cb64-54" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(UN11)</span>
<span id="cb64-55"><a href="#cb64-55" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-56"><a href="#cb64-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-57"><a href="#cb64-57" aria-hidden="true" tabindex="-1"></a><span class="fu">#### A)</span></span>
<span id="cb64-58"><a href="#cb64-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-59"><a href="#cb64-59" aria-hidden="true" tabindex="-1"></a>In studying the dependence of fertility on GDP, fertility is the predictor and GDP is the response.</span>
<span id="cb64-60"><a href="#cb64-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-61"><a href="#cb64-61" aria-hidden="true" tabindex="-1"></a><span class="fu">#### B)</span></span>
<span id="cb64-62"><a href="#cb64-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-65"><a href="#cb64-65" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-66"><a href="#cb64-66" aria-hidden="true" tabindex="-1"></a><span class="co"># generate scatterplot:</span></span>
<span id="cb64-67"><a href="#cb64-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-68"><a href="#cb64-68" aria-hidden="true" tabindex="-1"></a>scatter_1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(UN11, <span class="fu">aes</span>(<span class="at">x=</span>ppgdp, <span class="at">y=</span>fertility)) <span class="sc">+</span> </span>
<span id="cb64-69"><a href="#cb64-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="at">color=</span><span class="st">"black"</span>)</span>
<span id="cb64-70"><a href="#cb64-70" aria-hidden="true" tabindex="-1"></a>scatter_1</span>
<span id="cb64-71"><a href="#cb64-71" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb64-72"><a href="#cb64-72" aria-hidden="true" tabindex="-1"></a><span class="co"># with linear trend</span></span>
<span id="cb64-73"><a href="#cb64-73" aria-hidden="true" tabindex="-1"></a>scatter_2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(UN11, <span class="fu">aes</span>(<span class="at">x=</span>ppgdp, <span class="at">y=</span>fertility)) <span class="sc">+</span></span>
<span id="cb64-74"><a href="#cb64-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb64-75"><a href="#cb64-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">TRUE</span>)</span>
<span id="cb64-76"><a href="#cb64-76" aria-hidden="true" tabindex="-1"></a>scatter_2</span>
<span id="cb64-77"><a href="#cb64-77" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-78"><a href="#cb64-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-79"><a href="#cb64-79" aria-hidden="true" tabindex="-1"></a>In viewing this scatterplot, we can see that higher rates of birth correlates with lower per-person GPD. A straight-line mean function does not seem plausible for this graph, as the line extends far beyond the range of data points.</span>
<span id="cb64-80"><a href="#cb64-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-81"><a href="#cb64-81" aria-hidden="true" tabindex="-1"></a><span class="fu">#### C)</span></span>
<span id="cb64-82"><a href="#cb64-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-85"><a href="#cb64-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-86"><a href="#cb64-86" aria-hidden="true" tabindex="-1"></a><span class="co"># generate scatterplot using natural logarithms:</span></span>
<span id="cb64-87"><a href="#cb64-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-88"><a href="#cb64-88" aria-hidden="true" tabindex="-1"></a>scatter_3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(UN11, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(ppgdp), <span class="at">y=</span><span class="fu">log</span>(fertility))) <span class="sc">+</span></span>
<span id="cb64-89"><a href="#cb64-89" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb64-90"><a href="#cb64-90" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">TRUE</span>)</span>
<span id="cb64-91"><a href="#cb64-91" aria-hidden="true" tabindex="-1"></a>scatter_3</span>
<span id="cb64-92"><a href="#cb64-92" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-93"><a href="#cb64-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-94"><a href="#cb64-94" aria-hidden="true" tabindex="-1"></a>Using natural logarithms, we see a much more plausible summary for this graph.</span>
<span id="cb64-95"><a href="#cb64-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-96"><a href="#cb64-96" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 2</span></span>
<span id="cb64-97"><a href="#cb64-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-98"><a href="#cb64-98" aria-hidden="true" tabindex="-1"></a>| Annual income, in dollars, is an explanatory variable in a regression analysis. For a British</span>
<span id="cb64-99"><a href="#cb64-99" aria-hidden="true" tabindex="-1"></a>| version of the report on the analysis, all responses are converted to British pounds sterling (1 pound</span>
<span id="cb64-100"><a href="#cb64-100" aria-hidden="true" tabindex="-1"></a>| equals about 1.33 dollars, as of 2016).</span>
<span id="cb64-101"><a href="#cb64-101" aria-hidden="true" tabindex="-1"></a>| (a) How, if at all, does the slope of the prediction equation change?</span>
<span id="cb64-102"><a href="#cb64-102" aria-hidden="true" tabindex="-1"></a>| (b) How, if at all, does the correlation change?</span>
<span id="cb64-103"><a href="#cb64-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-104"><a href="#cb64-104" aria-hidden="true" tabindex="-1"></a><span class="fu">#### A)</span></span>
<span id="cb64-105"><a href="#cb64-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-106"><a href="#cb64-106" aria-hidden="true" tabindex="-1"></a>The slope of the prediction will need to be divided by 1.33 to account for the conversion to British pounds.</span>
<span id="cb64-107"><a href="#cb64-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-108"><a href="#cb64-108" aria-hidden="true" tabindex="-1"></a><span class="fu">#### B)</span></span>
<span id="cb64-109"><a href="#cb64-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-110"><a href="#cb64-110" aria-hidden="true" tabindex="-1"></a>The correlation will not change.</span>
<span id="cb64-111"><a href="#cb64-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-112"><a href="#cb64-112" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 3</span></span>
<span id="cb64-113"><a href="#cb64-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-114"><a href="#cb64-114" aria-hidden="true" tabindex="-1"></a>| Water runoff in the Sierras (Data file: water in alr4) Can Southern California's water</span>
<span id="cb64-115"><a href="#cb64-115" aria-hidden="true" tabindex="-1"></a>| supply in future years be predicted from past data? One factor affecting water availability is stream</span>
<span id="cb64-116"><a href="#cb64-116" aria-hidden="true" tabindex="-1"></a>| runoff. If runoff could be predicted, engineers, planners, and policy makers could do their jobs</span>
<span id="cb64-117"><a href="#cb64-117" aria-hidden="true" tabindex="-1"></a>| more efficiently. The data file contains 43 years' worth of precipitation measurements taken at six</span>
<span id="cb64-118"><a href="#cb64-118" aria-hidden="true" tabindex="-1"></a>| sites in the Sierra Nevada mountains (labeled APMAM, APSAB, APSLAKE, OPBPC, OPRC, and</span>
<span id="cb64-119"><a href="#cb64-119" aria-hidden="true" tabindex="-1"></a>| OPSLAKE) and stream runoff volume at a site near Bishop, California, labeled BSAAM. Draw</span>
<span id="cb64-120"><a href="#cb64-120" aria-hidden="true" tabindex="-1"></a>| the scatterplot matrix for these data and summarize the information available from these</span>
<span id="cb64-121"><a href="#cb64-121" aria-hidden="true" tabindex="-1"></a>| plots. (Hint: Use the pairs() function.)</span>
<span id="cb64-122"><a href="#cb64-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-125"><a href="#cb64-125" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-126"><a href="#cb64-126" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb64-127"><a href="#cb64-127" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(water)</span>
<span id="cb64-128"><a href="#cb64-128" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-129"><a href="#cb64-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-132"><a href="#cb64-132" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-133"><a href="#cb64-133" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(water)</span>
<span id="cb64-134"><a href="#cb64-134" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-135"><a href="#cb64-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-136"><a href="#cb64-136" aria-hidden="true" tabindex="-1"></a>Based on the scatterplot matrix, stream runoff near Bishop, California appears to be correlated with precipitation at "O" sites, but not with "A" sites or year.</span>
<span id="cb64-137"><a href="#cb64-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-138"><a href="#cb64-138" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 4</span></span>
<span id="cb64-139"><a href="#cb64-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-140"><a href="#cb64-140" aria-hidden="true" tabindex="-1"></a>| Professor ratings (Data file: Rateprof in alr4) In the website and online forum</span>
<span id="cb64-141"><a href="#cb64-141" aria-hidden="true" tabindex="-1"></a>| RateMyProfessors.com, students rate and comment on their instructors. Launched in 1999, the site</span>
<span id="cb64-142"><a href="#cb64-142" aria-hidden="true" tabindex="-1"></a>| includes millions of ratings on thousands of instructors. The data file includes the summaries of</span>
<span id="cb64-143"><a href="#cb64-143" aria-hidden="true" tabindex="-1"></a>| the ratings of 364 instructors at a large campus in the Midwest (Bleske-Rechek and Fritsch, 2011).</span>
<span id="cb64-144"><a href="#cb64-144" aria-hidden="true" tabindex="-1"></a>| Each instructor included in the data had at least 10 ratings over a several year period. Students</span>
<span id="cb64-145"><a href="#cb64-145" aria-hidden="true" tabindex="-1"></a>| provided ratings of 1--5 on quality, helpfulness, clarity, easiness of instructor's courses, and</span>
<span id="cb64-146"><a href="#cb64-146" aria-hidden="true" tabindex="-1"></a>| raterInterest in the subject matter covered in the instructor's courses. The data file provides the</span>
<span id="cb64-147"><a href="#cb64-147" aria-hidden="true" tabindex="-1"></a>| averages of these five ratings. Create a scatterplot matrix of these five variables. Provide a</span>
<span id="cb64-148"><a href="#cb64-148" aria-hidden="true" tabindex="-1"></a>| brief description of the relationships between the five ratings.</span>
<span id="cb64-149"><a href="#cb64-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-152"><a href="#cb64-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-153"><a href="#cb64-153" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Rateprof)</span>
<span id="cb64-154"><a href="#cb64-154" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-155"><a href="#cb64-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-158"><a href="#cb64-158" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-159"><a href="#cb64-159" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(Rateprof[,<span class="dv">8</span><span class="sc">:</span><span class="dv">12</span>])</span>
<span id="cb64-160"><a href="#cb64-160" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-161"><a href="#cb64-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-162"><a href="#cb64-162" aria-hidden="true" tabindex="-1"></a>**Quality**: Based on the scatterplot matrix, we can see that there is a positive correlation between quality and helpfulness, as well as between quality and clarity (though we see one outlier in this data set that represents a comparitively higher rate of clarity linked with a lower rate of quality). There is a slightly positive correlation between quality and easiness, but no definitive correlation between quality and rater interest.</span>
<span id="cb64-163"><a href="#cb64-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-164"><a href="#cb64-164" aria-hidden="true" tabindex="-1"></a>**Helpfulness**: Based on the scatterplot matrix, we see (as mentioned) a positive correlation between helpfulness and quality, as well as between helpfulness and clarity (though the spread of data points is slightly larger). Similar to quality, there is a slightly positive correlation between helpfulness and easiness, but no definitive correlation between helpfulness and rater interest.</span>
<span id="cb64-165"><a href="#cb64-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-166"><a href="#cb64-166" aria-hidden="true" tabindex="-1"></a>**Clarity**: Based on the scatterplot, we see (as mentioned) a positive correlation between clarity and quality, as well as between clarity and helpfulness (though the spread of data points is slightly larger). Similarly to quality and helpfulness, there is no definitive correlation between clarity and easiness or clarity and rater interest.</span>
<span id="cb64-167"><a href="#cb64-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-168"><a href="#cb64-168" aria-hidden="true" tabindex="-1"></a>**Easiness**: There are slightly positive correlations between easiness and quality, easiness and helpfulness, and easiness and clarity. There is no definitive correlation between easiness and rater interest.</span>
<span id="cb64-169"><a href="#cb64-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-170"><a href="#cb64-170" aria-hidden="true" tabindex="-1"></a>**Rater Interest**: There are no definitive correlations between rater interest and any of the remaining four variables.</span>
<span id="cb64-171"><a href="#cb64-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-172"><a href="#cb64-172" aria-hidden="true" tabindex="-1"></a>Overall, quality, helpfulness, and clarity provide more insight related to professor rating than easiness and rater interest.</span>
<span id="cb64-173"><a href="#cb64-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-174"><a href="#cb64-174" aria-hidden="true" tabindex="-1"></a><span class="fu">### Question 5</span></span>
<span id="cb64-175"><a href="#cb64-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-176"><a href="#cb64-176" aria-hidden="true" tabindex="-1"></a>| For the student.survey data file in the smss package, conduct regression analyses relating</span>
<span id="cb64-177"><a href="#cb64-177" aria-hidden="true" tabindex="-1"></a>| (by convention, y denotes the outcome variable, x denotes the explanatory variable)</span>
<span id="cb64-178"><a href="#cb64-178" aria-hidden="true" tabindex="-1"></a>| (i) y = political ideology and x = religiosity,</span>
<span id="cb64-179"><a href="#cb64-179" aria-hidden="true" tabindex="-1"></a>| (ii) y = high school GPA and x = hours of TV watching.</span>
<span id="cb64-180"><a href="#cb64-180" aria-hidden="true" tabindex="-1"></a>| (You can use ?student.survey in the R console, after loading the package, to see what each variable</span>
<span id="cb64-181"><a href="#cb64-181" aria-hidden="true" tabindex="-1"></a>| means.)</span>
<span id="cb64-182"><a href="#cb64-182" aria-hidden="true" tabindex="-1"></a>| (a) Graphically portray how the explanatory variable relates to the outcome variable in</span>
<span id="cb64-183"><a href="#cb64-183" aria-hidden="true" tabindex="-1"></a>| each of the two cases</span>
<span id="cb64-184"><a href="#cb64-184" aria-hidden="true" tabindex="-1"></a>| (b) Summarize and interpret results of inferential analyses.</span>
<span id="cb64-185"><a href="#cb64-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-186"><a href="#cb64-186" aria-hidden="true" tabindex="-1"></a><span class="fu">#### A)</span></span>
<span id="cb64-187"><a href="#cb64-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-190"><a href="#cb64-190" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-191"><a href="#cb64-191" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb64-192"><a href="#cb64-192" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(student.survey)</span>
<span id="cb64-193"><a href="#cb64-193" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(student.survey)</span>
<span id="cb64-194"><a href="#cb64-194" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-195"><a href="#cb64-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-198"><a href="#cb64-198" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-199"><a href="#cb64-199" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb64-200"><a href="#cb64-200" aria-hidden="true" tabindex="-1"></a>survey <span class="ot">&lt;-</span> student.survey <span class="sc">%&gt;%</span></span>
<span id="cb64-201"><a href="#cb64-201" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"poli_ideo"</span><span class="ot">=</span><span class="st">"pi"</span>, <span class="st">"relig"</span><span class="ot">=</span><span class="st">"re"</span>, <span class="st">"TV"</span><span class="ot">=</span><span class="st">"tv"</span>, <span class="st">"gpa_hs"</span><span class="ot">=</span><span class="st">"hi"</span>)</span>
<span id="cb64-202"><a href="#cb64-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-203"><a href="#cb64-203" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(poli_ideo <span class="sc">~</span> relig, <span class="at">data=</span>survey)</span>
<span id="cb64-204"><a href="#cb64-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-205"><a href="#cb64-205" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> survey, <span class="fu">aes</span>(<span class="at">x =</span> relig, <span class="at">fill =</span> poli_ideo)) <span class="sc">+</span></span>
<span id="cb64-206"><a href="#cb64-206" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> <span class="fu">scale_fill_brewer</span>(<span class="at">palette=</span><span class="st">"PiYG"</span>)</span>
<span id="cb64-207"><a href="#cb64-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-208"><a href="#cb64-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-211"><a href="#cb64-211" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-212"><a href="#cb64-212" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(gpa_hs <span class="sc">~</span> TV, <span class="at">data=</span>survey)</span>
<span id="cb64-213"><a href="#cb64-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-214"><a href="#cb64-214" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> survey, <span class="fu">aes</span>(<span class="at">x=</span>TV, <span class="at">y=</span>gpa_hs)) <span class="sc">+</span></span>
<span id="cb64-215"><a href="#cb64-215" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">TRUE</span>)</span>
<span id="cb64-216"><a href="#cb64-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-217"><a href="#cb64-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-218"><a href="#cb64-218" aria-hidden="true" tabindex="-1"></a><span class="fu">#### B)</span></span>
<span id="cb64-219"><a href="#cb64-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-222"><a href="#cb64-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb64-223"><a href="#cb64-223" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"stargazer"</span>)</span>
<span id="cb64-224"><a href="#cb64-224" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb64-225"><a href="#cb64-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-226"><a href="#cb64-226" aria-hidden="true" tabindex="-1"></a>poli_relig <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">as.numeric</span>(poli_ideo) <span class="sc">~</span> <span class="fu">as.numeric</span>(relig), </span>
<span id="cb64-227"><a href="#cb64-227" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> survey)</span>
<span id="cb64-228"><a href="#cb64-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-229"><a href="#cb64-229" aria-hidden="true" tabindex="-1"></a>gpa_tv <span class="ot">&lt;-</span> <span class="fu">lm</span>(gpa_hs <span class="sc">~</span> TV, <span class="at">data =</span> survey)</span>
<span id="cb64-230"><a href="#cb64-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-231"><a href="#cb64-231" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(poli_relig, gpa_tv, <span class="at">type =</span> <span class="st">'text'</span>, <span class="at">dep.var.labels =</span> <span class="fu">c</span>(<span class="st">'Political Ideology'</span>, <span class="st">'High School GPA'</span>), <span class="at">covariate.labels =</span> <span class="fu">c</span>(<span class="st">'Religiosity'</span>, <span class="st">'Hours of TV'</span>))</span>
<span id="cb64-232"><a href="#cb64-232" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb64-233"><a href="#cb64-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-234"><a href="#cb64-234" aria-hidden="true" tabindex="-1"></a>Based on this inferential analysis, we can see that there is a statistically significant and positive correlation between religiosity and political ideology (p-value<span class="sc">\&lt;</span>0.01). Specifically, there is for every "one unit of increase" in religiosity, there is a "0.970-unit increase" in political ideology. However, the adjusted R-squared value is 0.324, which suggests that a linear regression is not a very good fit for this model.</span>
<span id="cb64-235"><a href="#cb64-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-236"><a href="#cb64-236" aria-hidden="true" tabindex="-1"></a>However, we also see that there is a statistically significant negative correlation between hours of TV watch and high school GPA (p-value<span class="sc">\&lt;</span>0.05). Specifically, for every one hour of TV watched, there is a 0.018-unit decline in GPA. However, the adjusted R-squared value is 0.056, which suggests that a linear regression is a very unreliable fit for this model.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>