<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xiaoyan">
<meta name="dcterms.date" content="2023-05-17">
<meta name="description" content="Template of course blog qmd file">

<title>Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Final Project">
<meta name="twitter:description" content="Template of course blog qmd file">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-2-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#section" id="toc-section" class="nav-link active" data-scroll-target="#section"></a>
  <ul class="collapse">
  <li><a href="#introduction-and-background" id="toc-introduction-and-background" class="nav-link" data-scroll-target="#introduction-and-background">Introduction and background</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">research questions</a></li>
  <li><a href="#key-predictors" id="toc-key-predictors" class="nav-link" data-scroll-target="#key-predictors">key predictors</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">hypothesis</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">data description</a>
  <ul class="collapse">
  <li><a href="#overlook-of-data" id="toc-overlook-of-data" class="nav-link" data-scroll-target="#overlook-of-data">overlook of data</a></li>
  <li><a href="#parameter-explaination" id="toc-parameter-explaination" class="nav-link" data-scroll-target="#parameter-explaination">parameter explaination</a></li>
  <li><a href="#data-explanatory" id="toc-data-explanatory" class="nav-link" data-scroll-target="#data-explanatory">data explanatory</a></li>
  </ul></li>
  <li><a href="#hypothesis-test" id="toc-hypothesis-test" class="nav-link" data-scroll-target="#hypothesis-test">hypothesis test</a>
  <ul class="collapse">
  <li><a href="#higher-obesity-rate-increase-the-risk-of-depression" id="toc-higher-obesity-rate-increase-the-risk-of-depression" class="nav-link" data-scroll-target="#higher-obesity-rate-increase-the-risk-of-depression">1. Higher obesity rate increase the risk of depression</a></li>
  <li><a href="#higher-family-income-increase-the-rate-of-obesity" id="toc-higher-family-income-increase-the-rate-of-obesity" class="nav-link" data-scroll-target="#higher-family-income-increase-the-rate-of-obesity">2. higher family income increase the rate of obesity</a></li>
  <li><a href="#more-sibling-reduce-the-risk-of-both-depression-and-anxiety." id="toc-more-sibling-reduce-the-risk-of-both-depression-and-anxiety." class="nav-link" data-scroll-target="#more-sibling-reduce-the-risk-of-both-depression-and-anxiety.">3. More sibling reduce the risk of both depression and anxiety.</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Project</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">finalpart1</div>
  </div>
  </div>

<div>
  <div class="description">
    Template of course blog qmd file
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xiaoyan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 17, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'reshape2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    smiths</code></pre>
</div>
</div>
<section id="section" class="level1 tabset">
<h1 class="tabset"></h1>
<section id="introduction-and-background" class="level2">
<h2 class="anchored" data-anchor-id="introduction-and-background">Introduction and background</h2>
<p>The implementation of the one-child policy by the Chinese government in 1979 led to an increase in the number of families with only one child and a unique family structure known as the “four-two-one” model, consisting of four grandparents, two parents, and one child. While being part of such a family structure provides certain advantages in terms of family and social resources, children without siblings, commonly referred to as “only children,” may experience various physical and socio-psychological challenges during their development. One notable concern is the increased risk of overweight and obesity among only children. These children are more likely to struggle with weight-related issues compared to their counterparts who have one or more siblings. Additionally, the psychosocial consequences associated with being an only child are also worth investigating. In this context, it is important to explore not only the relationship between overweight/obesity and mental health in young adolescents but also how the presence or absence of siblings and other factors into this relationship. Overall, investigating the link between overweight/obesity, mental health, and sib-size in young adolescents within the context of the one-child policy can shed light on the potential challenges faced by only children and contribute to a better understanding of their overall well-being.</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">research questions</h2>
<ol type="1">
<li>Does obesity positively related to depression rate?</li>
<li>What are factors that affects obesity?</li>
<li>Does sibling or obesity directly related to depression?</li>
</ol>
</section>
<section id="key-predictors" class="level2">
<h2 class="anchored" data-anchor-id="key-predictors">key predictors</h2>
<ol type="1">
<li>depression rate</li>
<li>sibling number</li>
<li>obesity rate</li>
<li>Family location, finance and education</li>
</ol>
</section>
<section id="hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis">hypothesis</h2>
<ol type="1">
<li>Higher obesity rate increase the risk of depression</li>
<li>higher family income increase the rate of obesity</li>
<li>More sibling reduce the risk of depression</li>
</ol>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">data description</h2>
<section id="overlook-of-data" class="level3">
<h3 class="anchored" data-anchor-id="overlook-of-data">overlook of data</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"/Users/cassie199/Desktop/23spring/603_Spring_2023-1/posts/_data/mentalhealth_data.xlsx"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 29
  T0depres…¹ T0anx…² T1dep…³ T1anx…⁴ Height Weight    WC    HC   SBP   DBP   FBG
       &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1         31      35      41      35   153.   34.6    58  67      98    60   4.4
2         35      24      35      25   172.   46.1    63  78     110    70   3.9
3         31      34      37      26   146.   38.9    72  77.7   102    62   4.6
4         27      31      42      35   162.   46.8    62  80     116    80   4.5
5         31      26      49      33   154.   36.4    56  72      90    60   4.2
6         30      28      47      32   164.   40.6    55  73     102    70   3.7
# … with 18 more variables: TC &lt;dbl&gt;, TG &lt;dbl&gt;, `HDL-C` &lt;dbl&gt;, `LDL-C` &lt;dbl&gt;,
#   BMI &lt;dbl&gt;, WHR &lt;dbl&gt;, WtHR &lt;dbl&gt;, `Family location` &lt;dbl&gt;,
#   `Number of siblings` &lt;dbl&gt;,
#   `How much time do you spend with your father in elementary school?` &lt;dbl&gt;,
#   `How much time do you spend with your mother in elementary school?` &lt;dbl&gt;,
#   `Father’s education level` &lt;dbl&gt;, `Mother’s education level` &lt;dbl&gt;,
#   `Family financial situation` &lt;dbl&gt;, `Sleeping hours` &lt;dbl&gt;, …</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 728</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>T0depression<span class="sc">~</span>data<span class="sc">$</span>BMI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This dataset including 1348 variables and 29 columns. there are 728 NA in this data set. all variables was presented as numberic data. descriptive data was also presented as degrees such as education level, family financial situation and depression rate. By pre-plotting depression rate vs BMI, we can see that some ouliers may need to deal with and there is no siginifcant disrtibution on graph. More data processing is needed in future process.</p>
<p>Modified column name</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Family location"</span>, <span class="st">"Number of siblings"</span>, <span class="st">" time  spend with father in elementary school?"</span>, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>          <span class="st">" time spend with mother in elementary school?"</span>, <span class="st">"Father’s education level"</span>, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Mother’s education level"</span>, <span class="st">"Family financial situation"</span>, <span class="st">"Sleeping hours"</span>, <span class="st">"Skipping breakfast"</span>, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Vigorous"</span>, <span class="st">"Moderate"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>abreviations <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"FL"</span>, <span class="st">"NS"</span>, <span class="st">"TFE"</span>, <span class="st">"TME"</span>, <span class="st">"FEL"</span>, <span class="st">"MEL"</span>, <span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>, <span class="st">"VG"</span>, <span class="st">"MD"</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"varible table</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>varible table</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>variable_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(variables, abreviations)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>variable_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                                        variables abreviations
1                                 Family location           FL
2                              Number of siblings           NS
3   time  spend with father in elementary school?          TFE
4    time spend with mother in elementary school?          TME
5                        Father’s education level          FEL
6                        Mother’s education level          MEL
7                      Family financial situation           FS
8                                  Sleeping hours           SL
9                              Skipping breakfast           SB
10                                       Vigorous           VG
11                                       Moderate           MD</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"T0depression"</span>,<span class="st">"T0anxiety"</span>,<span class="st">"T1depression"</span>,<span class="st">"T1anxiety"</span>,<span class="st">"Height"</span>,<span class="st">"Weight"</span>,<span class="st">"WC"</span>,<span class="st">"HC"</span>,<span class="st">"SBP"</span>,<span class="st">"DBP"</span>,<span class="st">"FBG"</span>,<span class="st">"TC"</span>,<span class="st">"TG"</span>,<span class="st">"HDL-C"</span>,<span class="st">"LDL-C"</span>,<span class="st">"BMI"</span>,<span class="st">"WHR"</span>,<span class="st">"WtHR"</span>,<span class="st">"FL"</span>, <span class="st">"NS"</span>, <span class="st">"TFE"</span>, <span class="st">"TME"</span>, <span class="st">"FEL"</span>, <span class="st">"MEL"</span>, <span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>,<span class="st">"Vigorous"</span>,<span class="st">"Moderate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="parameter-explaination" class="level3">
<h3 class="anchored" data-anchor-id="parameter-explaination">parameter explaination</h3>
<p>BMI (body mass index) in this study is used as indicator of obisity. NIH divided BMI value into three levels as table below.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the data frame for BMI categories</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>bmi_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal Weight"</span>, <span class="st">"Overweight"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>bmi_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"&lt;18.5"</span>, <span class="st">"18.5-24.9"</span>, <span class="st">"&gt;=25"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>bmi_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Category =</span> bmi_levels, <span class="at">BMI =</span> bmi_values)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the BMI category table</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">BMI Categories</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
BMI Categories</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bmi_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       Category       BMI
1   Underweight     &lt;18.5
2 Normal Weight 18.5-24.9
3    Overweight      &gt;=25</code></pre>
</div>
</div>
</section>
<section id="data-explanatory" class="level3">
<h3 class="anchored" data-anchor-id="data-explanatory">data explanatory</h3>
<p>Some key predictors were plotted. The distribution of family location was plotted in the first chart and the distribution of family financial situation were plotted in the second chart.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>proportion <span class="ot">&lt;-</span> data<span class="sc">$</span>FL <span class="sc">/</span> <span class="fu">sum</span>(data<span class="sc">$</span>FL)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>category <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>FS, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>,<span class="st">"4"</span>))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> proportion, <span class="at">fill =</span> category)) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Category"</span>) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>proportion1 <span class="ot">&lt;-</span> data<span class="sc">$</span>FS <span class="sc">/</span> <span class="fu">sum</span>(data<span class="sc">$</span>FS)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> proportion1, <span class="at">fill =</span> category)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Category"</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A scatter plot was used to visualize the relationship between skipping breakfast and BMI rate. Only by scatter plot it is difficult to observe the relationship between two varibales. Therefore, further analysis is needed</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> SB, <span class="at">y =</span> BMI)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">height =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"indianred"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"skipping breakfast"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 36 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="hypothesis-test" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-test">hypothesis test</h2>
<section id="higher-obesity-rate-increase-the-risk-of-depression" class="level3">
<h3 class="anchored" data-anchor-id="higher-obesity-rate-increase-the-risk-of-depression">1. Higher obesity rate increase the risk of depression</h3>
<p>H0=no relationship between obesity rate and the risk of depression</p>
<p>Ha=higher obesity rate increases the risk of depression</p>
<p>In order to prove this hypothesis, linear model was used to calculate relationship between depression rate and BMI.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression of depresison and BMI</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>lm0<span class="ot">&lt;-</span><span class="fu">lm</span>(T1depression <span class="sc">~</span> BMI, <span class="at">data =</span> data)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = T1depression ~ BMI, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-19.2371  -6.2000   0.1719   6.2964  21.9845 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 40.75036    1.50580  27.062   &lt;2e-16 ***
BMI         -0.09528    0.07803  -1.221    0.222    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.093 on 1308 degrees of freedom
  (38 observations deleted due to missingness)
Multiple R-squared:  0.001139,  Adjusted R-squared:  0.0003749 
F-statistic: 1.491 on 1 and 1308 DF,  p-value: 0.2223</code></pre>
</div>
</div>
<p>The BMI coefficient (-0.09528) represents the estimated change in the depression score for a one-unit increase in BMI. For each unit increase in BMI, the depression score decreases by 0.09528. With p-value of 0.222, the coefficient is not significant. Therefore, there is no strong evidence of a linear relationship between BMI and depression. the residuals range from -19.2371 to 21.9845. The residual standard error is relatively high also indicates the model is not fit to the data. F-staistic gives an overall sinificance of the model and with a high p-value, this model is also not statically significant as a whole. The multiple R-squared value (0.001139) represents the proportion of variance in the depression score explained by the model and only 0.1139% of the variability in depression can be attributed to the linear relationship with BMI. The adjusted R-squared value (0.0003749) adjusts the multiple R-squared value for the number of predictors in the model. It penalizes the inclusion of unnecessary predictors. A lower adjusted R-squared suggests that the model does not provide a good fit to the data.</p>
<p>In summary, based on the provided output, there is no strong evidence to support a linear relationship between BMI and depression. The coefficient for BMI is not statistically significant, and the model’s overall fit is weak (low R-squared values and non-significant F-statistic).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#diagnostic</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Linear regression diagnostic plot was used to evaluate the performance.In residual vs fitted plot, the a horizontal red line represent the mean or expected value of the residuals. and the residuals are evenly distributes above and below the horizontal line. This indicates the linear model was fitted to our data. In normal Q_Q plot, the straight pattern suggests that the residuals of a linear regression model follow a normal distribution,supporting the assumption of normality. In a scale-location plot , a straight red line typically indicates homoscedasticity, which means that the residuals have a constant variance across different levels of the predictor variable(s). The scale-location plot detects any systematic patterns in the spread (variance) of the residuals.Here, the plot suggested that the assumption of homoscedasticity is met. According to these diagnostics，the linear model is reliable and presenting the relationship properly.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#visualization</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">y =</span> T1depression)) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"indianred"</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"darkred"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 38 rows containing non-finite values (`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 38 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>plott1depression<span class="ot">&lt;-</span>data<span class="sc">$</span>T1depression[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">predict</span>(lm0))]</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Predicted_value =</span> <span class="fu">predict</span>(lm0),  </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">Observed_value =</span> plott1depression)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> Predicted_value, <span class="at">y =</span> Observed_value)) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"green"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In addition to BMI, several other variables were included in the analysis to examine their relationship with depression rate in children. Two variables, namely time spent with father in elementary school and frequency of skipping breakfast, emerged as significant factors influencing children’s depression rate.</p>
<p>The findings revealed that less time spent with father in elementary school was associated with a higher likelihood of experiencing an increase in depression rate among children. This suggests the importance of positive father-child interactions and involvement during this critical period of development.The analysis showed that skipping breakfast more frequently was also linked to a higher depression rate in children. With diagnostic, there was not a substantial deviation from the assumptions of the model. This suggests that the linear regression analysis provided a reasonable fit to the data and supported the interpretation of the results.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression model 2</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>lm1<span class="ot">&lt;-</span><span class="fu">lm</span>(T1depression <span class="sc">~</span> BMI<span class="sc">+</span>NS<span class="sc">+</span>TFE<span class="sc">+</span>TME<span class="sc">+</span>FEL<span class="sc">+</span>MEL<span class="sc">+</span>FL<span class="sc">+</span>SL<span class="sc">+</span>SB, <span class="at">data =</span> data)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = T1depression ~ BMI + NS + TFE + TME + FEL + MEL + 
    FL + SL + SB, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-22.3852  -5.9985   0.1987   6.4197  21.1941 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 42.55778    2.88686  14.742  &lt; 2e-16 ***
BMI         -0.10358    0.07798  -1.328   0.1843    
NS           0.72821    0.51703   1.408   0.1592    
TFE         -0.57069    0.24271  -2.351   0.0189 *  
TME         -0.18783    0.30401  -0.618   0.5368    
FEL         -0.28747    0.24332  -1.181   0.2376    
MEL         -0.22372    0.26894  -0.832   0.4056    
FL           0.09777    0.18801   0.520   0.6031    
SL           0.10706    0.38873   0.275   0.7831    
SB           1.47402    0.31288   4.711 2.73e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.967 on 1300 degrees of freedom
  (38 observations deleted due to missingness)
Multiple R-squared:  0.0379,    Adjusted R-squared:  0.03124 
F-statistic: 5.691 on 9 and 1300 DF,  p-value: 9.18e-08</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#diagnostic</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To verify if the model is correct, some of varibles with large p value are deleted for backward elimination. “Time spend with mother in elementary school”, “Father’s educaion level”, “sleeping time” are deleted comparing to the model before. In this case, “Time spend with father in elementary school” and “skipping breakfast” still above the significant level. By comparing the adjusted R square of two models(0.03124 and 0.03321). There was no not two big difference in these two models.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression model 3</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>lm2<span class="ot">&lt;-</span><span class="fu">lm</span>(T1depression <span class="sc">~</span> BMI<span class="sc">+</span>NS<span class="sc">+</span>TFE<span class="sc">+</span>FEL<span class="sc">+</span>SB, <span class="at">data =</span> data)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = T1depression ~ BMI + NS + TFE + FEL + SB, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-22.9398  -6.0354   0.2289   6.3596  20.8288 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 41.91051    2.17737  19.248  &lt; 2e-16 ***
BMI         -0.10798    0.07716  -1.399  0.16193    
NS           0.73126    0.45738   1.599  0.11011    
TFE         -0.64654    0.20647  -3.131  0.00178 ** 
FEL         -0.33519    0.23154  -1.448  0.14795    
SB           1.51314    0.31049   4.873 1.23e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.959 on 1304 degrees of freedom
  (38 observations deleted due to missingness)
Multiple R-squared:  0.03681,   Adjusted R-squared:  0.03312 
F-statistic: 9.967 on 5 and 1304 DF,  p-value: 2.26e-09</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#diagnostic </span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm2)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co">#compare predicted value with observe value</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>lm3<span class="ot">&lt;-</span><span class="fu">lm</span>(T1depression <span class="sc">~</span> TFE, <span class="at">data =</span> data)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Predicted_value =</span> <span class="fu">predict</span>(lm3),  </span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">Observed_value =</span> data<span class="sc">$</span>T1depression[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">predict</span>(lm3))])</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> Predicted_value, <span class="at">y =</span> Observed_value)) <span class="sc">+</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"green"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Predicted value was plotted between first linear model and actual value.The regression line was slightly decreasing. This also implies the linear model is not statistic significant. In summary, based on the provided output, there is no strong evidence to support a linear relationship between BMI and depression. The coefficient for BMI is not statistically significant, and the model’s overall fit is weak (low R-squared values and non-significant F-statistic). Therefore, we fail to reject the null hypothesis.</p>
</section>
<section id="higher-family-income-increase-the-rate-of-obesity" class="level3">
<h3 class="anchored" data-anchor-id="higher-family-income-increase-the-rate-of-obesity">2. higher family income increase the rate of obesity</h3>
<p>H0=no relationship between family income and rate of obesity</p>
<p>Ha=higher family income increase the rate of obesity</p>
<p>Based on this data, we may also explore what factors may affect the obesity rate. Here we made a hypothsis as higher family income increase the rate of obesity. Due to most of the variables are ordinal variables, ordinal logistic regression is applied in this slot to verify the hypothesis.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#convert BMI to ordinal varible</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BMI_category <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>BMI, </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">18.5</span>, <span class="fl">24.9</span>, <span class="cn">Inf</span>),</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal weight"</span>, <span class="st">"Overweight"</span>))</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BMI_rank <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">unclass</span>(data<span class="sc">$</span>BMI_category))</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizing data</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out rows with NA values in BMI_rank or FS</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="ot">&lt;-</span> data[<span class="fu">complete.cases</span>(data<span class="sc">$</span>BMI_rank, data<span class="sc">$</span>FS), ]</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the plot with filtered data</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(filtered_data, <span class="fu">aes</span>(<span class="at">x =</span> BMI_category, <span class="at">y =</span> FS)) <span class="sc">+</span></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">size =</span> <span class="fl">0.75</span>, <span class="at">color =</span> <span class="st">"indianred"</span>) <span class="sc">+</span></span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Financial Situation"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># #Fit BMI rank and family finanacial situation into ordinal logit model</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">polr</span>(BMI_rank <span class="sc">~</span> FS, <span class="at">data =</span> data, <span class="at">Hess=</span><span class="cn">TRUE</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = BMI_rank ~ FS, data = data, Hess = TRUE)

Coefficients:
     Value Std. Error t value
FS -0.1883    0.07865  -2.394

Intercepts:
    Value   Std. Error t value
1|2 -0.7067  0.2554    -2.7672
2|3  2.6195  0.2828     9.2639

Residual Deviance: 2173.226 
AIC: 2179.226 
(36 observations deleted due to missingness)</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#p value</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>ctable <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(model))</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(ctable[, <span class="st">"t value"</span>]), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>ctable <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ctable, <span class="st">"p value"</span> <span class="ot">=</span> p)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>ctable</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         Value Std. Error   t value      p value
FS  -0.1883107  0.0786533 -2.394187 1.665724e-02
1|2 -0.7067002  0.2553870 -2.767174 5.654453e-03
2|3  2.6194751  0.2827624  9.263873 1.971474e-20</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting odds-ratio</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       FS 
0.8283573 </code></pre>
</div>
</div>
<p>The findings of the study indicate that financial situation (FS) is significantly associated with BMI ranks. The coefficient of -0.1883 suggests that higher financial situation is linked to a decreased likelihood of being in a higher BMI rank. Specifically, individuals with higher financial situation are less likely to fall into the normal weight category compared to the underweight category (1|2) with a coefficient of -0.7067. Conversely, they are more likely to be in the overweight category compared to the normal weight category (2|3) with a coefficient of 2.6195. These relationships were found to be statistically significant, indicating that the observed associations are unlikely to occur by chance. Furthermore, the inclusion of additional variables in the model improved its predictive ability, as indicated by the slightly lower AIC value. These findings highlight the importance of considering financial situation as a factor influencing BMI ranks and provide insights into the complex relationship between socioeconomic factors and weight status. The null hypothsis is therefore rejected</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#introduce more variables to compare</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>LR1<span class="ot">&lt;-</span><span class="fu">polr</span>(<span class="at">formula =</span> BMI_rank<span class="sc">~</span>SL<span class="sc">+</span>SB<span class="sc">+</span>FS, <span class="at">data =</span> data, <span class="at">Hess =</span> <span class="cn">TRUE</span>, <span class="at">method =</span> <span class="st">"logistic"</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>SUM1<span class="ot">&lt;-</span><span class="fu">summary</span>(LR1)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>SUM1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = BMI_rank ~ SL + SB + FS, data = data, Hess = TRUE, 
    method = "logistic")

Coefficients:
     Value Std. Error t value
SL -0.5179    0.09863  -5.250
SB  0.2064    0.07715   2.676
FS -0.1336    0.08003  -1.669

Intercepts:
    Value   Std. Error t value
1|2 -1.3558  0.3381    -4.0102
2|3  2.0251  0.3551     5.7024

Residual Deviance: 2136.853 
AIC: 2146.853 
(36 observations deleted due to missingness)</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#p value</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>ctable2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(LR1))</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(ctable2[, <span class="st">"t value"</span>]), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>ctable2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ctable2, <span class="st">"p value"</span> <span class="ot">=</span> p)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>ctable2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         Value Std. Error   t value      p value
SL  -0.5178720 0.09863452 -5.250414 1.517580e-07
SB   0.2064347 0.07715030  2.675748 7.456279e-03
FS  -0.1336130 0.08003340 -1.669465 9.502524e-02
1|2 -1.3557600 0.33807702 -4.010210 6.066466e-05
2|3  2.0251068 0.35513075  5.702426 1.181141e-08</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(SUM1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         Value Std. Error   t value
SL  -0.5178720 0.09863452 -5.250414
SB   0.2064347 0.07715030  2.675748
FS  -0.1336130 0.08003340 -1.669465
1|2 -1.3557600 0.33807702 -4.010210
2|3  2.0251068 0.35513075  5.702426</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(SUM1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        Value Std. Error      t value
SL  0.5957870   1.103663 5.245348e-03
SB  1.2292875   1.080204 1.452320e+01
FS  0.8749286   1.083323 1.883478e-01
1|2 0.2577513   1.402249 1.812958e-02
2|3 7.5769204   1.426367 2.995934e+02</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Predict probability</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame with possible IV values</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">FS =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">each =</span> <span class="dv">272</span>),</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">SL =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">each =</span> <span class="dv">340</span>),</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">SB =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">each =</span> <span class="dv">340</span>),</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">BMI =</span> <span class="fu">rep</span>(<span class="fu">seq</span>(<span class="at">from =</span> <span class="fl">12.8</span>, <span class="at">to =</span> <span class="dv">39</span>, <span class="at">length.out =</span> <span class="dv">340</span>), <span class="dv">4</span>))</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the predicted probability </span></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdat, <span class="fu">predict</span>(LR1, newdat, <span class="at">type =</span> <span class="st">"probs"</span>))</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Keeping the category with the highest probability</span></span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>lnewdat <span class="ot">&lt;-</span> <span class="fu">melt</span>(newdat, <span class="at">id.vars =</span> <span class="fu">c</span>(<span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>,<span class="st">"BMI"</span>),</span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a>                <span class="at">variable.name =</span> <span class="st">"Level"</span>, <span class="at">value.name=</span><span class="st">"Probability"</span>)</span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizing probability</span></span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lnewdat, <span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">y =</span> Probability, <span class="at">colour =</span> Level)) <span class="sc">+</span></span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(FS <span class="sc">~</span> SL, <span class="at">labeller=</span><span class="st">"label_both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> SL, <span class="at">y =</span> BMI)) <span class="sc">+</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"red4"</span>) <span class="sc">+</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>,<span class="at">color=</span><span class="st">"indianred"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 36 rows containing non-finite values (`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 36 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="more-sibling-reduce-the-risk-of-both-depression-and-anxiety." class="level3">
<h3 class="anchored" data-anchor-id="more-sibling-reduce-the-risk-of-both-depression-and-anxiety.">3. More sibling reduce the risk of both depression and anxiety.</h3>
<p>H0=no relationship between sibling numbers and depression rate</p>
<p>Ha=more siblings reduce the risk of depression</p>
<p>The sibling numbers here indicates as 1: only child and 2: have siblings. Therefore, a welch two sample t-test and corelation test were performed to explore the relationship.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(data,<span class="sc">!</span><span class="fu">is.na</span>(NS)), <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(NS), <span class="at">y =</span> T1depression)) <span class="sc">+</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"red4"</span>)<span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">color =</span> <span class="st">"tomato1"</span>)<span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Number of sibling"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject3_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>var1<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(data<span class="sc">$</span>T1depression)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>var2<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(data<span class="sc">$</span>NS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The analysis revealed a positive correlation between the number of siblings and depression score, with a sample estimate of the correlation coefficient (rho) of 0.0716. This suggests that as the number of siblings increases, the depression score tends to be higher. The statistical significance of this correlation was confirmed by a p-value of 0.0085, indicating that the observed relationship is unlikely to occur by chance. Furthermore, a Welch t-test was conducted, which demonstrated that the group with more siblings had a significantly higher depression index. Based on these findings, we can conclude that there is a positive relationship between the number of siblings and depression score, suggesting that having more siblings may contribute to increased levels of depression. Therefore, we conclude that number of siblings has a postive relationship with depression score.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>In this study, we investigated the relationship between depression, obesity, family financial situation, and sibling numbers among young adolescents.<br>
Firstly, we examined the association between depression and obesity using various linear regression models. The results indicated that there was no significant relationship between depression and obesity in this population. Next, we focused on the impact of family financial situation on obesity using ordinal logistic regression. Our findings revealed that higher family financial situation was associated with a higher likelihood of having abnormal weight, including being underweight or overweight, rather than having a normal weight. Furthermore, we tested the hypothesis regarding the association between depression and sibling numbers using a Welch t-test. Interestingly, the results showed that adolescents with siblings had significantly lower depression scores compared to those without siblings. Overall, this study contributes to our understanding of the factors influencing the mental and physical well-being of young adolescents. The findings suggest that family financial situation plays a role in the occurrence of abnormal weight, while the presence of siblings appears to have a protective effect against depression. These results emphasize the importance of considering familial and social factors in addressing the mental and physical health of young individuals. Further research and interventions can build upon these findings to develop strategies for promoting healthier outcomes in this population.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb69" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Project "</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Xiaoyan"</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Template of course blog qmd file"</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/17/2023"</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - finalpart1</span></span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb69-17"><a href="#cb69-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-18"><a href="#cb69-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb69-19"><a href="#cb69-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb69-20"><a href="#cb69-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb69-21"><a href="#cb69-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb69-22"><a href="#cb69-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb69-23"><a href="#cb69-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb69-24"><a href="#cb69-24" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-25"><a href="#cb69-25" aria-hidden="true" tabindex="-1"></a><span class="fu"># {.tabset}</span></span>
<span id="cb69-26"><a href="#cb69-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-27"><a href="#cb69-27" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction and background</span></span>
<span id="cb69-28"><a href="#cb69-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-29"><a href="#cb69-29" aria-hidden="true" tabindex="-1"></a> The implementation of the one-child policy by the Chinese government in 1979 led to an increase in the number of families with only one child and a unique family structure known as the "four-two-one" model, consisting of four grandparents, two parents, and one child. While being part of such a family structure provides certain advantages in terms of family and social resources, children without siblings, commonly referred to as "only children," may experience various physical and socio-psychological challenges during their development.</span>
<span id="cb69-30"><a href="#cb69-30" aria-hidden="true" tabindex="-1"></a>One notable concern is the increased risk of overweight and obesity among only children. These children are more likely to struggle with weight-related issues compared to their counterparts who have one or more siblings. Additionally, the psychosocial consequences associated with being an only child are also worth investigating.</span>
<span id="cb69-31"><a href="#cb69-31" aria-hidden="true" tabindex="-1"></a>In this context, it is important to explore not only the relationship between overweight/obesity and mental health in young adolescents but also how the presence or absence of siblings and other factors into this relationship.</span>
<span id="cb69-32"><a href="#cb69-32" aria-hidden="true" tabindex="-1"></a>Overall, investigating the link between overweight/obesity, mental health, and sib-size in young adolescents within the context of the one-child policy can shed light on the potential challenges faced by only children and contribute to a better understanding of their overall well-being.</span>
<span id="cb69-33"><a href="#cb69-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-34"><a href="#cb69-34" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb69-35"><a href="#cb69-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-36"><a href="#cb69-36" aria-hidden="true" tabindex="-1"></a><span class="fu">## research questions</span></span>
<span id="cb69-37"><a href="#cb69-37" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Does obesity positively related to depression rate?</span>
<span id="cb69-38"><a href="#cb69-38" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>What are factors that affects obesity?</span>
<span id="cb69-39"><a href="#cb69-39" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Does sibling or obesity directly related to depression?</span>
<span id="cb69-40"><a href="#cb69-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-41"><a href="#cb69-41" aria-hidden="true" tabindex="-1"></a><span class="fu">## key predictors</span></span>
<span id="cb69-42"><a href="#cb69-42" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>depression rate</span>
<span id="cb69-43"><a href="#cb69-43" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>sibling number</span>
<span id="cb69-44"><a href="#cb69-44" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>obesity rate</span>
<span id="cb69-45"><a href="#cb69-45" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Family location, finance and education</span>
<span id="cb69-46"><a href="#cb69-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-47"><a href="#cb69-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-48"><a href="#cb69-48" aria-hidden="true" tabindex="-1"></a><span class="fu">## hypothesis</span></span>
<span id="cb69-49"><a href="#cb69-49" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Higher obesity rate increase the risk of depression</span>
<span id="cb69-50"><a href="#cb69-50" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>higher family income increase the rate of obesity</span>
<span id="cb69-51"><a href="#cb69-51" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>More sibling reduce the risk of depression </span>
<span id="cb69-52"><a href="#cb69-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-53"><a href="#cb69-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-54"><a href="#cb69-54" aria-hidden="true" tabindex="-1"></a><span class="fu">## data description</span></span>
<span id="cb69-55"><a href="#cb69-55" aria-hidden="true" tabindex="-1"></a><span class="fu">### overlook of data</span></span>
<span id="cb69-58"><a href="#cb69-58" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-59"><a href="#cb69-59" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"/Users/cassie199/Desktop/23spring/603_Spring_2023-1/posts/_data/mentalhealth_data.xlsx"</span>)</span>
<span id="cb69-60"><a href="#cb69-60" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span>
<span id="cb69-61"><a href="#cb69-61" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data))</span>
<span id="cb69-62"><a href="#cb69-62" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>T0depression<span class="sc">~</span>data<span class="sc">$</span>BMI)</span>
<span id="cb69-63"><a href="#cb69-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-64"><a href="#cb69-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-65"><a href="#cb69-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-66"><a href="#cb69-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-67"><a href="#cb69-67" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-68"><a href="#cb69-68" aria-hidden="true" tabindex="-1"></a>This dataset including 1348 variables and 29 columns. there are 728 NA in this data set. all variables was presented as numberic data. descriptive data was also presented as degrees such as education level, family financial situation and depression rate. By pre-plotting depression rate vs BMI, we can see that some ouliers may need to deal with and there is no siginifcant disrtibution on graph. More data processing is needed in future process.</span>
<span id="cb69-69"><a href="#cb69-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-70"><a href="#cb69-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-71"><a href="#cb69-71" aria-hidden="true" tabindex="-1"></a>Modified column name </span>
<span id="cb69-74"><a href="#cb69-74" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-75"><a href="#cb69-75" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Family location"</span>, <span class="st">"Number of siblings"</span>, <span class="st">" time  spend with father in elementary school?"</span>, </span>
<span id="cb69-76"><a href="#cb69-76" aria-hidden="true" tabindex="-1"></a>          <span class="st">" time spend with mother in elementary school?"</span>, <span class="st">"Father’s education level"</span>, </span>
<span id="cb69-77"><a href="#cb69-77" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Mother’s education level"</span>, <span class="st">"Family financial situation"</span>, <span class="st">"Sleeping hours"</span>, <span class="st">"Skipping breakfast"</span>, </span>
<span id="cb69-78"><a href="#cb69-78" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Vigorous"</span>, <span class="st">"Moderate"</span>)</span>
<span id="cb69-79"><a href="#cb69-79" aria-hidden="true" tabindex="-1"></a>abreviations <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"FL"</span>, <span class="st">"NS"</span>, <span class="st">"TFE"</span>, <span class="st">"TME"</span>, <span class="st">"FEL"</span>, <span class="st">"MEL"</span>, <span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>, <span class="st">"VG"</span>, <span class="st">"MD"</span>)</span>
<span id="cb69-80"><a href="#cb69-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-81"><a href="#cb69-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-82"><a href="#cb69-82" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"varible table</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb69-83"><a href="#cb69-83" aria-hidden="true" tabindex="-1"></a>variable_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(variables, abreviations)</span>
<span id="cb69-84"><a href="#cb69-84" aria-hidden="true" tabindex="-1"></a>variable_table</span>
<span id="cb69-85"><a href="#cb69-85" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"T0depression"</span>,<span class="st">"T0anxiety"</span>,<span class="st">"T1depression"</span>,<span class="st">"T1anxiety"</span>,<span class="st">"Height"</span>,<span class="st">"Weight"</span>,<span class="st">"WC"</span>,<span class="st">"HC"</span>,<span class="st">"SBP"</span>,<span class="st">"DBP"</span>,<span class="st">"FBG"</span>,<span class="st">"TC"</span>,<span class="st">"TG"</span>,<span class="st">"HDL-C"</span>,<span class="st">"LDL-C"</span>,<span class="st">"BMI"</span>,<span class="st">"WHR"</span>,<span class="st">"WtHR"</span>,<span class="st">"FL"</span>, <span class="st">"NS"</span>, <span class="st">"TFE"</span>, <span class="st">"TME"</span>, <span class="st">"FEL"</span>, <span class="st">"MEL"</span>, <span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>,<span class="st">"Vigorous"</span>,<span class="st">"Moderate"</span>)</span>
<span id="cb69-86"><a href="#cb69-86" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-87"><a href="#cb69-87" aria-hidden="true" tabindex="-1"></a><span class="fu">### parameter explaination</span></span>
<span id="cb69-88"><a href="#cb69-88" aria-hidden="true" tabindex="-1"></a>BMI (body mass index) in this study is used as indicator of obisity. NIH divided BMI value into three levels as table below.</span>
<span id="cb69-91"><a href="#cb69-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-92"><a href="#cb69-92" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the data frame for BMI categories</span></span>
<span id="cb69-93"><a href="#cb69-93" aria-hidden="true" tabindex="-1"></a>bmi_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal Weight"</span>, <span class="st">"Overweight"</span>)</span>
<span id="cb69-94"><a href="#cb69-94" aria-hidden="true" tabindex="-1"></a>bmi_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"&lt;18.5"</span>, <span class="st">"18.5-24.9"</span>, <span class="st">"&gt;=25"</span>)</span>
<span id="cb69-95"><a href="#cb69-95" aria-hidden="true" tabindex="-1"></a>bmi_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Category =</span> bmi_levels, <span class="at">BMI =</span> bmi_values)</span>
<span id="cb69-96"><a href="#cb69-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-97"><a href="#cb69-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-98"><a href="#cb69-98" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the BMI category table</span></span>
<span id="cb69-99"><a href="#cb69-99" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">BMI Categories</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb69-100"><a href="#cb69-100" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bmi_table)</span>
<span id="cb69-101"><a href="#cb69-101" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-102"><a href="#cb69-102" aria-hidden="true" tabindex="-1"></a><span class="fu">### data explanatory</span></span>
<span id="cb69-103"><a href="#cb69-103" aria-hidden="true" tabindex="-1"></a>Some key predictors were plotted. The distribution of family location was plotted in the first chart and the distribution of family financial situation were plotted in the second chart.</span>
<span id="cb69-106"><a href="#cb69-106" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-107"><a href="#cb69-107" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>proportion <span class="ot">&lt;-</span> data<span class="sc">$</span>FL <span class="sc">/</span> <span class="fu">sum</span>(data<span class="sc">$</span>FL)</span>
<span id="cb69-108"><a href="#cb69-108" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>category <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>FS, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>,<span class="st">"4"</span>))</span>
<span id="cb69-109"><a href="#cb69-109" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> proportion, <span class="at">fill =</span> category)) <span class="sc">+</span></span>
<span id="cb69-110"><a href="#cb69-110" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb69-111"><a href="#cb69-111" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>) <span class="sc">+</span></span>
<span id="cb69-112"><a href="#cb69-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Category"</span>) <span class="sc">+</span></span>
<span id="cb69-113"><a href="#cb69-113" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span>
<span id="cb69-114"><a href="#cb69-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-115"><a href="#cb69-115" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>proportion1 <span class="ot">&lt;-</span> data<span class="sc">$</span>FS <span class="sc">/</span> <span class="fu">sum</span>(data<span class="sc">$</span>FS)</span>
<span id="cb69-116"><a href="#cb69-116" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> proportion1, <span class="at">fill =</span> category)) <span class="sc">+</span></span>
<span id="cb69-117"><a href="#cb69-117" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb69-118"><a href="#cb69-118" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>) <span class="sc">+</span></span>
<span id="cb69-119"><a href="#cb69-119" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Category"</span>) <span class="sc">+</span></span>
<span id="cb69-120"><a href="#cb69-120" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span>
<span id="cb69-121"><a href="#cb69-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-122"><a href="#cb69-122" aria-hidden="true" tabindex="-1"></a>A scatter plot was used to visualize the relationship between skipping breakfast and BMI rate. Only by scatter plot it is difficult to observe the relationship between two varibales. Therefore, further analysis is needed </span>
<span id="cb69-125"><a href="#cb69-125" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-126"><a href="#cb69-126" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> SB, <span class="at">y =</span> BMI)) <span class="sc">+</span></span>
<span id="cb69-127"><a href="#cb69-127" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">height =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"indianred"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb69-128"><a href="#cb69-128" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"skipping breakfast"</span>)</span>
<span id="cb69-129"><a href="#cb69-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-130"><a href="#cb69-130" aria-hidden="true" tabindex="-1"></a><span class="fu">## hypothesis test</span></span>
<span id="cb69-131"><a href="#cb69-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-132"><a href="#cb69-132" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1. Higher obesity rate increase the risk of depression</span></span>
<span id="cb69-133"><a href="#cb69-133" aria-hidden="true" tabindex="-1"></a>H0=no relationship between obesity rate and the risk of depression</span>
<span id="cb69-134"><a href="#cb69-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-135"><a href="#cb69-135" aria-hidden="true" tabindex="-1"></a>Ha=higher obesity rate increases the risk of depression</span>
<span id="cb69-136"><a href="#cb69-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-137"><a href="#cb69-137" aria-hidden="true" tabindex="-1"></a>In order to prove this hypothesis, linear model was used to calculate relationship between depression rate and BMI.</span>
<span id="cb69-138"><a href="#cb69-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-141"><a href="#cb69-141" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-142"><a href="#cb69-142" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression of depresison and BMI</span></span>
<span id="cb69-143"><a href="#cb69-143" aria-hidden="true" tabindex="-1"></a>lm0<span class="ot">&lt;-</span><span class="fu">lm</span>(T1depression <span class="sc">~</span> BMI, <span class="at">data =</span> data)</span>
<span id="cb69-144"><a href="#cb69-144" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm0)</span>
<span id="cb69-145"><a href="#cb69-145" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-146"><a href="#cb69-146" aria-hidden="true" tabindex="-1"></a>The BMI coefficient (-0.09528) represents the estimated change in the depression score for a one-unit increase in BMI. For each unit increase in BMI, the depression score decreases by 0.09528. With p-value of 0.222, the coefficient is not significant. Therefore, there is no strong evidence of a linear relationship between BMI and depression. the residuals range from -19.2371 to 21.9845. The residual standard error is relatively high also indicates the model is not fit to the data. F-staistic gives an overall sinificance of the model and with a high p-value, this model is also not statically significant as a whole. The multiple R-squared value (0.001139) represents the proportion of variance in the depression score explained by the model and only 0.1139% of the variability in depression can be attributed to the linear relationship with BMI.</span>
<span id="cb69-147"><a href="#cb69-147" aria-hidden="true" tabindex="-1"></a>The adjusted R-squared value (0.0003749) adjusts the multiple R-squared value for the number of predictors in the model. It penalizes the inclusion of unnecessary predictors. A lower adjusted  R-squared suggests that the model does not provide a good fit to the data. </span>
<span id="cb69-148"><a href="#cb69-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-149"><a href="#cb69-149" aria-hidden="true" tabindex="-1"></a>In summary, based on the provided output, there is no strong evidence to support a linear relationship between BMI and depression. The coefficient for BMI is not statistically significant, and the model's overall fit is weak (low R-squared values and non-significant F-statistic). </span>
<span id="cb69-152"><a href="#cb69-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-153"><a href="#cb69-153" aria-hidden="true" tabindex="-1"></a><span class="co">#diagnostic</span></span>
<span id="cb69-154"><a href="#cb69-154" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb69-155"><a href="#cb69-155" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm0)</span>
<span id="cb69-156"><a href="#cb69-156" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-157"><a href="#cb69-157" aria-hidden="true" tabindex="-1"></a>Linear regression diagnostic plot was used to  evaluate the performance.In residual vs fitted plot, the a horizontal red line represent the mean or expected value of the residuals. and the residuals are evenly distributes above and below the horizontal line. This indicates the linear model was fitted to our data. In normal Q_Q plot, the straight pattern suggests that the residuals of a linear regression model follow a normal distribution,supporting the assumption of normality. In a scale-location plot , a straight red line typically indicates homoscedasticity, which means that the residuals have a constant variance across different levels of the predictor variable(s). The scale-location plot detects any systematic patterns in the spread (variance) of the residuals.Here, the plot suggested that the assumption of homoscedasticity is met.</span>
<span id="cb69-158"><a href="#cb69-158" aria-hidden="true" tabindex="-1"></a>According to these diagnostics，the linear model is reliable and presenting the relationship properly.</span>
<span id="cb69-159"><a href="#cb69-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-160"><a href="#cb69-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-161"><a href="#cb69-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-164"><a href="#cb69-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-165"><a href="#cb69-165" aria-hidden="true" tabindex="-1"></a><span class="co">#visualization</span></span>
<span id="cb69-166"><a href="#cb69-166" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">y =</span> T1depression)) <span class="sc">+</span></span>
<span id="cb69-167"><a href="#cb69-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"indianred"</span>) <span class="sc">+</span></span>
<span id="cb69-168"><a href="#cb69-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"darkred"</span>)</span>
<span id="cb69-169"><a href="#cb69-169" aria-hidden="true" tabindex="-1"></a>plott1depression<span class="ot">&lt;-</span>data<span class="sc">$</span>T1depression[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">predict</span>(lm0))]</span>
<span id="cb69-170"><a href="#cb69-170" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Predicted_value =</span> <span class="fu">predict</span>(lm0),  </span>
<span id="cb69-171"><a href="#cb69-171" aria-hidden="true" tabindex="-1"></a>                       <span class="at">Observed_value =</span> plott1depression)</span>
<span id="cb69-172"><a href="#cb69-172" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> Predicted_value, <span class="at">y =</span> Observed_value)) <span class="sc">+</span></span>
<span id="cb69-173"><a href="#cb69-173" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb69-174"><a href="#cb69-174" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"green"</span>)</span>
<span id="cb69-175"><a href="#cb69-175" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-176"><a href="#cb69-176" aria-hidden="true" tabindex="-1"></a>In addition to BMI, several other variables were included in the analysis to examine their relationship with depression rate in children. Two variables, namely time spent with father in elementary school and frequency of skipping breakfast, emerged as significant factors influencing children's depression rate.</span>
<span id="cb69-177"><a href="#cb69-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-178"><a href="#cb69-178" aria-hidden="true" tabindex="-1"></a>The findings revealed that less time spent with father in elementary school was associated with a higher likelihood of experiencing an increase in depression rate among children. This suggests the importance of positive father-child interactions and involvement during this critical period of development.The analysis showed that skipping breakfast more frequently was also linked to a higher depression rate in children. With diagnostic, there was not a substantial deviation from the assumptions of the model. This suggests that the linear regression analysis provided a reasonable fit to the data and supported the interpretation of the results.</span>
<span id="cb69-179"><a href="#cb69-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-180"><a href="#cb69-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-183"><a href="#cb69-183" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-184"><a href="#cb69-184" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression model 2</span></span>
<span id="cb69-185"><a href="#cb69-185" aria-hidden="true" tabindex="-1"></a>lm1<span class="ot">&lt;-</span><span class="fu">lm</span>(T1depression <span class="sc">~</span> BMI<span class="sc">+</span>NS<span class="sc">+</span>TFE<span class="sc">+</span>TME<span class="sc">+</span>FEL<span class="sc">+</span>MEL<span class="sc">+</span>FL<span class="sc">+</span>SL<span class="sc">+</span>SB, <span class="at">data =</span> data)</span>
<span id="cb69-186"><a href="#cb69-186" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span>
<span id="cb69-187"><a href="#cb69-187" aria-hidden="true" tabindex="-1"></a><span class="co">#diagnostic</span></span>
<span id="cb69-188"><a href="#cb69-188" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb69-189"><a href="#cb69-189" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm1)</span>
<span id="cb69-190"><a href="#cb69-190" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-191"><a href="#cb69-191" aria-hidden="true" tabindex="-1"></a>To verify if the model is correct, some of varibles with large p value are deleted for backward elimination. "Time spend with mother in elementary school", "Father's educaion level", "sleeping time" are deleted comparing to the model before. In this case, "Time spend with father in elementary school" and "skipping breakfast" still above the significant level. By comparing the adjusted R square of two models(0.03124 and 0.03321). There was no not two big difference in these two models. </span>
<span id="cb69-194"><a href="#cb69-194" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-195"><a href="#cb69-195" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression model 3</span></span>
<span id="cb69-196"><a href="#cb69-196" aria-hidden="true" tabindex="-1"></a>lm2<span class="ot">&lt;-</span><span class="fu">lm</span>(T1depression <span class="sc">~</span> BMI<span class="sc">+</span>NS<span class="sc">+</span>TFE<span class="sc">+</span>FEL<span class="sc">+</span>SB, <span class="at">data =</span> data)</span>
<span id="cb69-197"><a href="#cb69-197" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm2)</span>
<span id="cb69-198"><a href="#cb69-198" aria-hidden="true" tabindex="-1"></a><span class="co">#diagnostic </span></span>
<span id="cb69-199"><a href="#cb69-199" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb69-200"><a href="#cb69-200" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm2)</span>
<span id="cb69-201"><a href="#cb69-201" aria-hidden="true" tabindex="-1"></a><span class="co">#compare predicted value with observe value</span></span>
<span id="cb69-202"><a href="#cb69-202" aria-hidden="true" tabindex="-1"></a>lm3<span class="ot">&lt;-</span><span class="fu">lm</span>(T1depression <span class="sc">~</span> TFE, <span class="at">data =</span> data)</span>
<span id="cb69-203"><a href="#cb69-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-204"><a href="#cb69-204" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Predicted_value =</span> <span class="fu">predict</span>(lm3),  </span>
<span id="cb69-205"><a href="#cb69-205" aria-hidden="true" tabindex="-1"></a>                       <span class="at">Observed_value =</span> data<span class="sc">$</span>T1depression[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">predict</span>(lm3))])</span>
<span id="cb69-206"><a href="#cb69-206" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> Predicted_value, <span class="at">y =</span> Observed_value)) <span class="sc">+</span></span>
<span id="cb69-207"><a href="#cb69-207" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb69-208"><a href="#cb69-208" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"green"</span>)</span>
<span id="cb69-209"><a href="#cb69-209" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-210"><a href="#cb69-210" aria-hidden="true" tabindex="-1"></a>Predicted value was plotted between first linear model and actual value.The regression line was slightly decreasing. This also implies the linear model is not statistic significant. </span>
<span id="cb69-211"><a href="#cb69-211" aria-hidden="true" tabindex="-1"></a>In summary, based on the provided output, there is no strong evidence to support a linear relationship between BMI and depression. The coefficient for BMI is not statistically significant, and the model's overall fit is weak (low R-squared values and non-significant F-statistic). Therefore, we fail to reject the null hypothesis.  </span>
<span id="cb69-212"><a href="#cb69-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-213"><a href="#cb69-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-214"><a href="#cb69-214" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2. higher family income increase the rate of obesity</span></span>
<span id="cb69-215"><a href="#cb69-215" aria-hidden="true" tabindex="-1"></a>H0=no relationship between family income and rate of obesity </span>
<span id="cb69-216"><a href="#cb69-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-217"><a href="#cb69-217" aria-hidden="true" tabindex="-1"></a>Ha=higher family income increase the rate of obesity</span>
<span id="cb69-218"><a href="#cb69-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-219"><a href="#cb69-219" aria-hidden="true" tabindex="-1"></a>Based on this data, we may also explore what factors may affect the obesity rate. Here we made a hypothsis as higher family income increase the rate of obesity. Due to most of the variables are ordinal variables, ordinal logistic regression is applied in this slot to verify the hypothesis. </span>
<span id="cb69-222"><a href="#cb69-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-223"><a href="#cb69-223" aria-hidden="true" tabindex="-1"></a><span class="co">#convert BMI to ordinal varible</span></span>
<span id="cb69-224"><a href="#cb69-224" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BMI_category <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>BMI, </span>
<span id="cb69-225"><a href="#cb69-225" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">18.5</span>, <span class="fl">24.9</span>, <span class="cn">Inf</span>),</span>
<span id="cb69-226"><a href="#cb69-226" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal weight"</span>, <span class="st">"Overweight"</span>))</span>
<span id="cb69-227"><a href="#cb69-227" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BMI_rank <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">unclass</span>(data<span class="sc">$</span>BMI_category))</span>
<span id="cb69-228"><a href="#cb69-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-229"><a href="#cb69-229" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizing data</span></span>
<span id="cb69-230"><a href="#cb69-230" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out rows with NA values in BMI_rank or FS</span></span>
<span id="cb69-231"><a href="#cb69-231" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="ot">&lt;-</span> data[<span class="fu">complete.cases</span>(data<span class="sc">$</span>BMI_rank, data<span class="sc">$</span>FS), ]</span>
<span id="cb69-232"><a href="#cb69-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-233"><a href="#cb69-233" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the plot with filtered data</span></span>
<span id="cb69-234"><a href="#cb69-234" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(filtered_data, <span class="fu">aes</span>(<span class="at">x =</span> BMI_category, <span class="at">y =</span> FS)) <span class="sc">+</span></span>
<span id="cb69-235"><a href="#cb69-235" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">size =</span> <span class="fl">0.75</span>, <span class="at">color =</span> <span class="st">"indianred"</span>) <span class="sc">+</span></span>
<span id="cb69-236"><a href="#cb69-236" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb69-237"><a href="#cb69-237" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb69-238"><a href="#cb69-238" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Financial Situation"</span>)</span>
<span id="cb69-239"><a href="#cb69-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-240"><a href="#cb69-240" aria-hidden="true" tabindex="-1"></a><span class="co"># #Fit BMI rank and family finanacial situation into ordinal logit model</span></span>
<span id="cb69-241"><a href="#cb69-241" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">polr</span>(BMI_rank <span class="sc">~</span> FS, <span class="at">data =</span> data, <span class="at">Hess=</span><span class="cn">TRUE</span>)</span>
<span id="cb69-242"><a href="#cb69-242" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb69-243"><a href="#cb69-243" aria-hidden="true" tabindex="-1"></a><span class="co">#p value</span></span>
<span id="cb69-244"><a href="#cb69-244" aria-hidden="true" tabindex="-1"></a>ctable <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(model))</span>
<span id="cb69-245"><a href="#cb69-245" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(ctable[, <span class="st">"t value"</span>]), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb69-246"><a href="#cb69-246" aria-hidden="true" tabindex="-1"></a>ctable <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ctable, <span class="st">"p value"</span> <span class="ot">=</span> p)</span>
<span id="cb69-247"><a href="#cb69-247" aria-hidden="true" tabindex="-1"></a>ctable</span>
<span id="cb69-248"><a href="#cb69-248" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-251"><a href="#cb69-251" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-252"><a href="#cb69-252" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting odds-ratio</span></span>
<span id="cb69-253"><a href="#cb69-253" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model))</span>
<span id="cb69-254"><a href="#cb69-254" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-255"><a href="#cb69-255" aria-hidden="true" tabindex="-1"></a>The findings of the study indicate that financial situation (FS) is significantly associated with BMI ranks. The coefficient of -0.1883 suggests that higher financial situation is linked to a decreased likelihood of being in a higher BMI rank. Specifically, individuals with higher financial situation are less likely to fall into the normal weight category compared to the underweight category (1|2) with a coefficient of -0.7067. Conversely, they are more likely to be in the overweight category compared to the normal weight category (2|3) with a coefficient of 2.6195. These relationships were found to be statistically significant, indicating that the observed associations are unlikely to occur by chance. Furthermore, the inclusion of additional variables in the model improved its predictive ability, as indicated by the slightly lower AIC value. These findings highlight the importance of considering financial situation as a factor influencing BMI ranks and provide insights into the complex relationship between socioeconomic factors and weight status.</span>
<span id="cb69-256"><a href="#cb69-256" aria-hidden="true" tabindex="-1"></a>The null hypothsis is therefore rejected</span>
<span id="cb69-259"><a href="#cb69-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-260"><a href="#cb69-260" aria-hidden="true" tabindex="-1"></a><span class="co">#introduce more variables to compare</span></span>
<span id="cb69-261"><a href="#cb69-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-262"><a href="#cb69-262" aria-hidden="true" tabindex="-1"></a>LR1<span class="ot">&lt;-</span><span class="fu">polr</span>(<span class="at">formula =</span> BMI_rank<span class="sc">~</span>SL<span class="sc">+</span>SB<span class="sc">+</span>FS, <span class="at">data =</span> data, <span class="at">Hess =</span> <span class="cn">TRUE</span>, <span class="at">method =</span> <span class="st">"logistic"</span>)</span>
<span id="cb69-263"><a href="#cb69-263" aria-hidden="true" tabindex="-1"></a>SUM1<span class="ot">&lt;-</span><span class="fu">summary</span>(LR1)</span>
<span id="cb69-264"><a href="#cb69-264" aria-hidden="true" tabindex="-1"></a>SUM1</span>
<span id="cb69-265"><a href="#cb69-265" aria-hidden="true" tabindex="-1"></a><span class="co">#p value</span></span>
<span id="cb69-266"><a href="#cb69-266" aria-hidden="true" tabindex="-1"></a>ctable2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(LR1))</span>
<span id="cb69-267"><a href="#cb69-267" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(ctable2[, <span class="st">"t value"</span>]), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb69-268"><a href="#cb69-268" aria-hidden="true" tabindex="-1"></a>ctable2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ctable2, <span class="st">"p value"</span> <span class="ot">=</span> p)</span>
<span id="cb69-269"><a href="#cb69-269" aria-hidden="true" tabindex="-1"></a>ctable2</span>
<span id="cb69-270"><a href="#cb69-270" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-273"><a href="#cb69-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-274"><a href="#cb69-274" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(SUM1)</span>
<span id="cb69-275"><a href="#cb69-275" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(SUM1))</span>
<span id="cb69-276"><a href="#cb69-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-277"><a href="#cb69-277" aria-hidden="true" tabindex="-1"></a><span class="do">### Predict probability</span></span>
<span id="cb69-278"><a href="#cb69-278" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame with possible IV values</span></span>
<span id="cb69-279"><a href="#cb69-279" aria-hidden="true" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb69-280"><a href="#cb69-280" aria-hidden="true" tabindex="-1"></a>  <span class="at">FS =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">each =</span> <span class="dv">272</span>),</span>
<span id="cb69-281"><a href="#cb69-281" aria-hidden="true" tabindex="-1"></a>  <span class="at">SL =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">each =</span> <span class="dv">340</span>),</span>
<span id="cb69-282"><a href="#cb69-282" aria-hidden="true" tabindex="-1"></a>  <span class="at">SB =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">each =</span> <span class="dv">340</span>),</span>
<span id="cb69-283"><a href="#cb69-283" aria-hidden="true" tabindex="-1"></a>  <span class="at">BMI =</span> <span class="fu">rep</span>(<span class="fu">seq</span>(<span class="at">from =</span> <span class="fl">12.8</span>, <span class="at">to =</span> <span class="dv">39</span>, <span class="at">length.out =</span> <span class="dv">340</span>), <span class="dv">4</span>))</span>
<span id="cb69-284"><a href="#cb69-284" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb69-285"><a href="#cb69-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-286"><a href="#cb69-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-287"><a href="#cb69-287" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the predicted probability </span></span>
<span id="cb69-288"><a href="#cb69-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-289"><a href="#cb69-289" aria-hidden="true" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdat, <span class="fu">predict</span>(LR1, newdat, <span class="at">type =</span> <span class="st">"probs"</span>))</span>
<span id="cb69-290"><a href="#cb69-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-291"><a href="#cb69-291" aria-hidden="true" tabindex="-1"></a><span class="co"># Keeping the category with the highest probability</span></span>
<span id="cb69-292"><a href="#cb69-292" aria-hidden="true" tabindex="-1"></a>lnewdat <span class="ot">&lt;-</span> <span class="fu">melt</span>(newdat, <span class="at">id.vars =</span> <span class="fu">c</span>(<span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>,<span class="st">"BMI"</span>),</span>
<span id="cb69-293"><a href="#cb69-293" aria-hidden="true" tabindex="-1"></a>                <span class="at">variable.name =</span> <span class="st">"Level"</span>, <span class="at">value.name=</span><span class="st">"Probability"</span>)</span>
<span id="cb69-294"><a href="#cb69-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-295"><a href="#cb69-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-296"><a href="#cb69-296" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizing probability</span></span>
<span id="cb69-297"><a href="#cb69-297" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lnewdat, <span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">y =</span> Probability, <span class="at">colour =</span> Level)) <span class="sc">+</span></span>
<span id="cb69-298"><a href="#cb69-298" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(FS <span class="sc">~</span> SL, <span class="at">labeller=</span><span class="st">"label_both"</span>)</span>
<span id="cb69-299"><a href="#cb69-299" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb69-300"><a href="#cb69-300" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> SL, <span class="at">y =</span> BMI)) <span class="sc">+</span></span>
<span id="cb69-301"><a href="#cb69-301" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"red4"</span>) <span class="sc">+</span></span>
<span id="cb69-302"><a href="#cb69-302" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>,<span class="at">color=</span><span class="st">"indianred"</span>)</span>
<span id="cb69-303"><a href="#cb69-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-304"><a href="#cb69-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-305"><a href="#cb69-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-306"><a href="#cb69-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-307"><a href="#cb69-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-308"><a href="#cb69-308" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-309"><a href="#cb69-309" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb69-310"><a href="#cb69-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-311"><a href="#cb69-311" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3. More sibling reduce the risk of both depression and anxiety. </span></span>
<span id="cb69-312"><a href="#cb69-312" aria-hidden="true" tabindex="-1"></a>H0=no relationship between sibling numbers and depression rate</span>
<span id="cb69-313"><a href="#cb69-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-314"><a href="#cb69-314" aria-hidden="true" tabindex="-1"></a>Ha=more siblings reduce the risk of depression</span>
<span id="cb69-315"><a href="#cb69-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-316"><a href="#cb69-316" aria-hidden="true" tabindex="-1"></a>The sibling numbers here indicates as 1: only child and 2: have siblings. Therefore, a welch two sample t-test and corelation test were performed to explore the relationship. </span>
<span id="cb69-317"><a href="#cb69-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-320"><a href="#cb69-320" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb69-321"><a href="#cb69-321" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(data,<span class="sc">!</span><span class="fu">is.na</span>(NS)), <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(NS), <span class="at">y =</span> T1depression)) <span class="sc">+</span></span>
<span id="cb69-322"><a href="#cb69-322" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"red4"</span>)<span class="sc">+</span></span>
<span id="cb69-323"><a href="#cb69-323" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">color =</span> <span class="st">"tomato1"</span>)<span class="sc">+</span></span>
<span id="cb69-324"><a href="#cb69-324" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Number of sibling"</span>)</span>
<span id="cb69-325"><a href="#cb69-325" aria-hidden="true" tabindex="-1"></a>var1<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(data<span class="sc">$</span>T1depression)</span>
<span id="cb69-326"><a href="#cb69-326" aria-hidden="true" tabindex="-1"></a>var2<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(data<span class="sc">$</span>NS)</span>
<span id="cb69-327"><a href="#cb69-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-328"><a href="#cb69-328" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb69-329"><a href="#cb69-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-330"><a href="#cb69-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-331"><a href="#cb69-331" aria-hidden="true" tabindex="-1"></a>The analysis revealed a positive correlation between the number of siblings and depression score, with a sample estimate of the correlation coefficient (rho) of 0.0716. This suggests that as the number of siblings increases, the depression score tends to be higher. The statistical significance of this correlation was confirmed by a p-value of 0.0085, indicating that the observed relationship is unlikely to occur by chance. Furthermore, a Welch t-test was conducted, which demonstrated that the group with more siblings had a significantly higher depression index. Based on these findings, we can conclude that there is a positive relationship between the number of siblings and depression score, suggesting that having more siblings may contribute to increased levels of depression.</span>
<span id="cb69-332"><a href="#cb69-332" aria-hidden="true" tabindex="-1"></a>Therefore, we conclude that number of siblings has a postive relationship with depression score.</span>
<span id="cb69-333"><a href="#cb69-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-334"><a href="#cb69-334" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion</span></span>
<span id="cb69-335"><a href="#cb69-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-336"><a href="#cb69-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-337"><a href="#cb69-337" aria-hidden="true" tabindex="-1"></a>  In this study, we investigated the relationship between depression, obesity, family financial situation, and sibling numbers among young adolescents.      </span>
<span id="cb69-338"><a href="#cb69-338" aria-hidden="true" tabindex="-1"></a>Firstly, we examined the association between depression and obesity using various linear regression models. The results indicated that there was no significant relationship between depression and obesity in this population.</span>
<span id="cb69-339"><a href="#cb69-339" aria-hidden="true" tabindex="-1"></a>Next, we focused on the impact of family financial situation on obesity using ordinal logistic regression. Our findings revealed that higher family financial situation was associated with a higher likelihood of having abnormal weight, including being underweight or overweight, rather than having a normal weight.</span>
<span id="cb69-340"><a href="#cb69-340" aria-hidden="true" tabindex="-1"></a>Furthermore, we tested the hypothesis regarding the association between depression and sibling numbers using a Welch t-test. Interestingly, the results showed that adolescents with siblings had significantly lower depression scores compared to those without siblings.</span>
<span id="cb69-341"><a href="#cb69-341" aria-hidden="true" tabindex="-1"></a>      Overall, this study contributes to our understanding of the factors influencing the mental and physical well-being of young adolescents. The findings suggest that family financial situation plays a role in the occurrence of abnormal weight, while the presence of siblings appears to have a protective effect against depression. These results emphasize the importance of considering familial and social factors in addressing the mental and physical health of young individuals. Further research and interventions can build upon these findings to develop strategies for promoting healthier outcomes in this population.</span>
<span id="cb69-342"><a href="#cb69-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-343"><a href="#cb69-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-344"><a href="#cb69-344" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>