<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xiaoyan">
<meta name="dcterms.date" content="2023-04-17">
<meta name="description" content="Template of course blog qmd file">

<title>Final Project Checkin-2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta name="twitter:title" content="Final Project Checkin-2">
<meta name="twitter:description" content="Template of course blog qmd file">
<meta name="twitter:image" content="https://dacss.github.io/603_Spring_2023/posts/XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-2-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#section" id="toc-section" class="nav-link active" data-scroll-target="#section"></a>
  <ul class="collapse">
  <li><a href="#introduction-and-background" id="toc-introduction-and-background" class="nav-link" data-scroll-target="#introduction-and-background">Introduction and background</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">research questions</a></li>
  <li><a href="#key-predictors" id="toc-key-predictors" class="nav-link" data-scroll-target="#key-predictors">key predictors</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">hypothesis</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">data description</a>
  <ul class="collapse">
  <li><a href="#overlook-of-data" id="toc-overlook-of-data" class="nav-link" data-scroll-target="#overlook-of-data">overlook of data</a></li>
  <li><a href="#parameter-explaination" id="toc-parameter-explaination" class="nav-link" data-scroll-target="#parameter-explaination">parameter explaination</a></li>
  </ul></li>
  <li><a href="#hypothesis-test" id="toc-hypothesis-test" class="nav-link" data-scroll-target="#hypothesis-test">hypothesis test</a>
  <ul class="collapse">
  <li><a href="#higher-obesity-rate-increase-the-risk-of-depression" id="toc-higher-obesity-rate-increase-the-risk-of-depression" class="nav-link" data-scroll-target="#higher-obesity-rate-increase-the-risk-of-depression">1. Higher obesity rate increase the risk of depression</a></li>
  <li><a href="#higher-family-income-increase-the-rate-of-obesity" id="toc-higher-family-income-increase-the-rate-of-obesity" class="nav-link" data-scroll-target="#higher-family-income-increase-the-rate-of-obesity">2. higher family income increase the rate of obesity</a></li>
  <li><a href="#more-sibling-reduce-the-risk-of-both-depression-and-anxiety." id="toc-more-sibling-reduce-the-risk-of-both-depression-and-anxiety." class="nav-link" data-scroll-target="#more-sibling-reduce-the-risk-of-both-depression-and-anxiety.">3. More sibling reduce the risk of both depression and anxiety.</a></li>
  <li><a href="#others" id="toc-others" class="nav-link" data-scroll-target="#others">others</a></li>
  </ul></li>
  <li><a href="#answers-to-the-feedbacks-on-check-in-1" id="toc-answers-to-the-feedbacks-on-check-in-1" class="nav-link" data-scroll-target="#answers-to-the-feedbacks-on-check-in-1">Answers to the feedbacks on check in 1</a></li>
  <li><a href="#questions-need-to-be-addressed" id="toc-questions-need-to-be-addressed" class="nav-link" data-scroll-target="#questions-need-to-be-addressed">Questions need to be addressed</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Project Checkin-2</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">finalpart1</div>
  </div>
  </div>

<div>
  <div class="description">
    Template of course blog qmd file
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xiaoyan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 17, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="section" class="level1 tabset">
<h1 class="tabset"></h1>
<section id="introduction-and-background" class="level2">
<h2 class="anchored" data-anchor-id="introduction-and-background">Introduction and background</h2>
<p>The Chinese government implemented the one-child policy in 1979, which resulted in the increasing proportion of one-child families and the “four-two-one” family structure consisting of four grandparents, two parents, and one child. Despite being blessed with relatively more family and social resources, only children may face physical and socio-psychological problems during development, including an elevated risk for overweight and obesity and negative psychosocial consequences. Previous studies have shown that only children had a higher likelihood of overweight or obesity, compared with children who had one or more siblings. Over obesity, mental healthy is also interesting to explore that how it is related to overweight/obesity, as well as sib-size, in young adolescents affects mental health.。</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">research questions</h2>
<ol type="1">
<li>Does obesity positively related to mental health?</li>
<li>what are factors that affects mental healthy?</li>
<li>does sibling or obeisty directily related to mental health?</li>
</ol>
</section>
<section id="key-predictors" class="level2">
<h2 class="anchored" data-anchor-id="key-predictors">key predictors</h2>
<ol type="1">
<li>mental health</li>
<li>sibling number</li>
<li>obisity rate</li>
<li>Family location, finance and education</li>
</ol>
</section>
<section id="hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis">hypothesis</h2>
<ol type="1">
<li>Higher obesity rate increase the risk of depression</li>
<li>higher family income increase the rate of obesity</li>
<li>More sibling reduce the risk of both depression and anxiety.</li>
</ol>
<p>In these hypothesis, the response variables are depression rate, axiety rate and BMI index. The explanatory variables can be factors listed below. Analysis is needed to identify the control variables. For exapmle, in hypothesis 2, family income is the explanatory varible and rate of obsity(BMI) is response varible, the control varible may also be family financial situation.</p>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">data description</h2>
<section id="overlook-of-data" class="level3">
<h3 class="anchored" data-anchor-id="overlook-of-data">overlook of data</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"/Users/cassie199/Desktop/23spring/603_Spring_2023-1/posts/_data/mentalhealth_data.xlsx"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 29
  T0depres…¹ T0anx…² T1dep…³ T1anx…⁴ Height Weight    WC    HC   SBP   DBP   FBG
       &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1         31      35      41      35   153.   34.6    58  67      98    60   4.4
2         35      24      35      25   172.   46.1    63  78     110    70   3.9
3         31      34      37      26   146.   38.9    72  77.7   102    62   4.6
4         27      31      42      35   162.   46.8    62  80     116    80   4.5
5         31      26      49      33   154.   36.4    56  72      90    60   4.2
6         30      28      47      32   164.   40.6    55  73     102    70   3.7
# … with 18 more variables: TC &lt;dbl&gt;, TG &lt;dbl&gt;, `HDL-C` &lt;dbl&gt;, `LDL-C` &lt;dbl&gt;,
#   BMI &lt;dbl&gt;, WHR &lt;dbl&gt;, WtHR &lt;dbl&gt;, `Family location` &lt;dbl&gt;,
#   `Number of siblings` &lt;dbl&gt;,
#   `How much time do you spend with your father in elementary school?` &lt;dbl&gt;,
#   `How much time do you spend with your mother in elementary school?` &lt;dbl&gt;,
#   `Father’s education level` &lt;dbl&gt;, `Mother’s education level` &lt;dbl&gt;,
#   `Family financial situation` &lt;dbl&gt;, `Sleeping hours` &lt;dbl&gt;, …</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 728</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>T0depression<span class="sc">~</span>data<span class="sc">$</span>BMI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This dataset including 1348 variables and 29 columns. there are 728 NA in this data set. all variables was presented as numberic data. descriptive data was also presented as degrees such as education level, family financial situation and depression rate. By pre-plotting depression rate vs BMI, we can see that some ouliers may need to deal with and there is no siginifcant disrtibution on graph. More data processing is needed in future process.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Internalizing problem - Depression (SDS)"</span>, <span class="st">"Internalizing problem - Anxiety (SAS)"</span>, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Obesity parameters - BMI"</span>, <span class="st">"Obesity parameters - WC"</span>, <span class="st">"Obesity parameters - WHR"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Obesity parameters - WHtR"</span>, <span class="st">"Biochemical parameters - TG"</span>, <span class="st">"Biochemical parameters - FBG"</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Biochemical parameters - TC"</span>, <span class="st">"Biochemical parameters - HDL-C"</span>, <span class="st">"Biochemical parameters - LDL-C"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Blood pressure - SBP"</span>, <span class="st">"Blood pressure - DBP"</span>,<span class="st">"Family location"</span>, <span class="st">"Number of siblings"</span>, <span class="st">" time  spend with father in elementary school?"</span>, </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>          <span class="st">" time spend with mother in elementary school?"</span>, <span class="st">"Father’s education level"</span>, </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Mother’s education level"</span>, <span class="st">"Family financial situation"</span>, <span class="st">"Sleeping hours"</span>, <span class="st">"Skipping breakfast"</span>, </span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Vigorous"</span>, <span class="st">"Moderate"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>abreviations <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Depression"</span>, <span class="st">"Anxiety"</span>, <span class="st">"BMI"</span>, <span class="st">"WC"</span>, <span class="st">"WHR"</span>, <span class="st">"WHtR"</span>, <span class="st">"TG"</span>, <span class="st">"FBG"</span>, <span class="st">"TC"</span>, <span class="st">"HDL-C"</span>, <span class="st">"LDL-C"</span>, <span class="st">"SBP"</span>, <span class="st">"DBP"</span>,<span class="st">"FL"</span>, <span class="st">"NS"</span>, <span class="st">"TFE"</span>, <span class="st">"TME"</span>, <span class="st">"FEL"</span>, <span class="st">"MEL"</span>, <span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>, <span class="st">"VG"</span>, <span class="st">"MD"</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"varible table</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>varible table</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>variable_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(variables, abreviations)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>variable_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                                        variables abreviations
1        Internalizing problem - Depression (SDS)   Depression
2           Internalizing problem - Anxiety (SAS)      Anxiety
3                        Obesity parameters - BMI          BMI
4                         Obesity parameters - WC           WC
5                        Obesity parameters - WHR          WHR
6                       Obesity parameters - WHtR         WHtR
7                     Biochemical parameters - TG           TG
8                    Biochemical parameters - FBG          FBG
9                     Biochemical parameters - TC           TC
10                 Biochemical parameters - HDL-C        HDL-C
11                 Biochemical parameters - LDL-C        LDL-C
12                           Blood pressure - SBP          SBP
13                           Blood pressure - DBP          DBP
14                                Family location           FL
15                             Number of siblings           NS
16  time  spend with father in elementary school?          TFE
17   time spend with mother in elementary school?          TME
18                       Father’s education level          FEL
19                       Mother’s education level          MEL
20                     Family financial situation           FS
21                                 Sleeping hours           SL
22                             Skipping breakfast           SB
23                                       Vigorous           VG
24                                       Moderate           MD</code></pre>
</div>
</div>
</section>
<section id="parameter-explaination" class="level3">
<h3 class="anchored" data-anchor-id="parameter-explaination">parameter explaination</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the data frame for SAS and SDS scales</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>sas_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Mild to Moderate"</span>, <span class="st">"Marked to Severe"</span>, <span class="st">"Extreme"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>sas_scores <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"&lt;45"</span>, <span class="st">"45-59"</span>, <span class="st">"60-74"</span>, <span class="st">"&gt;=75"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>sas_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Level =</span> sas_levels, <span class="at">Score =</span> sas_scores)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>sds_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Mild"</span>, <span class="st">"Moderate to Marked Major"</span>, <span class="st">"Severe or Extreme Major"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>sds_scores <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"&lt;50"</span>, <span class="st">"50-59"</span>, <span class="st">"60-69"</span>, <span class="st">"&gt;=70"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>sds_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Level =</span> sds_levels, <span class="at">Score =</span> sds_scores)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the data frame for BMI categories</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>bmi_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal Weight"</span>, <span class="st">"Overweight"</span>, <span class="st">"Obesity"</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>bmi_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"&lt;18.5"</span>, <span class="st">"18.5-24.9"</span>, <span class="st">"25-29.9"</span>, <span class="st">"&gt;=30"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>bmi_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Category =</span> bmi_levels, <span class="at">BMI =</span> bmi_values)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the SAS scale table</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Self-rating Anxiety Scale (SAS)</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Self-rating Anxiety Scale (SAS)</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sas_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Level Score
1           Normal   &lt;45
2 Mild to Moderate 45-59
3 Marked to Severe 60-74
4          Extreme  &gt;=75</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the SDS scale table</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">SDS scores (SDS)</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
SDS scores (SDS)</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sds_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                     Level Score
1                   Normal   &lt;50
2                     Mild 50-59
3 Moderate to Marked Major 60-69
4  Severe or Extreme Major  &gt;=70</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the BMI category table</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">BMI Categories</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
BMI Categories</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bmi_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       Category       BMI
1   Underweight     &lt;18.5
2 Normal Weight 18.5-24.9
3    Overweight   25-29.9
4       Obesity      &gt;=30</code></pre>
</div>
</div>
</section>
</section>
<section id="hypothesis-test" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-test">hypothesis test</h2>
<section id="higher-obesity-rate-increase-the-risk-of-depression" class="level3">
<h3 class="anchored" data-anchor-id="higher-obesity-rate-increase-the-risk-of-depression">1. Higher obesity rate increase the risk of depression</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"T0depression"</span>,<span class="st">"T0anxiety"</span>,<span class="st">"T1depression"</span>,<span class="st">"T1anxiety"</span>,<span class="st">"Height"</span>,<span class="st">"Weight"</span>,<span class="st">"WC"</span>,<span class="st">"HC"</span>,<span class="st">"SBP"</span>,<span class="st">"DBP"</span>,<span class="st">"FBG"</span>,<span class="st">"TC"</span>,<span class="st">"TG"</span>,<span class="st">"HDL-C"</span>,<span class="st">"LDL-C"</span>,<span class="st">"BMI"</span>,<span class="st">"WHR"</span>,<span class="st">"WtHR"</span>,<span class="st">"FL"</span>, <span class="st">"NS"</span>, <span class="st">"TFE"</span>, <span class="st">"TME"</span>, <span class="st">"FEL"</span>, <span class="st">"MEL"</span>, <span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>,<span class="st">"Vigorous"</span>,<span class="st">"Moderate"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> T1depression, <span class="at">y =</span> BMI)) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 38 rows containing non-finite values (`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 38 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>T1depression, data<span class="sc">$</span>BMI,<span class="at">method =</span> <span class="fu">c</span>(<span class="st">"spearman"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(data$T1depression, data$BMI, method =
c("spearman")): Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  data$T1depression and data$BMI
S = 384922674, p-value = 0.3229
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
-0.0273327 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>T1depression, data<span class="sc">$</span>BMI,<span class="at">method =</span> <span class="fu">c</span>(<span class="st">"pearson"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  data$T1depression and data$BMI
t = -1.2211, df = 1308, p-value = 0.2223
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.08774365  0.02045498
sample estimates:
        cor 
-0.03374321 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(T1depression <span class="sc">~</span> BMI<span class="sc">+</span>NS<span class="sc">+</span>TFE<span class="sc">+</span>TME, <span class="at">data =</span> data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = T1depression ~ BMI + NS + TFE + TME, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-20.996  -6.131   0.232   6.436  21.536 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 43.08563    2.09342  20.581  &lt; 2e-16 ***
BMI         -0.08628    0.07766  -1.111  0.26681    
NS           1.00348    0.45136   2.223  0.02637 *  
TFE         -0.67037    0.24018  -2.791  0.00533 ** 
TME         -0.27532    0.30312  -0.908  0.36389    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.033 on 1305 degrees of freedom
  (38 observations deleted due to missingness)
Multiple R-squared:  0.01805,   Adjusted R-squared:  0.01504 
F-statistic: 5.999 on 4 and 1305 DF,  p-value: 8.78e-05</code></pre>
</div>
</div>
<p>The Pearson correlation test is a statistical test used to measure the linear relationship between two continuous variables.The Spearman’s rank correlation coefficient (rho) measures the strength and direction of the association between two variables which don’t have to be both continuous or have a linear relationship. It ranges between -1 and 1, where -1 indicates a perfect negative correlation, 1 indicates a perfect positive correlation, and 0 indicates no correlation. Due to the High p value of both test, the depression rate is less likely related to BMI.</p>
</section>
<section id="higher-family-income-increase-the-rate-of-obesity" class="level3">
<h3 class="anchored" data-anchor-id="higher-family-income-increase-the-rate-of-obesity">2. higher family income increase the rate of obesity</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> FS, <span class="at">y =</span> BMI)) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 36 rows containing non-finite values (`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 36 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>FS, data<span class="sc">$</span>BMI,<span class="at">method =</span> <span class="fu">c</span>(<span class="st">"spearman"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(data$FS, data$BMI, method = c("spearman")): Cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  data$FS and data$BMI
S = 390451141, p-value = 0.1766
alternative hypothesis: true rho is not equal to 0
sample estimates:
        rho 
-0.03732942 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>FS, data<span class="sc">$</span>BMI,<span class="at">method =</span> <span class="fu">c</span>(<span class="st">"pearson"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  data$FS and data$BMI
t = -0.74116, df = 1310, p-value = 0.4587
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.07451001  0.03368374
sample estimates:
        cor 
-0.02047308 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>fit2<span class="ot">&lt;-</span><span class="fu">lm</span>(FS <span class="sc">~</span> BMI, <span class="at">data =</span> data)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FS ~ BMI, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.1991 -0.1810 -0.1691  0.8085  1.8644 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.265193   0.128881  25.335   &lt;2e-16 ***
BMI         -0.004949   0.006677  -0.741    0.459    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6932 on 1310 degrees of freedom
  (36 observations deleted due to missingness)
Multiple R-squared:  0.0004191, Adjusted R-squared:  -0.0003439 
F-statistic: 0.5493 on 1 and 1310 DF,  p-value: 0.4587</code></pre>
</div>
</div>
<p>No significant corelationship on family financial status and obesity.</p>
</section>
<section id="more-sibling-reduce-the-risk-of-both-depression-and-anxiety." class="level3">
<h3 class="anchored" data-anchor-id="more-sibling-reduce-the-risk-of-both-depression-and-anxiety.">3. More sibling reduce the risk of both depression and anxiety.</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> NS, <span class="at">y =</span> T1depression)) <span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite values (`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>T1depression,data<span class="sc">$</span>NS, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"spearman"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(data$T1depression, data$NS, method = c("spearman")):
Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  data$T1depression and data$NS
S = 377319431, p-value = 0.008575
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.07162063 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>T1depression,data<span class="sc">$</span>NS, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"pearson"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  data$T1depression and data$NS
t = 2.6388, df = 1344, p-value = 0.008415
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.01843398 0.12474745
sample estimates:
       cor 
0.07179463 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>NS <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>NS)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(T1depression <span class="sc">~</span> NS, <span class="at">data =</span> data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  T1depression by NS
t = -2.6337, df = 1252.5, p-value = 0.008551
alternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0
95 percent confidence interval:
 -2.0381547 -0.2979518
sample estimates:
mean in group 1 mean in group 2 
       38.38127        39.54932 </code></pre>
</div>
</div>
<p>In this case, the sample estimate of the correlation coefficient (rho) is 0.1184734, indicating a positive correlation between T0depression and NS. However, the p-value of the test is 0.008575, which is less than 0.05, suggesting that the correlation is statistically significant at a 5% level of significance.</p>
<p>Therefore, we can conclude that there is a significant positive correlation between the number of siblings (NS) and the degree of depression in this dataset.</p>
<p>By carrying out a Welch t-test, the group with more siblings have higher depression index and p value &lt;0.05 indicates the result is siginifcant. (Not sure why the confident interval is negtive and none of the data was negative. )</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data<span class="sc">$</span>NS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   [1] 2 1 2 1 1 2 1 2 2 2 2 2 1 2 2 1 2 2 2 1 2 2 2 1 2 1 2 2 2 2 2 2 2 1 2 2 2
  [38] 1 2 2 1 1 2 2 2 2 2 1 1 2 2 2 2 1 2 2 2 2 2 2 2 2 2 1 2 2 1 2 1 2 1 1 1 1
  [75] 2 2 2 1 1 2 2 2 1 1 1 1 2 1 2 2 1 1 1 1 2 1 2 2 2 2 1 1 2 1 1 2 1 1 1 2 2
 [112] 1 2 2 2 1 1 1 2 2 2 2 2 2 2 2 1 2 2 1 1 1 2 2 1 2 2 1 2 1 2 1 1 1 2 1 1 2
 [149] 1 1 2 1 2 1 2 2 2 1 2 2 2 2 1 2 2 1 2 2 2 2 2 1 2 2 2 2 2 2 2 1 1 2 2 2 2
 [186] 1 2 2 2 1 2 1 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 1 1 1 2 2
 [223] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 1 1 1 1 1 2 2 2 2 1 1 1 2 1 2 2
 [260] 2 1 2 1 1 1 2 1 2 1 2 2 2 2 2 1 2 2 2 2 1 2 1 1 2 1 2 2 1 1 1 2 2 1 1 2 2
 [297] 2 1 1 2 2 1 2 2 2 2 1 2 1 2 2 2 2 1 2 2 2 1 2 2 2 2 2 1 2 1 1 1 2 1 2 2 1
 [334] 2 2 2 1 1 2 2 2 2 2 1 2 2 1 2 2 2 2 2 2 2 2 2 2 2 1 2 2 1 2 2 2 1 2 2 1 2
 [371] 2 1 1 2 2 2 2 1 2 2 2 2 2 1 2 2 1 2 2 2 2 1 2 2 2 2 1 2 2 1 2 2 2 1 2 1 2
 [408] 1 1 1 1 1 2 2 2 1 1 2 2 2 1 2 1 1 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2
 [445] 2 2 1 1 2 1 2 2 2 1 2 2 1 2 1 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2
 [482] 2 2 2 2 1 2 1 2 1 2 1 2 2 2 2 2 1 2 1 2 2 1 2 1 2 1 2 1 1 2 2 2 2 1 2 2 1
 [519] 1 2 2 1 1 2 2 2 1 1 2 2 2 1 2 2 2 1 1 2 1 2 2 2 1 2 2 1 2 2 2 1 1 1 2 2 2
 [556] 1 2 2 2 1 2 2 1 2 2 1 1 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 1 1 2 2 2 2 2 1 1 1
 [593] 2 2 2 2 1 2 2 2 1 2 2 2 2 1 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2 1 2 1 1 2 2 2
 [630] 2 2 2 1 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 1 1 2 2 2 2 2 1 1 2 2 1 1 2 2 2
 [667] 1 1 2 1 1 1 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1
 [704] 1 1 1 1 1 1 2 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1
 [741] 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 2 1 2 1 1 1
 [778] 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [815] 1 1 1 1 1 2 1 1 1 2 1 1 2 1 2 1 2 1 1 2 1 1 2 1 1 1 1 1 1 2 1 1 1 1 1 1 1
 [852] 2 1 1 2 1 1 1 2 1 1 1 1 2 1 2 2 1 1 1 2 2 2 1 2 1 2 1 2 1 1 1 1 1 2 1 1 2
 [889] 2 2 1 2 1 1 1 2 1 1 1 1 1 2 1 1 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [926] 1 2 1 1 1 1 1 1 1 2 1 2 1 1 1 1 2 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [963] 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 2 1 1 2 1 1 1 1 2 1 1 1 1 1 2 1 1 2 1 1 1
[1000] 1 1 1 1 2 1 1 1 1 2 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1 2 2 1 1 1 1 2
[1037] 2 1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 2 1 1 2 1 2 1 1 2 1 1 1 2 1 1 1 1 2
[1074] 1 1 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1
[1111] 2 2 1 1 2 2 1 1 1 2 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 2 1 1
[1148] 1 1 1 1 2 2 1 1 1 1 2 2 2 1 2 2 1 1 1 1 1 1 1 2 1 1 1 2 1 2 2 1 1 1 1 1 1
[1185] 1 1 2 1 2 1 1 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 2
[1222] 1 1 1 2 1 1 1 1 2 1 2 1 1 1 1 2 2 1 1 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2
[1259] 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 2 1 1 2 2 2 1 1 1 1
[1296] 1 1 2 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1
[1333] 1 1 1 2 1 1 1 1 1 1 2 1 1 1 1 2
Levels: 1 2</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> NS, <span class="at">y =</span> T1anxiety)) <span class="sc">+</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite values (`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>NS <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data<span class="sc">$</span>NS)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>T1anxiety,data<span class="sc">$</span>NS, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"spearman"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(data$T1anxiety, data$NS, method = c("spearman")):
Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  data$T1anxiety and data$NS
S = 343033890, p-value = 8.796e-09
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.1559788 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>fit3<span class="ot">&lt;-</span><span class="fu">lm</span>(T1anxiety <span class="sc">~</span> NS, <span class="at">data =</span> data)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = T1anxiety ~ NS, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.906  -3.997   0.003   3.003  33.003 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  30.0883     0.5185  58.030  &lt; 2e-16 ***
NS            1.9091     0.3411   5.597 2.64e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.207 on 1344 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.02278,   Adjusted R-squared:  0.02205 
F-statistic: 31.32 on 1 and 1344 DF,  p-value: 2.643e-08</code></pre>
</div>
</div>
</section>
<section id="others" class="level3">
<h3 class="anchored" data-anchor-id="others">others</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create sample data</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>BMI<span class="sc">~</span>data<span class="sc">$</span>T1depression)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>T1depression<span class="sc">~</span>data<span class="sc">$</span>FL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BMI_category <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>BMI, </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">18.5</span>, <span class="fl">24.9</span>, <span class="fl">29.9</span>, <span class="cn">Inf</span>),</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal weight"</span>, <span class="st">"Overweight"</span>, <span class="st">"Obesity"</span>))</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Depression_category <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>T1depression, </span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">45</span>, <span class="dv">59</span>,<span class="dv">74</span>,<span class="dv">75</span>),</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Mild"</span>, <span class="st">"Moderate to Marked Major"</span>, <span class="st">"Severe or Extreme Major"</span>))</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the bar chart</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="answers-to-the-feedbacks-on-check-in-1" class="level2">
<h2 class="anchored" data-anchor-id="answers-to-the-feedbacks-on-check-in-1">Answers to the feedbacks on check in 1</h2>
<p>Here are a few things you may want to work on in future steps: 1. Please provide more information of the dataset: what each variable means (e.g.&nbsp;WC, HC, SBP etc) and how it is measured. This is to make sure audiences understand your confounders. a table with explaination of abrivation is updated in data description</p>
<ol start="2" type="1">
<li><p>Since gender is one of your key predictors, you may consider using the interaction between gender and other key variables in the model to see whether gender influences the impact of other predictors. Also, seem I didn’t find the gender variable in the dataset you provided? Thanks for pointing out. Since gender is missiong, I will not use gender as a key predicor.</p></li>
<li><p>As you mentioned, there are some outliers in the data, especially the one on the top-right corner. This outlier can change the slope of the regression. Also, the relationship between BMI and depression is not very clear in the graph, as you mentioned, more data processing is needed. You can also try plotting different groups (e.g.&nbsp;gender, family location) in different colors to see if there’s any pattern.</p></li>
</ol>
<p>Thanks for the comments, I will try to process the data this time and plot more patterns.</p>
</section>
<section id="questions-need-to-be-addressed" class="level2">
<h2 class="anchored" data-anchor-id="questions-need-to-be-addressed">Questions need to be addressed</h2>
<ol type="1">
<li>the varibles such as family locations or education level can be expressed either as rank or ordinal, as drawed below,it is hard to find a correlationship with this kind of varibles. How can i explore the relationship between an ordinal varible and a continuous varible?</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(data[<span class="fu">c</span>(<span class="st">"T1depression"</span>,<span class="st">"T1anxiety"</span>,<span class="st">"BMI"</span>,<span class="st">"FL"</span>, <span class="st">"NS"</span>, <span class="st">"TFE"</span>, <span class="st">"TME"</span>, <span class="st">"FEL"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(data[<span class="fu">c</span>(<span class="st">"T1depression"</span>,<span class="st">"T1anxiety"</span>, <span class="st">"MEL"</span>, <span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>,<span class="st">"Vigorous"</span>,<span class="st">"Moderate"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="2" type="1">
<li>as some of the continuous varibles can also converted to ordinal varibles, what would be some method or test good to find the relationship between them?</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">#convert continuous varibles into categorical varibles</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>FL1 <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1348</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Rural"</span>, <span class="st">"Suburban"</span>, <span class="st">"Urban"</span>, <span class="st">"City"</span>, <span class="st">"Metropolis"</span>))</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BMI_category <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>BMI, </span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">18.5</span>, <span class="fl">24.9</span>, <span class="fl">29.9</span>, <span class="cn">Inf</span>),</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal weight"</span>, <span class="st">"Overweight"</span>, <span class="st">"Obesity"</span>))</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Depression_category <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>T1depression, </span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">45</span>, <span class="dv">59</span>,<span class="dv">74</span>,<span class="dv">75</span>),</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Mild"</span>, <span class="st">"Moderate to Marked Major"</span>, <span class="st">"Severe or Extreme Major"</span>))</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> FL1, <span class="at">y =</span> BMI, <span class="at">fill =</span> BMI_category)) <span class="sc">+</span> </span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#1b9e77"</span>, <span class="st">"#d95f02"</span>, <span class="st">"#7570b3"</span>, <span class="st">"#e7298a"</span>)) <span class="sc">+</span></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Family location"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"BMI"</span>) <span class="sc">+</span> </span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"BMI category and family location"</span>) <span class="sc">+</span></span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 36 rows containing missing values (`position_stack()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> FL1, <span class="at">y =</span> T1depression, <span class="at">fill =</span> Depression_category)) <span class="sc">+</span> </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`position_stack()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
</div>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Spring_2023" data-repo-id="R_kgDOI4oXIA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb80" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Project Checkin-2"</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Xiaoyan"</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Template of course blog qmd file"</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "04/17/2023"</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - finalpart1</span></span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb80-17"><a href="#cb80-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-18"><a href="#cb80-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb80-19"><a href="#cb80-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb80-20"><a href="#cb80-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb80-21"><a href="#cb80-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb80-22"><a href="#cb80-22" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb80-23"><a href="#cb80-23" aria-hidden="true" tabindex="-1"></a><span class="fu"># {.tabset}</span></span>
<span id="cb80-24"><a href="#cb80-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-25"><a href="#cb80-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction and background</span></span>
<span id="cb80-26"><a href="#cb80-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-27"><a href="#cb80-27" aria-hidden="true" tabindex="-1"></a> The Chinese government implemented the one-child policy in 1979, which resulted in the increasing proportion of one-child families and the "four-two-one" family structure consisting of four grandparents, two parents, and one child. Despite being blessed with relatively more family and social resources, only children may face physical and socio-psychological problems during development, including an elevated risk for overweight and obesity and negative psychosocial consequences. Previous studies have shown that only children had a higher likelihood of overweight or obesity, compared with children who had one or more siblings. Over obesity, mental healthy is also interesting to explore that how it is related to overweight/obesity, as well as sib-size, in young adolescents affects mental health.。</span>
<span id="cb80-28"><a href="#cb80-28" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb80-29"><a href="#cb80-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-30"><a href="#cb80-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## research questions</span></span>
<span id="cb80-31"><a href="#cb80-31" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Does obesity positively related to mental health?</span>
<span id="cb80-32"><a href="#cb80-32" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>what are factors that affects mental healthy?</span>
<span id="cb80-33"><a href="#cb80-33" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>does sibling or obeisty directily related to mental health?</span>
<span id="cb80-34"><a href="#cb80-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-35"><a href="#cb80-35" aria-hidden="true" tabindex="-1"></a><span class="fu">## key predictors</span></span>
<span id="cb80-36"><a href="#cb80-36" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>mental health</span>
<span id="cb80-37"><a href="#cb80-37" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>sibling number</span>
<span id="cb80-38"><a href="#cb80-38" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>obisity rate</span>
<span id="cb80-39"><a href="#cb80-39" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Family location, finance and education</span>
<span id="cb80-40"><a href="#cb80-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-41"><a href="#cb80-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-42"><a href="#cb80-42" aria-hidden="true" tabindex="-1"></a><span class="fu">## hypothesis</span></span>
<span id="cb80-43"><a href="#cb80-43" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Higher obesity rate increase the risk of depression</span>
<span id="cb80-44"><a href="#cb80-44" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>higher family income increase the rate of obesity</span>
<span id="cb80-45"><a href="#cb80-45" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>More sibling reduce the risk of both depression and anxiety. </span>
<span id="cb80-46"><a href="#cb80-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-47"><a href="#cb80-47" aria-hidden="true" tabindex="-1"></a>In these hypothesis, the response variables are depression rate, axiety rate and BMI index. The explanatory variables can be factors listed below. Analysis is needed to identify the control variables. For exapmle, in hypothesis 2, family income is the explanatory varible and rate of obsity(BMI) is response varible, the control varible may also be family financial situation. </span>
<span id="cb80-48"><a href="#cb80-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-49"><a href="#cb80-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## data description</span></span>
<span id="cb80-50"><a href="#cb80-50" aria-hidden="true" tabindex="-1"></a><span class="fu">### overlook of data</span></span>
<span id="cb80-53"><a href="#cb80-53" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-54"><a href="#cb80-54" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"/Users/cassie199/Desktop/23spring/603_Spring_2023-1/posts/_data/mentalhealth_data.xlsx"</span>)</span>
<span id="cb80-55"><a href="#cb80-55" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span>
<span id="cb80-56"><a href="#cb80-56" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data))</span>
<span id="cb80-57"><a href="#cb80-57" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>T0depression<span class="sc">~</span>data<span class="sc">$</span>BMI)</span>
<span id="cb80-58"><a href="#cb80-58" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb80-59"><a href="#cb80-59" aria-hidden="true" tabindex="-1"></a>This dataset including 1348 variables and 29 columns. there are 728 NA in this data set. all variables was presented as numberic data. descriptive data was also presented as degrees such as education level, family financial situation and depression rate. By pre-plotting depression rate vs BMI, we can see that some ouliers may need to deal with and there is no siginifcant disrtibution on graph. More data processing is needed in future process.</span>
<span id="cb80-60"><a href="#cb80-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-63"><a href="#cb80-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-64"><a href="#cb80-64" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Internalizing problem - Depression (SDS)"</span>, <span class="st">"Internalizing problem - Anxiety (SAS)"</span>, </span>
<span id="cb80-65"><a href="#cb80-65" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Obesity parameters - BMI"</span>, <span class="st">"Obesity parameters - WC"</span>, <span class="st">"Obesity parameters - WHR"</span>,</span>
<span id="cb80-66"><a href="#cb80-66" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Obesity parameters - WHtR"</span>, <span class="st">"Biochemical parameters - TG"</span>, <span class="st">"Biochemical parameters - FBG"</span>,</span>
<span id="cb80-67"><a href="#cb80-67" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Biochemical parameters - TC"</span>, <span class="st">"Biochemical parameters - HDL-C"</span>, <span class="st">"Biochemical parameters - LDL-C"</span>,</span>
<span id="cb80-68"><a href="#cb80-68" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Blood pressure - SBP"</span>, <span class="st">"Blood pressure - DBP"</span>,<span class="st">"Family location"</span>, <span class="st">"Number of siblings"</span>, <span class="st">" time  spend with father in elementary school?"</span>, </span>
<span id="cb80-69"><a href="#cb80-69" aria-hidden="true" tabindex="-1"></a>          <span class="st">" time spend with mother in elementary school?"</span>, <span class="st">"Father’s education level"</span>, </span>
<span id="cb80-70"><a href="#cb80-70" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Mother’s education level"</span>, <span class="st">"Family financial situation"</span>, <span class="st">"Sleeping hours"</span>, <span class="st">"Skipping breakfast"</span>, </span>
<span id="cb80-71"><a href="#cb80-71" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Vigorous"</span>, <span class="st">"Moderate"</span>)</span>
<span id="cb80-72"><a href="#cb80-72" aria-hidden="true" tabindex="-1"></a>abreviations <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Depression"</span>, <span class="st">"Anxiety"</span>, <span class="st">"BMI"</span>, <span class="st">"WC"</span>, <span class="st">"WHR"</span>, <span class="st">"WHtR"</span>, <span class="st">"TG"</span>, <span class="st">"FBG"</span>, <span class="st">"TC"</span>, <span class="st">"HDL-C"</span>, <span class="st">"LDL-C"</span>, <span class="st">"SBP"</span>, <span class="st">"DBP"</span>,<span class="st">"FL"</span>, <span class="st">"NS"</span>, <span class="st">"TFE"</span>, <span class="st">"TME"</span>, <span class="st">"FEL"</span>, <span class="st">"MEL"</span>, <span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>, <span class="st">"VG"</span>, <span class="st">"MD"</span>)</span>
<span id="cb80-73"><a href="#cb80-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-74"><a href="#cb80-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-75"><a href="#cb80-75" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"varible table</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb80-76"><a href="#cb80-76" aria-hidden="true" tabindex="-1"></a>variable_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(variables, abreviations)</span>
<span id="cb80-77"><a href="#cb80-77" aria-hidden="true" tabindex="-1"></a>variable_table</span>
<span id="cb80-78"><a href="#cb80-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-79"><a href="#cb80-79" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb80-80"><a href="#cb80-80" aria-hidden="true" tabindex="-1"></a><span class="fu">### parameter explaination</span></span>
<span id="cb80-83"><a href="#cb80-83" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-84"><a href="#cb80-84" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the data frame for SAS and SDS scales</span></span>
<span id="cb80-85"><a href="#cb80-85" aria-hidden="true" tabindex="-1"></a>sas_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Mild to Moderate"</span>, <span class="st">"Marked to Severe"</span>, <span class="st">"Extreme"</span>)</span>
<span id="cb80-86"><a href="#cb80-86" aria-hidden="true" tabindex="-1"></a>sas_scores <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"&lt;45"</span>, <span class="st">"45-59"</span>, <span class="st">"60-74"</span>, <span class="st">"&gt;=75"</span>)</span>
<span id="cb80-87"><a href="#cb80-87" aria-hidden="true" tabindex="-1"></a>sas_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Level =</span> sas_levels, <span class="at">Score =</span> sas_scores)</span>
<span id="cb80-88"><a href="#cb80-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-89"><a href="#cb80-89" aria-hidden="true" tabindex="-1"></a>sds_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Mild"</span>, <span class="st">"Moderate to Marked Major"</span>, <span class="st">"Severe or Extreme Major"</span>)</span>
<span id="cb80-90"><a href="#cb80-90" aria-hidden="true" tabindex="-1"></a>sds_scores <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"&lt;50"</span>, <span class="st">"50-59"</span>, <span class="st">"60-69"</span>, <span class="st">"&gt;=70"</span>)</span>
<span id="cb80-91"><a href="#cb80-91" aria-hidden="true" tabindex="-1"></a>sds_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Level =</span> sds_levels, <span class="at">Score =</span> sds_scores)</span>
<span id="cb80-92"><a href="#cb80-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-93"><a href="#cb80-93" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the data frame for BMI categories</span></span>
<span id="cb80-94"><a href="#cb80-94" aria-hidden="true" tabindex="-1"></a>bmi_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal Weight"</span>, <span class="st">"Overweight"</span>, <span class="st">"Obesity"</span>)</span>
<span id="cb80-95"><a href="#cb80-95" aria-hidden="true" tabindex="-1"></a>bmi_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"&lt;18.5"</span>, <span class="st">"18.5-24.9"</span>, <span class="st">"25-29.9"</span>, <span class="st">"&gt;=30"</span>)</span>
<span id="cb80-96"><a href="#cb80-96" aria-hidden="true" tabindex="-1"></a>bmi_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Category =</span> bmi_levels, <span class="at">BMI =</span> bmi_values)</span>
<span id="cb80-97"><a href="#cb80-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-98"><a href="#cb80-98" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the SAS scale table</span></span>
<span id="cb80-99"><a href="#cb80-99" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Self-rating Anxiety Scale (SAS)</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb80-100"><a href="#cb80-100" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sas_table)</span>
<span id="cb80-101"><a href="#cb80-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-102"><a href="#cb80-102" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the SDS scale table</span></span>
<span id="cb80-103"><a href="#cb80-103" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">SDS scores (SDS)</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb80-104"><a href="#cb80-104" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sds_table)</span>
<span id="cb80-105"><a href="#cb80-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-106"><a href="#cb80-106" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the BMI category table</span></span>
<span id="cb80-107"><a href="#cb80-107" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">BMI Categories</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb80-108"><a href="#cb80-108" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bmi_table)</span>
<span id="cb80-109"><a href="#cb80-109" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb80-110"><a href="#cb80-110" aria-hidden="true" tabindex="-1"></a><span class="fu">## hypothesis test</span></span>
<span id="cb80-111"><a href="#cb80-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-112"><a href="#cb80-112" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1. Higher obesity rate increase the risk of depression</span></span>
<span id="cb80-115"><a href="#cb80-115" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-116"><a href="#cb80-116" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"T0depression"</span>,<span class="st">"T0anxiety"</span>,<span class="st">"T1depression"</span>,<span class="st">"T1anxiety"</span>,<span class="st">"Height"</span>,<span class="st">"Weight"</span>,<span class="st">"WC"</span>,<span class="st">"HC"</span>,<span class="st">"SBP"</span>,<span class="st">"DBP"</span>,<span class="st">"FBG"</span>,<span class="st">"TC"</span>,<span class="st">"TG"</span>,<span class="st">"HDL-C"</span>,<span class="st">"LDL-C"</span>,<span class="st">"BMI"</span>,<span class="st">"WHR"</span>,<span class="st">"WtHR"</span>,<span class="st">"FL"</span>, <span class="st">"NS"</span>, <span class="st">"TFE"</span>, <span class="st">"TME"</span>, <span class="st">"FEL"</span>, <span class="st">"MEL"</span>, <span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>,<span class="st">"Vigorous"</span>,<span class="st">"Moderate"</span>)</span>
<span id="cb80-117"><a href="#cb80-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-118"><a href="#cb80-118" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> T1depression, <span class="at">y =</span> BMI)) <span class="sc">+</span></span>
<span id="cb80-119"><a href="#cb80-119" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb80-120"><a href="#cb80-120" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb80-121"><a href="#cb80-121" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>T1depression, data<span class="sc">$</span>BMI,<span class="at">method =</span> <span class="fu">c</span>(<span class="st">"spearman"</span>))</span>
<span id="cb80-122"><a href="#cb80-122" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>T1depression, data<span class="sc">$</span>BMI,<span class="at">method =</span> <span class="fu">c</span>(<span class="st">"pearson"</span>))</span>
<span id="cb80-123"><a href="#cb80-123" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(T1depression <span class="sc">~</span> BMI<span class="sc">+</span>NS<span class="sc">+</span>TFE<span class="sc">+</span>TME, <span class="at">data =</span> data))</span>
<span id="cb80-124"><a href="#cb80-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-125"><a href="#cb80-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb80-126"><a href="#cb80-126" aria-hidden="true" tabindex="-1"></a>The Pearson correlation test is a statistical test used to measure the linear relationship between two continuous variables.The Spearman's rank correlation coefficient (rho) measures the strength and direction of the association between two variables which don't have to be both continuous or have a linear relationship. It ranges between -1 and 1, where -1 indicates a perfect negative correlation, 1 indicates a perfect positive correlation, and 0 indicates no correlation.</span>
<span id="cb80-127"><a href="#cb80-127" aria-hidden="true" tabindex="-1"></a>Due to the High p value of both test, the depression rate is less likely related to BMI. </span>
<span id="cb80-128"><a href="#cb80-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-129"><a href="#cb80-129" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2. higher family income increase the rate of obesity</span></span>
<span id="cb80-132"><a href="#cb80-132" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-133"><a href="#cb80-133" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> FS, <span class="at">y =</span> BMI)) <span class="sc">+</span></span>
<span id="cb80-134"><a href="#cb80-134" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb80-135"><a href="#cb80-135" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb80-136"><a href="#cb80-136" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>FS, data<span class="sc">$</span>BMI,<span class="at">method =</span> <span class="fu">c</span>(<span class="st">"spearman"</span>))</span>
<span id="cb80-137"><a href="#cb80-137" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>FS, data<span class="sc">$</span>BMI,<span class="at">method =</span> <span class="fu">c</span>(<span class="st">"pearson"</span>))</span>
<span id="cb80-138"><a href="#cb80-138" aria-hidden="true" tabindex="-1"></a>fit2<span class="ot">&lt;-</span><span class="fu">lm</span>(FS <span class="sc">~</span> BMI, <span class="at">data =</span> data)</span>
<span id="cb80-139"><a href="#cb80-139" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span>
<span id="cb80-140"><a href="#cb80-140" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb80-141"><a href="#cb80-141" aria-hidden="true" tabindex="-1"></a>No significant corelationship on family financial status and obesity. </span>
<span id="cb80-142"><a href="#cb80-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-143"><a href="#cb80-143" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3. More sibling reduce the risk of both depression and anxiety. </span></span>
<span id="cb80-146"><a href="#cb80-146" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-147"><a href="#cb80-147" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> NS, <span class="at">y =</span> T1depression)) <span class="sc">+</span></span>
<span id="cb80-148"><a href="#cb80-148" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb80-149"><a href="#cb80-149" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb80-150"><a href="#cb80-150" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>T1depression,data<span class="sc">$</span>NS, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"spearman"</span>))</span>
<span id="cb80-151"><a href="#cb80-151" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>T1depression,data<span class="sc">$</span>NS, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"pearson"</span>))</span>
<span id="cb80-152"><a href="#cb80-152" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>NS <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>NS)</span>
<span id="cb80-153"><a href="#cb80-153" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(T1depression <span class="sc">~</span> NS, <span class="at">data =</span> data)</span>
<span id="cb80-154"><a href="#cb80-154" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb80-155"><a href="#cb80-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-156"><a href="#cb80-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-157"><a href="#cb80-157" aria-hidden="true" tabindex="-1"></a>In this case, the sample estimate of the correlation coefficient (rho) is 0.1184734, indicating a positive correlation between T0depression and NS. However, the p-value of the test is 0.008575, which is less than 0.05, suggesting that the correlation is statistically significant at a 5% level of significance.</span>
<span id="cb80-158"><a href="#cb80-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-159"><a href="#cb80-159" aria-hidden="true" tabindex="-1"></a>Therefore, we can conclude that there is a significant positive correlation between the number of siblings (NS) and the degree of depression  in this dataset.</span>
<span id="cb80-160"><a href="#cb80-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-161"><a href="#cb80-161" aria-hidden="true" tabindex="-1"></a>By carrying out a Welch t-test, the group with more siblings have higher depression index and p value &lt;0.05 indicates the result is siginifcant. (Not sure why the confident interval is negtive and none of the data was negative. )</span>
<span id="cb80-162"><a href="#cb80-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-165"><a href="#cb80-165" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-166"><a href="#cb80-166" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data<span class="sc">$</span>NS)</span>
<span id="cb80-167"><a href="#cb80-167" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> NS, <span class="at">y =</span> T1anxiety)) <span class="sc">+</span></span>
<span id="cb80-168"><a href="#cb80-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb80-169"><a href="#cb80-169" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb80-170"><a href="#cb80-170" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>NS <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data<span class="sc">$</span>NS)</span>
<span id="cb80-171"><a href="#cb80-171" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>T1anxiety,data<span class="sc">$</span>NS, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"spearman"</span>))</span>
<span id="cb80-172"><a href="#cb80-172" aria-hidden="true" tabindex="-1"></a>fit3<span class="ot">&lt;-</span><span class="fu">lm</span>(T1anxiety <span class="sc">~</span> NS, <span class="at">data =</span> data)</span>
<span id="cb80-173"><a href="#cb80-173" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit3)</span>
<span id="cb80-174"><a href="#cb80-174" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb80-175"><a href="#cb80-175" aria-hidden="true" tabindex="-1"></a><span class="fu">### others</span></span>
<span id="cb80-178"><a href="#cb80-178" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-179"><a href="#cb80-179" aria-hidden="true" tabindex="-1"></a><span class="co"># Create sample data</span></span>
<span id="cb80-180"><a href="#cb80-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-181"><a href="#cb80-181" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>BMI<span class="sc">~</span>data<span class="sc">$</span>T1depression)</span>
<span id="cb80-182"><a href="#cb80-182" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>T1depression<span class="sc">~</span>data<span class="sc">$</span>FL)</span>
<span id="cb80-183"><a href="#cb80-183" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BMI_category <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>BMI, </span>
<span id="cb80-184"><a href="#cb80-184" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">18.5</span>, <span class="fl">24.9</span>, <span class="fl">29.9</span>, <span class="cn">Inf</span>),</span>
<span id="cb80-185"><a href="#cb80-185" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal weight"</span>, <span class="st">"Overweight"</span>, <span class="st">"Obesity"</span>))</span>
<span id="cb80-186"><a href="#cb80-186" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Depression_category <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>T1depression, </span>
<span id="cb80-187"><a href="#cb80-187" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">45</span>, <span class="dv">59</span>,<span class="dv">74</span>,<span class="dv">75</span>),</span>
<span id="cb80-188"><a href="#cb80-188" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Mild"</span>, <span class="st">"Moderate to Marked Major"</span>, <span class="st">"Severe or Extreme Major"</span>))</span>
<span id="cb80-189"><a href="#cb80-189" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the bar chart</span></span>
<span id="cb80-190"><a href="#cb80-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-191"><a href="#cb80-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-192"><a href="#cb80-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-193"><a href="#cb80-193" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb80-194"><a href="#cb80-194" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb80-195"><a href="#cb80-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-196"><a href="#cb80-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-197"><a href="#cb80-197" aria-hidden="true" tabindex="-1"></a><span class="fu">## Answers to the feedbacks on check in 1</span></span>
<span id="cb80-198"><a href="#cb80-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-199"><a href="#cb80-199" aria-hidden="true" tabindex="-1"></a>Here are a few things you may want to work on in future steps:</span>
<span id="cb80-200"><a href="#cb80-200" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Please provide more information of the dataset: what each variable means (e.g. WC, HC, SBP etc) and how it is measured. This is to make sure audiences understand your confounders.</span>
<span id="cb80-201"><a href="#cb80-201" aria-hidden="true" tabindex="-1"></a>  a table with explaination of abrivation is updated in data description</span>
<span id="cb80-202"><a href="#cb80-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-203"><a href="#cb80-203" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Since gender is one of your key predictors, you may consider using the interaction between gender and other key variables in the model to see whether gender influences the impact of other predictors. Also, seem I didn't find the gender variable in the dataset you provided?</span>
<span id="cb80-204"><a href="#cb80-204" aria-hidden="true" tabindex="-1"></a>  Thanks for pointing out. Since gender is missiong, I will not use gender as a key predicor. </span>
<span id="cb80-205"><a href="#cb80-205" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb80-206"><a href="#cb80-206" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>As you mentioned, there are some outliers in the data, especially the one on the top-right corner. This outlier can change the slope of the regression. Also, the relationship between BMI and depression is not very clear in the graph, as you mentioned, more data processing is needed. You can also try plotting different groups (e.g. gender, family location) in different colors to see if there's any pattern.</span>
<span id="cb80-207"><a href="#cb80-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-208"><a href="#cb80-208" aria-hidden="true" tabindex="-1"></a>Thanks for the comments, I will try to process the data this time  and plot more patterns. </span>
<span id="cb80-209"><a href="#cb80-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-210"><a href="#cb80-210" aria-hidden="true" tabindex="-1"></a><span class="fu">## Questions need to be addressed</span></span>
<span id="cb80-211"><a href="#cb80-211" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>the varibles such as family locations or education level can be expressed either as rank or ordinal, as drawed below,it is hard to find a correlationship with this kind of varibles. How can i explore the relationship between an ordinal varible and a continuous varible?</span>
<span id="cb80-214"><a href="#cb80-214" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-215"><a href="#cb80-215" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(data[<span class="fu">c</span>(<span class="st">"T1depression"</span>,<span class="st">"T1anxiety"</span>,<span class="st">"BMI"</span>,<span class="st">"FL"</span>, <span class="st">"NS"</span>, <span class="st">"TFE"</span>, <span class="st">"TME"</span>, <span class="st">"FEL"</span>)])</span>
<span id="cb80-216"><a href="#cb80-216" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(data[<span class="fu">c</span>(<span class="st">"T1depression"</span>,<span class="st">"T1anxiety"</span>, <span class="st">"MEL"</span>, <span class="st">"FS"</span>, <span class="st">"SL"</span>, <span class="st">"SB"</span>,<span class="st">"Vigorous"</span>,<span class="st">"Moderate"</span>)])</span>
<span id="cb80-217"><a href="#cb80-217" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb80-218"><a href="#cb80-218" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>as some of the continuous varibles can also converted to ordinal varibles, what would be some method or test good to find the relationship between them?</span>
<span id="cb80-221"><a href="#cb80-221" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb80-222"><a href="#cb80-222" aria-hidden="true" tabindex="-1"></a><span class="co">#convert continuous varibles into categorical varibles</span></span>
<span id="cb80-223"><a href="#cb80-223" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>FL1 <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1348</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, </span>
<span id="cb80-224"><a href="#cb80-224" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Rural"</span>, <span class="st">"Suburban"</span>, <span class="st">"Urban"</span>, <span class="st">"City"</span>, <span class="st">"Metropolis"</span>))</span>
<span id="cb80-225"><a href="#cb80-225" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BMI_category <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>BMI, </span>
<span id="cb80-226"><a href="#cb80-226" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">18.5</span>, <span class="fl">24.9</span>, <span class="fl">29.9</span>, <span class="cn">Inf</span>),</span>
<span id="cb80-227"><a href="#cb80-227" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal weight"</span>, <span class="st">"Overweight"</span>, <span class="st">"Obesity"</span>))</span>
<span id="cb80-228"><a href="#cb80-228" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Depression_category <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>T1depression, </span>
<span id="cb80-229"><a href="#cb80-229" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">45</span>, <span class="dv">59</span>,<span class="dv">74</span>,<span class="dv">75</span>),</span>
<span id="cb80-230"><a href="#cb80-230" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Mild"</span>, <span class="st">"Moderate to Marked Major"</span>, <span class="st">"Severe or Extreme Major"</span>))</span>
<span id="cb80-231"><a href="#cb80-231" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb80-232"><a href="#cb80-232" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> FL1, <span class="at">y =</span> BMI, <span class="at">fill =</span> BMI_category)) <span class="sc">+</span> </span>
<span id="cb80-233"><a href="#cb80-233" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb80-234"><a href="#cb80-234" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#1b9e77"</span>, <span class="st">"#d95f02"</span>, <span class="st">"#7570b3"</span>, <span class="st">"#e7298a"</span>)) <span class="sc">+</span></span>
<span id="cb80-235"><a href="#cb80-235" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Family location"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"BMI"</span>) <span class="sc">+</span> </span>
<span id="cb80-236"><a href="#cb80-236" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"BMI category and family location"</span>) <span class="sc">+</span></span>
<span id="cb80-237"><a href="#cb80-237" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb80-238"><a href="#cb80-238" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> FL1, <span class="at">y =</span> T1depression, <span class="at">fill =</span> Depression_category)) <span class="sc">+</span> </span>
<span id="cb80-239"><a href="#cb80-239" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>)</span>
<span id="cb80-240"><a href="#cb80-240" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>