{
  "hash": "134f030d9e610ab62c7572d54226276f",
  "result": {
    "markdown": "---\ntitle: \"Homework - 1\"\nauthor: \"Darron Bunt\"\ndescription: \"Homework assignment 1 - Darron Bunt\"\ndate: \"02/28/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n:::\n\n\n\n# Question 1\n\nUse the *LungCapData* to answer the following questions. (Hint: Using *dplyr*, especially\n*group_by()* and *summarize()* can help you answer the following questions relatively efficiently.)\n\n## A\n\nWhat does the distribution of *LungCap* look like? (Hint: Plot a histogram with probability density on the y axis)\n\nFirst, let's read in the data from the Excel file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLungCapData <- read_excel(\"_data/LungCapData.xls\")\n```\n:::\n\n\nThe distribution of LungCap looks as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(LungCapData$LungCap)\n```\n\n::: {.cell-output-display}\n![](HW1_DarronBunt_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe histogram suggests that the distribution is close to a normal distribution. Most of the observations are close to the mean, while very few observations are close to the margins (0 and 15).\n\n## B\n\nCompare the probability distribution of the *LungCap* with respect to Males and Females? (Hint:\nmake boxplots separated by gender using the *boxplot()* function)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a boxplot comparing LungCap for males and females\nboxplot(LungCap~Gender, data=LungCapData)\n```\n\n::: {.cell-output-display}\n![](HW1_DarronBunt_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe boxplot suggests that the median for lung capacity in males is slightly higher than that of females. The IQR for lung capacity in males is also slightly higher than that of females. The minimum value for females is lower than that of males, as is the maximum. All of this suggests that males are more likely to have a greater lung capacity than females. \n\n## C\n\nCompare the mean lung capacities for smokers and non-smokers. Does it make sense?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean lung capacity for smokers and non-smokers\nLungCapData %>%\n  group_by(Smoke) %>%\n  summarise_at(vars(LungCap),\n               list(LCap = mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  LCap\n  <chr> <dbl>\n1 no     7.77\n2 yes    8.65\n```\n:::\n:::\n\nThis suggests that the mean lung capacity for smokers is greater than that of non-smokers. This is not what I would have expected given the (negative) impact that smoking has on the lungs. \n\n## D\n\nExamine the relationship between Smoking and Lung Capacity within age groups: “less than or\nequal to 13”, “14 to 15”, “16 to 17”, and “greater than or equal to 18”.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a new variable, AgeGroup, using the parameters outlined above\nAgeSmokeLC <- LungCapData %>%\n mutate(\n   AgeGroup = case_when(\n     Age <= 13 ~ \"13 and Under\",\n     Age == 14 | Age == 15 ~ \"14-15\",\n     Age == 16 | Age == 17 ~ \"16-17\", \n     Age >= 18 ~ \"18 and Over\")) \n\n# Calculate the mean lung capacity for smokers and non-smokers in each age group  \n  AgeSmokeLCMean <- AgeSmokeLC %>%\n    group_by(AgeGroup, Smoke) %>%\n  summarise_at(vars(LungCap),\n               list(MeanLungCap = mean)) %>%\n  arrange(desc(MeanLungCap))\nAgeSmokeLCMean\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 3\n# Groups:   AgeGroup [4]\n  AgeGroup     Smoke MeanLungCap\n  <chr>        <chr>       <dbl>\n1 18 and Over  no          11.1 \n2 18 and Over  yes         10.5 \n3 16-17        no          10.5 \n4 16-17        yes          9.38\n5 14-15        no           9.14\n6 14-15        yes          8.39\n7 13 and Under yes          7.20\n8 13 and Under no           6.36\n```\n:::\n:::\n\n\nThis suggests that lung capacity increases with age; the mean lung capacity for each subsequent age category is greater than the one before it. Individuals aged 13 and under who smoke have a greater mean lung capacity than those who do not; however, at ages 14-15, 16-17, and 18+,   non-smokers have a greater lung capacity than their similarly aged smoking counterparts.\n\n## E\n\nCompare the lung capacities for smokers and non-smokers within each age group. Is your answer\ndifferent from the one in part c. What could possibly be going on here?\n\nFrom the age group data above, we can ascertain that in the majority of age groups (three of the four), non-smokers have greater mean lung capacity than smokers, and yet when we calculated the mean lung capacity solely for smokers/non-smokers (ie. not accounting for age), smokers had greater mean lung capacity. The mean lung capacities for smokers/non-smokers (again, not accounting for age) are also lower than one might expect considering that when we do account for age, most of the represented groups have a higher mean lung capacity. This would suggest that something is skewing our results. \n\nOne way to gain insight into this is to examine how many respondents fell into each age/smoking status category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count number of responses in each age group who are smokers/non-smokers\nAgeSmokeLC %>%\n  count(AgeGroup, Smoke)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 3\n  AgeGroup     Smoke     n\n  <chr>        <chr> <int>\n1 13 and Under no      401\n2 13 and Under yes      27\n3 14-15        no      105\n4 14-15        yes      15\n5 16-17        no       77\n6 16-17        yes      20\n7 18 and Over  no       65\n8 18 and Over  yes      15\n```\n:::\n:::\n\n\nThere are more non-smoking individuals aged 13 and Under in this sample than all other categories combined. Accordingly, data from this group can (and has) skewed the overall non-smoking mean.  \n\n# Question 2\n\nLet X = number of prior convictions for prisoners at a state prison at which there are 810\nprisoners.\n\nX         0    1    2 3   4\nFrequency 128 434 160 64 24\n\nFirst, I need to turn the above into a data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create data frame for above data\nPriorConvictions <- data.frame(PriorConv=0:4, Inmates = c(128, 434, 160, 64, 24))\nPriorConvictions\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  PriorConv Inmates\n1         0     128\n2         1     434\n3         2     160\n4         3      64\n5         4      24\n```\n:::\n:::\n\n## A\n\nWhat is the probability that a randomly selected inmate has exactly 2 prior convictions?\n\nTo answer this question, we are going to need to know the total number of inmates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Find total number of inmates\nsum(PriorConvictions$Inmates)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 810\n```\n:::\n:::\n\nTo calculate this probability we are going calculate the binomial distribution. For this, we require three main arguments: \nx - the number specifying the outcomes you're trying to calculate (for this question, x=1)\nsize - the size of the experiment (for this question, size=1)\nprob - the probability of success for any one trial in the experiment (for this question, prob = the total number of inmates with two convictions / the total number of inmates, or 160/810)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate probability of randomly selecting an inmate with two prior convictions\ndbinom(x=1, size=1, prob=(160/810))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1975309\n```\n:::\n:::\n\nThe probability of randomly selecting an inmate with two prior convictions is roughly 19.8%. \n\n## B\n\nWhat is the probability that a randomly selected inmate has fewer than 2 prior convictions?\n\nHaving fewer than two prior convictions would mean that the inmate could either have zero or one prior convictions.\n\nx = 1\nsize = 1\nprob = ((the total number of inmates with no prior convictions + inmates with 1 conviction) / the total number of inmates, or ((128 + 434)/810), or 562/810.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate probability of randomly selecting an inmate with less than two prior convictions\ndbinom(x=1, size=1, prob=(562/810))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\nThe probability of randomly selecting an inmate with fewer than two prior convictions is roughly 69.4%. \n\n## C\n\nWhat is the probability that a randomly selected inmate has 2 or fewer prior convictions?\n\nHaving two or fewer prior convictions would mean that the inmate could either have zero, one, or two prior convictions.\n\nx = 1\nsize = 1\nprob = ((the total number of inmates with no prior convictions + inmates with 1 conviction + inmates with 2 convictions) / the total number of inmates, or ((128 + 434 + 160)/810), or 722/810.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate probability of randomly selecting an inmate with two or fewer prior convictions\ndbinom(x=1, size=1, prob=(722/810))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\nThe probability of randomly selecting an inmate with two or fewer prior convictions is roughly 89.1%. \n\n## D\n\nWhat is the probability that a randomly selected inmate has more than 2 prior convictions?\n\nHaving more than two prior convictions would mean that the inmate could either have three or four prior convictions.\n\nx = 1\nsize = 1\nprob = ((the total number of inmates with 3 convictions + inmates with 4 convictions) / the total number of inmates, or ((64+24)/810), or 88/810.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate probability of randomly selecting an inmate with more than two prior convictions\ndbinom(x=1, size=1, prob=(88/810))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\nThe probability of randomly selecting an inmate with more than two prior convictions is roughly 10.9%. \n\n## E\n\nWhat is the expected value for the number of prior convictions? (The expected value of a discrete random variable X, symbolized as E(X), is often referred to as the long-term\naverage or mean)\n\nIn order to calculate the expected value for the number of prior convictions, we will need to use the proportional breakdown of the number of inmates with each number of convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate proportion of inmates with 0,1,2,3,4 convictions\nPriorConvictionsProp <- PriorConvictions %>%\n  mutate(Proportion = Inmates/810)\nPriorConvictionsProp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  PriorConv Inmates Proportion\n1         0     128 0.15802469\n2         1     434 0.53580247\n3         2     160 0.19753086\n4         3      64 0.07901235\n5         4      24 0.02962963\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the expected value for prior number of convictions\nExpValue <- sum(PriorConvictionsProp$PriorConv*PriorConvictionsProp$Proportion)\nExpValue\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\nThe expected value is 1.29 prior convictions.\n\n## F\n\nCalculate the variance and the standard deviation for the Prior Convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the variance for prior convictions\nPriorConvVar <- sum((PriorConvictionsProp$PriorConv - ExpValue) ^ 2 * PriorConvictionsProp$Proportion)\nPriorConvVar\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8562353\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the standard deviation for prior convictions\nPriorConvSTD <- sqrt(PriorConvVar)\nPriorConvSTD\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9253298\n```\n:::\n:::",
    "supporting": [
      "HW1_DarronBunt_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}