{
  "hash": "8dfd986118a76beb837ab2af6f401ce9",
  "result": {
    "markdown": "---\ntitle: \"HW_4_Diana_Rinker\"\nauthor: \"Diana_Rinker\"\neditor: visual\n---\n\n\n------------------------------------------------------------------------\n\n# DACSS 603, spring 2023\n\n# Homework 4, Diana Rinker.\n\nLoading necessary libraries:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'car'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: effects\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\ndata(UN11)\n```\n:::\n\n\n# Question 1\n\nFor recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.\n\nA. A particular home of 1240 square feet on a lot of 18,000 square feet sold for \\$145,000. Find the predicted selling price and the residual, and interpret.\n\nB. For fixed lot size, how much is the house selling price predicted to increase for each square- foot increase in home size? Why?\n\nC. According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?\n\n## A.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx1<- 1240\nx2 <- 18000 \npredicted.price <- (-10536) + 53.8*x1 + 2.84*x2\nresidual <- predicted.price - 145000\ntable <- cbind( c(\"prediciton\", \"residual\"), c(predicted.price,residual))\nknitr::kable(table) \n```\n\n::: {.cell-output-display}\n|           |       |\n|:----------|:------|\n|prediciton |107296 |\n|residual   |-37704 |\n:::\n:::\n\n\nThe residual is negative, meaning that the model underestimated house price.\n\n## B.\n\nŷ = −10,536 + 53.8x1 + 2.84x2. If X2 is fixed, Y increases by 53.8 dollars per each square foot increase. The coeeficient of X1 indicates increase in Y with the change of X1, if the other variables kept the same.\n\n## C.\n\nTo increase Y by 53.8, X2 would need to increase by 53.8/2.84 = 8.94366.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx2.incr<- 53.8/2.84\nx2.incr\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\n# Question 2\n\n(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.\n\n## A.\n\nTest the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(salary)\nstr(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t52 obs. of  6 variables:\n $ degree: Factor w/ 2 levels \"Masters\",\"PhD\": 1 1 1 1 2 1 2 1 2 2 ...\n $ rank  : Factor w/ 3 levels \"Asst\",\"Assoc\",..: 3 3 3 3 3 3 3 3 3 3 ...\n $ sex   : Factor w/ 2 levels \"Male\",\"Female\": 1 1 1 2 1 1 2 1 1 1 ...\n $ year  : int  25 13 10 7 19 16 0 16 13 13 ...\n $ ysdeg : int  35 22 23 27 30 21 32 18 30 31 ...\n $ salary: int  36350 35350 28200 26775 33696 28516 24900 31909 31850 32850 ...\n```\n:::\n:::\n\n\nFirst, I will make sure that variances in male and female groups are equal:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$sex\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] Male   Male   Male   Female Male   Male   Female Male   Male   Male  \n[11] Male   Male   Male   Male   Male   Male   Male   Male   Male   Male  \n[21] Male   Male   Male   Female Male   Male   Male   Female Male   Male  \n[31] Female Male   Male   Female Female Male   Female Male   Male   Male  \n[41] Male   Male   Male   Female Male   Male   Female Female Male   Female\n[51] Female Female\nLevels: Male Female\n```\n:::\n\n```{.r .cell-code}\nMale <- subset(salary, sex == \"Male\")\nFemale<- subset(salary, sex == \"Female\")\nvar.test(Male$salary, Female$salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tF test to compare two variances\n\ndata:  Male$salary and Female$salary\nF = 0.84242, num df = 37, denom df = 13, p-value = 0.6525\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.3015275 1.9189474\nsample estimates:\nratio of variances \n         0.8424225 \n```\n:::\n:::\n\n\nP\\>0.05 means that the variances of thwo samples can be considered equal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$sex\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] Male   Male   Male   Female Male   Male   Female Male   Male   Male  \n[11] Male   Male   Male   Male   Male   Male   Male   Male   Male   Male  \n[21] Male   Male   Male   Female Male   Male   Male   Female Male   Male  \n[31] Female Male   Male   Female Female Male   Female Male   Male   Male  \n[41] Male   Male   Male   Female Male   Male   Female Female Male   Female\n[51] Female Female\nLevels: Male Female\n```\n:::\n\n```{.r .cell-code}\nMale <- subset(salary, sex == \"Male\")\nFemale<- subset(salary, sex == \"Female\")\nt.test(Male$salary, Female$salary, var.equal=T, Alternative=\"two.soded\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Male$salary and Female$salary\nt = 1.8474, df = 50, p-value = 0.0706\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -291.257 6970.550\nsample estimates:\nmean of x mean of y \n 24696.79  21357.14 \n```\n:::\n:::\n\n\nThe p-value of a t-test is above 0.05, which means that we accept H0 that the means of these two groups ere the same.\n\n## B.\n\nRun a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t52 obs. of  6 variables:\n $ degree: Factor w/ 2 levels \"Masters\",\"PhD\": 1 1 1 1 2 1 2 1 2 2 ...\n $ rank  : Factor w/ 3 levels \"Asst\",\"Assoc\",..: 3 3 3 3 3 3 3 3 3 3 ...\n $ sex   : Factor w/ 2 levels \"Male\",\"Female\": 1 1 1 2 1 1 2 1 1 1 ...\n $ year  : int  25 13 10 7 19 16 0 16 13 13 ...\n $ ysdeg : int  35 22 23 27 30 21 32 18 30 31 ...\n $ salary: int  36350 35350 28200 26775 33696 28516 24900 31909 31850 32850 ...\n```\n:::\n\n```{.r .cell-code}\nsummary ( lm(salary ~ degree + rank + sex + year +ysdeg , data = salary ))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nConfidence interval for the difference in salary between males and females:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(model, \"sexMale\", level = 0.95)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in confint(model, \"sexMale\", level = 0.95): object 'model' not found\n```\n:::\n:::\n\n\n## C.\n\nInterpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t52 obs. of  6 variables:\n $ degree: Factor w/ 2 levels \"Masters\",\"PhD\": 1 1 1 1 2 1 2 1 2 2 ...\n $ rank  : Factor w/ 3 levels \"Asst\",\"Assoc\",..: 3 3 3 3 3 3 3 3 3 3 ...\n $ sex   : Factor w/ 2 levels \"Male\",\"Female\": 1 1 1 2 1 1 2 1 1 1 ...\n $ year  : int  25 13 10 7 19 16 0 16 13 13 ...\n $ ysdeg : int  35 22 23 27 30 21 32 18 30 31 ...\n $ salary: int  36350 35350 28200 26775 33696 28516 24900 31909 31850 32850 ...\n```\n:::\n\n```{.r .cell-code}\nsummary ( lm(salary ~ degree + rank + sex + year +ysdeg , data = salary ))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\ndegree: shows no significance in the model (p-value is above 0.05), meaning that this variable cannot explain or predict salary. Rank variable shows high level of significance for all of its three levels (p-value lower than 0.0001), meaning that the rank influences the salary. The rank of the professor increases the salary twice more than the rank of the Associate professor.\n\nSex variable with two levels (male and female) has no significance and therefore does not contribute to the salary value.\n\nYear shows high significance (low p-value), but has the lowest coefficient to the salary value.\n\nYsdeg shows no significance and therefore does not contribute to the salary.\n\n## D.\n\nChange the baseline category for the rank variable. Interpret the coefficients related to rank again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t52 obs. of  6 variables:\n $ degree: Factor w/ 2 levels \"Masters\",\"PhD\": 1 1 1 1 2 1 2 1 2 2 ...\n $ rank  : Factor w/ 3 levels \"Asst\",\"Assoc\",..: 3 3 3 3 3 3 3 3 3 3 ...\n $ sex   : Factor w/ 2 levels \"Male\",\"Female\": 1 1 1 2 1 1 2 1 1 1 ...\n $ year  : int  25 13 10 7 19 16 0 16 13 13 ...\n $ ysdeg : int  35 22 23 27 30 21 32 18 30 31 ...\n $ salary: int  36350 35350 28200 26775 33696 28516 24900 31909 31850 32850 ...\n```\n:::\n\n```{.r .cell-code}\nlevels(salary$rank)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Asst\"  \"Assoc\" \"Prof\" \n```\n:::\n\n```{.r .cell-code}\nsalary$rank <- relevel(salary$rank, ref = \"Prof\")\nsummary ( lm(salary ~ degree + rank + sex + year +ysdeg , data = salary ))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nsexFemale     1166.37     925.57   1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nI used relevel() function tochange base cathegory for Rank from Asssistant to Professor. Now we can see that ssostant professor earns on average \\$11118 less than professor, and Associate makes \\$5826 less than professor.\n\n## E.\n\nFinkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, \"\\[a\\] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be 'tainted.'\" Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.\n\nExclude the variable rank, refit, and summarize how your findings changed, if they did.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# first, I return value \"Asst\" to be baseline, because it has smallest salaries. \nlevels(salary$rank)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Prof\"  \"Asst\"  \"Assoc\"\n```\n:::\n\n```{.r .cell-code}\nsalary$rank <- relevel(salary$rank, ref = \"Asst\")\n\n#excluding rank from the model \nsummary ( lm(salary ~ degree + sex + year +ysdeg , data = salary ))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\n\nOnce I excluded rank from the model, the variable sex became significant. I interpret it, as the variable rank was taking \"covering\" variable sex. It the previous model rank had very high significance, and now \"sex\" became significant, supporting Finkelstein's hypothesis.\n\n## F.\n\nEveryone in this dataset was hired the year they earned their highest degree.\n\nysdeg = time since hired\n\nIt is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean.\n\nseparate thos who been hired by him ysdeg \\<=15 yrs - \\> two groups compare\n\nSome people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.\n\nCreate a new variable that would allow you to test this hypothesis and run another multiple regression model to test this.\n\nSelect variables carefully to make sure there is no multicollinearity.\n\nExplain why multicollinearity would be a concern in this case and how you avoided it.\n\nDo you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ysdeg = time since hired\nsalary<-salary%>%\n  mutate (new.hire = ifelse (ysdeg >15, 0, 1))\n```\n:::\n\n\nSince new.hire variable is derived from ysdeg, I will remove ysdeg from the model to avoid multicollinearity:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary ( lm(salary ~ degree + sex +  rank + year + new.hire, data = salary ))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + rank + year + new.hire, \n    data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3403.3 -1387.0  -167.0   528.2  9233.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 13328.38    1483.38   8.985 1.33e-11 ***\ndegreePhD     818.93     797.48   1.027   0.3100    \nsexFemale     907.14     840.54   1.079   0.2862    \nrankProf    11096.95    1191.00   9.317 4.54e-12 ***\nrankAssoc    4972.66     997.17   4.987 9.61e-06 ***\nyear          434.85      78.89   5.512 1.65e-06 ***\nnew.hire     2163.46    1072.04   2.018   0.0496 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2362 on 45 degrees of freedom\nMultiple R-squared:  0.8594,\tAdjusted R-squared:  0.8407 \nF-statistic: 45.86 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# old summary ( lm(salary ~ degree + sex + year +ysdeg , data = salary ))\n```\n:::\n\n\nThe model is showing significance for the new.hire variable, supporting the hypothesis tha tpeople hired by the new Dean are paid better.\n\n# Question 3\n\n(Data file: house.selling.price in smss R package)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(house.selling.price)\n```\n:::\n\n\n## A.\n\nUsing the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(house.selling.price)\nstr(house.selling.price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t100 obs. of  7 variables:\n $ case : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Taxes: int  3104 1173 3076 1608 1454 2997 4054 3002 6627 320 ...\n $ Beds : int  4 2 4 3 3 3 3 3 5 3 ...\n $ Baths: int  2 1 2 2 3 2 2 2 4 2 ...\n $ New  : int  0 0 0 0 0 1 0 1 0 0 ...\n $ Price: int  279900 146500 237700 200000 159900 499900 265500 289900 587000 70000 ...\n $ Size : int  2048 912 1654 2068 1477 3153 1355 2075 3990 1160 ...\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary (lm(Price~ Size + New, data = house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThe model is demostrating statisticsl significance of both independent variable, with the size variable having a better significance level. Size coefficient of 115 indicates that with an increase of size by square foot, the price of the house would increase by 116 dollars. \n\nAt the same time, the coefficient of \"New\" variable is much bgger than  Size, meaning that the the new house would be 57736 dollars more expencive than the old one of the same size. \n\n## B. \nReport and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.\n\nPrediction equation is: \nPrice = (116 * Size) + (57736 * New) \n\nto form separate equations for new and not new houses,  I will split dataset into two by the \"New\" variable: \n\n::: {.cell}\n\n```{.r .cell-code}\nnew.houses<- house.selling.price%>%\n  filter(New==1)\nold.houses<- house.selling.price%>%\n  filter(New==0)\nnew.model<- (lm(Price~ Size , data = new.houses))\nnew.model\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size, data = new.houses)\n\nCoefficients:\n(Intercept)         Size  \n  -100755.3        166.4  \n```\n:::\n\n```{.r .cell-code}\nold.model<- (lm(Price~ Size , data = old.houses))\nold.model\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size, data = old.houses)\n\nCoefficients:\n(Intercept)         Size  \n   -22227.8        104.4  \n```\n:::\n:::\n\n\nModel for New houses: \nprice =  166* Size\n\n\nModel for Old houses: \nprice =  104* Size\n\n\n## C. Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\nNew house of size 3000\n\n::: {.cell}\n\n```{.r .cell-code}\nSize<- 3000\nnew.house<- 166*Size \nnew.house\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 498000\n```\n:::\n:::\n\nOld house of size 3000\n\n::: {.cell}\n\n```{.r .cell-code}\nold.house <- 104*Size\nold.house\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 312000\n```\n:::\n:::\n\n\n## D. Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary (lm(Price~ Size + New +Size*New, data = house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New + Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nOnce we added interaction term between New and size, the significance of \"New\" variable disappeared. Instead, the interaction term appears to explain the change in price better, i.e. combination of size and newness of the house impacts the price. \n\n\n\n## E. Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhouse.selling.price<- house.selling.price%>%\n  mutate (predicted.price = predict(lm(Price~ Size + New +Size*New)))\n\nnew.houses<- house.selling.price%>%\n  filter(New==1)\nggplot(new.houses, mapping=aes(x=Size, y=predicted.price))+\n  geom_smooth(method=\"lm\")+\n  labs(title=\" Predicted selling price to the size for  new homes\", x=\"Size\", y=\"Predicted price\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](HW_4_Diana_Rinker_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n```{.r .cell-code}\nold.houses<- house.selling.price%>%\n  filter(New==0)\nggplot(old.houses, mapping=aes(x=Size, y=predicted.price))+\n  geom_smooth(method=\"lm\")+\n  labs(title=\" Predicted selling price to the size for old homes\", x=\"Size\", y=\"Predicted price\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](HW_4_Diana_Rinker_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n:::\n\n\n\n\n## F. Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\nNew:\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <-lm(Price~ Size + New +Size*New, data = house.selling.price)\n\npredicted1.y.new <- predict(model, newdata = data.frame(Size = 3000, New = 1))\npredicted1.y.new \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n398307.5 \n```\n:::\n:::\n\nOld: \n\n::: {.cell}\n\n```{.r .cell-code}\npredicted1.y.old <- predict(model, newdata = data.frame(Size = 3000, New = 0))\npredicted1.y.old \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n291087.4 \n```\n:::\n:::\n\n\n\n\n## G. Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted2.y.new <- predict(model, newdata = data.frame(Size = 1500, New = 1))\npredicted2.y.new \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n148776.1 \n```\n:::\n\n```{.r .cell-code}\npredicted2.y.old <- predict(model, newdata = data.frame(Size = 1500, New = 0))\npredicted2.y.old\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n134429.8 \n```\n:::\n:::\n\nThe difference in prices between old and new house for F (3000sq.f) is \n\n::: {.cell}\n\n```{.r .cell-code}\ndif.1 <- predicted1.y.new -predicted1.y.old \ndif.1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n107220.1 \n```\n:::\n:::\n\nThe difference in prices between old and new house for G (1500sq.f) is \n\n::: {.cell}\n\n```{.r .cell-code}\ndif.2 <- predicted2.y.new -predicted2.y.old \ndif.2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n14346.32 \n```\n:::\n:::\n\nApparently the difference between old and new houses of the same square footage is increasing with increase of size. \n\n\n\n\n## H. Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?\n\nClearly the model with interaction represents relationship better, because difference in prices of larger houses is bigger than difference in prices for smaller houses. \n\n\n\n\n",
    "supporting": [
      "HW_4_Diana_Rinker_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}