{
  "hash": "5cdd5d31beb3f441ef40bedd453e35a0",
  "result": {
    "markdown": "---\ntitle: \"Kristin Abijaoude_HW4\"\neditor: visual\ndate: \"04/22/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Hw4\n  - kristin abijaoude\n---\n\n\n# Question 1\n\nŷ = −10,536 + 53.8x1 + 2.84x2\n\ny = selling price of home (in dollars) x1 = size of home (in square feet) x2 = lot size (in square feet)\n\nA. particular home of 1240 square feet on a lot of 18,000 square feet sold for \\$145,000. Find the predicted selling price and the residual, and interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice = -10536 + (53.8 * 1240) + (2.84 * 18000)\nprint(price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n\n```{.r .cell-code}\nresidual = price - 145000\nprint(residual)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -37704\n```\n:::\n:::\n\n\nThe predicted price is `$107,296`, which is much under the `$145,000` price sold by `-$37,704`.\n\nB. For fixed lot size, how much is the house selling price predicted to increase for each square- foot increase in home size? Why?\n\nIt's `$53.80` for every 1x increase in square feet of the selling house, as shown in the equation as a coefficient of 1x.\n\nC. According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?\n\nYou need to increase the lot size by 18.94 sq feet to have the same impact as a one square foot increase.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# x1 / x2\n\nlot = 53.80 / 2.84\nprint(lot)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\n# Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: effects\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\ndata(salary, package = \"alr4\")\nhead(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   degree rank    sex year ysdeg salary\n1 Masters Prof   Male   25    35  36350\n2 Masters Prof   Male   13    22  35350\n3 Masters Prof   Male   10    23  28200\n4 Masters Prof Female    7    27  26775\n5     PhD Prof   Male   19    30  33696\n6 Masters Prof   Male   16    21  28516\n```\n:::\n:::\n\n\nA. Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex.\n\nWith a p-value of 0.09, we can conclude that the mean salary for both men and women is the same, thus accepting the null hypothesis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsex <- select(salary, c(sex))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in select(salary, c(sex)): could not find function \"select\"\n```\n:::\n\n```{.r .cell-code}\nsalary1 <-  select(salary, c(salary))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in select(salary, c(salary)): could not find function \"select\"\n```\n:::\n\n```{.r .cell-code}\nsex <- as.numeric(unlist(sex))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in unlist(sex): object 'sex' not found\n```\n:::\n\n```{.r .cell-code}\nsalary1 <- as.numeric(unlist(salary1))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in unlist(salary1): object 'salary1' not found\n```\n:::\n\n```{.r .cell-code}\nmean <- t.test(salary1 ~ sex, var.equal = FALSE, alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(predvars, data, env): object 'salary1' not found\n```\n:::\n\n```{.r .cell-code}\nprint(mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfunction (x, ...) \nUseMethod(\"mean\")\n<bytecode: 0x1173612d0>\n<environment: namespace:base>\n```\n:::\n:::\n\n\nB. Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(formula = salary ~ ., data = salary)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(model, 'sexFemale', level=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              2.5 %   97.5 %\nsexFemale -697.8183 3030.565\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(model, level=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\n\nC. Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables\n\n`degreePD` - This means that, all else being equal, PhD holders can expect to earn an average of `$1,388.60` more in salary.\n\n`rankAssoc` - Associate professors can expect to earn an average of `$5,292.40` more in salary.\n\n`rankProf` - Professors would earn an average of `$11,118.80` more in salary.\n\n`sexFemale` - Female faculty workers would earn an average of `$1,166.4` more in salary.\n\n`year` - The longer a faculty member works at a college, the more they earn in salary, with an average of `$476.30` in increase.\n\n`ysdeg` - However, if it's been several years since you earned your last degree, expect a decrease of `-$124.60` in salary on average.\n\nD. Change the baseline category for the rank variable. Interpret the coefficients related to rank again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank <- relevel(salary$rank, ref = \"Prof\")\nmodel2 <- lm(formula = salary ~ ., data = salary)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nsexFemale     1166.37     925.57   1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nIn the new model, we can see that assistant professors and associate professors lose an average of `-$11,118.80` and `-$5,826.40` in salary, respectively.\n\nE Removing `rank` from the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\n\nWhen removing `rank` from the equation, we can see a decrease in the average salary for PhD holders and female faculty members by `-$3,299.30` and `-$1,286.50`, respectively. In addition, the salary average for year is smaller than before, but it's still an increase. The biggest shift is `ysdeg` with `$339.40` increase in salary on average.\n\nF New variable, new hypothesis\n\nSome people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary <- salary %>%\n  mutate(ysdeg15 = ifelse(ysdeg <= 15, 1,0))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in salary %>% mutate(ysdeg15 = ifelse(ysdeg <= 15, 1, 0)): could not find function \"%>%\"\n```\n:::\n\n```{.r .cell-code}\nsalary\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    degree  rank    sex year ysdeg salary\n1  Masters  Prof   Male   25    35  36350\n2  Masters  Prof   Male   13    22  35350\n3  Masters  Prof   Male   10    23  28200\n4  Masters  Prof Female    7    27  26775\n5      PhD  Prof   Male   19    30  33696\n6  Masters  Prof   Male   16    21  28516\n7      PhD  Prof Female    0    32  24900\n8  Masters  Prof   Male   16    18  31909\n9      PhD  Prof   Male   13    30  31850\n10     PhD  Prof   Male   13    31  32850\n11 Masters  Prof   Male   12    22  27025\n12 Masters Assoc   Male   15    19  24750\n13 Masters  Prof   Male    9    17  28200\n14     PhD Assoc   Male    9    27  23712\n15 Masters  Prof   Male    9    24  25748\n16 Masters  Prof   Male    7    15  29342\n17 Masters  Prof   Male   13    20  31114\n18     PhD Assoc   Male   11    14  24742\n19     PhD Assoc   Male   10    15  22906\n20     PhD  Prof   Male    6    21  24450\n21     PhD  Asst   Male   16    23  19175\n22     PhD Assoc   Male    8    31  20525\n23 Masters  Prof   Male    7    13  27959\n24 Masters  Prof Female    8    24  38045\n25 Masters Assoc   Male    9    12  24832\n26 Masters  Prof   Male    5    18  25400\n27 Masters Assoc   Male   11    14  24800\n28 Masters  Prof Female    5    16  25500\n29     PhD Assoc   Male    3     7  26182\n30     PhD Assoc   Male    3    17  23725\n31     PhD  Asst Female   10    15  21600\n32     PhD Assoc   Male   11    31  23300\n33     PhD  Asst   Male    9    14  23713\n34     PhD Assoc Female    4    33  20690\n35     PhD Assoc Female    6    29  22450\n36 Masters Assoc   Male    1     9  20850\n37 Masters  Asst Female    8    14  18304\n38 Masters  Asst   Male    4     4  17095\n39 Masters  Asst   Male    4     5  16700\n40 Masters  Asst   Male    4     4  17600\n41 Masters  Asst   Male    3     4  18075\n42     PhD  Asst   Male    3    11  18000\n43 Masters Assoc   Male    0     7  20999\n44 Masters  Asst Female    3     3  17250\n45 Masters  Asst   Male    2     3  16500\n46 Masters  Asst   Male    2     1  16094\n47 Masters  Asst Female    2     6  16150\n48 Masters  Asst Female    2     2  15350\n49 Masters  Asst   Male    1     1  16244\n50 Masters  Asst Female    1     1  16686\n51 Masters  Asst Female    1     1  15000\n52 Masters  Asst Female    0     2  20300\n```\n:::\n\n```{.r .cell-code}\nmodel4 <- lm(formula = salary ~ degree + sex + year + ysdeg15, data = salary)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(predvars, data, env): object 'ysdeg15' not found\n```\n:::\n\n```{.r .cell-code}\nprint(model4)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in print(model4): object 'model4' not found\n```\n:::\n\n```{.r .cell-code}\ncor.test(salary$ysdeg, salary$ysdeg15)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in cor.test.default(salary$ysdeg, salary$ysdeg15): 'y' must be a numeric vector\n```\n:::\n:::\n\n\nI took out the `ysdeg` variable as they're too similar to the new variable I created `ysdeg15` to avoid multicollinearity.\n\nThe correlation is `-0.8434239`, in which we can reject that alternative hypothesis. In other words, there are no changes in salary average.\n\n# Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(smss)\ndata(\"house.selling.price\", package = \"smss\")\nhead(house.selling.price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  case Taxes Beds Baths New  Price Size\n1    1  3104    4     2   0 279900 2048\n2    2  1173    2     1   0 146500  912\n3    3  3076    4     2   0 237700 1654\n4    4  1608    3     2   0 200000 2068\n5    5  1454    3     3   0 159900 1477\n6    6  2997    3     2   1 499900 3153\n```\n:::\n:::\n\n\nA. Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselling <- lm(formula = Price ~ Size + New, data = house.selling.price)\nsummary(selling)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nA new house sells at `$57,736.30` more, while for every one square foot is sold at `$116.10`.\n\nB. Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.\n\ny = `-40,230` + `116.10`x1 + `57,736.30`x2\n\nC. Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\n\nA not new house would be sold at `$308,070`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice1 = -40230 + (116.10 * 3000) + (57736.30 * 0)\nprint(price1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 308070\n```\n:::\n:::\n\n\nD. Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselling2 <- lm(formula = Price ~ Size*New, data = house.selling.price)\nsummary(selling2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nE. Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# new\nprice2 = -22227.808 + (104.44 * 3000 ) - (78527.50 * 1) + (61.92 * 1)\nprice2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 212626.6\n```\n:::\n\n```{.r .cell-code}\n# not new \nprice3 = -22227.808 + (104.44 * 3000 ) + 61.92\nprice3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 291154.1\n```\n:::\n:::\n\n\nF. Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\n\nA new house would sell at `$212,626.60`, while a not new house would sell at `$291,154.10`.\n\nG. Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# new\nprice4 = -40230 + (116.10 * 1500) + (57736.30 * 1)\nprice4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 191656.3\n```\n:::\n\n```{.r .cell-code}\n# not new \nprice5 = -40230 + (116.10 * 1500) \nprice5\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 133920\n```\n:::\n:::\n\n\nA new house would sell at `$191,656.30`, less than the `$212,626.60` in Question F, and a not new house would sell at `$133,920`, also less than the `$291,154.10` in Question F as well.\n\nH. Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?\n\nI think the model without the interaction represents the relationship of size and newness to the outcome price because it's simpler, easier to interpret, and there is more statistical significance as opposed to the model with the interaction. Despite that, the RSS, R-square, and adjusted R-square are similar.\n",
    "supporting": [
      "Kristin_Abijaoude_HW4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}