{
  "hash": "7d1266d454c6bf48b820dbf534a5f26a",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Miguel Curiel\"\ndescription: \"Probability and descriptive statistics homework for DACSS 603.\"\ndate: \"02/20/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n# Question 1\n\n## a\n\nFirst, let's read in the data from the Excel file:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\ndf <- read_excel(\"_data/LungCapData.xls\")\n```\n:::\n\n\nThe distribution of LungCap looks as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df$LungCap)\n```\n\n::: {.cell-output-display}\n![](HW1_MiguelCuriel_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\nThe histogram suggests that the distribution is close to a normal distribution. Most of the observations are close to the mean. Very few observations are close to the margins (0 and 15).\n\n## b\n\nCompare the probability distribution of the LungCap with respect to Males and Females? \n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages(library(dplyr))\nboxplot(LungCap~Gender, data=df)\n```\n\n::: {.cell-output-display}\n![](HW1_MiguelCuriel_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\nThe boxplot suggests that males tend to have a slightly higher lung capacity than females. While the mean of both genders is close to each other (~8), males' interquartile range is slightly higher (approximately from 6.5 to 10) when compared to the females' (approximately from 6 to 9).\n\n## c\n\nCompare the mean lung capacities for smokers and non-smokers. Does it make sense?\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  group_by(Smoke) %>%\n  summarise(mean = mean(LungCap), n = n())\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 2 × 3\n  Smoke  mean     n\n  <chr> <dbl> <int>\n1 no     7.77   648\n2 yes    8.65    77\n```\n:::\n:::\n\nSmokers have a mean lung capacity of 8.65, versus non-smokers who have a lung capacity of 7.77. These results do not make sense, as we would expect non-smokers to have greater lung capacity.\n\n## d\n\nExamine the relationship between Smoking and Lung Capacity within age groups: \n“less than or equal to 13”, “14 to 15”, “16 to 17”, and “greater than or equal to 18”.\n\n::: {.cell}\n\n```{.r .cell-code}\nage_groups <- df %>% \n  mutate(\n    # Create categories\n    AgeGroup = case_when(\n      Age <= 13            ~ \"0 to 13\",\n      Age == 14 | Age == 15 ~ \"14 to 15\",\n      Age == 16 | Age == 17 ~ \"16 to 17\",\n      Age >= 18             ~ \"18 and above\"\n    ),\n    # Convert to factor\n    AgeGroup = factor(\n      AgeGroup,\n      level = c(\"0 to 13\", \"14 to 15\",\"16 to 17\", \"18 and above\")\n    )\n  )\n\nboxplot(LungCap~AgeGroup, data=age_groups)\n```\n\n::: {.cell-output-display}\n![](HW1_MiguelCuriel_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nThe boxplot suggests that the greater the age, the greater the lung capacity. This is especially evident when comparing the lowest age group (0-13) versus the rest of them, but between the two oldest age groups (16-17 vs 18+), this is the least evident. This makes sense as the greatest physical growth usually happens earlier in life - from childhood to puberty - but then this slows down in the late teens and it almost entirely stops during young adulthood.\n\n## e\n\nCompare the lung capacities for smokers and non-smokers within each age group. Is your answer different from the one in part c. What could possibly be going on here?\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nage_groups %>% ggplot(aes(x=AgeGroup, y=LungCap, fill=Smoke)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](HW1_MiguelCuriel_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nThe answer is different than what I found in 1.C. I previously found that the lung capacity mean for non-smokers was less than the smoking counterpart; however, this new box plot suggests that most non-smoking age groups actually have better lung capacity than smokers. The only age group where this condition isn't met is in the youngest ages (0-13) so it is likely that this group that is skewing the overall smoker versus non-smoker analysis.\n\n# Question 2\n\nLet X = number of prior convictions for prisoners at a state prison at which there are 810 prisoners.\n\nx = 0, 1, 2, 3, 4; \nfrequency = 128, 434, 160, 64, 24.\n\n## a\n\nWhat is the probability that a randomly selected inmate has exactly 2 prior convictions?\n\n160/810 = .1975 = 19.75%\n\n## b\n\nWhat is the probability that a randomly selected inmate has fewer than 2 prior convictions?\n\n(128+434)/810 = 562/810 = .6938 = 69.38%\n\n## c\n\nWhat is the probability that a randomly selected inmate has 2 or fewer prior convictions?\n\n(128+434+160)/810 = 722/810 = .8914 = 89.14%\n\n## d\n\nWhat is the probability that a randomly selected inmate has more than 2 prior convictions?\n\n(64+24)/810 = 88/810 = .1086 = 10.86%\n\n## e\n\nWhat is the expected value for the number of prior convictions?\n(The expected value of a discrete random variable X, symbolized as E(X), is often referred to as the long-term\naverage or mean)\n\n::: {.cell}\n\n```{.r .cell-code}\n(0*128/810) + (1*434/810) + (2*160/810) + (3*64/810) + (4*24/810) \n```\n\n::: {.cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n## f\n\nCalculate the variance and the standard deviation for the Prior Convictions.\n\nBelow is the variance:\n\n::: {.cell}\n\n```{.r .cell-code}\n((0-1.28642)^2 * 0) + ((1-1.28642)^2 * .5358) + ((2-1.28642)^2 * .395) + ((3-1.28642)^2 * .237) + ((4-1.28642)^2 * .1185)\n```\n\n::: {.cell-output-stdout}\n```\n[1] 1.813581\n```\n:::\n:::\n\nAnd below is the standard deviation:\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt(((0-1.28642)^2 * 0) + ((1-1.28642)^2 * .5358) + ((2-1.28642)^2 * .395) + ((3-1.28642)^2 * .237) + ((4-1.28642)^2 * .1185))\n```\n\n::: {.cell-output-stdout}\n```\n[1] 1.346693\n```\n:::\n:::\n",
    "supporting": [
      "HW1_MiguelCuriel_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": [],
    "engineDependencies": {},
    "preserve": {},
    "postProcess": null
  }
}