{
  "hash": "74ca0b8393e80f71240ad31dfa21c187",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Young Soo Choi\"\ndescription: \"hw1\"\ndate: \"02/27/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n\n# prepare\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.1     ✔ purrr   1.0.1\n✔ tibble  3.1.8     ✔ dplyr   1.1.0\n✔ tidyr   1.3.0     ✔ stringr 1.5.0\n✔ readr   2.1.4     ✔ forcats 1.0.0\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(readxl)\ndf <- read_excel(\"C:/Users/rotte/Documents/R/603_Spring_2023/posts/_data/LungCapData.xls\")\n```\n:::\n\n\n\n# Question 1\n\n## a\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# descriptive statistics\nsummary(df$LungCap)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.507   6.150   8.000   7.863   9.800  14.675 \n```\n:::\n\n```{.r .cell-code}\nsd(df$LungCap)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.662008\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# making histogram\nhist(df$LungCap)\n```\n\n::: {.cell-output-display}\n![](HW1_young_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nRange is 0.507~14.675. Median is 8.00. And it's distribution is looks like normal distribution that mean is 7.863 and sd is 2.662.\n\n## b\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# descriptive statistics\ndf %>%\n  group_by(Gender) %>%\n  summarise(mean(LungCap), sd(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  Gender `mean(LungCap)` `sd(LungCap)`\n  <chr>            <dbl>         <dbl>\n1 female            7.41          2.56\n2 male              8.31          2.68\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# making boxplot\nboxplot(LungCap~Gender, df)\n```\n\n::: {.cell-output-display}\n![](HW1_young_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nMean and sd of female's LungCap are 7.406 and 2.564, respectively. And Mean and sd of male's LungCap are 8.309 and 2.683, respectively. Male's LungCap is bigger than female's. We can also check this through boxplot.\n\n## c\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# finding lungcap for smokers and non-smokers\ndf %>% group_by(Smoke) %>%\n  summarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke `mean(LungCap)`\n  <chr>           <dbl>\n1 no               7.77\n2 yes              8.65\n```\n:::\n:::\n\n\nSmokers have bigger Lung cap. It's a different result from common sense. Through the t-test, I will find out whether this result is statistically significant.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(LungCap~Smoke, df, alternative=\"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  LungCap by Smoke\nt = -3.6498, df = 117.72, p-value = 0.0001964\nalternative hypothesis: true difference in means between group no and group yes is less than 0\n95 percent confidence interval:\n       -Inf -0.4776762\nsample estimates:\n mean in group no mean in group yes \n         7.770188          8.645455 \n```\n:::\n:::\n\nAs a result of the one-sided t-test, it was found to be statistically significant at the 95% level of significance.\n\n##d\n\nFirst, a new variable cAge is created and a new value is given for each age. For those under the age of 13, \"Child\", 14, 15 years of age \"Middle\", 16, 17 years of age \"High\", and 18 years of age or older, \"Adult\" will be assigned.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf<-mutate(df, cAge = ifelse(Age<=13, \"Child\", ifelse(Age %in% 14:15, \"Middle\", ifelse(Age %in% 16:17, \"High\", \"Adult\"))))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% group_by(cAge) %>%\n  summarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n  cAge   `mean(LungCap)`\n  <chr>            <dbl>\n1 Adult            11.0 \n2 Child             6.41\n3 High             10.2 \n4 Middle            9.05\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x=Age, y=LungCap)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](HW1_young_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nLooking at each group's lung caps, child is 6.41, middle is 9.05, high is 10.25, and adult is 10.96. That is, the lung caps grow with age. Here, it is possible to infer why the lung caps of smokers and non-smokers presented in this data are different from our common sense. The more adults there are, the more smokers there will be, and that may have led to a larger lung cap for smokers.\n\n##e\n\nFirst, let's look at the children's group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchilddf<-filter(df, cAge==\"Child\")\ntable(childdf$Smoke)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n no yes \n401  27 \n```\n:::\n\n```{.r .cell-code}\nchilddf%>%group_by(Smoke) %>%\n  summarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke `mean(LungCap)`\n  <chr>           <dbl>\n1 no               6.36\n2 yes              7.20\n```\n:::\n:::\n\n\nSmokers have bigger lung cap.\nLet's look at the picture in more detail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(childdf, aes(x=Age, y=LungCap)) +\n  geom_point(aes(col=factor(Smoke)))\n```\n\n::: {.cell-output-display}\n![](HW1_young_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nFrom the plot, the older the age, the larger the lung cap for non-smokers. In other words, when looking at the entire child group, the growth of natural lung caps with growth is not well revealed, so smokers' lung caps seem to be larger.\n\nNext, let's look at the middle group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmiddf<-filter(df, cAge==\"Middle\")\ntable(middf$Smoke)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n no yes \n105  15 \n```\n:::\n\n```{.r .cell-code}\nmiddf%>%group_by(Smoke) %>%\n  summarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke `mean(LungCap)`\n  <chr>           <dbl>\n1 no               9.14\n2 yes              8.39\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(LungCap~Smoke, middf)\n```\n\n::: {.cell-output-display}\n![](HW1_young_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nNon-smokers of middle group seem to have bigger lung caps.\n\nThen, let's look at the high group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhighdf<-filter(df, cAge==\"High\")\ntable(highdf$Smoke)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n no yes \n 77  20 \n```\n:::\n\n```{.r .cell-code}\nhighdf%>%group_by(Smoke) %>%\n  summarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke `mean(LungCap)`\n  <chr>           <dbl>\n1 no              10.5 \n2 yes              9.38\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(LungCap~Smoke, highdf)\n```\n\n::: {.cell-output-display}\n![](HW1_young_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\nNon-smokers of high group also have bigger lung caps.\n\nLastly, let me check the adult group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadultdf<-filter(df, cAge==\"Adult\")\ntable(adultdf$Smoke)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n no yes \n 65  15 \n```\n:::\n\n```{.r .cell-code}\nadultdf%>%group_by(Smoke) %>%\n  summarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke `mean(LungCap)`\n  <chr>           <dbl>\n1 no               11.1\n2 yes              10.5\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(LungCap~Smoke, adultdf)\n```\n\n::: {.cell-output-display}\n![](HW1_young_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\nEven in the adult group, non-smokers have a bigger lung cap.\n\nFinally, I took a look at the overall plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x=Age, y=LungCap)) +\n  geom_point(aes(col=factor(Smoke)))\n```\n\n::: {.cell-output-display}\n![](HW1_young_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nOverall, it seems that the lung cap of non-smokers (red) is higher than that of smokers (blue).\n\n# Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-c(0, 1, 2, 3, 4)\nfreq<-c(128, 434, 160, 64, 24)\np_df<-data.frame(x, freq)\np_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  x freq\n1 0  128\n2 1  434\n3 2  160\n4 3   64\n5 4   24\n```\n:::\n:::\n\n\n## a\n\nThe probability of selecting inmate has exact 2 priority convictions is the number of inmates with 2 priority convictions divided by the total number of inmates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n160/sum(p_df$freq)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1975309\n```\n:::\n:::\n\n\nThe answer is 0.1975.\n\n## b\n\nIn the same way, the frequency of 0 priority convictions and 1 priority convictions can be combined and divided into the total number of prisoners.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(128+434)/sum(p_df$freq)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\n\nThe answer is 0.6938.\n\n## c\n\nAdd the probabilities obtained from problems a and b to get the answer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(160/sum(p_df$freq))+((128+434)/sum(p_df$freq))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\n\nThe answer is 0.8914.\n\n## d\n\nThis time, we can get the answer using the probability obtained from c. The total sum of the probabilities is 1, so you can get the answer by subtracting the value obtained from 1 and c.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1-((160/sum(p_df$freq))+((128+434)/sum(p_df$freq)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\n\nThe answer is 0.1086.\n\n## e\n\nTo obtain the expected value, we divide the sum of priority convictions(x) times frequency (freq) by the total number of prisoners.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(p_df$x*p_df$freq)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\nIn another way, the probability of priority conversions can be obtained and the expected value can be obtained by summing each frequency multiplied by this value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_df<-mutate(p_df, pro=freq/810)\np_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  x freq        pro\n1 0  128 0.15802469\n2 1  434 0.53580247\n3 2  160 0.19753086\n4 3   64 0.07901235\n5 4   24 0.02962963\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(p_df$x*p_df$pro)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\nThe answer is the same.\n\n## f\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean<-sum(p_df$x*p_df$pro)\n```\n:::\n\n\nFirst, to obtain the variance, get the sum of the squared difference between the x-value and the average value (expected value) and divided by the total number of prisoners.\n\nThe standard deviation is the square root of the variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum((x-mean)^2*p_df$freq)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8562353\n```\n:::\n\n```{.r .cell-code}\nsqrt(sum((x-mean)^2*p_df$freq)/810)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9253298\n```\n:::\n:::\n\n\nVariance is 0.8562 and standard deviation is 0.925.\n\nAlternatively, the variance can be obtained by multiplying the square of the difference between the x-value and the average value by each probability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum((x-mean)^2*p_df$pro)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8562353\n```\n:::\n\n```{.r .cell-code}\nsqrt(sum((x-mean)^2*p_df$pro))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9253298\n```\n:::\n:::\n\n\nAs expected, the answer is the same.\n\n",
    "supporting": [
      "HW1_young_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}