{
  "hash": "cc72e12ef5df1f31cd00a40758ab9974",
  "result": {
    "markdown": "---\ntitle: \"Homework 5\"\nauthor: \"Guanhua Tan\"\ndescription: \"Homework 5\"\ndate: \"05/07/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw5\n  - regression analysis\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n\nLoading required package: effects\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n```\n:::\n\n\n# Question 1\nA. For backward elimination, which variable would be deleted first? Why?\n\nThe variable Beds would be deleted first because the p-value is greatest.\n\nB. For forward selection, which variable would be added first? Why?\n\nThe variable Size would be first added because the p-value is smallest.\n\nC. Why do you think that BEDS has such a large P-value in the multiple regression model,\neven though it has a substantial correlation with PRICE?\n\nI believe Beds is highly identical to Size, which causes the multicollinearity.\n\nD. Using software with these four predictors, find the model that would be selected using each\ncriterion:\n\n1. R2\n2. Adjusted R2\n3. PRESS\n4. AIC\n5. BIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"house.selling.price.2\")\nmodel_house <- lm(P~S+Be+Ba+New, data=house.selling.price.2)\nmodel_house_no_Be <- lm(P~S+Ba+New, data=house.selling.price.2)\n\n# Press\npr <- resid(model_house)/(1 - lm.influence(model_house)$hat)\nsum(pr^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 28390.22\n```\n:::\n\n```{.r .cell-code}\npr <- resid(model_house_no_Be)/(1 - lm.influence(model_house_no_Be)$hat)\nsum(pr^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 27860.05\n```\n:::\n\n```{.r .cell-code}\n# AIC\nbroom::glance(model_house)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squa…¹ sigma stati…²  p.value    df logLik   AIC   BIC devia…³\n      <dbl>        <dbl> <dbl>   <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>   <dbl>\n1     0.869        0.863  16.4    146. 5.94e-38     4  -389.  791.  806.  23553.\n# … with 2 more variables: df.residual <int>, nobs <int>, and abbreviated\n#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance\n```\n:::\n\n```{.r .cell-code}\nbroom::glance(model_house_no_Be)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squa…¹ sigma stati…²  p.value    df logLik   AIC   BIC devia…³\n      <dbl>        <dbl> <dbl>   <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>   <dbl>\n1     0.868        0.864  16.3    195. 4.96e-39     3  -390.  789.  802.  23684.\n# … with 2 more variables: df.residual <int>, nobs <int>, and abbreviated\n#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance\n```\n:::\n:::\n\nR2: model_house is 0.87; model_house_no_be is 0.87.\n\nAdjusted R2: model_house is 0.86; model_house_no_be is 0.86.\n\nPress:model_house is 28390.22; model_house_no_be is 27860.05.\n\nAIC: model_house is 790.6225; model_house_no_be is 789.1366.\n\nBIC: model_house is 805.8181; model_house_no_be is 801.7996.\n\nE Explain which model you prefer and why\n\nI'd like to prefer model_house_no_b because the AIC, BIC and Press are smaller than those of model_house.\n\n\n\n# Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"trees\")\nhead(trees)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Girth Height Volume\n1   8.3     70   10.3\n2   8.6     65   10.3\n3   8.8     63   10.2\n4  10.5     72   16.4\n5  10.7     81   18.8\n6  10.8     83   19.7\n```\n:::\n:::\n\n\nA. Fit a multiple regression model with the Volume as the outcome and Girth and Height as\nthe explanatory variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrees_model_1 <- lm(Volume~Girth+Height, data=trees)\nsummary(trees_model_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Volume ~ Girth + Height, data = trees)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.4065 -2.6493 -0.2876  2.2003  8.4847 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -57.9877     8.6382  -6.713 2.75e-07 ***\nGirth         4.7082     0.2643  17.816  < 2e-16 ***\nHeight        0.3393     0.1302   2.607   0.0145 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.882 on 28 degrees of freedom\nMultiple R-squared:  0.948,\tAdjusted R-squared:  0.9442 \nF-statistic:   255 on 2 and 28 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\n\nB. Run regression diagnostic plots on the model. Based on the plots, do you think any of the\nregression assumptions is violated?\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,3))\nplot(trees_model_1, which= 1:6)\n```\n\n::: {.cell-output-display}\n![](HW5_Guanhua_Tan_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nI have noted that several plots show clear patterns. the line shows curvature in thhe Residue and Fitted plot. The same shaple has been found in the Scale-location plot. Normal Q-Q demonstrates that points larele don't fall along the line.\n\n\n# Question 3\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"florida\")\nhead(florida)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           Gore   Bush Buchanan\nALACHUA   47300  34062      262\nBAKER      2392   5610       73\nBAY       18850  38637      248\nBRADFORD   3072   5413       65\nBREVARD   97318 115185      570\nBROWARD  386518 177279      789\n```\n:::\n:::\n\nA. Run a simple linear regression model where the Buchanan vote is the outcome and the\nBush vote is the explanatory variable. Produce the regression diagnostic plots. Is Palm Beach\nCounty an outlier based on the diagnostic plots? Why or why not?\n\n::: {.cell}\n\n```{.r .cell-code}\nvotes_2000 <-lm(Buchanan~Bush, data=florida)\nsummary(votes_2000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Buchanan ~ Bush, data = florida)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-907.50  -46.10  -29.19   12.26 2610.19 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 4.529e+01  5.448e+01   0.831    0.409    \nBush        4.917e-03  7.644e-04   6.432 1.73e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 353.9 on 65 degrees of freedom\nMultiple R-squared:  0.3889,\tAdjusted R-squared:  0.3795 \nF-statistic: 41.37 on 1 and 65 DF,  p-value: 1.727e-08\n```\n:::\n\n```{.r .cell-code}\npar(mfrow=c(2,3))\nplot(votes_2000, which= 1:6)\n```\n\n::: {.cell-output-display}\n![](HW5_Guanhua_Tan_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\nAccording to the Cook's distance plots, Palm Beach County is a outlier.\n\nB. Take the log of both variables (Bush vote and Buchanan Vote) and repeat the analysis in\n(A.) Does your findings change?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvotes_2000_trans <-lm(log(Buchanan)~log(Bush), data=florida)\npar(mfrow=c(2,3))\nplot(votes_2000_trans, which= 1:6)\n```\n\n::: {.cell-output-display}\n![](HW5_Guanhua_Tan_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nAccording to the Cook's distance of the new model, although it seems disclose more outlies, Palm Beach is still a significant one.\n",
    "supporting": [
      "HW5_Guanhua_Tan_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}