{
  "hash": "22915057d81ad629cd09bcb9d2275f31",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Young Soo Choi\"\ndescription: \"hw2\"\ndate: \"03/27/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n---\n\n\n# Prepare\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.1     ✔ purrr   1.0.1\n✔ tibble  3.1.8     ✔ dplyr   1.1.0\n✔ tidyr   1.3.0     ✔ stringr 1.5.0\n✔ readr   2.1.4     ✔ forcats 1.0.0\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n:::\n\n\n\n# Question 1\n\nIn order to obtain the confidence interval, first, a t-value of 90% confidence level must be obtained with the given statistics.\n\nFirst, I will look for the confidence interval of the bypass group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# t of the given bypass group\nbypass.t<-qt(p=0.95, df=539)\nbypass.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647686\n```\n:::\n:::\n\n\nThe confidence interval includes a section that falls margin of error from a specific predicted value, and this problem is to obtain the confidence interval of the mean, so the upper and lower limits of the confidence interval were obtained using the sample mean and the previously obtained t-value, respectively.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# confidence interval of bypass group\nbypass.conf.up<-19+bypass.t*(10/sqrt(539))\nbypass.conf.low<-19-bypass.t*(10/sqrt(539))\nbypass.conf.up\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 19.70971\n```\n:::\n\n```{.r .cell-code}\nbypass.conf.low\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029\n```\n:::\n:::\n\nNow let's look at the confidence interval of 90% of the angiography group in the same way.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# confidence interval of angiography group\n\nangio.t<-qt(p=0.95, df=847)\nangio.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.646655\n```\n:::\n\n```{.r .cell-code}\nangio.conf.up<-18+angio.t*(9/sqrt(847))\nangio.conf.low<-18-angio.t*(9/sqrt(847))\nangio.conf.up\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.50922\n```\n:::\n\n```{.r .cell-code}\nangio.conf.low\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078\n```\n:::\n:::\n\n\nFor a 90% confidence interval, a bypass group is from 18.29 to 19.71, an angiography group is from 17.49 to 18.51.\n\n## More\nRandom data were generated using the given statistics and each confidence interval was also obtained.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\nbypass.s<-rnorm(539, mean=19, sd=10)\nangio.s<-rnorm(847, mean=18, sd=9)\n\nt.test(bypass.s, conf.level = .9)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  bypass.s\nt = 44.184, df = 538, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n90 percent confidence interval:\n 18.44913 19.87842\nsample estimates:\nmean of x \n 19.16377 \n```\n:::\n\n```{.r .cell-code}\nt.test(angio.s, conf.level = .9)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  angio.s\nt = 54.954, df = 846, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n90 percent confidence interval:\n 17.15787 18.21788\nsample estimates:\nmean of x \n 17.68788 \n```\n:::\n:::\n\n\nThe statistics of the generated data did not exactly match the statistics given by the problem, so the exact same confidence interval was not obtained, but they are similar.\n\n# Question 2\n\nA data vector of 1 for those who believe that college education is essential for success and 0 for those who do not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq2<-c(rep(1, 567), rep(0,464))\n```\n:::\n\n\nThen, we can simply obtain a 95% confidence interval using the t.test function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(q2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  q2\nt = 35.477, df = 1030, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 0.5195334 0.5803696\nsample estimates:\nmean of x \n0.5499515 \n```\n:::\n:::\n\n\nAs a result of this survey, the proportion of people who believe that college education is important for success is 55.0%, and the 95% confidence interval is from 52.0% to 58.0%.\n\nWhen the significance level is 5%, the meaning of this confidence interval is that if the survey is conducted several times in the same way, there is a 95% probability that the confidence interval calculated from each survey result contains the parameter within that range.\n\n# Question 3\n\nDepending on the value given in the problem, the population standard deviation is 42.5 (170/4), and the allowable margin of error is 5. And margin of error can be obtained by z*sd/(n^1/2).\nSo n can be obtained by solving the following equation.\n   margin of error =< z*sd(n^1/2)\ntransform that equation,\n   n >= (z*sd/margin of error)^2\n   \nThe significance level here is 5%, so z is 1.96. And sd is 42.5 margin of error is 5. \nThen n >= (1.96*42.5/5)^2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(1.96*42.5/5)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\n\nn >= 277.56, In other words, the number of samples must exceed 278 to meet the conditions in question.\n\n# Question 4\n\n## A\n\nFirst, assume that s in the population is equal to the sample in question. And the significance level is set at 5%.\n\nNull Hypothesis: μ = 500\nAlternative Hypothesis: μ ≠ 500\n\nSince it is a test that estimates whether the parameter is a specific value, a two-side t-test should be performed. At this time, t is ȳ - μ / s/(n^1/2).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.a<-((410-500)/(90/3))\nt.a\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\n\nt is -3. And since it is a two-side test, the p-value of this hypothesis can be obtained by multiplying the p-value at t=-3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np.a<-(pt(t.a, df=8))*2\np.a\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\np-value is 0.017. And this is smaller than our significant level(0.05). So, we can reject our null hypothesis. This means that At the 95% confidence level, μ is not 500.\n\n## B\n\nHere, the null hypothesis is μ >= 500. Then, the alternative hypothesis is μ < 500. In this case, a one-sided test shall be performed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.b<--3\np.b<-pt(t.b, df=8)\np.b\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nThe p-value can be obtained in the same way as A. Here, the value of p is 0.009. This means that at the 95% confidence level, μ is not greater than 500.\n\n## C\n\nHere, contrary to B, the the null hypothesis is μ =< 500. Since the direction of the inequality has changed, the area of the p value in the t-distribution must be opposite to B.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.c<--3\np.c<-(1-pt(t.c, df=8))\np.c\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nUsing these facts, the p-value is 0.9914. Now, at the 5% significance level, the null hypothesis cannot be rejected. That is, at a 95% confidence level, μ is less than 500.\n\n# Question 5\n\n## A\n\nt is (ȳ-μ) / (sd/sqrt(n)). And sd/sqrt(n) is se. So we can compute t through this equation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Jones's t and p-value\njones.t<-(519.5-500)/10\njones.p<-(1-pt(jones.t, df=999))*2\njones.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\njones.p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Smith's t and p-value\nsmith.t<-(519.7-500)/10\nsmith.p<-(1-pt(smith.t, df=999))*2\nsmith.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\nsmith.p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n## B\n\nα is a level arbitrarily set according to the researcher's judgment, and does not affect the t or p-value of each hypothesis.\n\nThe p value means the probability that t will have such a value when t is a normal distribution, that is, even if ȳ=μ=500, and se is 10, the probability of ȳ=519.5 can be 5.14%. Therefore, p greater than α means that even if ȳ=μ is true, the probability of accidentally ȳ=519.5 is greater than the type 1 error set by the researcher (false positive), which means that the null hypothesis cannot be rejected.\n\nSo when α=0.05, Jones's null hypothesis cannot be rejected, and Smith's null hypothesis can be rejected. In other words, only Smith's research results are statistically significant.\n\n## C\n\nAs seen in B, the p-value itself means the probability of a specific t, and not revealing a specific p-value does not tell how statistically significant this study will be at the significance level (type 1 error), so information loss occurs.\n\n# Question 6\n\nFirst, I will enter the data frame given in the problem in r.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf1 <- data.frame(\n  grade = rep(\"6th\", 100),\n  snack = c(rep(\"healthy\", 31), rep(\"unhealthy\", 69)))\n\ndf2 <- data.frame(\n  grade = rep(\"7th\", 100),\n  snack = c(rep(\"healthy\", 43), rep(\"unhealthy\", 57)))\n\ndf3 <- data.frame(\n  grade = rep(\"8th\", 100),\n  snack = c(rep(\"healthy\", 51), rep(\"unhealthy\", 49)))\n\ndf<-rbind(df1, df2, df3)\ntable(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     snack\ngrade healthy unhealthy\n  6th      31        69\n  7th      43        57\n  8th      51        49\n```\n:::\n:::\n\n\nNull Hypothesis: Snack selection ratio is the same for each grade.(Healthy Snack Choice Ratio of 6th grade, 7th grade, and 8th grade is equal.)\n\nTest: Here, the categorical data of healthy and unhealthy snacks are given, so Chi-square is used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(table(df))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  table(df)\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\n\nTest result chi-square value is 8.338. And p-value here(0.015) is less than given α(0.05). In other words, it can be concluded that the null hypothesis is rejected, and the selection ratio of snacks at the significance level of 0.05 varies depending on the grade.\n\n# Question 7\n\nHere, the null hypothesis is that the average cost of the 3 area are the same. Therefore, the research hypothesis is that the average cost of at least one area is different.\n\nSince the cost is a numeric variable, should ANOVA be selected to test that the average cost of 3 area are different.\n\nFirst, I created a data frame using the given data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.7<-data.frame(\n  cost=c(6.2, 9.3, 6.8, 6.1, 6.7, 7.5, 7.5, 8.2, 8.5, 8.2, 7.0, 9.3, 5.8, 6.4, 5.6, 7.1, 3.0, 3.5),\n  area=c(rep(\"a1\", 6), rep(\"a2\", 6), rep(\"a3\", 6))\n)\n```\n:::\n\n\nThen let's do ANOVA using the aov function and look at the resulting statistics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(cost~area, df.7))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \narea         2  25.66  12.832   8.176 0.00397 **\nResiduals   15  23.54   1.569                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nF value is 8.176 and p-value is 0.00397. Therefore, if the significance level is 0.05, the null hypothesis is rejected. In other words, at a 95% confidence level, it can be concluded that the average cost of these three regions is not the same.\n\nFinally, I will visually examine the average cost by region with a boxplot. From this, it can be seen that there is a clear difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(cost~area, data=df.7)\n```\n\n::: {.cell-output-display}\n![](HW2_young_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "HW2_young_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}