{
  "hash": "ddeb6484659b6c7a20839ffafe41877c",
  "result": {
    "markdown": "---\ntitle: \"Homework 4\"\nauthor: \"Guanhua Tan\"\ndescription: \"Homework 4\"\ndate: \"04/01/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw4\n  - regression analysis\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n\nLoading required package: effects\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\ndata(UN11)\n```\n:::\n\n\n# Question 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny<--10536 + 53.8 *1240 +2.84 *18000\ny\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n\n```{.r .cell-code}\nredidual_1 <- 145000-y\nredidual_1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37704\n```\n:::\n\n```{.r .cell-code}\nx2 <-53.8/2.84\nx2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\nA the predicted selling price is 107,292; the residual is 37,704; interpret is -10536.\n\nB For fixed lot size, if the house size increase one square feet, the house price will increase 53.8.\n\nC if the lot size need to increase 18.94, that will have the same impact as a one-square-foot increase in home size.\n\n\n# Question 2\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(salary)\nhead(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   degree rank    sex year ysdeg salary\n1 Masters Prof   Male   25    35  36350\n2 Masters Prof   Male   13    22  35350\n3 Masters Prof   Male   10    23  28200\n4 Masters Prof Female    7    27  26775\n5     PhD Prof   Male   19    30  33696\n6 Masters Prof   Male   16    21  28516\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(salary~sex, salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8602.8 -4296.6  -100.8  3513.1 16687.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    24697        938  26.330   <2e-16 ***\nsexFemale      -3340       1808  -1.847   0.0706 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5782 on 50 degrees of freedom\nMultiple R-squared:  0.0639,\tAdjusted R-squared:  0.04518 \nF-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706\n```\n:::\n:::\n\n\nA. According the Chisq test, sex has the impact on salary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(salary ~ ., data = salary) |>\n  confint()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\nThe 95% confidence intervals for the female salary is (-697.81, 3030.56), other variables controlled.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_salary <- lm(salary~degree+rank+sex+year+ysdeg, data=salary)\nsummary(sex_salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nC. degreePhD, sexFemale, and ysdeg doesn't show statistical significance. For other fixed terms, if one person hold a associate professor ranking, the salary increases 5292.36, compared to a assistant professor. In the same condition, if one person holds a full professor, the salary increases 11118.76, compared to a assistant professor. People's age has the positive impact on their salary. When the age increases 1 year, the salary increases 476.31.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank <-relevel(salary$rank, ref=\"Prof\")\nsalary$sex <-relevel(salary$sex, ref=\"Female\")\n\nsex_salary <- lm(salary~degree+rank+sex+year+ysdeg, data=salary)\nsummary(sex_salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  28031.18    1677.06  16.715  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nsexMale      -1166.37     925.57  -1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nD. For other fixed terms, if one person holds a assistant professor ranking, the salary decreases 11118.76, compared to a full professor. In the same condition, if one person hold a associate professor, the salary decreases 5826.40, compared to a full professor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_salary <- lm(salary~degree+sex+year+ysdeg, data=salary)\nsummary(sex_salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15897.03    1259.87  12.618  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexMale      1286.54    1313.09   0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\nE if the model drops the variable rank, the variable years after the degree presents the strongly statistical significance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary_F <- salary %>%\n  mutate(fifteen_years= case_when(ysdeg > 15 ~0,ysdeg <= 15 ~ 1))\nsummary(lm(salary~degree + sex + rank+ year+fifteen_years,salary_F))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + rank + year + fifteen_years, \n    data = salary_F)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3403.3 -1387.0  -167.0   528.2  9233.8 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    25332.46    1034.63  24.485  < 2e-16 ***\ndegreePhD        818.93     797.48   1.027   0.3100    \nsexMale         -907.14     840.54  -1.079   0.2862    \nrankAsst      -11096.95    1191.00  -9.317 4.54e-12 ***\nrankAssoc      -6124.28    1028.58  -5.954 3.65e-07 ***\nyear             434.85      78.89   5.512 1.65e-06 ***\nfifteen_years   2163.46    1072.04   2.018   0.0496 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2362 on 45 degrees of freedom\nMultiple R-squared:  0.8594,\tAdjusted R-squared:  0.8407 \nF-statistic: 45.86 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n# Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"house.selling.price\")\nhead(house.selling.price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  case Taxes Beds Baths New  Price Size\n1    1  3104    4     2   0 279900 2048\n2    2  1173    2     1   0 146500  912\n3    3  3076    4     2   0 237700 1654\n4    4  1608    3     2   0 200000 2068\n5    5  1454    3     3   0 159900 1477\n6    6  2997    3     2   1 499900 3153\n```\n:::\n\n```{.r .cell-code}\nhouse_model_1 <- lm(Price~Size+New, data=house.selling.price)\nsummary(house_model_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nA. The variables Size and New show the statistical significance. the price will increase 116 when the house size increases 1 square feet. If the house is new, the price will increase 57736.283, compared with the size old house.\n\nB. Price= 116.132*Size+57736.283*New-40230.86\nFor new homes\nPrice=115.132*Size + 57736.283-40230.86\nFor not new homes\nPrice=115.132*Size -40239.86.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny_new <- 116.32*3000+57736.283-40230.86\ny_old <- 116.32*3000-40230.86\ny_new\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 366465.4\n```\n:::\n\n```{.r .cell-code}\ny_old\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 308729.1\n```\n:::\n:::\n\n\nC. the new home price is 366465.4; the old home price is 308729.1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhouse_model_2 <- lm(Price~Size+New*Size, data=house.selling.price)\nsummary(house_model_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New * Size, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nD. The regression result shows that the interaction term is statistical significance and r squared value is larger than the previous model.\n\nE. for new homes, y=-22227.808+104.438*Size-78527.502+61.916*Size\nfor old homes, y=104.438*Size-100755.3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSize_3000 <-3000\nPrice_new <- 22227.808+104.438*Size_3000-78527.502+61.916*Size_3000\nPrice_old <-104.438*Size_3000-100755.3\nPrice_new\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 442762.3\n```\n:::\n\n```{.r .cell-code}\nPrice_old\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 212558.7\n```\n:::\n:::\n\nF. For 3000 square feet, the new hous is 442,762.3 which the old one is 212,558.7\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSize_1500 <-1500\nPrice_new_1500 <- 22227.808+104.438*Size_1500-78527.502+61.916*Size_1500\nPrice_old_1500 <-104.438*Size_1500-100755.3\nPrice_new_1500\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 193231.3\n```\n:::\n\n```{.r .cell-code}\nPrice_old_1500\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 55901.7\n```\n:::\n:::\n\n\nG. According to the predicted lines, when the size increases, the new house price will increase more than the old one's.\n\nH. I think the model with the interaction one represents the relationship between size and new because it has a larger value of R square.\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}