{
  "hash": "0e648a4d4b64187a118b19f382324c83",
  "result": {
    "markdown": "---\ntitle: \"Homework - Template\"\nauthor: \"Rosemary Pang\"\ndescription: \"Template of course blog qmd file\"\ndate: \"02/05/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n```\n:::\n\n\n\n\n\nFirst, let's read in the data from the Excel file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\ndf <- read_excel(\"_data/LungCapData.xls\")\n```\n:::\n\n\n# Question 1\n\n## a\n\nWhat does the distribution of LungCap look like? (Hint: Plot a histogram with probability density  on the y axis) \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calc mean of lung cap\nlc_mean <- mean(df$LungCap)\n\n#calc sd\nlc_sd <- sd(df$LungCap)\n\n#use denorm to generate array of probabilities associated with each value of lung cap\ndf['probs'] <- dnorm(x=df$LungCap, mean=lc_mean, sd = lc_sd)\n\n#plot histogram\nggplot(df, aes(x = LungCap)) + \n  geom_histogram(aes(y=..density..), binwidth=1, color=\"black\", fill=\"white\") +\n  stat_function(fun=dnorm, args=list(mean=lc_mean, sd=lc_sd), color=\"red\") +\n  xlab(\"Lung Capacity\") + ylab(\"Density\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.\nℹ Please use `after_stat(density)` instead.\n```\n:::\n\n::: {.cell-output-display}\n![](hw1_asch_harwood_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## b\n\nCompare the probability distribution of the LungCap with respect to Males and Females? (Hint:\nmake boxplots separated by gender using the boxplot() function)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = Gender, y = LungCap)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](hw1_asch_harwood_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n## c\n\nCompare the mean lung capacities for smokers and non-smokers. Does it make sense?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 7\n  LungCap   Age Height Smoke Gender Caesarean  probs\n    <dbl> <dbl>  <dbl> <chr> <chr>  <chr>      <dbl>\n1    6.48     6   62.1 no    male   no        0.131 \n2   10.1     18   74.7 yes   female no        0.104 \n3    9.55    16   69.7 no    female yes       0.123 \n4   11.1     14   71   no    male   no        0.0707\n5    4.8      5   56.9 no    male   no        0.0773\n6    6.22    11   58.7 no    female no        0.124 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  group_by(Smoke) %>%\n  summarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke `mean(LungCap)`\n  <chr>           <dbl>\n1 no               7.77\n2 yes              8.65\n```\n:::\n\n```{.r .cell-code}\nggplot(df, aes(x = Smoke, y = LungCap)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](hw1_asch_harwood_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n### Interpretation\n\nThe average lung capacity for none smokers is 7.77 compared to 8.65 for smokers, which does not make sense. I would assume that smokers would have a lower average lung capacity than non-smokers.\n\n\n## d\n\nExamine the relationship between Smoking and Lung Capacity within age groups: “less than or\nequal to 13”, “14 to 15”, “16 to 17”, and “greater than or equal to 18”.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf$AgeGroup <- cut(df$Age, breaks = c(0, 13, 15, 17, Inf),\n                    labels = c(\"<=13\", \"14 to 15\", \"16 to 17\", \">=18\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  group_by(AgeGroup) %>%\n  summarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n  AgeGroup `mean(LungCap)`\n  <fct>              <dbl>\n1 <=13                6.41\n2 14 to 15            9.05\n3 16 to 17           10.2 \n4 >=18               11.0 \n```\n:::\n\n```{.r .cell-code}\nggplot(df, aes(x = AgeGroup, y = LungCap)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](hw1_asch_harwood_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = Age, y = LungCap)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](hw1_asch_harwood_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n### Interpretation\n\n\nThere appears to be a relationship between age and lung capacity, where it increases through age 18. This is understandable given that lung capacity would increase as a someone grows from a kid into an adult. \n\n\n## e\n\nCompare the lung capacities for smokers and non-smokers within each age group. Is your answer\ndifferent from the one in part c. What could possibly be going on here?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 725 × 8\n   LungCap   Age Height Smoke Gender Caesarean  probs AgeGroup\n     <dbl> <dbl>  <dbl> <chr> <chr>  <chr>      <dbl> <fct>   \n 1    6.48     6   62.1 no    male   no        0.131  <=13    \n 2   10.1     18   74.7 yes   female no        0.104  >=18    \n 3    9.55    16   69.7 no    female yes       0.123  16 to 17\n 4   11.1     14   71   no    male   no        0.0707 14 to 15\n 5    4.8      5   56.9 no    male   no        0.0773 <=13    \n 6    6.22    11   58.7 no    female no        0.124  <=13    \n 7    4.95     8   63.3 no    male   yes       0.0823 <=13    \n 8    7.32    11   70.4 no    male   no        0.147  <=13    \n 9    8.88    15   70.5 no    male   no        0.139  14 to 15\n10    6.8     11   59.2 no    male   no        0.138  <=13    \n# … with 715 more rows\n```\n:::\n\n```{.r .cell-code}\nggplot(df, aes(x = AgeGroup, y = LungCap, fill=Smoke)) +\n  geom_boxplot() \n```\n\n::: {.cell-output-display}\n![](hw1_asch_harwood_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = LungCap, fill = Smoke)) +\n  geom_histogram(alpha = 0.5, bins = 10, position = \"identity\") +\n  facet_wrap(~AgeGroup, nrow = 2, scales = \"free\") +\n  labs(x = \"Lung Capacity\", y = \"Frequency\") +\n  ggtitle(\"Distribution of Lung Capacity by Age Group, Controlling for Smoking Status\")\n```\n\n::: {.cell-output-display}\n![](hw1_asch_harwood_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = Age, y = LungCap, color=Smoke)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](hw1_asch_harwood_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n### Interpretation\n\nWhen controlling for age, average smoker lung capacity is lower across the board for all age groups except \"13 <=\". In the later group, there are far fewer smokers, as one would (hope to) expect. \n\n\n",
    "supporting": [
      "hw1_asch_harwood_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}