{
  "hash": "021327f8c6554b55c863c06099f4b607",
  "result": {
    "markdown": "---\ntitle: \"Hw 1 by Kristin Abijaoude\"\nauthor: \"Kristin Abijaoude\"\ndescription: \"LungCap and Prison data HW1\"\ndate: \"02/27/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Hw1\n  - kristin abijaoude\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(readxl)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(summarytools)\nlibrary(stats)\n```\n:::\n\n\n# Lung Capacity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLungCapData <- read_excel(\"~/Documents/GitHub/Github Help/603_Spring_2023/posts/_data/LungCapData.xls\")\nLungCapData\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 725 × 6\n   LungCap   Age Height Smoke Gender Caesarean\n     <dbl> <dbl>  <dbl> <chr> <chr>  <chr>    \n 1    6.48     6   62.1 no    male   no       \n 2   10.1     18   74.7 yes   female no       \n 3    9.55    16   69.7 no    female yes      \n 4   11.1     14   71   no    male   no       \n 5    4.8      5   56.9 no    male   no       \n 6    6.22    11   58.7 no    female no       \n 7    4.95     8   63.3 no    male   yes      \n 8    7.32    11   70.4 no    male   no       \n 9    8.88    15   70.5 no    male   no       \n10    6.8     11   59.2 no    male   no       \n# … with 715 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(dfSummary(LungCapData,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.70, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>LungCapData</h4>\n<strong>Dimensions</strong>: 725 x 6\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">LungCap\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 7.9 (2.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0.5 &le; 8 &le; 14.7</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 3.7 (0.3)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">342 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAxEAOw6zmgmPAAABP0lEQVR42u2aSw7CMAxECeoduQOcp9yBU8ISB8lS2nzsGeat6KbpU/xrSnlfWLlGP4DUpGbZ7EVZsuT+k96PgcvaW2+n79LBzfx+TVtlkdoeUIiX7dp3p+btUw1xGZEaIsRq08pIRE1cpLaqe/kQB6TUEAmZIWtswRk5KidQmzWCEQek1BBJkGuWeobpKyrJ1EZOMMQBKTVEpIaI1BCRGiJSQ0RqiAyd/OOPVaepRXxq8iEOSKkhIjVEkh371PQdmadW62slnWq5mvRQtfhvnz7EZURqiEgNEakhcqKvZW7TnWq53qV9iAOSWC315G85/oLTqBZfOo7nd/OuYZQOC3GuSQ0RN9fiC8c0tcxHA238Y0Bmpu3/d5BqbalCHJDEapABWVNlnsk7AjVvui1W+Qnfpu9m1wq8jQtxGZEaIh/myC1w1tzOqAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMy0xN1QwMDo1OToxNCswMDowMFlK3SgAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDMtMTdUMDA6NTk6MTQrMDA6MDAoF2WUAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Age\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 12.3 (4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3 &le; 13 &le; 19</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 6 (0.3)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">17 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAxEAOw6zmgmPAAABCElEQVR42u2awQ3CMBAEY5Qe6QHqgR5SJXwPccjYMcSz2vklj9gj7cU+J+WxqHI6egJWs1pkjRflJ0PcGsr5unMKcai1+ykNnN/ubMm9ZdmGjiocSGG1vwTye/K67KvAydRGVqBwIK1GxGpErEbEakSsRsRqRIbu/FuOCmBqY5uSvTiQx9LXeyPU+mIuHEirEemstblWsKFqc61gOcKBtBoRqxGxGhGrEbEaEasRsRoRYbVqK0ropzvVCP10jnAgrUYEcTCek77gwncAsFr2b2xEOJBWI2I1IlYjIqz2smRzG5iqWn2FJyEcSKsRsRoRqxERVitxA3LH70Yu4Wyk4G0+IhxIqxF5AivUHZ7OzTROAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAzLTE3VDAwOjU5OjE0KzAwOjAwWUrdKAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMy0xN1QwMDo1OToxNCswMDowMCgXZZQAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Height\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 64.8 (7.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">45.3 &le; 65.4 &le; 81.8</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 10.4 (0.1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">274 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAxEAOw6zmgmPAAAA/0lEQVR42u2aUQ6CMAxAxXBH76DnwTt4Sv2diU2AOehr3vuDEMYj3dYWpvelKtezH0A11Vrm9mAaPNgSTuzHn4ZuB5h332UXt59nX0PGKhyQqhFRjYhqRIbsa0uKnHvQln3k1hxROCBVI6IaEdWIFFY7uMqOiPKXnsZCErUR2UvhgFSNSGG1rmUkR102RC1HXRZROCBVI6IaEdWIqEZENSKqEVGNiGpEVCOiGhHViBRWW9Vizd0l7lI7r0vc80kxyafDiJ5XWniuqUZENSKqEVGNyFc2wswVV6nl/qNgK4UDUjUihdWS12sR4VrelKhTe80Tv/jfI7VaFJ5rqhH5AN1eG5oyj3sIAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAzLTE3VDAwOjU5OjE0KzAwOjAwWUrdKAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMy0xN1QwMDo1OToxNCswMDowMCgXZZQAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Smoke\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. no</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. yes</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">648</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">89.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">77</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGoAAAAoCAQAAAC8uKd7AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAxEAOw6zmgmPAAAAi0lEQVRo3u2XQQqAMAwEG/GP/kHfo3/oK/VahYL0EmfdueUSMjSBbpxFjyl7AEv9WWpuiwN8YGt0pEpZsmcbpN4qyfWzFAVLUbAUBUtRsBQFSanHh7aOdfkY0aaNGG6TT+uhv357JyRusCd8ERJ5dya5fpaiYCkKlqJgKQqWoiAppR8SVZBcP0tRuADmmwuplv0LDgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMy0xN1QwMDo1OToxNCswMDowMFlK3SgAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDMtMTdUMDA6NTk6MTQrMDA6MDAoF2WUAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Gender\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. female</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. male</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">358</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">49.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">367</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">50.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEIAAAAoCAQAAADgMuRfAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAxEAOw6zmgmPAAAAe0lEQVRYw+3WwQmAMAyF4US6o0M4j+7QKfUkPOtNIUnhf7dWMB9NofHT8rNkA0Bomi6OoAuyuZmWas/PawChv3ZKtAMECBAgQEyFGB6w/u0vP+P6pHpgYa1brx175NQrx54w1JiNd69EO0CAAAECxFSIekNNVkq0A8SdC+SADD4g7+laAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAzLTE3VDAwOjU5OjE0KzAwOjAwWUrdKAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMy0xN1QwMDo1OToxNCswMDowMCgXZZQAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Caesarean\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. no</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. yes</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">561</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">77.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">164</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">22.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAF4AAAAoCAQAAADdoIU5AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAxEAOw6zmgmPAAAAhElEQVRYw+3XwQmAMBBE0azYoz1oPdpDqtTrKogYwWHC/7dcwoNsIIm9+DaoAeAdG/NiM7gAc9zgS5nUtofqaWU9NuDBgzcKPHjwRlnjLw+z2raLqMiv4Gje5r+yt5+xWV9+RhbxUX34jOjvh/XYgAcP3ijw4MEbZY3v5zPilvXYgFd1AE6MC6kTWgKqAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAzLTE3VDAwOjU5OjE0KzAwOjAwWUrdKAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMy0xN1QwMDo1OToxNCswMDowMCgXZZQAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.2)<br/>2023-03-16</p>\n</div>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(LungCapData)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"LungCap\"   \"Age\"       \"Height\"    \"Smoke\"     \"Gender\"    \"Caesarean\"\n```\n:::\n\n```{.r .cell-code}\ndim(LungCapData)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 725   6\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(LungCapData$LungCap)\n```\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW1_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n1a. The distribution looks pretty normal to me, with capacity between 6 and 9 being the most frequent. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(LungCap ~ Gender, data=LungCapData)\n```\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n1b. Separating the two genders, it looks like men have a higher lung capacity rate in comparison to women.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLungCapData %>%\n  group_by(Smoke) %>%\n  summarise(mean = mean(LungCap), n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  Smoke  mean     n\n  <chr> <dbl> <int>\n1 no     7.77   648\n2 yes    8.65    77\n```\n:::\n:::\n\n1c. The average lung capacity for a non-smoker is around 7.78, while for smokers it's 8.65. In other words, on average, the smokers have a higher lung capacity rate than non-smokers... this doesn't make sense because smoking is supposed to be bad for your lungs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagegroup <- LungCapData %>%\n  mutate(agegroup = case_when(Age <= 13 ~ \"Less than 13 years old\",\n                              Age == 14| Age == 15 ~ \"14 to 15 years old\",\n                              Age == 16 | Age == 17 ~ \"16 to 17 years old\",\n                              Age >= 18 ~ \"18 years old and older\"))\nagegroup %>%\n  ggplot(aes(x=LungCap, fill=Smoke)) +\n  geom_histogram() +\n  facet_wrap(~agegroup)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW1_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n1d. Obviously, older teens are more likely to be smokers, as well as have higher lung capacity, than younger teens. The vast majority of teens 13 years and younger are non-smoker (I would be horrified at the sight of a kid smoking).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagegroup <- agegroup %>%\n  mutate(AgeGroup = factor(agegroup, level= c(\"Less than 13 years old\", \n                                              \"14 to 15 years old\",\n                                              \"16 to 17 years old\",\n                                              \"18 years old and older\")))\n\nboxplot(LungCap ~ AgeGroup, data=agegroup)\n```\n\n::: {.cell-output-display}\n![](Kristin_Abijaoude_HW1_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n1e. There is a correlation between age and lung capacity. The lung capacity rate increases as the person gets older.\n\n# Prior Convictions\n\nAnother dataset I created here deals with prison convictions. The sample size is 810 prisoners in a state prison, some of the prisoners are there for the first time, while others have been imprison as many as 4 times, or have 4 prior convictions in other words. `prior` means numbers of prior convictions. `freq` means how many prisoners have a set of convictions (434 prisoners have 1 prior convictions, 160 prisoners have 2 prior convictions etc.). Finally, I created a new variable called `probability`, where I divided the `freq` variable by the total number of prisoners, to denote the probability that a prisoner had a certain number of prior convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(prior = c(0:4), \n                 freq = c(128, 434, 160, 64, 24)\n                 )\n\ndf <- df %>%\n  mutate(probability = freq/810)\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  prior freq probability\n1     0  128  0.15802469\n2     1  434  0.53580247\n3     2  160  0.19753086\n4     3   64  0.07901235\n5     4   24  0.02962963\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# alternatively\n(dbinom(x = 1, size = 1, prob = 160/810))*100\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 19.75309\n```\n:::\n:::\n\n\n2a. There is a less than 20% probability that a randomly selected inmate has exactly 2 prior convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n128 + 434\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 562\n```\n:::\n\n```{.r .cell-code}\n(dbinom(x = 1, size = 1, prob = 562/810))*100\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 69.38272\n```\n:::\n:::\n\n\n2b. There is a 69% probability that a randomly selected inmate has fewer than 2 prior convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n128 + 434 + 160\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 722\n```\n:::\n\n```{.r .cell-code}\n(dbinom(x = 1, size = 1, prob = 722/810))*100\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 89.1358\n```\n:::\n:::\n\n\n2c. There is a 89% probability that a randomly selected inmate has 2 or fewer prior convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n64 + 24\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 88\n```\n:::\n\n```{.r .cell-code}\n(dbinom(x = 1, size = 1, prob = 88/810))*100\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.8642\n```\n:::\n:::\n\n\n2d. There is a 10% probability that a randomly selected inmate has more than 2 prior convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior <- df$prior\nprob <- df$probability\nfreq <- df$freq\n\nexval <- sum(prior*prob)\nexval\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\n2e. The expected value `exval`, or long term mean, is 1.28642. I separated the variables into its own set and multiplied `prior` (# of prior convictions) and `prob` (the probability a given prisoner has a certain number of prior convictions).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# variance\nvar(rep(df$prior, df$freq))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8572937\n```\n:::\n\n```{.r .cell-code}\n# standard deviation\nsd(rep(df$prior, df$freq))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9259016\n```\n:::\n:::\n\nThe variance is 0.86, which mean the data is close to one another.\n\nThe standard deviation is 0.93, which means the data is more clustered around the mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrender(\"Kristin_Abijaoude_HW1.qmd\", output_format = \"pdf_document\", output_file = \"Kristin_Abijaoude_HW1.pdf\")\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in render(\"Kristin_Abijaoude_HW1.qmd\", output_format = \"pdf_document\", : could not find function \"render\"\n```\n:::\n:::\n",
    "supporting": [
      "Kristin_Abijaoude_HW1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}