{
  "hash": "d9087cc498d47b96ffa5b8ad2ab7c0b6",
  "result": {
    "markdown": "::: {.cell}\n\n```{.r .cell-code}\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: effects\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\nlibrary(ggplot2)\nlibrary(stargazer)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nPlease cite as: \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n R package version 5.2.3. https://CRAN.R-project.org/package=stargazer \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ny = -10536 + (53.8 * 1240) + (2.84 * 18000)\ny\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n\n```{.r .cell-code}\nactual_value = 145000 - y\nactual_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37704\n```\n:::\n:::\n\n\nThe actual selling price exceeded the predicted selling price by $37,704, indicating that the home sold for a higher price than what was estimated by the model.\n\n1B: When the lot size is fixed, the coefficient of x1 (53.8) captures the specific impact of the home size on the predicted selling price, controlling for the influence of lot size. Therefore, for a fixed lot size, the house selling price is predicted to increase by $53.8 for each additional square foot increase in home size, as determined by the coefficient of x1 in the model.\n\n1C: One-square-foot increase in home size is associated with an increase in price of $53.8. One-\nsquare-foot increase in lot size is associated with an increase in price of $2.84.(53.8 / 2.84) to have the same impact as a one-square-foot increase in home size, the lot size would need to increase by approximately 18.90 square feet according to the given prediction equation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(salary)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(formula = salary ~ sex, data = salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  salary by sex\nt = 1.7744, df = 21.591, p-value = 0.09009\nalternative hypothesis: true difference in means between group Male and group Female is not equal to 0\n95 percent confidence interval:\n -567.8539 7247.1471\nsample estimates:\n  mean in group Male mean in group Female \n            24696.79             21357.14 \n```\n:::\n:::\n\nThe results of the t-test indicate that there is a difference between the mean salary for men  and women. However, with a p-value of 0.09009, we do not have enough evidence to reject the null hypothesis at the 95% confidence level. In other words, we cannot conclude that there is a statistically significant difference in the mean salary between men and women when considering only the variable of sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(salary ~ ., data = salary) |>\n  confint() \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\nThe 95% confidence interval for the \"sexFemale\" variable is (-697, 3031). This confidence interval indicates that, when considering other variables, female faculty members may earn approximately $697 less to $3031 more in salary compared to male faculty members. This range provides an estimate of the potential difference in salaries between the genders, while taking into account the influence of other factors in the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(salary ~ ., data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nAmong the predictor variables examined, both rank and years in the current rank have statistically significant effects on salary. Controlling for all other factors, being at the Associate rank is associated with an average salary increase of $5,292.36 compared to the Assistant rank, while being a full professor corresponds to an average salary increase of $11,118.76 relative to the Assistant rank.\n\nAdditionally, each additional year in the current rank is linked to an average salary increase of $476.31. On the other hand, the number of years since obtaining the highest degree does not have a statistically significant impact on salary, suggesting that it does not contribute significantly to changes in salary when controlling for other factors.\n\nRegarding sex, controlling for all other variables, being a female professor is associated with a salary increase of $1,166 compared to being a male professor. However, this result is not statistically significant, as indicated by the p-value of 0.214.\n\nFinally, the variable of degree does not show a statistically significant effect on salary when controlling for other variables. Specifically, having a PhD is associated with a salary increase of $1,388.61 compared to having a master's degree, but this result is not statistically significant with a p-value of 0.180.\n\nIn summary, among the examined predictor variables, rank and years in the current rank have statistically significant impacts on salary, while the effects of sex, degree, and years since obtaining the highest degree are not statistically significant when controlling for other factors.\n\nD\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank <- relevel(salary$rank, ref = 'Prof')\nsummary(lm(salary ~ ., data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nsexFemale     1166.37     925.57   1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nn the updated model, the coefficients for the dummy variables representing the two categories other than the reference category (Prof) are as follows: rankAsst being -11118 and rankAssoc being -5826. These coefficients indicate the difference in salary compared to the reference category (Full Professors), while controlling for other variables.\n\nSpecifically, the coefficient of -11118 for rankAsst suggests that Assistant Professors earn $11118 less on average than Full Professors, considering the influence of other factors. Similarly, the coefficient of -5826 for rankAssoc indicates that Associate Professors earn $5826 less on average than Full Professors, controlling for other variables.\n\nIn summary, the new model presents the same information as before, but in a different way, emphasizing the salary differences between each rank category (Assistant and Associate Professors) and the reference category (Full Professors) while taking into account the impact of other variables.\n\nE\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(salary ~ degree + sex + year + ysdeg, data = salary)\n\n# Print the summary of the initial model\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\nWith the exclusion of the \"rank\" variable from the model, the findings regarding the impact of different predictor variables on salary have changed.\n\nDegree:\nWithout the \"rank\" variable, the variable \"degreePhD\" now becomes a statistically significant predictor. When controlling for all other factors, having a PhD (compared to a master's degree) is associated with a decrease in salary of $3,299.35. This is notably different from when the \"rank\" variable was included, where there was no statistical significance and a PhD increased salary by $1,388.61.\n\nYears Since Highest Degree:\nIn the absence of the \"rank\" variable, the variable \"ysdeg\" (years since obtaining the highest degree) becomes a statistically significant predictor. Controlling for other variables, each passing year now results in an increase in salary of $339.40. This differs from the previous model with the \"rank\" variable, where there was no statistical significance and a decrease in salary was suggested.\n\nYear:\nThe variable \"year\" remains statistically significant even after excluding the \"rank\" variable, although the p-value has increased. Controlling for other factors, each additional year of experience now contributes $351.97 to salary.\n\nSex:\nThe result for the variable \"sex\" remains not statistically significant, indicating that its impact on salary did not change significantly. However, the direction of the effect has changed from positive to negative.\n\nF\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$newDean <- ifelse(salary$ysdeg <= 15, 0, 1)\n# Run regression analysis with newDean included as a predictor variable\nlm_salary_NewDean <- lm(salary ~ degree + rank + sex + year + newDean, data = salary)\nsummary(lm_salary_NewDean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + newDean, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3403.3 -1387.0  -167.0   528.2  9233.8 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26588.79    1168.06  22.763  < 2e-16 ***\ndegreePhD      818.93     797.48   1.027   0.3100    \nrankAsst    -11096.95    1191.00  -9.317 4.54e-12 ***\nrankAssoc    -6124.28    1028.58  -5.954 3.65e-07 ***\nsexFemale      907.14     840.54   1.079   0.2862    \nyear           434.85      78.89   5.512 1.65e-06 ***\nnewDean      -2163.46    1072.04  -2.018   0.0496 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2362 on 45 degrees of freedom\nMultiple R-squared:  0.8594,\tAdjusted R-squared:  0.8407 \nF-statistic: 45.86 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThe analysis provides evidence supporting the hypothesis that individuals hired by the new Dean are earning higher salaries compared to those who were not. The statistical significance of the \"newDean\" variable, with a p-value of 0.0496, indicates that there is a notable difference in salaries between these two groups, even when considering other variables. Specifically, the findings suggest that faculty members who were not hired by the new Dean earn an average of $2,163.46 less, holding other factors constant.\n3\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(house.selling.price)\n```\n:::\n\nA\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(Price ~ Size + New, data = house.selling.price)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nIn the regression model, both the \"Size\" and \"New\" variables exhibit positive associations with the \"Price\" of the house. Furthermore, these associations are statistically significant at the 5% level. Specifically, a one-square-foot increase in the size of the house is associated with an average increase in price of $116, while controlling for whether the house is new or not. Additionally, new houses, when compared to old houses of the same size, have an average price difference of $57,736, indicating that new houses tend to be more expensive.\n\nB\ny = −40,230.867 + 116.132(Size) + 57736.283(New).\n\nWhere:\n\ny represents the predicted selling price.\n\ny = −40,230.867 + 116.132(Size) + 57736.283(1). #New house \ny = −40,230.867 + 116.132(Size) #Old house \nNew houses have high prices \n\nC\n\n::: {.cell}\n\n```{.r .cell-code}\n#New house\ny_new = -40230.867+(116.132*3000)+(57736.283*1)\ny_new\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 365901.4\n```\n:::\n\n```{.r .cell-code}\n#Old house \ny_old = -40230.867+(116.132*3000)+(57736.283*0)\ny_old\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 308165.1\n```\n:::\n:::\n\nThe predicted selling price for a new 3,000 square foot home is $365,901.40. The predicted selling price for a 3,000 square foot home that is not new is $308,165.10.\n\nD\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(Price ~ Size + New + Size * New, data = house.selling.price)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New + Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nE\n\nNew_home_P = −22227.808+104.438∗size+−78527.502∗1+61.916∗Size∗1 = −100755.3+166.354∗size\n\nOld_home_P = −22227.808+104.438∗size+−78527.502∗0+61.916∗Size∗0 = −22227.808+104.438∗size\n\nF\n\n::: {.cell}\n\n```{.r .cell-code}\nNew_home <- -22227.808 + (104.438*3000) -78527.502 + (61.916*3000)\nOld_home <- -22227.808 + (104.438*3000)\nNew_home\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 398306.7\n```\n:::\n\n```{.r .cell-code}\nOld_home\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 291086.2\n```\n:::\n:::\n\nG\n\n::: {.cell}\n\n```{.r .cell-code}\nNew_home <- -22227.808 + (104.438*1500) -78527.502 + (61.916*1500)\nOld_home <- -22227.808 + (104.438*1500)\nNew_home\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 148775.7\n```\n:::\n\n```{.r .cell-code}\nOld_home\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 134429.2\n```\n:::\n:::\n\nFor homes with a size of 3000 square feet, the predicted selling price is $398,306.70 for new homes and $291,086.20 for not new homes. This indicates a significant difference of $107,220.50 in the sale price between new and not new homes of the same size.\n\nIn contrast, for homes with a size of 1500 square feet, the predicted selling price is $148,775.70 for new homes and $134,429.20 for not new homes. The difference in sale price between new and not new homes in this case is smaller, amounting to $14,346.50.\n\nThe disparity in the price difference between new and not new homes for different sizes can be explained by the structure of the prediction equation. According to the predictive model, a house needs to have a size of approximately 606 square feet before it can be sold at a profit. In other words, only the square footage beyond this threshold contributes to the increase in the sale price.\n\nFor instance, a 1500 square foot home has approximately 894 \"money-making\" square feet, while a 3000 square foot home has around 2394 such square feet. Each additional money-making square foot adds approximately $166.354 to the sale price.\n\nTherefore, the observed differences in sale prices align with the predictive model's expectations, reflecting the influence of the size of the home on its profitability and the corresponding impact on the selling price.\n\nH: The inclusion of the interaction term in the model improves the representation of the relationship between size, newness, and the selling price. This is supported by the statistical significance of the interaction term, as indicated by its low p-value. Additionally, the adjusted R-squared value for the model with the interaction (0.7363) is higher compared to the model without the interaction (0.7169).\n\nThese findings suggest that the interaction between size and newness plays a significant role in explaining the variation in the selling price. The higher adjusted R-squared value indicates that the model with the interaction term captures a greater proportion of the variability in the data, providing a better fit to the observed selling prices.\n\nTherefore, the model with the interaction term is more reliable and informative in understanding how both size and newness influence the predicted selling price, taking into account their combined effect on the outcome variable.\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}