{
  "hash": "01bcf65e6e81a13dcf9189f03c3d7478",
  "result": {
    "markdown": "---\ntitle: \"Final Project Checkin-2\"\nauthor: \"Xiaoyan\"\ndescription: \"Template of course blog qmd file\"\ndate: \"04/17/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - finalpart1\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(ggplot2)\n```\n:::\n\n# {.tabset}\n\n## Introduction and background\n\n The Chinese government implemented the one-child policy in 1979, which resulted in the increasing proportion of one-child families and the \"four-two-one\" family structure consisting of four grandparents, two parents, and one child. Despite being blessed with relatively more family and social resources, only children may face physical and socio-psychological problems during development, including an elevated risk for overweight and obesity and negative psychosocial consequences. Previous studies have shown that only children had a higher likelihood of overweight or obesity, compared with children who had one or more siblings. Over obesity, mental healthy is also interesting to explore that how it is related to overweight/obesity, as well as sib-size, in young adolescents affects mental health.。\n \n\n## research questions\n1. Does obesity positively related to mental health?\n2. what are factors that affects mental healthy?\n3. does sibling or obeisty directily related to mental health?\n\n## key predictors\n1. mental health\n2. sibling number\n3. obisity rate\n4. Family location, finance and education\n\n\n## hypothesis\n1. Higher obesity rate increase the risk of depression\n2. higher family income increase the rate of obesity\n3. More sibling reduce the risk of both depression and anxiety. \n\nIn these hypothesis, the response variables are depression rate, axiety rate and BMI index. The explanatory variables can be factors listed below. Analysis is needed to identify the control variables. For exapmle, in hypothesis 2, family income is the explanatory varible and rate of obsity(BMI) is response varible, the control varible may also be family financial situation. \n\n## data description\n### overlook of data\n\n::: {.cell}\n\n```{.r .cell-code}\ndata<-read_excel(\"/Users/cassie199/Desktop/23spring/603_Spring_2023-1/posts/_data/mentalhealth_data.xlsx\")\nhead(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 29\n  T0depres…¹ T0anx…² T1dep…³ T1anx…⁴ Height Weight    WC    HC   SBP   DBP   FBG\n       <dbl>   <dbl>   <dbl>   <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1         31      35      41      35   153.   34.6    58  67      98    60   4.4\n2         35      24      35      25   172.   46.1    63  78     110    70   3.9\n3         31      34      37      26   146.   38.9    72  77.7   102    62   4.6\n4         27      31      42      35   162.   46.8    62  80     116    80   4.5\n5         31      26      49      33   154.   36.4    56  72      90    60   4.2\n6         30      28      47      32   164.   40.6    55  73     102    70   3.7\n# … with 18 more variables: TC <dbl>, TG <dbl>, `HDL-C` <dbl>, `LDL-C` <dbl>,\n#   BMI <dbl>, WHR <dbl>, WtHR <dbl>, `Family location` <dbl>,\n#   `Number of siblings` <dbl>,\n#   `How much time do you spend with your father in elementary school?` <dbl>,\n#   `How much time do you spend with your mother in elementary school?` <dbl>,\n#   `Father’s education level` <dbl>, `Mother’s education level` <dbl>,\n#   `Family financial situation` <dbl>, `Sleeping hours` <dbl>, …\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 728\n```\n:::\n\n```{.r .cell-code}\nplot(data$T0depression~data$BMI)\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\nThis dataset including 1348 variables and 29 columns. there are 728 NA in this data set. all variables was presented as numberic data. descriptive data was also presented as degrees such as education level, family financial situation and depression rate. By pre-plotting depression rate vs BMI, we can see that some ouliers may need to deal with and there is no siginifcant disrtibution on graph. More data processing is needed in future process.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariables <- c(\"Internalizing problem - Depression (SDS)\", \"Internalizing problem - Anxiety (SAS)\", \n               \"Obesity parameters - BMI\", \"Obesity parameters - WC\", \"Obesity parameters - WHR\",\n               \"Obesity parameters - WHtR\", \"Biochemical parameters - TG\", \"Biochemical parameters - FBG\",\n               \"Biochemical parameters - TC\", \"Biochemical parameters - HDL-C\", \"Biochemical parameters - LDL-C\",\n               \"Blood pressure - SBP\", \"Blood pressure - DBP\",\"Family location\", \"Number of siblings\", \"How much time do you spend with your father in elementary school?\", \n          \"How much time do you spend with your mother in elementary school?\", \"Father’s education level\", \n          \"Mother’s education level\", \"Family financial situation\", \"Sleeping hours\", \"Skipping breakfast\", \n          \"Vigorous\", \"Moderate\")\nabreviations <- c(\"Depression\", \"Anxiety\", \"BMI\", \"WC\", \"WHR\", \"WHtR\", \"TG\", \"FBG\", \"TC\", \"HDL-C\", \"LDL-C\", \"SBP\", \"DBP\",\"FL\", \"NS\", \"TFE\", \"TME\", \"FEL\", \"MEL\", \"FS\", \"SL\", \"SB\", \"VG\", \"MD\")\n\n\ncat(\"varible table\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nvarible table\n```\n:::\n\n```{.r .cell-code}\nvariable_table <- data.frame(variables, abreviations)\nvariable_table\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                           variables\n1                           Internalizing problem - Depression (SDS)\n2                              Internalizing problem - Anxiety (SAS)\n3                                           Obesity parameters - BMI\n4                                            Obesity parameters - WC\n5                                           Obesity parameters - WHR\n6                                          Obesity parameters - WHtR\n7                                        Biochemical parameters - TG\n8                                       Biochemical parameters - FBG\n9                                        Biochemical parameters - TC\n10                                    Biochemical parameters - HDL-C\n11                                    Biochemical parameters - LDL-C\n12                                              Blood pressure - SBP\n13                                              Blood pressure - DBP\n14                                                   Family location\n15                                                Number of siblings\n16 How much time do you spend with your father in elementary school?\n17 How much time do you spend with your mother in elementary school?\n18                                          Father’s education level\n19                                          Mother’s education level\n20                                        Family financial situation\n21                                                    Sleeping hours\n22                                                Skipping breakfast\n23                                                          Vigorous\n24                                                          Moderate\n   abreviations\n1    Depression\n2       Anxiety\n3           BMI\n4            WC\n5           WHR\n6          WHtR\n7            TG\n8           FBG\n9            TC\n10        HDL-C\n11        LDL-C\n12          SBP\n13          DBP\n14           FL\n15           NS\n16          TFE\n17          TME\n18          FEL\n19          MEL\n20           FS\n21           SL\n22           SB\n23           VG\n24           MD\n```\n:::\n:::\n\n### parameter explaination\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the data frame for SAS and SDS scales\nsas_levels <- c(\"Normal\", \"Mild to Moderate\", \"Marked to Severe\", \"Extreme\")\nsas_scores <- c(\"<45\", \"45-59\", \"60-74\", \">=75\")\nsas_table <- data.frame(Level = sas_levels, Score = sas_scores)\n\nsds_levels <- c(\"Normal\", \"Mild\", \"Moderate to Marked Major\", \"Severe or Extreme Major\")\nsds_scores <- c(\"<50\", \"50-59\", \"60-69\", \">=70\")\nsds_table <- data.frame(Level = sds_levels, Score = sds_scores)\n\n# Create the data frame for BMI categories\nbmi_levels <- c(\"Underweight\", \"Normal Weight\", \"Overweight\", \"Obesity\")\nbmi_values <- c(\"<18.5\", \"18.5-24.9\", \"25-29.9\", \">=30\")\nbmi_table <- data.frame(Category = bmi_levels, BMI = bmi_values)\n\n# Print the SAS scale table\ncat(\"Self-rating Anxiety Scale (SAS)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSelf-rating Anxiety Scale (SAS)\n```\n:::\n\n```{.r .cell-code}\nprint(sas_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Level Score\n1           Normal   <45\n2 Mild to Moderate 45-59\n3 Marked to Severe 60-74\n4          Extreme  >=75\n```\n:::\n\n```{.r .cell-code}\n# Print the SDS scale table\ncat(\"\\nSDS scores (SDS)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nSDS scores (SDS)\n```\n:::\n\n```{.r .cell-code}\nprint(sds_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                     Level Score\n1                   Normal   <50\n2                     Mild 50-59\n3 Moderate to Marked Major 60-69\n4  Severe or Extreme Major  >=70\n```\n:::\n\n```{.r .cell-code}\n# Print the BMI category table\ncat(\"\\nBMI Categories\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBMI Categories\n```\n:::\n\n```{.r .cell-code}\nprint(bmi_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       Category       BMI\n1   Underweight     <18.5\n2 Normal Weight 18.5-24.9\n3    Overweight   25-29.9\n4       Obesity      >=30\n```\n:::\n:::\n\n## hypothesis test\n\n### 1. Higher obesity rate increase the risk of depression\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(data)<-c(\"T0depression\",\"T0anxiety\",\"T1depression\",\"T1anxiety\",\"Height\",\"Weight\",\"WC\",\"HC\",\"SBP\",\"DBP\",\"FBG\",\"TC\",\"TG\",\"HDL-C\",\"LDL-C\",\"BMI\",\"WHR\",\"WtHR\",\"FL\", \"NS\", \"TFE\", \"TME\", \"FEL\", \"MEL\", \"FS\", \"SL\", \"SB\",\"Vigorous\",\"Moderate\")\n\nggplot(data, aes(x = T1depression, y = BMI)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 38 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 38 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncor.test(data$T1depression, data$BMI,method = c(\"spearman\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in cor.test.default(data$T1depression, data$BMI, method =\nc(\"spearman\")): Cannot compute exact p-value with ties\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tSpearman's rank correlation rho\n\ndata:  data$T1depression and data$BMI\nS = 384922674, p-value = 0.3229\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n-0.0273327 \n```\n:::\n\n```{.r .cell-code}\ncor.test(data$T1depression, data$BMI,method = c(\"pearson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  data$T1depression and data$BMI\nt = -1.2211, df = 1308, p-value = 0.2223\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.08774365  0.02045498\nsample estimates:\n        cor \n-0.03374321 \n```\n:::\n:::\n\nThe Pearson correlation test is a statistical test used to measure the linear relationship between two continuous variables.The Spearman's rank correlation coefficient (rho) measures the strength and direction of the association between two variables which don't have to be both continuous or have a linear relationship. It ranges between -1 and 1, where -1 indicates a perfect negative correlation, 1 indicates a perfect positive correlation, and 0 indicates no correlation.\nDue to the High p value of both test, the depression rate is less likely related to BMI. \n\n### 2. higher family income increase the rate of obesity\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = FS, y = BMI)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 36 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 36 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncor.test(data$FS, data$BMI,method = c(\"spearman\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in cor.test.default(data$FS, data$BMI, method = c(\"spearman\")): Cannot\ncompute exact p-value with ties\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tSpearman's rank correlation rho\n\ndata:  data$FS and data$BMI\nS = 390451141, p-value = 0.1766\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n        rho \n-0.03732942 \n```\n:::\n\n```{.r .cell-code}\ncor.test(data$FS, data$BMI,method = c(\"pearson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  data$FS and data$BMI\nt = -0.74116, df = 1310, p-value = 0.4587\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.07451001  0.03368374\nsample estimates:\n        cor \n-0.02047308 \n```\n:::\n:::\n\nNo significant corelationship on family financial status and obesity. \n\n### 3. More sibling reduce the risk of both depression and anxiety. \n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = NS, y = T1depression)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncor.test(data$T1depression,data$NS, method = c(\"spearman\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in cor.test.default(data$T1depression, data$NS, method = c(\"spearman\")):\nCannot compute exact p-value with ties\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tSpearman's rank correlation rho\n\ndata:  data$T1depression and data$NS\nS = 377319431, p-value = 0.008575\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n0.07162063 \n```\n:::\n\n```{.r .cell-code}\ncor.test(data$T1depression,data$NS, method = c(\"pearson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  data$T1depression and data$NS\nt = 2.6388, df = 1344, p-value = 0.008415\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.01843398 0.12474745\nsample estimates:\n       cor \n0.07179463 \n```\n:::\n\n```{.r .cell-code}\ndata$NS <- factor(data$NS)\nt.test(T1depression ~ NS, data = data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  T1depression by NS\nt = -2.6337, df = 1252.5, p-value = 0.008551\nalternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0\n95 percent confidence interval:\n -2.0381547 -0.2979518\nsample estimates:\nmean in group 1 mean in group 2 \n       38.38127        39.54932 \n```\n:::\n:::\n\n\n\nIn this case, the sample estimate of the correlation coefficient (rho) is 0.1184734, indicating a positive correlation between T0depression and NS. However, the p-value of the test is 0.008575, which is less than 0.05, suggesting that the correlation is statistically significant at a 5% level of significance.\n\nTherefore, we can conclude that there is a significant positive correlation between the number of siblings (NS) and the degree of depression  in this dataset.\n\nBy carrying out a Welch t-test, the group with more siblings have higher depression index and p value <0.05 indicates the result is siginifcant. (Not sure why the confident interval is negtive and none of the data was negative. )\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = NS, y = T1anxiety)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndata$NS <- as.numeric(data$NS)\ncor.test(data$T1anxiety,data$NS, method = c(\"spearman\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in cor.test.default(data$T1anxiety, data$NS, method = c(\"spearman\")):\nCannot compute exact p-value with ties\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tSpearman's rank correlation rho\n\ndata:  data$T1anxiety and data$NS\nS = 343033890, p-value = 8.796e-09\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.1559788 \n```\n:::\n:::\n\n### others\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create sample data\n\nplot(data$BMI~data$T1depression)\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(data$T1depression~data$FL)\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n```{.r .cell-code}\ndata$BMI_category <- cut(data$BMI, \n                       breaks = c(-Inf, 18.5, 24.9, 29.9, Inf),\n                       labels = c(\"Underweight\", \"Normal weight\", \"Overweight\", \"Obesity\"))\ndata$Depression_category <- cut(data$T1depression, \n                       breaks = c(0,45,\t59,74,75),\n                       labels = c(\"Normal\", \"Mild\", \"Moderate to Marked Major\", \"Severe or Extreme Major\"))\n# Plot the bar chart\n```\n:::\n\n \n\n\n## Answers to the feedbacks on check in 1\n\nHere are a few things you may want to work on in future steps:\n1. Please provide more information of the dataset: what each variable means (e.g. WC, HC, SBP etc) and how it is measured. This is to make sure audiences understand your confounders.\n  a table with explaination of abrivation is updated in data description\n\n2. Since gender is one of your key predictors, you may consider using the interaction between gender and other key variables in the model to see whether gender influences the impact of other predictors. Also, seem I didn't find the gender variable in the dataset you provided?\n  Thanks for pointing out. Since gender is missiong, I will not use gender as a key predicor. \n  \n3. As you mentioned, there are some outliers in the data, especially the one on the top-right corner. This outlier can change the slope of the regression. Also, the relationship between BMI and depression is not very clear in the graph, as you mentioned, more data processing is needed. You can also try plotting different groups (e.g. gender, family location) in different colors to see if there's any pattern.\n\nThanks for the comments, I will try to process the data this time  and plot more patterns. \n\n## Questions need to be addressed\n1. the varibles such as family locations or education level can be expressed either as rank or ordinal, as drawed below,it is hard to find a correlationship with this kind of varibles. How can i explore the relationship between an ordinal varible and a continuous varible?\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(data[c(\"T1depression\",\"T1anxiety\",\"BMI\",\"FL\", \"NS\", \"TFE\", \"TME\", \"FEL\")])\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\npairs(data[c(\"T1depression\",\"T1anxiety\", \"MEL\", \"FS\", \"SL\", \"SB\",\"Vigorous\",\"Moderate\")])\n```\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n:::\n\n2. as some of the continuous varibles can also converted to ordinal varibles, what would be some method or test good to find the relationship between them?\n\n::: {.cell}\n\n```{.r .cell-code}\n#convert continuous varibles into categorical varibles\ndata$FL1 <- factor(sample(1:5, 1348, replace = TRUE), levels = 1:5, \n                            labels = c(\"Rural\", \"Suburban\", \"Urban\", \"City\", \"Metropolis\"))\ndata$BMI_category <- cut(data$BMI, \n                       breaks = c(-Inf, 18.5, 24.9, 29.9, Inf),\n                       labels = c(\"Underweight\", \"Normal weight\", \"Overweight\", \"Obesity\"))\ndata$Depression_category <- cut(data$T1depression, \n                       breaks = c(0,45,\t59,74,75),\n                       labels = c(\"Normal\", \"Mild\", \"Moderate to Marked Major\", \"Severe or Extreme Major\"))\n#plot\nggplot(data, aes(x = FL1, y = BMI, fill = BMI_category)) + \n  geom_bar(stat = \"identity\", position = \"stack\") +\n  scale_fill_manual(values = c(\"#1b9e77\", \"#d95f02\", \"#7570b3\", \"#e7298a\")) +\n  xlab(\"Family location\") + ylab(\"BMI\") + \n  ggtitle(\"BMI category and family location\") +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 36 rows containing missing values (`position_stack()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data, aes(x = FL1, y = T1depression, fill = Depression_category)) + \n  geom_bar(stat = \"identity\", position = \"stack\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (`position_stack()`).\n```\n:::\n\n::: {.cell-output-display}\n![](XiaoyanHu_Finalproject2_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n:::",
    "supporting": [
      "XiaoyanHu_Finalproject2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}