{
  "hash": "92c4cb81c725feaf695886db3708037f",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Adithya Parupudi\"\ndescription: \"my homework 2\"\ndate: \"02/27/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - Adithya Parupudi\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.1     ✔ purrr   0.3.4\n✔ tibble  3.1.8     ✔ dplyr   1.0.9\n✔ tidyr   1.2.1     ✔ stringr 1.4.1\n✔ readr   2.1.3     ✔ forcats 0.5.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(hrbrthemes)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nNOTE: Either Arial Narrow or Roboto Condensed fonts are required to use these themes.\n      Please use hrbrthemes::import_roboto_condensed() to install Roboto Condensed and\n      if Arial Narrow is not on your system, please see https://bit.ly/arialnarrow\n```\n:::\n\n```{.r .cell-code}\nlibrary(viridis)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'viridis' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: viridisLite\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\n```\n:::\n\n\n\n# Question 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprocedure <- c(\"Bypass\", \"Angiography\")\ns_size <- c(539, 847)\nmean_wait_time <- c(19, 18)\ns_sd <- c(10, 9)\n\nsurgery <- data.frame(procedure, s_size, mean_wait_time, s_sd)\n\ncolnames(surgery) <- c(\"Surgical Procedure\", \"Sample Size\",\"Mean Wait Time\", \"Standard Deviation\")\nsurgery\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Surgical Procedure Sample Size Mean Wait Time Standard Deviation\n1             Bypass         539             19                 10\n2        Angiography         847             18                  9\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstandard_error <- s_sd / sqrt(s_size)\nstandard_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4307305 0.3092437\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconfidence_level <- 0.90\ntail_area <- (1-confidence_level)/2\ntail_area\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt_score <- qt(p = 1-tail_area, df = s_size-1)\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691 1.646657\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconfidence_interval <- c(mean_wait_time - t_score * standard_error,mean_wait_time + t_score * standard_error)\nconfidence_interval\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 17.49078 19.70971 18.50922\n```\n:::\n:::\n\n\nWe can be 90% confident that the population mean wait time for the bypass procedure is between 18.29029 and 19.70971 days. And for the angiography procedure, We can be 90% confident that the population mean wait time is between 17.49078 and 18.50922 days.\n\nFrom the above results, confidence interval of angiography procedure is narrower.\n\n\n# Question 2\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(567, 1031, conf.level = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  567 out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\n# Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nME <- 5\nz <- 1.96\ns_sd <- (200-30)/4\n\nsample_size <- ((z*s_sd)/ME)^2\nsample_size\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\n\nThe necessary sample size is 278.\n\n# Question 4\n\n## 4A\n\nWe assume that the sample is random and that the population has a normal distribution.\nNull hypothesis: H0: μ = 500\nAlternative hypothesis: Ha: μ ≠ 500\nWe will reject the null hypothesis at a p-value, p <= 0.05\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# defining variables\ns_mean <- 410\nμ <- 500\ns_sd <- 90\ns_size <- 9\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating test-statistic\nt_score <- (s_mean-μ)/(s_sd/sqrt(s_size))\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating p-value\n\np <- 2*pt(t_score, s_size-1)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nThe test-statistic is -3 and p-value is 0.01707168. As p-value is less than the 0.05, we reject the null hypothesis. Therefore, the mean income of female employees is not equal to $500.\n\n## 4B\n\nWe assume that the sample is random and that the population has a normal distribution.\nNull hypothesis: H0: μ = 500\nAlternative hypothesis: Ha: μ < 500\nWe will reject the null hypothesis at a p-value less than 0.05\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_val <- pt(t_score, s_size-1, lower.tail = TRUE)\np_val\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nThe p-value is 0.008535841. As p-value is less than the 0.05, we reject the null hypothesis. Therefore, the mean income of female employees is less than $500.\n\n## 4C\n\nWe assume that the sample is random and that the population has a normal distribution.\nNull hypothesis: H0: μ = 500\nAlternative hypothesis: Ha: μ > 500\nWe will reject the null hypothesis at a p-value less than 0.05\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_val_c <- pt(t_score, s_size-1, lower.tail = FALSE)\np_val_c\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nThe p-value is 0.9914642. As p-value is less than the 0.05, we reject the null hypothesis. Therefore, the mean income of female employees is greater than $500.\n\n\n# Question 5\n\n## 5A\n\nWe assume that the sample is random and that the population has a normal distribution.\nNull hypothesis: H0: μ = 500\nAlternative hypothesis: Ha: μ ≠ 500\nWe will reject the null hypothesis at a p-value less than 0.05\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating t-statistic and p-value for Jones\ns_mean <- 519.5\nμ <- 500\nse <- 10\ns_size <- 1000\n\njames_t <- (s_mean-μ)/se\njames_t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\np <- 2*pt(james_t, s_size-1, lower.tail = FALSE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating t-statistic and p-value for Smith\ns_mean <- 519.7\nμ <- 500\nse <- 10\ns_size <- 1000\n\nsmith_t <- (s_mean-μ)/se\nsmith_t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\np <- 2*pt(smith_t, s_size-1, lower.tail = FALSE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\nThe test-statistic is 1.95, p-value is 0.05145555 for Jones and the test-statistic is 1.97, p-value is 0.05145555 for Smith.\n\n## 5B\n\nThe p-value is 0.05145555 for Jones. As p-value is greater than the 0.05, we fail to reject the null hypothesis. The p-value is 0.04911426 for Jones. As p-value is less than the 0.05, we reject the null hypothesis. Therefore, the result is statistically significant for Smith, but not Jones.\n\n## 5C\n\nIf we fail to report the P-value and simply state whether the P-value is less than/equal to or greater than the defined significance level of the test, one cannot determine the strength of the conclusion. In the Jones/Smith example, reporting the results only as *P ≤ 0.05* versus *P > 0.05* will lead to different conclusions about very similar results.\n\n# Question 6\nTo test the claim that the proportion of students who choose a healthy snack differs by grade level, we will use the chi-squared test of independence. \nThe null hypothesis is that the proportion of students who choose a healthy snack is the same across all grade levels. \nThe alternative hypothesis is that the proportion of students who choose a healthy snack differs by grade level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data in a matrix\ntable_6 <- matrix(c(31, 43, 51, 69, 57, 49), nrow = 2, byrow = TRUE)\n\n# Row and column names\nrownames(table_6) <- c(\"Healthy snack\", \"Unhealthy snack\")\ncolnames(table_6) <- c(\"6th grade\", \"7th grade\", \"8th grade\")\n\n# Chi-squared test of independence\ntest <- chisq.test(table_6)\ntest\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  table_6\nX-squared = 8.3383, df = 2, p-value = 0.01547\n```\n:::\n:::\n\nThe p-value (0.01547) is less than the significance level (α = 0.05). Therefore, we reject the null hypothesis and conclude that the proportion of students who choose a healthy snack differs by grade level.)\n\n\n\n\n# Question 7\nTo test the claim that there is a difference in means for the three areas, we will use a one-way ANOVA test. \nThe null hypothesis is that the means for the three areas are the same. \nThe alternative hypothesis is that at least one area's mean is different from the others.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data in vectors\narea1 <- c(6.2, 9.3, 6.8, 6.1, 6.7, 7.5)\narea2 <- c(7.5, 8.2, 8.5, 8.2, 7.0, 9.3)\narea3 <- c(5.8, 6.4, 5.6, 7.1, 3.0, 3.5)\n\n# One-way ANOVA test\ntest <- aov(c(area1, area2, area3) ~ factor(c(rep(\"Area 1\", length(area1)), rep(\"Area 2\", length(area2)), rep(\"Area 3\", length(area3)))))\nsummary(test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                                                                    Df\nfactor(c(rep(\"Area 1\", length(area1)), rep(\"Area 2\", length(area2)), rep(\"Area 3\", length(area3))))  2\nResiduals                                                                                           15\n                                                                                                    Sum Sq\nfactor(c(rep(\"Area 1\", length(area1)), rep(\"Area 2\", length(area2)), rep(\"Area 3\", length(area3))))  25.66\nResiduals                                                                                            23.54\n                                                                                                    Mean Sq\nfactor(c(rep(\"Area 1\", length(area1)), rep(\"Area 2\", length(area2)), rep(\"Area 3\", length(area3))))  12.832\nResiduals                                                                                             1.569\n                                                                                                    F value\nfactor(c(rep(\"Area 1\", length(area1)), rep(\"Area 2\", length(area2)), rep(\"Area 3\", length(area3))))   8.176\nResiduals                                                                                                  \n                                                                                                     Pr(>F)\nfactor(c(rep(\"Area 1\", length(area1)), rep(\"Area 2\", length(area2)), rep(\"Area 3\", length(area3)))) 0.00397\nResiduals                                                                                                  \n                                                                                                      \nfactor(c(rep(\"Area 1\", length(area1)), rep(\"Area 2\", length(area2)), rep(\"Area 3\", length(area3)))) **\nResiduals                                                                                             \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\nThe p-value (0.00397) is less than the significance level (α = 0.05). Therefore, we reject the null hypothesis and conclude that there is a difference in means for the three areas.\n",
    "supporting": [
      "AdithyaParupudi_hw2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}